### ISSUE TITLE
Support rolling CoreOS updates

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#1043]
Locking Deis releases to specific CoreOS releases is both inconvenient and not the intended release path for CoreOS - instead, we should be subscribing to the beta channel and using the update-engine service with locksmith to ensure that only one node in a cluster is rebooted at any one time. This is The CoreOS Way(tm).

In order to achieve this in Deis, a few things need to be completed:

* Remove the oneshot unit which disables the CoreOS automatic updater service
* Add locksmith configuration to the user-data file (https://github.com/coreos/coreos-cloudinit/blob/master/Documentation/cloud-config.md#update)
* Bind the deis-database-data and builder-database-data services to the deis-database and deis-builder (respectively) machines, so that fleet will not try to move them when the database or builder machines are rebooted (#1038)

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776), and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this.
