### ISSUE TITLE
Add header to indicate the node that processed the request

### ISSUE THREAD

**Issue by aledbf** [deis/deis#1078]
Right now it's not possible to know which node processed the request (I think that is important to know the node in case of an error or to know how is the load is balanced).

Just add `add_header    X-Deis-Upstream $upstream_addr;` inside `location /` section in the deis-router nginx templates

**Comment by TrollWarlord** [comment]
I would like to point out the HUGE security flaw this also opens. This is revealing a lot more about your internal cluster than a client should ever know. If there is an error, look through physical logs.

**Comment by TrollWarlord** [comment]
https://www.owasp.org/index.php/Fingerprint_Web_Server_%28OTG-INFO-002%29

Allowing server fingerprinting is a HORRIBLE security flaw. STOP IT!
