### ISSUE TITLE
feat(router) Allow router page customization

### ISSUE THREAD

**Issue by aledbf** [deis/deis#1082]
Right now deis returns the default nginx error page.
Maybe this could be an alternative to provide a default (with a deis styled output) to indicate that an error occurred and also to return a message in a format that the client is expecting (if the accept header is application/json I don't expect html as result)

this is the last version that I'm running.

```
    # Map response error type watching header Content-Type
    map $http_content_type $customType {
        default                 html;
        ~application/json json;
    }

    server {
        listen 80 default_server;

        # Inside /app/errors create files with name 404.html and 404.json (and the rest)
        # the content of 404.json could be:
        # { "message" : "404 Not Found" }
        # By default the content of index returns the same content that 404.
        root /app/errors;

        error_page 403 404 502 503 504  /$status.$customType;

        # Remove etags
        etag                            off;
    }
```

I'm expecting #1754 so I can provide a PR that will allow to the end user to customize the look and feel of the pages uploading a zip file to the store.

Just as reference this is the full template https://github.com/aledbf/deis/blob/custom_router/router/templates/nginx.conf

**Comment by gvilarino** [comment]
+1000 to this feature

**Comment by paralin** [comment]
+1 Really need something intuitive here.

**Comment by ianblenke** [comment]
For content of the error pages, the first impulse is to point nginx at some static content under cephfs in /var/lib/deis/store, but that breaks any hope of S3 compatibility.

The second impulse is to store the static content under an S3 or RadosGW bucket, and have nginx serve up the content cached from there.

There still needs to be some method of allowing custom nginx configurations beyond the served content, however.

@bacongobbler mentioned [progrium/nginx-appliance](https://github.com/progrium/nginx-appliance) which offers a neat API for changing the nginx config on the fly. The down-side to that is the need for an external convergence mechanism (by another container that re-configures deis-router to a desired configuration), and the window of opportunity of a new deis-router to service requests before it has been converged.

Having to manage our own custom deis-router images for things like HTTPS enforcement and ELB proxyProtocol support before they were embraced by Deis upstream, I can suggest that /app/templates/nginx.conf is really the key thing that we needed to change.

For folks interested in changing the content of the error pages, it seems like /opt/nginx/html is the thing they would want to modify. Optionally, the configuration could be changed in the nginx.conf template to share that static content from wherever they would like.

It is technically possible to avoid modifying the deis-router docker images, and instead modify the deis-router fleet units to allow a --volumes-from another container that has "VOLUME /app/templates" and/or "VOLUME /opt/nginx/html" with a copy of that tree from the version of deis-router in use with desired configuration changes. The down-side to this is that those changes are very likely to be version dependent, and will most likely break newer desired behaviors if deis is upgraded.

The big challenge here is embracing a sane default nginx config for the deis-router image that services most of the Deis project users while allowing configuration customizations that avoids breaking existing deployments that depend on that current default behavior.

**Comment by carmstrong** [comment]
> The big challenge here is embracing a sane default nginx config for the deis-router image that services most of the Deis project users while allowing configuration customizations that avoids breaking existing deployments that depend on that current default behavior.

Exactly. :+1: We're certainly open to proposals, but that's the primary concern.

**Comment by bacongobbler** [comment]
short of forking the registry and injecting your own custom router pages, I'm not sure how we can properly scope this in as everyone will want their own pages. Maybe we should close this as a wontfix and point users to customize the router pages as they choose?

**Comment by carmstrong** [comment]
> short of forking the registry and injecting your own custom router pages, I'm not sure how we can properly scope this in as everyone will want their own pages in different places, different pages for different domains etc.

I think there's some common ground we can achieve here - at the very least, with error pages that describe the error that occurred (Such as 503 instead of "Welcome to nginx!").

**Comment by azurewraith** [comment]
I'm a fan of @ianblenke's suggestion of pointing to S3 or RadosGW bucket.  Then you'd point a router config variable to that bucket.  At a global (all apps) level, this would be pretty simple if you used convention over configuration style principles or maybe provided an example template/script that you could use to upload to said bucket.

As for different pages for different domains, that'd be nice, but I'd sacrifice it for a path that didn't involve me rebasing/rebuilding the deis router all of the time.

**Comment by gvilarino** [comment]
Off the top of my head: what if deis would provide a very basic and bare admin UI (maybe under `deis.yourdomain.tld`) that allows you to set `URL`s for error codes? And also provide a default very simple page to handle errors beyond the ngnix horrible default?

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776), and the router has radically changed in v2 so I'm going to go ahead and close this. I'd imagine if you want to customize the router in v2, you'll still need to fork the router image and inject your custom pages in.
