### ISSUE TITLE
feat(ci): add vagrant box build to ci.deis.io

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#1153]
We should have a way to package a CoreOS VM with deis already packaged and ready-to-go in a QCOW image. I attempted to do this with http://ci.deis.io/job/deis-nightly/, but had no luck. Tracking this issue for posterity.

**Comment by wasbazi** [comment]
This seems like a good candidate for using something like [packer] (https://packer.io/docs/templates/introduction.html) for making an ISO (or another image type depending on how you are wanting to run it - VirtualBox or VMWare) to run off of that already has deis packaged into it. 

Assuming that works you could then build off of that to make deploying to AWS and DigitalOcean easier (as well as other features I'm not aware of like config management plugins).

I'll see if I can't get something working with Packer.

**Comment by technosophos** [comment]
Packer is a great idea for something like this!

**Comment by wasbazi** [comment]
It seems like creating the box and preseeding the docker file onto it is the easy part. The hard part is actually getting the vagrant machines to be part of a cluster since the etcd discovery url needs to be set after the cloud config is already on the machines. 

I'll keep on going with it but if anyone has ideas that'd be helpful.

**Comment by technosophos** [comment]
How is the etcd url set in the current Vagrant setup?

**Comment by bacongobbler** [comment]
@technosophos it's set up through the coreos-cloudinit. `make discovery-url` pulls a new discovery url from discovery.etcd.io/new and throws it into contrib/coreos/user-data, which the provisioning scripts use to provision the cluster.

**Comment by wasbazi** [comment]
Running the `coreos-cloudinit` with the new `cloud-config` file updates the etcd settings but it doesn't appear that those changes persist the machine rebooting. It seems like only doing `coreos-install` with a new `cloud-config` file is the only way I've seen to get it to persist but that would defeat the purpose if you had to run the install on vagrant boot. I also think I need to restart etcd for those changes to take effect but my limited knowledge of CoreOS is getting in the way.

**Comment by bacongobbler** [comment]
closing as something we won't get to for the Deis v1 LTS release, and in v2 provisioning is handled by kubernetes.
