### ISSUE TITLE
Support for interactive `deis run bash` session

### ISSUE THREAD

**Issue by gabrtv** [deis/deis#117]
While #70 provided us with the ability to run one-off admin commands, we really need an interactive shell into the ephemeral docker containers.  

This is quite tricky, as it requires a full duplex channel (HTTP Chunked Encoding? WebSockets?) as well as a select loop on the API server to handle routing stdin, stdout and stderr.

https://github.com/paramiko/paramiko/blob/master/demos/interactive.py#L39 provides a good example of a terminal-enabled select loop.

**Comment by bacongobbler** [comment]
for the meantime, this has been the workaround for most users: https://github.com/deis/deis/issues/3449#issuecomment-91845128

**Comment by jwaldrip** [comment]
@bacongobbler I will say that the workaround I have been doing is to just use `docker exec` to get into the running container. Seems to work fine for me (as much as it pains me to do it)

**Comment by fbjork** [comment]
Any update on this? This is as pretty big limitation of Deis compared to Heroku.

**Comment by gabrtv** [comment]
@fbjork I would have liked to ship this earlier, but as we've discussed in the open planning meetings, this feature is on hold pending Deis v2.  Reason being the plumbing we need for this already exists in `kubectl exec`, versus having to write and maintain a bi-directional channel from scratch -- only to throw it away for v2.

We expect to have an RC for Deis v2 available by the end of the year.

**Comment by hajimenomomo** [comment]
Hi everyone,
I wrote a python script for my personal use that opens a rails console directly from your deis app folder, using TLS to authenticate to the docker remote API on your cluster nodes, to use it, you have to enable Docker remote API with TLS, see: https://coreos.com/os/docs/latest/customizing-docker.html 
I personally put it in my PATH directory (/usr/local/bin).
You may find it in my repo: https://github.com/hajimenomomo/deis_rails_console.git
I hope this helps.

**Comment by kaedroho** [comment]
Django are planning on adding a new "channels" feature into the core for 1.10 (http://channels.readthedocs.org/en/latest/integration-plan.html). This should make it possible to serve Websockets from the controller.

**Comment by rstacruz** [comment]
The workaround is to SSH into one of your CoreOS nodes:

```sh
# try the one in DEISCTL_TUNNEL
ssh core@1.2.3.4
```

then check out the docker containers running:

```sh
docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                                                                                      NAMES
bc11d8da5e52        1.2.3.4:5000/staging:v10              "/runner/init start w"   2 minutes ago       Up 2 minutes        0.0.0.0:32869->5000/tcp                                                                    staging_v10.web.1
```

Then use that container ID for docker exec:

```sh
docker exec -i -t bc11d8da5e52 bash
```

**Comment by nathansamson** [comment]
If you have a more recent deis (v1.11+ for sure) version you can just do

`deisctl dock your_app /runner/init yourcmd"`

you can even pick a specific container with 
`deisctl dock your_app_v10.web.1 /runner/init yourcmd"`

I am not sure if this is intended to work (it originally was supposed to be for deis components itself) but I find it very useful for application containers as well

**Comment by rstacruz** [comment]
Can confirm... that works brilliantly.

**Comment by krancour** [comment]
The one potential problem with that workaround, however, is that `deisctl` is an admin tool whilst `deis` is in many cases a developer tool.  In an org with many developers and good separation of roles, the sysadmins / devops guys or gals likely would not have widely distributed the key that woyld allow a developer to use `deisctl`.

**Comment by rstacruz** [comment]
> however, is that deisctl is an admin tool whilst deis is in many cases a developer tool

sadly so! hope a proper implementation of interactive `deis run` would land soon exactly because of this.

**Comment by nathansamson** [comment]
@krancour While thats certainly true, ssh-ing into the server has the exact same problem (only the admins should be able to do so).

So while we all are eagerly waiting for deis run to work interactively natively, deisctl is a very handy trick to work with...

**Comment by bacongobbler** [comment]
FYI this won't be immmediately implemented in Deis v2 as we are targeting for v1 compatibility while rebasing on top of kubernetes, so the workaround in v2.0.0 will be to run `kubectl exec --namespace=myapp -it <pod name> bash`. This will achieve the same behavior as running `docker exec -it <my container> bash` in v1.

**Comment by sheerun** [comment]
My ugly workaround:


> export NAMESPACE=xxx PROCESS=web && kubectl exec -it --namespace $NAMESPACE "$(kubectl get pods --namespace $NAMESPACE -o name | grep $NAMESPACE-$PROCESS | cut -d '/' -f 2)" -- bash -c '. /app/.profile.d/ruby.sh && PATH=/app/.heroku/node/bin:$PATH /app/bin/rails c'

It's a shame deis doesn't support interactive output..

**Comment by bacongobbler** [comment]
@sheerun you can simplify that bash incantation with `-- /runner/init rails c` if you're using Heroku buildpacks.

**Comment by bacongobbler** [comment]
also see https://github.com/deis/controller/pull/1162.

**Comment by sheerun** [comment]
@bacongobbler thanks! here's my new `deis-ssh` command:

```
deis-run() { export NAMESPACE="$1" && PROCESS="$2" && shift && shift && kubectl exec -it --namespace $NAMESPACE "$(kubectl get pods --namespace $NAMESPACE -o name | grep $NAMESPACE-$PROCESS | cut -d '/' -f 2)" -- /runner/init "$@"; }
```

Usage:

```bash
# deis-run <application> <process> <command>
deis-run my-app web rails c
```

**Comment by deis-admin** [comment]
This issue was moved to deis/controller#1215
