### ISSUE TITLE
feat(client): add `deis logs -n`

### ISSUE THREAD

**Issue by developerinlondon** [deis/deis#1264]
how can I get more logs using `deis logs --app=<appname>`

i can see in the API there is settings.`settings.LOG_LINES`... can it be passed as a parameter somehow so we can get as much log as we want?

mainly wanted to give developers access to deis without having to give them ssh access.

**Comment by LoicMahieu** [comment]
Like said by @krancour , follow option to `deis logs` would be awesome. Today I ssh into host and `jounalctl -fu`, no better way ?

**Comment by bacongobbler** [comment]
not at the moment. This is due to the limitations of WSGI, which cannot handle asynchronous requests out of the box.
