### ISSUE TITLE
How to code, debug application with deis?

### ISSUE THREAD

**Issue by ntquyen** [deis/deis#1298]
One of our goals is to ensure the environment consistency among development, staging, production or whatever the application is deployed to.

I'm concerned about the local development environment, if I deploy my app to local machine using `git push deis master`, it would be very slow, and hard to debug.

I can still code and debug my app inside a docker container, thanks to this reference [Docker from development to release](http://brainsiqdeveloper.wordpress.com/2013/11/21/docker-from-development-to-release/). But with Deis, I don't know how.

Thanks for suggesting me a way to develop application with Deis!

**Comment by huyz** [comment]
> I think using our own Dockerfile (or cedarish) that we use for both dev and production is the solution I was looking for (and also perhaps @ntquyen?). With that, we can use docker's -v flag to mount the codebase from our dev machines into locally running containers and get the best of both worlds.

Or maybe use https://github.com/EugenMayer/docker-sync
