### ISSUE TITLE
Discuss: Create deis etcd folders as first action

### ISSUE THREAD

**Issue by johanneswuerbach** [deis/deis#1300]
Today every deis unit has an etcd folder, which is created in its app/boot script (e.g. https://github.com/deis/deis/blob/master/cache/bin/boot#L29) The problem is, that confd doesn't allow to subscribe to a none existing folder and error-prone workarounds are required to ensure that the folder exists (https://github.com/johanneswuerbach/deis/commit/99a2c1438ff9a6225b6aa57d6a1e4af3331f30c1), even when the actual values are optional (e.g. the registry can use deis cache, but doesn't requires it).

I think it would be easier to create all `deis/component` folders before starting deis units to allow confd subscription and simplify the startup process.

**Comment by bacongobbler** [comment]
I believe we already do this with the components in their publish loop. This is no longer an issue, correct?

**Comment by carmstrong** [comment]
> I believe we already do this with the components in their publish loop. This is no longer an issue, correct?

I think the proposal was to move etcd keyspace creation entirely out of the bin/boot scripts, which we haven't done. @johanneswuerbach can comment as to the current relevancy of the proposal.

**Comment by johanneswuerbach** [comment]
I think this is solved. Thanks guys.
