### ISSUE TITLE
TCP support for Deis applications

### ISSUE THREAD

**Issue by Xe** [deis/deis#1315]
This issue obsoletes #1061 and #18.

Also see #535.

Can an admin close #1061 and #18 and inform conversations to be directed here?

**Comment by nekinie** [comment]
Is there any news on tcp support in the router?

**Comment by bacongobbler** [comment]
We need to spec it out, make a proposal and hash out the details on this feature request. We need to figure out the UX as well as how we can properly implement this before moving onto development so we're all on the same page.

**Comment by gust1n** [comment]
Maybe it's a stupid question but doesn't nginx handle TCP? http://nginx.com/resources/admin-guide/tcp-load-balancing/

**Comment by aledbf** [comment]
@gust1n that is the commercial version of nginx.

**Comment by Xe** [comment]
Another big problem is that a lot of applications that use IP addresses to figure out who is connecting and if they are banned or not use the remote TCP address to figure this out. With any sort of TCP proxy this is broken.

**Comment by bacongobbler** [comment]
TCP support for applications will most likely be written up as an addon through #231, so it won't break our current application/proxy stack. How it will be architected is a separate question which we'd probably need to take a look at #231 first, but I'd imagine that it'd be a separate proxy layer outside of the core component stack.

**Comment by chendo** [comment]
+1 for this feature.

There's a TCP module for nginx (https://github.com/yaoweibin/nginx_tcp_proxy_module) but I haven't used it yet, but we're planning to investigate it as a replacement for haproxy in our Marathon/Mesos cluster.

**Comment by carmstrong** [comment]
> There's a TCP module for nginx

We're actually already using this - https://github.com/deis/deis/blob/ce484e5524b8570e511c041b327bdc38a70ff76a/router/build.sh#L66

**Comment by chendo** [comment]
Oh whoops, never mind me then.

Is the strategy to update the config, then reload nginx? I was planning on using nginx-mruby to have to dynamically provide routing.

**Comment by carmstrong** [comment]
> Is the strategy to update the config, then reload nginx?

Yep, that's how it happens currently - confd will re-template the nginx configuration, and then sighup the process to reload.

**Comment by chendo** [comment]
How often does this happen? We have issues where our script currently reloads every 15s, but our deploys can happen faster than that so we end up with stale backends which cause 503s

**Comment by carmstrong** [comment]
> How often does this happen?

confd re-templates every 5 seconds: https://github.com/deis/deis/blob/ce484e5524b8570e511c041b327bdc38a70ff76a/router/image/confd.toml#L3

**Comment by deis-admin** [comment]
This issue was moved to deis/router#305
