### ISSUE TITLE
docs(installing_deis): add HAProxy docs for load balancing

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#1362]
See discussion in https://github.com/deis/deis/pull/1352

**Comment by deis-admin** [comment]
Deis v1 LTS support ends February 13, 2017, and [v1.13.4](https://github.com/deis/deis/releases/tag/v1.13.4) is intended to be the last official release, so I'm closing this.

Please see [Deis Workflow](https://github.com/deis/workflow), the documentation / hub repository for the next-generation PaaS.
