### ISSUE TITLE
discussion(contrib): add cloud-agnostic provisioner script

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#1406]
To make it easier to add additional cloud providers, we could rewrite our provision scripts into one script. This could be written using [libcloud](https://libcloud.apache.org/) and would enable us to only concentrate on Deis logic.

Some additional benefits:
- Prevent us from repeating logic
- Remove requirement for users to install a different CLI and scripting language for each contrib/ platform
- Reduce time to implement a new cloud provider
- Have load balancer support for all providers, not just EC2(!?)

This was suggested by @ianblenke

**Comment by ianblenke** [comment]
Ran into this same problem when trying to model the options in the EC2 CloudFormation in TerraForm, it was missing a couple of things that we needed (public IPs, and something else), and was unstable while iterating somehow managing to repeatedly corrupt its local database that it creates of the resources.

Writing something in Fog is just painful. Boto isn't much better. As you've mentioned, these libcloud options tend not to cover the full range of cloud resources and options available for provisioning.

The best we can hope for at the moment is parallel documented/supported methods to install to these different cloud providers.

**Comment by carmstrong** [comment]
@ianblenke Have you given TerraForm another shot as of late? Wondering if it's better supportive of the cloud providers.

**Comment by ianblenke** [comment]
TerraForm has improved slightly, but was still missing a few attributes on resources, as well as a couple of resources that we model our CloudFormations. Any third-party cloud convergence tool is going to be playing catch-up with the cloud providers as they add new offerings over time.

**Comment by mboersma** [comment]
> TerraForm has improved slightly, but...

ping @econnell, who has worked on a TerraForm version of Deis EC2 provisioning.

**Comment by carmstrong** [comment]
Reopening, as @sgoings wanted to take a look at this.

**Comment by krancour** [comment]
If we can eliminate some of the existing complexity by adopting a common provider-agnostic abstraction for cloud provisioning, something I think we should consider shortly thereafter would be some variations on the existing recipe.

One in particular that I have in mind would establish a more secure virtual network topology by placing all Deis nodes in private subnets with _only_ the load balancers in public subnets.  This is something that larger customers with specific audit and compliance requirements are likely to want.

This is merely one example.  If we simplify provisioning enough to ensure it does not become a support burden, what would we all think about maintaining a modest catalog of recipes that account for common deployment scenarios instead of assuming one-size-fits-all?

**Comment by mackwic** [comment]
Also, providing provisioning scripts for the different coreos [documented topologies](https://coreos.com/os/docs/latest/cluster-architectures.html) would be very nice.
Being able to specify the number of nodes in the central/worker topology and just `terraform apply` it would be particularly great... Maybe for the 1.0

**Comment by krancour** [comment]
+1

**Comment by rimusz** [comment]
+1 @mackwic suggestion, as we need less complex deis provisioning scripts, terraform does a good job there, but it does not support all major providers/bare-metal yet

**Comment by sstarcher** [comment]
I would be interested in working on a terraform provisioning script at least the AWS portion.
@econnell  and @ianblenke I would be interested in seeing any terraform scripts you may currently have for deis.

**Comment by rimusz** [comment]
@gabrtv @carmstrong I can help on GCE part terraform provisioning scripts

**Comment by bacongobbler** [comment]
@sstarcher see #4247. @econnell has been working on that, but any input would be appreciated!

**Comment by carmstrong** [comment]
Closing in favor of individual provider-specific issues. Also see #4345
