### ISSUE TITLE
Add intelligent HA app support to the scheduler

### ISSUE THREAD

**Issue by krancour** [deis/deis#1480]
Currently Deis exposes no ability to control _where_ containers will be scheduled.  This is often important.  See #1376, which has to do with pinning/pegging a container to a particular host or hosts based on certain arbitrary tags.  (e.g. Run me where there's an SSD.)  This issue is, in essence, a fork of that issue.

Currently, it's possible (and ideal) to run Deis on a CoreOS cluster that spans multiple racks / availability zones / regions / data centers / what have you.  This maximizes the availability of the _cluster itself_, yet there is no way currently to fully take advantage of that and maximize the availability of an _application_ by ensuring its containers are hosted on CoreOS machines in, wherever possible, multiple racks / availability zones / regions / data centers / what have you.

This is a feature request for additional intelligence in scheduling such that this would be possible.

**Comment by bacongobbler** [comment]
@intellix bumping an old thread, but couldn't that be done already with the current setup?

i.e. set metadata for fleet hosts, then `deis tags:set datacentre=igaming`

**Comment by bacongobbler** [comment]
> The bottomline for me is that I split up my cluster in different regions/datacenters (as many levels as I want), and I can restrict my app to one or more regions/datacenters/other levels. Within such a region the distribution of containres would be as fair as possible (not necessarily even, because one datacenter can contain more / bigger machines than another).

That's all possible with `tags:set`, no? Considering if you have your cluster running in us-west-1, us-west-2 and us-east-1, you should be able to set up fleet to set the us-west-* regions with the tag `region=us-west`, then `deis tags:set region=us-west` would distribute the apps across both regions, but not us-east-1.

> I should also be able to specify weights (were restricting to one region would actaully be weight=1 for this region, and weight=0 for all others).

That's an interesting thought. Would you mind opening a proposal with documentation on how that would work/how a user would use that feature?

**Comment by krancour** [comment]
Housekeeping...

I opened this ages ago when I was first getting involved with Deis.  At the time, what I had wanted was to get some assurance that _n_ application containers would be spread across racks or availability zones to ensure availability in the event of a zone-wide failure, for instance.

What I see more clearly a year later is that this doesn't matter so much.

1. This can't be done with Fleet anyway.
2. It's the scheduler's responsibility to reschedule containers if hosts fail.  Kubernetes replication controllers, for instance, are very good at this.
3. The most this would have accomplished is avoiding some small amount of downtime while Docker pulls complete on a machine to which a container has been re-assigned (if it didn't already have the image in question).
4. The possibility of downtime due to no. 3 is mitigated if you're running at any sort of scale.

At the end of the day, it's the _cluster's_ health and ability to host _n_ instances of you app that matter; _not_ which nodes of the cluster are doing it or how evenly the _n_ are spread over nodes in different racks or AZs.

I see no reason not to close this.
