### ISSUE TITLE
Tutorial still unavailable

### ISSUE THREAD

**Issue by tiagoboldt** [deis/deis#1481]
#13 proposed a tutorial for deis and was closed. Today there's still no clear documentation on how to start using deis after having a controller deployed. I believe it should be once again evaluated.

**Comment by bacongobbler** [comment]
This is something which we don't plan on getting to in the near future. We have "[quick start](http://docs.deis.io/en/latest/installing_deis/quick-start/)" documentation on getting set up with Deis, then docuementation on [using buildpacks](http://docs.deis.io/en/latest/using_deis/using-buildpacks/) and [dockerfiles](http://docs.deis.io/en/latest/using_deis/using-dockerfiles/) which should cover the tutorial. We also have screencasts available to see the deployment process at http://deis.io/overview/. Thanks!
