### ISSUE TITLE
ref(docs): client autodocs HTML generation needs refactoring

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#1528]
We really need to refactor how Sphinx generates HTML for the autodocs. They are butt-ugly at the moment, and very inconsistent. I think this is just the nature of how Sphinx generates the autodocs, but we should really take this matter in our own hands (Maybe a switch to mkdocs like #976 suggests would make things easier?)

**Comment by bacongobbler** [comment]
Right you are. This could very well be a CSS issue that could be fixed up by fixing up our theme layout.

**Comment by Joshua-Anderson** [comment]
@bacongobbler By `autodocs` are you referring to the auto-generated python libraries documentation or the docs in general?

**Comment by bacongobbler** [comment]
yes, I'm referring to http://docs.deis.io/en/latest/reference/client/ and http://docs.deis.io/en/latest/reference/server

**Comment by mboersma** [comment]
The auto-generated client documentation became a non-issue with #4341, but the server docs could still use attention.

**Comment by mboersma** [comment]
I'm closing this because it isn't likely to receive attention now that focus has shifted to Deis v2 and [its documentation](https://github.com/deis/workflow). Although PRs are of course welcome!
