### ISSUE TITLE
External authentication

### ISSUE THREAD

**Issue by aledbf** [deis/deis#1578]
Right now I need to create at least one account to interact with the controller and deis-cli commands  (this means a new user/pass). Please provide some external authentication method to avoid this duplication.

**Comment by phspagiari** [comment]
Guys, about this issue... There is already a way to due this? I work at a company with a thousand of ops/devs and without a external auth to link with a LDAP/AD or even some call through API that return the token will be very difficult to manage their accounts.

I saw that if I start a python shell with the manage.py of deis-controller I can use de django / rest_framework models to do something like this, but still hard to use in a distributed mode.

**Comment by bacongobbler** [comment]
If you can come up with a proposal, we're welcome to implementations! Our authentication views are tied into the [api views](https://github.com/deis/deis/blob/master/controller/api/views.py#L21-L46) in the controller as well as [DRF's authtoken views](https://github.com/deis/deis/blob/master/controller/api/urls.py#L78-L79), so it would probably have to be cut out into a separate module like `api.auth`, defaulting to our token auth but allowing users to override with a separate django conf setting.

**Comment by phspagiari** [comment]
Perfect @bacongobbler, I just asked because if you guys is already doing something its better to know first of all.
So, I will start with some tests and I will come up with new doubts and  a possible future PR. :)

**Comment by sstarcher** [comment]
Support for some oauth platform would be excellent.

**Comment by bacongobbler** [comment]
Wondering if we should close this more generic issue in favour of smaller, tightly scoped issues like "add OAuth support" now that we have LDAP support. ping @carmstrong

**Comment by carmstrong** [comment]
> Wondering if we should close this more generic issue in favour of smaller, tightly scoped issues like "add OAuth support" now that we have LDAP support.

:+1:

**Comment by bacongobbler** [comment]
@sstarcher would you mind opening a proposal for how OAuth support would work? There's many  different implementations out there, so some feedback on how we can nail down the UX/how users would integrate with them (like Github's OAuth) would be awesome. Thanks! :)
