### ISSUE TITLE
AWS doesn't support subnets in us-east-1a

### ISSUE THREAD

**Issue by clayzermk1** [deis/deis#1601]
CloudFormation doesn't support subnets in us-east-1a. The defaults tried to make one there.

I cloned master@1aa32511 and followed the instructions in `contrib/ec2/README.md`. (I ran into the EC2-Classic/ELB/SG issue in 0.10.0 so I decided to try master.)

cloudformation.json
```
[
    {
        "ParameterKey":     "InstanceType",
        "ParameterValue":   "t1.micro"
    },
    {
        "ParameterKey":     "KeyPair",
        "ParameterValue":   "deis"
    }
]
```

CloudFormation log:

> Value (us-east-1a) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-east-1b, us-east-1c, us-east-1d.

![screen shot 2014-08-14 at 5 56 21 pm](https://cloud.githubusercontent.com/assets/1075015/3929060/b7bda794-2417-11e4-86bb-e3b7dda42c4e.png)

deis looks amazing, I'm really looking forward to getting it going. I'm going to look around for a way to specify the availability zone. Thanks for all your hard work everyone! Cheers :beers:

**Comment by carmstrong** [comment]
Closing, as there's nothing actionable. Folks who run into this can find the issue.
