### ISSUE TITLE
wildcard subdomain needs to be supported to host some heroku apps

### ISSUE THREAD

**Issue by dreamcodez** [deis/deis#1608]
Hi, there was one other issue which I saw related to this:

https://github.com/deis/deis/pull/563

I was wondering if this was still on the table, and if so when? I have a couple apps that I can't host on deis because of this currently.

Otherwise what is the workaround? Hack nginx config directly?

NOTE: If you can point me to work in progress branch, I can probably finish the work. Just sayin'

Thanks.

The error received after typing "deis domains:add '*.mydomain.com'" is :
{u'domain': [u'Adding a wildcard subdomain is currently not supported']}

**Comment by jwaldrip** [comment]
+1 we need this as well!

**Comment by christofferh** [comment]
+1

**Comment by jnettome** [comment]
Any updates on that? +1

**Comment by brunoalano** [comment]
+1

**Comment by rukor** [comment]
Any idea if this is in the pipeline?

**Comment by carmstrong** [comment]
> Any idea if this is in the pipeline?

This change won't make it into Deis v1, but @helgi is working on it for Deis v2 (see https://github.com/deis/workflow/pull/338). The opportunity to make breaking changes gave us the ability to reimplement our models to better represent things like this.

**Comment by rukor** [comment]
Thanks

**Comment by helgi** [comment]
Looks like #4762 will get into the LTS and the improvements be forced ported to v2 on top of all of my changes. It may be slightly different in v2 due to model changes @carmstrong mentioned but it should be mostly the same.

Hope it helps.

**Comment by helgi** [comment]
Forward ported to v2*

**Comment by bacongobbler** [comment]
this has been implemented in v2, [which is now generally available](https://deis.com/blog/2016/workflow-stable/). Closing!
