### ISSUE TITLE
Disk space delimma

### ISSUE THREAD

**Issue by ianblenke** [deis/deis#1678]
We are presently at 77% disk space used on one of our nodes, and 55% on the others.

As deis-builder is on the first one, it has started dying with "no space left on device" during deploys. 

At the time of these space errors, this is what df looked like from within deis-builder:

$ nse deis-builder
groups: cannot find name for group ID 11
root@42f041aba839:/# df -k
df: `/etc/resolv.conf (deleted)': No such file or directory
Filesystem     1K-blocks     Used Available Use% Mounted on
rootfs         102366188 77256868  23987612  77% /
/dev/xvda9     102366188 77256868  23987612  77% /
tmpfs            7704148        0   7704148   0% /dev
shm                65536        0     65536   0% /dev/shm
/dev/xvda9     102366188 77256868  23987612  77% /.dockerinit
/dev/xvda9     102366188 77256868  23987612  77% /etc/hostname
/dev/xvda9     102366188 77256868  23987612  77% /etc/hosts
/dev/xvda9     102366188 77256868  23987612  77% /var/lib/docker
cgroup           7704148        0   7704148   0% /sys/fs/cgroup
/dev/xvda9     102366188 77256868  23987612  77% /var/lib/docker/btrfs

**Comment by carmstrong** [comment]
> Will have to investigate more on that front.

@bacongobbler did we clean this up at some point?

**Comment by bacongobbler** [comment]
Unfortunately not. At the moment, there's no way to determine which parent images to clean up other than the app image itself. :(

**Comment by carmstrong** [comment]
@ianblenke I used some of your tips in #3021

**Comment by ianblenke** [comment]
There is another benefit of having cephfs occasionally kill instances: we're only running at 6% of our 1TB volumes on our 5 deis nodes. It helps when you keep building new instances and the old images eventually disappear organically on their own.

**Comment by wenzowski** [comment]
Failing proper LRU tracking for cached containers, I really the idea of introducing a little chaos @ianblenke.

If cached parent containers were to be randomly selected for deletion @bacongobbler, they would probably be available to the builder (good for build speed as noted elsewhere) but may have been randomly deleted (minor penalty since they would transparently be pulled back in).

So the longer the interval since last use of a parent container, the more likely that parent container will have been randomly purged. Entropy :tada:

**Comment by carmstrong** [comment]
@ianblenke @wenzowski What do you guys think about closing this? A good discussion around disk usage, but not sure if there's anything actionable out of it. If there is, we should probably file a separate issue to track.

**Comment by ianblenke** [comment]
I've been using 1TB root volumes now to ensure I never run into btrfs issues again. Beyond CoreOS 561, it defaults to ext4 + OverlayFS anyway, so I'm not sure the same btrfs issues will continue to apply. I'm ok with closing this if you are.

**Comment by aledbf** [comment]
> it defaults to ext4 + OverlayFS anyway

overlay is selected only if the module `overlay` is loaded (and by default is not)

**Comment by ianblenke** [comment]
Good to know. When stable makes it to 561+, we should definitely try and make sure the overlay module is loaded on boot before docker starts.

**Comment by wenzowski** [comment]
Making sure overlay is loaded on boot seems actionable. New issue? Otherwise ok to close for me.

**Comment by carmstrong** [comment]
> Making sure overlay is loaded on boot seems actionable. New issue?

Sounds good to me.
