### ISSUE TITLE
Concurrency issues on simultaneous application actions

### ISSUE THREAD

**Issue by bfosberry** [deis/deis#1724]
If you create an app with a large container, and while it is being pulled you change a config variable, deis will create a new release and deploy it, but not clean up the old container

**Comment by bacongobbler** [comment]
this is fairly generic, meaning that this issue can never be potentially closed. If there are specific race conditions that need to be fixed up, let's open another issue so we can investigate. The first obvious places to check would be with concurrent `git push` operations, setting config etc. :)
