### ISSUE TITLE
bin/compile in buildpacks are not being passed $3 (ENV_DIR)

### ISSUE THREAD

**Issue by ianblenke** [deis/deis#1738]
While working through some layering issues with http://github.com/ianblenke/rbenv-buildpack, it seemed a bit out of place that deis does not appear to pass the environment directory argument to the compile script for a buildpack.

With this in my bin/compile script:
```
BUILD_DIR=$1 # The app directory, usually /app. This will have the app source initially. Whatever is left here will be persisted.
CACHE_DIR=$2 # The contents of CACHE_DIR will be persisted between builds so we can use it to speed the builds up
ENV_DIR=$3     # An envdir directory of the app's environment variables

echo BUILD_DIR="$BUILD_DIR"
echo CACHE_DIR="$CACHE_DIR"
echo ENV_DIR="$ENV_DIR"
```
Applying it as a buildpack to a deis deployed project will output this:
```
BUILD_DIR=/tmp/build
CACHE_DIR=/tmp/cache
ENV_DIR=
```

Oddly, there is no third argument for the environment directory, as mentioned in the https://devcenter.heroku.com/articles/buildpack-api

Is this by design? As environment variables are natively passed and used by default, is this feature deprecated? I may be missing some heroku lore here that would explain this documentation/implementation divergence.

**Comment by bacongobbler** [comment]
Closing. This is not an issue with the officially supported buildpacks as we inject the app's environment variables into the container building the app. If they eventually do come around to support this as a documented and enforced argument then we'll have to revisit this, but for now it's not necessary (personal note: AFAICT it looks like a deprecated feature more than anything).

**Comment by crigor** [comment]
Can we reopen this or should I open a new issue? ENV_DIR is now documented on https://devcenter.heroku.com/articles/buildpack-api#bin-compile. 

A third-party buildpack for elixir uses MIX_ENV on ENV_DIR during the compile phase and defaults to"prod" if it's missing.

https://github.com/HashNuke/heroku-buildpack-elixir/blob/cebc35376e4a2840d3a395ef9e07e11893cfe2e8/lib/misc_funcs.sh#L59-L67
https://github.com/HashNuke/heroku-buildpack-elixir/blob/cebc35376e4a2840d3a395ef9e07e11893cfe2e8/lib/app_funcs.sh#L93

**Comment by mboersma** [comment]
> ENV_DIR is now documented on https://devcenter.heroku.com/articles/buildpack-api#bin-compile.

Deis should support it then. PRs happily accepted!
