### ISSUE TITLE
Initial git push fails sometimes with pre-receive hook

### ISSUE THREAD

**Issue by bfosberry** [deis/deis#1748]
If we perform the initial code push for a new application from our bamboo build server, the git push fails with a pre-receive hook error. We can push the code manually from a workstation, and then future pushes work from the build server.

02-Sep-2014 15:45:15    Already on 'master'
02-Sep-2014 15:45:16    HEAD is now at 93de9d5 Merge pull request #103 from shopkeep/blah-adding-authsrv-to-deis
02-Sep-2014 15:45:17    To ssh://git@deis.myserver.com/authentication-service.git
02-Sep-2014 15:45:17     ! [remote rejected] master -> master (pre-receive hook declined)
02-Sep-2014 15:45:17    error: failed to push some refs to 'ssh://git@deis.myserver.com/authentication-service.git'
02-Sep-2014 15:45:17    Failing task since return code of [/bin/sh /tmp/31227906-31358980-31686708-ScriptBuildTask-2590419885636869137.sh] was 1 while expected 0
02-Sep-2014 15:45:17    Finished task 'Push to Deis' with result: Failed
02-Sep-2014 15:45:17    Finalising the build...
02-Sep-2014 15:45:17    Stopping timer.

The task performs the following:
git checkout master
git reset --hard $(cat master.sha)
git remote add deis ssh://git@${bamboo.deisControllerHost}:2222/authentication-service.git
git push -f deis master

**Comment by btrepp** [comment]
I had a similar error today.

My authorized keys in deis-builder looks like this though
```
command="/usr/local/bin/gitreceive run admin 9a:b1:0f:e7:53:5f:53:1d:40:d3:69:d3:ac:fa:d8:e8",no-agent-forwarding,no-pty,no-user-rc,no-X11-forwarding,no-port-forwarding ssh-rsa *KEYINFO*
```

That seems horribly wrong

**Comment by carmstrong** [comment]
@btrepp That actually looks okay to me - see https://github.com/deis/deis/blob/f3489c3f430f7cd41965f723ee7a51a05a77a75a/builder/image/templates/authorized_keys#L2

This error has two common causes - your public key is no longer being offered by your local ssh-agent and/or it doesn't match the key in Deis; and the second is #2707. 

Can you confirm you don't fall into either bucket?

**Comment by btrepp** [comment]
Yeah further investigation shows thats what you are meant to see. I just reflexively am used to seeing the authorized keys file look a tad different that that :).

My agent was definitely offering the key, I think 2707 was probably the case though. I have to run a fork of the builder (it doesn't work standard in my environment), so my fork probably didn't have that commit in it.

**Comment by carmstrong** [comment]
> so my fork probably didn't have that commit in it.

That makes sense - that bug manifests in this way, too.
