### ISSUE TITLE
nginx location customisation

### ISSUE THREAD

**Issue by coen-hyde** [deis/deis#1753]
It would be great if the router allowed multiple apps to be mounted per domain. eg.

example.com/admin/ -> admin.service
example.com/blog/ -> blog.service
example.com/ -> example.com.service

**Comment by bacongobbler** [comment]
This is probably something which we cannot reasonably support, considering that we have other features like `deis certs` and `deis domains` that directly affect the router. However, structuring it yourself through hacking on the templates could be done by following the "Hacking on Deis" guide: http://docs.deis.io/en/latest/contributing/hacking/

Does that help guide you in the right direction?

**Comment by clayzermk1** [comment]
:+1: I too would love to have this.

**Comment by bacongobbler** [comment]
I'm closing this issue for the reasons stated above (other supported features would break with this change), though if someone were to come up with a custom router image supported by the community with this feature, we could look into documenting that as a custom router.
