### ISSUE TITLE
proposal: use a platform-agnostic database migration tool

### ISSUE THREAD

**Issue by mboersma** [deis/deis#1793]
We would like to use a tool other than Django South or Django 1.7 migrations to manage the controller's schema changes and data migrations. As we see in #1756, moving between South in Django 1.6 and migrations in 1.7 is not painless. And using a neutral framework like [goose](https://bitbucket.org/liamstask/goose) (written in go, but we would integrate it as a command-line tool) makes the idea of someday rewriting the controller itself in go more plausible.

 * Migrations still need run idempotently on each controller boot
 * We need to handle data migrations as well as schema migrations
 * Must be 100% backwards compatible with South

**Comment by bacongobbler** [comment]
Seeing how migration tools are not compatible with each other, there's no easy migration path between south -> goose. Because of that, we'd have to cut a v2.0 with this change so this'll have to stick on the back-burner for now.

**Comment by mboersma** [comment]
> this'll have to stick on the back-burner for now.

Can't disagree with you there. (We've also mumbled about using a different backing store like Mongo--Deis doesn't use PostgreSQL that extensively--but that would require a shift away from Django as well.)

**Comment by bacongobbler** [comment]
We should revisit this if we ever consider migrating the controller to some other language (probably an impossible task at this point) but this isn't something we can reasonably address without breaking compatibility. Originally I requested this feature (I just guilt-tripped @mboersma into writing out another issue for me :smiling_imp:) so I'm closing this for now, but lets re-open if we ever do decide to re-write the controller.
