### ISSUE TITLE
Specifying ssl certificates for deis-builder

### ISSUE THREAD

**Issue by btrepp** [deis/deis#1857]
So I've managed to get deis playing decently nicely with a proxy. The issue I am having is that the proxy resigns everything, which is causing deis-builder to fail on bootup. Logs of the builder are

```
Loading containers: ............: done.
Loading cedarish...
Step 0 : FROM progrium/cedarish:cedar
 ---> 8c923d10c52e
Step 1 : MAINTAINER OpDemand <info@opdemand.com>
 ---> Using cache
 ---> 3c431a226cc5
Step 2 : RUN useradd slugbuilder --home-dir /app
 ---> Using cache
 ---> 58145b5b6dcb
Step 3 : ADD ./builder/ /tmp/builder
 ---> Using cache
 ---> b96148477f5a
Step 4 : RUN /tmp/builder/install-buildpacks
 ---> Running in 98266a543582
Cloning into '/tmp/buildpacks/heroku-buildpack-multi.git'...
error: Failed connect to github.com:443; Connection timed out while accessing https://github.com/ddollar/heroku-buildpack-multi.git/info/refs
```

I'm not sure if that the builder is actually using the proxy, but i'm a little out of my depth with docker. The coreos host is using the proxy, and I've copied the cert into the coreos instance.

I've jumped into the container with `nse deis-builder` once it is starting up, and it does have env variables set from the proxy, though I these may have come form the coreos host?.

Testing the waters with curl I've gotten

```
root@b0edabf06cbd:/# curl https://github.com/ddollar/heroku-buildpack-multi.git/info/refs
curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

Which implies I'm going to need to add the certificate to the builder, but I'm not sure how. The builder seems to disappear from `docker ps` when it eventually fails. So I'm not sure how I would even tweak it.

Two questions arise, 
1) does anything other than the builder require net access?. 
2) Is there a good way to transparently proxy any containers that require net access?. Roughly I'm thinking having a proxy container running in docker, so the coreos would direct all http traffic through this, which could then be upstream. This is where we could configured trusted certs, and perhaps this even resigns it with a cert that every docker container would trust. In my mind deis is showing heaps of potential for a 'private' cloud, but its reliance on the internet is tricky with corporate IT.
3) failing 2, is there a quick way I can get my certs added to the builder image that will persist?.

**Comment by mvalbuquerque** [comment]
I used sudo curl -i -H
