### ISSUE TITLE
ref(registry): create upstream deis/docker-registry image

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#1945]
At the moment, we build `deis/registry` from complete scratch, importing the source code via retrieving the souce code from a git sha and constructing the image. This goes against The Docker Way in which we should be doing configuration *on top* of deis/docker-registry. To give an example, the registry Dockerfile should look like the following:

```
FROM deis/docker-registry:import-repository

ADD . /app
WORKDIR /app
CMD /app/bin/boot
```

and let upstream handle the rest.

**Comment by mboersma** [comment]
> we should be doing configuration on top of deis/docker-registry

I'm not sure we should. The current docker registry is based off ubuntu, and the new docker/distribution registry is big old `golang:1.4`. Deis uses `alpine:3.1`, which means Deis registry needs its own Dockerfile, and at that point I don't see much point in using Docker image inheritance. 

I've packaged the new registry for Deis [here](https://github.com/mboersma/deis/tree/new-docker-registry) and I don't see any good reason to change how we're doing it there. The docs for the new registry basically say "this is for development, you should repackage it for your production use."

**Comment by bacongobbler** [comment]
Sounds reasonable. I was just looking for a way to package our fork of the registry without having to clone the source code in our Dockerfile. Our process works though, and I know we eventually want to move away from our fork back to Docker, which we won't have control over the base image so the work invested here would be wasted.
