### ISSUE TITLE
Builder and Controller "hang" on fresh install

### ISSUE THREAD

**Issue by kingcody** [deis/deis#1953]
I was hoping I might be able to get some guidance on this issue. I have successfully installed the deis services by running `deisctl install platform` but on `deisctl start platform` my controller and builder containers are indefinitely 'waiting for confd to write initial templates'.

My setup is as follows:
- coreOS 440 new installs
- 2 bare metal, 1 libvirt
- working etcd and fleetctl from all nodes in cluster and dev computer
- cloud config based on deis example with proper variables changed and what not...

I've tried reinstalling the deis services and images. I've also done coreOS reinstalls (they're pretty quick) and always the same result. I've tried enough times that each machine in the cluster has had a turn being the "controller node".

Not trying to be a bother, but I've looked through the docker logs for obvious errors, attempted to trouble shoot etcd and/or fleet to see what I can discover there, and I think I'm pretty stuck ATM. If anyone could even just point me in the right direction it would be really awesome.

Thanks, and if there's any more information I can provide that will be helpful please just let me know.

**Comment by bacongobbler** [comment]
sorry, necro'ing an old thread to answer your question :)

~/.deis/units is created by `deisctl refresh-units`: https://github.com/deis/deis/blob/master/deisctl/cmd/cmd.go#L462-L465

**Comment by kingcody** [comment]
+1 to @bacongobbler for commitment  (:
