### ISSUE TITLE
builder: Bad protocol version identification 'dummy-value' from 10.240.190.22

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#1973]
When reading logs from builder, users may see something like:
```
Bad protocol version identification 'dummy-value' from 10.240.190.22
```

This is due to the changes made in #1940 - we had to refactor the ExecStartPost loops to use `ncat` instead of `cat /dev/tcp/...` because of the bash vulnerability fixed in [CoreOS 452.0.0](https://coreos.com/releases/#452.0.0) (specifically, bash no longer has direct network access). We need to pass something to ncat to send over the wire, so we use 'dummy-value'. We don't care that it's an invalid string - the import thing is that ncat can connect.

So, this is innocuous, but ideally we shouldn't need a string at all - maybe we can just send an end of transmission character?

**Comment by mboersma** [comment]
After #4273 this no longer shows up in the logs.
