### ISSUE TITLE
rolling restart for `deisctl restart router`

### ISSUE THREAD

**Issue by PierreKircher** [deis/deis#1988]
deisctl restart router
deis-router@1.service: dead                                      
deis-router@2.service: dead                                 
deis-router@3.service: dead                                 
deis-router@1.service: running                                 
deis-router@2.service: running                                 
deis-router@3.service: running   

in terms of the HA prep id be probably better to 
bring them down and start it up each after a other 
example with 3 routers
id 1 down .. id 1 up 
id 2 down .. id 2 up
id 3 down .. id 3 up

if we got a cluster full of apps .. its not really practical to have all routers instances go down at the same time and wait till the first 1 fetches the image from dockerhub 

that could result in an outage of all depending apps 

with that proposed reboot behavior we would keep at least 1 router up and serving all the time 

supposed to be an easy fix

**Comment by bacongobbler** [comment]
closing as something we won't be able to get for the LTS release, and deisctl has been deprecated in v2.
