### ISSUE TITLE
Feature request: deis users:list

### ISSUE THREAD

**Issue by ianblenke** [deis/deis#2006]
Presently, there is no way to list users without resorting to django magic or postgres queries.

The story:

As an admin, I wish to be able to enumerate all deis users presently registered.

So I run "deis help", no users command listed. I run "deis perms help", it does promise "deis perms:list", which falls short. Looking at http://docs.deis.io/en/latest/reference/client/, only users of an app can be enumerated, as well as all admin users, but there is no direct way of enumerating _all_ users including those who may not yet be associated with an app.

Manually enumerating all users is possible nse'd into the deis-database:

    psql "select * from django_users;"

or at the djago manage.py nse'd into the deis controller:

    User.objects.all();
 
Something more user friendly would be better.

**Comment by gvilarino** [comment]
+1

**Comment by Joshua-Anderson** [comment]
Started work on this in #3524

**Comment by ianblenke** [comment]
Just verified this, though I'm a bit concerned about the AnonymousUser:

    $ fleetctl ssh deis-controller
    $ docker exec -ti deis-controller bash -c 'ETCD=172.17.42.1:4001 ./manage.py shell'
    Python 2.7.6 (default, Mar 22 2014, 22:59:56)
    [GCC 4.8.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    (InteractiveConsole)
    >>> from django.contrib.auth.models import User
    >>> User.objects.all()
    [<User: AnonymousUser>, <User: myuser>]

Any ideas if this AnonymousUser is a dangerous thing?

**Comment by Xe** [comment]
That looks like an abstraction Django uses for a user that is not "logged in". No idea why it's being exposed though.
