### ISSUE TITLE
Running 2 web processes in one application

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#2011]
Hi,

I want to build a Rails Web Application that consists of 2 components.
A) A public facing website
B) An internal facing API server

Both will largely work on the same data, so it makes sense for me to have them in one repository because they act on the same database & same Rails models.

I want both components to be seperataly scalable + the internal facing API server to be hosted on seperate machines in my fleet (and having different firewall rules). I know that this last thing is not really yet possible, but ignore that for a second here.

Feature request: make it possible to have 2 (or more) different Procfile entries (web & web_api for example), that both axpose an HTTP frontend. Nice to have would be that they also use seperate set of domain names, although the probably simpler solution would be to expose them on 2 different public ports (web = 80, web_api = 8080), to make sure the proxy routes correctly.

Proposal of a different architecture (eg, using 2 apps) is also welcome, but note that codebase & env settings will be mostly shared...

**Comment by olalonde** [comment]
:+1:

**Comment by deis-admin** [comment]
Deis v1 LTS support ends February 13, 2017, and [v1.13.4](https://github.com/deis/deis/releases/tag/v1.13.4) is intended to be the last official release, so I'm closing this.

Please see [Deis Workflow](https://github.com/deis/workflow), the documentation / hub repository for the next-generation PaaS.
