### ISSUE TITLE
Deis publisher improvements

### ISSUE THREAD

**Issue by gust1n** [deis/deis#2044]
Hey! 
I thought I would create an issue before a PR so that we can discuss if you want this change or not. I've been keeping track of the new publisher service since it was first discussed and I've build one of my own for my company. Two things that bugs me with your approach are:
- The inability to unregister a service immediately when the container stops.
- Not handling multiple ports

Luckily I have solved both issues for me and I thought I would contribute my code if you want to:

The first issue is solved by keeping a simple in memory map of container id -> published keys. Since the only thing we get when container dies or stops it it's ID we can still safely remove all published keys for that container.

The second issue is solved by using the containerport as a sub key so the keys looks something like this:

`/deis/services/userservice/userservice-1/80 "1.2.3.4:49872"`
`/deis/services/userservice/userservice-1/3000 "1.2.3.4:49873"`

which for us worked really well both in our heads and in code. This works kind of the same way as docker env vars where you also state the port (like DB_PORT_5432_TCP_ADDR)

I could of course split this up in separate issues and PRs, but I wanted to know if this is interesting before I start working on it (my solution is not as generic as it has to be in a project like deis). Let me know what you think!

**Comment by bacongobbler** [comment]
considering that #3069 covers the "support multiple ports" part of this and we have a TTL in place for when a container is stopped I'm going to create a new issue for the "instant stop" feature and close this one out. Thanks @gust1n :)
