### ISSUE TITLE
Deis update engine

### ISSUE THREAD

**Issue by gabrtv** [deis/deis#2106]
Deis update engine is based on CoreUpdate and will ultimately provide fast, painless, zero-downtime upgrades of the platform control plane.

**Comment by iancoffey** [comment]
This should use the upgrade-prep and upgrade-takeover functionality in deisctl, and the CoreOS omaha server on the other end. It should ship as a unit, and be probably be initially disabled by default until it is mature.

Related:
https://coreos.com/docs/coreupdate/custom-apps/coreupdate-protocol/

**Comment by bacongobbler** [comment]
Is this something we still want to tackle in terms of v2? I think this is going to be solved in later versions of `helm` from what I've heard.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776), and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this.
