### ISSUE TITLE
deisctl erroring out on etcd errors from fleet

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#2126]
I see this issue way too often. When running a `deisctl start platform` or something similar, I see this:

```
><> deisctl start platform
● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●

Launching data containers...
deis-logger-data.service: exited
Data containers launched.
Launching service containers...
deis-logger@1.service: running
deis-publisher.service: running
deis-store-monitor.service: running
INFO log.go:73: Failed getting response from http://127.0.0.1:4001/: cancelled

Error: timeout reached
```

Which looks like we're erroring out [here](https://github.com/deis/deis/blob/65ef8e0779c005ad8c21801a32b2b35264fb76e5/deisctl/backend/fleet/state.go#L166-L170). I don't think we should be exiting on these errors.

**Comment by carmstrong** [comment]
@bacongobbler Safe to close this? I'm really hoping etcd/fleet errors aren't nearly as common!

**Comment by bacongobbler** [comment]
It's uncommon but still pops up from time to time. Still not sure what the culprit is for this, though...

**Comment by mboersma** [comment]
The code in question went away, and now we [ask `systemctl` directly](https://github.com/deis/deis/blob/master/deisctl/backend/fleet/status.go#L21-L41) for unit state. It seems unlikely that we could hit the same issue now, and in practice I haven't seen this halt `deisctl start platform` in many moons.

**Comment by mboersma** [comment]
@bacongobbler can we close this issue?

**Comment by bacongobbler** [comment]
yep!
