### ISSUE TITLE
Controller/Confd Issues

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/deis#2132]
I successfully created a local deis cluster (v13) with vagrant and was using it happily. After stopping the cluster with `vagrant halt` and starting it again with `vagrant run` I ran into the `Welcome to Nginx` issue. `deisctl jorunal controller` returns `Oct 13 23:51:55 deis-2 sh[1833]: controller: waiting for confd to write initial templates...` every 5 seconds.

Did I do anything wrong? Would you like me to supply any more info?

**Comment by carmstrong** [comment]
Closing as this is quite old @Joshua-Anderson. Have you given a recent release another shot?

**Comment by Joshua-Anderson** [comment]
Sounds good!
