### ISSUE TITLE
go buildpack doesn't respect version in Godeps.json

### ISSUE THREAD

**Issue by mboersma** [deis/deis#2153]
I changed the go version to 1.3.3 in this branch of our example app: https://github.com/deis/example-go/tree/update-go-ver

But we seem to install with 1.2.2 regardless on a `git push`. Detecting it this way apparently works on Heroku: https://github.com/kr/heroku-buildpack-go/issues/46.

**Comment by bacongobbler** [comment]
Hmm, upstream seems to indicate that it reads Godeps.json, so we should see if this is true: https://github.com/heroku/heroku-buildpack-go/blob/master/bin/compile#L65

**Comment by mboersma** [comment]
I tested with Godeps.json and it was ignored previously. I'll test this again with v1.4.0.

**Comment by mboersma** [comment]
Yes indeed this works as advertised. I finally got around to testing it:
```console
$ git push deis master
Counting objects: 32, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (27/27), done.
Writing objects: 100% (32/32), 10.43 KiB | 0 bytes/s, done.
Total 32 (delta 10), reused 0 (delta 0)
-----> Go app detected
-----> Installing go1.2.2... done
-----> Running: godep go install -tags heroku ./...
-----> Discovering process types
       Procfile declares types -> web
-----> Compiled slug size is 1.7M

-----> Building Docker image
...
```

And after [updating the go version](deis/example-go#6):
```console
$ git push deis master
Warning: Permanently added the RSA host key for IP address '[172.17.8.102]:2222' to the list of known hosts.
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 484 bytes | 0 bytes/s, done.
Total 4 (delta 1), reused 0 (delta 0)
-----> Go app detected
-----> Installing go1.4.2... done
-----> Running: godep go install -tags heroku ./...
-----> Discovering process types
```
