### ISSUE TITLE
Use confd watch

### ISSUE THREAD

**Issue by johanneswuerbach** [deis/deis#2160]
Currently it takes up to 5 seconds until a new app is added to nginx (5 seconds polling). Watch support was recently added to confd https://github.com/kelseyhightower/confd/pull/150 so it's time to add it to deis.

Might fix: https://github.com/deis/deis/issues/1927

**Comment by mboersma** [comment]
We are (almost) completely moved over to [`confd` 0.8](https://github.com/kelseyhightower/confd/releases/tag/v0.8.0) now thanks to the hard work of @bacongobbler. I am retitling this to reference `confd watch` only and assigning it.

**Comment by bacongobbler** [comment]
Thanks! let's get this in for 1.5 :D
