### ISSUE TITLE
Secure method for storing application credentials?

### ISSUE THREAD

**Issue by benmccann** [deis/deis#2217]
Would it make sense to use [crypt](http://xordataexchange.github.io/crypt/) for storing application credentials? Not sure what Deis is doing now, but it seemed like potentially a neat way to have that part managed by an open source component that can be shared by other projects as well such that it's more standardized and less unique to Deis.

**Comment by bacongobbler** [comment]
From my perspective crypt looks like a mini fork of confd with keyring support. If this is a good practice for us, we should investigate how we can use this for things like the router's SSL certificate/keys.

**Comment by benmccann** [comment]
I've been trying to follow what other projects are doing for this. Kubernetes recently started to make some really good progress here and has a good design doc. I think what they're doing looks like a pretty good solution
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/secrets.md

**Comment by bacongobbler** [comment]
For Deis, we bake the security credentials directly into the docker image. That way, the user does not need to source a file inside the container. The only way external users can access those secrets are by accessing the container directly. Eventually we can switch this out for something like docker/docker#10310 but this works for us at the moment.

The relevant code: https://github.com/deis/deis/blob/master/controller/registry/private.py#L60-L64

**Comment by bacongobbler** [comment]
@benmccann does this help you understand how application credentials are stored or would a specification help clarify things? Not quite sure what's the actionable item for this issue is.

**Comment by benmccann** [comment]
I'll close this since there's no specific ask at the moment. I was just curious how Deis handles this
