### ISSUE TITLE
CI jobs should ignore untestable files

### ISSUE THREAD

**Issue by mboersma** [deis/deis#2221]
At least with the build trigger strategy of polling, it's possible to ignore certain paths and wildcards. This would save us significant time since the `[skip ci]` comment to the GitHub PR builder doesn't seem to work for us. Currently we trigger most jobs on any change.

**Comment by bacongobbler** [comment]
+1 for stuff like only performing doc tests with doc changes, integration tests with platform changes, etc.

**Comment by sgoings** [comment]
Relates to #4039 and #4003

**Comment by mboersma** [comment]
This isn't something we plan to tackle for Deis v1 CI.
