### ISSUE TITLE
Add docs for disabling TLS in boot2docker

### ISSUE THREAD

**Issue by mboersma** [deis/deis#2230]
Currently to work with Docker 1.3.0 and Deis' tests, it is necessary to disable TLS if the docker engine is remote from the docker client, as in `boot2docker`. Otherwise, some confusing errors arise when starting the test-etcd container. We should add this (temporary) workaround to our hacking docs so Mac users in particular aren't confused.

The current workaround is a bit of a pain, and seems to revert when `boot2docker` restarts. You will need to add the line `DOCKER_TLS=""` to line 24 of _/etc/init.d/docker_ on your boot2docker vm so that section looks like this:

``````
start() {
    DOCKER_TLS=""
    # Not enabling Docker daemon TLS by default.
    if [ "$DOCKER_TLS" != "" ]; then```
``````

Don't bother editing _/var/lib/boot2docker/profile_; it doesn't seem to work as advertised for this setting.

``` console
$ boot2docker ssh
$ sudo /etc/init.d/docker stop
$ sudo vi /etc/init.d/docker  # make the changes described above, and save
$ sudo /etc/init.d/docker start
```

Make sure your local environment variables use port `2375` now instead of `2376` for TLS:

```
export DOCKER_HOST=tcp://192.168.59.103:2375
#export DOCKER_CERT_PATH=/Users/matt/.boot2docker/certs/boot2docker-vm
#export DOCKER_TLS_VERIFY=0
```

**Comment by mattheworiordan** [comment]
FYI, to work around this issue, I implemented this in my `Vagrantfile`

```
# Allow Mac OS X docker client to connect to Docker without TLS auth
  config.vm.provision "shell", inline: "echo 'DOCKER_TLS=no' > /var/lib/boot2docker/profile"
  config.vm.provision "shell", inline: "sudo /etc/init.d/docker stop >/dev/null 2>&1 || sudo /etc/init.d/docker start"
```
