### ISSUE TITLE
Support for private Docker registries with auth (Quay.io/Docker Hub)

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#2232]
The Deis controller currently has no functionality to manage credentials for pulling from private registries with auth enabled. This includes private registries on Quay.io and Docker Hub, as well as custom-deployed registries with auth enabled. 

A workaround for this currently is to deploy a custom registry with auth disabled. As long as it's accessible from the Deis installation, it can be firewalled off from the world.

**Comment by jacinto123** [comment]
+1 Really hope we get this some time soon

**Comment by hectorj2f** [comment]
+1

**Comment by ngbinh** [comment]
:+1: the work around works! But without auth and public facing private repo, it is impossible to try out images on local dev/qa machines.

**Comment by carmstrong** [comment]
Some additional discussion in #2124.

**Comment by pjvds** [comment]
:+1: for the deis user manage their own set of docker authentication credentials

**Comment by jmreicha** [comment]
+1

**Comment by carmstrong** [comment]
The planned solution for this is the `deis push` workflow (#2680) which will enable users to pull an image to their local Docker graph and then `deis push` it to deploy to Deis. 

For more information on our roadmap, see: http://docs.deis.io/en/latest/roadmap/roadmap/

**Comment by bacongobbler** [comment]
For anyone on Deis v1 with a Dockerfile relying on a private image, here is a quick and hacky solution thanks to @aabed:

```
$ deisctl dock builder
$ docker login quay.io
Login against server at https://quay.io/v1/
Username: myusername
Password: mypassword
Email: myemail@example.com
$ exit
$ git push deis master
```

I'm sure the same could be done in the controller too to allow `deis pull quay.io/...`:

```
$ deisctl dock controller
$ docker login quay.io
Login against server at https://quay.io/v1/
Username: myusername
Password: mypassword
Email: myemail@example.com
$ exit
$ deis pull quay.io/...
```

For Workflow (Deis v2), see http://docs-v2.readthedocs.org/en/latest/using-workflow/using-docker-images/#private-registry.

**Comment by Crispy1975** [comment]
@bacongobbler @aabed tried the above an no luck, getting the following output from the controller...

**Comment by bacongobbler** [comment]
We dropped support for v1 3 months ago so I can only ask you to upgrade to v2. Sorry!
