### ISSUE TITLE
App availability problems when stopping a node

### ISSUE THREAD

**Issue by bilts** [deis/deis#2278]
If an app has all of its instances running on the same node, and that node shuts down, the app will be unavailable, initially producing gateway timeout errors, then displaying the generic "Welcome to nginx" page.

Two improvements could remedy this:

1. Allow a node to be seamlessly removed from the cluster (bring up new services/apps on other nodes, route new requests to other nodes, allow pending requests to finish, shut down old services/apps).  Is this already possible somehow?
2. Ensure apps scaled to more than one instance are placed on different nodes, making them more robust against single node failures.

Deis is usually quick to recover from the above, but it seems to become a significant availability problem when the node in question also holds the builder service and the builder service moves to a node which does not have the builder image (as happens nearly every time in EC2 with auto load-balancing).  In that case, it seems to require multiple minutes for the app to recover.

**Comment by bacongobbler** [comment]
Note that Swarm has a really great use case for failover. Combined with https://github.com/docker/swarm/pull/349 and some app affinity rules for application scheduling, #3134 should see significant improvements with app fail-over cases, as we won't have to pull the image if the instance is moved on another host.

**Comment by bacongobbler** [comment]
fleet's solved this issue as of late by scheduling units through least-loaded node, so the net result should be a well-balanced ~~breakfast~~ cluster. If there are specific fleet issues which not causing this intended behaviour, then let's open it up at coreos/fleet. Thanks!
