### ISSUE TITLE
Allow to use any S3 compatible store

### ISSUE THREAD

**Issue by johanneswuerbach** [deis/deis#2295]
deis-store is great, but it feels less production ready then deis (crashed twice yesterday and bringing it back up took 2 hours) and when the store is not running, everything is down. Most deis components are using deis-store already via the S3 compatible gateway so I would make sense from my point-of-view to have this option configurable.

Side note: I'm already using S3 as registry storage and RDS as database, but an unavailable deis-store still results in a not bootable registry, which means non of your apps will start / restart.
Issue: https://github.com/deis/deis/blob/master/registry/bin/boot#L48

**Comment by bacongobbler** [comment]
oops. Since most of the conversation has been ongoing in #2812 let's keep it rolling over there.
