### ISSUE TITLE
Service registry lookup

### ISSUE THREAD

**Issue by mboersma** [deis/deis#231]
Come up with simple design for new object models / dynamic config / envvars to be Deis' service registry and attachment workflow.

**Comment by mboersma** [comment]
This came up again on IRC, so here is a proxy +1 on this issue; it is very much wanted.

**Comment by ianblenke** [comment]
This came up again this week with regard to having a plugin to support submodules (being that git archive strips the .git directory) as mentioned in #3157

**Comment by ianblenke** [comment]
Flynn has a service control plane of sorts:

https://flynn.io/docs/postgres

At the moment, it seems to be a certain amount of manual json to add your own persistence service layers based on docker containers:

https://gist.github.com/lmars/fca0f18b4ecd507fb39a

Similarly, tsuru has a services layer:

http://docs.tsuru.io/en/stable/services/index.html

There are some great ideas and parallel development going on in this space. Might not be a bad idea to take a quick look and understand the directions they are headed.

**Comment by bacongobbler** [comment]
We've been keeping our eyes on Cloud Foundry's [Service Broker](https://github.com/cloudfoundry/cloud_controller_ng/blob/master/app/models/services/service_broker.rb) as well as the corresponding [API](http://docs.cloudfoundry.org/services/api.html) as I am partially familiar with it, but we're open to look at what other PaaSes have done for an initial proposal.

**Comment by azurewraith** [comment]
Left a blurb that relates to some motivation and use cases here: https://github.com/deis/deis/issues/3229#issuecomment-77943128

**Comment by onbjerg** [comment]
What is the temporary way to add databases etc. and access them via. your application?

**Comment by bacongobbler** [comment]
@onbjerg http://docs.deis.io/en/latest/using_deis/config-application/#attach-to-backing-services

**Comment by onbjerg** [comment]
@bacongobbler What if I want to run my database _on_ Deis? Not possible yet?

Also, any news on this? Still researching, or?

**Comment by bacongobbler** [comment]
No news other than what's already been posted. Lots of feature requests with very little manpower is all :)

**Comment by jwaldrip** [comment]
Any chance this is getting priority with the recent EY aquisition?

**Comment by cddr** [comment]
In the meantime, how would people suggest sharing a development database setup with colleagues. To me, the best options seem to be:-

 * setup a hosted instance on something like RDS and config the app to connect to that (would only work with teams small enough not to clobber each other's development databases.
 * fork the repo and tweak the deis Vagrantfile to add an instance that provisions a database service and makes it available to the rest of the cluster

Am I missing anything better?

**Comment by bacongobbler** [comment]
Short from hosting it on your own infrastructure, that sounds correct to me.

**Comment by CloudSide** [comment]
@bacongobbler  Where is the Service Registry repository?

**Comment by bacongobbler** [comment]
@CloudSide I deleted https://github.com/bacongobbler/service-registry as it was from a pre-production release of Deis (v0.7.0 or something) and is quite out of date. We weren't going to move forward with that branch. The idea now is to implement a service endpoint in the controller, which then will register and consume Cloud Foundry broker APIs since that project has been open-sourced and is used in production.

**Comment by CloudSide** [comment]
@bacongobbler How do I use `Cloud Foundry broker APIs ` in `deis` ?

**Comment by bacongobbler** [comment]
it isn't implemented yet. This issue is to track the progress of that feature. :)

**Comment by CloudSide** [comment]
I'm looking forward

**Comment by pascalschwientek** [comment]
Any progress in the last 2 month on this?

**Comment by bacongobbler** [comment]
@pascalschwientek we've updated [the roadmap](http://docs.deis.io/en/latest/roadmap/roadmap/#service-broker), but all communication related to this feature will be laid out in this issue. No progress has been made.

**Comment by zeiv** [comment]
> all communication related to this feature will be laid out in this issue

Is this still true?  What about Workflow?

**Comment by bacongobbler** [comment]
It will be a continuation of this thread. I will be tackling `deis addons` support once [steward](https://github.com/deis/steward) becomes a little more stable for general use. Right now it's in the middle of a major refactor after a face-to-face meeting with users from SIG-service-catalog.

**Comment by zeiv** [comment]
Ok sweet, thanks for the update.

**Comment by deis-admin** [comment]
Moved to deis/controller#1220.
