### ISSUE TITLE
"deisctl start platform" stuck at deis-store-monitor

### ISSUE THREAD

**Issue by jamespacileo** [deis/deis#2330]
The "activating" continues till infinity. This is on a fresh set of 3 boxes on DigitalOcean running on CoreOS alpha channel.

```
core@deis-1 ~ $ deisctl start platform
● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●

Storage subsystem...
deis-store-monitor.service: activating/start-pre
deis-store-monitor.service: activating/auto-restart
deis-store-monitor.service: activating/start-pre
deis-store-monitor.service: activating/auto-restart
deis-store-monitor.service: activating/start-pre
deis-store-monitor.service: activating/auto-restart
deis-store-monitor.service: activating/start-pre
...
```

**Comment by josh-padnick** [comment]
Just wanted to chime in that I also experienced this issue.  In my case, I had mistakenly assumed from the docs that I could provision deis onto any arbitrary CoreOS cluster so I didn't bother using the `Vagrantfile` or `user-data` defined in the deis repo.  

Once I launched a new Vagrant cluster from the deis-provided `Vagrantfile` and `user-data`, things worked great.

This might be improved with better error messages for the `deis start platform` command and more explicit notices in the documentation that you have to use the deis-provided `Vagrantfile` and `user-data`.

**Comment by carmstrong** [comment]
> This might be improved with better error messages for the deis start platform command and more explicit notices in the documentation that you have to use the deis-provided Vagrantfile and user-data.

We're pretty explicit about this in the Vagrant installation docs: http://docs.deis.io/en/latest/installing_deis/vagrant/#boot-coreos

However, if you feel there is room for improvement, we'd welcome a pull request to propose changes.

**Comment by rljohnsn** [comment]
Running into the same attempting an install on a bare metal coreos cluster.

```
ljohnson@jor-el[~]
() $ deisctl install platform
● ▴ ■
■ ● ▴ Installing Deis...
▴ ■ ●

Storage subsystem...
deis-store-daemon.service: loaded
deis-store-volume.service: loaded
deis-store-monitor.service: loaded
deis-store-metadata.service: loaded
deis-store-gateway@1.service: loaded
Logging subsystem...
deis-logspout.service: loaded
deis-logger.service: loaded
Control plane...
deis-controller.service: loaded
deis-registry@1.service: loaded
deis-database.service: loaded
deis-builder.service: loaded
deis-cache.service: loaded
Data plane...
deis-publisher.service: loaded
Routing mesh...
deis-router@3.service: loaded
deis-router@1.service: loaded
deis-router@2.service: loaded
Done.

Please run `deisctl start platform` to boot up Deis.
ljohnson@jor-el[~]
() $ deisctl start platform
● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●

Storage subsystem...
deis-store-monitor.service: activating/start-pre
deis-store-monitor.service: activating/auto-restart
#never gets beyond this point
```

```
Mar 27 01:12:11 comp02 systemd[1]: Starting deis-store-monitor...
Mar 27 01:12:11 comp02 sh[1680]: /bin/sh: /run/deis/bin/get_image: No such file or directory
Mar 27 01:12:11 comp02 sh[1680]: docker: "pull" requires 1 argument. See 'docker pull --help'.
Mar 27 01:12:11 comp02 systemd[1]: deis-store-monitor.service: control process exited, code=exited status=1
Mar 27 01:12:11 comp02 systemd[1]: Failed to start deis-store-monitor.
Mar 27 01:12:11 comp02 systemd[1]: Unit deis-store-monitor.service entered failed state.
Mar 27 01:12:11 comp02 systemd[1]: deis-store-monitor.service failed.
```

What is missing from my cloud-config file? My computes were pxe booted, CoreOS installed to disk and a cloud-config like the following. Trying to make it completely reproducible via cloud-config.
https://gist.github.com/rljohnsn/2939b2cb21f1af1906ba

Thanks in advance for any help.

**Comment by aledbf** [comment]
@rljohnsn deis uses a custom cloud-config file https://github.com/deis/deis/blob/master/contrib/coreos/user-data.example#L117
The missing script (`/run/deis/bin/get_image`) is defined in the `write_files` section. Maybe you can start from that template to generate your custom configuration.

**Comment by rljohnsn** [comment]
@aledbf rockin! and a record 2m response time!

**Comment by artmees** [comment]
so @rljohnsn how exactly was you able to fix it ?

**Comment by rljohnsn** [comment]
@artmees you must start from the deis cloud-config files as it creates many custom files the components require during install and operation. As shown in the link from @aledbf 

At the time my specific issues was because I didn't have the following defined:

https://github.com/deis/deis/blob/master/contrib/coreos/user-data.example#L113

I never found anywhere in the online documentation mention of the requirement to begin with a specific set of cloud-config files.
