### ISSUE TITLE
platform: moving a deis-* container causes confd error

### ISSUE THREAD

**Issue by kingcody** [deis/deis#2351]
I've observed that whenever a deis container is moved to another host, due to host failure, that other deis containers that require `etcd` entries that are provided by the moved container, need to be restarted manually. Those container's `confd` service will repeatedly fail with exit code `1` until the "required" container has been restarted.

Steps to reproduce:
- Kill node running `deis-database`
- `deis-database` is started on another machine in the cluster
- `deis-controller`'s confd process will start exiting `1`

If anyone has any Ideas as to what would be useful as far as logs, etcd output, etc..., just let me know and I'll try to include.

**coreOS: `472`**
**deis: `0.15.0`**

**Comment by mboersma** [comment]
We have tested HA failover scenarios, and losing the deis-database node doesn't require services to be restarted at least with v1.2.0. I'm going to close this issue since it hasn't seen an update in a couple months.
