### ISSUE TITLE
deisctl should have unit tests for parsing logic

### ISSUE THREAD

**Issue by mboersma** [deis/deis#2418]
As a first pass at enhancing unit tests for `deisctl`, we should refactor all `docopt` parsing logic into separately testable functions and add regression tests for CLI argument variations. This should be a straightforward task post-stable, and allow us to add some useful tests (before tackling the trickier issues of mocking `fleet` and such).

**Comment by bacongobbler** [comment]
FYI I was able to do something like this with a pet project a few weeks back. I was just relying on Go's native `flag` library, though, so this may act differently for docopt: https://github.com/fishworks/dis/blob/master/dis/install_test.go#L90-L117

**Comment by carmstrong** [comment]
We'll track unit tests and mocking fleet in #2418.
