### ISSUE TITLE
Nightly testing against coreos alpha channel

### ISSUE THREAD

**Issue by johanneswuerbach** [deis/deis#2420]
As some platforms (DO and Rackspace) allow customers only to select a coreos channel and not a specific version, deis should be tested regularly against the latest coreos alpha.

**Comment by mboersma** [comment]
I added nightly jobs [test-coreos-alpha](https://ci.deis.io/job/test-coreos-alpha/) and friends to CI. Thanks for pointing this out @johanneswuerbach.
