### ISSUE TITLE
Deis for apps + Smartstack for backend services. Good combination?

### ISSUE THREAD

**Issue by gebrits** [deis/deis#2440]
It seems Deis is targeted towards apps. It may encompass service lookup (Postgrs, Redis) somewhere in the future ([issue](https://github.com/deis/deis/issues/231)), but discovery of backend services will likely never be part of Deis. Is that correct? 

In view of that, would you say using Deis for apps + something like [SmartStack](http://nerds.airbnb.com/smartstack-service-discovery-cloud/) for discovery of backend services would be a good combination?

**Comment by bacongobbler** [comment]
@gebrits does this answer your question? If so, do I have your permission to close this? :)

**Comment by gebrits** [comment]
please do ;)
