### ISSUE TITLE
Log ownership change after in-place upgrade from 0.15.1 to 1.0.0

### ISSUE THREAD

**Issue by jorihardman** [deis/deis#2481]
I was unable to run any commands with the deis client on one of my apps without getting a ```IOError: [Errno 13] Permission denied: u'/data/logs/production.log'``` where production is the name of the app. I was able to fix it by sshing into the machine running the controller. I then performed an ```nse deis-controller``` and looked into the log directory. Whereas my other app.log was owned by the deis user, this one was owned by root. ```chown deis:deis production.log``` fixed the issue for me.

**Comment by bacongobbler** [comment]
sounds like #2455 indicates this was a ceph issue upgrading from firefly to giant. Considering that this is a really old bug and there's nothing actionable on our end, I'm going to go ahead and close this but please re-open if you feel like this is still an issue. Thanks!
