### ISSUE TITLE
Can't start platform 1.0.0 in Openstack

### ISSUE THREAD

**Issue by adrianmoya** [deis/deis#2496]
I've been strugling with 1.0.0 and a clean installation. `deisctl start platform`always end up in a mess. I tryed hard restarting components and stuff before opening another "can't start platform" ticket, but it's so frustrating...

The symptoms are the same always: in the middle of `deisctl start platform` I get an `could not find unit: deis-database.service` and hangs. I ctrl+C and rerun `deisctl start platform` until I get `could not find unit: deis-builder.service` and hangs.Finally the result is:

```
UNIT				MACHINE			LOAD	ACTIVE		SUB
deis-builder.service		99de9b2a.../10.21.12.26	loaded	activating	start-post
deis-cache.service		0d105515.../10.21.12.25	loaded	active		running
deis-controller.service		7489579f.../10.21.12.24	loaded	active		running
deis-database.service		99de9b2a.../10.21.12.26	loaded	active		running
deis-logger.service		7489579f.../10.21.12.24	loaded	active		running
deis-logspout.service		0d105515.../10.21.12.25	loaded	active		running
deis-logspout.service		7489579f.../10.21.12.24	loaded	active		running
deis-logspout.service		99de9b2a.../10.21.12.26	loaded	active		running
deis-publisher.service		0d105515.../10.21.12.25	loaded	active		running
deis-publisher.service		7489579f.../10.21.12.24	loaded	active		running
deis-publisher.service		99de9b2a.../10.21.12.26	loaded	active		running
deis-registry.service		0d105515.../10.21.12.25	loaded	active		running
deis-router@1.service		0d105515.../10.21.12.25	loaded	active		running
deis-router@2.service		7489579f.../10.21.12.24	loaded	active		running
deis-router@3.service		99de9b2a.../10.21.12.26	loaded	active		running
deis-store-daemon.service	0d105515.../10.21.12.25	loaded	active		running
deis-store-daemon.service	7489579f.../10.21.12.24	loaded	active		running
deis-store-daemon.service	99de9b2a.../10.21.12.26	loaded	active		running
deis-store-gateway.service	0d105515.../10.21.12.25	loaded	active		running
deis-store-metadata.service	0d105515.../10.21.12.25	loaded	active		running
deis-store-metadata.service	7489579f.../10.21.12.24	loaded	active		running
deis-store-metadata.service	99de9b2a.../10.21.12.26	loaded	active		running
deis-store-monitor.service	0d105515.../10.21.12.25	loaded	active		running
deis-store-monitor.service	7489579f.../10.21.12.24	loaded	active		running
deis-store-monitor.service	99de9b2a.../10.21.12.26	loaded	active		running
deis-store-volume.service	0d105515.../10.21.12.25	loaded	active		running
deis-store-volume.service	7489579f.../10.21.12.24	loaded	active		running
deis-store-volume.service	99de9b2a.../10.21.12.26	loaded	active		running
```

Almost all components are stuck in confd loops. I know there are missing etcd keys, but I don't know how to manually recover from this situation. 

```
etcdctl ls --recursive /deis | grep -E "host|port"
/deis/store/hosts
/deis/store/hosts/10.21.12.25
/deis/store/hosts/10.21.12.26
/deis/store/hosts/10.21.12.24
/deis/store/gateway/host
/deis/store/gateway/port
/deis/cache/host
/deis/cache/port
/deis/router/hosts
/deis/router/hosts/10.21.12.26
/deis/router/hosts/10.21.12.24
/deis/router/hosts/10.21.12.25
/deis/logs/port
/deis/logs/host
```

Maybe the docs should include instructions for a manual installation, o installation by groups of components, or a way to pre-fech deis images to prevent timeouts which I think it may be the reason, althou my connection is 10MB speed (let's say 2MB in real life). I'll be happy to contribute to the troubleshooting section this case which for me happens every time :(

**Comment by carmstrong** [comment]
> please ping me once you implement this change and I'll be happy to try again installation to see if it goes better.

@adrianmoya We implemented these changes for AWS and have seen significant stability and performance improvements around etcd/fleet. The relevant unit changes are here: https://github.com/deis/deis/blob/master/contrib/ec2/gen-json.py

We have no way of using or testing OpenStack in-house (it's a community-supported platform for Deis), but I'm hoping we can help users to implement the same fixes we saw on EC2.
