### ISSUE TITLE
Error with deisctl install platform: Could not find unit template for store-daemon

### ISSUE THREAD

**Issue by mikehaertl** [deis/deis#2498]
I've followed the installation guide for Vagrant. Everything worked fine so far, but `deisctl install platform` stalls forever:

```
$ deisctl install platform
● ▴ ■
■ ● ▴ Installing Deis...
▴ ■ ●

Storage subsystem...
Could not find unit template for store-daemon
```

If it helps, here some system specs from `inxi -v 2`:

```
System:    Host: Nilar Kernel: 3.13.0-24-generic x86_64 (64 bit) Desktop: Gnome Distro: Linux Mint 17 Qiana
Machine:   Mobo: ASUSTeK model: M2N68 Plus version: Rev X.0x Bios: American Megatrends version: 1004 date: 11/04/2009
CPU:       Quad core AMD Athlon II X4 640 (-MCP-) clocked at 3013.444 MHz 
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Redwood XT [Radeon HD 5670/5690/5730] 
           X.Org: 1.15.1 drivers: ati,fglrx (unloaded: fbdev,vesa,radeon) Resolution: 1920x1200@60.0hz 
           GLX Renderer: AMD Radeon HD 5670 GLX Version: 4.3.12798 - CPC 13.35.1005
Network:   Card-1: NVIDIA MCP61 Ethernet driver: forcedeth 
           Card-2: Ralink RT2500 Wireless 802.11bg driver: rt2500pci 
Drives:    HDD Total Size: 252.1GB (17.3% used) 1: model: Samsung_SSD_840 
           2: model: QIMONDA 
Info:      Processes: 218 Uptime: 24 min Memory: 3308.6/3953.1MB Client: Shell inxi: 1.8.4 
```

**Comment by MarkHerhold** [comment]
Fast forward to April 2015 and this still appears to be an issue, but it may have been partially due to permissions.
Running `chown [me] ~/.deis/ -R` then `refresh-units` fixed the issue.

**Comment by toxicblu** [comment]
@mikehaertl same here. Thanks for posting a solution.

**Comment by dudymas** [comment]
Unfortunately, that's not fixing the issue for me right now.
Has anyone else been unable to get the chown fix to work?

I bring up three coreos nodes using the cloudinit from the deis repo ( make discovery-url ).
then I ssh in. Verify that all the nodes are found ( fleetctl list-machines )
After setting domain info and other configs
I then do:
- deisctl refresh-units
- deisctl install platform
- chown core ~/.deis/ -R
- deisctl refresh-units
- deisctl install platform

still broken. Should we open an issue? I tried installing deisctl on a fresh mac and I still got the same issue. This is clean installs, so maybe there's some lingering files that refresh-units isn't touching that we need to also include in a fix?

**Comment by carmstrong** [comment]
@dudymas You may actually be running into #3832 which is a legitimate bug that we are fixing in #3835. Sorry for the trouble!

**Comment by dudymas** [comment]
confirmed!

for anyone affected, run this:
```
for fn in ~/.deis/units/* ; do mv $fn{,.service} ; done
```

this fixed this issue for me... just note that you shouldn't do this if you have existing files already with the correct .service extension

thanks @carmstrong

**Comment by carmstrong** [comment]
> for anyone affected, run this:

Appreciate the workaround! We're deciding whether or not we're cutting a v1.7.1 release of Deis - if so, we'll include that fix to deisctl. We'll probably need to ship the fix somehow...
