### ISSUE TITLE
deis-store-daemon incorrectly fails; Ceph clusters have more OSDs than machines

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#2519]
On initial provision, the daemons sometimes fail with error output:

```
Nov 14 13:41:44 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal systemd[1]: Starting deis-store-daemon...
Nov 14 13:42:01 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal systemd[1]: Started deis-store-daemon.
Nov 14 13:42:11 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal sh[8757]: store-daemon: creating OSD...
Nov 14 13:42:48 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal sh[8757]: store-daemon: FATAL - We have an OSD ID that isn't an integer
Nov 14 13:42:48 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal sh[8757]: store-daemon: FATAL - This likely means the monitor we tried to connect to isn't up, but others may be.
Nov 14 13:42:48 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal sh[8757]: store-daemon: FATAL - We can't proceed because we don't know if an OSD was created or not.
Nov 14 13:42:49 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal systemd[1]: deis-store-daemon.service: main process exited, code=exited, status=1/FAILURE
Nov 14 13:42:49 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal docker[9086]: Error response from daemon: No such container: deis-store-daemon
Nov 14 13:42:49 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal docker[9086]: 2014/11/14 13:42:49 Error: failed to remove one or more containers
Nov 14 13:42:49 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal systemd[1]: Unit deis-store-daemon.service entered failed state.
Nov 14 13:42:54 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal systemd[1]: deis-store-daemon.service holdoff time over, scheduling restart.
Nov 14 13:42:54 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal systemd[1]: Stopping deis-store-daemon...
Nov 14 13:42:54 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal systemd[1]: Starting deis-store-daemon...
Nov 14 13:43:04 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal systemd[1]: Started deis-store-daemon.
Nov 14 13:43:11 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal sh[9176]: store-daemon: creating OSD...
Nov 14 13:43:27 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal sh[9176]: store-daemon: created OSD 3
Nov 14 13:43:27 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal sh[9176]: store-daemon: OSD not yet initialized. Initializing...
Nov 14 13:43:29 deis-cc4a9dd1-ed85-4958-9fcd-51444b43cfb3.novalocal sh[9176]: 2014-11-14 13:43:29.708416 7f3005a6f900  0 ceph version 0.87 (c51c8f9d80fa4e0168aa52685b8de40e42758578), process ceph-osd, pid 68
<snipped...>
```

This is caused by [this check](https://github.com/deis/deis/blob/6bbccb748f604d72236e9b54c94971c1f49066f7/store/daemon/bin/boot#L25-L30) in the /bin/boot script for store-daemons. This was intended to be a more foolproof method of ensuring that OSD creation succeeds - [previously](https://github.com/deis/deis/blob/b5cb7427b3e83381afa4aa6e52c29231c5a18862/store/daemon/bin/boot#L23-L24), we had the OSDs sleep for 10 seconds after coming up to ensure the monitors were up before proceeding to create an OSD. It actually achieves this goal. However, we are actually creating more OSDs than we intend to. When we get a non-integer back from `ceph osd create`, this usually means we are looking at a monitor fault, which means that the monitor we tried to connect to isn't yet up. The create will most likely succeed anyway, as the Ceph client will connect to a different monitor to create the OSD. There doesn't seem to be a good way to trust the output from `ceph osd create`.

The result of failing this check is that the `store-daemon` container will exit. When fleet restarts it, the script will again try to create an OSD (and usually this time it will succeed), which is what results in having more OSDs than we intend.

I'm wondering if the way to handle this is rather than trying to interpret the output of `ceph osd create`, we instead run the command and then pollwait on the OSD map output until we see ourselves in the list. This will require some output cleaning which could be fragile, but I can't think of a better way to do this.

**Note**: this isn't a major issue - having more OSDs that aren't up doesn't really affect our cluster, since we require Ceph to maintain 3 copies of all data. As long as we have 3 OSDs up, our cluster should be in a `HEALTH_OK` state. But I don't know what affect this has on the [CRUSH map](http://ceph.com/docs/master/rados/operations/crush-map/), so it's a good idea for us to fix this.

**Comment by carmstrong** [comment]
@gabrtv This is related to the /bin/bash to Go rewrite.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776), and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this.

**Comment by bacongobbler** [comment]
closing as irrelevant for [v2](https://deis.com/blog/2016/workflow-stable/).
