### ISSUE TITLE
etcd frequent failure with 3-node cluster

### ISSUE THREAD

**Issue by jensb1** [deis/deis#2547]
Hello, 

I have experimented some with a three node cluster on Amazon EC2. It seems that when terminating an instance the cluster is very rarely coming up without any manual fix. When I instead increase the cluster size to 5 i have had no problems. 

Frequent problems:

* Total failure: etcd fails and cannot be started

* Fixable: Docker fails to start some instances with "file or directory not found", it seems that the docker images is corrupt, removing all images and reloading the fixed it.
* Fixable: Brtfs subvolume is not created correctly on the new node that is started, docker fails to pull repository. Manual brtfs create fixes this
* Fixable: Need to restart all of the units in order to get all units up and running again. 

Question:

* Anyone else have this experience with etcd of failing frequently on a three node cluster. Feels like the recommendation of at least 3 nodes should be at least 5 since I have never had that problem in a 5-node cluster.

* How are downscaling of the cluster supposed to work, does it require manual ssh:ing to take down the monitors, osds, etcd config variables etc. Or is there a script for solving this?

**Comment by carmstrong** [comment]
@jensb1 Deis v1.2.0 has significant improvements in etcd/fleet performance. Could you please retry this test on the latest Deis release (or master)? I'm thinking you'll have a much better experience.

**Comment by carmstrong** [comment]
Closing - we've seen significant improvements in performance on EC2 over the past few releases, and #2877 is tracking the autoscaling issue.
