### ISSUE TITLE
docs(deisctl): add documentation around registry HA

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#2606]
#2434

**Comment by bacongobbler** [comment]
related: #3617

**Comment by mboersma** [comment]
Deis intends to move to registry V2 in #4641. This is the upstream [guidance on HA](https://github.com/docker/distribution/blob/master/docs/deploying.md#load-balancing-considerations) I could find.

**Comment by bacongobbler** [comment]
closing as irrelevant for [v2](https://deis.com/blog/2016/workflow-stable/).
