### ISSUE TITLE
deis-logger dependency question

### ISSUE THREAD

**Issue by aledbf** [deis/deis#2615]
The `deis-logger.service` has a dependency in another service (`deis-store-volume.service`).
I had a problem with ceph in one node with `deis-store-volume` and in the same node was scheduled `deis-logger` but the ceph shared mount was ok (`/var/lib/deis/store`). With this scenario the logger never starts so `deis-logspout` and `deis-controller` never start.

Is this dependency ok? Is not possible to depend just on the ceph mount?

**Comment by mboersma** [comment]
Is this still something we need to PR or can we close this now? It's five months old. :older_man:

**Comment by carmstrong** [comment]
> It's five months old.

Let's close this - we can reopen if someone runs into it.
