### ISSUE TITLE
`deis ps` prints list of processes twice

### ISSUE THREAD

**Issue by renegare** [deis/deis#2654]
Given I have 3 servers in my cluster, and I scale ```myapp``` to 3
Running  the following (in the root of my project):
```
$ deis ps
```
Prints out:
```
=== myapp Processes

--- cmd:
cmd.1 up (v1)
cmd.2 up (v1)
cmd.3 up (v1)
cmd.1 up (v1)
cmd.2 up (v1)
cmd.3 up (v1)
```

This gives the incorrect impression that ```myapp``` is running at a scale of 6!

I can confirm that running ```fleetctl list-units``` shows that there is in fact only 3 processes running.

I imagine that this is more of a superficial bug ... here are my environment details:

```
Client Env:
> OS: osx 10.10.1
> Python: 2.7.6
> deis: 1.0.2

COREOS: 509.1.0
```

If there is anymore information I should give, please let me know.

**Comment by mboersma** [comment]
We haven't managed to reproduce this. If it's still a problem with the current version of Deis, please reopen this issue or create a new one.
