### ISSUE TITLE
Deis app hangs on launch, app sits as (created)

### ISSUE THREAD

**Issue by adamkdean** [deis/deis#2705]
I'm having a strange issue I've not had before on Deis 1.0.2, where when I push to the deis remote, most times it hangs on the `Launching` stage.

When I run deis ps, I get one process as up and one as created. If I scale it down, it removes the created one and stays at the old version.

    adam@toolbox:~/test-pipeline$ deis ps
    === test-pipeline-master Processes

    --- cmd:
    cmd.1 up (v7)
    cmd.1 created (v9)

I did manage to push some which worked, but now they're just freezing.

Is there a way I can investigate this?

FYI I am running on Rackspace, three performance1-4 machines, they have two networks attached, the eth0 (public) is 10.21.12.0/24 and eth1 (private) is 10.0.0.0/24. The reason is that these are behind a firewall and so couldn't have an actual public network attached. I don't think this should make a difference.

**Comment by carmstrong** [comment]
@adamkdean Any more insights on this funky issue?

**Comment by adamkdean** [comment]
Afraid not mate, we decommissioned the cluster over the Christmas period. We've just received some hardware which is with ops at the moment, but once that's up and running I'm going to be getting another cluster up and running on the local side and will be testing it once more. If I run into this issue, I'll update this call.

**Comment by adamkdean** [comment]
Going to close it for now though as I don't have this particular issue *right now*
