### ISSUE TITLE
Apps should communicate over local network

### ISSUE THREAD

**Issue by mattapperson** [deis/deis#2715]
If I have 2 apps on the same cluster that need to communicate as a Backing Services, this should in my opinion communicate over the local network vs going out to the internet and being routed back locally

**Comment by bacongobbler** [comment]
/me dons security hat

This looks like it collides with https://github.com/deis/deis/issues/986. The general idea I get from most of our customers is that they do not want containers able to talk to each other. Heroku has the same answer, which is to say that communication does not occur internally and that if you want to link apps together, use DNS. I could see a proposal where we add a way for users to allow communication between apps via some internal network tunnel... I'm just concerned about the security implications.

/me removes security hat

**Comment by seeksong** [comment]
There are cases communication between containers are required. Especially if the app needs to identify individual instance of a service, like Netflix Eureka.

**Comment by PierreKircher** [comment]
that can go over the router .. apart from that .. im all for internal dns

**Comment by seeksong** [comment]
Why cannot Deis populate a set of environment variables to expose the internal ip address and port number when the container starts? That way, if internal communication required, the app can just use the internal private ip and port.

**Comment by seeksong** [comment]
what I am looking for here is a way to communicate with an "instance" of an application. Say if we have an application and we scale it up to 3 instances. Now if we want to send a request to instance 2 to query its status, I don't think there is any way we can do it in current version of Deis.

**Comment by carmstrong** [comment]
> what I am looking for here is a way to communicate with an "instance" of an application.

I think that's an abstraction that Deis arguably *shouldn't* need to know or care about. Is that something that you can handle in the application logic itself, and keep track of its peers?

**Comment by bacongobbler** [comment]
related: #3812

**Comment by krancour** [comment]
> The general idea I get from most of our customers is that they do not want containers to be able to talk to each other. Heroku has the same answer, which is to say that communication does not occur internally and that if you want to link apps together, use DNS.

And...

> what I am looking for here is a way to communicate with an "instance" of an application.

I agree with @carmstrong that making individual application instances directly addressable is territory we ought not head into, but I think that saying "communication does not occur internally" might be a little heavy-handed.

If I am understanding the OP's objections correctly, it's really about the unnecessary (albeit brief) loop out to the open internet and back when two apps in the same cluster need to communicate.  It is a concern I have had in the past as well.  Donning my own security hat, if sensitive traffic is routed over an open network unnecessarily, it makes me uneasy.

There's a middle ground...

I guess if "communication does not occur internally" means inter-app communication ought not occur _within_ a Deis cluster itself, I can buy that, both on the grounds of security _and_ a firm belief that we'd be doing ourselves a disservice by cutting the load balancer out of the equation.  But IMO there is definitely a use case here for "internal communication" if the definition of "internal" means strictly within the _network or VPC_ in which the Deis cluster resides.  All such traffic should _still_ be load-balanced, obviously.

I have some ideas kicking around (mostly involving a second, internal load balancer), but no complete implementation in mind yet, but I'd like to add my voice in saying the OP's concern is legitimate.

**Comment by seeksong** [comment]
The problem I am facing is how to monitor an application instance. Say I have an app and I put up 10 instances and the app acts funky and I need to know which instance(s) causes it. Deis provides functions to monitor a container (CPU, Memory usage etc), but how can I monitor from a application level?

**Comment by bacongobbler** [comment]
If you want to perform monitoring from an application level, there are agents which you can install in your container such as [datadog](http://www.datadoghq.com/) or [new relic](http://newrelic.com/). That way you can filter the data you want specifically for your app. I'm not sure this is something we can easily solve in Deis as every app will want to monitor different things :)

**Comment by seeksong** [comment]
I could be wrong but I think those agents all depend on application to PUSH information to them. Are there any pulling solutions? Your statement is exactly correctly - because every app will want to monitor different things, would it be better for Deis to open the communication channel and let the app to decide what to monitor?

**Comment by carmstrong** [comment]
> would it be better for Deis to open the communication channel and let the app to decide what to monitor?

@jchauncey is working on defining a metrics API and collection agent for Deis over in #3699. We'd love to have your feedback there!

**Comment by bacongobbler** [comment]
> Are there any pulling solutions?

[statsd](https://github.com/etsy/statsd) and [collectd](https://collectd.org/) are the only two I'm aware of, though I'm sure there are others. :)

**Comment by seeksong** [comment]
--statsd and collectd are the only two I'm aware of, though I'm sure there are others. :)

Don't think so. If a monitoring program cannot talk to individual agent, how can it "poll" information from them?

**Comment by eroubal** [comment]
I agree with @seeksong that deis should allow middleware to communicate with each other.  We use Spring Cloud and Eureka is key for middleware service registry.  Decomposing the complexity of the backend for externally accessible web interfaces is pretty much the way everybody is going... and forcing a suite of backend services to the 'outside' world is not going to help your adoption.  Imagine all the extra work there to lock down security.  This is the reason my company eliminated Cloud Foundry, Heroku and other PaaS ... complex service to service communication hacks, everything exposed to the world, and forced server side load balancing.  

Microservices for backend and middleware is the way everybody is going.  Odd to me that you all are not considering this.

**Comment by bacongobbler** [comment]
We are considering this. This is actually globbed up into #4173, where apps deployed in the same team (synonymous with orgs in Cloud Foundry land) will be discoverable and can communicate with each other. This is one of the main drivers for why we are moving over to kubernetes.

**Comment by bacongobbler** [comment]
As seen with https://deis.com/blog/2016/private-applications-on-deis-workflow/ this is now possible in v2. Closing!
