### ISSUE TITLE
ApplyLayer exit status 1 unexpected EOF

### ISSUE THREAD

**Issue by aledbf** [deis/deis#2723]
Using deis pull I saw this error.

I think that is related to https://github.com/docker/docker/issues/9327

deis 1.1.0

**Comment by Vish0007** [comment]
I am getting the "ApplyLayer exit status 1 unexpected EOF" how did you solve this?
I guess missing layer should throw http 404 error but not EOF. EOF might also come from invalid/partial write of an image layer.

**Comment by msendetsky** [comment]
This does not seem to be related with missing layers or something. Retrying was able to pull the same layer from the same repository with no problems.

First attempt:
> [10.0.104.20] 80ef4c5db056: Pulling fs layer
> [10.0.104.20] 80ef4c5db056: Error downloading dependent layers
> [10.0.104.20] eb8d8bd629e3: Error pulling image (1447) from docker.xxx.com/app, endpoint: https://docker.xxx.com/v1/, ApplyLayer exit status 1 unexpected EOF

Next attempt in a minute:
> [10.0.104.20] 80ef4c5db056: Pulling metadata
> [10.0.104.20] 80ef4c5db056: Pulling fs layer
> [10.0.104.20] 80ef4c5db056: Download complete
> [10.0.104.20] eb8d8bd629e3: Pulling metadata
> [10.0.104.20] eb8d8bd629e3: Pulling fs layer
> [10.0.104.20] eb8d8bd629e3: Download complete
> [10.0.104.20] eb8d8bd629e3: Download complete

This seems to be another concurrency issue. In the process above, two images are downloaded in two threads and they have some shared layers. Notice that layer `eb8d8bd629e3` is mentioned as completed twice.

**Comment by msendetsky** [comment]
@aledbf thoughts?

**Comment by aledbf** [comment]
@msendetsky are you using deis pull?
If that's the case the "error" is produced because in deis pull one of the steps creates a new tag in the local deis registry while it downloads the image from the remote repository. The EOF error will disappear after a couple of retries (when the download of the image finishes)

**Comment by msendetsky** [comment]
@aledbf oh man, sorry :) i thought it's a docker issue discussion.

**Comment by aledbf** [comment]
@msendetsky np :) . Docker 1.5 returns a better error message.

**Comment by Vish0007** [comment]
@msendetsky @aledbf 
i am facing this issue just with docker (1.3.3) [not deis].
Its pretty consistently happening here.
Couple of reties solves the issue but I cannot got with this solution.
Any ideas why this error is happening?

**Comment by carmstrong** [comment]
> i am facing this issue just with docker (1.3.3) [not deis].

The bug @aledbf originally linked to, https://github.com/docker/docker/issues/9327, points to https://github.com/docker/docker/commit/001ac15b54686761960352103ebf4ff2c6e1d803 which is in Docker 1.4.0. Deis master will soon use a CoreOS version with Docker 1.4.0, so hopefully this will be alleviated then.

**Comment by msendetsky** [comment]
@carmstrong i originally caught this in docker 1.5.0. so it's definitely not solved.

**Comment by msendetsky** [comment]
@carmstrong @Vish0007 actually, funny thing is that i was on docker 1.4.1 originally and never got that issue. as soon as i switched to 1.5.0, i got the bug in one of the very first pulls.

**Comment by carmstrong** [comment]
Reopening if this is indeed still an issue.

@aledbf Is this potentially solved with the docker-registry retry logic introduced in https://github.com/deis/docker-registry/pull/10 and landing in Deis v1.4.0?

**Comment by aledbf** [comment]
@carmstrong after docker 1.4.x (I'm in 1.5 now) and the retry logic I don't see the EOF error.

**Comment by carmstrong** [comment]
> after docker 1.4.x (I'm in 1.5 now) and the retry logic I don't see the EOF error.

@msendetsky to confirm - you only see this with `deis pull`? If so, I'm fairly confident this issue will go away with Deis v1.4.0, which will release next Tuesday.

**Comment by msendetsky** [comment]
@carmstrong not exactly. i see this in docker. i've learnt this is deis issue tracker, but @Vish0007 mentioned they see this in docker (not deis), so i just replied.

also, i replied to you, because you mentioned that "Deis master will soon use a CoreOS version with Docker 1.4.0, so hopefully this will be alleviated then.". my point was that it probably won't be.

**Comment by carmstrong** [comment]
> also, i replied to you, because you mentioned that "Deis master will soon use a CoreOS version with Docker 1.4.0, so hopefully this will be alleviated then.". my point was that it probably won't be.

Right, I'm with you. But we made some changes in https://github.com/deis/docker-registry/pull/10 to our in-house Docker registry which adds retry logic to hopefully work around this when pulling from our registry.

**Comment by msendetsky** [comment]
@carmstrong damn, i'm inattentive for the second time in this thread :D i mistakenly read the link as "docker/docker-registry#10", although docker registry is not even in docker repository...

**Comment by carmstrong** [comment]
> i'm inattentive for the second time in this thread :D

![flo](http://memeorama.com/wp-content/uploads/2012/02/happens-to-me-all-the-time-gif.gif)

Let's revisit this after v1.4.0 lands - if it's an issue, we can open it.

**Comment by monaka** [comment]
Unfortunately, I got similar issue. I tried 10 times and reproduced 100% on my environment.

```
$ deisctl config platform get version
v1.12.3
```
```
 $ cat /etc/lsb-release 
DISTRIB_ID=CoreOS
DISTRIB_RELEASE=835.13.0
DISTRIB_CODENAME="Red Dog"
DISTRIB_DESCRIPTION="CoreOS 835.13.0"
```
```
$ docker --version
Docker version 1.8.3, build cedd534-dirty
```

```
-- Logs begin at Thu 2016-03-17 22:50:47 UTC. --
Mar 30 05:29:19 deisNode1 sh[47715]: [2016-03-30 05:29:19 +0000] [11741] [WARNING] worker aborted
Mar 30 05:29:21 deisNode1 sh[47715]: [2016-03-30 05:29:21 +0000] [23467] [INFO] Booting worker with pid: 23467
Mar 30 05:31:57 deisNode1 sh[47715]: ERROR Internal Server Error: /v1/hooks/build
Mar 30 05:31:57 deisNode1 sh[47715]: Traceback (most recent call last):
Mar 30 05:31:57 deisNode1 sh[47715]: File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
Mar 30 05:31:57 deisNode1 sh[47715]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
Mar 30 05:31:57 deisNode1 sh[47715]: File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
Mar 30 05:31:57 deisNode1 sh[47715]: return view_func(*args, **kwargs)
Mar 30 05:31:57 deisNode1 sh[47715]: File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view
Mar 30 05:31:57 deisNode1 sh[47715]: return self.dispatch(request, *args, **kwargs)
Mar 30 05:31:57 deisNode1 sh[47715]: File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
Mar 30 05:31:57 deisNode1 sh[47715]: response = self.handle_exception(exc)
Mar 30 05:31:57 deisNode1 sh[47715]: File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
Mar 30 05:31:57 deisNode1 sh[47715]: response = handler(request, *args, **kwargs)
Mar 30 05:31:57 deisNode1 sh[47715]: File "/app/api/views.py", line 393, in create
Mar 30 05:31:57 deisNode1 sh[47715]: super(BuildHookViewSet, self).create(request, *args, **kwargs)
Mar 30 05:31:57 deisNode1 sh[47715]: File "/app/api/views.py", line 117, in create
Mar 30 05:31:57 deisNode1 sh[47715]: return super(BaseDeisViewSet, self).create(request, *args, **kwargs)
Mar 30 05:31:57 deisNode1 sh[47715]: File "/usr/lib/python2.7/site-packages/rest_framework/mixins.py", line 21, in create
Mar 30 05:31:57 deisNode1 sh[47715]: self.perform_create(serializer)
Mar 30 05:31:57 deisNode1 sh[47715]: File "/app/api/viewsets.py", line 21, in perform_create
Mar 30 05:31:57 deisNode1 sh[47715]: self.post_save(obj)
Mar 30 05:31:57 deisNode1 sh[47715]: File "/app/api/views.py", line 400, in post_save
Mar 30 05:31:57 deisNode1 sh[47715]: build.create(self.user)
Mar 30 05:31:57 deisNode1 sh[47715]: File "/app/api/models.py", line 760, in create
Mar 30 05:31:57 deisNode1 sh[47715]: source_version=source_version)
Mar 30 05:31:57 deisNode1 sh[47715]: File "/app/api/models.py", line 873, in new
Mar 30 05:31:57 deisNode1 sh[47715]: release.publish()
Mar 30 05:31:57 deisNode1 sh[47715]: File "/app/api/models.py", line 889, in publish
Mar 30 05:31:57 deisNode1 sh[47715]: publish_release(source_image, self.config.values, self.image, deis_registry)
Mar 30 05:31:57 deisNode1 sh[47715]: File "/app/registry/dockerclient.py", line 120, in publish_release
Mar 30 05:31:57 deisNode1 sh[47715]: return client.publish_release(source, config, target, deis_registry)
Mar 30 05:31:57 deisNode1 sh[47715]: File "/app/registry/dockerclient.py", line 42, in publish_release
Mar 30 05:31:57 deisNode1 sh[47715]: self.pull(repo, src_tag)
Mar 30 05:31:57 deisNode1 sh[47715]: File "/app/registry/dockerclient.py", line 74, in pull
Mar 30 05:31:57 deisNode1 sh[47715]: log_output(stream)
Mar 30 05:31:57 deisNode1 sh[47715]: File "/app/registry/dockerclient.py", line 108, in log_output
Mar 30 05:31:57 deisNode1 sh[47715]: raise docker.errors.DockerException(chunk)
Mar 30 05:31:57 deisNode1 sh[47715]: DockerException: {"errorDetail":{"message":"Error pulling image (git-7c9e02ee) from 10.0.0.5:5000/www, ApplyLayer exit status 1 stdout:  stderr: unexpected EOF"},"error":"Error pulling image (git-7c9e02ee) from 10.0.0.5:5000/www, ApplyLayer exit status 1 stdout:  stderr: unexpected EOF"}
Mar 30 05:31:58 deisNode1 sh[47715]: 10.244.22.1 "POST /v1/hooks/build HTTP/1.1" 500 27 "deis-builder"
```

**Comment by monaka** [comment]
I run the cluster on Azure A1 instances. It's possible this issue was caused by poor environment or heavy load.

**Comment by carmstrong** [comment]
> It's possible this issue was caused by poor environment or heavy load.

Very likely, given such a small instance size and instance type. We strongly recommend DS2 instances with premium storage. See http://docs.deis.io/en/latest/installing_deis/azure/

**Comment by monaka** [comment]
I upgraded instances to A2 and the issue was not reproduced.

> We strongly recommend DS2 instances with premium storage. 

Yes. I got this issue by my mis-configuration. And I don't want run Deis on such poor instances.
But I guess this issue can be reproduced by heavy load situations even if I use DS2.
So the tips is "Add/Upgrade servers when this issue was reproduced."
