### ISSUE TITLE
Fail to create a zone with the gcloud utility

### ISSUE THREAD

**Issue by oren** [deis/deis#2726]
I follow http://docs.deis.io/en/latest/installing_deis/gce/#configure-dns and the command for creating a zone fails:  

    gcloud dns managed-zone create --dns_name latechnews.com. --description "Example Deis cluster domain name" deis

Output:
```
Creating {'dnsName': 'latechnews.com.', 'name': 'deis', 'description':
 'Example Deis cluster domain name'} in graphite-disk-780

Do you want to continue (Y/n)?  y

ERROR: (gcloud.dns.managed-zone.create) ResponseError: status=403, code=Forbidden, reason(s)=accessNotConfigured
message=Access Not Configured. The API is not enabled for your project, or there is a per-IP or per-Referer restriction configured on your API key and the request does not match these restrictions. Please use the Google Developers Console to update your configuration.
```

Is there something I need to configure on https://console.developers.google.com ?
What about my domain provider (godaddy, in my case), is there any configuration I should do there?

Thanks!

**Comment by carmstrong** [comment]
@oren Did you figure out this issue? If there's something misleading or incomplete in the GCE documentation, we'd love to see a correction! That documentation is maintained by our community.

**Comment by oren** [comment]
unfortunately i was not able to resolve this issue and I no longer have a GCE account.
