### ISSUE TITLE
deisctl fails to initialize ssh client with Vagrant 1.7

### ISSUE THREAD

**Issue by mgartner** [deis/deis#2727]
I'm going through the latest Getting Started guide on deis.io for setting up a local vagrant cluster on OS X with v1.1.0, and when I got to [Installing the Deis Platform](http://docs.deis.io/en/latest/installing_deis/install-platform/) any deisctl commands fail with:

```
Error: failed initializing SSH client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

I've made sure to run add the vagrant ssh key with `ssh-add ~/.vagrant.d/insecure_private_key`.

I've looked through a couple of other issues where this error was mentioned, but nothing noted in those issues seems to help. Any help is appreciated.

**Comment by Morriz** [comment]
Hi, I just installed 1.6.1 of deis(ctl) and have vagrant 1.7.1, and got local3 running:
```
vagrant status
Current machine states:

deis-01                   running (vmware_fusion)
deis-02                   running (vmware_fusion)
deis-03                   running (vmware_fusion)
```
but can't ssh into deis-1:
```
The machine with the name 'deis-1' was not found configured for
this Vagrant environment.
```

So I was wondering where to find this newly generated vagrant key...could you help me?
