### ISSUE TITLE
docs: add documentation around debugging applications

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#2736]
see bugs like #2705. We should document the general workflow for debugging and reporting an application failing to start.

**Comment by adamkdean** [comment]
I know it took a while but thanks for getting round to this @bacongobbler 😂 good work. Hope everything at Deis is going ok!

**Comment by bacongobbler** [comment]
No worries, and yes everything is awesome here :)

Thank you for submitting the issue!
