### ISSUE TITLE
Dead control plane units not rescheduled

### ISSUE THREAD

**Issue by jorihardman** [deis/deis#2737]
Here's the timeline on how I noticed the issue and returned the platform to a working state. The cluster is on digitalocean with platform version 1.0.2.

1. Pushed to one of my apps last night successfully.
1. This morning, push denied due to connection issue. ```fleetctl list-units``` showed that several units were dead on one particular host. Dead units were builder, database, logspout, publisher, registry, daeomn, gateway, and store-metadata. Controller and store were still active. App units had been redistributed.
1. Controller and builder were not redistributed. Client commands all returned 500 errors.
1. Ran ```journalctl -b -u etcd``` and last messages were a full day prior to the incident. Message was:
    ```
    Dec 10 01:26:30 deis-3 etcd[641]: [etcd] Dec 10 01:26:30.495 WARNING   | [ss] Error: nil response 
    ```
    This nil response message was there hundreds of times.
1. Rebooted the host. For some reason, the image reverted back to coreos 409.0, meaning it didn't have insecure-registry support causing docker to fail. Unmasked the update-engine and ran update. Rebooted host again.
1. Host came up fine and restarted all units. Platform returned to working state.

**Comment by carmstrong** [comment]
Perhaps #2851 would help with this.

**Comment by carmstrong** [comment]
@jorihardman This is pretty clearly an etcd issue likely exacerbated by Digital Ocean's behavior of reverting to the original CoreOS installation any time the instance is rebooted. Reverting to a CoreOS version that old is almost certainly going to introduce issues into your cluster. Unfortunately, I'm not sure the best way to work around this, other than to provide documentation that DigitalOcean has this behavior.

**Comment by carmstrong** [comment]
Filed #3149 to document this behavior.
