### ISSUE TITLE
Add deisctl recipe to Homebrew

### ISSUE THREAD

**Issue by mboersma** [deis/deis#2739]
It would be very convenient to get the latest `deisctl` client via `brew install deisctl` on a Mac. See [Homebrew](https://github.com/Homebrew/homebrew).

See #2710, ping @andyshinn --I separated it into two issues.

**Comment by andyshinn** [comment]
This has been merged in finally. Though, it probably needs a version bump. Maybe a new issue for bumping Homebrew revs with `easy fix` tag.

**Comment by mboersma** [comment]
So `brew install deis deisctl` actually works now. @andyshinn you rock!

But we need to figure out some way to keep the Homebrew packages up-to-date, because Deis has significant releases every month. If we can't keep things reasonably fresh, we should drop the packages entirely. (BDFL said so a while back.)

**Comment by andyshinn** [comment]
It usually ends up being a crowdsourced kind of thing. I opened another PR to update the version: https://github.com/Homebrew/homebrew/pull/38435.

**Comment by carmstrong** [comment]
> I opened another PR to update the version

Deis 1.5.0 should land today, so we may just want to bump to that.

**Comment by andyshinn** [comment]
![orly](https://cloud.githubusercontent.com/assets/315485/7026014/ce3dc248-dd0c-11e4-920e-0e24d0891b33.jpg)

OK, i'll just close that one and get ready to open a PR for 1.5.0 then.

**Comment by bacongobbler** [comment]
original issue has been resolved. We also try to maintain them ourselves as per the release checklist: http://docs.deis.io/en/latest/contributing/releases/

**Comment by carmstrong** [comment]
> We also try to maintain them ourselves as per the release checklist: http://docs.deis.io/en/latest/contributing/releases/

I think we decided this isn't something we want to maintain as an officially-supported installation mechanism, as the burden of keeping them up-to-date is substantial (and when they're merged upstream is out of our hands).

If someone from the community chooses to own these we certainly won't stop them, but out-of-date clients will probably do more harm than good.

**Comment by alias1** [comment]
For the sake of bumping the brew version when you guys do releases, I would find it super useful as an osx user.
