### ISSUE TITLE
Deis integration with Kubernetes

### ISSUE THREAD

**Issue by Fandekasp** [deis/deis#2744]
I have a kubernetes cluster of CoreOS nodes running on AWS, and I'm now looking into how to setup a Continuous Integration & Continuous Deployment workflow on top of it.
The goal is to do something like that:

1. git commit on specific branch (or git tag)
2. unit tests checked
3. docker build & push to docker private registry node
4. kubectl create "test" pod
5. integration/acceptance tests checked
6. kubecfg rollingUpdate "production" replicationController

@gabrtv wrote on [StackOverflow](http://stackoverflow.com/questions/27242980/whats-the-difference-between-kubernetes-flynn-deis#comment43038384_27280549):

     Deis has already begun prototyping container orchestration via Kubernetes

Can you share some resources for me to test that prototype and help with its integration?

@kernel8liang you apparently tried to run Deis with Kubernetes in #1741, but it seems that you used fleet directly, bypassing kubernetes, hence they shouldn't be registered as pods in kubernetes. Did you make any more progress?

----

Here is how I believe the integration should be done (without reading the Deis doc yet):

* Create a specific aws autoscaling group, where all kubernetes minions/nodes will have deis autoinstalled with cloud-config
* Start all deis services with systemd on CoreOS or as fleetctl units
* Replace fleetctl calls into kubectl calls in Deis
* OR keep the fleetctl calls, but follow them with kube-register calls to notify kubernetes about those new pods.

**Comment by arkadijs** [comment]
I'm running Deis and Kubernetes on top of CoreOS with Flannel. Deis is well suited for user-facing web applications, and Kubernets is well suited for providing service layer: database, cache, etc. I wrote a simple utility - [kubevars](https://github.com/arkadijs/kubevars), to export Kubernets service's environment variables and plugged it into app's systemd unit template: https://github.com/arkadijs/deis/commit/bf4629133c80a0184a5612c6a055090a709f4e0f

The presence of Kubernetes can be tested by checking `/registry` branch in Etcd.

Let me know in case you want to include this functionality, I can polish it based on your suggestions.

**Comment by pires** [comment]
+1

**Comment by tslater** [comment]
+1

**Comment by idosh** [comment]
+1

**Comment by smothiki** [comment]
closing in favor of issue [3850](https://github.com/deis/deis/issues/3850)
