### ISSUE TITLE
After machine reboot (or Docker daemon restart), deis-store-monitors get stuck in `/usr/bin/ceph mon getmap -o /etc/ceph/monmap`

### ISSUE THREAD

**Issue by jimmychu0807** [deis/deis#2745]
Hi, 

I am running Deis v1.0.1 on a three-node cluster. After rebooted the cluster, I couldn't restart the deis platform successfully. `journalctl` on deis-store-monitors, all 3 monitors output log of the following:

```console
Dec 14 16:38:44 deis-1 sh[933]: 2014-12-14 08:38:44.265419 7f5cec71f700  0 -- :/1000021 >> 10.132.183.191:6789/0 pipe(0x7f5ce40296a0 sd=4 :0 s=1 pgs=0 cs=0 l=1 
c=0x7f5ce4029930).fault
Dec 14 16:38:44 deis-1 sh[933]: 2014-12-14 08:38:44.265419 7f5cec71f700  0 -- :/1000021 >> 10.132.183.192:6789/0 pipe(0x7f5ce40296a0 sd=4 :0 s=1 pgs=0 cs=0 l=1 
c=0x7f5ce4029930).fault
Dec 14 16:38:50 deis-1 sh[933]: 2014-12-14 08:38:50.267398 7f5cec71f700  0 -- :/1000021 >> 10.132.183.190:6789/0 pipe(0x7f5cd40030e0 sd=4 :0 s=1 pgs=0 cs=0 l=1 
c=0x7f5cd4003370).fault
...
```

I am able to run fleetctl list-machines (so etcd sync'ed), and able to ping the private IP address after `nse` into the store-volume docker container. 

What should be my next step in troubleshooting the ceph problem? Thanks.

**Comment by aledbf** [comment]
@carmstrong I can confirm that this is solved in docker 1.4.1 (CoreOS >= 547.0.0)

**Comment by mcallaway** [comment]
This bug still happens in deis 1.13 on CoreOS 899.

    core@ptero-production-deis-20160705-0 ~ $ deisctl --version
    1.13.0
    core@ptero-production-deis-20160705-0 ~ $ grep VERSION= /etc/os-release
    VERSION=899.13.0
    core@ptero-production-deis-20160705-0 ~ $ nse deis-store-admin
    root@be57ce4f63b5:/app# ceph -s
    2016-10-12 13:24:16.480389 7fbadd7fa700  0 -- :/548357443 >> 192.168.201.41:6789/0 pipe(0x7fbae0064010 sd=4 :0 s=1 pgs=0 cs=0 l=1 c=0x7fbae005c6f0).fault
    2016-10-12 13:24:16.480389 7fbadd7fa700  0 -- :/548357443 >> 192.168.201.41:6789/0 pipe(0x7fbae0064010 sd=4 :0 s=1 pgs=0 cs=0 l=1 c=0x7fbae005c6f0).fault

**Comment by bacongobbler** [comment]
Ceph faults usually mean your cluster lost quorum and will probably need to intervene to recover. Have you gone through the debugging Ceph doc? http://docs.deis.io/en/latest/troubleshooting_deis/troubleshooting-store/
