### ISSUE TITLE
Don't store app state in the database - query it fresh on a `deis ps`

### ISSUE THREAD

**Issue by mgartner** [deis/deis#2766]
When I released a bad version of an app that was crashing, I noticed that `deis ps` was reporting the containers were up when `fleetctl list-units` was showing that they were dead. Ideally `deis ps` would show me that something was wrong.

```
$ deis ps
=== lob-images Processes

--- cmd: 
cmd.1 up (v21)
cmd.2 up (v21)
```

```
$ fleetctl list-units
UNIT					MACHINE			ACTIVE		SUB
...
lob-images_v21.cmd.1.service		7af5ddc0.../10.21.1.111	inactive	dead
lob-images_v21.cmd.2.service		e00d7927.../10.21.2.134	inactive	dead
```

**Comment by mgartner** [comment]
It might be nice to also see the hosts that each container is running on  from `deis ps` - which should be possible with this change.

**Comment by aledbf** [comment]
+1 to get the state from fleet
