### ISSUE TITLE
[WIP] - Deis-Skydns - an Opera in 3 acts

### ISSUE THREAD

**Issue by PierreKircher** [deis/deis#2767]
Usecase: 

Internal service discovery via DNS .. avoid latency / bandwidth usage via utilizing solid/proven technologies for internal communications on private interface ( without the need to go throw the router )

after chatting with gabrtv regarding that big pr we decided to split it of to essentially 3 parts
and get it merged 1 after a other .

steps in sequential order: 

- [x] #2772 - Supply Unit-file for SkyDns + changes in deisctl to bring skydns up as part of the platform 
- [ ] change publisher to publish apps for internal dns ( soa / µ-services) 
- [ ] change boot-stripts of internal components to register them self with skydns inside etcd

any ideas / critics are highly welcome

**Comment by carmstrong** [comment]
Closing in favor of #3072.
