### ISSUE TITLE
How to setup a complete web server box with deis

### ISSUE THREAD

**Issue by phuongnd08** [deis/deis#2773]
I want to setup the server box with a number of containers like this on deis:

1. postgres container
2. redis container
3. web containers

web container will be published for external access
redis container is only accessible from web container, not the external
postgres container is only accessible from web container, not the external.

redis and postgres need to have its data volume. In the future I want to run multiple redis container (w/ sentinels) that together form a high availability redis cluster, as well as postgres.

I gone through deis documentation but I can't make up how to achieve this with deis.

Would you please give some advice?

**Comment by bacongobbler** [comment]
I believe I've answered your question, so I'll go ahead and close this issue. If you want to discuss this further, the mailing list (as I've mentioned above) is a great place to ask these questions as there are more eyes watching it. Thanks!
