### ISSUE TITLE
ceph-osd and ceph-mon take high disk usage all the time

### ISSUE THREAD

**Issue by phuonglm** [deis/deis#2807]
After install deis 1.1.1 with coreos 494.5.0 on 3 bare-metal machine, every going fine for first day and after that ceph keep writing to 3 nodes all the time, keep disk busy and cluster performance going down ( although no task or job running at all ), is it normal behavior of ceph? Any suggestion to reduce disk usage by Ceph or improve this.

I attached the atop of one node for reference.
![root node1 - terminal_003](https://cloud.githubusercontent.com/assets/646429/5560877/ccb3fa64-8de3-11e4-87d5-5acabd7c5d55.png)

**Comment by carmstrong** [comment]
@phuonglm This definitely shouldn't be happening, and I'm not aware of anyone else reporting this.

Is this the same device that etcd writes to? etcd writes pretty consistently. I'd also try writing to the ceph-users mailing list: http://ceph.com/resources/mailing-list-irc/

Those folks are running Ceph on bare metal more than our users are, and may have some insights.

**Comment by carmstrong** [comment]
@phuonglm I'm going to close these - I suspect this has to do with the underlying platform moreso than Deis.

**Comment by phuonglm** [comment]
Thank @carmstrong, i'll definitely check new version to re-verify. And yes, the bare metal run on one 7200RPM disk.
