### ISSUE TITLE
Apps should be published with an descriptive hostname

### ISSUE THREAD

**Issue by Blystad** [deis/deis#2835]
Hello,

I'm currently testing out New Relic for monitoring applications we have running on Deis, and all the instances (JVMs) show up with names like this: `1ecbec0cb893`, since that is the Docker hostname.

What I would rather prefer, is a hostname like`my-application.cmd.1.deis.example.com` or  `my-application.cmd.1`, since this would make looking up the actual instance in New Relic easier.

I think the solution would be to use Dockers `--hostname=` parameter in `docker run` ( https://docs.docker.com/articles/networking/#dns ).

>`-h HOSTNAME` or `--hostname=HOSTNAME` — sets the hostname by which the container knows itself. This is written into `/etc/hostname`, into `/etc/hosts` as the name of the container's host-facing IP address, and is the name that `/bin/bash` inside the container will display inside its prompt. But the hostname is not easy to see from outside the container. It will not appear in docker ps nor in the `/etc/hosts` file of any other container.

Any thoughts?

**Comment by aledbf** [comment]
@Blystad this was discarded in #2428 (and others) because is not a thing that every deis user wants
For now the solution is use a custom controller image adding `-h %H` to the container template.
This is what I use https://github.com/soficom/deis/blob/cuscom_1.1.0/controller/scheduler/fleet.py#L295

**Comment by aledbf** [comment]
@Blystad I forgot to clarify that `%H` will use the node hostname.
If you use the application name as hostname that means that each app will count as 1 server, i.e. 1 server license in newrelic terms, so if you have 30 apps that will require a plan for 30 servers. But using `%H` in a 3 node cluster only uses 3 "servers" and you will see the apps as a group in each server

**Comment by Blystad** [comment]
I see...I would like to avoid having to maintain my own local version of the controller if possible, but my boss won't pay for 30 instances of New Relic...that's for sure :)

Based on what I could find, it seems that the conflict is between wether one should use `%H` or the application name `dancing-django_v2`

> Our preference would be to have application containers have a hostname that is the unit name, but this isn't valid due to the underscores (i.e. `dancing-django_v2`). (Ref: #2428)

#254 forces DNS compatible application names, so what if one simply strips out the version part (or replaces the underscore with a dot), then it would be a compatible DNS name.

If we also add an option, like:
`/deis/controller/exportHostname` - [`application` / `server`]
where application would set `hostname=dancing-django.v2.web.1` and `server`  `hostname=ip-10-0-2-5.eu-west-1.compute.internal`

Wouldn't that satisfy both parties by giving them the choice?

**Comment by aledbf** [comment]
> /deis/controller/exportHostname - [application / server]

Just add the actual behavior as default: `/deis/controller/exportHostname` : `[random|application|server]`

:+1:
