### ISSUE TITLE
feat(router): Add HTTP to HTTPs redirect

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#2838]
This was attempted in #2635 and again in #2782, but the implementation in those PRs doesn't seem to work. This is a desired feature, so I wanted to track it separately so it wasn't lost.

I've attempted this myself, but it appears the `server` blocks keep conflicting in the nginx template. After several failed attempts at this, I resorted to [asking StackOverflow](http://stackoverflow.com/a/27711250/644992) for help. An answer seems worthy of attempting, but I haven't had the time to get back to this, and likely will be working on other things for the next Deis release.

I wanted to document this so hopefully someone else can pick it up.

**Comment by aledbf** [comment]
@carmstrong just add 
`server_name ~^{{ Base $service.Key }}\.(?<domain>.+)${{ range $app_domains := $domains }}{{ if eq (Base $service.Key) (Base $app_domains.Key) }} {{ $app_domains.Value }}{{ end }}{{ end }};`

after https://github.com/deis/deis/blob/b37c5757a7417b992b5574bba62b11ae3ebaf4bc/router/templates/nginx.conf#L150

Without a server_name that server block never is going to be reached.
Adding the mentioned line will create N server block (one per app) that redirects to https.

**Comment by azurewraith** [comment]
has anyone tested @aledbf's suggestion yet?

**Comment by carmstrong** [comment]
> has anyone tested @aledbf's suggestion yet?

I haven't had a chance to (and won't get to it for v1.3.0), but I'd love it if someone could!

**Comment by ngbinh** [comment]
+1

**Comment by ngbinh** [comment]
One popular use case for http -> https redirection is to use AWS Load Balancer to terminate SSL connections. So nginx router does NOT need to handle SSL but https -> http redirection is still necessary.

**Comment by azurewraith** [comment]
I'm guessing this issue is obsoleted by #3075 now?
