### ISSUE TITLE
REST errors question

### ISSUE THREAD

**Issue by aledbf** [deis/deis#2843]
I'm using the deis API and I see one "annoying" thing: the error formats.
In case of an error (not relevant) the error returns a JSON object where the key changes and the value can be an array.
It's possible to define 1 format and wrap the errors just indicating the first error? Like:
```
{
  "message": "invalid credentials"
}
```

**Some errors responses from the API:**
```
{"id":["App with this Id already exists."]}
{"username":["User with this Username already exists."]}
```

**Comment by bacongobbler** [comment]
I think this has to do with how we're handling these errors through Django Rest Framework's Serializer class. How this format works is the following:

```
{"<invalid_field_in_api_request>": [<reasons why>]}
```

Which makes sense, considering that multiple validation rules could be broken with a specific app ID (for example, using capital letters and making the name shorter than 4 characters in length).

The first step to standardizing these errors would be to identify all of the error cases and document them. If we document and throw these into the [API documentation](http://docs.deis.io/en/latest/reference/api-v1.1/) then we can take a closer look at all of the responses and standardize them accordingly.
