### ISSUE TITLE
"deis rollback" works for an unauthorized user

### ISSUE THREAD

**Issue by mboersma** [deis/deis#2846]
Testing interactively with current master and attempting to verify #2826 shows there is more work to do.

```console
$ deis register http://deis.deis.rocks
username: badguy
...
$ deis rollback
Rolling back one release... done, v5
$ deis info
404 NOT FOUND
Detail:
Not found
```

**Comment by bacongobbler** [comment]
This is odd, because the unit tests cover this very issue: https://github.com/deis/deis/blob/master/controller/api/tests/test_release.py#L269-L272

I'll play around with master and see where I get with it.
