### ISSUE TITLE
Unable to add a node to a cluster or restart an existing one (GCE)

### ISSUE THREAD

**Issue by nagliyvred** [deis/deis#2848]
Hi guys! Have been playing with deis for a few days now and it looks pretty awesome - great job :)
However, I came across a weird issue, first when trying to add a new node to my GCE cluster (was just following the documentation here http://docs.deis.io/en/latest/managing_deis/add_remove_host/)
I am not 100% if it is deis issue or coreos or, in fact, docker. But that's what happens:

Most of the deis services fail to start

```
core5 core # systemctl list-units --all | grep deis
  var-lib-deis-store.mount                                                                    loaded    active     mounted            /var/lib/deis/store
  deis-logspout.service                                                                       loaded    activating start-pre    start deis-logspout
  deis-publisher.service                                                                      loaded    activating auto-restart       deis-publisher
  deis-store-daemon.service                                                                   loaded    activating auto-restart       deis-store-daemon
  deis-store-metadata.service                                                                 loaded    activating start-pre    start deis-store-metadata
  deis-store-monitor.service                                                                  loaded    activating auto-restart       deis-store-monitor
  deis-store-volume.service                                                                   loaded    active     running            deis-store-volume
```
By using journalctl one can notice that docker is having some problem with /var/lib/docker/repositories-btrfs:
```
[error] server.go:110 HTTP Error: statusCode=500 open /var/lib/docker/repositories-btrfs: no such file or directory
```
(see: https://gist.github.com/nagliyvred/7bd8f7c4f97855392686 )

Then, I realised that if you shut the docker daemon down it does not start up again:
```
core5 core # systemctl stop docker
Job for docker.service canceled.
core5 core # systemctl start docker
Job for docker.service failed. See 'systemctl status docker.service' and 'journalctl -xn' for details.
core5 core # systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib64/systemd/system/docker.service; disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─50-insecure-registry.conf
   Active: failed (Result: start-limit) since Tue 2015-01-06 06:11:49 UTC; 10s ago
     Docs: http://docs.docker.io
  Process: 9776 ExecStart=/usr/bin/docker --daemon --storage-driver=btrfs --host=fd:// $DOCKER_OPTS (code=exited, status=1/FAILURE)
  Process: 9773 ExecStartPre=/bin/mount --make-rprivate / (code=exited, status=0/SUCCESS)
 Main PID: 9776 (code=exited, status=1/FAILURE)

Jan 06 06:11:49 core5.c.trunkplatform.internal systemd[1]: Failed to start Docker Application Container Engine.
Jan 06 06:11:50 core5.c.trunkplatform.internal systemd[1]: Starting Docker Application Container Engine...
Jan 06 06:11:50 core5.c.trunkplatform.internal systemd[1]: docker.service start request repeated too quickly, refusing to start.
Jan 06 06:11:50 core5.c.trunkplatform.internal systemd[1]: Failed to start Docker Application Container Engine.
Jan 06 06:11:55 core5.c.trunkplatform.internal systemd[1]: Starting Docker Application Container Engine...
Jan 06 06:11:55 core5.c.trunkplatform.internal systemd[1]: docker.service start request repeated too quickly, refusing to start.
Jan 06 06:11:55 core5.c.trunkplatform.internal systemd[1]: Failed to start Docker Application Container Engine.
Jan 06 06:11:55 core5.c.trunkplatform.internal systemd[1]: Starting Docker Application Container Engine...
Jan 06 06:11:55 core5.c.trunkplatform.internal systemd[1]: docker.service start request repeated too quickly, refusing to start.
Jan 06 06:11:55 core5.c.trunkplatform.internal systemd[1]: Failed to start Docker Application Container Engine.
```

Which I was able to narrow down to...
```
core5 core # /usr/bin/docker -d -D
2015/01/06 06:12:56 docker daemon: 1.3.3 5dc1c5a; execdriver: native; graphdriver: 
[5f9f93a9] +job serveapi(unix:///var/run/docker.sock)
2015/01/06 06:12:56 invalid argument
core5 core # 
```

So, it looks like docker does not like something. I was able to find something similar issue in docker https://github.com/docker/docker/issues/7585 that is somehow related to mounted partitions, however that didn't help me much as I am not mounting anything myself.

One more thing: if I restart the node - docker daemon does start on boot. The other concerning thing I figured out was - if I take an existing node in the cluster and restart it - I get exactly the same problem. So I am not only not able to spin up additional nodes, but I am also potentially capable of losing the working ones...

After some more playing around with it I found a **workaround** (hope that might shed some light?).

I modified the docker.service file to specify the working directory different from /var/lib/docker (the best one I was able to find ended up being /var/lib/docker/docker, so that it shares the same partition)
and re-enabled the docker service. After that all the other services managed to get successfully restarted within minutes. ...

Environment:
```
Platform: Google Compute Engine
CoreOS: coreos-stable-494-5-0-v20141215
Docker: version 1.3.3, build 5dc1c5a
Deis version: 21fcbc62abea2b4a4e2cf51646e7784d33735ca1
```

**Comment by nagliyvred** [comment]
To clarify my workaround, I ended up modifying docker.service like this (with -g in it):
```
....
ExecStart=/usr/bin/docker -g '/var/lib/docker/docker' --daemon --storage-driver=btrfs --host=fd:// $DOCKER_OPTS
....
```

**Comment by carmstrong** [comment]
Can you `df -h`? I'm honestly not sure what's going on here - it sounds like you may have hit a btrfs issue. You can also `sudo btrfs fi show` to see if btrfs thinks the volume is full. See https://coreos.com/docs/cluster-management/debugging/btrfs-troubleshooting/ for more info.

**Comment by carmstrong** [comment]
Also, did you provision your GCE machines with our GCE guide/provision scripts? We use a separate volume for `/var/lib/docker` which qualifies as a best practice. The cloud-config specific to GCE is here: https://github.com/deis/deis/blob/f3489c3f430f7cd41965f723ee7a51a05a77a75a/contrib/gce/gce-user-data-template

**Comment by nagliyvred** [comment]
Yep, I did use the scripts from the guide (with the only exception being a region/zone). Will post df -h in a bit

**Comment by carmstrong** [comment]
@nagliyvred Did you ever get to the bottom of this? We have several users on GCE and this doesn't seem to be a common problem, thankfully.

**Comment by nagliyvred** [comment]
@carmstrong Nope, unfortunately the issue still persists :( 
Sorry for silence. This is my df -h output:
```
~ $ df -h
Filesystem                                                   Size  Used Avail Use% Mounted on
rootfs                                                       6.7G  152M  6.4G   3% /
devtmpfs                                                     3.7G     0  3.7G   0% /dev
tmpfs                                                        3.7G     0  3.7G   0% /dev/shm
tmpfs                                                        3.7G  260K  3.7G   1% /run
tmpfs                                                        3.7G     0  3.7G   0% /sys/fs/cgroup
/dev/sda9                                                    6.7G  152M  6.4G   3% /
/dev/sda3                                                   1008M  289M  668M  31% /usr
tmpfs                                                        3.7G     0  3.7G   0% /media
tmpfs                                                        3.7G     0  3.7G   0% /tmp
/dev/sda6                                                    108M   38M   62M  38% /usr/share/oem
/dev/sda9                                                     32G   17M   30G   1% /var/lib/docker/btrfs
10.240.127.116,10.240.167.206,10.240.140.185,10.240.77.90:/   64G   44G   21G  68% /var/lib/deis/store
/dev/sdb                                                      32G   17M   30G   1% /var/lib/docker
```

Also, from `sudo btrfs fi show` I am getting this:
```
devid    1 size 32.00GiB used 2.04GiB path /dev/sdb
```
so, I don't belive btrfs thinks it is full ...

**Comment by wenzowski** [comment]
I can replicate this across all zones.

The issue only presents when adding a host to an existing cluster; that is when `coreos.etcd.discovery` in `cloud-config` is not set to a new url.

on a heathy host...
```
$ ls -lh /var/lib/docker
total 16K
drwx------ 1 root root   20 Mar  9 21:16 btrfs
drwx------ 1 root root 1.9K Mar 13 02:12 containers
drwx------ 1 root root   12 Mar  9 21:16 execdriver
drwx------ 1 root root  23K Mar 13 01:36 graph
drwx------ 1 root root   32 Mar  9 21:16 init
-rw-r--r-- 1 root root  11K Mar 13 02:12 linkgraph.db
-rw------- 1 root root 2.1K Mar 13 02:12 repositories-btrfs
drwx------ 1 root root    0 Mar  9 21:16 tmp
drwx------ 1 root root   26 Mar  9 21:16 trust
drwx------ 1 root root    6 Mar  9 21:16 vfs
drwx------ 1 root root  768 Mar 13 01:36 volumes
```

on a newly-added unhealthy host
```
$ ls -lh /var/lib/docker
total 0
drwx------ 1 root root  20 Mar 13 02:26 btrfs
drwx------ 1 root root 136 Mar 13 02:26 graph
```

the drive is actually writable
```
$ echo 'foo' | sudo tee ./bar
foo
$ cat ./bar
foo
```

My guess is that some critical unit is missing a
```
Requires=var-lib-docker.mount
```
and it's doing its thing before `/usr/sbin/wipefs` is called...and that it's not showing up elsewhere because whatever it is doesn't normally get called until after `deisctl install platform`

**Comment by wenzowski** [comment]
ref docker/docker#9997

**Comment by wenzowski** [comment]
progress in isolating:

on a heathy node
```
$ df | grep /var/lib/docker
/dev/sdb                                  268435456 10175792 256790736   4% /var/lib/docker
/dev/sdb                                  268435456 10175792 256790736   4% /var/lib/docker/btrfs
```

on an unhealthy node
```
$ df | grep /var/lib/docker
/dev/sda9                                                393216000   708364 390497108   1% /var/lib/docker/btrfs
/dev/sdb                                                 393216000   708364 390497108   1% /var/lib/docker
```

**Comment by wenzowski** [comment]
Completely independent of disk type, be it SCSI, NVMe, or Persistent SSD pool, `var-lib-docker-btrfs.mount` is reattaching the boot disk at `/var/lib/docker/btrfs`. Dropping back a coreos version doesn't help either. The btrfs version is the same on healthy and unhealthy hosts.

The `var-lib-docker-btrfs.mount` declaration doesn't appear anywhere on the filesystem, and masking the offending service does absolutely nothing: `systemctl status var-lib-docker-btrfs.mount` goes ahead and runs it anyway, helpfully reporting back `active (masked)`.

8 hours in, this is a rabbit hole I can't afford. Hope someone else has better luck.

**Comment by wenzowski** [comment]
this is definitely intermittent

**Comment by carmstrong** [comment]
Is there a chance you guys could test a fresh reprovision and see if you're still seeing this? Not sure what else to go on, or why this is isolated to GCE :(

**Comment by wenzowski** [comment]
I would wager this is isolated to GCE due to how they're attaching disks. This issue is definitely isolated to GCE and frequent enough to provide incentive to move elsewhere.

They have a great offering for other purposes but their CoreOS image appears to contain a lot of their own code. Perhaps someone with a commercial support plan can investigate this issue with them?

**Comment by nagliyvred** [comment]
Hi guys,
Thanks for the follow up. Unfortunately, we ended up moving away from both
deis and GCE, so I can't really give it another try now. Thanks a lot for
the effort to investigate this though.
