### ISSUE TITLE
Chinese Version of Deis Documentation

### ISSUE THREAD

**Issue by xishuixixia** [deis/deis#2852]
We have translated Deis documentation to [Chinese](http://dockerone.com/article/124).We all love Deis and hope Deis has a good development. we are committed to the promotion of Deis in China.

**Comment by mboersma** [comment]
@xishuixixia that is wonderful! Thank you and your team very much for doing this work.

In the long run, it might also be possible to include Chinese or other language translations directly with the original English documentation at http://docs.deis.io/. There are several ways to do this, explained at http://sphinx-doc.org/intl.html. It would be a lot of work--I'm just mentioning it in case we decide to make I18N a priority, or in case some community members are motivated to do so.

Thanks again!

**Comment by xishuixixia** [comment]
@mboersma Thanks for your quick response.I have read the i18n doc,and here is our [translate around project](https://github.com/xishuixixia/Deis-Documentation).DockerOne is a docker community from China and our community members love deis.So I look forward to add the [Chinese documention](http://dockerone.com/article/124) at http://docs.deis.io.

Thank you for approving our  job.

**Comment by xishuixixia** [comment]
@mboersma

**Comment by mboersma** [comment]
For now, let's add a link to this unofficial Chinese documentation in our FAQ.

**Comment by xishuixixia** [comment]
Cool.Thanks.

**Comment by CloudSide** [comment]
Full version: http://deis.heheapp.com/
