### ISSUE TITLE
"deis destroy" doesn't show the 40x error for an unauthorized user

### ISSUE THREAD

**Issue by mboersma** [deis/deis#2855]
While an unauthorized user cannot actually destroy the app, the `deis` CLI doesn't report that fact currently. Cosmetic, but annoying:
```console
$ deis destroy -a wilder-zeppelin

 !    WARNING: Potentially Destructive Action
 !    This command will destroy the application: wilder-zeppelin
 !    To proceed, type "wilder-zeppelin" or re-run this command with --confirm=wilder-zeppelin

> wilder-zeppelin
Destroying wilder-zeppelin... 
done in 0s
```

**Comment by bacongobbler** [comment]
The problem child:

https://github.com/deis/deis/blob/b8058d8950a5883414f7d5cfd37f9109b9bff0a8/client/deis.py#L542

Really this should be returning a 403 (see discussion in #2856), but we should remove this check.

Marking as easy-fix.
