### ISSUE TITLE
Deis Registration failed

### ISSUE THREAD

**Issue by prateek121** [deis/deis#2860]
Registration failed: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>

Latest Version of deis

**Comment by mboersma** [comment]
Registration requires using the `deis` CLI, but this looks like output from a web browser. Could you include the logs of the command-line session where you tried to register, and the output of `deisctl journal controller`?

**Comment by prateek121** [comment]
No thats of cli actually 
and the o/p of deisctl journal controller
-- Logs begin at Mon 2015-01-05 02:53:22 UTC. --
Jan 05 10:01:00 ip-10-0-10-72 sh[19789]: [2015-01-05 10:01:00 +0000] [229] [INFO] Using worker: sync
Jan 05 10:01:00 ip-10-0-10-72 sh[19789]: [2015-01-05 10:01:00 +0000] [234] [INFO] Booting worker with pid: 234
Jan 05 10:01:00 ip-10-0-10-72 sh[19789]: [2015-01-05 10:01:00 +0000] [235] [INFO] Booting worker with pid: 235
Jan 05 10:01:00 ip-10-0-10-72 sh[19789]: [2015-01-05 10:01:00 +0000] [236] [INFO] Booting worker with pid: 236
Jan 05 10:01:00 ip-10-0-10-72 sh[19789]: [2015-01-05 10:01:00 +0000] [237] [INFO] Booting worker with pid: 237
Jan 05 10:01:00 ip-10-0-10-72 sh[19789]: [2015-01-05 10:01:00 +0000] [238] [INFO] Booting worker with pid: 238
Jan 05 10:01:00 ip-10-0-10-72 sh[19789]: [2015-01-05 10:01:00 +0000] [239] [INFO] Booting worker with pid: 239
Jan 05 10:01:00 ip-10-0-10-72 sh[19789]: [2015-01-05 10:01:00 +0000] [240] [INFO] Booting worker with pid: 240
Jan 05 10:01:00 ip-10-0-10-72 sh[19789]: [2015-01-05 10:01:00 +0000] [244] [INFO] Booting worker with pid: 244
Jan 05 13:36:15 ip-10-0-10-72 sh[19789]: 2015-01-05T13:36:15Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 05 17:12:27 ip-10-0-10-72 sh[19789]: 2015-01-05T17:12:27Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 05 20:48:33 ip-10-0-10-72 sh[19789]: 2015-01-05T20:48:33Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 06 00:24:40 ip-10-0-10-72 sh[19789]: 2015-01-06T00:24:40Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 06 04:00:52 ip-10-0-10-72 sh[19789]: 2015-01-06T04:00:52Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 06 07:37:03 ip-10-0-10-72 sh[19789]: 2015-01-06T07:37:03Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 06 11:13:15 ip-10-0-10-72 sh[19789]: 2015-01-06T11:13:15Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 06 11:13:20 ip-10-0-10-72 sh[19789]: 2015-01-06T11:13:20Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 06 14:49:26 ip-10-0-10-72 sh[19789]: 2015-01-06T14:49:26Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 06 14:49:31 ip-10-0-10-72 sh[19789]: 2015-01-06T14:49:31Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 06 18:25:37 ip-10-0-10-72 sh[19789]: 2015-01-06T18:25:37Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 06 18:25:42 ip-10-0-10-72 sh[19789]: 2015-01-06T18:25:42Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 06 22:01:54 ip-10-0-10-72 sh[19789]: 2015-01-06T22:01:54Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 06 22:01:59 ip-10-0-10-72 sh[19789]: 2015-01-06T22:01:59Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 07 01:38:05 ip-10-0-10-72 sh[19789]: 2015-01-07T01:38:05Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 07 01:38:10 ip-10-0-10-72 sh[19789]: 2015-01-07T01:38:10Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 07 05:14:17 ip-10-0-10-72 sh[19789]: 2015-01-07T05:14:17Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 07 05:14:22 ip-10-0-10-72 sh[19789]: 2015-01-07T05:14:22Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 07 06:51:37 ip-10-0-10-72 sh[19789]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Jan 07 08:50:29 ip-10-0-10-72 sh[19789]: 2015-01-07T08:50:29Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 07 08:50:34 ip-10-0-10-72 sh[19789]: 2015-01-07T08:50:34Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 07 12:26:45 ip-10-0-10-72 sh[19789]: 2015-01-07T12:26:45Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 07 16:02:56 ip-10-0-10-72 sh[19789]: 2015-01-07T16:02:56Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 07 16:03:01 ip-10-0-10-72 sh[19789]: 2015-01-07T16:03:01Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 07 19:39:08 ip-10-0-10-72 sh[19789]: 2015-01-07T19:39:08Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 07 19:39:13 ip-10-0-10-72 sh[19789]: 2015-01-07T19:39:13Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 07 23:15:19 ip-10-0-10-72 sh[19789]: 2015-01-07T23:15:19Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 07 23:15:24 ip-10-0-10-72 sh[19789]: 2015-01-07T23:15:24Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 08 02:51:35 ip-10-0-10-72 sh[19789]: 2015-01-08T02:51:35Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 08 06:27:47 ip-10-0-10-72 sh[19789]: 2015-01-08T06:27:47Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1
Jan 08 06:27:52 ip-10-0-10-72 sh[19789]: 2015-01-08T06:27:52Z ceee9b91fcde confd[222]: ERROR Config check failed: exit status 1

**Comment by prateek121** [comment]
Im using  AWS ELB domain directly 
aws register http://elbdomainname
then i get the registration failed from the cli

**Comment by mboersma** [comment]
`Error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]` probably indicates that all the nodes in the cluster are not successfully participating in the same `etcd` cluster. You should verify that first, because if `etcd` communication isn't solid, nothing is likely to work.

The second issue is that you must set up DNS properly in order to register with Deis. See http://docs.deis.io/en/latest/managing_deis/configure-dns/#configure-dns. There should be a wildcard CNAME record pointing to the ELB hostname (or A records, or Route53). Then you can register at the `deis` subdomain of that domain:
```console
$ deis register http://deis.my.domain
```
Without the `deis` prefix to the URL, Deis' routing mesh won't know where to send the request.

**Comment by carmstrong** [comment]
@prateek121 Closing this - Deis will most definitely not work when using the ELB hostname, as we required wildcard subdomain DNS records for application and controller traffic to work properly.

**Comment by prateek121** [comment]
Thanks 
@carmstrong  & @mboersma 
This was helpful and was working post creating deis.xx.elb.domain,.com.
