### ISSUE TITLE
surprising effect of changing from go-buildpack to Dockerfile

### ISSUE THREAD

**Issue by iansmith** [deis/deis#2861]
I was using the go buildpack and I added a Dockerfile to switch to using that style of build.  I did this in an existing project.

The surprising result is that my containers built fine but the container would not start,  No output from the logs at all.  I eventually found the problem when `deis run <start command>`  succeeded in starting the container with my program inside it but the "automatic" deployment did not.

It wasn't being started because the "dyno type" had gotten set to web because of the original go build pack and the Dockerfile expected a type of "cmd."  `deis ps:scale cmd=1` fixes the problem, but even a warning message might be helpful.

**Comment by bacongobbler** [comment]
We could solve this by migrating containers over to the new default process type once we detect this change. That way you won't get stuck on the wrong process type.

**Comment by carmstrong** [comment]
@iansmith Sorry you got tripped up on this - we discussed this in today's issue review and think that this is a pretty infrequent edge case, and logic required to fix this would be fragile and hard to test.

The solution here is probably just to document the workaround for this, or to recommend deploying a new application when moving from a Dockerfile to a `git push` workflow (or vice versa).
