### ISSUE TITLE
Waiting for ceph gateway

### ISSUE THREAD

**Issue by karlo57** [deis/deis#2878]
Hi, I encountered this error when starting `store-gateway`. It gets stuck in an infinite loop.

    deis-3 sh[5879]: Waiting for ceph gateway on 8888/tcp...
    deis-3 sh[5879]: curl: (56) Recv failure: Connection reset by peer

Any thoughts? Thanks!

**Comment by carmstrong** [comment]
@karlo57 This typically indicates that there is an issue somewhere else in your cluster. Can you post the output of `ceph -s` following the "Troubleshooting deis-store" instructions? http://docs.deis.io/en/latest/troubleshooting_deis/#a-deis-store-component-fails-to-start

**Comment by karlo57** [comment]
It returns this: 
    cluster 7137b101-b995-4db3-b863-f3c67f40f386
     health HEALTH_WARN 1007 pgs peering; 147 pgs stale; 1007 pgs stuck inactive; 147 pgs stuck stale; 1007 pgs stuck unclean; 4 requests are blocked > 32 sec; mds cluster is degraded
     monmap e6: 4 mons at {deis-1b=10.132.218.110:6789/0,deis-2=10.132.166.88:6789/0,deis-3=10.132.198.68:6789/0,deis-haproxy=10.132.218.107:6789/0}, election epoch 82, quorum 0,1,2,3 deis-2,deis-3,deis-haproxy,deis-1b
     mdsmap e70: 1/1/1 up {0=deis-2=up:replay}, 3 up:standby
     osdmap e348: 4 osds: 3 up, 3 in
      pgmap v563182: 1536 pgs, 12 pools, 11245 MB data, 7852 objects
            86305 MB used, 142 GB / 233 GB avail
                 147 stale+active+clean
                1007 peering
                 382 active+clean

**Comment by carmstrong** [comment]
@karlo57 Usually `deisctl restart store-daemon` will resolve this, although I'd like to get to the bottom of it.

**Comment by carmstrong** [comment]
@karlo57 Did you resolve this?

**Comment by karlo57** [comment]
Yes. Restarting `store-daemon` did the trick. Thank you.

**Comment by GabKlein** [comment]
Hi, I encountered this error when installing the cluster after update

**Comment by josh-padnick** [comment]
I received this after `vagrant halt` and then `vagrant up`.  I have not made any modifications to the cluster other than launching a couple of applications.  Doing `deisctl restart store-daemon` did fix it, though.

**Comment by josh-padnick** [comment]
Although the above issue was fixed, I then got stuck on the service `deis-builder.service`.

And the logs show...

```
Feb 16 22:51:39 deis-02 sh[13169]: 2015-02-16T22:51:39Z 3d42af786bed confd[2573]: ERROR Config check failed: exit status 1
Feb 16 22:51:39 deis-02 sh[13169]: 2015-02-16T22:51:39Z 3d42af786bed confd[2573]: ERROR Config check failed: exit status 1
Feb 16 22:51:39 deis-02 sh[13169]: builder: waiting for confd to write initial templates...
```

I was unable to fix this issue, so I'm going to either reboot all servers or destroy and re-create.

**Comment by carmstrong** [comment]
> I received this after vagrant halt and then vagrant up.

Typically, Vagrant is used for short-lived test clusters. I'm not surprised you ran into issues - actually, I'm surprised you didn't run into more! If all the machines in a cluster are stopped, it's not difficult to get into a state where etcd has lost quorum and cannot recover.

**Comment by josh-padnick** [comment]
@carmstrong Thanks for your reply, and that's good to know.  Initially, my thinking was that our devs would use a local Vagrant cluster of deis to do development, and then an Amazon-based cluster for prod and test.  In a dev environment, I expected the devs to `vagrant halt` and `vagrant up` all the time.

I've since discovered that deis Vagrant is more for testing while you configure a production cluster rather than a dev environment.  It's worth noting explicitly that boostrapping a new Vagrant-based cluster is about a 20 - 30 minute affair.  Might be something to mention in the docs.  If I have time I'll do a PR for them.

**Comment by carmstrong** [comment]
> I've since discovered that deis Vagrant is more for testing while you configure a production cluster rather than a dev environment. It's worth noting explicitly that boostrapping a new Vagrant-based cluster is about a 20 - 30 minute affair.

It should be about 10 minutes if you have the images locally. All of us on the Deis team build Deis in a local Vagrant environment, and we run a local Docker registry which contains all the freshly-baked Deis components. Pulling them from a local source is usually much faster than pulling them from Docker Hub. That's our development workflow, but we usually tear down at the end of the day (at least I do!).

**Comment by josh-padnick** [comment]
Ah, that is good to know.  Actually, the local registry idea may be good practice in general since you can cut down on so much download time.  Looking at the docs, I'm guessing you guys use the `make dev-registry` container to handle this?  Any issue with using application containers on this as well?

**Comment by carmstrong** [comment]
> I'm guessing you guys use the make dev-registry container to handle this?

Yep! 

> Any issue with using application containers on this as well?

Just to clarify - this is a local registry **in addition** to the `deis-registry` component that ships with Deis. So we run a stock Docker registry in a `boot2docker` VM on our Macs which we push to as we're developing. Then we tell Deis to pull from this registry when it deploys.

This can't replace the `deis-registry` component because that has some magic to support the `deis pull` workflow.

**Comment by zackp30** [comment]
I get close to this error, but instead it's "Empty reply from server". Exact quote:

```
curl: (52) Empty reply from server
```

**Comment by zackp30** [comment]
```
root@fedc53865bdb:/app# ceph -s
    cluster 5a8dacb0-f0d9-452d-ad19-040fe8ed03c6
     health HEALTH_WARN 168 pgs degraded; 152 pgs peering; 152 pgs stuck inactive; 320 pgs stuck unclean; 168 pgs undersized; recovery 16/24 objects degraded (66.667%)
     monmap e3: 3 mons at {deis0=192.168.122.150:6789/0,deis1=192.168.122.151:6789/0,deis2=192.168.122.152:6789/0}, election epoch 12, quorum 0,1,2 deis0,deis1,deis2
     mdsmap e12: 1/1/1 up {0=deis1=up:creating}, 2 up:standby
     osdmap e88: 3 osds: 3 up, 3 in
      pgmap v148: 320 pgs, 3 pools, 818 bytes data, 8 objects
            16750 MB used, 57508 MB / 77703 MB avail
            16/24 objects degraded (66.667%)
                 160 active+undersized+degraded
                  71 peering
                  81 creating+peering
                   8 active+replay+undersized+degraded
  client io 212 B/s wr, 0 op/s

```

**Comment by carmstrong** [comment]
@zackp30 Your cluster is in recovery - give it a few minutes. You can also `deisctl restart store-daemon` to poke things, although I suspect that by now it's recovered on its own.

**Comment by zackp30** [comment]
@carmstrong Sorry for the late reply, been busy lately. Anyway, it doesn't recover after a good 10 minutes, is this normal? The host and VMs have plenty of RAM free.

Also, is it normal that the curl error only appears on one host (deis2), while the others (deis0, deis1) have something like:

```
Apr 22 20:00:18 deis0 systemd[1]: Starting Generate /run/coreos/motd...
Apr 22 20:00:18 deis0 systemd[1]: Started Generate /run/coreos/motd.
Apr 22 20:00:20 deis0 sh[3715]: 2015-04-22 20:00:20.526698 7f891da18700  0 log_channel(cluster) log [INF] : pgmap v153: 512 pgs: 122 peering, 20 active+clean+replay, 306 creating+peering, 63 active+clean, 1 active+clean+scrubbing; 588 bytes data, 22057 MB used, 52201 MB / 77703 MB avail
Apr 22 20:00:24 deis0 sh[3715]: 2015-04-22 20:00:24.648281 7f891da18700  0 log_channel(cluster) log [INF] : pgmap v154: 512 pgs: 122 peering, 21 active+clean+replay, 302 creating+peering, 66 active+clean, 1 active+clean+scrubbing; 588 bytes data, 22057 MB used, 52201 MB / 77703 MB avail
Apr 22 20:00:28 deis0 sh[3715]: 2015-04-22 20:00:28.670856 7f891da18700  0 log_channel(cluster) log [INF] : pgmap v155: 512 pgs: 122 peering, 21 active+clean+replay, 302 creating+peering, 66 active+clean, 1 active+clean+scrubbing; 588 bytes data, 22058 MB used, 52200 MB / 77703 MB avail
Apr 22 20:00:32 deis0 sh[3715]: 2015-04-22 20:00:32.709203 7f891da18700  0 log_channel(cluster) log [INF] : pgmap v156: 512 pgs: 122 peering, 23 active+clean+replay, 298 creating+peering, 68 active+clean, 1 active+clean+scrubbing; 588 bytes data, 22058 MB used, 52200 MB / 77703 MB avail
Apr 22 20:00:36 deis0 sh[3715]: 2015-04-22 20:00:36.969326 7f891da18700  0 log_channel(cluster) log [INF] : pgmap v157: 512 pgs: 122 peering, 24 active+clean+replay, 287 creating+peering, 78 active+clean, 1 active+clean+scrubbing; 588 bytes data, 22059 MB used, 52199 MB / 77703 MB avail
Apr 22 20:00:39 deis0 sh[3715]: 2015-04-22 20:00:39.760002 7f891da18700  0 log_channel(cluster) log [INF] : pgmap v158: 512 pgs: 122 peering, 24 active+clean+replay, 287 creating+peering, 78 active+clean, 1 active+clean+scrubbing; 588 bytes data, 22059 MB used, 52199 MB / 77703 MB avail
Apr 22 20:00:43 deis0 fleetd-0.9.2[711]: ERROR engine.go:218: Engine leadership lost, renewal failed: timeout reached
Apr 22 20:00:43 deis0 fleetd-0.9.2[711]: INFO client.go:291: Failed getting response from http://localhost:4001/: cancelled
Apr 22 20:00:45 deis0 sh[3715]: 2015-04-22 20:00:45.821073 7f891da18700  0 log_channel(cluster) log [INF] : pgmap v159: 512 pgs: 122 peering, 24 active+clean+replay, 285 creating+peering, 80 active+clean, 1 active+clean+scrubbing; 588 bytes data, 22059 MB used, 52199 MB / 77703 MB avail
Apr 22 20:00:46 deis0 fleetd-0.9.2[711]: ERROR engine.go:218: Engine leadership lost, renewal failed: 101: Compare failed ([6199 != 6200]) [6200]
Apr 22 20:00:48 deis0 sh[3715]: 2015-04-22 20:00:48.295294 7f891da18700  0 log_channel(cluster) log [INF] : pgmap v160: 512 pgs: 122 peering, 24 active+clean+replay, 284 creating+peering, 81 active+clean, 1 active+clean+scrubbing; 588 bytes data, 22060 MB used, 52199 MB / 77703 MB avail
Apr 22 20:00:51 deis0 sh[3715]: 2015-04-22 20:00:51.638593 7f891da18700  0 log_channel(cluster) log [INF] : pgmap v161: 512 pgs: 122 peering, 25 active+clean+replay, 283 creating+peering, 81 active+clean, 1 active+clean+scrubbing; 588 bytes data, 22060 MB used, 52199 MB / 77703 MB avail
Apr 22 20:00:55 deis0 sh[3715]: 2015-04-22 20:00:55.997884 7f891da18700  0 log_channel(cluster) log [INF] : pgmap v162: 512 pgs: 122 peering, 25 active+clean+replay, 283 creating+peering, 81 active+clean, 1 active+clean+scrubbing; 588 bytes data, 22060 MB used, 52198 MB / 77703 MB avail
Apr 22 20:00:57 deis0 sh[3715]: 2015-04-22 20:00:57.989688 7f891da18700  0 log_channel(cluster) log [INF] : pgmap v163: 512 pgs: 122 peering, 26 active+clean+replay, 280 creating+peering, 83 active+clean, 1 active+clean+scrubbing; 588 bytes data, 22061 MB used, 52198 MB / 77703 MB avail
Apr 22 20:01:00 deis0 sh[3715]: 2015-04-22 20:01:00.499950 7f891da18700  0 log_channel(cluster) log [INF] : pgmap v164: 512 pgs: 122 peering, 27 active+clean+replay, 278 creating+peering, 84 active+clean, 1 active+clean+scrubbing; 588 bytes data, 22061 MB used, 52198 MB / 77703 MB avail
Apr 22 20:01:00 deis0 sh[3715]: 2015-04-22 20:01:00.559487 7f891ca16700  0 mon.deis0@0(leader).data_health(12) update_stats avail 67% total 25901 MB, used 7348 MB, avail 17404 MB
Apr 22 20:01:06 deis0 sh[3715]: 2015-04-22 20:01:06.400428 7f891da18700  0 log_channel(cluster) log [INF] : pgmap v165: 512 pgs: 122 peering, 27 active+clean+replay, 275 creating+peering, 87 active+clean, 1 active+clean+scrubbing; 588 bytes data, 22061 MB used, 52197 MB / 77703 MB avail
Apr 22 20:01:11 deis0 sh[3715]: 2015-04-22 20:01:11.084859 7f891da18700  0 log_channel(cluster) log [INF] : pgmap v166: 512 pgs: 122 peering, 27 active+clean+replay, 273 creating+peering, 89 active+clean, 1 active+clean+scrubbing; 588 bytes data, 22061 MB used, 52197 MB / 77703 MB avail
Apr 22 20:01:15 deis0 sh[3715]: 2015-04-22 20:01:15.281000 7f891da18700  0 log_channel(cluster) log [INF] : pgmap v167: 512 pgs: 122 peering, 28 active+clean+replay, 270 creating+peering, 91 active+clean, 1 active+clean+scrubbing; 588 bytes data, 22061 MB used, 52197 MB / 77703 MB avail
Apr 22 20:01:18 deis0 systemd[1]: Starting Generate /run/coreos/motd...
Apr 22 20:01:18 deis0 systemd[1]: Started Generate /run/coreos/motd.
Apr 22 20:01:19 deis0 sh[3715]: 2015-04-22 20:01:19.718328 7f891da18700  0 log_channel(cluster) log [INF] : pgmap v168: 512 pgs: 122 peering, 28 active+clean+replay, 267 creating+peering, 94 active+clean, 1 active+clean+scrubbing; 588 bytes data, 22061 MB used, 52197 MB / 77703 MB avail
```
(last line repeats a lot)

**Comment by zackp30** [comment]
In fact deis1 seems to be inactive after a while, with only:

```
Apr 22 20:02:37 deis1 fleetd-0.9.2[710]: INFO client.go:291: Failed getting response from http://localhost:4001/: cancelled 
```

repeated a lot in the logs.

**Comment by zackp30** [comment]
Host sysload is quite high (~4.0) as well.

**Comment by Xowap** [comment]
@zackp30 did you recover your cluster in the end? I'm basically going through the same issue and the output of `ceph -s` seems to be frozen

**Comment by carmstrong** [comment]
> I'm basically going through the same issue and the output of ceph -s seems to be frozen

That would typically indicate to me that the monitors the client is trying to connect to are down, or your cluster has lost quorum. Have you experienced host failure/replacement recently?

**Comment by wajatimur** [comment]
This might happen due to no empty space on main node server.
