### ISSUE TITLE
integration tests should share an app

### ISSUE THREAD

**Issue by mboersma** [deis/deis#2880]
Each integration test file is an island currently. In particular, we waste a lot of time creating, `git push`ing, and destroying apps, even when that functionality isn't specifically under test.

Perhaps with some ref-counting `setUp`/`tearDown` approach, we could have the tests all share a single Deis app that is only updated or destroyed when the test calls for that. This should speed up the integration tests significantly.

**Comment by bacongobbler** [comment]
:+1:

**Comment by mboersma** [comment]
This improvement isn't likely to happen for Deis v1 (although pull requests are of course welcome). Instead, see the current state-of-the-art testing for Deis v2 at https://github.com/deis/workflow-e2e/issues.
