### ISSUE TITLE
integration tests should be one go command line

### ISSUE THREAD

**Issue by mboersma** [deis/deis#2881]
The integration tests still have a brittle and non-idiomatic invocation that requires executing what is effectively a `setUp` func as a test, before running each other test file one-by-one. It works, so we hadn't gotten around to cleaning it up. but `godep go test -tags integration -v ./...` should work instead of the sequence of commands in the Makefile. This would also allow us to subset the tests with a regex.

**Comment by bacongobbler** [comment]
Would we be able to take advantage of https://github.com/deis/workflow-e2e for testing against v1?

**Comment by mboersma** [comment]
This improvement isn't likely to happen for Deis v1 (although pull requests are of course welcome). Instead, see the current state-of-the-art testing for Deis v2 at https://github.com/deis/workflow-e2e/issues.
