### ISSUE TITLE
integration tests should run against existing cluster

### ISSUE THREAD

**Issue by mboersma** [deis/deis#2882]
We assume a freshly-provisioned cluster so that our `test` user can be registered. If the username could be parameterized to point to an existing admin user and we can ensure the overall suite is non-destructive, it would be more practical for users and contributors to run the tests.

**Comment by Joshua-Anderson** [comment]
:+1:, but this should probably be part of a larger refactor allowing people to better run subsets of the integration tests.

We could use deisctl to execute a command on the controller container, allowing creation of an admin even if users already exist.

**Comment by mboersma** [comment]
This improvement isn't likely to happen for Deis v1 (although pull requests are of course welcome). Instead, see the current state-of-the-art testing for Deis v2 at https://github.com/deis/workflow-e2e/issues.
