### ISSUE TITLE
builder not displaying underlying error

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#2883]
When the builder fails, there is no error output. it just responds with `[remote rejected] master -> master (pre-receive hook declined)` with no reason for the error. This was introduced when we refactored the builder in #2335 to start refactoring the component over to Go.

This has been seen in previous issues such as #2876 and in #1748, so a fixup would help us better determine the underlying issue.

**Comment by carmstrong** [comment]
:100:

**Comment by bacongobbler** [comment]
This seems to have gone away -- if not, please open another issue on the specific error. :)
