### ISSUE TITLE
feat(client): Teach option flag for tracing requests

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#2884]
An option flag to trace requests would help users understand how communication between the client and the server occur, as well as help understand where a connection issue may occur, such as in a proxied environment or if DNS routes are set up incorrectly.

Common client option flags would be `--debug`, `--verbose` or `--trace`. I'm personally in favour of `--verbose` as typically you can tune the verbosity up or down based on your needs.

**Comment by Joshua-Anderson** [comment]
@bacongobbler What would this output look like?
Things that could be shown with `--verbose`:

- [ ] request URL
- [ ] request body
- [ ] response body/headers

**Comment by deis-admin** [comment]
This issue was moved to deis/workflow-cli#290
