### ISSUE TITLE
add deis CLI unit tests

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#2885]
related to #2392. Our CLI is being covered by our integration test suite, but there are some changes that would be more fitting as unit tests for a faster response time.

**Comment by bacongobbler** [comment]
I know that we've tossed around the idea of re-writing the client in Go to take advantage of static compilation as well as having the ability to share resources between the controller and the client, so it may be more worthwhile to punt on this one for a little bit.

**Comment by carmstrong** [comment]
Tracking in #3806
