### ISSUE TITLE
How to handle a host running out of space

### ISSUE THREAD

**Issue by ngpestelos** [deis/deis#2886]
(or can I move deis-registry's storage somewhere else?)

We had a recent problem where one of our nodes had its storage full and we could no longer deploy apps to our cluster. Is there a way to move the deis-registry to a different (cheaper) storage backend?

Also, I would like to ask advice on how to address the problem of a host running out of storage space. 

Thank you very much.

PS I'm following https://github.com/deis/deis/issues/1678, too.

**Comment by carmstrong** [comment]
If you're on EC2, Docker now uses a separate volume that is 100GB by default.

**Comment by ngpestelos** [comment]
Thanks, @carmstrong. We are using 80GB droplets now, but I think what we're looking for is a way to somehow attach storage not bounded to these droplets.

**Comment by carmstrong** [comment]
> we're looking for is a way to somehow attach storage not bounded to these droplets.

Yes, that would certainly be ideal. I'm surprised DO doesn't yet offer this...

**Comment by ngpestelos** [comment]
We just realized that a Deis host running on a droplet suffers from an additional burden, namely having its Docker daemon keep a local cache of images.

**Comment by ngpestelos** [comment]
@carmstrong Is it a good idea to symlink `/var/lib/docker` to a Ceph directory?

**Comment by carmstrong** [comment]
> Is it a good idea to symlink /var/lib/docker to a Ceph directory?

You mean a Ceph FS directory under `/var/lib/deis/store`? I don't think so - that would introduce a circular dependency, as Deis (and deis-store) is shipped as Docker containers, so the Ceph FS mount won't exist before Docker starts.

**Comment by carmstrong** [comment]
I think we'll cover this as part of #2559 - we should also discuss how to recover space that is no longer needed.
