### ISSUE TITLE
Proposal: allow custom log level in components

### ISSUE THREAD

**Issue by aledbf** [deis/deis#2889]
For example in `deis-controller` is not possible to customize the log level. 
In this case the value is hardcoded in `/bin/boot` as `--log-level info` and only using a custom image is possible to change this.

**Comment by bacongobbler** [comment]
Yes. In terms of the controller, it should be as simple as setting a LOG_LEVEL envvar which defaults to `info`, then referencing that in the boot script. That should be an easy task.

**Comment by bacongobbler** [comment]
work is ongoing with some of this stuff so let's open separate issues for each component. Thanks!
