### ISSUE TITLE
No Procfile -> obscure failure error

### ISSUE THREAD

**Issue by timfpark** [deis/deis#2897]
If you forget to include Procfile in a project that you are deploying with Deis, the deployment fails with a pretty obscure git push failure error:

-----> Launching... 
To ssh://git@deis.timdeis.com:2222/frontdoor-staging.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@deis.timdeis.com:2222/frontdoor-staging.git'

Expected: An error message that indicates that Deis expected to have a Procfile.

**Comment by bacongobbler** [comment]
related: #2883

**Comment by carmstrong** [comment]
@timfpark We're going to close this - not bubbling up errors to the user is a general case which we need to solve with #2883.
