### ISSUE TITLE
sync system clock before starting etcd/fleet

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#2900]
In our cloud-config, we sync the system clock using NTP: https://github.com/deis/deis/blob/dbd42a7352759f9ac98cbd59bf20ac757672bc6d/contrib/coreos/user-data.example#L46-L58

The cloudinit service parses and starts these services in-order, meaning that currently we're changing the system time after etcd has been started. I'm wondering if this could potentially result in etcd getting out of sync between nodes. We should move this service to start before etcd and fleet.

**Comment by bacongobbler** [comment]
is this resolved now?
