### ISSUE TITLE
Component status of "running" doesn't mean the component is functioning properly

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#2906]
This commonly trips people up, especially when investigating a component and seeing that its journal is filled with `ERROR Config check failed: exit status 1` even thought the service is technically "running".

#2701 may be an opportunity to fix things up - perhaps we should have the container exit whenever a config check fails, so it's apparent that it's not functioning properly?

**Comment by carmstrong** [comment]
@bacongobbler Think we can tackle this as part of the Go-init refactor?

**Comment by bacongobbler** [comment]
Hopefully, yes. With `/bin/boot` gone, PID 1 will be reserved for the actual process, which means that the process should die when these errors are coughed up.

**Comment by bacongobbler** [comment]
Alternatively, if we just wanted to fix the `ERROR Config check failed: exit status 1` error we can just tell confd to write to a PIDfile and capture/trap that as most other users do.

**Comment by bacongobbler** [comment]
This looks more like a limitation of a delayed boot with systemd. Refactoring to Go won't solve this problem. For example, given that the database has been running for a while then is rebooted and scheduled on a new host, bin/boot will still have to replay backups from ceph before it is actually booted. This will act the same as a boot script or as a Go static binary. :(

I'm looking into alternative approaches to resolve this issue, particularly around tweaking our systemd units.

**Comment by carmstrong** [comment]
> I'm looking into alternative approaches to resolve this issue, particularly around tweaking our systemd units.

Yeah, wondering if recovery could be in an ExecStartPost or something. Hmm....

**Comment by bacongobbler** [comment]
closing as irrelevant for [v2](https://deis.com/blog/2016/workflow-stable/). kubernetes reports the proper status of the container.
