### ISSUE TITLE
Failed to register user after recreating controller

### ISSUE THREAD

**Issue by bengrunfeld** [deis/deis#291]
```
(deis)ben$ deis > deis register http://<controller>
username: <usrName>
password: 
password (confirm): 
email: <usrEmail>
Registered <usrName>
Login failed
Login failed
```

**Comment by ianmiell** [comment]
deis register http://<domain>:8000

worked for me. Could this be made clearer in the docs? Quite a lot of time was wasted for me on this :)

ie a note similar to the Vagrant one here:

http://docs.deis.io/en/latest/using_deis/register-user/
