### ISSUE TITLE
Proposal: publish master version every night to docker

### ISSUE THREAD

**Issue by aledbf** [deis/deis#2913]
As an alternative for those users that need a fix and don't have the time/resources to build a custom image to fix some problem and is not required to wait until the next release. 
It makes sense?

**Comment by bacongobbler** [comment]
The problem with a `latest` tag for our case is determinism. We'd have users who would be running deis off master but we had no way of figuring out which commit they were using, so issues were hard to debug between versions.

There also poses the problem with how `latest` works if a node is rescheduled. Let's take a look at a sample scenario:

 - An administrator deploys deis tag `latest`, currently built from commit `1234567`
 - Fast forward 2 weeks
 - deis `latest` is now built from commit `2345678`
 - An administrator restarts the controller

At this point, fleet is called upon to schedule the controller. At this point, two things can happen:

### Fleet schedules to the same host

The docker daemon notices that tag `latest` exists on this machine, therefore we are using commit `1234567`

### Fleet schedules to a new host

The docker daemon notices that tag `latest` does not exist, therefore pulls down the controller from DockerHub. We are now using commit `2345678`.

We were running into this issue several times while debugging with users so we opted to go for a more explicit route.

**Comment by aledbf** [comment]
About the version thing: that already is solved in deis, just use `GIT_SHA` like in the apps.

To give one example of why this proposal today an user had a problem with the builder that was fixed yesterday (custom Procfile with worker as process). 
How a normal user can use that without compiling a custom image?

**Comment by Blystad** [comment]
What about publishing images with tags? e.g. `deis/builder:5a25b4c` or something like that.

**Comment by carmstrong** [comment]
> What about publishing images with git short SHA tags? e.g. deis/builder:5a25b4c or something like that.

I think that would work well (and is actually already our developer experience). I think the primary concern is with clutter on DockerHub. We don't want users seeing thousands of images that aren't published releases. I suppose we could automatically clean up the latest build each night, and only have one nighty.

**Comment by Blystad** [comment]
Fair enough, but that could cause issues if a component is moved between hosts. What about just creating an extra teams and have: `deis-nightly/builder:5a25b4c`?

**Comment by bacongobbler** [comment]
this is not something we want to do. However, we do publish the images from Jenkins to the `deisci` org, so we have a happy medium here :)
