### ISSUE TITLE
Cannot pull image - tag not found

### ISSUE THREAD

**Issue by daemonza** [deis/deis#2916]
Trying to deploy the go-example app from the documentation : http://docs.deis.io/en/latest/using_deis/using-docker-images/#using-docker-images

I am skipping the "Prepare the application" bit and trying to deploy the example docker app gabrtv/example-go

I run the following to do the deployment :

deis pull gabrtv/example-go:latest
Does not work I get the following :

"GET Image Error (404: {\"error\": \"Tag not found\"})"
Looking at https://registry.hub.docker.com/u/gabrtv/example-go/tags/manage/

The latest tag is there. Pulling it with

docker pull gabrtv/example-go
it get's pulled correctly. So I am not really sure what I am doing wrong.

Using the controller API with curl gives me the same result :

     curl -i -X POST \
     -H "Authorization: token $TOKEN" \
     -H "Content-Type: application/json" \
     -d '{"image":"gabrtv/example-go"}' \
     http://$IP:$PORT/v1/apps/dummyapp2/builds/

**Comment by glogiotatidis** [comment]
I'm having the same issue with a newly build v1.2.1 cluster

**Comment by glogiotatidis** [comment]
I set ELB Idle timeout to 1200 secs, still the same error.

**Comment by daemonza** [comment]
Tried the same as glogiotatidis against a 1.2.0 and I get the same problem : 

    deis create
    Creating application... done, created b

    deis pull mozillamffos/masterfirefoxos:latest
    Creating build... 503 SERVICE UNAVAILABLE
    GET Image Error (404: {"error": "Tag not found"})

    deis pull deis/example-go:latest
    Creating build... done, v3

    deis pull mozillamffos/masterfirefoxos:latest
    Creating build... done, v4

**Comment by glogiotatidis** [comment]
I rebuilt the cluster using Deis version 1.1.1, works OK now. I don't have the time to try with 1.2.0

**Comment by daemonza** [comment]
Tried just now on 1.1.1 and it's working for me as well. So I will just be sticking with 1.1.1 till this get fixed.

**Comment by carmstrong** [comment]
We saw this the other day, and some investigation suggested an OOM issue with the registry. The only relevant registry change for the 1.2.0 release was ef121c78d66ca8e326b8b0ed5aaa91c20cc3b976 -- if we can confirm that is indeed the cause, we can revert the change, but right now more testing is needed.

If anyone who runs into this could try disabling the LRU cache for their registry (entering deis-registry with `nse deis-registry`, editing '/docker-registry/config/config.yml` to remove the LRU cache config settings, and then running `/app/bin/reload`), that'd give us some confidence in the fix.

**Comment by bacongobbler** [comment]
> editing /docker-registry/config/config.yml to remove the LRU cache config settings, and then running /app/bin/reload), that'd give us some confidence in the fix.

You probably meant `/app/templates/config.yml` (the former is overwritten by the latter), but from my initial testing I could not figure out the problem.

**Comment by carmstrong** [comment]
> You probably meant /app/templates/config.yml

I did indeed.

**Comment by carmstrong** [comment]
This is likely reproducible more easily in clusters with some actual load - it's probably harder to detect in small test clusters with little use of registry/cache. Some confirmation from users would be helpful. 

If testing does indeed point to the LRU cache, we could make it configurable (i.e. disabled by default).

**Comment by rjocoleman** [comment]
I came up on this issue today too! 

I consistently had:
```
Creating build... 503 SERVICE UNAVAILABLE
GET Image Error (404: {"error": "Tag not found"})
```

I took @carmstrong's suggestion and disabled the LRU portion of registry's `/app/templates/config.yml`.
I now get a different error:

```
$ deis pull registry.example.com:5000/foo-app:v4
Creating build... 404 NOT FOUND
Detail:
Not found
```

Not sure if this helps!

**Comment by carmstrong** [comment]
> Update: I was in a different directory when I tried after the config change, once I change to the application's directory I get:

Interesting. I guess the LRU cache isn't the culprit :(

**Comment by carmstrong** [comment]
If folks can get any relevant logs from the deis-registry journal when this occurs, perhaps that will shed some light. `journalctl -fu deis-registry` on the host is the most complete method.

**Comment by mboersma** [comment]
I also tested today with LRU cache disabled but was running into what I think was the same error. So I concur at this point--it doesn't seem to be cache-related.

**Comment by rjocoleman** [comment]
https://gist.github.com/rjocoleman/974af9864da2a4b108ee

I've had to access the IP of the instance with the registry on directly as I couldnt go in via `registry.example.com:5000`.

I believe `/deis/registry/masterLock` is a red herring, it's part of the reason I'm trying to migrate my apps off this cluster..

**Comment by carmstrong** [comment]
@rjocoleman In your case, the spewing of etcd errors is more alarming than anything else: `501: All the given peers are not reachable`. I'm afraid if you've lost etcd quorum there's not much you can do there :(

**Comment by glogiotatidis** [comment]
@carmstrong I was able to reproduce this twice on fresh, just build, 1.2.1 deis clusters on EC2. It happened on the first project I created, I was pulling `mozillamffos/masterfirefoxos` with no tag, `latest` tag and with another tag. 

The cluster was build with the provided ec2 provision scripts with 3 instances, no extra customization, in an existing VPC. Connection to ELB was over https with idle timeout increased to 1200 secs.

I don't have this cluster anymore but hopefully with this information will help you reproduce the error.

**Comment by aledbf** [comment]
@bacongobbler @carmstrong I hit this problem very frequently.
The error occurs after the download of the image in `deis pull` when it tries to write in the deis registry.
It throws an error during the post and after that it tries to do a get on the new version of the deis application and that returns 404 (because the post failed and the new version doesn't exists).
```
Jan 31 16:32:10 nodo-2 sh[3656]: 10.0.0.15 - - [31/Jan/2015:16:32:10 +0000] "POST /v1/repositories/error-demo/tags HTTP/1.1" 500 129 "-" "python-requests/2.5.1 CPython/2.7.6 Linux/3.18.2"
Jan 31 16:32:10 nodo-2 sh[3656]: 10.0.0.15 - - [31/Jan/2015:16:32:10 +0000] "GET /v1/repositories/error-demo/tags/v63 HTTP/1.1" 404 26 "-" "docker/0.9.0"
```

**Comment by aledbf** [comment]
@bacongobbler @carmstrong I found the issue
```
api_error: HTTPSConnectionPool(host='registry.XXXXX.cl', port=5000): Read timed out.
```
This is a "random" behavior that I can reproduce every 20 `deis pull` executions. 
I see that error in debug mode in the registry.

**Comment by bacongobbler** [comment]
So in that case, it seems like it's a network issue between the remote registry and deis's registry. Is there anything else that shows up in the logs which would help us dive deeper into the issue? https://github.com/deis/deis/issues/2916#issuecomment-70724734 suggests that this could culminate as multiple separate issues, ending with the same result.

**Comment by aledbf** [comment]
@bacongobbler at the end the problem is in urllib (. The library do not supports automatic retries in post request (unless you use try/catch).
To increase the time between failures I modified the registry with this:
```
session = requests.Session()
adapter = requests.adapters.HTTPAdapter(
    pool_connections=1000,
    pool_maxsize=1000,
    max_retries=5,
    pool_block=False
)
session.mount('http://', adapter)
session.mount('https://', adapter)
requests = session
```

**Comment by glogiotatidis** [comment]
It there a workaround for this until it gets fixed? 

All the clusters I've build of Deis >1.1.1 do eventually get this error which renders them useless. I cannot pull image to any of the available apps. I'm running on AWS if that's of any help.

**Comment by carmstrong** [comment]
> To increase the time between failures I modified the registry with this:

@aledbf Can you PR that fix?

**Comment by aledbf** [comment]
@carmstrong sure.

**Comment by carmstrong** [comment]
Thanks for the bug reports, folks. We're hoping this is fixed with #3077, which will land in Deis v1.4.0.

**Comment by glogiotatidis** [comment]
@carmstrong thanks for the update! do you have eta for 1.4.0?

**Comment by carmstrong** [comment]
> do you have eta for 1.4.0?

Releases ship on the first Tuesday of the month, so 1.4.0 will ship on March 3rd.

**Comment by bacongobbler** [comment]
@glogiotatidis for future reference, here's the docs on our release schedule :)

http://docs.deis.io/en/latest/contributing/schedule/

**Comment by glogiotatidis** [comment]
Thanks folks

**Comment by fretboarder** [comment]
Upgraded to Deis 1.4.0 yesterday but deis pull is still failing. I tried pulling from the official docker hub as well as from a private registry.

**Comment by carmstrong** [comment]
@fretboarder Can you try disabling the cache? See https://github.com/deis/deis/issues/3116#issuecomment-77472068 and https://github.com/deis/deis/issues/2916#issuecomment-70724734

**Comment by carmstrong** [comment]
If anyone stumbles across this, please see #3218 - we're going to move the discussion over there.

**Comment by franzliedke** [comment]
We also have this problem, running Deis 1.9.0. Any clue what else could be the cause?

**Comment by bacongobbler** [comment]
@franzliedke perhaps you're hitting https://github.com/deis/deis/issues/4541?

**Comment by franzliedke** [comment]
Thanks for the pointer, that's probably it. Using Docker 1.8.2, too.
