### ISSUE TITLE
store: Consider running Ceph on ephemeral disk on EC2

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#2927]
As of #2850, we're preparing and mounting the fast ephemeral disk on EC2. I'd like to at least benchmark recovery times and see if moving the Ceph volume to the ephemeral disk results in a significant speedup.

**Comment by carmstrong** [comment]
It turns out we can't really do this, as we're using Docker volumes in the `deis-daemon` and `deis-monitor` containers, which use volumes from `deis-daemon-data` and `deis-monitor-data`, respectively.

We can't reasonably special-case the units for EC2. Removing the data containers entirely is probably preferred (opting instead to write to the host filesystem and just bind-mount the volume in the container), but [setting NOCOW](https://coreos.com/docs/cluster-management/debugging/btrfs-troubleshooting/#disable-copy-on-write) within the container is probably the most general way to improve performance, although I'd really like to see Ceph on a fast disk :(

/cc @gabrtv

**Comment by carmstrong** [comment]
On second thought,

**Comment by ianblenke** [comment]
Note: as the CloudFormation created AutoScalingGroup tends to terminate instances when any kernel panic makes an instance stop responding, I'm personally quite ok with ephemeral disk instead of having to provision SSD EBS.

Let me put together a PR for that, as this is how we use SSD in our CloudFormation:

        "BlockDeviceMappings" : [
          {
            "DeviceName" : { "Fn::FindInMap": [ "RootDevices", { "Ref": "EC2VirtualizationType" }, "Name" ] },
            "Ebs" : { "VolumeSize" : "1024", "VolumeType": "gp2" }
          }
        ]

**Comment by carmstrong** [comment]
> Let me put together a PR for that, as this is how we use SSD in our CloudFormation:

Is there an additional cost for `gp2`? I assume it's not the same as provisioned IOPs. I never knew there were different types for EBS volumes! http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html

**Comment by carmstrong** [comment]
I'm wondering if `gp2` isn't the default already? http://aws.amazon.com/ebs/pricing/
