### ISSUE TITLE
Custom HTTP request headers not being passed in to web app (v1.2.1)

### ISSUE THREAD

**Issue by synaptics** [deis/deis#2928]
Hi,

I have a Ruby/Sinatra web application that requires an api key to be passed in the headers, however when I make a request the headers are not being forwarded to the container.  Presumably this is something that's happening in the router, but I don't see why this should happen.  I've tried renaming the key from API_KEY to X-API_KEY and tried passing other key/values too but none of them ever appear in the request.  Can you let me know why this might be happening and if there's a way for me to fix this?

My platform (Deis v1.2.1) is hosted in AWS and otherwise seems to be functioning well.

Thanks,
John

**Comment by carmstrong** [comment]
I'm not sure if we're passing arbitrary headers by default, but the relevant nginx config is here: https://github.com/deis/deis/blob/c0c859095cc2d30a8612f32dfd3e24e4b1d2cc06/router/image/templates/nginx.conf#L142-L162

Maybe @aledbf has some insights?

**Comment by bacongobbler** [comment]
This may also be due to EC2's ELB settings. I'd look there as well, as some people have had issues in the past: http://serverfault.com/questions/499089/amazon-elb-not-passing-x-forwarded-for-to-iis

**Comment by aledbf** [comment]
@synaptics `API_KEY` or `X-API_KEY` are invalid header names (for nginx). Change to `API-KEY` or `X-API-KEY`. This is the [reason](http://wiki.nginx.org/Pitfalls#Missing_.28disappearing.29_HTTP_headers)

**Comment by synaptics** [comment]
Argh, sometimes these things are so simple! @aledbf was absolutely correct, the issue was with my naming - as soon as I changed the name to API-KEY it was passed through as HTTP_API_KEY as expected.

Thank you all for the prompt replies :)
