### ISSUE TITLE
builder: unable to restart builder if cedarish fails to download

### ISSUE THREAD

**Issue by ngpestelos** [deis/deis#2939]
I think this is also related to having a cached image with a broken cedarish.tar.gz.

https://github.com/deis/deis/blob/master/builder/image/bin/boot#L66

**Comment by bacongobbler** [comment]
I'm not quite sure how it fails to download. It's bundled in the builder image. Could you please post some logs so we can better understand the issue?

https://github.com/deis/deis/blob/master/builder/image/Dockerfile#L44-L47

**Comment by ngpestelos** [comment]
Hi, @bacongobbler. We're using our own cedarish and we've noticed when building deis-builder, while it was able to download the cedarish image archive successfully, `docker load` was unable to extract the cedarish image and failed silently.

I'll see if I could fix the problem by rebuilding our cedarish archive and rebuilding deis-builder.

**Comment by carmstrong** [comment]
> We're using our own cedarish and we've noticed when building deis-builder, while it was able to download the cedarish image archive successfully, docker load was unable to extract the cedarish image and failed silently.

@aledbf Didn't you also mention something similar for https://github.com/deis/deis/pull/2915#discussion_r23255260 ? @bacongobbler perhaps we're not using the cedarish we're loading as we thought...

**Comment by aledbf** [comment]
@carmstrong the issue in the comment is that the progrium in the tgz is not the same to progrium/cedarish:latest or any other published tag:
```
progrium/cedarish                    latest                  63dae3c23c6d        8 days ago          984.5 MB
progrium/cedarish                    cedar                   7cac39834d95        8 days ago          843.3 MB
progrium/cedarish                    cedar14                 e030ae9b1977        8 days ago          984.5 MB
progrium_cedarish.tar.gz             latest                  4b458f40de0a        6 weeks ago         995 MB
```

**Comment by bacongobbler** [comment]
woah... it shouldn't be loading as `progrium_cedarish.tar.gz`. I'll look into it.

**Comment by aledbf** [comment]
@bacongobbler I tagged 4b458f40de0a  as `progrium_cedarish.tar.gz`. The thing is that the image ids are different.

**Comment by bacongobbler** [comment]
Oh, okay. That's intentional. It's supposed to be an archived version of cedarish based on the date that it was archived, hence why https://github.com/deis/deis/blob/master/builder/image/Dockerfile#L47 has `2014_12_15` tagged onto the end here. That image is then [unpacked before we build deis/slugbuilder and deis/slugrunner](https://github.com/deis/deis/blob/master/builder/image/bin/boot#L62-L73) so that they are using the archived version of cedarish. That way, we don't have to rely so much on the network during builder boot time to build the images.

Anyways, let's keep that discussion over there since it's getting a little off topic from @ngpestelos's issue. :)

**Comment by bacongobbler** [comment]
@ngpestelos just as a note, we archive/ship the default tarball with `make -C builder cedarish/build` so you can take a look there for pointers :)

**Comment by ngpestelos** [comment]
Thanks, @bacongobbler :+1:

**Comment by ngpestelos** [comment]
We reviewed progrium's previous commits on cedarish and saw this: https://github.com/progrium/cedarish/commit/f7b704c825e7982ae8efef4193436c902477c650

Part of the refactoring effort changed the way the image is tagged, so our deis-builder is looking for a image tagged differently (i.e., `cedar14-build` vs `<our-fork>/cedarish`).
