### ISSUE TITLE
docs: Link to community members' custom components, tools, and Deis extensions

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#2952]
We should have a page somewhere in the documentation which point to useful tools folks from our community have developed. Off the top of my head:

* @aledbf's Ceph store-dashboard container: https://github.com/aledbf/deis/tree/optional_store_dashboard
* @ianblenke's various junk drawer tools: https://github.com/ianblenke/coreos-vagrant-kitchen-sink/tree/master/cloud-init

I think @lorieri has some good tools, too.

**Comment by lorieri** [comment]
They will be :)

https://github.com/lorieri/deis-dashboard
https://github.com/lorieri/deis-docs
https://github.com/lorieri/deis-netstat

**Comment by lorieri** [comment]
one more:
https://github.com/lorieri/deis-proxy (transparent proxy)
