### ISSUE TITLE
etcd: inconsistent value for /deis/registry/host

### ISSUE THREAD

**Issue by ngpestelos** [deis/deis#2958]
This happened today:

![screen shot 2015-01-26 at 10 21 52 am](https://cloud.githubusercontent.com/assets/5047/5894687/869cdb7a-a546-11e4-9f9f-2880ce97bba5.png)

**Comment by bacongobbler** [comment]
seems like that would occur if your registry were to go down, as the keys are removed once it's down. Can you confirm that?

**Comment by ngpestelos** [comment]
We restarted `deis-registry` an hour ago and it hasn't died since.

**Comment by ngpestelos** [comment]
In some cases, when I run `etcdctl get /deis/registry/host` it gives me different IP addresses (or `Key not found`).

**Comment by bacongobbler** [comment]
@ngpestelos I haven't been able to reproduce this issue. Are you running a vanilla Deis 1.3.1 cluster or is there something missing here?

**Comment by ngpestelos** [comment]
We saw this problem on Deis 1.3.1, but it hasn't appeared after we re-built our cluster (currently 1.4.0-dev).

**Comment by bacongobbler** [comment]
okay let's close this for now but if it pops up again let's re-open.
