### ISSUE TITLE
Push Failure after Restoration of from Backup

### ISSUE THREAD

**Issue by babarinde** [deis/deis#2960]
Hi,
I just did a restored my apps from a backup as described [here](http://docs.deis.io/en/latest/managing_deis/backing_up_data/) without any major issues except [this which was not backing up](http://docs.deis.io/en/latest/managing_deis/backing_up_data/#database-data).

When i try to push new changes  to my app , the git push fails (only via the buildpacks workflow , there are no problems with the Dockerfile workflow), but from my little observation, the push seems to be pushing the entire code base and not the latest changes, I thought this might be a good starting point.
Please see [gist](https://gist.github.com/babarinde/b9def784d4cbc576fcc0#file-gistfile1-txt)
Also I just need to be sure that when doing a recovery, does the new  deis platform version have to be the same version as the backed up one or is not necessary?

Thanks

**Comment by bacongobbler** [comment]
could you please post some logs from your push failure? We need to see something that resembles your issue so we can try to identify the problem. :)

**Comment by babarinde** [comment]
@bacongobbler 
https://gist.github.com/babarinde/b9def784d4cbc576fcc0#file-gistfile1-txt

**Comment by bacongobbler** [comment]
that looks like a buildpack issue. Could you please try `deis config:set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php` before pushing again and see if that fixes the issue? If so we may need to update buildpack-php.

**Comment by babarinde** [comment]
@bacongobbler setting the buildpack url make the push progress but its now stuck at launching...
pls see ```deisctl journal deis-builder``` [logs](https://gist.github.com/babarinde/b9def784d4cbc576fcc0#comment-1380545)

**Comment by bacongobbler** [comment]
Unfortunately the builder logs doesn't show anything useful. If you want to figure out why the application isn't launching, you'll have to take a look at the controller logs and `fleetctl list-units` to start digging into the root issue.

**Comment by babarinde** [comment]
@bacongobbler 
After a while at the launching stage it shows this:
-----> Launching... 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x40179b]

goroutine 1 [running]:
main.main()
remote: /home/jenkins/workspace/test-acceptance/src/github.com/deis/deis/builder/bin/publish-release-controller.go:80 +0xb5b
To ssh://git@deis.abacus.com.ng:2222/ischool.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@deis.abacus.com.ng:2222/ischool.git'

**Comment by bacongobbler** [comment]
that seems to be pointing to https://github.com/deis/deis/blob/master/builder/bin/publish-release-controller.go#L80 which means that the response timed out. That's a different issue, but basically the container failed to launch, which usually indicates an app issue. Can you please check the status of the app container via fleet?

**Comment by babarinde** [comment]
@bacongobbler , i tried pushing again and the app deployed successfully,
Just as I close this issue, does the php buildpack need updating via a PR or do we need to be setting the BUILDPACK_URL to the latest https://github.com/heroku/heroku-buildpack-php

**Comment by bacongobbler** [comment]
already done :) #2965

**Comment by babarinde** [comment]
ok, thanks
