### ISSUE TITLE
store: Consider using ceph-fuse rather than the kernel client for Ceph FS (deis-store-volume)

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#2970]
When Ceph fixes bugs in the Linux kernel driver for Ceph FS, we have to wait for the patch to get accepted, a kernel to be released, and then a CoreOS release with that kernel version to make it to the stable channel.

Instead of using the kernel client, we could instead use [ceph-fuse](http://ceph.com/docs/master/man/8/ceph-fuse/), which allows us to upgrade to the latest any time the container is rebuilt. If we go this route, we would certainly have to test upgrades from the kernel client filesystem to a FUSE filesystem.

I'm hoping this will prevent Ceph bugs from taking down instances (which @ianblenke has seen), but it definitely allows us to quickly adopt upstream fixes (specifically [this one](http://lists.ceph.com/pipermail/ceph-users-ceph.com/2015-January/045838.html) reported by @lorieri, which has a patch pending).

**Comment by carmstrong** [comment]
Also, it looks like the bug I linked to only exists in the kernel client, so we'd eliminate it by switching to ceph-fuse.

**Comment by ianblenke** [comment]
Had another crash today related to mds0:

https://gist.github.com/ianblenke/b74e5aa5547130ebc0fb

I'm for trying ceph-fuse instead at this point.

**Comment by carmstrong** [comment]
@ianblenke It looks like you're using kernel 3.17.2 - out of curiosity, have you been able to test the latest kernel in 522.6.0?

I will whip up the ceph-fuse change this week. We want to make sure that its performance is comparable to the kernel driver and is just as stable before we switch, but having you confirm that you no longer see the crash would be helpful.

**Comment by carmstrong** [comment]
Ceph recommends the kernel client for performance - closing.
