### ISSUE TITLE
store: Improve performance by setting NOCOW on the mounted volume

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#2972]
Disabling [copy-on-write](https://coreos.com/docs/cluster-management/debugging/btrfs-troubleshooting/#disable-copy-on-write) for Ceph seems to be a good idea.

I'm wondering, though, if we'll need to do this once CoreOS switches over to OverlayFS instead of btrfs for `/var/lib/docker`, but it's probably worth exploring before then.

refs #2647
refs #2927

**Comment by ianblenke** [comment]
Waiting with great anticipation for CoreOS 561 where this will start happening by default

**Comment by carmstrong** [comment]
I'm actually not sure we want to mess with how Ceph uses btrfs - it seems to be preferred: http://ceph.com/docs/master/rados/configuration/filesystem-recommendations/#filesystem-background-info

**Comment by carmstrong** [comment]
I consulted the Ceph community for advice.

**Comment by carmstrong** [comment]
We dropped btrfs for overlayfs, so this is irrelevant.
