### ISSUE TITLE
aws: consider reverting to instance storage

### ISSUE THREAD

**Issue by johanneswuerbach** [deis/deis#2974]
EC2 instance storage was removed in ff24d62 as a 8GB root partition was mounted per default, which is not enough for a deis instance.

As docker containers and ceph data are now stored on a separate partition, instance storage might be an option again and should be reconsidered as it is [faster](https://gist.github.com/ktheory/3c3616fca42a3716346b), free and independent from network troughput.

Remaining questions:
- [ ] Can the instance storage be mounted as a single 32gb root partition?
- [ ] Are any fast growing files / folders still using the root disk?

**Comment by carmstrong** [comment]
:+1: Some background - we added the EBS-backed root partition because an 8GB root partition was far too small.

@johanneswuerbach how did your research go with this?

**Comment by johanneswuerbach** [comment]
@carmstrong sorry for the delay.
CoreOS does not provide instance store based AMIs at the moment https://github.com/coreos/bugs/issues/177

The 8GB you saw in the past is the default volume size for an EBS on AWS.
