### ISSUE TITLE
logspout: /var/lib/docker/init/dockerinit-1.4.1: cannot allocate memory

### ISSUE THREAD

**Issue by mboersma** [deis/deis#2975]
Builder ends up restarting over and over, and looking at the instances, logspout was restarting on all:
```console
core@deis-2 ~ $ journalctl -fu deis-logspout
-- Logs begin at Tue 2015-01-27 22:56:15 UTC. --
Jan 27 23:36:46 deis-2 systemd[1]: deis-logspout.service holdoff time over, scheduling restart.
Jan 27 23:36:46 deis-2 systemd[1]: Stopping deis-logspout...
Jan 27 23:36:46 deis-2 systemd[1]: Starting deis-logspout...
Jan 27 23:36:46 deis-2 sh[5108]: Error: No such image or container: deis-logspout
Jan 27 23:36:46 deis-2 systemd[1]: Started deis-logspout.
Jan 27 23:36:46 deis-2 systemd[1]: deis-logspout.service: main process exited, code=exited, status=1/FAILURE
Jan 27 23:36:46 deis-2 sh[5119]: time="2015-01-27T23:36:46Z" level="fatal" msg="Error response from daemon: Cannot start container 070c2884756f7a5b93b7a43b1c5a01f91f5276aa9d136a87eb39ac9a0336473f: fork/exec /var/lib/docker/init/dockerinit-1.4.1: cannot allocate memory"
Jan 27 23:36:46 deis-2 systemd[1]: Unit deis-logspout.service entered failed state.
Jan 27 23:36:46 deis-2 systemd[1]: deis-logspout.service failed.
Jan 27 23:36:46 deis-2 docker[5137]: deis-logspout
Jan 27 23:36:51 deis-2 systemd[1]: deis-logspout.service holdoff time over, scheduling restart.
Jan 27 23:36:51 deis-2 systemd[1]: Stopping deis-logspout...
Jan 27 23:36:51 deis-2 systemd[1]: Starting deis-logspout...
Jan 27 23:36:51 deis-2 sh[5187]: Error: No such image or container: deis-logspout
Jan 27 23:36:51 deis-2 systemd[1]: Started deis-logspout.
Jan 27 23:36:52 deis-2 sh[5198]: 2015/01/27 23:36:52 attach: 0c82c510868b deis-logspout success
Jan 27 23:36:52 deis-2 sh[5198]: 2015/01/27 23:36:52 attach: 1ae37b8d7083 deis-router success
Jan 27 23:36:52 deis-2 sh[5198]: 2015/01/27 23:36:52 attach: 66d720dfdcda deis-database success
Jan 27 23:36:52 deis-2 sh[5198]: 2015/01/27 23:36:52 attach: a12d3b495c70 deis-cache success
Jan 27 23:36:52 deis-2 sh[5198]: 2015/01/27 23:36:52 attach: 390fff8c3f4f deis-publisher success
Jan 27 23:36:52 deis-2 sh[5198]: 2015/01/27 23:36:52 attach: 0aa2a15097ac deis-store-metadata success
Jan 27 23:36:52 deis-2 sh[5198]: 2015/01/27 23:36:52 attach: 84ef4afc802b deis-store-daemon success
Jan 27 23:36:52 deis-2 sh[5198]: 2015/01/27 23:36:52 attach: d1b335cdaf35 deis-store-monitor success
Jan 27 23:36:52 deis-2 sh[5198]: 2015/01/27 23:36:52 etcd: http://172.17.8.101:4001
Jan 27 23:36:53 deis-2 sh[5198]: 2015/01/27 23:36:53 url: 100: Key not found (/deis/logs) [21297]
Jan 27 23:36:53 deis-2 systemd[1]: deis-logspout.service: main process exited, code=exited, status=1/FAILURE
Jan 27 23:36:53 deis-2 docker[5240]: Error response from daemon: No such container: deis-logspout
Jan 27 23:36:53 deis-2 docker[5240]: time="2015-01-27T23:36:53Z" level="fatal" msg="Error: failed to remove one or more containers"
```
CoreOS beta channel and stable seem to be fine. See https://ci.deis.io/job/test-coreos-alpha/5/console for an example.

**Comment by bacongobbler** [comment]
is etcd 2.0 on alpha? That may cause an issue, as logspout depends on the etcd client.

**Comment by carmstrong** [comment]
> is etcd 2.0 on alpha?

Nope, still 0.4.6.

**Comment by carmstrong** [comment]
Issue is `/var/lib/docker/init/dockerinit-1.4.1: cannot allocate memory`

**Comment by mboersma** [comment]
Seems like that should also have happened on CoreOS beta, but it didn't. This failure happened several times in CI with CoreOS alpha though. We should figure this out, but it's nice to be on the stable channel. :smiling_imp:

**Comment by mboersma** [comment]
The issue seems to be builder not starting because `btrfs: driver not available`. I'm testing use of `overlay` instead, but we would need to make it conditional somehow so that this works with CoreOS nodes formatted as `btrfs` and `ext4`.

**Comment by carmstrong** [comment]
> The current issue seems to be builder not starting because btrfs: driver not available.

I think just removing the storage driver from https://github.com/deis/deis/blob/master/builder/image/bin/boot#L54 should do it -- Docker will pick the best option. This is how CoreOS is doing it now, too: https://github.com/coreos/coreos-overlay/blob/master/app-emulation/docker/files/dockerd#L34-L56

**Comment by mboersma** [comment]
@carmstrong we still need to be able to override `STORAGE_DRIVER` for the functional tests, because only `aufs` has not been problematic in that context. I did try removing it for a quick test and didn't get the behavior I expected--which you suggested. Instead Docker didn't start. I'll keep working on it.

**Comment by carmstrong** [comment]
@mboersma gotcha

**Comment by achannarasappa** [comment]
I encountered this problem after my Deis cluster (v1.7.3) had been running fine for several months. Here's the cluster information:
```sh
$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2-dirty
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2-dirty
OS/Arch (server): linux/amd64
```
```sh
$ cat /etc/lsb-release
DISTRIB_ID=CoreOS
DISTRIB_RELEASE=681.2.0
DISTRIB_CODENAME="Red Dog"
DISTRIB_DESCRIPTION="CoreOS 681.2.0"
```

In case anyone else is searching for an answer on this, I was able to resolve this by restarting the docker daemon:
```sh

**Comment by bacongobbler** [comment]
I know that there's an issue with a memory leak in docker at some point. Perhaps that would be the cause of your issue?

**Comment by achannarasappa** [comment]
Yes I believe that was the cause of the issue. I forgot to clarify that in my original comment. I think this will be a reoccurring problem until  [this issue with Docker](https://github.com/docker/docker/issues/8539) is fixed.
