### ISSUE TITLE
deis blocks domain creation under improper circumstances

### ISSUE THREAD

**Issue by jetole** [deis/deis#2979]
`$ deis domains:add django.paas-sandbox`
`Adding django.paas-sandbox to rubber-undertow... 400 BAD REQUEST`
`{u'domain': [u'Hostname does not look like a valid hostname. Only lowercase characters are allowed.']}`

deis will not let me create a domain where the top of the domain is "paas-sandbox", as displayed above, however this is not a top level domain nor is it intended as one. Our corporation uses an internal domain that is set as the dns search on all corporate computers. For example, if someone types `http://www/` in their browser, it will come up because their dns searches `corp.example.com` for non qualifying domains. They are really going to the site `www.corp.example.com` but all they type and all the host header on the server sees is "www". deis requires the domain to exist how the user will display it in the browser in order to render the page. Our DNS system is almost identical to Active Directory so anyone using Active Directory can relate but this is not a MS / Active Directory specific scenario. This can be done using only dhcp and most ISP's will do this from their dhcp as well.

Anyways, please fix. Thank you.

**Comment by bacongobbler** [comment]
That indicates an issue with the regular expression here: https://github.com/deis/deis/blob/master/controller/api/serializers.py#L242-L248

The error is misleading, but the domain needs to be fully qualifiable, i.e. `django.paas-sandbox.com`.

**Comment by jetole** [comment]
>
> the domain needs to be fully qualifiable


Why?

My point is that it should not require the domain to be fully qualifiable.
 deis is aimed at private PaaS, if I'm not mistaken, and most corporations
do not reference hosts by their fully qualifiable name in the web browser.
deis does not seem to want to show the page if I do not use the fully
qualifiable name or did I misconfigure something else.

Are you saying it's just a policy that deis does not want to render a page
unless the host header contains the fully qualifiable name?

On Wed, Jan 28, 2015 at 12:55 PM, Matthew Fisher <notifications@github.com>
wrote:

> That indicates an issue with the regular expression here:
> https://github.com/deis/deis/blob/master/controller/api/serializers.py#L242-L248
>
> The error is misleading, but the domain needs to be fully qualifiable,
> i.e. django.paas-sandbox.com.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deis/deis/issues/2979#issuecomment-71882105>.
>



-- 

:: Sincerely,
:: Joseph Tole

**Comment by jetole** [comment]
Just an update, if I set wildcard records for *.paas.corp.example.com and
set my app to use the domain django.paas then I can reference it via
http://django.paas/ since our corp computers will search corp.example.com
for non qualifying domains but paas-1 seems to break the regex it uses for
allowed domains.

On Wed, Jan 28, 2015 at 1:00 PM, Joseph Tole <joseph.tole@gmail.com> wrote:

> the domain needs to be fully qualifiable
>
>
> Why?
>
> My point is that it should not require the domain to be fully qualifiable.
>  deis is aimed at private PaaS, if I'm not mistaken, and most corporations
> do not reference hosts by their fully qualifiable name in the web browser.
> deis does not seem to want to show the page if I do not use the fully
> qualifiable name or did I misconfigure something else.
>
> Are you saying it's just a policy that deis does not want to render a page
> unless the host header contains the fully qualifiable name?
>
> On Wed, Jan 28, 2015 at 12:55 PM, Matthew Fisher <notifications@github.com
> > wrote:
>
>> That indicates an issue with the regular expression here:
>> https://github.com/deis/deis/blob/master/controller/api/serializers.py#L242-L248
>>
>> The error is misleading, but the domain needs to be fully qualifiable,
>> i.e. django.paas-sandbox.com.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/deis/deis/issues/2979#issuecomment-71882105>.
>>
>
>
>
> --
>
> :: Sincerely,
> :: Joseph Tole
>
>


-- 

:: Sincerely,
:: Joseph Tole

**Comment by bacongobbler** [comment]
looks like the regex is wrong. As per [RFC1034](http://tools.ietf.org/html/rfc1034):

> The labels must follow the rules for ARPANET host names.  They must
start with a letter, end with a letter or digit, and have as interior
characters only letters, digits, and hyphen.  There are also some
restrictions on the length.  Labels must be 63 characters or less.

So in other words, that should be a valid domain name.

**Comment by jetole** [comment]
Ok. Just want to make sure I understood you right. So this _IS_ a bug and
to be resolved. Is that correct?

On Wed, Jan 28, 2015 at 1:11 PM, Matthew Fisher <notifications@github.com>
wrote:

> looks like the regex is wrong. As per RFC1034
> <http://tools.ietf.org/html/rfc1034>:
>
> The labels must follow the rules for ARPANET host names. They must
> start with a letter, end with a letter or digit, and have as interior
> characters only letters, digits, and hyphen. There are also some
> restrictions on the length. Labels must be 63 characters or less.
>
> So in other words, that should be a valid domain name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deis/deis/issues/2979#issuecomment-71884867>.
>



-- 

:: Sincerely,
:: Joseph Tole

**Comment by bacongobbler** [comment]
yes.

**Comment by jetole** [comment]
Thank you.

On Wed, Jan 28, 2015 at 1:21 PM, Matthew Fisher <notifications@github.com>
wrote:

> yes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deis/deis/issues/2979#issuecomment-71886749>.
>



-- 

:: Sincerely,
:: Joseph Tole
