### ISSUE TITLE
ugly error on builder failing to retrieve release values

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#2984]
While testing an unrelated fix, the builder spewed an ugly error message. We were recently able to see builder failures with #2964, but it looks butt-ugly:

```
-----> Launching...
2015/01/28 21:40:07 failed retrieving config from controller: &{%!s(*http.body=&{0xc20800ae10 0xc2080581b0 0xc20805a3c0 true {0 0} false}) {%!s(int32=0) %!s(uint32=0)} %!s(bool=false) <nil> %!s(func(error)=0x49c0b0) %!s(func() error=0x49c040)}
To ssh://git@deis.104.236.239.206.xip.io:2222/go.git
```

**Comment by aledbf** [comment]
@bacongobbler that was the error that #2888 fixes

**Comment by bacongobbler** [comment]
the reason this is occurring is because we are not reading the response body from the buffer as per the standard Go docs: http://golang.org/pkg/net/http/
