### ISSUE TITLE
Uninstall Platform leaves deis-registry@2.service hanging around

### ISSUE THREAD

**Issue by withinboredom** [deis/deis#2995]
True story ...

Don't have any logs, just tore down the whole cluster. :/

**Comment by bacongobbler** [comment]
Unfortunately, `deisctl uninstall platform` is not smart enough to figure out how many registries/routers you have available: https://github.com/deis/deis/blob/master/deisctl/cmd/cmd.go#L519

Maybe it'd make sense to scale back down to the default platform instances and then uninstall?

**Comment by carmstrong** [comment]
This be a bug...

https://github.com/deis/deis/blob/0459ccc19e76d3c3bf28891c248776322a544057/deisctl/cmd/cmd.go#L275
and
https://github.com/deis/deis/blob/0459ccc19e76d3c3bf28891c248776322a544057/deisctl/cmd/cmd.go#L519

We should also ensure #2929 accounts for this.
