### ISSUE TITLE
Key not found (/deis/logs)

### ISSUE THREAD

**Issue by ngpestelos** [deis/deis#2997]
We built a fresh cluster yesterday and started seeing this error:

![screenshot 2015-01-30 08 35 42](https://cloud.githubusercontent.com/assets/5047/5969218/f6bed030-a85b-11e4-9db8-922fbfe66ea8.png)

**Comment by carmstrong** [comment]
It sounds like logger either isn't running or isn't publishing properly: http://docs.deis.io/en/latest/customizing_deis/logger_settings/

**Comment by carmstrong** [comment]
@ngpestelos Did you figure this out?

**Comment by bacongobbler** [comment]
I think this could have been #3007, so it should be resolved. This popped up right when CoreOS made that breaking change in go-etcd.

**Comment by carmstrong** [comment]
> This popped up right when CoreOS made that breaking change in go-etcd.

But that would have only bitten folks who rolled their own images, since we didn't cut any releases in that window as far as I know.

**Comment by ngpestelos** [comment]
Yes, it's OK now (see screenshot). I also noticed that `deis-store-admin` wasn't started with the platform. Was this intended?

![screenshot 2015-02-03 14 56 26](https://cloud.githubusercontent.com/assets/5047/6032216/7b1b0c84-ac41-11e4-9f39-e904f8e139f8.png)

**Comment by carmstrong** [comment]
> I also noticed that deis-store-admin wasn't started with the platform.

Yes, that's an optional component that's only used for debugging the store components. Closing - glad to hear it's running smoothly!
