### ISSUE TITLE
All the given peers are not reachable

### ISSUE THREAD

**Issue by marzolfb** [deis/deis#3003]
Just getting started following install instructions with Vagrant on a MacBookPro. Trying to run first deisctl command:

    deisctl config platform set sshPrivateKey=~/.vagrant.d/insecure_private_key 

And getting this error:

    Error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

Yes, I have read this: http://docs.deis.io/en/latest/troubleshooting_deis/#all-the-given-peers-are-not-reachable. But, I've followed those instructions without success.

I'm operating behind a corporate proxy - not sure if this has an impact or not.

I can ssh to the deis VMs. So, it doesn't seem obvious what the problem is. 

Are there any additional troubleshooting steps I can take?

**Comment by bacongobbler** [comment]
I'd try and see if any of these issues on coreos/etcd apply to you: https://github.com/coreos/etcd/search?q=all+the+given+peers+are+not+reachable&type=Issues&utf8=%E2%9C%93

**Comment by carmstrong** [comment]
@marzolfb Chances are you forgot to use a fresh discovery URL before provisioning or your instances can't community with each other due to firewall issues. Inspecting the etcd journal on the hosts should give you some insight - `journalctl -u etcd`.

**Comment by marzolfb** [comment]
Ugh. Based on @jonboulle 's response here, https://github.com/coreos/coreos-vagrant/issues/187, discovery in etcd doesn't support connectivity through a proxy (yet) and a manual effort to work around it is required.

**Comment by carmstrong** [comment]
@marzolfb The new etcd version he refereneced in that issue (v0.5.0) has been renamed v2.0.0, and it's actually out now. We're just waiting for it to make its way to the stable channel on CoreOS before Deis users can use it.

I'm going to close this issue as there's nothing we can really do on Deis's end.
