### ISSUE TITLE
client returns "could not create deis remote" on host verification error

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#3005]
...even though the deis remote was created :trollface: 

```
><> deis create uuid
Creating application... done, created uuid
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
xxxxxxxxxxxx.
Please contact your system administrator.
Add correct host key in /Users/bacongobbler/.ssh/known_hosts to get rid of this message.
Offending RSA key in /Users/bacongobbler/.ssh/known_hosts:6
RSA host key for [deis.xxxxxxxxxx]:2222 has changed and you have requested strict checking.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch deis
Could not create Deis remote
><> vim ~/.ssh/known_hosts # remove offending key
><> git push deis master
Counting objects: 17, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (9/9), done.
Writing objects: 100% (17/17), 1.93 KiB | 0 bytes/s, done.
Total 17 (delta 6), reused 17 (delta 6)
-----> Python app detected
```

**Comment by wenzowski** [comment]
indeed, there appears to be more than 1 keypair floating around somehow

though rather than removing the fingerprint...
```bash
GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git push deis master # insecure quickfix
```

**Comment by bacongobbler** [comment]
I have that set locally as well. It's just a misleading error message which should get fixed up (the `Could not create Deis remote` message, I mean). :)

**Comment by bacongobbler** [comment]
to be clear, the remote host verification failure message is a good thing, but can also be misleading if the builder jumps hosts: #2203

**Comment by wenzowski** [comment]
Yes, that error message is misleading.

Don't know how this is implemented. Are you doing a `git add -f deis <url>` to automatically attempt to fetch on add? If so, why not split this into two calls (add then fetch) to state:

1. the deis remote was added
2. the deis remote is reachable

Automatically attempting to fetch does ensure the added url is valid and reachable...which it was not in this case because of a keypair change.

**Comment by wenzowski** [comment]
Is there an issue tracking the builder jumping hosts? To my unfamiliar eyes I don't see that in the PR you linked @bacongobbler.

**Comment by wenzowski** [comment]
hmm, [doesn't appear](https://github.com/deis/deis/blob/v1.3.1/client/deis.py#L494) to be calling `-f`

**Comment by bacongobbler** [comment]
no, there's no specific issue WRT the builder re-generating SSH keys when jumping hosts.

> hmm, doesn't appear to be calling -f

We used to, but I changed that up recently in #2857. :)

**Comment by wenzowski** [comment]
Ah. Well that's that then!

**Comment by bacongobbler** [comment]
builder jumping hosts and re-generating keys has been fixed up in https://github.com/deis/deis/pull/3767, though the error message in the client still needs to be fixed up for this edge case. pinging @Joshua-Anderson as he's working on the client rewrite in Go so he's aware of this pitfall in the existing client.

**Comment by mboersma** [comment]
The python client is deprecated and will be removed with the v1.10.0 release. If you see similar issues with the new go CLI, please open a new issue.
