### ISSUE TITLE
Proposal: Self updating Deis CLI

### ISSUE THREAD

**Issue by rjocoleman** [deis/deis#3013]
The Deis CLI for users is great but it's version is matched to the platform version.

Since the platform is progressing rapidly there are many regular updates (yay!) but the workflow for users is a little cumbersome updating every couple of weeks. We've got some users that every time they use `deis` they need to update their CLI!

There's a library to do some self-updating in Go here: https://github.com/sanbornm/go-selfupdate

This lib requires a couple of things: 
* version API to announce current versions for each supported architecture.
* diff or binaries to download each version.

I think adding the version API to currently logged in deis's controller and using generic diff's and binaries from the common S3 would work.

I need to think more carefully about the initial install and situations where a user logs into controllers of multiple versions.

`deisctl` could also make use of this.

Any interest in a PR for this?

**Comment by bacongobbler** [comment]
the client is matched to the platform version, but that does not mean that the client is tied to a specific platform version. It's matched to the API version: https://github.com/deis/deis/pull/2567

I think deisctl could partially benefit from this, but it's mostly a glorified fleet wrapper so it's not tied to a specific version, either. We just version them all the same when we cut releases for simplicity's sake.

Also, the client's written in python so go-selfupdate won't help here :)

I'm not sure if there's a particular reason we should add more logic to the clients... unless there's a way we can do an in-place upgrade of the clients when a new version is available. I'd be happy with that.

**Comment by rjocoleman** [comment]
@bacongobbler looks like I'm completely off the mark! I think there's a case for in-place upgrade for the client but this proposal isn't right!
