### ISSUE TITLE
a way to pull configs into another application

### ISSUE THREAD

**Issue by mhahn** [deis/deis#3016]
to run migrations on my app, "services", i create another application "services-migrations". when i change models, i push to "services-migrations", run the db migration and then push to "services".

this works if "services" and "services-migrations" have the same configs (ie. DATABASE_URL).

this process is the same for any of the environments i create (qa/staging/production). i think it would be useful to easily copy the settings from one application to another.

this works, but it could be better supported IMO:

```
deis config:list -a services --oneline | grep -v == | xargs deis config:set -a services-migrations
```

i'm happy to add if i can get pointed in the right direction if you think its useful.

**Comment by bacongobbler** [comment]
I know that we formatted the output to follow the Heroku client (that was the main driver back in the day... and still to this day) but having some ability to take a look at the client output and make it more programmable would be nice, IMO. :+1:

**Comment by mboersma** [comment]
`deis config:set` takes multiple values, so I don't think you need to use `xargs` here. If it didn't output the header line when you specify `--oneline`, then I think you could pipe them together directly.

**Comment by bacongobbler** [comment]
The following works for me:

```
$ deis config:set -a go $(deis config:list -a go --oneline | grep -v ===)
```

If we remove the `=== go Config` line when `--oneline` is present then we can remove the `grep -v`. Does that seem acceptable to you?

**Comment by bacongobbler** [comment]
With #3059 the supported way of doing this would be `deis config:set -a newapp $(deis config:list -a oldapp --oneline)`. Thanks!
