### ISSUE TITLE
Need a way to stop one-off stale commands

### ISSUE THREAD

**Issue by glogiotatidis** [deis/deis#3022]
With `deis info` I get 

```
=== xx-prod Application
{
  "updated": "2015-02-04T10:08:37UTC", 
  "uuid": "b1812xxx1", 
  "created": "2015-01-20T12:46:39UTC", 
  "url": "xx-prod.masterfirefoxos.com", 
  "owner": "xx", 
  "id": "xx-prod", 
  "structure": {
    "cmd": 3, 
    "run": 32
  }
}
```
 1. Deis believes that there are 32 "run" processes but "docker ps" in all hosts returns 0 "run" processes
 2. Even if there were 32 running processes, we need a way to stop them

`deis scale run=0` returns 
```
400 BAD REQUEST
Container type run does not exist in application
```

**Comment by bacongobbler** [comment]
I think this is just false info that shouldn't be shown in the client. run processes are the process type when you perform `deis run`, which mean you've run 32 `deis apps:run` commands against it. :)

**Comment by glogiotatidis** [comment]
I didn't explain myself correctly:
It should totally be shown in the client, when they do exist. These don't exist (no docker containers related to the "run" command" and I've no way to reset Deis.

**Comment by bacongobbler** [comment]
These containers are [killed after they're executed](https://github.com/deis/deis/blob/master/controller/scheduler/fleet.py#L306-L308), so they do not exist in the scheduler. It's just an implementation detail of the platform so we can run multiple one-off commands in parallel. We keep the database entry around such that each one-off job has a unique number, so there's nothing that you need to do on your end to "reset Deis".

**Comment by bacongobbler** [comment]
what version of deis are you you running, by the way?

**Comment by glogiotatidis** [comment]
OK I get that but in this case why other apps on which I've used `deis run` don't display this line?

```
=== xx-dev Application
{
  "updated": "2015-01-20T14:59:25UTC", 
  "uuid": "93d069d8-xx-4bc8-9ef3-163c1203c502", 
  "created": "2015-01-20T12:45:17UTC", 
  "url": "xx-dev.masterfirefoxos.com", 
  "owner": "xx", 
  "id": "xx-dev", 
  "structure": {
    "cmd": 3
  }
}
```

(I'm running 1.1.1)

**Comment by glogiotatidis** [comment]
More info:
Running other commands in the same app doesn't increase the displayed "run" number, i.e. the output of `deis info` is exactly the same. I guess that Deis believes that there are 32 currently running "run" commands.

**Comment by bacongobbler** [comment]
My assumption is that since we do not clean up the Container objects in the database, the [structure is updated](https://github.com/deis/deis/blob/master/controller/api/models.py#L230-L232) with the run values, when in reality these should [be excluded](https://github.com/deis/deis/blob/master/controller/api/models.py#L270).

**Comment by glogiotatidis** [comment]
More info:
Deis probably believes that there are 32 commands running due to #3035.

**Comment by bacongobbler** [comment]
if you could ssh into one of the boxes and run `fleetctl list-units`, that would be helpful to show if there is indeed 32 commands running.

**Comment by glogiotatidis** [comment]
These are the units related to the app under investigation, returned by `fleetctl list-units`

```
masterfirefoxos-prod_v48.run.20.service	1ecca637.../10.152.74.15	inactive	dead
masterfirefoxos-prod_v52.run.22.service	6e753008.../10.152.74.225	inactive	dead
masterfirefoxos-prod_v53.run.23.service	96834fc1.../10.152.74.172	inactive	dead
masterfirefoxos-prod_v53.run.26.service	1ecca637.../10.152.74.15	inactive	dead
masterfirefoxos-prod_v53.run.27.service	6e753008.../10.152.74.225	inactive	dead
masterfirefoxos-prod_v53.run.28.service	96834fc1.../10.152.74.172	inactive	dead
masterfirefoxos-prod_v53.run.29.service	96834fc1.../10.152.74.172	inactive	dead
masterfirefoxos-prod_v53.run.30.service	6e753008.../10.152.74.225	inactive	dead
masterfirefoxos-prod_v55.run.33.service	1ecca637.../10.152.74.15	inactive	dead
masterfirefoxos-prod_v58.run.36.service	6e753008.../10.152.74.225	inactive	dead
masterfirefoxos-prod_v58.run.37.service	96834fc1.../10.152.74.172	inactive	dead
masterfirefoxos-prod_v59.run.41.service	1ecca637.../10.152.74.15	inactive	dead
masterfirefoxos-prod_v60.run.42.service	6e753008.../10.152.74.225	inactive	dead
```
