### ISSUE TITLE
How can isolate Control Plane and Router Mesh 

### ISSUE THREAD

**Issue by nekrox** [deis/deis#3023]
I like only scale the Data Plane how can isolate the Control Plane and Router Mesh, i dont like the idea of repeat data on every single host of cluster

http://docs.deis.io/en/latest/understanding_deis/architecture/

In the last paragraph you mention about topologies but its not clear and/or missing documentation.

**Comment by sforsman** [comment]
Currently you can do this manually by copying the default unit files from deisctl/units and then adding metadata restrictions under [X-Fleet] (e.g. MachineMetadata=plane=control). You can point the Deis installer to the new unit files by setting the DEISCTL_UNITS environment variable. Of course, you also need to add the appropriate metadata for the CoreOS hosts in your cloud-config (e.g. coreos/fleet/metadata: plane=control). Finally, you need to tell your applications you want to run them on the Data Plane. For this, you need to use deis tags:set (e.g. deis tags:set plane=data).

Please correct me if there is already an easier way.

**Comment by bacongobbler** [comment]
nope, that sounds pretty accurate to me

**Comment by sforsman** [comment]
Related to this topic, have you ever considered making it possible to define default tags for new applications (with something like `deisctl config controller set defaultApplicationTags=plane=data`)?

What currently happens - when the planes are isolated - is that fleet sometimes schedules new applications to the routing (or control) plane which is undesirable for several reasons. It would be great if the application's initial unit file could already have the X-Fleet -section up, so that applications are always deployed only to the data plane. While you can avoid this by adding conflicts for the routing/control plane unit files (e.g. *.web.*) , the default tags could also be useful for other default metadata restrictions (e.g. region, cabinet, disk type, environment).

**Comment by carmstrong** [comment]
> have you ever considered making it possible to define default tags for new applications (with something like deisctl config controller set defaultApplicationTags=plane=data)?

We haven't, although off the top of my head, that implementation would make sense. You'd really only need to change https://github.com/deis/deis/blob/0dc6819f544c24ccca4e834f993504cc498991a1/controller/scheduler/fleet.py#L322-L331 and maybe the run template too. The `DEFAULT_APPLICATION_TAGS` could be a setting in https://github.com/deis/deis/blob/0dc6819f544c24ccca4e834f993504cc498991a1/controller/templates/confd_settings.py which is written to by that etcd key. Does that make sense? That's only my view, though - the other maintainers have a different approach.

**Comment by bacongobbler** [comment]
The cluster-wide config discussion is at https://github.com/deis/deis/issues/1804 :)

**Comment by sforsman** [comment]
Thank you for the responses. The cluster-wide config would surely be an useful and interesting feature! If cluster-wide tag-managament became possible through it, the first thing that comes to mind is that it should probably support at least 3 different propagation strategies, mainly regarding existing applications. 1) Update all applications 2) Update applications matching the previous value 3) Do not update existing applications.

**Comment by bacongobbler** [comment]
Okay so it sounds like the call-to-action here is to clarify more on control plane/data plane isolation. @sforsman let's keep the discussion rolling in #1804 so we don't derail this thread, but your input is greatly appreciated :)

**Comment by carmstrong** [comment]
> Okay so it sounds like the call-to-action here is to clarify more on control plane/data plane isolation.

Yep! I assigned this to me so I can whip up some documentation around this, because @nekrox is right - we briefly mention this in the documentation but don't have much information.

The code solution is in #1804.

**Comment by sforsman** [comment]
Sorry, my bad :) @carmstrong if you'd like I'm more than happy to contribute to the documentation on the isolation of the planes - it is pretty fresh in my memory and I actually have saved notes on it. I could also provide a CloudFormation template for fast deployment.

**Comment by carmstrong** [comment]
> if you'd like I'm more than happy to contribute to the documentation on the isolation of the planes

Absolutely! I'm thinking the Architecture section you already linked to could link to new page in Managing Deis where we could instruct operators on how to actually achieve separation.

> I could also provide a CloudFormation template for fast deployment.

We could perhaps include the changes/additions as a code snippet in the docs? I hesitate to include a completely separate CloudFormation template, as it'd have to receive updates whenever we update the one in contrib/ec2, and we really try to avoid updating code in multiple places.

**Comment by sforsman** [comment]
> Absolutely!

Excellent, I'll get on it. 

> I hesitate to include a completely separate CloudFormation template, as it'd have to receive updates whenever we update the one in contrib/ec2, and we really try to avoid updating code in multiple places.

That of course makes sense. However duplication is not really needed since you can launch and configure stacks from within stacks and make resources conditional. Either way, I will just include the changes and additions as a code snippet, as you suggested :)

**Comment by carmstrong** [comment]
@sforsman Did you get a chance to PR this yet? Even if you could PR what snippets or docs you have in your head, I can clean it up and PR it. I'd like to get this in for our v1.4 release.

**Comment by sforsman** [comment]
> I'd like to get this in for our v1.4 release
With this in mind, when would you prefer to have the PR?

**Comment by carmstrong** [comment]
> With this in mind, when would you prefer to have the PR?

The code freeze for v1.4 is this Thursday, but since it's a documentation change it can pretty much go in whenever.

**Comment by sforsman** [comment]
@carmstrong I have the actual documentation pretty far - it basically just needs reviewing. However I would also like to include modifications for the contrib scripts of at least one cloud provider, so that it would be easier for the community to get an isolated cluster up and running.

If you prefer, I can also submit PRs and/or snippets for the contrib scripts later and just finish the documentation tonight :)

**Comment by carmstrong** [comment]
> If you prefer, I can also submit PRs and/or snippets for the contrib scripts later and just finish the documentation tonight :)

Let's submit it all as one - we'll need to discuss how to wrap all of the contrib changes to make them optional.

**Comment by carmstrong** [comment]
I think this work may be closely related to @krancour's work in #3635...

**Comment by mboersma** [comment]
#3718 is a great example of how separating the control and data planes can be done in Deis now with some minor changes.

**Comment by krancour** [comment]
I think #3718 actually should have closed this.  Closing.
