### ISSUE TITLE
Getting inconsistent 403 errors from 'deis domains'

### ISSUE THREAD

**Issue by dorkusprime** [deis/deis#3025]
Hi there!  I've been working with Deis for a few days now, and I'm getting really close to being able to use it in Production!  But there's one glaring issue that keeps me from doing so: with no consistency, `deis domains` commands return a 403 FORBIDDEN for one of my cluster's apps, when logged in as the Admin user.  This obviously means that it's impossible for me to configure the clusters/apps for real-world use.

Here's an example:

```
> deis apps
=== Apps
staging-routes
staging-web

> deis config -a staging-web
=== staging-web Config
ENV             staging
REDIS_HOST      stag-web-cache.8a22t8.0022.use1.cache.domain.com

> deis domains -a staging-web
=== staging-web Domains
web.staging.domain.com

> deis config -a staging-routes
=== staging-routes Config
ENV             staging
REDIS_HOST      stag-web-cache.8a22t8.0022.use1.cache.domain.com

> deis domains -a staging-routes
403 FORBIDDEN
Detail:
You do not have permission to perform this action.
```

Some key info:
* This is happening from the Admin user. I have tried adding this user to the "perms" list, but that changes nothing. I've tried logging in as a different privileged user, as well – the behavior still happens (and still happens inconsistently)
* I have multiple Deis clusters ("production" and "staging"), and I switch between them with `deis login <controller>`.  At any given time, the symptom may appear on *any* of the apps on *either* of these clusters.
* I have tried deleting `~/.deis`, and that *sometimes* alters the the nature of the symptom (it might switch clusters/apps, but there's almost always one app that fails `deis domains`)  

Any idea how I might troubleshoot this?

**Comment by bacongobbler** [comment]
Was the close unintentional or did you resolve this?

**Comment by dorkusprime** [comment]
Well, I (think I) fixed it for myself by destroying and recreating the apps . . . I think there's still an underlying bug, but it's *really* difficult to nail down.
