### ISSUE TITLE
Go-based bin/boot scripts don't use Godep to manage dependencies

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3029]
go-etcd has a backwards-incompatible change in https://github.com/coreos/go-etcd/commit/5348c80bde6223fa53c48ef546b4802db69b1d70#diff-33c1223aac4ef741731cc8c73b4d7777L295. Components that `go get` the source when they're built are getting this bad change. 

logspout was fixed in #3007, but we need to audit the other Go-based components to see if they need to be updated.

This appears to be the root cause of #3028.

refs #3007
refs #3028

**Comment by carmstrong** [comment]
A search of the codebase suggests only cache does this.

**Comment by mboersma** [comment]
> A search of the codebase suggests only cache does this.

That's what it looks like to me too. (It's fine for `Makefile`s to use `go get` for tools like `golint` and `godep`.)
