### ISSUE TITLE
Consider datetime format to ISO8601

### ISSUE THREAD

**Issue by jasoncox** [deis/deis#3032]
Currently deis is using:
```
DEIS_DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S%Z'

const DEIS_DATETIME_FORMAT string = "2006-01-02T15:04:05MST"
```

ISO8601:
```
DEIS_DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S%z'

const DEIS_DATETIME_FORMAT string = "2006-01-02T15:04:05Z0700"
```

ISO8601 expects UTC be represented by 'Z', Go supports this, however Pythons strftime does not which makes the example above not 100% correct. I think instead we'd need to call .isoformat() - which kinda breaks the pattern of defining time format in one spot.

This would make it a little simpler for log ingestion etc.

Would this adversely affect existing clusters?

**Comment by carmstrong** [comment]
> however Pythons strftime does not

It seems like it does: https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior What makes you think it doesn't?

Anyhow, I'm for this change if it's backwards-compatible.

**Comment by jasoncox** [comment]
strftime() and strptime() gives only two options for timezone, %z or %Z. ISO8601 prefers UTC be represented by the character 'Z' and all others as +HHMM or -HHMM.

**Comment by carmstrong** [comment]
I think the backwards-incompatibility of this change means it's probably something we won't change as a default - however, I think it would be a solid change to enable the timestamp to be configurable (maybe via an environment variable). That would satisfy your use case while still using our default in most cases.

Here's where the format is used in logspout: https://github.com/deis/deis/blob/76cd8cfc174db92042b276c8e1606754bd2e1222/logspout/logspout.go#L76

We could allow that to be overridden via an environment variable.

**Comment by jasoncox** [comment]
Thanks @carmstrong for me it's not critical as I can manually parse the date when I ingest the logs - it just might save that step for others.

**Comment by jasoncox** [comment]
I will make a PR for logspout to use a platform variable.

**Comment by carmstrong** [comment]
@jasoncox Oops! I had a spare few minutes so I just PRed this - #3037.

**Comment by jasoncox** [comment]
@carmstrong thanks!
