### ISSUE TITLE
can not start

### ISSUE THREAD

**Issue by apps4u** [deis/deis#3033]
HI I update my source today and Ive checked out 1.3.0 tag , Ive got Deisctl -version 1.3.0 installed .. Ive then create a new cluster on AWS which Ive been doing every day but now I get up to running ```deisctl start platform``` and all the service startup but not the builder server Ive recreated the CloudFormation cluster 3 time and each time its getting stuck at the same spot -- ```deis-builder.service activating/start-post``` and just stays like that for over 40 mins. Ive cleaned out my ~/.deis/units file and re-install deisctl tool which created the units file again the source I have made sure is on tag 1.3.0 ... Please any advice would be good or is this a bug has any one else not been able to get started today.

**Comment by carmstrong** [comment]
@apps4u Could you investigate registry and cache and see if this is really #3028?

**Comment by withinboredom** [comment]
I ran an uninstall on the same cluster, then reinstalled and worked like a charm ... it was some kind of one-off dns issue for me ...

**Comment by apps4u** [comment]
what version are u using ?

**Comment by apps4u** [comment]
Ive just gone through two more installs and its still getting stuck on ``deis-builder activating/start-post``` 
If I run a fleetctl status on the builder I get a builder: waiting for configd to  write initial templates .. If I run the same fleetctl status on the cache I get a message "All the given peers are not reachable" (tried to connect to each per twice and failed) ..  And third is I fleetctl status the registry@1 I get a error saying "registry: waiting for confd to write inlaid templates..." Error 100: Key not found (/deis/cache) ..  Now all the errors or messages are repeated a few time ...

**Comment by carmstrong** [comment]
@apps4u This is fixed in #3031. We're going to merge that and cut Deis v1.3.1 in the next few days to fix the issue. So sorry for the trouble!
