### ISSUE TITLE
command fails: deisctl config platform set sshPrivateKey=~/.ssh/deis

### ISSUE THREAD

**Issue by yekeqiang** [deis/deis#3034]
The command "deisctl config platform set sshPrivateKey=~/.ssh/deis" fails with:
Error: failed initializing SSH client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

i have execute command "eval `ssh-agent -s`" and " ssh-add ~/.ssh/deis"
Identity added: /home/core/.ssh/deis (/home/core/.ssh/deis)

**Comment by bacongobbler** [comment]
Have you set $DEISCTL_TUNNEL? That is the machine which is used to tunnel communication with your fleet cluster over SSH.

**Comment by yekeqiang** [comment]
@bacongobbler  i have set my $DEISCTL_TUNNEL，
```
export DEISCTL_TUNNEL=101.251.xx.xx
```
beause i install deis base Bare Metal, maybe my CoreOS cluster have problem？
in  Bare Metal , i must install CoreOS use follow command?：
```
 cp -av /home/core/deis/contrib/coreos/user-data /tmp/config
sudo coreos-install -C stable -c /tmp/config -d /dev/sda
```
i have 3 CoreOS，the CoreOS's ~/.ssh/deis must be same?

**Comment by bacongobbler** [comment]
> i have 3 CoreOS，the CoreOS's ~/.ssh/deis must be same?

No necessarily. Your SSH agent is forwarded over when you invoke deisctl (a wrapper of fleetctl), so if each box has a different key then you'll need to add each one to your agent if you want to use the `journal` command.

**Comment by carmstrong** [comment]
@yekeqiang To clarify - are you running `deisctl` on a local workstation, or on a CoreOS host that you're installing Deis onto? From your output, it looks like the latter. In that case, you don't need to set `DEISCTL_TUNNEL` at all - it will by default use the local fleet installation on the CoreOS host.

**Comment by yekeqiang** [comment]
@bacongobbler 
```
I'd SSH into one of the boxes and inspect your cluster to make sure it's up and healthy.
```
how can i give u my id_rsa to login my box? 

when i run command `fleetctl -debug=true list-machines` ，output error like this：

```
2015/02/06 06:02:41 INFO client.go:353: etcd: sending HTTP request GET http://127.0.0.1:4001/v2/keys/_coreos.com/fleet/machines?consistent=true&recursive=true&sorted=true
2015/02/06 06:02:41 INFO client.go:356: etcd: recv error response from GET http://127.0.0.1:4001/v2/keys/_coreos.com/fleet/machines?consistent=true&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused
2015/02/06 06:02:41 INFO client.go:278: Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused
2015/02/06 06:02:41 ERROR client.go:200: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 100ms
2015/02/06 06:02:41 INFO client.go:353: etcd: sending HTTP request GET http://127.0.0.1:4001/v2/keys/_coreos.com/fleet/machines?consistent=true&recursive=true&sorted=true
2015/02/06 06:02:41 INFO client.go:356: etcd: recv error response from GET http://127.0.0.1:4001/v2/keys/_coreos.com/fleet/machines?consistent=true&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused
2015/02/06 06:02:41 INFO client.go:278: Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused
2015/02/06 06:02:41 ERROR client.go:200: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 200ms
2015/02/06 06:02:41 INFO client.go:353: etcd: sending HTTP request GET http://127.0.0.1:4001/v2/keys/_coreos.com/fleet/machines?consistent=true&recursive=true&sorted=true
2015/02/06 06:02:41 INFO client.go:356: etcd: recv error response from GET http://127.0.0.1:4001/v2/keys/_coreos.com/fleet/machines?consistent=true&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused
2015/02/06 06:02:41 INFO client.go:278: Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused
2015/02/06 06:02:41 ERROR client.go:200: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 400ms
2015/02/06 06:02:41 INFO client.go:353: etcd: sending HTTP request GET http://127.0.0.1:4001/v2/keys/_coreos.com/fleet/machines?consistent=true&recursive=true&sorted=true
2015/02/06 06:02:41 INFO client.go:356: etcd: recv error response from GET http://127.0.0.1:4001/v2/keys/_coreos.com/fleet/machines?consistent=true&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused
2015/02/06 06:02:41 INFO client.go:278: Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused
2015/02/06 06:02:41 ERROR client.go:200: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 800ms
2015/02/06 06:02:42 INFO client.go:353: etcd: sending HTTP request GET http://127.0.0.1:4001/v2/keys/_coreos.com/fleet/machines?consistent=true&recursive=true&sorted=true
2015/02/06 06:02:42 INFO client.go:356: etcd: recv error response from GET http://127.0.0.1:4001/v2/keys/_coreos.com/fleet/machines?consistent=true&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused
2015/02/06 06:02:42 INFO client.go:278: Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused
2015/02/06 06:02:42 ERROR client.go:200: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 1s
```
is this  indicate  fleetd is Incorrectly？

**Comment by yekeqiang** [comment]
@carmstrong 

yeap,   i am installing Deis on a CoreOS host. i‘ll  unset  DEISCTL_TUNNEL，and have a try。THS

**Comment by bacongobbler** [comment]
> how can i give u my id_rsa to login my box?

sorry, I meant "if I were you, I'd SSH into one of the boxes and check etcd/fleet". :)

Yes, those errors indicate that your etcd cluster is set up incorrectly as fleet cannot connect to it (etcd typically listens on port 4001). I've seen this occur when either the discovery URL was not set or you re-used a discovery URL, which is described in http://docs.deis.io/en/latest/troubleshooting_deis/#all-the-given-peers-are-not-reachable

**Comment by yekeqiang** [comment]
@carmstrong 

must set DEISCTL_TUNNEL，if not set ，will output error like this:

···
Error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
···

**Comment by yekeqiang** [comment]
@bacongobbler 

ths，i'll see the described and have a try.

**Comment by yekeqiang** [comment]
@bacongobbler  @carmstrong  

this problem is my CoreOS clueter set up incorrectly, thank you。
