### ISSUE TITLE
NPM lock issue.

### ISSUE THREAD

**Issue by joshmackey** [deis/deis#3038]
Hit the same issue as described here: https://github.com/flynn/flynn/issues/537

Seems like the builder docker image needs to have its npm upgraded?

**Comment by bacongobbler** [comment]
We're on v64. buildpack-nodejs has cut a v70, so we're a few releases behind. Could you try the following for me and see if it works for you?

```
deis config:set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-nodejs
```

That will make your build fetch from master instead of using the buildpack bundled with the builder.

**Comment by aledbf** [comment]
@joshmackey the npm in v0.10.35 is 1.4.28. Just add:
```
"engines": {
  "npm": "2.x"
}
```

to the `package.json` and the node.js buildpack will use that version.

**Comment by joshmackey** [comment]
Its too late to test any of these. I restarted the builder which removed the lock file.

@bacongobbler I use https://github.com/appstack/heroku-buildpack-nodejs-gulp for a buildpack.
@aledbf I imagine that this would work. I'll update it and we'll see if it ever happens again.

Thanks for the quick response.
