### ISSUE TITLE
Vagrant problem: direct box file path

### ISSUE THREAD

**Issue by ineu** [deis/deis#3044]
Trying to install deis according to the documentation here: http://docs.deis.io/en/latest/installing_deis/vagrant/ I receive error:
```
==> deis-01: Running triggers before up...
==> deis-01: Box 'coreos-stable' could not be found. Attempting to find and install...
    deis-01: Box Provider: virtualbox
    deis-01: Box Version: >= 522.6.0
You specified a box version constraint with a direct box file
path. Box version constraints only work with boxes from Vagrant
Cloud or a custom box host. Please remove the version constraint
and try again.
```
I've found this issue: https://github.com/mitchellh/vagrant/issues/3378
Using vagrant version 1.7.2 and deis rev 0dc6819f

**Comment by carmstrong** [comment]
@ineu I'm unable to replicate this on Deis master and Vagrant 1.7.2 -- things work just fine for me:

```console
$ vagrant up
Bringing machine 'deis-01' up with 'virtualbox' provider...
Bringing machine 'deis-02' up with 'virtualbox' provider...
Bringing machine 'deis-03' up with 'virtualbox' provider...
==> deis-01: Running triggers before up...
==> deis-01: Box 'coreos-stable' could not be found. Attempting to find and install...
    deis-01: Box Provider: virtualbox
    deis-01: Box Version: >= 522.6.0
==> deis-01: Loading metadata for box 'http://stable.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json'
    deis-01: URL: http://stable.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json
==> deis-01: Adding box 'coreos-stable' (v522.6.0) for provider: virtualbox
    deis-01: Downloading: http://stable.release.core-os.net/amd64-usr/522.6.0/coreos_production_vagrant.box
    deis-01: Calculating and comparing box checksum...
==> deis-01: Successfully added box 'coreos-stable' (v522.6.0) for 'virtualbox'!
```

Anything else you can provide to help us debug this? Are you using VirtualBox or another provider?

**Comment by ineu** [comment]
@carmstrong No, I did not do any changes. What I've done is
1. Installed Vagrant from ArchLinux repo.
2. `vagrant plugin install vagrant-triggers`
3. Cloned deis repo
4. `make discovery-url`
5. `vagrant up`
And it fails immediately without even trying to fetch box or metadata. But if I comment out line 58 in Vagrantfile, `config.vm.box_version = ">= 522.6.0"`, it works fine.
It doesn't look like a problem in Arch package because installed  code responsible for this error is the same as https://github.com/mitchellh/vagrant/blob/master/lib/vagrant/action/builtin/box_add.rb#L117

**Comment by mboersma** [comment]
This looks like the same issue as coreos/coreos-vagrant#165.

**Comment by carmstrong** [comment]
Good find - sounds like a resolution or connection issue.

**Comment by ineu** [comment]
Thanks for the link. I'll check if there are network problems on the machine I've run commands on.

**Comment by ineu** [comment]
So this is network issue indeed. `vagrant up --debug` outputs:
```
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
```

This is because Google bans Crimean IPs. Seems like not only commercial apps are banned, as Google claims, but access to cloud storage as well.
Thanks for investigation, closing this.
