### ISSUE TITLE
Customized deis router times out at times

### ISSUE THREAD

**Issue by anoopknayak** [deis/deis#3052]
I have a customised deis-router in order to run it as a reverse proxy for some of the apps I have deployed on deis. I have taken the code from deis-router from the 1.2.1 release. It works but at times it times out on servicing the requests. The requests doesn't seem to have forwarded to the other apps(which is again uwsgi servers configured to accept http data). Currently it is still under development and so there is isn't much traffic for the timeouts to occur. Any suggestions to improve this?

What I have really done is just to modify nginx templates with my custom rules. I haven't changed anything else. I attempted to upgrade confd to a newer version(it is 5.0 in the router) but couldn't get it to work so stuck with the old one deis used.

**Comment by carmstrong** [comment]
> What I have really done is just to modify nginx templates with my custom rules.

Well, that could cause issues depending on what you've changed. Can you post a diff of your router from the stock router?

> The requests doesn't seem to have forwarded to the other apps

Are you sure this isn't a problem with the apps themselves (i.e. #3051)? The router still forwards requests to upstream apps until they are no longer being published, which can take a few seconds after they become unresponsive.

**Comment by anoopknayak** [comment]
> Are you sure this isn't a problem with the apps themselves (i.e. #3051)? The router still forwards requests to upstream apps until they are no longer being published, which can take a few seconds after they become unresponsive.

Don't think so as this is another app which has only "web" as the process and is working fine without any problems.
Further i felt the configuration is so different now that its better to put my nginx.conf here. Rest apart nothing is changed.. I'm using the same files "deis/router/image" except for the nginx.conf in the templates directory
```
# required to run in a container
daemon off;
error_log /dev/stdout info;
user www-data;
worker_processes auto;
pid /run/nginx.pid;


events {
    worker_connections 768;
    # multi_accept on;
}

http {
    # basic settings
    access_log /dev/stdout;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 60;
    types_hash_max_size 2048;
    server_names_hash_bucket_size 64;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    {{ if .deis_router_gzipCompLevel }}
    gzip {{ .deis_router_gzip }};
    gzip_comp_level {{ .deis_router_gzipCompLevel }};
    gzip_disable {{ .deis_router_gzipDisable }};
    gzip_http_version {{ .deis_router_gzipHttpVersion }};
    gzip_min_length {{ .deis_router_gzipMinLength }};
    gzip_types {{ .deis_router_gzipTypes }};
    gzip_proxied {{ .deis_router_gzipProxied }};
    gzip_vary {{ .deis_router_gzipVary }};{{ end }}

    client_max_body_size {{ or (.deis_router_bodySize) "1m" }};
    
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    {{ range $service := .deis_services }}
    {{ if $service.Nodes }}
    {{ $name := Base $service.Key }}
    {{ if ne $name "api-beta" }}
    {{ if ne $name "app" }}
    upstream {{ $name }} {
        {{ range $upstream := $service.Nodes }}
        server {{ $upstream.Value }};
        {{ end }}
    }
    {{ end }}
    {{ end }}
    {{ end }}
    {{ end }}



    server {
        listen 80 default_server;
        #WORKAROUND for sending larger files
        client_max_body_size 10M;

        location / {
                if ($http_origin ~* (https?://[^/]*\.octonius\.com(:[0-9]+)?)) {
                    set $cors "true";
                }
                if ($request_method = 'OPTIONS') {
                    set $cors "${cors}options";  
                }
                if ($request_method = 'GET') {
                    set $cors "${cors}get";  
                }
                if ($request_method = 'POST') {
                    set $cors "${cors}post";
                }

                if ($cors = "trueget") {
                    add_header 'Access-Control-Allow-Origin' "$http_origin";
                    add_header 'Access-Control-Allow-Credentials' 'true';
                }

                if ($cors = "truepost") {
                    add_header 'Access-Control-Allow-Origin' "$http_origin";
                    add_header 'Access-Control-Allow-Credentials' 'true';
                }

                if ($cors = "trueoptions") {
                    add_header 'Access-Control-Allow-Origin' "$http_origin";
                    add_header 'Access-Control-Allow-Credentials' 'true';
                    add_header 'Access-Control-Max-Age' 1728000;
                    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
                    add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,Keep-Alive,X-Requested-With,If-Modified-Since';
                    add_header 'Content-Length' 0;
                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                    return 204;
                }
                root /app/www;
                index index.html;
                try_files /js/$1 $uri $uri/ /index.html;
        }

        {{ range $service := .deis_services }}
        {{ if $service }}
        {{ $name := Base $service.Key }}
        {{ if ne $name "api-beta"}}
        {{ if ne $name "app" }}
        location /v3/{{$name}} {
               proxy_redirect off;
               proxy_pass http://{{$name}}/{{$name}};
               proxy_redirect              off;
               proxy_connect_timeout       10s;
               proxy_send_timeout          1200s;
               proxy_read_timeout          1200s;
               proxy_set_header            Upgrade $http_upgrade;
               proxy_set_header            Connection $connection_upgrade;
               #proxy_set_header X-Real-IP $remote_addr;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /api-docs/{{$name}} {
                proxy_redirect off;
                proxy_pass http://{{$name}}/api-docs;
                proxy_redirect off;
                #proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        {{ end }}
        {{ end }}
        {{ end }}
        {{ end }}
        location /health-check {
            default_type 'text/plain';
            access_log off;
            return 200;
        }
    }
}
```

**Comment by carmstrong** [comment]
> Don't think so as this is another app which has only "web" as the process and is working fine without any problems.

Right - I don't mean the application code itself, but rather the app unit. If an app unit is unresponsive (as your #3051 would make it seem), it will stop publishing itself, and the router will forward traffic there for a few seconds until its configuration is updated and it reloads (within 5 seconds after the app stops publishing).

I guess my point is that the router issue could really just be a manifestation of the application units becoming unresponsive.

**Comment by bacongobbler** [comment]
> It works but at times it times out on servicing the requests.

Is this an issue with the stock router as well, or only with this custom router?

I think @carmstrong is onto something. If the underlying containers die, deis/publisher stops publishing them to etcd, which would cause the router to respond with a 503 response (on the stock router). I'd take a look at both the router and the containers, which again could be related to #3501.

**Comment by anoopknayak** [comment]
This happens rarely. I initially thought my modules hung up. but it was momentarily, like the next request I send is processed. I think I will have to save the log then then as now its out of the deis logs(as there has been many requests after that). Anyway I will close this issue for now and open it when i get a log for that
