### ISSUE TITLE
Azure: Client hangs on "Launching app..." but app is successfully launched

### ISSUE THREAD

**Issue by timfpark** [deis/deis#3053]
This seems related to https://github.com/deis/deis/issues/2987 which was closed but I am still seeing this pretty consistently (3 out of 4 times) with Azure in the East US datacenter.  I am pushing the example-nodejs-express example to a 3 member Deis cluster. The builder hangs on the Launching... step but the app is functional and launched.  

$ git push deis master
Counting objects: 5596, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2012/2012), done.
Writing objects: 100% (5596/5596), 1.65 MiB | 0 bytes/s, done.
Total 5596 (delta 3478), reused 5596 (delta 3478)
-----> Node.js app detected
       
       Node engine:         0.10.x
       Npm engine:          unspecified
       Start mechanism:     Procfile
       node_modules source: package.json
       node_modules cached: false
       
       NPM_CONFIG_PRODUCTION=true
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       Resolving node version 0.10.x via semver.io...
       Downloading and installing node 0.10.35...
       
-----> Building dependencies
...
<npm stuff>
...
-----> Building Docker image
remote: Sending build context to Docker daemon 12.97 MB
remote: build context to Docker daemon 
Step 0 : FROM deis/slugrunner
 ---> c14accfba13d
Step 1 : RUN mkdir -p /app
 ---> Running in 0311a4217f15
 ---> 64098d2ad113
Removing intermediate container 0311a4217f15
Step 2 : WORKDIR /app
 ---> Running in 1d1e8bfed9ad
 ---> 9ed4f5473fbc
Removing intermediate container 1d1e8bfed9ad
Step 3 : ENTRYPOINT /runner/init
 ---> Running in 85fca40add0c
 ---> 5d33e3182c2b
Removing intermediate container 85fca40add0c
Step 4 : ADD slug.tgz /app
 ---> 045e08bac40b
Removing intermediate container 8745d0cf7206
Step 5 : ENV GIT_SHA bf450929ac0716c2c21538ba7ef47c588f2407b1
 ---> Running in 72c077e62065
 ---> 8589badbe1fa
Removing intermediate container 72c077e62065
Successfully built 8589badbe1fa
-----> Pushing image to private registry

-----> Launching...

$ deisctl status builder
● deis-builder.service - deis-builder
   Loaded: loaded (/run/fleet/units/deis-builder.service; linked-runtime)
   Active: active (running) since Tue 2015-02-10 20:48:46 UTC; 1h 13min ago
  Process: 11409 ExecStartPost=/usr/bin/docker exec deis-builder /usr/local/bin/push-images (code=exited, status=0/SUCCESS)
  Process: 17239 ExecStartPost=/bin/sh -c echo 'Waiting for builder on 2223/tcp...' && until echo 'dummy-value' | ncat $COREOS_PRIVATE_IPV4 2223 >/dev/null 2>&1; do sleep 1; done (code=exited, status=0/SUCCESS)
  Process: 17229 ExecStartPre=/bin/sh -c docker inspect deis-builder >/dev/null && docker rm -f deis-builder || true (code=exited, status=0/SUCCESS)
  Process: 12004 ExecStartPre=/bin/sh -c IMAGE=`/run/deis/bin/get_image /deis/builder` && docker history $IMAGE >/dev/null || docker pull $IMAGE (code=exited, status=0/SUCCESS)
  Process: 11785 ExecStartPre=/bin/sh -c docker inspect deis-builder-data >/dev/null 2>&1 || docker run --name deis-builder-data -v /var/lib/docker ubuntu-debootstrap:14.04 /bin/true (code=exited, status=0/SUCCESS)
 Main PID: 17238 (sh)
   CGroup: /system.slice/deis-builder.service
           ├─17238 /bin/sh -c IMAGE=`/run/deis/bin/get_image /deis/builder` && docker run --name deis-builder --rm -p 2223:22 --volumes-from=deis-builder-data -c 800 -e EXTERNAL_PORT=2223 -e HOST=$COREOS_PRIVATE_IPV4 --privileged $IMAGE
           └─17259 docker run --name deis-builder --rm -p 2223:22 --volumes-from=deis-builder-data -c 800 -e EXTERNAL_PORT=2223 -e HOST=100.72.102.91 --privileged deis/builder:v1.3.1

Feb 10 22:02:04 n2-cluster-coreos-0 sh[17238]: Did not receive identification string from 100.72.212.83
Feb 10 22:02:15 n2-cluster-coreos-0 sh[17238]: 2015-02-10T22:02:15Z a20b798e24be confd[145]: ERROR Config check failed: exit status 1
Feb 10 22:02:15 n2-cluster-coreos-0 sh[17238]: 2015-02-10T22:02:15Z a20b798e24be confd[145]: ERROR Config check failed: exit status 1
Feb 10 22:02:15 n2-cluster-coreos-0 sh[17238]: 2015-02-10T22:02:15Z a20b798e24be confd[145]: ERROR Config check failed: exit status 1
Feb 10 22:02:19 n2-cluster-coreos-0 sh[17238]: Did not receive identification string from 172.17.42.1
Feb 10 22:02:19 n2-cluster-coreos-0 sh[17238]: Did not receive identification string from 100.72.190.47
Feb 10 22:02:19 n2-cluster-coreos-0 sh[17238]: Did not receive identification string from 100.72.212.83
Feb 10 22:02:20 n2-cluster-coreos-0 sh[17238]: 2015-02-10T22:02:20Z a20b798e24be confd[145]: ERROR Config check failed: exit status 1
Feb 10 22:02:20 n2-cluster-coreos-0 sh[17238]: 2015-02-10T22:02:20Z a20b798e24be confd[145]: ERROR Config check failed: exit status 1
Feb 10 22:02:20 n2-cluster-coreos-0 sh[17238]: 2015-02-10T22:02:20Z a20b798e24be confd[145]: ERROR Config check failed: exit status 1

**Comment by carmstrong** [comment]
@timfpark I'm also seeing this, but only on Azure. I'm also seeing *very* slow pulls from the Deis registry, again only on Azure. So I'm thinking this is performance-related.

**Comment by carmstrong** [comment]
@timfpark We need to make sure the request timeout on the hosted service is sufficiently long - the "Launching..." phase results in no output for several minutes, and many load balancers will close the connection before we're done. We set the timeout to 20 minutes on the router component to accommodate this, but we need to make sure the Azure load balancer is similarly configured.

**Comment by carmstrong** [comment]
@timfpark So this is what we need to do: http://azure.microsoft.com/blog/2014/08/14/new-configurable-idle-timeout-for-azure-load-balancer/

But as far as I can tell, azure-sdk-for-python [doesn't support](https://github.com/Azure/azure-sdk-for-python/blob/dc6d2c5ff4155e18e17cc5285d4818e3e0b3a205/azure/servicemanagement/__init__.py#L1044-L1075) that configuration option yet.

**Comment by carmstrong** [comment]
@timfpark Maybe we're actually supposed to set it on the [Public IP](https://github.com/Azure/azure-sdk-for-python/blob/dc6d2c5ff4155e18e17cc5285d4818e3e0b3a205/azure/servicemanagement/__init__.py#L1015)? This is outside my realm of Azure knowledge.

**Comment by timfpark** [comment]
I think so - they mean the public side of the load balancer (aka Cloud Service) I think.  We need this for the deis endpoint (2222) correct?  I'll try manually and then deploy a couple of apps to see if this is the issue.

**Comment by carmstrong** [comment]
Yep. Haven't tried this yet:

```diff
diff --git a/contrib/azure/azure-coreos-cluster b/contrib/azure/azure-coreos-cluster
index 8f1bf9c..3dd931d 100755
--- a/contrib/azure/azure-coreos-cluster
+++ b/contrib/azure/azure-coreos-cluster
@@ -151,7 +151,7 @@ def network_config(subnet_name=None, port='59913', public_ip_name=None):
     if subnet_name:
         network.subnet_names.append(subnet_name)
     if public_ip_name:
-        network.public_ips.public_ips.append(PublicIP(name=public_ip_name))
+        network.public_ips.public_ips.append(PublicIP(name=public_ip_name, idle_timeout_in_minutes=20))
     if args.deis:
         # create web endpoint with probe checking /health-check
         network.input_endpoints.input_endpoints.append(endpoint_config('web', '80', load_balancer_probe('/health-check', '80', 'http')))
```

**Comment by carmstrong** [comment]
I filed https://github.com/Azure/azure-sdk-for-python/issues/280

**Comment by timfpark** [comment]
I just manually configured the load balancer to 20 minutes and had two successful app deploys in a row. This must be the issue.

**Comment by timfpark** [comment]
I will make a PR on the Azure project per their comments on your issue.

**Comment by carmstrong** [comment]
@timfpark I saw your PR on the Azure SDK, but even once that's merged, we'll have to wait for another release to get the change.

Is changing the timeout on the PublicIP a reasonable workaround for now, or will that not work? Must we configure that on the load-balanced endpoint set?

**Comment by timfpark** [comment]
yes - let's just document the powershell script command to update the LB endpoint with the 20 min timeout for now.  I'll open a PR on the documentation with that.

**Comment by carmstrong** [comment]
> yes - let's just document the powershell script command to update the LB endpoint with the 20 min timeout for now. I'll open a PR on the documentation with that.

Doesn't powershell require Windows? We can only expect users to have the Azure Python CLI installed. Is setting the timeout on the PublicIPs programmatically as I did in my gist not acceptable?

**Comment by timfpark** [comment]
Yes - it requires Windows but I think that is the only way that currently
will work.

Did the PublicIPs approach work for you without the PR I created?  I don't
believe without that PR that it will actually set the timeout on the LB
endpoint.

Tim

**Comment by carmstrong** [comment]
> Yes - it requires Windows but I think that is the only way that currently
> will work.

Yeah, I don't think that's an option. 

> Did the PublicIPs approach work for you without the PR I created?

I'll try it now -- hopefully that works, as it's by far the easiest approach.
