### ISSUE TITLE
501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

### ISSUE THREAD

**Issue by ianblenke** [deis/deis#3058]
As a matter of operational necessity, I now run this on my workstation to stream my aggregate system logs:

    aws ec2 describe-instances --filters Name=tag-value,Values="$LIFECYCLE" | \
    jq -r '.Reservations[].Instances[] | .PublicDnsName' | \
    xargs -P10 -L1 -I% ssh core@% journalctl -f

I pipe this through a grep to watch for error messages:

    | grep --line-buffered -e 'fail\|error'

Normally, that is a trickle, mostly from web crawlers or oversized web posts or other odds and ends.

This morning, I woke up to find this scrolling by:

    501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

Having seen this before, I know this is when confd can't talk to etcd for some reason, so I paniced a bit.

While I can see the IP of the CoreOS host the short message originated from, I had to add `-o short` to get the service that was originating the message.

The culprits were the deis-publisher/deis-router on two of the nodes, and the deis-router on another node.

Restarting those services resolved the messages.

Reminder, I'm running that weirdo v1.0.1 deployment with 4 CoreOS 499 and one CoreOS 584 host with the resultant mixed fleet versions.

Today's task will be to update the older CoreOS nodes to the latest stable.

Is this confd-forgetting-how-to-talk-to-etcd a known problem?

**Comment by bacongobbler** [comment]
I haven't seen that happen before. Are you able to determine why it originally occurred? My first thoughts would be network latency but I have no evidence to back that claim.

**Comment by carmstrong** [comment]
We used to see this occasionally on EC2 when there was significant IO - etcd writes frequently to disk, and would miss heartbeats when there's significant IO activity preventing its writes from occurring within a reasonable time.

Moving the Docker graph to its own EBS volume and moving the etcd snapshot directory to the fast ephemeral disk on EC2 virtually eliminated etcd/fleet issues on EC2.

@ianblenke If you're running v1.0.1, you don't have these improvements. See https://github.com/deis/deis/blob/46c2b6ab29113c8125d0a042cfd60456c5bf6182/contrib/ec2/gen-json.py#L8-L63

**Comment by carmstrong** [comment]
@ianblenke I'm going to close this, as we're fairly confident the provisioning improvements in recent releases have alleviated most etcd/fleet issues. I understand you're running an old version of Deis, so it's likely that a fresh Deis deployment would alleviate some of these issues. If you see these issues on a recent deploy, please feel free to reopen (and/or ping me) so we can address them. Thanks!
