### ISSUE TITLE
Proposal: Deis should support multiple ports for applications

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3069]
This was attempted in #2095, but the implementation is incomplete. Specifically, the PR is lacking:
* Router template logic to handle an application having multiple ports
* Tests wherever possible

Thanks for the great work in starting this, @gust1n! Also pinging @mattapperson as he expressed interest in tackling this.

refs #2044

**Comment by juniorjbn** [comment]
Hi, this issue have any milestone ? or maybe a date to be fixed ? Dies didn't suport multiple ports make de things a lot harder.

**Comment by bacongobbler** [comment]
there's a large design discussion in #2095 if you want to try tackling it, but there is currently no milestone for this.

**Comment by mxk1235** [comment]
are there any plans to support this?  i'm willing to help, but having done no digging through the code, i would require some direction.

wrto #2095 , i think the limitation of supporting only one port is worse than having users provide explicit port configurations for their second/third port.  for example, the graphite dockerfile is a pretty commonly used one, but it is impossible to deploy here.

**Comment by bacongobbler** [comment]
There are some fundamental changes with the routing mesh that would need to be replaced, so I think this would have to be done in a v2 so we don't have to worry too much about backwards compatibility. However, @mxk1235 if you're up for it and think you can do it in a backwards-compatible fashion, a [design document](http://docs.deis.io/en/latest/contributing/design-documents/) describing the architectural changes to the platform would be really helpful. It doesn't necessarily need to show code, but some form of how you'd expect we could hypothetically roll over users from the previous version to the next (as well as the expected user experience with this feature), then we can talk more in-depth on the implementation details in the proposal.

**Comment by mxk1235** [comment]
thanks, i'll try to carve out some time to look into it.  is v2 the next planned major version, or are you working on 1.9 at the moment?

**Comment by bacongobbler** [comment]
we're working on v1.9 at the moment :)

**Comment by robeferre** [comment]
+1

**Comment by bacongobbler** [comment]
Now that Deis Workflow has released a [stable v2.0.0 release](https://deis.com/blog/2016/workflow-stable/), we can start to tackle these problems with Kubernetes. Closing this in favour of deis/workflow#324 since we are not planning on backporting this feature to v1 and to keep the conversation going on over there, where new v2 users can see the feature request. Thanks everyone for all your support! :)
