### ISSUE TITLE
Proposal: Interactive `deis run`

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3070]
@johanneswuerbach had a great start of this in #2239, but we still need to clean it up and get it over the finish line.

**Comment by carmstrong** [comment]
Not sure why I opened this - I think #117 suffices.

**Comment by jwaldrip** [comment]
@carmstrong what can I do to help here? Whatever it needs I will do, this is a major feature needed @Brandfolder

**Comment by bacongobbler** [comment]
@jwaldrip basically we need to hook in `gevent` for django and handle the run logic so we can support long-running requests.
