### ISSUE TITLE
Deis internal service discovery

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3072]
This has been attempted as two different approaches (in #2774 by @aledbf and in #2772 by @PierreKircher). We need to agree on an implementation so the folks interested in helping can coordinate effectively. Specifically:
* What are we using for service discovery? SkyDns?
* How is the service discovery component shipped?

We'll need to come up with an approach here that everyone agrees with.

**Comment by wenzowski** [comment]
Forgive my unfamiliarity with this ecosystem; what makes SkyDNS superior to [consul]? Kubernetes integration?

[consul]: https://github.com/hashicorp/consul

**Comment by bacongobbler** [comment]
we're already tied to etcd so it makes the most sense, architecturally speaking

**Comment by wenzowski** [comment]
makes sense; for some reason I was under the incorrect impression that consul's dns layer was pluggable

**Comment by wenzowski** [comment]
[hdns](https://github.com/mrwilson/helixdns)? Once again, thanks for your patience here.

**Comment by mboersma** [comment]
> HelixDNS serves all its records with a relatively low TTL, that of 5s.

:heart_eyes: Interesting project, small codebase too.

**Comment by aledbf** [comment]
@mboersma rr is not supported in helixdns https://github.com/mrwilson/helixdns/issues/11

**Comment by arkadijs** [comment]
I'm successfully using Registrator and SkyDNS2 to wire infrastructure services started via Fleet. I've put unit files and README into the [gist](https://gist.github.com/arkadijs/d8ee3b479b7bdd69a32c).

**Comment by haf** [comment]
+1 on consul if you're considering something else than etcd in the future - especially nice with the health checks and SWIM implementation.

Following this thread with excitement!

**Comment by ianblenke** [comment]
If we're going to go totally crazy, let me throw Avahi mdns/zeroconf into the ring as well:

https://registry.hub.docker.com/u/ianblenke/avahi/

**Comment by aledbf** [comment]
This could help to increase security to `deis - etcd` interaction https://github.com/kelseyhightower/etcd-talk/tree/master/demo (after etcd 2.x in CoreOS)

**Comment by sstarcher** [comment]
+1 for consul integration, but I understand not wanting to use an additional consensus cluster

**Comment by cgswong** [comment]
Why not [weave](http://weave.works/) instead of SkyDNS2 or flannel (from following the thread)?

**Comment by bacongobbler** [comment]
We're still taking a look at possible candidates, but the winner so far is SkyDNS simply because it's [bundled with kubernetes](https://github.com/deis/deis/issues/4222), making the entire package easy. Ultimately we want something that works with minimal maintenance on our end.

**Comment by ianblenke** [comment]
Just avoid skydock if you're looking at SkyDNS. Operationally, it grows out of control.

From https://github.com/tonistiigi/dnsdock, it is a known problem by others as well:

"AFAIK skydock currently does not have a state machine so the raft log always keeps growing and you have to recreate the server periodically if you wish to run it for a long period of time. Also the startup is very slow because it has to read in all the previous log files."

**Comment by bacongobbler** [comment]
kubernetes has built-in service discovery and as we have announced, v2 is now GA! https://deis.com/blog/2016/workflow-stable/

Closing as resolved. Anyone interested in internal application service discovery can follow  https://github.com/deis/deis/issues/2715. Thanks!
