### ISSUE TITLE
builder: Pass DEBUG through to slugbuilder

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3076]
The builder bin/boot script performs a `set -x` when `DEBUG=true`, but slugbuilder doesn't, which makes it impossible to debug an application's build. 

We need to pass through the debug flag to `image/slugbuilder/builder/build.sh` and `templates/builder`.

**Comment by wenzowski** [comment]
I'm relying on `deis config set DEBUG="*"` to [toggle debug logs](https://github.com/visionmedia/debug).

Would a more explicit `[[ "$DEBUG" == "true" ]] && set -x` in builder help prevent accidentally triggering build debugging?

**Comment by bacongobbler** [comment]
Maybe `DEIS_DEBUG`? More specific IMO

**Comment by wenzowski** [comment]
`DEIS_DEBUG` :+1:

**Comment by bacongobbler** [comment]
fixed in v2
