### ISSUE TITLE
tests: Add tests for buildpacks and BUILDPACK_URL

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3080]
Currently, we can't effectively test buildpacks because `BUILDPACK_URL` always gets the latest from master, and some buildpacks are more fragile than others.

As of #3042 we'll be able to specify tags for buildpacks, so we can write tests which use a known-to-be-working version of a buildpack, testing both buildpacks and `BUILDPACK_URL` (which was broken in #3020).

**Comment by bacongobbler** [comment]
implemented in https://github.com/deis/deis/commit/26dab0490968abaf71cbf87e8d94f7d957172bdc
