### ISSUE TITLE
Proxying web request causes timeout when target is another Deis application

### ISSUE THREAD

**Issue by timfpark** [deis/deis#3081]
One of our projects is attempting to use a fairly well known node.js HTTP proxy module:

https://github.com/nodejitsu/node-http-proxy

to redirect incoming requests to a particular microservice in the backend to consolidate the API surface to one domain and provide application auth services in a central location. The source of what this app is trying to do is here:

https://github.com/nitrogenjs/frontdoor/blob/master/server.js

and the relevant code that this http-proxy module is using to proxy is here:

https://github.com/nodejitsu/node-http-proxy/blob/master/lib/http-proxy/passes/web-incoming.js

(see "stream" function)

This "frontdoor" server and all of the backend microservices are Deis apps. However, when it makes a proxy of a request, the proxy does not reach the backend microservice but times out. Making a direct request on the microservice of the same URL works perfectly.

This works well right now as a set of applications running in a set of load balanced VMs - is there anything special I need to do to make application level proxying like this work in Deis?

**Comment by wenzowski** [comment]
I haven't tried this yet but curious to see how it gets resolved, as I had intended to do something similar. I currently have [request.pipe](https://github.com/request/request) pointed at a few *external* services without issue. Have you confirmed that straight piping from an internal target is working? Just to rule out an issue with `nitrogen-http-proxy`.

I do see socket.io hanging out in there...any chance you have a custom router image running that might be causing this? If no, you will want one based on #2060 or #3089 for sticky support per [docs](http://socket.io/docs/using-multiple-nodes/).

**Comment by bacongobbler** [comment]
hmm, Is there something missing in the router which is causing the request to hang? Maybe some more debugging/research is required here.

**Comment by bacongobbler** [comment]
ping @timfpark, were you able to resolve/debug this issue?

**Comment by timfpark** [comment]
I stopped proxying through Deis and used an external server to do this...
