### ISSUE TITLE
Nginx 5-tuple microflow affinity load balancing to enable arbitrary TCP

### ISSUE THREAD

**Issue by wenzowski** [deis/deis#3087]
For arbitrary TCP connections, preserving affinity of packets in a

> 5-tuple {dest addr, source addr, protocol, dest port, source port}
> <cite>[RFC 6438](https://tools.ietf.org/html/rfc6438#page-6)</cite>

commonly known as a

> Microflow: a single instance of an application-to-application flow of
> packets which is identified by source address, destination address,
> protocol id, and source port, destination port (where applicable).
> <cite>[RFC 2474](https://tools.ietf.org/html/rfc2474#page-5)</cite>

is frequently expected of modern OSI Layer-4 load balancers, and is currently the default for [GCE](https://cloud.google.com/compute/docs/load-balancing/network/target-pools#sessionaffinity) and [Azure](http://azure.microsoft.com/blog/2014/10/30/azure-load-balancer-new-distribution-mode/). As an OSI Layer-7 load balancer, I understand that Nginx terminates HTTP/1.0 "keep-alive" and HTTP/1.1 sessions by default. This can cause problems for mechanisms which take advantage of [Hop-by-hop](http://tools.ietf.org/html/rfc2616#section-13.5.1) headers or analogues to perform a handshake over HTTP that results in the initiation of an alternate protocol. My understanding is that the termination of the HTTP session at the load balancer is the reason [the Nginx WebSockets module](http://nginx.org/en/docs/http/websocket.html) exists.

I hope someone more knowledgeable in the ways of Nginx would be willing to correct me if I misunderstand.

**Comment by wenzowski** [comment]
this seems related to #1315

**Comment by wenzowski** [comment]
There's ip hashing [going on](https://github.com/yaoweibin/nginx_tcp_proxy_module/blob/f2156eff9f6621aaf601eaa8dee40c6820dea0b0/modules/ngx_tcp_upstream_ip_hash_module.c) in the [nginx_tcp_proxy_module](http://yaoweibin.github.io/nginx_tcp_proxy_module/) but more effort is still needed on my part in figuring out exactly how that module works.

**Comment by deis-admin** [comment]
Deis v1 LTS support ends February 13, 2017, and [v1.13.4](https://github.com/deis/deis/releases/tag/v1.13.4) is intended to be the last official release, so I'm closing this.

Please see [Deis Workflow](https://github.com/deis/workflow), the documentation / hub repository for the next-generation PaaS.
