### ISSUE TITLE
builder re-generating SSH keys when jumping hosts

### ISSUE THREAD

**Issue by wenzowski** [deis/deis#3092]
split from #3005

Would the be purely an upgrade pain, or can the builder end up re-generating SSH keys whenever it gets re-scheduled?

**Comment by carmstrong** [comment]
I recall @aledbf storing keys in deis-store so the builder can reuse them even when it moves hosts...

**Comment by aledbf** [comment]
@carmstrong https://github.com/soficom/deis/blob/custom_1.2.0/builder/backup_restore_ssh.go

**Comment by aledbf** [comment]
@carmstrong I need to finish https://github.com/aledbf/deis-go-boot-proposal and this issue will be solved transparently.

**Comment by wenzowski** [comment]
anything the rest of us can do to help @aledbf?

**Comment by bacongobbler** [comment]
this has been fixed in https://github.com/deis/deis/pull/3767.
