### ISSUE TITLE
deis-builder doesn't honor registry protocol

### ISSUE THREAD

**Issue by ineu** [deis/deis#3098]
I'm trying to setup deis on a bare-metal cluster. `deisctl start platform` goes fine except `deis-builder` step. When I check logs, I see following:  https://gist.github.com/ineu/1ba3dec085358f4e6337
Why is it trying to connect to https? `registry` runs http:
```
core@staging-188_40_90_200 ~ $ etcdctl get /deis/registry/protocol
http
```
So connect to https obviously fails.
I'm using Deis version 1.3.1 on CoreOS beta.

I don't have private network on these machines, but I've added extra --insecure-registry option to docker options on every machine.

**Comment by carmstrong** [comment]
> I don't have private network on these machines, but I've added extra --insecure-registry option to docker options on every machine.

You'll also need to bake your own builder with that change, too: https://github.com/deis/deis/blob/3d59fef75033a8dd641eb10c8b4fb2c0867627ef/builder/image/bin/boot#L55

**Comment by ineu** [comment]
@carmstrong Thanks for the tip. But still, why it tries to use https when /deis/registry/protocol is set to http? Is is hardcoded?

**Comment by aledbf** [comment]
>  Is it hardcoded?

Sort of :P (not in deis, just in case). 
By default docker only allows HTTPS connections to registries unless you use `--insecure-registry`.

**Comment by ineu** [comment]
I see. Thank you for explanation guys.
Custom builder works great. I had to build custom docker image from deis/builder because `make -C builder build` didn't work for me. It's not related to this ticket by maybe you could tell what I am doing wrong?
I have go and godep installed. That's what I receive:
```
ineu@rei ~/deis (master*) $ make -C builder build
make: вход в каталог «/home/ineu/deis/builder»
for i in extract-domain extract-types extract-version generate-buildhook get-app-config get-app-values publish-release-controller yaml2json-procfile; do \
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 godep go build -a -v -ldflags '-s' -o image/bin/$i bin/$i.go || exit 1; \
done
bin/extract-domain.go:8:2: cannot find package "github.com/deis/deis/builder" in any of:
	/usr/lib/go/src/github.com/deis/deis/builder (from $GOROOT)
	/home/ineu/deis/Godeps/_workspace/src/github.com/deis/deis/builder (from $GOPATH)
godep: go exit status 1
```
 Maybe there's some configuration step to install required dependencies?

**Comment by mboersma** [comment]
@ineu I think your Deis code isn't in your `$GOPATH`. See http://docs.deis.io/en/latest/installing_deis/quick-start/#get-the-source

I don't think go should be looking under /usr/lib/go/ for deis sources. Maybe try `export GOPATH=/home/ineu/deis`?

**Comment by ineu** [comment]
Yes, it worked. Thank you.

**Comment by aelmadho** [comment]
Hi,

I am having a similar situation, and I am pretty new to go.  I have my GOPATH and all, and I ran:

export GOPATH=<>
export PATH=$PATH:$GOPATH/bin
go get github.com/deis/deis/builder
 go build github.com/deis/deis/builder

I see a builder.a, how do I go about installing the platform with my own version of the builder? and should I not expect an image of some sort?

Any help of any sort is greatly appreciated, as I am not in private IP space.

**Comment by aelmadho** [comment]
Or, how would I configure the deis registry to just run HTTPS? I tried changing the etcd k/v and restart the registry, but that did not work.

**Comment by mboersma** [comment]
You will want to `go get github.com/deis/deis` so you have the entire codebase locally. See http://docs.deis.io/en/latest/contributing/hacking/#fork-the-deis-repository for details. Then you'll want to provision a Deis cluster, get it running, make your local modifications to builder, and then do `make -C builder/ build deploy` to build and deploy your changed deis-builder component.

**Comment by aelmadho** [comment]
Thanks, I just figured it out, my first exposure to go!!! thanks, and by the way am loving it! thnx
