### ISSUE TITLE
Installing deis client on OSX 10.7.5

### ISSUE THREAD

**Issue by jwarzech** [deis/deis#3102]
I get the follow error when trying to run the deis client:

```
Error loading Python lib '/var/folders/jc/b21x4jns6sqb053yyv9slzsc0000gn/T/_MEI6doEMT/.Python': dlopen(/var/folders/jc/b21x4jns6sqb053yyv9slzsc0000gn/T/_MEI6doEMT/.Python, 10): Symbol not found: ___sincos_stret
  Referenced from: /var/folders/jc/b21x4jns6sqb053yyv9slzsc0000gn/T/_MEI6doEMT/.Python
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/jc/b21x4jns6sqb053yyv9slzsc0000gn/T/_MEI6doEMT/.Python
```

**Comment by mboersma** [comment]
The binary clients from `curl -sSL http://deis.io/deis-cli/install.sh | sh` are built on a Mac OS X 10.9 system. These are really self-contained archives with python and the necessary libs and .py files. The binaries work fine on 10.9 and 10.10, but I'm not surprised to see a dynamic linker error on 10.7.

As a workaround, you can build a binary `deis` client on your system with `make -C client/ build`, or run `deis` locally like a [developer](http://docs.deis.io/en/latest/contributing/hacking/#install-the-client) would.

**Comment by mboersma** [comment]
@jwarzech were you able to get a `deis` client running on your Mac OS X 10.7.5 machine?
