### ISSUE TITLE
Questions on increase-nf_conntrack-connections.service

### ISSUE THREAD

**Issue by ineu** [deis/deis#3105]
There's service `increase-nf_conntrack-connections.service` installed by Deis. On new CoreOS installation it fails because there's no conntrack module loaded by default in CoreOS 557. I have some questions/proposals regarding it. Here's what (as it seems to me) should be changed, please let me know if I misunderstand the purpose of this service.

1. Conntrack connections limit should persist after reboot. This can be done by either installing `increase-nf_conntrack-connections.service` or by adding following to `write_files:` section:

```
# /etc/sysctld.d/conntrack.conf
net.netfilter.nf_conntrack_max=262144
```

2. Same for module `nf_conntrack`. It should be either loaded in the service before calling `sysctl` or added as a file:

```
# /etc/modules-load.d/conntrack.conf
nf_conntrack
```

**Comment by carmstrong** [comment]
> On new CoreOS installation it fails because there's no conntrack module loaded by default in CoreOS 557.

That's news to me! We'll need to verify that it fails and investigate the workarounds.

**Comment by mboersma** [comment]
Confirmed, the service is failing now:
```console
core@deis-01 ~ $ systemctl status increase-nf_conntrack-connections.service
● increase-nf_conntrack-connections.service - Increase the number of connections in nf_conntrack. default is 65536
   Loaded: loaded (/etc/systemd/system/increase-nf_conntrack-connections.service; static)
   Active: failed (Result: exit-code) since Fri 2015-02-20 21:15:16 UTC; 2h 1min ago
 Main PID: 771 (code=exited, status=255)

Feb 20 21:15:16 deis-01 systemd[1]: Starting Increase the number of connections in nf_conntrack. default is 65536...
Feb 20 21:15:16 deis-01 systemd[1]: increase-nf_conntrack-connections.service: main process exited, code=exited, status=255/n/a
Feb 20 21:15:16 deis-01 systemd[1]: Failed to start Increase the number of connections in nf_conntrack. default is 65536.
Feb 20 21:15:16 deis-01 systemd[1]: Unit increase-nf_conntrack-connections.service entered failed state.
Feb 20 21:15:16 deis-01 sh[771]: sysctl: cannot stat /proc/sys/net/netfilter/nf_conntrack_max: No such file or directory
Hint: Some lines were ellipsized, use -l to show in full.
core@deis-01 ~ $ cat /etc/os-release 
NAME=CoreOS
ID=coreos
VERSION=522.6.0
```
