### ISSUE TITLE
CI: Docker networking issue?

### ISSUE THREAD

**Issue by johanneswuerbach** [deis/deis#3107]
Currently building docker containers on CI fails with the following error message:
 `Failed to fetch http://archive.ubuntu.com/***.deb  Could not resolve 'archive.ubuntu.com'`

Example CI run: https://ci.deis.io/job/test-integration/2134/console
Maybe this could resolve the issue? http://serverfault.com/a/642984

**Comment by mboersma** [comment]
Wow, nice research. I was just about to flush the docker cache and reboot, but then the test-integration jobs got past it. 

I think that post may be on to something. If this happens again I'll try those troubleshooting steps.

**Comment by mboersma** [comment]
This hasn't occurred in months. I'm going to close this, but let's revisit if it starts to haunt CI again.
