### ISSUE TITLE
Invalid registry endpoint error

### ISSUE THREAD

**Issue by achannarasappa** [deis/deis#3112]
I am getting the invlaid registry error even though I have the registry I am trying to use added to `/etc/systemd/system/docker.service.d/50-insecure-registry.conf`. The custom registry was added by modifying  `contrib/coreos/user-data` prior to provisioning the cluster

When I check the configuration file, the registry seems to be there
```sh
$ ssh -i ~/.ssh/deis core@0.0.0.0
core@0.0.0.0 $ cat /etc/systemd/system/docker.service.d/50-insecure-registry.conf
[Service]
EnvironmentFile=/etc/environment_proxy
Environment="DOCKER_OPTS=--insecure-registry docker-registry.example.com:5000 --insecure-registry 10.0.0.0/8 --insecure-registry 172.16.0.0/12 --insecure-registry 192.168.0.0/16 --insecure-registry 100.64.0.0/10"
```

However if I try to push an application
```sh
$ deis apps:create myapp
$ git push deis master
Counting objects: 759, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (574/574), done.
Writing objects: 100% (759/759), 960.35 KiB | 0 bytes/s, done.
Total 759 (delta 366), reused 445 (delta 163)

-----> Building Docker image
remote: Sending build context to Docker daemon  1.79 MB
remote: build context to Docker daemon 
Step 0 : FROM docker-registry.example.com:5000/exm-laravel
2015/02/18 22:29:07 Invalid registry endpoint https://docker-registry.example.com:5000/v1/: Get https://docker-registry.example.com:5000/v1/_ping: EOF. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry docker-registry.example.com:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/docker-registry.example.com:5000/ca.crt
To ssh://git@deis.app.example.com:2222/myapp.git
 * [new branch]      master -> master
```

Is there somewhere else that needs to be edited to fix the insecure registry issue that I am missing?

**Comment by gabrtv** [comment]
@achannarasappa in order for the builder to push to the custom registry, you must also add an `insecure-registry` flag to: https://github.com/deis/deis/blob/master/builder/image/bin/boot#L56-L57 See [Customizing Builder](http://docs.deis.io/en/latest/customizing_deis/builder_settings/#using-a-custom-builder-image) documentation for more details.

**Comment by carmstrong** [comment]
@achannarasappa Did you resolve this? As @gabrtv said, you'll need a custom builder if your private network doesn't fall in one of the ranges we include out-of-the-box.

**Comment by carmstrong** [comment]
Closing. Please let us know if you still need help!
