### ISSUE TITLE
Deis should check if container's port is accepting connections before adding it to the pool

### ISSUE THREAD

**Issue by glogiotatidis** [deis/deis#3115]
Sometimes you need to run commands to setup your application before you run the web server. E.g. you may want to run `./manage.py syncdb` in a django app to apply database migrations before you run  `gunicorn`.

Deis should check if the exposed port of the container accepts connections, before adding the container to the pool.  Otherwise the container gets into the pool, router sends traffic to it and nginx returns 502 (bad gateway) because no server listens to the exposed port of a second or two.

Is this something that can go into [IsPublishableApp](https://github.com/deis/deis/blob/master/publisher/server/publisher.go#L104)?

(Apologies if this has being already reported. I've this memory but I cannot find the issue)

**Comment by gvilarino** [comment]
:+1: I think I'm crashing into this same problem, on another scenario:

Node app that relies on a MongoDB hosted on a remote DB cloud (MongoLab). When I launch the app everything seems fine but after a some minutes al requests from my app to the DB are just getting back to my app (in the container).

**Comment by carmstrong** [comment]
> Is this something that can go into IsPublishableApp?

I certainly suppose so! I think having publisher check if the port is listening before actually publishing the app is a great place for this. :+1:

**Comment by gvilarino** [comment]
This module/feature could be called Parker Lewis™ :joy:
