### ISSUE TITLE
Problems with Deis in vagrant installation

### ISSUE THREAD

**Issue by phspagiari** [deis/deis#3117]
Hi guys,

I am having some problems / errors when installing deis in vagrant mode. I follow step-by-step the vagrant guide (http://docs.deis.io/en/latest/installing_deis/vagrant/) and the platform installation (http://docs.deis.io/en/latest/installing_deis/install-platform/#install-deis-platform)  and everything works fine, but when I ran **deisctl start platform** I got some "random" errrors, like:

```shell
# deisctl start platform
● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●

Storage subsystem...
deis-store-monitor.service: activating/start-pre
could not find unit: deis-store-monitor.service
```
But the unit exists at ~/.deis/units/deis-store-monitor.service

If I start again, I got another error:

```shell
# deisctl start platform
● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●

Storage subsystem...
deis-store-monitor.service: active/running
INFO client.go:297: Response 500 Internal Server Error from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Set /_coreos.com/fleet/job/deis-store-daemon.service/target-state}, retrying in 100ms
deis-store-daemon.service: active/running
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 100ms
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 200ms
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 400ms
deis-store-metadata.service: activating/start-pre
could not find unit: deis-store-metadata.service
```
And if I keep starting the deis platform, I got errors in anothers services:

```shell
# deisctl start platform
● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●

Storage subsystem...
deis-store-monitor.service: active/running
deis-store-daemon.service: active/running
deis-store-metadata.service: activating/start-pre
deis-store-metadata.service: active/running
deis-store-gateway.service: activating/start-pre

# deisctl start platform
● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●

Storage subsystem...
deis-store-monitor.service: active/running
deis-store-daemon.service: active/running
deis-store-metadata.service: active/running
could not find unit: deis-store-gateway.service

# deisctl start platform
● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●

Storage subsystem...
deis-store-monitor.service: active/running
deis-store-daemon.service: active/running
deis-store-metadata.service: active/running
deis-store-gateway.service: activating/start-pre
could not find unit: deis-store-gateway.service
```
But I cannot pass the store-gateway service. 

I already tested the access of etcd and fleet and even curl at the http://127.0.0.1:4001:

```shell
core@deis-1 ~ $ etcdctl ls
/deis

core@deis-1 ~ $ fleetctl list-machines
MACHINE		IP		METADATA
4ea93b64...	172.17.8.101	-
6c692f33...	172.17.8.100	-
7a4b5d77...	172.17.8.102	-

core@deis-1 ~ $ curl http://127.0.0.1:4001
404 page not found

core@deis-1 ~ $ curl http://127.0.0.1:7001
404 page not found
```
I apreciate any ideas of how I fix this. I am starting this environment in order to starting to contribute / develop deis. I already have a deis platform running with 3 coreos servers, I got this problem only on vagrant mode.

**Comment by mboersma** [comment]
> could not find unit: deis-store-monitor.service

That's odd, because it seems to find some of the unit files. "deisctl install" looks for unit files in these directories, in this order:
- the $DEISCTL_UNITS environment variable, if set
- $HOME/.deis/units
- /var/lib/deis/units

Is it possible you have `$DEISCTL_UNITS` set to a bad location? Otherwise, I would try `deisctl refresh-units --help` and then `deisctl refresh-units` to see if that rectifies things. 

If you're doing development on the Deis codebase, I think this is the most convenient:
```export DEISCTL_UNITS=$GOPATH/src/github.com/deis/deis/deisctl/units```

**Comment by carmstrong** [comment]
These sporadic "unit not found" errors point to issues with etcd/fleet in your cluster:
```
INFO client.go:297: Response 500 Internal Server Error from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Set /_coreos.com/fleet/job/deis-store-daemon.service/target-state}, retrying in 100ms
deis-store-daemon.service: active/running
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 100ms
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 200ms
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 400ms
deis-store-metadata.service: activating/start-pre
could not find unit: deis-store-metadata.service
```

Check the etcd/fleet journal on your hosts to see what's happening. It sounds like fleet died on at least one of your hosts. `journalctl -u etcd` and `journalctl -u fleet` should shed some light.

**Comment by phspagiari** [comment]
So @mboersma I didnt set this variable, the deis is looking for the units at $HOME/.deis/units indeed. But I look more deep into the problem of etcd/fleet and after some tests I found that some of etcd servers of the cluster is not working.

I start to test the etcd externally setting/getting keys pointing directly to each node of etcd and in some cases the node didnt return a valid response.

Cases:
1) Set a key to node1 and get from node1 = OK
2) Set a key to node2 = FAIL
3) Set a key from node3 = FAIL
4) Set a key from node1 and get from node2 and node3 = OK
5) Get a key from node2 again = FAIL

So it seems like a local network issue into etcd clusters / fleet clusters. The most weird part is that after each vagrant up / vagrant destroy the symptoms change (Example: Set a key in node1 and node2 and get from node1, 2 and 3 its possible but I cant Set a key from node3).

I will check the journal of the etcd / fleet for more infos. Thanks for everything @mboersma  @carmstrong

**Comment by mboersma** [comment]
I think my advice was off-base, as your comments seem to indicate it's a networking / etcd issue as @carmstrong suspected. Let us know what you find out.

**Comment by carmstrong** [comment]
> The most weird part is that after each vagrant up / vagrant destroy the symptoms change

Are you setting a fresh discovery URL with `make discovery-url` before each `vagrant up`? Your situation  is symptomatic of you not having an actual cluster, but just one machine in its own "cluster". That's why only one is accepting writes.

**Comment by phspagiari** [comment]
@carmstrong yes, I'm setting a new discovery url before each vagrant up. 

So after a new vagrant destroy / vagrant up (with a fresh discovery url) the etcd started to working normally, I can get and set from all clusters and everything is ok.

The journal of etcd doesnt show anything wrong, just some INFO logs about "heartbeat timeout reached".

But the journal of fleet have a lot of errors:

```shell
Feb 20 18:49:25 deis-2 fleetd[960]: ERROR engine.go:180: Engine leadership acquisition failed: timeout reached
Feb 20 18:49:25 deis-2 fleetd[960]: INFO client.go:291: Failed getting response from http://localhost:4001/: cancelled
Feb 20 18:49:25 deis-2 fleetd[960]: INFO client.go:291: Failed getting response from http://localhost:4001/: cancelled
Feb 20 18:49:28 deis-2 fleetd[960]: INFO client.go:291: Failed getting response from http://localhost:4001/: cancelled
Feb 20 18:49:33 deis-2 fleetd[960]: INFO client.go:297: Response 500 Internal Server Error from http://localhost:4001/ unusable
Feb 20 18:49:33 deis-2 fleetd[960]: ERROR client.go:213: Unable to get result for {Update /_coreos.com/fleet/machines/4ea93b64f3134b218412170bc276017f/object}, retrying in 100ms
```
And its even more weird because the errors is exactly when fleet are making calls to etcd through localhost.

**Comment by carmstrong** [comment]
> The journal of etcd doesnt show anything wrong, just some INFO logs about "heartbeat timeout reached".

That's definitely an issue - the hosts can't communicate with each other. Are you using the Vagrantfile in the project root? Something isn't right with your environment. It could also be that running 3 VMs is taxing your machine to its limits. Do you have 8GB+ RAM?

**Comment by phspagiari** [comment]
@carmstrong the Virtualbox + Vagrant are running in a CentOS server with 4 Cores and 16GB of ram. Before you asking, its running on a server because in my company is not allowed to use vms into developers machine :smile: 

Anyway in my coreos cluster (QA env) I got this error and everything works fine o.O

I will make another test and start the units directly from the coreos instead using deis start platform.

**Comment by carmstrong** [comment]
> Anyway in my coreos cluster (QA env) I got this error and everything works fine o.O

If it happens sporadically it's not disastrous, but if you're seeing nothing but heartbeat timeouts on the initial deploy of the platform, something is certainly wrong.

High disk iowait can also prevent etcd from snapshotting in a timely fashion.

**Comment by phspagiari** [comment]
So I "solved" the problem yesterday... stil I cant understand why the deis cannot locate some sporadic units, I solved the problem logging into a node of coreos and starting all the services that ```deis start platform``` starts manually with fleet. 

Me and @lorieri saw that the problem is indeed performance, the machine have 8gb ram and 4 cpus but the ceph (storage-gateway) take a long time to start and the ```deis start platform``` got a timeout. Starting manually there is no timeout so all good.

After this we upgrade de instance to 4 real cpu cores and 16gb ram and everything looks fine.

I only have no answer for the ```could not find unit``` error.

**Comment by bacongobbler** [comment]
I've found that too. My laptop with 8GB cannot handle running 3 nodes on Virtualbox, however it seems to work for @carmstrong and @mboersma quite nicely since they have 16GB laptops.

As for `could not find unit: deis-store-gateway.service`, we allowed deis-store-gateway to be scalable, which means that in reality it should be looking for `deis-store-gateway@1`: https://github.com/deis/deis/pull/2929

I'd inspect your deisctl version and inspect if you're up to date :)

**Comment by carmstrong** [comment]
> which means that in reality it should be looking for deis-store-gateway@1

Good catch.

**Comment by carmstrong** [comment]
> As for could not find unit: deis-store-gateway.service, we allowed deis-store-gateway to be scalable, which means that in reality it should be looking for deis-store-gateway@1

Actually, we didn't merge that until this release, so I don't think we're scaling gateway in the wild.

@phspagiari I'm going to close this for now as there's unfortunately not much for us to go on, and it sounds like you've solved the immediate issue in your environment, although it's still unclear what caused the drop in performance.

**Comment by ainux4mrvce** [comment]
$deisctl install platform
every time i tries to install deisctl platform i get this error message 
o/p
Error: Missing platform domain, use:
deisctl config platform set domain=

i allready use the command : "$deisctl config platform set domain=local3.deisapp.com".

**Comment by phspagiari** [comment]
Try to get the key from etcd after you set with deisctl config and see if you are really setting the domain or you have a problem with your etcd cluster. Also I think this is not the right issue for your problem.
