### ISSUE TITLE
store: Use separate disks for store-daemon and store-monitor

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3124]
See https://github.com/deis/deis/pull/3123#issuecomment-75377578 and http://ceph.com/docs/master/start/hardware-recommendations/

**Comment by wenzowski** [comment]
Does such a large refactor go hand in hand with multiple OSDs per host? Enough to take advantage of an ec2 `hs1.8xlarge` for instance?

**Comment by carmstrong** [comment]
> Does such a large refactor go hand in hand with multiple OSDs per host?

That's probably a level of complexity we wouldn't by default support out of the box, although I'd be happy to review/test a PR which added optional support for multiple OSDs.

**Comment by carmstrong** [comment]
Note that the complexity here is due to the use of `deis-store-monitor-data` and `deis-store-daemon-data`, which are Docker volumes and thus live on the same volume. Ideally we want to drop these, but that complicates the upgrade path.

**Comment by bacongobbler** [comment]
closing as irrelevant for [v2](https://deis.com/blog/2016/workflow-stable/).
