### ISSUE TITLE
bug(go): some binaries are not static

### ISSUE THREAD

**Issue by aledbf** [deis/deis#3131]
```
docker run -it deis/cache:v1.3.1 /bin/bash
root@ce60d047494f:/app# ldd /app/bin/boot
	linux-vdso.so.1 =>  (0x00007fffc7f07000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f792e126000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f792dd60000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f792e348000)
```

workaround: `CGO_ENABLED=0 go build -a -installsuffix cgo`

https://github.com/golang/go/issues/9344
https://github.com/golang/go/issues/9369

**Comment by mboersma** [comment]
Programs which import the net package and need to be statically linked won't be in go 1.4, but it appears the `-installsuffix` is a sufficient workaround. Glad you found this @aledbf.
