### ISSUE TITLE
Provide a way to install packages when using the buildpack workflow

### ISSUE THREAD

**Issue by ashaffer** [deis/deis#3139]
I have a node.js application that I would like to use with libreoffice and unoconv.  I would like to use the standard node buildpack and git push workflow because that's how all of our other applications are set up, but as far as I can tell there is no way for me to install these two packages (aside perhaps from compiling them from source in a custom buildpack) without creating my own Dockerfile and discarding the benefits and simplicity of the buildpack workflow.

It seems like all I would really need is the ability to add a set of commands to the end of the shim.dockerfile file in the slugbuilder, or replace it entirely using an environment variable to specify a replacement file or file to be cat'd onto the end.

This would significantly improve the power and flexibility of deis while still maintaining simple buildpack workflows for common applications.

**Comment by bacongobbler** [comment]
I can see how this would be beneficial, but maybe there's a way we can contribute to heroku's buildpack first and see what they have to say. In general, Heroku's answer has been that you should fork their buildpack if you want a custom environment.

**Comment by ashaffer** [comment]
Ya, the main problem with that is that it requires you to build everything from source, since buildpacks cannot use apt-get, which is much slower and more difficult generally.

**Comment by ashaffer** [comment]
I have created an alternate version of the builder component that implements this available here:

https://registry.hub.docker.com/u/ashaffer/builder/

To use it simply include a file in the root of your repository called shim.dockerfile.  For instance to install unoconv/libreoffice you might do: 

```
USER root
RUN apt-get update
RUN apt-get install -qy libreoffice-script-provider-python unoconv
USER slug
```

**Comment by bacongobbler** [comment]
Alternatively, I was notified that https://github.com/ddollar/heroku-buildpack-apt exists. Along with heroku-buildpack-multi you might be able to achieve the same effect.

**Comment by bacongobbler** [comment]
@ashaffer since the recommended cross-platform workflow is to use heroku-buildpack-apt in tandem with heroku-buildpack-multi, I think it's safe to close this now. Thanks!
