### ISSUE TITLE
pass env vars to buildpack

### ISSUE THREAD

**Issue by wenzowski** [deis/deis#3145]
I should be able to `deis config:set NODE_MODULES_CACHE=false` when using [heroku-buildpack-nodejs](https://github.com/heroku/heroku-buildpack-nodejs/tree/v64/).

Currently, when my build cache gets borked (an unfortunately a common occurrence with npm) I have to delete and recreate the app to solve the problem, which results in downtime and loss of old images.

**Comment by bacongobbler** [comment]
@wenzowski config vars which you set via `config:set` are present in the environment: https://github.com/deis/deis/pull/960

**Comment by wenzowski** [comment]
something else afoot here then; guess I'll have to fork the buildpack & find out
