### ISSUE TITLE
SIGTERM on exceeded memory quota

### ISSUE THREAD

**Issue by wenzowski** [deis/deis#3147]
This request aims for parity with [OOM Killer](http://linux-mm.org/OOM_Killer) behaviour.

The fact that Heroku does a straight SIGKILL on [r15](https://devcenter.heroku.com/articles/error-codes#r15-memory-quota-vastly-exceeded) ram exhaustion has always baffled me, seeing as [r14](https://devcenter.heroku.com/articles/error-codes#r14-memory-quota-exceeded) is logged but never signalled to the offending container. If this was fixed and I'm woefully clueless please do let me know.

I propose the same signalling from #3086 be applied to ram exhaustion. For now, I don't think we need to set hard and soft limit triggers (unless these are already in place), but simply kill with timeout. I'm assuming that if coreos itself runs out of ram OOM Killer will do the expected rapid-fire SIGTERM && SIGKILL.

I don't see this as an excuse to avoid crash-only design patterns, but knowing why a crash has happened at the app level sure does help debug it. Signals are my friends.

**Comment by carmstrong** [comment]
> For now, I don't think we need to set hard and soft limit triggers (unless these are already in place), but simply kill with timeout.

I'm a little unclear on the proposal - how do you think we should accomplish this?

**Comment by wenzowski** [comment]
Perhaps with `KillSignal` and `TimeoutStopSec` documented in [systemd.kill](http://www.freedesktop.org/software/systemd/man/systemd.kill.html)? Haven't fully thought this through yet.

**Comment by wenzowski** [comment]
Hmm, I think this is already happening as of #3091 since `KillSignal=SIGTERM` by default and `KillMode` is documented to respect `TimeoutStopSec` between sending `KillSignal` and the final `SIGKILL`.

systemd :sunglasses:
