### ISSUE TITLE
Rolling restarts with deis ps:restart

### ISSUE THREAD

**Issue by wenzowski** [deis/deis#3148]
with `deis ps:restart` proposed in #3110 would love to do the following sequentially for each upstream
- mark an nginx upstream as [down](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#down)
- reboot that upstream
- remove the down flag from nginx

distinct from #1988 I think

**Comment by wenzowski** [comment]
this is probably one of those simple requests that requires significant code to solve, hmm @carmstrong?

should this be accomplished with separate rest calls to the api to reboot specifica instances, or one api call and handle the cascading reboot in py?

**Comment by carmstrong** [comment]
> this is probably one of those simple requests that requires significant code to solve, hmm @carmstrong?

Probably. I think it should be a client command as you suggest, as well as a controller API endpoint. As to how this coordination is actually achieved, I'm not sure. The controller would have to set something in etcd to signify that an app should be restarted. Then, the router could (somehow) recognize this key, do what it needs to do, and then remove the key when it's done. The controller would then return to the client.

However, I'm just spitballing here, and that really doesn't feel clean to me.

**Comment by wenzowski** [comment]
The ability to mark the nginx upstream as down across all routers necessitates an edtcd key. Great thing to acknowledge.

I'm going to have to think about this a little more before I take a stab at it.

**Comment by bacongobbler** [comment]
does `deis ps:restart web.1` work for you?

**Comment by wenzowski** [comment]
If it is, could be entirely client code: poll `deis ps` for `web.1` to come back up.

**Comment by bacongobbler** [comment]
closing as resolved
