### ISSUE TITLE
Error in upgrading-deis.rst

### ISSUE THREAD

**Issue by aledbf** [deis/deis#3155]
In the docs this is the procedure to do a manual update:

> $ ssh core@<server ip>
> $ sudo su
> $ echo GROUP=stable > /etc/coreos/update.conf
> $ systemctl unmask update-engine.service
> $ systemctl start update-engine.service
> $ update_engine_client -update
> $ systemctl stop update-engine.service
> $ systemctl mask update-engine.service
> $ reboot

this is wrong (at least now).
Why? https://github.com/coreos/bugs/issues/262

the boot partition is updated after the reboot so if the update-engine service is disabled it will not run and update the boot flags.
Only after this output from `journalctl -u update-engine.service`
`[0226/232543:INFO:update_attempter.cc(674)] Updating boot flags...`
is safe to disable the update-engine service. (after the next update it will use the updated version)

This means that https://github.com/deis/deis/blob/master/contrib/coreos/user-data.example#L25 must be remove so after the reboot with the update update-engine.service will start automatically

reference https://github.com/coreos/bugs/issues/262

**Comment by carmstrong** [comment]
Thanks @aledbf. So we have to somehow allow it to run once after a reboot before disabling it? That sounds difficult :(
