### ISSUE TITLE
Curly braces in Procfile are unescaped

### ISSUE THREAD

**Issue by ianblenke** [deis/deis#3157]
The Deis scheduler handling of Dockerfile + Procfile is now broken.

We had deployed a cluster with Deis v1.0.1 following the guidance in [gh#2545](https://github.com/deis/deis/issues/2545) for the Dockerfile + Procfile behavior at the time.

For that, we had the Dockerfile CMD start a script that prepares application environment variables. If it detects $1 as the proctype ("start web" would pass "web", for example) and would run foreman start on that proctype, otherwise it would execute $@ outright.

This was logical. The Dockerfile had a CMD, and Deis honored it. It wasn't pretty, but it wasn't horrible either.

We just deployed a cluster with Deis v1.3.1, which no longer honors the CMD script defined in the Dockerfile.

Instead, it seems that [pr2605](https://github.com/deis/deis/pull/2605) has the scheduler scanning the procfile to find the command to run.

This is conceptually the correct behavior. However, the generated unit isn't being executed in a pure shell context.

Case in point, here's our Procfile:

    web: bundle exec puma -t ${PUMA_MIN_THREADS:-16}:${PUMA_MAX_THREADS:-16} -w ${PUMA_WORKERS:-8} -p ${PORT:-3000} -e ${RAILS_ENV:-development} --preload

And here is the unit that Deis v1.3.1's fleet scheduler now generates:

    [Unit]
    Description=myapp_v5.web.1
    
    [Service]
    ExecStartPre=/bin/sh -c "IMAGE=$(etcdctl get /deis/registry/host 2>&1):$(etcdctl get /deis/registry/port 2>&1)/,myapp:v5; docker pull $IMAGE"
    ExecStartPre=/bin/sh -c "docker inspect myapp_v5.web.1 >/dev/null 2>&1 && docker rm -f myapp_v5.web.1 || true"
    ExecStart=/bin/sh -c "IMAGE=$(etcdctl get /deis/registry/host 2>&1):$(etcdctl get /deis/registry/port 2>&1)/myapp:v5; port=$(docker inspect -f '{{range $k, $v := .ContainerConfig.ExposedPorts }}{{$k}}{{end}}' $IMAGE | cut -d/ -f1) ; docker run --name myapp.web.1 -m 3g   -P -e PORT=$port $IMAGE bash -c 'bundle exec puma -t ${PUMA_MIN_THREADS:-16}:${PUMA_MAX_THREADS:-16} -w ${PUMA_WORKERS:-8} -p ${PORT:-3000} -e ${RAILS_ENV:-development} --preload'"
    ExecStop=/usr/bin/docker rm -f myapp_v5.web.1
    TimeoutStartSec=20m
    RestartSec=5
    Restart=on-failure

The shell script quoting looks right. But this is a systemd service. As we all know from painful first-hand experience, those variable expansions happen differently there.

When I look at the running process that is failing to start using ps, I see this:

    docker run --name myapp.web.1 -m 3g -P -e PORT=3000 10.113.1.220:5000/myapp:v5 bash -c bundle exec puma -t : -w  -p  -e  --preload

That's right. All of those ${} expansions are being eaten by systemd.

My problem here is that now I can't simply backslash the $'s in the Procfile and not break my other environments (nor should I have to).

I still have this stuff running on developer workstations using docker-expose/fig, which correctly runs the CMD entrypoint script of the Dockerfile to start the container there.

I also have this deployed to that old deis v1.0.1 cluster, which likewise would break if I do the same.

Instead, I now have to change my Procfile to look like this:

    web: ./bin/web.sh

And in bin/web.sh in the project I now have this:

    #!/bin/bash
    set -eo pipefail
    
    # re-export the environment variables for the next process
    export $(env | cut -d= -f1)
    
    proc="exec bundle exec puma -t ${PUMA_MIN_THREADS:-16}:${PUMA_MAX_THREADS:-16} -w ${PUMA_WORKERS:-8} -p ${PORT:-3000} -e ${RAILS_ENV:-development} --preload"
    
    if [[ -x /run.sh ]]; then
      /run.sh "$proc"
    else
      $proc
    fi

This "hides" those variables from systemd and lets them evaluate in a shell context as they should be.

It would be great if we could default to running the Dockerfile CMD by default as it has been in the past, but allow that to be overridden by a later deis client command for a given app and proctype if the devops so desires.

As mentioned above, I've worked around this. No doubt others WILL encounter this problem, and this WILL be a support issue for someone other than myself, it's just a matter of time.

You've already partially reverted this behavior at least for heroku buildpacks in [gh#2673](https://github.com/deis/deis/pull/2673).

What does OpDemand think?

**Comment by gabrtv** [comment]
@ianblenke agree that this is broken. Exploring a fix now..

**Comment by gabrtv** [comment]
@ianblenke it turns out that we cannot fix this through normal quoting/escaping as systemd is going to interpolate the curly braces regardless.  We are exploring an alternate `run` implementation that will not suffer from this same limitation.  Closing for now.
