### ISSUE TITLE
Deis cannot build git submodules 

### ISSUE THREAD

**Issue by ianblenke** [deis/deis#3160]
We have a couple of projects that use submodules. The precise SHA1 is important to us.

deis-builder uses this in `./builder/image/templates/builder' to generate the tarball that is sent to the docker slugbuilder:

    git archive $GIT_SHA | tar -xmC $TMP_DIR

Unfortunately, git archive strips the `.git` directory, and we need that for our submodules.

@bacongobbler mentioned [gh1094](https://github.com/deis/deis/issues/1094) as related to this, and rightfully explained that submodules are also an issue on Heroku.

To add .git, I've had to modify our deis/builder image to do this instead:

    git ls-files --cached --full-name --no-empty-directory -z $GIT_SHA | tar cf - -T - --null |  tar -xmC $TMP_DIR

It would be nice to somehow flag an app to selectively include .git, as no doubt others will run into this limitation.

Thanks!

**Comment by bacongobbler** [comment]
@ianblenke considering that this is a duplicate, could you please append this comment to #1094 so that we can track submodule support for Deis in one bug? Thanks.

**Comment by ianblenke** [comment]
ok! reposted there, closing this issue in favor of #1094
