### ISSUE TITLE
List environment variables in alphabetical order

### ISSUE THREAD

**Issue by ashaffer** [deis/deis#3161]
It's kind of trivial, but it'd be really nice if the environment variables were listed in alphabetical order by default by 'deis config'.

**Comment by bacongobbler** [comment]
Are they not sorted already? https://github.com/deis/deis/blob/master/client/deis.py#L1005 seems to indicate that it should be. :)

**Comment by ashaffer** [comment]
Hah, you are right.  Not sure what I was thinking sorry.  Closing.
