### ISSUE TITLE
(azure) builder doesn't start

### ISSUE THREAD

**Issue by gvilarino** [deis/deis#3163]
Running `1.3.1` on a 5-box Windows Azure cluster (followed [this guide](https://github.com/chanezon/azure-linux/blob/master/coreos/deis/README.md))

So yes, I'm using the non-standard builder `deis/builder:v1.1.1-azure`; as the guide explains.

When I run `deisctl start platform` it never ends, and my `deisctl list` shows:

```
UNIT				MACHINE				LOAD	ACTIVE		SUB
deis-builder.service		9778e1cc.../10.215.60.17	loaded	activating	start-post
deis-cache.service		98ed7c79.../10.215.76.76	loaded	active		running
deis-controller.service		d8703fba.../10.215.60.28	loaded	activating	running
deis-database.service		0d7474f9.../10.175.234.32	loaded	active		running
deis-logger.service		3862510f.../10.215.54.83	loaded	active		running
deis-logspout.service		0d7474f9.../10.175.234.32	loaded	active		running
deis-logspout.service		3862510f.../10.215.54.83	loaded	active		running
deis-logspout.service		9778e1cc.../10.215.60.17	loaded	active		running
deis-logspout.service		98ed7c79.../10.215.76.76	loaded	active		running
deis-logspout.service		d8703fba.../10.215.60.28	loaded	active		running
deis-publisher.service		0d7474f9.../10.175.234.32	loaded	active		running
deis-publisher.service		3862510f.../10.215.54.83	loaded	active		running
deis-publisher.service		9778e1cc.../10.215.60.17	loaded	active		running
deis-publisher.service		98ed7c79.../10.215.76.76	loaded	active		running
deis-publisher.service		d8703fba.../10.215.60.28	loaded	active		running
deis-registry@1.service		3862510f.../10.215.54.83	loaded	active		running
deis-router@1.service		9778e1cc.../10.215.60.17	loaded	active		running
deis-router@2.service		98ed7c79.../10.215.76.76	loaded	active		running
deis-router@3.service		d8703fba.../10.215.60.28	loaded	active		running
deis-store-daemon.service	0d7474f9.../10.175.234.32	loaded	active		running
deis-store-daemon.service	3862510f.../10.215.54.83	loaded	active		running
deis-store-daemon.service	9778e1cc.../10.215.60.17	loaded	active		running
deis-store-daemon.service	98ed7c79.../10.215.76.76	loaded	active		running
deis-store-daemon.service	d8703fba.../10.215.60.28	loaded	active		running
deis-store-gateway.service	0d7474f9.../10.175.234.32	loaded	active		running
deis-store-metadata.service	0d7474f9.../10.175.234.32	loaded	active		running
deis-store-metadata.service	3862510f.../10.215.54.83	loaded	active		running
deis-store-metadata.service	9778e1cc.../10.215.60.17	loaded	active		running
deis-store-metadata.service	98ed7c79.../10.215.76.76	loaded	active		running
deis-store-metadata.service	d8703fba.../10.215.60.28	loaded	active		running
deis-store-monitor.service	0d7474f9.../10.175.234.32	loaded	active		running
deis-store-monitor.service	3862510f.../10.215.54.83	loaded	active		running
deis-store-monitor.service	9778e1cc.../10.215.60.17	loaded	active		running
deis-store-monitor.service	98ed7c79.../10.215.76.76	loaded	active		running
deis-store-monitor.service	d8703fba.../10.215.60.28	loaded	active		running
deis-store-volume.service	0d7474f9.../10.175.234.32	loaded	active		running
deis-store-volume.service	3862510f.../10.215.54.83	loaded	active		running
deis-store-volume.service	9778e1cc.../10.215.60.17	loaded	active		running
deis-store-volume.service	98ed7c79.../10.215.76.76	loaded	active		running
deis-store-volume.service	d8703fba.../10.215.60.28	loaded	active		running
```

My builder journal shows the following.

```
-- Logs begin at Fri 2015-02-27 20:28:59 UTC. --
Feb 28 19:39:26 dos-deis-coreos-3 systemd[1]: Stopped deis-builder.
Feb 28 20:42:46 dos-deis-coreos-3 systemd[1]: Starting deis-builder...
Feb 28 20:42:48 dos-deis-coreos-3 sh[2222]: time="2015-02-28T20:42:48Z" level="fatal" msg="Error response from daemon: no such id: deis/builder:v1.1.1-azure"
Feb 28 20:42:48 dos-deis-coreos-3 sh[2222]: Pulling repository deis/builder
Feb 28 20:42:50 dos-deis-coreos-3 sh[2222]: dc38c8d993de: Pulling image (v1.1.1-azure) from deis/builder
Feb 28 20:42:50 dos-deis-coreos-3 sh[2222]: dc38c8d993de: Pulling image (v1.1.1-azure) from deis/builder, endpoint: https://registry-1.docker.io/v1/
Feb 28 20:42:50 dos-deis-coreos-3 sh[2222]: dc38c8d993de: Pulling dependent layers
Feb 28 20:42:50 dos-deis-coreos-3 sh[2222]: 511136ea3c5a: Download complete
Feb 28 20:42:50 dos-deis-coreos-3 sh[2222]: 3620ce89267d: Pulling metadata
Feb 28 20:42:52 dos-deis-coreos-3 sh[2222]: 3620ce89267d: Pulling fs layer
Feb 28 20:43:00 dos-deis-coreos-3 sh[2222]: 3620ce89267d: Download complete
...
Feb 28 20:45:58 dos-deis-coreos-3 sh[2222]: dc38c8d993de: Pulling metadata
Feb 28 20:45:59 dos-deis-coreos-3 sh[2222]: dc38c8d993de: Pulling fs layer
Feb 28 20:46:05 dos-deis-coreos-3 sh[2222]: dc38c8d993de: Download complete
Feb 28 20:46:05 dos-deis-coreos-3 sh[2222]: dc38c8d993de: Download complete
Feb 28 20:46:05 dos-deis-coreos-3 sh[2222]: Status: Downloaded newer image for deis/builder:v1.1.1-azure
Feb 28 20:46:05 dos-deis-coreos-3 sh[2573]: Error: No such image or container: deis-builder
Feb 28 20:46:05 dos-deis-coreos-3 sh[2584]: Waiting for builder on 2223/tcp...
Feb 28 20:46:19 dos-deis-coreos-3 sh[2583]: 2015-02-28T20:46:19Z 2b79f754f30c confd[74]: ERROR Config check failed: exit status 1
Feb 28 20:46:19 dos-deis-coreos-3 sh[2583]: 2015-02-28T20:46:19Z 2b79f754f30c confd[74]: ERROR Config check failed: exit status 1
Feb 28 20:46:19 dos-deis-coreos-3 sh[2583]: builder: waiting for confd to write initial templates...
Feb 28 20:46:24 dos-deis-coreos-3 sh[2583]: 2015-02-28T20:46:24Z 2b79f754f30c confd[105]: ERROR Config check failed: exit status 1
Feb 28 20:46:24 dos-deis-coreos-3 sh[2583]: 2015-02-28T20:46:24Z 2b79f754f30c confd[105]: ERROR Config check failed: exit status 1
Feb 28 20:46:24 dos-deis-coreos-3 sh[2583]: builder: waiting for confd to write initial templates...
Feb 28 20:46:29 dos-deis-coreos-3 sh[2583]: 2015-02-28T20:46:29Z 2b79f754f30c confd[118]: ERROR Config check failed: exit status 1
Feb 28 20:46:29 dos-deis-coreos-3 sh[2583]: 2015-02-28T20:46:29Z 2b79f754f30c confd[118]: ERROR Config check failed: exit status 1
Feb 28 20:46:29 dos-deis-coreos-3 sh[2583]: builder: waiting for confd to write initial templates...
```

The thing is, I **was** able to run deis properly in a 3-box cluster a couple of weeks ago. Since I'm getting ready for production, I had to re-start the whole cluster with 5 boxes and I'm hitting this brick wall.

I guess this is related with #3057 and #3085 but I'm not entirely sure, I'm sort of new in the deis world.

Maybe @carmstrong or @aledbf can lend a hand? I'm very close to a deadline and I really need my deis up and running again :)

**Comment by carmstrong** [comment]
> Running 1.3.1 on a 5-box Windows Azure cluster (followed this guide)
> 
> So yes, I'm using the non-standard builder deis/builder:v1.1.1-azure; as the guide explains.

That documentation is old - you're using the builder for Deis v1.1.1, with the rest of the components on Deis v1.3.1. Please use the official documentation at http://docs.deis.io/en/latest/installing_deis/azure.html

@chanezon Perhaps we could remove your documentation and point users to the official Deis documentation now that it's merged?

**Comment by gvilarino** [comment]
Well, to tell you the truth, I've worked with both set of docs and followed a hybrid (DNS settings weren't working with @chanezon 's article instructions). I have tried the default builder (i.e.: not setting the builder to `deis/builder:v1.1.1-azure`) with similar results (although I didn't pay that close attention to the logs in that scenario). I'm gonna try this now and get back with more info, also with `deis-debug-logs`.

**Comment by carmstrong** [comment]
> I'm gonna try this now and get back with more info, also with deis-debug-logs.

Sounds good - your logs should hopefully show something. If you see the `builder: waiting for confd to write initial templates`, one of the other components that builder depends on is showing as "running" but isn't actually working properly.

**Comment by gvilarino** [comment]
Ok, this time, for some reason I'm not sure of, it ended up working properly, after about 30 minutes of `start-post` state in the `builder`.

If it's of any value, here are gists with my logs:
* [gist with `deis-debug-logs` output](https://gist.github.com/gvilarino/b3b75453b9ce2834110a). The only `etcd`-related error I'm seeing is `Feb 28 23:25:02 dos-deis-coreos-3 fleetd[750]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: cancelled`.
* [gist with `deisctl journal builder` output](https://gist.github.com/gvilarino/523328ac4bf728880087)

I'll close this since it's working, but if anyone can confirm my logs look good it'd be great.

**Comment by strider4560** [comment]
This is my first time trying to install and run deis and my startup is hanging at the builder too on digital ocean. My deis-debug-logs shows that requests to http://127.0.0.1:4001 are failing. I've tried destroying and starting from scratch several times with the same problem.

**Comment by gvilarino** [comment]
@strider4560 I also had errors in requests to `http://127.0.0.1:4001` but they end after a while. I assume they are just temporal things until the whole deis fleet is up and nodes can reach each other.

Also, in my case, I just had to wait for a LONG time (30+ minutes) for `deis platform start` to finish. Use `deisctl journal builder` to see if there are relevant `ERROR` entries.

**Comment by chanezon** [comment]
@carmstrong done.
https://github.com/chanezon/azure-linux/blob/master/coreos/deis/README.md

**Comment by carmstrong** [comment]
> Also, in my case, I just had to wait for a LONG time (30+ minutes) for deis platform start to finish.

That's longer than normal, although not unheard of - the builder does a lot of heavy lifting and is the longest in its start-post phase. As long as you don't see it restart, it's fine.

> My deis-debug-logs shows that requests to http://127.0.0.1:4001 are failing. I've tried destroying and starting from scratch several times with the same problem.

@strider4560 Are you following our Digital Ocean deployment documentation? That sounds like etcd/fleet are having issues on that host. Please open a separate issue if you can't get things running.

**Comment by carmstrong** [comment]
> done.

Thanks!
