### ISSUE TITLE
Unable to start arbitrary Procfile entries

### ISSUE THREAD

**Issue by simpsora** [deis/deis#3165]
This is a similar/duplicate issue to https://github.com/deis/deis/issues/2874.

I'm running Deis 1.3.1, and am unable to get Procfile entries other than `web` to work at all.

`Procfile`:

```
item-1-watcher: jruby $WATCHER_JAVA_OPTS -S bin/rake watch WATCH_TYPE=item INDEX_SUFFIX=1
worker: jruby -Eutf-8 $SIDEKIQ_JAVA_OPTS -S bin/sidekiq -r config/boot.rb -c ${SIDEKIQ_WORKERS:-2} -q item-1,1 -q item-2,1 -q comment-1,1 -q comment-2,1
web: jruby -S bin/rackup -p $PORT
```
`git push`:

```
$ git push deis master
...
-----> Ruby app detected
...
-----> Discovering process types
       Procfile declares types -> item-1-watcher, item-2-watcher, comment-1-watcher, comment-2-watcher, worker, web
       Default process types for Ruby -> rake, console, web
...
```

`deis info`:

```
$ deis info
=== dewey-api Application
{
  "updated": "2015-03-01T22:37:21UTC",
  "uuid": "250639c3-6fc9-48ab-8d7d-2e8823484689",
  "created": "2015-03-01T22:32:06UTC",
  "url": "...",
  "owner": "rosssimpson",
  "id": "dewey-api",
  "structure": {
    "web": 1
  }
}

=== dewey-api Processes

--- web:
web.1 up (v8)

...
```

And, finally, the problem:

`deis scale`:

```
$ deis scale worker=1
Scaling processes... but first, coffee!
400 BAD REQUEST
Container type worker does not exist in application
```

I would have thought this would be fixed in https://github.com/deis/deis/pull/2909, but it doesn't appear to have been.

Am I missing something?  Any suggestions would be appreciated.

**Comment by rjocoleman** [comment]
I had a similar issue, turns out my upgrade to 1.3.1 hadn't upgraded. Are you certain the units you're running are from 1.3.1?

```
$ deisctl config platform get version
$ docker ps # will show you whats actually running on a single node
```

**Comment by bacongobbler** [comment]
your worker has curly braces. @ianblenke reported similar failures in #3157.

**Comment by simpsora** [comment]
Ah!  Thanks @rjocoleman, you are absolutely right.  My "upgrade" to 1.3.1, wasn't.

The `deisctl` command you reference doesn't work on my new (really 1.3.1) cluster:

```
$ deisctl config platform get version
Error: 100: Key not found (/deis/platform/version) [77167]
```

But, `docker ps` does, and now shows 1.3.1 since I've built a new cluster.

@bacongobbler, I'll have to fight the battle of curly braces next.  Thanks for pointing that out!

Closing this issue, since it's not really an issue.

**Comment by carmstrong** [comment]
> The deisctl command you reference doesn't work on my new (really 1.3.1) cluster:

That's expected, although I agree it's confusing. That key is only used to override the Deis version in `/etc/deis-release`, typically when upgrading the platform (as the file is only written on initial provision).
