### ISSUE TITLE
unable to provision AWS ec2 

### ISSUE THREAD

**Issue by apps4u** [deis/deis#3166]
HI Ive tried to provision ec2 cluster today but Im getting a error that Ive not be able to track down . I use EC2 all the time so I know there templates but I still can not find the error in the generated template . Ive also just dumped the provision scripts output to file and I can upload and run on AWS but when calling the provision script I get this error.

    ✹  ec2 (develop *=) 👽  ./provision-ec2-cluster.sh baas
    usage: aws [-h] [-v] {elb,as,ec2} ...
    aws: error: invalid choice: 'cloudformation' (choose from 'elb', 'as', 'ec2')

**Comment by bacongobbler** [comment]
if you run `bash -x provision-ec2-cluster.sh baas`, do you get any more verbose information?

**Comment by carmstrong** [comment]
@apps4u What version of the `aws-cli` are you using? Sounds like it's old.

Mine is:
```console
$ aws --version
aws-cli/1.4.3 Python/2.7.6 Darwin/14.1.0
```

**Comment by apps4u** [comment]
yes here is the output 

http://laravel.io/bin/DeyGx <http://laravel.io/bin/DeyGx>


Jason Kristian | Director | Apps 4 U Pty Ltd.
ph: +61 075699 8109
mob: +61 0411 389 392
e: Jason Kristian <mailto:jasonk@apps4u.com.au>

**Comment by apps4u** [comment]
✹  laravel-five (develop *=) 👽   aws --version
0.2.5


Jason Kristian | Director | Apps 4 U Pty Ltd.
ph: +61 075699 8109
mob: +61 0411 389 392
e: Jason Kristian <mailto:jasonk@apps4u.com.au>

**Comment by apps4u** [comment]
I run the gen-json.py > cloud.json  to get the out put from the provision script I then used AWS web console and was able to start and provision the CloudFormation cluster just by uploading the cloud.json file and setting the correct SSH key . and Ive just install platform and its running ok so I think it might be the AWS client tool that might have changed . IF thats any help.


Jason Kristian | Director | Apps 4 U Pty Ltd.
ph: +61 075699 8109
mob: +61 0411 389 392
e: Jason Kristian <mailto:jasonk@apps4u.com.au>

**Comment by carmstrong** [comment]
> so I think it might be the AWS client tool that might have changed

Yes, I bet you find that things work just fine if you update your `aws-cli`.

**Comment by apps4u** [comment]
My fault Ive just noticed that some installed pip AWS and it was overriding pip awscli which is at version awscli (1.7.5)

s I’ll uninstall pip uninstall aws should fix it .


Jason Kristian | Director | Apps 4 U Pty Ltd. 
ph: +61 075699 8109
mob: +61 0411 389 392
e: Jason Kristian <mailto:jasonk@apps4u.com.au>

**Comment by carmstrong** [comment]
> s I’ll uninstall pip uninstall aws should fix it .

Sounds good. Closing, as this isn't a Deis issue. Let us know if that doesn't resolve things.
