### ISSUE TITLE
deis-builder 1.4.0 won't start

### ISSUE THREAD

**Issue by arkadijs** [deis/deis#3180]
In `builder/image/slugbuilder/builder/install-buildpacks`:

    git clone --branch $buildpack_commit --depth 1 $buildpack_url $BUILDPACK_INSTALL_PATH/$buildpack_name
    download_buildpack https://github.com/ddollar/heroku-buildpack-multi.git         6e79094

Commit `6e79094` exists but its not a branch:

    $ git clone --branch 6e79094 --depth 1 https://github.com/ddollar/heroku-buildpack-multi.git 
    Cloning into 'heroku-buildpack-multi'...
    warning: Could not find remote branch 6e79094 to clone.
    fatal: Remote branch 6e79094 not found in upstream origin
    Unexpected end of command stream

Log:

    Mar 04 09:14:24 ip-10-21-1-146.ec2.internal sh[21707]: Step 8 : RUN /tmp/builder/install-buildpacks
    Mar 04 09:14:24 ip-10-21-1-146.ec2.internal sh[21707]: ---> Running in 627d64fdf78c
    Mar 04 09:14:24 ip-10-21-1-146.ec2.internal sh[21707]: time="2015-03-04T09:14:24Z" level="info" msg="+job allocate_interface(627d64fdf78ce5f585840ff694bff29f7b2b8f195f112c4d03b971ce397e41c2)"
    Mar 04 09:14:24 ip-10-21-1-146.ec2.internal sh[21707]: time="2015-03-04T09:14:24Z" level="info" msg="-job allocate_interface(627d64fdf78ce5f585840ff694bff29f7b2b8f195f112c4d03b971ce397e41c2) = OK (0)"
    Mar 04 09:14:24 ip-10-21-1-146.ec2.internal sh[21707]: time="2015-03-04T09:14:24Z" level="info" msg="+job log(start, 627d64fdf78ce5f585840ff694bff29f7b2b8f195f112c4d03b971ce397e41c2, d7fb68605e2e)"
    Mar 04 09:14:24 ip-10-21-1-146.ec2.internal sh[21707]: time="2015-03-04T09:14:24Z" level="info" msg="-job log(start, 627d64fdf78ce5f585840ff694bff29f7b2b8f195f112c4d03b971ce397e41c2, d7fb68605e2e) = OK (0)"
    Mar 04 09:14:24 ip-10-21-1-146.ec2.internal sh[21707]: time="2015-03-04T09:14:24Z" level="info" msg="+job logs(627d64fdf78ce5f585840ff694bff29f7b2b8f195f112c4d03b971ce397e41c2)"
    Mar 04 09:14:24 ip-10-21-1-146.ec2.internal sh[21707]: Cloning into '/tmp/buildpacks/heroku-buildpack-multi.git'...
    Mar 04 09:14:24 ip-10-21-1-146.ec2.internal sh[21707]: warning: Could not find remote branch 6e79094 to clone.
    Mar 04 09:14:24 ip-10-21-1-146.ec2.internal sh[21707]: fatal: Remote branch 6e79094 not found in upstream origin
    Mar 04 09:14:24 ip-10-21-1-146.ec2.internal sh[21707]: Unexpected end of command stream

**Comment by bacongobbler** [comment]
I'm seeing this, but it's a false negative. In [install-buildpacks](https://github.com/deis/deis/blob/master/builder/image/slugbuilder/builder/install-buildpacks#L11-L22) we first try to shallow clone the buildpack to speed up the clone process, which only works for branches and tags. If that fails, a full clone is performed instead.

To illustrate, this script works just fine for me:

```
$ docker run -itv $PWD/install-buildpacks:/install-buildpacks ubuntu bash
$ apt-get update && apt-get install -yq git
...
$ /install-buildpacks
loning into '/tmp/buildpacks/heroku-buildpack-multi.git'...
warning: Could not find remote branch 6e79094 to clone.
fatal: Remote branch 6e79094 not found in upstream origin
Unexpected end of command stream
Cloning into '/tmp/buildpacks/heroku-buildpack-multi.git'...
remote: Counting objects: 132, done.
remote: Total 132 (delta 0), reused 0 (delta 0), pack-reused 132
Receiving objects: 100% (132/132), 19.59 KiB | 0 bytes/s, done.
Resolving deltas: 100% (23/23), done.
Checking connectivity... done.
Cloning into '/tmp/buildpacks/heroku-buildpack-ruby.git'...
...
```

**Comment by bacongobbler** [comment]
is there something else that's causing builder to not start or was this something you're seeing in the logs?

**Comment by arkadijs** [comment]
Cannot reproduce currently - tried 5 times with different cluster sizes. I didn't captured the full log from that run, unfortunately. But, I noticed, that after all units are started (including deis-registry@1.service) deisctl won't exit:

    core@ip-10-21-1-176 ~ $ systemctl status install-deis

    ● install-deis.service - Install Deis
       Loaded: loaded (/etc/systemd/system/install-deis.service; static; vendor preset: disabled)
       Active: activating (start) since Thu 2015-03-05 10:55:57 UTC; 32min ago
     Main PID: 884 (sh)
       CGroup: /system.slice/install-deis.service
               ├─ 884 /usr/bin/sh -c curl -sSL --retry 5 --retry-delay 2 (cut)/deis.sh | sh
               ├─ 886 sh
               └─1234 /opt/bin/deisctl start platform

    Mar 05 10:58:24 ip-10-21-1-176.ec2.internal sh[884]: deis-store-gateway@1.service: activating/start-post
    Mar 05 10:59:13 ip-10-21-1-176.ec2.internal sh[884]: deis-store-gateway@1.service: active/running
    Mar 05 10:59:17 ip-10-21-1-176.ec2.internal sh[884]: deis-store-volume.service: active/running
    Mar 05 10:59:17 ip-10-21-1-176.ec2.internal sh[884]: Logging subsystem...
    Mar 05 10:59:21 ip-10-21-1-176.ec2.internal sh[884]: deis-logger.service: activating/start-pre
    Mar 05 10:59:31 ip-10-21-1-176.ec2.internal sh[884]: deis-logger.service: active/running
    Mar 05 10:59:37 ip-10-21-1-176.ec2.internal sh[884]: deis-logspout.service: activating/start-pre
    Mar 05 11:00:51 ip-10-21-1-176.ec2.internal sh[884]: deis-logspout.service: active/running
    Mar 05 11:00:51 ip-10-21-1-176.ec2.internal sh[884]: Control plane...
    Mar 05 11:00:52 ip-10-21-1-176.ec2.internal sh[884]: could not find unit: deis-docker-registry.service

It bugs be because I have additional post-install activities down the script.

**Comment by bacongobbler** [comment]
There are some edge cases where deisctl won't properly exit during `start platform` (such as with the error you see there). Could you please put that in a separate bug?

**Comment by arkadijs** [comment]
Opened a separate issue. Please close this one, I'll reopen in case the problem arises again.
