### ISSUE TITLE
deis auth:cancel is not deleting the user account 

### ISSUE THREAD

**Issue by smothiki** [deis/deis#3190]
[stacktrace failed call] (https://gist.github.com/smothiki/9820dd7486e9654e3c77)

Its actually throwing 500 but we never caught it .

```
mothikis-MacBook-Pro:tests smothiki$ deis auth:cancel
Please log in again in order to cancel this account
username: test
password: 
Logged in as test
Cancel account "test" at http://deis.smothiki.io? (y/N) y
Account cancelled
```

**Comment by bacongobbler** [comment]
looks related to https://github.com/deis/deis/pull/2865 in a sense, though really the client should've caught that 500 error
