### ISSUE TITLE
deisctl fail to start platform

### ISSUE THREAD

**Issue by jeffkit** [deis/deis#3199]
The vagrant version, after finish the installation, start  in a long time, end up with an error.

$deisctl start platform
● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●

Storage subsystem...
deis-store-monitor.service: activating/start-pre                                 
deis-store-monitor.service: active/running                                 
deis-store-daemon.service: activating/start-pre                                 
deis-store-daemon.service: active/running                                 
deis-store-metadata.service: activating/start-pre                                 
deis-store-metadata.service: active/running                                 
deis-store-gateway@1.service: activating/start-pre                                 
deis-store-gateway@1.service: activating/start-post                                 
deis-store-gateway@1.service: active/running                                 
deis-store-volume.service: active/running                                 
Logging subsystem...
deis-logger.service: activating/start-pre                                 
deis-logger.service: active/running                                 
deis-logspout.service: activating/start-pre                                 
deis-logspout.service: active/running                                 
Control plane...
deis-cache.service: activating/start-pre                                 
deis-database.service: activating/start-pre                                 
deis-registry@1.service: activating/start-pre                                 
deis-controller.service: activating/start-pre                                 
deis-cache.service: active/running                                 
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 100ms
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 100ms
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 100ms
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 200ms
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 200ms
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 200ms
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 400ms
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 400ms
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 400ms
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 800ms
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 800ms
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: too many redirects
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 800ms

After that, I remove images from VirtualBox, and retry from command: Vagrant up, I found I can not perform 'deisctl config' any more, the same error as above:

$vagrant up
Bringing machine 'deis-01' up with 'virtualbox' provider...
Bringing machine 'deis-02' up with 'virtualbox' provider...
Bringing machine 'deis-03' up with 'virtualbox' provider...
==> deis-01: Running triggers before up...
==> deis-01: Importing base box 'coreos-stable'...
==> deis-01: Matching MAC address for NAT networking...
==> deis-01: Checking if box 'coreos-stable' is up to date...
==> deis-01: Setting the name of the VM: deis_deis-01_1425519703403_62905
==> deis-01: Clearing any previously set network interfaces...
==> deis-01: Preparing network interfaces based on configuration...
    deis-01: Adapter 1: nat
    deis-01: Adapter 2: hostonly
==> deis-01: Forwarding ports...
    deis-01: 22 => 2222 (adapter 1)
==> deis-01: Running 'pre-boot' VM customizations...
==> deis-01: Booting VM...
==> deis-01: Waiting for machine to boot. This may take a few minutes...
    deis-01: SSH address: 127.0.0.1:2222
    deis-01: SSH username: core
    deis-01: SSH auth method: private key
    deis-01: Warning: Connection timeout. Retrying...
==> deis-01: Machine booted and ready!
==> deis-01: Setting hostname...
==> deis-01: Configuring and enabling network interfaces...
==> deis-01: Running provisioner: file...
==> deis-01: Running provisioner: shell...
    deis-01: Running: /var/folders/54/6_m3psqs7xjgp6560z4r2jtm0000gp/T/vagrant-shell20150305-1999-13dsrzq.sh
==> deis-01: Running provisioner: shell...
    deis-01: Running: inline script
==> deis-02: Running triggers before up...
==> deis-02: Importing base box 'coreos-stable'...
==> deis-02: Matching MAC address for NAT networking...
==> deis-02: Checking if box 'coreos-stable' is up to date...
==> deis-02: Setting the name of the VM: deis_deis-02_1425519729818_37754
==> deis-02: Fixed port collision for 22 => 2222. Now on port 2200.
==> deis-02: Clearing any previously set network interfaces...
==> deis-02: Preparing network interfaces based on configuration...
    deis-02: Adapter 1: nat
    deis-02: Adapter 2: hostonly
==> deis-02: Forwarding ports...
    deis-02: 22 => 2200 (adapter 1)
==> deis-02: Running 'pre-boot' VM customizations...
==> deis-02: Booting VM...
==> deis-02: Waiting for machine to boot. This may take a few minutes...
    deis-02: SSH address: 127.0.0.1:2200
    deis-02: SSH username: core
    deis-02: SSH auth method: private key
    deis-02: Warning: Connection timeout. Retrying...
==> deis-02: Machine booted and ready!
==> deis-02: Setting hostname...
==> deis-02: Configuring and enabling network interfaces...
==> deis-02: Running provisioner: file...
==> deis-02: Running provisioner: shell...
    deis-02: Running: /var/folders/54/6_m3psqs7xjgp6560z4r2jtm0000gp/T/vagrant-shell20150305-1999-2jmh3b.sh
==> deis-02: Running provisioner: shell...
    deis-02: Running: inline script
==> deis-03: Running triggers before up...
==> deis-03: Importing base box 'coreos-stable'...
==> deis-03: Matching MAC address for NAT networking...
==> deis-03: Checking if box 'coreos-stable' is up to date...
==> deis-03: Setting the name of the VM: deis_deis-03_1425519756366_10917
==> deis-03: Fixed port collision for 22 => 2222. Now on port 2201.
==> deis-03: Clearing any previously set network interfaces...
==> deis-03: Preparing network interfaces based on configuration...
    deis-03: Adapter 1: nat
    deis-03: Adapter 2: hostonly
==> deis-03: Forwarding ports...
    deis-03: 22 => 2201 (adapter 1)
==> deis-03: Running 'pre-boot' VM customizations...
==> deis-03: Booting VM...
==> deis-03: Waiting for machine to boot. This may take a few minutes...
    deis-03: SSH address: 127.0.0.1:2201
    deis-03: SSH username: core
    deis-03: SSH auth method: private key
    deis-03: Warning: Connection timeout. Retrying...
==> deis-03: Machine booted and ready!
==> deis-03: Setting hostname...
==> deis-03: Configuring and enabling network interfaces...
==> deis-03: Running provisioner: file...
==> deis-03: Running provisioner: shell...
    deis-03: Running: /var/folders/54/6_m3psqs7xjgp6560z4r2jtm0000gp/T/vagrant-shell20150305-1999-1j6h5t4.sh
==> deis-03: Running provisioner: shell...
    deis-03: Running: inline script
jeff@jeffkit-2~/projects/gocode/src/github.com/deis/deis$ssh-keygen -q -t rsa -f ~/.ssh/deis -N '' -C deis
/Users/jeff/.ssh/deis already exists.
Overwrite (y/n)? n
jeff@jeffkit-2~/projects/gocode/src/github.com/deis/deis$ssh-add ~/.vagrant.d/insecure_private_key
Identity added: /Users/jeff/.vagrant.d/insecure_private_key (/Users/jeff/.vagrant.d/insecure_private_key)
jeff@jeffkit-2~/projects/gocode/src/github.com/deis/deis$export DEISCTL_TUNNEL=172.17.8.100
jeff@jeffkit-2~/projects/gocode/src/github.com/deis/deis$deisctl config platform set sshPrivateKey=/Users/jeff/.vagrant.d/insecure_private_key
Error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

**Comment by carmstrong** [comment]
@jeffkit etcd/fleet errors on Vagrant are usually caused by running VMs on a machine which can't handle the load. What are the specs of this host?

**Comment by jeffkit** [comment]
My machine is Macbook Pro, system is OSX Yosemite 10.10.1

**Comment by carmstrong** [comment]
> My machine is Macbook Pro, system is OSX Yosemite 10.10.1

Right, but how much memory?

**Comment by jeffkit** [comment]
@carmstrong 8GB for total.

**Comment by carmstrong** [comment]
> 8GB for total.

That's probably not enough. I suspect there's a lot of swapping on that machine, resulting in io thrashing which kills etcd/fleet. Try evaluating Deis on Digital Ocean or even EC2, if you can afford it. Testing on DO is only a few dollars.

**Comment by matti** [comment]
Yep, 8 gb is not enough. You can get Deis up and running with vagrant if you reboot your machine, kill everything that's extra, hold your breath and avoid touching anything, but doing anything else beyond that just requires more than 8 gb. See the Activity Monitor on how memory consumption goes up.
