### ISSUE TITLE
Add Email Sending Functionality to Deis

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/deis#3200]
It would be really useful if deis could send emails. You could do things like reset passwords, setup invite only invitation, email admins when a component or apps fails or errors appear in the log. It could also notify admins when new users or apps are created.

This would also be simple to setup. It would entail adding a STMP server component in a docker container, [such as this postfix container here](https://registry.hub.docker.com/u/linuxkonsult/postfix/), the deis controller being wired up to use it, and possibly having the user set up a [SPF policy](https://en.wikipedia.org/wiki/Sender_Policy_Framework) to authorize deis to email using their deis domain.

**Comment by daemonza** [comment]
I second this, would be nice to have the password resets, and invite mails etc. I track the app/component fails with Datadog and get emails/hipchat alerts from that.

**Comment by carmstrong** [comment]
@Joshua-Anderson I think this is a great candidate for a third-party component that we'd link to in https://github.com/deis/deis/blob/master/contrib/README.md

Note also that #3174 is proposing adding LDAP or other third-party authentication integrations. This would probably eliminate the need for emailing users directly, no?

**Comment by Joshua-Anderson** [comment]
Yes, if the user was using LDAP. It could still be useful for emailing users about app issues. Also, even if some users switch to LDAP, I'm sure that many groups will still use built in auth and require password reset and invitations.

It also could be a feature that could be enabled if desired.

Another option is you setup deis controller for email, and have users set up the stmp server itself, possibly suppling instructions for installing the stmp server on deis.

**Comment by azurewraith** [comment]
>  email admins when a component or apps fails or errors appear in the log

or when your Ceph cluster is in HEALTH_WARN state :+1:

**Comment by Joshua-Anderson** [comment]
Closing because this isn't going to land in V1 and [monitor for V2](https://github.com/deis/monitor) supports email alerts, filling the major use case.
