### ISSUE TITLE
Create a config variable to set the number of Docker images to keep for an app

### ISSUE THREAD

**Issue by mastephens** [deis/deis#3209]
Running and pushing many different updates to a Deis environment can add up to a lot of Docker images.  I have no reason for keep ALL Docker images for an app along the way.   

It would be nice if we could add a config var like DIMAGE_CNT=3 that would force the builder to always remove any Docker images for an application that are not the most recent 3 images.

The goal is to prevent 100 different images from accumulating that haven't been used in weeks and are just consuming disk space.

**Comment by bacongobbler** [comment]
sounds like a dupe/proposal for #3144. Let's keep this over there :)

**Comment by bacongobbler** [comment]
> In my case I don't seem to have issues with intermediate images not being cleaned up, it its purely from an archival issue for the final image for each build. I am using a fork of a Heroku Buildpack for NodeJs for our builds. We can run upwards of 20+ builds a day, with these old images hanging around we are having to manually purge the older ones pretty frequently to keep from running out of disk.

> bacongobbler commented 5 minutes ago
> ah, so you're having to purge old images from the hosts? We have documentation around that, though it'd be nice for the scheduler to remove the image when the process is killed.

> mastephens commented 2 minutes ago
> You hit it on the head. Yeah I have no problem purging the images manually, your docs were great for helping out with that. It would just be nice if we could set a ENV_VAR for the app and the builder would do its thing and push the most recent image to the registry, then purge any older than X.

**Comment by aledbf** [comment]
> ah, so you're having to purge old images from the hosts? 

@bacongobbler I proposed https://github.com/deis/deis/pull/2968 exactly for that reason

**Comment by bacongobbler** [comment]
right but that's more of a "mark and sweep" operation which could potentially remove images which the administrator may not want to be removed, hence the hesitation. We could handle this quite cleanly within [the scheduler itself](https://github.com/deis/deis/blob/master/controller/scheduler/fleet.py#L369-L389).

**Comment by bacongobbler** [comment]
frankly I'm surprised that it's not doing that already: https://github.com/deis/deis/blob/master/controller/scheduler/fleet.py#L375

**Comment by mastephens** [comment]
@bacongobbler Isn't that only going to clean up the container,  not the image as well?  Wouldn't you need a docker **rmi** {name} rather than just rm to cleanup the image?

**Comment by bacongobbler** [comment]
ah yes you're right

**Comment by mastephens** [comment]
And like you said before,  I'm not sure everyone would want their images torn down just because the container stopped.   That was why my suggestion was to keep X number of images,  that lets someone set their own comfort level on the number of successfully built images to keep that they could roll back to if necessary.

**Comment by croemmich** [comment]
I'd like to see this. We sometimes deploy multiple times a day with each image being around 500MB. Needless to say we get close to running out of space frequently.

**Comment by Crispy1975** [comment]
We'd love to see this also if possible. We're hitting the `/var/lib/docker` volume limit on our install on a regular basis.

**Comment by lukasmartinelli** [comment]
> It would be nice if we could add a config var like DIMAGE_CNT=3 that would force the builder to always remove any Docker images for an application that are not the most recent 3 images.

Implemented exactly this functionality in https://github.com/dreipol/cleanup-deis-images. This solves most of storage problems for us.
You need to run a service that runs this task daily.

```bash
docker run --rm \
 -v /var/run/docker.sock:/var/run/docker.sock \
 -e KEEP_LAST_VERSIONS=3 dreipol/cleanup-versions
```

**Comment by bacongobbler** [comment]
closing as something we cannot do for v1 (everyone has their own solution). Thankfully kubernetes has a built-in solution for cleaning up stale images on worker nodes so we get this feature for free!

**Comment by olalonde** [comment]
Just ran into a disk space problem as well. Managed to clean up by running:

```
fleetctl ssh deis-builder nse deis-builder
```

and once in `deis-builder` container:

```
docker images -aq | xargs docker rmi
```

I also had to use `docker images -aq | xargs docker rmi -f` on another machine because I was getting following message: `Conflict, cannot delete image 24d3f635e599 because it is tagged in multiple repositories, use -f to force`

**Comment by Crispy1975** [comment]
This one works pretty well for us:

```shell
docker rmi -f $(docker images -a | grep "<none>" | awk "{print \$3}")
```

Also note that if you are running out of inodes and cannot free space you most likely need to reboot the node to release them.
