### ISSUE TITLE
deisctl won't exit after platform is started

### ISSUE THREAD

**Issue by arkadijs** [deis/deis#3210]
deisctl from Deis 1.4.0 won't exit after all units are started (including `deis-registry@1.service`):

    core@ip-10-21-1-176 ~ $ systemctl status install-deis

    ● install-deis.service - Install Deis
       Loaded: loaded (/etc/systemd/system/install-deis.service; static; vendor preset: disabled)
       Active: activating (start) since Thu 2015-03-05 10:55:57 UTC; 32min ago
     Main PID: 884 (sh)
       CGroup: /system.slice/install-deis.service
               ├─ 884 /usr/bin/sh -c curl -sSL --retry 5 --retry-delay 2 (cut)/deis.sh | sh
               ├─ 886 sh
               └─1234 /opt/bin/deisctl start platform

    Mar 05 10:58:24 ip-10-21-1-176.ec2.internal sh[884]: deis-store-gateway@1.service: activating/start-post
    Mar 05 10:59:13 ip-10-21-1-176.ec2.internal sh[884]: deis-store-gateway@1.service: active/running
    Mar 05 10:59:17 ip-10-21-1-176.ec2.internal sh[884]: deis-store-volume.service: active/running
    Mar 05 10:59:17 ip-10-21-1-176.ec2.internal sh[884]: Logging subsystem...
    Mar 05 10:59:21 ip-10-21-1-176.ec2.internal sh[884]: deis-logger.service: activating/start-pre
    Mar 05 10:59:31 ip-10-21-1-176.ec2.internal sh[884]: deis-logger.service: active/running
    Mar 05 10:59:37 ip-10-21-1-176.ec2.internal sh[884]: deis-logspout.service: activating/start-pre
    Mar 05 11:00:51 ip-10-21-1-176.ec2.internal sh[884]: deis-logspout.service: active/running
    Mar 05 11:00:51 ip-10-21-1-176.ec2.internal sh[884]: Control plane...
    Mar 05 11:00:52 ip-10-21-1-176.ec2.internal sh[884]: could not find unit: deis-docker-registry.service

It bugs me because there are additional post-install activities down the script. Full log:

    Mar 05 10:55:59 ip-10-21-1-176.ec2.internal sh[884]: + /opt/bin/deisctl install platform
    Mar 05 10:55:59 ip-10-21-1-176.ec2.internal sh[884]: ● ▴ ■
    Mar 05 10:55:59 ip-10-21-1-176.ec2.internal sh[884]: ■ ● ▴ Installing Deis...
    Mar 05 10:55:59 ip-10-21-1-176.ec2.internal sh[884]: ▴ ■ ●
    Mar 05 10:55:59 ip-10-21-1-176.ec2.internal sh[884]: Storage subsystem...
    Mar 05 10:56:02 ip-10-21-1-176.ec2.internal sh[884]: deis-store-daemon.service: loaded
    Mar 05 10:56:03 ip-10-21-1-176.ec2.internal sh[884]: deis-store-volume.service: loaded
    Mar 05 10:56:03 ip-10-21-1-176.ec2.internal sh[884]: deis-store-metadata.service: loaded
    Mar 05 10:56:04 ip-10-21-1-176.ec2.internal sh[884]: deis-store-monitor.service: loaded
    Mar 05 10:56:04 ip-10-21-1-176.ec2.internal sh[884]: deis-store-gateway@1.service: loaded
    Mar 05 10:56:05 ip-10-21-1-176.ec2.internal sh[884]: Logging subsystem...
    Mar 05 10:56:12 ip-10-21-1-176.ec2.internal sh[884]: deis-logspout.service: loaded
    Mar 05 10:56:13 ip-10-21-1-176.ec2.internal sh[884]: deis-logger.service: loaded
    Mar 05 10:56:13 ip-10-21-1-176.ec2.internal sh[884]: Control plane...
    Mar 05 10:56:19 ip-10-21-1-176.ec2.internal sh[884]: deis-controller.service: loaded
    Mar 05 10:56:20 ip-10-21-1-176.ec2.internal sh[884]: deis-registry@1.service: loaded
    Mar 05 10:56:20 ip-10-21-1-176.ec2.internal sh[884]: deis-builder.service: loaded
    Mar 05 10:56:24 ip-10-21-1-176.ec2.internal sh[884]: deis-cache.service: loaded
    Mar 05 10:56:26 ip-10-21-1-176.ec2.internal sh[884]: deis-database.service: loaded
    Mar 05 10:56:27 ip-10-21-1-176.ec2.internal sh[884]: Data plane...
    Mar 05 10:56:30 ip-10-21-1-176.ec2.internal sh[884]: deis-publisher.service: loaded
    Mar 05 10:56:31 ip-10-21-1-176.ec2.internal sh[884]: Routing mesh...
    Mar 05 10:56:35 ip-10-21-1-176.ec2.internal sh[884]: deis-router@2.service: loaded
    Mar 05 10:56:36 ip-10-21-1-176.ec2.internal sh[884]: deis-router@3.service: loaded
    Mar 05 10:56:38 ip-10-21-1-176.ec2.internal sh[884]: deis-router@1.service: loaded
    Mar 05 10:56:38 ip-10-21-1-176.ec2.internal sh[884]: Done.
    Mar 05 10:56:38 ip-10-21-1-176.ec2.internal sh[884]: Please run `deisctl start platform` to boot up Deis.
    Mar 05 10:56:38 ip-10-21-1-176.ec2.internal sh[884]: + /opt/bin/deisctl start platform
    Mar 05 10:56:38 ip-10-21-1-176.ec2.internal sh[884]: ● ▴ ■
    Mar 05 10:56:38 ip-10-21-1-176.ec2.internal sh[884]: ■ ● ▴ Starting Deis...
    Mar 05 10:56:38 ip-10-21-1-176.ec2.internal sh[884]: ▴ ■ ●
    Mar 05 10:56:38 ip-10-21-1-176.ec2.internal sh[884]: Storage subsystem...
    Mar 05 10:56:41 ip-10-21-1-176.ec2.internal sh[884]: deis-store-monitor.service: activating/start-pre
    Mar 05 10:57:16 ip-10-21-1-176.ec2.internal sh[884]: deis-store-monitor.service: active/running
    Mar 05 10:57:20 ip-10-21-1-176.ec2.internal sh[884]: deis-store-daemon.service: activating/start-pre
    Mar 05 10:57:44 ip-10-21-1-176.ec2.internal sh[884]: deis-store-daemon.service: active/running
    Mar 05 10:57:47 ip-10-21-1-176.ec2.internal sh[884]: deis-store-metadata.service: activating/start-pre
    Mar 05 10:57:51 ip-10-21-1-176.ec2.internal sh[884]: deis-store-metadata.service: active/running
    Mar 05 10:57:54 ip-10-21-1-176.ec2.internal sh[884]: deis-store-gateway@1.service: activating/start-pre
    Mar 05 10:58:24 ip-10-21-1-176.ec2.internal sh[884]: deis-store-gateway@1.service: activating/start-post
    Mar 05 10:59:13 ip-10-21-1-176.ec2.internal sh[884]: deis-store-gateway@1.service: active/running
    Mar 05 10:59:17 ip-10-21-1-176.ec2.internal sh[884]: deis-store-volume.service: active/running
    Mar 05 10:59:17 ip-10-21-1-176.ec2.internal sh[884]: Logging subsystem...
    Mar 05 10:59:21 ip-10-21-1-176.ec2.internal sh[884]: deis-logger.service: activating/start-pre
    Mar 05 10:59:31 ip-10-21-1-176.ec2.internal sh[884]: deis-logger.service: active/running
    Mar 05 10:59:37 ip-10-21-1-176.ec2.internal sh[884]: deis-logspout.service: activating/start-pre
    Mar 05 11:00:51 ip-10-21-1-176.ec2.internal sh[884]: deis-logspout.service: active/running
    Mar 05 11:00:51 ip-10-21-1-176.ec2.internal sh[884]: Control plane...
    Mar 05 11:00:52 ip-10-21-1-176.ec2.internal sh[884]: could not find unit: deis-docker-registry.service

**Comment by bacongobbler** [comment]
it looks like you're running a custom `deisctl` which is trying to find `deis-docker-registry.service`. What should happen is that it should exit out with a non-zero exit code.

**Comment by arkadijs** [comment]
I'm running stock deisctl on a fresh cluster

    curl -sSL --retry 5 --retry-delay 2 http://deis.io/deisctl/install.sh | sh -s 1.4.0

**Comment by wenzowski** [comment]
I noticed all sorts of curiosities with `deisctl`. Found it to be very useful for issuing automation commands but have been watching for status with `watch "fleetctl list-units | grep deis-"` at this point. There's probably an entire suite of tests to cover status polling that's worth writing, but I still have to read more code before I can take a stab at that myself.

**Comment by bacongobbler** [comment]
The problem with `deisctl` was that it was hacked up over a week's time with Deis pre-1.0 with hardly any unit tests due to a lack of fleet test infra. I think the first step is to get some proper unit tests in deisctl.

**Comment by mboersma** [comment]
This particular issue is fixed with #3802 in upcoming v1.8.
