### ISSUE TITLE
Config variables set with `deis config:set` are wrapped in single quotes

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3212]
This breaks when apps try to use them, as they obviously don't expect these to be wrapped in quotes:
```
URI::InvalidURIError: bad URI(is not URI?): 'mysql2://XXXXXX:XXXXXX@1.2.3.4:3306/db'
```

This is likely a regression with https://github.com/deis/deis/commit/f6bcb25b2fec5ae0d5daf698f6b034526fb2dfb0.

**Comment by mastephens** [comment]
Great!  I ran into this today and had to modify our build scripts to account for it.

**Comment by bacongobbler** [comment]
sorry about that! We'll be shortly releasing a v1.4.1 with a fix in place for this.

**Comment by mastephens** [comment]
Perfect!

**Comment by bacongobbler** [comment]
done. Just follow through the [in-place upgrade](http://docs.deis.io/en/latest/managing_deis/upgrading-deis/#in-place-upgrade) documentation and you should be all set.
