### ISSUE TITLE
Proposal: Deis Connector - A way to connect between two Deis

### ISSUE THREAD

**Issue by phspagiari** [deis/deis#3217]
We were thinking about a secure and reliable way for containers running in separated Deis installations (and probably in production) to comunicate with each other.
The idea begins because we have two Deis installation on each environment. We have a Deis "Web Facing" and a Deis "Private".
The Web Facing Deis only receive and send https connections and the Private Deis only receive https connections but he can send tcp/http connections to resources / services like MySQL, Redis, MongoDB and more.

The initial idea was:

{ **WEB** }  *---(https)->* [ **Deis Web Facing** ] *---(https)->* [ **Deis Private** ]  *---(tcp/http)->* **Resource**

But we think that we can modify this connection between the two Deis installations and use a "connector" based on the AWS IAM way, using a KEY/SECRET and a JSON allowing / denying the access. 

##### Example of Deis Connector:
 - Frontend (Web Facing)
 - API (Private)
 - MySQL (Recurso)
 - DeisConnectorKey:  ``80MNOUQADpSu``
 - DeisConnectorPass: ``4QWU8f4ei1pnKEfyPN9Sr36X``
 - DeisConnectorJSON Example:

```json
{
	"DeisAuthorizations": [
		{
			"Action": "Access",
			"Effect": "Allow",
			"Rules": [
				{
					"Origin": "web-app.paas.comp.org",
					"Destination": "api-app.paas.com.org",
					"ConnectionType": "http"
				}
			]
		}
	]
}
```

With this, we can control between a module/app of own Deis the communication of external containers that belong to the same "Stack". Its very helpful in a environment like production where we want to limit the access.

**Comment by ianblenke** [comment]
Something here just isn't clicking in my brain.

Your JSON example looks like an IAM policy, but the Action: "Access"  isn't an action for any AWS resource that I can think of, and I'm not able to find an Origin/Destination/ConnectionType rule of any kind in the IAM documentation either. Then again, I could be looking for it in the wrong places.

This makes me think that you're asking for an IAM custom policy of some kind. While it is possible to augment CloudFormation with custom resources with some (non-trivial) effort, I'm not aware of any ability to provide custom IAM policies like this.

There are two ways I would approach this:
1. As two different VPC SecurityGroups with transitive restrictions
2. As two different VPCs with a VPC peering and appropriate SecurityGroup restrictions

As it sounds like both things are running in the same environment/lifecycle, that sounds like they probably belong in the same VPC with a SecurityGroup ingress trust in your "Private" Deis SecurityGroup ingress of your "Web Facing" Deis SecurityGroup egress.

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-security-group-egress.html
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html

Neither of these things are really Deis specific, however, they're AWS constructs that wouldn't really apply to GCE, Azure, RackSpace, ...

Am I understanding your proposal correctly, or am I just not getting it? If it's the latter (which it very well may be), can you help me understand your JSON approach here for Deis?

**Comment by phspagiari** [comment]
Hi @ianblenke,

So the JSON fields are just a example about what we can do. I'm not sure about if the fields and values in the example is a good idea. The proposal is exactly to discuss about the better way for Deis to do this.

I used the "IAM Idea" only for the model that the connector will use, I mean the key/secret and the json. The idea is not to replicating the IAM to Deis even I think that the Deis Connector looks more like the Security Group of AWS.

You are using CloudFormation / VPC examples and indeed we can do this with this guys, but in my case I dont use AWS as provider :smile: . My environment is bare-metal / VMWare. So because of this Deis Connector is apparently a good idea. We will don't use a external tool to segregate / control the access between two Deis, but we use a tool provided by own Deis.

**Comment by bacongobbler** [comment]
this sounds a lot like a proposal to #231, which would essentially work like this but within a single deis cluster, only the "Deis Private" would instead be a "service broker" that only receives http connections, but can send https/tcp/whatever type of connection the resource will give.

**Comment by bacongobbler** [comment]
closing in favour of #231 and #4173.
