### ISSUE TITLE
Update the docs' cadvisor unit file

### ISSUE THREAD

**Issue by haf** [deis/deis#3221]
Hi,

Newbie here. As you've seen in the previous issue ;).

I'm testing the platform, randomly resetting machines and seeing if I can manage to nurse the clusters back to health again. It seems to be doing alright, but of course, there's no load on the platform.

Anyway, as a part of trying to get some diagnostics into each of the services running in docker, I installed cadvisor according [to the docs](http://docs.deis.io/en/latest/managing_deis/platform_monitoring/#cadvisor) with a unit file that I did `fleetctl start cadvisor.service`, which started it across all three nodes that I have in my vagrant cluster.

I then reset a single node, node 3 and watched whether things would still show up and route properly. They did.

Now I started it again.

Here's where the first question comes: if a node reboots, why doesn't `deisctl status` tell me about it? It's just blank, exiting 0.

Also, when the node goes back up, not all unit are automatically started, even though they should optimally be started as soon as possible to ensure availability: specifically:

deis-store-daemon.service		169914f2.../172.17.8.102	activating	start-pre

and 

deis-logspout.service			169914f2.../172.17.8.102	activating	auto-restart

I had to run `deisctl start platform` for them to start. I didn't manage any `fleetctl` command that made a difference. At this point it was a bit opaque.

When they had started, I noticed that cadvisor looked like this:

```
UNIT					MACHINE				ACTIVE		SUB
cadvisor.service			169914f2.../172.17.8.102	failed		failed
cadvisor.service			21d1548b.../172.17.8.100	active		running
cadvisor.service			28ed8692.../172.17.8.101	active		running
deis-builder.service			21d1548b.../172.17.8.100	active		running
# snip
```

As it turns out, it didn't want to start again, because, according to journalctl (deisctl journal didn't want to give me anything:

```
$ deisctl journal cadvisor
Unable to get journal for global unit cadvisor.service. Check the logs on the host using journalctl.
```
) despite it being a global unit.

```
$ journalctl -fu cadvisor
Mar 06 23:00:33 deis-03 systemd[1]: Starting Google Container Advisor...
Mar 06 23:00:33 deis-03 systemd[1]: Started Google Container Advisor.
Mar 06 23:00:33 deis-03 docker[3135]: time="2015-03-06T23:00:33Z" level="fatal" msg="Error response from daemon: Conflict, The name cadvisor is already assigned to 0dc97d3eb6b8. You have to delete (or rename) that container to be able to assign cadvisor to a container again."
Mar 06 23:00:33 deis-03 systemd[1]: cadvisor.service: main process exited, code=exited, status=1/FAILURE
Mar 06 23:00:33 deis-03 systemd[1]: Unit cadvisor.service entered failed state.
Mar 06 23:00:33 deis-03 systemd[1]: cadvisor.service failed.
```

How to start cadvisor again? Do I have to manually go through and SSH to all machines to `docker rm -f cadvisor` the containers and their images?

And why don't needed containers, such as the ceph monitor container, start when the node goes back up? I'm absolutely certain a restart will bite me in the ass at some point, me failing to notice it and then another node crashing, pulling everything down with it. So I'd rather save my ass when I have time to learn how to do it. ;)

**Comment by haf** [comment]
It also seems that `docker ps -a | grep cadvis | awk '{ print $1 }' | xargs docker rm` followed by `fleetctl start cadvisor.service` still lists cadvisor as 'failed'...

**Comment by haf** [comment]
Answering my own question: the reason is that the unit file is not as robustly written as the other unit files.

The other unit files seem to do a `docker rm -f`, so the help should be updated to make cadvisor's unit file match those.

Here's the improved unit-file which now matches other other deis unit files:

```
[Unit]
Description=Google Container Advisor
Requires=docker.socket
After=docker.socket

[Service]
ExecStartPre=/bin/sh -c "docker history google/cadvisor:latest >/dev/null || docker pull google/cadvisor:latest"
ExecStartPre=/bin/sh -c "docker inspect cadvisor >/dev/null && docker rm -f cadvisor || true"
ExecStart=/usr/bin/docker run --volume=/:/rootfs:ro --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --publish=8080:8080 --name=cadvisor google/cadvisor:latest
ExecStopPost=-/usr/bin/docker rm -f cadvisor
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

[X-Fleet]
Global=true
```

**Comment by bacongobbler** [comment]
Thanks! This documentation was provided by the community, so any improvements to the existing documentation would be helpful.

**Comment by haf** [comment]
Where are they updated? Will you take the changes specified in this thread and merge?

**Comment by bacongobbler** [comment]
`docs` is our documentation hosted at http://docs.deis.io. Any changes made there via Pull Request will show on the site.

**Comment by haf** [comment]
Closing in favor of the PR. Merge/reject at your pleasure.
