### ISSUE TITLE
Proposal ref(store): make ceph optional if the node is running in aws or azure

### ISSUE THREAD

**Issue by aledbf** [deis/deis#3223]
The objective is to delegate the decision to use the `ceph` cluster or not.
It makes more sense (at least to me) to use the blob store provided by the `IAAS` and not `ceph`.

**This implies that the application logs cannot be retrieved using `deis logs -a <app>`**
(this could be a good reason to rethink the actual logging mechanism)

Right now is not possible to decide this and this *option* can eliminate the issues that `ceph` some times can present like "4 requests are blocked > 32 sec;" that are painful to solve.

*I know that this proposal can cause a passionate discussion but I just want to know if I'm the only one thinking that this could be an option*

**Comment by bacongobbler** [comment]
You're not the only one. We needed a quick and dirty solution to make Deis HA by default and Ceph helped us get to 1.0. I'm personally open to making this an optional component (I can finally have my 1-node mini cluster for developing once more).

**Comment by croemmich** [comment]
I'd love to see this as well. Nearly every issue I have had with Deis has been related to ceph doing silly things. The worst was the time it decided to fill my three equally sized disks to 35%, 91% and 95%. I then did a rebalance by utilization and it ended up at 31, 99, and 100 even though it declared reasonable weights for each osd.

**Comment by mgartner** [comment]
+1 (related to #2812).

Most of the issue I've had while running Deis have been caused by Ceph, unfortunately.

**Comment by bacongobbler** [comment]
ceph is now optional with #3947. docs are at http://docs.deis.io/en/latest/managing_deis/running-deis-without-ceph/
