### ISSUE TITLE
Update docs' debugging of ceph in vagrant

### ISSUE THREAD

**Issue by haf** [deis/deis#3225]
Could add a FAQ entry on HEALTH_WARN state, as it gets when using `vagrant suspend` and then `vagrant up`:

Q: `ceph -s` states HEALTH_WARN with a clock skew (see below), how do I make it right again?

Sample output:

```
root@e95e4fbd4cdd:/app# ceph -s
    cluster ff727d9d-8bbb-4308-9142-7c2364bdc8f0
     health HEALTH_WARN clock skew detected on mon.deis-03
     monmap e3: 3 mons at {deis-01=172.17.8.100:6789/0,deis-02=172.17.8.101:6789/0,deis-03=172.17.8.102:6789/0}, election epoch 30, quorum 0,1,2 deis-01,deis-02,deis-03
     mdsmap e14: 1/1/1 up {0=deis-02=up:active}, 2 up:standby
     osdmap e59: 3 osds: 3 up, 3 in
      pgmap v3271: 1536 pgs, 12 pools, 428 MB data, 652 objects
            30476 MB used, 17195 MB / 49578 MB avail
                1536 active+clean
```

A: Run this for all machines on which ceph detects a clock skew:

``` bash
sudo systemctl stop ntpd
sudo ntpd -gq
sudo systemctl start ntpd
```

This will synchronise the time over ntp, manually, and then start ntpd (the daemon) again.

**Comment by haf** [comment]
If you would like me to add this to the docs, I can send a PR.

**Comment by carmstrong** [comment]
@haf I think #3222 addresses this

**Comment by haf** [comment]
Nice, you're way ahead of me!
