### ISSUE TITLE
How do I deploy a "resource" in 12-FA vocab?

### ISSUE THREAD

**Issue by haf** [deis/deis#3226]
I've been searching the docs for a description on how to deploy a database (in my case) properly, when that database has more than one exposed port -- it should simply be a service that my app consumes. I'm looking for answers to this query:

 1. How can I easily deploy a service through a Dockerfile, which is NOT to be load-balanced by the routers?
 2. How do know what environment variables Deis sets as this service' endpoint configuration data, as exposed to the app?
 3. How can my app know the health state of the deployed service? I want to connect only to alive instances.

**Comment by haf** [comment]
Related: https://github.com/deis/deis/issues/231 https://groups.google.com/forum/#!topic/deis-users/XUQDDpaH4KI

**Comment by ianblenke** [comment]
The persistence layer is ideally something external to Deis, like AWS RDS or something similar. Your apps should deal with something like a DATABASE_URL environment variable, and the URL contained therein should be auto-failover and self-healing so as to be available.

**Comment by haf** [comment]
I'm not so sure I agree. Deploying Deis is in itself a rather large cost commitment so I'd rather re-use what the platform provides; I want the 3 nodes to have a 80% CPU utilisation before I start firing up more of them. This is my current requirement, but that could change as we start getting more customers.

With the database url - there are two issues with it - the first is that it would mean adding another level of failover - and therefore a proxy in between, like [HAProxy + etcd](http://jasonwilder.com/blog/2014/07/15/docker-service-discovery/) -- except, now there are even more moving parts, especially so if I have a client that's capable of failover itself.

Another issue with introducing a service proxy is that if my client expects Strict Serializability on Write, but only guarantees it per-session (read-your-writes if you're connecting to the same instance), having a load-balanced solution could possibly void the consistency semantics of the database with such a consistency option.

I've done work with AWS RDS and it's the most terrible form of storage I can think of - it has high latency, varying latency and isn't available directly on boot -- which is why I would prefer using the local storage of the nodes that deis is deployed on instead. I'm planning on setting it up in DigitalOcean. Consul's SRV records would be a great way of doing it, but again, we have etcd - and the service discovery issue is still open.

I was planning on using Registrator with Consul + Health Checks before I found Deis - that way it's all automatic and I can place a watch on the record, to re-create the connection (pool) whenever it changes. It would be great if there could be something similar in Deis.

**Comment by bacongobbler** [comment]
Hi!

> I've been searching the docs for a description on how to deploy a database (in my case) properly, when that database has more than one exposed port -- it should simply be a service that my app consumes.

Currently http applications which expose only a single port are the only type supported through the router: #1315 #3069

> How can I easily deploy a service through a Dockerfile, which is NOT to be load-balanced by the routers?

http://docs.deis.io/en/latest/using_deis/process-types/#declaring-process-types

> How do know what environment variables Deis sets as this service' endpoint configuration data, as exposed to the app?

That's a question for #231, though through Heroku's model that implementation is left to the service broker.

> How can my app know the health state of the deployed service? I want to connect only to alive instances.

This is another question for #231. :)

**Comment by ianblenke** [comment]
@haf, it is generally a good idea to separate your Deis control plane from your application hosting plane so that your applications can't impact the operation of your Deis deployment.

I've found that having a larger compute instance for the deis-builder instance cuts image build times, and that the other Deis nodes can be made considerably smaller.

Fleet tagging of application nodes allows you to sequester your application units off to their own tier so as to not interfere with Deis.

The key to running Deis effectively in production is really to avoid impeding etcd leadership elections, and ensure uninterrupted ceph quorum.

**Comment by bacongobbler** [comment]
Closing in favor of #231 as the original question is around deploying application resources,  which defines this as a duplicate. Thanks!

**Comment by haf** [comment]
Service Orchestation != Service Discovery, wouldn't you say? Even though they are normally close.

**Comment by bacongobbler** [comment]
service orchestration would be done through the broker, so in this case they are one and the same.
