### ISSUE TITLE
Docs on etcd interaction?

### ISSUE THREAD

**Issue by haf** [deis/deis#3227]
I'm looking for docs on the etcd interaction in deis. Really, what I'd like to get is a way to declaratively expose a health check endpoint with a TTL and/or status codes (info, warn, error, fatal) from my app. Basically like Consul's health checks.

Since etcd is being used for service runtime configuration and deployment data (right?) - I suppose I'd have to poll/put a token in there every nth second, to make my service visible? (e.g. containing the actual date the PUT was done, so that the control plane knows when to remove my service from load)?

**Comment by haf** [comment]
Related https://github.com/deis/deis/issues/3072

**Comment by carmstrong** [comment]
@haf I think this is a good thing to bring up in #3072, since it's relevant to that discussion - let's move the discussion over there. Thanks!
