### ISSUE TITLE
Docs on using Deis to locally develop dockerfiles?

### ISSUE THREAD

**Issue by haf** [deis/deis#3231]
I was wondering what the recommended way of using the registry that comes with deis is?

 - What are the security blocks on the registry? Can I push to it from any node without going through the builder?
 - If I can't, then from where can I push to it?
 - In what way is it configured in comparison to [docker-registry](https://github.com/docker/docker-registry) or [this guide to configuring it](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-private-docker-registry-on-ubuntu-14-04)?

**Comment by ianblenke** [comment]
@haf, this might help:

http://docs.deis.io/en/latest/customizing_deis/registry_settings/

The deis-registry's port 5000 is not publicly exposed by default. It stores everything via the deis-store-gateway (ceph radosgw). There is a secretKey, though I'm not sure how this is really used. It is painless to push to it. You do not need to go through the registry. I often push to it directly from the underlying coreos hosts using docker tag followed by a docker push. It is actually running docker-registry:

https://github.com/deis/deis/blob/master/registry/build.sh#L29-L30

The source tree there is very small, mostly shell scripts and template config files, very easy to read.

**Comment by haf** [comment]
@ianblenke thank you! I will study those! Great to know that someone else has a similar requirement.

**Comment by bacongobbler** [comment]
The registry is simply docker-registry with a few patches on top of v0.9.1 for some of the features utlized in `deis pull`. As @ianblenke said, it's not publicly exposed by default.

> There is a secretKey, though I'm not sure how this is really used

That's a key which was used in older versions of the registry: https://github.com/docker/docker-registry/blob/0.6.0/config_sample.yml#L7-L8

It's probably safe to remove from the documentation now, considering that it's no longer in use.

**Comment by carmstrong** [comment]
> It's probably safe to remove from the documentation now, considering that it's no longer in use.

We should probably file this so we don't forget about it.

**Comment by bacongobbler** [comment]
it's ok I filed #3237 :)

**Comment by haf** [comment]
Here's another thing, that I think should go in the docs:

```
sudo coreos-cloudinit --from-file share/deis-vagrant/contrib/coreos/user-data
```

If you want to run cloud-init in your machine, to access docker-tcp.

Also docker-tcp doesn't work out of the box.

Also if you try `systemctl start docker-tcp` you get errors saying that the socket is already bound.

There should be a mention of whether I need to mount a NFS share or if the 'context' of the docker invocation is automatically sent.

Also see discussion in https://github.com/coreos/coreos-vagrant/issues/172

This means https://github.com/deis/deis/issues/1493#issuecomment-51026554 isn't a working solution, I suppose? At least I haven't been able to make it work.

**Comment by haf** [comment]
Docs relating to this page: http://docs.deis.io/en/latest/using_deis/using-dockerfiles/#using-dockerfiles

**Comment by haf** [comment]
We should mention that 2375 is being used as opposed to 2376 in 1.5 of docker and that the next release is changing that.

**Comment by haf** [comment]
Should mention that CoreOS is on the 'stable' release track and that you need a client to go with it.
