### ISSUE TITLE
Proposal ref(database): remove data container

### ISSUE THREAD

**Issue by aledbf** [deis/deis#3236]
This will remove the possibility of start the service in a different node where it was running previously and do not restore the last backup from S3

**Comment by ianblenke** [comment]
That puts all of your cards on "trust your backing store", be it ceph or s3. I'm ok with that, assuming there's a very obvious way of attempting periodic wal-e restores and generating a verifiable delta to the running state (to make sure the backups _work_ and are usable), as well as presenting wal-e backup failures in a very loud way.

**Comment by wenzowski** [comment]
the default install as it currently exists does not give us confidence in ceph since we there's no UI for monitoring ceph health and monitoring containers must be manually installed

I would schedule resolution of this issue post UI & webhooks for ceph heath. My 2 cents.

**Comment by carmstrong** [comment]
There's some discussion around removing the data container in #3128, and I think the fix proposed there fixes the root cause of this issue.

**Comment by carmstrong** [comment]
See the discussion in #3128 about why we cannot remove the data container.
