### ISSUE TITLE
redirect loop when enforceHTTPS is enabled on 1.4.1

### ISSUE THREAD

**Issue by wenzowski** [deis/deis#3245]
first registration with enforceHTTPS enabled results in redirect loop

**Comment by wenzowski** [comment]
...seems to be all api calls.

**Comment by bacongobbler** [comment]
@wenzowski does https://github.com/deis/deis/issues/3258#issuecomment-78168072 look familiar to the errors you're seeing on your end?

**Comment by wenzowski** [comment]
in the extent that I'm seeing 302 redirects, yes

```
$ deisctl config router set enforceHTTPS=true
true
$ deis ps
Exceeded 30 redirects
$ deisctl config router set enforceHTTPS=false
false
$ deis ps
=== demo Processes

--- web:
web.1 up (v8)
web.2 up (v8)
web.3 up (v8)
```

**Comment by wenzowski** [comment]
I'm using a signed wildcard cert though, so I shouldn't be seeing cert validation errors on this end (and I'm not).

tcpdump shows the EDH hops look like they're working then ~30 identical requests being fired off (same 401 bytes every time) and ~30 identical requests being returned (same 436 bytes every time).

Can't do much more on that front because the traffic is encrypted at the interface level.

Any debug flags in the command line utility I should know about?

**Comment by carmstrong** [comment]
> Any debug flags in the command line utility I should know about?

We just use the Python requests library, so you can hook into it and debug the request/response: https://github.com/deis/deis/blob/661b8165dfbe5bab57845c9290366636f5e63e65/client/deis.py#L374-L400

**Comment by wenzowski** [comment]
thanks @carmstrong my py is terribly rusty but I'm sure I'll get to the bottom of this

**Comment by wenzowski** [comment]
the current aws config assumes an elb, while I'm terminating ssl on the router

I've got a fix running, but it isn't useful for you yet because it breaks elb compat

**Comment by wenzowski** [comment]
#3264 fix needs to be tested manually on aws; but working well elsewhere
