### ISSUE TITLE
Deis apps:destroy does not remove the git repo with the same name

### ISSUE THREAD

**Issue by wenzowski** [deis/deis#3249]
if a new application is created with the same name, everything is already up to date on git push

**Comment by carmstrong** [comment]
Hm.... builder's [check-repos](https://github.com/deis/deis/blob/8826c83b28a573334083edc83571488238857924/builder/image/templates/check-repos) script should be handling this....

@wenzowski If you run that manually within the container (`nse deis-builder` then `/home/git/check-repos`), can you confirm that the repo is still there?

**Comment by bacongobbler** [comment]
I've found that if you apps:destroy and apps:create quick enough, you can repro this issue.

**Comment by wenzowski** [comment]
manual run works; appears it was an execution speed thing as @bacongobbler has noted

**Comment by haf** [comment]
Also, if either adding the git remote succeeds and the other fails, or the create succeeds and git remote already exists, we can either end up in a git remote that can't be pushed to, in the first case, and in the second case a failed call (non zero exit code), which requires manual intervention: first destroy the app, then git remote rm the remote.

**Comment by bacongobbler** [comment]
we should investigate this now with v0.8.0. With --watch enabled this should happen simultaneously... unless there's some race condition happening
