### ISSUE TITLE
Security: open port for PostgreSQL with default script

### ISSUE THREAD

**Issue by haf** [deis/deis#3256]
After running the [firewall-script](https://github.com/deis/deis/blob/master/contrib/util/custom-firewall.sh#L41) as instructed in the setup of Deis, these ports are left open:

```
$ nmap -sS $HOST
..
Host is up (0.66s latency).
Not shown: 994 filtered ports
PORT     STATE  SERVICE
22/tcp   open   ssh
80/tcp   open   http
443/tcp  closed https
2222/tcp open   EtherNet/IP-1
5432/tcp open   postgresql -- part of deis
8080/tcp open   http-proxy -- with cadvisor started
```

But according to the docs only four ports should be open:

```
        22: for remote SSH
        80: for the routers
        443: (optional) routers w/ SSL enabled
        2222: for the builder
```

All ports in 'open' state accept connections.

How do I lock it down?

**Comment by bacongobbler** [comment]
@haf are you inspecting it from inside the cluster via the private IP address or via the public address? The connections are allowed from [within the cluster](https://github.com/deis/deis/blob/master/contrib/util/custom-firewall.sh#L34-L35) but otherwise the [connection is dropped](https://github.com/deis/deis/blob/master/contrib/util/custom-firewall.sh#L43-L45).

**Comment by haf** [comment]
I'm inspecting it from the outside, from my own network into the production network.

I can telnet to postgresql's port and the connection is not dropped. Also, I can access 8080 and click around in the web app.

**Comment by bacongobbler** [comment]
just to confirm, did you reboot the node after running the script? How is your cluster set up? I'm going to try reproducing this.

**Comment by haf** [comment]
No, I didn't reboot the node.

I set up a 3-node cluster according to the docs, exactly following them.

I can see the rules for iptables -- and they match the script. Perhaps they are not enforced? I'm sorry, I'm a bit of a newbie at core-os and bridge forward chains...

**Comment by haf** [comment]
Did you manage to reproduce it?

**Comment by haf** [comment]
I think it's because `systemctl start iptables-restore.service` isn't run by the script.

**Comment by bacongobbler** [comment]
correct; it just [enables it](https://github.com/deis/deis/blob/master/contrib/util/custom-firewall.sh#L59), but doesn't start. However, it does make a call to [iptables-restore](https://github.com/deis/deis/blob/master/contrib/util/custom-firewall.sh#L65), so the rules should have applied.

**Comment by carmstrong** [comment]
@haf Any update on this? Were you able to repro?

**Comment by haf** [comment]
Yes, if you start iptables-restore it closes the firewall.

**Comment by bacongobbler** [comment]
okay so maybe the actionable item here is to start iptables-restore after we enable it. :+1:

**Comment by bacongobbler** [comment]
closing as this has been resolved by starting iptables-restore after enabling the unit. Thanks for the report!

**Comment by haf** [comment]
Np, thanks for fixing.
