### ISSUE TITLE
Router: Serve content on example.com?

### ISSUE THREAD

**Issue by haf** [deis/deis#3257]
Is it possible to configure Deis to serve a specific app for the top level domain? I have a domain `example.com` under which apps go, `app.example.com`, and I want `example.com` to be forwarded to an app.

How do I go about doing that?

**Comment by nathansamson** [comment]
This is a limitation on the DNS system. In short CNAMEs are not allowed on top level domains.

You can fix this by either
A) Using the IP addresses directly (obviously this is not as HA as you would like it)
B) Use a DNS provider that can emulate (some of) the CNAME behaviour on top level domains.

see heroku docs
https://devcenter.heroku.com/articles/custom-domains#root-domain 
https://devcenter.heroku.com/articles/apex-domains

Note that my solution is to use www.mydomain.com, and let mydomain.com redirect to www.mydomain.com (eg wwwizer.com offers this for free).

**Comment by nathansamson** [comment]
Now I think of it, I am not sure if deis allows you to add example.com, but I think it does.

**Comment by bacongobbler** [comment]
We have `deis domains`, similar to heroku: http://docs.deis.io/en/latest/using_deis/config-application/#custom-domains

**Comment by haf** [comment]
Awesome! =)
