### ISSUE TITLE
Deis cmd-line util: using SSL for self-signed certs --verify-ssl=false for all

### ISSUE THREAD

**Issue by haf** [deis/deis#3258]
When developing an app it's useful to use a self-signed certificate -- I've followed the docs for setting a SSL certificate for the domain -- now when I want to connect to the domain, I can't because:

```
deis create
Creating application... Couldn't connect to the Deis Controller:
[Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Make sure that the Controller URI is correct and the server is running.
```

Can I tell deis to ignore cert self-signed errors, given that having a self-signed cert is more secure than having no encryption at all?

**Comment by bacongobbler** [comment]
I believe this is because your self-signed certificate has not been added to your system cert authority. There's plenty of documentation on how to get your CA installed into your chain: http://superuser.com/a/719047

If that doesn't work for you, there's a flag for disabling ssl verification across requests:

```
$ deis help login
Logs in by authenticating against a controller.

Usage: deis auth:login <controller> [options]

Arguments:
  <controller>
    a fully-qualified controller URI, e.g. `http://deis.local.deisapp.com/`.

Options:
  --username=<username>
    provide a username for the account.
  --password=<password>
    provide a password for the account.
  --ssl-verify=false
    disables SSL certificate verification for API requests
```

**Comment by haf** [comment]
Thank you! That's what I needed!

**Comment by haf** [comment]
Sorry, that didn't work:

```
/var/folders/j7/wbmqw81j2_jcfwn6_hh0ltlh4zjfkz/T/_MEITEzP6V/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
301 Moved Permanently
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
```

Also;

```
deis logs --ssl-verify=false
Usage: deis apps:logs [options]
```

**Comment by haf** [comment]
Related? https://github.com/deis/deis/issues/3245 Duplicate?

**Comment by bacongobbler** [comment]
yep, sounds like the error you're seeing is a duplicate.

**Comment by wenzowski** [comment]
not *entirely* a dup: since you're using a self-signed I'm assuming you'll still want `--ssl-verify=false`

**Comment by wenzowski** [comment]
...though you could always grab a free cert from https://www.startssl.com/

Just make sure you set the common name to `deis.whateveryourdomainactuallyis.com`

**Comment by haf** [comment]
@wenzowski Ok, then let's make this issue about having `--ssl-verify=false` on everything that uses the controller.

**Comment by wenzowski** [comment]
makes sense to me @haf 

so this should be resolved when all `deis` calls respond correctly to `--ssl-verify=false`?

**Comment by haf** [comment]
Yes

**Comment by carmstrong** [comment]
> Ok, then let's make this issue about having --ssl-verify=false on everything that uses the controller.

This should already be the case - the verify is written to `~/.deis/client.json` and is read on subsequent calls. If you can produce a repro case, please open an issue specific to that. Thanks!

See #2892 for details.
