### ISSUE TITLE
Deis detects albacore as ruby app

### ISSUE THREAD

**Issue by haf** [deis/deis#3263]
When you have a mono app that uses albacore https://github.com/Albacore/albacore/ and https://rubygems.org/gems/albacore to build, `git push deis master` thinks it's a ruby app -- despite it having a Dockerfile.

Could you guide me to where I improve on this condition? Are you open for a PR that knows whether to treat the app as a .Net app?

How about if I make it check if Gemfile contains the 'albacore' gem? I'm certain there are no plain-ruby projects using albacore since it's very .Net specific.

Or would it be better to use the Dockerfile present by default and first when not finding a dockerfile, using the 'guessed' language buildpack?

**Comment by bacongobbler** [comment]
this is a limitation of https://github.com/heroku/heroku-buildpack-ruby. The [detect script](https://github.com/heroku/heroku-buildpack-ruby/blob/master/bin/detect) is the one that determines if this app should be built by the buildpack.

**Comment by wenzowski** [comment]
alternatively @haf you could use your own buildpack
```
deis config:set BUILDPACK_URL=http://github.com/friism/heroku-buildpack-mono
```
can't vouch for whether that particular one will work ^

see [installed buildpacks](http://docs.deis.io/en/latest/using_deis/using-buildpacks/)

**Comment by ianblenke** [comment]
I think the key there may be "despite it having a Dockerfile". Were you intending on using the Dockerfile to deploy your project?

https://registry.hub.docker.com/u/microsoft/aspnet/
https://github.com/aspnet/aspnet-docker
http://blogs.msdn.com/b/webdev/archive/2015/01/14/running-asp-net-5-applications-in-linux-containers-with-docker.aspx

There are other Dockerfile examples out there using mono to do this as well.

**Comment by haf** [comment]
@ianblenke yes exactly - the dockerfile works -- if it is used, but it's not being used.

We've written our own F# web server, http://suave.io, which is just a TCP socket, so there's no need for the fat-cat ASP.Net =)

**Comment by wenzowski** [comment]
good catch @ianblenke 

confirming @haf that a Dockerfile is present in your repo but the buildpack process is being triggered instead of the docker build?

**Comment by haf** [comment]
I'm sorry, it does recognise the dockerfile, but I was on the wrong branch. Sorry everyone and thank you for the help you extended!

![screen shot 2015-03-11 at 08 50 03](https://cloud.githubusercontent.com/assets/193115/6592259/bad34ac6-c7cb-11e4-82bc-882c1c0cb5fb.png)

**Comment by wenzowski** [comment]
just glad you figured it out @haf :+1:
