### ISSUE TITLE
should ssl endpoint docs explain how to get a signed cert?

### ISSUE THREAD

**Issue by wenzowski** [deis/deis#3265]
If we get certs-per-app then a wildcard cert, though still helpful, might no longer be necessary to get started.

StartCom has been [giving away](https://www.startssl.com/?app=1) free class1 certs for ages. Free ones not wildcard, but if the CN is set to `deis.domain.com` they would still be usable for control surface...which would reduce the risk of control surface credentials being lifted. And seeing as those can do a lot of damage, this seems desirable to me.

**Comment by ianblenke** [comment]
That is called SNI, and nginx is capable of it, we just need to make sure nginx and openssl are compiled for it, and that we generate the appropriate nginx.conf template things based on the availability of SSL certs on a per-domain basis.

http://nginx.org/en/docs/http/configuring_https_servers.html#sni

**Comment by wenzowski** [comment]
Thanks @ianblenke I'm well aware of SNI but that's not quite what I was thinking about in this one. I'm using a wildcard myself because SNI support kinda sucks.

It occurred to me that a signed default certificate with a single CN is no worse than a self-signed cert, and that if the CN were to be `deis.domain.tld` then the control plane would work over https without having to ignore the trust chain because there would actually be one.

Solving the problem of 1 cert per app eg. with SNI is ongoing in other issues.

**Comment by carmstrong** [comment]
I think this issue serves as a good pointer should someone need help generating a valid cert. :thumbsup:

The docs in #2911 should help, too.
