### ISSUE TITLE
Domain name validation: w3.domain.com

### ISSUE THREAD

**Issue by gahissy** [deis/deis#3270]
I tried to add a domain to my app: `deis domains:add w3.domain.com`
and got the following error :
`{u'domain': [u'Hostname does not look valid.']}`
w3.domain.com is a valid domain.

**Comment by bacongobbler** [comment]
That's interesting. [RFC 1123](http://tools.ietf.org/html/rfc1123#page-13) allows each hostname label to start and end with a digit, which is what the validation should allow.

This should be as easy as [adding tests](https://github.com/deis/deis/blob/master/controller/api/tests/test_domain.py#L51-L58) for this hostname to validate this, then amending the checks at https://github.com/deis/deis/blob/master/controller/api/serializers.py#L254 to be permissive for these domains.

To confirm, are you on v1.4.1?

**Comment by gahissy** [comment]
Yes @bacongobbler, I am indeed on v1.4.1

**Comment by mboersma** [comment]
In this case, it should be as simple as adding the tests and removing the `or label[-1].isdigit()` clause.

**Comment by bacongobbler** [comment]
> In this case, it should be as simple as adding the tests and removing the or label[-1].isdigit() clause.

:+1:
