### ISSUE TITLE
503's from nginx

### ISSUE THREAD

**Issue by dylanz** [deis/deis#3279]
https://gist.github.com/dylanz/c1c61793fa6b352bf619

We're running at about 80% memory usage across our cluster (CPU usage is low), and everything was humming along fine.  At one point however, performance degraded, and we started getting 503's from nginx when trying to communicate with our cluster.

I found this:  http://serverfault.com/questions/412323/nginx-503-error-in-high-traffic
... which lead me to this:  https://github.com/deis/deis/blob/master/router/image/templates/nginx.conf

I'm assuming we need to customize our worker_connections, which I don't think is a customizable option in the Router yet:  http://docs.deis.io/en/latest/customizing_deis/router_settings/

We're going to try a custom router in the mean time.

If this sounds like I'm moving in the wrong direction, any guesses would be appreciated (above is my best guess =)).  If this ends up being the issue, I'd definitely be game to make this a configurable setting in Router and issue a PR for it.

**Comment by aledbf** [comment]
@dylanz the current configuration in the router is 768 connections per worker. The number of workers depend of the number of CPU cores detected (`worker_processes auto;`).

I opened a PR to allow this customization but you will hit another limits like the number of open files per process. Can you share the output of `lsof -f -p <nginx master pid>`?

**Comment by dylanz** [comment]
@aledbf:  that makes sense.  Here is lsof output from two of our different instances.  The first is from our active backup instance (not running Deis, but is handling inbound traffic), and the second is from our Deis cluster (which shouldn't be receiving inbound traffic at the moment):  https://gist.github.com/dylanz/0459ad377f126593dda8
