### ISSUE TITLE
How to handle large images?

### ISSUE THREAD

**Issue by haf** [deis/deis#3284]
We have written an app that uses three SDKs to build itself; Ruby, Node and Mono/F#. It only uses the mono runtime (150MB) when actually running. However, because we need to install a full build-chain for some gems and for some node packages, the actual image that is pushed to the private registry is `1.898 GB`!

It took 28 minutes to launch...

Since I'm using the 'push a dockerfile and let it build it' workflow (for speed, was my idea), I don't really care about many of the intermediate containers. Could this article be relevant? http://jasonwilder.com/blog/2014/08/19/squashing-docker-images/

**Comment by bacongobbler** [comment]
You'll probably get a better response from the [docker-user mailing list](https://groups.google.com/forum/#!forum/docker-user) as someone there might've followed the same path.

That being said, we some image squishing ourselves in the router by running a script: https://github.com/deis/deis/blob/master/router/build.sh

If you can take advantage of it, there are also a few minimal images like [gliderlabs/docker-alpine](https://github.com/gliderlabs/docker-alpine) which is based on more minimal distros like Alpine Linux.

Hope this helps!
