### ISSUE TITLE
Consider adding mono sample

### ISSUE THREAD

**Issue by haf** [deis/deis#3288]
https://github.com/SuaveIO/Melano

**Comment by bacongobbler** [comment]
We'd be happy to add an F# project to the example list. Currently our example apps follow a standard:

 - by default, when deployed they respond with

```
200 OK HTTP/1.1
Powered by Deis
```

However if someone sets up the envvar POWERED_BY, then that will override "Deis" such that the response will be "Powered by $POWERED_BY". Here's a good example: https://github.com/deis/example-go/blob/master/web.go

Does your melano app behave in that way or would it need a bit of tweaking? :)

**Comment by haf** [comment]
There we go! https://github.com/SuaveIO/Melano/blob/master/src/melano/Program.fs#L1
