### ISSUE TITLE
Proposal feat(controller): add fine-grain scheduling policy

### ISSUE THREAD

**Issue by aledbf** [deis/deis#3289]
The idea behind this is the creation of a default policy to schedule apps inside the cluster using only the patterns shared by different implementations in fleet (the only option for now), mesos (and kubernetes?).
It must be possible to define a default configuration for all the apps but if any app can have a custom policy that will override the default.

The idea of this proposal is to see if this makes sense to other users :)  and what other options to schedule can/should be supported. 

Policies:
- one instance per node
- metadata

proposed etcd content:
```
/deis/controller/schedulerModule                  -> [fleet | mesos]
/deis/controller/schedulingPolicy/default         -> [onePerNode | metadata]
/deis/controller/schedulingPolicy/apps/<app name> -> [onePerNode | metadata]
```

to define the metadata in any app we can use a env var like `DEIS_SCHEDULER_METADATA="rack=rack-1"`

*the definition in deis must be agnostic to the scheduler and only the controller can be aware of the semantic of every scheduler option*

**Only one instance per node:**

mesos:
```
{
 "instances": XX,
 "constraints": [
   ["hostname", "UNIQUE"],
   ["<app name_type.vXXX>", "GROUP_BY"]
 ]
}
```

fleet:
```
{
  "section": "X-Fleet",
  "name": "Conflicts",
  "value": "<app name_type.vXXX>"
}
```

**Schedule using metadata:**

mesos:
```
{
  "instances": XX,
  "constraints": [
    ["rack", "CLUSTER", "rack-1"]
  ]
}
```

fleet:
```
{
  "section": "X-Fleet",
  "name": "MachineMetadata",
  "value": "rack=rack-1"
}
```

https://github.com/coreos/fleet/blob/master/Documentation/unit-files-and-scheduling.md
https://github.com/mesosphere/marathon/blob/master/docs/docs/constraints.md#unique-operator
https://github.com/mesosphere/marathon/blob/master/docs/docs/constraints.md#group_by-operator
https://github.com/mesosphere/marathon/blob/master/docs/docs/constraints.md#cluster-operator

**Comment by PierreKircher** [comment]
+1

**Comment by carmstrong** [comment]
@aledbf We see the motivation behind this, but I think this is difficult for a few reasons:

* Deis arguably shouldn't deal with this level of scheduling, and instead should just deal with a scheduler abstraction much like the one we have now
* Determining the common set of capabilities/features across different schedules is difficult and nearly impossible when the schedulers are changing as rapidly as they are currently
* The motivation behind your policy concerns seem to stem from shortcomings with fleet, and will be addressed once we add support for more advanced schedulers like Kubernetes, Mesos, Swarm, etc.

**Comment by gabrtv** [comment]
@aledbf I'd like to take a closer look at this once #3134 lands in an optional "Swarm Preview".

**Comment by ianblenke** [comment]
Until then, I continue to run this script:

https://gist.github.com/ianblenke/36f1b82efd7eecef0732#file-add-xfleet-conflicts-sh

Purely out of operational necessity.

**Comment by aledbf** [comment]
@ianblenke for the same reason I did this:
https://github.com/soficom/deis/blob/custom_1.3.1/controller/scheduler/fleet.py#L160

**Comment by ianblenke** [comment]
Not knowing django settings whatsoever, how someone set X_FLEET_CONFLICTS?

Would love to see a PR for that, or something very similar to that.

**Comment by aledbf** [comment]
>  how someone set X_FLEET_CONFLICTS?

@ianblenke sorry. From here https://github.com/soficom/deis/blob/custom_1.3.1/controller/templates/confd_settings.py#L56

**Comment by jgmize** [comment]
Now that we have previews for swarm, marathon, and k8s, I'd love to see this issue revisited.

**Comment by bacongobbler** [comment]
Closing as we aren't adding any more features to v1 as we focus on Deis v2. Re-iterating @carmstrong's point, Deis shouldn't deal with this level of scheduling, and instead should just deal with a scheduler abstraction much like the one we have now.
