### ISSUE TITLE
Request: `deis auth:passwd` takes --user argument for admins to change user passwords

### ISSUE THREAD

**Issue by ianblenke** [deis/deis#3292]
Changing your own password with `deis auth:passwd` is easy.
Changing the password for a user who has forgot their password is not.

http://stackoverflow.com/questions/1873806/changing-password-in-django

```
$ docker exec -ti deis-controller ./manage.py shell
WARNING Cannot synchronize with etcd cluster
Python 2.7.6 (default, Mar 22 2014, 22:59:56)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.contrib.auth.models import User
>>> u = User.objects.get(username__exact='theirusername')
>>> u.set_password('iforgotmypassword')
>>> u.save()
```

There really should be an easier way.

**Comment by bacongobbler** [comment]
if we were to implement #3200 we could send out an email with a reset code.

**Comment by carmstrong** [comment]
:+1: I think this is a fairly easy and reasonable feature request.
