### ISSUE TITLE
(builder) Can't set task name /dev/mapper/docker-202:25-3667816-pool

### ISSUE THREAD

**Issue by croemmich** [deis/deis#3294]
If the builder is restarted on the same node the following (fatal) error is thrown:
``Can't set task name /dev/mapper/docker-202:25-3667816-pool ``

I'm a bit unfamiliar with how the device mapper works. I suspect the error may be occurring because a loopback device is being setup in ExecStartPre but not cleaned up in ExecStopPost.
https://github.com/deis/deis/blob/master/deisctl/units/deis-builder.service#L10

This is likely related:
https://github.com/docker/docker/issues/4639

**Comment by carmstrong** [comment]
Great digging, @croemmich. We'll have to figure out what's going on here.
