### ISSUE TITLE
Question: going from docker-compose (fig) to deis?

### ISSUE THREAD

**Issue by olalonde** [deis/deis#3296]
My current project's infrastructure (2 web API servers, a PostgreSQL database and a worker daemon which processes data from the database) is currently managed by docker-compose. This is great for development as I have my entire environment setup with a simple `docker-compose up` command. 

However, it falls short in production (no load balancing, scaling, logging, monitoring, automated deployments, etc.). I'm using Amazon Web Services.

My questions are:

1) Would deis be suitable for my use case in production? Where would the PostgreSQL database fit in the picture?

2) It would be great if my deis configuration could simply be my `docker-compose.yml` to keep things DRY and reduce production/dev environment disparities, perhaps with some additional attributes like container type, scaling, etc. (if that makes sense). Is this being considered for the future?

**Comment by bacongobbler** [comment]
Hi!

> 1) Would deis be suitable for my use case in my production?

We are considered production-ready, so I don't see why not!

>  Where would the PostgreSQL database fit in the picture?

At the moment we have an open enhancement to the project for attaching resources to applications in #231. Until that is solved, you'll have to stand up your own database outside of Deis and [attach the application to the database](http://docs.deis.io/en/latest/using_deis/config-application/#attach-to-backing-services) through credentials stored in the config.

> Is this being considered for the future?

Docker compose specifies container links, exposed ports etc. whereas Deis sets up the exposed port address in the ephemeral range, and does not work with links (links only work across a single host). I think at some point we *may* have something similar to `docker-compose.yml` but it'll look a little different. It's more likely that it'll look closer to Cloud Foundry's [Application Manifest](http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html).

Hope this helps!

**Comment by olalonde** [comment]
Ok thanks. My wish as a developer is to be able to easily reproduce my production environment locally. Docker-compose is officially supported by docker and might eventually become suitable for production deployments (with docker swarm for example) so I think it'd be a good thing for the deis team to keep an eye on it. Just my 2cents.
