### ISSUE TITLE
Failed getting response from http://127.0.0.1:4001/: ssh: rejected: connect failed (Connection refused)

### ISSUE THREAD

**Issue by olalonde** [deis/deis#3304]
After going running the ec2 setup script and trying to install deis, I am getting this error (where 57.172.158.30 is one of the public IPs on EC2):

```bash
$ export DEISCTL_TUNNEL=57.172.158.30
$ deisctl list
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: ssh: rejected: connect failed (Connection refused)
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 100ms
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: ssh: rejected: connect failed (Connection refused)
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 200ms
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: ssh: rejected: connect failed (Connection refused)
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 400ms
```

I also tried setting DEISCTL_TUNNEL to the ELB IP...

```bash
$ export DEISCTL_TUNNEL=deis-1.mydomain.com
$ deisctl list
Error: failed initializing SSH client: timed out while initiating SSH connection
```

**Comment by bacongobbler** [comment]
Hmm, that timeout could mean that etcd could be down or you forgot to add your key to your ssh agent via `ssh-add`. If you SSH into the machine, what's the status of etcd?

**Comment by gvilarino** [comment]
I got that problem once I created a cluster with an old discovery URL in my settings. @olalonde are you sure your discovery URL is right?

**Comment by olalonde** [comment]
I deleted the cloudformation stack and removed the key pair and started from scratch. Platform successfully installed. I'm not entirely sure but I think the issue might have been due to an incorrect ssh key.
