### ISSUE TITLE
"Convenience DNS" to SSH into CoreOS cluster?

### ISSUE THREAD

**Issue by olalonde** [deis/deis#3320]
The docs mention that it is possible to use a domain name to ssh into the coreos cluster but I haven't been able to do so. My deis.domain.com domain resolves to the AWS load balancer IP which only seems to forward port 80 and 2222. Right now, I need to open EC2 and copy/paste the IP address of one of the machines in order to ssh and was wondering if there was a way to setup DNS so I don't have to do that.

**Comment by carmstrong** [comment]
> The docs mention that it is possible to use a domain name to ssh into the coreos cluster but I haven't been able to do so.

I think that refers to the instance public DNS name, which you can find in the EC2 web interface - something like ip-1.2.3.4.us-east.aws.amazon.com. You can't access them using your DNS name that is pointed to the ELB. Sorry for the confusion!

**Comment by olalonde** [comment]
Ok, thanks.
