### ISSUE TITLE
EC2 install: what are the volumes used for?

### ISSUE THREAD

**Issue by olalonde** [deis/deis#3322]
I noticed that the ec2 cluster setup script creates two volumes for each instance (50 GB and 100 GB respectively). Why are 2 volumes needed and what are they both used for? I am asking because I'd like to reduce their sizes but not sure which one would make more sense to resize.

**Comment by carmstrong** [comment]
Details on disk usage is here: http://docs.deis.io/en/latest/managing_deis/disk_usage/

I'd *strongly* recommend against making them smaller. Running out of disk space will cause huge operational headaches, and will likely result in that host no longer functioning properly.

**Comment by olalonde** [comment]
@carmstrong Thanks. I'm mostly using Deis for development now and internal apps and was wondering where I could cut down on AWS fees. Also, do you have any estimates on how much it costs to run the AWS Deis installation per month?
