### ISSUE TITLE
ELB healthchecks failing

### ISSUE THREAD

**Issue by dylanz** [deis/deis#3327]
I've tried starting a 5 machine cluster on EC2 both with specific VPC_ID/SUBNET/ZONE envs set, and, with them unset.  After each deployment, I check the newly created ELB, and all of the instances are marked "OutOfService" with "Instance has failed at least the UnhealthyThreshold number of health checks consecutively."

I'm making sure to run a "make discovery-url" after each attempt, and the only customizations to the cloudformation.json are as follows (the r3.xlarge instance type requires HVM):
```
[
    {
        "ParameterKey":     "KeyPair",
        "ParameterValue":   "deis"
    },
    {
        "ParameterKey":     "InstanceType",
        "ParameterValue":   "r3.xlarge"
    },
    {
        "ParameterKey": "EC2VirtualizationType",
        "ParameterValue": "HVM"
    }
]
```

Any ideas on why this would be happening?

**Comment by ianblenke** [comment]
If you run "fleetctl list-units", are your deis-router instances healthy?

**Comment by bacongobbler** [comment]
The health checks will fail until the routers are up and running on a few hosts. Was this just a bare provision? @ianblenke has the right idea here.

**Comment by dylanz** [comment]
Ugh... this was actually user error.  I had too many clusters up and realized I was logged into the wrong one (one which I hadn't installed the platform on yet).  My healthy cluster has 3 of 5 healthy (the instances that have the router running).  My bad.  Thank you both!
