### ISSUE TITLE
tests: Error starting userland proxy: listen tcp 0.0.0.0:42649: bind: address already in use

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3330]
Documenting an error seen in https://ci.deis.io/job/test-ec2/127/consoleFull#682192135502066c60b2236c09cc9bf8

```
--- FAIL: TestStore (5.00s)
	dockercli.go:265: Error response from daemon: Cannot start container 6f0f70322e1386956a21b4c1f0f05aafaca3c71c07d4583d96173ec9f5b3447c: Error starting userland proxy: listen tcp 0.0.0.0:42649: bind: address already in use
```

**Comment by adamkdean** [comment]
Did you ever find out what was causing this? I'm getting the same issue with some non-Deis Docker stuff.

**Comment by mboersma** [comment]
This [docker issue](https://github.com/docker/docker/issues/8714) looks like it, but they think it's closed in Docker v1.5.0, which disagrees with our experience.

**Comment by adamkdean** [comment]
Hmm, interesting. Thanks. I had it when binding to a specific IP, there was no way the port was in use as I just created that interface! Thanks for the info though, if I hit it again I'll update this thread.

**Comment by webtoed** [comment]
Any updates to this issue? I am seeing it on V 1.8.1 Ubuntu 14.04.3

**Comment by dudheit314** [comment]
@webtoed Maybe mysql service is running? If your in local dev environment you might try ``sudo service mysql stop``

**Comment by mboersma** [comment]
@webtoed are you seeing this when you run `make test-functional` on the deis codebase? This hasn't happened in our CI setup in a long time AFAICT.

**Comment by mboersma** [comment]
This is not evident in Deis v1 CI any more.
