### ISSUE TITLE
Customizing Controller domain

### ISSUE THREAD

**Issue by dylanz** [deis/deis#3335]
We currently have a small cluster who's controller is accessible at deis.foobar.com, but are planning on using a larger cluster (bigger machines).  This cluster is going to use the same domain, and was wondering if there was a way to customize the Controller subdomain (currently "deis") so that I can get the new cluster configured while the old is still running?

I saw the /deis/domains/* setting in http://docs.deis.io/en/latest/customizing_deis/controller_settings/, but I wasn't sure how to access this via deisctl config controller get.

**Comment by bacongobbler** [comment]
This is currently hardcoded in the router as well as the controller (can't let someone create an app with the name `deis` :smile) but I can see the use case for it.

**Comment by dylanz** [comment]
Ah... that makes a lot of sense =)  I'll definitely take a look at what it would take to allow customization to that subdomain, but in the meantime, do you have any thoughts on how to run two parallel platform installations using the same domain?

**Comment by bacongobbler** [comment]
If you modify [this line](https://github.com/deis/deis/blob/master/router/image/templates/nginx.conf#L73) here to the subdomain of your choice and push that change as a custom router, you should be good to go for both controllers on the same domain.

As for application routing, you can try the following DNS records (caveat emptor: here be dragons):

```
* A <first loadbalancer>
* A <second loadbalancer>
```

If that fails to work, you might need to manually set up DNS records for each subdomain. For example, given the following 2 clusters, with cluster A having an app named `foo` and cluster B having an app named `bar`:

```
foo A <first loadbalancer>
bar A <second loadbalancer>
```

Hope this helps!

**Comment by dylanz** [comment]
This is super helpful.  Thank you!
