### ISSUE TITLE
Orphaned bridge interfaces w/ Docker

### ISSUE THREAD

**Issue by dylanz** [deis/deis#3336]
This is more likely a Docker specific issue, but I would think others using a default EC2 cluster would run into something like this (which is why I'm posting it here).

We have a high memory usage Deis installation on machines that can't handle the load, and are currently in the process of migrating to a new cluster.  On our current cluster, it looks like there is a lot of container churn due to these memory issues.  This shouldn't necessarily be "too" much of an issue, but we ran into the following:

```
$ brctl show | wc -l
1024
```

This is a big problem because it prevents us from starting up any more containers
```
FATA[0002] Error response from daemon: Cannot start container b696114a75e6a314cbf9c1929070448f4302f117e175ab5c427cbd7f6496da12: exchange full
```

It seems like it's related to this, https://github.com/docker/docker/issues/1320#issuecomment-22346764, however, it seems like our default cluster install shouldn't have this problem.

```
$ uname -a
Linux ip-10-21-1-34.us-west-2.compute.internal 3.18.1 #2 SMP Tue Feb 3 20:55:12 UTC 2015 x86_64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz GenuineIntel GNU/Linux

$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8-dirty
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8-dirty
```

I'd like to try restarting (and probably upgrading) Docker on the machines in my cluster, but wasn't sure what the process of doing this would be with Deis involved.  Any ideas or suggestions would be greatly appreciated!

**Comment by carmstrong** [comment]
> I'd like to try restarting (and probably upgrading) Docker on the machines in my cluster, but wasn't sure what the process of doing this would be with Deis involved.

Upgrading Docker involves upgrading CoreOS. CoreOS 607.0.0 with Docker 1.5.0 just landed in the stable channel, so you can follow the upgrading instructions to upgrade: http://docs.deis.io/en/latest/managing_deis/upgrading-deis/#upgrading-coreos

**Comment by dylanz** [comment]
Chris!  This is perfect (I missed it).  I did do a "systemctl docker restart" and was able to quickly launch my container before the interface level maxed out again (if that helps anyone else).  I'm definitely going to go for the CoreOS upgrade.  Thanks!

**Comment by anapsix** [comment]
Despite using newer version of CoreOS (633.1.0), I'm having same issue with interfaces maxing out:
```
anapsix@core1 ~ $ brctl show | wc -l
1024

anapsix@core1 ~ $ ip -o link sh | wc -l
18191

anapsix@core1 ~ $ docker info
Containers: 8
Images: 117
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Kernel Version: 3.19.0
Operating System: CoreOS 633.1.0
CPUs: 24
Total Memory: 62.91 GiB
Name: core1.internal
ID: EGWF:6EOB:VPOB:EY5Z:SBLM:FGHL:HG5Y:XA5K:OGAW:EZ6U:OWH2:WOJZ

anapsix@core1 ~ $ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef-dirty
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef-dirty
```

**Comment by bacongobbler** [comment]
@anapsix could you please post this upstream for docker? I'm afraid this is something which is out of our domain. Thanks!

**Comment by anapsix** [comment]
@bacongobbler right.. right..
