### ISSUE TITLE
bug(services) deis apps:destroy doesn't delete root directory

### ISSUE THREAD

**Issue by gvilarino** [deis/deis#3337]
1. Let's say I create app  `mytest`
2. I deploy via `deis pull someImage --app mytest` to it.
3. I run it and use it.
4. I `ssh` into a node and `/opt/bin/deis-debug-logs | grep /deis/services/mytest` lists:
  `/deis/services/mytest`
  `/deis/services/mytest/mytest_v3.cmd.1`
5. Logout and `deis destroy --app mytest --confirm mystest`
6. Wait for a bit
7. `ssh` back into a node and `/opt/bin/deis-debug-logs | grep /deis/services/mytest` lists:
    `/deis/services/mytest`

Am I getteing this wrong or this should be removed as well by `deis destroy`?

I think I'm being unable to create apps with a previously used name because of this (I get `500`s from the deis api)

**Comment by gvilarino** [comment]
@bacongobbler indicated that those directories *should* be deleted automatically, [as can be deduced from this code](https://github.com/deis/deis/blob/master/controller/api/models.py#L909-L911). But it doesn't seem to be working. 

I'm fixing these cases manually with `etcdctl rm --recursive /deis/services/mytest` but that doesn't scale for prod.

**Comment by mboersma** [comment]
Perhaps publisher isn't deleting the directory itself after TTL expires.

**Comment by aledbf** [comment]
I think that it could be easier to add a TTL to the directory https://github.com/coreos/etcd/blob/master/Documentation/api.md#using-a-directory-ttl (removing the directory could be a problem if the app is using scale > 1 and scheduled in different nodes)

**Comment by gvilarino** [comment]
Can you suggest ways to debug this? I'm sort of at a loss with this.
