### ISSUE TITLE
Proposal feat(controller): allow deis pull from deis-registry

### ISSUE THREAD

**Issue by aledbf** [deis/deis#3341]
Something like

```
deis pull —from-internal-registry application-a:version -a application-b
```

to allow the deploy in `application-b` from `application-a` without using internal ip addresses

**Comment by mboersma** [comment]
This could also be a use case for [`deis push`](#2680), and we would rather add new functionality to that than on top of `deis pull` I think.

**Comment by babarinde** [comment]
This s really a needed feature.
Thanks for the work
@aledbf @mboersma
Can I Pull (and Push ) from the deis-registry from a coreos node in the cluster ?
Also if i do ``` deis pull example.com:5000/image:v2 -a app```
Is this good practice as against using the Internal Ip of the registry

**Comment by aledbf** [comment]
@babarinde the idea of this proposal is to avoid the search of the ip inside the cluster where the registry is running.

> Can I Pull (and Push ) from the deis-registry from a coreos node in the cluster ?

yes, just use the ip inside the cluster `docker pull <ip>:5000/app:vXX`

> Also if i do deis pull example.com:5000/image:v2 -a app

that's the idea of deis pull :)  (http://deis.io/demo-deis-pull-in-action/)

> Is this good practice as against using the Internal Ip of the registry

I don't know if is a "good practice" but for me solves a huge problem (have 1 app as "template" and N "copies", is useful to pull from the cluster without any external connection)

**Comment by babarinde** [comment]
@aledbf   
> that's the idea of deis pull :) (http://deis.io/demo-deis-pull-in-action/)

 How does deis resolve example.com:5000 to the internal IP of the registry when the registry is not scaled to 3

**Comment by aledbf** [comment]
> How does deis resolve example.com:5000 to the internal IP of the registry when the registry is not scaled to 3?

If you do not specify a full hostname:port `deis pull` will use the public docker registry to retrieve the image. Remember that this is a proposal to change that behavior.


Now how deis resolve the registry if there's more than one is the easy part :) 
check with `etcdctl ls --recursive /deis/registry` the key `/deis/registry/host` contains the registry that is acting as "master" (you can have multiple registries in the cluster but only one is used to pull/push)

**Comment by deis-admin** [comment]
This issue was moved to deis/controller#1227
