### ISSUE TITLE
If buildpack crashes, deis-builder won't accept any new pushes.

### ISSUE THREAD

**Issue by joshmackey** [deis/deis#3342]
We have a node.js buildpack that runs some gulp tasks. If one of those tasks crashes, it appears that deis-builder hangs. It won't accept any new builds and errors with "Another git push is ongoing. Aborting..."

Restarting the builder seems to fix for now but the builder shouldn't hang.

Buildpack: https://github.com/EQCO/heroku-buildpack-nodejs

**Comment by carmstrong** [comment]
This sounds like a bug scenario where we're not cleaning up the lockfile: https://github.com/deis/deis/blob/777ef1c50ae1809f150c8695b388988fb1fac9d9/builder/image/templates/gitreceive#L45-L69

**Comment by joshmackey** [comment]
To add onto this, it may not be a crash. One of the gulp tasks hangs indefinitely and will continue to hang even if the push is canceled (ctrl-c) resulting in the same issue.

**Comment by ianblenke** [comment]
We've had this same problem with Dockerfile based deployments every now and then. It's not just Buildpack deployments. It doesn't happen all that often.

Manually cleaning out the lockfile on deis-builder fixes it.

**Comment by joshmackey** [comment]
Is there an easy way to clean it out without restarting the deis-builder container?

**Comment by ianblenke** [comment]
If memory serves, the lockfile is either in /tmp or under /home/git/{project} 

    docker exec -ti deis-builder /bin/bash -li

**Comment by onbjerg** [comment]
Also happens if your computer shuts down mid push. Even a rollback won't help.
