### ISSUE TITLE
Proposal: Admins can create new users

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3343]
We currently have the ability to [disable user registration](http://docs.deis.io/en/latest/managing_deis/operational_tasks/#disabling-user-registration) entirely, but a common scenario is that admin users want to be able to create users, but to disallow just anyone from creating an account.

The proposal is to have three registration permission modes:
* Users can register themselves (the default)
* No users can register (`registrationEnabled`, which we currently have)
* Only admins can create user accounts (`registrationByAdminOnly` or something similar)

These could even be collapsed into one setting called something like `registrationMode`.

**Comment by bacongobbler** [comment]
:+1: from me. Seems to solve the most common use cases. Administrators can just create an account, email the credentials w/ a temp password and ask the user to `auth:passwd` afterwards as is the norm in the IT world.

**Comment by Joshua-Anderson** [comment]
I would be interested in takeling this. I think I will add this to the users endpoint under `users:create`. Sound good?

**Comment by bacongobbler** [comment]
We should be able to plug into `auth:register` with only allowing administrators to register based on some arbitrary django setting.

**Comment by Joshua-Anderson** [comment]
OK. Will do.

**Comment by Joshua-Anderson** [comment]
@carmstrong Does #3393 fit your requirements?

**Comment by carmstrong** [comment]
> Does #3399 fit your requirements?

It sure does! :+1:
