### ISSUE TITLE
Submodules support without .git

### ISSUE THREAD

**Issue by ianblenke** [deis/deis#3349]
Reading through #3305 and having had my PR #3172 closed, I'm left scratching my head here.

In the PR review for #3172 this morning, I'm sure you discussed how submodules would work with #3305. I'm just not seeing it.

Consider this issue a documentation request on how someone can make use of submodules without including the .git directory.

**Comment by ianblenke** [comment]
Seriously though, am I stuck maintaining my own fork? Would it acceptable as a PR if I put a switch in here that made including .git optional?

**Comment by bacongobbler** [comment]
Here's how I understand how submodules work:

 - all submodules are listed in the `.gitmodules` record file
 - When you `git submodule update --init`, the modules included in the record are cloned using the listed remote
 - `ssh://` remotes in `.gitmodules` rely on your SSH agent for authentication against remote repositories, which is how #3305 came to be.

Given my understanding, I'm not quite sure how adding `.git` here is relevant. What is there inside of `.git` that is required to initialize and update your submodules?

**Comment by ianblenke** [comment]
I think I understand the confusion.

The .gitmodules record file merely tracks the refs to the git repos, but it does not track the SHA1's.

Meaning, if I:

```console
git submodule add git@github.com:ianblenke/otherproject.git otherproject/
```

you will see a .gitmodules file like:

```
[submodule "otherproject"]
	path = otherproject
	url = git@github.com.ianblenke/otherproject.git
```

The key point of using a submodule for otherproject/ isn't merely to have a link to a foreign repo, it is to track a specific SHA1 of the foreign repo.

This SHA1 is present in even a shallow clone of .git, as the folder reference otherproject/ is actually stored in the git tree leaf as the SHA1 itself.

Disambiguating the remote origin of the otherproject/ folder is the function of the .gitmodule file.

I too once thought as you, that the .gitmodule somehow magically encapsulated the entirety of submodules. Unfortunately, this is not the case.

This is why I need a shallow clone of the .git folder. My developers work from features branches and need to track the SHA1 of submodule folders for associated projects that are also implementing associated feature branches. When they deploy these feature branches to an environment as a deis application, it is critical that the submodules be tied to the SHA1 present in the shallow .git tree, so as not to track the master branch by default.

**Comment by ianblenke** [comment]
I'm going to generate another PR, this time with some logic that detects if there is a .gitmodules file - if there is, it will do a git clone and include the .git folder, otherwise it will revert to the present behavior. Any concerns with this?

**Comment by bacongobbler** [comment]
If it's conditional when .gitmodules is present, I'm fine with that

**Comment by Crispy1975** [comment]
How are git submodules working right now - if at all? We have a requirement for submodules at build time, so would be great if this was working.

**Comment by bacongobbler** [comment]
there were a few attempts but they never passed CI. Submodules don't work at the moment.

**Comment by Crispy1975** [comment]
@bacongobbler thanks, I figured as much, a shame, would be a great things to see. :+1:

**Comment by technosophos** [comment]
Do git subtrees work? The mechanics might just be different enough...

(Good overview: http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/)

**Comment by Crispy1975** [comment]
@technosophos cool idea, I'm working on a project using submodules now but would be painless to make the switch if they do work. I shall report back if it works...

**Comment by Crispy1975** [comment]
@bacongobbler @technosophos Ok, so for us the git subtree idea worked perfectly in place of the submodule. We have a simple rep with some bash deployment scripts that pull in keys and such at build time, with the submodule this didn't work, but using the git subtree idea it worked perfectly. Me happy. :)

**Comment by azurewraith** [comment]
I'll have to play around with the subtree functionality.  I stumbled across needing something similar to submodules again.

**Comment by azurewraith** [comment]
Using subtrees results in duplicated (separated if you `--squash`) history which I'm pretty strongly against.  I'll just have to keep wishing for submodule support in Deis :)

**Comment by bacongobbler** [comment]
closing; let's keep the discussion over in #1094.
