### ISSUE TITLE
bug(test): during the test if the user app is stopped it continues running

### ISSUE THREAD

**Issue by aledbf** [deis/deis#3352]
instead of fail.

Steps to reproduce:
- during the test enter in any node.
- stop the app.
- the suite will continue running instead of throwing an error

*Why is relevant?*
In case of an error in the deployed app it will restarted until the next output:
```
Mar 22 04:31:15 deis-01 systemd[1]: configsample_v9.cmd.1.service holdoff time over, scheduling restart.
```
then the service will stop and the suite will continue running.

**Comment by mboersma** [comment]
Do you mean we have to wait until the 10 minute go test timeout before we see that the app has gone away?

**Comment by aledbf** [comment]
Closing. Not reproducible since 1.11
