### ISSUE TITLE
Deis limits isn't as forgiving as it could be

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#3354]
[nathan@omega hedgehog]$ deis limits:set web=1024MB worker=512MB
Applying limits... 400 BAD REQUEST
{u'memory': [u'Limit format: <number><unit>, where unit = B, K, M or G']}

The error format isn't also very nice...

**Comment by bacongobbler** [comment]
Yes the client could read those errors and display them better, but the syntax is 1024M and 512M

**Comment by mboersma** [comment]
This message comes more or less directly from Docker's [constraints docs](https://docs.docker.com/reference/run/#runtime-constraints-on-cpu-and-memory). Deis passes these args through to Docker essentially. I agree it could be written more clearly. It also wasn't obvious to me that **B**ytes is the default. Suggestions?

**Comment by nathansamson** [comment]
I think the client should not leak implementation details anyway.

I had read the deis docs on setting limits, and then just typed MB on auto-pilot. It felt more intuitive...

The client should support MB/GB etc as alternatives to M, G, ...
Additionally for consistency it probably needs to support Mb & Gb as well, although I can't really see the use case for this

**Comment by bacongobbler** [comment]
> It also wasn't obvious to me that Bytes is the default. Suggestions?
 
We could explicitly write out in the docstring that the values are represented in bytes.

> I had read the deis docs on setting limits, and then just typed MB on auto-pilot. It felt more intuitive...

We could add support for MB/GB if it makes it easier for people to remember. We'd just need to strip the extra `B` before we make the API request.

> Additionally for consistency it probably needs to support Mb & Gb as well

There's no way to pass a value of bits to docker so we can't support that until it's supported upstream.

**Comment by smothiki** [comment]
There is no hard enforcement of syntax on  specifying memory from docker side . I think we should return an Error only if docker engine errors out and accept any syntax.
```
$ sudo docker run -d --name serame -m 30MB busybox sleep 30
$ docker inspect serame|grep Memory
        "Memory": 31457280,
        "MemorySwap": 0,
$ sudo docker run -d --name serame -m 30M busybox sleep 30
$ docker inspect serame|grep Memory
        "Memory": 31457280,
        "MemorySwap": 0,
$ sudo docker run -d --name serame -m 30Mb busybox sleep 30
$ docker inspect serame|grep Memory
        "Memory": 31457280,
        "MemorySwap": 0,
$ sudo docker run -d --name serame -m 30mb busybox sleep 30
$ docker inspect serame|grep Memory
        "Memory": 31457280,
        "MemorySwap": 0,
$ sudo docker run -d --name serame -m 30MK busybox sleep 30
FATA[0000] invalid size: '30MK'
```
