### ISSUE TITLE
Deis builder should do best effort to keep git checkout

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#3355]
I udnerstand that deis builder will throw away all git checkouts it has on a reboot / node movement.

Problem is when pushing a branch with rather some history, this might take a while every time.

I think deis builder should do a best (better than currently) to keep a quick checkout of branches.
I am thinking of a new container / volume that has all repos, that can be fetched.
Ofcourse in case that is down, or the repo isn't available there it must keep current behaviour to just repush the branch from scratch..

This will be even more important when deis builder is scalable (I hope there are plans for this) in large clusters

Hreoku displays "fetching branch" when pushign to an existing app, so I assume they push branches to a central (but distributed) location, fetch it locally from the datacenter (which should be fast), and then accepts new pushes from there on.
I hope we can achieve something similar...

**Comment by carmstrong** [comment]
I think this could be achieved by having builder consume a `deis-store-volume` mount. This is an optimization that we could see being optional for users who want this performance improvement.

**Comment by deis-admin** [comment]
This issue was moved to deis/builder#471
