### ISSUE TITLE
Best Practices for Staging Environment

### ISSUE THREAD

**Issue by hhff** [deis/deis#3362]
Hi Friends!

Just getting started with Deis.  Got it up and running in a Vagrant box - and successfully deployed the example sinatra app twice:

```bash
# Setup "prod"
deis create
git push deis master

# Then for "staging"
deis apps:create

# output:
Creating application... done, created nested-quilting
fatal: remote deis already exists.
Could not create Deis remote

# Manually add remote:
git remote add deis-staging ssh://git@deis.local3.deisapp.com:2222/nested-quilting.git
git push deis-staging master

# success
```

However now when I run `deis anything:anything` it will only ever refer to the "Production" version of the application.

What's the best practice here?

Happy to add to the docs when I know!

**Comment by olalonde** [comment]
I think you can specify an `-a appID` flag for most commands. e.g.: `deis logs -a nested-quilting` to view your staging logs. The other option would be  clone the repo in another directory and treat it as a separate app maybe? `git remote add deis ssh://git@deis.local3.deisapp.com:2222/nested-quilting.git`.

**Comment by johanneswuerbach** [comment]
As commented by @olalonde `-a` is the way to go. I recommend to actually make `staging` your `deis` remote and `production` something like `deis-production`. deis-cli uses the `deis` remote as default target and nothing is worse then running `deis config:set DB=my-new-db` accidentally against production.

Setup:

git remote | app | command
-------- | ----- | -------------
deis | staging-app | deis config:set X=Y
deis-production | production-app | deis config:set X=Y -a production-app

**Comment by hhff** [comment]
amazing - thankyou both!

**Comment by bacongobbler** [comment]
Also note that there are a few new option flags in master for `apps:create` which will help with some of this orchestration:

```
  -r --remote REMOTE
    name of remote to create. [default: deis]
```

Sounds like this question is answered so I'll go ahead and close this, but please re-open if you feel like there's something here that we need to fix. Thanks! :)

**Comment by hhff** [comment]
thanks @bacongobbler!
