### ISSUE TITLE
Deis: minimal installation to reduce AWS cost

### ISSUE THREAD

**Issue by olalonde** [deis/deis#3363]
I would like to adopt Deis for our production deployments but as we are a small 2 dev team in early stages (not much traffic) and we'd like to keep Deis as minimal as possible to avoid AWS cost.

Are there any cost estimates for running the default ec2 Deis install for a month? Where can we cut down on resources to keep the cost low?

**Comment by johanneswuerbach** [comment]
The default deis setup based on 3 m3.large instances is around 350$ / month (including 50$ / month for volumes) 3 m3.medium instances might also work ($200 / month including volumes), but aren't officially supported.

deis was build for cluster (3+ instances). When your deployment does not require that much resources yet, checkout https://github.com/progrium/dokku, which requires only a single instance.

**Comment by bacongobbler** [comment]
The other maintainers can correct me if I'm wrong but our AWS scripts are for a production deployment right out the door. If you're looking to cut costs, You can run on DigitalOcean for $120 per month (3 nodes with 4GB of RAM @ $40 per month), though you'll be limited to 180GB for hard drive space and you'll be missing out on stuff like ELB/Route53.

**Comment by mboersma** [comment]
I want to test if `m3.medium` instances still work for the EC2 test suite, so we could save a few pennies here and there in the tests, but past experience shows `m3.large` is necessary for a real cluster. DigitalOcean is much cheaper although @bacongobbler points out some of the tradeoffs.

**Comment by kelvin22** [comment]
Any updates on running Deis on m3.medium or smaller?

**Comment by mboersma** [comment]
Deis CI tests do run sucessfully with m3.medium by default since this PR was merged, but m3.large or better is recommended for longer-lived, production clusters.

**Comment by olalonde** [comment]
I wonder if it would be possible to run a [Ceph less Deis](http://docs.deis.io/en/latest/managing_deis/running-deis-without-ceph/) on a single m3.medium/large VM. I believe etcd can work on a single machine. I might try that eventually.

**Comment by carmstrong** [comment]
@olalonde You'd lose all the advantages of a highly-available platform. For one-node platforms, we recommend Dokku: https://github.com/progrium/dokku
