### ISSUE TITLE
Save into a different remote name when deis remote already exists

### ISSUE THREAD

**Issue by ghostbar** [deis/deis#3368]
I want to be able to create several different instances of the same app, for example: production, staging, beta, branch-x.

Doing `deis create staging` works, but it fails to create the remote. It's easy to do it manually but maybe it would be nice to have `deis create` to recognize there's a remote called like that already and do something like `git remote add deis-staging ssh://...`.

**Comment by bacongobbler** [comment]
In master there's a new option flag `-r` or `--remote` which will allow you to write to a different remote. Will that work for you?

**Comment by mboersma** [comment]
I wouldn't like `deis` to automagically create the remote this way. I think the `--remote` flag handles this case.

**Comment by bacongobbler** [comment]
ping

**Comment by mboersma** [comment]
I'm closing this since `deis create --remote` covers this use case. @ghostbar please let us know if we've missed something.

**Comment by ghostbar** [comment]
I'm just checking this in. This has been the perfect solution, I'm already using it a lot on my daily workflow.

Thanks a lot!
