### ISSUE TITLE
change domain name and gateway fails to restart

### ISSUE THREAD

**Issue by kgk** [deis/deis#3370]
I had to change the domain name from a test platform to our true domain name. 
After stop/uninstall/install/start I seem to get stuck during the store-gateway restart..

deis-store-gateway@1.service: activating/start-post  

This is on ec2.

Do I need to shutdown/restart the ec2 cluster. If I do, what is the procedure for that?

Thanks,
Kris 

I tried:

deisctl stop platform 
...
deisctl uninstall platform 
...
deisctl config platform set domain=biobisque.org
...
$ deisctl install platform
● ▴ ■
■ ● ▴ Installing Deis...
▴ ■ ●

Storage subsystem...
deis-store-daemon.service: loaded                                 
deis-store-volume.service: loaded                                 
deis-store-metadata.service: loaded                                 
deis-store-monitor.service: loaded                                 
deis-store-gateway@1.service: loaded                                 
Logging subsystem...
deis-logger.service: loaded                                 
deis-logspout.service: loaded                                 
Control plane...
deis-database.service: loaded                                 
deis-controller.service: loaded                                 
deis-cache.service: loaded                                 
deis-builder.service: loaded                                 
deis-registry@1.service: loaded                                 
Data plane...
deis-publisher.service: loaded                                 
Routing mesh...
deis-router@2.service: loaded                                 
deis-router@3.service: loaded                                 
deis-router@1.service: loaded                                 
Done.
$ deisctl start platform 
● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●

Storage subsystem...
deis-store-monitor.service: active/running                                 
deis-store-daemon.service: activating/start-pre                                 
deis-store-daemon.service: active/running                                 
deis-store-metadata.service: active/running                                 
deis-store-gateway@1.service: activating/start-post

**Comment by bacongobbler** [comment]
were you able to resolve this? I recall there's an issue where the gateway can get locked up somehow (a `deisctl restart gateway@1` solves this), but the original issue and deis-store-gateway failing to start look unrelated.

**Comment by kgk** [comment]
I actually tried a fresh install, but ran into some issues there too.. I think tried shutting down the cluster (on amazon) and restarting with a fresh cluster, but probably made some mistakes because I got the same error.

**Comment by carmstrong** [comment]
@kgk Please see if this behavior continues on Deis v1.5.0. We switched from using Apache to a built-in web server for gateway, and I suspect that you won't see the issue anymore.

If you do, or if we can help at all, feel free to ping us on this issue.
