### ISSUE TITLE
 All the given peers are not reachable (Tried to connect to each peer twice and failed)

### ISSUE THREAD

**Issue by zyxia** [deis/deis#3371]
hello again ,and  i have install and start the deis platform half an hour ago. and when i Inspecting health follow the step of doc ,and run ceph -s .it is good now.
however when i exit the deis-01,and run deisctl list .it shows me unable to connected to ............
so  i guss something wrong when is exit the ceph.  so i remove all coreos in the virtualbox,and rebuild deis all. i get the deis source again,and really run  make discovery-url .and when i follow the step  deisctl config platform set sshPrivateKey=~/.vagrant.d/insecure_private_key.
 it shows me  All the given peers are not reachable (Tried to connect to each peer twice and failed).

**Comment by bacongobbler** [comment]
did you use an old discovery URL? http://docs.deis.io/en/latest/troubleshooting_deis/#all-the-given-peers-are-not-reachable

**Comment by bacongobbler** [comment]
it's either that or etcd's down. Do you still have the logs available?

**Comment by zyxia** [comment]
thank you .i have solve it .by make discovery-url before vagrant up .
