### ISSUE TITLE
Command 'run' fails when using a non-standard SSH port

### ISSUE THREAD

**Issue by a-saad** [deis/deis#3378]
When using a non-standard port, the deis run command fails with a "Connection refused" error. I tracked it down the fleet scheduler not taking SSH port into account while establishing an SSH connection. See https://github.com/deis/deis/blob/master/controller/scheduler/fleet.py#L261

**Comment by a-saad** [comment]
Also, any thoughts on a work around other than deploying a patched controller?

**Comment by bacongobbler** [comment]
No workarounds that I know of. Our documentation explicitly says that we listen on ports 22, 80, 443 and 2222. If you're running SSH on non-standard ports then you'll have to patch the controller.

**Comment by carmstrong** [comment]
> other than deploying a patched controller?

Nope, that's the only option. I don't think this is a common enough use case to accommodate in Deis itself. For more information on customizing a component, see: http://docs.deis.io/en/latest/customizing_deis/controller_settings/
