### ISSUE TITLE
PV clock drift causes more ceph havok

### ISSUE THREAD

**Issue by ianblenke** [deis/deis#3386]
I am running nothing but CoreOS 607 instances now, in both of my environments.

While load testing our 3-node staging cluster, the cluster was a bit slow. Looking into the problem, I noticed that one of these PV based instances had drifted 10-15 seconds into the future. I turned up ntp and synced the times. Not more than 15 minutes later, two of our instances became non-responsive. After rebooting both instances from the AWS console, we stopped the load testing, and I spent a couple of hours piecing back together the fleet units that had fallen over - repairing ceph in the process.

**Comment by mboersma** [comment]
We are scratching our heads about what else can be done to ensure clock sync. Was it definitely drift that made etcd/fleet go unresponsive?

**Comment by carmstrong** [comment]
Ceph hammer was just released, and @aledbf has seen that it seems to be more stable and less susceptible to clock drift issues. We'll bump that for v1.6.0.
