### ISSUE TITLE
deis run: Authentication failed

### ISSUE THREAD

**Issue by ineu** [deis/deis#3394]
When I try to use `deis run`, I receive
```
> $ deis run rails r 'puts RUBY_VERSION'
Running `rails r puts RUBY_VERSION`...
500 INTERNAL SERVER ERROR
<h1>Server Error (500)</h1>
```
The problem is with authentication:
```
> $ deis logs | tail
2015-03-30T06:28:03UTC deis[api]: example: Ineu runs 'rails r puts RUBY_VERSION'
2015-03-30T06:28:14UTC deis[api]: example: example_v54.run.6 (run): Authentication failed.
```

Responding with 500 in this case is highly confusing. 401 would be better code to respond with. Even better would be to display 'authentication failed' message directly to user.

**Comment by bacongobbler** [comment]
This authentication failure means that the key you supplied with `deisctl config platform set sshPrivateKey` is not the same key used to authenticate against the CoreOS servers. The 500 error in this case is correct because it's an internal authentication error from server configuration rather than a user error.

**Comment by ineu** [comment]
So, if I understand this and https://github.com/deis/deis/issues/2614#issuecomment-87723478 this key should be added twice: private key should be put into sshPrivateKey and according public key should be put into /home/core/.ssh/authorized_keys on every server. Am I correct?

**Comment by bacongobbler** [comment]
Correct. Usually the pubkey's added to authorized_keys via the provisioning scripts but if you're running on bare metal then you'd have to do this yourself.

**Comment by ineu** [comment]
I was a bit confused by https://github.com/deis/deis/issues/2614#issuecomment-64963352 because to access CoreOS hosts I use my usual `~/.ssh/id_rsa.pub` and not dedicated `~/.ssh/deis.pub`, while it's `~/.ssh/deis` which is added to sshPrivateKey. Now I got it, thanks a lot!
