### ISSUE TITLE
Installing Deis on DigitalOcean prompts password

### ISSUE THREAD

**Issue by onbjerg** [deis/deis#3396]
Hey!

I'm currently installing Deis on DigitalOcean. When I run the custom firewall script, it asks me to enter a password.

![Terminal output](http://imgur.com/GweTSMB.png)

CoreOS does not use passwords. I have configured the SSH key as shown in the guide.

Any help is appreciated, thanks.

**Comment by onbjerg** [comment]
@bacongobbler I understand that you initially wrote the DO scripts, if I am not mistaken. Any info?

**Comment by aledbf** [comment]
@onbjerg you need root permissions to run that script. Please use `sudo`

**Comment by onbjerg** [comment]
I've tried using sudo multiple places now. No change. Also, it keeps prompting me that the host ID changed.

![Terminal output](http://imgur.com/4suokVk)

**Comment by bacongobbler** [comment]
@onbjerg you'll have to log in as the root user rather than the core user to run the script.

**Comment by onbjerg** [comment]
@bacongobbler No luck.

![Terminal output](http://imgur.com/OOwqnbG.png)

**Comment by bacongobbler** [comment]
Hmm, that seems like an SSH authentication failure. Not sure why that's happening though, since your SSH key should be used and password authentication should be completely disabled.

The DO provision scripts are just a glorified wrapper around https://github.com/nathansamson/docl

**Comment by aledbf** [comment]
@onbjerg please try this:
```
for i in 1 2 3; do ssh core@deis-$i.pfmedia.dk sudo contrib/util/firewall.sh;done
```

**Comment by onbjerg** [comment]
@bacongobbler I've tried multiple times from scratch, as I thought I was maybe doing something wrong. Same result each time. I've made sure that I've also read the docs on this very carefully.

@aledbf ![Terminal output](http://imgur.com/1fH37I7.png)

**Comment by aledbf** [comment]
@onbjerg you have an issue with the dns for those names

```
aledbf:~ aledbf$ dig -t any deis-1.pfmedia.dk

; <<>> DiG 9.10.2 <<>> -t any deis-1.pfmedia.dk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53689
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;deis-1.pfmedia.dk.		IN	ANY

;; ANSWER SECTION:
deis-1.pfmedia.dk.	3593	IN	A	178.62.254.77
deis-1.pfmedia.dk.	3593	IN	A	188.166.58.153
deis-1.pfmedia.dk.	3593	IN	A	188.166.17.187

;; Query time: 3 msec
;; SERVER: 192.168.2.1#53(192.168.2.1)
;; WHEN: Mon Mar 30 12:32:06 CLST 2015
;; MSG SIZE  rcvd: 94

aledbf:~ aledbf$ dig -t any deis-2.pfmedia.dk

; <<>> DiG 9.10.2 <<>> -t any deis-2.pfmedia.dk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8212
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;deis-2.pfmedia.dk.		IN	ANY

;; ANSWER SECTION:
deis-2.pfmedia.dk.	3599	IN	A	188.166.17.187
deis-2.pfmedia.dk.	3599	IN	A	178.62.254.77
deis-2.pfmedia.dk.	3599	IN	A	188.166.58.153

;; Query time: 404 msec
;; SERVER: 192.168.2.1#53(192.168.2.1)
;; WHEN: Mon Mar 30 12:32:13 CLST 2015
;; MSG SIZE  rcvd: 94

aledbf:~ aledbf$ dig -t any deis-3.pfmedia.dk

; <<>> DiG 9.10.2 <<>> -t any deis-3.pfmedia.dk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14742
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;deis-3.pfmedia.dk.		IN	ANY

;; ANSWER SECTION:
deis-3.pfmedia.dk.	3599	IN	A	178.62.254.77
deis-3.pfmedia.dk.	3599	IN	A	188.166.58.153
deis-3.pfmedia.dk.	3599	IN	A	188.166.17.187

;; Query time: 375 msec
;; SERVER: 192.168.2.1#53(192.168.2.1)
;; WHEN: Mon Mar 30 12:32:20 CLST 2015
;; MSG SIZE  rcvd: 94
```


You need that each host resolve only to one IP. This is because each CoreOS machine has a different ssh key (and that's the error that you are seeing)
To check if this is the issue you can change this in your machine changing the /etc/hosts file with something like this:
```
178.62.254.77 deis-1.pfmedia.dk
188.166.58.153 deis-2.pfmedia.dk
188.166.17.187 deis-3.pfmedia.dk
```

and before the execution of the loop please remove the lines for this hosts in your `know_hosts file` and run `ssh core@<host>` for each host

**Comment by onbjerg** [comment]
Hmm.

I've added 3 more DNS records to see if it fixes it. Waiting for propogation. I will check back when it is done.

**Comment by onbjerg** [comment]
I don't know. I added the entries to the hosts file, but I still get the same error.

![Terminal output](http://imgur.com/anGgVLv.png)

**Comment by aledbf** [comment]
@onbjerg you can use the root account to run ssh to the nodes. Please use the `core` user

**Comment by onbjerg** [comment]
@aledbf Still prompting for password.

**Comment by bacongobbler** [comment]
@onbjerg sorry but it all works for me:

```
><> ./contrib/digitalocean/provision-do-cluster.sh nyc3 ****** 4GB bacon
Provisioning bacon-1...
Waiting for droplet to become available.......Completed
You can connect to your Droplet via
***.***.***.***
Provisioning bacon-2...
Waiting for droplet to become available......Completed
You can connect to your Droplet via
***.***.***.***
Provisioning bacon-3...
Waiting for droplet to become available......Completed
You can connect to your Droplet via
***.***.***.***
Your Deis cluster has successfully deployed to DigitalOcean.
Please continue to follow the instructions in the README.
><> ssh core@***.***.***.***
 * *    *   *****    ddddd   eeeeeee iiiiiii   ssss
*   *  * *  *   *     d   d   e    e    i     s    s
 * *  ***** *****     d    d  e         i    s
*****  * *    *       d     d e         i     s
*   * *   *  * *      d     d eee       i      sss
*****  * *  *****     d     d e         i         s
  *   *****  * *      d    d  e         i          s
 * *  *   * *   *     d   d   e    e    i    s    s
***** *****  * *     ddddd   eeeeeee iiiiiii  ssss

Welcome to Deis			Powered by CoreOS
core@bacon-1 ~ $ sudo su
bacon-1 core # 
```

**Comment by onbjerg** [comment]
Hmm. Odd. I will try again.

**Comment by onbjerg** [comment]
Nope. Same stuff. Maybe it is because my docl has two keys?

**Comment by bacongobbler** [comment]
We have ~8 keys on our account so that wouldn't be the issue

**Comment by onbjerg** [comment]
I don't get it then. This is even a brand new computer, so old conflicting data or something wouldn't be an issue.

**Comment by onbjerg** [comment]
Okay. That was silly. It works now.

I think the issue was, that I uploaded the newly generated Deis key-pair, but it was trying to log in using my regular key-pair. I should've known.

Thank you for your time, though. Really helpful. Also, great project :smile:
