### ISSUE TITLE
deis run should escape commands

### ISSUE THREAD

**Issue by ineu** [deis/deis#3400]
`heroku run 'rails r "puts RUBY_VERSION"'` performs as expected, outputs
```
2.2.1
```

`deis run 'rails r "puts RUBY_VERSION"'` hangs infinitely.
`fleetctl list-units | grep 'run\.'`:
```
example_v56.run.12.service				8059d8cd.../192.168.0.3	inactive	dead
```

`fleetctl journal example_v56.run.12.service`:
```
-- Logs begin at Tue 2015-03-24 11:30:59 UTC, end at Tue 2015-03-31 07:02:02 UTC. --
Mar 31 07:01:58 staging-coreos-3 systemd[1]: [/run/fleet/units/example_v56.run.12.service:7] Trailing garbage, ignoring.
Mar 31 07:01:58 staging-coreos-3 systemd[1]: example_v56.run.12.service lacks both ExecStart= and ExecStop= setting. Refusing.
Mar 31 07:01:59 staging-coreos-3 systemd[1]: [/run/fleet/units/example_v56.run.12.service:7] Trailing garbage, ignoring.
Mar 31 07:01:59 staging-coreos-3 systemd[1]: example_v56.run.12.service lacks both ExecStart= and ExecStop= setting. Refusing.
Mar 31 07:02:00 staging-coreos-3 systemd[1]: [/run/fleet/units/example_v56.run.12.service:7] Trailing garbage, ignoring.
Mar 31 07:02:00 staging-coreos-3 systemd[1]: example_v56.run.12.service lacks both ExecStart= and ExecStop= setting. Refusing.
Mar 31 07:02:00 staging-coreos-3 systemd[1]: [/run/fleet/units/example_v56.run.12.service:7] Trailing garbage, ignoring.
Mar 31 07:02:00 staging-coreos-3 systemd[1]: example_v56.run.12.service lacks both ExecStart= and ExecStop= setting. Refusing.
Mar 31 07:02:01 staging-coreos-3 systemd[1]: [/run/fleet/units/example_v56.run.12.service:7] Trailing garbage, ignoring.
Mar 31 07:02:01 staging-coreos-3 systemd[1]: example_v56.run.12.service lacks both ExecStart= and ExecStop= setting. Refusing.
```

`fleetctl cat example_v56.run.12.service`:

```
[Unit]
Description=example_v56.run.12 admin command

[Service]
ExecStartPre=/bin/sh -c "IMAGE=$(etcdctl get /deis/registry/host 2>&1):$(etcdctl get /deis/registry/port 2>&1)/example:v56; docker pull $IMAGE"
ExecStartPre=/bin/sh -c "docker inspect example_v56.run.12 >/dev/null 2>&1 && docker rm -f example_v56.run.12 || true"
ExecStart=/bin/sh -c "IMAGE=$(etcdctl get /deis/registry/host 2>&1):$(etcdctl get /deis/registry/port 2>&1)/example:v56; docker run --name example_v56.run.12 --entrypoint=/runner/init -a stdout -a stderr $IMAGE 'rails r "puts RUBY_VERSION"'"
TimeoutStartSec=20m
```

So the problem here is that arguments to runner are not escaped. Not only this breakes unit file, but can also be used to add extra arguments to `sh` invocation, which is a security issue. No user input should ever be interpolated unsanitized.

**Comment by bacongobbler** [comment]
The thing is that the command *is* escaped... Just not being escaped properly. This is due to how unwieldy the [run template](https://github.com/deis/deis/blob/master/controller/scheduler/fleet.py#L383-L389) is.

**Comment by ineu** [comment]
Wouldn't it be simpler to wrap user input into shell script and attach it to the runner container via `-v` option?

**Comment by bacongobbler** [comment]
@ineu not without re-implementing our own docker scheduler, which is something we're avoiding entirely. Just trying to use the tools that fleet provides to us.

@gabrtv has hinted before that we are looking into a cleaner implementation in the future which I predict will land with #3134.

**Comment by ineu** [comment]
@bacongobbler Ok, I see. Is there an easy fix for this escape issue? It looks like a security problem to me. Is it possible to manually replace `"` -> `\"` and `'` -> `\'` before interpolating them into template? Sorry, I know nothing of Go templates.

**Comment by carmstrong** [comment]
> Is there an easy fix for this escape issue? It looks like a security problem to me. Is it possible to manually replace " -> \" and ' -> \' before interpolating them into template?

We would *love* to have someone else take a stab at this. Every time we try to improve this, we end up breaking someone else's use. We'd welcome a PR that re-evaluates how `deis run` commands are passed to the scheduler.

**Comment by carmstrong** [comment]
To be specific, the issue is with the systemd unit. Systemd does its own escaping which conflicts with our escaping.

/cc @gabrtv

**Comment by gabrtv** [comment]
@carmstrong that's correct.  We _are_ escaping commands, the problem is that systemd interpolates any `${VAR}` syntax  that ends up in a unit file.  We plan to address this over time with a better scheduler for batch jobs, but it will take a few release cycles to get there.

In the meantime, if you are running complex commands with fancy shell, you should consider including those scripts in your application source and calling it with `deis run bin/myscript.sh`.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776), and Deis v2 uses kubernetes which should handle this for us so I'm going to go ahead and close this. Considering that there is the workaround @gabrtv provided that should work for v1. Thanks!
