### ISSUE TITLE
Private key file is encrypted

### ISSUE THREAD

**Issue by diddeb** [deis/deis#3402]
When running:

```
$ deis run echo 'Ehlo'
Running `echo Ehlo`...
500 INTERNAL SERVER ERROR
<h1>Server Error (500)</h1>
```

...on a (EC2) Deis cluster the log output is:

```
2015-03-31T20:26:59UTC deis[api]: foo-bar: diddeb runs 'echo Ehlo'
2015-03-31T20:27:09UTC deis[api]: foo-bar: foo-bar_v13.run.5 (run): Private key file is encrypted
```

I have tried finding more details on the error message itself to no avail.

**Comment by bacongobbler** [comment]
was your private key already encrypted when you ran `deisctl config platform set sshPrivateKey`?

**Comment by diddeb** [comment]
No, it was not. And it's still not, on my local FS.

**Comment by bacongobbler** [comment]
Do you happen to require a password for the key? http://stackoverflow.com/a/15597194/2853424 seems to indicate that a password may be required, which is something which we currently do not support.

**Comment by diddeb** [comment]
No, there's no password on the key:

```
$ ssh-add ~/.ssh/deis
Identity added: /Users/diddeb/.ssh/deis (/Users/diddeb/.ssh/deis)
```

Weird?

**Comment by bacongobbler** [comment]
yes, that's very weird. I'd try and see if you can reproduce this with paramiko locally and see if you can figure out if it's a bug or a feature with them.

The relevant code in Deis is https://github.com/deis/deis/blob/master/controller/scheduler/fleet.py#L254-L263. We base64 encode the private key when you upload it to etcd hence why the b64 decode is necessary here.

**Comment by diddeb** [comment]
I rebuilt the cluster. Not a problem now. Writing it off as me being silly – although I am not sure how or when it happened. Thanks for your patience & help @bacongobbler!
