### ISSUE TITLE
'Container type {} does not exist in application'.format(container_type))

### ISSUE THREAD

**Issue by olalonde** [deis/deis#3404]
I have a Node.js app with a `package.json` file and a start script (`node ./server/index.js`). When I `git push deis`, I receive the following error:

```
-----> Launching...
2015/04/01 15:31:32 failed retrieving config from controller: &{%!s(*http.body=&{0xc20800ae10 0xc208058120 0xc20805a420 true {0 0} false}) {%!s(int32=0) %!s(uint32=0)} %!s(bool=false) <nil> %!s(func(error)=0x49c180) %!s(func() error=0x49c110)}
```

Following the advice [given here](https://github.com/deis/deis/issues/3290#issuecomment-78965073) by @aledbf , I checked the logs of deis-controller and am getting this:

```
Apr 01 15:18:54 ip-10-21-1-80.ec2.internal sh[4183]: 'Container type {} does not exist in application'.format(container_type))
Apr 01 15:18:54 ip-10-21-1-80.ec2.internal sh[4183]: EnvironmentError: Container type web does not exist in application
```

How can I fix this? Is this a problem with deis or my app?

**Comment by johanneswuerbach** [comment]
Do you have a Procfile? If not, could you create one with the following content:
`web: node ./server/index.js`

**Comment by olalonde** [comment]
The Procfile solved the problem. I was under the impression it was optional :(

**Comment by bacongobbler** [comment]
it's only optional if the buildpack supplies one!

**Comment by olalonde** [comment]
The logs did say the a Procfile was generated though. Do I need to do something with `deisctl` for this to work without a Procfile?

**Comment by bacongobbler** [comment]
If the default procfile being supplied by the buildpack is not being respected, then that's a bug. I'll re-open and see if I can reproduce this.

**Comment by bacongobbler** [comment]
Can reproduce on master with example-nodejs-express: https://gist.github.com/bacongobbler/0a530ebaf08685b20d09

**Comment by bacongobbler** [comment]
The issue is that slugbuilder is not appending the Procfile to the `.release` file when the buildpack is finished compiling. I'll file a fix for that.
