### ISSUE TITLE
deis-store-daemon: auto-restart

### ISSUE THREAD

**Issue by Natsuke** [deis/deis#3413]
Hi everyone,

We've launched a 3 node cluster using deis v1.4.1.
```deisctl install platform``` worked well but when we start platform ```deisctl start platform```
we enter in a deis-store-daemon auto-restart loop. As we see, ceph didn't start.

Here is a gist with more informations : [deis-store-daemon](https://gist.github.com/Natsuke/da51a69d6ca2652f3b3e)

Ask for more information. Thanks in advance for your help !

**Comment by bacongobbler** [comment]
This looks related to https://github.com/deis/deis/issues/3240 and https://github.com/deis/deis/issues/2521

**Comment by carmstrong** [comment]
> This looks related to #3240 and #2521

Not quite - the error here is `error creating empty object store in /var/lib/ceph/osd/ceph-2: (22) Invalid argument`. I have seen this when developing the deis-store components, but was resolved by using `--net host` when running the container so that the container has access to the host's full network stack.

@Natsuke Did you ever figure this out?

**Comment by Natsuke** [comment]
@carmstrong As I can see the daemon already run using the --net host
```sh
$ cat /var/lib/deis/units/deis-store-daemon.service
[Unit]
Description=deis-store-daemon

[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=20m
ExecStartPre=/bin/sh -c "docker inspect deis-store-daemon-data >/dev/null 2>&1 || docker run --name deis-store-daemon-data -v /var/lib/ceph/osd ubuntu-debootstrap:14.04 /bin/true"
ExecStartPre=/bin/sh -c "IMAGE=`/run/deis/bin/get_image /deis/store-daemon` && docker history $IMAGE >/dev/null 2>&1 || docker pull $IMAGE"
ExecStartPre=/bin/sh -c "docker inspect deis-store-daemon >/dev/null 2>&1 && docker rm -f deis-store-daemon >/dev/null 2>&1 || true"
ExecStartPre=/usr/bin/sleep 10
ExecStart=/bin/sh -c "IMAGE=`/run/deis/bin/get_image /deis/store-daemon` && docker run --name deis-store-daemon --volumes-from=deis-store-daemon-data --rm -e HOST=$COREOS_PRIVATE_IPV4 -p 6800 --net host $IMAGE"
ExecStopPost=-/usr/bin/docker rm -f deis-store-daemon
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

[X-Fleet]
Global=true
```

**Comment by Natsuke** [comment]
I alse run `docker ps -a` on one node and the store seem to don't take the right name
```sh
# docker ps -a
CONTAINER ID        IMAGE                       COMMAND                CREATED             STATUS                       PORTS                                    NAMES
992c78bcc30a        deis/store-monitor:v1.5.1   "/app/bin/boot"        19 minutes ago      Up 19 minutes                                                         deis-store-monitor
b5f4c8cf86a8        deis/store-daemon:v1.5.1    "/app/bin/boot --net   2 hours ago         Up 7 minutes                 6800/tcp, 6801/tcp, 6802/tcp, 6803/tcp   gloomy_sammet
a9454679460b        deis/store-daemon:v1.5.1    "/app/bin/boot --net   2 hours ago         Exited (137) 7 minutes ago                                            agitated_rosalind
52b0266a0621        ubuntu-debootstrap:14.04    "/bin/true"            3 hours ago         Exited (0) 3 hours ago                                                deis-store-daemon-data
9fc47f2bf534        ubuntu-debootstrap:14.04    "/bin/true"            3 hours ago         Exited (0) 3 hours ago                                                deis-store-monitor-data
```

**Comment by Natsuke** [comment]
Also deisctl restart platform made store daemon considering ceph directory to be created:
```
Apr 21 13:10:54 core1 systemd[1]: Starting deis-store-daemon...
Apr 21 13:11:04 core1 systemd[1]: Started deis-store-daemon.
Apr 21 13:11:04 core1 sh[11731]: store-daemon: starting daemon on core1...
Apr 21 13:11:04 core1 sh[11731]: 2015-04-21 13:11:04.268860 7f47faaf1900  0 ceph version 0.87.1 (283c2e7cfa2457799f534744d7d549f83ea1335e), process ceph-osd, pid 1
Apr 21 13:11:04 core1 sh[11731]: 2015-04-21 13:11:04.269044 7f47faaf1900 -1  ** ERROR: unable to open OSD superblock on /var/lib/ceph/osd/ceph-1: (2) No such file or directory
Apr 21 13:11:04 core1 systemd[1]: deis-store-daemon.service: main process exited, code=exited, status=1/FAILURE
Apr 21 13:11:04 core1 docker[11788]: Error response from daemon: No such container: deis-store-daemon
Apr 21 13:11:04 core1 docker[11788]: time="2015-04-21T13:11:04Z" level="fatal" msg="Error: failed to remove one or more containers"
Apr 21 13:11:04 core1 systemd[1]: Unit deis-store-daemon.service entered failed state.
Apr 21 13:11:04 core1 systemd[1]: deis-store-daemon.service failed.
Apr 21 13:11:09 core1 systemd[1]: deis-store-daemon.service holdoff time over, scheduling restart.
Apr 21 13:11:09 core1 systemd[1]: Stopping deis-store-daemon...
Apr 21 13:11:09 core1 systemd[1]: Starting deis-store-daemon...
```

**Comment by carmstrong** [comment]
```
b5f4c8cf86a8        deis/store-daemon:v1.5.1    "/app/bin/boot --net   2 hours ago         Up 7 minutes                 6800/tcp, 6801/tcp, 6802/tcp, 6803/tcp   gloomy_sammet
a9454679460b        deis/store-daemon:v1.5.1    "/app/bin/boot --net   2 hours ago         Exited (137) 7 minutes ago                                            agitated_rosalind
```

@Natsuke That definitely looks wrong that there are two `store-daemon`s - even though only one is running now, that could have caused you problems. Did you try to start one of them manually? I don't know how it could be in that state by just using `deisctl` to stop and start our containers. Our service scripts always give containers and explicit name.

**Comment by carmstrong** [comment]
@natsuke I would try `docker stop gloomy_sammet` and then `deisctl restart store-daemon`.

**Comment by Natsuke** [comment]
@carmstrong I cleared all wrong container, reinstall platform. At the first start daemon container didn't start. A simple platform restart resolve this problem. Now the daemon is running but ```** ERROR: error creating empty object store in /var/lib/ceph/osd/ceph-1: (22) Invalid argument``` is still there.
And now the gateway is in start-post state.
[Here](https://gist.github.com/Natsuke/d6066676df68fcf0b621) is a gist. I hope it'll help.

**Comment by carmstrong** [comment]
@Natsuke I'm sorry - I'm really out of ideas :(

**Comment by mboersma** [comment]
@Natsuke, Deis updated Ceph to the ["hammer" release](http://ceph.com/docs/hammer/release-notes/#v0-94-2-hammer) in v1.6, and there have been many changes made to improve related aspects of platform startup since v1.4.1. 

I'm going to close this issue since it hasn't had any activity in almost two months, but please let us know if you have better success with the current [Deis v1.7.3](http://docs.deis.io/en/latest/installing_deis/quick-start/#get-the-source).
