### ISSUE TITLE
deis tags per process type

### ISSUE THREAD

**Issue by azurewraith** [deis/deis#3416]
It could be useful if you could configure process types to run in particular places based on fleet metadata with deis tags.

For example, if you have asynchronous workers that don't necessarily have to be on a fast machine but you want your web processes on better hardware.  Or you have asynchronous workers which require a lot of CPU/Memory and you want to schedule them only on hardware that could support it.

Right now, you have to have separate apps for them which can lead to a lot of redundancy, multiple pushes/envirionment config, etc.

I understand not everyone is running a heterogeneous cloud environment but there is some aspect of cluster cost maintenance untapped here where you could have redundant large hosts paired with redundant smaller hosts and reserve the large hosts for process types that need them.  Case in point here from a deis core perspective, the deis-builder.

**Comment by bacongobbler** [comment]
I can see the use case for this. This is actually how `deis limits` works too, so it makes sense :+1:

**Comment by azurewraith** [comment]
Yeah, `deis limits` can help with this problem in the sense that a process type won't eat up more CPU/Memory then you lend it.  If your machines are all equally powerful, then this works well.  I had forgotten you could set limits by process type, though.

**Comment by carmstrong** [comment]
I think this makes a lot of sense and is worth exploring :+1:

**Comment by fabiob** [comment]
Have anyone started to work on this?

I tried to start something, but I got really lost on the Django migrations.

**Comment by robholland** [comment]
It would be great to have `deis tags` extended to support this. We have a lot of applications with frontend and backend components which we'd like to segregate.

**Comment by deis-admin** [comment]
This issue was moved to deis/controller#1212
