### ISSUE TITLE
bug(controller): If is not possible to access etcd it should fail with an error

### ISSUE THREAD

**Issue by aledbf** [deis/deis#3417]
Right now any command that uses etcd (like upload the user key) will just show this message
```
WARNING Cannot synchronize with etcd cluster
```
and continue, but the user key is not stored in etcd.

For instance if `etcd` is not available when the user upload the ssh key it will fail to do any push.

**Comment by mboersma** [comment]
Does this mean the `deis` CLI doesn't see an error in this case?

**Comment by aledbf** [comment]
@mboersma that warning is from `deis-controller` If is not possible to access etcd during any get/set operation.

**Comment by bacongobbler** [comment]
I think this was resolved with https://github.com/deis/deis/pull/3791. Is this correct, or is this still an ongoing issue?

**Comment by aledbf** [comment]
@bacongobbler no, I'm sorry, my fault to not be clear. 
I mean here https://github.com/deis/deis/blob/master/controller/api/models.py#L1059
if there's any error connecting to `etcd` you just see a warning in the controller logs and the content of `etcd` is not the correct one (the operation from the controller failed)

**Comment by bacongobbler** [comment]
Ah, I see where you're coming from here. I know that this is a workaround so we can run unit tests locally without having to set up etcd, but yes that would indeed be an issue.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776), and etcd is going away in Deis v2 so I'm going to go ahead and close this. Thanks!
