### ISSUE TITLE
Environment Variables not being set

### ISSUE THREAD

**Issue by scottrobertson** [deis/deis#3421]
Hey,

I am trying to set RAILS_ENV to staging, but the app seems to just ignore it.

![image](https://cloud.githubusercontent.com/assets/68361/7013908/c42ea1ac-dcb5-11e4-83f8-e2fcc818e55b.png)

I have tried looking for related issues, but i could not see anything, so apologies if this is a duplicate.

**Comment by bacongobbler** [comment]
I think this is something which the buildpack hardcodes: https://github.com/heroku/heroku-buildpack-ruby/blob/e4bd79031406e1da7487d0269c86c895ed226c84/lib/language_pack/rails2.rb#L26-L27

Did you set the config before or after you deployed the application?

**Comment by scottrobertson** [comment]
I set it after yeah. However i figured "When config is changed, a new release is created and deployed automatically." would mean that when it redeploys it uses the new config. 

WIll I have to trigger a new build? Or can it only be set on initial build?

**Comment by bacongobbler** [comment]
Yeah we do create and deploy a new release with the modified changes, but I assume that the buildpack conjures some black magic which hardcodes the value in the application which is out of our control :simple_smile:

Try triggering a new build via `git commit --allow-empty -m "test" && git push deis master` and see how that goes.

**Comment by scottrobertson** [comment]
That worked :) triggering a new build sorted it all.

Do you think I should raise an issue on the buildpack, or is it just what it is?

Thanks for your help

**Comment by scottrobertson** [comment]
Another quick kinda-related question. Is there a way to make it set ENV vars based on the .env file?

**Comment by bacongobbler** [comment]
You can try and see if you can reproduce the issue in heroku. If you can't then maybe there's something here which we can learn and improve upon in Deis. :)

As for the other question, in master there's a new `deis config:push` command which will upload your .env file to Deis. Will that help?

**Comment by scottrobertson** [comment]
I shall have a play around with it on Heroku tomorrow night and let you know.

And yeah, that will help a lot. Maybe load env variables from that file on first push? But that may not be a valid usecase for most people.

Thank you very much for your help.

**Comment by scottrobertson** [comment]
@bacongobbler could I make a request to be able to specify a file in the config:push. As i have a staging app and a production app in the same repo, each have totally separate configs (`.env.production`, `.env.staging`).

**Comment by carmstrong** [comment]
> could I make a request to be able to specify a file in the config:push

I think that request makes a lot of sense. :+1: 

@scottrobertson can you file that as a separate feature request issue? It sounds like this immediate issue is probably resolved.

**Comment by scottrobertson** [comment]
@carmstrong Shall do :)

Thank you both for the help.
