### ISSUE TITLE
Allow file to be specified for config:push

### ISSUE THREAD

**Issue by scottrobertson** [deis/deis#3423]
Hey,

It would be good for `deis config:push` to accept a path to a .env file. 

I have 2 apps setup from 1 repo, one for staging and one for production, each have their own .env files.

An example would be: `deis config:push ./env.production`

**Comment by apps4u** [comment]
ive got some code it reads a config.json file from the project root when creating a projects so on ```deis create``` the config it added to the application so by the time you run ```git push deis master``` the config it in place.
It lets you set RAM, CPU , VALUES etc. it you want Im happy to issue a pull request , It would not be hard to change it to use a .env file ..

**Comment by bacongobbler** [comment]
@apps4u that may be a great candidate for a plugin!

http://docs.deis.io/en/latest/customizing_deis/cli-plugins/

**Comment by scottrobertson** [comment]
@apps4u That would be awesome. Does it let you set all ENV vars?

**Comment by apps4u** [comment]
yes , I’ll create a public repo and issue a push or should I just publish the link as I said its reads from a file called config.json in the project root but it would not be hard to change to read a .env file . Also It has not had any test written for the features I added so the pull request won’t be approved so I’ll just post a link to the repo and copy the code ..

All you need to do is change the default file name from config.json to your .env and then write one or two tests as it required for the pull request to be approved .. 

I use the code every day so its works 100% but I didn’t write a test for it.



Jason Kristian | Director | Apps 4 U Pty Ltd.
ph: +61 075699 8109
mob: +61 0411 389 392
e: Jason Kristian <mailto:jasonk@apps4u.com.au>

**Comment by mboersma** [comment]
+1

**Comment by apps4u** [comment]
Sorry The codes on my laptop and I left it mothers when I went for easter.  so I wont have it back for three days please wait and I'll upload the code then sorry for the delay Ive not added the changes to repo  so its the only copy is on my laptop.

**Comment by onbjerg** [comment]
I have a working bash script for this. It is Heroku-specific, but making it work with a .env file shouldn't be too hard, as the format is the same as the output from ``heroku config``.

https://github.com/onbjerg/heroku-to-deis

**Comment by onbjerg** [comment]
Wow. Ok, I didn't even realize you only needed to make it possible to specify a path. I need to get some more sleep.
