### ISSUE TITLE
Error response from daemon: No such container: deis-logspout

### ISSUE THREAD

**Issue by CptJason** [deis/deis#3425]
![8ac3d3cb-73cf-40d3-968c-7a07af3767dd](https://cloud.githubusercontent.com/assets/397285/7015685/2b18f1f2-dd0a-11e4-859a-027fd803a497.png)

**Comment by bacongobbler** [comment]
Hi! Could you please provide some more info:

 - what version of deis are you running? 
 - how are you able to re-create this issue?

I've been deploying clusters off master all day and haven't seen this. Thanks!

**Comment by CptJason** [comment]
I just used this command " git clone https://github.com/deis/deis.git " to clone, and I found it was version 1.5.0-dev.

**Comment by carmstrong** [comment]
@CptJason Jason What does `journalctl -fu deis-logspout` show? It looks like the error removing the container may be nothing - we remove all containers when they are stopped. Discovering why the service crashed is crucial.

**Comment by CptJason** [comment]
As your mentions, I restored the Vagrantfile, and tried again, at last that error gone.
I've gilded the lily.Thanks!
