### ISSUE TITLE
Any user seems to be able to push to app

### ISSUE THREAD

**Issue by scottrobertson** [deis/deis#3427]
#### Update

Ok, this is maybe worse than I thought. I have managed to fix this, but the issue was that the user didn't have perms on the correct app (i have example-production and example-staging, it just had permission on example-production but i was pushing to example-staging).

So a user who does not have permission on an app, can push to that app.

#### Original Post 

Hey,

Trying to setup continuous integration deployments via CircleCI. I have the following to run:

```
deployment:
    staging:
      branch: master
      commands:
        - git push ssh://git@example:2222/example.com.git $CIRCLE_SHA1:master
```

I created a deploy user, and added the keys for them. 

The issue I am having is that the actual git push works perfectly, but it does not do the actual deployment process for some reason.

```
ubuntu@box1351:~/example.com$ git push ssh://git@example:2222/example.com.git 82143c0798a9c6dc973f76ef88bdad3ef9f15e76:master
Warning: Permanently added the ECDSA host key for IP address '[ip_address]:2222' to the list of known hosts.
Counting objects: 1, done.
Writing objects: 100% (1/1), 178 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To ssh://git@example:2222/example.com.git
   3ca779d..82143c0  82143c0798a9c6dc973f76ef88bdad3ef9f15e76 -> master
```

~~The only difference I can tell is the git client version. The one on CircleCI is 1.8.5.6, locally I am using 2.3.5.~~

Edit: Nope, not that. Upgraded git client and it still does not trigger hooks.

Edit: Could this be due to user permissions or something? The user has collab permissions on the application.

Thanks for any help.

**Comment by scottrobertson** [comment]
Ok, this is maybe worse than I thought. I have managed to fix this, but the issue was that the user didnt have perms on the correct app (i have example-production and example-staging, it just had example-production but i was pushing to example-staging).

So a user who does not have permission on an app, can push to that app.

**Comment by bacongobbler** [comment]
hey @scottrobertson, while this looks like a bug, it's not necessarily an issue. Any authenticated user may be able to `git push` to a repository, but the controller will deny the upload request unless said user has access to the app: https://github.com/deis/deis/blob/master/controller/api/views.py#L298-L301

However, the builder should deny the `git push` if the user does not have access, which seems like it's something which the builder is not doing correctly. That is certainly a bug which we need to fix, but it's not nearly as catastrophic as it seems :)

**Comment by scottrobertson** [comment]
Hey @bacongobbler, you are right, it's not that big a deal :)

The most annoying thing about it is that it then blocks me from pushing again from a real user. I have to commit something else and push again.

**Comment by carmstrong** [comment]
> The most annoying thing about it is that it then blocks me from pushing again from a real user. I have to commit something else and push again.

Definitely annoying, and this is certainly something we need to fix. Thanks for reporting and for the detailed write-up, @scottrobertson!
