### ISSUE TITLE
deis-logspout crashing/stuck in auto-restart

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3428]
It seems like logspout has lately been crashing for a few of our users.

We've had a few reports of this lately, although we don't have much to go on. See https://github.com/deis/deis/issues/2293#issuecomment-90713786 for one report.

Perhaps logspout has become less stable in recent releases? If folks run into this, please post relevant log output here. `journalctl -u deis-logspout` on hosts where it's failing is a great start. Thanks!

**Comment by mboersma** [comment]
This hasn't seen any activity for a couple months, and isn't a focus of support now AFAICTL. I'm closing it, but please open specific issues with detail if it recurs.
