### ISSUE TITLE
registry create_bucket - bucket exist check seems non-functional

### ISSUE THREAD

**Issue by Blystad** [deis/deis#3430]
This check doesn't seem to work as expected:

```
if not bucket in conn.get_all_buckets():
  conn.create_bucket(bucket)
```
[registry/templates/create_bucket#L15-L16](https://github.com/deis/deis/blob/95746aadc8e2c77771174f2702dae6fc48951c4d/registry/templates/create_bucket#L15-L16)

`bucket` is a String where as the items in `conn.get_all_buckets()` is of type `boto.s3.bucket`.

I changed it to this:
```
for b in conn.get_all_buckets():
  if b.name == bucket:
    print bucket + ' exists'
    sys.exit(0)

conn.create_bucket(bucket)
```

which seems to maybe work. Going to test it now.

**Comment by carmstrong** [comment]
Good find. Surprised it isn't causing any problems - maybe it silently fails if the bucket already exists and it tries to create it again.

If this works, we'll need to fix it for both database and registry, as they both have this logic.
