### ISSUE TITLE
builder v1.3.1 won't start 

### ISSUE THREAD

**Issue by szymonpk** [deis/deis#3434]
I'm trying to deploy fresh deis 1.5.0 in DigitalOcean (CoreOS 607) and I've issue with builder service startup during `deis platform start`.

    $ journalctl -u deis-builder.service
    ....
    Apr 08 18:31:43 deis-1 sh[4411]: Status: Downloaded newer image for deis/builder:v1.3.1
    Apr 08 18:31:43 deis-1 sh[6874]: /dev/loop0
    Apr 08 18:31:43 deis-1 sh[6892]: Waiting for builder on 2223/tcp...
    Apr 08 18:31:55 deis-1 sh[6891]: 2015-04-08T18:31:55Z f92999f410e4 confd[76]: ERROR exit status 123
    Apr 08 18:31:55 deis-1 sh[6891]: builder: waiting for confd to write initial templates...
    Apr 08 18:32:00 deis-1 sh[6891]: 2015/04/08 18:32:00 docker daemon: 1.3.3 d344625; execdriver:     native; graphdriver: btrfs
    Apr 08 18:32:00 deis-1 sh[6891]: [d6caa525] +job serveapi(unix:///var/run/docker.sock)
    Apr 08 18:32:00 deis-1 sh[6891]: 2015/04/08 18:32:00 prerequisites for driver not satisfied (wrong filesystem?)
    Apr 08 18:33:33 deis-1 sh[6892]: /bin/sh: line 0: echo: write error: Broken pipe

I didn't found anything similar.

**Comment by bacongobbler** [comment]
hi @szymonpk, could you please dump `deisctl config platform get version` as well as `deisctl config builder get image` for me? It's interesting that it's trying to pull v1.3.1 when by default the version should be v1.5.0.

**Comment by szymonpk** [comment]
Both configs aren't there

    $ deisctl config platform get version
    Error: 100: Key not found (/deis/platform/version) [23425]

    $ deisctl --version
    1.5.0

**Comment by bacongobbler** [comment]
okay. Could you also paste the output of `cat /etc/deis-release`? Basically what I'm trying to nail down is how v1.3.1 is getting selected from the `get_image` script: https://github.com/deis/deis/blob/master/contrib/coreos/user-data.example#L134-L146

**Comment by szymonpk** [comment]
$ cat /etc/deis-release
DEIS_RELEASE=v1.3.1

**Comment by bacongobbler** [comment]
It looks like you're using an [older user-data](https://github.com/deis/deis/blob/v1.5.0/contrib/coreos/user-data.example#L112-L115) template. Can you please try again using the user-data template from the v1.5.0 release? Thanks!

**Comment by szymonpk** [comment]
I think I've found it.. old user-data.example, I haven't pulled code between cluster re-installations just updated deisctl.

My fault, sorry :-1:
