### ISSUE TITLE
enforceHTTPS=true causes deis client to bail

### ISSUE THREAD

**Issue by azurewraith** [deis/deis#3437]
Based on the documentation, this should work but doesn't:

    [user@lavos ssl]$ deisctl config router set enforceHTTPS=true
    true  
    [user@lavos django_boilerplate|master]$ deis apps:create django-boilerplate
    Creating application... Couldn't connect to the Deis Controller:
    ('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known'))
    Make sure that the Controller URI is correct and the server is running.
    [user@lavos ssl]$ deisctl config router set enforceHTTPS=false
    false
    [user@lavos django_boilerplate|master]$ deis apps:create django-boilerplate
    Creating application... done, created django-boilerplate
    Git remote deis added

**Comment by croemmich** [comment]
Don't know if it's related, but enforceHTTPS seems to be causing issues in 1.5.0 as the redirects are not happening properly. Did you use http or https when you logged in to the deis client?

**Comment by croemmich** [comment]
After looking into this more, I suspect it's related to #3438.

**Comment by azurewraith** [comment]
enforceHTTPS seems to work better in v1.5.0, it used to be that in order to get it to work in v1.4.1 I had to set it to true, then false.

In v1.5.0 everything else seems to be working great, except the client.

If enforcing HTTPS was working properly for the controller, it wouldn't matter what URL I logged in as or whether I configured SSL for the deis client.

#3438 seems relevant but for normal application access, enforceHTTPS is working for me.

**Comment by azurewraith** [comment]
Actually, I stand corrected... if I restart my routers I get behavior resembling #3438.
