### ISSUE TITLE
bug(router) enforceHTTPS Redirects Improperly

### ISSUE THREAD

**Issue by croemmich** [deis/deis#3438]
After I updated to v1.5.0 enforceHTTPS is creating bogus redirects for non-https requests.

HTTPS:
```
$ wget https://phpinfo.mydeis.com
--2015-04-08 18:21:53--  https://phpinfo.mydeis.com/
Resolving phpinfo.mydeis.com... 104.200.23.83, 2600:3c00:1::68c8:1753
Connecting to phpinfo.mydeis.com|104.200.23.83|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'index.html'

index.html              [ <=>                  ]   3.39K  --.-KB/s   in 0s     

2015-04-08 18:21:53 (60.3 MB/s) - 'index.html' saved [3475]
```

HTTP:
```
$ wget http://phpinfo.mydeis.com
--2015-04-08 18:17:45--  http://phpinfo.mydeis.com/
Resolving phpinfo.mydeis.com... 104.200.23.83, 2600:3c00:1::68c8:1753
Connecting to phpinfo.mydeis.com|104.200.23.83|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://~^phpinfo\.(?<domain>.+)$/ [following]
--2015-04-08 18:17:46--  https://~%5Ephpinfo%5C.(/?%3Cdomain%3E.+)$/
Resolving ~^phpinfo\\.(... failed: nodename nor servname provided, or not known.
wget: unable to resolve host address '~^phpinfo\\.('
```

I'll look in to and create a pull request if I find it, but won't have a ton of time this week.

**Comment by bacongobbler** [comment]
relevant PRs: https://github.com/deis/deis/pull/3264 https://github.com/deis/deis/pull/3266

**Comment by mboersma** [comment]
#3266 is the culprit apparently. I can reproduce this, and reverting to the regex-based redirect seems to fix it.

I'll see if we have some error in the current 301 code and if I can't clean it up, we'll revert.

**Comment by bacongobbler** [comment]
hmm, maybe a switch from `$server_name` to `$host`? I'm not knowledgeable enough about nginx to know the difference but I'd imagine that `$server_name` is expanding to the literal `server_name` entry in the `server` directive.

**Comment by mboersma** [comment]
> maybe a switch from $server_name to $host

Yes, that's what I tried first and it seems to work so far. Makes sense.

**Comment by wenzowski** [comment]
Whoops, guess there was a reason for `$host`. Guess I must have set `$server_name` myself somewhere...sorry folks.

**Comment by mboersma** [comment]
No worries, I should have read the diff more closely and asked that question. :crystal_ball: Thanks again for all your contributions @wenzowski!

**Comment by croemmich** [comment]
Thanks for getting this fixed and released... all in a couple days. I have deployed 1.5.1 and haven't found an issues so far. You guys rock!

**Comment by mboersma** [comment]
@croemmich excellent, thanks very much for following up on `enforceHTTPS` and verifying it works for you in v1.5.1.

**Comment by dmcnaught** [comment]
I'm getting this when running on 1.12.1 with the sample application deploy:

$curl -s http://quirky-playroom.oursite.com
```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.9.6</center>
</body>
</html>
```

If I turn off enforceHTTPS:

$deisctl config router set enforceHTTPS=false

$ curl -s http://quirky-playroom.cafewelltest.com
```Welcome to Deis!
See the documentation at http://docs.deis.io/ for more information.```

**Comment by bacongobbler** [comment]
@dmcnaught this looks related to #4400. Are you on AWS, by any chance?

**Comment by dmcnaught** [comment]
@bacongobbler - it looks similar, and I am on AWS, but I am using the Deis routers to terminate SSL connections.

**Comment by bacongobbler** [comment]
The main problem seems to be that the http_x_forwarded_for header is removed from the ELB because we switched from HTTP listeners to TCP for proxy protocol support pre-1.0, which has caused problems with the request being redirected. See more info at https://github.com/deis/deis/issues/4400#issuecomment-154198112.

Could you please try the following for me?

 - go into EC2 console and switch ELB listening protocol from TCP to HTTP(S)
 - run the following command to disable proxy protocol:

```
$ deisctl config router rm proxyProtocol
```

Then see if the router runs properly.

**Comment by bacongobbler** [comment]
scratch that comment entirely... Need more :tea:. It looks like your application is redirecting properly... You're hitting the `http://` endpoint with `enforceHTTPS` enabled, which forces applications to redirect to `https://`. If you run `curl -sSL http://quirky-playroom.cafewelltest.com`, does it show the success message? (`-L` follows redirects)

**Comment by dmcnaught** [comment]
yeah - that works @bacongobbler 
$ curl -sSL http://quirky-playroom.oursite.com
Welcome to Deis!
See the documentation at http://docs.deis.io/ for more information.

**Comment by bacongobbler** [comment]
Sounds like your application works then as intended. Is there some other behaviour that you were expecting?

**Comment by dmcnaught** [comment]
ok - that's fine. I guess I wasn't expect the sample app to not work with HTTPS enforced, but it makes sense.
