### ISSUE TITLE
Application SSL does not support SAN certificates

### ISSUE THREAD

**Issue by Blystad** [deis/deis#3441]
When I register a SAN certificate using `deis certs:add` only the common name is picked up, not the other SANs (which can be entierly different domain names)

An example certificate can have: `CN=example.com` and `SAN=DNS:example.co.uk,DNS:example.no,DNS:example.io,DNS:my-aweseome-example.com,DNS:other-website.com`

See this for a guide on how to create SAN certificates: http://apetec.com/support/GenerateSAN-CSR.htm

My (hopefully temporary) workaround is to just use platform SSL certificates for now and remove the application SSL solution from my `deis-router`.

**Comment by carmstrong** [comment]
Thanks for reporting this, @Blystad. SAN support is definitely something we want. We're going to look at adding a flag for `deis certs:add` like `--domains` that would allow you to specify which domains a cert should be added to, bypassing our inspection for "normal" SSL certs. This should enable us to support SANs with minimal code changes. Does that make sense?

**Comment by Blystad** [comment]
Sounds good to me.

**Comment by bacongobbler** [comment]
So to gather requirements here with an example:

 - We have an SSL certificate with common name `foo.deisapp.com`
 - A certificate contains SAN entries `bar.deisapp.com`, `car.deisapp.com`, `star.deisapp.com`
 - `deis certs:add <cert>` by default should attach all SAN entries
 - if `--subjaltnames bar.deisapp.com,car.deisapp.com` is supplied, only those two alt names are read in
 - after creating the certificate, no other certificate may claim those names

In that case, this could be an easy PR by just creating additional Certificate objects in the database for each subject alt name. We already have the infrastructure in the controller for this, so it'd just be a client change. This has the effect of having to manually delete each entry for each SAN, but for some users this may be a benefit. Then again, SSL is not my strong point.

@Blystad does this seem good to you?

**Comment by Blystad** [comment]
Sounds good to me.

What about wildcard SSL certificates? (Unrelated isse, but semi relevant)

**Comment by bacongobbler** [comment]
We don't currently support them at this time. We need to address the workflow for that: https://github.com/deis/deis/issues/1608

There is currently some infrastructure in place where you can attach a certificate and a key, but give it a different common name so a wildcard certificate *could* be attached to a specific subdomain, but that means that you'd have to attach the wildcard certificate to every domain which is something that I'd imagine users wouldn't want at this time :)

**Comment by bacongobbler** [comment]
I have a branch available, but it still needs integration tests: https://github.com/bacongobbler/deis/tree/3441-support-san-certificates
