### ISSUE TITLE
deis router unresponsive until restart

### ISSUE THREAD

**Issue by chrisgeo** [deis/deis#3442]
I'm not sure what causes this yet. After sitting idle for hours deis router is throwing a 503 error when attempting to authenticate with the system:

```
503 Service Temporarily Unavailable
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.7.10</center>
</body>
</html>
```

I also see these a large portion in all the logs:
```
sh[2929]: [INFO] - 2015/04/09 11:06:38 [emerg] 14#0: bind() to 0.0.0.0:2222 failed (98: Address already in use)
 503 - "POST /v1/auth/login/ HTTP/1.1" - 390 - "http://host/v1/auth/login/" - "python-requests/2.5.1 CPython/2.7.6 Darwin/14.3.0" - "~^deis\x5C.(?<domain>.+)$" - - - host.com - - - 0.000
```

Upon restart

```
Apr 09 11:08:17 leadgenius-apps-coreos-3 systemd[1]: Stopping deis-router...
Apr 09 11:08:17 leadgenius-apps-coreos-3 sh[2929]: time="2015-04-09T11:08:17Z" level="fatal" msg="Error response from daemon: No such container: 37c2dd69b66d47f3e44fcc3ae75c7d85b69fad6983108a9ea2c5cfd916278a8d"

```

After restarting all of the routers in the cluster after starts working fine again.

**Comment by carmstrong** [comment]
503s are thrown when there are no upstreams for a config section. Where exactly are you seeing the 503? When trying to use the `deis` client to interact with the controller? 

This is also odd:
```
sh[2929]: [INFO] - 2015/04/09 11:06:38 [emerg] 14#0: bind() to 0.0.0.0:2222 failed (98: Address already in use)
```

Port 2222 is used to forward traffic to the builder component. It sounds to me like you had a rogue nginx process somehow (or one that got wedged), and nginx was unable to bind. Restarting should have sorted it out.

**Comment by chrisgeo** [comment]
Moving to #3466
