### ISSUE TITLE
Error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

### ISSUE THREAD

**Issue by CptJason** [deis/deis#3443]
It's ok to play deis on OS X, but there is an error when I play it on Centos 6.6.
============================================
export DEISCTL_TUNNEL=172.17.8.100
[root@deis deis]# deisctl config platform set sshPrivateKey=~/.vagrant.d/insecure_private_key
Error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
============================================
It's very weird。

These are the info that cmd: "journalctl -f " shows:
=======================================================
core@deis-01 ~ $ journalctl -f
-- Logs begin at Thu 2015-04-09 07:45:32 UTC. --
Apr 09 11:44:33 deis-01 etcd[5692]: [etcd] Apr  9 11:44:33.960 INFO      | 467b4aef3e8d47ccb26a61170db8b3ff attempted to join via 172.17.8.102:7001 failed: fail on join request: Raft Internal Error ()
Apr 09 11:44:33 deis-01 etcd[5692]: [etcd] Apr  9 11:44:33.962 INFO      | 467b4aef3e8d47ccb26a61170db8b3ff is unable to join the cluster using any of the peers [172.17.8.101:7001 172.17.8.102:7001 172.17.8.100:7001 172.17.8.101:7001 172.17.8.102:7001] at 0th time. Retrying in 4.8 seconds
Apr 09 11:44:37 deis-01 etcd[5692]: [etcd] Apr  9 11:44:37.965 INFO      | 467b4aef3e8d47ccb26a61170db8b3ff attempted to join via 172.17.8.101:7001 failed: fail checking join version: Client Internal Error (strconv.ParseInt: parsing "404 page not found\n": invalid syntax)
Apr 09 11:44:37 deis-01 etcd[5692]: [etcd] Apr  9 11:44:37.971 INFO      | Send Join Request to http://172.17.8.102:7001/join
Apr 09 11:44:37 deis-01 etcd[5692]: [etcd] Apr  9 11:44:37.974 INFO      | 467b4aef3e8d47ccb26a61170db8b3ff attempted to join via 172.17.8.102:7001 failed: fail on join request: Raft Internal Error ()
Apr 09 11:44:37 deis-01 etcd[5692]: [etcd] Apr  9 11:44:37.976 INFO      | 467b4aef3e8d47ccb26a61170db8b3ff attempted to join via 172.17.8.100:7001 failed: fail checking join version: Client Internal Error (Get http://172.17.8.100:7001/version: dial tcp 172.17.8.100:7001: connection refused)
Apr 09 11:44:37 deis-01 etcd[5692]: [etcd] Apr  9 11:44:37.978 INFO      | 467b4aef3e8d47ccb26a61170db8b3ff attempted to join via 172.17.8.101:7001 failed: fail checking join version: Client Internal Error (strconv.ParseInt: parsing "404 page not found\n": invalid syntax)
Apr 09 11:44:37 deis-01 etcd[5692]: [etcd] Apr  9 11:44:37.984 INFO      | Send Join Request to http://172.17.8.102:7001/join
Apr 09 11:44:37 deis-01 etcd[5692]: [etcd] Apr  9 11:44:37.987 INFO      | 467b4aef3e8d47ccb26a61170db8b3ff attempted to join via 172.17.8.102:7001 failed: fail on join request: Raft Internal Error ()
Apr 09 11:44:37 deis-01 etcd[5692]: [etcd] Apr  9 11:44:37.988 INFO      | 467b4aef3e8d47ccb26a61170db8b3ff is unable to join the cluster using any of the peers [172.17.8.101:7001 172.17.8.102:7001 172.17.8.100:7001 172.17.8.101:7001 172.17.8.102:7001] at 1th time. Retrying in 4.8 seconds
Apr 09 11:44:41 deis-01 etcd[5692]: [etcd] Apr  9 11:44:41.990 INFO      | 467b4aef3e8d47ccb26a61170db8b3ff attempted to join via 172.17.8.101:7001 failed: fail checking join version: Client Internal Error (strconv.ParseInt: parsing "404 page not found\n": invalid syntax)
Apr 09 11:44:41 deis-01 etcd[5692]: [etcd] Apr  9 11:44:41.997 INFO      | Send Join Request to http://172.17.8.102:7001/join
Apr 09 11:44:42 deis-01 etcd[5692]: [etcd] Apr  9 11:44:41.999 INFO      | 467b4aef3e8d47ccb26a61170db8b3ff attempted to join via 172.17.8.102:7001 failed: fail on join request: Raft Internal Error ()
Apr 09 11:44:42 deis-01 etcd[5692]: [etcd] Apr  9 11:44:42.001 INFO      | 467b4aef3e8d47ccb26a61170db8b3ff attempted to join via 172.17.8.100:7001 failed: fail checking join version: Client Internal Error (Get http://172.17.8.100:7001/version: dial tcp 172.17.8.100:7001: connection refused)
Apr 09 11:44:42 deis-01 etcd[5692]: [etcd] Apr  9 11:44:42.002 INFO      | 467b4aef3e8d47ccb26a61170db8b3ff attempted to join via 172.17.8.101:7001 failed: fail checking join version: Client Internal Error (strconv.ParseInt: parsing "404 page not found\n": invalid syntax)
Apr 09 11:44:42 deis-01 etcd[5692]: [etcd] Apr  9 11:44:42.008 INFO      | Send Join Request to http://172.17.8.102:7001/join
Apr 09 11:44:42 deis-01 etcd[5692]: [etcd] Apr  9 11:44:42.011 INFO      | 467b4aef3e8d47ccb26a61170db8b3ff attempted to join via 172.17.8.102:7001 failed: fail on join request: Raft Internal Error ()
Apr 09 11:44:42 deis-01 etcd[5692]: [etcd] Apr  9 11:44:42.013 WARNING   | 467b4aef3e8d47ccb26a61170db8b3ff cannot connect to existing peers [172.17.8.101:7001 172.17.8.102:7001 172.17.8.100:7001 172.17.8.101:7001 172.17.8.102:7001]: fail joining the cluster via given peers after 3 retries
Apr 09 11:44:42 deis-01 etcd[5692]: [etcd] Apr  9 11:44:42.015 CRITICAL  | fail joining the cluster via given peers after 3 retries
Apr 09 11:44:42 deis-01 systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Apr 09 11:44:42 deis-01 systemd[1]: Unit etcd.service entered failed state.
Apr 09 11:44:42 deis-01 systemd[1]: etcd.service failed.
Apr 09 11:44:42 deis-01 systemd[1]: fleet.service holdoff time over, scheduling restart.
Apr 09 11:44:42 deis-01 systemd[1]: Stopping fleet daemon...
Apr 09 11:44:42 deis-01 systemd[1]: Starting etcd...
Apr 09 11:44:52 deis-01 systemd[1]: etcd.service holdoff time over, scheduling restart.
Apr 09 11:44:52 deis-01 systemd[1]: Stopping etcd...
Apr 09 11:44:52 deis-01 systemd[1]: Starting etcd...
Apr 09 11:44:52 deis-01 systemd[1]: Started etcd.
Apr 09 11:44:52 deis-01 systemd[1]: Starting fleet daemon...
Apr 09 11:44:52 deis-01 systemd[1]: Started fleet daemon.

**Comment by PierreKircher** [comment]
etcd problem get a new tocken and reset the full coreos install

**Comment by bacongobbler** [comment]
closing as a duplicate: #3058 #2696
