### ISSUE TITLE
Backup/restore docs should note limitations of store gateway

### ISSUE THREAD

**Issue by krancour** [deis/deis#3445]
http://docs.deis.io/en/latest/managing_deis/backing_up_data/#database-backups-and-registry-data

In my experience, if you have any appreciable amount of stuff in the store, the gateway is easily overwhelmed during s3cmd sync.  Scaling up the number of gateways and running s3cmd sync multiple times both seem to help.

Unless I am totally off on this and this issue is only happening for me, then it probably bears mention in the docs.

**Comment by carmstrong** [comment]
@krancour I think this is a fine addition if you want to take a stab at it.
