### ISSUE TITLE
Interactive Rake Tasks

### ISSUE THREAD

**Issue by scottrobertson** [deis/deis#3449]
Hey,

I have a rake task which requires user input. I use the following very simple way of getting user input:

```ruby
charge = STDIN.gets.strip
```

However, when i run this, i get the following:

```
NoMethodError: undefined method `strip' for nil:NilClass
```

This only happens when running via `deis run`. Is there a better way to run these commands? Or am I doing something stupid?

Thanks
Scott

**Comment by mboersma** [comment]
No interactive task will work in `deis run` until #117 is implemented, unfortunately.

**Comment by scottrobertson** [comment]
Hey @mboersma thanks for that. Do you know of a workaround for now? Or is there not one?

**Comment by nathansamson** [comment]
I ssh into the machine, and run nse tot enter the container.

A hack which you can only do if you are administrator.

Regards.
Op 11 apr. 2015 1:22 PM schreef "Scott Robertson" <notifications@github.com

**Comment by mboersma** [comment]
>  ssh into the machine, and run nse to enter the container.

I think @nathansamson's workaround is the only thing you can do currently, until there is support for interactive `deis run` tasks.

**Comment by bacongobbler** [comment]
let's close this and keep the discussion rolling in #117.

**Comment by scottrobertson** [comment]
@nathansamson thanks for that. I have managed to get into the container, but none of the bundle stuff seems to be installed or working for this session, so i cannot run any rake commands or anything. 

```
bash: rake: command not found
```

**Comment by nathansamson** [comment]
After entering your container you have to run your cmd as "/runner/init
rake" ....

Regards
Op 12 apr. 2015 10:16 AM schreef "Scott Robertson" <notifications@github.com

**Comment by scottrobertson** [comment]
Perfect, thank you @nathansamson
