### ISSUE TITLE
Minimum install of deis consumes a lot of disk space

### ISSUE THREAD

**Issue by joshrtay** [deis/deis#3450]
consider using gliderlabs/docker-alpine as the base image instead of ubuntu

**Comment by PierreKircher** [comment]
not possible everywhere yet + there is work in progess already

**Comment by bacongobbler** [comment]
currently we can't do a true cut-over due to ceph requiring res_nquery from libc: https://github.com/deis/deis/pull/3175#issuecomment-77197581

**Comment by joshrtay** [comment]
didn't see #3715. looking forward to the changes.

**Comment by carmstrong** [comment]
> didn't see #3175. looking forward to the changes.

Going to close in favor of #3175, where we're tracking the alpine changes.
