### ISSUE TITLE
Deis no longer produces app logs after an in-place upgrade

### ISSUE THREAD

**Issue by davidcelis** [deis/deis#3459]
Hi, all. I'm a bit new to Deis so apologies if I just missed something while doing an upgrade. I recently did an in-place upgrade from 1.4.x (I think 1.4.1) to 1.5.0 and I'm having a problem with one of my apps. It's just a Twitter markov chain account so it's not a big deal; I was able to produce a new release of one of my apps (the other is unfortunately plagued by #3458) and `deis ps` shows a process running:

```
% deis ps
=== dcelis-ebooks Processes

--- worker: 
worker.1 up (v9)
```

However, now `deis apps:logs` now only shows release-based logging output:

```
2015-04-11T16:52:36UTC deis[api]: davidcelis scaled containers worker=1
2015-04-11T16:54:31UTC deis[api]: davidcelis scaled containers worker=1
2015-04-11T18:16:17UTC deis[api]: davidcelis deployed ff3399f
2015-04-11T18:23:06UTC deis[api]: davidcelis scaled containers worker=0
2015-04-11T18:23:26UTC deis[api]: davidcelis scaled containers worker=1
```

The framework I am using usually produces logging info to STDOUT upon boot, and I haven't changed the version of that framework, so I expect to see some log output like this:

```
2015-04-08T19:55:01UTC deis[api]: davidcelis deployed bfe540e
2015-04-08T19:55:58UTC dcelis-ebooks[worker.1]: @dcelis_ebooks: starting tweet stream
2015-04-08T19:55:58UTC dcelis-ebooks[worker.1]: @dcelis_ebooks: Online!
```

I followed the documentation to the T, but it seems something is weird with logging. `deisctl` shows that all services are running and active. Any thoughts as to what I should do or try? Thanks!

**Comment by bacongobbler** [comment]
Since the controller's still shipping logs, let's start by taking a look at `logspout`. Could you please SSH into one of the hosts and post the output of `docker logs deis-logspout`? Since it's a global fleet unit, there's no way to grab individual logs via `deisctl` or `fleetctl`.

**Comment by davidcelis** [comment]
```
core@deis-2 ~ $ docker logs deis-logspout
2015/04/11 18:30:11 attach: 386846d4c87b deis-logspout success
2015/04/11 18:30:11 attach: 231e9e1513ca deis-database success
2015/04/11 18:30:11 attach: 5cd2704595c1 deis-router success
2015/04/11 18:30:11 attach: f23972b43bb9 deis-registry success
2015/04/11 18:30:11 attach: b62474b57399 deis-builder success
2015/04/11 18:30:11 attach: c67218d7601b deis-publisher success
2015/04/11 18:30:11 attach: bf3624026d59 deis-store-metadata success
2015/04/11 18:30:11 attach: 0224eb6f2ecb deis-store-daemon success
2015/04/11 18:30:11 attach: c73ff09977f9 deis-store-monitor success
2015/04/11 18:30:11 etcd: http://10.132.68.48:4001
2015/04/11 18:30:11 routing all to 10.132.68.47:514
2015/04/11 18:30:11 loading and persisting routes in /tmp
2015/04/11 18:30:11 logspout serving http on :8000
core@deis-2 ~ $ docker logs deis-logger
FATA[0000] Error response from daemon: No such container: deis-logger 
```

I'm guessing that's the problem!

**Comment by davidcelis** [comment]
Here's the full output of a `deisctl list`

```
% deisctl list
UNIT				MACHINE				LOAD	ACTIVE	SUB
deis-builder.service		95ef2ecf.../10.132.68.48	loaded	active	running
deis-controller.service		df8a013a.../10.132.68.47	loaded	active	running
deis-database.service		95ef2ecf.../10.132.68.48	loaded	active	running
deis-logger.service		df8a013a.../10.132.68.47	loaded	active	running
deis-logspout.service		671116fd.../10.132.68.50	loaded	active	running
deis-logspout.service		95ef2ecf.../10.132.68.48	loaded	active	running
deis-logspout.service		df8a013a.../10.132.68.47	loaded	active	running
deis-publisher.service		671116fd.../10.132.68.50	loaded	active	running
deis-publisher.service		95ef2ecf.../10.132.68.48	loaded	active	running
deis-publisher.service		df8a013a.../10.132.68.47	loaded	active	running
deis-registry@1.service		95ef2ecf.../10.132.68.48	loaded	active	running
deis-router@1.service		df8a013a.../10.132.68.47	loaded	active	running
deis-router@2.service		95ef2ecf.../10.132.68.48	loaded	active	running
deis-router@3.service		671116fd.../10.132.68.50	loaded	active	running
deis-store-daemon.service	671116fd.../10.132.68.50	loaded	active	running
deis-store-daemon.service	95ef2ecf.../10.132.68.48	loaded	active	running
deis-store-daemon.service	df8a013a.../10.132.68.47	loaded	active	running
deis-store-gateway@1.service	df8a013a.../10.132.68.47	loaded	active	running
deis-store-metadata.service	671116fd.../10.132.68.50	loaded	active	running
deis-store-metadata.service	95ef2ecf.../10.132.68.48	loaded	active	running
deis-store-metadata.service	df8a013a.../10.132.68.47	loaded	active	running
deis-store-monitor.service	671116fd.../10.132.68.50	loaded	active	running
deis-store-monitor.service	95ef2ecf.../10.132.68.48	loaded	active	running
deis-store-monitor.service	df8a013a.../10.132.68.47	loaded	active	running
deis-store-volume.service	671116fd.../10.132.68.50	loaded	active	running
deis-store-volume.service	95ef2ecf.../10.132.68.48	loaded	active	running
deis-store-volume.service	df8a013a.../10.132.68.47	loaded	active	running
```

It looks like the following services are only running on one host:

* deis-builder
* deis-controller
* deis-database
* deis-logger
* deis-registry (shown as deis-registry@1)
* deis-store-gateway (shown as deis-store-gateway@1)

Should any of those be running on all hosts instead of just one?

**Comment by davidcelis** [comment]
I completely reinstalled the platform (`deisctl stop platform; deisctl uninstall platform; deisctl install platform; deisctl start platform`) and after a re-deploy of my app, I have logs again. It also allowed me to re-deploy the other app that was experiencing the issue in #3458.

**Comment by carmstrong** [comment]
> I completely reinstalled the platform (deisctl stop platform; deisctl uninstall platform; deisctl install platform; deisctl start platform) and after a re-deploy of my app, I have logs again.

Well, that's good news! I have a feeling the issue was with the store component and that was poked in the restart. Unfortunately, a component showing as "running" doesn't necessarily mean it's functioning properly, and may need to be poked - see #2906. 

Investigating component logs is usually the next step. I'm going to close this since it's resolved. Thank you for the detailed troubleshooting!
