### ISSUE TITLE
Deis application access and error logs not showing in v1.5

### ISSUE THREAD

**Issue by babarinde** [deis/deis#3463]
Hello and Good day,
Thanks for the great jobs you guys do.

I have v1.5 installed and application log drain set in place but i no longer see the access logs and error logs in my application.
when I run ``` deis logs``` i see 
```
2015-04-13T00:49:16UTC adpub[web.1]: bin/heroku-php-apache2: line 292:    92 Terminated              tail -qF -n 0 "${logs[@]}"
2015-04-13T00:49:16UTC adpub[web.1]:         93 Done                    | strip_fpm_child_said 1>&2
```
not sure what this means but also in my logentries, I see logs but no access or error logs as i used to see pre 1.5.
Now I only see a bunch of publisher and deis store monitor logs

Thanks

**Comment by carmstrong** [comment]
> application log drain set in place

Can you elaborate on the drain? I'm wondering if logspout is using that drain instead of our default one, not in addition to it.

**Comment by babarinde** [comment]
@carmstrong 
http://docs.deis.io/en/latest/managing_deis/platform_logging/#application-log-drain

**Comment by bacongobbler** [comment]
chat logs from IRC this morning: https://botbot.me/freenode/deis/2015-04-17/?msg=36867694&page=2

seems like a buildpack issue to me (by that I mean how heroku-buildpack-php ships logs to stdout)

**Comment by bacongobbler** [comment]
ping @babarinde, were you able to resolve this?

**Comment by babarinde** [comment]
@bacongobbler 
Not yet but I think I'll be trying a newer installation of deis on a new cluster(due to some unrelated issues) over the weekend. and will watch out from the start, this time around

**Comment by carmstrong** [comment]
@babarinde Have you run into this again, or should we close the issue?

**Comment by mboersma** [comment]
I'm closing this since there hasn't been an update in a month, but please re-open if there is still an issue here that can be fixed in Deis.

**Comment by alexw23** [comment]
I'm getting this issue - I can't even tail the logs in the heroku-buildpack-php.

**Comment by carmstrong** [comment]
> the recent change in btrfs to overlayfs.

That was almost a year ago now. What version of Deis are you running?
