### ISSUE TITLE
can't execute apps:run

### ISSUE THREAD

**Issue by szymonpk** [deis/deis#3464]
While I'm trying to 'execute' any command on application. I'm getting 500 from controler

    $ deis apps:run "rake db:migrate" -a admin
    Running `rake db:migrate`...
    500 INTERNAL SERVER ERROR
    <h1>Server Error (500)</h1>

journalctl shows:

    Apr 13 06:55:22 deis-3 sh[4123]: 2015/04/13 06:55:22 attach: e89814e9487f admin_v7.run.5 success
    Apr 13 06:55:23 deis-3 fleetd-0.9.2[746]: INFO reconcile.go:332: AgentReconciler completed task: type=UnloadUnit job=admin_v7.run.5.service reason="unit loaded but not scheduled here"
    Apr 13 06:55:23 deis-3 fleetd-0.9.2[746]: INFO reconcile.go:332: AgentReconciler completed task: type=ReloadUnitFiles job=N/A reason="always reload unit files"
    Apr 13 06:55:24 deis-3 sh[5194]: ERROR admin: admin_v7.run.5 (run): Authentication failed.
    Apr 13 06:55:24 deis-3 sh[5194]: ERROR Internal Server Error: /v1/apps/admin/run
    Apr 13 06:55:24 deis-3 sh[5194]: Traceback (most recent call last):
    Apr 13 06:55:24 deis-3 sh[5194]: File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
    Apr 13 06:55:24 deis-3 sh[5194]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
    Apr 13 06:55:24 deis-3 sh[5194]: File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    Apr 13 06:55:24 deis-3 sh[5194]: return view_func(*args, **kwargs)
    Apr 13 06:55:24 deis-3 sh[5194]: File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 85, in view
    Apr 13 06:55:24 deis-3 sh[5194]: return self.dispatch(request, *args, **kwargs)
    Apr 13 06:55:24 deis-3 sh[5194]: File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 407, in dispatch
    Apr 13 06:55:24 deis-3 sh[5194]: response = self.handle_exception(exc)
    Apr 13 06:55:24 deis-3 sh[5194]: File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 404, in dispatch
    Apr 13 06:55:24 deis-3 sh[5194]: response = handler(request, *args, **kwargs)
    Apr 13 06:55:24 deis-3 sh[5194]: File "/app/api/views.py", line 162, in run
    Apr 13 06:55:24 deis-3 sh[5194]: output_and_rc = app.run(self.request.user, request.data['command'])
    Apr 13 06:55:24 deis-3 sh[5194]: File "/app/api/models.py", line 380, in run
    Apr 13 06:55:24 deis-3 sh[5194]: return c.run(escaped_command)
    Apr 13 06:55:24 deis-3 sh[5194]: File "/app/api/models.py", line 514, in run
    Apr 13 06:55:25 deis-3 sh[5194]: rc, output = self._scheduler.run(job_id, image, entrypoint, command)
    Apr 13 06:55:25 deis-3 sh[5194]: File "/app/scheduler/fleet.py", line 261, in run
    Apr 13 06:55:25 deis-3 sh[5194]: ssh.connect(primaryIP, username="core", pkey=pkey)
    Apr 13 06:55:25 deis-3 sh[5194]: File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 307, in connect
    Apr 13 06:55:25 deis-3 sh[5194]: look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
    Apr 13 06:55:25 deis-3 sh[5194]: File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 519, in _auth
    Apr 13 06:55:25 deis-3 sh[5194]: raise saved_exception
    Apr 13 06:55:25 deis-3 sh[5194]: AuthenticationException: Authentication failed.

I'm using deis 1.5.0.

**Comment by bacongobbler** [comment]
that error indicates that the SSH key you provided via `deisctl config platform set sshPrivateKey` (if provided) could not authenticate against the server. Did you set a key, or is your key encrypted?

**Comment by szymonpk** [comment]
My key isn't encrypted and `deisctl config platform get sshPrivateKey` shows proper key.

**Comment by szymonpk** [comment]
sshPrivateKey didn't match /home/core/.ssh/authorized_keys
