### ISSUE TITLE
Unable to build 1.6.0-dev

### ISSUE THREAD

**Issue by ngpestelos** [deis/deis#3465]
Hi,

I ran into this problem while rebuilding my fork of Deis:

`bin/get-app-config.go:101: cannot use body (type []byte) as type *http.Response in argument to builder.ParseConfig`

Has anyone encountered the same problem?

BTW, I'm using Ubuntu 14.04 and Go 1.4.1 to build the sources.

**Comment by bacongobbler** [comment]
`make -C builder build` works fine for me on master.

**Comment by ngpestelos** [comment]
Thank you for your suggestion; I was able to build successfully now.
