### ISSUE TITLE
SSL is broken after upgrade to 1.5.1

### ISSUE THREAD

**Issue by ineu** [deis/deis#3470]
After upgrading deis from 1.4.1 to 1.5.1, which introduced application-level certificates (http://docs.deis.io/en/latest/using_deis/app-ssl/), my previous wildcard certificates (http://docs.deis.io/en/latest/managing_deis/ssl-endpoints/#router-ssl) no longer work. Deployed application work via http, but trying to access them via https always give 404. According to deis-router logs, it tries to route all https requests, whatever subdomain they are for, to deis-controller (in my case 192.168.0.1:8000), like:
```
Apr 13 18:15:13 staging-coreos-2 sh[5425]: [INFO] - [13/Apr/2015:18:15:13 +0000] - 46.219.37.191 - - - 301 - "HEAD / HTTP/1.1" - 183 - "-" - "curl/7.41.0" - "staging.example.com" - 192.168.0.2:49159 - staging.example.com - 0.000 - 0.000
Apr 13 18:15:23 staging-coreos-2 sh[5425]: [INFO] - [13/Apr/2015:18:15:23 +0000] - 46.219.37.191 - - - 404 - "HEAD / HTTP/1.1" - 214 - "-" - "curl/7.41.0" - "~^deis\x5C.(?<domain>.+)$" - 192.168.0.1:8000 - staging.example.com - 0.003 - 0.003
```
First request is http, seconds is https. Obviously `staging.example.com` doesn't match `^deis` wildcard, but this upstream is chosen, probably because it is first in nginx.conf.

**Comment by ineu** [comment]
Looks like the problem is https://github.com/deis/deis/blob/master/router/image/templates/nginx.conf#L161-L163
Does it mean that I no longer can use wildcard certificate for custom domains?

**Comment by ineu** [comment]
What do you guys think about following solutions for custom domains:
1. If sslKey is set and there's no custom certificate for the domain, enable platform certificate.
2. If custom certificate contains asterisk, remove it and match against domain, so not only exact matches would work, but wildcards as well.

**Comment by Blystad** [comment]
This is related to #3441 Application SSL does not support SAN certificates

I suggest you just create a custom router for now.

Just replace these lines: [router/image/templates/nginx.conf#L158-L169](https://github.com/deis/deis/blob/fa48fd21e9aed44f7c50c43211b96dfa4c28f21e/router/image/templates/nginx.conf#L158-L169) with ` include deis.conf;` and you should be good to go. That's what I did.

**Comment by ineu** [comment]
@Blystad Thank you, plan in #3441 sounds great to me.

**Comment by carmstrong** [comment]
@bacongobbler This definitely sounds like a regression. If users use a router-level wildcard certificate, that should apply to *all* domains as it did before. We'll need to address this and consider #3441 as a potential solution.

**Comment by bacongobbler** [comment]
> This definitely sounds like a regression. If users use a router-level wildcard certificate, that should apply to all domains as it did before.

That should be unchanged, but if it isn't then yes it's a regression. I specifically [called that out](http://docs.deis.io/en/latest/using_deis/app-ssl/) in the docs, so if it isn't working then it's definitely a regression

> Note
> deis certs is only useful for custom domains. Default application domains are SSL-enabled already and can be accessed simply by using https, e.g. https://foo.deisapp.com (provided that you have installed your wildcard certificate on the routers or on the load balancer).

**Comment by carmstrong** [comment]
> That should be unchanged, but if it isn't then yes it's a regression. I specifically called that out in the docs, too

Look at the code @Blystad called out:

> Just replace these lines: router/image/templates/nginx.conf#L158-L169 with include deis.conf; and you should be good to go. That's what I did.

Not including deis.conf at all for app domains seems like the culprit.

**Comment by carmstrong** [comment]
@ineu @Blystad Would you mind testing out the proposed solution in #3519? You can upgrade your routers by:
```console
$ deisctl config set router image=deisci/router:jenkins-test-ec2-580
$ deisctl restart router@*
```

**Comment by ineu** [comment]
@carmstrong Works for me, thank you.
