### ISSUE TITLE
deis run is not attaching stdin

### ISSUE THREAD

**Issue by jwaldrip** [deis/deis#3473]
I am trying to do a `deis run bash` on a deployed docker container. As soon as it starts it disconnects as if stdin was closed. Help. I need into the container.

**Comment by szymonpk** [comment]
As far as I know it's not yet possible to run interactive processes via deis run. If you want get into container you can ssh to host machine (via fleet ssh or directly) and run `nse container-name`.

**Comment by carmstrong** [comment]
> As far as I know it's not yet possible to run interactive processes via deis run.

Exactly correct - see #117.
