### ISSUE TITLE
Deis domains:remove removing all domains

### ISSUE THREAD

**Issue by babarinde** [deis/deis#3475]
Hello and Good day guys and thanks for the great work

Am experiencing a strange behaviour in v1.5
when i add two domains to my app using the 
```deis domains:add my1.example.com```
```deis domains:add my2.example.com```
When I delete one
```deis domains:remove my2.example.com```
both domains are deleted
Is this an expected behaviour?

**Comment by carmstrong** [comment]
@babarinde What version of Deis are you running? This sounds like #3308 which should be fixed in Deis v1.5.0 (and v1.5.1).

**Comment by babarinde** [comment]
@carmstrong Deis v1.5.0 upgraded from v1.4

**Comment by mboersma** [comment]
Note to self: uncomment the skipped test we wrote to validate the fix I'm going to write.
