### ISSUE TITLE
logs.papertrailapp.com drain type is not implemented

### ISSUE THREAD

**Issue by ngpestelos** [deis/deis#3477]
I'm seeing this after setting up log drain on 1.6.0-dev. Has anyone encountered this error?

**Comment by bacongobbler** [comment]
The protocol should start with `syslog://` or else you'll receive this error. https://github.com/deis/deis/blob/54badc5f2337694c584ffc0d610d3667b616fb17/logger/drain/drain.go#L39

**Comment by ngpestelos** [comment]
Thank you :+1:
