### ISSUE TITLE
Add http check in addition to the port open check

### ISSUE THREAD

**Issue by glogiotatidis** [deis/deis#3478]
In https://github.com/deis/deis/pull/3156 we check if the port is open before publishing the container. This works OK for most of the cases but it seems that there's a marginal chance that port is open but the server hasn't finished initializing yet. 

A possible solution would be to add an additional HTTP status check: if port open, send a 
`HEAD / HTTP/1.0` and expect a `HTTP/1.1 200 OK`. 

How does that sound?

**Comment by bacongobbler** [comment]
that might be a bit too opinionated. I know that some apps (like our own controller) respond with a 404 response on `/`. Maybe anything other than 503 (the response from the router) would be acceptable.

**Comment by glogiotatidis** [comment]
We're getting 502s when that happens. Excluding 502s and 503s can work

**Comment by bacongobbler** [comment]
Hmm... Maybe 50x in general? Don't know if that's still too opinionated... Let's see what the other maintainers say.

ping @carmstrong @mboersma

**Comment by carmstrong** [comment]
> that might be a bit too opinionated.

I would agree. I don't think it's our responsibility to understand when an app is done initializing other than accepting connections on the bound port, and I don't think we can make a decision here that everyone will be pleased with.

We actually hear this question from users not infrequently - I just spoke with someone about this yesterday, who was wondering how this health check could be improved. I just don't think we can come up with a solution that works for everyone.

**Comment by mboersma** [comment]
It would be too strict to expect a 200 response, but it might be reasonable to expect the thing on the other end to act like an HTTP server (and ignore the status code).

**Comment by carmstrong** [comment]
I'd like to hear from more people if this is really how everyone wants health checking to work. I can't think of many cases where an app takes so much longer to start up/initialize after its daemon is up and listening on the port, which we are currently waiting for.

**Comment by carmstrong** [comment]
This is being tracked in #3813, which is a solution to address a number of issues for application health checks during deploy and publishing.
