### ISSUE TITLE
Application SSL is not working when using multiple certs

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#3483]
Hi

I have 2 apps (lets call it staging.app.com & www.app.com).
Both are using custom domains (my Deis isn't hosted on app.com)

Both domains have attached a cert for that CN.

As a test I've attached a cert to staging.app.com, and that worked perfectly.
Afterwards I've done the same to www.app.com, that worked perfectly as well.

Now when accessing staging.app.com, I get unsafe connection, because the cert served is for www.app.com.

This is obviously incorrect, and renders using multiple certs useless...

Nathan

**Comment by nathansamson** [comment]
Is someone else having this problem?

Is there something I can do to debug the problem?

**Comment by carmstrong** [comment]
> Is someone else having this problem?

There have been some reports of SSL cert funkiness, namely #3441 and #3470, so I wouldn't be surprised if there's something wrong here.

> Is there something I can do to debug the problem?

It would be helpful if you could enter a router with `nse deis-router`, then gist the contents of `/opt/nginx/conf/nginx.conf `. That will show how the domains are configured, and what certs they're serving.

**Comment by nathansamson** [comment]
See https://gist.github.com/nathansamson/ee6c209746bdababb0c1

From what I know from nginx, that looks fine but if you try accessing http://demo.beeple.eu you'll see it will serve up the incorrect file

**Comment by nathansamson** [comment]
Running

diff /etc/ssl/deis/certs/demo.beeple.eu.cert /etc/ssl/deis/certs/www.radarwerk.be.cert

does return an empty output, so it seems the files are equal.

Wondering if I did something stupid, or if the upload overwrites older cert files...

Deis certs is giving the output I expect
~~~
deis cer[nathan@omega hedgehog]$ deis certs
Common Name       Expires
----------------  ----------------------
demo.beeple.eu    2018-04-12T23:59:59UTC
www.radarwerk.be  2018-04-13T23:59:59UTC
~~~

**Comment by carmstrong** [comment]
> does return an empty output, so it seems the files are equal.
> 
> Wondering if I did something stupid, or if the upload overwrites older cert files...
> 
> Deis certs is giving the output I expect

Given that the expires time is identical, I'm guessing that they're in actuality the same cert. You can inspect the certs with the `openssl` client, or try creating a new self-signed cert and ensure Deis serves that.

**Comment by nathansamson** [comment]
Please look again: The expires time is ONE day off :)

**Comment by nathansamson** [comment]
To make sure I wasn't doing stupid I removed the old demo.beeple.eu cert, and reuploaded

~~~
[nathan@omega certs]$ diff  -q www_radarwerk_be.bundle demo_beeple_eu.bundle
Files www_radarwerk_be.bundle and demo_beeple_eu.bundle differ
[nathan@omega certs]$ deis certs:add demo_beeple_eu.bundle demo.beeple.eu.key
~~~

After a few seconds the router was synced again

(In the router)
~~~
root@35c667c6da16:/app# md5sum /etc/ssl/deis/certs/*.cert
53382f5974ff0e73f8c244637e7267bf  /etc/ssl/deis/certs/demo.beeple.eu.cert
53382f5974ff0e73f8c244637e7267bf  /etc/ssl/deis/certs/www.radarwerk.be.cert
root@35c667c6da16:/app# 
~~~

(Local machine)
~~~
[nathan@omega certs]$ md5sum *.bundle
80caf2f448d43b503398dfe9bb928e3c  demo_beeple_eu.bundle
53382f5974ff0e73f8c244637e7267bf  www_radarwerk_be.bundle
[nathan@omega certs]$
~~~

**Comment by nathansamson** [comment]
It seems something wrong is going on in the syncing certs part...

**Comment by carmstrong** [comment]
> Please look again: The expires time is ONE day off :)

Ah, yes. Hmm... what does `/bin/generate-cert` look like inside the container? That's what generates the certs from etcd. 

Also, inspect the etcd keyspace at `/deis/certs` - I think we'll need to work backwards to figure out where the issue is.

**Comment by nathansamson** [comment]
Okay, the generate-certS looks wrong

I've updated https://gist.github.com/nathansamson/ee6c209746bdababb0c1

in the loop it is writing out 2 cert files, and 2 key files, which looks odd. I would expect to only write one key file & 1 cert file per loop run...

/deis/certs looks correct.

generate-certs writes out ALL certs (they ARE different) out in every loop run, so obviously every file will have the last cert file...

**Comment by carmstrong** [comment]
> generate-certs writes out ALL certs (they ARE different) out in every loop run, so obviously every file will have the last cert file...

That would explain it. Thanks for investigating, @nathansamson. We'll need to fix this ASAP.

/cc @bacongobbler

**Comment by nathansamson** [comment]
I would expect the generate-certs template to look more something like this

Can we please fix this BEFORE v1.6 (v1.5.2) as this is impacting me right now...

~~~
#!/usr/bin/env bash

# create or truncate the file
> /etc/ssl/deis_certs

{{ range $cert := .deis_certs }}
echo {{ $cert.Key }} >> /etc/ssl/deis_certs
{{ end }}

CERT_PATH=/etc/ssl/deis/certs
KEY_PATH=/etc/ssl/deis/keys

# clean up all certs
rm -rf $CERT_PATH
rm -rf $KEY_PATH

# ...then re-create the paths
mkdir -p $CERT_PATH
mkdir -p $KEY_PATH

    ETCD_SLUG=".$(echo $etcd_path | sed s/\\/// | sed s/\\//_/g)"
    ETCD_CERT_SLUG="${ETCD_SLUG}_cert"
    ETCD_KEY_SLUG="${ETCD_SLUG}_key"

    # cert template
    {{ range $cert := .deis_certs }}{{ if $cert.Nodes }}
    {{ range $certFields := $cert.Nodes }}
    {{ if eq (Base $certFields.Key) "cert" }}
    cat << EOF > "$CERT_PATH/{{ $cert.Key }}.cert"
{{ $certFields.Value }}
EOF
    {{ else if eq (Base $certFields.Key) "key" }}
    cat << EOF > "$KEY_PATH/{{ $cert.Key }}.key"
{{ $certFields.Value }}
EOF
    {{ end }}
    {{ end }}
    {{ end }}{{ end }}
done < /etc/ssl/deis_certs
~~~

**Comment by carmstrong** [comment]
> I would expect the generate-certs template to look more something like this
> 
> Can we please fix this BEFORE v1.6 (v1.5.2) as this is impacting me right now...

Yes, this will warrant a patch release for v1.5.2. We don't typically track patch releases in milestones, but I think it's a good idea for transparency.

@nathansamson Please try your proposed template. If it works, open a PR and we'll test it against this issue.

**Comment by bacongobbler** [comment]
This worked completely fine for me. My process on reproducing:

```
$ deis apps
foo
go
$ deis domains -a foo
=== foo Domains
foo.bacongobbler.com
$ deis domains -a go
=== go Domains
www.bacongobbler.com
$ deis certs
Common Name           Expires
--------------------  ----------------------
www.bacongobbler.com  2015-06-18T19:57:43UTC
foo.bacongobbler.com  2016-04-16T15:44:14UTC
$ dig foo.bacongobbler.com +short
foo.23.253.34.152.xip.io.
23.253.34.152
$ dig www.bacongobbler.com +short
go.23.253.34.152.xip.io.
23.253.34.152
$ # foo.bacongobbler.com is a self-signed certificate
$ curl -k https://foo.bacongobbler.com
Powered by Deis
$ curl https://www.bacongobbler.com
Powered by Deis
```

**Comment by nathansamson** [comment]
By ignoring your self signed certificate oyu also ignored the fact that it was for a wrong domain name.

"The certificate is only valid for the following names: www.bacongobbler.com, bacongobbler.com " is the error I get with firefox

**Comment by bacongobbler** [comment]
> generate-certs writes out ALL certs (they ARE different) out in every loop run, so obviously every file will have the last cert file...

Oh. that would explain the issue here. Good catch

**Comment by bacongobbler** [comment]
patch incoming...
