### ISSUE TITLE
deis config:set numbers as string error

### ISSUE THREAD

**Issue by raphaelluchini** [deis/deis#3485]
Running ``deis config:set PARAM="7782089"``, when I get this env var,(for example in node ``process.env['PARAM'];``) I'm getting 7.782089e+06. Should come as string like "7782089" right?.

I'm using deis 1.4.0.

Thanks

**Comment by bacongobbler** [comment]
Is this during the build (i.e. `git push deis`) or in the actual container? Can you please run `deis run env` in the application for me?

**Comment by raphaelluchini** [comment]
Is after build, running ``deis run env`` the output is ``PARAM=7782089``, I got a workaround, using single quotes inside double quotes eg: ``deis config:set PARAM="'7782089'"``. Worked fine, but it's weird :P.

**Comment by bacongobbler** [comment]
this is probably an app issue, most likely due to the integer getting casted to a float. AFAICT it looks fine from Deis' end.

**Comment by bacongobbler** [comment]
I just found out that all numbers [are stored as floating point numbers](http://www.w3schools.com/js/js_numbers.asp) in Javascript, so yes this is an application issue.

**Comment by raphaelluchini** [comment]
I got the same issue using PHP

**Comment by aledbf** [comment]
@raphaelluchini running `docker inspect <your app name>_v<version>.web.1` in the node where the app is scheduled you can see in the "Env" section of the output how the variable is stored in the docker image. You will see PARAM=7782089
