### ISSUE TITLE
Request: do not store user keys in etcd:/deis/builder/users

### ISSUE THREAD

**Issue by krancour** [deis/deis#3486]
Currently, when users upload keys, their keys are stored in two places: the database (makes sense) and etcd under the key `/deis/builder/users`.

The builder, ultimately needs to be aware of these keys and the builder runs confd in the background to update /home/git/.ssh/authorized_keys based on what's found in etcd under the `/deis/builder/users key`.

The problem with this is that anyone who's seeking to externalize durable platform state using the likes of RDS and S3 has no way of externalizing this little bit of configuration.  It has, at least once, left me tearing down a cluster that I presumed to be _stateless_, only to replace it with another brand new cluster, backed by the same externalized datastores which users were then unable to push/deploy to.  Deleting and re-adding their keys fixed the situation, but that's less than ideal.

IMO, using etcd to configure platform components and bind them to backing services makes sense, but storing durable platform state _in_ etcd seems to make less sense.

Is there a viable alternative?  It would sure would be helpful to those of use that want to fully externalize platform state.  @Blystad mentioned a possibility in #2812

**Comment by bacongobbler** [comment]
Alternatively we could connect to the database and do some SQL queries to retrieve the keys. That means there's a dependency on the database for the builder though

**Comment by krancour** [comment]
But would you agree that etcd feels like the wrong place to maintain durable platform state an that its role should be more constrained to configuration and discovery?

**Comment by bacongobbler** [comment]
Yes, I would agree with you :)

**Comment by krancour** [comment]
> That means there's a dependency on the database for the builder though

Totally nitpicking (sorry), but want to request clarification.  Does "the database" imply _the_ `deis-database` component explicitly enumerated in the `deis-builder.service` unit as a requirement?  Or could this be a more implicit requirement?

I ask because there's been a theme to my issues/comments lately that has to do with relaxing some such tight couplings so that it's _easier_ to bind to external backing services (like an RDS database, for instance).  If `deis-database` were to become an explicit dependency of `deis-builder`, it would move Deis in the direction of _tighter_ couplings to its own storage subsystem instead.

**Comment by bacongobbler** [comment]
"The database" in this case implies connecting to the database set up in the relevant `/deis/database` etcd keyspace, similar to how the controller connects. The database can easily be swapped out for an RDS instance by modifying the keys set at the [database settings page](http://docs.deis.io/en/latest/customizing_deis/database_settings/) and shutting off `deis-database`.

This is a loose requirement. Just like the controller, we can just connect to the database via the relevant etcd keyspace so we don't have a hard requirement on Deis' provided database, but it would be used by default for those who don't want to offload their services.

**Comment by krancour** [comment]
Perfect.

**Comment by johanneswuerbach** [comment]
Wouldn't it make more sense to add another controller api instead of coupling to builder to the database? This way the builder doesn't need to be aware of the underling data store and it has already a controller requirement.

**Comment by krancour** [comment]
@johanneswuerbach that makes sense to me.

**Comment by krancour** [comment]
Superseded by #4355
