### ISSUE TITLE
deis:perms is not working in fresh installation

### ISSUE THREAD

**Issue by ineu** [deis/deis#3493]
I've just set up cluster with Deis 1.5.1 and trying to make user an admin. Unfortunately I get 404 on `deis:perms`:

```
$ deis perms
404 NOT FOUND
Detail:
Not found
```

deis-router:

```
Apr 15 17:01:02 production-coreos-1 sh[1191]: [INFO] - [15/Apr/2015:17:01:02 +0000] - 46.219.37.191 - - - 404 - "GET /v1/apps/org/perms HTTP/1.1" - 370 - "http://deis.prod.example.com/v1/apps/org/perms" - "python-requests/2.5.1 CPython/2.7.6 Linux/3.19.3-3-ARCH" - "~^deis\x5C.(?<domain>.+)$" - 192.168.0.3:8000 - deis.prod.example.com - 0.553 - 0.553
```

deis-controller:

```
192.168.0.1 "GET /v1/apps/org/perms HTTP/1.0" 404 22 "python-requests/2.5.1 CPython/2.7.6 Linux/3.19.3-3-ARCH"
```

**Comment by carmstrong** [comment]
This means the app wasn't found. You either need to change your local directory to the application directory, or specify the app name with `--app=`.

**Comment by ineu** [comment]
@carmstrong Thanks for the explanation. It worked indeed. But `perms:create username --admin` doesn't require `-a` key. I assume that `--admin` is system-wide, and `perms:list` is per-app?

**Comment by bacongobbler** [comment]
yes you are correct in that sense. However, `deis perms` is synonymous with `deis perms:list` which is the per-app endpoint. If you want to list sysdamins then you have to use the full `deis perms:list --admin` (note: `deis perms --admin` may work but I've never tried)

**Comment by ineu** [comment]
Yes, `deis perms --admin` works. Awesome, thank you.
