### ISSUE TITLE
Do not automatically scale up to 1 after a deploy

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3494]
If a user has 0 containers of an app running and publishes a new release, we should confirm that Deis doesn't automatically scale up to 1. 

**Example:**
I have an app that defines two proctypes, **web** and **foo**. I keep my **web** scaled to 0, and only want **foo** to be running most of the time. If I deploy my app again, will Deis scale **web** back to 1?

**Comment by bacongobbler** [comment]
I couldn't find any relevant unit tests that cover this, sadly, so a unit test (even if it is skipped for now) would be appreciated.
