### ISSUE TITLE
deisctl tries to destroy app named "registry" when uninstalling platform

### ISSUE THREAD

**Issue by rogerleite** [deis/deis#3497]
```
$ deisctl stop platform
● ▴ ■
■ ● ▴ Stopping Deis...
▴ ■ ●

Routing mesh...
deis-router@1.service: inactive/dead                                 
deis-router@2.service: inactive/dead                                 
deis-router@3.service: inactive/dead                                 
Data plane...
deis-publisher.service: inactive/dead                                 
Control plane...
Could not parse target: registry_v4.web.1.service
```

We have a app named as "registry", maybe this is a problem. I tried to start platform and hangs exactly the same.

Now deis client is getting 503 service unavailable for any command that i try. I'd like scale 0 or even destroy this app.

My units status: https://gist.github.com/rogerleite/f18b05a2099b10529a23

**Comment by rogerleite** [comment]
To fix this situation, i did:

Destroyed all services:
`fleetctl list-units | grep service | cut -f1 | xargs fleetctl destroy`

Install and start via deisctl:
`deisctl install platform`
`deisctl start platform`

**Comment by bacongobbler** [comment]
thanks for the report, @rogerleite. I've updated the title to better reflect the problem at hand here.

**Comment by rogerleite** [comment]
Thanks.

**Comment by carmstrong** [comment]
ping @slack didn't you have some similar fixes for apps named `deis-` that you were going to PR?

**Comment by slack** [comment]
Yeah, commit is sitting on this branch https://github.com/deis/deis/compare/master...slack:deisctl-list

I need to circle back, extract the filtering and add a unit test.

However, looks like https://github.com/slack/deis/blob/3794474cbc4408a9c47a782b9a063230ffa90488/deisctl/cmd/cmd.go#L271 actually needs the fix and wouldn't be covered by the branch I was working on.

**Comment by rogerleite** [comment]
Reading deisctl source, maybe the problem is:

When Stop calls [`expandTargets`](https://github.com/slack/deis/blob/3794474cbc4408a9c47a782b9a063230ffa90488/deisctl/backend/fleet/stop.go#L14), registry has the suffix `@*`, so it calls [`expandTarget` with `registry` argument](https://github.com/slack/deis/blob/3794474cbc4408a9c47a782b9a063230ffa90488/deisctl/backend/fleet/utils.go#L93) and **probably** [`fleetctl client`](https://github.com/slack/deis/blob/3794474cbc4408a9c47a782b9a063230ffa90488/deisctl/backend/fleet/utils.go#L107) make a simple grep with `registry` string only.

My suggestion: `expandTarget` should use a regex like [this](https://github.com/slack/deis/blob/3794474cbc4408a9c47a782b9a063230ffa90488/deisctl/backend/fleet/utils.go#L54) to filter `c.Units(target)` results.

Maybe it's time to me finally learn go. :smile:
