### ISSUE TITLE
Non existing app returns http 200

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#3502]
Hi

Relaed to: #1624

I do not want customization right now, but more importantly this is now HTTP 200, while in fact this should be HTTP 404 or HTTP 500.

I encountered this issue when my cluster was unstable & my app wasn't served.
My monitoring did not raise errors as a 200 request was returned.
I could strengthen up my monitoring by looking for certain words, but that is cumbersome and should not be forced.

Can we change the default nginx page to return a 500 or any other error code that is sensible?

**Comment by babarinde** [comment]
@nathansamson 
Is the application deployed? run
``` deis apps:logs -a appName``` to find.
If your app is returning a 200 then it means you probably have an error from your code

**Comment by nathansamson** [comment]
Its a non existing app.

I also had the problem with a deployed app where all the containers were down.

My app doesn't give any nginx pages, so it is definitly NOTHING to do with my app...

**Comment by bacongobbler** [comment]
it's because the routers have a `default_server` directive which returns 200 OK. We need it for the health checks so we're not sure how to remove it in a clean way.

**Comment by bacongobbler** [comment]
https://github.com/deis/deis/blob/master/router/image/templates/nginx.conf#L266-L277

**Comment by carmstrong** [comment]
We could actually do this quite easily by adding a default `return` on line 268-269 of the template, and explicitly returning a 200 for the health-check and status endpoints.
