### ISSUE TITLE
Affinity arg is not working correctly

### ISSUE THREAD

**Issue by ashaffer** [deis/deis#3508]
Right now if you set the affinity arg, I would expect that if a url does not contain that argument at all, it will be routed with no affinity.  But it appears that instead it is routed consistently to the same server, as if it were consistently hashing the undefined value.

This is a problem for us, because we only want to use sticky routing on one of our services (for xhr polling / sockets), but the rest we would like to be load balanced in the standard way.

**Comment by bacongobbler** [comment]
I believe this was the intended behaviour, but I'm not knowledgeable enough about affinity args to refute that. @wenzowski, how do you feel about this one?

**Comment by wenzowski** [comment]
Digging into the `$arg_name` construct, it does indeed return empty string when the argument is unset and therefore nginx is consistently hashing on empty string. This is indeed a bug.

Yes @ashaffer what you're doing does sound like the most common use case.

I'm exploring this, but completely open to suggestions.

**Comment by carmstrong** [comment]
I guess I'm not sure why https://github.com/deis/deis/blob/master/router/image/templates/nginx.conf#L147 is being evaluated when `/deis/router/affinityArg` is unset?

**Comment by wenzowski** [comment]
Oh was that the question? My understanding @carmstrong is that when affinityArg was set, eg to `'sticky'` and nginx received a request containing the arg, eg to `GET 'https://example.com/xhr?sticky=prngHash'` everything works as expected, but when a request comes in that doesn't contain an http get variable, eg to GET `'https://example.com/'` then nginx returns an empty string for `$arg_sticky` thus breaking load balancing.

**Comment by wenzowski** [comment]
Off the top of my head, I'm thinking of something like this
```
set_random $prng 0 99;
set_if_empty $arg_{{ $affinityArg }} $prng;
```
Which [takes advantage] of c++ `rand()` rather than a csprng and stores the resulting integer in a string. I would assume this would always generate the random number, regardless of if it gets used or not, but seems like negligible overhead, and the fastest way to fix the problem.

[takes advantage]: http://wiki.nginx.org/HttpSetMiscModule#set_random

**Comment by wenzowski** [comment]
It'll probably take me to Tuesday to get to this. Can you confirm I understand correctly @ashaffer or is @carmstrong on the money?

**Comment by ashaffer** [comment]
@wenzowski Yes, your understanding is correct.  That should address the issue.

**Comment by carmstrong** [comment]
Yep, this is something we should fix. Let us know how we can help, @wenzowski!

**Comment by wenzowski** [comment]
@carmstrong I'll submit the sketched patch tomorrow as an immediate fix, but a proper discussion needs to be had with the Nginx team. Continuing to perform sticky routing based on a hash of empty string seems like an upstream bug to me, and where the fix really belongs imho. At quick read stuff appears to be going down in [ngx_http_upstream_get_chash_peer](https://github.com/nginx/nginx/blob/master/src/http/modules/ngx_http_upstream_hash_module.c#L468).

**Comment by babarinde** [comment]
Hi, 
Please is it possible to have some clearer docs on how to use the affinity args

**Comment by carmstrong** [comment]
@wenzowski Maybe we could link to the affinity arg documentation in the "Customizing Router" docs?

**Comment by wenzowski** [comment]
@babarinde nginx hashes the contents of a GET variable named whatever affinityArg is set to
> for requests with the indicated query string variable, hash its contents to perform session affinity (default: undefined)
><cite>[Settings used by router](http://docs.deis.io/en/latest/customizing_deis/router_settings/#settings-used-by-router)</cite>

Struggling with some coreos fun & my timetable got pushed. PR forthcoming.

**Comment by wenzowski** [comment]
issue for nginx hash module [opened upstream](http://trac.nginx.org/nginx/ticket/765#ticket)
