### ISSUE TITLE
enforceHTTPS=true causes client side and git issues

### ISSUE THREAD

**Issue by azurewraith** [deis/deis#3512]
[user@lavos app|master]$ git push -f deis master
    /usr/local/bin/gitreceive: line 33: /home/git/app.git/hooks/pre-receive: No such file or directory
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

So I tried to delete and recreate the app:

    [user@lavos app|master]$ deis apps:destroy --app app
    
     !    WARNING: Potentially Destructive Action
     !    This command will destroy the application: app
     !    To proceed, type "app" or re-run this command with --confirm=app

    > app
    Destroying app...
     ... /var/folders/2q/1zznrz4j3bs37qmd_159m_n00000gp/T/_MEIcsMCXL/requests/packages/urllib3/connection.py:251: SecurityWarning: Certificate has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
    done in 4s
    [user@lavos app|master]$ deis apps:create app
    Creating application...  ... /var/folders/2q/1zznrz4j3bs37qmd_159m_n00000gp/T/_MEIpx2oZp/requests/packages/urllib3/connection.py:251: SecurityWarning: Certificate has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
    200 OK
    {u'count': 1, u'previous': None, u'results': [{u'updated': u'2015-04-08T20:24:55UTC', u'uuid': u'9253b6c7-3706-4a14-be61-c4b687a8410c', u'created': u'2015-04-08T20:17:56UTC', u'url': u'other-app-name.domain.com', u'owner': u'<me>', u'id': u'other-app-name', u'structure': {u'web': 1}}], u'next': None}

The interesting thing is that the JSON returned references the first app created on this cluster (other-app-name)...

Once I set enforceHTTPS=false, things worked fine again...

    [user@lavos app|master]$ deis apps:destroy --app app
    
     !    WARNING: Potentially Destructive Action
     !    This command will destroy the application: app
     !    To proceed, type "app" or re-run this command with --confirm=app

    > app 
    Destroying app... 
    404 NOT FOUND
    Detail:
    Not found
    [user@lavos app|master]$ deis apps:create app
    Creating application... done, created app
    Git remote deis added

well...except for this issue...

    [user@lavos app|master]$ git push deis master
    /usr/local/bin/gitreceive: line 33: /home/git/app.git/hooks/pre-receive: No such file or directory
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

Pushing the other app works...

If I delete and rename the app, it starts working again:

    [user@lavos app|master]$ deis apps:create app_new_name
    Creating application... done, created app_new_name
    Git remote deis added
    [user@lavos app|master]$ git push deis master
    Counting objects: 134, done.
    Delta compression using up to 8 threads.
    Compressing objects: 100% (125/125), done.
    Writing objects: 100% (134/134), 46.63 KiB | 0 bytes/s, done.
    Total 134 (delta 18), reused 0 (delta 0)
    -----> Node.js app detected
    ...

Strange...

**Comment by azurewraith** [comment]
I restarted the builder and `app_new_name` started to throw the pre-receive error again...

**Comment by babarinde** [comment]
@azurewraith 
am not so sure this is because of the enforceHTTPS.
I think it is related to this https://github.com/deis/deis/issues/3458

**Comment by azurewraith** [comment]
I think I'm experiencing #3458 at the same time, there definitely is a client side issue happening concurrently given that the create app behavior is different and the end result is the new app is not created...

    [user@lavos app|master]$ deis apps:create app
    Creating application...
    /var/folders/2q/1zznrz4j3bs37qmd_159m_n00000gp/T/_MEIpx2oZp/requests/packages/urllib3/connection.py:251: SecurityWarning: Certificate has no `subjectAltName`, falling back to check for a   `commonName` for now. This feature is being removed by major browsers and deprecated by RFC   2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
    200 OK
    {u'count': 1, u'previous': None, u'results': [{u'updated': u'2015-04-08T20:24:55UTC', u'uuid': u'9253b6c7-3706-4a14-be61-c4b687a8410c', u'created': u'2015-04-08T20:17:56UTC', u'url': u'other-app-name.domain.com', u'owner': u'<me>', u'id': u'other-app-name', u'structure': {u'web': 1}}], u'next': None}

**Comment by bacongobbler** [comment]
@azurewraith that sounds like you have an older python version. Try updating to 2.7.9

**Comment by bacongobbler** [comment]
oh this is with the self-contained deis client. We'll have to ensure we have 2.7.9 on Jenkins slaves.

**Comment by bacongobbler** [comment]
see #3514

**Comment by carmstrong** [comment]
@azurewraith The SecurityWarning is just a warning (see #3514).

The real issue you're seeing is #3458. We'd **love** to figure out why that's occurring. If you have any input, please provide it in #3458. Thanks!

**Comment by azurewraith** [comment]
Setting aside the security warning and the receive hook error, IMO there is a legitimate issue here.

I created an app and it ended up not being created with enableHTTPS=true.  I can reproduce this if needed -- removing all the other cruft.

As for the Python issue, I didn't install anything except what is present in CoreOS or the core containers.

**Comment by azurewraith** [comment]
> As for the Python issue, I didn't install anything except what is present in CoreOS or the core containers.
Sorry, I know what you meant.  Client side I'm running 2.7.8 which comes standard with OSX.

**Comment by azurewraith** [comment]
For reference, I edited this comment to include the 404, which is the real reason I submitted this issue.

https://github.com/deis/deis/issues/3512#issuecomment-93991484
