### ISSUE TITLE
Add `deis whoami` to the help screen.

### ISSUE THREAD

**Issue by ineu** [deis/deis#3513]
`deis whoami` command from #1979 is unfortunately undocumented. Would be nice to add it to `deis help` output.

**Comment by bacongobbler** [comment]
It's not top-level entity so it's not shown on `deis help`. However, it's under both `deis help auth` and `deis shortcuts`.

**Comment by ineu** [comment]
Ok, then there should be help entry for `deis:auth`:
```
> $ deis help | grep auth; echo $?                                                                                                                                                1
```
