### ISSUE TITLE
InsecurePlatformWarning during builds

### ISSUE THREAD

**Issue by mboersma** [deis/deis#3514]
Recently urllib3 began [emitting these warnings](https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning) during our normal builds whenever python touches SSL. Looks like we can fix it by updating to Python 2.7.9 (or by explicitly silencing it). An example:
```
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
/tmp/tmp8K2oTh/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: 
A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and 
may cause certain SSL connections to fail. For more information, see 
https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
```

**Comment by mboersma** [comment]
While it's a huge pain to get anything but python 2.7.6 on Ubuntu 14.0.4, `alpine:3.1` has python 2.7.9. Just sayin'. :smiling_imp:

**Comment by Joshua-Anderson** [comment]
@mboersma I know I'm taking crazy here, but is there any reason that you aren't using python 3? :smiling_imp:  :smile_cat:

**Comment by mboersma** [comment]
>  aren't using python 3?

It's a good question. Porting controller to py3 would be a bit of work, and in the other two cases where this shows up in the build it's not a Deis project directly (ceph-monitor, docker-registry). And sadly today's state of affairs is that py2 is still heavily preferred everywhere, despite our efforts to move things forward.

We could do it for the controller, but we might need to make the whole enchilada py2/3 compatible at the same time, or else require devs to install python3 in order to do `make -C controller/ test-unit` and the like. It's not totally unreasonable, but every time something like this comes up ("let's use Django 1.~7~8"), we find we would rather start rewriting things in Go if we're going to do anything disruptive.

(And having said all that, this is just a warning. Based on my reading of it, Deis probably doesn't trigger the actual security bugs referenced.)

**Comment by mboersma** [comment]
Just to note this somewhere: the python buildpack does install Python 2.7.9, so if you had an app that uses `ssl` itself, it's covered already WRT this potential issue:
```console
$ git push deis master
Counting objects: 28, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (23/23), done.
Writing objects: 100% (28/28), 4.95 KiB | 0 bytes/s, done.
Total 28 (delta 7), reused 0 (delta 0)
-----> Python app detected
-----> Stack changed, re-installing runtime
-----> Installing runtime (python-2.7.9)
-----> Installing dependencies with pip
...
```
