### ISSUE TITLE
feat(deisctl): deisctl config <component> rm

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#3515]
Some users have been disabling features. The only workaround today is to SSH into one of the CoreOS hosts and run `etcdctl rm` on the specific key. We should map a `deisctl config <component> rm` command to do the equivalent.

**Comment by carmstrong** [comment]
This should probably be `deisctl config unset` and behave similarly to our existing commands:
```
  deisctl config <target> get [<key>...]
  deisctl config <target> set <key=val>...
  deisctl config <target> unset <key=val>...
```
