### ISSUE TITLE
Not able to run Deis::etcd on Amazon EC2

### ISSUE THREAD

**Issue by pdhar-tibco** [deis/deis#3518]
In continuation of my earlier issue #3489 trying to install DEIS on vmware fusion single node . As advised I am now trying to install DEIS on Amazon EC2 (3 nodes) and I have completed the provisioning step. I did the following steps as mention in the readme.
1. export DEISCTL_TUNNEL=52.11.XXX.XXX (masked my public ip of the ec2 node)
2. deisctl config platform set sshPrivateKey=~/.ssh/deis.pem (from laptop ssh console)
Error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
3. systemctl status etc -> (ec2 instance)
systemctl status etcd
● etcd.service - etcd -> (ec2 instance)
Loaded: loaded (/etc/systemd/system/etcd.service; static; vendor preset: disabled)
Drop-In: /run/systemd/system/etcd.service.d
└─10-oem.conf, 20-cloudinit.conf
Active: activating (auto-restart) (Result: exit-code) since Fri 2015-04-17 18:12:06 UTC; 2s ago
Process: 30752 ExecStart=/usr/bin/etcd (code=exited, status=1/FAILURE)
Main PID: 30752 (code=exited, status=1/FAILURE)
4.journalctl -u etcd -> ( discovery url was created fresh with DEIS_NUM_INSTANCES=3 as generated to user-data file ) (ec2 instance)
Apr 17 04:50:40 corevm etcd[859]: [etcd] Apr 17 04:50:40.356 INFO | Discovery via https://discovery.etcd.io using prefix /f4741ddaec75b183930c9c6ac38e3177.
Apr 17 04:50:40 corevm etcd[859]: [etcd] Apr 17 04:50:40.758 WARNING | Discovery encountered an error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Apr 17 04:50:40 corevm etcd[859]: [etcd] Apr 17 04:50:40.758 WARNING | c21ab1d7393b4b3bbb52f55766f3f651 failed to connect discovery service[https://discovery.etcd.io/f4741ddaec75b183930c9c6ac38e3177]: 501: All the given peers are n
Apr 17 04:50:40 corevm etcd[859]: [etcd] Apr 17 04:50:40.758 CRITICAL | c21ab1d7393b4b3bbb52f55766f3f651, the new instance, must register itself to discovery service as required
Apr 17 04:50:40 corevm systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Apr 17 04:50:40 corevm systemd[1]: Unit etcd.service entered failed state.
Apr 17 04:50:40 corevm systemd[1]: etcd.service failed.
5. etcd.service file looks like this (not sure if the ETCD_NAME should be there , automatically generated by the provisioning script)
Environment="ETCD_ADDR=172.31.40.165:4001"
Environment="ETCD_DATA_DIR=/media/ephemeral/etcd"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/f4741ddaec75b183930c9c6ac38e3177"
Environment="ETCD_PEER_ADDR=172.31.40.165:7001"
Environment="ETCD_PEER_ELECTION_TIMEOUT=2000"
Environment="ETCD_PEER_HEARTBEAT_INTERVAL=500"
6. etcd version = etcd version 0.4.7
7. network security rules are
Type Protocol Port Range Source
Custom TCP Rule TCP 2222 sg-97bab8f2 (DeisCluster-DeisWebELBSecurityGroup-19LO9VQJGKGWS)
SSH TCP 22 0.0.0.0/0
Custom TCP Rule TCP 4001 0.0.0.0/0
All traffic All All sg-99bab8fc (DeisCluster-VPCSecurityGroup-1GACN6BJIGFS3) (same subnet_
HTTPS TCP 443 sg-97bab8f2 (DeisCluster-DeisWebELBSecurityGroup-19LO9VQJGKGWS)
Custom TCP Rule TCP 7001 0.0.0.0/0
HTTP TCP 80 sg-97bab8f2 (DeisCluster-DeisWebELBSecurityGroup-19LO9VQJGKGWS)

I don't know at this point if I am missing something critical or there is an issue with etcd.

**Comment by bacongobbler** [comment]
Sounds like you re-used an old discovery URL. Did you ruin `make discovery-url` before provisioning the cluster? http://docs.deis.io/en/latest/troubleshooting_deis/#all-the-given-peers-are-not-reachable

**Comment by pdhar-tibco** [comment]
I ran the make discovery-url which used the user-data.examples template to generate the user-data.
Then i proceeded to run the provisioning script for ec2.
I can try it again and update shortly.

**Comment by carmstrong** [comment]
It actually looks like the machines cannot communicate with the discovery URL endpoint - they're getting injected with the proper discovery URL, but that URL has no hosts: https://discovery.etcd.io/f4741ddaec75b183930c9c6ac38e3177

Do you have anything that would prevent the hosts from making outbound requests?

**Comment by pdhar-tibco** [comment]
I am starting fresh again to prevent any missteps. As far as outbound network rules are concerned I was able to ping to the outside world from the ec2 instance. I made sure that the inbound rules have the ports 4001,7001 open.

**Comment by pdhar-tibco** [comment]
I tried again with the same results as before as shown in this gist https://gist.github.com/pdhar-tibco/0cc8a2309750c1c4b24e
What am I doing wrong ?

**Comment by pdhar-tibco** [comment]
In my newly setup ec2 instances I tried this to ensure output requests are working.

ip-172-31-35-233 etcd.service.d # curl https://discovery.etcd.io/f502b6f36dcb038239be260761e0d5b4
{"action":"get","node":{"key":"/_etcd/registry/f502b6f36dcb038239be260761e0d5b4","dir":true,"modifiedIndex":473784823,"createdIndex":473784823}}

**Comment by bacongobbler** [comment]
It looks like your instances aren't able to connect to discovery.etcd.io as per the logs.

**Comment by pdhar-tibco** [comment]
If that is the case then I should not be able to get to the url using curl. I can do it from command line on the instance ssh and etcd daemon can’t.

curl https://discovery.etcd.io/f502b6f36dcb038239be260761e0d5b4
{"action":"get","node":{"key":"/_etcd/registry/f502b6f36dcb038239be260761e0d5b4","dir":true,"modifiedIndex":473784823,"createdIndex":473784823}}

**Comment by pdhar-tibco** [comment]
I ran this from command line using the  configured parameters
[Service]
Environment="ETCD_ADDR=172.31.35.233:4001"
Environment="ETCD_DATA_DIR=/media/ephemeral/etcd"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/f502b6f36dcb038239be260761e0d5b4"
Environment="ETCD_PEER_ADDR=172.31.35.233:7001"
Environment="ETCD_PEER_ELECTION_TIMEOUT=2000"
Environment="ETCD_PEER_HEARTBEAT_INTERVAL=500”

------------------
ip-172-31-35-233 etcd.service.d # etcd -addr=172.31.35.233:4001 -peer-addr=172.31.35.233:7001 -data-dir=/media/ephemeral/etcd -discovery=https://discovery.etcd.io/f502b6f36dcb038239be260761e0d5b4 -peer-heartbeat-interval=500 -peer-election-timeout=2000 -vv
[etcd] Apr 17 22:53:49.002 CRITICAL  | raft.Server: Name cannot be blank
————————— NOTICED the ETCD_NAME is missing in the configured parameters. Provisioning script should add it ?????
After adding the name on command line
ip-172-31-35-233 etcd.service.d # etcd -addr=172.31.35.233:4001 -peer-addr=172.31.35.233:7001 -data-dir=/media/ephemeral/etcd -discovery=https://discovery.etcd.io/f502b6f36dcb038239be260761e0d5b4 -peer-heartbeat-interval=500 -peer-election-timeout=2000 -vv -name core01
------------------

I get this running on command line from the same ec2 ssh shell

[etcd] Apr 17 22:54:07.103 DEBUG     | core01 finished load snapshot
[raft]22:54:07.103362 log.open.open  /media/ephemeral/etcd/log
[raft]22:54:07.103393 log.open.exist  /media/ephemeral/etcd/log
[raft]22:54:07.103415 open.log.append: finish 
[raft]22:54:07.103441 open.log.recovery number of log  0
[etcd] Apr 17 22:54:07.103 DEBUG     | The type of path /media/ephemeral/etcd/log is 16914836
[etcd] Apr 17 22:54:07.103 INFO      | Discovery via https://discovery.etcd.io using prefix /f502b6f36dcb038239be260761e0d5b4.
[etcd] Apr 17 22:54:07.414 INFO      | Discovery _state was empty, so this machine is the initial leader.
[etcd] Apr 17 22:54:07.414 INFO      | Discovery fetched back peer list: []
[etcd] Apr 17 22:54:07.414 DEBUG     | core01 is joining a cluster [] via discover service
[etcd] Apr 17 22:54:07.415 INFO      | core01 is starting a new cluster
[etcd] Apr 17 22:54:07.416 INFO      | etcd server [name core01, listen on :4001, advertised url http://172.31.35.233:4001]
[etcd] Apr 17 22:54:07.416 INFO      | peer server [name core01, listen on :7001, advertised url http://172.31.35.233:7001]
[etcd] Apr 17 22:54:07.416 INFO      | core01 starting in peer mode
[etcd] Apr 17 22:54:07.416 INFO      | core01: state changed from 'initialized' to 'follower'.
[raft]22:54:07.416668 Name: core01, State: follower, Term: 0, CommitedIndex: 0 
[etcd] Apr 17 22:54:07.416 INFO      | core01: state changed from 'follower' to 'leader'.
[etcd] Apr 17 22:54:07.417 INFO      | core01: leader changed from '' to 'core01'.
[etcd] Apr 17 22:54:07.417 DEBUG     | URLs: /_etcd/machines: core01 / core01 ()
[etcd] Apr 17 22:54:07.417 DEBUG     | Register: core01
[raft]22:54:07.417988 setCommitIndex.set.result index: 1, entries index: 0
[etcd] Apr 17 22:54:07.418 DEBUG     | core01 start as a leader
[etcd] Apr 17 22:54:07.418 DEBUG     | core01 start as a leader
[etcd] Apr 17 22:54:07.418 DEBUG     | set cluster config as &{9 1800 5}
[raft]22:54:07.418493 setCommitIndex.set.result index: 2, entries index: 1
[etcd] Apr 17 22:54:07.418 DEBUG     | core01 start as a leader
[etcd] Apr 17 22:54:07.418 DEBUG     | core01 sets cluster config as &{9 1800 5}
[raft]22:54:07.418669 setCommitIndex.set.result index: 3, entries index: 2
[etcd] Apr 17 22:54:07.419 INFO      | failed to get local etcd versions: open /usr/libexec/etcd/internal_versions/: no such file or directory
[etcd] Apr 17 22:54:07.723 DEBUG     | [recv] PUT http://172.31.35.233:4001 /v2/keys/_coreos.com/fleet/machines/038336dd1a0c49cba9c21f9f3f6e6acf/object [127.0.0.1:48660]
[etcd] Apr 17 22:54:07.724 DEBUG     | Key not found (/_coreos.com)
[raft]22:54:07.724318 setCommitIndex.set.result index: 4, entries index: 3
[etcd] Apr 17 22:54:07.724 DEBUG     | Return error: Key not found (/_coreos.com)
[etcd] Apr 17 22:54:07.724 DEBUG     | [recv] PUT http://172.31.35.233:4001 /v2/keys/_coreos.com/fleet/machines/038336dd1a0c49cba9c21f9f3f6e6acf/object [127.0.0.1:48660]
[raft]22:54:07.724989 setCommitIndex.set.result index: 5, entries index: 4
[etcd] Apr 17 22:54:07.725 DEBUG     | [recv] GET http://172.31.35.233:4001 /v2/keys/_coreos.com/fleet/job [127.0.0.1:48660]
[etcd] Apr 17 22:54:07.725 DEBUG     | Return error: Key not found (/_coreos.com/fleet/job)
[etcd] Apr 17 22:54:07.726 DEBUG     | [recv] GET http://172.31.35.233:4001 /v2/keys/_coreos.com/fleet/job [127.0.0.1:48660]
[etcd] Apr 17 22:54:07.726 DEBUG     | Return error: Key not found (/_coreos.com/fleet/job)
[etcd] Apr 17 22:54:07.726 DEBUG     | [recv] GET http://172.31.35.233:4001 /v2/keys/_coreos.com/fleet/engine/version [127.0.0.1:48661]
[etcd] Apr 17 22:54:07.726 DEBUG     | Return error: Key not found (/_coreos.com/fleet/engine)
[etcd] Apr 17 22:54:07.727 DEBUG     | [recv] GET http://172.31.35.233:4001 /v2/keys/_coreos.com/fleet/job [127.0.0.1:48662]
[etcd] Apr 17 22:54:07.727 DEBUG     | [recv] GET http://172.31.35.233:4001 /v2/keys/_coreos.com/fleet/job [127.0.0.1:48663]
[etcd] Apr 17 22:54:07.731 DEBUG     | [recv] PUT http://172.31.35.233:4001 /v2/keys/_coreos.com/fleet/engine/version [127.0.0.1:48661]
[etcd] Apr 17 22:54:07.732 DEBUG     | Key not found (/_coreos.com/fleet/engine)
[raft]22:54:07.732219 setCommitIndex.set.result index: 6, entries index: 5
[etcd] Apr 17 22:54:07.732 DEBUG     | Return error: Key not found (/_coreos.com/fleet/engine)
[etcd] Apr 17 22:54:07.732 DEBUG     | [recv] PUT http://172.31.35.233:4001 /v2/keys/_coreos.com/fleet/engine/version [127.0.0.1:48661]
[raft]22:54:07.732717 setCommitIndex.set.result index: 7, entries index: 6
[etcd] Apr 17 22:54:07.733 DEBUG     | [recv] GET http://172.31.35.233:4001 /v2/keys/_coreos.com/fleet/lease/engine-leader [127.0.0.1:48661]
[etcd] Apr 17 22:54:07.733 DEBUG     | Return error: Key not found (/_coreos.com/fleet/lease)
[etcd] Apr 17 22:54:07.733 DEBUG     | [recv] PUT http://172.31.35.233:4001 /v2/keys/_coreos.com/fleet/lease/engine-leader [127.0.0.1:48661]
[raft]22:54:07.733580 setCommitIndex.set.result index: 8, entries index: 7
[etcd] Apr 17 22:54:07.733 DEBUG     | [recv] GET http://172.31.35.233:4001 /v2/keys/_coreos.com/fleet/job [127.0.0.1:48661]
[etcd] Apr 17 22:54:07.734 DEBUG     | Return error: Key not found (/_coreos.com/fleet/job)
[etcd] Apr 17 22:54:07.734 DEBUG     | [recv] GET http://172.31.35.233:4001 /v2/keys/_coreos.com/fleet/job [127.0.0.1:48661]
[etcd] Apr 17 22:54:07.734 DEBUG     | Return error: Key not found (/_coreos.com/fleet/job)
[etcd] Apr 17 22:54:07.734 DEBUG     | [recv] GET http://172.31.35.233:4001 /v2/keys/_coreos.com/fleet/machines [127.0.0.1:48661]
[raft]22:54:07.919008 setCommitIndex.set.result index: 9, entries index: 8
[etcd] Apr 17 22:54:08.418 DEBUG     | URLs: /_etcd/machines:  /  (core01)
[raft]22:54:08.419174 setCommitIndex.set.result index: 10, entries index: 9
[raft]22:54:08.918996 setCommitIndex.set.result index: 11, entries index: 10
…

...
[etcd] Apr 17 22:54:19.732 DEBUG     | Return error: Key not found (/_coreos.com/fleet/job)
[etcd] Apr 17 22:54:19.732 DEBUG     | [recv] GET http://172.31.35.233:4001 /v2/keys/_coreos.com/fleet/machines [127.0.0.1:48661]
[raft]22:54:19.918966 setCommitIndex.set.result index: 39, entries index: 38
[etcd] Apr 17 22:54:20.418 DEBUG     | URLs: /_etcd/machines:  /  (core01)
[raft]22:54:20.419140 setCommitIndex.set.result index: 40, entries index: 39
[raft]22:54:20.918995 setCommitIndex.set.result index: 41, entries index: 40

------------------------
Now the curl https://discovery.etcd.io/f502b6f36dcb038239be260761e0d5b4  shows the core1 node

{"action":"get","node":{"key":"/_etcd/registry/f502b6f36dcb038239be260761e0d5b4","dir":true,"nodes":[{"key":"/_etcd/registry/f502b6f36dcb038239be260761e0d5b4/core01","value":"http://172.31.35.233:7001","expiration":"2015-04-24T22:54:07.366639943Z","ttl":604557,"modifiedIndex":474014927,"createdIndex":474014927}],"modifiedIndex":473784823,"createdIndex":473784823}}
-------------------------
I wonder why the ETCD_NAME is not being populated in the etcd.service.d/20-cloudinit.conf ?

After manually adding Environment="ETCD_NAME=core1” and doing systemctl daemon-reload+systemctl start etcd.

------------------------
etcd.service - etcd
   Loaded: loaded (/etc/systemd/system/etcd.service; static; vendor preset: disabled)
  Drop-In: /run/systemd/system/etcd.service.d
           └─10-oem.conf, 20-cloudinit.conf
   Active: activating (auto-restart) (Result: exit-code) since Fri 2015-04-17 23:08:58 UTC; 6s ago
  Process: 12355 ExecStart=/usr/bin/etcd (code=exited, status=1/FAILURE)
 Main PID: 12355 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/etcd.service

Apr 17 23:08:58 ip-172-31-35-233.us-west-2.compute.internal systemd[1]: Unit etcd.service entered failed state.
Apr 17 23:08:58 ip-172-31-35-233.us-west-2.compute.internal systemd[1]: etcd.service failed.

----------
what could be the problem with etcd being run by systemctl which by the way works in command line ?
why is service not able to see the discovery url while the same etcd can see in command line.

**Comment by carmstrong** [comment]
@pdhar-tibco How did you provision these instances? Did you follow our instructions and provision scripts to deploy to AWS?

**Comment by pdhar-tibco** [comment]
Yes, I followed the instructions except configuring the DNS one which I don’t have the need at this early evaluation stage.

**Comment by carmstrong** [comment]
@pdhar-tibco You're still using the same discovery URL that you used for your local instances. Notice when you go to https://discovery.etcd.io/f502b6f36dcb038239be260761e0d5b4 that there is one machine listed, with an IP of `172.31.35.233`. Your EC2 hosts are trying to talk to this IP (when they of course cannot), so that's why you're seeing `501: All the given peers are not reachable (Tried to connect to each peer twice and failed)`.

You'll need to destroy your stack and ensure you get a new discovery URL with `make discovery-url` when provisioning the cluster.

**Comment by pdhar-tibco** [comment]
OK. I have started the provisioning atfer make discovery-url.
I had modified the user-data.example template with the following sections. I am wondering if any of these changes can contribute towards the problem.
--------------
< # Set SSH keys
< ssh_authorized_keys:
<  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD4E7QdfjEjeWES3t4I6iM1D6eerCcUTqggNOdzaVY39kaOZ4k4QxPzkpiX2M4hJLRupfM6sX3UmUCpZT+AQua7DrKXAzjXUy9Swy3TYGnnLaHc4i6nUT6FG7JhxfBGmoQiPKiB7Bs0/j+anHpbtQAPjInD+5BUZi2Nz7TvHxLOA+odzKABrGrySOvfBbNv8pUTzPdFGh/SI6zsuR2Zwi8/+h4h3ykyOKfd/S65NAryAQk8WCf5rW4uGqmP60CGxeaJmHSqBgHXY+5+po5yN6kQ5XNyc+YWGfUry5Afq1 deis
-----------------
> users:  
>   - name: pdhar
>     passwd: $1$GcTpNjP1$5skqoicX3G/YgFUoxrtt/
>     ssh-authorized-keys: 
>      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjgRKHNQJ+8AHilcbX2XFYm8d0Q8ApfwbHgoUkU9EM+mw63ZIRoPRfQrvHTD5Lkr7GVKrb7gFvPQ9qKg7Qwr0402TM5sWrclng4ZXSF/lGZHcrKD3p1BCzg+b+N+FQuflqaEEmdQSRV536sNd6wHRy8V1CieulM7NfPwcNwQ5O0V4Zq7WFvqQT5vHgY6Cfyn0gVmMOyQVpHPkpL7dA7v5YmJU+BlhRen+P3aJb4rf7e7IUAIIfhV3ZfJMrkOhdjfJgpnpAcIKAkmFdR+17Chf6jSBmvG5HXyBvfdun4hWLZ pdhar@pranabs-mbp
>   - groups:
>       - sudo
>       - docker  
>   - name: deis
>     passwd: $1$GcTpNjP1$5skqoicX3G/YgFUoxrtt/
>     ssh-authorized-keys: 
>     - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD4E7QdfjEjeWES3t4I6iM1D6eerCcUTqggNOdzaVY39kaOZ4k4QxPzkpiX2M4hJLRupfM6sX3UmUCpZT+AQua7DrKXAzjXUy9Swy3TYGnnLaHc4i6nUT6FG7JhxfBGmoQiPKiB7Bs0/j+anHpbtQAPjInD+5BUZi2Nz7TvHxLOA+odzKABrGrySOvfBbNv8pUTzPdFGh/SI6zsuR2Zwi8/+h4h3ykyOKfd/S65NAryAQk8WCf5rW4uGqmP60CGxeaJmHSqBgHXY+5+po5yN6kQ5XNyc+YWGfUry5Afq1 deis
>   - groups:
>       - sudo
>       - docker
>   - name: root
>     passwd: $1$GcTpNjP1$5skqoicX3G/YgFUoxrtt/
>     ssh-authorized-keys: 
>     - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD4E7QdfjEjeWES3t4I6iM1D6eerCcUTqggNOdzaVY39kaOZ4k4QxPzkpiX2M4hJLRupfM6sX3UmUCpZT+AQua7DrKXAzjXUy9Swy3TYGnnLaHc4i6nUT6FG7JhxfBGmoQiPKiB7Bs0/j+anHpbtQAPjInD+5BUZi2Nz7TvHxLOA+odzKABrGrySOvfBbNv8pUTzPdFGh/SI6zsuR2Zwi8/+h4h3ykyOKfd/S65NAryAQk8WCf5rW4uGqmP60CGxeaJmHSqBgHXY+5+po5yN6kQ5XNyc+YWGfUry5Afq1 deis
>   - groups:
>       - sudo
>       - docker
217a240,262
>   - path: /etc/resolv.conf
>     permissions: 0644
>     owner: root
>     content: |
>       nameserver 8.8.8.8
>       nameserver 8.8.4.4
>       domain www.example.com
>   - path: /etc/motd
>     permissions: 0644
>     owner: root
>     content: |
>       Good news, everyone!
>   - path: /etc/sudoers
>     permissions: 0644
>     owner: root
>     content: |
>       Defaults        env_reset
>       Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
>       %admin ALL=(ALL) ALL
>       %sudo  ALL=(ALL:ALL) ALL
>       root   ALL=(ALL) ALL
>       deis   ALL=(ALL) ALL
>       pdhar  ALL=(ALL) ALL

**Comment by pdhar-tibco** [comment]
It looks like the users were creating some problem. I only limited my changes to the ssh_authorized_keys and it is working.
