### ISSUE TITLE
Client warning of wrong version with latest cluster

### ISSUE THREAD

**Issue by jwaldrip** [deis/deis#3528]
I am getting the following error when trying to run any deis command. My cluster is at the latest release (v1.5.1) so I have no idea on why I would be seeing this warning...

``` ...
 !    WARNING: Client and server API versions do not match. Please consider upgrading.
 !    Client version: 1.2
 !    Server version: 1.1
```

**Comment by mboersma** [comment]
If the server is actually running v1.5.1, it should be responding with [API v1.2.0](https://github.com/deis/deis/blob/v1.5.1/controller/api/__init__.py), and release testing didn't show this warning. Can you check again that you aren't still running v1.4 or earlier of Deis on that controller?

**Comment by jwaldrip** [comment]
Correct. Just created a new cluster running 1.5.1 and I am still getting the warning.

**Comment by bacongobbler** [comment]
@jwaldrip can you please explain your deployment process? Curious to know how you're ending up with the wrong server API version.

**Comment by bacongobbler** [comment]
Also if you can't run `deis certs:list` then you're definitely on an older controller version

**Comment by jwaldrip** [comment]
Totally my fault. I had the 1.5.1 unit files but my user-data was specifying the old version.

**Comment by bacongobbler** [comment]
In the future, a `deisctl config platform set verstion=v1.5.1` and rebooting the platform will rectify the issue:)
