### ISSUE TITLE
Cannot get application SSL to function

### ISSUE THREAD

**Issue by jwaldrip** [deis/deis#3534]
I have the following setup:

* ELB with 443 frontend to 443 Backend over TCP assigned to Security Group with 443 inbound allowed from all ips.
* Cluster with security group allowing 443, and 80 from ELB security group.
* Cert added with `deis certs:add` with a wildcard cert for *.brandfolder.com

***Expected:***
Application is accessible at zip.brandfolder.com

***Actual:***
Connection timeout.

**Comment by bacongobbler** [comment]
Wildcard certs for custom domains are currently unsupported. If you're installing a platform wildcard certificate, that has to be installed either [on the load balancer](http://docs.deis.io/en/latest/managing_deis/ssl-endpoints/#installing-ssl-on-a-load-balancer) or [on the routers](http://docs.deis.io/en/latest/managing_deis/ssl-endpoints/#installing-ssl-on-the-deis-routers).

**Comment by cheshirecatalyst** [comment]
so related to this, i have added a similar cert, and am unable to remove it getting

```
deis certs:remove '*.hotelquickly.com'
Removing *.hotelquickly.com... 405 METHOD NOT ALLOWED
Detail:
Method 'DELETE' not allowed.
```

is there anyway to fix this? we have tried removing it from storage and a few other things, but nothing seems to work.

**Comment by carmstrong** [comment]
> is there anyway to fix this? we have tried removing it from storage and a few other things, but nothing seems to work.

Not being able to remove a domain certainly looks like a bug - we're looking into this. 

> and corollary question: do the routers support certs with SAN's?

Not yet. See #3441

**Comment by bacongobbler** [comment]
@cheshirecatalyst see #3533
