### ISSUE TITLE
router: Refactor nginx.conf to be more readable and testable

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3536]
Our router's [nginx.conf template](https://github.com/deis/deis/blob/master/router/image/templates/nginx.conf) has become quite unruly. I wouldn't be surprised if someone who knows nginx templates could see some significant refactors to make this code more readable and easy to test. 

We'd love some help with this!

**Comment by bacongobbler** [comment]
I think it got a lot cleaner once we started to use our own custom confd branch for #3415. Is this still necessary or can we close it?

**Comment by carmstrong** [comment]
> Is this still necessary or can we close it?

I think there are still some improvements - there is a lot of repeated code, and breaking up the monolithic config into smaller ones may serve us well.

/cc @helgi

**Comment by bacongobbler** [comment]
fixed in Deis v2. See https://github.com/deis/router :)
