### ISSUE TITLE
Request: do not store domains in etcd:/deis/domains

### ISSUE THREAD

**Issue by krancour** [deis/deis#3539]
Currently, when a domain is added for an app, the relationship between that app and that domain is stored in _two_ places: the database (makes sense) and etcd under the key `/deis/domains` (might not make quite as much sense).

The `deis-router`, ultimately needs to be aware of these relationships and I believe it runs confd in the background to update routes based on what's found in etcd under the `/deis/domains` key.

The problem with this is that anyone who's seeking to externalize durable platform state using the likes of RDS and S3 has no way of externalizing this little bit of configuration. It has, at least once, left me tearing down a cluster that I presumed to be stateless, only to replace it with another brand new cluster, backed by the same externalized datastores only to find that some of my routes are broken.  Deleting and re-adding the domains fixes the situation, but that's less than ideal.

Can the router source this information from the database instead?

#3486 is strikingly similar in nature, but pertains to the builder.  These two issues probably call for one common solution.

**Comment by bacongobbler** [comment]
The router relies on confd, which in turn relies on certain backends like etcd, consul, redis, etc. We'd need a way to allow confd to read from either a database or some other construct.

> Deleting and re-adding the domains fixes the situation, but that's less than ideal.

Note that we explicitly call that out in the documentation: http://docs.deis.io/en/latest/managing_deis/backing_up_data/#finishing-up

**Comment by krancour** [comment]
@bacongobbler sorry... I missed that part of the documentation.  Thank you.

Question: what about pivoting a little on both this issue and #3486 and instead of _not_ storing any platform state in etcd as initially requested, we made restoring those key/value pairs a bit easier?  I'm thinking that the steps highlighted in the documentation you just linked me to could be performed by a new API endpoint (accessible only to admins) and the CLI could allow admins to perform this final restoration step with ease.

Thoughts?

**Comment by johanneswuerbach** [comment]
Maybe the controller could re-add this keys to etcd on boot from the database. This would ensure that on a restore from an existing database all keys are re-populated.

**Comment by krancour** [comment]
This issue is quite old, but has new relevance because of #4333 

I do think controller should re-publish application config, application domains, and user keys at startup.

**Comment by krancour** [comment]
Superseded by #4355
