### ISSUE TITLE
test-infrastructure: Add SKIP_CLEANUP option to builds

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3543]
The [test-ec2](https://ci.deis.io/job/test-ec2/) Jenkins job will automatically clean up the cluster on failure. We should add an option to builds kicked off manually so they will [skip cleanup](https://github.com/deis/deis/blob/603c537ce9c1b88430a06d0bcb1309ff37b92fcc/tests/bin/test-integration-ec2.sh#L30) if the option is set, enabling someone to investigate the broken state of the world and diagnose the issue preventing the PR from passing.

**Comment by bacongobbler** [comment]
I wish there would be a way we could only allow admins to whitelist this so people can't run off with free CoreOS clusters just by using our AWS account and shutting off the flag, but maybe that's just me being pessimistic. :)

**Comment by carmstrong** [comment]
> I wish there would be a way we could only allow Jenkins admins to whitelist this

Only people who explicitly have access to Jenkins can modify build parameters, no?

**Comment by mboersma** [comment]
Yes, only authenticated admins can change the build scripts or parameters on Jenkins.
