### ISSUE TITLE
Scala buildpack is broken

### ISSUE THREAD

**Issue by mboersma** [deis/deis#3545]
In trying to test a PR against our example-scala app, I found I was unable to get the buildpack to initialize:
```
       [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
       [warn] 	::              FAILED DOWNLOADS            ::
       [warn] 	:: ^ see resolution messages for details  ^ ::
       [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
       [warn] 	:: com.twitter#util-collection;1.11.4!util-collection.jar
       [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
       sbt.ResolveException: download failed: com.twitter#util-collection;1.11.4!util-collection.jar
       at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:211)
```
I tried many times with a couple versions of [example-scala](https://github.com/deis/example-scala), but this error was consistent. It looks to me like heroku-buildpack-scala [v43](https://github.com/deis/deis/blob/master/builder/image/slugbuilder/builder/install-buildpacks#L41) has rusted.

I updated the buildpack to [current v55](https://github.com/heroku/heroku-buildpack-scala/releases) and tried again. The buildpack initializes fine (and more quickly), but [the example app](https://github.com/deis/example-scala) has some errors I couldn't figure out:
```console
       [info] Compiling 1 Scala source to /tmp/scala_buildpack_build_dir/.sbt_home/plugins/target/scala-2.9.2/sbt-0.12/classes...
       [error] error while loading CharSequence, class file '/tmp/scala_buildpack_build_dir/.jdk/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
       [error] (bad constant pool tag 18 at byte 10)
       [error] error while loading Comparator, class file '/tmp/scala_buildpack_build_dir/.jdk/jre/lib/rt.jar(java/util/Comparator.class)' is broken
       [error] (bad constant pool tag 18 at byte 20)
       [error] two errors found
       [error] (compile:compile) Compilation failed
       Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
       !     ERROR: Failed to run sbt!
       We're sorry this build is failing! If you can't find the issue in application
       code, please submit a ticket so we can help: https://help.heroku.com
       You can also try reverting to our legacy Scala buildpack:
       $ heroku buildpack:set https://github.com/heroku/heroku-buildpack-scala#legacy
       
       Thanks,
       Heroku
```

**Comment by onbjerg** [comment]
Hmm. The errors look like your JRE is either too new or too old. What version of Scala is v55 using?

**Comment by mboersma** [comment]
> Looks like they need to use Java 6 or 7.

I see. Thanks for all the sleuthing here. Let me see if there is some way to coerce it into doing that: https://devcenter.heroku.com/articles/customizing-the-jdk#specify-a-jdk-version
