### ISSUE TITLE
/run/deis/bin/fleetd-0.9.2 disappears on host reboot

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3547]
We added fleet 0.9.2 in #3422, since CoreOS ships fleet 0.9.1 with a known issue that affected the reliability of deploying apps on Deis.

@rjocoleman reported in https://github.com/deis/deis/pull/3422#issuecomment-94619495 that upon rebooting his hosts, the binary went missing. 

Is this happening on all providers? Could it be due to the way CoreOS mounts filesystems?

**Comment by bacongobbler** [comment]
could this be related to #3149, perhaps?

**Comment by rjocoleman** [comment]
I'm on AWS provisioned with https://github.com/deis/deis/blob/v1.4.1/contrib/ec2/provision-ec2-cluster.sh and no changes other than the name and number of hosts (5)

**Comment by chrisgeo** [comment]
I can confirm it happened on Azure as well. Brought back by unmasking the service.

**Comment by crigor** [comment]
/run uses tmpfs on the AWS instances so this is expected behavior. I haven't checked the other providers.

**Comment by ineu** [comment]
`/run` is in-memory in CoreOS, as well as in most modern distributions, it doesn't depend on provider. I see the same in bare metal cluster:
```
production-coreos-3 ~ # ls /run/deis/bin
get_image  preseed
```

If recent fleet should be used, then it should be either downloaded on each boot or stored in some persistent storage (probably somewhere in `/var` as `/usr` is readonly in CoreOS).

**Comment by pdhar-tibco** [comment]
On my virtual box even after running the the upgrade-fleet-091.services download script manually to get fleet_0.9.2  it vanishes after reboot. I would like to know what is causing this or if there is any way  to make it persistent.

**Comment by carmstrong** [comment]
Ah - I was confused because our other scripts in `/run/deis/bin` persist, but that's because they're written by the cloud-config on each boot. 

Upgrading fleet was a workaround for a very broken fleet 0.9.1 which is what ships on the latest stable. We're really waiting for that to land in stable.

Would a reasonable workaround be to modify this unit to write to `/home/core` instead? That should certainly persist.

**Comment by pdhar-tibco** [comment]
If the systemctl start fleet is run I believe it should check for the two conditions
1. ConditionPathIsSymbolicLink=!/etc/systemd/system/fleet.service.d/99-upgrade-fleet-091.conf which checks the 0.9.1 configuration file is not a symbolic link.
2. Also if it is a symbolic link and pointing to the correct 0.9.2 configuration which was serialized in the /run/deis/conf/fleetd-092-custom-binary.conf file if the fleet_0.9.2 is missing

**Comment by pdhar-tibco** [comment]
Missed one small detail 
if the link already exists use ln -sf to force relinking.

**Comment by carmstrong** [comment]
@pdhar-tibco If you want to take a stab at fixing this, that'll help people who are provisioning in master. Users with existing deploys will need to manually patch the unit.

Most likely, this unit will be gone before Deis 1.6.0 ships as we're expecting fleet 0.9.2 to hit the stable channel by then.

**Comment by pdhar-tibco** [comment]
I added this section to the user-data.example below the update-fleet-091.service section and it worked(downloaded the fleet_0.9.2) when I started etcd manually after filling in the addr/peer ip numbers as there is no $public_ipv4 on the virtual box install.
localhost system # ls -al /run/deis/bin/
total 8412
drwxr-xr-x 2 root root     100 Apr 22 19:19 .
drwxr-xr-x 4 root root      80 Apr 22 19:19 ..
-rwxr-xr-x 1 root root 8604584 Apr 22 19:19 fleetd-0.9.2
-rwxr-xr-x 1 root root     473 Apr 22 19:19 get_image
-rwxr-xr-x 1 root root     300 Apr 22 19:19 preseed
-------------------------------------
  - name: check-fleet-092.service
    command: start
    content: |
     [Unit]
     Description=Download fleetd_0.9.2 forcefully if it does not exist after upgrade-fleet-091.service
     Before=fleet.service
     After=upgrade-fleet-091.service
     ConditionPathExists=!/run/deis/bin/fleetd-0.9.2

     [Service]
     ExecStart=/usr/bin/bash -c 'if fleetd --version | grep -q 0.9.1; then wget --quiet --tries 5 -w 2 -O /run/deis/bin/fleetd-0.9.2 https://s3-us-west-2.amazonaws.com/opdemand/fleetd-v0.9.2 && chmod +x /run/deis/bin/fleetd-0.9.2 && mkdir -p /etc/systemd/system/fleet.service.d/ && ln -sf /run/deis/conf/fleetd-092-custom-binary.conf /etc/systemd/system/fleet.service.d/99-upgrade-fleet-091.conf; else rm -f /etc/systemd/system/fleet.service.d/99-upgrade-fleet-091.conf; fi'
     RemainAfterExit=yes
     Type=oneshot

**Comment by zag2art** [comment]
This is happening on DO as well.

**Comment by ngpestelos** [comment]
I encountered this problem today on Digital Ocean. Here's what I found when I ran `journalctl -f` on the node: http://imgur.com/lP44GQC

I then ran the following scripts manually (see also contrib/coreos/user-data.example):

    $ curl -sSL --retry 5 --retry-delay 2 -o /run/deis/bin/fleetd-0.9.2 https://s3-us-west -2.amazonaws.com/opdemand/fleetd-v0.9.2
    $ chmod +x /run/deis/bin/fleetd-0.9.2
    $ mkdir -p/etc/systemd/system/fleet.service.d/ && ln -s /run/deis/conf/fleetd-092-custom-binary.conf

**Comment by zag2art** [comment]
@ngpestelos yeah, that is right, but if you reboot the machine you will have to run the script again.

**Comment by ngpestelos** [comment]
Thanks, @zag2art, I wrote them before reading #3594.

**Comment by ineu** [comment]
@carmstrong Coreos 647 with fleet 0.9.2 is now stable

**Comment by carmstrong** [comment]
@ineu See #3676 :)

**Comment by ineu** [comment]
nice!

**Comment by zag2art** [comment]
+1
