### ISSUE TITLE
Apps built on Docker 1.6 -- Cannot `deis pull`: Invalid image ID

### ISSUE THREAD

**Issue by glogiotatidis** [deis/deis#3550]
I get this error on Deis 1.5.0. I used to work just fine a couple of days back.

```
deis pull mozillamffos/masterfirefoxos:ab98aa464cc4eccb1ed8c62145a745d7d2ee95c0 -a masterfirefoxos-dev
Creating build..503 SERVICE UNAVAILABLE
Detail:
GET Image Error (404: {"error": "Invalid image ID"})
```

The tag exists on docker hub and I can manually `docker pull mozillamffos/masterfirefoxos:ab98aa464cc4eccb1ed8c62145a745d7d2ee95c0` from the Deis hosts.

I tried the same command with different deis app, same issue.

**Comment by glogiotatidis** [comment]
More information: All deis services appear to be running with `fleetctl list-units`. I restarted the registry and the problem is still there.

`fleetctl journal deis-registry@1`
```
Apr 22 12:33:20 ip-10-152-74-8 sh[18022]: 22/Apr/2015:12:33:20 +0000 INFO: Starting new HTTPS connection (1): registry.hub.docker.com
Apr 22 12:33:21 ip-10-152-74-8 sh[18022]: 22/Apr/2015:12:33:21 +0000 INFO: Resetting dropped connection: registry.hub.docker.com
Apr 22 12:33:21 ip-10-152-74-8 sh[18022]: 22/Apr/2015:12:33:21 +0000 INFO: Starting new HTTPS connection (1): cdn-registry-1.docker.io
Apr 22 12:33:21 ip-10-152-74-8 sh[18022]: 22/Apr/2015:12:33:21 +0000 INFO: Resetting dropped connection: cdn-registry-1.docker.io
Apr 22 12:33:22 ip-10-152-74-8 sh[18022]: 22/Apr/2015:12:33:22 +0000 INFO: Resetting dropped connection: cdn-registry-1.docker.io
Apr 22 12:33:22 ip-10-152-74-8 sh[18022]: 22/Apr/2015:12:33:22 +0000 INFO: Resetting dropped connection: cdn-registry-1.docker.io
Apr 22 12:33:22 ip-10-152-74-8 sh[18022]: 22/Apr/2015:12:33:22 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Apr 22 12:33:22 ip-10-152-74-8 sh[18022]: 10.152.74.240 - - [22/Apr/2015:12:33:22 +0000] "POST /v1/repositories/masterfirefoxos-dev/tags HTTP/1.1" 200 4 "-" "python-requests/2.4.3 CPython/2.7.6 Linux/3.18.6"
Apr 22 12:33:22 ip-10-152-74-8 sh[18022]: 22/Apr/2015:12:33:22 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Apr 22 12:33:22 ip-10-152-74-8 sh[18022]: 10.152.74.240 - - [22/Apr/2015:12:33:22 +0000] "GET /v1/repositories/masterfirefoxos-dev/tags/ab98aa464cc4eccb1ed8c62145a745d7d2ee95c0 HTTP/1.1" 200 10 "-" "docker/1.0.0"
Apr 22 12:33:22 ip-10-152-74-8 sh[18022]: 22/Apr/2015:12:33:22 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Apr 22 12:33:22 ip-10-152-74-8 sh[18022]: 10.152.74.240 - - [22/Apr/2015:12:33:22 +0000] "GET /v1/images/220da1da/json HTTP/1.1" 404 29 "-" "docker/1.0.0"
```

**Comment by babarinde** [comment]
what does your builder say
```fleetctl journal deis-builder```

**Comment by glogiotatidis** [comment]
> what does your builder say
> fleetctl journal deis-builder

I'm not using the builder. I'm pulling pre-built docker images.

**Comment by babarinde** [comment]
First your error above
> Creating build..503 SERVICE UNAVAILABLE

second i think deis pull uses 
http://docs.deis.io/en/latest/reference/api-v1.3/#create-application-build

so i think you need to see your builder logs

**Comment by glogiotatidis** [comment]
There is nothing related in the builder logs.

**Comment by bacongobbler** [comment]
@babarinde `deis pull` goes through the controller so there won't be any relevant logs in the builder.

Out of curiosity, did you build this image using Docker v1.6?

**Comment by glogiotatidis** [comment]
Indeed! We upgraded our builder yesterday and I think it's the same time the problem started. How's that related?

**Comment by bacongobbler** [comment]
Docker v1.6 introduced a new image format with digests on both the DockerHub side and the daemon itself. Because `deis pull` is essentially a hack, I think it'll only work with pre-v1.6 images that use the older image format. I experienced something similar yesterday when I upgraded my daemon to v1.6, so it might be causing the issue you're seeing here.

Are you able to pull other images (for example `gabrtv/example-go:latest`)?

**Comment by glogiotatidis** [comment]
Yes I can pull other images. What is the proposed solution here?

**Comment by bacongobbler** [comment]
For now I'd say that you should work with images built with v1.5 or earlier until either
a) we update our fork of the registry to handle v2 images
b) pull out the hack and take the performance hit around pulling images as explained in https://github.com/deis/deis/pull/1190#issuecomment-46607167
c) deprecate `deis pull` in favour of something like `deis push`: https://github.com/deis/deis/issues/2680

**Comment by glogiotatidis** [comment]
Downgrading to docker 1.5 fixed the issue. Thanks for the workaround.
