### ISSUE TITLE
CoreOS update docs are inexact

### ISSUE THREAD

**Issue by ineu** [deis/deis#3551]
Instructions on updating CoreOS in http://pythonhosted.org/deis/managing_deis/upgrading-deis/#upgrading-coreos have a drawback: update is not persistent.
When system is upgraded, partitions are switched for one boot only. If server is rebooted again, no matter how long after the first reboot, system will be reset to previous version.
Solution to it is to unmask and start `update-engine` again after reboot and give it some time to update boot flags:
```
# journalctl -u update-engine | grep boot
...
Apr 22 12:41:11 production-coreos-2 update_engine[3456]: [0422/124111:INFO:update_attempter.cc(674)] Updating boot flags...
```

**Comment by aledbf** [comment]
similar to #3155

**Comment by bacongobbler** [comment]
let's close this in favour of #3155 as a duplicate. Thanks for pointing that out @aledbf :)

**Comment by ineu** [comment]
Great, thanks.
