### ISSUE TITLE
deis-logger log drain format

### ISSUE THREAD

**Issue by jannispl** [deis/deis#3553]
I've set up my cluster to forward logs to Papertrail using `deisctl config logs set drain=syslog://logs2.papertrailapp.com:port` but it seems that the logs being sent are not in correct syslog format (Papertrail can't filter by app/apply color codes).

An illustration:
![image](https://cloud.githubusercontent.com/assets/838818/7278709/729ce6b4-e917-11e4-9717-437ee2c67633.png)

**Comment by bacongobbler** [comment]
The format of the logs are from here, which is custom to Deis: https://github.com/deis/deis/blob/master/logspout/logspout.go#L73-L79

**Comment by bacongobbler** [comment]
We're open to suggestions, but note that this is how Deis' logger filters logs based on which container it came from. It filters based on the tag which in our case is the name of the container.

**Comment by eMxyzptlk** [comment]
Perhaps, every log message should be reformatted back using the default format before being sent to the drain server?
