### ISSUE TITLE
INFO client.go:291: Failed getting response from http://localhost:4001/: unexpected EOF

### ISSUE THREAD

**Issue by pdhar-tibco** [deis/deis#3558]
Hi ,
I have been able to start the etcd and fleetd_0.9.2 on the non vagrant virtual box set up on my development mac. I have not been able to execute "deisctl install platform" and I noticed the following in the journalctl logs. Any clues ?
● ▴ ■
■ ● ▴ Installing Deis...
▴ ■ ●

Storage subsystem...
deis-store-monitor.service: loaded                                 
deis-store-daemon.service: loaded                                 
deis-store-metadata.service: loaded                                 
deis-store-volume.service: loaded                                 
deis-store-gateway@1.service: loaded                                 
Logging subsystem...
deis-logspout.service: loaded                                 
deis-logger.service: loaded                                 
Control plane...
deis-registry@1.service: loaded                                 
deis-database.service: loaded                                 
deis-controller.service: loaded                                 
deis-builder.service: loaded                                 
Data plane...
deis-publisher.service: loaded                                 
Routing mesh...
deis-router@2.service: loaded  

** The installation is stuck at deis-router step **
------------------------
Apr 22 23:17:56 localhost fleetd-0.9.2[639]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Apr 22 23:17:57 localhost fleetd-0.9.2[639]: INFO client.go:291: Failed getting response from http://localhost:4001/: unexpected EOF
Apr 22 23:17:57 localhost fleetd-0.9.2[639]: ERROR client.go:213: Unable to get result for {Watch /_coreos.com/fleet/job}, retrying in 100ms
Apr 22 23:18:41 localhost systemd[1]: Starting Generate /run/coreos/motd...
Apr 22 23:18:41 localhost systemd[1]: Started Generate /run/coreos/motd.
Apr 22 23:19:41 localhost systemd[1]: Starting Generate /run/coreos/motd...
Apr 22 23:19:41 localhost systemd[1]: Started Generate /run/coreos/motd.
Apr 22 23:20:41 localhost systemd[1]: Starting Generate /run/coreos/motd...
Apr 22 23:20:41 localhost systemd[1]: Started Generate /run/coreos/motd.
Apr 22 23:21:41 localhost systemd[1]: Starting Generate /run/coreos/motd...
Apr 22 23:21:41 localhost systemd[1]: Started Generate /run/coreos/motd.
Apr 22 23:22:41 localhost systemd[1]: Starting Generate /run/coreos/motd...
Apr 22 23:22:41 localhost systemd[1]: Started Generate /run/coreos/motd.
Apr 22 23:22:57 localhost fleetd-0.9.2[639]: ERROR event.go:107: etcd watcher {Watch /_coreos.com/fleet/job} returned error: unexpected end of JSON input
Apr 22 23:22:57 localhost fleetd-0.9.2[639]: INFO client.go:291: Failed getting response from http://localhost:4001/: unexpected EOF
Apr 22 23:22:57 localhost fleetd-0.9.2[639]: ERROR client.go:213: Unable to get result for {Watch /_coreos.com/fleet/job}, retrying in 100ms
Apr 22 23:23:13 localhost systemd[1]: Starting OpenSSH per-connection server daemon (10.108.0.76:61196)...
Apr 22 23

**Comment by carmstrong** [comment]
@pdhar-tibco You're getting a bunch of errors from etcd - is it running and healthy on that host? `journalctl -u etcd`.

**Comment by pdhar-tibco** [comment]
Since I cloned the virtual box VM’s and changed only the /etc/environment the /etc/machine-id remained the same. I am in the process of changing the machine id’s
and also at /var/lib/etcd/conf which also has the same if. I am not sure where else I need to change to get it correct and running.

**Comment by carmstrong** [comment]
> I am not sure where else I need to change to get it correct and running.

I'm really not sure either. I'd recommend a reprovision with fresh VMs. 

Is there a reason you're not using Vagrant? Our workflow is configured to work well, and we use it many times a day ourselves.

**Comment by pdhar-tibco** [comment]
The disk space on the vagrant vm images was low. I wanted to set development vm’s which can be set independently and can be tooled as per our requirements.

**Comment by bacongobbler** [comment]
Unfortunately I don't think there's much we can do to help you here since this isn't something we support, so we don't have experience handling this sort of setup. Perhaps there may be something useful on the [coreos-dev mailing list](https://groups.google.com/forum/#!forum/coreos-dev) which may help you? They also have QEMU images available at https://coreos.com/docs/running-coreos/platforms/qemu/ which may be what you're looking for to tweak the images.
