### ISSUE TITLE
deis pull from local/private docker registry fails 

### ISSUE THREAD

**Issue by fretboarder** [deis/deis#3559]
deis pull(ing) from a private docker registry in my local network fails,
here's what I'm doing:

$ deis create my-app
Creating application... done, created my-app

**Logs from deis-controller:
INFO myapp: config myapp-24bcd81 updated
INFO myapp: release myapp-v1 created
10.99.89.1 "POST /v1/apps HTTP/1.0" 201 192 "python-requests/2.5.1 CPython/2.7.6 Linux/3.13.0-46-generic"**

$ deis pull myregistry.deis.local:25000/demoapp/myapp:TAG_1.0_20150421_23 -a myapp
Creating build... 503 SERVICE UNAVAILABLE
Detail:
GET Image Error (404: {"error": "Tag not found"})

**Logs from deis-controller:
INFO myapp: build myapp-157c0c0 created
INFO myapp: release myapp-v2 created
192.168.10.145 "POST /v1/apps/myapp/builds HTTP/1.0" 503 66 "python-requests/2.5.1 CPython/2.7.6 Linux/3.13.0-46-generic"**

What is being POSTed to 192.168.10.145?

**Logs from deis-registry
23/Apr/2015:07:18:05 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
192.168.10.146 - - [23/Apr/2015:07:18:05 +0000] "POST /v1/repositories/myapp/tags HTTP/1.1" 500 109 "-" "python-requests/2.4.3 CPython/2.7.6 Linux/3.19.3"
23/Apr/2015:07:18:06 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
192.168.10.146 - - [23/Apr/2015:07:18:06 +0000] "GET /v1/repositories/myapp/tags/TAG_1.0_20150421_23 HTTP/1.1" 404 26 "-" "docker/1.0.0"**

I'm using CoreOS (beta) with flannel. Here's the list of deis-units

$ deisctl list
UNIT                            MACHINE                         LOAD    ACTIVE  SUB
deis-builder.service            6ec08f2c.../192.168.10.144      loaded  active  running
deis-controller.service         7203e5ef.../192.168.10.146      loaded  active  running
deis-database.service           6ec08f2c.../192.168.10.144      loaded  active  running
deis-logger.service             7203e5ef.../192.168.10.146      loaded  active  running
deis-logspout.service           6ec08f2c.../192.168.10.144      loaded  active  running
deis-logspout.service           7203e5ef.../192.168.10.146      loaded  active  running
deis-logspout.service           c9407b5b.../192.168.10.145      loaded  active  running
deis-publisher.service          6ec08f2c.../192.168.10.144      loaded  active  running
deis-publisher.service          7203e5ef.../192.168.10.146      loaded  active  running
deis-publisher.service          c9407b5b.../192.168.10.145      loaded  active  running
deis-registry@1.service         6ec08f2c.../192.168.10.144      loaded  active  running
deis-router@1.service           7203e5ef.../192.168.10.146      loaded  active  running
deis-router@2.service           c9407b5b.../192.168.10.145      loaded  active  running
deis-router@3.service           6ec08f2c.../192.168.10.144      loaded  active  running
deis-store-daemon.service       6ec08f2c.../192.168.10.144      loaded  active  running
deis-store-daemon.service       7203e5ef.../192.168.10.146      loaded  active  running
deis-store-daemon.service       c9407b5b.../192.168.10.145      loaded  active  running
deis-store-gateway@1.service    7203e5ef.../192.168.10.146      loaded  active  running
deis-store-metadata.service     6ec08f2c.../192.168.10.144      loaded  active  running
deis-store-metadata.service     7203e5ef.../192.168.10.146      loaded  active  running
deis-store-metadata.service     c9407b5b.../192.168.10.145      loaded  active  running
deis-store-monitor.service      6ec08f2c.../192.168.10.144      loaded  active  running
deis-store-monitor.service      7203e5ef.../192.168.10.146      loaded  active  running
deis-store-monitor.service      c9407b5b.../192.168.10.145      loaded  active  running
deis-store-volume.service       6ec08f2c.../192.168.10.144      loaded  active  running
deis-store-volume.service       7203e5ef.../192.168.10.146      loaded  active  running
deis-store-volume.service       c9407b5b.../192.168.10.145      loaded  active  running

**Comment by bacongobbler** [comment]
> What is being POSTed to 192.168.10.145?

That's how `deis pull` works. It's a shortcut for `deis builds:create`: https://github.com/deis/deis/blob/aaa2f8eae2fbee577050b18e42131cb3b3d63a50/client/deis.py#L952

Does your cluster have network access to myregistry.deis.local:25000?

**Comment by fretboarder** [comment]
> Does your cluster have network access to myregistry.deis.local:25000?

Yes, sure. I can pull from the command line of any of the hosts with 

docker pull myregistry.deis.local:25000/demoapp/myapp:TAG_1.0_20150421_23

**Comment by eMxyzptlk** [comment]
I'm having the same issue just pulling from the public docker registry.

```
$ deis pull dmsquadads/phabricator:latest -a phabricator
Creating build... 503 SERVICE UNAVAILABLE
Detail:
GET Image Error (404: {"error": "Tag not found"})
```

Logs from registry:
```
Apr 28 00:21:52 ip-10-21-1-104.ec2.internal sh[4361]: 28/Apr/2015:00:21:52 +0000 INFO: Resetting dropped connection: registry.hub.docker.com
Apr 28 00:21:53 ip-10-21-1-104.ec2.internal sh[4361]: 28/Apr/2015:00:21:53 +0000 INFO: Resetting dropped connection: registry.hub.docker.com
Apr 28 00:21:53 ip-10-21-1-104.ec2.internal sh[4361]: 28/Apr/2015:00:21:53 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Apr 28 00:21:53 ip-10-21-1-104.ec2.internal sh[4361]: 10.21.2.173 - - [28/Apr/2015:00:21:53 +0000] "POST /v1/repositories/phabricator/tags HTTP/1.1" 500 31 "-" "python-requests/2.4.3 CPython/2.7.6 Linux/3.18.6"
Apr 28 00:21:53 ip-10-21-1-104.ec2.internal sh[4361]: 28/Apr/2015:00:21:53 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Apr 28 00:21:53 ip-10-21-1-104.ec2.internal sh[4361]: 10.21.2.173 - - [28/Apr/2015:00:21:53 +0000] "GET /v1/repositories/phabricator/tags/latest HTTP/1.1" 404 26 "-" "docker/1.0.0"
Apr 28 00:21:53 ip-10-21-1-104.ec2.internal sh[4361]: 28/Apr/2015:00:21:53 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Apr 28 00:21:53 ip-10-21-1-104.ec2.internal sh[4361]: 10.21.2.173 - - [28/Apr/2015:00:21:53 +0000] "PUT /v1/images/c117bd0eb422432baf7c772c4b70fedcc117bd0eb422432baf7c772c4b70fedc/json HTTP/1.1" 200 4 "-" "docker/1.0.0"
Apr 28 00:21:53 ip-10-21-1-104.ec2.internal sh[4361]: 28/Apr/2015:00:21:53 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Apr 28 00:21:53 ip-10-21-1-104.ec2.internal sh[4361]: 10.21.2.173 - - [28/Apr/2015:00:21:53 +0000] "PUT /v1/images/c117bd0eb422432baf7c772c4b70fedcc117bd0eb422432baf7c772c4b70fedc/layer HTTP/1.1" 200 4 "-" "docker/1.0.0"
Apr 28 00:21:54 ip-10-21-1-104.ec2.internal sh[4361]: 28/Apr/2015:00:21:54 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Apr 28 00:21:54 ip-10-21-1-104.ec2.internal sh[4361]: 10.21.2.173 - - [28/Apr/2015:00:21:54 +0000] "PUT /v1/images/c117bd0eb422432baf7c772c4b70fedcc117bd0eb422432baf7c772c4b70fedc/checksum HTTP/1.1" 200 4 "-" "docker/1.0.0"
Apr 28 00:21:54 ip-10-21-1-104.ec2.internal sh[4361]: 28/Apr/2015:00:21:54 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Apr 28 00:21:54 ip-10-21-1-104.ec2.internal sh[4361]: 10.21.2.173 - - [28/Apr/2015:00:21:54 +0000] "PUT /v1/repositories/phabricator/tags/v0 HTTP/1.1" 200 4 "-" "docker/1.0.0"
Apr 28 00:21:54 ip-10-21-1-104.ec2.internal sh[4361]: 28/Apr/2015:00:21:54 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Apr 28 00:21:54 ip-10-21-1-104.ec2.internal sh[4361]: 10.21.2.173 - - [28/Apr/2015:00:21:54 +0000] "GET /v1/repositories/phabricator/tags/latest HTTP/1.1" 404 26 "-" "docker/1.0.0"
```

Logs from controller

```
Apr 28 00:24:47 ip-10-21-2-173.ec2.internal sh[11814]: INFO phabricator: build phabricator-6ba8c0b created
Apr 28 00:24:47 ip-10-21-2-173.ec2.internal sh[11814]: INFO phabricator: release phabricator-v22 created
Apr 28 00:24:49 ip-10-21-2-173.ec2.internal sh[11814]: 10.21.1.104 "POST /v1/apps/phabricator/builds HTTP/1.0" 503 66 "python-requests/2.5.1 CPython/2.7.5 Darwin/14.3.0"
```

**Comment by eMxyzptlk** [comment]
I also saw this:

```
Apr 27 20:21:12 52.6.112.55 logger:  2015-04-28T03:21:12UTC deis-database[1]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Apr 27 22:25:46 52.6.112.55 logger:  2015-04-28T05:25:46UTC deis-builder[1]: time="2015-04-28T05:25:46Z" level="error" msg="Error from V2 registry: error getting registry endpoint: invalid registry endpoint https://registry-1.docker.io/v2/: https://registry-1.docker.io/v2/ does not appear to be a v2 registry endpoint. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry registry-1.docker.io` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/registry-1.docker.io/ca.crt" 
```

**Comment by carmstrong** [comment]
@bacongobbler Perhaps we need to see if the public registry was updated, requiring us to update our fork?

**Comment by bacongobbler** [comment]
Yes we should investigate, but we should track that conversation in another PR so we're not de-railing @fretboarder's issue

**Comment by carmstrong** [comment]
> but we should track that conversation elsewhere so we're not de-railing @fretboarder's issue

Wondering if it isn't related - it looks like they're seeing the same error.

**Comment by bacongobbler** [comment]
After inspecting the image, I see this:

```
><> docker inspect -f '{{ .DockerVersion }}' dmsquadads/phabricator:latest
1.6.0
```

So this issue looks related to https://github.com/deis/deis/issues/3550, which is because our registry fork doesn't support Docker's new image format which was introduced in 1.6

**Comment by carmstrong** [comment]
> So this issue looks related to #3550, which is because our registry fork doesn't support Docker's new image format which was introduced in 1.6

Thanks for checking, @bacongobbler. @fretboarder any chance you have the same issue? Was your application built on Docker 1.6?

**Comment by fretboarder** [comment]
We found out that our cloud provider had an IP address conflict that affected one of the deis nodes. after resolving this problem (and upgrading to deis 1.5.2) pulling from the private docker registry now works like a charm.

**Comment by carmstrong** [comment]
> pulling from the private docker registry now works like a charm.

Glad to hear it!
