### ISSUE TITLE
deis-router error_log should have etcd configurable error level

### ISSUE THREAD

**Issue by Blystad** [deis/deis#3560]
When debugging issues with `deis-router` it might be difficult to track the error down since we are relying on the default logging level in `error_log` - `error`. While there are log levels going all the way down to `debug`. [ngx_core_module#error_log](http://nginx.org/en/docs/ngx_core_module.html#error_log)

We already compile with `--with-debug`. So all we need to do is expose the ability to change `error_log` via a `etcd` key.

(This should be a quick 2 line fix. One in nginx.conf and one in docs.)

**Comment by carmstrong** [comment]
:+1: This sounds like a good addition.
