### ISSUE TITLE
Add profile parameter to provision-ec2-cluster.sh

### ISSUE THREAD

**Issue by cleblanc87** [deis/deis#3562]
When provisioning a new cluster, the aws cli uses the default profile, it would be nice to specify which cli profile you would like to use.

**Comment by cleblanc87** [comment]
Looks like this could apply to:
update-ec2-cluster.sh
provision-ec2-cluster.sh

Anything else?

**Comment by bacongobbler** [comment]
`git grep "aws "` also shows `tests/bin/test-integration-ec2.sh` uses awscli

**Comment by cleblanc87** [comment]
This would introduce multiple optional args. Seems like a good place for getopts, but should that be a separate issue?

**Comment by carmstrong** [comment]
:+1: This would be nice to have.

**Comment by eMxyzptlk** [comment]
I can work on this if nobody is working on it.

**Comment by cleblanc87** [comment]
I have it working for update-ec2-cluster.sh & provision-ec2-cluster.sh

But I have been unable to get test-integration-ec2.sh to run on my local machine (not an issue with the param)

**Comment by eMxyzptlk** [comment]
I added support through an environment variable. I did not modify test-intergration-ec2 since it takes credentials from env-vars.
