### ISSUE TITLE
masterLock and updating logic

### ISSUE THREAD

**Issue by ineu** [deis/deis#3563]
https://github.com/deis/deis/blob/8e960ca203bd5d8c48e129c4172dd2b13cdc4439/store/gateway/bin/boot#L128-L132
https://github.com/deis/deis/blob/8e960ca203bd5d8c48e129c4172dd2b13cdc4439/registry/bin/boot#L89-L93
Both these components have the same problem: lock may expire between being checked and being updated. I see following in my logs:
```
Apr 23 18:46:24 staging-coreos-1 sh[31203]: + etcdctl --no-sync -C 192.168.0.1:4001 mk /deis/store/gateway/masterLock 192.168.0.1 --ttl 10
Apr 23 18:46:25 staging-coreos-1 sh[31203]: ++ etcdctl --no-sync -C 192.168.0.1:4001 get /deis/store/gateway/masterLock
Apr 23 18:46:25 staging-coreos-1 sh[31203]: + [[ 192.168.0.1 == \1\9\2\.\1\6\8\.\0\.\1 ]]
Apr 23 18:46:25 staging-coreos-1 sh[31203]: + etcdctl --no-sync -C 192.168.0.1:4001 set /deis/store/gateway/host 192.168.0.1 --ttl 10
Apr 23 18:46:26 staging-coreos-1 sh[31203]: + etcdctl --no-sync -C 192.168.0.1:4001 set /deis/store/gateway/port 8888 --ttl 10
Apr 23 18:46:27 staging-coreos-1 sh[31203]: + etcdctl --no-sync -C 192.168.0.1:4001 update /deis/store/gateway/masterLock 192.168.0.1 --ttl 10
Apr 23 18:46:28 staging-coreos-1 sh[31203]: Error:  100: Key not found (/deis/store/gateway/masterLock) [78855932]
```
So from the moment masterLock was checked to the moment it was updated 4 seconds pass. With default TTL of 10 seconds this means that update will fail frequently.

**Comment by carmstrong** [comment]
Good find. A few people have reported seeing this, and we weren't sure what was up.

**Comment by bacongobbler** [comment]
@ineu which version and platform are you running this on? I'd like to try re-create this issue if possible.

**Comment by ineu** [comment]
@bacongobbler 1.5.1, bare metal.
