### ISSUE TITLE
bug(deisctl): are some services started twice?

### ISSUE THREAD

**Issue by krancour** [deis/deis#3569]
Maybe I am reading this wrong, but lines 186 - 189 look like they're, functionally, a duplicate of what follows on lines 191 - 203.

https://github.com/deis/deis/blob/master/deisctl/cmd/cmd.go#L186-L203

**Comment by carmstrong** [comment]
It's confusing (and there should probably be a comment there), but I think that's intentional. We kick them all off in the background so they start more quickly, then we wait for them individually in the later blocks. The starts themselves are idempotent, as they're already running.

**Comment by bacongobbler** [comment]
Yep, that was intentional. For some reason the old comment got removed: https://github.com/deis/deis/commit/e4492f14a2f4d968eb2b61743a8d15d2fa11918a#diff-b969dcfd7599375f524fa76c72a1817dR144

**Comment by krancour** [comment]
Thanks for the clarification.  Closing.
