### ISSUE TITLE
Deis elements should use etcd2's permission resources

### ISSUE THREAD

**Issue by sitya** [deis/deis#3572]
The problem is still with us, that all etcd can be read by any container. We have already talked about defending strategies by using certificates (#3201) and/or using firewall, but I think the best way could be using [etcd2's permission resources](https://github.com/coreos/etcd/blob/master/Documentation/security_api.md). Yes, first it has to come to CoreOS stable channel, but it is possible to prepare :) I think there should be a `deis user` used by only `deis-*` containers and the `/deis` folder could be read only by this user.  I think this is a pretty easy solution to defend sensitive data stored in etcd (like applications specific private ssl keys).

**Comment by bacongobbler** [comment]
What's stopping attackers from adding a `USER deis` entry in their own Dockerfile apps and calling their app name `deis-*`? Would that defeat the purpose?

I think the better way would be to somehow inject secrets into the core components via something like the Docker Vault (PR 10310 on docker/docker) which we can then use to gain access to etcd.

**Comment by sitya** [comment]
> What's stopping attackers from adding a USER deis entry in their own Dockerfile apps and calling their app name deis-*? 

The password belongs to deis user.

**Comment by carmstrong** [comment]
@gabrtv what do you think about this? etcd2 is coming down the pike, so this is something we could consider.

**Comment by Joshua-Anderson** [comment]
ETCD 2 has landed now, so this could theoretically be implemented now.

**Comment by bacongobbler** [comment]
etcd will be going away in v2 and we won't be able to get to this for the LTS release so I'm going to close this, but thank you very much for posting this :)
