### ISSUE TITLE
builder: Rewrite in Go to be more reliable and more testable

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3578]
The builder component is notoriously fragile, and has many associated issues, including:
- #3317 
- #3249
- #1772 
- #2980
- #3078

Part of this is due to the fragility of the scripts themselves, but it's also because we cannot write unit tests for the builder component. We need to prioritize rewriting the component in Go so it's something that can be more easily maintained moving forward.

**Comment by bacongobbler** [comment]
+1

**Comment by bacongobbler** [comment]
#3684 helps a bit with this. To be clear, I think that the core part of builder (the script that is run when a commit is received) would definitely benefit from a re-factor. *However*, `gitreceive` or re-implementing a git server in Go is fruitless. `openssh`/`gitreceive` seems to handle that quite well.

**Comment by carmstrong** [comment]
> However, gitreceive or re-implementing a git server in Go is fruitless.

I think that's perfectly reasonable. In my mind, the goals of a builder refactor are twofold:
* Make the codebase less fragile and easier to maintain (many bug fix attempts have resulted in regressions)
* Add test coverage to gain confidence in changes

Having the builder in Go is secondary to both of these primary motivations.

Both of those can be achieved without a new git server. :+1:

**Comment by carmstrong** [comment]
closing in favor of #3758
