### ISSUE TITLE
deis-database: create_bucket failed after upgrading platform

### ISSUE THREAD

**Issue by ngpestelos** [deis/deis#3595]
http://imgur.com/jWrw6vy

**Comment by carmstrong** [comment]
@ngpestelos It sounds like you're missing some etcd keys. What do `deisctl list` and `etcdctl ls --recursive /` look like?

**Comment by ngpestelos** [comment]
Hi, @carmstrong.

http://imgur.com/4RZv3BS

**Comment by carmstrong** [comment]
@ngpestelos Unfortunately that is incomplete. Can you post a gist?

**Comment by ngpestelos** [comment]
Sorry about that, @carmstrong. Here you go: https://gist.github.com/ngpestelos/f472fb9f9b7aa2e443ec

**Comment by carmstrong** [comment]
@ngpestelos Can you post the original post as a text gist instead of a screenshot? I think those are getting cut off too.

**Comment by ngpestelos** [comment]
@carmstrong https://gist.github.com/ngpestelos/16839f522298349717cf

**Comment by bacongobbler** [comment]
@ngpestelos have you been able to see this on v1.6? We pushed a fix that may have transparently resolved this issue.

**Comment by mboersma** [comment]
I'm closing this since it hasn't seen activity in six weeks and the `create_bucket` issue is likely fixed in Deis v1.6 and later. Please re-open it or create a new issue if this recurs.
