### ISSUE TITLE
Expose nginx 'gunzip' configuration via etcd key (for Deis Router)

### ISSUE THREAD

**Issue by davidlmorton** [deis/deis#3600]
While it is currently possible to set a number of nginx configuration values via etcd, it isn't possible to set 'gunzip' in this way.  The 'gunzip' option controls decompression (of the request body) for nginx, not the compression (of the response body) which is set by 'gzip'.  

It would be nice to expose all of the nginx configuration settings in this manner if possible, instead of whitelisting a handful of them.

**Comment by aledbf** [comment]
@davidlmorton from the nginx docs (http://nginx.org/en/docs/http/ngx_http_gunzip_module.html) what you are asking is not possible

> The 'gunzip' option controls decompression (of the request body)

```
gunzip on;
Enables or disables decompression of gzipped responses for clients that lack gzip support
```

**Comment by davidlmorton** [comment]
I misunderstood the option, closing this issue.
