### ISSUE TITLE
is running without wildcard sub domain possible?

### ISSUE THREAD

**Issue by FreakinaBox** [deis/deis#3601]
My corporate environment wont let me dedicate a sub domain to deis.
Is it possible to bypass this requirement by creating individual DNS records for each required url?
If so what urls in a sub domain does deis use other than applications i create?

**Comment by bacongobbler** [comment]
Sure. Like you said you can create individual DNS records for each required URL. THe only one that you'd need otherwise is the `deis.` subdomain to communicate with the controller.

**Comment by FreakinaBox** [comment]
does deis use the deis sub domain itself or is that only for me to connect to the controller? I am wondering if setting the deis controller url in my local hosts file will work.

**Comment by bacongobbler** [comment]
internally we're just using the private IP addresses of the hosts, so the subdomain is not a hard requirement. :)

**Comment by FreakinaBox** [comment]
Thanks for the help!
