### ISSUE TITLE
config:set k=v with non-validating SSL doesn't work

### ISSUE THREAD

**Issue by haf** [deis/deis#3602]
I upgraded the cluster to v1.5.2 and I'm having trouble getting config:set to work. Previously I have set config successfully, but now I've enabled force https after getting the bugfix for that.

Unfortunately I didn't want to pay for a star-cert this time, so the cert is for the top-domain, not deis.topdomain.com. Still, it's better than no security and besides the domain, the cert is fine.

So I do `ssl_verify: false` in `~/.deis/client.json`.

Now I try to set a config setting:

```
$ deis config:set S3_SECRET_ACCESS_KEY=use-your-own-key
Creating config... /var/folders/j7/wbmqw81j2_jcfwn6_hh0ltlh4zjfkz/T/_MEI3XynoY/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
200 OK
{u'updated': u'2015-04-01T16:06:38UTC', u'uuid': u'5cf31ce1-1130-4fac-97e6-2532428b16c4', u'tags': {}, u'app': u'app-com', u'created': u'2015-04-01T16:06:38UTC', u'values': { cut to save the innocent }, u'memory': {}, u'owner': u'haf', u'cpu': {}}
```

Now that's strange. Nor does `config:list` doesn't show the new config.

I had a look at the [code](https://github.com/deis/deis/blob/v1.5.2/client/deis.py#L1169-L1185):

``` python
        body = {'values': json.dumps(values)}
        sys.stdout.write('Creating config... ')
        sys.stdout.flush()
        try:
            progress = TextProgress()
            progress.start()
            response = self._dispatch('post', "/v1/apps/{}/config".format(app), json.dumps(body))
        finally:
            progress.cancel()
            progress.join()
        if response.status_code == requests.codes.created:
            version = response.headers['x-deis-release']
            self._logger.info("done, v{}\n".format(version)) # this isn't printed
            config = response.json()
            values = config['values']
            self._logger.info("=== {}".format(app)) # this is printed
            items = values.items()
```

But I can't seem to find how that can go wrong. Does the invalid cert-warning interfere with the POST somehow? In that case, it's probably inside the `self._dispatch` method or children.

As a side-issue; perhaps you could make the ssl_verify non-binary? To accept other well-defined (configured) Host headers, but not accept other issues: self-signed, no cert-chain, invalid cert-chain, cert-chain references cert not in root store, SHA1-hashes used instead of >=SHA2, OCSP failure, CRL failure, invalid signatures, invalid handshakes, client-server handshake algorithm mismatch and so on. 

The scary-looking error message above should really show if I'm using *no encryption*, both on 'login' and usage of the app.

I have verified it's a TLS-client issue by removing security and posting the passwords in plain text over the internets, and then Deis accepts them without complaints. NSA shall be happy to know this ;)

**Comment by bacongobbler** [comment]
> As a side-issue; perhaps you could make the ssl_verify non-binary?

This is just a hook into python-requests which doesn't give you any other option than "ssl_verify on or off", so I'd see if they'd entertain that idea and we can hook into that.

> Now that's strange. Nor does config:list doesn't show the new config.

While it looks like it didn't show the expected message, it looks like the config was set properly. If it actually was an error, the response would have been a non-200 error. The response data from the controller seems fine too.

For reference, the [latest integration tests](https://ci.deis.io/job/test-ec2/750/console) shows that config:set seems to work, so if it's something to do with using self-signed certs with the client then that might explain things, but asides from ugly formatting errors everything seems normal to me.

> The scary-looking error message above should really show if I'm using no encryption, both on 'login' and usage of the app.

That's a valid point. Mind making a PR to display a warning when you've disabled SSL verification?

**Comment by mboersma** [comment]
This could be fixed by #3532 which is in master. Could you try by using a newer client from master? Otherwise that will be in our next release v1.6.

**Comment by haf** [comment]
@bacongobbler You state that *it looks like the config was set properly*; may I ask how you can say that?

If that was the case, wouldn't `config:list` show the set value?

And by browsing your integration tests, I can't see the error from pyrequests that the bad behaviour might be based around.

@mboersma It might, yes. Is it the same -sh script to run like when installing it but with `master` tucked at the end?

**Comment by bacongobbler** [comment]
@haf we just released v1.6. Could you please try that? :)

**Comment by carmstrong** [comment]
@haf Deis v1.6.0 has been released - try upgrading to the latest release and let you know if you still run into this. Thanks!

**Comment by mboersma** [comment]
Between #3532 and #3712, I think it's likely this issue is fixed. @haf if you could try the newer Deis v1.7.3 client in this scenario, please let us know if your case is still problematic.
```console
$  curl -sSL http://deis.io/deis-cli/install.sh | sh
```

**Comment by haf** [comment]
I'm afraid I won't be using this software until it's production safe and doesn't kill the servers when disk runs out. (And the 25 minute deploys need to be fixed too)

**Comment by mboersma** [comment]
Thanks, we're trying to harden and improve Deis every day. Please make sure there are GitHub issues tracking your specific problems so we can address them.

**Comment by carmstrong** [comment]
> Please make sure there are GitHub issues tracking your specific problems so we can address them.

In addition, we'd love to have you in our roadmap planning meetings to make sure we're held accountable for resolving these issues, @haf! Details are here: http://docs.deis.io/en/latest/roadmap/planning/#release-planning-meetings

**Comment by haf** [comment]
I've sent an e-mail to Gabriel about this.
