### ISSUE TITLE
Custom security group rules block Ceph; deis-store-gateway@1 fails

### ISSUE THREAD

**Issue by zxcvbn97** [deis/deis#3604]
I'm using deis 1.5.2 and getting this error. PLease help.

Apr 30 16:54:46 m sh[10809]: 2015-04-30 21:54:46.851843 7fd44827c700  0 -- :/1000027 >> 131.xxx.xxx.xxx:6789/0 pipe(0x7fd430003040 sd=5 :0 s=1 pgs=0 cs=0 l=1 c=0x7fd43000fd60).fault
Apr 30 16:54:46 m sh[10810]: Waiting for ceph gateway on 8888/tcp...
Apr 30 16:54:46 m sh[10810]: curl: (56) Recv failure: Connection reset by peer
Apr 30 16:54:47 m sh[10810]: Waiting for ceph gateway on 8888/tcp...
Apr 30 16:54:47 m sh[10810]: curl: (56) Recv failure: Connection reset by peer

**Comment by bacongobbler** [comment]
does restarting `store-daemon` resolve the issue for you? Sounds like a duplicate of https://github.com/deis/deis/issues/2878

**Comment by zxcvbn97** [comment]
No, i still having the same issue. What info do you need to debug?

**Comment by pdhar-tibco** [comment]
I have the same experience on non-vagrant 3 node deis cluster. etcd + fleet is up.
####################################################################
WARNING: fleetctl (0.9.1) is older than the latest registered
version of fleet found in the cluster (0.9.2). You are strongly
recommended to upgrade fleetctl to prevent incompatibility issues.
####################################################################
MACHINE		IP		METADATA
23cc306d...	172.17.8.102	-
488a79de...	172.17.8.101	-
78ca936f...	172.17.8.100	-
---------
See Gist:https://gist.github.com/pdhar-tibco/cf9d204fb138099a41b3

**Comment by zxcvbn97** [comment]
It seems like deis does not know how to connect to my machines.
I'm not using FQDN hostnames

root@102baefb23f9:/app# ceph -s
server name not found: machine1 (Name or service not known)
unable to parse addrs in 'machine1,machine2'
Error connecting to cluster: Error

**Comment by zxcvbn97** [comment]
I'm seeing inconsistent image versions in my deis deployment.
Is there anyway to completely uninstall deis and start from fresh or force image version? 
I tried delete deis images then run deis install platform again, but I'm still seeing the inconsistent images

deis/store-daemon                               v1.5.2              5f3e8e99a810        8 days ago          309.4 MB
deis/store-admin                                v1.5.2              826574a67cbc        8 days ago          309.4 MB
ubuntu-debootstrap                              14.04               f798ea50fc89        9 days ago          87.02 MB
deis/store-monitor                              v1.5.0              c16b4c3cb00e        3 weeks ago         309.4 MB
deis/store-metadata                             v1.5.0              96c05985ecf1        3 weeks ago         309.4 MB
deis/store-gateway                              v1.5.0              84dbc03b9382        3 weeks ago         323.9 MB
deis/store-daemon                               v1.5.0              79a118002929        3 weeks ago         309.4 MB

**Comment by sklose** [comment]
I have the same problem, "deisctl start platform" hangs at deis-store-gatewat@1.service activating/start-post". I installed store-monitor and checked the status of ceph. The error message is: 10.61.11.197:6789/0 pipe(0x7fa560000c00 sd=4 :0 s=1 pgs=0 cs=0 l=1 c=0x7fa560000e90).fault

I am setting up a 1.5.2 cluster from scratch, I retried several times, but everytime I get the same error.

**Comment by bacongobbler** [comment]
Hmm... if you follow http://docs.deis.io/en/latest/troubleshooting_deis/troubleshooting-store/, is there anything else interesting that stands out?

**Comment by bacongobbler** [comment]
@zxcvbn97 try `deisctl config platform set version=v1.5.2`

**Comment by sklose** [comment]
I finally found the issue ... my security groups in AWS blocked traffic between instances, I had only opened the ports for CoreOS. Is there a list of ports required for DEIS to work? For now I allow all traffic on all ports between all instances in my clusters, I'd like to restrict that to the required ports.

**Comment by carmstrong** [comment]
> Is there a list of ports required for DEIS to work? For now I allow all traffic on all ports between all instances in my clusters, I'd like to restrict that to the required ports.

I don't think such a list exists - there are a dozen or so ports that I can think of: 4001, 7001, 22, 2222, 80, 6789, 6800-6810 or so (for Ceph services), but then deployed applications will bind to ports that are assigned by the Docker daemon. I'm not sure you can get away with restricting traffic.

**Comment by carmstrong** [comment]
@zxcvbn97 Are you still having issues? What platform are you on? Your Ceph error makes me think that the machines were not deployed correctly, with resolvable hostnames and public/private IP addresses.

**Comment by bacongobbler** [comment]
> but then deployed applications will bind to ports that are assigned by the Docker daemon.

Those use the ephemeral port range :) http://www.ncftp.com/ncftpd/doc/misc/ephemeral_ports.html

**Comment by carmstrong** [comment]
> Those use the ephemeral port range :)

Sure, which is a huge range - it kind of defeats the purpose when you have to allow a few thousand ports.

**Comment by zxcvbn97** [comment]
I'm using bare metal. I'm seeing this: 2015-04-30 21:54:46.851843 7fd44827c700 0 -- :/1000027 >> 131.xxx.xxx.xxx:6789/0 pipe(0x7fd430003040 sd=5 :0 s=1 pgs=0 cs=0 l=1 c=0x7fd43000fd60).fault

**Comment by carmstrong** [comment]
@zxcvbn97 That means the daemons are unable to communicate with the monitors. Are you sure you've opened up firewall rules?

**Comment by zxcvbn97** [comment]
I still have the same problem. The machines are assigned a network 220.154.xxx.xxx.
I read that on bare metal deis requires a specific IP ranges. Is there anyway to bypass this requirement? 

"Due to changes introduced in Docker 1.3.1 related to insecure Docker registries, the hosts running Deis must be able to communicate via a private network in one of the RFC 1918 or RFC 6598 private address spaces: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, or 100.64.0.0/10."
http://docs.deis.io/en/latest/installing_deis/baremetal/#check-system-requirements

**Comment by carmstrong** [comment]
> Is there anyway to bypass this requirement?

Machines will need both public and private IPs, and the private interface should be in that range. If not, you'll need to change the cloud-config here: https://github.com/deis/deis/blob/4de2c904f35c2a4862d6ed0791581ea7bb3b8912/contrib/coreos/user-data.example#L102

And you'll need to build a custom builder component with the change here: https://github.com/deis/deis/blob/4de2c904f35c2a4862d6ed0791581ea7bb3b8912/builder/image/bin/boot#L68
