### ISSUE TITLE
deisctl start platform stuck at deis-store-gateway@1.service: activating/start-post

### ISSUE THREAD

**Issue by pdhar-tibco** [deis/deis#3608]
I am using a  non-vagrant 3 node deis vbox cluster. 
etcd + fleet is up.
####################################################################
WARNING: fleetctl (0.9.1) is older than the latest registered
version of fleet found in the cluster (0.9.2). You are strongly
recommended to upgrade fleetctl to prevent incompatibility issues.
####################################################################
MACHINE IP METADATA
23cc306d... 172.17.8.102 -
488a79de... 172.17.8.101 -
78ca936f... 172.17.8.100 -

See Gist:https://gist.github.com/pdhar-tibco/cf9d204fb138099a41b3

**Comment by zxcvbn97** [comment]
+1 . I'm having the same issue.

**Comment by carmstrong** [comment]
@pdhar-tibco From your logs, it looks like the Ceph services are unable to communicate with one another.

> I am using a non-vagrant 3 node deis vbox cluster.

Can you explain exactly how you provisioned these machines? At first guess, I would suspect that they are unable to communicate with each other on the Ceph ports.

**Comment by pdhar-tibco** [comment]
I am trying closely to do what vagrant does while configuring the virtualbox paravirtualized network i.e. VBoxNet2 .
After installing the coreos manually , I update the /etc/environment to fill in the public_ipv4  values so that etcd,fleetd can see the other nodes in the cluster.
Upto this point it works. I can install the deis platform. It is a different problem when I want to start it and it blocks after a few steps as mentioned in the subject.

I understand Vagrant makes the job easier by doing many things behind the scenes. I was going by the knowledge that if I provision the nodes and the network 
in the same manner I should be able to run deis.

- Pranab

**Comment by mboersma** [comment]
I'm closing this since it hasn't had any activity in six weeks and a manual install of CoreOS on VirtualBox directly isn't something Deis supports. My apologies @pdhar-tibco, please re-open this or create a new issue if you're able to try again with Vagrant and [Deis v1.7.3](https://github.com/deis/deis/releases).
