### ISSUE TITLE
Q: safe way to re-run cloud-init on existing machine?

### ISSUE THREAD

**Issue by haf** [deis/deis#3610]
What is the recommended way to re-run cloud-init on a deis cluster member? I want to add https://raw.githubusercontent.com/ianblenke/coreos-vagrant-kitchen-sink/d8f3b5dc17831148449c351068a374bc9fef5a0f/tested/blackhole.cloud-init to the node (-- and it should probably be the default from a logging-verbosity standpoint).

**Comment by bacongobbler** [comment]
You may want to ask github.com/coreos/coreos-cloudinit about that, but I think you can try using the `--from-file` option.
