### ISSUE TITLE
deis domains:add does not work and other problems "Welcome to nginx!"

### ISSUE THREAD

**Issue by kingdonb** [deis/deis#3614]
I am operating under the assumption this is all one bug, but manifest in several different ways...

The first thing I noticed was that adding a domain to my app does not work.  I visit the domain and I get "Welcome to nginx!"

I should tell you that when I brought the cluster up, I was preparing a replacement for a broken cluster that lost quorum and could not add new apps anymore (both clusters are named "deis") so when the new cluster finished coming up with 5 nodes, I had not finished setting up DNS and `*.deis` was still aimed at the old cluster.  I set one of the new nodes in my /etc/hosts to resolve as `deis`, `deis.deis`, `myapp1.deis`, and `myapp2.deis` for testing purposes, registered a new user, and launched my apps preparing for a zero-downtime live migration.

Nothing here did seem like a show-stopper, and I didn't notice the domains issue until I had already cut over DNS, so I went on using my cluster.

I've now added 3 nodes (6,7,8) and removed 3 nodes (1,2,3) from the cluster, following the instructions to clean up their store daemons and monitors; `ceph -s` healthy looks fine, turning the spare machines off and letting apps move back onto the big iron that was my old cluster, now decommissioned and reborn as new-cluster nodes 6, 7, 8.  That went fine, some apps were running on the removed nodes, they came up fine on the new nodes on their own.

I watched one app that was only running on node 1 come back up on another node and the gateway correctly routes requests for that app to its new home.  Great!

But one of my apps that moved homes is no longer accessible.  I just get a 404 from nginx.  I tried destroying the app and recreating it with the same name, no dice.  "Welcome to nginx!" it says now.

Finally I created the app again with a different name, and at that URL (reporter2.deis) I am getting 503.  

In fact it looks like my cluster is not accepting any new apps now.  They deploy with no errors, no errors in the apps' logs, but 503s all around.

I just noticed that I forgot to update my `*.deis` record, I've fixed it now to only point to active hosts, but it didn't help; is there a wrong time and a right time to configure DNS, or does this have nothing at all to do with my 503s?

The only thing I can think of is, I didn't `mds rm` my metadatas, there is a note about this being undocumented at the bottom of: http://docs.deis.io/en/latest/managing_deis/add_remove_host/ which strongly infers that you don't need to remove them manually and it's fine to just 'down' the host once you get to this point.  I've been through some journals in fleetctl and nothing is jumping out at me, but if there's one I can take a closer look at, let me know.

**Comment by carmstrong** [comment]
@kingdonb DNS shouldn't cause 503s or anything like that, and can be changed at any time. It only affects accessibility of your apps. 

Can you provide logs from your router components? You could also investigate the router configuration directly to see if it has your application defined. You can do this by SSHing into a host that runs a router and `nse deis-router` to enter the container. Then, inspect `/opt/nginx/conf/nginx.conf`.

**Comment by yebyen** [comment]
OK, inspecting /opt/nginx/conf/nginx.conf revealed a lot:

1) my broken apps/domains are actually configured to return 503:

    server {
        server_name ~^preset-eggplant\.(?<domain>.+)$;
        include deis.conf;

        
        location / {
            return 503;
        }
        
        
    }
    server {
        server_name ~^reporter2\.(?<domain>.+)$;
        include deis.conf;

        
        location / {
            return 503;
        }
        
        
    }

... it looks like they were never set up completely, I guess.  My living domains have a lot more than this.  Could this happen because many of my nodes came online some time after the initial `deisctl install platform`?  I've been experimenting with adding/removing nodes as I mentioned.

And,

2) I misunderstood how the domains:add tool is supposed to work.  I had assumed that adding a bare domain with no TLD would result in `yourbaredomain.domain` being assigned to the app, as in `deisctl config platform set domain=domain`.  Looking at the config provided me with the "duh" moment -- why would you want that, I understand now that `domains:add` is meant to take a FQDN.  I'm not sure how I came to believe it worked this way, "I swear it worked like that when I tried it before".

So, if you can tell me under what conditions `deis apps:create` should leave a 503 in the config like I have shown above in (1), we'll be at the meat of this issue report and hopefully we can fix something.

**Comment by yebyen** [comment]
I pulled the logs from journal on my deis-router@*.service

One of them reads like a lot of this:

    May 05 13:36:03 hp-01 sh[2604]: [WARNING] - 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

The other two seem to be normal.  The configs for all three have the same issue with hardcoded 503s for all of my new apps.

**Comment by carmstrong** [comment]
@yebyen That error means that etcd is likely having issues on that host - `journalctl -fu etcd` to confirm.

Your issue shouldn't have anything to do with router configuration. The router template is here: https://github.com/deis/deis/blob/f08e9b0a87ae8fcd2b5d4dd208e75b8269143243/router/image/templates/nginx.conf#L161-L241

Note that seeing simply a 
```
    location / {
        return 503;
    }
```

means that there are no active upstreams for that app - I'd inspect `deis ps` for your application and ensure that you've `deis scale`d up appropriately.

**Comment by yebyen** [comment]
Hmm.  It's possible that a bad etcd on one host could have done that?

I am sure I had processes running, but with debugging and other things I did wind up critically wounding my cluster, just finished rebuilding it and I'm able to build and create apps again.

So, nothing left to debug for now, closing.

**Comment by kingdonb** [comment]
(Closing)
