### ISSUE TITLE
Unable to push a new app in vagrant

### ISSUE THREAD

**Issue by ngpestelos** [deis/deis#3616]
I was able to set `/deis/platform/sshPrivateKey`, but when I tried to push `example-ruby-sinatra` to my local cluster, it failed with `Permission denied (publickey).`.

I also did a `ssh-add ~/.vagrant.d/insecure_private_key` before pushing my app.

I then restarted deis-builder but without luck.

**Comment by deepy** [comment]
I've personally earlier today followed the instructions step for step and set up vagrant with deis, your issue did not affect me, did you perhaps miss some step?
I'm on master at f4c2a241530522d0d612fe3448bf9309d2c7927f.

**Comment by bacongobbler** [comment]
@ngpestelos did you run `deis keys:add`?

**Comment by mboersma** [comment]
Any update on this `Permission denied (publickey)` issue? This usually means `deis keys:add` wasn't run, or that the key added isn't available to the client with `ssh-add ~/.ssh/privkey`.

**Comment by mboersma** [comment]
I'm going to close this since it hasn't had any updated activity in a couple weeks. Please re-open if there is still an issue here that Deis should fix.

**Comment by ngpestelos** [comment]
OK, thank you.
