### ISSUE TITLE
Registry Should be URL based, not IP

### ISSUE THREAD

**Issue by jwaldrip** [deis/deis#3619]
Why doesn't the registry mount on a domain?

i.e. registry.mycluster.com

**Comment by bacongobbler** [comment]
So then users remote to the cluster won't be able to pull your app images and view your database credentials you set up with `deis config:set`. :)

related #2680

**Comment by jwaldrip** [comment]
What port does the registry run on? Couldn't this be changed to run on a different port that could be protected from the interwebs?

**Comment by bacongobbler** [comment]
Not to mention pushing a malicious image via 

```
docker tag myapp-cracked registry.mycluster.com/myapp-production:v2
docker push registry.mycluster.com/myapp-production:v2
deis ps:restart -a myapp-production
```

:trollface:

**Comment by bacongobbler** [comment]
> Couldn't this be changed to run on a different port that could be protected from the interwebs?

DigitalOcean, Rackspace and other cloud providers have every port exposed by default so this is not something that we can effectively "protect" unless we started "officially" supporting the [firewall script](https://github.com/deis/deis/blob/master/contrib/util/custom-firewall.sh) in `contrib`.

The other reason why we don't have a URL rather than just IP addresses is because of a lack of internal DNS discovery in Deis. See #3072

**Comment by johanneswuerbach** [comment]
Using an URL would also mean all traffic flows through your routers, which is also not what you would want.

**Comment by smothiki** [comment]
@bacongobbler we didn't hit any use case with Fleet node failover  that has registry, as the systemD unit file dynamically  gets the registry Ip and Port and appends image to it. This is not the case with other schedulers like swarm, kubernetes or Marathon. We have to specify image at the time of creation and its static.
 For Example, registry IP and port are (172.17.8.100:5000) app image X at the time of creation will be 172.17.8.100:5000/X and node that has registry failed and scheduler started registry on different node and Ip changed to 172.17.8.101. Now the schedulers will try to reschedule the apps on the failed node by pulling image from 172.17.8.100:5000 but not 172.17.8.101:5000.

This is something we need to address in the future and movign to URL based Registry is one of the solutions

**Comment by krancour** [comment]
@smothiki when a `deis-registry` container is rescheduled to another host, it will update the value of the `/deis/registry/host` key.  The situation in your example where other rescheduled work attempts to pull from the failed registry could happen, but it will fail.  Units are configured to restart upon failure.  Eventually the new registry will come up and will have updated etcd accordingly and things will move forward without any trouble.

**Comment by smothiki** [comment]
@krancour it works only with fleet-units template which generates gets created whenever fleet reschedules them. But with swarm,kubernetes pod templates and other schedulers [swarm.py](https://github.com/deis/deis/blob/master/controller/scheduler/swarm.py#L25-L35) we have to give image during the creation of container and they try to pull the same image even the registry changed it static creation. where as fleet units gets crated dynamically [fleet.py](https://github.com/deis/deis/blob/master/controller/scheduler/fleet.py#L382) whenever rescheduling happens and they get updated with registry

**Comment by krancour** [comment]
@smothiki, I may have misunderstood what you were saying.  I understand now.  Sorry for the confusion.

**Comment by bacongobbler** [comment]
related: #3072

**Comment by bacongobbler** [comment]
closing as the original question has been answered, and @smothiki's concerns have been addressed in v2 via kubernetes services.
