### ISSUE TITLE
Proposal: Make Deis compatible with large-scale, production cluster architecture

### ISSUE THREAD

**Issue by krancour** [deis/deis#3635]
Apologies... this is long and detailed, but (I think) comprehensive...

Because building etcd consensus can be time-consuming when the number of nodes in an etcd cluster is large, CoreOS recommends the following architecture for production and/or large scale deployments:

https://coreos.com/docs/cluster-management/setup/cluster-architectures/#production-cluster-with-central-services

In such an architecture, only a small, fixed number of nodes run etcd while all other nodes (an elastic pool of "workers") are merely configured with a list of etcd peers they can speak to.

Unfortunately, Deis doesn't play nicely with this cluster architecture fresh out of the box because Deis components generally expect that etcd is running locally.  Some components allow you to configure your way around this on some level, but generally do not go far enough in that regard.

Ultimately, I have overcome these challenges, but it required quite a significant investment in customizing images and unit files.  That's not tenable in the long-term for operators who wish to upgrade Deis frequently and don't want to have to re-apply their customizations with each release.

Here, I want to enumerate the few issues that comprise this (each on its own is pretty minor) and then propose a simple solution, which I would be happy to work on.

The following components are those that would run on worker nodes without etcd running locally:

* `deis-logspout`
* `deis-publisher`
* Arguably, `deis-router` (since it may need to scale significantly)
* Applications

Issues arising on such worker nodes:

1. `deis-logspout` and `deis-publisher`'s unit files require `etcd.service`.  This imposes a constraint that etcd be running locally.

2.  `get_image` script (and raw `etcdctl`) don't work from within unit files-- this can interfere with resolving custom image names for `deis-logspout`, `deis-publisher`, and `deis-router` (if applicable).  In the case of applications (with unit files created by `deis-controller`), image names cannot be resolved at all.

3. Most components (their containers) can be passed an `ETCD_HOST` environment variable that will allow them to speak to a remote etcd.  This is good, but does not go far enough.  It creates a single point of failure on that one host and also means unit files need to be modified to assign a specific IP address to the `ETCD_HOST` environment variable.  That sort of customization-per-cluster is something we should want to avoid.

4. `MachineMetadata` that articulates a Deis component's assignment to a "common services" node vs. a "worker" node isn't present in existing component unit files.  For an application, it's present only if explicitly added via `deis tags:set`.

Here are simple solutions to each of these, in turn:

1. `deis-logsout`, `deis-publisher`'s unit files can be modified to "want" `etcd.service` instead of requiring it.  etcd's absence from a system will no longer be an issue, but on systems where `etcd` _is_ scheduled, it will still come up first.  (`After` clause would not be touched.)

2. The `ETCDCTL_PEERS` environment variable can be used anywhere `etcdctl` is installed to tell etcdctl to use that list of peers instead of assuming etcd is running locally.  I've seen this work brilliantly on worker nodes.  I inject this into the environment using `cloud-config` and a custom `/etc/profile.d/etcdctl.sh`.  The trouble is that this only helps a logged in user.  The value isn't visible to systemd.  That can be changed, however, by using the same strategy (`cloud-config`) to _optionally_ inject `ETCDCTL_PEERS` into the `/etc/environment` file where Deis components' unit files already source environment variables from today.  The unit files for applications would need to be modified to include `EnvironmentFile=/etc/environment` as well-- they do not currently.  Once this is set, `etcdctl` and the Deis `get_image` script will begin working within unit files on machines where etcd is not running.

3. As stated before, it is `deis-logspout`, `deis-publisher`, and `deis-router` that are most affected by this.  With `ETCDCTL_PEERS` environment variable (potentially) set via no. 2 above, this environment variable can also be passed to each of those components using `-e ETCD_PEERS=$ETCDCTL_PEERS`.  Only slight modifications would be required to the Go code for each of those components to make them prefer the list of etcd peers mentioned by `ETCD_PEERS` (if set) over the singular etcd host that might otherwise be mentioned by `ETCD_HOST`.

4. fleet assigns each unit to nodes that match _any_ (not all) of the `MachineMetadata` constraints.  As such, we could use the following for any unit that must run _only_ on "common services nodes":

```
[X-Fleet]
MachineMetadata="deisRole=general"
MachineMetadata="deisRole=control"
```

Or this for any unit that must run _only_ on worker nodes:

```
[X-Fleet]
MachineMetadata="deisRole=general"
MachineMetadata="deisRole=worker"
```

Existing example user-data (`cloud-config`) could be updated to assign a `deisRole` of `general` to all nodes.

With all these changes in play, the fresh-out-of-the-box experience for a novice operator on a  small cluster is not complicated or tarnished in any way.  For a more skilled operator wanting to run Deis on a larger, production cluster, `cloud-config` becomes a one-stop shop for partitioning their cluster into "common services" and "worker" nodes-- which is not a stretch because I believe most who are running (or want to run Deis) at any sort of scale are already doing custom things with their user-data /  `cloud-config`.

Does anyone have any thoughts on this?  I think it's a relatively simple and comprehensive approach.  If there are any gaping holes in it, I am eager to be called out on it!  :)

**Comment by krancour** [comment]
This is all easy enough, so I've started work on this so there's something concrete to discuss.

This branch currently has my WIP: https://github.com/krancour/deis/tree/large-cluster-compatibility

I'm going to put this to the test in a live cluster tomorrow.

MY biggest concern is no. 4 in the list.  While I wish there were a way to express something in a unit file like "this component can run where deisRole=work _or_ deisRole is undefined," but that doesn't seem to be possible, as far as I can tell.  This leaves me doing things like this in unit files:

```
[X-Fleet]
MachineMetadata="deisRole=general"
MachineMetadata="deisRole=worker"
```

The bad thing about that is that it possibly represents a breaking change whereby every node would _have to have_ a `deisRole` of `general`, `control`, or `worker`.  I've made appropriate modifications to example userdata, but this change possibly complicates the upgrade path, which I think is no bueno.

I'd love other options for no. 4 if anyone can think of anything.

**Comment by krancour** [comment]
Tested today...

So far, this is working very nicely on a cluster such as the one described here:

https://coreos.com/docs/cluster-management/setup/cluster-architectures/#production-cluster-with-central-services

I still want to test this against a more traditional cluster (where every node runs etcd) before I open any PR.  I want to be certain that the out-of-the-box install / launch experience for such a cluster is not tarnished in any way by these changes.  Should get to that tomorrow or possibly over the weekend.

**Comment by krancour** [comment]
Ok.  And I've now tested my modifications on a "traditionally" structured cluster (i.e. etcd running on every node) and provided that a `deisRole` of `general` is set in the cloud-config, the usual install / start workflow goes off without a hitch.

I feel like the next step is to provide additional provisioning options for each hosting platform that can create these sort of clusters.  For example, on EC2, this may call for a new Cloud Formation template that creates a fixed number of worker nodes with certain cloud-config in the userdata and an autoscaling group of worker nodes with _different_ cloud-config (to not start etcd and to enumerate etcd host addresses).

I don't have sufficient familiarity with all hosting platforms in contrib to tackle that.  It's also probably not worth tackling anyway until I hear some sort of buy-in on this approach.  I'll wait to hear from the maintainers on that , but at this point, at the very least, I think the approach is proven feasible.

**Comment by eMxyzptlk** [comment]
@krancour maybe split this into 2 PRs:

1.  Add support for this without metadata changes in the unit files, the `userdata`or the provisions script
2.  Work on the `userdata` and the provisions scripts.

**Comment by krancour** [comment]
@eMxyzptlk, I don't know how this could be accomplished without changes to machine metadata.  Tagging machines and units in a CoreOS cluster is how you ensure that certain work is scheduled to certain machines.

**Comment by eMxyzptlk** [comment]
Well for part 1, you don't really need that, it will just add support for it (for example adding `EnvironmentFile=/etc/environment` to all of the applications unit files). For part 2, if you default the `deisRole` to `general`, it should be enough for a starter.

**Comment by krancour** [comment]
@carmstrong some of your comments in #3023 answer at least one of my concerns-- seems I should _not_ bother with updated, provider-specific cloud-config, but address the few changes required to make this tenable via documentation updates.  Ping @sforsman.  If you've got documentation you were working on related to this, some of it may prove useful here.

**Comment by carmstrong** [comment]
> but address the few changes required to make this tenable via documentation updates

:+1: I think we can probably achieve a reasonable middle ground by adding documentation around this, and maybe a few smaller code changes.

**Comment by krancour** [comment]
The code changes I am accumulating are all very small.  I'm in final stages of testing and will open a PR soon.

**Comment by carmstrong** [comment]
> I'm in final stages of testing and will open a PR soon.

Sounds great!

**Comment by krancour** [comment]
Replaced by #4142
