### ISSUE TITLE
swarm scheduler does not expose $PORT to the container

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#3636]
Fleet exposes a $PORT envvar to the container for Heroku compatibility, but swarm does not. I notice that there's a function which inspects the container's exposed ports in swarm.py but we don't take advantage of that. I'd imagine that a few example apps may rely on this feature.

**Comment by smothiki** [comment]
Using Swarm scheduler Deis does a  kind of lazy pull where the image is pulled on a particular node when there is a create call on the node. So we dont have image to inspect the exposed ports. 
Reason for doing lazy pull is some images are very large and doing pull operation with swarm results in pulling on every node in the swarm cluster. We need to find a way to get exposed ports .

**Comment by bacongobbler** [comment]
Ah, maybe we don't even need this check any more now that we expose port 5000 for buildpacks. This check isn't even necessary. The original reason this came to be was due to attempting to fix #1156. Now it seems that this logic isn't necessary any more :)

https://github.com/deis/deis/blob/master/builder/image/slugrunner/Dockerfile#L10-L12
