### ISSUE TITLE
Ceph reports "too many PGs per OSD" in Deis 1.6

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3638]
In testing Deis 1.6, my cluster reports:

```
     health HEALTH_WARN
            too many PGs per OSD (1536 > max 300)
```

This seems to be a new warning in the Hammer release of Ceph, which we're shipping in Deis 1.6. This got me thinking - perhaps we aren't calculating placement group usage properly, and this is contributing to the various issues we're seeing with Ceph performance (particularly on platform start).

I posted a message to the Ceph mailing list asking for clarification: http://lists.ceph.com/pipermail/ceph-users-ceph.com/2015-May/001222.html

We're using the default 12 pools:
```
root at ca-deis-1:/# ceph osd lspools
0 rbd,1 data,2 metadata,3 .rgw.root,4 .rgw.control,5 .rgw,6 .rgw.gc,7 .users.uid,8 .users,9.rgw.buckets.index,10 .rgw.buckets,11 .rgw.buckets.extra,
```

So, I think the calculation is something like:
12 pools * 128 = 1536
12 pools * 32 = 384
12 pools * 16 = 192

It seems that the placement group documentation is unclear. If we should shoot for 300 PGs per OSD, then it seems like we should use a `pg_num` of 16, since even 32 would result in more than 300 per OSD.

However, if this computation is based on the resources of the host, it'll be harder to choose a default value.

**Comment by aledbf** [comment]
@carmstrong if you change `pg_num` you need to update `pgp_num` too
http://ceph.com/docs/master/rados/operations/pools/

**Comment by carmstrong** [comment]
> if you change pg_num you need to update pgp_num too

Yeah I know :) Just listed it as `pg_num` so this is easier to follow. We set them both together: https://github.com/deis/deis/blob/e6a078b4119887b4de73e8a6d04291b7cdeb823b/store/gateway/bin/boot#L40-L59

**Comment by carmstrong** [comment]
It sounds like we should indeed try lowering the number of PGs here, and shoot for 300/host. This may be useful: http://ceph.com/pgcalc/
