### ISSUE TITLE
fail to install deisctl 

### ISSUE THREAD

**Issue by ainux4mrvce** [deis/deis#3642]
cmd : curl -sSL http://deis.io/deisctl/install.sh | sudo sh -s 1.5.2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1572k  100 1572k    0     0  53036      0  0:00:30  0:00:30 --:--:--  100k
Verifying archive integrity... All good.
Uncompressing Deis Control Utility  100%  
Error: Get https://raw.githubusercontent.com/deis/deis/v1.5.2/deisctl/units/deis-builder.service: dial tcp: lookup raw.githubusercontent.com: no DNS servers

**Comment by bacongobbler** [comment]
Sounds like you don't have any DNS resolution set up. Try to add `nameserver 8.8.8.8` and `nameserver 8.8.4.4` to your `/etc/resolv.conf`.

**Comment by ainux4mrvce** [comment]
@bacongobbler  thankyou now its working

**Comment by bacongobbler** [comment]
no problem :)

**Comment by ainux4mrvce** [comment]
curl -sSL http://deis.io/deisctl/install.sh | sudo sh -s 1.5.2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1572k  100 1572k    0     0   245k      0  0:00:06  0:00:06 --:--:--  323k
Verifying archive integrity... All good.
Uncompressing Deis Control Utility  100%  
Refreshed deis-builder.service from v1.5.2
Refreshed deis-cache.service from v1.5.2
Refreshed deis-controller.service from v1.5.2
Refreshed deis-database.service from v1.5.2
Refreshed deis-logger.service from v1.5.2
Refreshed deis-logspout.service from v1.5.2
Refreshed deis-publisher.service from v1.5.2
Refreshed deis-registry.service from v1.5.2
Refreshed deis-router.service from v1.5.2
Refreshed deis-store-admin.service from v1.5.2
Refreshed deis-store-daemon.service from v1.5.2
Refreshed deis-store-gateway.service from v1.5.2
Refreshed deis-store-metadata.service from v1.5.2
Refreshed deis-store-monitor.service from v1.5.2
Refreshed deis-store-volume.service from v1.5.2

deisctl is in the current directory and unit files are
in /home/mca/.deis/units. Please move deisctl to a
directory in your search PATH.

See http://docs.deis.io/ for documentation.

mca@mca:/bin$ sudo ln -fs $PWD/deisctl /usr/local/bin/deisctl
[sudo] password for mca: 
no talloc stackframe at ../source3/param/loadparm.c:4864, leaking memory
mca@mca:/bin$ sudo whoiam
sudo: whoiam: command not found
mca@mca:/bin$ whomi
No command 'whomi' found, did you mean:
 Command 'whom' from package 'nmh' (universe)
 Command 'whom' from package 'mailutils-mh' (universe)
 Command 'whoami' from package 'coreutils' (main)
whomi: command not found
mca@mca:/bin$ whoami 
mca
mca@mca:/bin$ sudo whoami 
root
mca@mca:/bin$ cd 
mca@mca:~$  apt-cache policy samba
samba:
  Installed: 2:4.1.6+dfsg-1ubuntu2.14.04.7
  Candidate: 2:4.1.6+dfsg-1ubuntu2.14.04.7
  Version table:
 *** 2:4.1.6+dfsg-1ubuntu2.14.04.7 0
        500 http://in.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     2:4.1.6+dfsg-1ubuntu2 0
        500 http://in.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
mca@mca:~$  apt-cache policy samba
samba:
  Installed: 2:4.1.6+dfsg-1ubuntu2.14.04.7
  Candidate: 2:4.1.6+dfsg-1ubuntu2.14.04.7
  Version table:
 *** 2:4.1.6+dfsg-1ubuntu2.14.04.7 0
        500 http://in.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     2:4.1.6+dfsg-1ubuntu2 0
        500 http://in.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
mca@mca:~$ 
mca@mca:~$ sudo uptime
 20:44:18 up 1 day,  1:56,  2 users,  load average: 0.15, 0.16, 0.14
mca@mca:~$ sudo ln -fs $PWD/deisctl /usr/local/bin/deisctl
mca@mca:~$ cd deis/
mca@mca:~/deis$ export DEIS_NUM_INSTANCES=3
mca@mca:~/deis$ make discovery-url && vagrant up
sed -e "s,# discovery:,discovery:," -e "s,discovery: https://discovery.etcd.io/.*,discovery: $(curl -s -w '\n' https://discovery.etcd.io/new)," contrib/coreos/user-data.example > contrib/coreos/user-data
Bringing machine 'deis-01' up with 'virtualbox' provider...
Bringing machine 'deis-02' up with 'virtualbox' provider...
Bringing machine 'deis-03' up with 'virtualbox' provider...
==> deis-01: Running triggers before up...
==> deis-01: Checking if box 'coreos-stable' is up to date...
==> deis-01: VirtualBox VM is already running.
==> deis-02: Running triggers before up...
==> deis-02: Checking if box 'coreos-stable' is up to date...
==> deis-02: VirtualBox VM is already running.
==> deis-03: Running triggers before up...
==> deis-03: Checking if box 'coreos-stable' is up to date...
==> deis-03: VirtualBox VM is already running.
mca@mca:~/deis$ vagrant halt
==> deis-03: Attempting graceful shutdown of VM...
==> deis-02: Attempting graceful shutdown of VM...
==> deis-01: Attempting graceful shutdown of VM...
mca@mca:~/deis$ make discovery-url && vagrant up
sed -e "s,# discovery:,discovery:," -e "s,discovery: https://discovery.etcd.io/.*,discovery: $(curl -s -w '\n' https://discovery.etcd.io/new)," contrib/coreos/user-data.example > contrib/coreos/user-data
Bringing machine 'deis-01' up with 'virtualbox' provider...
Bringing machine 'deis-02' up with 'virtualbox' provider...
Bringing machine 'deis-03' up with 'virtualbox' provider...
==> deis-01: Running triggers before up...
==> deis-01: Checking if box 'coreos-stable' is up to date...
==> deis-01: Clearing any previously set forwarded ports...
==> deis-01: Clearing any previously set network interfaces...
==> deis-01: Preparing network interfaces based on configuration...
    deis-01: Adapter 1: nat
    deis-01: Adapter 2: hostonly
==> deis-01: Forwarding ports...
    deis-01: 22 => 2222 (adapter 1)
==> deis-01: Running 'pre-boot' VM customizations...
==> deis-01: Booting VM...
==> deis-01: Waiting for machine to boot. This may take a few minutes...
    deis-01: SSH address: 127.0.0.1:2222
    deis-01: SSH username: core
    deis-01: SSH auth method: private key
    deis-01: Warning: Connection timeout. Retrying...
==> deis-01: Machine booted and ready!
==> deis-01: Setting hostname...
==> deis-01: Configuring and enabling network interfaces...
==> deis-01: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> deis-01: to force provisioning. Provisioners marked to run always will still run.
==> deis-02: Running triggers before up...
==> deis-02: Checking if box 'coreos-stable' is up to date...
==> deis-02: Clearing any previously set forwarded ports...
==> deis-02: Fixed port collision for 22 => 2222. Now on port 2200.
==> deis-02: Clearing any previously set network interfaces...
==> deis-02: Preparing network interfaces based on configuration...
    deis-02: Adapter 1: nat
    deis-02: Adapter 2: hostonly
==> deis-02: Forwarding ports...
    deis-02: 22 => 2200 (adapter 1)
==> deis-02: Running 'pre-boot' VM customizations...
==> deis-02: Booting VM...
==> deis-02: Waiting for machine to boot. This may take a few minutes...
    deis-02: SSH address: 127.0.0.1:2200
    deis-02: SSH username: core
    deis-02: SSH auth method: private key
    deis-02: Warning: Connection timeout. Retrying...
==> deis-02: Machine booted and ready!
==> deis-02: Setting hostname...
==> deis-02: Configuring and enabling network interfaces...
==> deis-02: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> deis-02: to force provisioning. Provisioners marked to run always will still run.
==> deis-03: Running triggers before up...
==> deis-03: Checking if box 'coreos-stable' is up to date...
==> deis-03: Clearing any previously set forwarded ports...
==> deis-03: Fixed port collision for 22 => 2222. Now on port 2201.
==> deis-03: Clearing any previously set network interfaces...
==> deis-03: Preparing network interfaces based on configuration...
    deis-03: Adapter 1: nat
    deis-03: Adapter 2: hostonly
==> deis-03: Forwarding ports...
    deis-03: 22 => 2201 (adapter 1)
==> deis-03: Running 'pre-boot' VM customizations...
==> deis-03: Booting VM...
==> deis-03: Waiting for machine to boot. This may take a few minutes...
    deis-03: SSH address: 127.0.0.1:2201
    deis-03: SSH username: core
    deis-03: SSH auth method: private key
    deis-03: Warning: Connection timeout. Retrying...
==> deis-03: Machine booted and ready!
==> deis-03: Setting hostname...
==> deis-03: Configuring and enabling network interfaces...
==> deis-03: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> deis-03: to force provisioning. Provisioners marked to run always will still run.
mca@mca:~/deis$ ssh-add ~/.vagrant.d/insecure_private_key
Identity added: /home/mca/.vagrant.d/insecure_private_key (/home/mca/.vagrant.d/insecure_private_key)
mca@mca:~/deis$ export DEISCTL_TUNNEL=172.17.8.100
mca@mca:~/deis$ deisctl config platform set sshPrivateKey=~/.vagrant.d/insecure_private_key
LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBNk5GOGlhbGx2UVZwMjJXRGtUa3lydHZwOWVXVzZBOFlWcitrejRUakdZZTdnSHpJCncrbmlObHRHRUZIekQ4K3YxSTJZSjZvWGV2Y3QxWWVTMG85SFp5TjFROXFnQ2d6VUZ0ZE9LTHY2SWVkcGxxb1AKa2NtRjBhWWV0MlBrRURvM01sVEJja0ZYUElUQU16RjhkSlNJRm85RDhIZmRPVjBJQWR4NE83UHRpeFdLbjV5MgpoTU5HMHpRUHlVZWNwNHB6QzZraXZBSWh5ZkhpbEZSNjFSR0wrR1BYUTJNV1pXRlliQUdqeWlZSm5BbUNQM05PClRkMGpNWkVuRGtiVXZ4aE1tQllTZEVUazFyUmdtK1I0TE96RlVHYUhxSERMS0xYK0ZJUEtjRjk2aHJ1Y1h6Y1cKeUxiSWJFZ0U5OE9IbG5WWUN6UmRLOGpscW04dGVoVWM5YzlXaFFJQkl3S0NBUUVBNGlxV1BKWHR6WkE2OG1LZApFTHM0akpzZHlreStld2RaZU5kczV0amNuSFU1elVZRTI1SytmZkpFRDlxVVdJQ2NMWkRjODFUR1dqSHlBcUQxCkJ3N1hwZ1V3RmdlVUp3VWx6UXVyQXYrL3lTbnhpd3VhR0pmaEZNMUNhUUh6ZlhwaGdWbWwrZlpVdm5KVVR2emYKVEsyTGc2RWRiVUU5VGFyVWxCZi94UGZ1RWhNU2xJRTVrZWIvWnozL0xVbFJnOHlEcXo1dytRV1ZKNHV0bktuSwppcXdaTjBtd3B3VTdZU3lKaGxUNFlWMUYzbjRZakxzd001d0pzMm9xbTBqc3NRdS9CVDB0eUVYTkRZQkxFRjRBCnNDbGFXdVNKMmtqcTdLaHJyWVh6YWdxaG5TZWk5T0RZRlNoSnU4VVdWZWMzSWhiNVpYbHpPNnZkTlExSjlYc2YKNG0rMnl3S0JnUUQ2cUZ4eC9SdjlDTk45NmwvNHJiMTRIS2lyQzJvL29yQXBpSG1IRHNVUnM1clVLRHgwZjlpUApjWE43UzF1ZVBYdUpSSy81aHN1YmFPQ3gzT3dkMnU5Z0Q2T3EwQ3NNa0U0Q1VTaUpjWXJNQU50eDU0Y0dIN1JrCkVqRlp4Szh4QXYxbGRFTEV5eHJGcWtiRTRCS2Q4UU90NDE0cWp2VEd5QUsrT0xEM00yUWRDUUtCZ1FEdHg4cE4KQ0F4Ujd5aEhiSVdUMUFINjYrWFdOOGJYcTdsM1JPL3VrZWFjaTk4SmZrYmt4VVJaaHR4Vi9ISHV2VWhuUExkWAozVHd5Z1BCWVpGTm80cHpWRWh6V29UdG5FdHJGdWVLeHljMytMalpwdW8rbUJsUTZPUnRmZ2tyOWdCVnBoWFpHCllFemtDRDNsVmRsOEw0Y3c5QlZwS3JKQ3MxYzV0YUdqRGdkSW5RS0JnSG0vZlZ2djk2Ykp4Yzl4MXRmZlhBY2oKM09WZFVOMFVnWE5DU2FmLzNBL3BoYmVCUWU5eFMrM21wYzRyNnF2eCtpeTY5bU5CZU5aMHhPaXRJanBqQm8yKwpkQkVqU0J3TGs1cTV0SnFIbXkvaktNSkw0bjlST2x4OTNYUytuanhnaWJUdlU2RnA5dytOT0ZEL0h2eEIzVGN6CjYrakpGODVENUJOQUczREJNS0JqQW9HQkFPQXhadmdzS04rSnVFTlhzU1Q3Rjg5VGNrMmlUY1FJVDhnNXJ3V0MKUDlWdDc0eWJvZTJrRFQ1MzF3OCtlZ3o3bkFtUkJLTk03NTFVLzk1UDl0ODhFRGFjREkvWjJPd251RlFIQ1BERgpsbFlPVUkrU3BMSjYvdlVSUmJIU25ubjhhL1hHK256ZWRHSDVKR3FFSk5Rc3oreFQyYXhNMC9XL0NSa25tR2FKCmtkYS9Bb0dBTldyTEN6NzA4eTdWWWdBdFcyVWYxRFBPSVlNZHZvNmZ4SUI1aTlaZklTZ2NKL2JiQ1VrRnJob0gKK3ZxLzVDSVd4Q1BwMGY4NVI0cXh4UTVpaHhKMFlEUVQ5SnB4NFRNc3M0UFNhdlBhQkgzUlhvdzVPaGUrYllvUQpORTVPZ0VYazJ3VmZaY3pDWnBpZ0JLYktaSE5ZY2VsWHRUdC9uUDNyc0N1R2NNNGg1M3M9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
mca@mca:~/deis$ deisctl config platform set domain=local3.deisapp.com
local3.deisapp.com
mca@mca:~/deis$ deisctl install platform && deisctl start platform
● ▴ ■
■ ● ▴ Installing Deis...
▴ ■ ●

Storage subsystem...
Could not find unit template for store-daemon

**Comment by ainux4mrvce** [comment]
after following the all steps this the error i get at end 
deis$ deisctl install platform
● ▴ ■
■ ● ▴ Installing Deis...
▴ ■ ●

Storage subsystem...
Could not find unit template for store-daemon

**Comment by ainux4mrvce** [comment]
if i check fleet of one of instances its gives this message 


fleetctl list-units 
####################################################################
WARNING: fleetctl (0.9.1) is older than the latest registered
version of fleet found in the cluster (0.9.2). You are strongly
recommended to upgrade fleetctl to prevent incompatibility issues.
####################################################################
UNIT	MACHINE	ACTIVE	SUB
