### ISSUE TITLE
Controler couldn't connect to database after node crash

### ISSUE THREAD

**Issue by szymonpk** [deis/deis#3643]
- deis 1.5.0
- 3 node setup on digital ocean toasters (4GB instances)

1. One node (with controller and database) went off.
2. Controller and database were moved to other node.
3. Controller was unable to connect to database, it was trying to use old ip ([log](https://gist.github.com/szymonpk/a7b365aa6649193b97a4)).
4. Controller restart helped.

I've waited about 1-2 minutes before controller restart, I've thought maybe fleet/etcd had some issues. None of services were down atm and previously down node was up and fully running.

**Comment by bacongobbler** [comment]
@szymonpk do you know if the database was "fully" up at the point when the controller was failing to connect? I have a feeling this is due to #2741.

**Comment by bacongobbler** [comment]
I tried the following situation:

1. Controller + database on same node (deis-01)
2. `vagrant halt deis-01`
3. Controller and database were scheduled to deis-02
4. Both came up, controller was connected to database

If you can provide logs on how this failure occurred or some insight on how you're able to reproduce this issue, that would be greatly appreciated!

**Comment by carmstrong** [comment]
@bacongobbler I would try recreating this by stopping/failing over just the database component, and leaving the controller running. I suspect it won't actually reload once the database comes up on the new host and its IP changes.

**Comment by bacongobbler** [comment]
I actually say the same issue after stopping the database. However, the cluster self-healed once the database recovered and pulled its backups from ceph. Seems like #2906, actually. The database said it's running, but it's still recovering from a backup at that time.

**Comment by szymonpk** [comment]
If it would be #2906 shouldn't controller at least try to connect to proper ip? Database was fully recovered at this time ([log](https://gist.github.com/szymonpk/7a6f2748f20e848acdbb), 1 minute before events from my original report)

**Comment by bacongobbler** [comment]
@szymonpk sorry, I meant #2741.

**Comment by carmstrong** [comment]
I could see how #2741 would cause this, since once the database stops publishing its host/port entirely, the confd running in controller would refuse to re-template the file because of the missing key. So the result would be that the controller keeps trying to access the old database host/port.

However, it'd be great to confirm this is indeed the root cause of this issue rather than just speculation.

**Comment by szymonpk** [comment]
I've done some log digging around crash date, I haven't found any log messages related to confd failure, but if you sure I won't argue.

**Comment by carmstrong** [comment]
> I've done some log digging around crash date

If you have windows for the components (specifically controller and database) before and after the issue, I will see what I can find.

**Comment by szymonpk** [comment]
@carmstrong unfortunately I've only deis-database logs from this time, looks like journalctl for deis-controller were rotated few days ago.

**Comment by bacongobbler** [comment]
I have not been able to reproduce this through my testing, but if anyone else is able to on master then that would be appreciated. :)

**Comment by Dovjenkos** [comment]
# **Guys. I solve the problem !!!!**
You need just download stable version 0.6.2
