### ISSUE TITLE
Integration tests should be table-driven

### ISSUE THREAD

**Issue by mboersma** [deis/deis#3646]
Deis' integration tests boil down to "run this command line and inspect the return code and stdout/stderr." This maps nicely to a common go idiom: table-driven tests. Refactoring the tests this way would make them much more approachable.

I've already begun working on this and intend to finish it for the next Deis release.

**Comment by smothiki** [comment]
+1

**Comment by mboersma** [comment]
The v1 integration tests aren't likely to be rewritten at this point. Some of the [v2 workflow-e2e tests](https://github.com/deis/workflow-e2e) do use Ginkgo's table-driven extension, however.
