### ISSUE TITLE
Automated release testing on all cloud providers

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3648]
Manually testing Deis releases on the various supported platforms is 1-2 days of manual work for the entire Deis team. We have [test-ec2](https://ci.deis.io/job/test-ec2/) now successfully validating changes and releases against EC2 - we should investigate doing this for all cloud providers. Saving this manual effort is a big win.

**Comment by sgoings** [comment]
This issue is pretty large in scope. I'll be opening separate issues to cover the providers individually. Seem reasonable to you?

**Comment by carmstrong** [comment]
> Seem reasonable to you?

:+1:
