### ISSUE TITLE
unable to set deisctl config platform sshPrivateKey

### ISSUE THREAD

**Issue by ainux4mrvce** [deis/deis#3649]
root@mca:/home/mca/deis# deisctl config platform set sshPrivateKey=${HOME}/.vagrant.d/insecure_private_key
Error: failed initializing SSH client: dial tcp 172.17.8.100:22: no route to host
root@mca:/home/mca/deis# deisctl --version
1.6.0

Error: failed initializing SSH client: dial tcp 172.17.8.100:22: no route to host
root@mca:/home/mca/deis# deisctl config platform set sshPrivateKey=${root}/.vagrant.d/insecure_private_key
Error: failed initializing SSH client: dial tcp 172.17.8.100:22: no route to host

root@mca:/home/mca/deis# deisctl config platform set sshPrivateKey=$PWD/.vagrant.d/insecure_private_key
Error: failed initializing SSH client: dial tcp 172.17.8.100:22: no route to host

**Comment by ainux4mrvce** [comment]
current directory structure and working directory 
root@mca:/home/mca# ls -a 
.              .bash_logout   .cache   deisctl    .mkshrc   .rvm          vagrant_1.7.2_x86_64.deb  VirtualBox VMs  .zlogin
..             .bash_profile  .config  .ecryptfs  .Private  sources.list  .vagrant.d                .w3m            .zshrc
.bash_history  .bashrc        deis     .gnupg     .profile  .ssh          .viminfo                  .Xauthority

root@mca:/home/mca# pwd
/home/mca
root@mca:/home/mca#

**Comment by ainux4mrvce** [comment]
root@mca:/home/mca/deis# vagrant ssh deis-01 -- -A
Welcome to Deis			Powered by CoreOS
core@deis-01 ~ $ fleetctl list-machines 
####################################################################
WARNING: fleetctl (0.9.1) is older than the latest registered
version of fleet found in the cluster (0.9.2). You are strongly
recommended to upgrade fleetctl to prevent incompatibility issues.
####################################################################
MACHINE		IP		METADATA
9e413bab...	172.17.8.100	-

**Comment by ainux4mrvce** [comment]
core@deis-01 ~ $ etcd start 
[etcd] May  8 12:42:21.323 WARNING   | Using the directory deis-01.etcd as the etcd curation directory because a directory was not specified. 
[etcd] May  8 12:42:21.324 INFO      | deis-01 is starting a new cluster
[etcd] May  8 12:42:21.326 INFO      | etcd server [name deis-01, listen on :4001, advertised url http://127.0.0.1:4001]
[etcd] May  8 12:42:21.327 CRITICAL  | Failed to create listener: listen tcp :4001: bind: address already in use
core@deis-01 ~ $ etcd journallog

**Comment by mboersma** [comment]
Based on #3651 I assume you got past the "Error: failed initializing SSH client: dial tcp 172.17.8.100:22: no route to host" issue. I'm going to close this, but please re-open it or create a new issue if there is something here Deis should fix.
