### ISSUE TITLE
not able to start deisctl platform 

### ISSUE THREAD

**Issue by ainux4mrvce** [deis/deis#3650]
root@mca:/home/mca/deis# deisctl install platform
● ▴ ■
■ ● ▴ Installing Deis...
▴ ■ ●

Storage subsystem...
deis-store-daemon.service: loaded                                 
deis-store-monitor.service: loaded                                 
deis-store-volume.service: loaded                                 
deis-store-metadata.service: loaded                                 
deis-store-gateway@1.service: loaded                                 
Logging subsystem...
deis-logger.service: loaded                                 
deis-logspout.service: loaded                                 
Control plane...
deis-database.service: loaded                                 
deis-controller.service: loaded                                 
deis-registry@1.service: loaded                                 
deis-builder.service: loaded                                 
Data plane...
deis-publisher.service: loaded                                 
Routing mesh...
deis-router@1.service: loaded                                 
deis-router@3.service: loaded                                 
deis-router@2.service: loaded                                 
Done.

Please run `deisctl start platform` to boot up Deis.
root@mca:/home/mca/deis# deisctl start platform 
● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●

Storage subsystem...
deis-store-monitor.service: activating/start-pre

"it stuck at this point"

**Comment by bacongobbler** [comment]
Assuming from the other byg, you were just waiting for the docker images to get pulled which takes time :)

**Comment by ainux4mrvce** [comment]
ya it took time but now its working
