### ISSUE TITLE
deisctl fail to start at control plane builder.service

### ISSUE THREAD

**Issue by ainux4mrvce** [deis/deis#3651]
root@mca:/home/mca/deis# deisctl start platform 
● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●

Storage subsystem...
deis-store-monitor.service: activating/start-pre                                 
deis-store-monitor.service: active/running                                 
deis-store-daemon.service: activating/start-pre                                 
deis-store-daemon.service: active/running                                 
deis-store-metadata.service: activating/start-pre                                 
deis-store-metadata.service: active/running                                 
deis-store-gateway@1.service: activating/start-pre                                 
deis-store-gateway@1.service: activating/start-post                                 
deis-store-gateway@1.service: active/running                                 
deis-store-volume.service: active/running                                 
Logging subsystem...
deis-logger.service: activating/start-pre                                 
deis-logger.service: active/running                                 
deis-logspout.service: activating/start-pre                                 
deis-logspout.service: active/running                                 
Control plane...
deis-controller.service: activating/start-pre                                 
deis-database.service: activating/start-pre                                 
deis-registry@1.service: activating/start-pre                                 
deis-database.service: active/running                                 
deis-registry@1.service: active/running                                 
deis-controller.service: active/running                                 
deis-builder.service: activating/start-pre                                 
deis-builder.service: activating/start-post      

"never goes beyond this level stuck this point at this point"

**Comment by ainux4mrvce** [comment]
base ubuntu with 20 Gb RAM

**Comment by szymonpk** [comment]
How long have you waited? Platform may take some time to install (30minutes++).

**Comment by krancour** [comment]
`deis-builder` in particular takes a long time.  Btw... I assume Ubuntu + 20 Gb RAM is the machine from which you are running `deisctl`.  That machine's specs have little bearing on how long installation and launch takes.  It will be the specs of the CoreOS nodes in your cluster that matter there.

**Comment by bacongobbler** [comment]
hi @ainux4mrvce, what does `deisctl journal builder` show?

**Comment by mboersma** [comment]
@ainux4mrvce were you able to get past this? deis-builder can take a very long time to start but should get there eventually.
