### ISSUE TITLE
docs(customizing_deis): clarify usage of registrationMode

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#3653]
Some users are confused on where to find this setting, and how to use it. It would be useful to write a small tutorial on what each setting does and how they apply to their environment.

**Comment by Joshua-Anderson** [comment]
@bacongobbler Where would this tutorial go? A blog post?

**Comment by bacongobbler** [comment]
Just in http://docs.deis.io/en/latest/customizing_deis/controller_settings/ just like the others like "Unit Hostname" and "Using LDAP"
