### ISSUE TITLE
high load + logger causes excessive traffic to etcd

### ISSUE THREAD

**Issue by slack** [deis/deis#3657]
Running some very small load generators while playing with sysdig uncovered the fact that the syslog module appears to be hitting up etcd for the drain key on every log line.

Not sure if you want to memoize with a TTL or config file + confd.

![2015-05-08 at 17 11](https://cloud.githubusercontent.com/assets/28873/7547588/53fa7e98-f5a5-11e4-9da4-65e5ea694a34.png)

![2015-05-08 at 17 13](https://cloud.githubusercontent.com/assets/28873/7547615/ce71eb98-f5a5-11e4-93fe-ae3bc7370407.png)

Edit: forgot the code!

https://github.com/deis/deis/blob/df00fb4e41ed1f825e6c210c637d2e4772326f64/logger/syslogd/syslogd.go#L87

**Comment by bacongobbler** [comment]
Yep. GetDrain seems to be creating a new connection every time. We should be re-using the same client connection rather than re-establishing, at the very least.

**Comment by eMxyzptlk** [comment]
@bacongobbler The settings should probably be refreshed every X (maybe 1) minutes or so, easy fix. Anyone working on this? Otherwise please assign it to me.

**Comment by bacongobbler** [comment]
We can't assign the issue to you but feel free to contribute a fix if you're up for it :)

**Comment by bacongobbler** [comment]
I'd personally opt for a feature flag + reload on etcd key changes similar to the publisher issue, though
