### ISSUE TITLE
Provide container/unit name in journal

### ISSUE THREAD

**Issue by simpsora** [deis/deis#3672]
I'm using the system-wide log drain mechanism (`journalctl -o short -f | ncat log-dest`) to send all my logs to a Logstash instance.  However, the entries don't mention which unit generated them, e.g.:

```
May 11 21:54:08 search-coreos-10-1-4-82 sh[23501]: [EnableReplication] Pushing settings to index : num_replicas=2, refresh_interval=60s
```

I could write a script that did a `ps` for the pid (`sh[23501]`) and replaced it before sending to ncat, but that seems kludgy.  Is there a way to have the journal print the unit name instead of / in addition to the pid?

This is basically the same question as asked here:
http://stackoverflow.com/questions/28422963/how-can-i-get-more-precise-log-sources-from-my-deis-apps-containers

However, I don't see the `_SYSTEMD_UNIT` field in the journal output, except when using `verbose` output mode.

Are there any other options here?  We have several apps running in our Deis cluster, and need to differentiate the logs.

Thanks!!

**Comment by bacongobbler** [comment]
@simpsora with v1.5.0 you can use `deisctl config logs sest drain=syslog://...`. The logger will then forward logs over to your endpoint via udp.

**Comment by bacongobbler** [comment]
relevant docs: http://docs.deis.io/en/latest/managing_deis/platform_logging/#application-log-drain

**Comment by simpsora** [comment]
Thanks @bacongobbler.  It's not clear from the docs what the difference is between the log drain and routing the logs with `journalctl` via `ncat`.  It does look like the log drain is the way to go (log messages do contain the app name).

I'm struggling getting a custom logger image working which supports the syslog drain over TCP, but that's another issue.

Cheers!

**Comment by carmstrong** [comment]
> It's not clear from the docs what the difference is between the log drain and routing the logs with journalctl via ncat.

Good point - would you be willing to update the docs to make them clearer?

**Comment by simpsora** [comment]
If be happy to, just need to understand the difference a little better myself, then will put up a PR. 

In the meantime, just a quick question -- getting the log drain to send via tcp rather than udp *should* be as simple as changing the protocol in the call to `net.Dial` in `drain.go`, would you agree?

Cheers!

**Comment by carmstrong** [comment]
> If be happy to, just need to understand the difference a little better myself, then will put up a PR.

Sounds great! Let us know how we can help.

**Comment by bacongobbler** [comment]
closing as irrelevant for [v2](https://deis.com/blog/2016/workflow-stable/).
