### ISSUE TITLE
Does deis have disk self-cleaning mechanism?

### ISSUE THREAD

**Issue by szymonpk** [deis/deis#3675]
My cluster is filling up, most of space is taken by /var/lib/docker, currently I've only 4 apps. After running `docker images -aq | xargs -l10 docker rmi` almost nothing is removed. But `docker images -a` shows many of previous deployments. Is there some kind of logic which will keep disk space sane?

**Comment by bacongobbler** [comment]
You can also try `docker rmi $(docker images -f "dangling=true" -q)`: https://docs.docker.com/reference/commandline/cli/

**Comment by eMxyzptlk** [comment]
I think that this deserves a mention in "Troubleshooting Deis".

**Comment by carmstrong** [comment]
> I think that this deserves a mention in "Troubleshooting Deis".

We should probably add it to http://docs.deis.io/en/latest/managing_deis/disk_usage/#recovering-disk-space

**Comment by szymonpk** [comment]
@bacongobbler didn't helped, I still have old releases and /var/lib/docker is taking almost 70% (40GB) of disk.

**Comment by croemmich** [comment]
@szymonpk This is what I use.. use at your own risk:
```
[Unit]
Description=Clean up disk space

[Service]
Type=oneshot
ExecStartPre=-/bin/sh -c 'docker pull martin/docker-cleanup-volumes'
ExecStart=-/bin/sh -c "docker rm `docker ps -a | grep Exited | awk '{print $1 }'`"
ExecStart=-/bin/sh -c 'docker run -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker:/var/lib/docker --rm martin/docker-cleanup-volumes'
ExecStart=-/bin/sh -c 'docker images -aq | xargs -l10 docker rmi'
ExecStart=-/run/deis/bin/preseed

[X-Fleet]
Global=true
```

**Comment by gabrtv** [comment]
I know many users have solved this problem in different ways.  I'd love to see these sort of maintenance tasks packaged as default units on all clusters.

**Comment by haf** [comment]
This is a big (!) problem for me too.

**Comment by carmstrong** [comment]
If anyone wants to PR their cleanup solution, we'd love to review it!

**Comment by szymonpk** [comment]
@croemmich looks like your solution gave me best result. It didn't break any deployments. Looks like I'll be running this once every few weeks. Thanks!

**Comment by carmstrong** [comment]
@croemmich Is your Docker image something that you'd like to add to https://github.com/deis/deis/blob/master/contrib/README.md ?

We may also want to bring that logic into Deis proper if it works well!

**Comment by croemmich** [comment]
@carmstrong Which image? The martin/docker-cleanup-volumes is by @chadoe.

**Comment by carmstrong** [comment]
> The martin/docker-cleanup-volumes is by @chadoe.

Ah, okay. Was hoping to get some visibility into what it's doing. Looks like that's here: https://github.com/chadoe/docker-cleanup-volumes

Maybe we should add this to our shared user-data to the project, and just not start it by default?

**Comment by croemmich** [comment]
Yeah, I can submit a pull for that if you want. So far I haven't noticed any issues using it.

Can you comment as to what these containers are used for?
deis-database-data
deis-store-daemon-data
deis-store-monitor-data

The command `docker rm `docker ps -a | grep Exited | awk '{print $1 }'`` will wipe them out. Is that OK?

**Comment by carmstrong** [comment]
> Is that OK?

Good catch - we definitely don't want to remove those. They expose Docker volumes which are used by components to store data. This allows us to upgrade database, store-daemon, and store-monitor on platform upgrades without wiping away their data.

**Comment by croemmich** [comment]
Good to know. I'll write something to make sure those don't get nuked.

As an aside, is that the proper way to provide those volumes? It feels weird that an exited container is still "in-use."

**Comment by carmstrong** [comment]
> As an aside, is that the proper way to provide those volumes?

I'd actually prefer not to use those for the store components, but I'm not sure what a better solution looks like - #3124

**Comment by croemmich** [comment]
Ah, fair enough.

In hindsight, I'm guessing removal of the data containers is probably what caused #3647.

I'll make sure the data containers aren't being removed and will create a pull shortly. Thanks!

**Comment by carmstrong** [comment]
> In hindsight, I'm guessing removal of the data containers is probably what caused #3647.

Most likely - that's essentially nuking data in Ceph, which confuses things because the node things it's a member.

> I'll make sure the data containers aren't being removed and will create a pull shortly. Thanks!

Much appreciated! We can have the PR close this issue.

**Comment by bacongobbler** [comment]
Copypasta from my comment in #3716:

So to keep the ball rolling, I guess there's a few things needed to be done here from my point of view to merge this:

 - Introduce a new component called `deis/waste-collector` (just throwing out a name) that is an agent like publisher and logspout that runs on all hosts
 - `deis/waste-collector` contains the script from https://github.com/chadoe/docker-cleanup-volumes, running it periodically (daily?)
 - introduce this new component to deisctl so that this new component is installed
 - Add documentation on this new component, including what it does, how often it does it, how to tweak/uninstall it, etc.

Since this is something that seems pretty important and that we'd need to support, installing a new component seems to be the most ideal solution such that users don't have to re-provision their platform from scratch, and it does give users who do not want their artifacts to be cleaned up a way to opt out. It also gives us a way to opt out if we find a better solution in future versions of Deis.

**Comment by szymonpk** [comment]
@croemmich Is your fixed cleanup (one which won't remove deis/ceph containers) script version available anywhere?

**Comment by szymonpk** [comment]
```
[Unit]
Description=Clean up disk space

[Service]
Type=oneshot
ExecStartPre=-/bin/sh -c 'docker pull martin/docker-cleanup-volumes'
ExecStart=-/bin/sh -c "docker rm `docker ps -a | grep Exited | grep -v deis | awk '{print $1 }'`"
ExecStart=-/bin/sh -c 'docker run -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker:/var/lib/docker --rm martin/docker-cleanup-volumes'
ExecStart=-/bin/sh -c 'docker images -aq | xargs -l10 docker rmi'
ExecStart=-/run/deis/bin/preseed

[X-Fleet]
Global=true
```
I should have done this earlier, `grep -v deis` excludes ceph data volumes from removal.

**Comment by wgrrrr** [comment]
Thought I'd add my support for the idea of an automatic disk clean up feature. I will trying using the service described by @szymonpk immediately above this comment and see how that goes. Thanks for sharing it!

**Comment by szymonpk** [comment]
Issue struck me again, on host with builder I've almost twice disk usage (20 vs 40GB) as on rest of deis nodes. Most of the space is taken by /var/lib/docker

```
deis-staging-3 deis # ionice -c 2 du -sh /var/lib/docker/*
...
7.8G	/var/lib/docker/overlay
...
39G	/var/lib/docker/vfs
...
```
vs.
```
deis-staging-2 deis # ionice -c 2 du -sh /var/lib/docker/*
...
4.1G	/var/lib/docker/overlay
...
18G	/var/lib/docker/vfs
...
```

Any idea how to handle this or debug further? Maybe I shouldn't blame builder? All volumes are in use cannot remove anything else. /cc @bacongobbler @carmstrong

**Comment by szymonpk** [comment]
I've dug a little bit more, I've found I've some old tagged releases which aren't running any more for example 

```
10.131.169.228:5000/test-api         v3                  76e7288aa2ea        6 weeks ago         1.471 GB
```

Where currently I'm running v28. Can I delete it safely?

**Comment by bacongobbler** [comment]
related: https://github.com/spotify/docker-gc

**Comment by szymonpk** [comment]
Spotify's docker-gc doesn't help much. Did anyone else noticed much higher disk usage on builder node?

**Comment by wgrrrr** [comment]
I have the same issue with high disk usage on the builder node. I have regularly used the cleanup service provided by @szymonpk above (which removes old images), as well as restarting the builder component (which erases the deployed Git repos) and manually removing the `deis-builder-data` container. Even with all that, disk usage continues to increase every day (even without any deployments being done).

Is there any way to force the builder to jump to a different node? That would at least buy me some time until I figure out what's going on. I only have about 25% free disk space on the 100GB Docker volume on the builder node. The other nodes in the cluster each have around 75% disk space available.

**Comment by carmstrong** [comment]
> Is there any way to force the builder to jump to a different node?

You could stop the builder, manually remove the `deis-builder-data` container, and then restart builder. That should purge all of its data.

What version of Deis is this? There was some hope that #3918 would ensure we're removing containers.

**Comment by szymonpk** [comment]
@wgrrrr what deis and coreos version are you using?

**Comment by wgrrrr** [comment]
I'm running Deis 1.7.3 on CoreOS 647.2.0.

I just did the following:
```
core@ip-10-0-x-x ~ $ deisctl stop deis-builder
deis-builder.service: inactive/dead  
core@ip-10-0-x-x ~ $ docker rm -fv deis-builder-data
deis-builder-data
core@ip-10-0-x-x ~ $ deisctl start deis-builder
deis-builder.service: activating/start-post                                 
deis-builder.service: active/running   
```

Disk usage before:
```
/dev/xvdf                               94G   65G   25G  73% /var/lib/docker
```

Disk usage after:
```
/dev/xvdf                               94G   65G   25G  73% /var/lib/docker
```

There was no impact on disk space usage (as I mentioned, I've already been through this recently, so it's not surprising to me that there was little to no benefit).

Still wonder if there is a way I can run builder on a different host in the cluster?

**Comment by carmstrong** [comment]
> Still wonder if there is a way I can run builder on a different host in the cluster?

That's up to the scheduler (fleet), not us. You could try uninstalling/reinstalling the unit until it lands on a different host. 

Are you running `df -h` on the host? It could be that the data is used by deployed application images and not the builder component itself.

**Comment by szymonpk** [comment]
@carmstrong I've same issue wherever builder migrates disk is used more there and it isn't freed even if builder is moved elsewhere.

**Comment by szymonpk** [comment]
I've found some related (I think) issues (docker/docker#3925, docker/docker#6354, docker/compose#1327) however they are using aufs instead of dir. Is there anyway to correlate content of `/var/lib/docker/vfs/dir/` to any images?

**Comment by wgrrrr** [comment]
Here is where all the disk space is being used on my builder node:
```
ip-10-0-x-x docker # ionice -c 2 du -sh /var/lib/docker/*
362M	/var/lib/docker/containers
248K	/var/lib/docker/execdriver
1.9M	/var/lib/docker/graph
7.5M	/var/lib/docker/init
32K	/var/lib/docker/linkgraph.db
16K	/var/lib/docker/lost+found
5.8G	/var/lib/docker/overlay
4.0K	/var/lib/docker/repositories-overlay
4.0K	/var/lib/docker/tmp
8.0K	/var/lib/docker/trust
59G	/var/lib/docker/vfs
60K	/var/lib/docker/volumes
```

While it is possible that the disk space is being used by applications, none of the other nodes in the cluster is experiencing out-of-control disk usage. Just in case, I will try restarting all the apps to see if the disk usage is reduced.

**Comment by szymonpk** [comment]
Ok I've done next portion of digging, on host where `deis-builder` was previously. I've container:

```
fcf3f02c6dee        ubuntu-debootstrap:14.04           "/bin/true"            8 weeks ago         Exited (0) 8 weeks ago                                                                      deis-builder-data
```
Via `docker inspect` I've checked it's using `/var/lib/docker/vfs/dir/4a5e62053277e226fea28f51abd06da116b05bd424b850ba422dddcf5be58fe6`, which is main disk space hog on this host. I've tried to remove it, it went fine (same as @wgrrrr):

```$ docker rm -fv deis-builder-data
deis-builder-data```

But! directory is still there :/ DOCKER you ...!!

@wgrrrr as possible solution, if you managed to move builder elsewhere (or when it's stopped), run:

```
# as root
for i in `docker ps -q -a`; do docker inspect $i >> /tmp/dock.tmp; done
for i in `ls /var/lib/docker/vfs/dir/`; do grep $i /tmp/dock.tmp; done | sort | uniq
```

You will get list of dirs really used (I suppose?). Then you can look at content of `/var/lib/docker/vfs/dir/` and probably remove directory which isn't on the list. I'll  try this on my deis cluster when it will be decomissioned next week.

**Comment by wgrrrr** [comment]
I've done some more digging. Here are all the directories and their sizes in my `/var/lib/docker/vfs/dir` directory:
```
ip-10-0-x-x docker # ionice -c 2 du -sh /var/lib/docker/vfs/dir/*
47M	/var/lib/docker/vfs/dir/1e3e545d496fc39c3ddf4372e2f5794ffb41d766411b3199a33b5cef62c4933a
19G	/var/lib/docker/vfs/dir/50bed551d049e8e756541fced3023d629e9c2e4b2a0cd47cbbf60082d44dfdde
39G	/var/lib/docker/vfs/dir/86ed07cc2182cec0964928eb22b51aa2c760ed4dd0eae62c2d96e0a96b2d12cc
20K	/var/lib/docker/vfs/dir/9daf3c86285d88c73ac63388bcf6a25cf5d0cf1ad31a799b80254833402984af
1.7G	/var/lib/docker/vfs/dir/c926e2bf73a6270860361c5e7c4c8983c31e4f43fe6754b2ddeaa23d5eecb26c
```

I then attempted to see if the 39G directory (50bed551d049e8e756541fced3023d629e9c2e4b2a0cd47cbbf60082d44dfdde) was in use by any container:
```
ip-10-0-x-x docker # for i in `docker ps -q -a`; do docker inspect $i >> /tmp/dock.tmp; done
ip-10-0-x-x docker # for i in `ls /var/lib/docker/vfs/dir/`; do grep $i /tmp/dock.tmp; done | sort | uniq
        "/etc/ceph": "/var/lib/docker/vfs/dir/9daf3c86285d88c73ac63388bcf6a25cf5d0cf1ad31a799b80254833402984af",
        "/var/lib/ceph/mon": "/var/lib/docker/vfs/dir/1e3e545d496fc39c3ddf4372e2f5794ffb41d766411b3199a33b5cef62c4933a"
        "/var/lib/ceph/mon": "/var/lib/docker/vfs/dir/1e3e545d496fc39c3ddf4372e2f5794ffb41d766411b3199a33b5cef62c4933a",
        "/var/lib/ceph/osd": "/var/lib/docker/vfs/dir/50bed551d049e8e756541fced3023d629e9c2e4b2a0cd47cbbf60082d44dfdde"
        "/var/lib/docker": "/var/lib/docker/vfs/dir/c926e2bf73a6270860361c5e7c4c8983c31e4f43fe6754b2ddeaa23d5eecb26c"
ip-10-0-x-x docker # grep 86ed07cc2182cec0964928eb22b51aa2c760ed4dd0eae62c2d96e0a96b2d12cc /tmp/dock.tmp 
``` 

So it seems that directory is orphaned. I wonder if I can just delete it?

**Comment by wgrrrr** [comment]
I have manually deleted the orphaned volume that Docker should have deleted and have recovered a vast amount of disk space.

Thanks to everyone in this thread for their help. The `martin/docker-cleanup-volumes` Docker image was particularly helpful in confirming and removing the orphaned volume.

**Comment by szymonpk** [comment]
If you don't want to stop builder you can nse to deis-builder and run `docker images` from inside. I've found there pretty huge [pile of images](https://gist.github.com/szymonpk/99deed8edb97586c681e). I've removed all except one, newest for each app. We'll see how it goes.

**Comment by lukasmartinelli** [comment]
Check our approach to the problem:
https://github.com/dreipol/cleanup-deis-images

We run a daily cleanup script that removes old versions (all versions older than `current - 4`) by inspecting  the Docker image tag because of the many times the builder had full disk space errors.

```bash
docker run --rm \
 -v /var/run/docker.sock:/var/run/docker.sock \
 -e KEEP_LAST_VERSIONS=3 dreipol/cleanup-versions
```

I have examples of service files and timers in the repo so you can setup daily cleanup task.

**Comment by szymonpk** [comment]
Thank @lukasmartinelli we wanted to create something similar because, docker-cleanup started to misbehave lately (due to io heavy, completely unnecessary find commands).

However there is still issue with clean up inside builder.

**Comment by szymonpk** [comment]
We've took a little bit different approach (https://github.com/Ragnarson/deis-cleanup), our cleanup script can run inside builder too, however it still isn't complete solution, because we've some some untagged (with repository and tag name set to `<none>`) application images left by builder.

**Comment by krancour** [comment]
fwiw, Kubernetes has built-in "garbage collection" of stale Docker images and such, and its policies are configurable if I'm not mistaken.  Deis v2, aka Workflow, benefits from this since it is Kubernetes native.  

As for Deis v1.x, feature dev is no longer ongoing.  An LTS release will focus on bug fixes and overall stability improvements.  I would guess that an out-of-the-box solution to this is too "featurey" / too big to qualify.  The best way to address this is probably as @carmstrong had suggested quite a ways back-- amendments to the "recovering disk space" page.

http://docs.deis.io/en/latest/managing_deis/disk_usage/#recovering-disk-space

I'm going to mark this as "needs docs."

**Comment by bacongobbler** [comment]
closing as irrelevant for [v2](https://deis.com/blog/2016/workflow-stable/). kubernetes handles disk usage for us and cleans up stale images on the worker nodes.
