### ISSUE TITLE
docker.service needs to depend on the mount.

### ISSUE THREAD

**Issue by jwaldrip** [deis/deis#3677]
Ran into some edge cases where the mount would not complete before docker started. This would cause docker run to never work until the docker daemon was restarted. We fixed this on our end by putting an After and Require statement in the docker.service.

**Comment by carmstrong** [comment]
Thanks @jwaldrip. Mind PRing what you've got?

**Comment by carmstrong** [comment]
Clearing milestone - I thought this was related to the docker-tcp.socket added in Deis 1.6, but I think you seem to be referring to the mount volume.

**Comment by jwaldrip** [comment]
Seems to be a bigger issue...
