### ISSUE TITLE
change of deploy strategy for deis to use resource aware schedulers.

### ISSUE THREAD

**Issue by smothiki** [deis/deis#3685]
Right now on a new release, deis pushes the new containers and destroys the old ones. Which works fine with fleet. For resource aware scheduler like mesos or swarm. Once the cluster is packed with containers, we cannot do a new release as the cluster has no resources left to schedule new containers.

Solutions :
1. Do a rolling release of container by container. destroy one container of old release and start one container of new release.
2. Rolling release of 50% of the containers for that release which takes logN time.

**Comment by bacongobbler** [comment]
related: https://github.com/deis/deis/issues/3148

**Comment by bacongobbler** [comment]
shifting this over to a v2 discussion, as we should display scheduler errors when resources are not available to deploy a new release of an application.

**Comment by bacongobbler** [comment]
closing as irrelevant for [v2](https://deis.com/blog/2016/workflow-stable/).
