### ISSUE TITLE
'stateless plx' option

### ISSUE THREAD

**Issue by haf** [deis/deis#3693]
I've been running deis now for about three months with fairly frequent releases, in a DigitalOcean environment. I've had three major outages due to Deis:

 - The first cluster I put up became catatonic after etcd blew up and couldn't be saved (Deis is still on a version that's vulnerable)
 - The load balancer stopped forwarding to apps
 - The upgrade to 1.5.2 took about 30 minutes to complete -- too long imo. Should be sub-second outage.

I'm currently experiencing a third partial outage due to the drives on the builder machine having been filled up. The docs helped me free 400 MiB, but that's not enough, so I can't make progress (I've been waiting about an hour on `du` to finish, and meanwhile just using du crashed docker and that made deisctl fail completely (SSH timeout)).

I don't particularly like operating this fire service and I need to be sure that my customers can get to their apps.

I have these invariants:

 - I don't care about old releases much, most of the time. If I do, it's normally a rollback.
 - I don't want to have to manually clean disks - the deis platform should not roll itself over the edge of the cliff unless I allow it explicitly, but that's what it's currently doing
 - I don't care about saving old logs on disk -- I want to ship logs and I've set up papertrail - but I would much prefer semantic logging over "text" logging - i.e. Logentries or [Logary](https://logary.github.io/). I could take potentially ownership of this as I've written logary and have a fairly good idea of how to deal with logs.

Therefore I would suggest a 'stateless plx' option:

 - `deis releases prune` - remove all but the latest and also remove all docker containers not in use
 - no systemctl logs saved to disk by default - make ceph an add-on and expose it with *service discovery* for my apps instead
 - supply a default log router ([Heka](https://github.com/mozilla-services/heka) or Logstash) with op-/user-facing, mutable-after-deploy configuration, and configure it BOTH for metrics and for logs, *semantically* so that you don't have to parse the line of log in every log sink
 - supply a default [alerting framework](https://sensuapp.org/docs/latest/events) out of the box so I know when the platform is going belly-up -- and ensure log-levels and tags are used throughout the code-base: { verbose, debug, info, error, fatal } are my normal levels and fatal errors I always send text messages from -- I can write a logary target for 46elks and have texts available to deis users
 - supply a default backup engine such as [bacula](http://blog.bacula.org/) and have the CLI that configures the platform take a S3 API endpoint + credentials + encryption phrase
 - supply an inverse/corresponding 'provision from backup' command that invokes [the machinery](http://www.bacula.org/5.1.x-manuals/en/main/main/Restore_Command.html)
 - schedule the restart of services in upgrades so that downtime is minimised
   * restart routers last
   * coordinated restarts of routers to let round-robin DNS do its thing

This is the fourth outage and I'm currently setting up the environment without Deis now.

**Comment by mboersma** [comment]
> due to the drives on the builder machine having been filled up

@haf as of the [Deis v1.7.3](https://github.com/deis/deis/releases) release, deis-builder reliably cleans up the git repositories and Docker images for apps you delete with `deis destroy`. It's a start... :disappointed_relieved: 

Also, please come to our July 2 [open planning meeting](http://docs.deis.io/en/latest/roadmap/planning/#release-planning-meetings) and ensure that some of the larger issues you describe are addressed on the [road map](http://docs.deis.io/en/latest/roadmap/roadmap/).

**Comment by bacongobbler** [comment]
All of these points have been opened as smaller issues so that we may track them individually. To call them out one by one:

> but I would much prefer semantic logging over "text" logging - i.e. Logentries or Logary.

http://docs.deis.io/en/latest/managing_deis/platform_logging/

> I don't want to have to manually clean disks - the deis platform should not roll itself over the edge of the cliff unless I allow it explicitly, but that's what it's currently doing

https://github.com/deis/deis/issues/3675#issuecomment-115809720

> deis releases prune

#3698 

> make ceph an add-on

#231 along with a conversation in some issue I can't find right now

> supply a default log router (Heka or Logstash)

deis-logger is our default log router.

> supply a default alerting framework out of the box so I know when the platform is going belly-up

#3699 

> supply a default backup engine

I'm not sure that's something we can reasonably resolve for everyone as each user has their own backup story. However, we have [documentation](http://docs.deis.io/en/latest/managing_deis/backing_up_data/) on what you **should** be backing up, so that should give you a head start.

> schedule the restart of services in upgrades

#1829, #3811 and #3461.

If you have any more feedback, please open issues for each issue you're currently having. Thank you!

**Comment by haf** [comment]
@bacongobbler Looking good; I might look into Deis again during the next "ops period" now that these things have been fixed!
