### ISSUE TITLE
deis utility warnings should go to stderr

### ISSUE THREAD

**Issue by ineu** [deis/deis#3694]
I have staging and production clusters running different versions of Deis. Version of `deis` tool is 1.6.0.
When connecting to older cluster, I receive warning:
```
> $ deis apps 2>/dev/null
  !    WARNING: Client and server API versions do not match. Please consider upgrading.
  !    Client version: 1.3
  !    Server version: 1.2

=== Apps
...
```
Unfortunately trick with `2>/dev/null` does not work, looks like `deis` tool sends warning to stdout instead of stderr.

**Comment by mboersma** [comment]
The `deis` CLI doesn't seem to use stderr at all, and I agree it's unexpected and should be changed.

**Comment by bacongobbler** [comment]
Sounds like a regression: https://github.com/deis/deis/pull/1739#issue-41580796

**Comment by bacongobbler** [comment]
Yep, definitely a regression, though I don't recall why we went forward with this instead of stdout/stderr: https://github.com/deis/deis/pull/1839

**Comment by mboersma** [comment]
See also #4085.

**Comment by Joshua-Anderson** [comment]
See #4440
