### ISSUE TITLE
Installing swarm is taking too long/seems to fail

### ISSUE THREAD

**Issue by haf** [deis/deis#3695]
```
deisctl install swarm && deisctl start swarm
● ▴ ■
■ ● ▴ Installing Swarm...
▴ ■ ●

Swarm node and Swarm Manager...
Could not find unit template for swarm-node
Done.

Please run `deisctl start swarm` to start swarm.
● ▴ ■
■ ● ▴ Starting Swarm...
▴ ■ ●

swarm nodes...
could not find unit: deis-swarm-node.service

```

That error message and then blocking in not good UI. Has it failed like so many other times? Should I wait? Should I cancel?

**Comment by PierreKircher** [comment]
seems like you missing the unitfile for swarm

**Comment by haf** [comment]
The docs and git checkout 1.6.1 is missing it then.

**Comment by PierreKircher** [comment]
its an expermintal feature .. so dond supect it working like its stable

**Comment by haf** [comment]
It's a broken feature since it can't be installed though. Hence the ticket.

**Comment by PierreKircher** [comment]
stop beeing a jerk .. i told you already what todo .. its opensource after all

**Comment by mboersma** [comment]
It depends on where your have the unit files installed. You can set the DEISCTL_UNITS environment variable to point to a directory containing the v1.6.1 unit files, or just run `deisctl refresh-units` to install them to $HOME/deis/units. Then `deisctl` should find them and install swarm.

**Comment by carmstrong** [comment]
@haf You're absolutely right - that was an oversight. `deisctl refresh-units` doesn't include the Swarm units. We're fixing that up now. :+1:
