### ISSUE TITLE
Deis monitoring & telemetry API and agent (statspout)

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3699]
Deis needs to define metrics and monitoring interfaces and implement a collection agent so users can have operational visibility into their Deis clusters.

**Comment by bacongobbler** [comment]
+1. What kind of metrics are we looking to track? I'm guessing that we'd want to monitor /proc, `docker info` at the very least, but I'd be curious how we'd retrieve other component-specific information.

**Comment by carmstrong** [comment]
I think @slack has fleshed some of this out, but details are TBD.

**Comment by carmstrong** [comment]
> What kind of metrics are we looking to track?

Some of this is fleshed out at http://docs.deis.io/en/latest/roadmap/roadmap/

The categories are:
 - Host Telemetry (cpu, memory, network, disk)
 - Container Telemetry (cpu, memory, network, disk)
 - Platform Telemetry (control plane, data plane)
 - Controller Telemetry (app created, build created, containers scaled)

We're actually looking to add someone to the Deis/Engine Yard team to work on this full-time, so if anyone's interested, please reach out!

**Comment by technosophos** [comment]
From experience, some of the things I was asked for when I worked on PaaS were:

- App (Container) stop, start, restart events (Probably the same as Controller Telemetry)
- Access (e.g HTTP 2XX) and Error hits on apps (Containers)
- Frequency of various platform errors, like routing failures

I guess I figure we have four classes of telemetry data users:

- Business Analytics: Desire to know information that indicates customer engagement.
- SLA data: Monitor availability for uptime and service level agreement.
- Operations: The health of the system is paramount. Errors are important.
- Security/performance: Looking for ways to identify and improve the system.

Most are interested in the same baseline set of facts, I'd imagine.

**Comment by sstarcher** [comment]
We currently use cadvisor to accomplish some of this are you guys looking at a custom solution?

**Comment by carmstrong** [comment]
> We currently use cadvisor to accomplish some of this are you guys looking at a custom solution?

The solution will require knowing something about the running containers - specifically, which Deis apps they correlate with. This is something that nothing is going to give us off-the-shelf. We're investigating monitoring partners and their agents, and will come up with a solution which works best for our users. 

/cc @slack

**Comment by jchauncey** [comment]
See #4110  for the current Design Proposal

**Comment by bacongobbler** [comment]
closing: see https://github.com/deis/monitor for a implementation of monitoring + telemetry for Deis v2.
