### ISSUE TITLE
deisctl: Add 'backup' and 'restore' commands

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3700]
We have the [backup/restore](http://docs.deis.io/en/latest/managing_deis/backing_up_data/) docs, but `deisctl` itself should have a backup/restore command to ease this process. We could also back up and restore etcd keys, which is not something we currently do - we just repopulate them from the database.

**Comment by Joshua-Anderson** [comment]
Ref #1408

The suggested CLI from there is:

``` shell
$ deisctl backup > deis.tar
$ deisctl restore < deis.tar
$ deisctl backup database > deis-database.tar
$ deisctl restore database < deis-database.tar
```

**Comment by carmstrong** [comment]
This is probably easier since etcd2 provides native backup/restore functionality in `etcdctl`, so we could probably vendor that code quite easily.

**Comment by bacongobbler** [comment]
deisctl is going away in Deis v2 and I don't think we will be able to get to this for the LTS release so I'm going to go ahead and close this. Thank you for the report though!
