### ISSUE TITLE
Python errors unreadable in non-english locale

### ISSUE THREAD

**Issue by ineu** [deis/deis#3715]
With my system locale (ru_RU.UTF-8) I receive following error:
```
> $ deiss apps             
Couldn't connect to the Deis Controller:
('Connection aborted.', error(104, '\xd0\xa1\xd0\xbe\xd0\xb5\xd0\xb4\xd0\xb8\xd0\xbd\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 \xd1\x80\xd0\xb0\xd0\xb7\xd0\xbe\xd1\x80\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbe \xd0\xb4\xd1\x80\xd1\x83\xd0\xb3\xd0\xbe\xd0\xb9 \xd1\x81\xd1\x82\xd0\xbe\xd1\x80\xd0\xbe\xd0\xbd\xd0\xbe\xd0\xb9'))
Make sure that the Controller URI is correct and the server is running.
```

With default locale it's much better:
```
> $ LANG= deiss apps          
Couldn't connect to the Deis Controller:
('Connection aborted.', error(104, 'Connection reset by peer'))
Make sure that the Controller URI is correct and the server is running.
```

This is probably a python problem, but `print` for cyrillic letter from python3 console works fine with ru_RU locale.

**Comment by mboersma** [comment]
I couldn't reproduce this using the `deis` built binary or `deis.py` locally:
```console
$ LANG=ru_RU.UTF-8 deis apps
Couldn't connect to the Deis Controller:
('Connection aborted.', error(61, 'Connection refused'))
Make sure that the Controller URI is correct and the server is running.
$ LANG= deis apps
Couldn't connect to the Deis Controller:
('Connection aborted.', error(61, 'Connection refused'))
Make sure that the Controller URI is correct and the server is running.
```

This looks like it should all be client-side, so I'm not sure what else to try. The client does start up with [the standard invocation](https://docs.python.org/2/library/locale.html#locale.setlocale) to set the locale from the LANG variable, and your tests indicate it is being honored...

**Comment by ineu** [comment]
@mboersma I suspect you don't have russian locale configured, that's why it falls back to english for you. I've just set up another non-latin locale (greek):
```
> $ LANG=el_GR.UTF-8 deiss apps                           
Couldn't connect to the Deis Controller:
('Connection aborted.', error(111, '\xce\x91\xcf\x80\xcf\x8c\xcf\x81\xcf\x81\xce\xb9\xcf\x88\xce\xb7 \xcf\x83\xcf\x8d\xce\xbd\xce\xb4\xce\xb5\xcf\x83\xce\xb7\xcf\x82'))
Make sure that the Controller URI is correct and the server is running.
```

**Comment by ineu** [comment]
Same on Debian 8 with python 2

**Comment by mboersma** [comment]
The python client is deprecated and will be removed with the v1.10.0 release. If you see similar issues with the new go CLI, please open a new issue.
