### ISSUE TITLE
Feature Request: Maintenance Mode

### ISSUE THREAD

**Issue by jwaldrip** [deis/deis#3722]
Allow for a maintenance mode config option that will stop serving web traffic and send it to a static maintenance page.

ex:

```sh
$ deis maintenance:set_page http://s3.aws.com/mybucket/mypage.html
$ deis maintenance:on
$ curl http://mysite.com
<html>
We are under maintenance!!!
</html>
```

**Comment by Joshua-Anderson** [comment]
Heroku's CLI docs for maintennance mode are [here](https://devcenter.heroku.com/articles/maintenance-mode), for reference. I like this because when deploying you often have to migrate your app, which requires stopping the web server. Giving a nice error page is much better than the a 404 error.

**Comment by gabrtv** [comment]
Big +1 for this.  I don't see this being a big effort either.

**Comment by kalbasit** [comment]
:+1: 

FYI for a client, I solved this by creating a `maintenance` application which is an Nginx serving the maintenance page for any request and then did:

```
deis domains:remove www.example.com -a example && deis domains:add www.example.com -a maintenace
```
