### ISSUE TITLE
deis-builder fails to set keys to etcd

### ISSUE THREAD

**Issue by ngpestelos** [deis/deis#3726]
I've upgraded my cluster from `1.6.0-dev` to `1.7.0-dev`. Most services have started, except for builder and router.

`deis-builder[1]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]`

**Comment by bacongobbler** [comment]
what's the current status of etcd?

**Comment by ngpestelos** [comment]
parse error: Invalid literal at line 1, column 4

**Comment by mboersma** [comment]
Where is that last log coming from, the builder logs? Could you include more context?

**Comment by bacongobbler** [comment]
I'd love to help you, but I need more context :)

**Comment by ngpestelos** [comment]
etcd.service - etcd
   Loaded: loaded (/etc/systemd/system/etcd.service; static; vendor preset: disabled)
  Drop-In: /run/systemd/system/etcd.service.d
           └─20-cloudinit.conf
   Active: active (running) since Mon 2015-04-20 12:12:27 UTC; 4 weeks 2 days ago
 Main PID: 742 (etcd)
   CGroup: /system.slice/etcd.service
           └─742 /usr/bin/etcd

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

**Comment by bacongobbler** [comment]
Looks like etcd is down or not started. I'd start there and see why it failed to start. That parse error doesn't seem to show any bugs in coreos/etcd, but I'd take a look at `journalctl -u etcd` to see why that error occurred.

**Comment by ngpestelos** [comment]
May 19 20:55:58 45.55.160.197 logger:  2015-05-20T03:55:57UTC deis-builder[1]: 2015-05-20T03:55:57Z 0a94b3d0177c confd[234]: ERROR template: builder:79:49: executing "builder" at <getv "/deis/controll...>: error calling getv: key does not exist
May 19 20:55:58 45.55.160.197 logger:  2015-05-20T03:55:57UTC deis-builder[1]: 2015-05-20T03:55:57Z 0a94b3d0177c confd[234]: ERROR template: receiver:15:55: executing "receiver" at <getv "/deis/controll...>: error calling getv: key does not exist
May 19 20:56:03 45.55.160.197 logger:  2015-05-20T03:56:02UTC deis-builder[1]: 2015-05-20T03:56:02Z 0a94b3d0177c confd[234]: ERROR template: builder:79:49: executing "builder" at <getv "/deis/controll...>: error calling getv: key does not exist
May 19 20:56:03 45.55.160.197 logger:  2015-05-20T03:56:03UTC deis-builder[1]: 2015-05-20T03:56:03Z 0a94b3d0177c confd[234]: ERROR template: receiver:15:55: executing "receiver" at <getv "/deis/controll...>: error calling getv: key does not exist
May 19 20:56:08 45.55.160.197 logger:  2015-05-20T03:56:08UTC deis-builder[1]: 2015-05-20T03:56:08Z 0a94b3d0177c confd[234]: ERROR template: builder:79:49: executing "builder" at <getv "/deis/controll...>: error calling getv: key does not exist
May 19 20:56:08 45.55.160.197 logger:  2015-05-20T03:56:08UTC deis-builder[1]: 2015-05-20T03:56:08Z 0a94b3d0177c confd[234]: ERROR template: receiver:15:55: executing "receiver" at <getv "/deis/controll...>: error calling getv: key does not exist
May 20 08:21:22 45.55.160.197 logger:  2015-05-20T15:21:22UTC deis-builder[1]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
May 20 08:21:22 45.55.160.197 logger:  2015-05-20T15:21:22UTC deis-builder[1]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
May 20 08:21:32 45.55.160.197 logger:  2015-05-20T15:21:32UTC deis-builder[1]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

**Comment by ngpestelos** [comment]
No luck getting any logs from `journalctl -u etcd`. Is there a way to force builder to be scheduled to another host?

**Comment by ngpestelos** [comment]
Environment variables (after doing `nse deis-builder`):

HOSTNAME=3b9f0f201977
HOST=10.132.81.194
GITHOME=/home/git
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
GITUSER=git
EXTERNAL_PORT=2223
SHLVL=1
HOME=/root
DEIS_RELEASE=1.7.0-dev

**Comment by ngpestelos** [comment]
I may have found the problem: https://github.com/deis/deis/blame/master/builder/rootfs/bin/boot#L23.

For some reason, the version deployed uses `--no-syncuntil` instead of `--no-sync`.

**Comment by ngpestelos** [comment]
Sorry, I take that back.

**Comment by bacongobbler** [comment]
> No luck getting any logs from journalctl -u etcd

That means it's probably never started on that host. Try `sudo systemctl start etcd` and try journaling the logs again. If no logs show up after that, this might be a good issue to prop up to coreos (etcd failing to come up)

**Comment by ngpestelos** [comment]
OK, will do. Thanks again :)

**Comment by sbuss** [comment]
I ran into this problem today.

Re: this errror:

```
parse error: Invalid literal at line 1, column 4
```

This is because of an error either in `debug-etcd`, or a change in the etcd API.

The `debug-etcd` service looks like this:

```
core@ip-10-128-1-31 ~ $ systemctl cat debug-etcd
# /etc/systemd/system/debug-etcd.service
[Unit]
Description=etcd debugging service

[Service]
ExecStartPre=/usr/bin/curl -sSL -o /opt/bin/jq http://stedolan.github.io/jq/download/linux64/jq
ExecStartPre=/usr/bin/chmod +x /opt/bin/jq
ExecStart=/usr/bin/bash -c "while true; do curl -sL http://127.0.0.1:4001/v2/stats/leader | /opt/bin/jq . ; sleep 1 ; done"
```

Notice that `curl` is piping into `jq`. It turns out that if you `curl -sL http://127.0.0.1:4001/v2/stats/leader` on a non-leader etcd peer, the response is `not current leader`, which `jq` fails to parse with the `invalid literal` error message.

As for the root problem of etcd not setting keys, I am also experiencing this issue on a new 1.7.3 cluster.

**Comment by carmstrong** [comment]
> It turns out that if you curl -sL http://127.0.0.1:4001/v2/stats/leader on a non-leader etcd peer

That's a known issue. I should probably caveat that or handle it in `debug-etcd` so that users aren't confused. We really should have it determine who the current leader is and then hit that endpoint on the appropriate host. @sbuss do you mind opening an issue for that?

> As for the root problem of etcd not setting keys, I am also experiencing this issue on a new 1.7.3 cluster.

Are you also seeing the issue with etcd? How has your cluster been deployed? What platform is it on? It looks like the underlying problem is etcd, but we have accommodated it in various ways through our releases. We *really* need etcd2 :( - #3564

**Comment by mboersma** [comment]
This hasn't had an update in two and a half months, and is unlikely to behave this way with the new builder. Please open a new issue if you see this with a current version of Deis.

**Comment by mattcurrycom** [comment]
Carmstrong, I am experiencing this same issue with getv keys issue.  It is happening in AWS, and I have replicated it 2 times now.  Any ideas on what my be causing this?  How can I fix it after the fact?  Its happening during a deploy.
