### ISSUE TITLE
Using DNS and Azure

### ISSUE THREAD

**Issue by josephwinston** [deis/deis#3731]
Call me clueless, but I don't know where I can put the DNS records provided by `azure-coreos-cluster`.  My google cred is certainly taking a hit, but I'd like an example that I can follow.

**Comment by carmstrong** [comment]
You'll need a domain name you can point to your DNS cluster. A subdomain will do as well.

If you were using `myapps.mydomain.com, for example, you'd configure appropriate records. See http://docs.deis.io/en/latest/managing_deis/configure-dns/ for details.

**Comment by chrisgeo** [comment]
@josephwinston If you use the cluster creation script in deis/contrib/azure it will create a virtual private network for you, including a VIP. That way you only need to point your DNS to that single point and it will take care of the rest.

So if you got: ```11.11.11.11``` just point your dns record: ```foo.app.com``` to it from your provider.

You should see it on the Azure portal under: "Public Vitrual IP (VIP) Address"

**Comment by mboersma** [comment]
This hasn't had an update in three and a half months. Please open a new issue if you see this with a current version of Deis.
