### ISSUE TITLE
deis login - fix "bad request" message to be user readable

### ISSUE THREAD

**Issue by colleen1** [deis/deis#3739]
As a user, I would like a clearer message when my username and/or password fail on login.

Today reads as follows:
 "400 BAD REQUEST
{u'non_field_errors': [u'Unable to log in with provided credentials.']}

Recommended:
"Unable to login: 
The username and password you entered do not match"

SEE image: http://cl.ly/image/143z3J2W202o
![deis be kind](https://cloud.githubusercontent.com/assets/535370/7759834/eb90e4f8-ffc9-11e4-8b98-3b4644d15bed.png)

**Comment by mboersma** [comment]
This is a great point--we just spit out the raw JSON currently. Changing this will involve fixing up some tests and other things, so it's not a simple change, but it's one we should consider doing soon.

**Comment by bacongobbler** [comment]
cc @Joshua-Anderson as he's working on the Go client re-write :)

**Comment by Joshua-Anderson** [comment]
Yeah. I have plans for better parsing errors.
