### ISSUE TITLE
Deis should have a (pliggbable) deploy hooks config method per app

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#3741]
Similar to https://devcenter.heroku.com/articles/deploy-hooks

First version could include HTTP only (exactly my use case), later versions can also integrate with hipchat, campfire, <pick your own> etc...

**Comment by Joshua-Anderson** [comment]
I like the idea! Adding webhook events to the controller could be really useful.

**Comment by bacongobbler** [comment]
dupe of #1486?

**Comment by nathansamson** [comment]
@bacongobbler I guess, I looked for "deploy hooks" but couldn't find anything...  Can be closed for me
