### ISSUE TITLE
deisctl start platform stuck at deis-store-gateway@1.service : activating/start-post

### ISSUE THREAD

**Issue by ainux4mrvce** [deis/deis#3750]
ad@as:~$ deisctl start platform 
● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●

Storage subsystem...
deis-store-monitor.service: active/running                                 
deis-store-daemon.service: active/running                                 
deis-store-metadata.service: active/running                                 
deis-store-gateway@1.service: activating/start-post                                 
deis-store-gateway@1.service: activating/auto-restart                                 
deis-store-gateway@1.service: activating/start-post                                 
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: cancelled
timeout reached
INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: cancelled

i created coreos machine cluster on digital ocean, then i instal deisctl client on my system.
register to the controller. then login to it , uploaded my ssh key, set my domain name, install the deis platform

**Comment by ainux4mrvce** [comment]
core@deis-1 ~ $ fleetctl list-units
UNIT				MACHINE				ACTIVE		SUB
deis-builder.service		103b9ca9.../10.130.127.228	inactive	dead
deis-controller.service		103b9ca9.../10.130.127.228	inactive	dead
deis-database.service		7fc088bd.../10.130.127.230	inactive	dead
deis-logger.service		7fc088bd.../10.130.127.230	inactive	dead
deis-logspout.service		103b9ca9.../10.130.127.228	inactive	dead
deis-logspout.service		7fc088bd.../10.130.127.230	inactive	dead
deis-logspout.service		c732da0d.../10.130.127.229	inactive	dead
deis-publisher.service		103b9ca9.../10.130.127.228	inactive	dead
deis-publisher.service		7fc088bd.../10.130.127.230	inactive	dead
deis-publisher.service		c732da0d.../10.130.127.229	inactive	dead
deis-registry@1.service		7fc088bd.../10.130.127.230	inactive	dead
deis-router@1.service		103b9ca9.../10.130.127.228	inactive	dead
deis-router@2.service		7fc088bd.../10.130.127.230	inactive	dead
deis-router@3.service		c732da0d.../10.130.127.229	inactive	dead
deis-store-daemon.service	103b9ca9.../10.130.127.228	active		running
deis-store-daemon.service	7fc088bd.../10.130.127.230	active		running
deis-store-daemon.service	c732da0d.../10.130.127.229	active		running
deis-store-gateway@1.service	103b9ca9.../10.130.127.228	activating	start-post
deis-store-metadata.service	103b9ca9.../10.130.127.228	active		running
deis-store-metadata.service	7fc088bd.../10.130.127.230	inactive	dead
deis-store-metadata.service	c732da0d.../10.130.127.229	active		running
deis-store-monitor.service	103b9ca9.../10.130.127.228	active		running
deis-store-monitor.service	7fc088bd.../10.130.127.230	active		running
deis-store-monitor.service	c732da0d.../10.130.127.229	active		running
deis-store-volume.service	103b9ca9.../10.130.127.228	activating	auto-restart
deis-store-volume.service	7fc088bd.../10.130.127.230	activating	start-pre
deis-store-volume.service	c732da0d.../10.130.127.229	activating	start-pre

**Comment by carmstrong** [comment]
What does the Ceph health look like? Use the `deis-store-admin` container to run `ceph -s`: http://docs.deis.io/en/latest/troubleshooting_deis/troubleshooting-store/#using-store-admin

**Comment by ainux4mrvce** [comment]
@carmstrong thank you let me check

**Comment by ainux4mrvce** [comment]
actually i restart deisctl so its taking some time

**Comment by ainux4mrvce** [comment]
deisctl install store-admin
Error: failed initializing SSH client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

ssh-add ~/.ssh/deis
Identity added: /home/ad/.ssh/deis (/home/ad/.ssh/deis)
ad@as:~$ deisctl config platform set sshPrivateKey=~/.ssh/deis
Error: failed initializing SSH client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Comment by bacongobbler** [comment]
@ainux4mrvce those issues look like setup issues. Have you taken a read at setting up deisctl at http://docs.deis.io/en/latest/installing_deis/install-platform/#install-the-deis-platform?

once you get that set up, following the documentation that @carmstrong pointed out should get you in the right direction, then we can start to help you from there.
