### ISSUE TITLE
Split user-data into separate files for each service

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3751]
See https://github.com/deis/deis/pull/3716#issuecomment-106017374

Basically, the user-data file is unruly. Adding new units or files to this is difficult to manage.

I'd like to explore creating a new Makefile target like `combine-user-data` which would simply combine all of these files together. `make discovery-url` could depend on this target before it replaces the discovery URL. 

Note that we need to be careful that we don't break the provision scripts in this. I think we should be fine as long as we still ensure users are running `make discovery-url` before running the provision scripts, since this target would also combine the user data pieces.

**Comment by carmstrong** [comment]
I was thinking of a directory structure like:
```
contrib/coreos/units/stop-update-engine.service.yaml
contrib/coreos/files/run-deis-bin-preseed.yaml
...
```

**Comment by croemmich** [comment]
I agree that this would make maintenance a bit easier, however the generated user-data file would still be huge, which doesn't feel like we're solving the real issue... but I don't have a better solution, so I probably can't say much :)

**Comment by nathansamson** [comment]
one problem with putting too much logic in user-data is that it doesn't get updated when upgrading deis releases, unless I am mistaken....

**Comment by mboersma** [comment]
> it doesn't get updated when upgrading deis

You're exactly right, and it is a big reason user-data is problematic for config management.

**Comment by carmstrong** [comment]
> the generated user-data file would still be huge

True, but if the user never sees it, it probably doesn't matter how big it is ;) Making changes in the codebase is the real pain currently.

> it doesn't get updated when upgrading deis

> You're exactly right, and it is a big reason user-data is problematic for config management.

Absolutely. Just not sure there's a better solution currently. :(

**Comment by croemmich** [comment]
I apply some networking and other config in my user-data so I'd still have to maintain a big file :(

**Comment by kalbasit** [comment]
:+1: I do the same and maintaining the user-data is getting a bit heavy

**Comment by aespinosa** [comment]
Since coreos-cloudinit accepts a URL for the location of cloudconfig, maybe we can have the 'bootstrap' user-data just contain a unit that downloads a public cloud-init (released and maintained artifact alongside w/ deis, deisctl and unit files) for bootstrapping all the things that deisctl needs to properly install deis.

**Comment by krancour** [comment]
One potential problem with that is that the etcd discovery URL needs to be included in the etcd section of the userdata.  That means userdata is custom for each cluster.  We couldn't use URL that points to static userdata.  Something more complex would be required.

**Comment by aespinosa** [comment]
I can see the problem with that.

But since user-data would be split anyway, the more static parts can be moved. The the static parts seems to be the bulk of the content now now so the management of that can be simpler.

I'll check if I can make some prototype pull request. I'm thinking something along the lines of

```
coreos:
  etcd2:
   # ... normal things you put here
  fleet:
  #  ...

  units:
    name: bootstrap-deis.service
    content: |
       [Service]
       Type=oneshot
        ExecStart=/usr/bin/cloud-init -from-url=http://deis.io/all-the-big-things-that-used-to-be-in-user-data.yml
```

Are there tests for the user-data stuff that I can validate against when attempting to do this refactoring?

**Comment by krancour** [comment]
Only the integration tests would cover that.

**Comment by bacongobbler** [comment]
@aespinosa to explain a little further, you can try running through the steps at http://docs.deis.io/en/latest/contributing/testing/, specifically [`test-integration-aws.sh`](https://github.com/deis/deis/blob/master/tests/bin/test-integration-aws.sh) which is what is run against all pull requests on https://ci.deis.io/. That would help you validate that the cluster is up and operational :)

**Comment by bacongobbler** [comment]
this isn't something we will able to get for the LTS release. The user-data should be okay to manage while maintaining a few more releases during the LTS, and provisioning Deis v2 will be on a vanilla kubernetes cluster so the user-data is going away. I'm going to go ahead and close this. Thanks!
