### ISSUE TITLE
store-gateway failed to obtain masterLock

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#3754]
For some reason when I was deploying, store-gateway failed to acquire the masterLock even though no other gateway was running.

Symptoms show that the host is being published, but /deis/store/gateway/masterLock, /host or /port were not published:

```
core@deis-01 ~ $ etcdctl ls /deis/store/gateway --recursive
/deis/store/gateway
/deis/store/gateway/hosts
/deis/store/gateway/hosts/172.17.8.102
/deis/store/gateway/accessKey
/deis/store/gateway/secretKey
/deis/store/gatewayKeyring
```

A restart works, but this makes me think that the [`if` logic](https://github.com/deis/deis/blob/master/store/gateway/bin/boot#L89-L90) may be fragile in some cases. The logs didn't show anything, but that's to be expected because we suppress those logs. :cry:

**Comment by bacongobbler** [comment]
this seems different to the other store-gateway related issues like #3750 and #3608 because it only popped up when the builder was starting. This seems more closely related to #3595 since the logs are similar in the registry:

```
ERROR template: create_bucket:10:13: executing "create_bucket" at <getv "/deis/store/ga...>: error calling getv: key does not exist
```

**Comment by mboersma** [comment]
This issue is five months old and I think this was resolved by the deis-builder rewrite to go and the v1.10.1 patch.
