### ISSUE TITLE
git push hangs at `Launching...`

### ISSUE THREAD

**Issue by olalonde** [deis/deis#3755]
Sometimes when I do a `git push deis`, the deploy will be successful but the command won't terminate and just hangs at `Launching...`. deis v1.6.1 on AWS.

What might be causing this problem and is it a deis bug or incorrect configuration on my side?

**Comment by carmstrong** [comment]
Did you perhaps change the ELB timeout? We set it to 20 minutes. The deploy itself usually takes a few minutes where nothing is sent over the wire, so ELB or other load balancers will kill the request to the client.

**Comment by bacongobbler** [comment]
This could also due to the controller detecting that the container is not in a running state (the container exited early). We should be capturing these cases, but that may not be the issue at hand here :)

**Comment by olalonde** [comment]
Oh, it seems the deploy did indeed fail but it's really hard to tell it did:

```
$ deis logs --app=testnet
2015-05-27T22:10:46UTC deis[api]: williamcotton deployed fcad676
2015-05-27T22:13:18UTC testnet[cmd.1]:
2015-05-27T22:13:18UTC testnet[cmd.1]: > bsync@0.0.0 start /src
2015-05-27T22:13:18UTC testnet[cmd.1]: > psy start -n bsync -- node app/cli
2015-05-27T22:13:18UTC testnet[cmd.1]:
```

Also, 

```
$deis releases --app=testnet
=== testnet Releases
v32     30 minutes ago               williamcotton deployed fcad676
v31     Tue 12 May 23:18:51 2015 CST olalonde added DEBUG_COLORS, changed DEBUG
```

If I `deis open`, the server is running correctly.

However, if I ssh into deis and run `fleetctl list-units`, I see

```
$ fleetctl list-units
...
testnet_v31.cmd.1.service       9c69bab3.../10.21.2.122 active          running
testnet_v32.cmd.1.service       9c69bab3.../10.21.2.122 inactive        dead
...
```

```
$ fleetctl journal testnet_v32.cmd.1.service                                                                                       master ✗
-- Logs begin at Tue 2015-05-26 02:11:15 UTC, end at Wed 2015-05-27 22:45:29 UTC. --
May 27 22:13:13 ip-10-21-2-122.ec2.internal sh[18416]: 77af3279dddd: Pulling metadata
May 27 22:13:13 ip-10-21-2-122.ec2.internal sh[18416]: 77af3279dddd: Pulling fs layer
May 27 22:13:16 ip-10-21-2-122.ec2.internal sh[18416]: 77af3279dddd: Download complete
May 27 22:13:16 ip-10-21-2-122.ec2.internal sh[18416]: 77af3279dddd: Download complete
May 27 22:13:16 ip-10-21-2-122.ec2.internal sh[18416]: Status: Downloaded newer image for 10.21.2.122:5000/testnet:v32
May 27 22:13:16 ip-10-21-2-122.ec2.internal systemd[1]: Started testnet_v32.cmd.1.
May 27 22:13:18 ip-10-21-2-122.ec2.internal sh[19256]: > bsync@0.0.0 start /src
May 27 22:13:18 ip-10-21-2-122.ec2.internal sh[19256]: > psy start -n bsync -- node app/cli
May 27 22:13:18 ip-10-21-2-122.ec2.internal docker[19357]: testnet_v32.cmd.1
May 27 22:13:19 ip-10-21-2-122.ec2.internal docker[19366]: testnet_v32.cmd.1
```

In terms of developer UX this isn't great but not sure if it's a "bug".

Is there any way for me to find out 

1) why is `testnet_v32.cmd.1.service` "dead"

2) how to know a deploy failed next time without resorting to `fleetctl list-units`

**Comment by olalonde** [comment]
It seems the problem was that the docker container immediately terminated because `psy` (https://github.com/substack/psy) runs processes in the background.

**Comment by bacongobbler** [comment]
Hmm... Maybe we should add logs directly inside an application's systemd unit to notify that the container has shut down and is booting up as ExecStartPre and ExecStopPost entries.
