### ISSUE TITLE
Deis on Opennebula?

### ISSUE THREAD

**Issue by r4wr** [deis/deis#3756]
Has anyone looked at or currently have a deis deis/coreos running on top of [OpenNebula](http://opennebula.org)? It's our cloud of choice so far and we just started to look at deis as well. I have a mostly working template and coreos image so far for opennebula. I was looking at possibly following the bare metal install/config path in the deis docs to get things going. Any input would be helpful. Thanks!

**Comment by bacongobbler** [comment]
Hey @r4wr! You may get a better chance at a response if you post your question the deis-users mailing list. If you have any specific questions/issues with provisioning on OpenNebula, we'd be happy to help here. FWIW I haven't heard of any other users deploying Deis on OpenNebula.

**Comment by r4wr** [comment]
Will do, thanks!

**Comment by mboersma** [comment]
I see this discussion continued at the [deis-users list](https://groups.google.com/forum/#!topic/deis-users/Okk4o7msSAE), so I'm closing this issue.
