### ISSUE TITLE
Rewrite components in Go so they are resilient, testable, and self-publishing

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3758]
There's been some discussion and debate in #2701 about how to approach refactoring components. The core maintainers had an architectural meeting today and decided to move forward with a Go-based rewrite of the components, with the following goals:
- ~~No more Docker-in-Docker for the builder component -- instead, bind-mount the host's Docker volume so we can use that Docker graph~~ WONTFIX: This introduces security issues (breakouts in container builds can affect the host OS)
- Better log output for components, showing the component's actual status and helpful details when it fails (no more `waiting for confd to write initial templates` as in #2906)
- Components are more easily testable and less fragile (such as builder - see #3578)
- confd runs in-memory, enabling us to vendor some of its code so we can use native templating logic
- Shared Go-based libraries (with unit tests!) for code common among boot scripts
- Boot logic in a component is minimal thanks to the previous point ^
- Cleaner code and improved control flow made possible by use of Go idioms and channels (for example, rewriting the SSL certificate generation logic)

A long-term goal here is to at some point in the future be able to say `docker run -P deis/builder:2.0` and have the component come up and publish itself with everything it needs self-contained.

**Implementation details/questions**
- Do we use go-extpoints or not? An argument against is that it lends itself well to plugins, but that may not be as useful in this implementation

**Bonus**
It would be great to address the following as part of this refactor:
- nginx template rewrite (#3536)
- better handling of Ceph OSD creation errors (#2519)

replaces #2701

**Comment by Joshua-Anderson** [comment]
@carmstrong Awesome!

I see the target for this is `v1.8`, July 6th. 

Since that deadline is coming up fast, I'm guessing that the rewrite will being momentarily.

Since these components are being completely rewritten, I'm guessing you want to avoid feature requests on the affected components for the time being?

**Comment by carmstrong** [comment]
> Since these components are being completely rewritten, I'm guessing you want to avoid feature requests on the affected components for the time being?

Not necessarily at all. This is a longer-running goal. We'll still be adding small features and fixing bugs in components, but yes, probably none that require a major refactor until this work is done.

**Comment by Joshua-Anderson** [comment]
Thank you! I'll keep that in mind.

**Comment by bacongobbler** [comment]
Shall we close this now that most of the components have been rewritten for v2? The builder is also pure Go now, which was the main pain point for most of this.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776), and Deis v2 has rewritten some of the compoenents in Go so I'm going to go ahead and close this.
