### ISSUE TITLE
Operational hardening for large production deployments

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3759]
We've identified various tasks relating to hardening Deis to perform better in large, production deployments. These include:

* Logic and documentation (suggesting best practices) around isolating the Deis control and data planes (#3023, #3679, #3718)
* Preventing out-of-disk-space conditions, such as log rotation or automatic pruning of old release images (#3698, #3716)

**Comment by bacongobbler** [comment]
Maybe we should be using a separate tool like a public [trello](https://trello.com/) board for handling task lists. Github issues works but isn't the *best* tool for the job. Just a suggestion though :)

**Comment by Joshua-Anderson** [comment]
:+1: for a external task list. Much easier to scan and you can enable fun features like voting for most wanted features.

**Comment by carmstrong** [comment]
For now I've just removed the checkboxes ;) I'm a fan of an issue being a definable task. I just haven't fleshed out these other issues yet.

**Comment by krancour** [comment]
Relates to #3718 and #4142

**Comment by bacongobbler** [comment]
closing as irrelevant for [v2](https://deis.com/blog/2016/workflow-stable/).
