### ISSUE TITLE
Idea: update config on push

### ISSUE THREAD

**Issue by scottrobertson** [deis/deis#3765]
For those who commit their .env file, it would be good for deis to update the config on push

**Comment by mboersma** [comment]
I'm not sure we would always want this behavior, and then there would need to be a flag to disable the .env processing... `deis config:push && git push deis master` should do it.

**Comment by bacongobbler** [comment]
agreed.

**Comment by kalbasit** [comment]
it would be cool though to be able to push the config without applying them to the current version, so for example, `deis config:push --no-update && git push deis master` should allow you to publish the configs with a newer version of the code.

**Comment by aledbf** [comment]
> push the config without applying them to the current version

But then the returned information of `deis config:list` is not what is currently running

**Comment by bacongobbler** [comment]
@kalbasit if you can make a compelling use case we may consider it. My first reaction to that was "why would anyone want to push config without publishing it?", but I'd like to hear your thoughts in a proposal in a separate issue. It sounds different than updating config with a .env on push,
