### ISSUE TITLE
`deis run` should support commands longer than 20 minutes

### ISSUE THREAD

**Issue by olalonde** [deis/deis#3769]
So I just ran:

```bash
$ deis run node app/cli/deoptimize-for-catchup.js
Running `node app/cli/deoptimize-for-catchup.js`...

```

The command hangs there (it hasn't terminated, so this is normal) but I'm not seeing any output. However, I can see the command's output using `fleetctl journal`:

```bash
$ fleetctl journal -f livenet_v27.run.8.service
...
May 28 20:12:21 ip-10-21-2-217.ec2.internal systemd[1]: Started livenet_v27.run.8 admin command.
May 28 20:12:23 ip-10-21-2-217.ec2.internal sh[26768]: Creating indexes...
```

Is this expected behaviour?

**Comment by bacongobbler** [comment]
Once the container exits, the output will be displayed to the user. Does that command require input from the user? How is `fleetctl status livenet_v27.run.8` doing?

**Comment by olalonde** [comment]
Ah ok, that makes sense. Is there a technical reason why the output isn't streamed instead so I can see it in real time? I expect the command to take a few hours because it is creating indexes on a large database.

```
core@ip-10-21-2-217 ~ $ fleetctl status livenet_v27.run.8
● livenet_v27.run.8.service - livenet_v27.run.8 admin command
   Loaded: loaded (/run/fleet/units/livenet_v27.run.8.service; linked-runtime; vendor preset: disabled)
   Active: active (running) since Thu 2015-05-28 20:12:21 UTC; 16min ago
...
```

The command doesn't require input from the user but what would happen if it did? Is that supported?

**Comment by bacongobbler** [comment]
> Is there a technical reason why the output isn't streamed instead so I can see it in real time?

It's a limitation of WSGI: https://github.com/deis/deis/issues/117#issuecomment-53226399

> The command doesn't require input from the user but what would happen if it did? Is that supported?

that is being tracked in #117.

> So I guess Deis doesn't support running long lived commands?

It should, but I guess commands running longer than 20 minutes will hit the ELB timeout due to the long-running request. The container itself should still be running though.

**Comment by olalonde** [comment]
Thanks for the quick and helpful answers. One last thing:

> It should, but I guess commands running longer than 20 minutes will hit the ELB timeout due to the long-running request. The container itself should still be running though.

The container didn't keep running. Here's the journalctl log:

```bash
core@ip-10-21-2-217 ~ $ journalctl -u livenet_v27.run.8
...
May 28 20:12:21 ip-10-21-2-217.ec2.internal sh[26675]: Status: Downloaded newer image for 10.21.1.79:5000/livenet:v27
May 28 20:12:21 ip-10-21-2-217.ec2.internal systemd[1]: Started livenet_v27.run.8 admin command.
May 28 20:12:23 ip-10-21-2-217.ec2.internal sh[26768]: Creating indexes...
May 28 20:32:15 ip-10-21-2-217.ec2.internal systemd[1]: Stopping livenet_v27.run.8 admin command...
May 28 20:32:15 ip-10-21-2-217.ec2.internal systemd[1]: Stopped livenet_v27.run.8 admin command.
```

The script should ouptut `Created indexes` or output an error message if there is an error. It should also take a lot longer to run.

**Comment by mboersma** [comment]
There is also a timeout hard-coded to 20 minutes to match [here in the controller](https://github.com/deis/deis/blob/master/controller/templates/gconf.py#L11) unfortunately.

**Comment by olalonde** [comment]
Ah ok, thanks. Any tips on how to run the command directly on CoreOS?

**Comment by olalonde** [comment]
This seems to be working:

```bash
docker run -ti 10.21.1.79:5000/livenet:v27 /bin/bash -c "node app/cli/deoptimize-for-catchup.js"
```

Curiously, `docker ps` was listing `livenet_v27.run.8` and `livenet_v27.run.10`  as `running` but they didn't show up in `fleetctl list-units` or `deis ps`. I'm not too familiar with CoreOS but that looked unexpected so I manually `docker stop`ped them.

```bash
 $ docker ps
CONTAINER ID        IMAGE                         COMMAND                CREATED             STATUS              PORTS               NAMES
00757de0c63d        10.21.1.79:5000/livenet:v27   "/bin/bash -c 'node    24 minutes ago      Up 24 minutes       3000/tcp            livenet_v27.run.10
81e0a11da9cb        10.21.1.79:5000/livenet:v27   "/bin/bash -c 'node    About an hour ago   Up About an hour    3000/tcp            livenet_v27.run.8
```

**Comment by bacongobbler** [comment]
closing as irrelevant for [v2](https://deis.com/blog/2016/workflow-stable/).
