### ISSUE TITLE
Cached repo is not removed from builder when app is deleted

### ISSUE THREAD

**Issue by ineu** [deis/deis#3780]
How to reproduce:
1. Create application named `foo`
2. Push to it to make builder generate /home/git/foo.git
3. Destroy application with `deis apps:destroy`
4. Create application again with the same name
5. Try to push
Outcome: 'remote is up to date'.
Expected: proper push.
What happens is repo not being removed from the builder when application is destroyed.

**Comment by bacongobbler** [comment]
this was fixed recently with https://github.com/deis/deis/pull/3752, but thanks for the report :)

**Comment by ineu** [comment]
Oh, nice, looking forward for 1.7 :)
