### ISSUE TITLE
deisctl stop platform stops at "could not find unit: deis-cache.service"

### ISSUE THREAD

**Issue by olalonde** [deis/deis#3782]
```bash
core@ip-10-21-2-122 ~ $ deisctl stop platform
● ▴ ■
■ ● ▴ Stopping Deis...
▴ ■ ●

Routing mesh...
deis-router@2.service: inactive/dead
deis-router@1.service: inactive/dead
deis-router@3.service: inactive/dead
Data plane...
deis-publisher.service: inactive/dead
Control plane...
deis-database.service: inactive/dead
deis-registry@1.service: inactive/dead
deis-builder.service: inactive/dead
deis-controller.service: inactive/dead
could not find unit: deis-cache.service
```

**Comment by mboersma** [comment]
That probably means that you are using `deisctl` 1.5.x with a git checkout of master code. deis-cache is not installed by default any longer, but your version of `deisctl` expected it to be there.

**Comment by olalonde** [comment]
Oh, I recently upgraded to `1.6.1`.

```bash
core@ip-10-21-2-122 ~ $ deisctl config platform get version
v1.6.1
core@ip-10-21-2-122 ~ $ deisctl --version
1.4.1
```

How can I upgrade `deisctl` from a CoreOS machine?

**Comment by bacongobbler** [comment]
@olalonde there's a comment on http://docs.deis.io/en/latest/installing_deis/install-deisctl/#run-the-installer about installing deisctl on CoreOS

**Comment by mboersma** [comment]
@olalonde I'm going to close this issue, but please re-open it if there is more we can help with.
