### ISSUE TITLE
Support multiple store-gateways running simultaneously

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3784]
Both the `registry` and `database` components use the `store-gateway` to store their persistent data. With a large amount of data, we've seen the gateway fall over in some cases (#3479). We implemented multiple gateways in #2929, but there is a `masterLock` mechanism which ensures only one is serving traffic at any one time.

We should investigate supporting multiple gateways running at once. This involves removing the `masterLock` logic, changing the host/port publishing path of the components, and changing `router` to template multiple gateway upstreams.

Some considerations:
- Does it cause problems that all of the containers use the same hostname (`deis-store-gateway`)?
- Is there a possible conflict if the registry and database are talking to different gateways, but modifying the same objects in Ceph via the S3 API?

**Comment by carmstrong** [comment]
@johanneswuerbach Brought up the great point that traffic to `store-gateway` is currently internal on the cluster, even though it's accessible at `store.<DOMAIN>`. We would have to route traffic to the gateway out through the routers if we wanted to take advantage of having multiple gateways.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant so I'm closing this.
