### ISSUE TITLE
etcdctl fails to set keys during provisioning

### ISSUE THREAD

**Issue by mboersma** [deis/deis#3790]
Testing showed that often on vagrant, and occasionally on EC2, the `boot` scripts of controller, builder, or database can somehow get to the `confd --onetime` section without actually having set keys or created etcd dirs with `etcd_safe_mkdir` or `etcd_set_default`. The user-visible symptom is that builder loops forever, waiting for `confd` templating, and eventually goes into `activating/auto-restart` status.

**Comment by bacongobbler** [comment]
#3791 helps us identify the root issue (seems to be the infamous `All the given peers are not reachable` error), but I'll re-open this once it's merged since it won't fix the root issue.

**Comment by carmstrong** [comment]
> I'll re-open this once it's merged

I think if you edit #3791 to remove the "closes", it shouldn't close this once it's merged.

**Comment by bacongobbler** [comment]
apparently that did the trick! That used to be a bug in github but I guess they fixed that. Thanks!
