### ISSUE TITLE
Stopping Swarm when Swarm is disabled causes a hang in deisctl

### ISSUE THREAD

**Issue by technosophos** [deis/deis#3793]
When I run `deisctl stop swarm` on a platform that does not have Swarm enabled, `deisctl` hangs:
```
⇒  deisctl stop swarm
● ▴ ■
■ ● ▴ Stopping Swarm...
▴ ■ ●

swarm nodes and swarm manager
could not find unit: deis-swarm-node.service
<CTRL-C>
```

**Comment by bacongobbler** [comment]
deisctl hangs on every error, actually. We should be exiting non-zero when these errors occur. I recall that there was some clunky logic in deisctl that causes it to be this way.

**Comment by technosophos** [comment]
Yeah, the hanging is caused by a blocking channel. The exit code is a separate problem -- it always exits 0.

**Comment by kalbasit** [comment]
Ok so I see the problem now.

Calling deisctl stop, call [`b.Stop`](https://github.com/deis/deis/blob/master/deisctl/backend/fleet/stop.go#L12) which in turn calls [`b.doStop`](https://github.com/deis/deis/blob/master/deisctl/backend/fleet/stop.go#L27). If an error happened in their, it wants to send an error to the errorChan.

On the other end, the stop call also starts a goroutine for [`printState`](https://github.com/deis/deis/blob/master/deisctl/cmd/cmd.go#L461) which can return if it receives an empty output. The goroutine should only return if one (or both) of the channels are closed.

**Comment by kalbasit** [comment]
@bacongobbler is there a reason why we enforce a delay between [channel receiving](https://github.com/deis/deis/blob/master/deisctl/cmd/cmd.go#L476)?
