### ISSUE TITLE
config:push with .env doesn't handle export or double quotes

### ISSUE THREAD

**Issue by glenwong** [deis/deis#3796]
If you have environment variables in your .env file that are surrounded by double quotes or start with an export they aren't handled correctly when pushed to deis. For example:

export REDIS_URL="redis://localhost:6379"

ends up as

export REDIS_URL: "redis://localhost:6379"

Where "export REDIS_URL" is the key and the value is still surrounded by double quotes which can then cause things to fail when the config is referenced.

**Comment by mboersma** [comment]
Are env vars containing spaces in their names legal on Heroku? If not, we should tighten the .env file validation rules; if so, we should probably document `config:push` and `config:pull` behavior more specifically around this case.

**Comment by bacongobbler** [comment]
same answer as I laid out in https://github.com/deis/deis/issues/4512; we should move to a shared library or follow the spec laid out in https://github.com/bkeepers/dotenv#usage.

**Comment by deis-admin** [comment]
This issue was moved to deis/workflow-cli#289
