### ISSUE TITLE
Rewrite client in Go with proper unit tests

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3806]
The Python client is a nuisance to maintain and would be much better as a Go-based client in the vein of `deisctl`. We should rewrite it in Go with a test-driven approach so we have proper unit test coverage.

Replaces #2392, #2885

**Comment by aledbf** [comment]
this could also solve #2680 using https://github.com/docker/docker/blob/master/graph/push.go#L497

**Comment by Joshua-Anderson** [comment]
Go client is now on par, feature wise, with the python client.
