### ISSUE TITLE
TTY broker component

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3808]
Currently, the platform doesn't have the ability to support long-running sessions. To support features on the open roadmap like interactive `deis run` (#117) and `deis logs -f` (#465), we'll need to create a new Go-based component that is responsible for creating long-lived websocket sessions.

**Comment by bacongobbler** [comment]
Closing as kubernetes has exec and tailing log support, so we should be able to ride on their coattails. If not then let's open up a proposal on deis/controller for #117 and #465.
