### ISSUE TITLE
Deis networking V2

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3812]
There are fundamental but breaking improvements to the Deis platform and the way components communicate that will likely necessitate a Deis v2.0 release. These changes include:

- Overlay network
- ~~Internal service discovery (#3072)~~
- Migration strategy to networking v2

**Comment by carmstrong** [comment]
We decided to drop internal service discovery from this requirement, and instead consider networking v2 the introduction of the overlay network in #3868.

**Comment by mboersma** [comment]
Deis will have flannel in v1.9 thanks to #4103.
