### ISSUE TITLE
Upgrade registry to docker-registry v2 (Docker Distribution)

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3814]
There are several issues relating to registry performance (#3580, #3479).

We should upgrade to the Go-based rewrite of the [official Docker registry](https://docs.docker.com/registry/), which is now called [Docker distribution](https://github.com/docker/distribution). We'll also need to patch in our changes to support the `deis pull` workflow.

Additionally, there is also a [native driver](https://github.com/docker/distribution/blob/master/registry/storage/driver/rados/rados.go) to consume Ceph RADOS which is likely going to be significantly more performant than our current S3-on-Ceph implementation. We should investigate this, although it is likely to complicate our upgrade path.

Upgrading to registry v2 also allows us to support Docker 1.6-built images, resolving issues like #3550.

**Comment by mboersma** [comment]
Using registry:2.0.1 requires a rewrite of the code in controller/registry/private.py to use the much different Docker Registry v2 API. I'm not sure that our current approach for appending a "last-mile" layer to the image will work with the new Docker image format: there is no "upload layer with JSON metadata" endpoint, only a way to upload blobs already created by Docker.

**Comment by aledbf** [comment]
@mboersma this is the PR in the new registry that could help for "the last-mile" https://github.com/docker/distribution/pull/610 but is not ready (yet)

**Comment by fabiob** [comment]
@mboersma, where can I find more about the "last-mile" thing deis need?

Can't we just make `deis-builder` append a few lines on the Dockerfile, just before building?

**Comment by Machool** [comment]
@mboersma , do you know when registry v2 will be available in deis? is it in 1.10.0?

**Comment by SomeoneWeird** [comment]
Is there any update on this?

**Comment by pomke** [comment]
considering dockerhub etc have now moved on from the older version, and it's becoming difficult to setup the older docker registry (docs are vanishing, etc), this unresolved issue makes deis unfortunately a non-viable-solution for it's primary use case (running pre-built docker images).   I realise that existing users are happy with their old/working deployments but for new people deis is a non-operational death-star. :/

**Comment by lorieri** [comment]
@mboersma https://github.com/docker/distribution/issues/422

**Comment by mboersma** [comment]
@lorieri exciting! This is actually implemented now in 2.1.1, right? I may not be able to hook up delete right away, but at least the potential is there to keep deis-registry storage from growing forever.

**Comment by mboersma** [comment]
The two difficulties currently are:
- Docker's manifest signing requires JWK signing with x.509 in a [libtrust](https://github.com/docker/libtrust) chain, which looks difficult from the controller Python code
- Assuming those difficulties can be worked out, using registry v2 internally will still be blocked by docker/docker#9718

**Comment by bacongobbler** [comment]
> Docker's manifest signing requires JWK signing with x.509 in a libtrust chain, which looks difficult from the controller Python code

Would it be easier to migrate over to plugging into a Docker engine instead so we don't have to maintain these registry module hacks? If it's 95% of the way done then it might not be worth switching over at this point but it might make things more maintainable in the future (e.g. if Docker changes libtrust in a future release).

**Comment by mboersma** [comment]
> Would it be easier to migrate over to plugging into a Docker engine instead...

Yes indeedy, but bundling D-in-D into deis-controller has some big tradeoffs. It would be simpler IMHO to move this responsibility to builder, but triggering builder from controller in the event of `deis config:set` has architectural and security implications that need to be thought through.

Using `docker` directly is the way to go, I agree. Even if we can push through with this mini-client implementation in python, it will break when the Docker image format v2 is adopted (currently registry v2 uses what it calls a v1 provisional format). Then we scramble to update these registry module hacks again, as you pointed out.

**Comment by mboersma** [comment]
Also, here's a way we can continue to work around the Docker simultaneous pull bug:
- continue to build and push Deis components with Docker 1.5.0, ensuring they are distributed from the "classic" registry v1 side of hub.docker.com
- use [`flock`](https://github.com/coreos/bugs/issues/377#issuecomment-112506058) in Deis-generated systemd app units to serialize `docker pull` access if deis-registry is v2

**Comment by bacongobbler** [comment]
> Yes indeedy, but bundling D-in-D into deis-controller has some big tradeoffs. It would be simpler IMHO to move this responsibility to builder, but triggering builder from controller in the event of deis config:set has architectural and security implications that need to be thought through.

I believe @smothiki is looking to run a docker engine outside of builder that would be accessible to all platform components, so it might be useful to sync up with him to see if you can abuse that and make your life a little easier :)

For the second point about simultaneous pulls failing, `flock` may be a good interim solution so we can keep up-to-date with security fixes in Docker. I have a faint feeling that they'll kill off the v1 registry after a while @ DockerHub so it's probably worth gettin' with the times.

**Comment by smothiki** [comment]
We are actually trying to avoid registry for building buildpack apps. But for dockerfile apps currently running docker 1.5.0 inside qemu. We had issues running latest docker as we have encountered a race condition while pulling images. 
I'm in for pointing docker client to remote docker engine rather than running on qemu (which is slow).

**Comment by jchauncey** [comment]
I honestly think mounting in the docker sock or the docker binary is an acceptable solution. Trying to provide a DinD experience with several layers of indirection will only make debugging issues harder in the future.

**Comment by smothiki** [comment]
For now we are thinking decoupling the builder, build pack apps doesn't have to deal with any of these issues. But we are evaluating options for building dockerfiles. bind mounting docker sock is one of them.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776), but we are running the new registry in Deis v2. Closing!
