### ISSUE TITLE
deis login error 

### ISSUE THREAD

**Issue by ainux4mrvce** [deis/deis#3817]
i create droplet on digitalocean, then install deis and start the platform till day before yesterday i am able to login using deis-client but from yesterday when ever i am trying this command:
 "ad@as:~$ deis login http://deis.paas.deeproot.in"   its shows this error

<h2>_error:
http://deis.paas.deeproot.in does not appear to be a valid Deis controller.
Make sure that the Controller URI is correct and the server is running.

<h2>Specific Error: ('Connection aborted.', error(110, 'Connection timed out'))_

<h1>_my dig result is_ 

ad@as:~$ dig deis.paas.deeproot.in

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> deis.paas.deeproot.in
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40304
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 8, ADDITIONAL: 3

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;deis.paas.deeproot.in.		IN	A

;; ANSWER SECTION:
deis.paas.deeproot.in.	300	IN	A	128.199.81.209
deis.paas.deeproot.in.	300	IN	A	128.199.134.109
deis.paas.deeproot.in.	300	IN	A	128.199.214.66

;; AUTHORITY SECTION:
in.			68113	IN	NS	ns7.cdns.net.
in.			68113	IN	NS	b1.in.afilias-nst.in.
in.			68113	IN	NS	a0.in.afilias-nst.info.
in.			68113	IN	NS	a1.in.afilias-nst.in.
in.			68113	IN	NS	b2.in.afilias-nst.org.
in.			68113	IN	NS	c0.in.afilias-nst.info.
in.			68113	IN	NS	a2.in.afilias-nst.info.
in.			68113	IN	NS	b0.in.afilias-nst.org.

;; ADDITIONAL SECTION:
b1.in.afilias-nst.in.	23614	IN	AAAA	2404:a800:2:1e::19:90
ns7.cdns.net.		43589	IN	AAAA	2001:678:4::7

;; Query time: 1370 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Mon Jun 08 09:34:55 IST 2015
;; MSG SIZE  rcvd: 351

what is this problem and what should i do to resolve it.

**Comment by ainux4mrvce** [comment]
i am not able to do ssh to any of three node

**Comment by ainux4mrvce** [comment]
hi <h3>bacongobbler
plz help me out

**Comment by bacongobbler** [comment]
It looks like your nodes aren't up:

```
ping -c 5 128.199.134.109
PING 128.199.134.109 (128.199.134.109): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
^C
--- 128.199.134.109 ping statistics ---
5 packets transmitted, 0 packets received, 100.0% packet loss
```

I'd take a look into why your nodes are down.

**Comment by ainux4mrvce** [comment]
@bacongobbler  thanx sir it was not running

**Comment by ainux4mrvce** [comment]
hi @bacongobbler 
<h3>i used all these steps 
$ gem install docl
$ docl authorize
$ docl upload_key deis ~/.ssh/deis.pub
$ # retrieve your SSH key's ID
$ docl keys
deis (id: 12345)
$ # retrieve the region name
$ docl regions --metadata --private-networking
Amsterdam 2 (ams2)
Amsterdam 3 (ams3)
London 1 (lon1)
New York 3 (nyc3)
Singapore 1 (sgp1)
$ ./contrib/digitalocean/provision-do-cluster.sh nyc3 12345 4GB

<h3> then ssh to core@deis.paas.deeproot.in
it gives 

<h2> CoreOS stable (647.2.0)
<h2>Failed Units: 1
<h2>oem-cloudinit.service

**Comment by bacongobbler** [comment]
did you run `make discovery-url` before provisioning the nodes? You can check why cloudinit failed with `sudo journalctl -u oem-cloudinit` on the host.

**Comment by ainux4mrvce** [comment]
My cloud config file had error. I corrected it using cloud validator..

**Comment by bacongobbler** [comment]
all righty. Are you able to connect to your cluster now? :)

**Comment by ainux4mrvce** [comment]
yes sir, i do. thanx for kindness. your always there whenever i needed you thanx a lot

**Comment by bacongobbler** [comment]
You're very welcome! :)

I'm gonna close this but please feel free to re-open or open another issue if needed, and we'll take a look into it. Thanks!
