### ISSUE TITLE
Multiple clusters for dev, staging, and production?

### ISSUE THREAD

**Issue by glenwong** [deis/deis#3823]
Does anyone have any strategies they use for deploying the same deis app across multiple clusters? I stumbled across #1155 but the suggested fix of using the --cluster flag doesn't seem to appear anywhere in the documentation.

**Comment by mboersma** [comment]
@glenwong maybe this question is better suited to the [deis-users](https://groups.google.com/forum/#!forum/deis-users) mailing list? You would probably get better responses there.

**Comment by mboersma** [comment]
I'm going to close this as it hasn't had any followup in several weeks, and may be better suited for discussion on the [deis-users](https://groups.google.com/forum/#!forum/deis-users) mailing list.
