### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by ainux4mrvce** [deis/deis#3825]
hi @bacongobbler  i already have ruby on rails project running on my local system. how to write dockerfile and what are thing need to deploy rails-apps using deis

**Comment by bastilian** [comment]
This should give you a good start to develop and deploy your application with docker: https://robots.thoughtbot.com/rails-on-docker

The post references **fig**, which has become [docker-compose](https://docs.docker.com/compose/) and it is used to spin up two containers one database container and one container with the actual application environment. Note that when deploying to deis a database container won't be started as `docker-compose.yml` is not used.

**Comment by bacongobbler** [comment]
@ainux4mrvce does @bastilian's answer help give you some insight on how to start working with Dockerfiles?

**Comment by ainux4mrvce** [comment]
@bacongobbler not exactly sir.

**Comment by bacongobbler** [comment]
While this isn't necessarily a deis-specific question, here's some further documentation on getting started with Rails and Docker:

https://robots.thoughtbot.com/rails-on-docker
http://docs.docker.com/compose/rails/

Most of the documentation explains how you can get started with Dockerfiles. I'd take a look at the oodles of documentation out there with Docker :)

If you have further starting questions, try checking out the [docker-user](https://groups.google.com/forum/#!forum/docker-user) mailing list. :)

**Comment by ainux4mrvce** [comment]
@bacongobbler thanx again i'll do that
