### ISSUE TITLE
404 after upgrading to 1.7.0

### ISSUE THREAD

**Issue by aendrew** [deis/deis#3827]
This may be related to #3819, but am thinking not because I can deploy without a problem.

Recently, I upgraded from 1.2.x to 1.6.1 and then today from 1.6.1 to 1.7.0 (using the "in-place upgrade" instructions for both). Alas, despite being able to deploy without problem, all of my apps now 404 (Including Deis' own example-nodejs-express, which I just deployed).

`fleetctl list-units` shows everything up. Looking through the logs for the router doesn't reveal anything obvious, except the following, which might have been while I was upgrading:

```
Jun 09 12:18:19 ip-10-21-2-14.eu-west-1.compute.internal sh[2486]: [INFO] - 2015/06/09 12:18:19 [emerg] 742#0: invalid port in upstream "10.21.1.64:" in /opt/nginx/conf/.nginx.conf159700271:164
Jun 09 12:18:19 ip-10-21-2-14.eu-west-1.compute.internal sh[2486]: 2015-06-09T12:18:19Z 9cffb69233b8 confd[47]: ERROR Config check failed: exit status 1
```

Yet if I do `deis logs`, it seems the application is up and running and everything's fine.

Any suggestions?

**Comment by Joshua-Anderson** [comment]
I think this is related to #3819 but what is interesting is you can still push.

**Comment by gabrtv** [comment]
@aendrew Apologies for the disruption.  In the meantime please try this as a workaround:

```console
$ deisctl config set publisher image=deis/publisher:v1.6.1
$ deisctl restart publisher
```

.. then wait 10s or so and retry access your deployed apps.

**Comment by aendrew** [comment]
@gabrtv Thanks for getting back to me! I'm trying that, but all I get is the usage instructions — 
```
Usage:
  deisctl config <target> get [<key>...]
  deisctl config <target> set <key=val>...
```

**Comment by gabrtv** [comment]
Sorry, syntax problem in my comment:

```console
$ deisctl config publisher set image=deis/publisher:v1.6.1
$ deisctl restart publisher
```

**Comment by aendrew** [comment]
@gabrtv Amazing, my stuff's back up! Thanks a million! :+1:

**Comment by bacongobbler** [comment]
`deisctl config publisher set image=deis/publisher:v1.6.1` is the correct usage. There seems to be some race condition in publisher that was introduced which is hard to track down.

**Comment by bacongobbler** [comment]
Let's close this since we're tracking the problem in #3819. That way we can keep it all in one place. Thanks!

**Comment by aendrew** [comment]
@bacongobbler Awesome. Thanks a bunch!
