### ISSUE TITLE
Upgrade docs don't mention PROXY protocol support changes

### ISSUE THREAD

**Issue by mboersma** [deis/deis#3829]
Deis v1.4 introduced changes to provisioning and to the ELB for PROXY protocol support, but the only upgrade reference I see for users coming from earlier versions is here: https://github.com/deis/deis/pull/2717#issue-51572755

We should have a section describing those steps more clearly in the "upgrading Deis" document.

**Comment by jwaldrip** [comment]
:+1:

**Comment by jeff-lee** [comment]
It looks like this change breaks ssl termination on the load balancer.  I believe crigor is going to open a ticket to change the load-balancer configuration [docs](http://docs.deis.io/en/latest/managing_deis/ssl-endpoints/#installing-ssl-on-a-load-balancer), but I think it probably deserves a callout in the upgrade instructions that 1.7 requires that SSL certs be uploaded to the routers now.

**Comment by carmstrong** [comment]
> It looks like this change breaks ssl termination on the load balancer.

Sorry for the confusion! I was under the impression based on my understanding of #3096 that termination *may* occur on the routers now, not that it's required. But it sure looks like it is...

@johanneswuerbach any ideas?

**Comment by johanneswuerbach** [comment]
Yes, SSL termination on the elb should still work when proxy protocol is disabled.
