### ISSUE TITLE
Pull new versions of deis in advance?

### ISSUE THREAD

**Issue by ineu** [deis/deis#3839]
When Deis is upgraded, most time is spent pulling new images. It would be great to have an ability to pull new images on all hosts in the cluster before issuing `deisctl stop platform`, so `start platform` would be much faster.

**Comment by carmstrong** [comment]
See http://docs.deis.io/en/latest/managing_deis/production_deployments/#preseeding-containers

**Comment by ineu** [comment]
Yes, like that, but this script downloads images for currently running version of Deis. Upgrade docs suggest to stop platform first and update /deis/platform/version afterwards. It means that during preseeding whole cluster will be down, like:
1. `deisctl stop platform` (apps are not responding now)
2. `deisctl config platform set version`
3. run preseed on each hosts (takes a while, apps are still not responding)
4. `deisctl install && deisctl start`.
What I propose is to force preseed for release to be installed *before* stopping old platform to minimize downtime while performing upgrade.

**Comment by carmstrong** [comment]
> What I propose is to force preseed for release to be installed before stopping old platform to minimize downtime while performing upgrade.

Ah, okay. Well, you could set the platform version (`deisctl config platform set version`) to the new release version before running the preseed script. This config value is only checked when a component service first starts up, so as long as you don't have host failure during that time (which would cause components on the new host to use the new version), you would be fine.

You could always set the version back to the previous release until you're ready to actually perform the upgrade.

**Comment by ineu** [comment]
I see. So it's
1. set platform version to the new release
2. run preseed on every machine
3. perform platform uninstall && stop && install && start

What do you think about adding some command like `deisctl preseed <version>` to call preseed with version argument, in which case it could skip checks for /deis/platform/version? Then upgrade could be like (from 1.6.0 to 1.7.0)
```
curl -sSL http://deis.io/deisctl/install.sh | sh -s 1.7.0
export DEISCTL_TUNNEL=...
deisctl preseed 1.7.0 # fetches images on all nodes, takes a while, cluster is up
deisctl stop platform && deisctl uninstall platform
deisctl install platform && deisctl start platform # should be much faster as images are already downloaded
```
And, as images will already be preseeded, we won't need to do run it after installation.

**Comment by mboersma** [comment]
I disagree that most of the time is spent pulling Docker images when upgrading (or provisioning from scratch). Unless your net connection is really slow, it's more likely to be deis-builder startup consuming most of that time, and unfortunately that won't benefit much from pre-seeding `deis/builder:v1.7.0`. Most of its startup time happens *after* that image is already resident. (And in v1.7.0 all images but deis-store-* are significantly smaller than before thanks to `alpine:3.1`.)

So I can see how a `deisctl preseed` command could help, I just don't think it would help nearly as much as you expect. And you can already accomplish the same by using the existing `preseed` script as @carmstrong noted.

@ineu if you were able to try the preseed script as suggested, did it make a dramatic difference? I'd be happy to guess wrong about this. :smile: If not, I'm not sure it would be worth adding something like `deisctl preseed`.

**Comment by ineu** [comment]
> And in v1.7.0 all images but deis-store-* are significantly smaller than before thanks to alpine:3.1

Probably yes, I was mostly talking from my experience going through versions from 1.4, when there was ubuntu image. With tiny images it shouldn't be a problem anymore.
What bothers me is extra work happening after platform stop. I believe there was a ticket about stopping deis-routers as soon as possible, maybe it would also help a lot.

**Comment by ineu** [comment]
Another usecase for early preseed: trying to upgrade to 1.7.2 now. Docker pulls are extremely slow for me. So in case docker hub is down or slow, it is almost impossible to upgrade. It may also be not possible to run previous version of Deis if preseed wasn't run before, as some images may be absent.
So preseed is vital for reliable work, as unresponsive Docker Hub may break cluster any minute.

**Comment by bacongobbler** [comment]
deisctl is going away in Deis v2 and I don't think we will be able to get to this for the LTS release so I'm going to go ahead and close this. Thank you for the report though!
