### ISSUE TITLE
Client may break if enforceHTTPS=true and the client config points to http

### ISSUE THREAD

**Issue by etcinit** [deis/deis#3849]
On Deis 1.7.1: After enabling HTTP redirection through `deisctl`, some commands on the Deis client, like `deis scale`, stopped working (POST requests) with the following error:

```
$ deis scale web=2
Scaling processes... but first, coffee!
405 METHOD NOT ALLOWED
Detail:
Method 'GET' not allowed.
```

Manually updating the `~/.deis/client.json` file to use https fixes the issue.

**Comment by mboersma** [comment]
The python client is deprecated and will be removed with the v1.10.0 release. If you see similar issues with the new go CLI, please open a new issue.
