### ISSUE TITLE
Proposal integrating kubernetes with deis

### ISSUE THREAD

**Issue by smothiki** [deis/deis#3850]
Once we start a CoreOS machine with flannel, an overlay network is created for containers. Each container gets a unique IP address.
Here are some changes and proposals :
1. The app container port shouldn't be bind-mounted
2. Publisher should be able to publish the container IP as well as the port
3. The only relevant JobStates are Up, Destroyed, Crashed, Error
4. Scale logic should move from models.py to each scheduler backend
5. Template the user-data to allow custom flannel interfaces and IPs, like "make discovery-url" does
6. Give deis-registry a unique hostname URL, or run it on every host
7. Create a Kubernetes service for each app and let the router read from etcd endpoint of the service. This should avoid writing a custom publisher for Kubernetes.

**Comment by aledbf** [comment]
It makes sense the use of deis-publisher in kubernetes? the `expose rc` from kubernetes achieves the same thing and it uses a dedicated ip address and port.

In 7. you mentioned read the kubernetes service located in etcd and that is in json format. I don’t know if confd can read and filter json from etcd

**Comment by gabrtv** [comment]
Kubernetes _should_ allow us to deprecate the publisher component.  Ideally we would update the router via the `/registry/services/<namespace>/<service-name>` keyspace.

Overall, the strategy should be to use everything that Kubernetes gives us.  The less we have to worry about in Deis (i.e. publisher, rolling upgrades, replication control, internal discovery) the better.

**Comment by smothiki** [comment]
Kubernetes Supports both Cpu shares and #cpus. I think we should support same 
something like 
```
$ deis limits:set -cs <type>=1000 ---- for cpuShares which supports integer values of Cpus shares
$ deis limits:set -c <type>=1.2 ---- for #cpu which support float value of cpus 
```

**Comment by carmstrong** [comment]
@smothiki How would this work for non-Kubernetes schedulers? having both of these flags may not make sense unless we make it clear that they're unsupported for some schedulers.

**Comment by smothiki** [comment]
its not specific to kubernetes. Some scheduler take cpu-shares (fleet) and some take #cpus ( kubernetes, marathon, swarm) and right now we are supporting integer values of CPUS. So while running an app unit ( container or pod) we cannot give fractional values of Cpus like 0.5 or 1.3. If we change the value to float CpuShares cannot accept float and error out. So solution would be to implement two options one to take cpus and other to take cpu shares

**Comment by bgrant0607** [comment]
@smothiki It's important to distinguish the API/model from the implementation. Kubernetes supports cpus. We currently translate cpus into shares, but plan to enhance the implementation in the future, such as using cpu masks and/or throttling to provide greater isolation for latency-critical applications. Some discussion of future extensions can be found in:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/resources.md
https://github.com/GoogleCloudPlatform/kubernetes/issues/147
It's also worth looking at our prior work:
http://static.googleusercontent.com/media/research.google.com/en/us/pubs/archive/43438.pdf
https://github.com/google/lmctfy

If shares are exposed directly, it's pretty important to have some notion of how many total shares should be allocated on a single node. Otherwise, performance can degrade arbitrarily once a node is significantly oversubscribed.

Also, while we support expression of resource values using floating-point values, we represent the values using integers internally. Using floating point to represent cpu caused us significant grief in Borg.

**Comment by smothiki** [comment]
Specifying ports on before hand avoid calls to k8s apiserver and docker engine to inspect ports 
1. if no ports are specified default is 5000
2. deis create --app=<name> --ports=["x","Y","Z",]

**Comment by bacongobbler** [comment]
> 3. The new App object model will have scale method something like deis scale ++ , --, +X, -X

While that's certainly a useful feature, I think we should keep that feature out of this so that the amount of code review required is kept at a minimum. :)

**Comment by aledbf** [comment]
> 2. deis create --app= --ports=["x","Y","Z",]

this will work with a Dockerfile deploy or deis pull? If the user sets the wrong port it will never work?

>  deis scale ++ , --, +X, -X

why this change?

**Comment by smothiki** [comment]
@bacongobbler  correct but k8s will be developed in multiple stages.. So first its a release tech preview and then might be production ready beta or some other iterative stage. So release preview just focuses on getting k8s ready with existing features. Just to keep track of what ever features that are possible.

**Comment by bacongobbler** [comment]
> this will work with a Dockerfile deploy or deis pull? If the user sets the wrong port it will never work?

Yes. If the user fails to set this up for Dockerfiles/`deis pull` and their app does not listen on port 5000, the app won't be routed. From my understanding, the proposed kubernetes integration needs to know about what ports the app exposes beforehand so we can set up the replication controllers on `deis create`.

**Comment by smothiki** [comment]
@aledbf we create a k8s service for each app and router routes the traffic to that end point. If the ports are not specified it involves multiple API calls to get what port the app is listening on and creating a service. Specifying ports on before hand avoids 3 API calls atlest. Kind of performance improvement.

**Comment by smothiki** [comment]
closing this in favor of https://github.com/deis/deis/pull/3975
