### ISSUE TITLE
Admins should be able to delete users

### ISSUE THREAD

**Issue by crigor** [deis/deis#3851]
On 1.7.1, it looks like you have to know the password of the user when using `deis auth:cancel`.

As an admin, you should be able to delete users even without knowing their passwords.

**Comment by bacongobbler** [comment]
I think the reasoning behind this is that the /auth/cancel endpoint requires the authenticated user's token, meaning that you can only cancel your own account. I agree that administrators should be able to cancel accounts.

**Comment by croemmich** [comment]
Along with with, I don't think it is possible to change a user's password with out their current one, which makes password resets a pain.

**Comment by carmstrong** [comment]
> I don't think it is possible to change a user's password with out their current one,

Maybe we should close this in favor of a new meta-issue around admin permissions for `deis:users`. They should be able to pretty much do whatever they want.

**Comment by bacongobbler** [comment]
@croemmich I've opened #3889 to track your other issue.
