### ISSUE TITLE
deisctl installation script output is not colorized in bash or zsh

### ISSUE THREAD

**Issue by ineu** [deis/deis#3852]
```
> $ curl -sSL http://deis.io/deisctl/install.sh | sh -s 1.7.1
...

\033[0;36mdeisctl\033[0m is in the current directory and unit files are
in /home/ineu/.deis/units. Please move \033[0;36mdeisctl\033[0m to a
directory in your search PATH.

See http://docs.deis.io/ for documentation.

> $ echo $TERM                
xterm
```

**Comment by ineu** [comment]
Same for deis-cli:
```
Verifying archive integrity... All good.
Uncompressing Deis CLI  100%  

\033[0;36mdeis\033[0m is in the current directory. Please
move \033[0;36mdeis\033[0m to a directory in your search PATH.

```

**Comment by ineu** [comment]
That's interesting, I've just set up VM with Debian 8, and colors seem fine there.

**Comment by ineu** [comment]
So the problem here is that `echo` is called without  `-e` flag:
```
script="echo    && echo '\033[0;36mdeis\033[0m is in the current directory. Please'     && echo 'move \033[0;36mdeis\033[0m to a directory in your search PATH.'        && echo         && echo 'See http://docs.deis.io/ for documentation.'   && echo"
```

`man echo` (GNU coreutils)
>       -e     enable interpretation of backslash escapes
>       -E     disable interpretation of backslash escapes (default)

**Comment by mboersma** [comment]
On Mac OS X (and others), we get a BSD-derived `echo` which only understands the `-n` flag (don't print trailing newline char). So adding `-e` will cause the installer to literally print `-e` on those platforms. And the ANSI coloring works just fine on Ubuntu without the `-e` flag (but not on CoreOS, where it shows up incorrectly as you described).

The code in question is [here](https://github.com/deis/deis/blob/master/deisctl/Makefile#L16-L29) and [here](https://github.com/deis/deis/blob/master/client/Makefile#L19-L28). I don't see a simple way to fix this in general other than removing the ANSI color codes.

**Comment by ineu** [comment]
@mboersma 
Yes, it works without `-e`, but only when used with built-in shell `echo`, and not in all shells. For example:
```
> $ echo $SHELL
/usr/bin/zsh

# built-in zsh echo, colorized
> $ echo '\033[0;36mdeis\033[0m'
deis

# gnu coreutils echo, not colorized by default
> $ /bin/echo '\033[0;36mdeis\033[0m'
\033[0;36mdeis\033[0m

# bash, not colorized by default
> $ bash -c "echo '\033[0;36mdeis\033[0m'"
\033[0;36mdeis\033[0m
```

Unfortunately I don't have ubuntu installation to check how shell is set up there. In `docker run -ti --rm ubuntu` with default bash it's not colorized either.

**Comment by ineu** [comment]
Tried debian jessie with `systemd-nspawn`. Default bash - not colorized, zsh - colorized.

**Comment by mboersma** [comment]
@ineu unless you can think of a portable way to fix the colorization, I'm just going to remove the ANSI codes in #3882. It was helpful to call attention to the name of the binary just installed, but really not essential, and it's better for it at least to be readable everywhere.

**Comment by ineu** [comment]
Thank you. Unfortunately I don't know how to make it portable.
