### ISSUE TITLE
deis-logger is eating whole cpu

### ISSUE THREAD

**Issue by szymonpk** [deis/deis#3853]
3-node cluster, fresh 1.7.0 with 1.6.1 publisher (due to issue with 404's).

One node where I've deis-logger, logger and etcd process together are eating whole cpu. If I stop deis-logger.service, etcd cpu usage is dropping. journalctl -f all together on all nodes combined is showing on average maybe <100 lines per minute.

journalctl -f -u for etcd or deis-logger doesn't show any warnings/errors.

Strace on etcd process is showing lots of GET requests to '/v2/keys/deis/logs/drain?con...', but if I remove log drain it doesn't change much in case of cpu usage.

Any advice where I should look?

**Comment by mackwic** [comment]
I think I found it: [missing `.Seconds()` on logger/main.go](https://github.com/deis/deis/blob/master/logger/main.go#L79).

Seriously guys. 10 nanoseconds as publish interval is not nice. ಠ_ಠ
