### ISSUE TITLE
Pin all installed packages to specific versions

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3856]
In many package installations (such as [Ceph in store-base](https://github.com/deis/deis/blob/c73c8f7e0fc96576f90a6cd4c2a66d08ba2dbae9/store/base/build.sh#L30)), we perform an `apt-get install` without pinning the installation to a specific release. We should be validating even minor changes in packages before bumping them. Without this change, there is also the possibility that some image builds will get newer builds and some will get older builds (depending on where they're built, the status of the apt mirror, etc.).

We need to do an assessment of all the package installations and ensure we're always specifying a specific version.

**Comment by mboersma** [comment]
I tried doing this for `ceph=0.94.2.1-1trusty` and it worked, but no earlier versions appeared to be available from the Ceph apt repo. I'm not sure that they retain every release there, so it might be problematic to pin ceph.

**Comment by carmstrong** [comment]
> I'm not sure that they retain every release there, so it might be problematic to pin ceph.

Hmm.. good point, although maybe they just mark them as old via `apt`? It looks like they keep old packages in the repo: http://ceph.com/debian-hammer/pool/main/c/ceph/

**Comment by carmstrong** [comment]
Anyway, good thing to keep in mind in general. If we pin everywhere, those packages may not stick around forever.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant so I'm closing this.
