### ISSUE TITLE
Play framework build failed

### ISSUE THREAD

**Issue by sockeye44** [deis/deis#3861]
This error occurs when you attempt to build Scala/Play application. Other Scala or Play/Java applications are not affected.

	-----> Discovering process types
       Default process types for Play 2.x - Scala -> web
	-----> Compiled slug size is 83M

	-----> Building Docker image
	remote: Sending build context to Docker daemon  87.8 MB
	remote: build context to Docker daemon 
	Step 0 : FROM deis/slugrunner
	 ---> 3a353a73715f
	Step 1 : RUN mkdir -p /app
	 ---> Using cache
	 ---> 1ead5993880f
	Step 2 : WORKDIR /app
	 ---> Using cache
	 ---> 769845e87ec9
	Step 3 : ENTRYPOINT /runner/init
	 ---> Using cache
	 ---> bdc7eb3f9485
	Step 4 : ADD slug.tgz /app
	 ---> ae6b8101e46c
	Removing intermediate container 11dce3baff3c
	Step 5 : ENV GIT_SHA 93f8fdd6972ab520d9e015e254cf2eee8cb8dfa7
	 ---> Running in cdc650bcfd7f
	 ---> 0a3e72d81428
	Removing intermediate container cdc650bcfd7f
	Successfully built 0a3e72d81428
	-----> Pushing image to private registry

	tar: invalid tar magic
	To ssh://git@deis.sockeye.cc:2222/oldest-tinkerer.git
	 ! [remote rejected] master -> master (pre-receive hook declined)
	error: failed to push some refs to 'ssh://git@deis.sockeye.cc:2222/oldest-tinkerer.git'

**Comment by Joshua-Anderson** [comment]
Do you have a `procfile`? Somebody had the same problem with the `nodejs`  buildpack and discovered that was the problem.

**Comment by sockeye44** [comment]
Thank you, there was a corrupted Procfile.
