### ISSUE TITLE
Update Installing SSL on a Load Balancer Doc

### ISSUE THREAD

**Issue by crigor** [deis/deis#3863]
> To enable SSL, you will need to open port 443 on the load balancer and forward it to port 80 on the routers

http://docs.deis.io/en/latest/managing_deis/ssl-endpoints/#installing-ssl-on-a-load-balancer

Starting deis 1.6 we enabled proxy protocol. If proxy protocol is enabled, the load balancer (at least for ELBs) has to use TCP 443:443.

If you use instance protocol 443, you need to set the ssl termination on the router.

Do we recommend disabling proxy protocol? In that case they can still use 443:80 as mentioned in the docs.

**Comment by carmstrong** [comment]
There's some discussion on this in #3829

**Comment by mboersma** [comment]
Closed by #3951.
