### ISSUE TITLE
Idea: Deployment Keys

### ISSUE THREAD

**Issue by scottrobertson** [deis/deis#3875]
Hey,

It would be quite cool if we could add deployment keys to a project. The work around right now is to create a deployment user, but that is a bit cumbersome. 

When adding deployment keys, we should have the ability to supply our own, or have deis generate a keypair automatically (and return the public key so we can add it to CI).

**Comment by nathansamson** [comment]
Hi,

Why I support this feature (in a broader way actually), it is exactly the
other way around. The CI system (and ONLY the CI system in principle)
should know the private key, while deis would need the public key.

In general I am intrested in more fine-grained ACL's to apps, specifically
I am intrested in following options

* (As this use case): a (pseude)-user that can do deployments
* A user to manage domains / certs
* An admin that can do everything.

Reason I am intrested in second bullet point is that I have a website where
people (in the future) should be able to subscribe to a SaaS system, and
choose their own domain name attached to it.
At that point a very restricted user should be able to access the DEIS API,
and add domains to the app.


Nathan

**Comment by scottrobertson** [comment]
You are right @nathansamson, it is totally the opposite way around :P 

But yeah, this would be an awesome feature to have.

**Comment by deis-admin** [comment]
This issue was moved to deis/builder#472
