### ISSUE TITLE
deis auth:passwd should not require the old password

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#3889]
See comment at https://github.com/deis/deis/issues/3851#issuecomment-112901929

**Comment by Joshua-Anderson** [comment]
@bacongobbler does this apply to all users or just administrators? 
Admins can change other user's passwords with knowing them since d887af0fd6504f9b4f1795bdf54b85ff20ff38da

**Comment by bacongobbler** [comment]
nah just admins.
