### ISSUE TITLE
Proposal: Client Go Rewrite

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/deis#3891]
#### Packages

**main**: Does initial command line parsing and parses out the command, like `deisctl`
**client**: Parses command options and calls cmd package, like `deisctl`
**cmd**: takes options and works with models and api, somewhat like `deisctl`

**controller/client**:

- Orchestrates connection to controller, loads user preferences to configure a REST api used by `controller/models`. See [this comment](https://github.com/deis/deis/issues/3891#issuecomment-112996543).

**controller/models**:
 - high level api for working with the controller. Example of the `App` object:

```
Apps.Delete(app App) (error)
Apps.Get(id string) (App, error)
Apps.List()([]App, error)

type App struct {
  Id string
  Owner string
  Created time.Time
  Updated time.Time
  ...
}

(app) Save() (error)
```

##### Testing:

I plan to use a `httptest` server to mock the controller api.

**Comment by technosophos** [comment]
Is there a reason why the App struct has all private fields?

**Comment by Joshua-Anderson** [comment]
@technosophos Nope, just a typo.

**Comment by technosophos** [comment]
I think this looks good. For the most part, it mirrors deisctl, and the proposed structure makes sense to me.

I would prefer not having a package named "api" or "apis", since that is not descriptive (in fact, it's confusing). Maybe "http" or "rest"?

I'm also a little confused over the term "session". User preferences aren't really a session. If the package "session" marshals and unmarshals preferences, shouldn't it be called "preferences" or "prefs"?

**Comment by Joshua-Anderson** [comment]
> I would prefer not having a package named "api" or "apis", since that is not descriptive (in fact, it's confusing). Maybe "http" or "rest"?

rest sounds good. I didn't choose http to avoid confusion with the native `http` package.

> I'm also a little confused over the term "session". User preferences aren't really a session. If the package "session" marshals and unmarshals preferences, shouldn't it be called "preferences" or "prefs"?

Preferences is better. I was thinking about the starting a session after authenticating, but preferences better reflects the more general use of the file.

**Comment by bacongobbler** [comment]
I agree with the name `models`, however I'd move it to `controller/models`. If we ever re-write the controller in Go (unlikely, but possible), I'd imagine that the import package would be `github.com/deis/deis/controller/models`, so it'd be a quick change from `github.com/deis/deis/client/controller/models` to `github.com/deis/deis/controller/models`.

I would also move the controller interaction into a separate package. `controller/client` would be better for communicating with the API. As an brain dump, here's how I think it should look like:

```go
// A Client manages communication with the controller API.
type Client struct {
    // HTTP client used to communicate with the API.
    client *http.Client

    // URL used to communicate with the controller.
    URL *url.URL

    // Base URL for API requests.  Defaults to the v1 API, but can be
    // set to a new api endpoint if the user has customized their controller.
    // BaseURL should always be specified with a trailing slash.
    BaseURL *url.URL

    // User agent header used when communicating with the controller API.
    UserAgent string

    // Token is used to authenticate the request against the API.
    Token string

    // Username is the name of the user performing requests against the API.
    Username string

    // Handle to a local Deis settings file. By default this is found in
    // ~/.deis/client.json, but can be tweaked by setting $DEIS_PROFILE.
    // It is used to persist client data on the local machine.
    SettingsFile *os.File
}
```

This way if users require a proxy (Go handles this by default), they can extend the HTTP client to their liking by setting up their own http.Transport in the client.

I'm not sure how the API requests would be handled, but that's my 2 cents on how the controller interaction should be set up.

**Comment by Joshua-Anderson** [comment]
@bacongobbler I like your ideas. I'll update the spec accordingly.

**Comment by Joshua-Anderson** [comment]
Closing this in favor of #3956. The actual implementation is similar to this, but I did change some things to make the code cleaner.
