### ISSUE TITLE
Automatically build release EBS snapshots for AWS

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3896]
At Engine Yard, we create EBS snapshots of the Docker volume for each Deis release. We then use this snapshot to create new volumes for hosts that we create. 

Currently, this process is manual and tedious. We should have a CI job that kicks off this automatic build and snapshot creation so that we can share it with our community.

/cc @iancoffey

**Comment by bacongobbler** [comment]
closing as irrelevant for [v2](https://deis.com/blog/2016/workflow-stable/).
