### ISSUE TITLE
/home/git/repo.git/build not being cleaned up

### ISSUE THREAD

**Issue by scottrobertson** [deis/deis#3910]
Not sure if this is a buildpack issue or deis. Close if it's a buildpack issue and sorry.

I had about 50 "tmp.*" folders in there. It was using around 5gb.

**Comment by scottrobertson** [comment]
Also, is deis meant to remove old exited containers? They are all lying around doing nothing. I have removed some older ones and ran the cleanup script again, which has saved lots of space.

**Comment by scottrobertson** [comment]
It's also not removing old images. I have images lying around from the past 3 weeks (when i created this new cluster). This a bug, or am I just going to have to run `docker images -q |xargs docker rmi` all the time?

**Comment by bacongobbler** [comment]
I know that we intentionally keep the cache directory to persist between builds, but if the build directory isn't being removed then we can probably clean that up :)

App images are kept for the same reason; the intention is that new builds should have access to layers from older builds for caching ourposes, but they should be removed when you destroy the app.

**Comment by scottrobertson** [comment]
Thanks @bacongobbler 

And what about the old containers? I had one for every version of the app, and they took up so much space.

**Comment by bacongobbler** [comment]
Yes, that's how things are implemented right now for faster failover purposes IIRC, however there's ongoing research ongoing in another issue. I'd give you the issue number but I'm on my phone in the middle of nowhere :)

**Comment by scottrobertson** [comment]
@bacongobbler Thanks :D I think keeping the last 5 would be safe enough. Keeping them all seems pretty a bit over the top, as you will run out of disk space super quickly.

I will try and find it. Have fun!

**Comment by mboersma** [comment]
As far as Docker images, see #3209 for that feature request. Cleaning up the git repo buildpack `build` directory sounds like a separate issue.

**Comment by scottrobertson** [comment]
Thanks @mboersma. Didn't realise that existed. Both issues are pretty big ones for me, as I sometime deploy upwards of 20 times/day. Things get pretty crowded on the SDD :P
