### ISSUE TITLE
HTTPS 504 GATEWAY_TIMEOUT after setting AWS ELB https

### ISSUE THREAD

**Issue by olalonde** [deis/deis#3912]
I just setup HTTPS on my AWS ELB balancer and I keep getting a HTTP 504 gateway timeout when trying to load my app with https. Http still works fine though.

I'm not sure if this is an issue with Deis or my AWS ELB configuration but maybe someone can help.

Here's my ELB config:

```
Load Balancer Protocol / Load Balancer Port / Instance Protocol / Instance Port / Cipher / SSL Certificate
TCP	80	TCP	80	N/A	N/A
HTTPS   443	HTTP	80	Change	mydomaincert Change
TCP	2222	TCP	2222	N/A	N/A
```

**Comment by olalonde** [comment]
Changing

```
HTTPS
HTTP
```

to

```
SSL
TCP
```

fixed it.

**Comment by mboersma** [comment]
I think this is related to #3829.
