### ISSUE TITLE
Jenkins should set overall PR status, not just sub-test status

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3917]
After a Jenkins test fails, Jenkins updates the sub-test status to green, but not the overall PR. This makes it hard to identify PRs that have since passed after failing once.

![http://i.imgur.com/6LMe0l9.png](http://i.imgur.com/6LMe0l9.png)

**Comment by carmstrong** [comment]
Maybe this is a non-issue, and it just takes a few minutes to update the overall PR?

**Comment by mboersma** [comment]
No, I have a script I run manually--all the time--to rectify the status. We intend a "last test run wins" behavior, but the Jenkins PR builder doesn't play ball that way, and if you can figure out how to fix that without forking the plugin and writing some Java code (yes, I tried that), I will buy you :beers:.

**Comment by Joshua-Anderson** [comment]
In the meantime you could make the script a cronjob or a post build trigger :smiling_imp:.

**Comment by carmstrong** [comment]
> In the meantime you could make the script a cronjob or a post build trigger

I was actually thinking the same thing! :+1:

**Comment by mboersma** [comment]
> In the meantime you could make the script a cronjob or a post build trigger...

Of course! Problems are:
1) It's hacky Ruby octokit code. Maybe I could redo it in groovy, which Jenkins likes.
2) I think I can't buy you :beers: legally.

Thanks for the clueslap, I'll give it a try today.

**Comment by mboersma** [comment]
This is much less of an issue now that we mostly use the [Naginator plugin](https://wiki.jenkins-ci.org/display/JENKINS/Naginator+Plugin)'s "Retry" link, but it's still present.

**Comment by bacongobbler** [comment]
fixed for v2
