### ISSUE TITLE
Gateway  Key not found (/deis/store/gateway/masterLock) [8462114]

### ISSUE THREAD

**Issue by liuyang1204** [deis/deis#3919]
Deis version 1.7.2

After a certain period, Gateway always get:

```
Jun 25 08:12:47 deis-2 sh[17360]: Error:  100: Key not found (/deis/store/gateway/masterLock) [8462114]
```

And I need to restart it.

**Comment by bacongobbler** [comment]
@liuyang1204 are you still seeing this on v1.8? I'm curious how your etcd cluster is set up. Perhaps there's some serious latency which is causing the publish loops in each component to run longer than 20 seconds, causing these keys to expire before they're refreshed again.

**Comment by liuyang1204** [comment]
@bacongobbler Thanks for response!

My deis cluster is composed by 3 bare metal PCs in office LAN env, with internet access.

I haven't upgraded to v1.8. I'll continue reporting the symptom when I have time to upgrade.

BTW, Recently I found Docker has [memory leak issue](https://github.com/docker/docker/issues/13470), and I guess my problem is quite related with it. Since many problems happen after several days running DEIS.

I'm OK if you judge to close this ticket. If I find this error again, I'll reopen it.

Thanks!

**Comment by carmstrong** [comment]
> I'm OK if you judge to close this ticket. If I find this error again, I'll reopen it.

Sounds good. Thanks!
