### ISSUE TITLE
Proposal ref(publisher): change the publication loop logic

### ISSUE THREAD

**Issue by aledbf** [deis/deis#3922]
Right now the publisher uses a ttl to expire the key of the application if the container and the open are available. This works just fine until you start hundreds of container because at that point the 10 seconds loops never ends.

Why not change the logic to publish the port when the container starts and use the loop to check if the container is and the port opened and remove it if not available?
```
if s.IsPublishableApp(containerName) && !s.IsPortOpen(hostAndPort) {
  s.removeEtcd(keyPath, false)
}
```

With this change the interaction with etcd is just 1 request per application when is not available instead of  `O(n)` every 10 seconds (to update the ttl) (n is the number of apps running in the local node)

**Comment by bacongobbler** [comment]
If publisher dies, I believe the intention is that the keys should also be removed such that the issue becomes apparent to the user, which is why we're using TTLs instead of just creating them once and waiting for the containers to die.

**Comment by aledbf** [comment]
@bacongobbler you are right, but see this process when you have more than 100 containers in a node, the amount of traffic with etcd starts to create issues with fleet for instance and the publication loop never ends

**Comment by aledbf** [comment]
Just to clarify: the way it works now is not wrong, this "issue" appear after hundreds of containers

**Comment by bacongobbler** [comment]
If we can make that workflow fault-tolerant, then I'm all for it! We could also just document bumping the TTLs up to 2n seconds, but in essence we're just bumping an arbitrary number that could fail again at 2n containers. :/

Alternatively, kubernetes has service discovery built into the platform, therefore eliminating the need for deis/publisher. That might be something worth looking into!

**Comment by aledbf** [comment]
> If publisher dies,....

is not posible to know which container died. When the publisher is restarted the map that contains the information about the running containers in the node it will be empty. That's why I added an additional component that checks every 40 seconds the published containers and if is not responding it just eliminate the key from `/deis/services/<app>'
https://github.com/aledbf/deis/commit/eb7291612251b9556917f45a07a9d79dd7f14e81#diff-d480fdb907bf18e9fc3592040c5dd4e7R36

> Alternatively, kubernetes has service discovery built into the platform,
I know and it does exactly why I implemented, the only difference is that it checks an URL in the pod (livenessProbe) https://github.com/GoogleCloudPlatform/kubernetes/blob/release-0.20/release-0.19.0/docs/pod-states.md#container-probes

**Comment by aledbf** [comment]
It makes no sense to change this if the scheduler is fleet. As @bacongobbler mentioned kubernetes already provides a "native" alternative for `deis-publisher`
