### ISSUE TITLE
Cannot deploy using Heroku buildpack and private repositories.

### ISSUE THREAD

**Issue by Crispy1975** [deis/deis#3923]
Using version 1.7.3 I am unable to push to a fresh Vagrant Deis (3 node) cluster. Using the latest Heroku buildpack specified here:

https://github.com/heroku/heroku-buildpack-nodejs

I have logged into the deis-builder and confirmed that the container has access to GitHub with the correct known_hosts and private/public keys. However when doing a git push to Deis (Node.js v0.12.5 and npm 2.7.x) I get the following...

       $ git push -f deis testing/deis 
       Counting objects: 427, done.
       Delta compression using up to 8 threads.
       Compressing objects: 100% (200/200), done.
       Writing objects: 100% (427/427), 45.25 KiB | 0 bytes/s, done.
       Total 427 (delta 251), reused 366 (delta 218)
       -----> Node.js app detected
              
       -----> Reading application state
              package.json...
              build directory...
              cache directory...
              environment variables...
              
              Node engine:         0.12.x
              Npm engine:          2.7.x
              Start mechanism:     npm start
              node_modules source: package.json
              node_modules cached: false
              
              NPM_CONFIG_PRODUCTION=true
              NODE_MODULES_CACHE=true
              
       -----> Installing binaries
              Resolving node version 0.12.x via semver.io...
              Downloading and installing node 0.12.5...
              Resolving npm version 2.7.x via semver.io...
              Downloading and installing npm 2.7.6 (replacing version 2.11.2)...

              ...

              npm ERR! Host key verification failed.
              npm ERR! fatal: Could not read from remote repository.
              npm ERR!
              npm ERR! Please make sure you have the correct access rights
              npm ERR! and the repository exists.
              npm ERR!
              npm ERR!
              npm ERR! If you need help, you may report this error at:
              npm ERR!     <https://github.com/npm/npm/issues>
              
              npm ERR! Please include the following file with any support request:
              npm ERR!     /tmp/build/npm-debug.log
              
       -----> Build failed

If I then force the npm version to 2.6.x I get a different build error as follows...

       $ git push -f deis testing/deis:master
       Counting objects: 424, done.
       Delta compression using up to 8 threads.
       Compressing objects: 100% (197/197), done.
       Writing objects: 100% (424/424), 45.00 KiB | 0 bytes/s, done.
       Total 424 (delta 249), reused 366 (delta 218)
       -----> Node.js app detected
              
       -----> Reading application state
              package.json...
              build directory...
              cache directory...
              environment variables...
              
              Node engine:         0.12.x
              Npm engine:          2.6.x
              Start mechanism:     npm start
              node_modules source: package.json
              node_modules cached: false
              
              NPM_CONFIG_PRODUCTION=true
              NODE_MODULES_CACHE=true
              
       -----> Installing binaries
              Resolving node version 0.12.x via semver.io...
              Downloading and installing node 0.12.5...
              Resolving npm version 2.6.x via semver.io...
              Downloading and installing npm 2.6.1 (replacing version 2.11.2)...

              ...

       npm ERR! ssh: connect to host github.com port 22: No route to host
       npm ERR! fatal: Could not read from remote repository.
       npm ERR!
       npm ERR! Please make sure you have the correct access rights
       npm ERR! and the repository exists.

ssh having issues getting through to GitHub on port 22. Yet inside the deis-builder I had connectivity. Very odd that a simple change of npm version could result in two different build errors.

**Comment by aledbf** [comment]
@Crispy1975 why are you downgrading npm to an older version than the provided by 0.12.5?

**Comment by Crispy1975** [comment]
@aledbf simple as the issue here shows a problem with npm 2.7.x and the buildpack, so tried the earlier version to see if it helped. While it did not, it was a different issue. Here is where I sourced the details...

https://github.com/heroku/heroku-buildpack-nodejs/issues/208

**Comment by aledbf** [comment]
@Crispy1975 ok, but you are replacing the npm version provided in node.js 0.12.5 (2.11.2) with an older release (https://github.com/npm/npm/compare/v2.7.6...master)
If don't specify the npm engine version the deploy works?

**Comment by Crispy1975** [comment]
@aledbf no, the first code block is done with the associated npm version and not forcing it to an earlier version. So the package.json contains only the following to force the version of Node.js

	"engines": {
		"node": "0.12.x"
	}

The npm version is naturally chosen and not specified in this case.

**Comment by aledbf** [comment]
@Crispy1975 ok, the error that you see is "Host key verification failed." if you the default version?
If that's the case are you using npm dependencies behind a private registry or git repository that requires authentication?

**Comment by Crispy1975** [comment]
@aledbf yes, the reference to another issue that seems similar is on this thread above. I have logged into the deis-builder container and confirmed known_hosts file and keys are present, and that I can authenticate against GitHub with `git -T git@github.com`. But when pushing I get the failed build based on the host error.

**Comment by Crispy1975** [comment]
This does not seem specifically related to the Heroku buildpacks from what I can tell now. I have converted a number of our apps to use Dockerfiles over buildpacks and get the same "Host key verification failed." error.

	npm ERR! Cloning into bare repository '/root/.npm/_git-remotes/ssh-git-github-com-api-plugin-git-be643e25'...
	npm ERR! Host key verification failed.
	npm ERR! fatal: Could not read from remote repository.
	npm ERR! 
	npm ERR! Please make sure you have the correct access rights
	npm ERR! and the repository exists.
	npm ERR! 
	npm ERR! 
	npm ERR! If you need help, you may report this error at:
	npm ERR!     <https://github.com/npm/npm/issues>

	npm ERR! Please include the following file with any support request:
	npm ERR!     /tmp/npm-debug.log

**Comment by Crispy1975** [comment]
We eventually got around this by switching from buildpacks to using Dockerfiles for building and deploying. In essence we pull in our custom Docker image, make sure cURL is installed along with a few other things, then pull the private repo key from a private S3 bucket (doesn't have to be S3, could be any location), the make sure that is in the correct location for the build process. Here is a sanitised version of the Dockerfile I am now using...

	# Set the base image to Debian Jessie with Node.js
	FROM crispy1975/jessie-nodejs:latest

	# File Author / Maintainer
	MAINTAINER Crispy1975

	# Install Node.js and other dependencies
	RUN apt-get update \
		&& apt-get -y install git-core \
		&& apt-get -y install curl \
		&& apt-get -y install openssh-client \
		&& apt-get -y install python \
		&& apt-get -y install build-essential \
		&& apt-get -y upgrade

	# Copy repo access keys over
	RUN mkdir -p /root/.ssh \
		&& curl -SLO https://s3-eu-west-1.amazonaws.com/my-bucket/my-key \
		&& mv my-key /root/.ssh/id_rsa \
		&& chmod 600 /root/.ssh/id_rsa \
		&& ssh-keyscan github.com >> /root/.ssh/known_hosts

	# Provide a cached layer for node_modules
	COPY package.json /tmp/package.json
	RUN cd /tmp && npm install
	RUN mkdir -p /src && cp -a /tmp/node_modules /src/

	# Remove key for security
	RUN rm -R /root/.ssh

	# Define working directory
	WORKDIR /src
	COPY . /src

	# Move into the src folder
	RUN cd /src

	# Expose port (override this elsewhere)
	EXPOSE  80

	# Run the app
	ENTRYPOINT ["npm", "start"]

Hope that helps somebody having problems with this. Would also love to hear if there is a better way.

**Comment by Crispy1975** [comment]
Coming back to this I feel I should also mention that you should make sure you restrict the access the the key location by machine IP addresses, secutiry groups if on AWS etc. We now have a custom script that we use to download private files into the Docker build process ... ssl certs, private keys etc. etc.

**Comment by bacongobbler** [comment]
@Crispy1975 mind giving this a shot on [v2](https://deis.com/blog/2016/workflow-stable/)? :)

**Comment by Crispy1975** [comment]
Yup, will do for sure. We're gonna try it in Google Cloud and not AWS and see how we get on. :)

**Comment by bacongobbler** [comment]
closing this issue since I believe this is now fixed, but please re-open if you find different results. Thanks!

**Comment by cmmartin** [comment]
Is there an actual solution to this? On Dokku, we have to use the [host keys plugin](https://github.com/cedricziel/dokku-hostkeys-plugin) to get around this. It uses the same buildpack as Heroku, so Heroku must provide a similar mechanism to use private github repos as npm dependencies. Does it?

**Comment by bacongobbler** [comment]
Yes. The solution is to use `deis config:set SSH_KEY=...`. https://github.com/deis/deis/pull/3305#issuecomment-81807358 implemented this feature and the docs also describe the usage in https://deis.com/docs/workflow/applications/using-buildpacks/#using-private-repositories.

**Comment by cmmartin** [comment]
@bacongobbler I deleted my comment immediately because I realized it was in the wrong repo. It was a heroku question. Thanks though.
