### ISSUE TITLE
bug(docs): Inaccurate description of builder responsibilities

### ISSUE THREAD

**Issue by krancour** [deis/deis#3926]
Would we all agree this is inaccurate?  If so, I'll open a PR to simply remove this line.

https://github.com/deis/deis/blame/master/docs/understanding_deis/components.rst#L50

AFAIK, config is not baked into the images.  It is held in the database and used to regenerate application units when a the new release is produced.

I saw this particular bullet point cause some confusion for some co-workers recently.

**Comment by bacongobbler** [comment]
Yes, that is partially inaccurate. The builder pulls down config from the controller during the build process, but it does not add the latest config to the resulting docker image. That is the responsibility of the `registry` module in the controller.

**Comment by mboersma** [comment]
Agreed, the docs would be more accurate if that line were removed. Thanks for reading closely @krancour!

**Comment by krancour** [comment]
I can't take the credit.  A co-worker read that line and took the doc's word for it.  Caused us a bit of confusion.  I'll nix this just as soon as I get a moment.

Do you think that besides removing that line, it might make sense to add a note that specifically explains that config values are never baked into the images directly?  Of is that TMI WRT to the brief overview of each component?
