### ISSUE TITLE
deis domains doesn't check for existing apps

### ISSUE THREAD

**Issue by lorieri** [deis/deis#3934]
lets say my domain is: mypaas.com

if I create an app called: app 

and set a domain myapp.mypaas.com for it
```$ deis domains:add myapp.mypaas.com```

deis allows to create another app called "myapp"
if the "myapp" already exists before ```deis domains:add```, it doesn't fail causing difficult debug situations for users.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and this has been fixed in deis v2 (the domain is created on `apps:create` so it'll fail if the domain has been claimed) so I'm closing this. :)
