### ISSUE TITLE
Deis scale isnt respecting the cluster.

### ISSUE THREAD

**Issue by phspagiari** [deis/deis#3940]
I have a Deis in production running on AWS with 3 nodes m3.large. And I scaled an app to 3 expecting that deis will distribute between the nodes, but the result of this is:
```
app_v6.cmd.1.service	5ecdbac1.../10.21.2.168	active	running
app_v6.cmd.2.service	5ecdbac1.../10.21.2.168	active	running
app_v6.cmd.3.service	5ecdbac1.../10.21.2.168	active	running
```
And if I scale to 6:

```
app_v6.cmd.1.service	5ecdbac1.../10.21.2.168	active	running
app_v6.cmd.2.service	5ecdbac1.../10.21.2.168	active	running
app_v6.cmd.3.service	5ecdbac1.../10.21.2.168	active	running
app_v6.cmd.4.service	5ecdbac1.../10.21.2.168	active	running
app_v6.cmd.5.service	7ce6fb89.../10.21.2.167	active	running
app_v6.cmd.6.service	7ce6fb89.../10.21.2.167	active	running
```
This is normal?

**Comment by aledbf** [comment]
@phspagiari this is the default fleet behavior:
> The current scheduler distributes units based on the current number of units scheduled to each host

 https://github.com/coreos/fleet/issues/747#issuecomment-57818552

**Comment by phspagiari** [comment]
Oh ok, makes sense. Even if I have only "this" app running, I have the apps of Deis too...
I imagined that Fleet was smarter than that.

**Comment by carmstrong** [comment]
> I imagined that Fleet was smarter than that.

Unfortunately not. We're working to support both Mesos and Kubernetes in addition to fleet and Docker Swarm so that users will have their choice of application scheduler. Going to close this issue as there's nothing we can do here, unfortunately.
