### ISSUE TITLE
proposal feat(client) allow for custom git hostname

### ISSUE THREAD

**Issue by szymonpk** [deis/deis#3948]
When I was trying to set cloudflare between deis and rest of the world it came to my attention that they will block anything except http/https traffic (for example tcp/2222), I don't know if cloudfront is affected too. 

Maybe I can add support for optional git hostname which will be passed from commandline to client.json, and used for all git related actions. I could implement it myself client code looks clean. 

I just need your opinion.

**Comment by bacongobbler** [comment]
I think that would be a reasonable workaround, as long as the default behaviour stays the same.

**Comment by jannispl** [comment]
CloudFlare only supports reverse proxying for HTTP(S). It's the way it works, and they're not blocking it for any other reasons.
You could also set up a DNS entry in cloudflare without having it pass through them (click the orange cloud next to the DNS entry).
