### ISSUE TITLE
"Welcome to NGINX" after switching from Dockerfile based deployment to Procfile

### ISSUE THREAD

**Issue by olalonde** [deis/deis#3949]
I used to deploy with a custom Dockerfile but trying to use Procfile instead. It works locally when running `foreman start web` but when I deploy to Deis, I'm getting the "Welcome to NGINX" page. After deployment, I did `deis ps:scale cmd=0 web=1 daemon=1`. Logs don't show anything either, last line is `2015-07-01T14:04:13UTC deis[api]: olalonde scaled containers web=1 daemon=1 cmd=0`.

Do I have to start my app on a specific port?

**Comment by bacongobbler** [comment]
Yes, your app must listen on $PORT, which is identical to heroku's docunentation. :)

**Comment by olalonde** [comment]
Ok thanks. I don't think this is in the Deis docs though (except that small Rails Procfile example - http://docs.deis.io/en/latest/using_deis/process-types/) might be a good idea to mention that the $PORT is there for a good reason :)
