### ISSUE TITLE
Weird `deis ps` output after running `deis config:set ...` and `git push` at the "same" time

### ISSUE THREAD

**Issue by olalonde** [deis/deis#3950]
```bash
$ deis ps
=== testnet Processes

--- web:
web.1 up (v13)
web.1 up (v13)

--- daemon:
daemon.1 up (v13)
daemon.1 up (v13)
```

I ran `git push deis` and `deis config:set SOMETHING=1` one after the other (by accident) and ended up with this. Not sure if it's intended behaviour or some sort of concurrency issue. Also, I'm currently getting the Nginx page on that app.

Edit: forgot to mention I got this in the logs: `2015-07-01T14:28:20UTC deis[api]: warning, some containers failed to start`

**Comment by olalonde** [comment]
Running `deis ps:scale web=0 daemon=0 && deis ps:scale web=1 daemon=1` fixed the issue.

**Comment by smothiki** [comment]
Might be a transient issue. We've been running integration tests for the past 4 days and didn't came across this issue. Closing the issue, please reopen if you are facing the same issue again.
