### ISSUE TITLE
create_bucket should use secure transport if external s3 is used and it should respect s3 region

### ISSUE THREAD

**Issue by szymonpk** [deis/deis#3961]
As discussed in #3947.

1. `s3secure=false` is completely [ignored](https://github.com/deis/deis/blob/master/registry/templates/create_bucket#L12). In case of local s3 transport it may be fine, but for amazon I would like to use https if possible.
1. boto's [create_bucket](https://github.com/deis/deis/blob/master/registry/templates/create_bucket#L17) with single name param will always create bucket in US region, it may cause higher bill if you have bucket in different region than deis and for sure it will degrade performance. It's fine if bucket is created before setup.
1. boto's [get_all_buckets](https://github.com/deis/deis/blob/master/registry/templates/create_bucket#L16) method requires special s3 permission, which I don't wan't to give deis s3 user. Maybe we can use `lookup`?. I've prepared [IAM policy](https://gist.github.com/szymonpk/07f3a0f18d78e6821983) which may be included into doc. It will limit permissions to just necessary ones, however I don't like `ListAllMyBuckets` which is forced by `get_all_buckets`.

**Comment by bacongobbler** [comment]
Those are all good changes. @szymonpk would you be up for a PR or are you just documenting enhancements that you'd like to see? The first bullet point should be fairly straightforward, but the others may need a [design document](http://docs.deis.io/en/latest/contributing/design-documents/) for approval/testing purposes. :)

**Comment by szymonpk** [comment]
@bacongobbler Lately I've few 'issues' 1. No time ;( 2. No free resources to run deis integration tests (I'm working on it but no ETA). I could probably take care of this, but not within two-three weeks.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant so I'm closing this.
