### ISSUE TITLE
Installator hanged, but platform is up and running

### ISSUE THREAD

**Issue by woopstar** [deis/deis#3962]
So i just installed Deis on a bare metal setup for 3 machines.

When doind the deis start platform command from my client, the installator hangs at the builder service and does not get any further. But when looking into the platform, the entire platform is running.

http://pastebin.com/PEGGinn9 
http://pastebin.com/Ga8rTfRY

**Comment by bacongobbler** [comment]
@woopstar looking at the logs, it looks like your builder is running:

> Jul 03 13:38:07 coreos-d0jrkncedibgdztt sh[3259]: deis-builder running...
> Jul 03 13:38:07 coreos-d0jrkncedibgdztt sh[3259]: Server listening on 0.0.0.0 port 22.

Does `deisctl list` show everything as running now?

**Comment by woopstar** [comment]
Yeah. Everyting is working very fine, nothing there. But the installer just hangs when it comes to the builder service.

**Comment by mboersma** [comment]
This should be fixed by #4025 and #4026.

**Comment by technosophos** [comment]
So I have been looking into this, and there are a few things that may be happening:

1) If the service gets into the state `failed` during a `deisctl start|stop|restart` operation, the deisctl client may hang even if the service continues to function. #4026 fixes this (I just finished it, and we'll get it merged as soon as its been tested)

2) Several people are noticing a case where builder takes a CRAZY amount of time to stand up -- hours, in one case. This has something to do with docker hub, and we're looking at it.

**Comment by mboersma** [comment]
This should be fixed by #4026. I'm going to close this, but please re-open it if the current master / upcoming v1.9 `deisctl` client seems to hang on a service start.

**Comment by woopstar** [comment]
I just tested a new setup on the cluster, and can confirm this seems to be fixed
