### ISSUE TITLE
Proposal: Get rid of `go printState` in deisctl

### ISSUE THREAD

**Issue by technosophos** [deis/deis#3971]
The `deisctl` command uses channels to send error and output messages, when it should just use `io.Writer` objects. Channels block too much, are the cause of a few past bugs, and force us to write an unnecessary number of goroutines to handle this. As far as I can tell, we're not gaining anything from using channels instead of writers.

In this proposal, I suggest that we switch to `io.Writer` instances instead of channels. We would usually hand `os.Stderr` and `os.Stdout` to a caller (instead of `outchan` and `errchan`). For testing, we would also be able to pass in different writers. 

Instead of doing `outchan <- fmt.Sprintf(...)`, we'd do `fmt.Fwritef(out, ...)`.

In the event that the underlying writer is not suitably synchronous, we can easily wrap in a synchronized writer.

**Comment by bacongobbler** [comment]
:+1: to using writers rather than channels. I agree that this would be the better approach.

**Comment by technosophos** [comment]
Doing this the right way requires changing an interface:

```go
type Backend interface {
	Create([]string, *sync.WaitGroup, chan string, chan error)
	Destroy([]string, *sync.WaitGroup, chan string, chan error)
	Start([]string, *sync.WaitGroup, chan string, chan error)
	Stop([]string, *sync.WaitGroup, chan string, chan error)
	Scale(string, int, *sync.WaitGroup, chan string, chan error)
	SSH(string) error
	ListUnits() error
	ListUnitFiles() error
	Status(string) error
	Journal(string) error
}
```

Changing exported interfaces without revving the major version number is generally considered bad form.

We can do one of the following:

- Create a second interface (`StateManager` or something) and re-implement the internals using the new backend, and then add a glue layer to expose the old interface, too. Lots of work.
- Create a second interface, and use that, but don't change (or use) the original one.
- Make a breaking change to the interface, on the theory that nobody outside of the project is actually using the `deisctl` code as a library, and hence nobody will care.
- Completely ignore the channels altogether, leave the interface alone, and add a new way to set the input streams.
- Delay fixing this until Deis 2, whenever that happens.

**Comment by technosophos** [comment]
To be clear, the proposed alternative interface would look like this:

```go
type Backender interface {
	Create([]string, *sync.WaitGroup, io.Writer, io.Writer)
	Destroy([]string, *sync.WaitGroup, io.Writer, io.Writer)
	Start([]string, *sync.WaitGroup, io.Writer, io.Writer)
	Stop([]string, *sync.WaitGroup, io.Writer, io.Writer)
	Scale(string, int, *sync.WaitGroup, io.Writer, io.Writer)
	SSH(string) error
	ListUnits() error
	ListUnitFiles() error
	Status(string) error
	Journal(string) error
}
```

With a possible alternative being:
```go
type Backender interface {
	SetWriters(io.Writer, io.Writer) 
	Create([]string, *sync.WaitGroup)
	Destroy([]string, *sync.WaitGroup)
	Start([]string, *sync.WaitGroup)
	Stop([]string, *sync.WaitGroup)
	Scale(string, int, *sync.WaitGroup)
	SSH(string) error
	ListUnits() error
	ListUnitFiles() error
	Status(string) error
	Journal(string) error
}
```

**Comment by smothiki** [comment]
+1 - separate interface for backend. Also there should be an interface for cmd.go. At present we are rewriting the same code for different orchestrations and changing names. there should be a common code which accepts configuration files for various orchestrations to execute respective commands.

**Comment by technosophos** [comment]
@smothiki Can you open an issue for the interface for commands? I can do that, too.

**Comment by technosophos** [comment]
I chose to break the interface. Since this is not (by design) a library, I think we can release this without considering it an API-breaking change.

**Comment by smothiki** [comment]
I'll open an issue for the interface for commands.
