### ISSUE TITLE
Consider using quay.io or self-hosted Docker registry for test runs

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3974]
Countless issues with our CI infrastructure have resulted due to transient errors with Docker Hub. We should consider using Quay.io or a self-hosted registry for our CI runs, and only push to Docker Hub for final release images.

**Comment by mboersma** [comment]
By all accounts, using a newer Docker should fix this as well. We are still hitting the registry V1 API which is known to have a fair number of runtime issues.

**Comment by mboersma** [comment]
See docker/docker-registry#298 and docker/docker-registry#941 for detail on these errors we are currently battling:
```
7e95d6e29486: Pushing
time="2015-07-07T15:28:13-06:00" level="fatal" msg="HTTP code 500 while uploading metadata: invalid character '<' looking for beginning of value" 
ea17760e6617: Pushing
time="2015-07-07T15:28:14-06:00" level="fatal" msg="HTTP code 404 while uploading metadata: invalid character 'p' after top-level value" 
```

**Comment by dvanbuskirk** [comment]
I have started a build on a 1.6.2.  I am hoping it works.  I guess it could have been worse.  My CI environment is all configured to use docker commands where as all my dev environments use chef-docker which is quite a bit of work I haven't planned for yet.  ;) I should know the outcome of my constantly failing docker build/push here in a few minutes.

**Comment by dvanbuskirk** [comment]
Update on my support ticket should be good news for those unable to upgrade.  

<SUPPORT>
We will definitely fix this issue sooner as possible. In fact, our engineering team already started working on this.

I was just recommending, if it is completely blocking for your now, you can temporarily push via 1.6 or above.

I will keep the ticket open and update you on our progress.
</SUPPORT>

1.6.2 testing is underway.  If I have an update from support I will comment here.

**Comment by dvanbuskirk** [comment]
I was able to push my docker image from my Jenkins slave running Docker 1.6.2 with no errors.  I then pulled it in my integration environment running 1.5.0 and all my minitests are passing using he new Docker image that was produced.  I'll comment again if I run into any issues.

**Comment by mboersma** [comment]
Thanks for comparing notes @dvanbuskirk. I'm also testing Docker 1.6.2 in place of 1.5.0, and it does fix the registry upload errors. Deis is pretty intimate with Docker though, so I need to do a fair amount more testing before we're comfortable moving wholesale to Docker 1.6.2. But so far it looks hopeful.

**Comment by dvanbuskirk** [comment]
Can't test already upgraded not going to waste time downgrading but Support reports the V1 issue is resolved.

----start----
Glad that you were able to push now. Also, I appreciate your concerns for those who are not upgrading.

I am happy to say that the issue with V1 registry has been resolved as well.

Sorry for the inconvenience caused to you and thank you for your patience.
----end----

**Comment by mboersma** [comment]
Deis is currently using quay.io for test runs.
