### ISSUE TITLE
Auto restart app when it crashes?

### ISSUE THREAD

**Issue by olalonde** [deis/deis#3978]
I was wondering if Deis had any mechanism to restart a web server that crashes (Node.js) or if that should be implemented in my code.

**Comment by bacongobbler** [comment]
Yes, we have a [`Restart=on-fail` policy](https://github.com/deis/deis/blob/master/controller/scheduler/fleet.py#L388) for the systemd units deployed via fleet.

**Comment by bacongobbler** [comment]
closing as a dupe of #1282

**Comment by olalonde** [comment]
Interesting, `fleetctl cat appname.v1.service` does show the `Restart=on-fail` but my crashed app doesn't seem to get restarted.
