### ISSUE TITLE
Unable to publish App while testing v1.8.0

### ISSUE THREAD

**Issue by kmala** [deis/deis#3981]
There are docker containers running for the app but unable to do a curl to the app.
core@ip-10-21-1-199 ~ $ etcdctl ls --recursive|grep flaxen
/deis/services/flaxen-darkroom

The endpoints are not published for the app.

**Comment by mboersma** [comment]
I think this was a transient or test setup error--we didn't see anything like this in further testing, and the images we were using when testing this were obsoleted after further changes.
