### ISSUE TITLE
no output from deis run while using ruby's puts or pp

### ISSUE THREAD

**Issue by szymonpk** [deis/deis#3989]
Deis is eating my output, if I run:

```
$ deis run "bundle exec ruby -rpp -e 'pp 10'"
Running `bundle exec ruby -rpp -e 'pp 10'`...
# thats all, no output
```
```
$ deis run "bundle exec ruby -e 'puts 10'"
Running `bundle exec ruby -e 'puts 10'`...

# empty line as output, nothing else
```
Which is fine from my local machine, I've tried to push output to stderr, but no luck.

Strangely `bundle exec rake <some task>` is putting proper output. 

Any advice how to handle this? Since there is no interactive console yet, I wanted to execute small parts of codes on app containers.

**Comment by carmstrong** [comment]
I'd guess that the issue is around the quotes, but I'm not sure off the top of my head. Can you debug it by trying it in pieces? Is the output going to the logs of the `deis-controller` component instead of being channeled to the client?

**Comment by szymonpk** [comment]
It has to be sth with quotes because `bundle exec ruby -v` is putting proper output. Nothing goes to `deis-controller` logs. I'll try to escape quotes somehow, if if switch single quotes with double it fails terribly.

```
Jul 08 18:45:17 deis-staging-3 systemd[1]: [/run/fleet/units/app-api_v3.run.27.service:7] Trailing garbage, ignoring.
Jul 08 18:45:17 deis-staging-3 systemd[1]: app-api_v3.run.27.service lacks both ExecStart= and ExecStop= setting. Refusing.
```

**Comment by szymonpk** [comment]
I don't know how to handle these quotes, everything fails one way or another. I've found terrible workaround, I'm a little bit ashamed when using this...
```
wget https://gist.githubusercontent.com/szymonpk/<gist id>/gistfile1.txt -O /tmp/script.rb 2>/dev/null; bundle exec ruby /tmp/script.rb`
```

**Comment by carmstrong** [comment]
@szymonpk I think this is a dupe of #3400 - see that issue for the root cause. systemd is causing issues. If you find a solution, we would *love* to fix that...

**Comment by szymonpk** [comment]
Ok, I'll look into this. Let's close this one,
