### ISSUE TITLE
Sanitize/filter config variables from client

### ISSUE THREAD

**Issue by szymonpk** [deis/deis#3994]
One of my devs has done sth like this (on working/deployed application) `deis config:set PASSWORD=:g2ZY_"QA%M86Y3N` (probably he escaped it somehow) on working application, everything went fine. Next day he tries to deploy and we've got this:
```
$ git push deis master
Counting objects: 472, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (252/252), done.
Writing objects: 100% (472/472), 58.94 KiB | 0 bytes/s, done.
Total 472 (delta 174), reused 419 (delta 151)
/home/git/builder: eval: line 118: unexpected EOF while looking for matching `''
/home/git/builder: eval: line 119: syntax error: unexpected end of file
To ssh://git@deis:2222/app-api.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@deis:2222/app-api.git'
```
[builder#L116](https://github.com/deis/deis/blob/master/builder/rootfs/etc/confd/templates/builder#L116) is evaluated to `/usr/bin/docker run -v /etc/environment_proxy:/etc/environment_proxy -e API_PASSWORD="':g2ZY_"QA%M86Y3N'" -d -v /home/git/api-api.git/build/tmp.v0xy9D5E80:/tmp/app -v /home/git/api-api.git/cache:/tmp/cache:rw deis/slugbuilder`. Which obviously fails because it isn't escaped properly.

Fasters solution I can see is validating user input when config:set and push are used or replacing devs my devs... but I don't see this coming ;-)

**Comment by mboersma** [comment]
Closing in favor of #2980.
