### ISSUE TITLE
Connection Draining

### ISSUE THREAD

**Issue by sstarcher** [deis/deis#3996]
Deis currently supports sending a sigterm to the running container and giving it 10 seconds to clean up.  It would be nice to have the ability to have deis wait for the container's connection to close before forcefully shutting down the container.

**Comment by bacongobbler** [comment]
If the connection closes before 10 seconds are up, the container will die gracefully. We can't keep fleet holding a container forever, should the connection never die. This is [the exact same behaviour as Heroku](https://devcenter.heroku.com/articles/dynos#shutdown):

> The application processes have ten seconds to shut down cleanly (ideally, they will do so more quickly than that). During this time they should stop accepting new requests or jobs and attempt to finish their current requests, or put jobs back on the queue for other worker processes to handle. If any processes remain after ten seconds, the dyno manager will terminate them forcefully with SIGKILL.

What would be the resolution for this?

**Comment by carmstrong** [comment]
@sstarcher Curious - what sort of long-lived connections are you dealing with? Perhaps there's an alternative solution we could propose.

**Comment by sstarcher** [comment]
We have a few reports that are generated that can take up to a minute to generate, but as @bacongobbler you do currently support the same behavior as Heroku so maybe the solution is for us to handle our connections differently.
