### ISSUE TITLE
Integration tests aren't goroutine-safe

### ISSUE THREAD

**Issue by mboersma** [deis/deis#3998]
There is code in the integration tests that is known to deal with stdin/stdout in a way that is not safe for concurrency. `GOMAXPROCS=4 ./tests/bin/test-integration.sh` will fail at some point as a result.

In Go 1.5, setting `GOMAXPROCS` to the number of available CPU cores will be the default. For now we can continue to run the tests with Go 1.4.x and the default `GOMAXPROCS` of 1, but this is technical debt we should resolve at some point.

**Comment by Joshua-Anderson** [comment]
@mboersma Do you have examples of these failures? Go test shouldn't run tests in parallel unless you add `t.Parallel()`.

**Comment by mboersma** [comment]
I don't think it's necessary to mark the tests with `t.Parallel()` to cause this problem--I have seen it simply by running the existing test suite with `GOMAXPROCS=4`. I don't have examples at hand but I'll add them when I'm able to.

**Comment by mboersma** [comment]
This is a potential problem, but isn't likely to receive attention given that Deis v1 tests work in the current environment. See https://github.com/deis/workflow-e2e instead where parallelization owns us all.
