### ISSUE TITLE
Stateless logger

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#4000]
Users who have elected to run a Ceph-less cluster (http://docs.deis.io/en/latest/managing_deis/running-deis-without-ceph/) give up application logs since ``deis-controller`` has nowhere to store them. To alleviate this, we plan to implement an in-memory ring buffer for the ``deis-logger`` component, so that a reasonable period of recent logs is stored and can be queried with ``deis logs``.

**Comment by bacongobbler** [comment]
related: #3963
