### ISSUE TITLE
Feature Request: Cluster-Wide ENV vars

### ISSUE THREAD

**Issue by jwaldrip** [deis/deis#4013]
### Example Use Case:
```
deis config:set --all NEW_RELIC_LICENSE_KEY=abc123
```

### Acceptance Criteria:
* New builds will reflect the ENV variable.
* New applications will reflect the ENV variable.
* ENV variable can be overridden if set at the application level.

### Nice to haves:
Aliasing. It would be great if I could set `SOME_VAR=$OTHER_VAR`. This would allow me to do `NEW_RELIC_APP_NAME=$DEIS_APP`.

**Comment by bacongobbler** [comment]
Would you mind adding this to #1804? :)

**Comment by jwaldrip** [comment]
@bacongobbler sure. I didn't see that one.
