### ISSUE TITLE
Proposal ref(controller): add additional restriction for application name

### ISSUE THREAD

**Issue by aledbf** [deis/deis#4014]
The objective of this change is to avoid issues with long names in kubernetes.
There is a restriction to use (rfc952)[https://tools.ietf.org/html/rfc952] in labels (and the application name is one)

```
Regex: "[a-z]([-a-z0-9]*[a-z0-9])?"
Maximum length: 24
```

**Comment by bacongobbler** [comment]
We have a max length of 64 characters to sync up with docker's restrictions on image names. Changing it to 24 would be a breaking change for older clusters that utilize fleet. Maybe we can configure the app name length based on what the value of `settings.SCHEDULER_MODULE` is?

**Comment by aledbf** [comment]
Closing because is possible to bypass this restriction using labels (at least in kubernetes).
https://github.com/deis/deis/pull/3975/files#diff-0846f028c19323121b40cee6ead7c3c3R314
