### ISSUE TITLE
Virtualbox requirements are wrong

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#4018]
In the hacking on deis docs it mentions "VirtualBox latest" while in fact VirtualBox 5.0 (recently released), doesnt seem to be compatible with vagrant yet...

**Comment by helgi** [comment]
Vagrant 1.7.3 got VB 5.0 compatibility. https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#173-july-10-2015

**Comment by mboersma** [comment]
Thanks @helgi! I updated Linux node4 in our CI setup to use vagrant 1.7.3 with VirtualBox 5.0, and it worked fine for a test-coreos-stable job. I'm also using the same versions locally on Mac OS X to run test-integration.sh, and everything's happy.

So I think the wording about "VirtualBox latest" is still technically accurate. I'm closing this, but please reopen it if you find any problems specific to the latest VirtualBox / vagrant.
