### ISSUE TITLE
Security concern: controller and app data paths mixed together

### ISSUE THREAD

**Issue by nilnullzip** [deis/deis#4027]
Love Deis and we're trying to implement it for our App. My concern is that the controller and user traffic go through the same domain. So for example, the user path is myapp.example.com and control path is deis,example.com and the deis router looks at the subdomain to direct the traffic to the myapp or control plate.

I had expected that the control path would be separated in some way so that it might be isolated and not accessible outside the App firewall. Do others have this concern, and how do you address it?

**Comment by bacongobbler** [comment]
Hey @nilnullzip, may I inquire what the security concern may be here? Authn/Authz is handled on the controller side of things, so users would have to be given an administrator's API key to do anything malicious on the platform side.

**Comment by nilnullzip** [comment]
1) I'd be concerned about vulnerabilities in the API. For example:
> https://groups.google.com/forum/#!msg/deis-users/pcHFIKl5ZFM/QEHTV2Dety8J
Better to minimize exposure to this kind of problem.

2) I'm a little uncomfortable with single factor keys. SSH is nice because it's two factor.

I think I'd rather have a single SSH entrypoint into a server from which we could manage things. Less ways to go wrong.

**Comment by bacongobbler** [comment]
Sounds reasonable to be concerned about these things. How would you feel we could go about documenting this? I'm not too familiar with the workflow that you describe, but perhaps a [design document](http://docs.deis.io/en/latest/contributing/design-documents/) on how you envision this type of feature (either with architectural or documentation changes) could get rolled out would be very helpful!

**Comment by nilnullzip** [comment]
@bacongobbler Thanks for the followup! I'm not sure I know what to specify yet. I'm new to Deis. I'd be interested in hearing some views about this from those that are more knowledgeable before making a proposal.

**Comment by bacongobbler** [comment]
We'll continue to handle vulnerabilities as they come in. I'm going to close this as it's way too broad of a scope to narrow down to an action item, but if you come up with something then we're all ears :)

Thanks!
