### ISSUE TITLE
Investigate spike in logger container during load test

### ISSUE THREAD

**Issue by jchauncey** [deis/deis#4030]
While load testing my deis cluster yesterday I noticed the logger container was always using more cpu than the rest of the containers in the cluster. It would be a good exercise to determine why that might be. 

Attached is the scap file which. You can use sysdig to examine the dump.
[capture.scap](https://s3-us-west-2.amazonaws.com/jchauncey-artifacts/capture150714030443.scap)

**Comment by mboersma** [comment]
This was Deis v1.8-era when @jchauncey noticed and faithfully reported this, but nothing similar has cropped up since so I'm closing it.
