### ISSUE TITLE
Automate upgrade test

### ISSUE THREAD

**Issue by sgoings** [deis/deis#4033]
We'd like to add the ability test the deis upgrade process in an automated fashion. This process currently is:

- spin up the previous release of deis
- deploy an app to it
- verify that the app is running properly (smoke test)
- tear down deis around the app
- deploy the current version of deis
- verify that the app is running properly (smoke test)

Ideally this test should be able to run on all providers, but for the first round of implementation I'm only looking to support Vagrant and EC2.

**Comment by carmstrong** [comment]
> Ideally this test should be able to run on all providers,

I think EC2, Azure, and GCE are ones we should shoot for. Other providers don't have separate volumes and etcd would almost certainly fall to its knees under heavy IO. See https://github.com/deis/deis/issues/3648#issuecomment-121672023
