### ISSUE TITLE
Automate smoke test on GCE

### ISSUE THREAD

**Issue by sgoings** [deis/deis#4035]
In order to improve deis' quality on various providers, we'd like to have a way to test deis on GCE in an automated fashion.

What I'd like to see is:
- provision a 3 node cluster on GCE
- run the smoke test script after provisioning is complete.

I'll probably take a stab at reviving some of the work that others have done with Terraform for the provisioning bit.

**Comment by bacongobbler** [comment]
You may want to talk to @econnell  about this, as he has been working on Terraform recently :)

**Comment by sgoings** [comment]
You bet @bacongobbler. @econnell is there a place I can go to check out your work/understand your progress in that domain?

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to fixing for the LTS release, and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this.
