### ISSUE TITLE
Automate smoke test on Azure

### ISSUE THREAD

**Issue by sgoings** [deis/deis#4036]
In order to improve deis' quality on various providers, we'd like to have a way to test deis on Azure in an automated fashion.

What I'd like to see is:
- provision a 3 node cluster on Azure
- run the smoke test script after provisioning is complete.

Also see #4035

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to fixing for the LTS release, and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this.
