### ISSUE TITLE
Automate stress test of deis

### ISSUE THREAD

**Issue by sgoings** [deis/deis#4037]
@jchauncey has found some interesting problems when running significant load through deis. I'd like to see an automated version of this test (or similar) so that we can watch deis' performance over the course of future releases. We could even run this on the various providers and compare performance. :smile:

**Comment by carmstrong** [comment]
:+1:

This should also record statistics so we can be aware of regressions. etcd failures and is one thing I'd like to see.

**Comment by bacongobbler** [comment]
FYI Go has benchmarking built in. I bet we can use this to our advantage with the integration tests.

http://dave.cheney.net/2013/06/30/how-to-write-benchmarks-in-go

**Comment by jchauncey** [comment]
With gatling we could easily create scenarios to test different types of
load and let that generate reports for us.

We should be testing the various components individually as well as the
whole.

**Comment by jchauncey** [comment]
http://gatling.io/ link for those interested

**Comment by sgoings** [comment]
@jchauncey feel free to create an issue or two for the individual component approach. I'm trying to get as many of our hallway conversations documented in GitHub.

**Comment by bacongobbler** [comment]
cross-posted to jenkins-jobs
