### ISSUE TITLE
Add shell unit testing harness

### ISSUE THREAD

**Issue by sgoings** [deis/deis#4040]
We have a bunch of shell scripts in the deis project, and no unit (or integration) tests for them. There are many shell unit testing frameworks and even ones that have mock/stub functionality. Let's pull one of them in and provide a model for shell script tests.

I know it may sound weird to test your shell scripts with more shell scripts, but take for example #4023. Wouldn't it have been cool to have a way to test all those conditions during the development of that script? Additionally, it would help someone in the future verify that future changes have not broken existing behavior.

**Comment by bacongobbler** [comment]
:+1: for more tests

**Comment by sgoings** [comment]
Also see parallel discussion happening in https://github.com/deis/rigger/issues/14.

**Comment by mboersma** [comment]
Good stuff here, but this isn't going to be a development priority as Deis v1 LTS is focused on stability and Deis v2 has minimized the use of shell scripts.
