### ISSUE TITLE
Configure Jenkins jobs with jenkins-job-dsl

### ISSUE THREAD

**Issue by sgoings** [deis/deis#4041]
Instead of fiddling around with Jenkins job configuration in the UI, I've found that defining the behavior of your Jenkins jobs through the [Netflix Jenkins Job DSL](https://github.com/jenkinsci/job-dsl-plugin) and possibly the [ReadyTalk Pipline DSL](https://github.com/ReadyTalk/jenkins-pipeline-dsl) (might be biased :smile:) leads to less hassle in the long run.

It also makes testing larger Jenkins changes (updating plugins, testing new job behavior) less disruptive to others since you can start a local Jenkins instance, load all the jobs into it, and be off to the races with your experimentation.

**Comment by mboersma** [comment]
As a counterpoint: learning a Jenkins-job-configuration-specific DSL still requires learning, whereas the clunky Jenkins web forms are largely self-documenting. We've had other team members need to tweak settings on jobs, and filling out a web form is easy.

Granted, there aren't a large number of similar jobs in CI (yet?), so maintenance has not been much work, and I respect your expertise in this area. If the DSL plugins somehow make it easier to test Jenkins changes locally, that would be very welcome.

**Comment by jchauncey** [comment]
+1000 on the job dsl

**Comment by bacongobbler** [comment]
see https://github.com/deis/jenkins-jobs.
