### ISSUE TITLE
Move build slaves into EC2

### ISSUE THREAD

**Issue by sgoings** [deis/deis#4046]
We currently have:

*node2-boulder*
Asus Tower (64bit Linux)

*node3-boulder*
Macmini

*node4-boulder*
Lenovo Thinkpad (64bit Linux)

We can definitely move *node2* and *node4* to EC2 instances, but the macmini will have to stay for now (as it builds the deis and deisctl clients for darwin). We can look at hosted Macs as a service (would love input/suggestions here if anyone has experience with any of those services).

This change should improve network connectivity and speed (vs. being tied to our office network bandwidth).

**Comment by mboersma** [comment]
Our current hardware is a ragtag, fugitive fleet, on a lonely quest...

The only obstacle I can think of here is that we still run some vagrant/VirtualBox-based test jobs, which require real hardware. Those jobs could be replaced by cloud-based provisioning jobs, but we would need to find a way to provision the latest available CoreOS build for each channel, which is something vagrant cloud gives us for free.

**Comment by Joshua-Anderson** [comment]
@mboersma You can use ec2 to provision the latest CoreOS images. CoreOS has a api to lookup the latest ami: `http://$CHANNEL.release.core-os.net/amd64-usr/current/coreos_production_ami_all.json`.

**Comment by bacongobbler** [comment]
> The only obstacle I can think of here is that we still run some vagrant/VirtualBox-based test jobs, which require real hardware.

perhaps we can do some slave tagging, much like we do for the cli installers for windows and OS X. That way the integration tests can run on hosts that don't require vagrant (i.e. EC2 instances), and the coreos-test-$CHANNEL tests (which IIRC are the only ones using vagrant) can run on the bare-metal hosts. Either that or re-write the channel tests with the endpoint that @Joshua-Anderson suggested.

**Comment by mboersma** [comment]
Once we merge #4032, the nightly "canary" jobs could be replaced with EC2^h^h^h AWS jobs that just set `COREOS_CHANNEL=alpha COREOS_VERSION=current`. 

I'm fine with tossing out the vagrant-based jobs and decommissioning the current nodes; it will free up office bandwidth for surfing the web. :surfer:

**Comment by mboersma** [comment]
@bacongobbler we already do have the nodes tagged as you suggest. The vagrant jobs can't run on master, for example, since it's an EC2 instance, only the nodes tagged "vagrant".

**Comment by sgoings** [comment]
Just a note: we have node[5-7]-ec2 up and running and connected to ci.deis.io.

**Comment by mboersma** [comment]
CI no longer uses the vagrant-based jobs, and all slave nodes are in ec2.
