### ISSUE TITLE
Restrict app creation to admins only

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#4052]
@fbjork asked about the ability to restrict new app creation to admins only. I think this may be part of a larger discussion around permissions. Related is #3976.

**Comment by fbjork** [comment]
Something along these lines would be great: https://devcenter.heroku.com/articles/org-users-access

**Comment by carmstrong** [comment]
@fbjork Can you elaborate? Do you think the implementation of organizations would be useful, or the permissions split between admins/users that Heroku uses?

We try to be Herokuish whenever possible. We're also working to rewrite the controller into smaller services, and auth is going to be one of those, so we have the opportunity to revisit our design for user authentication.

/cc @mboersma @bacongobbler @technosophos

**Comment by fbjork** [comment]
Permissions between admins and users is what we need. For example we want some users to deploy apps, view configuration, but not create new apps or edit configuration.

**Comment by mackwic** [comment]
viewing configuration is a sensible point, as it's where secrets and passwords are stored. I don't think it's a good idea, or it would need some special config treatment

**Comment by bacongobbler** [comment]
No, this likely won't become a default, however users who have special use cases like @fbjork should be able to tune the permissions to their liking. Today you can tune the settings by changing the values set as seen [here](https://github.com/deis/deis/blob/master/controller/api/views.py#L96) in the AppViewSet (updating the unit tests to ensure it's correct) and then deploying your own controller.

I think it's a matter of documenting how users like @fbjork can do this to cover their own use cases, but a larger proposal on how we can make this easier would probably need to have a larger discussion through a [design document](http://docs.deis.io/en/latest/contributing/design-documents/).

**Comment by carmstrong** [comment]
> I think it's a matter of documenting how users like @fbjork can do this to cover their own use cases

I don't think asking everyone who wants to do this to build a custom controller component is a solution - we're going to need to address customizable permissions at some point, and breaking down the controller into microservices seems to be a good time to do this.

But agreed on the design document for a proposal. :+1: Assigning this issue to @technosophos to think about when taking a stab at the controller rewrite.

**Comment by Joshua-Anderson** [comment]
@fbjork Does https://github.com/deis/deis/issues/4150 fit your use case? I'd love any feedback you have!

**Comment by Joshua-Anderson** [comment]
PR #4265 will fix this.

**Comment by bacongobbler** [comment]
closed via https://github.com/deis/controller/pull/1116.
