### ISSUE TITLE
[Docs] Move away from two column layout.

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/deis#4054]
Unless you have a very wide monitor, the two column layout takes more than 50% of the screen width, and are not visible more than a page down. This makes the text column seem very narrow.
<img width="1120" alt="screen shot 2015-07-16 at 5 08 08 pm" src="https://cloud.githubusercontent.com/assets/3526404/8737948/630c92b8-2bdd-11e5-9220-2fecf1a774df.png">

If you could make the two columns narrower or somehow compact the two into one column, the docs would be a lot more readable.

**Comment by mboersma** [comment]
This is still a (minor) issue, but it's not likely to get fixed for the Deis v1 docs (although PRs are always welcome). Integrating the Deis v2 docs into the https://deis.com/ is work already underway.
