### ISSUE TITLE
deisctl should warn when unit files have errors

### ISSUE THREAD

**Issue by jeff-lee** [deis/deis#4058]
We're using tags to isolate the control plane and application units to different hosts/autoscaling groups in EC2.

We ran into an issue earlier this week where a node failed and some of the deis control plane units moved to an unexpected node because the MachineMetadata option was incorrectly specified in some of the deis unit files ( MachineMetaData instead of MachineMetadata ).

Fleetctl will load the unit, but will give you a warning. It would be nice if deisctl did something similar or perhaps rejected the submission outright.

$ grep MachineMetaData deis-controller.service
MachineMetaData=role=services

$ fleetctl --version
fleetctl version 0.11.1

$ fleetctl submit deis-controller
2015/07/17 08:22:36 WARN fleetctl.go:576: Unit deis-controller.service: unrecognized requirement in [X-Fleet] section: "MachineMetaData"

**Comment by bacongobbler** [comment]
deisctl is going away in Deis v2 and I don't think we will be able to get to this for the LTS release so I'm going to go ahead and close this. Thank you for the report though!
