### ISSUE TITLE
Dynamic typing for config response 

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/deis#4070]
```
POST /v1/apps/<app id>/config/

{
	"cpu" {
		"web": 1024
	}
}

Response:

{
	...
	"cpu" {
		"web": 1024
	}
}

POST /v1/apps/<app id>/config/

{
	"cpu" {
		"web": "1024"
	}
}

Response:

{
	...
	"cpu" {
		"web": "1024"
	}
}
```

I think that dynamic parsing for the request is fine, but having a dynamic type for a response make it very difficult to parse.

**Comment by bacongobbler** [comment]
How are you seeing the second value? If it isn't an integer value then there's probably somewhere in the controller that's messing with the value.

**Comment by Joshua-Anderson** [comment]
`cpu` is stored in the database as a JSON value, so you get out the type you put in, since we're not checking type beforehand (at least between int and string).
