### ISSUE TITLE
`deis register` -> `deis auth:register` indirection/improvement

### ISSUE THREAD

**Issue by sgoings** [deis/deis#4075]
After installing and starting the deis platform via deisctl, the deisctl tells you:

```Please use `deis register` to setup an administrator account.```

However when you type:

```deis register```

you get:

```Usage: deis auth:register <controller> [options]```

As a new user of Deis, I'd find this confusing as my first assumption is that `deis register` doesn't exist, but it has moved to `deis auth:register`. Instead, what is actually happening is I just didn't pass in a controller.

A few options:
- improve the output of deisctl after the start of the platform to tell the user to now use the deis cli to register an account (with the correct instructions, maybe even putting in the controller IP/DNS entry for them)
- be more vague on how you register a user via the deis cli from deisctl
- change the usage output of `deis register` to show as `deis register` not `deis auth:register`
- give the user of the deis cli a bit more help on what option/argument they missed (in my case: controller)

**Comment by Joshua-Anderson** [comment]
How would changing the message to `Please use 'deis register <controller>' to setup an administrator account.` sound?

**Comment by technosophos** [comment]
Alternatively: `Please set up and administrative account. See 'deis help register'`.

**Comment by sgoings** [comment]
I like @technosophos' idea. A bit more future-proofed.

**Comment by Joshua-Anderson** [comment]
Yeah, I think that @technosophos's suggestion would work well.

**Comment by carmstrong** [comment]
I think the bigger question is when did `deis register` break? It definitely used to work - my provision helper script looks like:
```console
#!/bin/bash

deis register http://deis.apps.carmstrong.io --username=chris --password=adsf --email=chris@opdemand.com
deis keys:add ~/.ssh/deis.pub
```

**Comment by sgoings** [comment]
@carmstrong it's not broken, I was just complaining about the output and what it led me to believe the first few go-rounds with setting up a cluster.

**Comment by carmstrong** [comment]
> I was just complaining about the output

Gotcha. Made more sense on a second read-through.

**Comment by Joshua-Anderson** [comment]
PR #4276
