### ISSUE TITLE
bug(controller): Incorrect process type using deis pull 

### ISSUE THREAD

**Issue by aledbf** [deis/deis#4077]
```
deis create example-go-fleet --no-remote
deis pull deis/example-go:latest -p '{"web":"example-go"}' -a example-go-fleet
```

`deis info` returns cmd as process type but it should be web

@bacongobbler mentioned this line https://github.com/deis/deis/blob/master/controller/api/models.py#L354 as the reason of the default

**Comment by bacongobbler** [comment]
closing as fixed in deis/controller#1059.
