### ISSUE TITLE
deis pull registry returns error "Tag not found" on 1.8.0

### ISSUE THREAD

**Issue by clayzermk1** [deis/deis#4089]
I just set up a new 1.8.0 cluster on AWS but am unable to migrate my apps. `deis pull` is throwing the "Tag not found" error described in #3218 and others.

`deis pull registry.<deis domain>:5000/<app>:<version number>`
`deis pull registry.<deis domain>:5000/<app>:v<version number>`
`deis pull <public IP of registry>:5000/<app>:<version number>`
`deis pull <public IP of registry>:5000/<app>:v<version number>`
return an error:
```
Creating build... 503 SERVICE UNAVAILABLE
Detail:
GET Image Error (404: {"error": "Tag not found"})
```

The only deviation from a default install of deis is that I have disabled proxy protocol per the documentation.
I have tried opening up TCP 5000 on both clusters' ELB security group, and ELB but that did not seem to make a difference.
I have tried opening up TCP 5000 on the VPC security group that the instances use but that didn't seem to make a difference either.

The output of `/opt/bin/deis-debug-logs` and `deisctl journal registry` for both clusters can be found [here](https://gist.github.com/clayzermk1/c363ee6293a580431cfe).

Has anyone else been experiencing this on 1.8.0?

Thank you in advance for your help, cheers! :beers:

**Comment by carmstrong** [comment]
@clayzermk1 Can you also confirm the Docker version on both old and new hosts?

**Comment by bacongobbler** [comment]
From the logs, it looks like your internal registry can't connect to your external registry: https://gist.github.com/clayzermk1/c363ee6293a580431cfe#file-deisctl-journal-registry_on_180-L19

**Comment by clayzermk1** [comment]
@carmstrong The old stack is 1.4.1 and the new one is 1.8.0.

@bacongobbler Thank you. I wonder why. Is the only port used for this operation TCP 5000?

**Comment by bacongobbler** [comment]
@clayzermk1 yep! `deis pull` essentially emulates a "docker pull" from the old docker v1 API. The code which is invoked on a `deis pull` can be seen [here](https://github.com/deis/docker-registry/compare/master...new-repository-import-master), for reference.

To oversimplify things, the registry is pulling the layers directly from your remote registry and tagging it as `myapp:vn`. The error is confusing on the client's end, but that's mostly been because we're looking to EOL `deis pull` in favour of [`deis push`](http://docs.deis.io/en/latest/roadmap/roadmap/#deis-push).

**Comment by bacongobbler** [comment]
ping @clayzermk1, were you able to resolve this issue?

**Comment by clayzermk1** [comment]
Just got back around to this now actually. Will let you know before EOD.

**Comment by clayzermk1** [comment]
@bacongobbler I took another look at my EC2 SG/ELB configuration and made sure TCP 5000 was on everything just for giggles - no dice, still getting timeouts. At this point unless you would like me to help debug this issue, I'm content just re-creating the apps on the new cluster.

**Comment by clayzermk1** [comment]
I tore down my 1.8.0 cluster.
