### ISSUE TITLE
Show quantitative progress during deisctl install/start

### ISSUE THREAD

**Issue by sgoings** [deis/deis#4098]
In the process of installing and starting a Deis cluster via deisctl, it would be nice to see a more quantitative progress of how much of the process is left to go as well as quell questions of "is it even _doing_ anything?" when slower components (like builder) are building/deploying.

Some suggestions that have been thrown out include:
- showing the deisctl logs for the component that's currently being started (obviously this would be verbose and probably a bit too much for first time users, but it'd be awesome to have for automated tests)
- showing a [step N] of [step M] type progress meter
- showing a physical progress bar of some sort

**Comment by carmstrong** [comment]
SGTM. I also augmented a local branch to add timers to deisctl to show how long each provision sub-step took (including each component's start time). I was thinking that would be an optional debug flag to enable. Let me know if you want that code.

**Comment by technosophos** [comment]
@carmstrong I think we should add that. Maybe even enable by default.

**Comment by carmstrong** [comment]
> I think we should add that.

Here's some code to play with. Note that the global flag I created isn't being recognized. I never had a chance to go back to this. https://github.com/carmstrong/deis/commit/f51ca65cd8a63b76563c667fc2f3bf1c9e4518bf

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and deisctl is going away in deis v2 so I'm closing this. Thanks!

**Comment by bacongobbler** [comment]
Perhaps an enhancement request to [helm](/helm/helm) would be useful?
