### ISSUE TITLE
`deis certs:update` doesn't exist

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/deis#4102]
See [here](https://github.com/deis/deis/blob/master/client/deis.py#L1096). There is no code to implement the command.

I'd vote for entirely removing the command, since it presumably was never functional and nobody caught that it was broken yet.

**Comment by carmstrong** [comment]
:+1: Given that someone could quite easily `deis certs:remove` and then `deis certs:add`, I think it's reasonable to remove.

**Comment by bacongobbler** [comment]
:+1: sorry! Forgot to remove that in the docs
