### ISSUE TITLE
Add AnsiColor Plugin to ci.deis.io

### ISSUE THREAD

**Issue by sgoings** [deis/deis#4106]
We could be getting nice and fancy colors in our Jenkins output instead of color characters by installing this plugin: https://wiki.jenkins-ci.org/display/JENKINS/AnsiColor+Plugin

**Comment by mboersma** [comment]
:+1:

**Comment by mboersma** [comment]
Done, committed to ci.deis.io config in version control and tested. This is so much nicer! Great idea @sgoings.
