### ISSUE TITLE
[question] Why should I maintain an odd number of servers ?

### ISSUE THREAD

**Issue by altitude** [deis/deis#4108]
When you add servers to your cluster on the Deis Pro UI, it says:

> For optimal availability and latency, maintain an odd number of servers.

Just out of curiosity, why this rule?

**Comment by carmstrong** [comment]
Because it maximizes failure tolerance for the etcd cluster - see: https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#fault-tolerance-table

**Comment by carmstrong** [comment]
@altitude I'm going to close this - let us know if we can be clearer about this!

**Comment by altitude** [comment]
Sorry, I completely forgot to answer. Thanks for the clarification @carmstrong !
