### ISSUE TITLE
Logstash doesn't receive logs from Logspout

### ISSUE THREAD

**Issue by arkkanoid** [deis/deis#4111]
Hi!
I've created a fresh installation of Deis without Ceph. I use Logstash as Losgpout external component.
All services are working correctly except the Logspout component, I can see all logs with:
docker logs deis-logspout,  but Logstash doesn't receive it.

I've tried to send messages with to logstash with an external server and it works fine.

How I know if Deis is really sending the logs to the correct host?

My configuration is:

$ HOST=<logstash_host>
$ PORT=5000
$ deisctl config logs set host=${HOST} port=${PORT}

docker logs deis-logspout
2015/07/22 10:02:43 attach: 02844915660b deis-logspout success
2015/07/22 10:02:43 attach: eeb36af7d42a deis-publisher success
2015/07/22 10:02:43 etcd: http://10.21.1.217:4001
2015/07/22 10:02:43 routing all to <logstash_host>:5000
2015/07/22 10:02:43 loading and persisting routes in /tmp
2015/07/22 10:02:43 logspout serving http on :8000
2015/07/22 10:03:09 event: deis/router: pull
2015/07/22 10:03:09 event: 6add83874e42 create
2015/07/22 10:03:10 event: 6add83874e42 start
.....

Thanks!!

**Comment by krancour** [comment]
> My configuration is:
> 
> $ HOST=

Is the env variable `HOST` actually blank?  Or have you just redacted it in your post?

**Comment by krancour** [comment]
Also `5000` doesn't look like a port that a log server (including logstash) would normally be running on.  514 is more common.

**Comment by arkkanoid** [comment]
Hi! The variable HOST is filled correctly. 
Yes, I know that port 5000 could be strange but it should work, no? 
Thanks!

**Comment by bacongobbler** [comment]
as long as your logspout instance is at HOST:PORT and it'll accept UDP messages, then yes that should be fine.

**Comment by krancour** [comment]
> as long as your logspout instance is at HOST:PORT and it'll accept UDP messages, then yes that should be fine.

@bacongobbler did you mean _logstash_?

@arkkanoid you logstash (external to Deis) is actually listening for UPD traffic on port 5000?

**Comment by bacongobbler** [comment]
Oops! Yes, I meant logstash :)

**Comment by arkkanoid** [comment]
Hey! I'd configured the port 5000 to accept TCP. I've changed the docker where I run Logstash to accept UDP connections and now it receives the logs of Deis :D

Thanks!!
