### ISSUE TITLE
store-metadata: mds.-1.0 ERROR: failed to authenticate: (1) Operation not permitted

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#4115]
This error has cropped up a bit lately, and has been seen by @crigor and @mdolian on users' clusters. Full logs from one cluster are as follows:

```
Jul 27 18:05:25 host1 sh[1094]: starting mds.host1 at :/0
Jul 27 18:05:25 host1 sh[1094]: 2015-07-27 18:05:25.768406 7fed4c852800 -1 auth: error parsing file /var/lib/ceph/mds/ceph-host1/keyring
Jul 27 18:05:25 host1 sh[1094]: 2015-07-27 18:05:25.789818 7fed4c852800 -1 mds.-1.0 log_to_monitors {default=true}
Jul 27 18:05:28 host1 sh[1094]: 2015-07-27 18:05:28.784466 7fed4c852800 -1 mds.-1.0 ERROR: failed to authenticate: (1) Operation not permitted
Jul 27 18:05:28 host1 sh[1094]: 2015-07-27 18:05:28.784495 7fed4c852800  1 mds.-1.0 suicide.  wanted down:dne, now up:boot
```

Note that in this instance, this didn't happen on first metadata boot, but only after the host had rebooted. I suspect a race condition in which confd has not yet run and templated a valid keyring file. Note that while we [block for confd](https://github.com/deis/deis/blob/e4a54d031280d708d962a2dbde6d11e0755fc6a6/store/metadata/bin/boot#L43-L46) during initial metadata setup, we do *not* block on subsequent starts before checking to see if the keyring file exists: https://github.com/deis/deis/blob/e4a54d031280d708d962a2dbde6d11e0755fc6a6/store/metadata/bin/boot#L50-L61

An example of where we do this properly is in the monitor: https://github.com/deis/deis/blob/e4a54d031280d708d962a2dbde6d11e0755fc6a6/store/monitor/bin/boot#L67-L70

While this is an assertion as to the root cause here, the proposed fix should be straightforward and strictly correct, so I'll implement it.

**Comment by carmstrong** [comment]
After thinking on this, I'm not convinced this is the issue - we're blocking for confd before even trying to set up: https://github.com/deis/deis/blob/8135ead2b4d83c85e2a539325568b8deedc750a7/store/metadata/bin/boot#L11-L14

Since the metadata servers don't template anything other than the base Ceph configs, I'm not sure why this should matter.... hmm....

**Comment by jeff-lee** [comment]
For what it's worth I can pretty consistently trigger this error by attempting to scale several nodes ( 5+ ) at the same time.  One store-metdata has failed the last 3 times I've tried.

Scaling more slowly ( e.g. 2 at a time ) seems to work fine.

**Comment by carmstrong** [comment]
Thanks for the report, @jeff-lee. I'm thinking that maybe the error isn't in the templating of the keyring, but that the Ceph cluster isn't handling the auth for everyone simultaneously. That sounds like a pretty straightforward test case to confirm. :+1: 

An additional note - we actually don't need `store-metadata` running on all hosts in the cluster. We need a few (3 should really do it) so that if there is a failure with the master, Ceph can failover to a hot standby. We could consider making this a templated unit (like `deis-router`) rather than a global unit.

/cc @iancoffey @krancour

**Comment by jeff-lee** [comment]
@carmstrong  - one other oddity that I'm seeing that may be related is that ceph is often reporting more osds than there are nodes for the cluster ( e.g. osdmap e45: 11 osds: 9 up, 9 in - this is for a new 9 node cluster that was scaled 2 nodes at a time ).  Haven't gotten around to troubleshooting further yet.

**Comment by carmstrong** [comment]
> one other oddity that I'm seeing that may be related is that ceph is often reporting more osds than there are nodes for the cluster

Yep - unfortunately that's due to #2519 :(

**Comment by bacongobbler** [comment]
closing as irrelevant for [v2](https://deis.com/blog/2016/workflow-stable/).
