### ISSUE TITLE
store: consider switching filesystem to XFS

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#4119]
From http://ceph.com/docs/master/rados/configuration/filesystem-recommendations/#filesystems

> Ceph OSD Daemons depend on the Extended Attributes (XATTRs) of the underlying file system for various forms of internal object state and metadata. The underlying filesystem must provide sufficient capacity for XATTRs. btrfs does not bound the total xattr metadata stored with a file. XFS has a relatively large limit (64 KB) that most deployments won’t encounter, but the ext4 is too small to be usable.

Following is this:

> You should always add the following line to the [osd] section of your ceph.conf file for ext4 filesystems; you can optionally use it for btrfs and XFS.:

```
filestore xattr use omap = true
```

We switched from btrfs to ext4 in #3319 and didn't add the `filestore xattr use omap` configuration directive. We should either switch this volume to use XFS (probably preferred) or add this configuration, although it is unknown how this would affect existing clusters on upgrade. 

Note also that we should split out the `daemon` and `monitor` volumes anyhow - that is tracked as #3124.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant so I'm closing this.
