### ISSUE TITLE
Deis cluster on Microsoft Azure script fails

### ISSUE THREAD

**Issue by arv1989** [deis/deis#4129]
I tried : 
./azure-coreos-cluster "xxxx" --subscription "xxxxx" --azure-cert azure-cert.pem --num-nodes 3 --location "South Central US" --vm-size Large --pip --deis --blob-container-url https://xxxxx.blob.core.windows.net/vhds/ --data-disk --custom-data azure-user-data

the commandline result is :

SSH arguments not given, generating certificate
Generated SSH certificate with thumbprint 7B8FBA4AAA7CBD4A652060CDCD10CAE609472D9D
Generating new CoreOS discovery URL for the cluster
Wrote file "/Users/ameenrashad/Documents/dev/wsplatfoemtemp/deis/contrib/azure/azure-user-data" with url "https://discovery.etcd.io/8f3da2c44530eed4a764e328fdf2a128"
Creating the hosted service... Successfully created hosted service baleen
Uploading SSH certificate... . Succeeded in 5s
Traceback (most recent call last):
  File "./azure-coreos-cluster", line 229, in <module>
    network = network_config(subnet_name=args.subnet_names, port=ssh_port, public_ip_name=pip_name)
  File "./azure-coreos-cluster", line 170, in network_config
    network.input_endpoints.input_endpoints.append(lb_endpoint_config('web', '80', load_balancer_probe('/health-check', '80', 'http')))
  File "./azure-coreos-cluster", line 145, in lb_endpoint_config
    endpoint = ConfigurationSetInputEndpoint(name, 'tcp', port, port, name, False, idle_timeout_minutes)
TypeError: __init__() takes at most 7 arguments (8 given)

**Comment by sgoings** [comment]
I was unable to reproduce this problem. :disappointed: Here's my output on a freshly created Azure provision:

```
 ~/go/src/github.com/deis/deis/contrib/azure  ⑂ master +    ./azure-coreos-cluster --subscription XXXX --azure-cert azure-cert.pem --num-nodes 3 --affinity-group XXXX --vm-size Large --pip --deis --blob-container-url https://XXXX.blob.core.windows.net/vhds/ --data-disk --custom-data azure-user-data XXXX
SSH arguments not given, generating certificate
Generated SSH certificate with thumbprint ...
Generating new CoreOS discovery URL for the cluster
Wrote file "/Users/sethgoings/go/src/github.com/deis/deis/contrib/azure/azure-user-data" with url "https://discovery.etcd.io/XXXX"
Creating the hosted service... Successfully created hosted service XXXX
Uploading SSH certificate... . Succeeded in 5s
Creating VM xxxx-coreos-0... . . . . . . . . . . . Succeeded in 55s
Creating VM xxxx-coreos-1... . . . . . . . . Succeeded in 40s
Creating VM xxxx-coreos-2... . . . . . . Succeeded in 30s
...
<snipped>
...
```

My current line of thinking is that it looks like `ConfigurationSetInputEndpoint(name, 'tcp', port, port, name, False, idle_timeout_minutes)` (line 145) is somehow getting 8 arguments, which could happen if on line 170 the function `load_balancer_probe(...)` (line 151) is returning something unexpected from the Azure Python SDK [xml parsing routine involved with LoadBalancerProbe](https://github.com/Azure/azure-sdk-for-python/blob/9120beca03924be5307d30a8e224a2933096a10b/azure/servicemanagement/__init__.py#L2810) such as a Python error, tuple, etc.

So... could you help me get some more info on this?

- Azure Python SDK version? (try using 0.11.1 - the latest from pypi)
- add some logging messages around the lines I discuss above to see if you see anything wonky happening.

**Comment by arv1989** [comment]
@sgoings (Y) Thanks! you are right.. I was using Azure Python SDK Ver. 0.9.0 , The issue got resolved when I upgraded the same... Thanks!
