### ISSUE TITLE
Proposal: add admin-only registration mode

### ISSUE THREAD

**Issue by krancour** [deis/deis#4131]
Currently registration can be either enabled or disabled.  It's just on or it's off.

There's probably a good use case for allowing registration _only_ by admins.  This would allow admins to create accounts on behalf of developers and set an initial password.  Developers can reset their password after initial login.

This helps admins avoid the "enable registration long enough for a new developer to register and then disable it again" dance.

**Comment by Joshua-Anderson** [comment]
Already exists. `deisctl config controller set registrationMode=adminOnly`!

**Comment by mboersma** [comment]
This was implemented in #3399.

**Comment by krancour** [comment]
Nice.  Missed that!!!  Closing.
