### ISSUE TITLE
Let the admin delete a user from the CLI

### ISSUE THREAD

**Issue by jacopofar** [deis/deis#4132]
If I am admin of a deis cluster and there's a normal user which has to be removed, it would be useful to be able to do so from the command line when logged in as the admin user, even without knowing that user credentials.

Currently the only way to do so from the CLI is to run `deis auth:cancel`, but that requires to log in as the user to be removed, and I may not have the password.

At the moment this seems to be possible only using the REST interface and regenerating a token, as said [here](http://docs.deis.io/en/latest/reference/api-v1.5/#cancel-account)

**Comment by krancour** [comment]
Every application has an owner.  This would have the potential to orphan some applications.  That shouldn't be a showstopper though.  I would propose, perhaps, that when an admin deletes a user, ownership the users' applications transfers to that admin.

**Comment by bacongobbler** [comment]
related: #3976

**Comment by Joshua-Anderson** [comment]
Resolved by f923e49ba87f3d99e72694fba6e7453a5d4ba8e3
