### ISSUE TITLE
deis run "interactive console"

### ISSUE THREAD

**Issue by msull92** [deis/deis#4141]
I'm wondering if there is a way to use an interactive console with the `deis run` command. Ex: `deis run rails console` would allow someone to interact with the live application environment. This is how heroku works so I assumed deis did too, but it doesn't seem to work. Is this intentional or just not implemented yet?

**Comment by mboersma** [comment]
This is actually our most senior feature request: see #117. And we're getting there, so this should be possible in a future release.

I'm going to close this in favor of #117. Please follow up there.
