### ISSUE TITLE
"version mismatch" warning should be an error in tests

### ISSUE THREAD

**Issue by mboersma** [deis/deis#4144]
I noticed that a [recent test run](https://ci.deis.io/job/test-ec2/2343/console) was emitting the client <-> server version mismatch warning, but it still passed. In the context of a PR that increments the API version, this should have been treated as an error by the test suite somehow.
```
apps:run env
Running `env`...

  !    WARNING: Client and server API versions do not match. Please consider upgrading.
  !    Client version: 1.6
  !    Server version: 1.5
```

**Comment by Joshua-Anderson** [comment]
PR #4202
