### ISSUE TITLE
bug: swarm preview broken by etcd2

### ISSUE THREAD

**Issue by krancour** [deis/deis#4159]
I looked briefly... it doesn't seem the swarm preview gets tested during integration tests.  Am I mistaken?

When using it locally (from the master branch), I see errors like those below repeated over and over for _both_ `deis-swarm-manager` and `deis-swarm-node`.

```
Jul 31 01:36:12 deis-02 systemd[1]: Starting deis-swarm-node...
Jul 31 01:36:12 deis-02 systemd[1]: Started deis-swarm-node.
Jul 31 01:36:12 deis-02 sh[9830]: ./deis-swarm join --addr=172.17.8.101:2375 etcd:///deis/scheduler/swarm/node
Jul 31 01:36:12 deis-02 sh[9830]: error at command wait
Jul 31 01:36:12 deis-02 sh[9830]: 2015/07/31 01:36:12 exit status 1
Jul 31 01:36:12 deis-02 systemd[1]: deis-swarm-node.service: main process exited, code=exited, status=1/FAILURE
Jul 31 01:36:12 deis-02 systemd[1]: Unit deis-swarm-node.service entered failed state.
Jul 31 01:36:12 deis-02 systemd[1]: deis-swarm-node.service failed.
Jul 31 01:36:17 deis-02 systemd[1]: deis-swarm-node.service holdoff time over, scheduling restart.
```

**Comment by mboersma** [comment]
I wonder if flannel has confused things for swarm.

**Comment by krancour** [comment]
I wondered the same thing.  I've rolled back to pre-flannel and am still seeing the same thing.

**Comment by krancour** [comment]
If I go back to 1.8.0 and `make discovery-url && vagrant up`, I can install the 1.8.0 swarm components no problem.  In fact, on that local cluster, I can also successfully `cd swarm && make build deploy`

Now on the other hand, if I go back to 2f41ca0 (one commit before flannel), and `make discovery-url && vagrant up`, neither 1.8.0 or `cd swarm && make build deploy` work out.  Both yield the errors shown above.

This would seem to indicate something changed in how we bring up local vagrant clusters-- most likely userdata.

**Comment by krancour** [comment]
@mboersma I just determined it broke immediately after we added etcd2 to the user-data.

**Comment by krancour** [comment]
I'm feeling pretty stumped by this.  We're using early-docker to pull and start a containerized etcd2.  I have a vague suspicion that may have something to do with this, but none of my experimentation can confirm that yet.

**Comment by krancour** [comment]
Ping @kmala and @smothiki.  I think you guys worked on the swarm preview.  Do you have any ideas on how that could have been broken by etcd2 or the early-docker service that etcd2 depends on in our case?

**Comment by smothiki** [comment]
Swarm requires docker version >1.6 . Recently we have downgraded CoreOS version to 647 whihc uses docker 1.5 because of some bug.

**Comment by krancour** [comment]
Interesting.  This seems to have broken at commit d332f73.  I didn't not a difference in docker version before that commit vs after, but I'm going to re-run my experiment to confirm that.
