### ISSUE TITLE
Containers are out of sync with releases

### ISSUE THREAD

**Issue by ineu** [deis/deis#4160]
Deis 1.8.0

Today I've encountered weird issue: `deis ps` reports all containers as 'destroyed':
```
web.1 destroyed (v77)
...
```

`deis releases` reports last release as v77:
```
v77     Пн 27 июл 2015 20:18:06 MSK circleci deployed 690d49b
```

But containers currently running are of version 79:
```
engine-staging_v79.web.1.service
...
```

So it looks like two releases are lost somewhere, though containers are there.

**Comment by mboersma** [comment]
@ineu we haven't seen anything like this happen before. Did you have new releases fail to deploy? Any idea how we could reproduce this situation?

**Comment by ineu** [comment]
No, after rebooting all machines in the cluster it's fine, except one problem: for almost all applications `deis releases` shows releases older than containers running. Looks like there's been some synchronization problem and information about new releases was lost after rebooting server. Though it was not hardware reset, but normal `reboot` command.
Maybe it's old fleet/etcd in CoreOS 653 that causes synchronization problems. Don't know where Deis stores its releases information.
`ceph -s` reported OK.

Anyway, it's fine now and I cannot reproduce it any longer, so I think the ticket can be closed.

**Comment by bacongobbler** [comment]
Data is stored in the database (postgres) so I don't think it's a sync issue.

In the future, a pg_dump would probably be the easiest way to confirm that the data is the same as expected after a reboot. Thanks!
