### ISSUE TITLE
deis config and releases are inconsistent

### ISSUE THREAD

**Issue by ineu** [deis/deis#4180]
Runing 1.8 now, upgraded from 1.7.3. Today I've encountered two similar problems.

1. `deis releases` reports different releases on each run. For example, two consequent runs on single application:

```
v88     43 minutes ago               anatolii deployed 0f52435
v87     Ср 29 июл 2015 10:55:26 MSK Ineu changed REDIS_URL
v86     Пн 27 июл 2015 11:52:29 MSK oleg deployed 0a2d010
v85     Пн 27 июл 2015 10:55:43 MSK anatolii deployed 1642877
v84     Пт 24 июл 2015 17:20:31 MSK anatolii deployed 9cd01b0
v83     Чт 23 июл 2015 12:52:09 MSK oleg deployed b1b33cf
v82     Ср 22 июл 2015 16:22:42 MSK oleg deployed 28ff9de
v81     Ср 22 июл 2015 16:06:23 MSK anatolii deployed 9c47ae8
v80     Ср 22 июл 2015 12:55:48 MSK anatolii deployed e105673
```

```
v93     7 minutes ago                Ineu changed nothing
v92     9 minutes ago                Ineu changed nothing
v91     Чт 30 июл 2015 19:20:25 MSK anatolii changed API_TOKEN
v90     Чт 30 июл 2015 17:25:46 MSK anatolii deployed 5c541b0
v89     Чт 30 июл 2015 12:15:39 MSK anatolii deployed 2c8e349
v88     Ср 29 июл 2015 15:57:01 MSK anatolii deployed bce473c
v87     Ср 29 июл 2015 11:08:30 MSK Ineu changed REDIS_URL
v86     Пн 27 июл 2015 11:52:29 MSK oleg deployed 0a2d010
v85     Пн 27 июл 2015 10:55:43 MSK anatolii deployed 1642877
```

As you can see, not only the number of releases differ, but even releases with the same number is completely different. Looks like it comes from absolutely different applications.

2. `deis config` output is also not consistent. For the same key (REDIS_URL in my case) it sometimes reports one value and another time another value:

```
> $ while true; do deiss config -a app | grep '/1'; done
REDIS_URL                        redis://user:password@example.com:6380/1
REDIS_URL                        redis://user:password@example.com:6380/1
REDIS_URL                        redis://user:password@example.com:6380/1
REDIS_URL                        redis://user:password@example.com:6380/1
REDIS_URL                        redis://user:password@example.com:6380/1
REDIS_URL                        redis://user:password@example.com:6380/1
REDIS_URL                        redis://user:password@example.com:6380/1
REDIS_URL                        redis://user:password@example.com:6380/1
REDIS_URL                        redis://user:password@example.com:6380/1
REDIS_URL                        redis://user:password@example.com:6380/1
REDIS_URL                        redis://user:password@example.com:6380/1
REDIS_URL                        redis://user:password@example.com:6380/1
REDIS_URL                        redis://user:password@example.com/1
REDIS_URL                        redis://user:password@example.com:6380/1
REDIS_URL                        redis://user:password@example.com/1
REDIS_URL                        redis://user:password@example.com:6380/1
REDIS_URL                        redis://user:password@example.com:6380/1
REDIS_URL                        redis://user:password@example.com:6380/1
REDIS_URL                        redis://user:password@example.com:6380/1
```

Where do these entries without port come from? I don't have any application on this cluster with REDIS_URL not using port.

There are three machines in the cluster, `ceph -s` reports OK, `fleetcl list-machines` is fine.

**Comment by ineu** [comment]
Note: I've discovered containers with the app name underscored (i.e. `my_app`) while it should have been `my-app`. Is it possible that there's some logic in Deis that converts dashes to underscores (or vice versa) and thus returns config and releases from two different applications? I don't have `my_app` application now but it's quite possible that it was there before.

**Comment by bacongobbler** [comment]
@ineu the controller logs show what endpoints you're hitting with each call. That way we can determine if your client is hitting the same app or there's something else going on.

**Comment by ineu** [comment]
According to deis-controller logs, all http requests were to `my-app` (with dash)

**Comment by bacongobbler** [comment]
if you try a raw cURL using the reference docs as a guide, do you see similar output to the logs above? That way we may be able to rule out if it's a client issue or an API issue. My thoughts are that there may be some API pagination going on which the client may not be handling properly, or perhaps the controller is acting a little wonky with the rendered responses.

**Comment by ineu** [comment]
Also there's a weird thing in controller logs: I see endless "Booting worker" followed by "Worker exiting". According to monitoring system, deis-controller containers were not being killed by OOM, so they were restarting for some other reason (SIGHUP?):

```
Aug 03 13:00:21 staging-coreos-1 sh[20520]: [2015-08-03 13:00:21 +0000] [136] [INFO] Handling signal: hup
Aug 03 13:00:21 staging-coreos-1 sh[20520]: [2015-08-03 13:00:21 +0000] [136] [INFO] Hang up: Master
Aug 03 13:00:21 staging-coreos-1 sh[20520]: [2015-08-03 13:00:21 +0000] [19675] [INFO] Booting worker with pid: 19675
<skipped>
Aug 03 13:00:22 staging-coreos-1 sh[20520]: [2015-08-03 13:00:22 +0000] [19607] [INFO] Worker exiting (pid: 19607)
<skipped>
Aug 03 13:00:26 staging-coreos-1 sh[20520]: [2015-08-03 13:00:26 +0000] [136] [INFO] Handling signal: hup
Aug 03 13:00:26 staging-coreos-1 sh[20520]: [2015-08-03 13:00:26 +0000] [136] [INFO] Hang up: Master
Aug 03 13:00:26 staging-coreos-1 sh[20520]: [2015-08-03 13:00:26 +0000] [19711] [INFO] Booting worker with pid: 19711
```
and so on

**Comment by ineu** [comment]
> if you try a raw cURL using the reference docs as a guide, do you see similar output to the logs above?

Unfortunately this cluster is in use, so I cannot keep it down for a long time.

**Comment by bacongobbler** [comment]
I meant like a `curl -H 'Authorization: token <mytoken>' -H 'Content-Type: application/json' http://deis.domain.com/v1/apps/myapp/releases`, essentially mimicking the call which [the client would be making](https://github.com/deis/deis/blob/master/client/deis.py#L2324).

**Comment by ineu** [comment]
@bacongobbler This really looks like some kind of synchronization issue between machines. Unfortunately I can no longer reproduce it after reboot. Closing this one.

**Comment by ineu** [comment]
Just encountered the same problem, reopening issue. After servers were heavily loaded, services were killed (probably because of OOM) and restarted. Now I see `deis releases` reporting latest versions 77, and `fleetctl list-units` says containers of version 82 are running.

I'll dig into deis-database contents a bit later

**Comment by ineu** [comment]
`deis-database` logs on restart:
```
Aug 10 15:01:53 staging-coreos-2 sh[4229]: 2015-08-10T15:01:53Z 562835eda2d7 confd[123]: ERROR template: WALE_S3_ENDPOINT:1:53: executing "WALE_S3_ENDPOINT" at <getv "/deis/store/ga...>: err
Aug 10 15:01:53 staging-coreos-2 sh[4229]: 2015-08-10T15:01:53Z 562835eda2d7 confd[123]: ERROR template: create_bucket:10:12: executing "create_bucket" at <getv "/deis/store/ga...>: error ca
Aug 10 15:01:53 staging-coreos-2 sh[4229]: database: waiting for confd to write initial templates...
Aug 10 15:02:05 staging-coreos-2 sh[4229]: database: expecting initialization id: none
Aug 10 15:02:05 staging-coreos-2 sh[4229]: database: no existing database found or it is outdated.
Aug 10 15:02:06 staging-coreos-2 sh[4229]: database: no backups found. Initializing a new database...
Aug 10 15:02:06 staging-coreos-2 sh[4229]: 2015-08-10 15:02:06 UTC LOG:  could not open usermap file "/etc/postgresql/main/pg_ident.conf": No such file or directory
Aug 10 15:02:06 staging-coreos-2 sh[4229]: 2015-08-10 15:02:06 UTC LOG:  database system was interrupted; last known up at 2015-08-03 13:44:06 UTC
Aug 10 15:02:07 staging-coreos-2 sh[4229]: 2015-08-10 15:02:07 UTC LOG:  database system was not properly shut down; automatic recovery in progress
Aug 10 15:02:07 staging-coreos-2 sh[4229]: 2015-08-10 15:02:07 UTC LOG:  redo starts at A9/D3000090
Aug 10 15:02:07 staging-coreos-2 sh[4229]: 2015-08-10 15:02:07 UTC LOG:  unexpected pageaddr A9/CB000000 in log segment 000000B0000000A9000000D4, offset 0
Aug 10 15:02:07 staging-coreos-2 sh[4229]: 2015-08-10 15:02:07 UTC LOG:  redo done at A9/D3000090
Aug 10 15:02:07 staging-coreos-2 sh[4229]: 2015-08-10 15:02:07 UTC LOG:  database system is ready to accept connections
Aug 10 15:02:07 staging-coreos-2 sh[4229]: 2015-08-10 15:02:07 UTC LOG:  autovacuum launcher started
```

Looking into the database itself I see that latest release has `created` field set to 2015-08-03. Looks like all my releases created after this date (last start?) was lost.

**Comment by ineu** [comment]
Looking at my log I see that `unexpected pageaddr` caused recovery to finish immediately, without any actions. Looks like somehow wal segment become corrupted.

**Comment by bacongobbler** [comment]
do you have logs from the database before the last reboot? Perhaps it was failing to back up the database to ceph, which would cause this issue.

**Comment by ineu** [comment]
There are timeouts pushing WAL to gateway, but they are usually followed by successful push. `nse deis-database` gives me access to this WAL segment, it is of proper size (16MB) but is probably corrupted for some reason.

**Comment by ineu** [comment]
Yesterday even without restarting deis-database I've seen issue with storing release info: push was succesful, deis reported new release, but looking at `deis releases` the latest release I see was from 2015-08-03. Though next push (with another commit to trigger post-receive hook) created new release. Very weird.

I'm thinking about possible artefacts from previous releases, as I was upgrading Deis to every new release, from 1.5 to 1.8. WIll try to backup things and completely recreated the cluster.
