### ISSUE TITLE
deis logs not showing application logs when use of Dockerfile

### ISSUE THREAD

**Issue by LoicMahieu** [deis/deis#4181]
From https://github.com/deis/deis/issues/3633#issuecomment-127050698

`deis@1.7.3`
App: https://github.com/LoicMahieu/deis-test-nodejs#master

When deploying application (https://github.com/LoicMahieu/deis-test-nodejs#master) with a Dockerfile instead of Procfile, `deis logs` shows only logs from controller.

deis logs:
```
$ deis logs
2015-08-02T17:42:22UTC deis[api]: loic created initial release
2015-08-02T17:42:48UTC deis[api]: loic deployed cbb1838
2015-08-02T17:42:48UTC deis[api]: loic scaled containers cmd=1
```

docker logs:
```
$ docker logs igloo-deis-nodejs-sample_v2.cmd.1

> igloo-deis-nodejs-sample@1.0.0 start /app
> node index.js

Listen to http://localhost:3000
10.10.0.235 - - [02/Aug/2015:17:43:28 +0000] "GET / HTTP/1.1" 200 11 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.107 Safari/537.36"
10.10.0.235 - - [02/Aug/2015:17:43:29 +0000] "GET / HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.107 Safari/537.36"
```

I tried to destroy/re-create the app, scale up or down and always no logs.

---

Same application but using buildback (Procfile) (https://github.com/LoicMahieu/deis-test-nodejs/tree/procfile) works correctly.

**Comment by bacongobbler** [comment]
@LoicMahieu let's start with a few more things:

 - what does `deisctl journal deis-logger` show?
 - is deis-publisher running?

Those two components are the ones that are important for shipping application logs, so I'd start there.

**Comment by krancour** [comment]
Check the status of `deis-logspout` as well.

**Comment by bacongobbler** [comment]
sorry, I did mean deis-logspout instead of publisher. Thanks @krancour!

**Comment by LoicMahieu** [comment]
[`deisctl list`](https://gist.github.com/LoicMahieu/10f4b0afac6c21edf19a#file-deisctl-list) or [`fleetctl list-units`](https://gist.github.com/LoicMahieu/10f4b0afac6c21edf19a#file-fleetctl-list-units) show that everything is running...

[`deisctl journal deis-logger`](https://gist.github.com/LoicMahieu/10f4b0afac6c21edf19a#file-deisctl-journal-deis-logger) show a configuration error... Strange I remember that I already used this command. (I've done this directly on one of the machine in the cluster)

Thanks for help.

**Comment by krancour** [comment]
@LoicMahieu what errors are you seeing in `deis-logger`?

**Comment by LoicMahieu** [comment]
```
Error running remote command: SSH_AUTH_SOCK environment variable is not set. Verify ssh-agent is running. See https://github.com/coreos/fleet/blob/master/Documentation/using-the-client.md for help.
```

**Comment by bacongobbler** [comment]
that means your ssh agent is not running on that host. An `ssh -A` should fix that up when logging into the first CoreOS machine.

**Comment by LoicMahieu** [comment]
Got it.
I run `ssh -A core@10.10.8.10 -i ./deis_key` and I got: 
`Error running remote command: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

`deis_key` is the private key whose the public has been copied in `ssh_authorized_keys` during installation.

---

For allowing us to going forward I ssh into each nodes.
- [journalctl -r -u deis-logger.service](https://gist.github.com/LoicMahieu/c57cc83175602248ed01#file-journalctl-r-u-deis-logger-service)
- [journalctl -r -u deis-logspout.service - node-1](https://gist.github.com/LoicMahieu/c57cc83175602248ed01#file-journalctl-r-u-deis-logspout-service-1)
- [journalctl -r -u deis-logspout.service - node-2](https://gist.github.com/LoicMahieu/c57cc83175602248ed01#file-journalctl-r-u-deis-logspout-service-2)
- [journalctl -r -u deis-logspout.service - node-3](https://gist.github.com/LoicMahieu/c57cc83175602248ed01#file-journalctl-r-u-deis-logspout-service-3)
- fleetctl list-units
```
$ fleetctl list-units
UNIT						MACHINE			ACTIVE	SUB
deis-builder.service				633cbd72.../10.10.8.11	active	running
deis-controller.service				4b9deb2d.../10.10.8.10	active	running
deis-database.service				633cbd72.../10.10.8.11	active	running
deis-logger.service				633cbd72.../10.10.8.11	active	running
deis-logspout.service				4b9deb2d.../10.10.8.10	active	running
deis-logspout.service				633cbd72.../10.10.8.11	active	running
deis-logspout.service				7e1438d1.../10.10.8.12	active	running
deis-publisher.service				4b9deb2d.../10.10.8.10	active	running
deis-publisher.service				633cbd72.../10.10.8.11	active	running
deis-publisher.service				7e1438d1.../10.10.8.12	active	running
deis-registry@1.service				4b9deb2d.../10.10.8.10	active	running
deis-router@1.service				633cbd72.../10.10.8.11	active	running
deis-router@2.service				4b9deb2d.../10.10.8.10	active	running
deis-router@3.service				7e1438d1.../10.10.8.12	active	running
deis-store-daemon.service			4b9deb2d.../10.10.8.10	active	running
deis-store-daemon.service			633cbd72.../10.10.8.11	active	running
deis-store-daemon.service			7e1438d1.../10.10.8.12	active	running
deis-store-gateway@1.service			4b9deb2d.../10.10.8.10	active	running
deis-store-metadata.service			4b9deb2d.../10.10.8.10	active	running
deis-store-metadata.service			633cbd72.../10.10.8.11	active	running
deis-store-metadata.service			7e1438d1.../10.10.8.12	active	running
deis-store-monitor.service			4b9deb2d.../10.10.8.10	active	running
deis-store-monitor.service			633cbd72.../10.10.8.11	active	running
deis-store-monitor.service			7e1438d1.../10.10.8.12	active	running
deis-store-volume.service			4b9deb2d.../10.10.8.10	active	running
deis-store-volume.service			633cbd72.../10.10.8.11	active	running
deis-store-volume.service			7e1438d1.../10.10.8.12	active	running
igloo-deis-nodejs-sample_v2.cmd.1.service	7e1438d1.../10.10.8.12	active	running
```

**Comment by LoicMahieu** [comment]
Now I run only deis in stateless mode so I can't reproduce. All logs are properly forwarded to papertrailapp.
I closed the issue, feel free to re-open.
Thanks for support.
