### ISSUE TITLE
SSL Session Ticket Rotation

### ISSUE THREAD

**Issue by croemmich** [deis/deis#4182]
Currently Deis enables SSL session tickets by default, however routers do not share the same keys, which somewhat defeats the point. We should share ticket keys between routers and rotate them frequently. See the discussion in #3915.

**Comment by mboersma** [comment]
@croemmich this is an important feature to finish out the great improvements in #3915. Is periodically rotating the SSL session tickets something you plan to work on, or should we try to tackle this? (And thanks again for making Deis better!)

**Comment by croemmich** [comment]
@mboersma I don't think I'll be able to work on this for at least two weeks. If the Deis teams wants to grab it sooner, by all means!

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant so I'm closing this. Thanks @croemmich!
