### ISSUE TITLE
bug: jenkins test executors tied up waiting for previous jobs to finish

### ISSUE THREAD

**Issue by krancour** [deis/deis#4184]
If multiple executions of the `test-ec2` job-- let's call them A and B-- are running concurrently and A _starts_ before B, but B _finishes_ before A, then job B hangs on the Slack notification step while waiting on a "checkpoint" from job A.

The negative implication of this is that executors can be tied up for a long time when they _could_ be actively testing something instead.

Example (from job 2501):

```
Slack Notifications is waiting for a checkpoint on test-ec2 #2500
```

Possible references to this issue:

https://issues.jenkins-ci.org/browse/JENKINS-29696

https://issues.jenkins-ci.org/browse/JENKINS-9913

**Comment by mboersma** [comment]
This should be fixed in a future version of the Slack notifier plugin for Jenkins: see jenkinsci/slack-plugin#121

**Comment by mboersma** [comment]
The Slack notification plugin for Jenkins can't be updated until someone can write a data migration for it as mentioned in jenkinsci/slack-plugin#106. I built and pinned a local version of the v1.8 plugin with jenkinsci/slack-plugin#122 added, so hopefully this fixes the issue for Deis CI until a new plugin is released.

**Comment by mboersma** [comment]
This was fixed in the Slack plugin itself, so my local-hack version isn't needed, and jobs won't serialize on Slack notifications any more. :rabbit2:
