### ISSUE TITLE
k8s: Use Downward API to expose namespace, pod name

### ISSUE THREAD

**Issue by technosophos** [deis/deis#4187]
It is probably a good practice for us to use the Kubernetes Downward API to add some environment variables into the container. Some simple changes to the pod spec in the rc would get us some useful information.

Downward API:
http://kubernetes.io/v1.0/docs/user-guide/downward-api/
Example: 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/downward-api/dapi-pod.yaml

Things I think we should probably expose:

- APP_NAME (pod name)
- APP_NAMESPACE (pod namespace)
- APP_LABELS (if we can get these into a pretty list)

Are there other pieces of metadata that might be good to add? Is there a way we can get the Docker image and label names? That would be useful for debugging.

If we're going to quickly switch the app name to be the same as DEIS_APP, then APP_NAME is probably redundant.

**Comment by technosophos** [comment]
Looking at the docs again, it appears that labels might not be available to the downward API.

**Comment by kmala** [comment]
I had checked this before and it supports only names and namespaces currently. I wanted it to be able to get nodename so that we could get the host ip using the spec.nodename as environment variable(https://github.com/GoogleCloudPlatform/kubernetes/issues/11288).

**Comment by bacongobbler** [comment]
This is fixed in v2.
