### ISSUE TITLE
proposal: upgrade to latest version of swarm

### ISSUE THREAD

**Issue by krancour** [deis/deis#4188]
I think this may eliminate the need for us to go hunting down the etcd leader at startup.

**Comment by mboersma** [comment]
This is a good idea, I just want to point out it's not a trivial effort. We made significant changes to an earlier version of Swarm that was undergoing major code churn at the time: https://github.com/deis/swarm

**Comment by carmstrong** [comment]
We've also not heard a peep from users about Swam, so I don't expect it to be a priority for us to maintain moving forward. Kubernetes has a ton of support from our users.

**Comment by smothiki** [comment]
Latest version of swarm is still have some issues that we fixed in our fork. Porting the code to latest swarm version takes lot of time.

**Comment by mboersma** [comment]
This would potentially fix #3783, although I wasn't able to reproduce that during v1.9 stress tests of swarm.

**Comment by smothiki** [comment]
Its better to move to latest version of swarm once node failover mechanism is implemented

**Comment by krancour** [comment]
Closing this.  It's not a trivial effort and our swarm tech preview hasn't gained any significant traction.  I don't think the effort could be justified.
