### ISSUE TITLE
provision-aws-cluster.sh vague error

### ISSUE THREAD

**Issue by technosophos** [deis/deis#4198]
Recently, the provision-aws-cluster.sh script got a new check at the end. It runs `deisctl list` repeatedly, looking for a successful exit. It times out after a few minutes.

https://github.com/deis/deis/blob/master/contrib/aws/provision-aws-cluster.sh#L150

The first few times I got this message, I thought the entire cluster install had failed, and I destroyed and re-installed the cluster multiple times. Later, I realized that this message is actually harmless.

I'm sure this is here for a good reason, but the messaging doesn't make any sense. Is it an error if it times out? If so... what are we supposed to do? If it's a warning, then put it in yellow. But in any event, give some clear indication of what the user needs to do.

In my tests, it appears that the *only* role for this is to delay until running the deisctl command to set the proxy type on nginx. If that's the case, let's make this explicit so that the user knows what to do.

**Comment by mboersma** [comment]
The goal of the `deisctl` loop is to ensure provisioning waited until `etcd2` is actually up and running. Checking fleet is an indirect way of doing that.

If you don't have the provisioning key available through ssh-agent, this will time out and print a red error that we couldn't verify core services are running. (Previously, if you don't have the correct key available, this would print a red error that proxyProtocol couldn't be enabled.) We could suggest in both error messages that the user run `ssh-add`.

**Comment by technosophos** [comment]
That would be better. And that probably explains the error I got. I wish I'd captured the output, because it looked like Christmas -- red and green all over. But I had no idea what to do.

If the `deisctl list` thing is a real error, why don't we just stop the script and print an error with the kind of message you suggest? That would definitely be more helpful. Right now, it prints that vague error and then goes on to try to set proxyProtocol anyway.

**Comment by mboersma** [comment]
Well...both are errors, but both are generally recoverable. If they succeed, we know the cluster's etcd2 is happy and proxyProtocol was set. If they fail, usually you can `ssh-add` and try again to set proxyProtocol, and you're fine.

Maybe we should make the first one a yellow warning and keep the second one red, then add a suggestion about `ssh-add` to the second error message? I can see that it's confusing to print the green "Your cluster is running" message in between these two errors as well; maybe that should go last?
