### ISSUE TITLE
Have provision-aws-cluster tell you your DEISCTL_TUNNEL

### ISSUE THREAD

**Issue by technosophos** [deis/deis#4199]
The new version of `provision-aws-cluster.sh` sets its own DEISCTL_TUNNEL to the IP address of the first EC2 instance in the cluster. This works, and is convenient.

But we should pass this info on to the user, who otherwise is stuck following the vague instructions in the user guide (http://docs.deis.io/en/latest/installing_deis/install-platform/#install-deis-platform).

Can we just emit a message from the script telling the user to set their DEISCTL_TUNNEL to the address we autodiscover?

**Comment by mboersma** [comment]
See also #3629.
