### ISSUE TITLE
`deisctl dock` requires full name of the container

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#4205]
Most other commands rely on `deis-` as a prefix. For example, `deisctl journal controller` will retrieve the logs for the `deis-controller` component. However, `deisctl dock` requires the full name:

```
$ deisctl dock controller
Excuting 'docker exec -it controller sh' on container 'controller'
FATA[0000] Error response from daemon: no such id: controller
$ deisctl dock deis-controller
Excuting 'docker exec -it deis-controller sh' on container 'deis-controller'
/app #
```

**Comment by krancour** [comment]
Related to #4210

**Comment by krancour** [comment]
^ This is solved pretty easily after that's merged.  Will hold on it until then.
