### ISSUE TITLE
k8s: change the port on which apiserver is running

### ISSUE THREAD

**Issue by kmala** [deis/deis#4208]
Currently Mesos runs java on port 8080 and kubernetes is also running the apiserver on the port 8080. Change the kubernetes apiserver to run on a different port.

**Comment by krancour** [comment]
Is there any real reason for anyone to run both Mesos _and_ k8s?  The controller can only _use_ one scheduler module at a time anyway, right?

Thinking out loud... probably the only scenario where this could be a problem is if someone evaluates one then without properly shutting it down, installs the other on the same cluster.

**Comment by bacongobbler** [comment]
yep, that would be the only time when someone would hit this. The simplest workaround is to not install and start both schedulers at the same time for now.

**Comment by carmstrong** [comment]
> The simplest workaround is to not install and start both schedulers at the same time for now.

:+1: I don't think it's worth worrying about this.

**Comment by jgmize** [comment]
> Is there any real reason for anyone to run both Mesos and k8s? The controller can only use one scheduler module at a time anyway, right?

No reason to worry about it now, but eventually it might be interesting to run deis on top of [kubernetes-mesos](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/contrib/mesos) once some of the [issues](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/contrib/mesos/docs/issues.md) have been addressed.
