### ISSUE TITLE
Proposal feat(k8s): custom labels per application

### ISSUE THREAD

**Issue by aledbf** [deis/deis#4211]
The idea is to allow additional labels in the application besides name and type defined with the variable `K8S_LABELS`. For instance `deis config:set K8S_LABELS="content=json,platform=nodejs"`
This labels are appended to the defaults and the new ones cannot override the defaults

**Comment by bacongobbler** [comment]
Would this be considered an integration point for `deis tags`, since kubernetes also performs scheduling based on the labels of the pod in question?

**Comment by bacongobbler** [comment]
closing as fixed via https://github.com/deis/workflow/pull/261
