### ISSUE TITLE
GCE provisioning fails with flannel errors

### ISSUE THREAD

**Issue by mboersma** [deis/deis#4217]
As reported on IRC, the Deis v1.9 flannel service reports "Error looking up interface eth0: no such network interface" on a newly provisioned GCE cluster. Potentially having the create-gce-user-data script remove eth0 would fix this (ens4v1 is apparently preferred).

See the [original conversation](https://botbot.me/freenode/deis/2015-08-05/?msg=46498456&page=3) for more detail.

**Comment by rimusz** [comment]
@mboersma it should be fixed in v1.9 :), as GCE provisioning is fully broken. I can do more testing tomorrow and issue the PR for `create-gcd-user-data`
