### ISSUE TITLE
Proposal feat(controller): add url to check status

### ISSUE THREAD

**Issue by aledbf** [deis/deis#4219]
Something like `/health-check` for `GET` and `HEAD` methods without authentication that returns 200 as status code and OK in the body.

**Comment by bacongobbler** [comment]
:+1: makes sense. The root path used to be where the UI was, but since that's gone by default it just returns a 404. I can see the reason behind this.

**Comment by bacongobbler** [comment]
note that this has been resolved in v2: https://github.com/deis/workflow/pull/288
