### ISSUE TITLE
tests & provisioning should wait for full etcd quorum

### ISSUE THREAD

**Issue by mboersma** [deis/deis#4220]
Run `make dev-cluster && deisctl list`. Notice that most services were scheduled to a single node. This is because fleet responded while etcd was still growing the cluster, so services were scheduled while only one machine was a member. Additionally, some AWS tests have stalled out here:
```
Routing mesh...
deis-router@3.service: loaded
deis-router@2.service: loaded
```
My assumption is that we don't yet have 3 machines in the cluster at this point.

Really all provisioning and tests of this type should poll until `fleetctl list-machines -no-legend | wc -l` equals `DEIS_NUM_INSTANCES` so that units are scheduled properly.

**Comment by krancour** [comment]
Agree.  I have been bitten by this many times locally lately.  I think it's been worse since the upgrade to etc2 since the containerized etcd2 takes longer to start on account of the `docker pull`.

I'll take this one.

**Comment by bacongobbler** [comment]
This also causes issues with `make dev-cluster` sometimes where it won't be ready to set config commands because we're still waiting on etcd:

```
==> deis-03: Running provisioner: shell...
    deis-03: Running: inline script
ssh-add ~/.vagrant.d/insecure_private_key
Identity added: /home/bacongobbler/.vagrant.d/insecure_private_key (rsa w/o comment)
deisctl config platform set sshPrivateKey=/home/bacongobbler/.vagrant.d/insecure_private_key
Error: failed initializing SSH client: timed out while initiating SSH connection
Makefile:26: recipe for target 'dev-cluster' failed
```

**Comment by bacongobbler** [comment]
closing as irrelevant for v2.
