### ISSUE TITLE
Deis publisher throwing error after 1.8 to 1.9 upgrade of stateless-platform

### ISSUE THREAD

**Issue by geeksoul-me** [deis/deis#4227]
I run a stateless deis platform (without ceph).Everything was running fine for a week till now.
But a few hours ago, I updated everything to 1.9 from 1.8, dies-publisher is throwing out a error in logs .
```
deis-publisher[1]: 2015/08/07 04:41:55 strconv.ParseInt: parsing "": invalid syntax
```
This is continuously logging since few hours.

I don't any other visible issue to my app containers from this.

**Comment by LoicMahieu** [comment]
I am also encounter this in my fresh install of Deis `1.9` in stateless installation. I also don't see any visible effect of this.

**Comment by bacongobbler** [comment]
Yes, this was something introduced recently from the new healthcheck feature in #4127, but it's not a critical issue. I'll patch that up so we're not trying to convert an empty string to an integer when the etcd key `/deis/config/appname/healthcheck_initial_delay` or `/deis/config/appname/healthcheck_timeout` doesn't exist. Thanks for the report!
