### ISSUE TITLE
Proposal isolating etcd/planes/router mesh

### ISSUE THREAD

**Issue by rimusz** [deis/deis#4229]
Isolating etcd doc http://docs.deis.io/en/latest/managing_deis/isolating-etcd/ should be improved, as it is not really clear for the most of users.

Also it would make a sense to move etcd part from user-data to extra templates for the cluster and proxy ones.
And `create-user-data` scripts then should prompt for the what kind setup e.g. 3 nodes or split setup

**Comment by bacongobbler** [comment]
> should be improved, as it is not really clear for the most of users.

How would you like this document to be improved? Which parts are unclear for you? :)

> Also it would make a sense to move etcd part from user-data to extra templates for the cluster and proxy ones.

That sounds related to #3751. If this is related, would you mind adding your comments there so we can keep track of everything there? Thanks!

**Comment by krancour** [comment]
@rimusz, to echo @bacongobbler and also offer my assistance, I'd be happy to consider some edits to the documentation to improve clarity if you can highlight the parts that are not clear.

As for the suggestion that we could offer this as an option at the time of provisioning-- I agree that would be ideal.  The difficulty in implementing that, however, is that it's not only a matter of managing user-data.  More extensive changes would be required to the provisioning process overall.  Using the AWS provisioning process as an example, we'd have to add the ability to optionally add a second auto-scaling group to the CloudFormation template.  We'd also have to make the analogous change to every other provider as well.  (In the meantime, operators can add a second ASG themselves if they want to isolate etcd and/or the control plane.  This is done fairly easily.)

I think we absolutely should tackle this, but I think it needs to be part of a broader effort to develop a provider-agnostic provisioning process.  With a provider-agnostic process in place, it would become less of a maintenance burden to begin supporting a modest number of pre-baked cluster configurations.  That proposal is being tracked in #1406 if you would like to contribute to that conversation as well.

**Comment by rimusz** [comment]
@krancour I think first thing should be included is proper proxy setup example for etcd, which needs to replace the etcd cluster part one.

Isolating planes needs a bit more details, expanding on how isolating planes should be done, how many servers are recommended for that.

**Comment by bacongobbler** [comment]
closing as irrelevant for v2.
