### ISSUE TITLE
Inaccurate output: executing on "container"

### ISSUE THREAD

**Issue by krancour** [deis/deis#4232]
```
$ deisctl ssh controller echo foo
Executing 'echo foo' on container 'controller'
foo
```

> ```
Executing 'echo foo' on container 'controller'
```

That is not an accurate statement.  The command is executing remotely on the host that is hosting that container.  The hostname should probably be shown instead.

**Comment by carmstrong** [comment]
If we have the host: "Executing 'echo foo' in container 'controller' on host 'core-01'."

**Comment by krancour** [comment]
@carmstrong I don't think that's accurate even.  Observe:

```
$ deisctl ssh controller hostname
Executing 'hostname' on container 'controller'
deis-03
```

There's no part of what's going on there that's happening _in_ the container.

**Comment by krancour** [comment]
(I should have gone straight to that second example.)

**Comment by carmstrong** [comment]
Ah, I see. So it's just running on the host which runs the target? That should probably be updated.

**Comment by krancour** [comment]
Yup.  I'm on it.

**Comment by bacongobbler** [comment]
Yep, nice catch. `deis run` runs the command inside the container. `deisctl dock` is the one that starts a shell in the container, but `deisctl ssh` runs on the host so you can do `deisctl ssh controller docker logs deis-controller`.

**Comment by krancour** [comment]
@carmstrong @bacongobbler hostname isn't easily accessible.  The host that container _x_ is running on is located via fleet, obviously.  The information fleet returns is machine id, public IP, and metadata.  Personally, if I can't see hostname (which probably isn't that useful anyway), I'd rather see public IP than machine id.  What are your thoughts?

**Comment by carmstrong** [comment]
> I'd rather see public IP than machine id

:+1:

**Comment by bacongobbler** [comment]
We could just make it `Executing 'echo foo' on host running 'controller'`. Either that or nothing at all so users can just do something like `HOST_RUNNING_CONTROLLER=$(deisctl ssh controller hostname)`.

If we can retrieve the public IP before creating the SSH session then that would be ideal, though.
