### ISSUE TITLE
Add ability to define separate cluster network

### ISSUE THREAD

**Issue by zapient** [deis/deis#4234]
For those with 2+ NIC's it would be nice to be able to configure a separate network for cluster. 

http://ceph.com/docs/master/rados/configuration/network-config-ref/

Looks like ceph-docker added it back in July: https://github.com/ceph/ceph-docker/blob/master/daemon/config.static.sh

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant so I'm closing this.
