### ISSUE TITLE
add deis domains:transfer support

### ISSUE THREAD

**Issue by olalonde** [deis/deis#4237]
I'm trying to do blue-green deployment with Deis. So I have two Deis apps (app-green and app-blue). At any time either app-green OR app-blue should be live (e.g. serve traffic for app.domain.com). Everything good so far except for one thing: is there any way to atomically change app-green and app-blue's DNS configs so that I can redirect traffic to one app or the other for my domain name atomically?

e.g: 

``` bash
deis domains:remove app.domain.com --app app-green && deis domains:add app.domain.com --app app-blue
```

Any way to make this atomically so there is no downtime? Other suggestions?

**Comment by bacongobbler** [comment]
Hmm... It might be easier to cut it over with a domain record outside of Deis. Try this: start with a CNAME record for app.domain.com pointing to app-green.domain.com. Then, change the CNAME to app-blue.domain.com when it is time to cut over. That might be the easiest way to make sure there's no downtime.

**Comment by olalonde** [comment]
Oh right... should have thought about this -_-

**Comment by nathansamson** [comment]
How would that work? As dat as  understand this is on the same deis
cluster. So the routers would work on hostname to route to the correct
application.... In fact I never setup cnames with app-name.deishost.example
but just to deis.deishost. example...

To answer the original question do you actually observe downtime? As far as
I would guess by the time the routers refresh their Config the new domain
should already be there (as the ttl is around 10s afaik) so unless you are
really unlucky to hit the small refresh window you should be fine.

Nathan
Op 9 aug. 2015 20:05 schreef "Olivier Lalonde" <notifications@github.com>:

**Comment by olalonde** [comment]
Oh yeah @nathansamson is correct, I can't just change the CNAME.

> To answer the original question do you actually observe downtime?

I haven't tried yet. Oh I see what you mean... if I change the domains quickly, the router might only restart once right?

**Comment by nathansamson** [comment]
That is what I expect...

Obviously there is still a small window where things can fail, and this window can be bigger if your client has slow / bad internet connection (even worse if the command fails, and you manually need to restart it)

I guess a real atomic replace of domains in the cotroller isn't a bad idea, but I think the current situation is probably good enough....

What is your actual reasoning for doing cutovers like this? I can understand if they are different deis clusters (eg upgrade of your cluster), but for application restarts I don't really see the need

**Comment by krancour** [comment]
@olalonde Deis already does blue/green in a manner of speaking.  During any release (deployment or config change), the controller waits for the new containers to be alive before re-routing incoming traffic to them and killing the old ones.  With the 1.9.0 release, @bacongobbler improved upon that substantially by allowing for you to insert your own custom application health check into that process.

The above might be good enough for most scenarios.  Where it breaks down is if you have more extensive verification testing that you want to do post-deploy, _before_ flipping the switch.

@nathansamson is correct that the CNAME magic won't work.  If you request `myapp.example.com`, it doesn't matter if that's a CNAME for `myapp-blue.my-deis.example.com` or `myapp-green.my-deis.example.com`.  In either scenario, when the request hits a router, the host header will still say `myapp.example.com`, and that router will send it wherever the configuration says to at the moment.  Whether it routes to blue or green will depend entirely on which of those is configured at that time to answer requests for `myapp.example.com`.

You _can_ quickly alter the configuration as @nathansamson has suggested.  To dispel one bit of confusion, however, that does not require the routers to restart.  Routers are dynamically re-configured periodically with a service called confd-- without any downtime.

The thing that will dictate whether you have any downtime or not is how fast you can update the configuration.  There _could_ be a very narrow window where you've removed the domain from "blue," for instance, but haven't added it to "green" yet.  This being the case, there might be a strong case for a feature request here.  As a workaround in the meantime, you could probably minimize that window by scripting those config changes.

**Comment by olalonde** [comment]
@krancour thanks for the clarifications. @nathansamson the reason I'm doing this style of deployment is that once in a while, I need to completely wipe out my app's database and rebuild it from scratch but this process takes a few hours (syncing the Bitcoin blockchain). In the meanwhile, I want the old version of the app/db to keep running. I suppose I could just rebuild the database and use `deis config` to tell my running app to start using the new database when it's ready. But if the database structure changed in a significant way, my old app code will fail. There are other ways to get around the problem (e.g. do proper database migrations) but it would involve more work for me and I'd rather go with a simple process. I could also have two clusters and do the switch over at DNS level but I have a limited budget.

I can accept some downtime but it would be nice to have this feature :) If we can agree on a deis command syntax or process to do this, I could attempt to do it though I don't guarantee I will figure it out all by myself. Maybe one solution would be to have `deis domains:add some.domain.com --force` which would remove `some.domain.com` from other apps as well.

**Comment by krancour** [comment]
> Maybe one solution would be to have deis domains:add some.domain.com --force which would remove some.domain.com from other apps that use it

That's a useful thought.  Ping @Joshua-Anderson.  Thoughts?

**Comment by Joshua-Anderson** [comment]
:+1: It wouldn't be too difficult to do, but I probably don't have time this week, as I have a lot I need to finish. I may have time to tackle this in the next month or so.

**Comment by bacongobbler** [comment]
To add my thoughts to this, I would like a native command rather than a flag. Something like `deis domains:update mycustomdomain.com` (with `--app` as a flag for non-interactive shells) would allow a user to modify and transfer a domain from one app to another. Of course, the user must have permission to both applications, but essentially that would allow us to update the db records without any deletions, which in turn will ensure that the router will re-template the domain route without any downtime. That way we can use this for more than just app transfers in the future.

Does that sound like something you'd want to tackle, @olalonde?

**Comment by olalonde** [comment]
@bacongobbler Yep, I'd be happy to try.

**Comment by krancour** [comment]
@olalonde first, thanks for the willingness to take a crack at it.  Before you get going, it's worth mentioning that our intention is to shortly transition off of the python-based `deis` CLI and onto a new one written in go.  The latter is functionally equivalent (save for a few minor bugs) and is being put through its paces now.  I'm mentioning this so you'll know to apply your efforts toward the go-based client and not the old python-based one.

**Comment by olalonde** [comment]
@krancour thanks for pointing out,

So far, I managed to install everything locally and looked around the code. If I understand correctly, I would need to add a method around here (https://github.com/deis/deis/blob/v1.9.0/controller/api/models.py#L1002) that only gets executed when a POST parameter is present (e.g. `force` or `update`) which would remove the old domain before carrying on with adding the new one (current behaviour is to refuse adding the domain if it is not unique). I suppose I would also need to make sure that the user has permission to the app that currently owns the domain. I think the etcd code `_etcd_publish_domains` will work as is and will just overwrite the previous app name with the new one (https://github.com/deis/deis/blob/v1.9.0/controller/api/models.py#L1190)

**Comment by Joshua-Anderson** [comment]
@olalonde That seems to imply you don't have a SSL library installed. Have you installed openssl where python can find it(via homebrew, etc)?

**Comment by olalonde** [comment]
`brew install postgresql` followed by `make setup-venv` fixed that problem.

**Comment by deis-admin** [comment]
This issue was moved to deis/controller#1218
