### ISSUE TITLE
Error pulling image ... ApplyLayer fork/exec ... /usr/bin/docker: cannot allocate memory

### ISSUE THREAD

**Issue by olalonde** [deis/deis#4238]
Getting the following error once in a while when doing a `git push deis`:

```
Aug 09 19:17:13 ip-10-21-1-251.ec2.internal sh[27909]: 8a497e4d8449: Pulling metadata
Aug 09 19:17:14 ip-10-21-1-251.ec2.internal sh[27909]: 8a497e4d8449: Pulling fs layer
Aug 09 19:17:27 ip-10-21-1-251.ec2.internal sh[27909]: 8a497e4d8449: Error downloading dependent layers
Aug 09 19:17:27 ip-10-21-1-251.ec2.internal sh[27909]: 78a282e472b1: Error pulling image (v3) from 10.21.1.252:5000/livenet-blue, endpoint: http://10.21.1.252:5000/v1/, ApplyLayer fork/exec /usr/bin/docker: cannot allocate memory stdout:  stderr:
Aug 09 19:17:27 ip-10-21-1-251.ec2.internal sh[27909]: 78a282e472b1: Error pulling image (v3) from 10.21.1.252:5000/livenet-blue, ApplyLayer fork/exec /usr/bin/docker: cannot allocate memory stdout:  stderr:
Aug 09 19:17:27 ip-10-21-1-251.ec2.internal sh[27909]: time="2015-08-09T19:17:27Z" level="fatal" msg="Error pulling image (v3) from 10.21.1.252:5000/livenet-blue, ApplyLayer fork/exec /usr/bin/docker: cannot allocate memory stdout:  stderr: "
Aug 09 19:17:27 ip-10-21-1-251.ec2.internal systemd[1]: livenet-blue_v3.web.1.service: control process exited, code=exited status=1
Aug 09 19:17:27 ip-10-21-1-251.ec2.internal systemd[1]: Failed to start livenet-blue_v3.web.1.
Aug 09 19:17:27 ip-10-21-1-251.ec2.internal systemd[1]: Unit livenet-blue_v3.web.1.service entered failed state.
Aug 09 19:17:27 ip-10-21-1-251.ec2.internal systemd[1]: livenet-blue_v3.web.1.service failed.
```

deis `v1.7.3`

The machine it is starting on still seems to have memory. The image is relatively large though this appears to be RAM related?

```
core@ip-10-21-1-251 ~ $ free -m
             total       used       free     shared    buffers     cached
Mem:          7517       7456         60         22        516        700
-/+ buffers/cache:       6239       1277
Swap:            0          0          0

core@ip-10-21-1-251 ~ $ docker -v
Docker version 1.5.0, build a8a31ef-dirty
```

**Comment by olalonde** [comment]
Well I noticed I posted the same issue here before and since it is probably not an issue with deis itself, going to close this.

**Comment by szymonpk** [comment]
It's [upstream issue](https://github.com/docker/docker/issues/8539) with docker, it's fixed in 1.7.1(?). You have to restart dockerd from time to time, which will result in containers reboot on host.

**Comment by olalonde** [comment]
@szymonpk oh thanks! Any ideas how I would update docker on my CoreOS machines without removing them entirely? (I have 4 machines)

**Comment by szymonpk** [comment]
Just don't do it, as I wrote on irc - docker 1.6.2 have issues with pulling(or pushing?) multiple images from private registry. 1.7.1 may fix this but it's in alpha of coreos. @carmstrong wrote, when 1.7.1 is in coreos stable they will test it and there is non-zero chance to see it in 1.10 but no hard promises.

**Comment by olalonde** [comment]
@szymonpk thanks, can wait until later. I'll restart dockerd once in a while as a workaround. Or maybe write a fleet unit that does this for me.

**Comment by carmstrong** [comment]
Closing, as this should now be fixed with the latest release.

**Comment by olalonde** [comment]
Great thanks!
