### ISSUE TITLE
deis 1.9.0 does not “decorate” the Fleet units

### ISSUE THREAD

**Issue by rimusz** [deis/deis#4240]
I have tried to isolated the Planes as per http://docs.deis.io/en/latest/managing_deis/isolating-planes/ but the `deisctl` command line tool does not “decorate” the Fleet units.

'cloud-unit' files got necessary metadata controlPlane=true and dataPlane=true,routerMesh=true
but even setting with `deisctl config platform set enablePlacementOptions=true`, fleet units did not get the   
fleet "decoration"

**Comment by krancour** [comment]
@rimusz that feature was just recently merged into master to be included in the v1.10.0 release.  The documentation on deis.io is from and for the master branch.  If you'd like to get "early access" to this feature and you have go installed, you could build and install deisctl from source in the master branch.

```
git clone git@github.com:deis/deis.git
cd deis/deisctl
make build install
```

Apart from this, remember that (even in Vagrant) nodes also need to be tagged with appropriate metadata to support these decorators.

**Comment by rimusz** [comment]
@krancour so the  `http://docs.deis.io/en/latest/managing_deis/isolating-planes/#decorating-units` should be updated then from `To complement the cloud-config described above, Deis 1.9.0 and later ` to `To complement the cloud-config described above, Deis 1.10.0 and later ` as it confuses :) 

For now I got it working manually updating fleet units.

**Comment by krancour** [comment]
@rimusz nice catch.  I'll have that fixed today.

**Comment by bacongobbler** [comment]
I think that's the intention of /latest/, but we know that it's caused confusion/communication issues in the past. If you want to read docs for v1.9.0, use http://docs.deis.io/en/v1.9.0/.
