### ISSUE TITLE
Fresh AWS Install: Docs should say to install deisctl first

### ISSUE THREAD

**Issue by Crispy1975** [deis/deis#4252]
Out of interest followed the AWS install docs as a new user would and following each section step-by-step got me to a spun-up CloudFormation, however the supplied provisioning script started to complain that `deisctl` was not found (obviously as it was not installed).

    ./provision-aws-cluster.sh: line 148: deisctl: command not found
    Waiting until fleet is up and running ...

The docs need to make it clear for new users that `deisctl` should be installed *before* attempting to provision the CoreOS cluster.

**Comment by mboersma** [comment]
> deisctl should be installed before attempting to provision

Right you are--sorry we missed this. I'll update the docs.

**Comment by Crispy1975** [comment]
Thanks. Might have a few more relating to the AWS provisioning into an existing VPC, but will reserve judgement once I've gone over it a few times more to make sure it's not me. :)
