### ISSUE TITLE
builder returns success when new release fails to deploy

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#4255]
When deploying a new release of an app but it fails mid-way due to a scheduler error like `failed to create some containers`, the builder will still return success. The indicator to see if the app failed is by checking which version was deployed. For example, when deploying v2:

```
done, foo:v1 deployed to Deis
```

Will be displayed when the app failed to be scheduled.

**Comment by carmstrong** [comment]
@krancour We should look into this as part of the battle testing mandated by #4222

**Comment by krancour** [comment]
@carmstrong-- agreed.

**Comment by laurrentt** [comment]
+1 This is also true when the app being updated fail to pass healthchecks

**Comment by bacongobbler** [comment]
closing as irrelevant for v2
