### ISSUE TITLE
Install Jenkins plugins for ease of debugging/rebuilding

### ISSUE THREAD

**Issue by sgoings** [deis/deis#4257]
- [NodeLabel Plugin](https://wiki.jenkins-ci.org/display/JENKINS/NodeLabel+Parameter+Plugin) so people can choose individual boxes to run a job if they so choose
- [Matrix Reloaded](https://wiki.jenkins-ci.org/display/JENKINS/Matrix+Reloaded+Plugin) so people can choose which subset of the matrix they'd like to actually retry

**Comment by mboersma** [comment]
Installed Jenkins plugins:
- Matrix Reloaded Plugin 1.1.3
- Node and Label Parameter plugin 1.5.1

**Comment by sgoings** [comment]
Thanks @mboersma!
