### ISSUE TITLE
Problem with apps that can run on configurable port

### ISSUE THREAD

**Issue by krancour** [deis/deis#4262]
Take our own example-ruby-sinatra app as an example:

https://github.com/deis/example-ruby-sinatra

Its `Procfile` reads as follows:

```
web: bundle exec ruby web.rb -p ${PORT:-5000}
```

This permits the port that the Sinatra app runs on within the container to be configured via the `$PORT` environment variable.

Try the following:

```
$ git clone git@github.com:deis/example-ruby-sinatra.git
$ cd example-ruby-sinatra
$ deis create
$ deis config:set PORT=5001
$ git push deis master
$ deis open
```

Observe that you get a 502 from the router.

This happens (at least) with both the Fleet and k8s schedulers.

Digging into the reason, it seems the publisher may (I haven't confirmed) do a `docker inspect` of containers in order to ascertain what port is exposed and takes this into consideration when publishing.  Likewise (confirmed) the k8s scheduler module for the controller also does a `docker inspect` to find what port is exposed, and takes this into consideration when defining the app's service.  In either case, both believe that the application is running on port 5000 (because that is what is exposed), even though this may not actually be the case at all.

It's difficult to say what the right resolution is for this.  (I think) builder generates the Dockerfile for each app (unless an app provides their own) and _this_ is what dictates what port is exposed.  I don't know how we could make builder smart enough to detect what port an app would _actually_ run on if environment variables might be playing a role in that...

Maybe the real issue is that at least one example app hints this can be done, when in fact it doesn't work.

**Comment by krancour** [comment]
example-python-django is another example app that demonstrates this issue.

`Procfile`:
```
web: gunicorn --bind 0.0.0.0:${PORT:-8000} helloworld.wsgi
```

**Comment by bacongobbler** [comment]
You are correct. The problem here is that any buildpack app is [hardcoded to expose port 5000](https://github.com/deis/deis/blob/master/builder/rootfs/usr/local/src/slugrunner/Dockerfile#L11-L12), which would explain why it'd hang up when you change the port number, and both publisher/kubernetes pick up on that. I don't think there's a resolution for this. If you specify `EXPOSE 5000` in your Dockerfile but your app listens on port 5001, that sounds like uesr error more than a platform issue.

The $PORT logic is a backport from Heroku, where they allocate the exposed port at runtime so you have to listen on $PORT to expect your app to work. We can just remove that logic since I don't imagine this is a Deis example app.

**Comment by krancour** [comment]
Ok.  When time permits I will see about PR'ing affected example apps so we're not hinting that this can be done when in fact it can't.

**Comment by bacongobbler** [comment]
sounds good. To clarify, the $PORT logic is there for compatibility with most of Heroku's apps so we still need it, but manually changing the port envvar is not something we should be promoting due to the issue above :)

**Comment by krancour** [comment]
So our example apps wouldn't be deployable to Heroku without that?  Is this because Heroku selects a port _for_ you and populates `$PORT`.  I didn't think they do (but I could be wrong).  Wouldn't these apps deploy fine to Heroku if the port number were hardcoded in the Procfile?  I guess I could try.

**Comment by Joshua-Anderson** [comment]
@krancour Heroku chooses the port for you and populates `$PORT`. If port was hardcoded they couldn't be deployed to heroku.

**Comment by bacongobbler** [comment]
^^

**Comment by krancour** [comment]
Got it.  I don't think I'd realized they chose the port for you.  It's important to us that the example apps remain deployable to Heroku?

**Comment by mboersma** [comment]
I think it's important that our apps can be deployed to Heroku as-is, even if $PORT doesn't behave the same on Deis.
