### ISSUE TITLE
App logs not being aggregated when scheduler is k8s

### ISSUE THREAD

**Issue by krancour** [deis/deis#4264]
When using k8s as the scheduler, one can use `docker logs` to observe that an example app _is_ writing log messages, but these same messages aren't visible via `deis logs`.  Application events written by `deis-controller` do show up, but that's it.  My best guess is that `deis-logspout` is somehow not forwarding logs from such containers.

**Comment by carmstrong** [comment]
Possibly related to #3633

**Comment by krancour** [comment]
I'm no longer thinking this is _technically_ related to k8s, but I do think it's a problem of scale.  I'll close this and move further discussion ot #3633
