### ISSUE TITLE
Consider enumerating etcd peers instead of using a discovery URL

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#4268]
The etcd discovery service is meant only to bootstrap a new cluster, and there's no guarantee that the endpoint will work indefinitely. This can prevent users from adding new hosts to an existing CoreOS cluster. We should switch from a discovery service to manually specifying the cluster's peers.

To do this, we'll need to edit [user-data.example](https://github.com/deis/deis/blob/master/contrib/coreos/user-data.example) to replace the discovery URL with a list of etcd peers. We'll also need to specify IP addresses on each cloud provider so the hosts come up with a known IP address. We should be able to do this on AWS by disabling DHCP, but other providers may be more difficult.

**Comment by rimusz** [comment]
+1

**Comment by rimusz** [comment]
@carmstrong on GCE, instance needs to be created with `--can-ip-forward`, static IP added to `user-data ` file and forward route created for that static IP

**Comment by bacongobbler** [comment]
this isn't something we'll be able to get for the LTS release, and since etcd is going away in v2 I think we can safely close this as a wontfix.
