### ISSUE TITLE
deis logs with kubernetes missing process number in app logs

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#4271]
I found this change to be a little confusing:

```
><> deis logs
[...]
2015-08-13T22:57:19UTC go[web]: 2015/08/13 22:57:19 listening on 5000...
```

With fleet, this used to be `go[web.1]` which was clearer to the user which instance was being hit from incoming requests. This is also how `heroku logs` are formatted, so it seems like this is a regression of sorts for #4222.

**Comment by smothiki** [comment]
https://github.com/deis/deis/blob/master/logspout/logspout.go#L87-L98
here is the logic where we are sending name and process.[num]  type to logger if other schedulers and If kubernetes we are just sending name and Process type as in kubernetes container names are generated by kubelets there is no way to tell which pod is 1 or which pod is 2

**Comment by smothiki** [comment]
To identify the container we can change the regex to get next 8 digits after name and Proc type match. 
if the container name is k8s_go.web.59d25a52_.......... we can log go[web.59d25a52].....

**Comment by deis-releases** [comment]
+1 for pod ID

**Comment by carmstrong** [comment]
> +1 for pod ID

IT HAS BECOME SENTIENT!

**Comment by krancour** [comment]
@smothiki I like you idea, but I don't think the 8 digits you are referencing are the pod ID.

Take the following container name as an example:

```
k8s_lively-kerchief-web.566905c7_lively-kerchief-v2-web-06nko_lively-kerchief_6f96dd8e-4c38-11e5-8941-0e8e7928b8f5_7586f409
```

Accoring to `kubectl` the name of that pod is `lively-kerchief-v2-web-06nko`

IMO, the six digits `06nko` are the meaningful part here.

**Comment by krancour** [comment]
I think this may be the correct regex:

```
^k8s_([a-z0-9-]+)-[a-z]+\.[\da-f]+_[a-z0-9-]+-([a-z]+-[\da-z]*)_
```
