### ISSUE TITLE
Proposal: Optional Buildpacks

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/deis#4272]
This proposal would allow people to use builder without installing buildpacks.

Why do this?

Primarily because buildpacks are huge. If only you use dockerfile based apps, disabling buildpacks saves startup time and diskspace.

How would this work?

There would be a etcd key called `/deis/builder/disableBuildpacks`. If that is set, builder would skip buildpack setup and regect pushes for apps without `Dockerfiles`.

Migration?

When upgrading the cluster the user could do nothing or set the ETCD key to disable buildpacks for the new release.

Testing?

This would be tested by builder unit and functional tests.

**Comment by Joshua-Anderson** [comment]
Blocked by Go Builder #4010, soon (fingers crossed) to be merged.

**Comment by technosophos** [comment]
This should be fairly easy to implement, and it would definitely speed things up.

**Comment by technosophos** [comment]
What should happen if `disableBuildpacks` is removed from etcd? I'm thinking that we just lazily fetch slugbuilder and slugrunner the next time an app is pushed.

**Comment by carmstrong** [comment]
> I'm thinking that we just lazily fetch slugbuilder and slugrunner the next time an app is pushed.

:+1: That seems reasonable.

**Comment by bacongobbler** [comment]
> What should happen if disableBuildpacks is removed from etcd? I'm thinking that we just lazily fetch slugbuilder and slugrunner the next time an app is pushed.

We don't publish those images to DockerHub. They're built locally, so we'd have to lazily build them rather than fetch them :)

**Comment by Joshua-Anderson** [comment]
> I'm thinking that we just lazily fetch slugbuilder and slugrunner the next time an app is pushed.

I'm a little concerned that users would get impatient or the push would timeout. Would a better option possibly be to lazy fetch as soon as buildpacks are enabled, and then reject all buildback app pushes with a message saying the buildpack is are being fetched?

Now that the go builder is merged (\o/), hopefully I'll be able to tackle this.

**Comment by mboersma** [comment]
This is still a good idea, but since it's a bazillion years old in internet time and Deis development focus has shifted to version 2, where these pieces are already detachable and so potentially optional, I'm closing it.
