### ISSUE TITLE
Docker won't start in new cluster

### ISSUE THREAD

**Issue by ineu** [deis/deis#4275]
I've just provisioned new 1.9 cluster on CoreOS stable (723.3). Trying to run `deisctl start platform`, it hangs starting first set of services (deis-store-monitor). `docker.service` cannot start:
```
Aug 14 11:23:06 staging-coreos-1 systemd[1]: Dependency failed for Docker Application Container Engine.
Aug 14 11:23:06 staging-coreos-1 systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
```

All docker.service dependencies are satisfied except early-docker:
```
core@staging-coreos-1 ~ $ systemctl status early-docker.target
● early-docker.target - Run Docker containers before main Docker starts up
   Loaded: loaded (/usr/lib64/systemd/system/early-docker.target; static; vendor preset: disabled)
   Active: inactive (dead)
```

What can I do to make it work?

**Comment by ineu** [comment]
Found it. The problem is in flanneld, it is never started. Deis hardcodes `eth0` in cloud config. Flanneld fails to start as such interface doesn't exist. Flanneld retries again and again, never giving `early-docker.target` a change to complete.

Solution here is to remove eth0 from cloud config. Assumption that such interface is always present is wrong, as on bare metal machines interfaces can be named like 'enpXsY...' etc.

**Comment by bacongobbler** [comment]
Yes, this was fixed in master with https://github.com/deis/deis/commit/3769ee2e5e4e747daa7d526e74587b43ac013b07. Does that resolve your issue?

**Comment by ineu** [comment]
@bacongobbler I believe it should. I don't use flannel anyway, so I've just masked it, but it's good to know the issue is fixed. Thank you.
