### ISSUE TITLE
config push / set 500's

### ISSUE THREAD

**Issue by cheshirecatalyst** [deis/deis#4284]
So for the past few releases I will end up with one or two apps that i must use -a app-name to mess with because for some reason attempting to work from within their directory from the deis added remote will cause it to fail. Other apps are fine working from the remote added by deis and don't need the -a

`KeyError: 'Not a file : /deis/config/sources-availability-test'` and `10.244.77.1 "POST /v1/apps/sources-availability-test/config HTTP/1.0" 500 27 "python-requests/2.5.1 CPython/2.7.5` are the only entries related to this in the controller logs.

currently on 1.9.0 but as mentioned same problem on previous releases with a random app or two

**Comment by cheshirecatalyst** [comment]
Relevant output of `etcdctl ls /deis/config --recursive` before
```/deis/config/sources-availability-test
/deis/config/sources-availability-test/mysql_replica1_url
/deis/config/sources-availability-test/mysql_connection_limit
/deis/config/sources-availability-test/mysql_replica3_url
/deis/config/sources-availability-test/mysql_master_url
/deis/config/sources-availability-test/source_queue_name```

and after

```/deis/config/sources-availability-test
/deis/config/sources-availability-test/mysql_connection_limit
/deis/config/sources-availability-test/mysql_replica3_url
/deis/config/sources-availability-test/mysql_master_url
/deis/config/sources-availability-test/v
/deis/config/sources-availability-test/source_queue_name
/deis/config/sources-availability-test/mysql_replica1_url```

Where i was doing `deis config:set V=R`

**Comment by bacongobbler** [comment]
closing as this has been fixed in LTS and in v2.
