### ISSUE TITLE
Proposal: Upgrade logspout

### ISSUE THREAD

**Issue by krancour** [deis/deis#4292]
Logspout has undergone two major refactors in the time since we forked and enhanced it (mainly for the sake of discovering `deis-logger` host and port from etcd and to hijack the message format).

The master branch of logspout (which is trending toward a v3) is significantly more modular than what we've been using.  The possibility exists that we can bend logspout to our will by creating a module for it, rather than by forking it and hacking on it.

The major motivation for this would be the ability to reap the benefits of upstream bug fixes.

Do other maintainers want to weigh in?

**Comment by bacongobbler** [comment]
If there's a way we can extend logspout without having to maintain the source (keeping the source code upstream), that would be a nice enhancement as well. Otherwise I'm all for a version bump!

**Comment by carmstrong** [comment]
:+1:

**Comment by krancour** [comment]
@bacongobbler @carmstrong 

Trivial example of customizing logspout without forking:

https://github.com/gliderlabs/logspout/tree/master/custom

The major question will be whether the extension points logspout opens are sufficient hooks for us to do all the customizations we need.

**Comment by krancour** [comment]
I took a first swing at such a module here, but it's incomplete, and so far, it crashes my cluster every time I try it.  :astonished:

**Comment by carmstrong** [comment]
Have we reevaluated the need for us to maintain a fork of logspout? Could we ever switch back to using mainline?

**Comment by kalbasit** [comment]
While we're on the subject, I'd love to not change the message format when the message is sent to syslog-compatible (paperclip for instance). It should be changed for the sake of deis logs but I feel it should do so only after it has sent the raw log line to syslog.

**Comment by krancour** [comment]
@carmstrong the very idea here is that we could use mainline logspout and just maintain modules for whatever functionality we need to add... maybe.  Doing so may be easier said then done, but it's the hope.

@kalbasit re: message format... if one is running cephless/stateless and is therefore not running `deis-logger`, or has opted out of `deis-logger` for any other reason, I think we should make it easier to opt-into a syslog-compatible message format.  That being said, if `deis-logger` is the destination for the logs, then the responsibility of emitting syslog-compatible messages, IMO, belongs to `deis-logger`'s drain.

**Comment by krancour** [comment]
See https://github.com/deis/logspout-v3-deis for a possible implementation of a Deis adapter that would allow us to use a newer upstream logspout without forking it.

Also see related upstream logspout issue: https://github.com/gliderlabs/logspout/issues/124

**Comment by carmstrong** [comment]
:+1: On using the logspout master and this plugin.

**Comment by krancour** [comment]
fwiw, I've been using logspout master + the proposed plugin all day while heavily testing other things and have kept one eye on both it and `deis-logger`.  No issues so far.

Most notably, I want to emphasize that upstream logspout master does _not_ appear to suffer from the issue that was reported against our old logspout fork in #3633 and closed by #4291.  It seems to reliably attach to all containers even after many dozens of scaling events where i scaled up or down by 100 at a time.

**Comment by carmstrong** [comment]
@krancour I think it's probably worth PRing our switch to using the new logspout and plugin. I guess shipping v3 officially is a prerequisite for that?

**Comment by krancour** [comment]
Yes, although the plugin currently lacks unit and functional tests... so there's that.

re: an upstream v3 release, I'm working with @progrium on that.

**Comment by carmstrong** [comment]
> although the plugin currently lacks unit and functional tests

Ah, that's right.

**Comment by krancour** [comment]
Closing.  See final comment in #4347
