### ISSUE TITLE
Logspout only discovers logger at startup

### ISSUE THREAD

**Issue by krancour** [deis/deis#4293]
Logspout only discovers the host and port for the `deis-logger` at startup.  If `deis-logger` is rescheduled to another machine, logs are no longer aggregated.

For other components that have a dependency on another component that could move around the cluster, we rely on confd to reconfigure the dependent component.  Since our logspout is a forked and _minimally_ modified version of an older version of logspout, we're not doing any of this.

This also relates to #4292

**Comment by krancour** [comment]
The proposed adapter for logspout v3 fixes this:

https://github.com/deis/logspout-v3-deis

**Comment by krancour** [comment]
The reconciliation loop required to fix this seems like a bigger feature than what we currently are intending to put in the LTS.  However, this _is_ a problem.  Do any other maintainers have thoughts on this?  Ping @bacongobbler and @mboersma

**Comment by krancour** [comment]
Bump @bacongobbler and @mboersma.  This bit someone else today.  Any thoughts on whether this should be fixed in LTS?

**Comment by bacongobbler** [comment]
I feel like this should be fixed for the LTS unless there's a way we can restart the logspout processes through systemd whenever deis-logger is rebooted.

**Comment by krancour** [comment]
Ok.  Tagged it as an LTS issue.
