### ISSUE TITLE
Freshly set up deis cluster does not work [bare-metal]

### ISSUE THREAD

**Issue by cimnine** [deis/deis#4294]
So I set up this new deis cluster because I wanted to switch test those new features like k8s and flannel, but I can't get a cluster up and running.

I followed http://docs.deis.io/en/latest/installing_deis/baremetal/ closely.

My cloud-config looks like this:

    #cloud-config
    ---

    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7jERP9aCrcbFlu/mt/MokpHEqQ4WXI2ECmNnPrpR+81yLJhkzpuScQhHQYvtLMzTS3LSGXZ3RwaLCo6xXbbbLMBgtkHMc0wrotIveuNJTPfJRVQlhY+r4fUPT8ZytygoUX5eaH/ARzmYF2oCL24Fc0S9LOGA/MDED1Vu+cBdA0NJoMyPnvV+lm9LEKZRMM3rDloGIpUEUNaoKyRxyY/QF8svJmjbfNpOp+tQ5RhVztslfJKZLqLzSIg2/mM+uCY77YaqGk9M8R7OjnrgOzugSryIOlE4IM/LWF42bnoHPndLPHxNyO5fVPZYfrw1zemwaTNwfoDiF1jE/aU5coLIZ deis

    hostname: cloud-1

    coreos:
      fleet:
        # We have to set the public_ip here so this works on Vagrant -- otherwise, Vagrant VMs
        # will all publish the same private IP. This is harmless for cloud providers.
        public-ip: 10.250.0.11
        # allow etcd to slow down at times
        etcd_request_timeout: 3.0
      units:
      - name: etcd.service
        command: start
        content: |
          [Unit]
          Description=etcd2 container
          Requires=early-docker.service
          After=early-docker.service
          Before=early-docker.target

          [Service]
          User=etcd
          PermissionsStartOnly=true
          Restart=always
          RestartSec=10s
          LimitNOFILE=40000
          EnvironmentFile=/etc/environment
          Environment="ETCD_IMAGE=quay.io/coreos/etcd:v2.1.1"
          Environment="ETCD_ELECTION_TIMEOUT=2000"
          Environment="ETCD_HEARTBEAT_INTERVAL=400"
          Environment="ETCD_DATA_DIR=/var/lib/etcd2"
          Environment="ETCD_NAME=%m"
          Environment="DOCKER_HOST=unix:///var/run/early-docker.sock"
          ExecStartPre=/bin/sh -c "docker history $ETCD_IMAGE >/dev/null 2>&1 || docker pull $ETCD_IMAGE"
          ExecStartPre=/bin/sh -c "docker inspect $ETCD_NAME >/dev/null 2>&1 && docker rm -f $ETCD_NAME || true"
          ExecStart=/usr/bin/docker run --net=host --rm \
            --volume=${ETCD_DATA_DIR}:/var/lib/etcd2 \
            --volume=/usr/share/ca-certificates:/etc/ssl/certs:ro \
            -p 4001:4001 -p 2380:2380 -p 2379:2379 -p 7001:7001 \
            --name ${ETCD_NAME} \
            ${ETCD_IMAGE} \
            -name ${ETCD_NAME} \
            -data-dir /var/lib/etcd2 \
            -advertise-client-urls http://${COREOS_PRIVATE_IPV4}:2379,http://${COREOS_PRIVATE_IPV4}:4001 \
            -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
            -initial-advertise-peer-urls http://${COREOS_PRIVATE_IPV4}:2380,http://${COREOS_PRIVATE_IPV4}:7001 \
            -listen-peer-urls http://0.0.0.0:2380,http://0.0.0.0:7001 \
            --heartbeat-interval ${ETCD_HEARTBEAT_INTERVAL} \
            --election-timeout ${ETCD_ELECTION_TIMEOUT} \
            --discovery https://discovery.etcd.io/7e7534b138720000fbd1c96ffd128298
          ExecStop=-/usr/bin/docker stop $ETCD_NAME
      - name: etcd2.service
        mask: true
      - name: docker-tcp.socket
        command: start
        enable: true
        content: |
          [Unit]
          Description=Docker Socket for the API

          [Socket]
          ListenStream=2375
          BindIPv6Only=both
          Service=docker.service
          [Install]
          WantedBy=sockets.target
      - name: flanneld.service
        command: start
        content: |
          [Unit]
          Description=Network fabric for containers
          Documentation=https://github.com/coreos/flannel
          Requires=early-docker.service etcd.service
          After=etcd.service early-docker.service
          Before=early-docker.target

          [Service]
          Type=notify
          Restart=always
          RestartSec=5
          Environment="TMPDIR=/var/tmp/"
          Environment="DOCKER_HOST=unix:///var/run/early-docker.sock"
          Environment="FLANNEL_VER=0.5.1"
          LimitNOFILE=40000
          LimitNPROC=1048576
          ExecStartPre=/sbin/modprobe ip_tables
          ExecStartPre=/usr/bin/mkdir -p /run/flannel
          ExecStartPre=/usr/bin/touch /run/flannel/options.env
          ExecStartPre=-/usr/bin/etcdctl mk /coreos.com/network/config '{"Network":"10.244.0.0/16", "SubnetLen": 24, "SubnetMin":"10.244.0.0", "Backend": {"Type": "vxlan"}}'
          ExecStart=/usr/libexec/sdnotify-proxy /run/flannel/sd.sock \
            /usr/bin/docker run --net=host --privileged=true --rm \
            --volume=/run/flannel:/run/flannel \
            --env=NOTIFY_SOCKET=/run/flannel/sd.sock \
            --env-file=/run/flannel/options.env \
            --volume=/usr/share/ca-certificates:/etc/ssl/certs:ro \
            quay.io/coreos/flannel:${FLANNEL_VER} /opt/bin/flanneld --iface=eth0 --ip-masq=true

          # Update docker options
          ExecStartPost=/usr/bin/docker run --net=host --rm -v /run:/run \
            quay.io/coreos/flannel:${FLANNEL_VER} \
            /opt/bin/mk-docker-opts.sh -d /run/flannel_docker_opts.env -i
      - name: stop-update-engine.service
        command: start
        content: |
          [Unit]
          Description=stop update-engine

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/systemctl stop update-engine.service
          ExecStartPost=/usr/bin/systemctl mask update-engine.service
      - name: graceful-deis-shutdown.service
        content: |
          [Unit]
          Description=Clean up
          DefaultDependencies=no
          After=fleet.service etcd.service docker.service docker.socket deis-store-admin.service deis-store-daemon.service deis-store-volume.service deis-store-monitor.service
          Requires=fleet.service etcd.service deis-store-admin.service deis-store-daemon.service deis-store-volume.service docker.service docker.socket deis-store-monitor.service

          [Install]
          WantedBy=shutdown.target halt.target reboot.target

          [Service]
          ExecStop=/opt/bin/graceful-shutdown.sh --really
          Type=oneshot
          TimeoutSec=1200
          RemainAfterExit=yes
      - name: install-deisctl.service
        command: start
        content: |
          [Unit]
          Description=Install deisctl utility
          ConditionPathExists=!/opt/bin/deisctl

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/sh -c 'curl -sSL --retry 5 --retry-delay 2 http://deis.io/deisctl/install.sh | sh -s 1.9.0'
      - name: debug-etcd.service
        content: |
          [Unit]
          Description=etcd debugging service

          [Service]
          ExecStartPre=/usr/bin/curl -sSL -o /opt/bin/jq http://stedolan.github.io/jq/download/linux64/jq
          ExecStartPre=/usr/bin/chmod +x /opt/bin/jq
          ExecStart=/usr/bin/bash -c "while true; do curl -sL http://127.0.0.1:4001/v2/stats/leader | /opt/bin/jq . ; sleep 1 ; done"
      - name: increase-nf_conntrack-connections.service
        command: start
        content: |
          [Unit]
          Description=Increase the number of connections in nf_conntrack. default is 65536

          [Service]
          Type=oneshot
          ExecStartPre=/usr/sbin/modprobe nf_conntrack
          ExecStart=/bin/sh -c "sysctl -w net.netfilter.nf_conntrack_max=262144"
      - name: fleet.service
        command: start
    write_files:
      - path: /etc/environment
        permissions: 0644
        content: |
          COREOS_PUBLIC_IPV4=10.250.0.11
          COREOS_PRIVATE_IPV4=10.250.0.11
      - path: /etc/deis-release
        content: |
          DEIS_RELEASE=v1.9.0
      - path: /etc/motd
        content: " \e[31m* *    \e[34m*   \e[32m*****    \e[39mddddd   eeeeeee iiiiiii   ssss\n\e[31m*   *  \e[34m* *  \e[32m*   *     \e[39md   d   e    e    i     s    s\n \e[31m* *  \e[34m***** \e[32m*****     \e[39md    d  e         i    s\n\e[32m*****  \e[31m* *    \e[34m*       \e[39md     d e         i     s\n\e[32m*   * \e[31m*   *  \e[34m* *      \e[39md     d eee       i      sss\n\e[32m*****  \e[31m* *  \e[34m*****     \e[39md     d e         i         s\n  \e[34m*   \e[32m*****  \e[31m* *      \e[39md    d  e         i          s\n \e[34m* *  \e[32m*   * \e[31m*   *     \e[39md   d   e    e    i    s    s\n\e[34m***** \e[32m*****  \e[31m* *     \e[39mddddd   eeeeeee iiiiiii  ssss\n\n\e[39mWelcome to Deis\t\t\tPowered by Core\e[38;5;45mO\e[38;5;206mS\e[39m\n"
      - path: /etc/profile.d/nse-function.sh
        permissions: '0755'
        content: |
          function nse() {
            docker exec -it $1 bash
          }
      - path: /etc/systemd/system/docker.service.d/50-insecure-registry.conf
        content: |
          [Unit]
          Requires=flanneld.service
          After=flanneld.service

          [Service]
          EnvironmentFile=/etc/environment_proxy
          Environment="DOCKER_OPTS=--insecure-registry 10.0.0.0/8 --insecure-registry 172.16.0.0/12 --insecure-registry 192.168.0.0/16 --insecure-registry 100.64.0.0/10"
      - path: /run/deis/bin/get_image
        permissions: '0755'
        content: |
          #!/bin/bash
          # usage: get_image <component_path>
          IMAGE=`etcdctl get $1/image 2>/dev/null`

          # if no image was set in etcd, we use the default plus the release string
          if [ $? -ne 0 ]; then
            RELEASE=`etcdctl get /deis/platform/version 2>/dev/null`

            # if no release was set in etcd, use the default provisioned with the server
            if [ $? -ne 0 ]; then
              source /etc/deis-release
              RELEASE=$DEIS_RELEASE
            fi

            IMAGE=$1:$RELEASE
          fi

          # remove leading slash
          echo ${IMAGE#/}
      - path: /run/deis/bin/preseed
        permissions: '0755'
        content: |
          #!/bin/bash

          COMPONENTS=(builder cache controller database logger logspout publisher registry router store-daemon store-gateway store-metadata store-monitor)
          for c in "${COMPONENTS[@]}"; do
            image=`/run/deis/bin/get_image /deis/$c`
            docker history $image >/dev/null 2>&1 || docker pull $image
          done
      - path: /opt/bin/deis-debug-logs
        permissions: '0755'
        content: |
          #!/bin/bash

          echo '--- VERSIONS ---'
          source /etc/os-release
          echo $PRETTY_NAME
          source /etc/deis-release
          echo "Deis $DEIS_RELEASE"
          etcd -version
          fleet -version
          printf "\n"

          echo '--- SYSTEM STATUS ---'
          journalctl -n 50 -u etcd --no-pager
          journalctl -n 50 -u fleet --no-pager
          printf "\n"

          echo '--- DEIS STATUS ---'
          deisctl list
          etcdctl ls --recursive /deis
          printf "\n"
      - path: /home/core/.toolboxrc
        owner: core
        content: |
          TOOLBOX_DOCKER_IMAGE=alpine
          TOOLBOX_DOCKER_TAG=3.1
          TOOLBOX_USER=root
      - path: /etc/environment_proxy
        owner: core
        content: |
          HTTP_PROXY=
          HTTPS_PROXY=
          ALL_PROXY=
          NO_PROXY=
          http_proxy=
          https_proxy=
          all_proxy=
          no_proxy=
      - path: /etc/systemd/coredump.conf
        content: |
          [Coredump]
          Storage=none
      - path: /opt/bin/graceful-shutdown.sh
        permissions: '0755'
        content: |
          #!/usr/bin/bash
          if [ "$1" != '--really' ]; then
            echo "command must be run as: $0 --really"
            exit 1
          fi
          # procedure requires the store-admin
          ADMIN_RUNNING=$(docker inspect --format="{{ .State.Running }}" deis-store-admin)
          if [ $? -eq 1 ] || [ "$ADMIN_RUNNING" == "false" ]; then
            echo "deis-store-admin container is required for graceful shutdown"
            exit 2
          fi
          set -e -x -o pipefail
          # determine osd id
          CURRENT_STATUS=$(/usr/bin/docker exec deis-store-admin ceph health | awk '{print $1}')
          OSD_HOSTS=($(/usr/bin/etcdctl ls /deis/store/hosts/| awk -F'/' '{print $5}'))
          for HOST in "${OSD_HOSTS[@]}"
          do
            PUBLIC_IP=$(fleetctl list-machines -fields="machine,ip" -full -no-legend| grep `cat /etc/machine-id` | awk '{print $2}')
            if [ "$HOST" = "$PUBLIC_IP" ] ; then
              OSD_ID=$(/usr/bin/etcdctl get /deis/store/osds/$PUBLIC_IP)
              break
            fi
          done
          # if we own an osd and its healthy, try to gracefully remove it
          if [ ! -z "$OSD_ID" ] && [[ "$CURRENT_STATUS" == *"HEALTH_OK"* ]] && [ ${#OSD_HOSTS[@]} -gt "3" ]; then
            /usr/bin/docker exec deis-store-admin ceph osd out $OSD_ID
            sleep 30
            TIMEWAITED=0
            until [[ $(/usr/bin/docker exec deis-store-admin ceph health) == *"HEALTH_OK"* ]]
            do
              if [ $TIMEWAITED -gt "1200" ]
              then
                echo "ceph graceful removal timeout exceeded"
                break
              fi
              echo "waiting" && sleep 5
              TIMEWAITED=$((TIMEWAITED+5))
            done
            /usr/bin/docker stop deis-store-daemon
            /usr/bin/docker exec deis-store-admin ceph osd crush remove osd.$OSD_ID
            /usr/bin/docker exec deis-store-admin ceph auth del osd.$OSD_ID
            /usr/bin/docker exec deis-store-admin ceph osd rm $OSD_ID
            /usr/bin/etcdctl rm /deis/store/osds/$PUBLIC_IP
            etcdctl rm /deis/store/hosts/$PUBLIC_IP && sleep 10
            # remove ceph mon
            /usr/bin/docker stop deis-store-monitor || true
            /usr/bin/docker exec deis-store-admin ceph mon remove `hostname -f` # fixme
            /usr/bin/docker stop deis-store-metadata || true
          fi

          # TODO: remove the next check once etcdctl is using etcd2
          ETCDCTL=/usr/bin/etcdctl
          if ! $ETCDCTL --version | grep -q "etcdctl version 2.0."; then
            ETCD_VERSION=2.0.13
            curl -sSL https://github.com/coreos/etcd/releases/download/v${ETCD_VERSION}/etcd-v${ETCD_VERSION}-linux-amd64.tar.gz | \
              tar zxv -C /opt/bin etcd-v${ETCD_VERSION}-linux-amd64/etcdctl --strip=1
            ETCDCTL="/opt/bin/etcdctl"
          fi
          # removing the node from etcd
          NODE=$($ETCDCTL member list | grep `cat /etc/machine-id` | cut -d ':' -f 1)
          $ETCDCTL member remove $NODE
      - path: /opt/bin/wupiao
        permissions: '0755'
        content: |
          #!/bin/bash
          # [w]ait [u]ntil [p]ort [i]s [a]ctually [o]pen
          [ -n "$1" ] && \
            until curl -o /dev/null -sIf http://${1}; do \
              sleep 1 && echo .;
            done;
          exit $?
      - path: /opt/bin/download-k8s-binary
        permissions: '0755'
        content: |
          #!/bin/bash
          export K8S_VERSION="v1.0.1"
          mkdir -p /opt/bin
          FILE=$1
          if [ ! -f /opt/bin/$FILE ]; then
            curl -sSL -o /opt/bin/$FILE https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/$FILE
            chmod +x /opt/bin/$FILE
          else
            # we check the version of the binary
            INSTALLED_VERSION=$(/opt/bin/$FILE --version)
            MATCH=$(echo "${INSTALLED_VERSION}" | grep -c "${K8S_VERSION}")
            if [ $MATCH -eq 0 ]; then
              # the version is different
              curl -sSL -o /opt/bin/$FILE https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/$FILE
              chmod +x /opt/bin/$FILE
            fi
          fi
      - path: /opt/bin/scheduler-policy.json
        content: |
          {
              "kind": "Policy",
              "apiVersion": "v1",
              "predicates": [{"name": "PodFitsPorts"},{"name": "PodFitsResources"},{"name": "NoDiskConflict"},{"name": "MatchNodeSelector"},{"name": "HostName"}],
              "priorities": [{"name": "LeastRequestedPriority","weight": 1},{"name": "BalancedResourceAllocation","weight": 1},{"name": "ServiceSpreadingPriority","weight": 2},{"name": "EqualPriority","weight": 1}]
          }
    manage_etc_hosts: localhost

It's exactly like https://github.com/deis/deis/blob/e2c06895ec5202a751cfb2b61f8b64039de98a2e/contrib/coreos/user-data.example with the mandatory adjustments made.

I have three nodes, cloud-1, cloud-2 and cloud-3, and they have the IPs 10.250.0.11, 10.250.0.12, 10.250.0.13, respectively.

I installed the nodes with this command:

    coreos-install -C stable -c user-data.1.txt -d /dev/sda -V 647.2.0

(user-data.1.txt is the user-data file configured for the 10.250.0.11 host.)

I am able to log into any of those node after they boot and they do find each other:

    core@cloud-1 ~ $ fleetctl list-machines
    MACHINE		IP		METADATA
    07efeeec...	10.250.0.13	-
    499e43f8...	10.250.0.11	-
    73b7dcd6...	10.250.0.12	-

Sure enough, from my control machine I executed:

    $ deisctl --version
    1.9.0
    $ deisctl install platform
    ● ▴ ■
    ■ ● ▴ Installing Deis...
    ▴ ■ ●
    Storage subsystem...
    [shortened]
    Logging subsystem...
    [shortened]
    Control plane...
    [shortened]
    Data plane...
    deis-publisher.service: loaded
    Routing mesh...
    deis-router@2.service: loaded
    deis-router@3.service: loaded
    deis-router@1.service: loaded
    Done.
    
    Please run `deisctl start platform` to boot up Deis.

So I did not run deisctl start platform, because I want to restore previous data. According to http://docs.deis.io/en/latest/managing_deis/backing_up_data/ I executed

    $ deisctl start store-monitor

I took forever so I finally CTRL-C'd it and logged into the server and checked: `journalctl -u deis-store-monitor`

    Aug 18 20:23:50 cloud-1 systemd[1]: Starting deis-store-monitor...
    Aug 18 20:27:50 cloud-1 systemd[1]: deis-store-monitor.service stop-sigterm timed out. Killing.
    Aug 18 20:27:50 cloud-1 systemd[1]: deis-store-monitor.service: control process exited, code=killed status=9
    Aug 18 20:27:50 cloud-1 systemd[1]: Stopped deis-store-monitor.service.
    Aug 18 20:27:50 cloud-1 systemd[1]: Unit deis-store-monitor.service entered failed state.
    Aug 18 20:27:50 cloud-1 systemd[1]: deis-store-monitor.service failed.

Strange. I wanted to check on the overall system. So I executed `systemctl list-units`
The usual system services are running, update-engine.service is `masked` as it should be, but:

    user-cloudinit@var-lib-coreos\x2dinstall-user_data.path                  loaded active     running         Watch for a cloud-config at /var/lib/coreos-install/user_data
    user-configdrive.path                                                    loaded active     waiting         Watch for a cloud-config at /media/configdrive
    docker-05ce8b75ce5e8c44eb0f187abc0797be16ea6e1925a70d214b93381ce48069f5.scope loaded active     running         docker container 05ce8b75ce5e8c44eb0f187abc0797be16ea6e1925a70d214b9
    docker-de30aeaf8759dbbff0795a65da9b3b4f50703c1a469597e9c192a90486c0429f.scope loaded active     running         docker container de30aeaf8759dbbff0795a65da9b3b4f50703c1a469597e9c19
    dbus.service                                                             loaded active     running         D-Bus System Message Bus
    deis-store-daemon.service                                                loaded activating start-pre start deis-store-daemon
    deis-store-monitor.service                                               loaded activating start-pre start deis-store-monitor
    docker.service                                                           loaded inactive   dead      start Docker Application Container Engine
    early-docker.service                                                     loaded active     running         Early Docker Application Container Engine
    etcd.service                                                             loaded active     running         etcd2 container
    flanneld.service                                                         loaded activating start     start Network fabric for containers
    fleet.service                                                            loaded active     running         fleet daemon

(store-daemon is on that list because I thought maybe a `deis install platform` would do the trick. It skipped starting store-monitor and tried to start store-daemon, which won't start either, just like store-monitor.)

See that `docker.service`? It's inactive. Dead. I guess it should be running. See what causes the troubles, shall we? `journalctl -u docker.service`

    -- Logs begin at Tue 2015-08-18 20:19:03 UTC, end at Tue 2015-08-18 20:57:11 UTC. --
    Aug 18 20:21:00 anti-cloud-1 systemd[1]: Dependency failed for Docker Application Container Engine.
    Aug 18 20:21:00 anti-cloud-1 systemd[1]: Job docker.service/start failed with result 'dependency'.
    Aug 18 20:22:36 anti-cloud-1 systemd[1]: Dependency failed for Docker Application Container Engine.
    Aug 18 20:22:36 anti-cloud-1 systemd[1]: Job docker.service/start failed with result 'dependency'.
    Aug 18 20:24:29 anti-cloud-1 systemd[1]: Dependency failed for Docker Application Container Engine.
    Aug 18 20:24:29 anti-cloud-1 systemd[1]: Job docker.service/start failed with result 'dependency'.

Those two lines repeat ever since. On all three servers. And that's where my discoveries end.

Any ideas on how to resolve this and get me a running cluster again?

**Comment by kmala** [comment]
Can you paste the output of  journalctl -fu flanneld.service

**Comment by cimnine** [comment]
Sure:

-- Logs begin at Tue 2015-08-18 20:19:03 UTC, end at Wed 2015-08-19 06:10:00 UTC. --
	Aug 18 20:19:30 anti-cloud-1 systemd[1]: Starting Network fabric for containers...
	Aug 18 20:19:30 anti-cloud-1 etcdctl[671]: Error:  Cannot sync with the cluster using peers 127.0.0.1:4001
	Aug 18 20:19:30 anti-cloud-1 sdnotify-proxy[678]: Unable to find image 'quay.io/coreos/flannel:0.5.1' locally
	Aug 18 20:19:31 anti-cloud-1 sdnotify-proxy[678]: Pulling repository quay.io/coreos/flannel
	Aug 18 20:19:32 anti-cloud-1 sdnotify-proxy[678]: b057e4234ba4: Pulling image (0.5.1) from quay.io/coreos/flannel
	Aug 18 20:19:32 anti-cloud-1 sdnotify-proxy[678]: b057e4234ba4: Pulling image (0.5.1) from quay.io/coreos/flannel, endpoint: https://quay.io/v1/
	Aug 18 20:19:33 anti-cloud-1 sdnotify-proxy[678]: b057e4234ba4: Pulling dependent layers
	Aug 18 20:19:33 anti-cloud-1 sdnotify-proxy[678]: 91a6195f52a2: Pulling metadata
	Aug 18 20:19:33 anti-cloud-1 sdnotify-proxy[678]: 91a6195f52a2: Pulling fs layer
	Aug 18 20:19:37 anti-cloud-1 sdnotify-proxy[678]: 91a6195f52a2: Download complete
	Aug 18 20:19:37 anti-cloud-1 sdnotify-proxy[678]: 2b8e51ef6b0f: Pulling metadata
	Aug 18 20:19:37 anti-cloud-1 sdnotify-proxy[678]: 2b8e51ef6b0f: Pulling fs layer
	Aug 18 20:19:38 anti-cloud-1 sdnotify-proxy[678]: 2b8e51ef6b0f: Download complete
	Aug 18 20:19:38 anti-cloud-1 sdnotify-proxy[678]: 1290177406fa: Pulling metadata
	Aug 18 20:19:40 anti-cloud-1 sdnotify-proxy[678]: 1290177406fa: Pulling fs layer
	Aug 18 20:19:43 anti-cloud-1 sdnotify-proxy[678]: 1290177406fa: Download complete
	Aug 18 20:19:43 anti-cloud-1 sdnotify-proxy[678]: f9581e483dd3: Pulling metadata
	Aug 18 20:19:43 anti-cloud-1 sdnotify-proxy[678]: f9581e483dd3: Pulling fs layer
	Aug 18 20:19:44 anti-cloud-1 sdnotify-proxy[678]: f9581e483dd3: Download complete
	Aug 18 20:19:44 anti-cloud-1 sdnotify-proxy[678]: b057e4234ba4: Pulling metadata
	Aug 18 20:19:45 anti-cloud-1 sdnotify-proxy[678]: b057e4234ba4: Pulling fs layer
	Aug 18 20:19:45 anti-cloud-1 sdnotify-proxy[678]: b057e4234ba4: Download complete
	Aug 18 20:19:45 anti-cloud-1 sdnotify-proxy[678]: b057e4234ba4: Download complete
	Aug 18 20:19:45 anti-cloud-1 sdnotify-proxy[678]: Status: Downloaded newer image for quay.io/coreos/flannel:0.5.1
	Aug 18 20:19:46 anti-cloud-1 sdnotify-proxy[678]: I0818 20:19:46.032984 00001 main.go:275] Installing signal handlers
	Aug 18 20:19:46 anti-cloud-1 sdnotify-proxy[678]: E0818 20:19:46.033166 00001 main.go:180] Error looking up interface eth0: no such network interface
	Aug 18 20:21:00 anti-cloud-1 systemd[1]: flanneld.service start operation timed out. Terminating.
	Aug 18 20:21:00 anti-cloud-1 sdnotify-proxy[678]: I0818 20:21:00.776470 00001 main.go:292] Exiting...
	Aug 18 20:21:00 anti-cloud-1 systemd[1]: Failed to start Network fabric for containers.
	Aug 18 20:21:00 anti-cloud-1 systemd[1]: Unit flanneld.service entered failed state.
	Aug 18 20:21:00 anti-cloud-1 systemd[1]: flanneld.service failed.
	Aug 18 20:21:06 anti-cloud-1 systemd[1]: flanneld.service holdoff time over, scheduling restart.
	Aug 18 20:21:06 anti-cloud-1 systemd[1]: Starting Network fabric for containers...
	Aug 18 20:21:06 anti-cloud-1 etcdctl[862]: {"Network":"10.244.0.0/16", "SubnetLen": 24, "SubnetMin":"10.244.0.0", "Backend": {"Type": "vxlan"}}
	Aug 18 20:21:06 anti-cloud-1 sdnotify-proxy[868]: I0818 20:21:06.282175 00001 main.go:275] Installing signal handlers
	Aug 18 20:21:06 anti-cloud-1 sdnotify-proxy[868]: E0818 20:21:06.282361 00001 main.go:180] Error looking up interface eth0: no such network interface
	Aug 18 20:22:36 anti-cloud-1 systemd[1]: flanneld.service start operation timed out. Terminating.
	Aug 18 20:22:36 anti-cloud-1 sdnotify-proxy[868]: I0818 20:22:36.276692 00001 main.go:292] Exiting...
	Aug 18 20:22:36 anti-cloud-1 systemd[1]: Failed to start Network fabric for containers.
	Aug 18 20:22:36 anti-cloud-1 systemd[1]: Unit flanneld.service entered failed state.
	Aug 18 20:22:36 anti-cloud-1 systemd[1]: flanneld.service failed.
	Aug 18 20:22:58 anti-cloud-1 systemd[1]: flanneld.service holdoff time over, scheduling restart.
	Aug 18 20:22:58 anti-cloud-1 systemd[1]: Starting Network fabric for containers...
	Aug 18 20:22:58 anti-cloud-1 etcdctl[1150]: Error:  105: Key already exists (/coreos.com/network/config) [282]
	Aug 18 20:22:58 anti-cloud-1 sdnotify-proxy[1157]: I0818 20:22:58.885857 00001 main.go:275] Installing signal handlers
	Aug 18 20:22:58 anti-cloud-1 sdnotify-proxy[1157]: E0818 20:22:58.886041 00001 main.go:180] Error looking up interface eth0: no such network interface

The last part repeats forever.

I guess "eth0: no such network interface" is actually the problem, because `ip addr` prints:

	core@anti-cloud-1 ~ $ ip addr
	1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
	    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
	    inet 127.0.0.1/8 scope host lo
	       valid_lft forever preferred_lft forever
	    inet6 ::1/128 scope host 
	       valid_lft forever preferred_lft forever
	2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
	    link/ether c0:3f:d5:67:af:4e brd ff:ff:ff:ff:ff:ff
	    inet 10.250.0.11/14 brd 10.251.255.255 scope global dynamic eno1
	       valid_lft 50861sec preferred_lft 50861sec

**Comment by bacongobbler** [comment]
could you please try deploying from master? We recently fixed this with https://github.com/deis/deis/commit/3769ee2e5e4e747daa7d526e74587b43ac013b07.

**Comment by cimnine** [comment]
This fixed the troubles. Thx!
