### ISSUE TITLE
Controller error : 'remaining connection slots are reserved for non-replication superuser connections'

### ISSUE THREAD

**Issue by MaxenceAdnot** [deis/deis#4297]
I tried to stress test my running env on AWS and the error "'remaining connection slots are reserved for non-replication superuser connections'" appeared while trying to scale down an app currently running 700 web processes. This error looks very similar to #1619 but the problem seems to be resolved this is why I opened a new ticket. 

My ceph-less cluster on AWS:
3 Control Plane / Router Mesh hosts - t2.medium with gp2 storage (ssd)
3 Data Plane hosts - m4.large with gp2 storage (ssd)
The storage is running on S3 and the database on a t2.micro RDS instance. 

I'm using the version 1.10.0-dev for the deisctl utility and the controller is running on the image deisci/controller:jenkins-test-ec2-2847 (latest stable according to jenkins at this time)

The placement options are working properly and my 700 web processes are distributed across my 3 "data plane" hosts. These hosts are under very heavy load I admit it but I don't understand this error on the controller component. Restarting the controller doesn't change anything. The app continue to run (quite slowly because of the load but running anyway) but I can't scale the app down (503 SERVICE UNAVAILABLE Detail: aborting, failed to destroy some containers). 

The database and the control plane hosts doesn't seem to be loaded in any way. 

New Relic Server of the hosts (except SRV-VIRTUDEVOPS):
<img width="1068" alt="capture d ecran 2015-08-19 a 06 33 07" src="https://cloud.githubusercontent.com/assets/1312130/9348785/34fb9eae-463c-11e5-82d5-3c78fe5c9acc.png">

I can also send you the complete papertrail logs if needed.

**Comment by szymonpk** [comment]
How small/big is connection limit on rds using t2.micro? Maybe default settings aren't enough.

You can check it from psql by executing `show max_connections;`

**Comment by bacongobbler** [comment]
by default deis-database allows a maximum of [250 connections](https://github.com/deis/deis/blob/master/database/templates/postgresql.conf#L64) which basically resolved most of these issues for now, so it's probably something on RDS's side as @szymonpk suggested. According to [this StackOverflow answer](http://serverfault.com/a/599428) the maximum for a t1.micro is 34, so I wouldn't be surprised that you'd hit such an error with a t2.micro.

**Comment by MaxenceAdnot** [comment]
@szymonpk @bacongobbler thank you for your answers 

db.t2.micro :
```
deis=> show max_connections;
 max_connections
-----------------
 26
```

I'm going to try with a db.m1.large RDS instance and will keep you informed soon.

**Comment by szymonpk** [comment]
It's 118 on m3.medium, but I think you can change it - https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithParamGroups.html. It's just matter of memory I think.

**Comment by MaxenceAdnot** [comment]
@szymonpk Thank you, I didn't know about Parameter Groups. I will try with a brand new cluster in few hours and close this issue if it's working properly.

**Comment by MaxenceAdnot** [comment]
I set the max_connections to 2000 and the problem seems to be resolved. Thank you for you help :+1:
