### ISSUE TITLE
is cloud formation template is on the edge of size?

### ISSUE THREAD

**Issue by szymonpk** [deis/deis#4298]
We're running slightly modified user-data. To be precise, for example with [blackhole](https://gist.githubusercontent.com/ianblenke/5507b76945a7fb41ba06/raw/8bcb7912c62410f0662a0539a280a8cec39cb87f/blackhole.cloud-init) service added.

Today I was unable to deploy next cluster (our first 1.9.0, with 1.8.0 it was fine :/) due to strange validation errors:

```-------------------------------------------------------------------------------------------------------------------------------
|                                                         CreateStack                                                         |
+---------+-------------------------------------------------------------------------------------------------------------------+
|  StackId|  arn:aws:cloudformation:us-east-1:358804306695:stack/deis190useast1/89f84110-4659-11e5-bc3c-500150b34cb4   |
+---------+-------------------------------------------------------------------------------------------------------------------+
Waiting for instances to be provisioned (CREATE_IN_PROGRESS, 600s) ...
Waiting for instances to be provisioned (CREATE_IN_PROGRESS, 590s) ...
Waiting for instances to be provisioned (CREATE_IN_PROGRESS, 580s) ...
Waiting for instances to be provisioned (CREATE_IN_PROGRESS, 570s) ...
Waiting for instances to be provisioned (CREATE_IN_PROGRESS, 560s) ...
Waiting for instances to be provisioned (CREATE_IN_PROGRESS, 550s) ...
error creating stack:
CoreOSServerLaunchConfig	1 validation error detected: Value '<some kind of base64 hash
Unable to locate credentials. You can configure credentials by running "aws configure".
```

After some trial and error attempts I've noticed adding any two files to `write_files` sections is resulting in error as above (any two new services probably too). For example:

```diff
+  - path: /srv/blackhole-create-fleet-units.sh
+    permissions: '0755'
+    owner: root
+    content: |
+      #!/bin/bash
+      source /etc/environment
+      set -ex
+
+      cp /srv/blackhole@.service /srv/blackhole@$(hostname).service
+      ( echo -n MachineID=; cat /etc/machine-id ) >> /srv/blackhole@$(hostname).service
+      /usr/bin/fleetctl start /srv/blackhole@$(hostname).service
+  - path: /srv/blackhole@.service
+    permissions: '0644'
+    owner: root
+    content: |
+      [Unit]
+      Description=Turn on automated addition of blackhole routes for sshd attackers
+
+      [Service]
+      ExecStart=/srv/blackhole.sh start
+      ExecStop=/srv/blackhole.sh stop
+      Restart=always
+
+      [Install]
+      WantedBy=multi-user.target
+
+      [X-Fleet]
```

Any idea how to handle this? Breaking content with `\n` and wrapping it around `""` doesn't help for long. Basicly adding any file definition with full set of options (owner, permissions) is resulting in errors. 

If I take template itself and try to validate template via `aws cloudformation validate-template --template-body file:///<path>` I'm not getting any errors.

**Comment by MaxenceAdnot** [comment]
According to the AWS documentation (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html) the limit size per request is 51,200 bytes. Mine is 48KB and it embed two user-data, I don't think the blackhole service you added to the user-data can cause the validation error you are facing. Nevertheless have you tried to upload your template to a S3 bucket which allow you to use a larger template body (460,800 bytes) ?

**Comment by szymonpk** [comment]
@MaxenceAdnot thanks for suggestions. Without blackhole added as show above, it works, I've deployed it without a problem. When I'm adding two new files, I've cryptic validations errors.

Output of gen-json.py is 28913 bytes so it isn't even close to overall template limit. Maybe I'm hitting different limit from page you pasted? I wonder why it's passing aws cli validation but it's failing on web panel.

**Comment by mboersma** [comment]
@szymonpk the user-data.example in Deis is already very close to 16K in size, which itself is a hard limit for AWS. We've seen similar incrutable errors with some PRs which added too much to user-data.

I'm not sure how that relates exactly to the 51,200-byte request limit, but I know it's easy to add things to our user-data and have AWS reject it. It needs to be trimmed down if possible.

**Comment by MaxenceAdnot** [comment]
`CoreOSServerLaunchConfig    1 validation error detected: Value '<some kind of base64 hash'`
The value causing the validation here is the user-data encoded in base64 for the Launch Config object. Have you tried to validate your user-data with a tool like https://coreos.com/validate/ ? Can you also try to decode the "base64-ed" user-data sent to Cloud Formation and verify everything is correct ?

**Comment by szymonpk** [comment]
When error is thrown I see only some part of base64 encoded string. My raw user-data is validating fine on coreos page. I don't know how I can retrieve Base64 encoded user-data, everywhere I look it's already decoded and it's always valid if I check it via external tools.

**Comment by szymonpk** [comment]
@mboersma 1.9.0 base64 encoded user data is already over 16kB, it's 21kB to be precise. Moreover there is section in AWS [doc](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) - `https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html`.

**Comment by szymonpk** [comment]
Nailed it :/ User-data limit isn't 16kB it's something between 21kB and 22kB, I've two files (base64 encoded):

```$ ls -al file*
-rw-r--r--+ 1 szymon  staff  21586 19 sie 19:16 file.js
-rw-r--r--+ 1 szymon  staff  22570 19 sie 19:20 file2.js
```
I can setup instance with file.js but I can't with file2.js. I think we can close it, but deis user-data will have to go on a diet.
