### ISSUE TITLE
Builder not coming up after 1.9 upgrade

### ISSUE THREAD

**Issue by aendrew** [deis/deis#4299]
I'm trying to start all the services up after upgrading to 1.9 from 1.7, and Builder refuses to come up. I've tried restarting it both via `deistctl` and `fleetctl`, and running `deisctl stop builder && deisctl uninstall builder && deisctl install builder && deisctl start builder`. Regardless, it stays stuck.

I've done a deis-debug-logs, deisctl journal builder and a deisctl status builder and posted the output at: https://gist.github.com/aendrew/490178ed01b022dd4039

N.b., I've been having an ongoing issue where it seems builder creates a new version of the app and then doesn't kill off the old one, such that `fleetctl list-units` shows two widely-outdated versions; see below. Also note, for reasons I totally do not understand, the log output from `deisctl journal builder` seems to be from three months ago (?!).

```
UNIT					MACHINE			ACTIVE		SUB
deis-builder.service			75fb29b7.../10.21.2.14	activating	start-post
deis-controller.service			0e71417b.../10.21.2.13	active		running
deis-database.service			5ada1bbf.../10.21.1.64	active		running
deis-logger.service			5ada1bbf.../10.21.1.64	active		running
deis-logspout.service			0e71417b.../10.21.2.13	active		running
deis-logspout.service			5ada1bbf.../10.21.1.64	active		running
deis-logspout.service			75fb29b7.../10.21.2.14	active		running
deis-publisher.service			0e71417b.../10.21.2.13	active		running
deis-publisher.service			5ada1bbf.../10.21.1.64	active		running
deis-publisher.service			75fb29b7.../10.21.2.14	active		running
deis-registry@1.service			75fb29b7.../10.21.2.14	active		running
deis-router@1.service			0e71417b.../10.21.2.13	active		running
deis-router@2.service			5ada1bbf.../10.21.1.64	active		running
deis-router@3.service			75fb29b7.../10.21.2.14	active		running
deis-store-admin.service		0e71417b.../10.21.2.13	active		running
deis-store-admin.service		5ada1bbf.../10.21.1.64	active		running
deis-store-admin.service		75fb29b7.../10.21.2.14	active		running
deis-store-daemon.service		0e71417b.../10.21.2.13	active		running
deis-store-daemon.service		5ada1bbf.../10.21.1.64	active		running
deis-store-daemon.service		75fb29b7.../10.21.2.14	active		running
deis-store-gateway@1.service		75fb29b7.../10.21.2.14	active		running
deis-store-metadata.service		0e71417b.../10.21.2.13	active		running
deis-store-metadata.service		5ada1bbf.../10.21.1.64	active		running
deis-store-metadata.service		75fb29b7.../10.21.2.14	active		running
deis-store-monitor.service		0e71417b.../10.21.2.13	active		running
deis-store-monitor.service		5ada1bbf.../10.21.1.64	active		running
deis-store-monitor.service		75fb29b7.../10.21.2.14	active		running
deis-store-volume.service		0e71417b.../10.21.2.13	active		running
deis-store-volume.service		5ada1bbf.../10.21.1.64	active		running
deis-store-volume.service		75fb29b7.../10.21.2.14	active		running
[...]
video_v5.web.1.service			0e71417b.../10.21.2.13	active		running
video_v8.web.1.service			0e71417b.../10.21.2.13	active		running
```

Notice video_v8 vs. video_v5.

Any help very much appreciated.

**Comment by aendrew** [comment]
Hmm. I tried stopping and uninstalling the platform, then reinstalling it. Suddenly everything's come up. Truly bizarre. Closing issue, though feel free to reopen it if you want more information to try and troubleshoot it.

**Comment by carmstrong** [comment]
Thanks for the report, @aendrew. Unfortunately, sometimes Docker Hub oddities can be at play here too. Glad everything is working now!
