### ISSUE TITLE
Mesos fails to start

### ISSUE THREAD

**Issue by MaxenceAdnot** [deis/deis#4305]
I wanted to try Mesos as the scheduler for the apps so I installed my stateless platform and the mesos components using `deisctl install mesos && deisctl start mesos` and  `deisctl config controller set schedulerModule=mesos_marathon` but when I looked at the logs I got the following output : 

```
deis-mesos-marathon[1]: [2015-08-20 03:28:52,730] INFO Opening socket connection to server ip-10-0-1-87.eu-west-1.compute.internal/10.0.1.87:3888 (org.apache.zookeeper.ClientCnxn:1061)
deis-mesos-marathon[1]: [2015-08-20 03:28:52,731] INFO Socket connection established to ip-10-0-1-87.eu-west-1.compute.internal/10.0.1.87:3888, initiating session (org.apache.zookeeper.ClientCnxn:950)
deis-zookeeper[1]: 2015-08-20 03:28:52,731 [myid:3] - INFO  [NIOWorkerThread-2:NIOServerCnxn@1006] - Closed socket connection for client /10.0.1.86:49153 (no session established for client)
deis-zookeeper[1]: 2015-08-20 03:28:52,731 [myid:3] - WARN  [NIOWorkerThread-2:NIOServerCnxn@372] - Exception causing close of session 0x0: ZooKeeperServer not running
deis-mesos-marathon[1]: [2015-08-20 03:28:52,733] INFO Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn:1186)
deis-mesos-slave[1]: I0820 03:28:52.752389    11 containerizer.cpp:110] Using isolation: posix/cpu,posix/mem
deis-mesos-slave[1]: 2015-08-20 03:28:52,753:11(0x7f185b57c700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
deis-zookeeper[1]: 2015-08-20 03:28:52,796 [myid:5] - INFO  [NIOWorkerThread-2:NIOServerCnxn@1006] - Closed socket connection for client /10.0.4.50:48239 (no session established for client)
deis-mesos-slave[1]: I0820 03:28:52.752926    11 slave.cpp:174] Slave started on 1)@10.0.4.50:5051
deis-mesos-slave[1]: I0820 03:28:52.752668    11 main.cpp:200] Starting Mesos slave
deis-mesos-slave[1]: 2015-08-20 03:28:52,753:11(0x7f185b57c700):ZOO_INFO@log_env@725: Client environment:os.version=#2 SMP Fri Aug 14 20:25:33 UTC 2015
deis-zookeeper[1]: 2015-08-20 03:28:52,796 [myid:5] - INFO  [NIOServerCxnFactory.AcceptThread:/10.0.2.86:3888:NIOServerCnxnFactory$AcceptThread@296] - Accepted socket connection from /10.0.4.50:48239
deis-mesos-slave[1]: 2015-08-20 03:28:52,722:16(0x7f02c1959700):ZOO_INFO@log_env@716: Client environment:host.name=ip-10-0-4-48.eu-west-1.compute.internal
deis-mesos-slave[1]: I0820 03:28:52.753198    11 slave.cpp:322] Slave resources: cpus(*):2; mem(*):6963; disk(*):90745; ports(*):[31000-32000]
deis-mesos-slave[1]: 2015-08-20 03:28:52,753:11(0x7f185b57c700):ZOO_INFO@log_env@716: Client environment:host.name=ip-10-0-4-50.eu-west-1.compute.internal
deis-mesos-slave[1]: 2015-08-20 03:28:52,753:11(0x7f185b57c700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
deis-zookeeper[1]: 2015-08-20 03:28:52,796 [myid:5] - WARN  [NIOWorkerThread-2:NIOServerCnxn@372] - Exception causing close of session 0x0: ZooKeeperServer not running
deis-mesos-slave[1]: 2015-08-20 03:28:52,754:11(0x7f185b57c700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=10.0.1.86:3888,10.0.1.87:3888,10.0.2.86:3888,10.0.4.48:3888,10.0.4.49:3888,10.0.4.50:3888 sessionTimeout=10000 watcher=0x7f185efdba60 sessionId=0 sessionPasswd=<null> context=0x7f1830000930 flags=0
deis-mesos-slave[1]: 2015-08-20 03:28:52,722:16(0x7f02c1959700):ZOO_INFO@log_env@733: Client environment:user.name=(null)
deis-mesos-slave[1]: I0820 03:28:52.755291    11 main.cpp:200] Starting Mesos slave
deis-mesos-slave[1]: 2015-08-20 03:28:52,754:11(0x7f185b57c700):ZOO_INFO@log_env@741: Client environment:user.home=/root
deis-mesos-slave[1]: 2015-08-20 03:28:52,722:16(0x7f02c1959700):ZOO_INFO@log_env@724: Client environment:os.arch=4.1.5-coreos
deis-mesos-slave[1]: 2015-08-20 03:28:52,753:11(0x7f185b57c700):ZOO_INFO@log_env@724: Client environment:os.arch=4.1.5-coreos
deis-mesos-slave[1]: 2015-08-20 03:28:52,754:11(0x7f185b57c700):ZOO_INFO@log_env@733: Client environment:user.name=(null)
deis-mesos-slave[1]: 2015-08-20 03:28:52,722:16(0x7f02c1959700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
deis-mesos-slave[1]: 2015-08-20 03:28:52,756:11(0x7f683e9d4700):ZOO_INFO@log_env@716: Client environment:host.name=ip-10-0-4-49.eu-west-1.compute.internal
deis-mesos-slave[1]: 2015-08-20 03:28:52,722:16(0x7f02c1959700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
deis-mesos-slave[1]: 2015-08-20 03:28:52,754:11(0x7f185b57c700):ZOO_INFO@log_env@753: Client environment:user.dir=/
deis-mesos-slave[1]: I0820 03:28:52.722054    16 main.cpp:200] Starting Mesos slave
deis-mesos-slave[1]: I0820 03:28:52.754984    11 containerizer.cpp:110] Using isolation: posix/cpu,posix/mem
deis-mesos-slave[1]: I0820 03:28:52.756424    11 slave.cpp:352] Slave checkpoint: true
deis-mesos-slave[1]: I0820 03:28:52.755782    11 slave.cpp:322] Slave resources: cpus(*):2; mem(*):6963; disk(*):90745; ports(*):[31000-32000]
deis-mesos-slave[1]: I0820 03:28:52.755508    11 slave.cpp:174] Slave started on 1)@10.0.4.49:5051
deis-zookeeper[1]: 2015-08-20 03:28:52,763 [myid:3] - INFO  [NIOServerCxnFactory.AcceptThread:/10.0.1.87:3888:NIOServerCnxnFactory$AcceptThread@296] - Accepted socket connection from /10.0.4.48:44366
deis-mesos-slave[1]: 2015-08-20 03:28:52,722:16(0x7f02c1959700):ZOO_INFO@log_env@741: Client environment:user.home=/root
deis-mesos-slave[1]: 2015-08-20 03:28:52,754:11(0x7f1856917700):ZOO_ERROR@handle_socket_error_msg@1697: Socket [10.0.4.50:3888] zk retcode=-4, errno=111(Connection refused): server refused to accept the client
deis-mesos-slave[1]: 2015-08-20 03:28:52,756:11(0x7f683e9d4700):ZOO_INFO@log_env@724: Client environment:os.arch=4.1.5-coreos
deis-mesos-slave[1]: 2015-08-20 03:28:52,756:11(0x7f683e9d4700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
deis-mesos-slave[1]: I0820 03:28:52.726512    16 slave.cpp:352] Slave checkpoint: true
deis-mesos-slave[1]: 2015-08-20 03:28:52,756:11(0x7f683e9d4700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
deis-mesos-slave[1]: 2015-08-20 03:28:52,722:16(0x7f02c1959700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=10.0.1.86:3888,10.0.1.87:3888,10.0.2.86:3888,10.0.4.48:3888,10.0.4.49:3888,10.0.4.50:3888 sessionTimeout=10000 watcher=0x7f02c4bb7a60 sessionId=0 sessionPasswd=<null> context=0x7f02b0001260 flags=0
deis-mesos-slave[1]: I0820 03:28:52.758374    11 slave.cpp:351] Slave hostname: ip-10-0-4-49.eu-west-1.compute.internal
deis-mesos-slave[1]: I0820 03:28:52.723480    16 slave.cpp:174] Slave started on 1)@10.0.4.48:5051
deis-mesos-slave[1]: I0820 03:28:52.755872    11 slave.cpp:351] Slave hostname: ip-10-0-4-50.eu-west-1.compute.internal
deis-mesos-slave[1]: 2015-08-20 03:28:52,756:11(0x7f683e9d4700):ZOO_INFO@log_env@753: Client environment:user.dir=/
deis-mesos-slave[1]: 2015-08-20 03:28:52,756:11(0x7f683e9d4700):ZOO_INFO@log_env@725: Client environment:os.version=#2 SMP Fri Aug 14 20:25:33 UTC 2015
deis-mesos-slave[1]: 2015-08-20 03:28:52,756:11(0x7f683e9d4700):ZOO_INFO@log_env@741: Client environment:user.home=/root
deis-mesos-slave[1]: I0820 03:28:52.767526    12 state.cpp:35] Recovering state from '/tmp/mesos/meta'
deis-mesos-slave[1]: I0820 03:28:52.726207    16 slave.cpp:351] Slave hostname: ip-10-0-4-48.eu-west-1.compute.internal
deis-zookeeper[1]: 2015-08-20 03:28:52,784 [myid:4] - INFO  [NIOServerCxnFactory.AcceptThread:/10.0.1.86:3888:NIOServerCnxnFactory$AcceptThread@296] - Accepted socket connection from /10.0.4.49:45318
deis-mesos-slave[1]: 2015-08-20 03:28:52,775:11(0x7f1856917700):ZOO_ERROR@handle_socket_error_msg@1721: Socket [10.0.2.86:3888] zk retcode=-4, errno=112(Host is down): failed while receiving a server response
deis-zookeeper[1]: 2015-08-20 03:28:52,791 [myid:4] - WARN  [NIOWorkerThread-4:NIOServerCnxn@372] - Exception causing close of session 0x0: ZooKeeperServer not running
deis-zookeeper[1]: 2015-08-20 03:28:52,792 [myid:3] - INFO  [NIOWorkerThread-4:NIOServerCnxn@1006] - Closed socket connection for client /10.0.4.49:57440 (no session established for client)
deis-mesos-slave[1]: 2015-08-20 03:28:52,787:11(0x7f683cd75700):ZOO_ERROR@handle_socket_error_msg@1721: Socket [10.0.2.86:3888] zk retcode=-4, errno=112(Host is down): failed while receiving a server response
Aug 20 05:28:52 52.19.59.199 logger:  2015-08-20T03:28:52UTC deis-mesos-slave[1]: 2015-08-20 03:28:52,786:11(0x7f683cd75700):ZOO_INFO@check_events@1703: initiated connection to server [10.0.2.86:3888]
deis-zookeeper[1]: 2015-08-20 03:28:52,832 [myid:5] - INFO  [NIOServerCxnFactory.AcceptThread:/10.0.2.86:3888:NIOServerCnxnFactory$AcceptThread@296] - Accepted socket connection from /10.0.4.48:49134
deis-zookeeper[1]: 2015-08-20 03:28:52,833 [myid:5] - WARN  [NIOWorkerThread-3:NIOServerCnxn@372] - Exception causing close of session 0x0: ZooKeeperServer not running
deis-zookeeper[1]: 2015-08-20 03:28:52,836 [myid:5] - INFO  [NIOWorkerThread-4:NIOServerCnxn@1006] - Closed socket connection for client /10.0.4.49:44566 (no session established for client)
deis-zookeeper[1]: 2015-08-20 03:28:52,836 [myid:5] - WARN  [NIOWorkerThread-4:NIOServerCnxn@372] - Exception causing close of session 0x0: ZooKeeperServer not running
deis-zookeeper[1]: 2015-08-20 03:28:52,833 [myid:5] - INFO  [NIOWorkerThread-3:NIOServerCnxn@1006] - Closed socket connection for client /10.0.4.48:49134 (no session established for client)
deis-zookeeper[1]: 2015-08-20 03:28:53,755 [myid:5] - WARN  [NIOWorkerThread-1:NIOServerCnxn@372] - Exception causing close of session 0x0: ZooKeeperServer not running
```

The components are shown as active / running. I tried to restart the mesos components using deisctl but it didn't help.

Any idea on the reason of these errors ? 

---
My stateless cluster on AWS:
3 Control Plane / Router Mesh hosts - t2.medium with gp2 storage (ssd)
3 Data Plane hosts - m4.large with gp2 storage (ssd)
The storage is running on S3 and the database on a db.t2.medium RDS instance with 2000 max_connections.

**Comment by carmstrong** [comment]
@MaxenceAdnot Sorry you're running into trouble - it looks like the Zookeeper units aren't running. Could you paste the output of `deisctl list units` on on ehost and `journalctl -u deis-zookeeper` on all hosts?

**Comment by MaxenceAdnot** [comment]
Sorry for the late reply.
I reproduced the problem with the v1.10.

Here is the output of `deisctl list units`:
UNIT				MACHINE			LOAD	ACTIVE	SUB
deis-builder.service		1a414592.../10.0.2.211	loaded	active	running
deis-cache.service		1a414592.../10.0.2.211	loaded	active	running
deis-controller.service		49898be9.../10.0.2.210	loaded	active	running
deis-logspout.service		1a414592.../10.0.2.211	loaded	active	running
deis-logspout.service		3ac56e7f.../10.0.3.226	loaded	active	running
deis-logspout.service		49898be9.../10.0.2.210	loaded	active	running
deis-logspout.service		5a0ce883.../10.0.3.224	loaded	active	running
deis-logspout.service		63178ea7.../10.0.1.107	loaded	active	running
deis-logspout.service		ee065673.../10.0.3.225	loaded	active	running
deis-mesos-marathon.service	49898be9.../10.0.2.210	loaded	active	running
deis-mesos-master.service	49898be9.../10.0.2.210	loaded	active	running
deis-mesos-slave.service	3ac56e7f.../10.0.3.226	loaded	active	running
deis-mesos-slave.service	5a0ce883.../10.0.3.224	loaded	active	running
deis-mesos-slave.service	ee065673.../10.0.3.225	loaded	active	running
deis-publisher.service		3ac56e7f.../10.0.3.226	loaded	active	running
deis-publisher.service		5a0ce883.../10.0.3.224	loaded	active	running
deis-publisher.service		ee065673.../10.0.3.225	loaded	active	running
deis-registry@1.service		63178ea7.../10.0.1.107	loaded	active	running
deis-router@1.service		1a414592.../10.0.2.211	loaded	active	running
deis-router@2.service		49898be9.../10.0.2.210	loaded	active	running
deis-router@3.service		63178ea7.../10.0.1.107	loaded	active	running
deis-zookeeper.service		1a414592.../10.0.2.211	loaded	active	running
deis-zookeeper.service		49898be9.../10.0.2.210	loaded	active	running
deis-zookeeper.service		63178ea7.../10.0.1.107	loaded	active	running

The content of each journalctl -u deis-zookeeper on 10.0.2.211, 10.0.2.210, 10.0.1.107:
10.0.2.211 : http://pastebin.com/gSFwsG2r
10.0.2.210 : http://pastebin.com/7YSfGBsh
10.0.1.107 : http://pastebin.com/AkyeDb19

Just before it crashes, we have the message `WARN  [WorkerSender[myid=5]:QuorumCnxManager@384] - Cannot open channel to 2 at election address /10.0.3.226:2888`. I checked with a netstat on the host 10.0.3.226 but there is no port 2888 opened.

Any idea ?

**Comment by MaxenceAdnot** [comment]
I found something interesting in the first lines of the logs of zookeeper : 

ep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - returning default value "/zookeeper/nodes" for key "ETCD_PATH"
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - returning default value "4001" for key "ETCD_PORT"
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - returning default value "127.0.0.1:4001" for key "ETCD_PEERS"
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - connecting to [http://10.0.2.211:4001] etcd server/s
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - 105: Key already exists (/zookeeper/nodes) [9071]
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [INFO] - boot version [1.10.0]
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [INFO] - zookeeper: starting...
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - getlist /zookeeper/nodes -> []
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - zookeeper nodes []
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - machines []
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [WARNING] -
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [WARNING] - there is no machine using metadata zookeeper=true in the cluster to run zookeeper
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [WARNING] - we will create the mapping with for all the nodes
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [WARNING] -
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - initializing zookeeper cluster
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - adding node %v to zookeeper cluster10.0.2.211
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - set /zookeeper/nodes/10.0.2.211/id -> 1
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - adding node %v to zookeeper cluster10.0.3.226
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - set /zookeeper/nodes/10.0.3.226/id -> 2
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - adding node %v to zookeeper cluster10.0.2.210
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - set /zookeeper/nodes/10.0.2.210/id -> 3
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - adding node %v to zookeeper cluster10.0.3.224
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - set /zookeeper/nodes/10.0.3.224/id -> 4
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - adding node %v to zookeeper cluster10.0.1.107
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - set /zookeeper/nodes/10.0.1.107/id -> 5
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - adding node %v to zookeeper cluster10.0.3.225
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [DEBUG] - set /zookeeper/nodes/10.0.3.225/id -> 6
Sep 05 01:36:44 ip-10-0-2-211.eu-west-1.compute.internal sh[5171]: [INFO] - waiting for confd to write initial templates...

I seems that using the mesos scheduler on a "isolated planes" cluster causes zookeeper to crash as it tries to define its quorum based on all hosts (with data planes hosts which are not running zookeeper at all).

**Comment by MaxenceAdnot** [comment]
That was what i thought ! I added `zookeeper=true` to the metadata in the user-config for the control plane and it worked. This should be described in the documentation page for using mesos :)

**Comment by carmstrong** [comment]
Great debugging, @MaxenceAdnot!

> This should be described in the documentation page for using mesos :)

Would you mind making that change? The documentation is under the `docs` subdirectory. We'd love the contribution!

**Comment by MaxenceAdnot** [comment]
I'll send the PR as soon as possible.
