### ISSUE TITLE
Should document limitations WRT SNI

### ISSUE THREAD

**Issue by krancour** [deis/deis#4312]
Since the router relies on SNI, we should probably document the incompatibility between SNI and older versions of IE, just so users are aware.

**Comment by deis-admin** [comment]
Deis v1 LTS support ends February 13, 2017, and [v1.13.4](https://github.com/deis/deis/releases/tag/v1.13.4) is intended to be the last official release, so I'm closing this.

Please see [Deis Workflow](https://github.com/deis/workflow), the documentation / hub repository for the next-generation PaaS.
