### ISSUE TITLE
Discussion: improving the provisioning process

### ISSUE THREAD

**Issue by krancour** [deis/deis#4318]
The purpose of this issue is to highlight some pain points or general problems with the existing provisioning processes in order to fuel discussion directed at improving those processes.

Disclaimer: I am most familiar with the AWS provisioning process, so my comments are most informed by that.  If others want to call out other pain points or general problems with the process for other providers, go right ahead!

discovery URLs
---------------------

Generating user-data: many operators are well-acquainted with using `make discovery-url` to generate user-data.  What that make task does not do-- probably by design-- is it doesn't delete  / overwrite existing user-data.  The adverse affect of this is someone who has already failed in a prior attempt to provision a Deis cluster or is provisioning a second one might inadvertently re-use an etcd discovery URL without realizing they are doing so (even though they have re-run `make discovery-url`).

User-data and templates
---------------------------------

Apart from provisioning scripts, we also provide "update" scripts that allow a CloudFormation template (for AWS, e.g.) to be re-run.  If an operator were to use this and in the time since provisioning a cluster, his or her user-data has changed (e.g. perhaps they altered it to stand up a second cluster) _or_ any environment variables that have an impact on the composition of the generated template or the parameters passed to it have changed, then the result is all of these undesired changes might accidentally be applied to an existing cluster.  This isn't ideal and could in fact cause some pretty big problems.

We should probably save user-data, templates, and parameters used in the provisioning process so that they can be tweaked by an advanced operator and / or re-used by an update process _as is_ (without the need to regenerate those artifacts).  This would allow an operator to keep the artifacts that accurately describe his or her clusters in source control.

Environment variables
------------------------------

The provisioning process is highly dependent on environment variables set by the operator to specify a variety of options or other required inputs.  As noted in the previous section, if these environment variables change between the time of initial provisioning and an update, some bad things can happen, but beyond that, relying on these environment variables makes for a clunky and error-prone user experience.  It is all too easy, for instance, to get all the way through the provisioning process never having set the `DEIS_NUM_INSTANCES` environment variable.  As a result, one ends up with an etcd cluster size of three by default.  What is five were desired, as is often the case in production?  At such a juncture, the only choice is to start over.

Virtual network topology
--------------------------------

Currently, by default (at least in AWS) we provision a VPC for each new Deis cluster.  We do offer the option of deploying a Deis cluster into an existing VPC instead.  The problems here are threefold:

* The VPCs we create only utilize two availability zones.  Quorum is more easily guaranteed in the face of inevitable network problems if the nodes of an etcd cluster are distributed across _at least_ three zones.

* As mentioned, we offer the possibility of provisioning a Deis cluster into an existing VPC, and when one does so, we also offer operators the possibility of deploying their cluster into private subnets.  IMO, this is actually a requirement for a production-worthy cluster.  The VPCs we create do not include private subnets.  IMO, this should at least be an option.

* In the default case where an operator elects to let our provisioning process create the VPC for their cluster, we generate a _single_ CloudFormation template that defines _both_ the VPC and the Deis cluster.  This isn't ideal for a number of reasons.  For one, it means we are more rapidly approaching the limit on CF template size.  Second, it means the existence of the VPC is atomically bound to the existence of the Deis cluster.  One cannot choose to delete the Deis cluster without also deleting the VPC-- which could be problematic if additional Deis clusters have been deployed into that VPC afterwards.  Third, in many organizations, network security gurus who most likely do not have and do not require extensive knowledge of Deis are going to want to tweak certain aspects of a VPC, such as route tables and network ACLs.  For all of these reasons, it is probably best that any option we provider for establishing a VPC is _decoupled_ from the creation of Deis clusters.

Isolating etcd and the control plane
----------------------------------------------

I think this issue is well understood, so I will skip over the details, but we _do_ recommend that in production, operators isolate both etcd and the Deis control plane to a small, fixed number of nodes, while allowing their data plane to scale more extensively.  In AWS terms, this requires _two_ sets of user-data (which vary just slightly from one another) to be used in the launch configuration for _two_ separate auto-scaling groups.  Although we highly recommend this, we haven't done more than document the recommendation with some modest advice on how one can achieve this themselves.  Our provisioning processes simply don't account for these recommendations, although they probably should.

Lowering the barriers for provisioning
-------------------------------------------------

Provisioning, again with respect to AWS, currently requires the AWS CLI to have been installed, as well as Python.  It seems there may be a growing consensus that Docker, instead, should be the lowest common denominator in terms of tooling that you assume (or hope) every operator has installed.  Containerizing the provisioning process would probably make life easier for most operators.

**Comment by krancour** [comment]
Add to the above:

Running Cephless
------------------------

We have extensively documented what is required to run the "stateless platform" (i.e. without Ceph).  It requires the use of an external (external to the cluster) database and storage gateway.  On a platform like AWS, we could easily provide an optional provisioning process for these components to further reduce the knowledge one requires in order to run the stateless platform.

**Comment by sgoings** [comment]
@krancour my approach with https://github.com/sgoings/rerun-deis is intended to help with the **Environment variables** problem as well as the "no common provisioning interface" problem. Check it out and let me know if that direction will eventually help you. :-)

**Comment by bacongobbler** [comment]
Simple: we implement Deis on top of Kubernetes!

v2 dramatically simplifies the bootstrapping process so I'm going to go ahead and close this as out of date, but if we find issues with the v2 provisioning process then we should revisit this.
