### ISSUE TITLE
AWS Elastic File System

### ISSUE THREAD

**Issue by apps4u** [deis/deis#4319]
HI Ive got a suggestion regarding AWS Elastic File System , We run a deis cluster of 4 node , 3 are for our services and the 4th is used for dev + testing, Now Ive got a preview access to EFS which is a new service from AWS .

Now I wanted to asked wether this is something to look at adding to Deis , One of our biggest cost is storage and the way EFS works you only pay for what you use so if will grow and shrink as needed , the file system uses NFS protocol and can be mounted on more then one instance at a time .

We have setup our cluster to use 100GB per node if I remember correctly now that leaves us room to add containers as needed but it also wastes at lot of unused space. We also keep all node with the same size storage so scaling etc works well. 

I know Deis does not want to have vendor lock-in so this would only be a option , So my questions are: 
 
1- Would this be something the community would consider?

2- If I was to go ahead with changing the storage for Deis what amount of work would I be looking at doing. ( I would hire another dev to work with our staff as this would be worth it for us as our storage needs will only grow).

This would remove storage as something to be managed to having AWS manage it , Its replicated to at lest 3 regions and will auto scale capacity and storage capacity as needed. 

If you read the spec of AWS Elastic File System I'm sure you will see the benefits and AWS user of Deis would get.

**Comment by Blystad** [comment]
Any reason why you can't throw everything on Amazon S3?

http://docs.deis.io/en/latest/managing_deis/running-deis-without-ceph/

With this I use almost no storage:

```
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        3.7G     0  3.7G   0% /dev
tmpfs           3.7G     0  3.7G   0% /dev/shm
tmpfs           3.7G  996K  3.7G   1% /run
tmpfs           3.7G     0  3.7G   0% /sys/fs/cgroup
/dev/xvda9       47G  862M   44G   2% /
/dev/xvda3      985M  349M  585M  38% /usr
tmpfs           3.7G     0  3.7G   0% /media
tmpfs           3.7G     0  3.7G   0% /tmp
/dev/xvda6      108M   60K   99M   1% /usr/share/oem
/dev/xvdf        94G  8.2G   81G  10% /var/lib/docker
/dev/xvdg       9.3G   26M  8.8G   1% /media/etcd
```

and the docker one I could probably free up more, by running some docker cleanup agent.

**Comment by apps4u** [comment]
Thanks I had no Idea there was a way to use S3 , Ive just looked at the page on the Deis Site as we are going to implement that.

I would still want to look at performance of S3 v's EFS.
