### ISSUE TITLE
/deis/platform/version missing in new installation

### ISSUE THREAD

**Issue by ineu** [deis/deis#4320]
Recently I've recreated my cluster from scratch with Deis 1.9. Today I've noticed that there's no `/deis/platform/version` key present. On http://docs.deis.io/en/latest/installing_deis/install-platform/ page there are no instructions to set version, though on http://docs.deis.io/en/latest/managing_deis/upgrading-deis/ there are.

Is this key not required? That's weird that you have to set it for upgrade, but not for installation.

**Comment by carmstrong** [comment]
> Is this key not required? That's weird that you have to set it for upgrade, but not for installation.

It's not required. The version is first read from `/deis/platform/version`, which overrides the default value in `/etc/deis-release`. The etcd key enables you to override the default version, such as when you're upgrading.

**Comment by ineu** [comment]
Ah, great. Thank you.
