### ISSUE TITLE
"Global" environment variables for all applications

### ISSUE THREAD

**Issue by klaussilveira** [deis/deis#4322]
Dokku has this [built in](https://github.com/cameron-martin/dokku-build-env) for a while and it's an interesting feature: you can define some environment variables that will be exposed to all containers. This is extremely useful for setting things like SSH_KEY, or New Relic configuration.

**Comment by Joshua-Anderson** [comment]
Dupe of #1804

**Comment by bacongobbler** [comment]
yep. Thanks for catching that :) closing as a dupe.
