### ISSUE TITLE
Attach volume to app

### ISSUE THREAD

**Issue by Xowap** [deis/deis#4325]
**Problem**
I am trying to host a Prestashop. I'll try to refrain myself from judging and will stick to objective facts, but Prestashop is a pile of crap. Basically, it does not allow for any kind of abstraction and does really stupid things with image files (idiotic rewriting rules, non-configurable storage directory, ...).

In order to adapt this to the 12-factor concepts, I need to store those images in an external service, like S3. This way, images are automatically available from everywhere. Especially with something like yas3fs which handles caching files and mounting the same bucket from several locations.

**Solution**
What would be interesting would be to be able to attach another app (or something similar) as Docker Volume Plugins that will be started alongside the main app, with the same config (so you can get credentials from environment).

Something like

```
cd plugin-app
deis create --storage-plugin plugin-app
git push origin master

cd ../main-app
deis create main-app volume_name:/app/img plugin-app
deis config:set TOKEN=xxxxxx
git push origin master
```

**Comment by alexanderkiel** [comment]
@Xowap I see what you like to do: adapting a non 12-factor app which needs a local file storage to PaaS platforms which like to only support 12-factor apps.

I'm not one of the Deis devs but I would like to keep things simple for Deis because I use it. For the API, I'm not sure if it's a good thing to mix Docker concepts like volumes into the original 12-factor (Heroku) inspired one.

You could investigate whether you can use Docker builds for your special case. In the Docker image, you could install some user space filesystem driver which connects to S3. I'm pretty sure something like this exists.

**Comment by bacongobbler** [comment]
While this issue is still unsolved, would this workaround work for you? http://hiousi.tumblr.com/post/94824087894/prestashop-images-hosted-on-amazon-s3

Essentially you'll be using `deis config:set AWS_ACCESS_KEY_ID=foo AWS_SECRET_KEY=bar` and configuring Pretashop to use S3 as the backing file store. I believe this is how wordpress et al are adapting to 12 factor environments with the help of plugins like [this one](https://wordpress.org/plugins/tantan-s3-cloudfront/).

**Comment by Xowap** [comment]
@bacongobbler this trick does not work anymore apparently, or at least I've been unable to make it work.

Wordpress has a kind-of good plugin architecture and allows to do flexible things, whereas Prestashop only allows superficial things/dirty hacks.

I find @alexanderkiel's point interesting and totally understandable. I'm not really fit to decide if this kind of feature would be needed in general or not, and have no feelings about this, it's merely a suggestion and a statement that I need this feature.

**Comment by Xowap** [comment]
Besides, @alexanderkiel, I can't install a user-space file system from inside the container, because it requires to run with extra privileges that I don't especially want to give to a container running a legacy PHP app, and that I can't really give to the app with deis as-is today.

**Comment by alexanderkiel** [comment]
@Xowap We use two clusters for our apps at work: one Deis cluster for all 12-factor apps and one vanilla CoreOS cluster for all the other stuff. Using CoreOS with fleet is quite a good story. You write your unit files and submit them to the cluster.

The `git push deis master` deployment model might be important if you develop the app yourself, but as I understand it, you just use Prestashop. So is it really important to have Deis to run it?

**Comment by Xowap** [comment]
@alexanderkiel indeed as you suggest CoreOS is a quite viable thing, or maybe even add Kubernetes on the top to get nice rolling updates.

But anyway, I have been hosting PHP apps for a decade, deploying them is not an issue per say. It's more that Deis is basically the ultimate tool for delegating your work to someone else which does not need to understand what happens, and just needs to push to a Git repo.

(And yes unfortunately, my Prestashop is being hosted on a private Git repo, due to its ability to self-modify its own source code for no reason at all, meaning that the `git push` workflow is actually pretty useful here)

**Comment by carmstrong** [comment]
@Xowap Unfortunately, there are a class of applications that don't run well in the distributed world of 12-factor applications that Deis lives in, and it sounds like this is one. I understand your hesitancy to hack Prestashop, but it sounds like using one of the myriad S3 client libraries would work quite well for this use case. Consuming a backing store like S3 is a common model in the 12-factor world.

I think your proposal of a `deis volumes` command is interesting, but it probably wouldn't be used to mount data from other applications.

I'm going to close this issue for now as the motivation behind volumes is something that should probably be solved by other means.

**Comment by Xowap** [comment]
There is no hesitancy to hack Prestashop, it's more like I can't rewrite half of its code nor run plugins that expect to have a stateful file system. The hack is not to use Prestashop. But it's not always a choice you can make.

Anyways, I completely understand why Deis wouldn't be interested into adding this kind of stuff to its code base, it is simply out of scope. Thanks everybody for your time :smile:
