### ISSUE TITLE
Insecure etcd by default

### ISSUE THREAD

**Issue by Xowap** [deis/deis#4326]
**Problem**
If you run Deis in a public cloud (say Digital Ocean), even though you can use the custom firewall script (https://github.com/deis/deis/blob/master/contrib/util/custom-firewall.sh), you still are on the same physical network than all other customers.

Which means that if in any way (firewall not up, security issue at the hosting company, ...) a hacker can reach etcd, he can access the whole configuration and even change it, which is basically disastrous.

**Solution (maybe)**
According to the [security model](https://coreos.com/etcd/docs/2.0.8/security.html) document from etcd, you can set up SSL encryption and authentication.

What would be really interesting then would be to set up etcd on HTTPS by default. I believe that with the emergence of services like https://letsencrypt.org/ this can be done in a way that would not affect (too much?) user experience, and even be extended to the app routers, internal traffic between containers, etc.

**Comment by bacongobbler** [comment]
related: https://github.com/deis/deis/issues/3201 https://github.com/deis/deis/issues/3572

**Comment by bacongobbler** [comment]
etcd will be going away in v2 and we won't be able to get to this for the LTS release so I'm going to close this, but thank you very much for posting this :)
