### ISSUE TITLE
Azure nodes should be launched into an availability set

### ISSUE THREAD

**Issue by mdolian** [deis/deis#4332]
Currently, the Azure cluster creation script does not create nor put nodes into an availability set.  An availability set is required to ensure that no more than 1 node in the set is rebooted at a time.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to fixing for the LTS release, and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this.
