### ISSUE TITLE
Provide SHA256 hashes of deis and deisctl binaries

### ISSUE THREAD

**Issue by sbuss** [deis/deis#4336]
I'd like to verify that I have the correct `deis` or `deisctl` binaries (or their `.run` files). Please provide a file for each release, available over TLS, listing the SHA256 (or SHA1, or MD5) hashes for the files.

**Comment by Joshua-Anderson** [comment]
This is related to #4031 

I would like this as well.
This would probably have to be done on the Jenkins deisctl/cli builds, but I don't know of any simple way to get the changes into the docs. The only thing I can think of is uploading a checksum file to s3 along with the binaries. This file could also be uploaded to the GitHub release. I think the checksum would have to be manually changed in the docs.

**Comment by mboersma** [comment]
For [Deis v1.11](https://github.com/deis/deis/releases/tag/v1.11.0) the SHA256 hashes are available from:
 https://s3-us-west-2.amazonaws.com/opdemand/deis-1.11.0-SHA256SUMS

**Comment by mboersma** [comment]
Each Deis release since v1.11 has made SHA256 hashes available for the client binary installers. This issue can be closed when the v1.13 LTS release also provides hashes.

**Comment by mboersma** [comment]
For [Deis v1.13.0](https://github.com/deis/deis/releases/tag/v1.13.0) the SHA256 hashes are available from:
 https://s3-us-west-2.amazonaws.com/get-deis/deis-1.13.0-SHA256SUMS
https://github.com/deis/deis/releases/download/v1.13.0/deis-1.13.0-SHA256SUMS
