### ISSUE TITLE
Google: configuring DNS managed outside of Google DNS service? 

### ISSUE THREAD

**Issue by gvilarino** [deis/deis#4342]
Trying to deploy a new cluster to Google Compute Engine, I reach the point of configuring my DNS server. The thing is [the instructions](http://docs.deis.io/en/latest/installing_deis/gce/#configure-dns) imply that my domain is managed by Google (or at least that's what I'm getting).

Is there any way to set-up externally-managed DNS setting for a Deis cluster to work on `GCE`?

Any help would be appreciated.

**Comment by bacongobbler** [comment]
I think you could try using the load-balanced IP address in [the previous step](http://docs.deis.io/en/latest/installing_deis/gce/#load-balancing) as the given CNAME record with whatever external DNS service you wish to use. Hvae you tried that, or are there issues with GCE's load balancer?

There's also this document that goes into more detail on setting up external IP addresses if the above doesn't work: https://cloud.google.com/compute/docs/instances-and-network#externaladdresses

**Comment by bacongobbler** [comment]
Closing as stale. @gvilarino please feel free to re-open if you've tried what I suggested and still need help configuring DNS for GCE. Thanks!

**Comment by gvilarino** [comment]
Thanks. I'll try this sometime in the future and will let you know if anything comes up
