### ISSUE TITLE
Do we need a more sophisticated health check for deis-router?

### ISSUE THREAD

**Issue by krancour** [deis/deis#4344]
This is unrelated to application health checks.

On each platform we support, load balancers are configured with a health check that just tests whether anything is listening on port 80.  This means any node in a Deis cluster that is running the `deis-router` reports back as "healthy" and is therefore included in that load balancer's pool of instances it can send traffic to.

Where this breaks down is the case where Kubernetes is the scheduler.  If the `deis-kube-proxy` component should fail on any given machine, then the consequence is that even though a router instance might be alive and well on that same machine, application traffic sent to that machine will never reach a pod.

Is it possible that `deis-router` should include a more sophisticated health check endpoint where a 200 is returned if the router is _able_ to route traffic?  Here, "able" is probably defined as the `deis-router` component is up and healthy, _and_, if applicable, `deis-kube-proxy` is as well.

Ping @bacongobbler for thoughts.

**Comment by bacongobbler** [comment]
Yes, if we are redirecting traffic to the service's virtual IP address for an app then we should probably do a health check against the proxy, or else the router will not be able to serve traffic. I see that there's https://github.com/kubernetes/kubernetes/pull/5984 which may help with the implementation.

**Comment by mboersma** [comment]
Refs #4222 -- we should fix this at least before k8s becomes the default scheduler.

**Comment by krancour** [comment]
kube-proxy has its own healthcheck endpoint: `localhost:10249/healthz`

I think what I'd like to do is modify the router to implement a healthcheck enpoint of its own.  If etcd key `/deis/controller/schedulerModule` != "k8s", then that endpoint can respond with a hard-coded 200.  (Meaning if router is up, router is "healthy.")  If `/deis/controller/schedulerModule` == "k8s", then that same endpoint will be a proxy for kube-proxy's own healthcheck endpoint.

@mboersma @bacongobbler would that implementation make sense?

**Comment by krancour** [comment]
And a shout out to @aledbf for informing me of kube-proxy's own healthcheck endpoint.

**Comment by bacongobbler** [comment]
Yes that was the endpoint that I pointed out in the kubernetes PR :)

**Comment by krancour** [comment]
@bacongobbler sorry!  I looked at that PR and once I saw that it was using monit, I think i stopped reading.  I was thinking a separate babysitter process doesn't help us much since that's all built into Fleet anyhow.  But I see now that PR _uses_ the aforementioned health check.  Sorry for not grokking that the first time around.

**Comment by sstarcher** [comment]
I would like to see a better health check on the router even without k8s as the scheduler.  I have previously had a one off incident where confd broke and re-wrote all of my templates in an invalid format causing the router to be entirely unfunctional.  This was only detectable as an intermittent routing failure since one of the other routers was still functional.

**Comment by krancour** [comment]
> I have previously had a one off incident where confd broke and re-wrote all of my templates in an invalid format causing the router to be entirely unfunctional.

If the router is entirely non functioning, wouldn't even the existing healthcheck fail anyway?

**Comment by sstarcher** [comment]
@krancour The only existing health check I see for an AWS deployment is a ping and as long as the router container is running that passes.

**Comment by krancour** [comment]
It's not a ping.  It's a check whether anything is listening on port 80.  If nginx is down, nothing is.  If you encountered some circumstance where confd wrote bad nginx config and still kept serving traffic on port 80, then whatever happened there had to have been an extreme outlier and I'd need more concrete information to go on in order to do anything about detecting that.  For now, my main concern is accurately detecting the case when a router can't do its job not because it is down, but because its downstream kube-proxy is down.

**Comment by krancour** [comment]
So this is a little harder to do than it looks, although I still feel it should be done.

The major barrier I am encountering at the moment is that the kube-proxy only binds to 10249 on 127.0.0.1 and _not_ on the host's private IP.  This makes it impossible for the containerized router to proxy kube-proxy's health check endpoint by passing traffic to the host's private IP.

Ping @aledbf.  Any thoughts?

**Comment by aledbf** [comment]
@krancour why not just change the default `kube-proxy` value of `--healthz-bind-address=127.0.0.1` to `--healthz-bind-address=0.0.0.0`?

**Comment by krancour** [comment]
I was digging and found that just as you posted it.  :)  That should solve the problem.

**Comment by krancour** [comment]
Thanks @aledbf !
