### ISSUE TITLE
Design Document: Provisioning Deis

### ISSUE THREAD

**Issue by sgoings** [deis/deis#4345]
Design Document: Provisioning Deis
==================================

Provisioning Deis is currently an adventure; usually a treacherous adventure.
We've fielded many provisioning related problems on our #deis irc channel, many
of which amounted to small missteps in the [manual process](http://docs.deis.io/en/latest/installing_deis/install-platform/).

We as the Deis maintainers have been frustrated with the provisioning process
during our normal development workflows and especially during release testing
time. See: #4318 (thanks @krancour for starting this public discussion!) and #2882.
We've been dreaming of a future where provisioning and deploying Deis to
any cloud provider is a trivial and an elegant experience.

Design Goals
------------

* Make the provisioning process less painful, more seamless, and faster for all
  users
* Provide a way to manage and update long-living Deis clusters
* Allow anyone to run our full suite of tests on any cluster
* Create a common user experience for provisioning Deis regardless of what
  provider is used
* Avoid implementing yet another desired state infrastructure tool (Terraform)
* Construct a buffer between users and the details of Deis' installation process
  and internal architecture
* Bridge the gap between basic and advanced deployments of Deis
* Enable users to service multiple Deis clusters simultaneously

Proposal: `rigger`
----------------

In order to achieve our dream of a more elegant Deis provisioning process for us
as maintainers and everyone as users, we'd like to build a new tool specific to
Deis called: `rigger`.

Why the name?

A rigger is a person who specializes in the lifting and moving of extremely
large or heavy objects. They understand the ins and outs of static and dynamic
loads and their expertise is of paramount importance to ensure that the
components of a project are delivered safely and expediently into the exact
positions. Consider the complexities involved for a rigger when [replacing a 38
ton thruster on the DCV Balder](https://www.youtube.com/watch?v=Bti0Z5a7GmE).
Therefore, naming this tool "rigger" makes sense: it's your highly experienced
aide in lifting your Deis platform into position.

`rigger` is your interface to deploying Deis on a variety of cloud providers.
`rigger` will:

* ask questions from the user up front instead of requiring full attention
  during the whole provisioning processes
* abstract the details of cloud providers and Deis provisioning quirks by
  default but allow you to coordinate details if you have specific demands
* show you how it created the infrastructure (an audit log and package of
  important components of the provisioning process will be provided to users)
* be held within a separate git repository from the core Deis project.
  * this will enable us to release updates to the provisioning process outside
    of the core Deis release cycle. Our plan is to keep a [strict interface
    ](#cloud-provider-interface) between `rigger` and the cloud providers
    already written in Deis' contrib directory. If we do have a need to break
    this interface, we can build in the smarts about which interface `rigger`
    should use per version of Deis.

So what will this look like for you?

For a **contributor**, hacking on Deis becomes:

    rigger configure # asked a set of questions

[![asciicast](https://asciinema.org/a/25605.png)](https://asciinema.org/a/25605)

    rigger checkout # checks out Deis repo <hack on Deis>
    rigger provision # provisions Deis cluster from checked out repository
    ...

[![asciicast](https://asciinema.org/a/25611.png)](https://asciinema.org/a/25611)

For a **tester**, testing Deis becomes:

    rigger configure # asked a set of questions (including what version you'd like to test)
    rigger provision
    rigger test # can choose what type of test to run or run manual tests at this point

[![asciicast](https://asciinema.org/a/25613.png)](https://asciinema.org/a/25613)

For an **operator**, provisioning Deis becomes:

    rigger configure
    rigger provision
    rigger test
    rigger save

    <time passes>

    rigger configure --file <package that was saved>
    rigger upgrade --to <version>

    <time passes>

    rigger configure --file <package that was saved>
    rigger provision # could be modifications to change infrastructure below Deis

`rigger`'s user interface
----------------

##### Inputs

The command will ask the absolute minimum amount of questions needed to
provision a Deis cluster. Such as:

1. What version of Deis? [latest Deis release]
2. [What cloud provider would you like to use? [Digital Ocean]](http://deis.io/code-for-credit-digitalocean/)
3. What type of cluster are you looking to create? [development]
4. What are your cloud provider credentials? [suggestion]

##### Operation

If no file is passed in, `rigger` will:

  - ask necessary questions to fill in a complete `rigger` config file
  - consider the file to be the "current" environment (used for future `rigger`
    commands)

If a file is passed in, `rigger` will:

  - validate the file
  - ask any questions to fill in missing information in the file
  - consider the file to be the "current" environment (used for future `rigger`
    commands)

##### Outputs

a configuration file

This file is used as the source of truth for any future `rigger` operation. It
could also be sourced into a shell environment to allow more advanced users
to easily dive into the inner workings of a Deis cluster (config file could
hold DEIS_VERSION, PROVIDER, GOPATH, DEIS_ROOT, DEIS_TEST_DOMAIN)

    export DEISCTL_UNITS="/Users/username/.rerun-deis/490572dde4/units"
    export DEIS_ROOT="/Users/username/go/src/github.com/deis/deis"
    export DEIS_TEST_AUTH_KEY="/Users/username/.ssh/deis-test"
    export DEIS_TEST_DOMAIN="deis.xyz"
    export DEIS_TEST_ID="490572dde4"
    export DEIS_TEST_ROOT="/Users/username/.rerun-deis/490572dde4"
    export DEIS_TEST_SSH_KEY="/Users/username/.ssh/deis-test"
    export DEIS_VARS_FILE="/Users/username/.rerun-deis/490572dde4/vars"
    export DEV_REGISTRY="registry.hub.docker.com"
    export GOPATH="/Users/username/go"
    export IMAGE_PREFIX="username/"
    export ORIGINAL_PATH="/Users/username/.rbenv/bin:/Users/username/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export PATH="/Users/username/go/bin:/Users/username/.rbenv/bin:/Users/username/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export PROVIDER="aws"
    export VERSION="1.9.1"

##### Operation

Ability to clone, just update, or leave the target alone

##### Outputs

DEIS_ROOT contains the version of Deis that you'd like to use (determined in the
configure stage)

********************************************************************************

##### Operation

Use config file contents to:

  - load provider logic from deis.git (see expected provider interface)
  - create a cluster of machines via cloud provider
  - install and start Deis

Could also use this on an existing cluster to increase/decrease/configure
infrastructure

##### Outputs

1. a working Deis cluster!
2. configuration file updates...

The cluster provisioning process will produce information necessary to interact
with the Deis cluster in future operations, such as DEISCTL_TUNNEL:

    export DEISCTL_TUNNEL="ec2-54-201-171-20.us-west-2.compute.amazonaws.com"
    export DEISCTL_UNITS="/Users/username/.rerun-deis/490572dde4/units"
    export DEIS_PROFILE="test-490572dde4"
    export DEIS_ROOT="/Users/username/go/src/github.com/deis/deis"
    export DEIS_TEST_AUTH_KEY="/Users/username/.ssh/deis-test"
    export DEIS_TEST_DOMAIN="test-490572dde4.deis.xyz"
    export DEIS_TEST_ID="490572dde4"
    export DEIS_TEST_ROOT="/Users/username/.rerun-deis/490572dde4"
    export DEIS_TEST_SSH_KEY="/Users/username/.ssh/deis-test"
    export DEIS_VARS_FILE="/Users/username/.rerun-deis/490572dde4/vars"
    export DEV_REGISTRY="registry.hub.docker.com"
    export ELB_DNS_NAME="deis-test-DeisWebE-1WG53EPRDVT11-1617219712.us-west-2.elb.amazonaws.com"
    export ELB_NAME="deis-test-DeisWebE-1WG53EPRDVT11"
    export GOPATH="/Users/username/go"
    export IMAGE_PREFIX="sgoings/"
    export ORIGINAL_PATH="/Users/username/.rbenv/shims:/Users/username/.rbenv/bin:/Users/username/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export PATH="/Users/username/.rerun-deis/490572dde4/bin:/Users/username/go/bin:/Users/username/.rbenv/shims:/Users/username/.rbenv/bin:/Users/username/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export PROVIDER="aws"
    export STACK_NAME="deis-test-490572dde4"
    export STACK_TAG="test-490572dde4"
    export VERSION="1.9.1"```

********************************************************************************

##### Inputs

type of test to run

  - full
  - smoke
  - specific component
  - app deploy + test (deploy some apps that we can keep an eye on during the
    upgrade process)
  - app test (make sure previously deployed apps are responding correctly)
  - app test + destroy (make sure previously deployed apps are responding
    correctly, and then remove them)

##### Outputs

Summary of tests run and their results

********************************************************************************

##### Outputs

completely destroyed cluster that was referred to in the configuration file

********************************************************************************

##### Outputs

deisctl and deis clients (including appropriate units files) installed in a
directory available to the user which could be added to the user's PATH

********************************************************************************

##### Outputs

package containing all relevant configuration, manipulation, and information of
what's been done to a certain environment... such as:

  - audit log
  - Terraform state files
  - complete userdata files
  - parameters passed into various scripts
  - `rigger` config file
  - deis test results

********************************************************************************

##### Inputs

    --to <version>

    supply the version that you want to upgrade your Deis cluster to

    --upgrade-style [graceful, inplace]

    graceful: (no application downtime) use the new (as of 1.9.0) Deis upgrade
    logic

    inplace: (more downtime) use the documented way of tearing down the whole
    cluster and reinstalling Deis

##### Operation

Verification that the upgrade is worth it (an upgrade from 1.9.0 -> 1.9.0
doesn't make sense)

##### Outputs

Your old cluster, but with the version of Deis you specified!

<a name="cloud-provider-interface">`rigger`'s interface for cloud providers</a>
----------------

Below are our requirements for building a set of scripts that `rigger` expects
to exist. Each operation (installation of deps, creating a cluster) will just
call the appropriate shell script. How you implement the logic of creating a
cluster is left up to the developer (as long as the dependencies are installed
via the *Install Dependencies* script)!

##### Install Dependencies

    contrib/<provider_name>/install.sh

##### Create Cluster

    contrib/<provider_name>/create.sh

##### Check Cluster

    contrib/<provider_name>/check.sh

##### Destroy Cluster

    contrib/<provider_name>/destroy.sh

Future Ideas
============

- make a web service on top of `rigger` that people could use to provision a Deis
  cluster

**Comment by bacongobbler** [comment]
Another future idea would be to use a config file format other than environment variables so that it's more portable to other language bindings (Go, python, nodejs etc) so that anyone could write a `rigger` client for their specific stack. However, I know that parsing json in bash is practically impossibls so it'll stay as a pipe dream for me :)

**Comment by krancour** [comment]
First let me say I _love_ this.  It addresses most of my gripes with the current provisioning processes.  My two favorite parts are the option to create dev vs prod clusters and the ability to save all the artifacts used for provisioning. :+1: 

Some crazy ideas...

Related to `rigger save`, it's probably a good idea for users to check those saved artifacts into source control.  That got me thinking that rigger could be a project-oriented tool, where the "project" is a repo containing the artifacts for all of an operator's clusters.  Idea:

Initiate a new rigger project:
```
rigger init
```

This could create a project level Rigfile to hold project level configuration.  :)

List clusters:
```
rigger list clusters
```

Configure a new cluster:
```
rigger config cluster <new cluster name>
```

The above could, perhaps, eliminate the need for an explicit `rigger save` because whatever artifacts are generated at config-time could be dumped directly into a directory specific to the cluster in question.

Other things like provision and update then also need the cluster name as context when executed:

```
rigger provision cluster <cluster name>
```

This might be crazy, but it could even be possible to integrate this pretty smartly with git so that operations that altar a cluster in any way actually automatically check upstream master for updates before proceeding.  Similarly, those changes could automatically be committed and pushed upstream upon completion.  These features would help clusters with multiple operators avoid race conditions that might occur in the course of cluster maintenance.

Lastly, how about support for provisioning pre-requisites like VPCs (with or without private subnets), or RDS databases and S3 buckets for Cephless clusters?

```
rigger list vpcs
rigger configure vpc <new vpc name>
rigger provision vpc <vpc name>
```

Note: I know "VPC" is an Amazon-specific term.  So maybe what this touches on is a need for rigger itself to be pluggable so that the provisioning process for each provider can contribute provider-specific doohickies.

**Comment by sgoings** [comment]
@bacongobbler - One of the things that is possibly the easiest (and makes the most sense) to port to Go from Bash is the "configure" step. `rigger configure` could just be a call to a go binary. Then you could build in support for various types of outputs (yaml, env var lists, Terraform inputs, etc.) only one of which matters to the rest of `rigger`'s operation.

Totally a fan of moving things away from bash where it makes sense. :+1:

**Comment by sgoings** [comment]
@krancour I like your idea of forcing users to use version control with `rigger` out of the box. I'm in agreement with the init -> config -> provision model. However, I want to be careful that we don't add too many dependencies for rigger itself (or it can self manage those dependencies). I have essentially two targets of people:

- people who just want to get Deis up and running with the least amount of friction (this could even be us while demo-ing Deis somewhere... and fewer moving parts is better here)
- people who care more about how easy the cluster will be to manage over time (this is definitely the case for the background that you and lots of current Deis community members come from)

I think there's a way to establish a happy medium by figuring out what the user is after, but early in the "configure" process (leaning toward doing your suggested `init` operation automatically if/when it makes sense).

For the idea of having `rigger` create vpcs, RDS databases, and S3 buckets... those actual operations seem like something CloudFormation should do (or Terraform) and could be done during the provision step. Why would we want to inject a prereq step before actual Deis provisioning + deployment? Why can't the single provision step do [everything](http://www.zombo.com/)?

**Comment by krancour** [comment]
> Why can't the single provision step do everything?

Good question.  I think there's a lot to be said for not atomically coupling a Deis cluster's destiny to the VPC it lives in.  In CloudFormation terms, this means having the VPC be one stack, while each cluster within is another.  RDS + S3 could even be another stack "between" those two.  This allows an operator who knows little about Deis to tweak network stuff like route tables and network ACLs and means also that destroying and rebuilding a cluster doesn't need to take the whole underlying network and persistence layer with it.  It also opens the possibility of multiples clusters per VPC.

Yes... all of that can be done to a certain extent today, but only if you bring your own VPC and then set a whole bunch of environment variable to make your new cluster go there.  That means a whole lot of prework for anyone wanting to work as outlined above.  (i.e. They need to bring their own VPC template.)  IMO, we should be able to provision that for users as a foundation of a production worthy cluster.

**Comment by sgoings** [comment]
Ah. Makes sense. Here's maybe an idea for the more advanced workflow you're looking for:

`rigger configure`
- finds out that you're a most excellent ops person who wants to create a fancy Deis setup in AWS.
- starts to create the rigfile which would have some metadata in it such that it would enable you to use a `rigger` AWS plugin

`rigger [vpc, s3, rds] [configure, provision, list]` is available which starts to write info about itself into the Rigfile (and probably CF/Terraform files).

`rigger provision` continues to have the same behavior of setting up the Deis specific cluster.

Thoughts?

**Comment by krancour** [comment]
We're starting to converge.  One point of clarification and one follow up thought...

I was thinking "Rigfile" was "project-level" and not cluster-specific, much like a Dockerfile, Vagrantfile, Makefile, Rakefile, etc. is typically at the root of a project-- that it would hold configuration specific to the "rigger project".  What goes in there?  Imaginatively, it could be YAML, JSON, or even a DSL for setting provider creds or installing and configuring rigger plugins like the potential AWS plugin you just proposed.

The other thing is that to promote a consistent implementation and UX, the core of rigger itself could be a plugin.  That means `rigger configure` might better be expressed as `rigger configure cluster` or `rigger cluster configure` (take your pick).

**Comment by bacongobbler** [comment]
[rigger's](https://github.com/deis/rigger) a thing now. Closing!
