### ISSUE TITLE
Deploys stop to work

### ISSUE THREAD

**Issue by ineu** [deis/deis#4350]
... soon after restarting `deis-store-gateway@1`.
When deploying app, it hangs on 'Succesfully built image' and never pushes to registry.
When I restart `deis-store-gateway@1`, next deploy works, but not for long, maybe for 10 minutes or so.
Other components like registry or builder don't require restart, only gateway does.
Ceph is HEALTH_OK, osds/mons/mdses are fine. Restarting them doesn't change things as well.
During deploy I see following in builder logs:
```
Aug 27 12:38:27 staging-coreos-2 sh[7896]: time="2015-08-27T12:38:27Z" level="error" msg="Error in LookupRemoteImage: HTTP code 404"
Aug 27 12:38:37 staging-coreos-2 sh[7896]: time="2015-08-27T12:38:37Z" level="error" msg="Error in LookupRemoteImage: HTTP code 404"
```
Don't know if it is related to this problem.

Also OSDs keep emiting to logs on every machine in the cluster:
```
Aug 27 14:02:11 staging-coreos-2 sh[31819]: 2015-08-27 14:02:11.151154 7f701b8bb700  0 <cls> cls/rgw/cls_rgw.cc:1947: ERROR: rgw_obj_remove(): cls_cxx_remove returned -2
```

Deis is 1.9, CoreOS is 723.3.

**Comment by dmitriy-kiriyenko** [comment]
![mc7ctyn3](https://cloud.githubusercontent.com/assets/124430/11061253/e0c3bd96-87b6-11e5-9a55-ff4534e2ae59.jpeg)
