### ISSUE TITLE
Problems cloning a public repository using NPM in builder

### ISSUE THREAD

**Issue by mdolian** [deis/deis#4352]
This is on Deis 1.9 and CoreOS 647.2.0

When trying to clone a public repository via SSH during deployment (using buildpacks), we get a permission denied error.  I can reproduce this error by jumping into the builder container and running the git clone command manually:

```
bash-4.3# git clone git@github.com:babel/broccoli-babel-transpiler.git
Cloning into 'broccoli-babel-transpiler'...
Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

The same command works fine locally and on the CoreOS host itself:

```
/tmp $ git clone https://github.com/babel/broccoli-babel-transpiler.git
Cloning into 'broccoli-babel-transpiler'...
remote: Counting objects: 403, done.
remote: Total 403 (delta 0), reused 0 (delta 0), pack-reused 403
Receiving objects: 100% (403/403), 60.93 KiB | 0 bytes/s, done.
Resolving deltas: 100% (225/225), done.
Checking connectivity... done.
```

Interestingly enough, using https inside the builder seems to work fine so it seems that there may be an issue with SSH inside the container:

```
bash-4.3# git clone https://github.com/babel/broccoli-babel-transpiler.git
Cloning into 'broccoli-babel-transpiler'...
remote: Counting objects: 403, done.        
remote: Total 403 (delta 0), reused 0 (delta 0), pack-reused 403        
Receiving objects: 100% (403/403), 60.93 KiB | 0 bytes/s, done.
Resolving deltas: 100% (225/225), done.
Checking connectivity... done.
```

Thanks

**Comment by carmstrong** [comment]
@mdolian Your first clone uses `git@...` which will authenticate using key authentication, and will fail. You'll need to use an anonymous HTTPs clone as you did in your other examples. 

I'm not sure where this is getting cloned/invoked, but you should be able to change this yourself or change the `BUILDPACK_URL` if this is a buildpack.

**Comment by mdolian** [comment]
ok, so it sounds like the expected result of a git clone using the ssh url is a key authentication failure.  This isn't an issue if that is the case.  We will use the https url.
