### ISSUE TITLE
Use cache in deployed Apps

### ISSUE THREAD

**Issue by arkkanoid** [deis/deis#4353]
Hi! I'm thinking to implement a Web Cache for the apps I've deployed. As we know, the router component has an Nginx running, it would be possible to set up our caching system enabling the Nginx Caching Module?
I've some doubts due to each node has a router component, so an independent cache. Depending on which node receive the HTTP request, it will be cached or not.

**Comment by laurrentt** [comment]
You could also use Nginx caching at the app container level.

**Comment by bacongobbler** [comment]
I don't think it's possible to set this up on the routers. Since they share nothing, the cache may or may not be available between requests which can cause unintentional behavior.

related: #3541 (sticky sessions only work if you hit the same router every time)

**Comment by arkkanoid** [comment]
@laurrentt not all apps I've deployed use Nginx, so I can't do it :(
Ok, I see that is not possible to implement the caching system at this layer. Maybe I can run an instance with Nginx / Varnish in front of the Deis ELB? Of course it would be replicated.

**Comment by bacongobbler** [comment]
Sure. Either that or you could use Redis at the application level to store your session data. :)

**Comment by bacongobbler** [comment]
closing as the original question has been answered. Please let us know if you have any more questions and we'd be happy to answer. Thanks! :)
