### ISSUE TITLE
Proposal: controller should republish certain things to etcd at startup

### ISSUE THREAD

**Issue by krancour** [deis/deis#4355]
Supersedes #3486 and #3539

In the event a new cluster is built as a replacement for an old one and the database is either external (as in the case of running Cephless) or is restored from a backup of the old cluster, certain necessary configuration that _is_ present in the database needs to be republished to etcd.

The controller could do this at startup.

I would propose (at least) the following things be republished:

* Application configuration
* Application domains
* User keys

Relates to #4333

**Comment by carmstrong** [comment]
Good idea. We already keep track of what needs to get done here: http://docs.deis.io/en/latest/managing_deis/backing_up_data/#finishing-up

It should be fairly straightforward to have that occur in an `ExecStartPost` script.

**Comment by krancour** [comment]
@carmstrong this should be safe to do every time the controller starts, right?  I can't see any reason why not.

**Comment by carmstrong** [comment]
> this should be safe to do every time the controller starts, right?

I think so, but @bacongobbler or @mboersma are probably best to confirm.

**Comment by bacongobbler** [comment]
as long as we're not modifying the objects themselves and just triggering the post-save signals it sounds fine to me.

**Comment by krancour** [comment]
@carmstrong so, interestingly, the [directions you referenced](http://docs.deis.io/en/latest/managing_deis/backing_up_data/#finishing-up) don't actually work-- at least not entirely.

With the exception of user keys published under `/deis/builder/users/<username>/<key>`, all the post-save hooks are publishing to etcd _only_ when the object in question is newly created.

[Here's a good example](https://github.com/deis/deis/blob/master/controller/api/models.py#L1190-L1193):

```
def _etcd_publish_domains(**kwargs):
    domain = kwargs['instance']
    if kwargs['created']:
        _etcd_client.write('/deis/domains/{}'.format(domain), domain.app)
```
