### ISSUE TITLE
`deis ps -a www` fails

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#4357]
This fails:

```
deis ps -a www
Found no matching command, try 'deis help'
Usage: deis <command> [<args>...]
```

but with the old client, this was a valid command. `deis ps:list -a www` works as expected.

**Comment by Joshua-Anderson** [comment]
I'll look into this. It probably has to do with the code that expands shortcuts.

**Comment by bacongobbler** [comment]
It's odd because `deis scale cmd=3 -a www` worked so there's probably some edge case here.

**Comment by mboersma** [comment]
Adding "ps" -> "ps:list" to the `replaceShortcut` func in deis.go does seem to fix this. (We didn't need to do that in the Python client, but this code path is different.)

**Comment by mboersma** [comment]
Also note the difference between `deis users -h` and `deis users:list -h`. No help message in the first case, unless you add "users" -> "users:list" to shortcuts. I think we may need to add explicit shortcuts for several commands.

**Comment by Joshua-Anderson** [comment]
@mboersma I found at least part of the [bug](https://github.com/deis/deis/blob/master/client-go/parser/ps.go#L22) as you can see there, I overrode the command line args for list without considering that args could be passed to `ps`.

**Comment by Joshua-Anderson** [comment]
@mboersma 
> I think we may need to add explicit shortcuts for several commands.

This bug affects several commands, but adding shortcuts will break catagory level help. I'll open a general PR to fix this.
