### ISSUE TITLE
Builder fails to start in stateless platform

### ISSUE THREAD

**Issue by daanemanz** [deis/deis#4358]
Hello,

I've been trying to set up a stateless platform (1.9.1), so far without success. I've set up the following:

* S3 bucket and credentials that allow all access to S3
* RDS instance accessible from the Deis hosts
* Log endpoint at Logentries

I've set up the keys according to [this guide](http://docs.deis.io/en/latest/managing_deis/running-deis-without-ceph/#deploying-the-cluster), and here's the output of `etcdctl ls --recursive`:

```
$ etcdctl ls --recursive
/deis
/deis/certs
/deis/logs
/deis/logs/host
/deis/logs/port
/deis/logs/protocol
/deis/registry
/deis/registry/protocol
/deis/registry/host
/deis/registry/s3bucket
/deis/registry/s3accessKey
/deis/registry/s3secretKey
/deis/registry/s3region
/deis/registry/s3path
/deis/registry/s3encrypt
/deis/registry/hosts
/deis/registry/hosts/x.x.x.x
/deis/registry/hosts/x.x.x.x/host
/deis/registry/hosts/x.x.x.x/port
/deis/registry/bucketName
/deis/registry/s3secure
/deis/registry/masterLock
/deis/registry/port
/deis/store
/deis/store/gateway
/deis/store/gateway/secretKey
/deis/store/gateway/host
/deis/store/gateway/port
/deis/store/gateway/accessKey
/deis/database
/deis/database/port
/deis/database/name
/deis/database/user
/deis/database/password
/deis/database/engine
/deis/database/host
/deis/cache
/deis/builder
/deis/builder/users
/deis/router
/deis/router/proxyProtocol
/deis/router/hosts
/deis/router/hosts/x.x.x.x
/deis/router/hosts/x.x.x.x
/deis/router/hosts/x.x.x.x
/deis/router/hsts
/deis/router/gzip
/deis/platform
/deis/platform/domain
/deis/platform/sshPrivateKey
/deis/controller
/deis/services
/deis/domains
```

The log output that I'm seeing on the builder instance is:

```
builder: waiting for confd to write initial templates...
2015-08-27T21:02:51Z 7a07bb52563a confd[303]: ERROR template: builder:79:8: executing "builder" at <getv "/deis/controll...>: error calling getv: key does not exist
2015-08-27T21:02:51Z 7a07bb52563a confd[303]: ERROR template: receiver:13:30: executing "receiver" at <getv "/deis/controll...>: error calling getv: key does not exist
builder: waiting for confd to write initial templates...
2015-08-27T21:03:01Z 7a07bb52563a confd[309]: ERROR template: builder:79:8: executing "builder" at <getv "/deis/controll...>: error calling getv: key does not exist
2015-08-27T21:03:01Z 7a07bb52563a confd[309]: ERROR template: receiver:13:30: executing "receiver" at <getv "/deis/controll...>: error calling getv: key does not exist
builder: waiting for confd to write initial templates...
2015-08-27T21:03:11Z 7a07bb52563a confd[315]: ERROR template: builder:79:8: executing "builder" at <getv "/deis/controll...>: error calling getv: key does not exist
2015-08-27T21:03:11Z 7a07bb52563a confd[315]: ERROR template: receiver:13:30: executing "receiver" at <getv "/deis/controll...>: error calling getv: key does not exist
builder: waiting for confd to write initial templates...
2015-08-27T21:03:21Z 7a07bb52563a confd[320]: ERROR template: builder:79:8: executing "builder" at <getv "/deis/controll...>: error calling getv: key does not exist
2015-08-27T21:03:21Z 7a07bb52563a confd[320]: ERROR template: receiver:13:30: executing "receiver" at <getv "/deis/controll...>: error calling getv: key does not exist
```
(on repeat)

Besides, the `deis-controller` refuses to start as well. Is there a step I'm missing here?

**Comment by bacongobbler** [comment]
the builder relies on the controller, so if the controller refuses to start then the builder won't be able to boot either. What does the logs for the controller say? :)

**Comment by daanemanz** [comment]
Nothing at all -- that's probably why. And running `deisctl start controller` doesn't do anything either, it just sits and waits...

**Comment by bacongobbler** [comment]
`deisctl journal controller` doesn't show anything? How about `deisctl list`? Is it showing up as attempting to boot or does it not exist there either?

**Comment by daanemanz** [comment]
Here's the output of `deisctl list`:
```
$ deisctl list
UNIT			MACHINE			LOAD	ACTIVE		SUB
deis-builder.service	15551a4a.../x.x.x.x	loaded	activating	start-post
deis-controller.service	41aa9c24.../x.x.x.x	loaded	inactive	dead
deis-logspout.service	15551a4a.../x.x.x.x	loaded	active		running
deis-logspout.service	41aa9c24.../x.x.x.x	loaded	active		running
deis-logspout.service	4e0f8d5e.../x.x.x.x	loaded	active		running
deis-logspout.service	cf95e747.../x.x.x.x	loaded	active		running
deis-logspout.service	eb208acb.../x.x.x.x	loaded	active		running
deis-publisher.service	15551a4a.../x.x.x.x	loaded	active		running
deis-publisher.service	41aa9c24.../x.x.x.x	loaded	active		running
deis-publisher.service	4e0f8d5e.../x.x.x.x	loaded	active		running
deis-publisher.service	cf95e747.../x.x.x.x	loaded	active		running
deis-publisher.service	eb208acb.../x.x.x.x	loaded	active		running
deis-registry@1.service	4e0f8d5e.../x.x.x.x	loaded	active		running
deis-router@1.service	cf95e747.../x.x.x.x	loaded	active		running
deis-router@2.service	eb208acb.../x.x.x.x	loaded	active		running
deis-router@3.service	15551a4a.../x.x.x.x	loaded	active		running
```

So it does exist, but it's not even attempting to boot. From the host that it's scheduled on:
```
$ journalctl -u deis-controller
-- Logs begin at Thu 2015-08-27 20:21:14 UTC, end at Thu 2015-08-27 21:53:31 UTC. --
```

Not much to look at...

**Comment by carmstrong** [comment]
@daanemanz If you follow the fleet daemon (`journalctl -fu fleetd`) on the host that controller is scheduled to, what you do see when you try to start the component?

**Comment by bacongobbler** [comment]
try booting it with `deisctl start controller`, then follow the logs. Seems odd that it never started though. What version of `deisctl` was this?

**Comment by daanemanz** [comment]
@carmstrong `journalctl -fu fleetd` doesn't show any output on any of the CoreOS hosts, but I can see it's running:
```
$ ps aux | grep fleetd
root       970  0.5  0.1 408004 23500 ?        Ssl  20:23   0:31 /usr/bin/fleetd
```

@bacongobbler This is `deisctl` version 1.9.1

While attempting to start the controller using `deisctl start controller`:
```
$ deisctl journal controller
-- Logs begin at Thu 2015-08-27 20:21:14 UTC. --
```

**Comment by daanemanz** [comment]
Could this have to do with the fact that I'm running my CoreOS hosts in private subnets on AWS, and they have to access S3 through a NAT? Should we connect to S3 over https instead?

**Comment by bacongobbler** [comment]
the controller does not require access to S3, so that shouldn't be the issue here. Is the container actually running or is it still inactive? If it's inactive then I'd probably look into fleet as @carmstrong mentioned. :/

**Comment by daanemanz** [comment]
I think I know what the issue might be... 
```
$ fleetctl cat deis-controller
[Unit]
Description=deis-controller
Requires=deis-store-volume.service
After=deis-store-volume.service
```
Because this is a stateless install, it's not running `deis-store-volume.service` at all and thus the service will never start. Would that make sense?

**Comment by bacongobbler** [comment]
Ah yes, this was fixed in v1.9.1: https://github.com/deis/deis/commit/850aceb91a160f9afd306bfdd431cc2ffe3dbb79

It looks like you have some older units installed. did you run `deisctl refresh-units` after installing the v1.9.1 client?

**Comment by daanemanz** [comment]
Ehhhh. That makes total sense. I did not run `deisctl refresh-units` but I will do so and report the outcome!

**Comment by daanemanz** [comment]
That worked! Will close this issue. Thanks for the help!
