### ISSUE TITLE
natdnshostresolver1 in Vagrantfile needs to be "on" for VirtualBox on OSX now?

### ISSUE THREAD

**Issue by cchamilt** [deis/deis#4360]
Hi, just setup a clean/new 1.9.1 on 10.10 OSX with current Vagrant 1.7 and 5.0 VirtualBox.  "deisctl start platform" couldn't start up and checking the logs I realized it wasn't resolving DNS.  So I stopped the VMs and set natdnshostresolver1 to "on" for them, restarted and now things seem to work and services are up.

**Comment by bacongobbler** [comment]
Could you explain your issue in more detail? I provisioned a fresh cluster this morning without any DNS resolution issues on my end, but I'd be curious to see how its failing for you.

**Comment by cchamilt** [comment]
The VMs have empty resolv.confs, so no ability to download anything.  I set natdnshostresolver1 back on and restarted them to populate resolv.conf and it worked.

**Comment by sgoings** [comment]
It looks like we've been setting this option in the Vagrantfile for a while: https://github.com/deis/deis/blame/34cce8351f928ad01522ecb4548cdd9e1c35eb33/contrib/docker-registry/Vagrantfile#L14

**Comment by bacongobbler** [comment]
According to master [this is disabled](https://github.com/deis/deis/blob/ea94180c7fff82cf8eb6dd39bc263060bfdcd0c1/Vagrantfile#L155-L159). This code came from upstream so I'm curious why DNS resolution would work fine for us but not for @cchamilt.

**Comment by cchamilt** [comment]
Yeah, I am not sure if the problem is just my system, but if Vagrant didn't provide me with a resolv.conf with natdns solutions off what does it do for other people setting up Deis with NAT Vagrant?  I thought these were two settings were the only DNS options outside setting resolv.conf manually.  

CoreOS removed it, but Deis recently put it back in - #4107.  Am I just lucky/unlucky, is it worked around in recent VirtualBox (5.0.0r101573), is it finally fixed by Apple (10.10.4) where it should be?

**Comment by carmstrong** [comment]
> CoreOS removed it

It's actually still there, but baked into the CoreOS .box image rather than the Vagrantfile - see the discussion on https://github.com/coreos/coreos-vagrant/pull/254#issuecomment-125300306

**Comment by bacongobbler** [comment]
ping @cchamilt, are you still seeing this issue? I don't think anything relevant has occurred in master but we haven't had any issues from anecdotal evidence.

**Comment by cchamilt** [comment]
Yeah, it works now.  I just tested in a new environment and everything comes up OK.

**Comment by cchamilt** [comment]
Works now with "on" set.
