### ISSUE TITLE
Proposal feat(builder): allow custom slugrunner images

### ISSUE THREAD

**Issue by aledbf** [deis/deis#4362]
Using an env variable like `SLUGRUNNER_IMAGE` configured in the app (could be global too)

One reason for this feature is the reduction of the size in the final image. 
(I know that the application images have `heroku/cedarish as parent image but doing `docker save` from any app implies 1.2GB).

As an example, using:

```
FROM alpine:3.2

# Download and install glibc
RUN apk add --update curl bash libstdc++ openssl zlib && \
  curl -o glibc-2.21-r2.apk -sSL "https://circle-artifacts.com/gh/andyshinn/alpine-pkg-glibc/6/artifacts/0/home/ubuntu/alpine-pkg-glibc/packages/x86_64/glibc-2.21-r2.apk" && \
  apk add --allow-untrusted glibc-2.21-r2.apk && \
  curl -o glibc-bin-2.21-r2.apk -sSL  "https://circle-artifacts.com/gh/andyshinn/alpine-pkg-glibc/6/artifacts/0/home/ubuntu/alpine-pkg-glibc/packages/x86_64/glibc-bin-2.21-r2.apk" && \
  apk add --allow-untrusted glibc-bin-2.21-r2.apk && \
  /usr/glibc/usr/bin/ldconfig /lib /usr/glibc/usr/lib && \
  echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf && \
  rm -rf *.apk && \
  rm -rf /var/cache/apk/*

RUN mkdir /app

RUN addgroup -g 2000 slug && \
    adduser slug -D -u 2000 -G slug -h /app -H -s /bin/bash && \
    chown slug.slug /app

# add default port to expose (can be overridden)
ENV PORT 5000

EXPOSE 5000

ADD ./runner /runner

RUN chown slug:slug /runner/init

USER slug

ENV HOME /app

ENTRYPOINT ["/runner/init"]

ONBUILD WORKDIR /app

ONBUILD ADD slug.tgz /app
```

as docker slugrunner image is 17MB + the size of the application.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776). On top of that, slugrunner by definition runs a Heroku cedar slug, so the cedar stack must be used. If you have a very specific use case such as this, you may want to customize the builder to allow this workflow but I don't think this is something we could reliably support. Sorry!
