### ISSUE TITLE
OSD doesn't join cluster after node reboot

### ISSUE THREAD

**Issue by ineu** [deis/deis#4369]
I've upgraded CoreOS on my nodes to 766.1. After reboot two nodes came back normally, but one deis-store-daemon failed to join cluster:
```
ID WEIGHT  TYPE NAME                 UP/DOWN REWEIGHT PRIMARY-AFFINITY 
-1 3.00000 root default                                                
-2 1.00000     host staging-coreos-1                                   
 0 1.00000         osd.0                down        0          1.00000 
-3 1.00000     host staging-coreos-2                                   
 1 1.00000         osd.1                  up  1.00000          1.00000 
-4 1.00000     host staging-coreos-3                                   
 2 1.00000         osd.2                  up  1.00000          1.00000 
```

To me it looks like OSD cannot connect to monitor for some reason. Though monitor restart followed by OSD restart didn't help.
Every monitor from `/etc/ceph/ceph.conf` is reachable on port 6789 from the deis-store-daemon container.

**Comment by ineu** [comment]
A bit of debugging of 'down' OSD shows: 
```
Aug 29 06:19:39 staging-coreos-1 sh[7393]: -99> 2015-08-29 06:18:51.855432 7f5902009700  3 osd.0 0 handle_osd_map epochs [1,90], i have 0, src has [1,90]
```
How come it has epoch 0? I haven't removed any data.

**Comment by ineu** [comment]
Eventually I found out that `current` directory was missing all data files, though `deis-store-daemon-data` was there and, according to `docker ps -a`, was created two weeks ago. Pretty weird.
I've had to remove data container to let deis-store-daemon recreate OSD.

**Comment by carmstrong** [comment]
> Eventually I found out that current directory was missing all data files

Very odd indeed...

**Comment by ineu** [comment]
Though there are tags attached to this issue let me close this one. I migrated to stateless Deis and no longer can reproduce Ceph issue.
