### ISSUE TITLE
Better error message when registration is disabled

### ISSUE THREAD

**Issue by ineu** [deis/deis#4371]
When `/deis/controller/registrationMode` is `disabled`, attempt to register returns
```
Registration failed: {"detail":"Authentication credentials were not provided."}
```
This message is misleading. It should explicitly say that registration is disabled.

**Comment by Joshua-Anderson** [comment]
:+1: I agree a better warning would be less confusing.

**Comment by mboersma** [comment]
When I tried this with current master, I see this instead:
```console
$ deisctl config controller get registrationMode
disabled
$ deis register http://deis.local3.deisapp.com --username=test2 --password=asdf1234 --email=just@testing.thanks
Registration failed: Error: 
detail: You do not have permission to perform this action.
403 FORBIDDEN
```
That's a slightly more accurate error message, but ideally Deis would specifically state "registration is disabled" in this case.

**Comment by ineu** [comment]
I tried it on 1.9.1. Yes, 'registration is disabled' would be great.
