### ISSUE TITLE
Deis using existing Kubernetes cluster

### ISSUE THREAD

**Issue by JeanMertz** [deis/deis#4372]
From what I've been able to gather, using Kubernetes as a backend for Deis means that the Deis setup scripts will actually create a Kubernetes cluster to work with.

What about coupling Deis to an existing cluster?

We currently have a k8s cluster for our application needs, but some people (including myself) are interested in improving their deployment/management flow of services by using Deis a management interface in front of the k8s cluster for some of our applications.

Having Deis schedule the services in our existing k8s cluster would be great, having a second k8s to take care of, not so much.

**Comment by krancour** [comment]
With a little effort to customize the `deis-controller`, you _might_ be able to successfully deploy applications to an external k8s cluster.  Among the things that would _not_ work, however, would be logging and routing.

For routing to work, `deis-router` instances need to share an etcd cluster with the k8s cluster so they can discover the service addresses for your pods.  Each `deis-router` instance also needs to be co-located with a `kube-proxy` instance that will route and load balance traffic _from_ that `deis-router` to an application pod.

Deis application logging relies on `deis-logspout` being co-located with your application containers so it can attach to their `STDOUT` and forward each line to the platform's internal log aggregator (i.e. `deis-logger`) or elsewhere (e.g. Papertrail).

All-in-all, you _could_ do it, but in the end, you wouldn't be getting the real Deis experience.  You'd be using it only for deployment, but relying on the services of the k8s cluster you already have in place for things like routing and logging.  While it may technically be doable, it's likely more trouble than it's worth in terms of the complexity that fragmented infrastructure would promote.

**Comment by bacongobbler** [comment]
@krancour is bang-on. It's only a tech preview at the moment, so it's not intended for production use at this time :)

**Comment by krancour** [comment]
I think this has been adequately answered, so I'm closing, but please feel free to re-open if it's not addressed to your satisfaction.
