### ISSUE TITLE
Healthcheck problem

### ISSUE THREAD

**Issue by vesmi** [deis/deis#4377]
My application consists of two parts: web (php) and scheduler (bash script). Health сheck of the second part causes an error because there is no interface, ability to give code 200. Is it possible to more flexibly adjust healthcheck to avoid similar problems?
```bash
2015-08-28T11:55:20UTC deis[api]: failed to connect to container ('Key not found : /deis/services/colibri-api/colibri-api_v11.scheduler.1'); trying again in 1.0 seconds
2015-08-28T11:55:21UTC deis[api]: failed to connect to container ('Key not found : /deis/services/colibri-api/colibri-api_v11.scheduler.1'); trying again in 5.0 seconds
2015-08-28T11:55:26UTC deis[api]: failed to connect to container ('Key not found : /deis/services/colibri-api/colibri-api_v11.scheduler.1'); trying again in 10.0 seconds
2015-08-28T11:55:36UTC deis[api]: failed to connect to container ('Key not found : /deis/services/colibri-api/colibri-api_v11.scheduler.1')
2015-08-28T11:55:41UTC deis[api]: aborting, app containers failed to respond to health check
```
Deis 1.9.1, config: 
HEALTHCHECK_URL="/1.0/service/healthcheck" 
HEALTHCHECK_TIMEOUT=30 
HEALTHCHECK_INITIAL_DELAY=10

Procfile example:
```bash
web: vendor/bin/heroku-php-nginx -C nginx.inc.conf web/
scheduler: while true; do ./yii schedule/run --verbose=0; sleep 3600; done
```

**Comment by bacongobbler** [comment]
Yes. The health check should only apply to web and cmd process types.

**Comment by laurrentt** [comment]
+1

**Comment by rvadim** [comment]
+1

**Comment by vmakhaev** [comment]
Even running web server (which returns 200) in worker process does not work for me.

**Comment by bacongobbler** [comment]
@vmakhaev would you mind checking out #4383? That should fix your issue :)

**Comment by vmakhaev** [comment]
Yes, making healthcheck work only for web processes should solve issue.
I have conceptual question. Could it be useful to have same health check for background processes (running web server inside them)? What are the best practices/recommendations in monitoring background processes?

**Comment by bacongobbler** [comment]
no, I don't think it will be useful. Deis requires that your app only listens on one port due to some limitations in v1 so we can only monitor the process listening on that container's port.

**Comment by vmakhaev** [comment]
Sorry, as background process, I mean process that run in separate container, which is different from web container. Which is configurable with Procfile.
In our case we have two roles in Procfile: 'web' and 'worker'. Web has http server, worker responsible for executing tasks from query. There is no problem to start http server in worker and listen for health check requests same as we can do it in web role, which could be helpful if something bad happened with worker. And in this case deis can restart it. Does it make sense?

**Comment by bacongobbler** [comment]
I think it should be done in some other form. non-web process types are assumed that they will not have a web service running inside those containers, which is how Heroku explains the process type definitions. Introducing some form of supervisor agent for your worker processes to restart them if they become flappy may be best, I think.

**Comment by vmakhaev** [comment]
Could we have such supervisor agent as part of Deis, please?

**Comment by krancour** [comment]
@vmakhaev what you're looking for is probably more closely related to #3699 and #4110

**Comment by vmakhaev** [comment]
@krancour thanks
