### ISSUE TITLE
Issue pulling docker images from local registry.

### ISSUE THREAD

**Issue by SomeoneWeird** [deis/deis#4378]
I have a docker registry set up at `10.10.1.101`, and am trying to deploy the image `example` with the `latest` tag onto a deis cluster.

```
ubuntu@ip-10-10-1-197:~/deis/example$ deis pull 10.10.1.101/example:latest
Creating build... 503 SERVICE UNAVAILABLE
Detail:
GET Image Error (404: {"error": "Tag not found"})
```

I cannot seem to be able to figure out why I'm getting this error, as I'm 100% sure the tag exists in the registry, and I can also manually log into the coreos hosts and do a 'docker pull' and it fetches it fine. I also had to manually install cacert bundle on the coreos hosts - or else docker refuses to pull because of a self signed cert. Is docker used in any of the deis services that would need it installed too?

**Comment by bacongobbler** [comment]
@SomeoneWeird `deisctl journal registry@1` may help debug the issue, though I think this may be related to https://github.com/deis/deis/issues/4089 or https://github.com/deis/deis/issues/3550.

**Comment by SomeoneWeird** [comment]
Hmm, it looks like it's timing out because it's trying to connect to :80 and not :443, is SSL not supported by them yet?

**Comment by SomeoneWeird** [comment]
Reading over the other issues - they seem to be a similar problem. I put in a 80->443 redirect in nginx that is sitting in front of my registry - no dice. Everything is running docker 1.5. 

Strangely, watching the journal logs for `deis-registry`, it seems to be getting 500s from the deis registry?

```
Sep 01 02:03:15 ip-10-21-2-17.ap-southeast-1.compute.internal sh[2647]: 10.21.1.74 - - [01/Sep/2015:02:03:15 +0000] "POST /v1/repositories/example/tags HTTP/1.1" 500 65 "-" "python-requests/2.7.0 CPython/2.7.9 Linux/4.0.1"
```

**Comment by lorieri** [comment]
it happened to me with remote images, maybe because it was already pulled once ?

**Comment by bacongobbler** [comment]
@SomeoneWeird yes, the external registry must allow unauthenticated connections on port 80 in order for `deis pull` to do its magic, unfortunately.

**Comment by lorieri** [comment]
by remote I meant offical docker hub images

**Comment by SomeoneWeird** [comment]
@bacongobbler The registry doesn't have any kind of authentication, it only has SSL running because if it doesn't you need to start all the docker daemons with `--insecure-registry`, as far as I'm aware.
