### ISSUE TITLE
Question about Kubernetes, Deis and etcd

### ISSUE THREAD

**Issue by sitya** [deis/deis#4379]
Sorry if the answer would be trivial...

I was wondering if Deis uses k8s scheduler whether it means that other elements of Deis system read and use `/registry` folder from etcd? For example if I start a pod and service using kubectl will it be pushed through deis-publiser automatically, and will itt be accesible using `deis apps`, will it be connected to `deis-router`? It would make sense when I have to start a more complex pod (eg. it uses nfs storage from outside, which can be handled by kubernetes fine not like deis) but I would like that pod to be part of deis system.

**Comment by bacongobbler** [comment]
I don't think that's something we can reasonably support. `deis apps` comes from the controller and `deis-publisher` looks for a specific regex to publish containers (it's unused with the kubernetes tech preview as far as I'm aware, anyways). However, I think the router would route the container: https://github.com/deis/deis/blob/master/router/rootfs/etc/confd/templates/nginx.conf#L342

**Comment by bacongobbler** [comment]
closing as answered. v2 will be removing etcd so most of the discussion is irrelevant. Most of the configuration is done through annotations on the v2 router. :)
