### ISSUE TITLE
Request feat(controller): Specify custom user in `docker run`

### ISSUE THREAD

**Issue by laurrentt** [deis/deis#4380]
Docker supports specifying a different user than root when using `docker run -u some-user ...`. I think it's a great security feature and I would like to use it in my Deis apps.

**Comment by bacongobbler** [comment]
As far as I'm aware if you add a USER directive to the Dockerfile, `docker run` (and in turn `deis run`) will use that same user. Is there a use case where you'd want to run an operation as someone other than the default user? I'm concerned that if we expose this flag, users would be able to just run `deis run -u root` without any repurcussions that the app developer might've relied on.

**Comment by laurrentt** [comment]
You're totally right :open_mouth: I didn't check well enough before opening this issue. I though the only way to specify a user was by CLI but, as you said, you can specify it directly in the Dockerfile, which solves my problem. Thanks !
