### ISSUE TITLE
Fleet failover fail

### ISSUE THREAD

**Issue by afterthought** [deis/deis#4387]
Hi,

We had an outage over the weekend and I'm trying to figure out root cause. It's a basic cluster setup using the AWS cloudformation still running Deis 1.6.1. Something went awry on one node in the cluster and the memory usage for the docker process was up over 70%. This caused most of the fleet services running on this node to become inactive/dead. I'm not super interested in what caused the memory leak as we'll be upgrading this cluster at some point. However, I am interested to understand the expected fleet behavior. Do we know why the services from this host would not get rescheduled to another host when they become inactive/dead? Is this expected behavior?

Thanks

**Comment by bacongobbler** [comment]
@afterthought no, the idea is that if a node goes down, fleet will recognize that and re-schedule the units to different nodes. If you have logs, I'd see if there's any information at https://github.com/coreos/fleet as it seems like it's in their domain :)

**Comment by afterthought** [comment]
Thanks. Unfortunately I don't have logs now. Does anyone have any ideas that might trigger reproducible type conditions that are similar? The cluster had run for several months without issues, so if there's a leak it won't be back anytime soon. Would stopping the process with systemd be enough maybe?

**Comment by bacongobbler** [comment]
I believe that is intentional by design but I would suggest looking for answers there, yes
