### ISSUE TITLE
Proposal: update etcdctl on all new CoreOS hosts

### ISSUE THREAD

**Issue by krancour** [deis/deis#4388]
Currently, we update etcdctl on CoreOS hosts _if_ one has opted into the graceful shutdown unit.

What if we just update etcdctl on _all_ new CoreOS clusters instead?  This would significantly aid troubleshooting efforts since newer versions expose things like `member list` and `cluster-health`.

This shouldn't break anything.  Any containerized component would continue to use the older etcdctl 0.4.6 to ensure backwards compatibility with older clusters.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to fixing for the LTS release, and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this.
