### ISSUE TITLE
Restrict Router application set

### ISSUE THREAD

**Issue by sstarcher** [deis/deis#4391]
We looking at running internal Deis cluster which contains applications that need to be made publically accessible along with applications which need to be not routable through the router.

I see 3 main solutions to our current setup.
* Run 2 seperate Deis clusters one for the publicly available services and one for the private services
* Modify the Deis router to allow for a router that has a restricted set of applications and run 2 separate routers (Hinted at by #3804)
* Run a proxy in front of the Deis router to filter out incoming requests and limit what is allowed through the outside load balancer

**Comment by bacongobbler** [comment]
So here's my ideas, let me bounce them off you:

 - all containers expose their ports thanks to the `-P` flag
 - all web and cmd process types are added to the router mesh
 - any other process types are not added and are considered standalone (worker) processes. Typically that means these processes will read off a queue, cache etc. and perform work on certain data sets.

What if you made your apps that you wanted unavailable from the router non-web process types? That way you can then tack on your own service that would detect the containers running as a specific process type in the cluster and make them internally available to your cluster via your private router mesh. Would that work? :)

**Comment by sstarcher** [comment]
That could work in certain cases, but I think in our case it would be a little clunky.  One of the use cases we have is we have a web application that web deploy into Deis, and we also create a separate Deis application for each branch of that application.  We would like the branches to not be publically accessible, but would like the master to be public.

I have yet to dig into the Deis Router, but the first thing that popped into my head was to have a config setting (deis config:set private_application=true) on the application that the public router could key off of to restrict which applications would get added into the router.

**Comment by krancour** [comment]
@sstarcher would #4333 help you?

All application access would still flow through the router, but in the case of your internal applications, they could only be accessed by users with designated IPs or IPs in a designated range.

**Comment by sstarcher** [comment]
@krancour I believe so, but let me make sure I'm reading it correctly.
If I set
```deisctl config router set enforceWhitelist=true```
and that would default to locking everything down and nothing would be accessible by default through the router.

If we wanted things open internal to our VPC we could 
```deis config:set -a our-private-app whitelist=10.0.0.0/16'```
If we wanted something opened up publically we could 
```deis config:set -a our-private-app whitelist=0.0.0.0/0'```


Or in-reverse we could allow everything to be public by not setting enforceWhitelist & make things private by doing 
```deis config:set -a our-private-app whitelist=10.0.0.0/16'```

@laurrentt could you confirm that I'm understanding #4333 correctly.

**Comment by laurrentt** [comment]
@sstarcher Yes I think you got it

**Comment by sstarcher** [comment]
#4333  will close my issue
