### ISSUE TITLE
Restore from backup: expected state of services

### ISSUE THREAD

**Issue by afterthought** [deis/deis#4392]
I just restored a backup. Everything worked perfectly. Except when I was done, none of the services are actually scheduled. I am manually having to run ps:scale cmd=0 followed by ps:scale cmd=N. Is this expected?

**Comment by bacongobbler** [comment]
The process for restoring applictions is documented [here](http://docs.deis.io/en/latest/managing_deis/backing_up_data/#finishing-up). Essentially those commands will re-populate the scheduler with the necessary units required to restart the application. Did you follow this process when restoring data and the units never came up?

**Comment by afterthought** [comment]
I followed the instructions to the letter. When I ran deis ps afterward the service processes showed as cmd.1 ... destroyed. Nothing scheduled in fleet. Not a show stopper. I just had to re-scale the apps.

**Comment by LoicMahieu** [comment]
I ran into the same issue. I am using Deis in stateless mode with s3 and rds. Multiple time on DigitalOcean I re-created the cluster with the same data. Everything works perfectly but `deis ps` tells that process are `destroyed`.
The only way I found is to `deis scale cmd=0` and `deis scale cmd=1`... Sounds a bit hacky... Do you recommend another command to force unit to be scheduled ?

**Comment by bacongobbler** [comment]
@LoicMahieu `deis ps:restart`, perhaps?

**Comment by LoicMahieu** [comment]
@bacongobbler Good point. I think I tried the command but I am not sure and anyway I don't have logs etc... I can't replace the situation right now but I will try asap.

**Comment by afterthought** [comment]
I'm 90% positive that was the first thing I tried too. I'll be doing some more restores at some point in the next few weeks.

**Comment by croemmich** [comment]
@bacongobbler deis ps:restart doesn't appear to work if the unit is destroyed.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant so I'm closing this.
