### ISSUE TITLE
Cluster recreation: git push gives weird errors

### ISSUE THREAD

**Issue by ineu** [deis/deis#4393]
Because of my Ceph OSD issues I've recreated cluster from scratch:
- made a backup of database contents
- skipped everything related to Ceph from http://docs.deis.io/en/latest/managing_deis/backing_up_data/ as my RGW didn't work correctly
- deisctl stop platform
- deisctl uninstall platform
- removed all data containers
- deisctl install platform
- deisctl start platform
- restored database backup
- executed http://docs.deis.io/en/latest/managing_deis/backing_up_data/#finishing-up

Everything is up and running, but I cannot really execute `git push`. I receive errors:

```
> $ git push deis HEAD:master
Подсчет объектов: 537, готово.
Delta compression using up to 8 threads.
Сжатие объектов: 100% (280/280), готово.
Запись объектов: 100% (537/537), 75.89 KiB | 0 bytes/s, готово.
Total 537 (delta 263), reused 442 (delta 213)
chown: cannot access ‘/home/git/test.git/build/tmp.pEVJ8klCpJ’: No such file or directory
fatal: Unable to read current working directory: No such file or directory
To ssh://git@deis.staging.cronycle.com:2222/test.git
 ! [remote rejected] HEAD -> master (pre-receive hook declined)
```

and on next push:

```
> $ LANG= git push deis HEAD:master
Counting objects: 537, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (280/280), done.
Writing objects: 100% (537/537), 75.89 KiB | 0 bytes/s, done.
Total 537 (delta 263), reused 442 (delta 213)
-----> Unable to select a buildpack
fatal: Unable to read current working directory: No such file or directory
To ssh://git@deis.staging.cronycle.com:2222/test.git
 ! [remote rejected] HEAD -> master (pre-receive hook declined)
```

And here's error when pushing another project:

```
Total 7860 (delta 5536), reused 7833 (delta 5520)
remote: fatal: unable to open objects/pack/tmp_pack_yP45pg: No such file or directory
fatal: Unable to read current working directory: No such file or directory
error: unpack failed: index-pack abnormal exit
To ssh://git@deis.staging.cronycle.com:2222/engine-staging.git
 ! [remote rejected] HEAD -> master (unpacker error)
```

There are no '*.git' directories created in /home/git as well. How do I debug this thing?
Also, despite I've removed all data containers, after the new installation in the `osd tree` I've seen my old OSD. Where could it persist?

**Comment by ineu** [comment]
Ok, I think I've found the reason. It was /home/git/check-repos which was removing repos immediately after push (or during push)

**Comment by krancour** [comment]
The apps in the `api_app` table are written to etcd like so:

* `/deis/services/<app name>` directory is created when an app is _created_ (i.e. via `deis create`)
* `deis-publisher` sets `/deis/services/<app name>/<container name> = <host>:<port>` _with a TTL_

It's hard for me to say what might have happened to you.  Can you share more details about your sequence of events-- especially whatever steps you might have taken in regard to the applications themselves in preparation for or after the rebuild?  Did you scale apps down, destroy, re-create, etcd.?

**Comment by lorieri** [comment]
Hi, @rochacon and I are investigating it, he found that is not "git gc" is not needed.
The /bin/cleanup watches etcd and deletes the git repositories before git gc runs on that line:
https://github.com/deis/deis/blob/v1.9.1/builder/rootfs/etc/confd/templates/builder#L175-L176

cleanup:
https://github.com/deis/deis/blob/v1.9.1/builder/rootfs/etc/confd/templates/check-repos#L12

Looks like the builder was rebuilt :smile: in Go, so probably we will not have a fix for it.

My suggestion: [remove those lines](https://github.com/deis/deis/blob/v1.9.1/builder/rootfs/etc/confd/templates/builder#L175-L176) from the builder, push it somewhere then:
```
$ deisctl config builder set image=myaccount/myimage:latest
```

Then wait for the new release.

**Comment by carmstrong** [comment]
> Looks like the builder was rebuilt  in Go, so probably we will not have a fix for it.

Actually, it looks like that file exists in the new builder unchanged: https://github.com/deis/deis/blob/master/builder/rootfs/etc/confd/templates/builder#L174-L175

@lorieri If you want to PR the change to that file, we can test/merge it. :+1:

**Comment by lorieri** [comment]
@rochacon made it :) PR please :smile:

**Comment by ineu** [comment]
> /deis/services/<app name> directory is created when an app is created (i.e. via deis create)

I understand this, but I'm talking about restoring database backup, not about normal work with Deis. The problem is that http://docs.deis.io/en/latest/managing_deis/backing_up_data/#finishing-up restored **most** applications, but not all. And, looking at database contents, I don't see much difference between apps that were restored and those that were not. 
Could it be possible that all applications were restored, but something later removed entries from /deis/services?

**Comment by bacongobbler** [comment]
Publisher sets a time-to-live on all keys set, so if the containers are not up (or publisher is not running), the keys will eventually expire. Does `deis ps` show any containers up?

**Comment by ineu** [comment]
@bacongobbler Yes, this looks like the reason

**Comment by ineu** [comment]
I think #4403 might also be the reason.
