### ISSUE TITLE
deis apps:destroy isn't fully removing contents from etcd

### ISSUE THREAD

**Issue by sgoings** [deis/deis#4396]
When an integration test failed mid-run, I tried restarting the test and found that even though `deis apps` reported an empty list:

```
~/code/rigger :  deis apps
=== Apps
```

there was still application specific data in etcd:

```
core@ip-xxxxx ~ $ etcdctl ls /deis/services/
/deis/services/testing
/deis/services/configsample
/deis/services/buildsample
```

And directories weren't necessarily empty either:

```
core@ip-xxxxx ~ $ etcdctl ls /deis/services/testing
/deis/services/testing/testing_v2.web.1
core@ip-xxxxx ~ $ etcdctl ls /deis/services/configsample
/deis/services/configsample/configsample_v7.web.1
core@ip-xxxxx ~ $ etcdctl ls /deis/services/buildsample
```

**Comment by schemacs** [comment]
Failed to `push deis master` after deis apps:create, and delete the git manually:
$ vagrant ssh deis-01 -- -A
$ nse deis-builder
$ rm -rf home/git/zircon-tinkerer
still found the app by `deis apps:list`

**Comment by bacongobbler** [comment]
closing this as it's not a serious issue, and we've removed reliance on etcd in deis v2.
