### ISSUE TITLE
Cluster restore does not populate etcd keys

### ISSUE THREAD

**Issue by gabrtv** [deis/deis#4398]
When trying to restore a v1.9.1 cluster (Ceph-less), the instructions in http://docs.deis.io/en/latest/managing_deis/backing_up_data/#finishing-up do not successfully populate etcd keys.  I had to recreate domains manually, for example.

We should strongly consider adding test coverage for backup/restore in the event of catastrophic failure.

**Comment by carmstrong** [comment]
Addressed by https://github.com/deis/deis/pull/4394

**Comment by gabrtv** [comment]
You guys think of everything, don't you :tongue:
