### ISSUE TITLE
Backup/restore documentation is not precise

### ISSUE THREAD

**Issue by ineu** [deis/deis#4403]
Section http://docs.deis.io/en/latest/managing_deis/backing_up_data/#finishing-up doesn't really work for me because of `kwargs['created']` check here: https://github.com/deis/deis/blob/master/controller/api/models.py#L1192 and, probably, all other methods. So `save()` method in the link above doesn't really do anything on restored database, as `kwargs['created]` is False.

**Comment by carmstrong** [comment]
@ineu I think #4394 may address this?

**Comment by bacongobbler** [comment]
yes, that would address @ineu's problems.

**Comment by ineu** [comment]
Yes, it does. Thank you.
