### ISSUE TITLE
Proposal feat(controller): add kubernetes response in case of errors

### ISSUE THREAD

**Issue by aledbf** [deis/deis#4406]
Scaling one application I see this:
```
Sep 03 21:42:36 backend-2 sh[8092]: ERROR app-server-demo: app-server-demo_v135.cron (scale): app-server-demo-v135-cron (create): 'status'
```

Is possible to add the returned response from the api-server?

**Comment by bacongobbler** [comment]
I believe this is resolved in v2. Would you mind opening a new issue on https://github.com/deis/workflow if this error still happens to occur for you? Thanks! <3
