### ISSUE TITLE
All database contents is lost when database is rescheduled to another machine

### ISSUE THREAD

**Issue by ineu** [deis/deis#4421]
I've just restarted node running deis-database, it was rescheduled to another machine, together with deis-store-gateway. When container started, it was not restored from the backup, but instead initialized from scratch and immediately performed initial backup though there were proper backups before.

`deis-database` logs on the new machine: https://gist.github.com/ineu/dcd1a78c3d2e93036d0b

Then I stopped deis-database, removed deis-database-data container and started it again. Logs: https://gist.github.com/ineu/8685e2b352a8d53bd603

As you can see, the second time it performed `fetch-backup`, but on the first run it didn't.

All backups present in Ceph:
```
bash-4.3# envdir /etc/wal-e.d/env wal-e backup-list
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-list".
        STRUCTURED: time=2015-09-07T07:40:00.110981-00 pid=1374
name	last_modified	expanded_size_bytes	wal_segment_backup_start	wal_segment_offset_backup_start	wal_segment_backup_stop	wal_segment_offset_backup_stop
base_000000010000000000000002_00000040	2015-09-07T07:02:19.000Z		000000010000000000000002	00000040		
base_000000010000000200000082_00000040	2015-09-03T17:52:11.000Z		000000010000000200000082	00000040		
base_0000000100000002000000A8_00000040	2015-09-03T20:52:24.000Z		0000000100000002000000A8	00000040		
base_0000000100000002000000CF_00000040	2015-09-03T23:52:46.000Z		0000000100000002000000CF	00000040		
base_0000000100000002000000F4_00000040	2015-09-04T02:53:09.000Z		0000000100000002000000F4	00000040		
base_000000010000000300000019_00000040	2015-09-04T05:53:43.000Z		000000010000000300000019	00000040	
```

**Comment by bacongobbler** [comment]
I've seen this happen a few times as well. `deisctl restart database` seems to do the trick, though we haven't been able to nail down how this occurs, I believe.

**Comment by carmstrong** [comment]
Wondering if this is #4402.

**Comment by ineu** [comment]
It's possible, as I've seen initId == 'none' in the logs despite it was present in etcd.
But I more worry about 'initial backup' logic. When it creates DB from scratch, it makes base backup which is newer than others. As far as I understand, `backup-fetch LATEST` on the next restart/reschedule will fetch this new backup of almost empty database.
It would be better to check if base backups exist instead of simply relying on initId match.

**Comment by bacongobbler** [comment]
okay, I think this sounds like this is closed by #4402. Would you mind testing master to see that this fixed your issue?

**Comment by ineu** [comment]
I'm using external DB at the moment. Going to upgrade to 1.10 next days, it could be a good chance to test it.
What do you think about logic modifications to check for existing base backups? To me it looks unlikely that anyone would want to have an empty database if there's base backup existing. Even if it might be old, it's still better than DB with no data in it.

**Comment by bacongobbler** [comment]
I don't think I quite follow. If a base backup exists, then the database will use it, replaying any logs [that may be missing](https://github.com/deis/deis/blob/master/database/tests/recovery_test.go#L158-L166). The only time a recovery will occur is on a new host which is not up to date (i.e. no data existing in deis-database-data). Is that what you're asking?

**Comment by ineu** [comment]
@bacongobbler Yes, you are right, there is a check for backups on https://github.com/deis/deis/blob/master/database/bin/boot#L78
But in this case I don't understand where https://gist.github.com/ineu/dcd1a78c3d2e93036d0b#file-gistfile1-txt-L49 comes from. It didn't find backups though backups were present, and it created initial backup of empty database, thus making `wal-e backup-fetch LATEST` fetching wrong base backup. That's what happened:

```
bash-4.3# envdir /etc/wal-e.d/env wal-e backup-list
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-list".
        STRUCTURED: time=2015-09-07T07:40:00.110981-00 pid=1374
name	last_modified	expanded_size_bytes	wal_segment_backup_start	wal_segment_offset_backup_start	wal_segment_backup_stop	wal_segment_offset_backup_stop
base_000000010000000000000002_00000040	2015-09-07T07:02:19.000Z		000000010000000000000002	00000040		
base_000000010000000200000082_00000040	2015-09-03T17:52:11.000Z		000000010000000200000082	00000040		
base_0000000100000002000000A8_00000040	2015-09-03T20:52:24.000Z		0000000100000002000000A8	00000040		
base_0000000100000002000000CF_00000040	2015-09-03T23:52:46.000Z		0000000100000002000000CF	00000040		
base_0000000100000002000000F4_00000040	2015-09-04T02:53:09.000Z		0000000100000002000000F4	00000040		
base_000000010000000300000019_00000040	2015-09-04T05:53:43.000Z		000000010000000300000019	00000040	
```

As you can see, it didn't find backups from September 3 and 4 and created new initial backup (of empty database) on September 7.

How could it find no existing backups? According to https://gist.github.com/ineu/dcd1a78c3d2e93036d0b#file-gistfile1-txt-L5 gateway was not available when database started, but is it possible that is was not really ready by the moment wal-e tried to list backups? Even if so, why didn't wal-e raise some kind of exception?

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776), and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this.
