### ISSUE TITLE
Support for self-signed certificates

### ISSUE THREAD

**Issue by Footjy** [deis/deis#4422]
Hi, I could not find a way for deis to support self-signed certificates in a safe way. Switching the flag "verify ssl" to false does not seem safe to me, though it may be enough for development. In case some teems would like to be using self-signed certificates for a longer time, there should be a way to tell your deis client to accept some specific certificates.

Something like requests.post(url, data=data, verify='/path/to/public_key.pem') for the python request library.

It could be as simple as: 
deis register "https://.example.com" -ca-bundle=path-to-ca-bundle
or:
deis register "https://.example.com" -ca-bundle=path-to-cert

Or any other solution that could prevent from buying a 100$ wildcard certificate and still be safe in development.

Just let me know if I missed an existing way to do that.

**Comment by Blystad** [comment]
Can't you just add your ca bundle to your system keystore?

**Comment by Footjy** [comment]
I'm on Mac OS, adding the certificate to keychain does not seem to work, though it is properly added as the warning is removed from the browser when requesting the url of the platform.

**Comment by Blystad** [comment]
Try something outlined in this article, perhaps:

http://www.robpeck.com/2010/10/google-chrome-mac-os-x-and-self-signed-ssl-certificates/

Could be the Go / Python client handles certificates a bit different then your browser.

E.g. try this:

```
sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain site.crt
```

**Comment by Footjy** [comment]
This does not change any thing. I still get the same bad handshake error when trying to login to deis controller.

I use whatever python library deis is using. Tried with version 1.8 and 1.9.

**Comment by bacongobbler** [comment]
We have since re-written the client in Go which this should be fixed now. If you're having issues working with the client with self-signed certificates on the Go-based client then please open another issue. Thanks!
