### ISSUE TITLE
Use "release candidate" builds

### ISSUE THREAD

**Issue by mboersma** [deis/deis#4429]
For mostly historical reasons, the Deis release process begins with an intended final build (v1.11.0, let's say) rather than a release candidate build (v1.11.0-rc1 perhaps). This build may be updated inline once or more during final testing as showstopper bugs are found.

Instead, the Deis project could produce more traditional release candidate builds and make them generally available, which would allow the community to help with testing as well. A smoke test on multiple providers must pass cleanly before the release candidate is publicized for testing.

Caveats here are:
- Need to ensure that upgrade testing will work smoothly with v1.11.0-rc1 - type tags
- The project tags are clean and useful now--can we avoid pushing a `git` tag of "v1.11.0-rc1", or can we delete it afterward safely?
- `deisctl` is intimately tied to git tags and needs a custom -rc1 release
- versions are splattered throughout the codebase so each release candidate will require `bumpver` work
- ideally we just re-tag Docker components, not rebuild, since `docker build` doesn't allow us precise control over the bits

**Comment by mboersma** [comment]
Here are some items agreed upon, the last one being my action item to try this proposal out this week:
- use branches instead of tags for -rc1 in git (need to test that `deisctl refresh-units` is ok with this)
- ensure testers set version to -rc1 with deisctl
- ensure testers use the -rc1 arg with "deisctl refresh-units"
- set version resources to intended release in codebase, so no rebuild will be needed
- investigate whether the DEIS_RELEASE env var is really required now
- announce release candidate build in IRC
- dry run of a release candidate build, then write up instructions

**Comment by mboersma** [comment]
We have begun using release candidate builds for testing Deis, but the last three bullet points are still in progress:
- investigate whether the DEIS_RELEASE env var is really required now
- announce release candidate build in IRC
- dry run of a release candidate build, then write up instructions

**Comment by bacongobbler** [comment]
are we able to close this now? :)
