### ISSUE TITLE
Need long-running cluster test

### ISSUE THREAD

**Issue by mboersma** [deis/deis#4430]
To assess platform stability, we need to stand up a Deis cluster and hand it off for multi-day testing, interactive or automated. Most testing currently centers on provisioning and accomplishing the basic workflow without incident, but there could be issues that are missed that only appear after prolonged activity or heavy load.

**Comment by carmstrong** [comment]
I think this cluster should resemble a production-grade cluster as closely as possible. Namely, it should:

* Be on AWS
* Be 5 node of an adequate size (large or xlarge)
* Use split control, data, and etcd planes
* Enable the optional graceful shutdown script @iancoffey authored

**Comment by carmstrong** [comment]
We should also maintain a separate cluster that uses a stateless control plane.

**Comment by iancoffey** [comment]
@carmstrong is there specific AWS account this should be under?

**Comment by carmstrong** [comment]
> is there specific AWS account this should be under?

Nope. We each have our own AWS account under consolidated billing that we use for testing. We can choose any account and share credentials for it.

**Comment by jackfrancis** [comment]
I'm reading here that we want two long-running clusters.

- 1 5 node large AWS cluster with split plane configuration, w/ optional graceful shutdown script enabled
- 1 5 node large AWS cluster with stateless control plane

**Comment by jackfrancis** [comment]
Stateless control plane cluster is available at *.canary-stateless.deis.works.

I'll work with @mboersma and @carmstrong to hand off documentation of the environment.

**Comment by iancoffey** [comment]
@jackfrancis Looks like the graceful shutdown script needs enabling, otherwise  the config looks :+1:

**Comment by jackfrancis** [comment]
Looks like the graceful shutdown feature doesn't apply to a stateless control plane cluster because it doesn't use ceph.

**Comment by sstarcher** [comment]
@jackfrancis graceful shutdown also removes the node from ETCD if this is not done it will cause issues with ETCD #4539

**Comment by jgmize** [comment]
I'd love to see continuous deployments of example apps to the long running-cluster(s?), with validation of healthchecks ensuring zero-downtime deploys to avoid issues like #4414.

**Comment by gabrtv** [comment]
:+1:

**Comment by mboersma** [comment]
Similar efforts for Deis v2 are going to see fruition, but this isn't part of the game plan for v1 now.
