### ISSUE TITLE
Instructions on creating external database from scratch

### ISSUE THREAD

**Issue by ineu** [deis/deis#4434]
I successfully moved database from deis-database to external postgres as specified in http://docs.deis.io/en/latest/managing_deis/running-deis-without-ceph/. The document is fine if you have existing database that you can dump/restore. But what if you want to create cluster from scratch? I believe we need some kind of documentation on creating initial schema in external database before installing stateless Deis.

**Comment by nathansamson** [comment]
Isn't this automatic on first startup of the controller?

This should probably be highlighted, but it is not that the user needs to do anythinh

**Comment by Blystad** [comment]
In the [configure database settings](http://docs.deis.io/en/latest/managing_deis/running-deis-without-ceph/#configure-database-settings) step you specify a database `host`, `name`, `user` and `password`.

As long as you have this already existing, then the controller will take care of the rest.

If you have a database, and you would like to, for example, share it between your applications and Deis, then you can do something like this:

```
CREATE DATABASE deis;
CREATE USER deis WITH password 'deisisawesome';
GRANT ALL PRIVILEGES ON DATABASE deis TO deis;
```

:smiley:

**Comment by ineu** [comment]
So if controller sees empty database, it populates it automatically? It sounds great. Can we still have one line of text describing it in http://docs.deis.io/en/latest/managing_deis/running-deis-without-ceph/ ?

**Comment by bacongobbler** [comment]
Yes, running [South migrations](https://github.com/deis/deis/blob/master/controller/bin/boot#L84) will create the database with the correct schema at boot.

**Comment by krancour** [comment]
@ineu it'd be a welcome contribution if you want to add it to the docs.

**Comment by mboersma** [comment]
There are also Django management commands that will emit all the DDL needed to create the schema, if you for some reason need to create the PostgreSQL schema separately: `./manage.py sqldump api`

**Comment by bacongobbler** [comment]
No documentation is necessary. By pointing your database to the RDS instance, the controller will populate the database with the schema. Data migration won't occur from the old database. You will have to migrate the old data to the new instance by following http://docs.deis.io/en/latest/managing_deis/backing_up_data/.
