### ISSUE TITLE
Stateless install: recommended RDS settings for database?

### ISSUE THREAD

**Issue by olalonde** [deis/deis#4443]
Is there a recommended storage size/postgresql version/instance class for the RDS database in stateless deployment? What exactly is saved in the database? Just user/app metadata?

http://docs.deis.io/en/latest/managing_deis/running-deis-without-ceph/#configure-database-settings

**Comment by bacongobbler** [comment]
In https://github.com/deis/deis/issues/4297 users have tried t2.micro instances without success due to too many open connections which the tiny instance cannot handle. The main limiter with RDS is the default connection pool size. I'd try m3.medium at the very least and see how that goes.

**Comment by olalonde** [comment]
Thanks that's what I went with actually. Any recommendation on database storage size?

**Comment by aledbf** [comment]
@olande you can change that value.

By default is `DBInstanceClassMemory/31457280` (26 connections in t2.micro)
You can get the current limit running `select * from pg_settings where name='max_connections';`

To do that you need a custom `Parameter Groups` changing `max_connections`

You can get information about the open connections with `SELECT * FROM pg_stat_activity;`

(I'm running a t2.micro instance with 64 connections without problems)

**Comment by olalonde** [comment]
@aledbf wait I'm confused... do you mean there is already an official aws ceph-less deployment script? My question was how many GB I should chose for my database.

**Comment by aledbf** [comment]
> do you mean there is already an official aws ceph-less deployment script? 

Sorry about that. What I mentioned is related just to Amazon RDS for Postgres.
About the size, is not possible to choose less than 5GB.

In my case 180 apps is using less than 20MB (you can check yours with `select pg_database_size('deis');`)

**Comment by olalonde** [comment]
Oh ok, got it.

**Comment by bacongobbler** [comment]
Is there any other questions you have or anything actionable here that we should add to the documentation? I guess a nudge to recommend an m3.medium instance and increase the max connections to deis-database's value should suffice.

**Comment by olalonde** [comment]
Yes, also maybe recommend a default database size (5 gb). The best of course would have to have a dedicated aws deploy script for stateless setups.

**Comment by mboersma** [comment]
We should settle on a default recommended size and add that to the stateless docs.

**Comment by nathansamson** [comment]
Would reducing the number of controller workers help to reduce the number of connections (and as a result make it work on a tiny instance)?

In a scenario with a smaller cluster (2-3 operators) you probably won't have too many queries to your controller anyway and so 5 DB connections is probably more than enough...

**Comment by bacongobbler** [comment]
@nathansamson are you able to confirm that with `deisctl config controller set workers=2` and a t1.micro instance? I could add that into the documentation for users who want to tweak with the settings, but I still think that the generic recommendations should still recommend an m3.medium instance for out-of-the-box installations.

**Comment by nathansamson** [comment]
@bacongobbler Sorry no, not running my database on RDS...

But even the tiniest of databases should be able to handle 2 connections I would say.

But I agree, better to confirm this before advicing this....

**Comment by bacongobbler** [comment]
sounds good. I filed #4989 for now but if you have any improvements then please feel free to add to them either in the PR or as a followup.
