### ISSUE TITLE
make deis command notations match

### ISSUE THREAD

**Issue by jchauncey** [deis/deis#4451]
You call `deis config:unset` but then you call `deisctl config <target> rm`

It would be nice if these matched as to avoid confusion

**Comment by bacongobbler** [comment]
I think the main problem here is the `<target>`, which isn't required in the deis client. `deisctl config:set controller webEnabled=true` still isn't a perfect match. Would that be a happy medium?

We'd probably have to introduce `config:set <target>` and `config:unset <target>` as aliases to `config <target> set` so it's backwards compatible.

**Comment by jchauncey** [comment]
Well I was trying to point out the `unset` vs `rm` part of the command more than anything. but making the subcommand notation match would be nice as well. 

I think `config:set <target>` for `deisctl` would be nice

**Comment by bacongobbler** [comment]
deisctl is going away in Deis v2 and I don't think we will be able to get to this for the LTS release so I'm going to go ahead and close this. Thank you for the report though!
