### ISSUE TITLE
deisctl journal help menu does not display options

### ISSUE THREAD

**Issue by jchauncey** [deis/deis#4452]
```
deisctl help journal
Prints log output for the specified components.

Usage:
  deisctl journal [<target>...] [options]
```

**Comment by bacongobbler** [comment]
I think the options list is misleading, as there is no options available :)

**Comment by jchauncey** [comment]
would be nice if `journal` worked like deis logs and showed you the output of each component colorized.

so doing `deisctl journal router` would tail the log output of each router. Right now it seems that doing `ctrl+c` stops the tail from 1 instance and brings up the next.

**Comment by jchauncey** [comment]
Having consistency between the two cli's would be really nice and eases the learning curve.
