### ISSUE TITLE
deisctl install platform command should suggest deisctl refresh-units on appropriate error conditions

### ISSUE THREAD

**Issue by jackfrancis** [deis/deis#4454]
It seems that my deisctl install didn't properly setup local unit files, and as a result when I ran deisctl install platform on a new deis cluster I got the following errors:

```
$ deisctl install platform
● ▴ ■
■ ● ▴ Installing Deis...
▴ ■ ●
Storage subsystem...
Error creating: Could not find unit template for store-daemon
Logging subsystem...
Error creating: Could not find unit template for logger
Control plane...
Error creating: Could not find unit template for database
Data plane...
Error creating: Could not find unit template for publisher
Router mesh...
Error creating: Could not find unit template for router
Done.

Please run `deisctl start platform` to boot up Deis.
```

Either one of the following approaches would improve the user experience:

- automatically block and run ```refresh-units``` in the background if a particular running ```deisctl``` feature failes because it can't find the unit files
- provide an error message suggesting that the user try a ```deisctl refresh-units``` if the reason for an error is an inability to locate the unit files

**Comment by chiefy** [comment]
:+1: deis n00b here, setting up on Vagrant and just ran into this. `refresh-units` seems to fix it

**Comment by bacongobbler** [comment]
deisctl is going away in Deis v2 and I don't think we will be able to get to this for the LTS release so I'm going to go ahead and close this. Thank you for the report though!
