### ISSUE TITLE
Creating an app when deis remote already exists 

### ISSUE THREAD

**Issue by michelleN** [deis/deis#4455]
'deis create' when a deis remote already exists bubbles up the git error that says the remote called deis already exists. 
It'd be nice to have an more clear error/warning like “Existing deis remote already exists. The app was created, but a git remote couldn’t be created. Remove the git remote and add the new one with <command>"

**Comment by carmstrong** [comment]
:+1:

**Comment by bacongobbler** [comment]
:+1: good proposal! Should make it more clear how the user should respond to this error.
