### ISSUE TITLE
HA PostgreSQL in K8S

### ISSUE THREAD

**Issue by technosophos** [deis/deis#4467]
Deis v2 will continue to use PostgreSQL. However, we want an HA version of Postgres with failover support, fault tolerance, and easy recovery.

Recovery data (e.g. WAL logs) should be stored in object storage (Ceph, Swift, S3, etc.)

We should run at least one master node, and at least one minion node, with dynamic failover.

**Comment by mboersma** [comment]
See https://github.com/deis/postgres.
