### ISSUE TITLE
Etcd staged startup

### ISSUE THREAD

**Issue by technosophos** [deis/deis#4473]
With etcd running inside of Kubernetes, we need etcd to be fault resilient and able to move from one host node to another.

To accomplish this:

- Discovery needs to be well done. Right now, the plan is to use an internal discovery service
- When pods come online, they need to first check to make sure that the old version of that pod is not still joined to the cluster. If it is, they need to remove and rejoin in order to get data.
- We need to check for race conditions in rapid restarts or in bringing a new pod online at the same time that an old pod is recovering. I believe the discovery service will handle most of this for us.

**Comment by aledbf** [comment]
@technosophos what's the purpose of etcd? I mean, why not use the api provided by kubernetes and remove etcd from the equation?

**Comment by technosophos** [comment]
What API is that? I am working to push a lot into secrets storage, and some we could move to annotations. But our use cases for etcd often require quite a bit of writing. Those APIs aren't good for write-heavy apps.

I'm trying very hard to not use "private" kube APIs, and to treat Kubernetes as a platform upon which Deis runs (rather than treat Deis as an extension of Kubernetes). But I would be open to other ideas.

**Comment by aledbf** [comment]
@technosophos this https://github.com/kubernetes/kubernetes/blob/master/docs/design/extending-api.md 

> But our use cases for etcd often require quite a bit of writing.

Which ones? 
Are you thinking in deis-publisher? If that's the case I think it could be removed because that functionality is provided by kube-proxy

**Comment by mboersma** [comment]
Realized in https://github.com/deis/etcd.
