### ISSUE TITLE
Go 1.5 Vendoring

### ISSUE THREAD

**Issue by technosophos** [deis/deis#4476]
We need to switch Deis to use GO15VENDOREXPERIMENT while we are in the development cycle. The Go developers have already committed to carrying this on into Go 1.6 (where it will be the default).

Because of this, we should also modify Makefiles to stop using godep.

**Comment by bacongobbler** [comment]
this has been done for 2.0 but we should also take a look at the makefiles for v1.

**Comment by bacongobbler** [comment]
closing as a wontfix for v1 as stated in https://github.com/deis/deis/pull/4864#issuecomment-175171993. We're doing this in v2 so I think that's our resolution for this.
