### ISSUE TITLE
Deny access to a configurable list of paths applicable for all apps.

### ISSUE THREAD

**Issue by kalbasit** [deis/deis#4477]
I have a use case where, for security reasons, I want to deny access to specific paths for all apps. I propose going as simple as possible for this (list of paths separated by a comma in etcd + range {location} in nginx)

**Comment by krancour** [comment]
The knowledge that certain application URLs are forbidden seems more of an application concern than a platform concern.

**Comment by kalbasit** [comment]
that's why my PR provides both. My use case is platform-wide but you can still do that per app.

**Comment by krancour** [comment]
I didn't mean to say that Deis should optionally be able to handle it at a per-application level.  I meant to say that I have my doubts that this should be Deis' responsibility at all.

**Comment by kalbasit** [comment]
Oh I see what you mean. It's definitely a question, however, most companies implement some sort of path for monitoring and usually they'd like it closed. @bacongobbler thoughts?

**Comment by mboersma** [comment]
Monsieur le Mangeur du Bacon is on a well-deserved vacation for a few more days. I admit I'm also on the fence as to whether or not this is something apps should handle themselves, versus Deis doing it for them. `deis config:set monitoring=false` could be nice and tidy and app-specific. I'd like to hear what others think about this proposal too.

**Comment by krancour** [comment]
> most companies implement some sort of path for monitoring and usually they'd like it closed

If that's the use case that motivated this, I have a further thought...  Restricting access to a monitoring URL isn't really about denying _all_ access to that URL.  (Which is what I mistakenly though you wanted initially.)  It's about about _authorizing_ access to the URL.  Perhaps certain authenticated users can access it, or more likely, agents in a certain IP range can access it.

Stepping back and recognizing that this is an authorization problem, I'm inclined to say that such problems are, perhaps, most aptly suited for an application's security framework.

**Comment by kalbasit** [comment]
The thing is, when you want to monitor an app, you want to monitor all of the running containers rather than doing so through the deis-router. So my monitoring platform run inside of the platform and uses etcd to find the containers to monitor them but these paths are not to be accessed through the router.

**Comment by kalbasit** [comment]
closing this. See discussion on #4484
