### ISSUE TITLE
In-cluster testing with Portunes

### ISSUE THREAD

**Issue by technosophos** [deis/deis#4478]
We are looking at building an in-cluster testing service called Portunes that can run tests against Deis clusters similarly to the way Chaos Monkey runs in Netflix (though perhaps not as destructively).

This can be used for integration and regression tests, smoke tests, monitoring, metrics, and so on.

**Comment by bacongobbler** [comment]
@technosophos is this still relevant or is this what spawned https://github.com/deis/monitor?

**Comment by bacongobbler** [comment]
closing as https://github.com/deis/workflow-e2e runs inside (or outside) a kubernetes cluster.
