### ISSUE TITLE
Healthz endpoints for Deis components

### ISSUE THREAD

**Issue by technosophos** [deis/deis#4482]
All Deis components should have Kubernetes health check endpoints.

**Comment by mboersma** [comment]
See also #4484.

**Comment by bacongobbler** [comment]
Kubernetes also allows exec checks as well such as running something like `cat /tmp/myprocess.pid` inside the container. Would it be suffice to say that we just want all components to have some form of way to communicate to kubernetes that it's unhealthy, or is this for a metrics/monitoring system?

**Comment by bacongobbler** [comment]
see https://github.com/deis/workflow/pull/288 https://github.com/deis/builder/issues/92 and other projects to follow progress. Closing!
