### ISSUE TITLE
Router: Implement routing into Kubernetes

### ISSUE THREAD

**Issue by technosophos** [deis/deis#4489]
There are several approaches for routing to services inside of Kubernetes. It is likely that at least one will be merged into k8s 1.1. We should investigate whether we will use that (probably haproxy based), use another, or write our own.

At one point, @aledbf did one that had some huge advantages. We should revisit whether we can run that one without requiring us to patch Kubernetes.

**Comment by aledbf** [comment]
@technosophos  this is what I am using in production https://github.com/aledbf/kube-haproxy-router
It doesn't support SSL (but is easy to add)

The downside of that change is that all the customization that is possible to achieve now with nginx it will be removed or not compatible with deis 1.X

There is an alternative to such radical change if this is merged https://github.com/openresty/lua-upstream-nginx-module/pull/13 [maybe in a month](https://github.com/openresty/lua-upstream-nginx-module/pull/13#issuecomment-131028493). It will be possible to not restart/reload nginx for operations related with upstreams: add_server(), add_peer(), remove_server(), remove_peer()

So with that PR + something similar to this https://github.com/kelseyhightower/motorboat is posible to provide a transparent upgrade path. At the same time is possible to remove the direct access to `etcd` and the need for `deis-publisher` to publish applications in the cluster.

**Comment by bacongobbler** [comment]
done, https://github.com/deis/router is now a thing
