### ISSUE TITLE
Builder: Make git sha hash available during build

### ISSUE THREAD

**Issue by olalonde** [deis/deis#4491]
Heroku calls it `SOURCE_VERSION` (https://devcenter.heroku.com/changelog-items/630). This would be helpful for things like cache invalidation and some projects (e.g. https://github.com/drone/drone/blob/master/Makefile#L1) require access to the git hash during build phase.

**Comment by olalonde** [comment]
Oh, it seems it's already available as `GIT_SHA` (https://github.com/deis/deis/pull/2089). Maybe add it to documentation? I don't recall reading about that.

**Comment by mboersma** [comment]
Good point--I don't think this is documented explicitly. We would love a PR that adds this--maybe to the bottom of http://docs.deis.io/en/latest/using_deis/deploy-application/? I'm having a hard time finding a more appropriate location in the docs.

**Comment by olalonde** [comment]
Wouldn't http://docs.deis.io/en/latest/using_deis/using-buildpacks/ be more appropriate since the `GIT_SHA` is not available for Dockerfile/docker pull deploys (afaik)?

**Comment by olalonde** [comment]
Oh, looks like I was mistaken. The GIT_SHA environment variable is added to the app container but is not available during the actual build. Would it be possible to make it available during build phase?

**Comment by technosophos** [comment]
Seems like we ought to be able to do that by adding an `-e SOURCE_VERSION=$GIT_SHA` right here:
https://github.com/deis/deis/blob/master/builder/rootfs/etc/confd/templates/builder#L98

**Comment by mboersma** [comment]
Closed by #4654.
