### ISSUE TITLE
Platform SSL certificate alongside application certificate

### ISSUE THREAD

**Issue by msull92** [deis/deis#4498]
I have a platform level ssl cert installed and is working perfectly, but when I try to add an application cert for the production urls it doesn't seem to serve it.

For the platform we use a ".us" domain and then for production applications I am attempting to map them to their pretty ".com" records and then apply a "*.example.com" certificate for applications on the ".com". Currently when I try to visit "api.example.com" it is recognizing the "api-production.example.us" ssl cert rather than the new one. Am I doing something wrong?

**Comment by msull92** [comment]
I'm not sure if this is related to my other issue #4487 or not.

**Comment by niels** [comment]
As per #4501, it simply isn't possible to use platform (i.e. router) and application certificates alongside one another. If the router is configured to use HTTPS, that certificate will override any application-specific certificates.

**Comment by krancour** [comment]
Did you also add "api.example.com" as a custom domain for the app in question?  You need to.  That affects the routing, while adding the cert only adds SSL to the custom domain.  If you have not added a custom domain, the net effect of what you have done is zero.  Try:

```
$ deis domains:add api.example.com
```

**Comment by afterthought** [comment]
I was just setting up a new platform and some sites and tripped over this. I must have already had this problem and dealt with it before, because I have an older platform setup that I referenced which reminded me of my workaround.

What doesn't work for me is:

    certs:add cert key --common-name *.mydomain.com

But what does work for me is:

    certs:add cert key --common-name app1.mydomain.com
    certs:add cert key --common-name app2.mydomain.com

I remember reading through the code last time to figure this out. I didn't report it at the time, so maybe it was intended behavior?

**Comment by bacongobbler** [comment]
Yes that's intended behaviour. We don't have a way to add a wildcard app certificate and attach it to every application under that umbrella. For now the latter workflow is the recommended way to attach a wildcard certificate to an app.

**Comment by niels** [comment]
Note that you can also add the same certificate for multiple domains in one go by supplying the `--subject-alt-names` option. E.g.:

```bash
deis certs:add $CERT_PATH $KEY_PATH --subject-alt-names domain1.com,domain2.com,sub.domain2.com
```

**Comment by krancour** [comment]
@msull92, are you all set?

**Comment by msull92** [comment]
@krancour @niels @bacongobbler Ahhh. This was super helpful thanks! My company ended up just buying some cheap $10 certs for each one for the time being because I couldn't find this in the documentation. Maybe make it easier to find or maybe I'm just completely blind. ;) Thanks!
