### ISSUE TITLE
Jenkins tool for notifying about merge conflicts

### ISSUE THREAD

**Issue by technosophos** [deis/deis#4499]
With the advent of a v2 branch, it would be nothing short of amazing if Jenkins could do something intelligent about warning us when a commit to master is going to cause a conflict in with v2. Is this something we could do?

I'm going to go ahead and flag @mboersma and @sgoings. :wink:

**Comment by carmstrong** [comment]
Don't know about Jenkins, but GitHub will tell you when a PR is no longer able to be cleanly merged with master. You could open a "never merge me" PR and let GH tell you when the branch is out-of-sync.

**Comment by mboersma** [comment]
I'm closing this issue, because that :ship: has sailed.
