### ISSUE TITLE
Builder timing out on post-start

### ISSUE THREAD

**Issue by iancoffey** [deis/deis#4500]
Ive noticed many consecutive attempts to start builder has failed with the same result - and another 2 people have noticed the same failure during the same time.

The builder unit times out while starting, without much relevant output.

https://gist.githubusercontent.com/iancoffey/ffe47cb5eccba37afdf4/raw/b6125d67edb1a5cea46bdaaf342a674ebb855af5/gistfile1.txt

I only noticed failures when starting 1.9.1, however a community member has seemingly the same issue installing 1.10.0.

**Comment by iancoffey** [comment]
Ill try to get more info for this one.

**Comment by sstarcher** [comment]
We currently have a 1.9.0 cluster running and I was attempting to setup a new cluster using the same process on AWS for 1.10.0.  I was seeing the same thing that is in that gist.  I just downgraded my client to version 1.9.0 so I can follow our process and see if 1.9.0 still works using our process.

**Comment by carmstrong** [comment]
The ExecStartPost is waiting for the builder to listen on its port:
```
ExecStartPost=/bin/sh -c "echo 'Waiting for builder on 2223/tcp...' && until ncat $COREOS_PRIVATE_IPV4 2223 --exec '/usr/bin/echo dummy-value' >/dev/null 2>&1; do sleep 1; done"
```

When you see this, can you enter the builder with `nse deis-builder` and `netstat -tnlp` to see if builder is actually listening?

I think someone on our team (@smothiki?) has also seen this.

**Comment by iancoffey** [comment]
For what its worth, I cant repro this now - startup succeeds for both 1.9.1 and 1.10.0 for me. Seems like maybe an external service was overloaded for a time. Might be nice to add some more output, even if its optional, to see whats going on.

**Comment by smothiki** [comment]
Yeah sometimes builder was stuck at startpost. Right now I'm  starting builder without startpost.

**Comment by technosophos** [comment]
Whenever that happens next, can you do a `deisctl journal builder` and paste at least the last 100 lines here? The question is whether or not builder's SSH server is starting. If it is, then we should figure out how to fix the ExecStartPost. If it's not... we have a bigger problem.

Another test you can do when it hangs is to get onto the cluster (`deisctl ssh deis-builder`) and see if you can connect to the SSH port (`ssh -p 2223 ...`). You won't be able to shell in, but it will hang up on you with an error message if it's listening. If it's not, you'll get a connection refused error.

**Comment by sstarcher** [comment]
I'm guessing /deis/builder/sshHostKey is my issue?

```
Sep 16 21:29:08 ip-10-0-20-104.ec2.internal sh[2077]: time="2015-09-16T21:29:08Z" level="info" msg="-job build() = OK (0)"
Sep 16 21:29:08 ip-10-0-20-104.ec2.internal sh[2077]: Error:  100: Key not found (/deis/builder/sshHostKey) [2120]
Sep 16 21:29:09 ip-10-0-20-104.ec2.internal sh[2077]: ssh-keygen: generating new host keys: RSA1 RSA DSA ECDSA ED25519
Sep 16 21:29:09 ip-10-0-20-104.ec2.internal sh[2077]: deis-builder running...
Sep 16 21:29:09 ip-10-0-20-104.ec2.internal sh[2077]: Server listening on 0.0.0.0 port 22.
Sep 16 21:29:09 ip-10-0-20-104.ec2.internal sh[2077]: Server listening on :: port 22.
```

**Comment by sstarcher** [comment]
As for testing SSH
```
(No info could be read for "-p": geteuid()=500 but you should be root.)
tcp6       0      0 :::2223                 :::*                    LISTEN      -
```

```
core@ip-10-0-20-104 ~ $ ssh localhost -p 2223
ssh_exchange_identification: read: Connection reset by peer
```

**Comment by technosophos** [comment]
If it does not find an ssh host key in etcd, it just creates new ones. So that shouldn't stop anything from working. Interestingly, you are running ssh on port 22 in the container. I thought we re-configured it all to use 2223 for Flannel.

**Comment by carmstrong** [comment]
> I thought we re-configured it all to use 2223 for Flannel.

The unit definitely shows us forwarding 2223 to 2223 within the container: https://github.com/deis/deis/blob/master/deisctl/units/deis-builder.service#L11

**Comment by technosophos** [comment]
And the Dockerfile has port 2223 as its exposed port:

https://github.com/deis/deis/blob/master/builder/rootfs/Dockerfile

So it might just be the case that SSH is running on port 22 while port 2223 is the only one being exposed.

**Comment by sstarcher** [comment]
Taking another glance at it that would make sense on my part.
```
22/tcp, 0.0.0.0:2223->2223/tcp
```
My container is listening on 22, but 2223 is what is being forwarded out of the container.  Should the unit file not be changed from 
```-p 2223:2223```
to 
```-p 2223:22```

**Comment by sstarcher** [comment]
Looking through your sshd config I see you setting it to 2223 I'm going to look into my containers config and see what's up

**Comment by technosophos** [comment]
The port number should be determined by the line above that in the unit file:

https://github.com/deis/deis/blob/master/deisctl/units/deis-builder.service#L11

The environment var `EXTERNAL_PORT` is what Builder reads to figure out what port it will listen on. I'm hunting through the code to see if there is some place where the port gets overridden to 22.

**Comment by technosophos** [comment]
One thing that might be helpful is to run `fleetctl cat deis-builder.service` from your `deisctl ssh` session, and dump that output here. It might be the case that the fleet unit file is out of sync.

**Comment by sstarcher** [comment]
I was looking through my logs and it looks like the images I'm using are still 1.9.0.  The deisctl version I was using is 1.10.0 and this was a new cluster.  Does the version get stored in the database?

**Comment by carmstrong** [comment]
> The deisctl version I was using is 1.10.0 and this was a new cluster. Does the version get stored in the database?

That'll explain the issue. You need to make sure you're using version 1.10.0 *of the Deis code* to provision the hosts the cluster runs on - this sets an `/etc/deis-release` file which exports a platform version. This version is overwritten for upgrade installs by using `deisctl` to set `/deis/platform/version`, but when provisioning new hosts it's important to use the appropriate version of the code so your user-data prepares the filesystem in the expected way.

**Comment by technosophos** [comment]
So I think this issue is capturing a couple of different cases where 1.9-1.10 migrations are stuck in an intermediate state.

We switched the Builder's internal port from 22 to 2223 for Flannel compatibility. But this means that if the Fleet unit files get out of sync then Builder will be listening on one port and the Fleet units will set up the other port.

So a 1.9 release with a fleet units for 1.10 will have the problem that @sstarcher is reporting, and a 1.10 release with 1.9 units may hit a slightly different variation of the problem, where Fleet never returns because it's waiting for port 22 to come up, and the container is running on 2223.

**Comment by sstarcher** [comment]
Confirmed that my problems were related to using 1.9.0 code base with deisctl/deis version 1.10.0.  I thought I was using the 1.10.0, but was mistaken.

**Comment by jweller** [comment]
My problem is definitely not upgrade-related. I've done fresh 1.10.0 installs on AWS four times now and hit the same issues every time. This has never happened to me on 1.9.1. Here's the rundown:

1. No issues during installation. At 'deisctl start platform', deis-builder.service never transitions from deis-'activating/start-post' to 'active/running'.
2. When platform startup completes and I run 'deisctl list', all the services show as 'active/running' except for builder, which is still stuck at 'activating/start-post'.
3. Oddly, the [output of 'deisctl status builder'](https://gist.github.com/jweller/f31c9817a595853d3820.js) shows the service as 'running'.

I've also verified that the deis and deisctl clients are version 1.10.0, as is the Deis codebase from which I installed the platform.

**Comment by sstarcher** [comment]
@jweller It certainly looks like you are not using the unit files from Deis 1.10.0 You seem to have the opposite problem I was having.  Your builder is listening on 2223, but the docker run command is forwarding to 22 instead of 2223 like Deis 1.10.0 expect.

Your unit file should have the following port direction "-p 2223:2223" when in reality you have " -p 2223:22"

What is the git sha of the code you have checked out?

**Comment by jweller** [comment]
@sstarcher I installed from commit b28574640b5f40392eaa6899e0ee40ea92cdcf93

**Comment by sstarcher** [comment]
The unit file you are executing and the unit file that is on that commit are not the same https://github.com/deis/deis/blob/b28574640b5f40392eaa6899e0ee40ea92cdcf93/deisctl/units/deis-builder.service

Notice how it has the correct "-p 2223:2223" I would recommend either building deisctl from source, pointing deisctl to the unit files you have checked out, or refreshing the unit files from branch v1.10.0

Pointing them to the ones you have checked out is probably best.

**Comment by jweller** [comment]
@sstarcher I think you were right. I'm not sure exactly what got out of sync or how, but I updated the unit files and that did the trick.

**Comment by sstarcher** [comment]
It sounds like everyone who has had a problem has fixed it and everytime it has been related to unit files / platform being on different versions.

**Comment by iancoffey** [comment]
@sstarcher Agreed, I'm going to close this issue in hopes that any reproducible problem gets created as a new issue. Cheers!
