### ISSUE TITLE
docs: Clarify router SSL vs. SSL per-app

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#4501]
SSL documentation is here: http://docs.deis.io/en/latest/managing_deis/ssl-endpoints/

I've heard a few users who were confused when trying to use both router-level SSL and per-application SSL certificates. As far as I'm aware, configuring router-level SSL certificates will terminate all requests using the single certificate configured there, even if some applications have their own certificates configured.

We should make this behavior clear, and ideally allow application-level SSL certs to override the router-level cert, which should just be a default.

**Comment by bacongobbler** [comment]
clarified in https://github.com/deis/router
