### ISSUE TITLE
Graceful Upgrade: Restart the routers once

### ISSUE THREAD

**Issue by crigor** [deis/deis#4503]
The experimental [graceful upgrade](http://docs.deis.io/en/latest/managing_deis/upgrading-deis/#graceful-upgrade) currently does a rolling restart of routers and an install and start of *all* components which results in restarting the routers twice. 

This results in downtime.

https://github.com/deis/deis/blob/e3a28b48a451338e12165ab769d9c711f9533805/deisctl/cmd/upgrade.go#L101-L104

Output of `deisctl upgrade-takeover`: https://gist.github.com/crigor/22baefac7ac494b02d17

**Comment by iancoffey** [comment]
@crigor great catch, this shouldnt happen anymore after https://github.com/deis/deis/issues/4506. that commit should also help with stateless cluster upgrades.
