### ISSUE TITLE
bug(builder): Procfile should not be parsed as YAML

### ISSUE THREAD

**Issue by benwilber** [deis/deis#4509]
Builder parses [Procfile as YAML](https://github.com/deis/deis/blob/master/builder/rootfs/usr/local/src/slugbuilder/builder/build.sh#L144)

This introduces issues with Heroku compatibility since [Procfile is not YAML](https://github.com/ddollar/foreman/issues/532#issuecomment-75386242)

**Comment by mboersma** [comment]
The simpler `key: value` format of a Procfile is a valid subset of YAML, but I agree Deis doing more general parsing opens the door to Deis-compatible apps that won't work on Heroku.

**Comment by benwilber** [comment]
@mboersma Yeah I figured it's a really small issue but at least something that should be mentioned since `Procfile` *looks* like YAML, but it's not really YAML, and that distiction has already burned at least one person (me).

**Comment by bacongobbler** [comment]
I think we should stick with parsing the Procfile as YAML, since changing it now will introduce breaking compatibility with users who may have been relying on this. I'd consider it a feature of Deis rather than a bug, IMHO.

**Comment by mboersma** [comment]
"Works like Heroku" is still the overall goal for buildpack apps, so I think making this more simple / strict would actually improve that. If users have real YAML Procfiles, those are by definition invalid and we shouldn't accept them. It's not the end of the world, but I think it should be fixed someday.

**Comment by johnwilson** [comment]
If you think we should have a purposely built parser for this I could write one
