### ISSUE TITLE
Proposal feat(k8s): docker-compose.yml syntax support via compose2kube

### ISSUE THREAD

**Issue by jgmize** [deis/deis#4514]
With some (admittedly non-trivial) changes to the builder, controller, and scheduler after the v2 switch to k8s as the standard scheduler, it might be possible to leverage [compose2kube](https://github.com/kelseyhightower/compose2kube) to create multi-container pods with a docker-compose.yml in the root of the repo and a "git push deis" deployment workflow that insulates the developer from needing to interact with k8s directly via kubectl.

**Comment by aegixx** [comment]
[kompose](https://github.com/skippbox/kompose) works effectively at converting docker-compose.yml to k8s template files.  

With that said, is there a path for deis to publish a docker-compose application?

**Comment by bacongobbler** [comment]
at this point, there is no path for deis to publish one, however it's probably best to bring this up at deis/builder since this is the v1 repo. :)

**Comment by krancour** [comment]
@bacongobbler any reason we shouldn't close this?

**Comment by deis-admin** [comment]
This issue was moved to deis/builder#467
