### ISSUE TITLE
ceph mon down

### ISSUE THREAD

**Issue by ghost** [deis/deis#4515]
after restarting (sudo reboot) one node ceph stuck in health_warn

ceph -s
    cluster b37334ff-c394-4741-badf-4e8fcd736606
     health HEALTH_WARN
            1 mons down, quorum 0,2,3,4 gdeis-3,gdeis-1,gdeis-2,gdeis-4
     monmap e5: 5 mons at {gdeis-1=10.130.29.228:6789/0,gdeis-2=10.130.29.229:6789/0,gdeis-3=10.130.28.223:6789/0,gdeis-4=10.130.29.230:6789/0,gdeis-5=10.130.28.224:6789/0}
            election epoch 232, quorum 0,2,3,4 gdeis-3,gdeis-1,gdeis-2,gdeis-4
     mdsmap e59: 1/1/1 up {0=gdeis-2=up:active}, 3 up:standby
     osdmap e418: 5 osds: 3 up, 3 in
      pgmap v736185: 768 pgs, 12 pools, 13245 MB data, 8189 objects
            102 GB used, 113 GB / 225 GB avail
                 768 active+clean
  client io 477 B/s wr, 0 op/s

when executing ceph -s often i also see another message

ceph -s
    cluster b37334ff-c394-4741-badf-4e8fcd736606
     health HEALTH_ERR
            64 pgs stuck inactive
            64 pgs stuck unclean
            no osds
     monmap e1: 1 mons at {gdeis-5=10.130.28.224:6789/0}
            election epoch 1, quorum 0 gdeis-5
     osdmap e1: 0 osds: 0 up, 0 in
      pgmap v2: 64 pgs, 1 pools, 0 bytes data, 0 objects
            0 kB used, 0 kB / 0 kB avail
                  64 creating

should i just follow the instructions from http://docs.deis.io/en/latest/managing_deis/add_remove_host/#removing-a-node to remove gdeis-5 and add the node again http://docs.deis.io/en/latest/managing_deis/add_remove_host/#adding-a-node

etcdctl get /deis/store/monSetupLock is also pointing to the faulty node -> gdeis-5

**Comment by carmstrong** [comment]
You could first try just restarting the monitor on that host: `sudo systemctl restart deis-store-monitor`.

**Comment by slash-** [comment]
@carmstrong just restarting the monitor doesn't help

**Comment by carmstrong** [comment]
Are you sure that `gdeis-5` came back with the same IP? 10.130.28.224

**Comment by slash-** [comment]
```core@gdeis-5 ~ $ ip a s eth1
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 04:01:65:af:a0:02 brd ff:ff:ff:ff:ff:ff
    inet 10.130.28.224/16 brd 10.130.255.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::601:65ff:feaf:a002/64 scope link 
       valid_lft forever preferred_lft forever```

also iptables looks fine and i can access gdeis-5 for the specific ports (nmap, telnet)

**Comment by slash-** [comment]
@carmstrong here are some more detailed information using ceph admin socket, on the ceph page there are also no information about having two leaders and how to solve it

[gdeis-3](https://gist.github.com/slash-/f4406611b298e856175c) - look the same on the other 3 but state = peon
[gdeis-5](https://gist.github.com/slash-/de535e2e9b04ae6d7cb5)

while restarting `deis-store-monitor` on `gdeis-5`
[debug log](https://gist.github.com/slash-/7a9b60e1eb9d9897b72a) 

`ceph health detail`
`HEALTH_WARN 1 mons down, quorum 0,2,3,4 gdeis-3,gdeis-1,gdeis-2,gdeis-4; 
`mon.gdeis-5 (rank 1) addr 10.130.28.224:6789/0 is down (out of quorum)`

`fleetctl list-machines`
`MACHINE		IP		METADATA`
`5410e838...	10.130.29.229	-`
`70a43ad9...	10.130.28.224	-`
`7a8cdda6...	10.130.29.230	-`
`f1c70a89...	10.130.28.223	-`
`fd16d587...	10.130.29.228	-`

`/deis/store/hosts/10.130.28.224 -> gdeis-5`
`/deis/store/hosts/10.130.29.228 -> gdeis-1`
`/deis/store/hosts/10.130.29.229 -> gdeis-2`
`/deis/store/hosts/10.130.28.223 -> gdeis-3`
`/deis/store/hosts/10.130.29.230 -> gdeis-4`

deis is running on DO (v1.9) with CoreOS 723.3.0 (where i know this is not a supported version but we were not able to launch a coreos version with docker 1.5 or 1.7 this time

**Comment by bacongobbler** [comment]
this issue has gone stale without and the user no longer exists on github. This is not something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant so I'm closing this.

**Comment by monaka** [comment]
Probably monmap gdeis-5 was broken in this case.

Yesterday I encountered a quite similar issue and resolved.
In my case, the monmap in one node is broken. So I did `ceph mon add` in `deis-store-admin` and the cluster was fixed.
