### ISSUE TITLE
test-integration should run a scaling stress test

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#4516]
When cutting a release, we often manually execute a stress test to scale from zero to ten containers and then back again several times. Sometimes, we only catch issues with a release when performing a stress test.

Jenkins should be running this test for us on each PR so that we're not only catching issues during a release.

**Comment by bacongobbler** [comment]
we now have a end-to-end test suite that we run on our own clusters for sanity purposes in v2. Closing!
