### ISSUE TITLE
How do I proxy the `deisctl` to Restful-API use https?

### ISSUE THREAD

**Issue by CloudSide** [deis/deis#4518]
How do I proxy the `deisctl` to Restful-API use https?

**Comment by mboersma** [comment]
@CloudSide `deisctl` uses SSH as an underlying transport. You can configure the host it communicates with either by setting the `DEISCTL_TUNNEL` environment variable to a host:port, or by specifying the tunnel on the command line:
```console
$ deisctl --tunnel=myhost.deis.works <command>
```
