### ISSUE TITLE
AWS provisioning inconsistent

### ISSUE THREAD

**Issue by iancoffey** [deis/deis#4519]
[This](https://github.com/deis/deis/commit/19b06d5ae3652e4572c0b8803a4377d7221cbe62) commit seems to have left aws provisioning via the contrib scripts in an inconsistent state.

In master, the [health check](http://docs.deis.io/en/latest/installing_deis/quick-start/#get-the-source) has been changed to reference 9090, but the user-data installs deisctl 1.10.1, the units of which doesnt expose 9090 yet.

The result is that using the /opt/bin/deisctl binary to install the platform will result in a cluster that cant be used, since the ELB will permanently kick out all the nodes.

This could be confusing for first-time installers.

**Comment by iancoffey** [comment]
Nevermind - the docs do correctly describe [checking out the correct tag](http://docs.deis.io/en/latest/installing_deis/quick-start/#get-the-source), so this is just my bad.

**Comment by mboersma** [comment]
> so this is just my bad.

True, but I've also run into this and helped others troubleshoot the same thing, before we realized we were mixing versions. We might think about a way to make the healthcheck more backward-compatible-friendly because it won't be the last time this crops up.
