### ISSUE TITLE
Can not use official nginx docker image on port 80

### ISSUE THREAD

**Issue by LoicMahieu** [deis/deis#4520]
Simple `Dockerfile`:
```
FROM nginx
EXPOSE 80
```
Even if `EXPOSE` has been rewritted, docker expose 2 ports:
`0.0.0.0:32779->80/tcp, 0.0.0.0:32780->443/tcp`
Publisher publish the port 443 on etcd:
```sh
$ etcdctl get /deis/services/test-docker-nginx/test-docker-nginx_v4.cmd.1
10.10.8.10:32779
```
But container does not listen on 443 and the routeur send 502 Bad Gateway.

For testing, just replace etcd value:
```sh
$ etcdctl set /deis/services/test-docker-nginx/test-docker-nginx_v2.cmd.1 "10.10.8.10:32778"
10.10.8.10:32778
```

**Comment by LoicMahieu** [comment]
I guess [`Server.isPortOpen`](https://github.com/deis/deis/blob/master/publisher/server/publisher.go#L121) should have result false for 443...

**Comment by bacongobbler** [comment]
The base nginx image exports 2 ports. All base images cannot override that so it's not an image we can support based on http://docs.deis.io/en/latest/using_deis/using-dockerfiles/#dockerfile-requirements.

**Comment by LoicMahieu** [comment]
Is [isPortOpen](https://github.com/deis/deis/blob/master/publisher/server/publisher.go#L194) should not have answered false?
```sh
$ netstat -ln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node Path
```

**Comment by bacongobbler** [comment]
IsPortOpen will answer true due to Docker's tcp proxy. It will always listen for a connection on that port even if the container is not.

I'm a little confused by the issue. In the OP it's stated that port 443 is exposed, yet in the example you showed, it published `10.10.8.10:32779` which is port 80. Is there a typo in your OP?

**Comment by LoicMahieu** [comment]
Arg sorry. Example is wrong... I quickly retried:
```
0.0.0.0:32786->80/tcp, 0.0.0.0:32785->443/tcp
```
```
$ etcdctl get /deis/services/test-nginx/test-nginx_v2.cmd.1
10.10.8.10:32785
```
Sorry for confusion. I had to be wrong in copy/paste...

---

Ok thanks for clarification about IsPortOpen. So if I understand, in most case, this check is useless if it always result false ?

Thanks for support on this issue. If you consider this is not an issue, you can close it.
I guess I have no choice but to create a base image exposing only a single port... This is really annoying.

**Comment by bacongobbler** [comment]
closing by proxy of #3069
