### ISSUE TITLE
Builder 400 error

### ISSUE THREAD

**Issue by msull92** [deis/deis#4521]
I have a dockerfile that uses:

```dockerfile
FROM mono:onbuild
```

This used to work just fine, but after upgrading to Deis 1.10.1, it gets this error:(it was a migration update)

```
Error pulling image (latest) from mono, endpoint: https://registry-1.docker.io/v1/, HTTP code 400
```

**Comment by bacongobbler** [comment]
sounds like https://github.com/docker-library/redis/issues/32

**Comment by msull92** [comment]
I got around this issue by creating our own version of the image and pulling from that instead.
