### ISSUE TITLE
deis-builder can't start

### ISSUE THREAD

**Issue by duanhongyi** [deis/deis#4524]
fleetctl list-units

UNIT				MACHINE				ACTIVE		SUB
deis-builder.service		833be1c5.../192.168.1.102	activating	start-post
deis-controller.service		a65bed4b.../192.168.1.101	active		running
deis-database.service		a65bed4b.../192.168.1.101	active		running
deis-logger.service		833be1c5.../192.168.1.102	active		running
deis-logspout.service		044cb879.../192.168.1.100	active		running
deis-logspout.service		833be1c5.../192.168.1.102	active		running
deis-logspout.service		a65bed4b.../192.168.1.101	active		running
deis-publisher.service		044cb879.../192.168.1.100	active		running
deis-publisher.service		833be1c5.../192.168.1.102	active		running
deis-publisher.service		a65bed4b.../192.168.1.101	active		running
deis-registry@1.service		044cb879.../192.168.1.100	active		running
deis-router@1.service		044cb879.../192.168.1.100	active		running
deis-router@2.service		a65bed4b.../192.168.1.101	active		running
deis-router@3.service		833be1c5.../192.168.1.102	active		running
deis-store-daemon.service	044cb879.../192.168.1.100	active		running
deis-store-daemon.service	833be1c5.../192.168.1.102	active		running
deis-store-daemon.service	a65bed4b.../192.168.1.101	active		running
deis-store-gateway@1.service	044cb879.../192.168.1.100	active		running
deis-store-metadata.service	044cb879.../192.168.1.100	active		running
deis-store-metadata.service	833be1c5.../192.168.1.102	active		running
deis-store-metadata.service	a65bed4b.../192.168.1.101	active		running
deis-store-monitor.service	044cb879.../192.168.1.100	active		running
deis-store-monitor.service	833be1c5.../192.168.1.102	active		running
deis-store-monitor.service	a65bed4b.../192.168.1.101	active		running
deis-store-volume.service	044cb879.../192.168.1.100	active		running
deis-store-volume.service	833be1c5.../192.168.1.102	active		running
deis-store-volume.service	a65bed4b.../192.168.1.101	active		running

==================================================================

deisctl journal deis-builder.service

Sep 22 06:07:14 deis-03 systemd[1]: Starting deis-builder...
Sep 22 06:07:14 deis-03 sh[2497]: Unable to find image 'alpine:3.1' locally
Sep 22 06:07:27 deis-03 sh[2497]: Pulling repository alpine
Sep 22 06:07:32 deis-03 sh[2497]: 8dd8107abd2e: Pulling image (3.1) from alpine
Sep 22 06:07:32 deis-03 sh[2497]: 8dd8107abd2e: Pulling image (3.1) from alpine, endpoint: https://registry-1.docker.io/v1/
Sep 22 06:07:34 deis-03 sh[2497]: 8dd8107abd2e: Pulling dependent layers
Sep 22 06:07:34 deis-03 sh[2497]: 8dd8107abd2e: Pulling metadata
Sep 22 06:07:35 deis-03 sh[2497]: 8dd8107abd2e: Pulling fs layer
Sep 22 06:08:00 deis-03 sh[2497]: 8dd8107abd2e: Download complete
Sep 22 06:08:00 deis-03 sh[2497]: 8dd8107abd2e: Download complete
Sep 22 06:08:00 deis-03 sh[2497]: Status: Downloaded newer image for alpine:3.1
Sep 22 06:08:00 deis-03 sh[2643]: Pulling repository deis/builder
Sep 22 06:08:56 deis-03 sh[2643]: d29365082f0c: Pulling image (v1.9.1) from deis/builder
Sep 22 06:08:56 deis-03 sh[2643]: d29365082f0c: Pulling image (v1.9.1) from deis/builder, endpoint: https://registry-1.docker.io/v1/
Sep 22 06:08:58 deis-03 sh[2643]: d29365082f0c: Pulling dependent layers
Sep 22 06:08:58 deis-03 sh[2643]: 878b6301beda: Download complete
Sep 22 06:12:06 deis-03 sh[2643]: 0f79c1aea908: Download complete
Sep 22 06:12:06 deis-03 sh[2643]: 0495177a08af: Pulling metadata
Sep 22 06:12:09 deis-03 sh[2643]: 0495177a08af: Pulling fs layer
Sep 22 06:12:33 deis-03 sh[2643]: 0495177a08af: Download complete
Sep 22 06:12:33 deis-03 sh[2643]: 00a4604a51ad: Pulling metadata
Sep 22 06:12:36 deis-03 sh[2643]: 00a4604a51ad: Pulling fs layer
Sep 22 06:14:10 deis-03 sh[2643]: 00a4604a51ad: Download complete
Sep 22 06:14:10 deis-03 sh[2643]: 2f7f86987709: Pulling metadata
Sep 22 06:14:18 deis-03 sh[2643]: 2f7f86987709: Pulling fs layer
Sep 22 06:15:04 deis-03 sh[2643]: 2f7f86987709: Download complete
Sep 22 06:15:04 deis-03 sh[2643]: 7ede470805df: Pulling metadata
Sep 22 06:15:08 deis-03 sh[2643]: 7ede470805df: Pulling fs layer
Sep 22 06:16:10 deis-03 sh[2643]: 7ede470805df: Download complete
Sep 22 06:16:10 deis-03 sh[2643]: 4f4b3827ebe1: Pulling metadata
Sep 22 06:16:19 deis-03 sh[2643]: 4f4b3827ebe1: Pulling fs layer
Sep 22 06:16:24 deis-03 sh[2643]: 4f4b3827ebe1: Download complete
Sep 22 06:16:24 deis-03 sh[2643]: 7136ae3e0258: Pulling metadata
Sep 22 06:16:27 deis-03 sh[2643]: 7136ae3e0258: Pulling fs layer
Sep 22 06:16:33 deis-03 sh[2643]: 7136ae3e0258: Download complete
Sep 22 06:16:33 deis-03 sh[2643]: a707b37bec9f: Pulling metadata
Sep 22 06:16:36 deis-03 sh[2643]: a707b37bec9f: Pulling fs layer
Sep 22 06:16:41 deis-03 sh[2643]: a707b37bec9f: Download complete
Sep 22 06:16:41 deis-03 sh[2643]: 274101c72c38: Pulling metadata
Sep 22 06:16:59 deis-03 sh[2643]: 274101c72c38: Pulling fs layer
Sep 22 06:17:09 deis-03 sh[2643]: 274101c72c38: Download complete
Sep 22 06:17:09 deis-03 sh[2643]: da671cb9660d: Pulling metadata
Sep 22 06:17:12 deis-03 sh[2643]: da671cb9660d: Pulling fs layer
...skipping...
Sep 23 05:20:06 deis-03 sh[19482]: time="2015-09-23T05:20:06Z" level="info" msg="+job history(deis/slugbuilder)"
Sep 23 05:20:06 deis-03 sh[19482]: time="2015-09-23T05:20:06Z" level="info" msg="-job history(deis/slugbuilder) = OK (0)"
Sep 23 05:20:06 deis-03 sh[19482]: time="2015-09-23T05:20:06Z" level="info" msg="GET /v1.17/images/deis/slugrunner/history"
Sep 23 05:20:06 deis-03 sh[19482]: time="2015-09-23T05:20:06Z" level="info" msg="+job history(deis/slugrunner)"
Sep 23 05:20:06 deis-03 sh[19482]: time="2015-09-23T05:20:06Z" level="info" msg="-job history(deis/slugrunner) = OK (0)"
Sep 23 05:20:06 deis-03 sh[19482]: SSH PRIVATE KEY FILE FORMAT 1.1
Sep 23 05:20:06 deis-03 sh[19482]: [117B blob data]
Sep 23 05:20:06 deis-03 sh[19482]: [189B blob data]
Sep 23 05:20:06 deis-03 sh[19482]: [32B blob data]
Sep 23 05:20:06 deis-03 sh[19482]: [15B blob data]
Sep 23 05:20:06 deis-03 sh[19482]: [31B blob data]
Sep 23 05:20:06 deis-03 sh[19482]: deis-builder running...
Sep 23 05:20:06 deis-03 sh[19482]: Server listening on 0.0.0.0 port 22.
Sep 23 05:20:06 deis-03 sh[19482]: Server listening on :: port 22.
Sep 23 05:28:18 deis-03 systemd[1]: Stopped deis-builder.
Sep 23 05:28:24 deis-03 systemd[1]: Starting deis-builder...
Sep 23 05:28:24 deis-03 sh[21644]: deis-builder
Sep 23 05:28:24 deis-03 sh[21666]: /dev/loop0
Sep 23 05:28:24 deis-03 sh[21672]: Waiting for builder on 2223/tcp...
Sep 23 05:28:46 deis-03 sh[21671]: time="2015-09-23T05:28:46Z" level="info" msg="+job serveapi(unix:///var/run/docker.sock)"
Sep 23 05:28:46 deis-03 sh[21671]: time="2015-09-23T05:28:46Z" level="info" msg="Listening for HTTP on unix (/var/run/docker.sock)"
Sep 23 05:28:46 deis-03 sh[21671]: time="2015-09-23T05:28:46Z" level="info" msg="+job init_networkdriver()"
Sep 23 05:28:46 deis-03 sh[21671]: time="2015-09-23T05:28:46Z" level="info" msg="-job init_networkdriver() = OK (0)"
Sep 23 05:28:46 deis-03 sh[21671]: time="2015-09-23T05:28:46Z" level="info" msg="Loading containers: start."
Sep 23 05:28:46 deis-03 sh[21671]: ..
Sep 23 05:28:46 deis-03 sh[21671]: time="2015-09-23T05:28:46Z" level="info" msg="Loading containers: done."
Sep 23 05:28:46 deis-03 sh[21671]: time="2015-09-23T05:28:46Z" level="info" msg="docker daemon: 1.5.0 a8a31ef; execdriver: native-0.2; graphdriver: overlay"
Sep 23 05:28:46 deis-03 sh[21671]: time="2015-09-23T05:28:46Z" level="info" msg="+job acceptconnections()"
Sep 23 05:28:46 deis-03 sh[21671]: time="2015-09-23T05:28:46Z" level="info" msg="-job acceptconnections() = OK (0)"
Sep 23 05:28:47 deis-03 sh[21671]: time="2015-09-23T05:28:47Z" level="info" msg="GET /v1.17/images/deis/slugbuilder/history"
Sep 23 05:28:47 deis-03 sh[21671]: time="2015-09-23T05:28:47Z" level="info" msg="+job history(deis/slugbuilder)"
Sep 23 05:28:47 deis-03 sh[21671]: time="2015-09-23T05:28:47Z" level="info" msg="-job history(deis/slugbuilder) = OK (0)"
Sep 23 05:28:47 deis-03 sh[21671]: time="2015-09-23T05:28:47Z" level="info" msg="GET /v1.17/images/deis/slugrunner/history"
Sep 23 05:28:47 deis-03 sh[21671]: time="2015-09-23T05:28:47Z" level="info" msg="+job history(deis/slugrunner)"
Sep 23 05:28:47 deis-03 sh[21671]: time="2015-09-23T05:28:47Z" level="info" msg="-job history(deis/slugrunner) = OK (0)"
Sep 23 05:28:47 deis-03 sh[21671]: SSH PRIVATE KEY FILE FORMAT 1.1
Sep 23 05:28:47 deis-03 sh[21671]: [117B blob data]
Sep 23 05:28:47 deis-03 sh[21671]: [189B blob data]
Sep 23 05:28:47 deis-03 sh[21671]: [32B blob data]
Sep 23 05:28:47 deis-03 sh[21671]: [15B blob data]
Sep 23 05:28:47 deis-03 sh[21671]: [31B blob data]
Sep 23 05:28:47 deis-03 sh[21671]: deis-builder running...
Sep 23 05:28:47 deis-03 sh[21671]: Server listening on 0.0.0.0 port 22.
Sep 23 05:28:47 deis-03 sh[21671]: Server listening on :: port 22.

==================================================================
Operating environment:

vagrant 1.7.4
deis 1.10.1

**Comment by carmstrong** [comment]
@duanhongyi Nothing here looks to be out of the ordinary. After builder starts, it pushes some large images to the Docker registry. You can see this with `deisctl status builder`. It will take a few minutes to complete.

**Comment by duanhongyi** [comment]
@carmstrong 


deisctl status builder

● deis-builder.service - deis-builder
   Loaded: loaded (/run/fleet/units/deis-builder.service; linked-runtime; vendor preset: disabled)
   Active: activating (start-post) since Wed 2015-09-23 05:45:22 UTC; 2min 10s ago
  Process: 26201 ExecStartPre=/bin/sh -c /sbin/losetup -f (code=exited, status=0/SUCCESS)
  Process: 26138 ExecStartPre=/bin/sh -c docker inspect deis-builder >/dev/null 2>&1 && docker rm -f deis-builder || true (code=exited, status=0/SUCCESS)
  Process: 26090 ExecStartPre=/bin/sh -c IMAGE=`/run/deis/bin/get_image /deis/builder` && docker history $IMAGE >/dev/null 2>&1 || docker pull $IMAGE (code=exited, status=0/SUCCESS)
  Process: 26082 ExecStartPre=/bin/sh -c docker inspect deis-builder-data >/dev/null 2>&1 || docker run --name deis-builder-data -v /var/lib/docker alpine:3.1 /bin/true (code=exited, status=0/SUCCESS)
 Main PID: 26204 (sh);         : 26205 (sh)
   Memory: 6.3M
   CGroup: /system.slice/deis-builder.service
           ├─26204 /bin/sh -c IMAGE=`/run/deis/bin/get_image /deis/builder` && docker run --name deis-builder --rm -p 2223:2223 --volumes-from=deis-builder-data -c 800 -e EXTERNAL_PORT=2223 -e HOST=$COREOS_PRIVATE_IPV4 --privileged -v /etc/environment_proxy:/etc/environment_proxy $IMAGE
           ├─26263 docker run --name deis-builder --rm -p 2223:2223 --volumes-from=deis-builder-data -c 800 -e EXTERNAL_PORT=2223 -e HOST=192.168.1.102 --privileged -v /etc/environment_proxy:/etc/environment_proxy deis/builder:v1.9.1
           └─control
             ├─26205 /bin/sh -c echo 'Waiting for builder on 2223/tcp...' && until ncat $COREOS_PRIVATE_IPV4 2223 --exec '/usr/bin/echo dummy-value' >/dev/null 2>&1; do sleep 1; done
             └─27069 sleep 1

Sep 23 05:47:08 deis-03 sh[26204]: time="2015-09-23T05:47:08Z" level="info" msg="-job history(deis/slugrunner) = OK (0)"
Sep 23 05:47:08 deis-03 sh[26204]: SSH PRIVATE KEY FILE FORMAT 1.1
Sep 23 05:47:08 deis-03 sh[26204]: [117B blob data]
Sep 23 05:47:08 deis-03 sh[26204]: [189B blob data]
Sep 23 05:47:08 deis-03 sh[26204]: [32B blob data]
Sep 23 05:47:08 deis-03 sh[26204]: [15B blob data]
Sep 23 05:47:08 deis-03 sh[26204]: [31B blob data]
Sep 23 05:47:08 deis-03 sh[26204]: deis-builder running...
Sep 23 05:47:08 deis-03 sh[26204]: Server listening on 0.0.0.0 port 22.
Sep 23 05:47:08 deis-03 sh[26204]: Server listening on :: port 22.

**Comment by duanhongyi** [comment]
I return to v1.9.1 version number, start a success

**Comment by carmstrong** [comment]
> I return to v1.9.1 version number, start a success

Good. My guess is that you're using units for a different Deis version than you provisioned. Did you use the version of `deisctl` that matched the version of the platform you're trying to install? And did you make sure that you either installed a new version or ran `deisctl refresh-units`?

**Comment by bacongobbler** [comment]
@carmstrong is definitely onto something. I recall during upgrade tests that the builder looked fine during boot but if you had an older unit file than the intended version, it would fail due to the logs above.

**Comment by mboersma** [comment]
It seems very likely that you are using an old systemd unit file with a newer builder component. Could you post the output of `deisctl cat deis-builder.service`? Looking at the unit file contents is the only way currently to match it up with a Deis release.

**Comment by duanhongyi** [comment]
Yes, systemd too old.
