### ISSUE TITLE
trying to provision a cluster on amazon aws

### ISSUE THREAD

**Issue by gred7** [deis/deis#4526]
hello, I am trying to follow the  http://docs.deis.io/en/latest/installing_deis/aws instruction.
all preparation steps went successful, but once I run:
cd contrib/aws; provision-aws-cluster.sh cluster1
Instances are available:
i-241a5af1	54.84.185.169	m4.large	us-east-1a	running
i-7cd3a2dc	54.174.142.131	m4.large	us-east-1b	running
i-7dd3a2dd	54.174.12.138	m4.large	us-east-1b	running
Using ELB cluster1-DeisWebELB-FIYZ48Z278XH at cluster1-DeisWebELB-FIYZ48Z278XH-1143530535.us-east-1.elb.amazonaws.com
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 100ms
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 200ms
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 400ms
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 800ms
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 1s
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 1s
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 1s
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 1s
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 1s
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 1s
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 1s
Waiting until fleet is up and running ...
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 100ms
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 200ms
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 400ms
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 800ms
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 1s
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 1s
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 1s
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 1s
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 1s
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 1s
INFO client.go:297: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 1s

Perhaps I am missing something very obvious.

**Comment by sgoings** [comment]
I've seen this happen when:

- you are reusing an already-used Discovery token (generated via `make discovery-url` - you can access that url in a browser to see if nodes registered or not)
- etcd has problems for one reason or another (ssh into the cluster and run `etcdctl cluster-health` for more info)
- the `DEISCTL_TUNNEL` variable isn't setup correctly (what's the `DEISCTL_TUNNEL` variable set to in the environment you ran this from?)
- (less certain on this) ssh keys aren't being handled properly or setup. That would be [this step](http://docs.deis.io/en/latest/installing_deis/aws/#upload-keys).

**Comment by gred7** [comment]
Thank you. the problem was my inet connection.
