### ISSUE TITLE
Add https log drain type

### ISSUE THREAD

**Issue by nsmith** [deis/deis#4527]
It would be very convenient to have an https log drain type. Log aggregation providers like SumoLogic do not provider managed syslog collectors, preferring instead https based collectors. While Sumo does offer self-hosted syslog collectors, it seems very awkward to run a non-Deis managed container on each CoreOS cluster node, and pipe journal messages in for each application, or alternatively consume all journal messages, with no application prefixes. Using a drain to an https collector endpoint seems like a much more elegant solution.

**Comment by deis-admin** [comment]
This issue was moved to deis/logger#134
