### ISSUE TITLE
provisioning should fail on a used discovery URL

### ISSUE THREAD

**Issue by mboersma** [deis/deis#4528]
A persistent problem is forgetting to run `make discovery-url` before provisioning a cluster. If it hasn't been run, and there's no user-data file, that is caught and handled well, but if a user-data exists with a discovery.etcd.io endpoint that's already been used, that isn't caught and provisioning will proceed and then fail with errors.

Potentially Deis could either:
- make an HTTP request of the discovery URL and fail if it exists, assuming that means it's been used already
- mark the user-data file with some canonical entry that will be caught and handled as an error on reuse, and/or make it invalid YAML
- generate a new disco URL on every provisioning (see #4548)

**Comment by bacongobbler** [comment]
perhaps we could check the timestamp of the user data and warn if it's been at least a half hour since it was last updated?

**Comment by krancour** [comment]
What about an HTTP request to the discovery URL as @mboersma suggested, but then actually parse the JSON response to determine if any nodes have already used it.

**Comment by mboersma** [comment]
> but then actually parse the JSON response

That's probably the most robust way. 

The real trick here is that there are multiple provisioning paths, from `vagrant up` to `provision-aws.sh` and friends. So the solution to this may need to be a standard shell script or binary tool that does what is outlined above, but can be called easily from any of those contexts.

**Comment by helgi** [comment]
What about just running `make discovery-url` on provision each time. That's what I have done.

I did this in python, for ... reasons (import os and subprocess in one of the gen-cluster scripts)

```python
def discovery_url():
    # Ensure the cluster has the latest user-data
    os.chdir(os.path.realpath(os.path.join(CURR_DIR, '..', '..', '..')))  # Just to get to the deis root
    cmd = "make discovery-url"
    _, err = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE).communicate()
    if err:
        print err
        raise
    os.chdir(CURR_DIR)
```

Is there a problem with generating a new one on each provision since it is separate from updating? Seems simpler than jumping into HTTP parsing

**Comment by krancour** [comment]
> So the solution to this may need to be a standard shell script or binary tool

@mboersma, ya.  I'd momentarily forgotten what a pain it is to parse JSON in a shell script.  A binary tool might be an interesting option.  I've been thinking for a while that the development environment and the environment from which provisioning is run might ideally be containerized to reduce the amount of setup required for operators and standardize the dev / test environment for contributors.  This is a larger discussion, obviously, but if one effect of that is that provisioning is consistently runs from a standardized environment, then using a binary tool built for this purpose might be possible and might make a lot of sense.

**Comment by krancour** [comment]
See this from @technosophos:

https://github.com/technosophos/jv

**Comment by jgmize** [comment]
See also https://stedolan.github.io/jq/

**Comment by bacongobbler** [comment]
etcd will be going away in v2 and we won't be able to get to this for the LTS release so I'm going to close this. :)
