### ISSUE TITLE
Check running platform version

### ISSUE THREAD

**Issue by adamreese** [deis/deis#4532]
Platform version is stored in a number of ways throughout Deis.  Checking the version at different stages in a cluster's life cycle varies. A source of truth should be defined to know if an upgrade is needed or if a upgrade was successful.

## Current state of versioning

`/etc/deis-release` is set on initial install but not updated to reflect running version if a platform upgrade is performed.
https://github.com/deis/deis/blob/master/contrib/coreos/user-data.example#L102-L104

Platform version is set for performing an upgrade.  This is a `desired` version and does not reflect what is running.
http://docs.deis.io/en/latest/managing_deis/upgrading-deis/#in-place-upgrade

## Proposal

Add component versions to `deisctl version` to check container `DEIS_RELEASE` environment variables.

```
Client:
    deisctl:        v1.10.1
API:
    controller:     v1.7
Platform:
	builder:        v1.10.1
	controller:     v1.10.1
	database:       v1.10.1
	logger:         v1.10.1
	logspout:       v1.10.1
	publisher:      v1.10.1
	registry:       v1.10.1
	router:         v1.10.1
	store-daemon:   v1.10.1
	store-gateway:  v1.10.1
	store-metadata: v1.10.1
	store-monitor:  v1.10.1
```

**Comment by Joshua-Anderson** [comment]
:+1: I like the idea. I might suggest looking at the image instead though, so people running deis images can tell what is being used. This information is stored in etcd, so it would be easy to retrieve from the server.


Ex:

```
Client:
    deisctl:        v1.10.1
API:
    controller:     v1.7
Platform:
    builder:        deis/builder:v1.10.1
    controller:     deis/controller:v1.10.1
    database:       deis/database:v1.10.1
    logger:         custom/logger:v0.0.1
    logspout:       deis 192.168.1.72/deis/logspout:git-ab12dgas2
    publisher:      deis/publisher:v1.10.1
    registry:       deis/registry:v1.10.1
    router:         other-user/router:v2.0.0
    store-daemon:   deis/store-daemon:v1.10.1
    store-gateway:  deis/store-gateway:v1.10.1
    store-metadata: deis/store-metadata:v1.10.1
    store-monitor:  deis/store-monitor:v1.10.1

**Comment by adamreese** [comment]
@Joshua-Anderson where is this stored in etcd?

**Comment by carmstrong** [comment]
> where is this stored in etcd?

Take a look at `/run/bin/deis/get_image` for details on this logic: https://github.com/deis/deis/blob/7421f01cbcd0c6be617b9c4c8f9e4408ef63f8b0/contrib/coreos/user-data.example#L113-L134

Basically, the order of precedence is:
* Component image in etcd: `/deis/<component>/image`
* Platform version in etcd: `/deis/platform/version`
* Platform version in `/etc/deis-release`

**Comment by adamreese** [comment]
Oh right, I know that it can be set in etcd for install.  It sounded like the running version was stored, which would have made this easy. ha

**Comment by carmstrong** [comment]
> It sounded like the running version was stored

Technically not, but each time a component is started, it calls `/run/deis/bin/get_image` to figure out what image it should use. So following that same logic is effectively the same thing.

**Comment by adamreese** [comment]
After an upgrade `/run/deis/bin/get_image` will give you the `expected` running version.  What I am hunting for is `actual` running version.  If a service does not stop/start properly it will still be on an old version

**Comment by adamreese** [comment]
Here is an example of why I am trying to report on `actual` version
https://gist.github.com/adamreese/85ef1d3453ef49e47cfd

**Comment by adamreese** [comment]
`/opt/bin/deis-debug-logs` could have incorrect version also
https://github.com/deis/deis/blob/7421f01cbcd0c6be617b9c4c8f9e4408ef63f8b0/contrib/coreos/user-data.example#L153-L154

**Comment by bacongobbler** [comment]
> After an upgrade /run/deis/bin/get_image will give you the expected running version. What I am hunting for is actual running version.

Ah yes. I see your problem now:

> If a service does not stop/start properly it will still be on an old version

so basically you want a real-time look at what's running in the cluster? Technically we could extend `deisctl list` to do this task, since its job is to display information about the components running in the cluster. Right now it's just a glorified `fleetctl list-units | grep deis-`, but would displaying the component itself be a nice way to display?

cc'ing @technosophos as this may be something interesting to look at for v2 w/ `kubectl describe rc deis-`

**Comment by msull92** [comment]
I was looking for this feature just yesterday trying to debug something. So definitely useful. :+1:

**Comment by bacongobbler** [comment]
kubectl gives us an accurate description of what's running in the cluster for v2. We won't be able to get to this for v1 so closing this as fixed in v2.
