### ISSUE TITLE
Deisctl Cluster Health

### ISSUE THREAD

**Issue by iancoffey** [deis/deis#4538]
As a pre-req of the update service client, deisctl requires a means by which to quickly determine if the cluster is in a consistent state. 

This could make use of the [deis version work](https://github.com/deis/deis/issues/4532), and should also determine if the clusters generally healthy enough for update (ceph, dead components, etcd quorum, etc).

The result should be useful to run by a human as a deisctl command, as well as for the update client to consume.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant (deisctl no longer exists) so I'm closing this.
