### ISSUE TITLE
Graceful Shutdown requires Ceph

### ISSUE THREAD

**Issue by sstarcher** [deis/deis#4539]
When using a stateless platform the graceful shutdown script can't be used as it assumes you are running ceph and the data store tooling.

The very last part of the graceful shutdown is still required by a stateless platform.  The nodes must be removed from ETCD.

On a similar note I don't see the graceful shutdown script removing the node from the ETCD Discovery URL.

**Comment by szymonpk** [comment]
It isn't always the case. In latest deis (at least in 1.9.1) deployments nodes added after initial setup (by default you get 3 node cluster, so nodes 4th.. 5th.. etc) are configured as proxies to first three nodes and they aren't part of etcd cluster so I think they can be removed safely. Or am I wrong?

**Comment by sstarcher** [comment]
They can be safely removed, but the first 3 nodes can not be safely removed.

One solution would be to split the graceful shutdown script into 2 seperate scripts.  One that gets used always to remove from etcd and the other that additional run if not running on a stateless platform.

**Comment by iancoffey** [comment]
@sstarcher thats essentially what my pr does https://github.com/deis/deis/pull/4554

The unit ordering needs some tweaking before its ready, but it should handle all of these use cases.

**Comment by mboersma** [comment]
Fixed by #4554. Thanks again @iancoffey. :v:

**Comment by iancoffey** [comment]
:beers:
