### ISSUE TITLE
proposal: atomic cert update

### ISSUE THREAD

**Issue by szymonpk** [deis/deis#4544]
There is no way to do 'atomic' certificate update, if I do `deis certs:remove tld.com && derts certs:add tld.crt tld.key`. Cert is changed on routers disk but nginx isn't restarted. It's required to have few minutes pause between each command or do some strange workarounds (restart routers by hand or add/remove certs for other apps where downtime is acceptable, then configuration is reloaded as one).

I'm not sure which component should be modified to achieve this, can controller instrument routers? (request certificate refresh?)

**Comment by krancour** [comment]
Possibly the controller could be modified to publish an additional etcd key corresponding to each cert.  The value of that key could be a hash or fingerprint of the cert.  This would be updated as certs are added/modified.  On the router side, where the cert is used in the nginx config, the value of that etcd key could be included (using confd as usual) as a comment.  The overall effect would be that when a cert is updated, a corresponding change to the nginx config also happens automatically, which would akso trigger confd to reload nginx config.

**Comment by deis-admin** [comment]
This issue was moved to deis/controller#1223
