### ISSUE TITLE
CoreOS Configuration

### ISSUE THREAD

**Issue by nasali** [deis/deis#4547]
I have a three-node Deis cluster running 1.10.0 and I'd like to tweak some of the SSHD configurations, inside of /etc/ssh/sshd_config, of the CoreOS boxes that run it.

How would I go about doing that?

**Comment by bacongobbler** [comment]
You should be able to edit the cloud config in contrib/coreos/user-data.example before provisioning to add your custom sshd config. If you want to change settings in an existing cluster, you'll have to do it manually.

**Comment by nasali** [comment]
@bacongobbler Thank you. 
It is an existing cluster, so that rules out editing the user-data file to customize sushi config. Attempting to manually edit the file doesn't seem to work, or at least not according to what I expect. Here's what I tried:
```
$ deisctl ssh router
Last login: Tue Sep 29 14:27:22 2015 from 10.21.1.130
 * *    *   *****    ddddd   eeeeeee iiiiiii   ssss
*   *  * *  *   *     d   d   e    e    i     s    s
 * *  ***** *****     d    d  e         i    s
*****  * *    *       d     d e         i     s
*   * *   *  * *      d     d eee       i      sss
*****  * *  *****     d     d e         i         s
  *   *****  * *      d    d  e         i          s
 * *  *   * *   *     d   d   e    e    i    s    s
***** *****  * *     ddddd   eeeeeee iiiiiii  ssss

Welcome to Deis			Powered by CoreOS
core@ip-10-10-2-108 ~ $ ls -alh /usr/share/ssh/sshd_config 
-rw------- 1 root root 138 May 27 03:35 /usr/share/ssh/sshd_config
core@ip-10-10-2-108 ~ $ sudo chmod u=rw /usr/share/ssh/sshd_config 
chmod: changing permissions of '/usr/share/ssh/sshd_config': Read-only file system
core@ip-10-10-2-108 ~ $ sudo su - 
ip-10-10-2-108 ~ # chmod -f u=rw /usr/share/ssh/sshd_config 
chmod: changing permissions of '/usr/share/ssh/sshd_config': Read-only file system
```

What am I missing here?

**Comment by bacongobbler** [comment]
In CoreOS-land, anything in /usr is [read-only](https://coreos.com/os/docs/latest/sdk-disk-partitions.html), but /etc is read/write. According to [this document](https://coreos.com/os/docs/latest/customizing-sshd.html), you'll have to edit cloud config so I'm not sure you'll be able to modify it in an existing cluster.

**Comment by nasali** [comment]
Okay, so the reason I went after the /usr/share/ssh/sshd_config is the fact that /etc/ssh/sshd_config is a symlink. Either way, making them writable is not going to happen since the filesystem is mounted with "ro" flag. I had hoped there is a way I can tweak the SSHD configuration without downtime, but I'm guessing that is not possible without mounting the filesystem read/write to then edit that file. Correct?

**Comment by bacongobbler** [comment]
On next reboot from an update, those sshd settings won't apply because the second rootfs will be booted (more info on the disk layout [here](http://www.chromium.org/chromium-os/chromiumos-design-docs/disk-format)). It's probably not as easy as mounting the rootfs and editing /usr/share/sshd_config, but I'd ask more in #coreos in IRC to see if someone else knows more about editing files under /usr. :)

**Comment by nasali** [comment]
@bacongobbler Thank you, once more, for all your help.
