### ISSUE TITLE
Etcd Backup and Restore

### ISSUE THREAD

**Issue by technosophos** [deis/deis#4559]
We need an etcd backup and restore procedure for a cluster. Right now, etcd could store only in ephemeral container FS, and a massive outage would wipe out all the data.

**Comment by krancour** [comment]
Is that something that should maybe be contributed upstream instead of in deis?  We can't be the only ones with that concern.

**Comment by carmstrong** [comment]
They added `backup` and `restore` commands to `etcdctl` in a recent release, so this should be pretty easy to implement: https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#disaster-recovery

**Comment by szymonpk** [comment]
In typical deployment (aws, azure) if you restore etcd backup from one cluster to another, shouldn't it fail miserably? For example due to addresses stored in etcd which won't match new cluster layout.

**Comment by bacongobbler** [comment]
If the cluster is still up, yes. However, those have a relatively short time-to-live, so we could backup the keys when the cluster is down.

**Comment by carmstrong** [comment]
> so we could backup the keys when the cluster is down.

I don't think that'd work, either - I think @szymonpk has a point here. fleet, for example, stores its cluster state in etcd (and I imagine state is machine-specific even if they're down). I'm sure there's a solution for this, but something we'll have to investigate.

**Comment by szymonpk** [comment]
Wouldn't it be simpler to do just postgres backup/restore and propagate missing etcd (certificates, domains, etc..) values by some script?

**Comment by bacongobbler** [comment]
@szymonpk that'll work for controller-set etcd keys, but not for things like `deisctl config platform set version=x`. Those are the keys that are not saved between cluster migrations.

Perhaps there's a way we could tune etcd to backup only keys without a TTL...

**Comment by szymonpk** [comment]
@bacongobbler why we would need to backup platform version keys? In case of total crash, I will setup probably same deis version (all version keys will be set[?]), only thing I'll be missing are probably keys from controller.

**Comment by crigor** [comment]
I was able to test etcd backup and restore using https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#disaster-recovery. 

I had 3 nodes and restored the etcd data on the same cluster. However, if one of the nodes is gone and is replaced by a new node, the data will be stale because the backup will have data like

```
/deis/store/hosts/10.21.1.113
/deis/store/hosts/10.21.1.114
/deis/store/hosts/10.21.2.78
```
Do we need to remove the key manually or selectively backup keys?

**Comment by bacongobbler** [comment]
@crigor those keys were basically what I was alluding to :) I believe the best way would be to see if we can back up all the keys that do **not** have a TTL. That way these "ephemeral" keys can be discarded and re-populated by the new components.

> why we would need to backup platform version keys?

So users can restore those keys and expect the same version as the previous cluster. `deisctl` does not set this automatically with `install platform`.

**Comment by bacongobbler** [comment]
etcd will be going away in v2 and we won't be able to get to this for the LTS release so I'm going to close this, but thank you very much for posting this :)
