### ISSUE TITLE
Issues with Controller v1.6.1

### ISSUE THREAD

**Issue by jwaldrip** [deis/deis#4560]
We are on 1.6.1 of deis and keep getting this nasty error from the registry: 

```
ResponseError: max number of clients reached 
return self.view_functions[rule.endpoint](**req.view_args) 
response = self.full_dispatch_request() 
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request 
if nativestr(self.read_response()) != 'OK': 
```

**Comment by mboersma** [comment]
It sounds like you're hitting a `gunicorn` limitation. Deis v1.6.1 uses [docker-registry v0.9.1 plus tweaks](https://github.com/deis/docker-registry/tree/new-repository-import-v091) with 4 worker processes, so it looks like you could use the [`GUNICORN_WORKERS`](https://github.com/deis/docker-registry/blob/new-repository-import-v091/contrib/gunicorn_config.py#L16) environment variable to increase the concurrent capacity. This would require building a custom container or modifying the systemd unit to pass that variable into the container with `-e`, but might be a workraround.

**Comment by jwaldrip** [comment]
What would be holding onto those connections? They don't ever seem to drop off.

**Comment by carmstrong** [comment]
> What would be holding onto those connections?

Do any of your CoreOS hosts show a lot of network connections? The builder will push to the registry after it builds an app, and the Docker daemons on the CoreOS hosts themselves will pull from the registry when an app deploys. So if there are active connections open, they should show up on the hosts.

Does restarting registry resolve the issue, even for a time?

**Comment by jwaldrip** [comment]
The issue was redis, we have since moved it to elasticache on AWS.
