### ISSUE TITLE
Cannot perform, deis info, deis create

### ISSUE THREAD

**Issue by robeferre** [deis/deis#4565]
Hi this issue happened several times, I can log in successfully but I cannot perform any deis comands inside my app directory. I just restarted the platform and the issue still happening. Its happening several times. Does anyone knows how to fix it?

root@james:/u01/deis_apps/app_test/deisBuilder# deis login http://deis.192.168.57.69.xip.io
username: admin
password:
Logged in as admin

root@james:/u01/deis_apps/app_test/deisBuilder# deis info
Error:
404 NOT FOUND
detail: Not found

All units seems to be working fine.

root@james:/u01/deis_apps/app_test/deisBuilder# deisctl list
UNIT                                    MACHINE                         LOAD    ACTIVE  SUB
deis-builder.service                    6f57887c.../192.168.57.66       loaded  active  running
deis-controller.service                 88e4817d.../192.168.57.65       loaded  active  running
deis-database.service                   88e4817d.../192.168.57.65       loaded  active  running
deis-kube-apiserver.service             6f57887c.../192.168.57.66       loaded  active  running
deis-kube-controller-manager.service    6f57887c.../192.168.57.66       loaded  active  running
deis-kube-kubelet.service               6f57887c.../192.168.57.66       loaded  active  running
deis-kube-kubelet.service               88e4817d.../192.168.57.65       loaded  active  running
deis-kube-kubelet.service               cd2b9b48.../192.168.57.67       loaded  active  running
deis-kube-proxy.service                 6f57887c.../192.168.57.66       loaded  active  running
deis-kube-proxy.service                 88e4817d.../192.168.57.65       loaded  active  running
deis-kube-proxy.service                 cd2b9b48.../192.168.57.67       loaded  active  running
deis-kube-scheduler.service             6f57887c.../192.168.57.66       loaded  active  running
deis-logger.service                     88e4817d.../192.168.57.65       loaded  active  running
deis-logspout.service                   6f57887c.../192.168.57.66       loaded  active  running
deis-logspout.service                   88e4817d.../192.168.57.65       loaded  active  running
deis-logspout.service                   cd2b9b48.../192.168.57.67       loaded  active  running
deis-publisher.service                  6f57887c.../192.168.57.66       loaded  active  running
deis-publisher.service                  88e4817d.../192.168.57.65       loaded  active  running
deis-publisher.service                  cd2b9b48.../192.168.57.67       loaded  active  running
deis-registry@1.service                 88e4817d.../192.168.57.65       loaded  active  running
deis-router@1.service                   6f57887c.../192.168.57.66       loaded  active  running
deis-router@2.service                   88e4817d.../192.168.57.65       loaded  active  running
deis-router@3.service                   cd2b9b48.../192.168.57.67       loaded  active  running
deis-store-daemon.service               6f57887c.../192.168.57.66       loaded  active  running
deis-store-daemon.service               88e4817d.../192.168.57.65       loaded  active  running
deis-store-daemon.service               cd2b9b48.../192.168.57.67       loaded  active  running
deis-store-gateway@1.service            6f57887c.../192.168.57.66       loaded  active  running
deis-store-metadata.service             6f57887c.../192.168.57.66       loaded  active  running
deis-store-metadata.service             88e4817d.../192.168.57.65       loaded  active  running
deis-store-metadata.service             cd2b9b48.../192.168.57.67       loaded  active  running
deis-store-monitor.service              6f57887c.../192.168.57.66       loaded  active  running
deis-store-monitor.service              88e4817d.../192.168.57.65       loaded  active  running
deis-store-monitor.service              cd2b9b48.../192.168.57.67       loaded  active  running
deis-store-volume.service               6f57887c.../192.168.57.66       loaded  active  running
deis-store-volume.service               88e4817d.../192.168.57.65       loaded  active  running
deis-store-volume.service               cd2b9b48.../192.168.57.67       loaded  active  running

**Comment by bacongobbler** [comment]
404 typically means that the app name was not found. Does it exist when you run `deis apps`? If not, what's the current status of the database?

**Comment by robeferre** [comment]
Its strange, I had to restart the platform, when the platform started the apps are not showing, I will try to redeploy. When I list conteiners running on coreos, all apps are running, but its not listing from "deis apps c" commands. Question:  When I destroy an app,  the docker images should be erased as well or I have to remove them mannually? I didn't destroy any app that are not showing.

The database seems to be working fine:

deis-database.service - deis-database
   Loaded: loaded (/run/fleet/units/deis-database.service; linked-runtime; vendor preset: disabled)
   Active: active (running) since Mon 2015-10-05 16:41:57 UTC; 40min ago


 Thanks @bacongobbler

**Comment by carmstrong** [comment]
@robeferre Also note that the Deis client infers the app name from the directory you're in based on the existence of the `deis` git remote. You can always specify the app name manually with `-a <app>`, as in: `deis info -a myapp`.

**Comment by robeferre** [comment]
The apps still running, I'm using kubernetes as scheduler.

CONTAINER ID        IMAGE                                   COMMAND                CREATED             STATUS              PORTS                                                              NAMES
42223c086f95        192.168.57.67:5000/rugged-fishbone:v2   "catalina.sh run"      5 minutes ago       Up 5 minutes                                                                           k8s_rugged-fishbone-cmd.941b040f_rugged-fishbone-v2-cmd-c2hkm_rugged-fishbone_2e2626b2-6b7f-11e5-b952-000c29fd65ad_86179568
3819b19fe49a        192.168.57.67:5000/deluxe-deadbolt:v2   "catalina.sh run"      5 minutes ago       Up 5 minutes                                                                           k8s_deluxe-deadbolt-cmd.18b703bb_deluxe-deadbolt-v2-cmd-6gs6g_deluxe-deadbolt_2df24468-6b7f-11e5-b952-000c29fd65ad_78993748
31ac0a939b17        192.168.57.67:5000/classy-windmill:v4   "catalina.sh run"      5 minutes ago       Up 5 minutes                                                                           k8s_classy-windmill-cmd.e60f0408_classy-windmill-v4-cmd-rebs8_classy-windmill_2e005162-6b7f-11e5-b952-000c29fd65ad_d92361cb
54fd5cec3ae4        gcr.io/google_containers/pause:0.8.0    "/pause"               5 minutes ago       Up 5 minutes                                                                           k8s_POD.e4cc795_deluxe-deadbolt-v2-cmd-6gs6g_deluxe-deadbolt_2df24468-6b7f-11e5-b952-000c29fd65ad_c1387beb
ac0edc7c8df7        192.168.57.67:5000/classy-windmill:v4   "catalina.sh run"      5 minutes ago       Up 5 minutes                                                                           k8s_classy-windmill-cmd.e60f0408_classy-windmill-v4-cmd-587e1_classy-windmill_2d50d2c4-6b7f-11e5-b952-000c29fd65ad_3cf5eb30
f001e8a61524        gcr.io/google_containers/pause:0.8.0    "/pause"               5 minutes ago       Up 5 minutes                                                                           k8s_POD.e4cc795_classy-windmill-v4-cmd-rebs8_classy-windmill_2e005162-6b7f-11e5-b952-000c29fd65ad_922778b9
2b0f12b4023a        gcr.io/google_containers/pause:0.8.0    "/pause"               5 minutes ago       Up 5 minutes                                                                           k8s_POD.e4cc795_rugged-fishbone-v2-cmd-c2hkm_rugged-fishbone_2e2626b2-6b7f-11e5-b952-000c29fd65ad_f5f326d4
70d22e673113        gcr.io/google_containers/pause:0.8.0    "/pause"               5 minutes ago       Up 5 minutes                                                                           k8s_POD.e4cc795_classy-windmill-v4-cmd-587e1_classy-windmill_2d50d2c4-6b7f-11e5-b952-000c29fd65ad_f63d59da

**Comment by krancour** [comment]
Stopping or restarting the platform only stops and restarts the platform components' containers.  It doesn't stop existing application containers.  It's normal that when the platform comes back up, the app container are still running.

It sounds to me like the most likely explanation here is that the database has lost some or all of its state.  Are you able to connect directly to the database and poke around the apps table to see if your app is listed there?

**Comment by robeferre** [comment]
@ krancour

I just destroyed all apps that I have created, and the Database table looks empty:

deis=# select * from api_app;
 uuid | created | updated | owner_id | id | structure
------+---------+---------+----------+----+-----------

I'm tring to figure out why the docker images related to my destroied apps has not been erased.
# -------------
# NODE 1
# -------------
core@coreos_1 ~ $ docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
192.168.57.66:5000/echoed-yearbook   v2                  5cfd8cf1e059        45 hours ago        795.2 MB
192.168.57.67:5000/rugged-fishbone   v2                  579a94317913        6 days ago          795.2 MB
192.168.57.67:5000/classy-windmill   v4                  396ba40043ea        6 days ago          795.2 MB
deis/router                          v1.10.1             b54973a4f497        2 weeks ago         35.22 MB
deis/publisher                       v1.10.1             23e3709f1d24        2 weeks ago         17.58 MB
deis/logspout                        v1.10.1             02a870675c74        2 weeks ago         15.47 MB
deis/logger                          v1.10.1             810f7cdfd922        2 weeks ago         14.9 MB
deis/builder                         v1.10.1             7bfb2d74ff7b        2 weeks ago         152.1 MB
deis/store-monitor                   v1.10.1             a035e3e596a2        2 weeks ago         379.6 MB
deis/store-metadata                  v1.10.1             f0127e076fbe        2 weeks ago         379.6 MB
deis/store-gateway                   v1.10.1             7989cbef9846        2 weeks ago         399.5 MB
deis/store-daemon                    v1.10.1             872b993588c7        2 weeks ago         379.6 MB
deis/registry                        v1.10.1             4e5b0f0435db        2 weeks ago         144.4 MB
deis/database                        v1.10.1             d00218251a12        2 weeks ago         180.9 MB
deis/controller                      v1.10.1             35710f0c155e        2 weeks ago         122.7 MB
alpine                               3.1                 8dd8107abd2e        3 weeks ago         5.037 MB
gcr.io/google_containers/pause       0.8.0               2c40b0526b63        6 months ago        241.7 kB


# -------------
# NODE 2
# -------------
core@coreos_2 ~ $ docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
192.168.57.66:5000/offset-keypunch   v2                  a2b50ae030d1        2 hours ago         876.5 MB
192.168.57.66:5000/preset-babushka   v2                  6858845710c7        2 hours ago         876.5 MB
192.168.57.66:5000/echoed-yearbook   v2                  5cfd8cf1e059        45 hours ago        795.2 MB
192.168.57.67:5000/classy-windmill   v3                  8e2d30e3a4b7        6 days ago          795.2 MB
192.168.57.67:5000/rugged-fishbone   v2                  579a94317913        6 days ago          795.2 MB
192.168.57.67:5000/classy-windmill   v2                  447b6fab235d        6 days ago          795.2 MB
192.168.57.67:5000/classy-windmill   v4                  396ba40043ea        6 days ago          795.2 MB
deis/router                          v1.10.1             b54973a4f497        2 weeks ago         35.22 MB
deis/publisher                       v1.10.1             23e3709f1d24        2 weeks ago         17.58 MB
deis/logspout                        v1.10.1             02a870675c74        2 weeks ago         15.47 MB
deis/logger                          v1.10.1             810f7cdfd922        2 weeks ago         14.9 MB
deis/builder                         v1.10.1             7bfb2d74ff7b        2 weeks ago         152.1 MB
deis/store-monitor                   v1.10.1             a035e3e596a2        2 weeks ago         379.6 MB
deis/store-metadata                  v1.10.1             f0127e076fbe        2 weeks ago         379.6 MB
deis/store-gateway                   v1.10.1             7989cbef9846        2 weeks ago         399.5 MB
deis/store-daemon                    v1.10.1             872b993588c7        2 weeks ago         379.6 MB
deis/registry                        v1.10.1             4e5b0f0435db        2 weeks ago         144.4 MB
deis/database                        v1.10.1             d00218251a12        2 weeks ago         180.9 MB
deis/controller                      v1.10.1             35710f0c155e        2 weeks ago         122.7 MB
alpine                               3.1                 8dd8107abd2e        3 weeks ago         5.037 MB
gcr.io/google_containers/pause       0.8.0               2c40b0526b63        6 months ago        241.7 kB
192.168.57.66:5000/wiggly-macaroni   v5                  99fa6fec60e2        13 months ago       637.1 MB
192.168.57.66:5000/calmer-doghouse   v7                  bc1b067e2ac1        13 months ago       676.8 MB

# -------------
# NODE 3
# -------------
core@coreos_3 ~ $ docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
192.168.57.66:5000/preset-babushka   v3                  f3bd71c6e3ef        About an hour ago   876.5 MB
192.168.57.66:5000/offset-keypunch   v3                  22154771ccaa        2 hours ago         876.5 MB
192.168.57.66:5000/rugged-fishbone   v6                  9c5b4be17ed0        5 hours ago         795.2 MB
192.168.57.66:5000/echoed-yearbook   v2                  5cfd8cf1e059        45 hours ago        795.2 MB
192.168.57.65:5000/nimbus-greenery   v2                  80bb449e5a42        2 days ago          795.2 MB
192.168.57.65:5000/junior-unicycle   v2                  12d5af12c820        3 days ago          795.2 MB
192.168.57.67:5000/classy-windmill   v3                  8e2d30e3a4b7        6 days ago          795.2 MB
192.168.57.67:5000/rugged-fishbone   v2                  579a94317913        6 days ago          795.2 MB
192.168.57.67:5000/classy-windmill   v4                  396ba40043ea        6 days ago          795.2 MB
192.168.57.67:5000/classy-windmill   v2                  2c5f811f3da6        6 days ago          795.2 MB
deis/router                          v1.10.1             b54973a4f497        2 weeks ago         35.22 MB
deis/publisher                       v1.10.1             23e3709f1d24        2 weeks ago         17.58 MB
deis/logspout                        v1.10.1             02a870675c74        2 weeks ago         15.47 MB
deis/logger                          v1.10.1             810f7cdfd922        2 weeks ago         14.9 MB
deis/builder                         v1.10.1             7bfb2d74ff7b        2 weeks ago         152.1 MB
deis/store-monitor                   v1.10.1             a035e3e596a2        2 weeks ago         379.6 MB
deis/store-metadata                  v1.10.1             f0127e076fbe        2 weeks ago         379.6 MB
deis/store-daemon                    v1.10.1             872b993588c7        2 weeks ago         379.6 MB
deis/registry                        v1.10.1             4e5b0f0435db        2 weeks ago         144.4 MB
deis/database                        v1.10.1             d00218251a12        2 weeks ago         180.9 MB
deis/controller                      v1.10.1             35710f0c155e        2 weeks ago         122.7 MB
alpine                               3.1                 8dd8107abd2e        3 weeks ago         5.037 MB
gcr.io/google_containers/pause       0.8.0               2c40b0526b63        6 months ago        241.7 kB
deis/slugrunner                      latest              cc4a0915354e        12 months ago       832.5 MB

Some apps PODs conteiners still running even when the app was destoied.

8e297480b0a9        gcr.io/google_containers/pause:0.8.0   "/pause"               27 hours ago        Up 27 hours                                                                            k8s_POD.e4cc795_cheery-pachinko-v2-cmd-iipkv_cheery-pachinko_170d030e-6bf4-11e5-948d-000c29fd65ad_74200f1f
571337e0571d        gcr.io/google_containers/pause:0.8.0   "/pause"               27 hours ago        Up 27 hours                                                                            k8s_POD.e4cc795_august-buttress-v2-cmd-iwb97_august-buttress_16543515-6bf4-11e5-948d-000c29fd65ad_1634b860
1f04a5fe9547        gcr.io/google_containers/pause:0.8.0   "/pause"               27 hours ago        Up 27 hours                                                                            k8s_POD.e4cc795_nimbus-greenery-v2-cmd-7a9hk_nimbus-greenery_184be0d3-6bf4-11e5-948d-000c29fd65ad_826a7d63
9dcab67f8e75        gcr.io/google_containers/pause:0.8.0   "/pause"               27 hours ago        Up 27 hours                                                                            k8s_POD.e4cc795_junior-unicycle-v2-cmd-fmdwj_junior-unicycle_17dc9727-6bf4-11e5-948d-000c29fd65ad_8288af02
c98eadea391d        gcr.io/google_containers/pause:0.8.0   "/pause"               27 hours ago        Up 27 hours                                                                            k8s_POD.e4cc795_oblong-whitecap-v2-cmd-n5ile_oblong-whitecap_18bab326-6bf4-11e5-948d-000c29fd65ad_ee698378

**Comment by davidcelis** [comment]
Any reason this issue was closed? I'm having the same problem with a recently created app, but another app that I have running on my cluster responds to these commands just fine

**Comment by bacongobbler** [comment]
@davidcelis if it doesn't show up in `deis apps:list`, that means there's no record of it in the database. Would you mind opening a new issue with the following information:

 - the version of Deis you're running
 - `deis --version` -- client version
- `deisctl journal controller`
 - a reproducible problem case (if possible)

Any info provided would be greatly appreciated. Thanks! :)

**Comment by carmstrong** [comment]
Also, triple-confirm that you're running the commands from the app's directory, or you're specifying the app with `--app`. The client infers what app you're working on based on its name or the existence of a git remote called `deis`.

**Comment by davidcelis** [comment]
I ended up finding #4096 and following steps there to remove the app's process found in `fleetctl`. There was definitely an entry for the app in the postgresql database. I was able to remove the process and then re-create the app (which, strangely enough, seemed only to add a git a remote and start working again)
