### ISSUE TITLE
Deis Registry miss /deis/store/gateway key while use S3 as storage

### ISSUE THREAD

**Issue by rvaralda** [deis/deis#4568]
I've got the error: "confd[641]: ERROR 100: Key not found (/deis/store) [366456]"

One option is to remove   "/deis/store/gateway" from registry/conf.d/config.toml
and from registry/conf.d/create_bucket.toml

Or a line like: store_gateway: {{if exists "/deis/store/gateway"}}{{ getv "/deis/store/gateway" }}{{ else }}""{{ end }} to config.yml

**Comment by jweller** [comment]
@rvaralda: I'm having this problem and tried your suggestion above (i.e., removed the /deis/store/gateway lines from the two conf files).  I then uninstalled and reinstalled the platform, but still seeing the same issue. Is there another step I might be missing?

**Comment by sstarcher** [comment]
Looks like the same issue on Deis 1.11.1 on AWS with statless-platform
```
Oct 20 16:57:35 ip-10-0-40-106.ec2.internal sh[1460]: 2015-10-20T16:57:35Z 342e5dda0840 confd[1597]: ERROR 100: Key not found (/deis/store) [13650]
Oct 20 16:57:35 ip-10-0-40-106.ec2.internal sh[1460]: 2015-10-20T16:57:35Z 342e5dda0840 confd[1597]: ERROR 100: Key not found (/deis/store) [13650]
Oct 20 16:57:35 ip-10-0-40-106.ec2.internal sh[1460]: registry: waiting for confd to write initial templates...
```

**Comment by sstarcher** [comment]
Previously we were setting the aws accessKey and the aws secret key.  Since we stopped this /deis/store did not exist.

After running the following everything looks fine
```deisctl config store set gateway=''```

**Comment by sstarcher** [comment]
My workaround of ```deisctl config store set gateway=''``` no longer functions in Deis 1.12.2 as the value is now validated
```Error: 'gateway' does not match the pattern 'key=var', ex: foo=bar```

**Comment by wintr-** [comment]
We've evolved your previous workaround to `deisctl config store set gateway='  '` with deisctl 1.12.2, and our cluster spun up.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776). The workaround will work for this use case and the architecture in deis v2 has dramatically changed such that this is no longer relevant so I'm closing this.

**Comment by sstarcher** [comment]
@bacongobbler so the intent is for the LTS version is for anyone who is using s3 as a ceph replacement with IAM instance keys is to use `deisctl config store set gateway=' '`

Maybe this should be documented if it won't be fixed for the LTS.

**Comment by bacongobbler** [comment]
good point. Let's doc this then :)
