### ISSUE TITLE
Possible inaccurate description of builder component

### ISSUE THREAD

**Issue by krancour** [deis/deis#4569]
https://github.com/deis/deis/blame/master/docs/understanding_deis/components.rst#L39

I thought we'd fixed this a while ago, but I guess not.  It's not quite accurate.  Configs are not actually ever baked into the images.

**Comment by krancour** [comment]
Ah... this commit partially clarified:

https://github.com/deis/deis/commit/2772232ec0b9b8aad92789ac336a134400e43e1a

But the note that was added still contradicts what is on line 39, so that could be confusing.

**Comment by krancour** [comment]
> Configs are not actually ever baked into the images.

I may actually have been mistaken on that point.  I'm looking into it.

**Comment by krancour** [comment]
>> Configs are not actually ever baked into the images.

> I may actually have been mistaken on that point. I'm looking into it.

So configs _do_ get baked into images, but it isn't the builder that does it.  The builder produces images that are devoid of "last mile" configs.  The builder triggers a release by calling a hook in the controller, and the controller _does_ bake configs into an image during the release process.

The process looks something like this:

build image + config == release image

Ultimately, yes... I do still want to clarify this bit of doc.

**Comment by bacongobbler** [comment]
closing as the documentation has drastically changed for v2. @krancour if you feel motivated and this is still relevant please re-open at https://github.com/deis/workflow :) thanks!
