### ISSUE TITLE
add pre/post deploy hook

### ISSUE THREAD

**Issue by shingara** [deis/deis#4579]
In dokku there are a simple plugin to run some pre/post deploy hook. It will be good to have this kind of feature on deis.

We can stop some service in pre hook and run some task in post deploy hook or notify some service

see the dokku plugin : https://github.com/mlomnicki/dokku-deploy-hooks

**Comment by jgmize** [comment]
see also: https://devcenter.heroku.com/articles/release-phase

**Comment by pmac** [comment]
Or even something as simple as [Heroku's new "release" process type](https://devcenter.heroku.com/changelog-items/908).

**Comment by bacongobbler** [comment]
@pmac see deis/slugubuilder#86. :)

**Comment by pmac** [comment]
@bacongobbler works for me. thanks!
