### ISSUE TITLE
Deis v2 Design Document

### ISSUE THREAD

**Issue by technosophos** [deis/deis#4582]
[Deisv2DesignDocument.pdf](https://github.com/deis/deis/files/10325/Deisv2DesignDocument.pdf)
Here is the link to the current design document for Deis v2:

https://docs.google.com/a/engineyard.com/document/d/1twPhGuLwRXMEtLoyQfx8_PEHt1YAEJKmblXqjTK2VlU/pub

It is backed by a Google Doc, but I don't seem to have the privileges to make comments visible. Feel free to leave comments inline here.

This is a work in progress. While the main concepts are solidifying pretty quickly, the details are all still in flux. We're still trying to iron out the details of how we can keep lots of people involved in the design process. If you have some ideas, feel free to share those here, too.

Here's how we went about writing this document:

- In late July and early August, I put together an initial version. It was more of a rough proposal for how we might switch from Fleet to Kubernetes, and reduce some tech debt along the way
- The core maintainers took a look at it and provided a lot of feedback. @bacongobbler and I made some changes. @aledbf and @carmstrong  made several very helpful comments when I was at this point.
- Over the last two months, @bacongobbler @kmala @smothiki and I did some explorations and I drafted out ideas as we had them. @sgoings and @krancour provided more feedback.
- Last month we introduced the ideas at the public release meeting. The document was taking shape at that point.
- A few days ago, @gabrtv @mboersma and I sat at a whiteboard and hashed out the basic architecture (and the splitting Deis into components). I redrafted accordingly, and prepared the document for release.
- At today's public release, we announced this document, and are looking forward to hearing some feedback.

I'll do my best to keep the document at the link above up to date. If I can figure out how to turn on comments, I will.

UPDAT: Attached as PDF document, since even Google Docs sharing seems disabled on our Google Apps instance.

**Comment by technosophos** [comment]
I'm sure I forgot a few names in there. My apologies.

**Comment by intellix** [comment]
Don't have the privileges to view it. Is this publicly available somewhere or only meant to be visible to a certain few?

**Comment by technosophos** [comment]
Looks like our Google Docs permissions are a little bit stricter than i thought. Attaching as a PDF.

**Comment by bacongobbler** [comment]
@technosophos while it may be a pain porting it over, would it make sense to formalize this in the official documentation i.e. docs.deis.io? That way we can get feedback and users can PR their thoughts on the v2 roadmap/design etc.

**Comment by nathansamson** [comment]
Like the design a lot, any timeplam? Eg after 1.12, or rather 1.13 or no clue yet and it might be after 1.20?

**Comment by technosophos** [comment]
@bacongobbler Good idea. Anyone else feel strongly one way or another?

@nathansamson My understanding is that 1.12 will be focused entirely on stability improvements, after which the 1.x line will go into LTS mode. All feature development will then be on the 2.x branch.

Some components will be ready fairly soon. But the entire platform... I think our view on that is that we will judge based on quality. So we don't have a fixed date.

One of the things I am very actively working on right now is figuring out what the pattern will be for our individual Deis repos. If you're interested in taking a look, my first cut is here: https://github.com/technosophos/prototype-repo

**Comment by jgmize** [comment]
> Overlay Networking: ​v2 will use F​lannel ​to provide a cluster­wide overlay network. We will use flannel’s default UDP ­based tunneling mechanism.

@technosophos as @aledbf pointed out in IRC earlier today, flannel has [backends](https://coreos.com/blog/introducing-flannel-0.5.0-with-aws-and-gce/) which manipulate provider IP routes instead of using overlay or encapsulation.  What do you think about updating the design doc to describe using them when available?

**Comment by yuvipanda** [comment]
Yes, we're using the VXLAN backend for flannel in production and it's a lot less CPU than using the default UDP userspace backend.

**Comment by jgmize** [comment]
> Yes, we're using the VXLAN backend for flannel in production and it's a lot less CPU than using the default UDP userspace backend.

To clarify, Deis v1 [currently uses VXLAN by default](https://github.com/deis/deis/blob/b07db69e9b3ad197d869fec4cb0b5a7051a0ef16/contrib/coreos/user-data.example#L56) and while moving the encapsulation to the kernel does help with performance, eliminating UDP encapsulation entirely by using a flannel backend like aws-vpc or gce should (in theory) give better performance than VXLAN.

**Comment by MaxenceAdnot** [comment]
@technosophos :
> My understanding is that 1.12 will be focused entirely on stability improvements, after which the 1.x line will go into LTS mode. All feature development will then be on the 2.x branch.

1.12 is now out, should we understand that 1.12 is the last version on the 1.X branch ? I've seen 1.13 mentioned in git commits. Any release date for Deis v2 ?

**Comment by carmstrong** [comment]
> I've seen 1.13 mentioned in git commits. Any release date for Deis v2 ?

We plan to release Deis 1.13 on schedule, and ship an alpha for v2 by the end of the year. A final release is slated for Q1 2016. We may have a 1.14, or 1.13 will be an LTS release - we haven't yet decided.

**Comment by bacongobbler** [comment]
Deis v2 has been released! Release post is here: https://deis.com/blog/2016/workflow-stable/

Thank you everyone for all your help and support!
