### ISSUE TITLE
Deis should send host header with health checks.

### ISSUE THREAD

**Issue by pmclanahan** [deis/deis#4585]
Many apps validate the "Host:" header as a security measure (e.g. Django does this by default). As such health check pings using just the IP will return a 400 unless the IP is specifically added to the config. The various health checks should therefore add a host header to the requests with the value being the FQDN for the app (e.g. `Host: friendly-dino.example.com`) so that apps can continue simply including the expected domains in the configuration.

**Comment by bacongobbler** [comment]
good thought.

**Comment by jgmize** [comment]
Note that we'll need to add the host header to the publisher health checks in addition to the controller health checks @pmclanahan has modified in #4586.

**Comment by bacongobbler** [comment]
@jgmize can you confirm if kubernetes health checks perform HTTP health checks as expected? That way we can determine if this is something we need to contribute upstream to fix for v2 or not.

**Comment by bacongobbler** [comment]
closing as something fixed in v2 with kubernetes' health checks.
