### ISSUE TITLE
app container failed to start

### ISSUE THREAD

**Issue by philippwiendl** [deis/deis#4589]
deis version

    1.10.1

docker version

    Client version: 1.7.1
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): df2f73d-dirty
    OS/Arch (client): linux/amd64
    Server version: 1.7.1
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): df2f73d-dirty
    OS/Arch (server): linux/amd64

/etc/os-release

    NAME=CoreOS
    ID=coreos
    VERSION=766.4.0
    VERSION_ID=766.4.0
    BUILD_ID=
    PRETTY_NAME="CoreOS 766.4.0"
    ANSI_COLOR="1;32"
    HOME_URL="https://coreos.com/"
    BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

commands like ps:restart and scale running forever. on one host i found the following problem
    
    docker run -ti --rm alpine:3.1 /bin/sh
    
    Cannot start container <id>: no available ip addresses on network

after rebooting the host everything was fine

**Comment by bacongobbler** [comment]
@philippwiendl this issue is a Docker issue, which is likely https://github.com/docker/docker/issues/14788 as some users have reported the same thing.

**Comment by philippwiendl** [comment]
@bacongobbler I know this is a Docker issue but deis client doesn't cover this kind of issue.
if I run `deis scale` or `deis ps:restart` it keeps running forever

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant so I'm closing this.
