### ISSUE TITLE
Cross zone load balancing disabled

### ISSUE THREAD

**Issue by jeff-lee** [deis/deis#4591]
Cross zone load balancing isn't enabled by default on the public load balancer in AWS.  I've been enabling it myself in the deis.template, but wanted to check to make sure there's not a reason it's disabled.

If not, I can submit a PR if it's helpful.

**Comment by krancour** [comment]
I cannot think of a reason for that to not be enabled.

**Comment by krancour** [comment]
And I would agree it's a useful improvement.

**Comment by jeff-lee** [comment]
Actually...reading up a bit more on the [proxy protocol docs](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html).

We had a huge issue ( EY-103355 ) a while ago where we weren't able to build because attempts to do a git push were hanging when using "git push deis master", but succeeded when we pushed directly to the IP of the builder.

At the time, I could see the calls make it down to the builder, but they stopped after trying to do the initial ssh negotiation.  When I recreated port 2222 on the load balancer, I was prompted for the host authorization and everything worked again.

It felt like an ssh issue, but we never found the root cause.  @crigor could the source IP information passed along by proxy protocol have caused ssh authentication issues if passed across AZs?

**Comment by krancour** [comment]
Keep in mind that traffic bound for the builder is actually proxied through the routers.  Even when cross-zone load-balancing isn't on, requests bound for the builder may arrive at _any_ of the routers and may then cross zones from there if the router it hits isn't in the same zone as the builder-- which will be likely the majority of the time if you're running 3+ routers to the one builder.  Enabling cross zone load balancing shouldn't affect that equation.

**Comment by krancour** [comment]
And if I am wrong, CI will catch this.

**Comment by jeff-lee** [comment]
Ok.  Just thought I'd mention it.  FWIW, there were several issues leading up to the eventual push failures including the builder bouncing around across AZs from and to router nodes, so the final resting place of the builder was far from the host it was originally on where there were no problems pushing.

I'll put together a quick PR for the change.

**Comment by krancour** [comment]
@jeff-lee are you running stateless / cephless?  Just curious.

**Comment by jeff-lee** [comment]
@krancour Not at the moment, but I'm considering it.

**Comment by krancour** [comment]
Unassigning myself.  This is easy and not critical... leaving it to the community to address.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to fixing for the LTS release, and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this. If someone wants to tackle this then that would be nice, otherwise we won't be assigning any people power to get this implemented.
