### ISSUE TITLE
problems running deis installer azure

### ISSUE THREAD

**Issue by pdaniel-frk** [deis/deis#4593]
Hello,

I have a problem running the deis installer. I don;t know if this is a problem with azure-cli or something else. When i run the command detailed in the documentation i get this error:

info:    Executing command group create
verbose: Getting resource group deis
verbose: Creating resource group deis
info:    Created resource group deis
error:   Unexpected token

info:    Error information has been recorded to /home/appsmart/.azure/azure.err
verbose: SyntaxError: Unexpected token

  <<< async stack >>>
    at Object.parse (native)
    at createDeploymentParameters (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils._js:246:37)
  at exports_createDeployment__1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils._js:69:28)
  at group_createResourceGroup__3 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group._js:121:18)
  at __1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group._js:53:32)
  <<< raw stack >>>
    at Object.parse (native)
    at __$createDeploymentParameters (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils._js:246:37)
    at __$createDeploymentParameters (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils._js:286:7)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at createDeploymentParameters (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils._js:224:10)
    at __$exports_createDeployment__1 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils._js:57:12)
    at __func (/usr/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:47:5)
    at Object.exports_createDeployment__1 [as createDeployment] (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/groupUtils._js:54:10)
    at __$group_createResourceGroup__3 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group._js:118:33)
    at __$group_createResourceGroup__3 (/usr/lib/node_modules/azure-cli/lib/commands/arm/group/group._js:124:13)

error:   group create command failed

I try to install the cluster for 3 days now. It's a little annoying.

**Comment by carmstrong** [comment]
@pdaniel-frk Can you post the commands you're running and a gist of your `parameters.json` file (with sensitive information hiddne)? I think something in there is probably malformed.

**Comment by pdaniel-frk** [comment]
parameters.json 

https://gist.github.com/pdaniel-frk/cdd2e317f00c5dd57fdf

The command that i run :

azure group create -n "deis" -l "North Europe" -f arm-template.json -e parameters.json  -v

Regards

**Comment by carmstrong** [comment]
@pdaniel-frk I suspect your issue is with the line breaks in your `customData`: https://gist.githubusercontent.com/pdaniel-frk/cdd2e317f00c5dd57fdf/raw/095b8279fe0210ae40fc689f8e7267ec7cd1ba1e/parameters.json

You'll need to remove those and make it one (long) line.

**Comment by pdaniel-frk** [comment]
For other facing a similar problem try running something like this after you generate azure-user-data :

CLOUDINIT=azure-user-data;INITCONTENT=`cat "$CLOUDINIT"|base64 -w 0`;echo "\"customData\":{\"value\":\"$INITCONTENT\"}" > updatepattern.txt;PARAMETERS=parameters.json;cat $PARAMETERS | tr '\n' ' ' | sed "s/\"customData[^{]*{[^}]*}/$(sed 's:/:\\/:g' updatepattern.txt)/" > params.json

then the command :

azure group create --name deis --location "West US" --deployment-name deis --template-file arm-template.json --parameters-file params.json

Thx carmstrong.

**Comment by pdaniel-frk** [comment]
Ok, now the command is sent to azure. But the resource still fail to be created. I get this error in azure 

{"error":{"code":"InvalidDomainNameLabel","message":"The domain name label 2 is invalid. It must conform to the following regular expression: ^[a-z][a-z0-9-]{1,61}[a-z0-9]$.","details":[]}}

Regards.

**Comment by carmstrong** [comment]
@pdaniel-frk Looks like the error is pretty clear: `The domain name label 2 is invalid. It must conform to the following regular expression: ^[a-z][a-z0-9-]{1,61}[a-z0-9]$.`. Try without dashes or spaces.

**Comment by pdaniel-frk** [comment]
ok, but where is the config for domain name. Sorry if i am noob, but it's my first time trying to deploy a coreos cluster.

Reagrds.

**Comment by carmstrong** [comment]
> ok, but where is the config for domain name

What are you naming the hosted service?

**Comment by pdaniel-frk** [comment]
if you mean 

 "publicDomainName": {
    "value": "deisappsmart2015"
  },

**Comment by sgoings** [comment]
FWIW these errors are being spit out by the Azure ARM provisioning process (not CoreOS, Deis, etc.). Don't get too discouraged... :smile: 

You might want to go into the Azure Portal and look at the resources/failed deployment so you can understand exactly which component failed and why. There are two possibilities: `publicDomainName` and `dnsPrefixNameForPublicIP`.

**Comment by pdaniel-frk** [comment]
Thank you for the info. I reviewed my data and now the machines are provisioned on azure. 

I moved to the next step. I installed deisctl, i exported export DEISCTL_TUNNEL="x.x.x.x.xip.io"
and executed ./deisctl config platform set sshPrivateKey=~/.ssh/deis

I get this error : 
Error: failed initializing SSH client: timed out while initiating SSH connection

I don't know if it is a problem with my public key or i need to setup a specific port for deisctl to connect to my servers.

**Comment by pdaniel-frk** [comment]
If i ssh only to one machine ssh core@x.x.x.x i can get into the machine. Through load balancer ip i cannot

**Comment by carmstrong** [comment]
> If i ssh only to one machine ssh core@x.x.x.x i can get into the machine. Through load balancer ip i cannot

That is to be expected - the load balancer does not forward traffic. Each instance was given a public IP address. You'll need to set the `DEISCTL_TUNNEL` to one of the instance IP addresses, as we say in the last step of the documentation: http://docs.deis.io/en/latest/installing_deis/azure/

**Comment by pdaniel-frk** [comment]
Ok, i put the ip of node in DEISCTL_TUNNEL. with ssh core@x.x.x.x i can login to the machine. Executing deisctl commands does not seems to work.

./deisctl config platform set sshPrivateKey=~/.ssh/deis

i get 

Error: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Put http://127.0.0.1:4001/v2/keys/deis/platform/sshPrivateKey: ssh: rejected: connect failed (Connection refused)]) [0]


executing deisctl list i get

INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: ssh: rejected: connect failed (Connection refused)
ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 100ms

**Comment by pdaniel-frk** [comment]
If i execute this command from one of the machines, i get some errors

core@deisNode0 ~ $ fleetctl -debug=true list-machines
2015/10/15 00:04:42 DEBUG http.go:28: HTTP GET http://domain-sock/fleet/v1/machines?alt=json
2015/10/15 00:04:42 DEBUG http.go:31: HTTP GET http://domain-sock/fleet/v1/machines?alt=json 503 Service Unavailable
Error retrieving list of active machines: googleapi: Error 503: fleet server unable to communicate with etcd
core@deisNode0 ~ $

**Comment by pdaniel-frk** [comment]
So, i managed to install the platform. My previous error was because the ./create-azure-user-data $(curl -s https://discovery.etcd.io/new) command was not inserting correctly the discovery url in my generated user data file. I cannot execute deis commands outlined in the documentation. Wehn i try to run deis register i get "deis: command not found". Any ideas? Thx.

**Comment by sgoings** [comment]
I'd be interested to see what the result of an `etcdctl cluster-health` is on this cluster. We've seen lots of situations where etcd will start to fall apart during the Deis installation/start process on Azure.

**Comment by pdaniel-frk** [comment]
Managed to deploy my cluster. Now i have another problem. I tried to deploy an app 
https://github.com/jumbojett/deis-ui The seems to be deployed, i think. But when i try to acces the app
at deisgui.xxx.com i get

404 Not Found
nginx/1.9.4

I also tried http://deisgui.x.x.x.x.xip.io/, with the ip of one of the machine.
I tried with the ip of the load balancer http://deisgui.<loadbalancerip>.xip.io/

Any ideas?

**Comment by pdaniel-frk** [comment]
So i managed to deploy my first app. A php example. Thx for your support. I will close this issue now. 
My previous error was due to the fact that the command create-azure-user-data did not correctly parse  the user-data-template and replace DISCOVERY_URL. I had to input by hand the url for discovery.
