### ISSUE TITLE
/deis/logs/drain was unset after upgrade 1.9.1 => 1.11.1

### ISSUE THREAD

**Issue by kalbasit** [deis/deis#4596]
Upgraded my stateless-platform to 1.11.1 (see #4595 for details). I had `/deis/logs/drain` set to a papertrail destination but after I did not see any logs there:

```
kalbasit@cratos ~ {dailymotion}  % deisctl config logs get drain

kalbasit@cratos ~ {dailymotion}  %
```

**Comment by krancour** [comment]
@kalbasit prior to v1.11.0, if you were running stateless, you would have been running without logger and would have had _logspout_ configured to send logs directly to Papertrail or wherever.  That actually wouldn't have been configured using `/deis/logs/drain`, but rather using `/deis/logs/host` and `/deis/logs/port`.  So, I'm guessing that maybe `/deis/logs/drain` was actually _not_ set for you prior to the upgrade.  If you set it now, everything should work.

**Comment by kalbasit** [comment]
Oh right thanks for clarifying. Worth a note perhaps in the docs? Probably, anyone updating to 1.11.1 from a stateless platform will run into the same issue.

**Comment by krancour** [comment]
Agreed.  I'm going to close this and open a separate issue against the doc.
