### ISSUE TITLE
Could not find some docker images (tag: v1.11.1)

### ISSUE THREAD

**Issue by CloudSide** [deis/deis#4598]
Could not find some docker images (tag: v1.11.1):

```
deis/cache:v1.11.1
deis/mesos-master:v1.11.1
deis/mesos-slave:v1.11.1
deis/mesos-marathon:v1.11.1
deis/zookeeper:v1.11.1
```

**Comment by carmstrong** [comment]
We removed the cache component recently. It looks like the others are commented-out in the test-acceptance job, so they are no longer being pushed. Here's the run for Deis v1.11.1: https://ci.deis.io/job/test-acceptance/76/console

@mboersma Do you recall why we removed these components from the job?

**Comment by mboersma** [comment]
They should have been built and pushed, but there was a compile error previously in the mesos/ dir and we probably forgot to re-enable those images. I will rebuild and push them in a few minutes.

**Comment by mboersma** [comment]
I re-ran the build job and verified the v1.11.1 mesos-* images are available from Docker Hub. Sorry about that @CloudSide--please let us know if you find any other problems.

**Comment by CloudSide** [comment]
@carmstrong @mboersma  thanks. 
no problems
