### ISSUE TITLE
Logger is not draining logs in 1.11.1

### ISSUE THREAD

**Issue by geeksoul-me** [deis/deis#4599]
Just upgraded stateless platform from 1.11.0 to 1.11.1, logs stopped appearing in my paper trail. 
On further investigation, found out that deis-logger service was not running/installed at all. So, installed and started deis-logger, but no luck. Logs still didn't show up. Storage and drain config were all proper.

Finally, uninstalled the platform and reinstalled 1.11.0, logs are back.

**Comment by krancour** [comment]
There were no changes to logging in the patch release.

**Comment by carmstrong** [comment]
> On further investigation, found out that deis-logger service was not running/installed at all.

That seems to be the hiccup. There is probably also an orchestration dependency on start that required you to restart the platform when logger failed to start. Deis v2 will mean we're no longer using fleet for control plane scheduling, improving component reliability.

I don't think there's anything to resolve here on our end, but thanks for reporting it!
