### ISSUE TITLE
Deis controller flipping

### ISSUE THREAD

**Issue by foxycoder** [deis/deis#4601]
Hi,

It seems to me that there is something wrong with my config state for the controller. It looks like it keeps receiving different values for the controller config, thus rewriting and restarting nginx. See the output below.

My platform version:

```
deisctl config platform get version
v1.11.0
```

My Controller keeps spitting out the following output:

```
Oct 12 13:53:55 ip-xxx sh[3667]: [2015-10-12 13:53:55 +0000] [172] [INFO] Booting worker with pid: 172
Oct 12 13:54:00 ip-xxx sh[3667]: [2015-10-12 13:54:00 +0000] [120] [INFO] Handling signal: hup
Oct 12 13:54:00 ip-xxx sh[3667]: [2015-10-12 13:54:00 +0000] [120] [INFO] Hang up: Master
Oct 12 13:54:00 ip-xxx sh[3667]: [2015-10-12 13:54:00 +0000] [190] [INFO] Booting worker with pid: 190
Oct 12 13:54:00 ip-xxx sh[3667]: [2015-10-12 13:54:00 +0000] [171] [INFO] Worker exiting (pid: 171)
Oct 12 13:54:00 ip-xxx sh[3667]: [2015-10-12 13:54:00 +0000] [170] [INFO] Worker exiting (pid: 170)
Oct 12 13:54:00 ip-xxx sh[3667]: [2015-10-12 13:54:00 +0000] [172] [INFO] Worker exiting (pid: 172)
Oct 12 13:54:00 ip-xxx sh[3667]: [2015-10-12 13:54:00 +0000] [173] [INFO] Worker exiting (pid: 173)
Oct 12 13:54:00 ip-xxx sh[3667]: [2015-10-12 13:54:00 +0000] [192] [INFO] Booting worker with pid: 192
Oct 12 13:54:00 ip-xxx sh[3667]: [2015-10-12 13:54:00 +0000] [174] [INFO] Worker exiting (pid: 174)
Oct 12 13:54:00 ip-xxx sh[3667]: [2015-10-12 13:54:00 +0000] [191] [INFO] Booting worker with pid: 191
Oct 12 13:54:00 ip-xxx sh[3667]: [2015-10-12 13:54:00 +0000] [193] [INFO] Booting worker with pid: 193
Oct 12 13:54:00 ip-xxx sh[3667]: [2015-10-12 13:54:00 +0000] [194] [INFO] Booting worker with pid: 194
```

Is there a (manual) fix for this? E.g. to get my config in a consistent state somehow?

Thanks

**Comment by foxycoder** [comment]
Oh it also keeps rewriting the SSH fingerprint, very annoyingly. So every `git push`, I need to remove the old value from my `known_hosts` file... Not sure if that's related to the controller or the builder? 

And deploys fail a lot with:

```
2015/10/12 13:47:34 failed retrieving config from controller: <h1>Server Error (500)</h1>
```

`deis config:set` fails often too..

I'd appreciate any help! Thanks in advance.

**Comment by foxycoder** [comment]
Could it be related to the certs that fail to init here in one of the routers? http://pastebin.com/UC2GS55y

**Comment by krancour** [comment]
@foxycoder can you give an example of some of the config keys whose values are changing frequently.  I hope this is not the case, but often times, inconsistent results from etcd can be an indicator that the cluster is not healthy.

**Comment by gabrtv** [comment]
@foxycoder another thing to check is `docker ps` on all hosts to look for any orphaned/old versions of Deis containers.  On upgrades prior to v1.9, it was possible to wind up with (for example) 2 database containers -- which would cause the kind of flapping you're seeing.

**Comment by foxycoder** [comment]
@gabrtv wow thanks, that was indeed the case! Although it was a v1.11.0 cluster that I upgraded to v1.11.1.

Thanks again!
