### ISSUE TITLE
stale discovery URL when adding hosts

### ISSUE THREAD

**Issue by aespinosa** [deis/deis#4602]
It should be noted in https://github.com/deis/deis/blob/master/docs/managing_deis/add_remove_host.rst#adding-a-node that when an etcd cluster has been running for a long time and all the original bootstrapped notes are already replaced with new ones from a long time, the discovery URLs list of nodes is completely stale.

At this point the proxy configuration is now required to list all the nodes manually with `--initial-cluster`

**Comment by krancour** [comment]
@aespinosa, you're absolutely right.  I think this ties into a larger issue.  Speaking for myself, my understanding of how to run rock solid etcd clusters in production is always evolving.  A big and recent realization is that we probably should not use auto-scaling groups or the etcd discovery service for managing etcd peers in production.  See #4645 for discussion on that.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant so I'm closing this.
