### ISSUE TITLE
Feature request - HTTP/2 support

### ISSUE THREAD

**Issue by myyk** [deis/deis#4603]
I know Nginx >= 1.9.5 supports HTTP/2 routing. I'm not sure if upgrading from 1.9.4 to 1.9.5 is enough. It would be nice to have this, so I could use it for `GRPC` services.

**Comment by mboersma** [comment]
The decision was to take it slow: see #4542. So Deis will probably catch up with nginx 1.9.6, is the current plan.

**Comment by myyk** [comment]
Thanks for the dedupe.
