### ISSUE TITLE
bug(client): New deis go client does not read `Procfiles` from current directory during `deis pull`

### ISSUE THREAD

**Issue by sbuss** [deis/deis#4605]
The [old behavior](https://github.com/deis/deis/blob/v1.9.1/client/deis.py#L1038-L1052) of `deis pull some-image -a myapp --procfile` would read a file named `Procfile` from the current directory. As of `deis-1.10`, the client [no longer reads `Procfile`](https://github.com/deis/deis/blob/v1.10.1/client/cmd/builds.go#L45-L53).

CC @Joshua-Anderson

**Comment by Joshua-Anderson** [comment]
This should be a simple fix. I'll see if I can quickly fix this.

**Comment by sbuss** [comment]
FWIW the `--procfile` option doesn't appear to be working at all for me in the go client:

Given this Procfile:

```yaml
web: run_scripts/web.sh
worker: run_scripts/worker.sh
beat: run_scripts/beat.sh
```

I serialized it to one line via:

```sh
$ PROCFILE=$(python -c "import yaml;print(yaml.dump(yaml.load(open('Procfile'))))")
$ echo $PROCFILE
{beat: run_scripts/beat.sh, web: run_scripts/web.sh, worker: run_scripts/worker.sh}
```

Then I tried passing that in via the `--procfile` flag and scale it:

```
$ ~/deis/deis-1.11.1 pull foo-image -a foo-app -p "$PROCFILE"
Creating build... done
$ ~/deis/deis-1.11.1 scale web=1 -a foo-app
Scaling processes... but first, coffee!
Error: 
400 BAD REQUEST
detail: Container type web does not exist in application
```

This might be bad yaml, but the go client didn't complain about it. I'm not sure what to do here.

**Comment by Joshua-Anderson** [comment]
PR #4606

**Comment by Joshua-Anderson** [comment]
The yaml string `{beat: run_scripts/beat.sh, web: run_scripts/web.sh, worker: run_scripts/worker.sh}` is properly parsed, so that indicates that either the client is making a bad request or there is a controller bug. I can't get a cluster up at the moment but I can test later.

**Comment by sbuss** [comment]
@Joshua-Anderson have you had a chance to test the `--procfile` flag? This was some core behavior we rely on and can't upgrade if its missing.

**Comment by Joshua-Anderson** [comment]
@sbuss I haven't, but you should be able to use the old oython client without issue (just some warnings).

**Comment by Joshua-Anderson** [comment]
@sbuss I wasn't able to reproduce locally.

``` shell
$ deis pull deis/example-go -a a -p "{beat: rcripts/beat.sh, web: run_scripts/web.sh, worker: run_scripts/worker.sh}"
$ deis scale asdf=1 -a a
Scaling processes... but first, coffee!
Error: 
400 BAD REQUEST
detail: Container type asdf does not exist in application
$ joshua-anderson@josh-steambox:~$ deis scale beat=1 -a a
Scaling processes... but first, coffee!
done in 14s
=== a Processes
--- beat:
beat.1 up (v2)
```
