### ISSUE TITLE
Error pulling image deis/slugbuilder

### ISSUE THREAD

**Issue by arkkanoid** [deis/deis#4607]
Hi!
I'm deploying a lot of apps on each node to test Deis. In one of these nodes, the /var/lib/docker path was full. I deleted some images to get free space. Now when I deploy an app, I get this error:
 
Counting objects: 292, done.
Compressing objects: 100% (277/277), done.
Writing objects: 100% (292/292), 920.68 KiB | 0 bytes/s, done.
Total 292 (delta 42), reused 0 (delta 0)
Unable to find image 'deis/slugbuilder:latest' locally
Pulling repository deis/slugbuilder
ef7aa6e95d41: Pulling image (latest) from deis/slugbuilder
ef7aa6e95d41: Pulling image (latest) from deis/slugbuilder, endpoint: https://registry-1.docker.io/v1/
ef7aa6e95d41: Pulling dependent layers
511136ea3c5a: Pulling metadata
511136ea3c5a: Pulling fs layer
511136ea3c5a: Error downloading dependent layers
ef7aa6e95d41: Error pulling image (latest) from deis/slugbuilder, endpoint: https://registry-1.docker.io/v1/, Mktemp failed: mkdir /var/lib/docker/graph: no such file or directory
ef7aa6e95d41: Error pulling image (latest) from deis/slugbuilder, Mktemp failed: mkdir /var/lib/docker/graph: no such file or directory
time="2015-10-13T07:31:56Z" level="fatal" msg="Error pulling image (latest) from deis/slugbuilder, Mktemp failed: mkdir /var/lib/docker/graph: no such file or directory" 

The /var/lib/docker/graph exist in all nodes.
I can execute on each node 'docker pull deis/slugbuilder' succesfully, but the error executing 'git push deis master' persist.

How can I solve it?

**Comment by bacongobbler** [comment]
@arkkanoid have you tried rebooting the builder? That does seem like an odd issue to have, though.
