### ISSUE TITLE
Consider shipping a custom Docker build

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#4610]
Lately, we've been bit by several major Docker bugs, including:
* https://github.com/docker/docker/issues/9718 (simultaneous pulls)
* https://github.com/docker/docker/issues/8539 (out-of-memory issues)

Issues/PRs affected:
#4609
#4590
#4238
#2975
#4536

As it stands now, there isn't a version of Docker that we consider stable that is even remotely recent (pre-Docker 1.5). Docker claims that the simultaneous pull issue is fixed in master, but Docker 1.9 won't ship for several more weeks, and it's likely that it won't make it to CoreOS stable for another month or two after that. We should investigate building our own and shipping that on CoreOS.

**Comment by krancour** [comment]
It seems we've elected not do do this.  Closing.
