### ISSUE TITLE
Encrypt the router<->container link

### ISSUE THREAD

**Issue by sbuss** [deis/deis#4611]
Deis should support encrypting the router<->container hop.

My company's services must be HIPAA compliant. That means that we can't have any unencrypted personal health information (PHI) ever hitting the wire. Currently we're using Deis for internal tools with a strict no-PHI policy, but we'd like to open up usage to teams that do handle PHI.

Unfortunately, the mullet VIP (TLS in the front, party in the back) that Deis uses by default makes this impossible.

Given the current architecture of Deis, I think the only two options are:

1. Terminate TLS in the router, but make a new TLS connection to a container, which requires:
    1. Add support for setting `https` for `proxy_pass`'s protocol, depending on an app's config
    2. Allow configuring a self-signed cert for the routers to trust OR let Deis generate and inject private keys into containers, which Deis is pre-configured to trust
2. Only Terminate TLS in the container, which requires:
    1. Add support for setting `https` for `proxy_pass`'s protocol, depending on an app's config
    2. Configure routing affinity to allow TLS sessions to be set up and used correctly

Are there any plans for encrypting the final hop in the works?

Note that in #deis @Joshua-Anderson suggested "It could be interesting v2 feature. The k8s proxy could rencrypt traffic and then expose the keys to app containers."

**Comment by krancour** [comment]
@sbuss we're investigating the feasibility of adding this feature now in 1.x.  It's definitely a gap that needs to be addressed.

**Comment by myyk** [comment]
We are also trying to investigate it. I think that NGINX re-encrypting to the backend is probably the easiest way forward since that's supported in NGINX with the `proxy ssl` flag.

**Comment by bacongobbler** [comment]
ping @krancour, what's the status on e2e https in v2? :)

**Comment by krancour** [comment]
This feature will be added in v2 and is now tracked in deis/workflow#355, as such, I am closing this.
