### ISSUE TITLE
Deis omits tag environment when a limit is set

### ISSUE THREAD

**Issue by arkkanoid** [deis/deis#4613]
Hi!
I have one app deployed in an specific environment, running: 
deis tags:set environ=dev -a myapp
It's delployed correctly in a 'dev' node.

When I execute:
 deis limits:set web=128M -c web=80 -a myapp
The app is deployed in another node, not in the node specified by the environment tag. 
I think that the app should be deployed in the same environment.

Thanks.

**Comment by bacongobbler** [comment]
@arkkanoid could you please post the systemd unit that is dropped on the other node? That would be interesting to see if the environ tag was omitted somehow.

**Comment by carmstrong** [comment]
It'd also be helpful to see `fleetctl list-machines` to confirm the expected machines are tagged as "dev".

**Comment by arkkanoid** [comment]
It was my fault, I had an error in my user-data file
Thanks!
