### ISSUE TITLE
Cant  start the platform in 1.11.1

### ISSUE THREAD

**Issue by robeferre** [deis/deis#4615]
I just reinstalled my cluster using the version 1.11.1 but when I start the platform the execution hangs on:

root@james:~/deis_install/deis/store# deisctl start platform
● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●
Storage subsystem...
deis-store-monitor.service: activating/auto-restart

I tried to debug executing this command:
coreos001 units # journalctl -fu deis-store-monitor

and I got:
Oct 14 18:47:50 coreos001 systemd[1]: Failed to start deis-store-monitor.
Oct 14 18:47:50 coreos001 systemd[1]: deis-store-monitor.service: Unit entered failed state.
Oct 14 18:47:50 coreos001 systemd[1]: deis-store-monitor.service: Failed with result 'resources'.
Oct 14 18:47:50 coreos001 systemd[1]: Starting deis-store-monitor...

Its just happening when I try the new version, the olders versions was working fine.

I included the domain and uploaded my key, the etcd cluster and fleet is working fine as well.

Any clue?

Thanks a lot

**Comment by rochacon** [comment]
@robeferre deis-store-monitor is a global unit, did it failed on all machines? Have you checked the logs directly from the deis-store-monitor container on every node?

If possible, please add more log output to this issue, there is not much info to help you out. The result of `fleetctl list-units | grep deis-` would be helpful too.

**Comment by robeferre** [comment]
@rochacon Thanks a lot for your help,

The "deis-store-monitor container" containers has not started until the "deis start platform" freezes. all my cluster nodes logs has printed the same error loop:

Oct 14 20:15:15 coreos003 systemd[1]: Starting deis-store-monitor...
Oct 14 20:15:20 coreos003 systemd[1]: deis-store-monitor.service: Service hold-off time over, scheduling restart.
Oct 14 20:15:20 coreos003 systemd[1]: deis-store-monitor.service: Failed to load environment files: No such file or directory
Oct 14 20:15:20 coreos003 systemd[1]: deis-store-monitor.service: Failed to run 'start-pre' task: No such file or directory
Oct 14 20:15:20 coreos003 systemd[1]: Failed to start deis-store-monitor.
Oct 14 20:15:20 coreos003 systemd[1]: deis-store-monitor.service: Unit entered failed state.
Oct 14 20:15:20 coreos003 systemd[1]: deis-store-monitor.service: Failed with result 'resources'.
Oct 14 20:15:20 coreos003 systemd[1]: Starting deis-store-monitor...
Oct 14 20:15:26 coreos003 systemd[1]: deis-store-monitor.service: Service hold-off time over, scheduling restart.
Oct 14 20:15:26 coreos003 systemd[1]: deis-store-monitor.service: Failed to load environment files: No such file or directory
Oct 14 20:15:26 coreos003 systemd[1]: deis-store-monitor.service: Failed to run 'start-pre' task: No such file or directory
Oct 14 20:15:26 coreos003 systemd[1]: Failed to start deis-store-monitor.
Oct 14 20:15:26 coreos003 systemd[1]: deis-store-monitor.service: Unit entered failed state.
Oct 14 20:15:26 coreos003 systemd[1]: deis-store-monitor.service: Failed with result 'resources'.
Oct 14 20:15:26 coreos003 systemd[1]: Starting deis-store-monitor...
Oct 14 20:15:31 coreos003 systemd[1]: deis-store-monitor.service: Service hold-off time over, scheduling restart.
Oct 14 20:15:31 coreos003 systemd[1]: deis-store-monitor.service: Failed to load environment files: No such file or directory
Oct 14 20:15:31 coreos003 systemd[1]: deis-store-monitor.service: Failed to run 'start-pre' task: No such file or directory
Oct 14 20:15:31 coreos003 systemd[1]: Failed to start deis-store-monitor.
Oct 14 20:15:31 coreos003 systemd[1]: deis-store-monitor.service: Unit entered failed state.
Oct 14 20:15:31 coreos003 systemd[1]: deis-store-monitor.service: Failed with result 'resources'.
Oct 14 20:15:31 coreos003 systemd[1]: Starting deis-store-monitor...
Oct 14 20:15:36 coreos003 systemd[1]: deis-store-monitor.service: Service hold-off time over, scheduling restart.
Oct 14 20:15:36 coreos003 systemd[1]: deis-store-monitor.service: Failed to load environment files: No such file or directory
Oct 14 20:15:36 coreos003 systemd[1]: deis-store-monitor.service: Failed to run 'start-pre' task: No such file or directory
Oct 14 20:15:36 coreos003 systemd[1]: Failed to start deis-store-monitor.
Oct 14 20:15:36 coreos003 systemd[1]: deis-store-monitor.service: Unit entered failed state.
Oct 14 20:15:36 coreos003 systemd[1]: deis-store-monitor.service: Failed with result 'resources'.
Oct 14 20:15:36 coreos003 systemd[1]: Starting deis-store-monitor...
Oct 14 20:15:41 coreos003 systemd[1]: deis-store-monitor.service: Service hold-off time over, scheduling restart.
Oct 14 20:15:41 coreos003 systemd[1]: deis-store-monitor.service: Failed to load environment files: No such file or directory
Oct 14 20:15:41 coreos003 systemd[1]: deis-store-monitor.service: Failed to run 'start-pre' task: No such file or directory
Oct 14 20:15:41 coreos003 systemd[1]: Failed to start deis-store-monitor.
Oct 14 20:15:41 coreos003 systemd[1]: deis-store-monitor.service: Unit entered failed state.
Oct 14 20:15:41 coreos003 systemd[1]: deis-store-monitor.service: Failed with result 'resources'.
Oct 14 20:15:41 coreos003 systemd[1]: Starting deis-store-monitor...

Here´s the return of fleetctl list-units | grep deis-:
coreos002 ~ # fleetctl list-units | grep deis-
deis-builder.service            b95dec9a.../192.168.57.65       inactive        dead
deis-controller.service         d5a263fd.../192.168.57.66       inactive        dead
deis-database.service           d5a263fd.../192.168.57.66       inactive        dead
deis-logger.service             b95dec9a.../192.168.57.65       inactive        dead
deis-logspout.service           67f00d0e.../192.168.57.67       inactive        dead
deis-logspout.service           b95dec9a.../192.168.57.65       inactive        dead
deis-logspout.service           d5a263fd.../192.168.57.66       inactive        dead
deis-publisher.service          67f00d0e.../192.168.57.67       inactive        dead
deis-publisher.service          b95dec9a.../192.168.57.65       inactive        dead
deis-publisher.service          d5a263fd.../192.168.57.66       inactive        dead
deis-registry@1.service         67f00d0e.../192.168.57.67       inactive        dead
deis-router@1.service           d5a263fd.../192.168.57.66       inactive        dead
deis-router@2.service           67f00d0e.../192.168.57.67       inactive        dead
deis-router@3.service           b95dec9a.../192.168.57.65       inactive        dead
deis-store-daemon.service       67f00d0e.../192.168.57.67       inactive        dead
deis-store-daemon.service       b95dec9a.../192.168.57.65       inactive        dead
deis-store-daemon.service       d5a263fd.../192.168.57.66       inactive        dead
deis-store-gateway@1.service    67f00d0e.../192.168.57.67       inactive        dead
deis-store-metadata.service     67f00d0e.../192.168.57.67       inactive        dead
deis-store-metadata.service     b95dec9a.../192.168.57.65       inactive        dead
deis-store-metadata.service     d5a263fd.../192.168.57.66       inactive        dead
deis-store-monitor.service      67f00d0e.../192.168.57.67       activating      auto-restart
deis-store-monitor.service      b95dec9a.../192.168.57.65       activating      auto-restart
deis-store-monitor.service      d5a263fd.../192.168.57.66       activating      auto-restart
deis-store-volume.service       67f00d0e.../192.168.57.67       inactive        dead
deis-store-volume.service       b95dec9a.../192.168.57.65       inactive        dead
deis-store-volume.service       d5a263fd.../192.168.57.66       inactive        dead

**Comment by carmstrong** [comment]
@robeferre Could you check to see if `/etc/environment` exists on your hosts? It sounds like it isn't there, for some reason.

What platform are you on?

**Comment by robeferre** [comment]
@carmstrong I´m deploing the cluster on a Baremetal server. You are corect I could not find the /etc/environment at my cluster hosts, which content should I include there?

Thanks a lot

**Comment by carmstrong** [comment]
> I could not find the /etc/environment at my cluster hosts, which content should I include there?

Make sure you're following our bare metal installation instructions: http://docs.deis.io/en/latest/installing_deis/baremetal/

Specifically, you'll need to write `/etc/environment` here: http://docs.deis.io/en/latest/installing_deis/baremetal/#add-environment

**Comment by robeferre** [comment]
@carmstrong You are correct I just added the /etc/environment and the platform is starting.

Thank you
