### ISSUE TITLE
HELP! deis-store-daemon high memory utilisation

### ISSUE THREAD

**Issue by synaptics** [deis/deis#4618]
Hi,

I have a 3 node cluster (deis 1.9) launched through deis.com.  Everything is mostly good, apart from about once every 3 weeks or so one of the nodes seems to die and generally has trouble coming back up without a bit of manual intervention.  Unfortunately I don't generally get time to retrospectively debug the issue, but I've been suspecting that it's a memory issue so I've been keeping a closer eye on it recently...

Today one of my nodes is showing this (the box is an AWS M3 Large):

CONTAINER           CPU %               MEM USAGE/LIMIT       MEM %               NET I/O
deis-logspout       0.09%               10.06 MiB/7.308 GiB   0.13%               89.95 MiB/86.96 MiB
deis-publisher      0.11%               10.73 MiB/7.308 GiB   0.14%               4.359 KiB/738 B
deis-router         0.00%               29.77 MiB/7.308 GiB   0.40%               3.442 GiB/1.036 GiB
deis-store-admin    0.08%               13.02 MiB/7.308 GiB   0.17%               769.2 MiB/192.9 MiB
deis-store-daemon   0.03%               5.007 GiB/7.308 GiB   68.52%              0 B/0 B
logstash_v6.cmd.1   0.06%               370.5 MiB/7.308 GiB   4.95%               59.32 MiB/64.57 MiB

As you can see the box is only running the Deis platform and a logstash container, but deis-store-daemon is using 5GB of 7GB available?!  Why is this so high on this one node?  Can I just restart the daemon and this will sort itself out?  Can i somehow limit this behaviour?  Can I just restart the service and it will resolve itself?

FYI the other 2 nodes in the cluster are running at this (much more reasonable) level:

deis-store-daemon         0.00%               520.8 MiB/7.308 GiB   6.96%               0 B/0 B
deis-store-daemon         0.06%               577.4 MiB/7.308 GiB   7.72%               0 B/0 B

Thanks,
John

**Comment by bacongobbler** [comment]
@synaptics would you mind getting some logs from the deis-store-monitor container running on that host? That certainly is a high amount of memory usage. You could try restarting the daemon but it'd be better to get to the bottom of this for educational purposes.

**Comment by synaptics** [comment]
Do you want output from 'docker logs deis-store-daemon' or something else?

Thanks,
John

**Comment by bacongobbler** [comment]
yes, the output from docker logs in a gist would be helpful. Since you're only concerned with rebooting one of the daemons, I'd go with the former approach so you'll only reboot the one daemon instance. :)

**Comment by synaptics** [comment]
The output is here: http://expirebox.com/download/4a294b1608d6f500322444b9df69c27a.html

I'll try and hold off restarting the daemon just in case you need any other info.

Thanks,
John

**Comment by synaptics** [comment]
Hi,

Don't know if you got to look at that log, however I now have a new CoreOS cluster (running Deis v1.11.1) that is showing deis-store-monitor excessive memory utilisation on 1 node after ~10 days of running:

deis-store-monitor        0.13%               4.761 GB/7.882 GB   60.40%

Am I able to free this memory somehow, perhaps by restarting the container on that node only?

Thanks,
John

**Comment by bacongobbler** [comment]
Hey @synaptics. Sorry I didn't get back to you on this! I did take a look at the log but I couldn't see anything out of the ordinary that would indicate something had gone wrong (from my knowledge, at least). You could try restarting that container on that node, but I'm not sure how that'll fare out. Perhaps someone on the ceph user mailing list or IRC would know more? https://ceph.com/resources/mailing-list-irc/

**Comment by bacongobbler** [comment]
I don't think this is something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant so I'm closing this.
