### ISSUE TITLE
Improving ability to work with multiple deis clusters

### ISSUE THREAD

**Issue by jeff-lee** [deis/deis#4620]
After logging in, deis stores an access token in ~/.deis/client.json.  If you have multiple environments, it is very easy to accidentally perform operations in the wrong environment by doing something like:

1. Login to one cluster ( staging ) in one terminal
2. Do some work
3. Login to another cluster ( production ) in a different terminal session 
4. Go back to the staging terminal and accidentally perform operations on the most recently logged in environment ( production in this case )

I'm currently trying to make this less likely by doing some trickery with bash functions and prompts, but it would be nice if there were some way to prevent it from happening.

Maybe if there were multiple entries in the client.json tied to an ENV variable?

**Comment by bacongobbler** [comment]
@jeff-lee have you tried my plugin? :)

https://github.com/fishworks/deis-accounts

**Comment by jeff-lee** [comment]
Nice.

Just installed that and I think there may be a few issues:

1. It looks like it's using username to list the accounts so if you have the same username across multiple clusters it gets confused

2. I'm getting 401 unauthorized errors after doing a "deis accounts:set"

**Comment by Joshua-Anderson** [comment]
@jeff-lee There is also a env variable called DEIS_PROFILE that allows you to save login config to separate files.

So if you set DEIS_PROFILE to prod your credentials would be saved and retrieved from `~/.deis/prod.json`.

**Comment by jeff-lee** [comment]
Ah...perfect.  I guess it helps to actually read the new feature releases. That's exactly what I was looking for.

Thanks!
