### ISSUE TITLE
custom-firewall.sh with k8s scheduler issues

### ISSUE THREAD

**Issue by vinilios** [deis/deis#4623]
Applying the recommended firewall rules seems to block all the available applications when k8s scheduler is enabled.

**Comment by bacongobbler** [comment]
the custom firewall script was only intended for the fleet scheduler (tech previews like kubernetes aren't supported for production), so I'm not too surprised that it doesn't work. We'll probably have to revisit this firewall script when v2 comes around, though.

**Comment by aledbf** [comment]
@vinilios kubernetes uses iptables for many [things](https://github.com/kubernetes/kubernetes/wiki/Services-FAQ) and it could [change](https://github.com/kubernetes/kubernetes/issues/3760). 
As @bacongobbler mentioned the current script only works with fleet.

A script (or an approach) like the existing one will not work.

**Comment by bacongobbler** [comment]
closing as a wontfix. If you want to play around with Deis and kubernetes, we have released an alpha version and are working on a beta :) docs are at https://github.com/deis/workflow#hacking-workflow. Thanks!
