### ISSUE TITLE
contrib/util/firewall.sh breaks cluster

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#4626]
Hi,

Yesterday I deployed a clean 1.11.1 cluster on a DigitalOcean cluster

I did not follow the instructions to the letter, as I first installed the platform and even deployed an app before running the firewall script as documented. (although I doubt this would have made a difference in this case)

After doing this I saw my cluster dying before my eyes. After some looking around it seemed it only opened public IPs of the other nodes on each node (and not even for all nodes on every node).
Culprit is that fleetctl list-machines is printing public IPs, but at least for some operations the private IPs are run.

After starting from scratch (even after fixing firewall manually, ceph was totally confused and I couldn't bother to try to fix that as it was a new cluster anyway), I have manually changed the script to include (hardoded) but the public and private IPS in the ETCD_NODES variable, and this worked perfectly...

I've used the firewall script before and it always used to work in earlire releases...

Nathan

**Comment by carmstrong** [comment]
> Culprit is that fleetctl list-machines is printing public IPs, but at least for some operations the private IPs are run.

This is behavior that I've seen lately, as well. I'm not sure what changed, but it seems like something within fleet. This is why I opened #4608, but I don't fully understand the need for the change, so I'm hesitant to make it.

**Comment by mboersma** [comment]
Closed by #4635.
