### ISSUE TITLE
Support TLS-enabled log drain

### ISSUE THREAD

**Issue by krancour** [deis/deis#4633]
Clarifying that this is TLS over TCP and is separate from the feature requested in #4527

**Comment by bacongobbler** [comment]
@krancour just clarifying that this is something that is still relevant for v2?

**Comment by krancour** [comment]
Probably not. Logger doesn't do this anymore in v2. If you want to drain logs to somewhere off-cluster in v2, you configure fluentd to do so (in addition to having fluentd write to logger [or nsq now?]). So, in v2, we support whatever fluentd supports in this regard. I'll close this.
