### ISSUE TITLE
missing install instructions for deis client for windows

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#4634]
title says it all.

very well possible the client is not supported on windows, which should also be a bug

**Comment by Joshua-Anderson** [comment]
Dseis has [experimental windows support](https://github.com/deis/deis/tree/master/client#)

**Comment by sgoings** [comment]
@nathansamson you do bring up a good point that we should definitely be vetting the Windows client in some fashion through our CI infrastructure.
