### ISSUE TITLE
Mitigation strategy for older Deis clusters

### ISSUE THREAD

**Issue by mboersma** [deis/deis#4636]
Docker recently posted a [deprecation notice](http://blog.docker.com/2015/10/docker-hub-deprecation-1-5/) indicating that `docker pull` will stop working for `docker` clients version 1.5.0 or earlier on December 7. For existing Deis clusters, this means that:
- `deis pull` will stop working (see #4581 for the solution for newer clusters)
- provisioning new nodes via autoscaling may fail

Upgrading to Deis v1.11 or later isn't an option for everyone, so we need to come up with a transition plan or mitigation strategy to help existing customers navigate this change to Docker Hub.

**Comment by Joshua-Anderson** [comment]
Maybe push older deis releases to quay.io (free for public images) and write a script using deisctl to update the docker image in ETCD?

**Comment by mboersma** [comment]
> push older deis releases to quay.io (free for public images) and write a script

+1. There is already a [deis org at quay.io](https://quay.io/organization/deis) and we will publish all Deis product releases there as well. I'll mirror the existing images and tags there soon.
