### ISSUE TITLE
builder functional test fails on Mac OS X

### ISSUE THREAD

**Issue by mboersma** [deis/deis#4639]
The registry mock code seems only to succeed on Linux. `make -C builder test-functional` fails for me consistently on my MacBook:
```console
Successfully built be7ebed39da9
[info] Images downloaded
[info] Pushing deis/slugrunner:latest to 192.168.99.100:51823. This may take some time.
[warning] Failed to push deis/slugrunner:latest to host 192.168.99.100:51823/deis/slugrunner:latest: exit status 1 (time="2015-10-20T19:49:59Z" level="fatal" msg="Error: v1 ping attempt failed with error: Get http://192.168.99.100:51823/v1/_ping: dial tcp 192.168.99.100:51823: connection refused" 
)
[error] Fatal errror on boot: exit status 1
```

**Comment by bacongobbler** [comment]
huh... I saw something similar today, but it was because I couldn't push an image from a docker-machine host to a registry hosted on that same machine. That probably has something to do with it. It's likely that the virtualbox machine has no clue as to its own IP address by default.

**Comment by bacongobbler** [comment]
this has been removed in v2. closing!
