### ISSUE TITLE
Investigate floating IPs for DigitalOcean

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#4640]
Today DO introduced floating IPs (https://www.digitalocean.com/company/blog/floating-ips-start-architecting-your-applications-for-high-availability/)

I wonder if we can use this to setup a load balancer on DO (as DO is lacking this right now)

**Comment by bacongobbler** [comment]
It helps for failover, but it's not a true load balancer. You'd have to know which hosts the routers landed on and assign the floating IP to those (in other words, no health checks). All traffic is sent to an "active" node, not round-robin'd between active and passive nodes. Those two points make it a deal breaker for our use case :(

**Comment by nathansamson** [comment]
Hi,

What I would do is
A) Leave the router nodes on the Deis cluster as-is. Note that for DO to work reliable ALL nodes need a router, and DNS entries need to point to all Deis nodes. Which is fine if you have 5 nodes which run everything, or I guess  more nodes where some or routerPlane only.

B) Add 2 or more additional nodes (partially?) outside of the Deis cluster  which have a HAProxy (or nginx to be consistent?) on them which would do healtchecks on all real Deis nodes and enable/disable router nodes appropriatly.  This would make it possible to run only router nodes on 3/5 nodes and would also prevent issues when a deis node is in unstable state. [1]
The 2 or more additional nodes would have floating IPs so they can safely failover

[1] I had this situation a while ago when running out of disk space on a node, and after cleaning diskspace the docker graph was corrupted (not sure why), so it took me 10 minutes to detect and recover from this. At the same time we were having a demo to our clients, and the browser connected to this failing node, and would as a result give an error... Having some LB nodes in front of the deis cluster can prevent these issues

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776), and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this.
