### ISSUE TITLE
Deis is losing a node every time.

### ISSUE THREAD

**Issue by robeferre** [deis/deis#4649]
Hi, we are planning to use Deis at our production environment, but I have presented some strange issues regarding my cluster nodes availability

Eg. This is the normal behavior of my units.
coreos001 ~ # deisctl list
UNIT                            MACHINE                         LOAD    ACTIVE          SUB
deis-builder.service            c742616b.../192.168.57.66       loaded  activating      start-post
deis-controller.service         c742616b.../192.168.57.66       loaded  active          running
deis-database.service           c742616b.../192.168.57.66       loaded  active          running
deis-logger.service             c742616b.../192.168.57.66       loaded  active          running
deis-logspout.service           16a4564a.../192.168.57.65       loaded  active          running
deis-logspout.service           5ac8a25a.../192.168.57.67       loaded  active          running
deis-logspout.service           c742616b.../192.168.57.66       loaded  active          running
deis-mesos-marathon.service     c742616b.../192.168.57.66       loaded  active          running
deis-mesos-master.service       c742616b.../192.168.57.66       loaded  active          running
deis-mesos-slave.service        16a4564a.../192.168.57.65       loaded  active          running
deis-mesos-slave.service        5ac8a25a.../192.168.57.67       loaded  active          running
deis-mesos-slave.service        c742616b.../192.168.57.66       loaded  active          running
deis-publisher.service          16a4564a.../192.168.57.65       loaded  active          running
deis-publisher.service          5ac8a25a.../192.168.57.67       loaded  active          running
deis-publisher.service          c742616b.../192.168.57.66       loaded  active          running
deis-registry@1.service         c742616b.../192.168.57.66       loaded  active          running
deis-router@1.service           16a4564a.../192.168.57.65       loaded  active          running
deis-router@2.service           5ac8a25a.../192.168.57.67       loaded  active          running
deis-router@3.service           c742616b.../192.168.57.66       loaded  active          running
deis-store-daemon.service       16a4564a.../192.168.57.65       loaded  active          running
deis-store-daemon.service       5ac8a25a.../192.168.57.67       loaded  active          running
deis-store-daemon.service       c742616b.../192.168.57.66       loaded  active          running
deis-store-gateway@1.service    c742616b.../192.168.57.66       loaded  active          running
deis-store-metadata.service     16a4564a.../192.168.57.65       loaded  active          running
deis-store-metadata.service     5ac8a25a.../192.168.57.67       loaded  active          running
deis-store-metadata.service     c742616b.../192.168.57.66       loaded  active          running
deis-store-monitor.service      16a4564a.../192.168.57.65       loaded  active          running
deis-store-monitor.service      5ac8a25a.../192.168.57.67       loaded  active          running
deis-store-monitor.service      c742616b.../192.168.57.66       loaded  active          running
deis-store-volume.service       16a4564a.../192.168.57.65       loaded  active          running
deis-store-volume.service       5ac8a25a.../192.168.57.67       loaded  active          running
deis-store-volume.service       c742616b.../192.168.57.66       loaded  active          running
deis-zookeeper.service          16a4564a.../192.168.57.65       loaded  active          running
deis-zookeeper.service          5ac8a25a.../192.168.57.67       loaded  active          running
deis-zookeeper.service          c742616b.../192.168.57.66       loaded  active          running

The problem is that every time my cluster is losing a node and reconfiguring all the stuff.

coreos002 ~ # fleetctl list-units
UNIT                            MACHINE                         ACTIVE          SUB
deis-builder.service            c742616b.../192.168.57.66       activating      start-post
deis-controller.service         c742616b.../192.168.57.66       active          running
deis-database.service           c742616b.../192.168.57.66       active          running
deis-logger.service             c742616b.../192.168.57.66       active          running
deis-logspout.service           5ac8a25a.../192.168.57.67       active          running
deis-logspout.service           c742616b.../192.168.57.66       active          running
deis-mesos-marathon.service     c742616b.../192.168.57.66       active          running
deis-mesos-master.service       c742616b.../192.168.57.66       activating      start-pre
deis-mesos-slave.service        5ac8a25a.../192.168.57.67       active          running
deis-mesos-slave.service        c742616b.../192.168.57.66       active          running
deis-publisher.service          5ac8a25a.../192.168.57.67       active          running
deis-publisher.service          c742616b.../192.168.57.66       active          running
deis-registry@1.service         c742616b.../192.168.57.66       active          running
deis-router@2.service           5ac8a25a.../192.168.57.67       active          running
deis-router@3.service           c742616b.../192.168.57.66       active          running
deis-store-daemon.service       5ac8a25a.../192.168.57.67       active          running
deis-store-daemon.service       c742616b.../192.168.57.66       active          running
deis-store-gateway@1.service    c742616b.../192.168.57.66       activating      start-post
deis-store-metadata.service     5ac8a25a.../192.168.57.67       active          running
deis-store-metadata.service     c742616b.../192.168.57.66       active          running
deis-store-monitor.service      5ac8a25a.../192.168.57.67       active          running
deis-store-monitor.service      c742616b.../192.168.57.66       active          running
deis-store-volume.service       5ac8a25a.../192.168.57.67       active          running
deis-store-volume.service       c742616b.../192.168.57.66       active          running
deis-zookeeper.service          5ac8a25a.../192.168.57.67       active          running
deis-zookeeper.service          c742616b.../192.168.57.66       active          running
zookeeper@1.service             c742616b.../192.168.57.66       active          running
zookeeper@2.service             5ac8a25a.../192.168.57.67       active          running

How could I debug this issue, seems that my fleet is losing the communication with the etcd, when I type fleetctl list-machines, the missing node is not showing.

This issue is a little painfull since we are planning to use Deis at our production environment. Is there any way to make the nodes tottally available?

After 5 to 10 mins, the node is recovered, but I think its not a common behaviour.

**Comment by iancoffey** [comment]
@robeferre On the node that is flapping, is there any relevant output in the etcd and fleet journals? eg, `journalctl -u etcd` and `journalctl -u fleet`

Nodes shouldn't be flapping in and out of the cluster in that way, I suspect the etcd and fleet journals could tell more.

**Comment by robeferre** [comment]
I was not using enought ram to run the cluster, as soon as I increased the ram size this issue was solved.
