### ISSUE TITLE
feat(client): `deis logs -f`

### ISSUE THREAD

**Issue by mboersma** [deis/deis#465]
Currently with deis you can run `deis logs`, but it's a single request-response that returns the current app logs and ends. Nor does `deis run tail -f` work since that isn't (yet) a long-running, duplex connection. Users should be able to get live tailing of logs.

This was requested by user kfarrell on IRC. See also #117.

**Comment by paralin** [comment]
+1

**Comment by jwaldrip** [comment]
:+1:

**Comment by bacongobbler** [comment]
related comment: https://github.com/deis/deis/pull/3524#issuecomment-94201087

basically we could resolve this by enabling the controller to create a [tail](https://github.com/heroku/logplex/blob/master/doc/README.stream-management.md#tails) session in `deis-logger`, which then the controller would return the URL to the tail session in the response. The client would then connect to the session. This is very somilar to Heroku's current infrastructure layout as shown in their [client unit tests](https://github.com/heroku/heroku/blob/cd1cf68ff41dca75071fae1d74caf6138525ca80/spec/heroku/client_spec.rb#L153-L157).

**Comment by ethanmick** [comment]
:+1:

**Comment by LoicMahieu** [comment]
+1

**Comment by jeffday** [comment]
+1

**Comment by paralin** [comment]
What's the progress of this?

**Comment by bacongobbler** [comment]
no work done other than what's been laid out here :)

**Comment by carmstrong** [comment]
@paralin This is blocked by the [TTY broker](http://docs.deis.io/en/latest/roadmap/roadmap/#tty-broker) on our open roadmap. If this feature is important to you, we'd love to see you at next Thursday's open roadmap meeting, and we can share more details about its progress and blockers. More details on our roadmap planning meetings: http://docs.deis.io/en/latest/roadmap/planning/

I'll be sending out the details on the meeting early next week to our [deis-users](https://groups.google.com/forum/#!forum/deis-users) mailing list. I'd encourage you to join that as well.

**Comment by dwelch2344** [comment]
+1

**Comment by deis-admin** [comment]
This issue was moved to deis/controller#1210
