### ISSUE TITLE
Disk cleaning does not remove all old images...

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#4650]
So after running the recovery command described in http://docs.deis.io/en/latest/managing_deis/disk_usage/ I still did not reclaim enough disk space to my taste.

I ran docker images to see what was still left.

~~~
core@ams3-cloud-beeple-3 ~ $ docker images                        
REPOSITORY                            TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
10.133.120.13:5000/bplpp-demos        v11                 39adeac10e77        4 hours ago         1.553 GB
10.133.120.13:5000/bplpp-demos        v9                  67e0e15af1a9        5 hours ago         1.553 GB
10.133.120.13:5000/bplpp-demos        v8                  f16bb09913ff        5 hours ago         1.553 GB
~~~

Is an extract
So clearly we should be able to remove at least v8 and v9 from this list. Lets try to do so.

~~~
core@ams3-cloud-beeple-3 ~ $ docker rmi f16bb09913ff
Error response from daemon: Conflict, cannot delete f16bb09913ff because the container c7e2b1883020 is using it, use -f to force
Error: failed to remove images: [f16bb09913ff]
core@ams3-cloud-beeple-3 ~ $ 
~~~

Lets see if we can find this container...

~~~
core@ams3-cloud-beeple-3 ~ $ docker ps | grep c7e2b1883020
core@ams3-cloud-beeple-3 ~ $ 
~~~

nope we couldn't. Lets try something else

~~~
core@ams3-cloud-beeple-3 ~ $ docker ps -a | grep c7e2b1883020
c7e2b1883020        10.133.120.13:5000/bplpp-demos:v8        "/runner/init start    5 hours ago         Exited (1) 5 hours ago                                                                                                 bplpp-demos_v8.clock.1         
core@ams3-cloud-beeple-3 ~ $ 
~~~~

Uhm, its exited, why would it not remove???

**Comment by bacongobbler** [comment]
Even though it's exited, it's still in use so Docker won't clean it up unless you explicitly tell it to with `-f`. You have to explicitly remove that container, which you can safely run `docker rm c7e2b1883020 && docker rmi f16bb09913ff` to remove the image.

From https://docs.docker.com/userguide/usingdocker/:

> This protects you from accidentally removing a running container you might need.

**Comment by nathansamson** [comment]
Is there a way to auomatically clean those? As I don't want to go and check every image out there if it is from an old release and I can safely remove them...

**Comment by nathansamson** [comment]
For anyone having the same problem try executing this

~~~
docker ps -a | grep "Exited" | grep -v "hours" | grep -v deis | cut -f1 -d" " | xargs docker rm
docker images -q | xargs -l10 docker rmi
~~~

This will remove all containers that are exited (and are not beloinging to deis), more than 2 days ago + all the images that can be safely removed.

Note the second command is slightly different from the docs, as the -a is not needed (I believe), and will make the command slower to execute (plus display more scary errors) than necessary.

Note this will still not remove all old images, it still keeps the following:
A) previous versions from images from deis components (as those containers are not cleaned up)
B) When your registry has moved, and your node has the same tagged image from 2 different repositories it wont remove them either. This also needs a -f (force) flag, but is not only limited to that error so you can not include it blindly. In theory you can get the errors from the second command, filter out this specific message and rerun with the -f flag. This case is not too common so I did not include it. For the few times it happened manually for me I just did those manually.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776), and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this. We'll likely need to revisit this documentation in the future as we find out how users are using Deis v2 with kubernetes.
