### ISSUE TITLE
Best practices for a production-grade Kubernetes cluster

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#4653]
We should describe in detail best practices for running a production-grade Kubernetes cluster. Eventually we'll be running production workloads (and Deis) on k8s, and our knowledge is something we should share with the community.

**Comment by zaa** [comment]
+1 on this one

**Comment by krancour** [comment]
I've been putting some effort lately into learning to build better etcd clusters.  I want @aledbf to weigh in on this if he has a chance.  Better etcd clusters are the foundation of a better Deis 1.x cluster, but I think @aledbf has some thoughts on how that may not be as relevant in the k8s world.  I'd like to establish whether that's truly the case or not before moving forward with establishing any best practices for a prod-grade k8s cluster.  There are many layers here and we really need to start with making sure that foundational layer is rock solid, and that means etcd.

**Comment by bacongobbler** [comment]
see https://deis.com/docs/workflow/quickstart/ and https://deis.com/docs/workflow/managing-workflow/production-deployments/ for our v2 documentation. Please feel free to add any changes related to production-ready suggestions for kubernetes at https://github.com/deis/workflow. Thanks!
