### ISSUE TITLE
deisctl install platform hangs on deis-router/router mesh

### ISSUE THREAD

**Issue by rvm2015** [deis/deis#4659]
Using CoreOS beta and deisctl as of yesterday with this documentation: http://docs.deis.io/en/latest/installing_deis/install-platform/

Both the first and second attempts hang at the same place, output is from the second run. This command has been hanging for half an hour at this point.

    core@deis1 ~ $ deisctl install platform
    Warning: Missing sshPrivateKey, "deis run" will be unavailable. Use:
    deisctl config platform set sshPrivateKey=<path-to-key>
    ● ▴ ■
    ■ ● ▴ Installing Deis...
    ▴ ■ ●
    Storage subsystem...
    deis-store-gateway@1.service: loaded
    deis-store-volume.service: loaded
    deis-store-monitor.service: loaded
    deis-store-daemon.service: loaded
    deis-store-metadata.service: loaded
    Logging subsystem...
    deis-logspout.service: loaded
    deis-logger.service: loaded
    Control plane...
    deis-registry@1.service: loaded
    deis-database.service: loaded
    deis-controller.service: loaded
    deis-builder.service: loaded
    Data plane...
    deis-publisher.service: loaded
    Router mesh...
    deis-router@1.service: loaded

**Comment by bacongobbler** [comment]
hey @rvm2015, can you please check the output of `fleetctl list-machines`? Typically I've seen that occur when fleet doesn't have all three nodes connected and they're all basically isolated from eachother.

**Comment by rvm2015** [comment]
Yeah I'm thinking it's probably that as I don't think I had fleet setup right. What specific services have to be up and configured on CoreOS before Deis can be provisioned? Fleet and etcd2?

I'm going to rebuild my test cluster again and will check back.

**Comment by rvm2015** [comment]
Nevermind, I'm an idiot and didn't ready the documentation closely enough. I'm rebuilding while actually following the document correctly (was using an existing cluster). You can close this.
