### ISSUE TITLE
bare-metal docs, move the hostname 'known issue' above the installation

### ISSUE THREAD

**Issue by rvm2015** [deis/deis#4660]
Specifically this document: http://docs.deis.io/en/latest/installing_deis/baremetal/#deis-on-bare-metal

If you're installing on bare metal or in VMWare you will have to do this workaround:

    Hostname is localhost¶
    If your hostname after installation to disk is localhost, set the hostname in user-data before installation:
    hostname: your-hostname
    The hostname must not be the fully qualified domain name!

This should be moved up with the section about public/private ips. It's incredibly infuriating to do the entire installation on 3 hosts, and then discover that you'll almost certainly have to add this step and have to restart from scratch. It should at least be above the coreos-install line.

**Comment by carmstrong** [comment]
@rvm2015 We rely on our community to help us keep the bare metal installation docs up-to-date, as that isn't something we're currently able to test ourselves. We'd welcome a pull request to move that farther up in the documentation - this file is https://github.com/deis/deis/blob/master/docs/installing_deis/baremetal.rst

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776), and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this.
