### ISSUE TITLE
expand installation docs on public/private ip space

### ISSUE THREAD

**Issue by rvm2015** [deis/deis#4661]
Specifically this document: http://docs.deis.io/en/latest/installing_deis/baremetal/#deis-on-bare-metal

In the section on Update $private_ipv4, specifically expand on the difference between COREOS_PUBLIC_IPV4 and COREOS_PRIVATE_IPV4. Can these be the same ip address? Do you need two separate physical interfaces?

This is in the context of bare metal or running on VMWare where typically you wouldn't create an instance with multiple network adapters unless you had a reason to. edit: I've done 3 rounds of installing coreos (at about 30 minutes a piece between building the configs and waiting for the images to write to disk) without getting this right at this point, very infuriating.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776), and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this.
