### ISSUE TITLE
expand installation docs on DNS setup

### ISSUE THREAD

**Issue by rvm2015** [deis/deis#4662]
Specifically: http://docs.deis.io/en/latest/managing_deis/configure-dns/#configure-dns

What is this document telling me to do? It says that a star record for a domain needs to be setup, however it doesn't give me any details on what that requires. Am I forwarding all requests for a specific subdomain to a host? Am I just setting dns records for the 3 docker hosts? I'm not getting what the requirement is, however it's listed as an installation step in http://docs.deis.io/en/latest/installing_deis/baremetal/#deis-on-bare-metal

**Comment by kenaniah** [comment]
To hopefully provide clarification:

Each app run on deis uses a virtual hostname, which requires that a wildcard DNS record be pointed at the deis cluster. This can be done at the top of your domain, or on a subdomain. Heroku, for example uses wildcard DNS for herokuapp.com. My preference is to put the wildcard on a subdomain, (like `*.deisapps.mydomain.com` and then using CNAMEs to expose apps using the top of my domain (CNAME `myapp.deisapps.mydomain.com` to `myapp.mydomain.com`).

**Comment by bacongobbler** [comment]
closing as answered :)
