### ISSUE TITLE
etcd2 setup fails on 2 of 3 nodes

### ISSUE THREAD

**Issue by rvm2015** [deis/deis#4664]
Using the bare metal installation instructions the etcd2 cluster fails to bootstrap on 2 out of 3 nodes. It seems that the first node in will generate it's data directory properly, the other two will get this error:

    2015/10/25 06:22:52 etcdmain: etcd Version: 2.1.2
    2015/10/25 06:22:52 etcdmain: Git SHA: ff8d1ec
    2015/10/25 06:22:52 etcdmain: Go Version: go1.4.2
    2015/10/25 06:22:52 etcdmain: Go OS/Arch: linux/amd64
    2015/10/25 06:22:52 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 2
    2015/10/25 06:22:52 etcdmain: listening for peers on http://:2380
    2015/10/25 06:22:52 etcdmain: listening for peers on http://:7001
    2015/10/25 06:22:52 etcdmain: listening for client requests on http://0.0.0.0:2379
    2015/10/25 06:22:52 etcdmain: listening for client requests on http://0.0.0.0:4001
    2015/10/25 06:22:52 netutil: resolving :2380 to :2380
    2015/10/25 06:22:52 netutil: resolving :2380 to :2380
    2015/10/25 06:22:53 etcdmain: stopping listening for client requests on http://0.0.0.0:4001
    2015/10/25 06:22:53 etcdmain: stopping listening for client requests on http://0.0.0.0:2379
    2015/10/25 06:22:53 etcdmain: stopping listening for peers on http://:7001
    2015/10/25 06:22:53 etcdmain: stopping listening for peers on http://:2380
    2015/10/25 06:22:53 etcdmain: member "default" has previously registered with discovery service token (https://discovery.etcd.io/snipped).
    2015/10/25 06:22:53 etcdmain: But etcd could not find vaild cluster configuration in the given data dir (/var/lib/etcd2).
    2015/10/25 06:22:53 etcdmain: Please check the given data dir path if the previous bootstrap succeeded
    2015/10/25 06:22:53 etcdmain: or use a new discovery token if the previous bootstrap failed.

Generating a new discovery url, wiping out all the etcd2 data directories, and then updating it on all 3 hosts makes no difference, same error with the new discovery url.

**Comment by crigor** [comment]
Did you replace $private_ipv4 with the private IP address on the cloud-config? Since you're using bare metal you can't use $private_ipv4. http://docs.deis.io/en/latest/installing_deis/baremetal/#update-private-ipv4

**Comment by rvm2015** [comment]
I discovered that while troubleshooting. Ended up correcting the underlying config files in the existing cluster with no change. Unfortunately I've since wiped out this cluster in favor of another solution so I can't retest. As such you can close this issue.
