### ISSUE TITLE
Issue with stateless setup

### ISSUE THREAD

**Issue by gred7** [deis/deis#4666]
I am trying to install a stateless setup of deis:
#!/bin/sh
deisctl uninstall stateless-platform
deisctl config registry set s3bucket=cloud-ckan-platform-resources s3region=us-east-1 s3path=/ s3encrypt=false s3secure=false
deisctl config logs set storageAdapterType=memory drain=logs3.papertrailapp.com:18752
deisctl config database set engine=postgresql host=ckan-rds.cmbk2prk21a7.us-east-1.rds.amazonaws.com  port=5432 name=ckan user=AdminCkanRds password=
deisctl install stateless-platform
deisctl start stateless-platform

and all I have is 
output from pre-run steps....

● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●
Logging subsystem...

and it hangs.
I suspect it can't resolve something....
Please tell me if you need more info

**Comment by olalonde** [comment]
Maybe your ssh connection just timed out? What's the output of `fleetctl list-units` and `fleetctl journal -f deis-logger`?

**Comment by gred7** [comment]
No, it's definitely not my ssh connection

core@ip-10-21-2-251 ~ $ fleetctl list-units
UNIT			MACHINE				ACTIVE		SUB
deis-builder.service	31f2302e.../52.23.255.26	inactive	dead
deis-controller.service	abad234c.../52.91.155.233	inactive	dead
deis-logger.service	31f2302e.../52.23.255.26	inactive	dead
deis-logspout.service	31f2302e.../52.23.255.26	inactive	dead
deis-logspout.service	abad234c.../52.91.155.233	inactive	dead
deis-logspout.service	acc7d732.../54.84.38.220	inactive	dead
deis-publisher.service	31f2302e.../52.23.255.26	inactive	dead
deis-publisher.service	abad234c.../52.91.155.233	inactive	dead
deis-publisher.service	acc7d732.../54.84.38.220	inactive	dead
deis-registry@1.service	acc7d732.../54.84.38.220	inactive	dead
deis-router@1.service	abad234c.../52.91.155.233	inactive	dead
deis-router@2.service	acc7d732.../54.84.38.220	inactive	dead
deis-router@3.service	31f2302e.../52.23.255.26	inactive	dead

the logs are not very helpful:
core@ip-10-21-2-251 ~ $ fleetctl journal -f deis-logger 
-- Logs begin at Mon 2015-10-26 12:46:56 UTC. --
Oct 26 14:10:52 ip-10-21-2-251.ec2.internal systemd[1]: Stopped deis-logger.
Oct 26 14:18:54 ip-10-21-2-251.ec2.internal systemd[1]: Stopped deis-logger.
Oct 26 14:42:25 ip-10-21-2-251.ec2.internal systemd[1]: Stopped deis-logger.
Oct 26 16:26:39 ip-10-21-2-251.ec2.internal systemd[1]: Stopped deis-logger.
Oct 26 16:52:27 ip-10-21-2-251.ec2.internal systemd[1]: Stopped deis-logger.
Oct 26 16:54:36 ip-10-21-2-251.ec2.internal systemd[1]: Stopped deis-logger.
Oct 27 10:28:27 ip-10-21-2-251.ec2.internal systemd[1]: Stopped deis-logger.

**Comment by olalonde** [comment]
`fleetctl journal -f -lines=1000 deis-logger` for more logs run .. try to run it just before you start the platform so you see where things go wrong with the logger

**Comment by gred7** [comment]
On 10/27/2015 01:44 PM, Olivier Lalonde wrote:
>
> |fleetctl journal -f -lines=1000 deis-logger| for more logs run .. try 
> to run it just before you start the platform so you see where things 
> go wrong with the logger
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/deis/deis/issues/4666#issuecomment-151465016>.
>
there is nothing more but this:
[greg@localhost aws]$ deisctl start stateless-platform
● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●
Logging subsystem...



core@ip-10-21-2-251 ~ $ fleetctl journal -lines=1000 -f deis-logger
-- Logs begin at Mon 2015-10-26 12:46:56 UTC. --
Oct 26 14:10:52 ip-10-21-2-251.ec2.internal systemd[1]: Stopped deis-logger.
Oct 26 14:18:54 ip-10-21-2-251.ec2.internal systemd[1]: Stopped deis-logger.
Oct 26 14:42:25 ip-10-21-2-251.ec2.internal systemd[1]: Stopped deis-logger.
Oct 26 16:26:39 ip-10-21-2-251.ec2.internal systemd[1]: Stopped deis-logger.
Oct 26 16:52:27 ip-10-21-2-251.ec2.internal systemd[1]: Stopped deis-logger.
Oct 26 16:54:36 ip-10-21-2-251.ec2.internal systemd[1]: Stopped deis-logger.
Oct 27 10:28:27 ip-10-21-2-251.ec2.internal systemd[1]: Stopped deis-logger.
[nothing new]

**Comment by olalonde** [comment]
Sorry, not sure how to help more, I'm just a deis user not a dev. Maybe try to run `journal -f` on the machine where the logger is started? Good luck...

**Comment by bacongobbler** [comment]
I haven't seen this issue before either so I'm sort of stumped at this point as well. I'd personally look at fleet's logs to see why the job is getting stopped so often. Are you on bare metal rather than AWS/DO, by any chance?

**Comment by gred7** [comment]
@bacongobbler no, it's an AWS setup.

**Comment by Blystad** [comment]
1) This was a clean cluster? I.e. you havn't had a Deis setup already running on it

2) Execute the journalctl -f command per olalonde's instructions. That might give some pointers.

3) On the machine executing deis-logger, can you get the output from "docker ps"

**Comment by gred7** [comment]
On 10/28/2015 12:43 AM, Arne-Christian Blystad wrote:
>
> 1) This was a clean cluster? I.e. you havn't had a Deis setup already 
> running on it
>
yes. the instances were provisioned from scratch
>
> 2) Execute the journalctl -f command per olalonde's instructions. That 
> might give some pointers.
>
executed, but got nothing
>
> 3) On the machine executing deis-logger, can you get the output from 
> "docker ps"
>
again got nothing.

**Comment by gred7** [comment]
On 10/28/2015 12:43 AM, Arne-Christian Blystad wrote:
>
> 1) This was a clean cluster? I.e. you havn't had a Deis setup already 
> running on it
>
yes.
>
> 2) Execute the journalctl -f command per olalonde's instructions. That 
> might give some pointers.
>
gives no new output
>
> 3) On the machine executing deis-logger, can you get the output from 
> "docker ps"
>
again. gives nothing

**Comment by krancour** [comment]
@gred7 the first line of your script is uninstalling all units of the stateless platform.  Start is probably hanging because the units aren't found.  Did you mean to _install_ on the first line?

**Comment by Blystad** [comment]
Should be fine:
```
deisctl uninstall stateless-platform
```
```
deisctl config registry set s3bucket=cloud-ckan-platform-resources s3region=us-east-1 s3path=/ s3encrypt=false s3secure=false
deisctl config logs set storageAdapterType=memory drain=logs3.papertrailapp.com:
deisctl config database set engine=postgresql host=ckan-rds.cmbk2prk21a7.us-east-1.rds.amazonaws.com port=5432 name=ckan user=AdminCkanRds password=
```
```
deisctl install stateless-platform
```
```
deisctl config registry set s3bucket= s3region=us-east-1 s3path=/ s3encrypt=false s3secure=false
deisctl config logs set storageAdapterType=memory drain=logs3.papertrailapp.com:
deisctl config database set engine=postgresql host=ckan-rds.cmbk2prk21a7.us-east-1.rds.amazonaws.com port=5432 name=ckan user= password=
```
```
deisctl start stateless-platform
```

Tried just destroying and provisioning a new cluster?

**Comment by krancour** [comment]
I missed the line halfway through where the stateless platform units were re-installed.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant so I'm closing this.
