### ISSUE TITLE
deis client breaks when enforceHTTPS is enabled

### ISSUE THREAD

**Issue by kenaniah** [deis/deis#4667]
The `deis` binary does not play well with the backend API if the backend cluster enforces the use of HTTPS. Requests made directly to the API via CURL still work when HTTPS is forced. The issue appears to be localized to the `deis` client.

To reproduce:

```bash
$ deis apps
=== Apps
...
$ deisctl config router set enforceHTTPS=true
$ deis apps
$ deis login ...
username: ...
password: ...
!    WARNING: Client and server API versions do not match. Please consider upgrading.
!    Client version: 1.7
!    Server version: 
Error: invalid character '<' looking for beginning of value
$ deisctl config router set enforceHTTPS=false
$ deis apps
=== Apps
...
```

`deis --version`: 11.1.1

**Comment by bacongobbler** [comment]
perhaps this has something to do with #4400 and #4504?

**Comment by bacongobbler** [comment]
ping @kenaniah. Were you able to further debug how or what causes this issue?

**Comment by kenaniah** [comment]
Unfortunately I don't have the time to look into this further at the moment. But more than happy to elaborate on the environment or repro steps if necessary.

**Comment by bacongobbler** [comment]
That would be very helpful. That way we can test and verify this is an issue on master.

**Comment by krancour** [comment]
Might the issue be simply that the client doesn't follow redirects?

**Comment by arkkanoid** [comment]
+1
    deis apps                                   
    Error: Get https://example.com/v1/apps/?page_size=100: stopped after 10 redirects

**Comment by krancour** [comment]
@kenaniah @arkkanoid in either of your cases, is their a proxy of any sort between the deis client and the load balancer?  If so, this could very well be related to #4504, #4997, and the pending fix in #4998.

**Comment by krancour** [comment]
> is there a proxy of any sort between the deis client and the load balancer?

If so, you might want to try again using a router built from the head of master-- #4998 was just merged.

**Comment by bacongobbler** [comment]
closing as we have a strong belief this has been fixed in the LTS release as well as in v2. please re-open if this is not the case. thanks!
