### ISSUE TITLE
Inconsistencies in registry s3 bucket creation with ceph-s3 vs stateless platform

### ISSUE THREAD

**Issue by helgi** [deis/deis#4668]
Looking at the `etcd` namespace configuration for s3 stateless platform vs ceph-s3 I started to notice some inconsistencies that should be address

Look at the configurations and namespaces at:
https://github.com/deis/deis/blob/master/registry/templates/config.yml#L78

And then head over to
https://github.com/deis/deis/blob/master/registry/templates/create_bucket and it is quickly apparent that we are only creating buckets with the `storage-gateway` namespaced keys but still doing `s3` namespaced bucket creation.

That's a pretty odd behaviour all in all. May be best if the script can do either namespace, or even *both* if we want to support that.

#4641 may fix this problem or help clean it up

**Comment by jchauncey** [comment]
I definitely think having `create_bucket` do an if check on which keys are set before it creates the connection object would be beneficial. It would allow people to convert a stateful cluster to stateless just by setting a few keys.

**Comment by helgi** [comment]
This should be fixed by #4729

**Comment by bacongobbler** [comment]
This has been fixed.
