### ISSUE TITLE
Should be able to restart container processes

### ISSUE THREAD

**Issue by mboersma** [deis/deis#467]
Heroku has `ps:restart` and Deis needs something similar to bounce databases or other processes that may become stuck.

**Comment by rjocoleman** [comment]
I'm going to take a look at this, how does this interface work for you guys?

```
$ heroku help restart
Alias: restart redirects to ps:restart
Usage: heroku ps:restart [DYNO]

 restart an app dyno

 if DYNO is not specified, restarts all dynos on the app

Examples:

 $ heroku ps:restart web.1
 Restarting web.1 dyno... done

 $ heroku ps:restart web
 Restarting web dyno... done

 $ heroku ps:restart
 Restarting dynos... done
```

**Comment by carmstrong** [comment]
> I'm going to take a look at this, how does this interface work for you guys?

Could you open a proposal like #2911? I think that's the vehicle we're using for planning features with the community moving forward.

**Comment by rjocoleman** [comment]
sure @carmstrong  proposal is here #3110
