### ISSUE TITLE
Proxying some apps through mashape/kong API gateway

### ISSUE THREAD

**Issue by olalonde** [deis/deis#4670]
I would like to use https://github.com/Mashape/kong to proxy some of my deis apps. Kong is an "Open-source, Microservice & API Management Layer" that does a few things like rate limiting and authentication.

My understanding is that I could deploy kong as a regular deis app and add my proxied apps using the kong api (going from the docs, haven't tested yet):

```bash
$ curl -i -X POST \
  --url http://kong.deis.domain.com/apis/ \
  --data 'name=api1' \
  --data 'upstream_url=http://api1.deis.domain.com/' \
  --data 'request_host=api1.domain.com'
```

and then just add `api1.domain.com` to my kong app to make sure it receives requests to this host:

```bash
deis domains:add api1.domain.com --app=kong
```

Everything looks good so far. Now, how would I make `api1.deis.domain.com` unreachable from outside my cluster? (I'm on AWS). It seems one approach would be to use [IP whitelisting](http://docs.deis.io/en/latest/managing_deis/security_considerations/#ip-whitelist) but then I would have to declare each app that needs to be public manually (`deis config:set -a some-public-app DEIS_WHITELIST="0.0.0.0/0"`). Is that correct? Other recommended approaches?

**Comment by Joshua-Anderson** [comment]
You could also use an api key for your internal app.

**Comment by olalonde** [comment]
Yes that's true but that partially defeats the point of using kong as an authentication layer (e.g. i still have to implement some authentication mechanism in the upstream app).

**Comment by bacongobbler** [comment]
In deis v2 the root domain object is attached to the app as soon as it's created, so in v2 you can just use `deis domains:remove api1` and that should solve your use case. We won't be able to backport this to v1 so I'm going to close this as resolved in v2.
