### ISSUE TITLE
deis cli should have a version command

### ISSUE THREAD

**Issue by jchauncey** [deis/deis#4674]
I was trying to use an old cli against a new cluster and was getting the following error - 

```
╰─± deis login http://deis.foo.com

http://deis.foo.com does not appear to be a valid Deis controller.
Make sure that the Controller URI is correct and the server is running.
```

It would be nice if the deis cli had a version command that returned the version of the server running and the version of the cli (like the docker version command)

**Comment by jchauncey** [comment]
Also the --version flag should be documented

**Comment by bacongobbler** [comment]
fixed in v2 and a backport has been made for v1. As for the full server version, see deis/workflow#329.
