### ISSUE TITLE
deis config:push should optionally take a path

### ISSUE THREAD

**Issue by jchauncey** [deis/deis#4675]
If you are deploying to multiple envs it would be nice if you could specify where to find the config for each env. Right now `deis config:push` only accepts a .env file. 

Proposal:
* `deis config:push` - looks for .env still
* `deis config:push staging.env` - Pushes staging.env

**Comment by olalonde** [comment]
I'd rather have `deis config:push < staging.env` and `deis config:pull > staging.env` instead, would be more flexible.

**Comment by bacongobbler** [comment]
@olalonde good thought on accepting pipes, though that's not necessarily something we can do in v1 without breaking things.

Sounds like this has already been resolved with the -p flag, so it's good to close.

**Comment by olalonde** [comment]
Just did: https://github.com/deis/deis/issues/4697 :+1:
