### ISSUE TITLE
Cut a 1.10.2 release with images pushed to Quay.io

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#4678]
We have a few users who are planning to go into production with Deis 1.10 so they have Docker 1.5 (presumably, known issues like memory leaks are better than unknown ones). They've requested that we cut a Deis 1.10.2 release which switches to pulling images from Quay.io so that they are not SOL when `docker pull` stops working for Docker Hub images pulled on <= 1.5 clients on December 7. 

Note that I'm not sure we even need to cut a release - perhaps pushing the 1.10.1 images to Quay and then instructing users to use `deisctl config <component> set image=` to instruct Deis to use the Quay image is sufficient.

@mboersma This may be something we can tackle together next week while you're orchestrating the 1.12 release.

**Comment by mboersma** [comment]
The v1.10.1 images (and all other recent releases) are already where you expect them to be on [quay.io](https://quay.io/organization/deis). My concern about making a v1.10.2 release is that it would imply using quay.io for Deis components to bootstrap fixes the [Docker D-Day](http://blog.docker.com/2015/10/docker-hub-deprecation-1-5/) issue, but it does not: `deis pull` and `git push deis master` for Dockerfile apps will stop working as well.

**Comment by jeff-lee** [comment]
Cutting a 1.10.2 without upgrading Docker will also mean that we won't be able to scale nodes if we run any third party apps ( e.g. logging, monitoring ) that are hosted or based on Dockerhub images right?

**Comment by mboersma** [comment]
> we won't be able to scale nodes if we run any third party apps...

True, this would only solve it for provisioning Deis components. Other services that implicitly reference Docker Hub will need a similar update to continue working with Docker 1.5.0.

**Comment by mboersma** [comment]
After further discussion, this seems less useful. Deis v1.12.1 and subsequent releases have a better fix for this issue. I'm closing this but I'll keep the proposed patch release around in a branch in case this is revisited.
