### ISSUE TITLE
Bug (contrib/azure) - unable to add new discovery URL to azure-user-data

### ISSUE THREAD

**Issue by ritazh** [deis/deis#4679]
The command `./create-azure-user-data $(curl -s https://discovery.etcd.io/new)` did not correctly parse the `user-data-template` file to replace value of DISCOVERY_URL in the `azure-user-data` file. The end result was  `discovery: null`. This was also mentioned in #4593

**Comment by sgoings** [comment]
Thanks for opening this @ritazh! I recently ran into this problem myself but failed to open up a separate issue. Could you take a look at the fix I linked into your PR and let me know if that seems like a reasonable alternative fix to yours?

**Comment by ritazh** [comment]
@sgoings Just tested your fix. Seems to fix the issue as well. What's the best way to proceed?

**Comment by sgoings** [comment]
I'm a little biased, but I'd say let's go with the fix I provided as it doesn't change the highly shared coreos/user-data contents (requiring a matrix of testing). Do you agree and want to head down that road? If so, you're welcome to pull my code over and update your PR #4680.

**Comment by ritazh** [comment]
@sgoings New commit with your changes: https://github.com/ritazh/deis/commit/6718a752d2935a2eb881219db12436437de106af
