### ISSUE TITLE
Integrate letsencrypt into the app provisioning / installation process

### ISSUE THREAD

**Issue by landonclark** [deis/deis#4681]
With [Let's Encrypt](https://letsencrypt.org) heading into Beta recently, it would be great for every http endpoint in Deis to be TLS enabled by default (over-rideable of course per app if you want to use an EV cert).

This would solve a lot of (minor!) issues - 
1. Bootstrapping the first user in a Deis cluster over HTTP.
2. Requiring a wildcard certificate.
3. Enabling better URLs even when a wildcard cert is enabled.  For instance, I dedicated *.apps.example.com to Deis, but I want to deploy to blog.example.com.

**Comment by krancour** [comment]
This has been discussed internally and the consensus is that we'll be looking to nail this right out of the gate with v2, but no changes of this magnitude will be making it into the v1.x.  Assigning v2 as he milestone.

**Comment by almereyda** [comment]
I don't know how much the dokku and deis development are already synced, but there is a letsencrypt plugin for the first at https://github.com/sgulseth/dokku-letsencrypt.

**Comment by slack** [comment]
Keeping this as an enhancement request, but unscheduling from the 2.0 milestone.

**Comment by jgmize** [comment]
There was a demo of [kube-lego](https://github.com/jetstack/kube-lego) at [last week's Kubernetes community meeting](https://www.youtube.com/watch?v=M3b8Wzqi56A) that looked like it could be relevant to this issue.

**Comment by bourquep** [comment]
The [kube-cert-manager](https://github.com/PalmStoneGames/kube-cert-manager) project might also be useful/relevant.

**Comment by deis-admin** [comment]
This issue was moved to deis/controller#1222
