### ISSUE TITLE
DO provider isn't working with latest terraform

### ISSUE THREAD

**Issue by leshik** [deis/deis#4683]
Hi,

Had trouble to start cluster at DigitalOcean when parsing ssh-keys fingerprint, using latest version of terraform (v0.6.6), the error is:

* digitalocean_droplet.deis.0: strconv.ParseInt: parsing "3a:4b:bf:d2:4c:92:af:5d:fa:72:07:5a:17:3c:09:3b": invalid syntax
* digitalocean_droplet.deis.1: strconv.ParseInt: parsing "3a:4b:bf:d2:4c:92:af:5d:fa:72:07:5a:17:3c:09:3b": invalid syntax
* digitalocean_droplet.deis.2: strconv.ParseInt: parsing "3a:4b:bf:d2:4c:92:af:5d:fa:72:07:5a:17:3c:09:3b": invalid syntax

Works with terraform v0.5.3, though.

**Comment by nathansamson** [comment]
This used to work for me on 0.6.3

**Comment by sgoings** [comment]
Looks like it broke with https://github.com/hashicorp/terraform/blame/master/builtin/providers/digitalocean/resource_digitalocean_droplet.go#L138

Which was added for the 0.6.5 release. Care to open up an issue for Terraform @leshik?

**Comment by sgoings** [comment]
Ah. Found an issue hashicorp/terraform#3628 which refers to a PR for a fix hashicorp/terraform#3633
