### ISSUE TITLE
heroku buildpack fails, but commits gets accepted

### ISSUE THREAD

**Issue by thiver** [deis/deis#4695]
Sometimes my Heroku PHP Buildpack fails, but deis accept the commit, so I have to do an empty commit to trigger a rebuild. A rebuild function would be greate as mentioned in other issues, but should'nt the commit be rejected? My main problem is that it seems that the app is up to date in the git tree, but in reality an old version is running online because the commit never deployed.

**Comment by nathansamson** [comment]
+1 This annoyed me the last few days as well when compiling failed because some file could not be downloaded to compile my buildpack...

Although obviously if a compile fails (for any reason, it could be the apps fault) and the commit would not get accepted then you are possibly in for a large upload again...

**Comment by bacongobbler** [comment]
Yes, the commit should get rejected. I'll cook up a test buildpack and see what I can come up with.

**Comment by sstarcher** [comment]
same behavior on nodejs and docker builds

**Comment by LoicMahieu** [comment]
I encounter this problem too using docker builds and dpl...

**Comment by bacongobbler** [comment]
I can confirm this with a custom heroku buildpack:

```
><> deis create fail
Creating Application... done, created fail
Git remote deis added
remote available at ssh://git@deis.172.17.8.100.xip.io:2222/fail.git
><> deis config:set BUILDPACK_URL=https://github.com/bacongobbler/heroku-buildpack-epic-fail
Creating config... done

=== fail Config
BUILDPACK_URL      https://github.com/bacongobbler/heroku-buildpack-epic-fail
><> git push deis master
Counting objects: 80, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (45/45), done.
Writing objects: 100% (80/80), 19.02 KiB | 0 bytes/s, done.
Total 80 (delta 30), reused 75 (delta 30)
-----> fail app detected
-----> failing buildpack with exit code 1...
To ssh://git@deis.172.17.8.100.xip.io:2222/fail.git
 * [new branch]      master -> master
```

Source available at https://github.com/bacongobbler/heroku-buildpack-epic-fail
