### ISSUE TITLE
./create-gce-user-data $(curl -s https://discovery.etcd.io/new) empty discovery

### ISSUE THREAD

**Issue by rimusz** [deis/deis#4696]
`./create-gce-user-data $(curl -s https://discovery.etcd.io/new)` creates gcd-user-data with empty discovery: 
    "discovery": !!null |-
      null
deis v1.11.2

**Comment by sgoings** [comment]
Fixed via: #4688 which goes out in v1.12.0 next week.

**Comment by rimusz** [comment]
cool
