### ISSUE TITLE
feat(client) support pipes with deis config:push and deis:config pull

### ISSUE THREAD

**Issue by olalonde** [deis/deis#4697]
It would be nice if deis config:push and deis:config pull supported piping like this:

```bash
deis config:pull > .env
deis config:push < .env
```

Or it could perhaps be:

```bash
deis config > .env
deis config < .env
```

**Comment by Joshua-Anderson** [comment]
I'll take a look at implementing this in Deis V2 in [deis/workflow](https://github.com/deis/workflow).

**Comment by bacongobbler** [comment]
fixed in deis/workflow#72

**Comment by olalonde** [comment]
Nice, thanks :+1:

**Comment by Joshua-Anderson** [comment]
@bacongobbler Not quite yet. We still need pipe support for `config:pull`. I have a little bit of time again, so I'll try and patch that up tomorrow.
