### ISSUE TITLE
Vagrantfile broken for CoreOS alpha / beta

### ISSUE THREAD

**Issue by mboersma** [deis/deis#4703]
The changes in #4562 (I think) broke the ability to set the CoreOS update channel for vagrant testing:
```console
$ COREOS_CHANNEL=alpha vagrant up
Bringing machine 'deis-01' up with 'virtualbox' provider...
Bringing machine 'deis-02' up with 'virtualbox' provider...
Bringing machine 'deis-03' up with 'virtualbox' provider...
==> deis-01: Running triggers before up...
==> deis-01: Box 'coreos-alpha' could not be found. Attempting to find and install...
    deis-01: Box Provider: virtualbox
    deis-01: Box Version: 766.4.0
==> deis-01: Box file was not detected as metadata. Adding it directly...
You specified a box version constraint with a direct box file
path. Box version constraints only work with boxes from Vagrant
Cloud or a custom box host. Please remove the version constraint
and try again.
```

**Comment by bacongobbler** [comment]
It works when you set `COREOS_CHANNEL=beta`, but now COREOS_VERSION is hardcoded to 766.4.0, whereas before it used to be `current`, so yes this did break backwards compatibility.

**Comment by bacongobbler** [comment]
My guess is that we'll now have to explicitly state `COREOS_VERSION=current` in our alpha and beta CI jobs so we're running on the expected boxes.

**Comment by bacongobbler** [comment]
I've updated the CI jobs to explicitly use `COREOS_VERSION=current` and re-jiggered the jobs tosee if that will work. If it does then I believe we don't have to call this a showstopper anymore :)

**Comment by carmstrong** [comment]
> I believe we don't have to call this a showstopper

Agreed - especially since this doesn't affect users for this release, assuming everyone is on the stable channel.

**Comment by mboersma** [comment]
`COREOS_VERSION=current` is a totally acceptable workaround for this. Thanks for sleuthing here @bacongobbler. It looks like CI is better with your changes, and I removed the milestone and showstopper label from this issue.
