### ISSUE TITLE
Urgent help! deis-controller not starting, seems caught in a loop

### ISSUE THREAD

**Issue by synaptics** [deis/deis#4706]
Hi,

So my controller seems to have died, and while trying to restart via fleetctl, deisctl and manually on the node it starts but the log shows this loop occurring:

[2015-11-01 18:10:47 +0000] [621] [INFO] Booting worker with pid: 621
[2015-11-01 18:10:47 +0000] [622] [INFO] Booting worker with pid: 622
[2015-11-01 18:10:47 +0000] [623] [INFO] Booting worker with pid: 623
[2015-11-01 18:10:47 +0000] [624] [INFO] Booting worker with pid: 624
[2015-11-01 18:10:47 +0000] [601] [INFO] Worker exiting (pid: 601)
[2015-11-01 18:10:47 +0000] [603] [INFO] Worker exiting (pid: 603)
[2015-11-01 18:10:47 +0000] [602] [INFO] Worker exiting (pid: 602)
[2015-11-01 18:10:47 +0000] [604] [INFO] Worker exiting (pid: 604)
[2015-11-01 18:10:47 +0000] [605] [INFO] Worker exiting (pid: 605)
[2015-11-01 18:10:47 +0000] [625] [INFO] Booting worker with pid: 625
[2015-11-01 18:10:52 +0000] [120] [INFO] Handling signal: hup
[2015-11-01 18:10:52 +0000] [120] [INFO] Hang up: Master
[2015-11-01 18:10:52 +0000] [630] [INFO] Booting worker with pid: 630
[2015-11-01 18:10:52 +0000] [631] [INFO] Booting worker with pid: 631
[2015-11-01 18:10:52 +0000] [622] [INFO] Worker exiting (pid: 622)
[2015-11-01 18:10:52 +0000] [633] [INFO] Booting worker with pid: 633
[2015-11-01 18:10:52 +0000] [621] [INFO] Worker exiting (pid: 621)
[2015-11-01 18:10:52 +0000] [623] [INFO] Worker exiting (pid: 623)
[2015-11-01 18:10:52 +0000] [624] [INFO] Worker exiting (pid: 624)
[2015-11-01 18:10:52 +0000] [625] [INFO] Worker exiting (pid: 625)
[2015-11-01 18:10:52 +0000] [632] [INFO] Booting worker with pid: 632
[2015-11-01 18:10:52 +0000] [629] [INFO] Booting worker with pid: 629
[2015-11-01 18:10:57 +0000] [120] [INFO] Handling signal: hup
[2015-11-01 18:10:57 +0000] [120] [INFO] Hang up: Master

Is there any suggestion available as to how to fix this?  Would running a Ceph-less cluster help reduce these kind of issues which seem to re-occur regularly.  I'm running Deis v1.11.1.

Many thanks,
John

**Comment by synaptics** [comment]
Aditionally on restart I get this, which all seems reasonable...

[2015-11-01 18:31:18 +0000] [120] [INFO] Shutting down: Master
controller: running etcd data migrations...
controller: done running etcd data migrations.
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for authtoken:
- Nothing to migrate.
 - Loading initial data for authtoken.
Installed 0 object(s) from 0 fixture(s)
Running migrations for api:
- Nothing to migrate.
 - Loading initial data for api.
Installed 0 object(s) from 0 fixture(s)
Running migrations for guardian:
- Nothing to migrate.
 - Loading initial data for guardian.
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.admin
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.humanize
 > django.contrib.messages
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.staticfiles
 > django_auth_ldap
 > json_field
 > rest_framework
 > south
 > corsheaders
 > web

Migrated:
 - rest_framework.authtoken
 - api
 - guardian
Publishing DB state to etcd...
Done Publishing DB state to etcd.
deis-controller running...
controller: running etcd data migrations...
controller: done running etcd data migrations.
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for authtoken:
- Nothing to migrate.
 - Loading initial data for authtoken.
Installed 0 object(s) from 0 fixture(s)
Running migrations for api:
- Nothing to migrate.
 - Loading initial data for api.
Installed 0 object(s) from 0 fixture(s)
Running migrations for guardian:
- Nothing to migrate.
 - Loading initial data for guardian.
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.admin
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.humanize
 > django.contrib.messages
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.staticfiles
 > django_auth_ldap
 > json_field
 > rest_framework
 > south
 > corsheaders
 > web

Migrated:
 - rest_framework.authtoken
 - api
 - guardian
[2015-11-01 18:28:27 +0000] [120] [INFO] Handling signal: hup
[2015-11-01 18:28:27 +0000] [120] [INFO] Hang up: Master

Publishing DB state to etcd...
INFO admin: config admin-5f9870e updated
INFO admin: config admin-fe86d5e updated
INFO admin: config admin-2be054f updated
INFO admin: config admin-94b425a updated
INFO kibana: config kibana-37aaa92 updated
INFO logstash: config logstash-f2421b1 updated
INFO access-license: config access-license-945af56 updated
INFO access-license: config access-license-4b8270f updated
INFO access-license: config access-license-8029289 updated
INFO kibana: config kibana-31b411d updated
INFO kibana: config kibana-4b8a5d0 updated
INFO widevine-proxy: config widevine-proxy-ad5d6c0 updated
INFO token-api: config token-api-a748277 updated
INFO stats-api: config stats-api-6b2f55d updated
INFO pssh-api: config pssh-api-cbd2640 updated
INFO logstash: config logstash-06c8459 updated
INFO logstash: config logstash-cbfd4ba updated
INFO keyingest-api: config keyingest-api-72ae173 updated
INFO keyingest-api: config keyingest-api-9e8e644 updated
INFO key-provider: config key-provider-56f2e81 updated
INFO key-provider: config key-provider-36c5ac4 updated
INFO config-api: config config-api-5ef738f updated
INFO config-api: config config-api-f8200c8 updated
INFO aes-license: config aes-license-b812883 updated
INFO admin: config admin-6beed60 updated
INFO access-license: config access-license-33a706e updated
INFO widevine-proxy: config widevine-proxy-df2c5b8 updated
INFO widevine-proxy: config widevine-proxy-e461fce updated
INFO token-api: config token-api-f8c6ab9 updated
INFO token-api: config token-api-2d0f563 updated
INFO stats-api: config stats-api-88e9f19 updated
INFO pssh-api: config pssh-api-d01daf8 updated
INFO pssh-api: config pssh-api-82619be updated
INFO aes-license: config aes-license-c435105 updated
INFO admin: config admin-f8fad56 updated
INFO admin: config admin-1ac77a7 updated
INFO 0-live-green-0: config 0-live-green-0-d511139 updated
Done Publishing DB state to etcd.
deis-controller running...

But then it spins off in to the loop given previously :(

Thanks,
John

**Comment by bacongobbler** [comment]
@synaptics is there anything in the fleet logs that would indicate why your controller is constantly being rebooted? Typically those first logs being shown happen when something in etcd is flapping/constantly changing, causing the controller config to keep re-templating and reload.

**Comment by synaptics** [comment]
@bacongobbler which service logs should I be looking at, etcd? Presumably using journalctl -u <whatever>.service to view these?

**Comment by bacongobbler** [comment]
fleet. `journalctl -u fleet.service` should help, but I'd also look at the other components I mentioned (registry and controller)

**Comment by synaptics** [comment]
@bacongobbler just had a look and there's nothing obvious to me - it looks like the controller came back up, worked for a while and then started flapping.  I'm thinking that moving to a Ceph-less environment is likely to help, however the instructions for that look a little sketchy, mostly around the Swift3 configuration.

**Comment by bacongobbler** [comment]
swift3 is only necessary if you want to use your own swift cluster. You're welcome to use S3 instead of openstack if you wish.

**Comment by synaptics** [comment]
@bacongobbler ah I see, so if I'm using S3 I just do all the other bits and ignore Swift3.  My only other concern then is if I set up the logger to use memory and don't set a drain, what happens?  I'm happy to do this as my containers log to Loggly anyway and right now I don't have a sensible alternative.

**Comment by bacongobbler** [comment]
If you set up a logger without a drain, all of your logs will be sent to the logger and available via `deis logs`. As described in http://docs.deis.io/en/latest/customizing_deis/logger_settings/#settings-used-by-logger, the default in-memory ring buffer size is 1000 lines, so if you want to keep them more permanent, you'll need to ship them elsewhere with a drain or increase the size of the adapter's ring buffer.

**Comment by synaptics** [comment]
@bacongobbler thanks, that makes sense. Everything seems to be heading in the right direction with regards to Ceph-less clustering, however when the builder starts I'm getting this:

Nov 02 17:28:15 ip-172-31-29-217.eu-west-1.compute.internal sh[4191]: Status: Downloaded newer image for deis/builder:v1.11.1
Nov 02 17:28:15 ip-172-31-29-217.eu-west-1.compute.internal sh[4467]: /dev/loop0
Nov 02 17:28:15 ip-172-31-29-217.eu-west-1.compute.internal sh[4480]: Waiting for builder on 2223/tcp...
Nov 02 17:28:15 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [debug] Name: ETCD_PORT, Val: 4001
Nov 02 17:28:15 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [debug] Name: ETCD_PATH, Val: /deis/builder
Nov 02 17:28:15 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [debug] Name: ETCD_TTL, Val: 20
Nov 02 17:28:15 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [debug] Name: HOST, Val: 172.31.29.217
Nov 02 17:28:15 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [debug] Name: ETCD, Val: 172.31.29.217:4001
Nov 02 17:28:15 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [info] Starting docker with -d --bip=172.19.42.1/16 --insecure-registry 10.0.0.0/8 --insecure-registry 172.16.0.0/12 --insecure-registry 192.168.0.0/16 --insecure-registry 100.64.0.0/10 --storage-driver=overlay
Nov 02 17:28:16 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [info] Docker is running.
Nov 02 17:28:16 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [info] Starting build for /usr/local/src/slugbuilder/ (tag: deis/slugbuilder)
Nov 02 17:28:16 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [info] Starting build for /usr/local/src/slugrunner/ (tag: deis/slugrunner)
Nov 02 17:28:16 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [info] Sleeping
Nov 02 17:28:37 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [info] Woke up.
Nov 02 17:28:37 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: warnContinuing after Recoverable Error on route boot: 105: Key already exists (/deis/builder/users) [5668]
Nov 02 17:28:37 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [info] Parsed host key /etc/ssh/ssh_host_rsa_key.
Nov 02 17:28:37 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [info] Parsed host key /etc/ssh/ssh_host_dsa_key.
Nov 02 17:28:37 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [info] Parsed host key /etc/ssh/ssh_host_ecdsa_key.
Nov 02 17:28:37 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [info] Building confd templates. This may take a moment.
Nov 02 17:28:37 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [debug] Recoverable error: exit status 1
Nov 02 17:28:37 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [debug] Output: "2015-11-02T17:28:37Z 3dc352ad7462 confd[161]: ERROR template: builder:59:14: executing \"builder\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-11-02T17:28:37Z 3dc352ad7462 confd[161]: ERROR template: check-repos:14:20: executing \"check-repos\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-11-02T17:28:37Z 3dc352ad7462 confd[161]: ERROR template: push-images:9:37: executing \"push-images\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-11-02T17:28:37Z 3dc352ad7462 confd[161]: ERROR template: receiver:15:55: executing \"receiver\" at <getv \"/deis/controll...>: error calling getv: key does not exist\n"
Nov 02 17:28:40 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [info] Re-trying template build. (Elapsed time: 3)
Nov 02 17:28:40 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [debug] Recoverable error: exit status 1
Nov 02 17:28:40 ip-172-31-29-217.eu-west-1.compute.internal sh[4477]: [debug] Output: "2015-11-02T17:28:40Z 3dc352ad7462 confd[167]: ERROR template: builder:59:14: executing \"builder\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-11-02T17:28:40Z 3dc352ad7462 confd[167]: ERROR template: check-repos:14:20: executing \"check-repos\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-11-02T17:28:40Z 3dc352ad7462 confd[167]: ERROR template: push-images:9:37: executing \"push-images\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2015-11-02T17:28:40Z 3dc352ad7462 confd[167]: ERROR template: receiver:15:55: executing \"receiver\" at <getv \"/deis/controll...>: error calling getv: key does not exist\n"

Any ideas?  Do I need to create some tables in the Postgres DB as nothing appears to be happening in there (I've triple-checked credentials) and there's nothing in S3 at this point either (again credentials have been triple-checked)?

**Comment by bacongobbler** [comment]
> confd[161]: ERROR template: receiver:15:55: executing \"receiver\" at : error calling getv: key does not exist\n"

> 2015-11-02T17:28:37Z 3dc352ad7462 confd[161]: ERROR template: check-repos:14:20: executing \"check-repos\" at : error calling getv: key does not exist

I believe that indicates that the controller and the registry are not flapping. It's not explicit, but confd is trying to template the [receiver](https://github.com/deis/deis/blob/master/builder/rootfs/etc/confd/templates/receiver) script and [check-repos](https://github.com/deis/deis/blob/master/builder/rootfs/etc/confd/templates/check-repos) which rely on the controller and registry, respectively.

**Comment by synaptics** [comment]
@bacongobbler sorry, maybe I wasn't clear - that log is from builder coming up on a new Ceph-less cluster hence my question about whether I need to do anything pre-emptively in Postgres or not.

**Comment by bacongobbler** [comment]
You shouldn't need to do anything in postgres. The migrations will do all the tricky work, but the point I'm trying to make is that the builder doesn't rely on postgres. It relies on the controller and the registry, which is what the logs are hinting at here. :)

**Comment by bacongobbler** [comment]
closing as stale. please re-open if you still see this issue.
