### ISSUE TITLE
100% inodes usage on machines running deis-builder

### ISSUE THREAD

**Issue by geeksoul-me** [deis/deis#4711]
I have been facing this issue for a long time now, but recently as we use deis more and more - this has become a huge problem.

We run around 30 applications, which have around 10 releases each on average per day. After 4 to 5 days, inodes become 100% (disk usage is still 45%).

We then start getting ```no space left on device``` when deploying apps using dockerfiles. 
We resolve this by 
```
root@my-local# deisctl ssh deis
core@deis-1 ~ $ nse deis-builder
bash-4.3#  docker images -aq | xargs docker rmi
```

This reduces inode usage from 100% to 64%

And after a few days, we have to do this again.

How can I prevent this from happening ?

**Comment by szymonpk** [comment]
Where are you running out of inodes, inside deis-builder container or on deis/coreos node?

How you deployed your cluster? Maybe it's something custom? Default deis settings for number of inodes never failed on me.

**Comment by geeksoul-me** [comment]
I'm running out inodes on coreoes node.

I have deployed a normal deis cluster in stateless mode. Nothing special. I have built, rebuilt the clusters several times. But this issue always comes up at some point.

I think it is due to excessive docker images inside builder, maybe its not cleaning up old images .

**Comment by geeksoul-me** [comment]
When I opened this issue, I had just cleaned up images and inode usage was 65%. We have made around 10 to 15 releases in total after that. Inode usage is already 81% now.

```
core@deis-1 ~ $ df -i
Filesystem       Inodes    IUsed   IFree IUse% Mounted on
devtmpfs         503169      318  502851    1% /dev
tmpfs            506481        1  506480    1% /dev/shm
tmpfs            506481     1143  505338    1% /run
tmpfs            506481       14  506467    1% /sys/fs/cgroup
/dev/vda9      15050112 12167784 2882328   81% /
/dev/vda3        260096     4572  255524    2% /usr
tmpfs            506481        8  506473    1% /tmp
/dev/vda1             0        0       0     - /boot
tmpfs            506481        1  506480    1% /media
/dev/vda6         32768       13   32755    1% /usr/share/oem
```

**Comment by geeksoul-me** [comment]
Some more information, that might be related to this. 

We use dockerfiles for deployment. Deployment is done through a script that that runs "git push deis master" inside several project folders. It was assumed that, if a project is already up to date in deis remote it would be not deployed and just returned with a message "everything is up to date". 

But that does no seem to be happening, I just ran a ```deis releases``` command in a app and found many releases with same git hash. Which means, its updating the apps, again and again - even when they are up to date. 

Sample ```deis releases``` output below:

```
v5      2015-11-05T11:56:07UTC  vinay deployed 0818d96
v4      2015-11-04T11:25:59UTC  vinay deployed 0818d96
v3      2015-11-02T07:01:45UTC  vinay deployed 0818d96
v2      2015-10-30T09:35:40UTC  vinay deployed 0818d96
v1      2015-10-30T09:33:52UTC  vinay created initial release
```

**Comment by szymonpk** [comment]
It's common issue, deis running out of space deis/deis#3675. But I've never ran out of inodes. Easies fix is stop builder remove `deis-builder-data` image and start it again, we've to do this once per 2-3 weeks on busy cluster with 100GB volumes for docker images.

**Comment by kuvi-innovations** [comment]
I had to teardown the cluster and provision a new one for now. I'm sure this is going to come up again, will try your suggestion.

**Comment by geeksoul-me** [comment]
Issue is back on the new cluster, removing ```deis-builder-data``` doesn't seem to be make any difference. I still have to:
```
core@deis-1 ~ $ nse deis-builder
bash-4.3#  docker images -aq | xargs docker rmi
```

**Comment by szymonpk** [comment]
In linked issue I've posted few command which can help you with pinpointing volume which is eating most of your disk space.

**Comment by geeksoul-me** [comment]
As I run a stateless-cluster , easiest work around for me is swapping out the inode crunched machine with a fresh machine, then builder is automatically scheduled to another machine where inodes are usually more than 60% free. I also get a new machine that has free inodes.

This is the easiest and quickest work around for this problem for me till now.

**Comment by bacongobbler** [comment]
I thought we removed deis-builder-data but I guess I was wrong. We should remove this so users can clear the inode usage by just restarting the builder for now.

**Comment by bacongobbler** [comment]
closing as resolved in v2. Kubernetes handles the stale image cleanup for us, so this shouldn't be an issue any more.
