### ISSUE TITLE
Unable to download any client versions instead of 1.12.0

### ISSUE THREAD

**Issue by rvadim** [deis/deis#4712]
curl -f -o /tmp/deis-cli-1.11.2-linux-amd64.run https://s3-us-west-2.amazonaws.com/get-deis/deis-cli-1.11.2-linux-amd64.run
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 403 Forbidden

**Comment by lamanotrama** [comment]
`deisctl` can't also be downloaded.

```
curl -f -o /tmp/deisctl-1.11.2-linux-amd64.run https://s3-us-west-2.amazonaws.com/get-deis/deisctl-1.11.2-linux-amd64.run
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
```

**Comment by LoicMahieu** [comment]
Confirmed... Really annoying :s blocking all deployments

**Comment by mboersma** [comment]
The previous installers are in the old S3 bucket "opdemand", not "get-deis". I will copy the older installers to the new bucket so either location will work.

**Comment by sgoings** [comment]
@mboersma didn't you fix this already? Can this be closed?

**Comment by rvadim** [comment]
Yes! It works, thank you.
