### ISSUE TITLE
deis v1.12.0 : clusters missing

### ISSUE THREAD

**Issue by goacid** [deis/deis#4714]
According to documentation deis clusters is an existing option.
According to the binary it is not : 
      
    login@login:~/.../Deis/MyApp$ deis --version
    1.12.0
    login@login:~/.../Deis/MyApp$ deis help clusters
    Found no matching command, try 'deis help'
    Usage: deis <command> [<args>...]
    login@login:~/.../Deis/MyApp$ deis  apps:create myapp --clusters=dev
    login@login:~/.../Deis/MyApp$ deis  apps:create myapp --cluster=dev
    Usage: deis apps:create [<id>] [options]

**Comment by sgoings** [comment]
Where do you see in the documentation that clusters is an existing option? When I execute `help` for `apps:create` I see:

```
deis help apps:create
Creates a new application.

- if no <id> is provided, one will be generated automatically.

Usage: deis apps:create [<id>] [options]

Arguments:
  <id>
    a uniquely identifiable name for the application. No other app can already
    exist with this name.

Options:
  --no-remote
    do not create a 'deis' git remote.
  -b --buildpack BUILDPACK
    a buildpack url to use for this app
  -r --remote REMOTE
    name of remote to create. [default: deis]
```

**Comment by goacid** [comment]
http://docs.deis.io/en/scheduler/client/clusters/
http://docs.deis.io/en/scheduler/client/create/

**Comment by sgoings** [comment]
You've managed to venture into a part of our old documentation... see reference to what version those docs are on this page: http://docs.deis.io/en/scheduler/operations/#operations

@mboersma was working with the folks at readthedocs.org to [get the stale documentation pages removed](https://github.com/rtfd/readthedocs.org/issues/999#issuecomment-60801546) but it never was resolved. We'll work on cleaning these old documentation references up on the readthedocs.org side.

To get you back up and running, the documentation you should be looking at has the root: http://docs.deis.io/en/latest/ (note /en/latest not /en/scheduler).

Thanks for bringing this to our attention!
