### ISSUE TITLE
Controller API (adding a donain) docs/implementation is not correct

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#4716]
http://docs.deis.io/en/latest/reference/api-v1.7/#add-domain

current example states
~~~
POST /v1/apps/example-go/domains/ HTTP/1.1
Host: deis.example.com
Authorization: token abc123

{'domain': 'example.example.com'}
~~~

which does not work (`{"app"=>["This field is required."]}`), it should be

~~~
POST /v1/apps/example-go/domains/ HTTP/1.1
Host: deis.example.com
Authorization: token abc123

{'domain': 'example.example.com', 'app': 'example-go'}
~~~

Although you can wonder why the app is in the URL then.

**Comment by nathansamson** [comment]
I did not any other similar requests, their might be others wrong in similar fashion

**Comment by bacongobbler** [comment]
Interesting. The request should be able to interpret the app from the incoming request URL, but I guess the serializers aren't playing ball.

**Comment by Joshua-Anderson** [comment]
@nathansamson Unable to reproduce on master in either the client (which uses this part of the api) or in a raw request.

![screenshot from 2015-11-09 18-48-34](https://cloud.githubusercontent.com/assets/3526404/11053055/856d7e36-8712-11e5-83d7-749847fa91d6.png)
![screenshot from 2015-11-09 18-49-37](https://cloud.githubusercontent.com/assets/3526404/11053075/aa29351c-8712-11e5-8a6b-56ef2fc6ba13.png)
