### ISSUE TITLE
502 bad gateway and/or app hanging on deploy - deis v1.12.0

### ISSUE THREAD

**Issue by jeff-lee** [deis/deis#4717]
Hey,

I started running some v1.12.0 tests and am getting 502 bad gateways on deploy.

Setup:
AWS
5 x c3.2xl cluster for platform
2 x c3.2xl cluster for apps

1. Clone and install the example-go app
2. ps:scale web=3
3. Start a loop curling the endpoint
4. Build the app

11:02:45 [ds12] - /Users/jefflee/work/trr/deis/deis-example/example-go
$ deis info -a jefftest
=== jefftest Application
updated:  2015-11-05T18:50:10UTC
uuid:     20949ab0-ffbd-4442-b490-f7b01951976b
created:  2015-11-05T18:43:43UTC
url:      jefftest.ds12.therealreal.com
owner:    jefflee
id:       jefftest

=== jefftest Processes
--- web:
web.1 up (v5)
web.2 up (v5)
web.3 up (v5)

Release v4 on af2bdfaa3e47
Thu Nov  5 10:57:48 PST 2015
Powered by Deis
Release v4 on af2bdfaa3e47
Thu Nov  5 10:57:49 PST 2015
Powered by Deis
Release v4 on 9127a2c51779
Thu Nov  5 10:57:49 PST 2015
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.9.6</center>
</body>
</html>
Thu Nov  5 10:57:49 PST 2015
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.9.6</center>
</body>
</html>
Thu Nov  5 10:57:49 PST 2015
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.9.6</center>
</body>
</html>
Thu Nov  5 10:57:49 PST 2015
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.9.6</center>
</body>
</html>
Thu Nov  5 10:57:50 PST 2015
Powered by Deis

In other tests, calls to the endpoint hang for over 30s while the the containers are switching over to the new version.

Thu Nov  5 11:05:09 PST 2015
Powered by Deis
Release v5 on f21dd3cabae1
Thu Nov  5 11:05:09 PST 2015

<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.9.6</center>
</body>
</html>
Thu Nov  5 11:05:39 PST 2015
Powered by Deis

**Comment by jeff-lee** [comment]
Everything stops after the old containers are killed.  It looks like they may be getting killed before the new ones are able to serve traffic.

<pre>
Nov 05 19:53:44 ip-10-10-19-9.ec2.internal sh[1164]: 2015/11/05 19:53:44 event: 88d54fc5497a stop
Nov 05 19:53:44 ip-10-10-19-9.ec2.internal sh[1164]: 2015/11/05 19:53:44 event: 88d54fc5497a kill

Thu Nov  5 19:53:43 UTC 2015
CONTAINER ID        IMAGE                            COMMAND                CREATED              STATUS                  PORTS                     NAMES
8361b450441e        10.10.16.243:5000/jefftest:v26   "/runner/init start    1 seconds ago        Up Less than a second   0.0.0.0:32805->5000/tcp   jefftest_v26.web.1
631f5861807d        10.10.16.243:5000/jefftest:v26   "/runner/init start    1 seconds ago        Up Less than a second   0.0.0.0:32804->5000/tcp   jefftest_v26.web.3
88d54fc5497a        10.10.16.243:5000/jefftest:v25   "/runner/init start    About a minute ago   Up About a minute       0.0.0.0:32803->5000/tcp   jefftest_v25.web.1
ab236a85fe2c        deis/publisher:v1.12.0           "/usr/local/bin/publ   About an hour ago    Up About an hour                                  deis-publisher
6fa2452a6d15        deis/logspout:v1.12.0            "/bin/logspout"        About an hour ago    Up About an hour                                  deis-logspout
Thu Nov  5 19:53:44 UTC 2015
CONTAINER ID        IMAGE                            COMMAND                CREATED             STATUS              PORTS                     NAMES
8361b450441e        10.10.16.243:5000/jefftest:v26   "/runner/init start    2 seconds ago       Up 1 seconds        0.0.0.0:32805->5000/tcp   jefftest_v26.web.1
631f5861807d        10.10.16.243:5000/jefftest:v26   "/runner/init start    2 seconds ago       Up 1 seconds        0.0.0.0:32804->5000/tcp   jefftest_v26.web.3
ab236a85fe2c        deis/publisher:v1.12.0           "/usr/local/bin/publ   About an hour ago   Up About an hour                              deis-publisher
6fa2452a6d15        deis/logspout:v1.12.0            "/bin/logspout"        About an hour ago   Up About an hour                              deis-logspout

Powered by Deis
Release v25 on 88d54fc5497a
Thu Nov  5 11:53:47 PST 2015
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.9.6</center>
</body>
</html>
Thu Nov  5 11:54:18 PST 2015
Powered by Deis
Release v26 on 8361b450441e
</pre>

**Comment by mboersma** [comment]
Does this behave better if you set a [`HEALTHCHECK_URL`](http://docs.deis.io/en/latest/using_deis/config-application/#custom-health-checks)?

**Comment by jeff-lee** [comment]
@mboersma That seems to fix the timeout, but am getting some strange results when scaling an app up or down while a build is happening - not sure whether or not it's related.  I'll try to isolate.

In general, should all apps have healthchecks now?  I don't recall seeing this error in earlier versions, but to be fair I didn't do a lot of testing of the endpoints while building.

**Comment by bacongobbler** [comment]
>  I don't recall seeing this error in earlier versions, but to be fair I didn't do a lot of testing of the endpoints while building.

This has always been Deis' behaviour when it comes to deploying a new version. By default, the old containers are killed off as soon as fleet says the new version is up, which essentially means the container has booted. However, if your new container takes a while to actually boot (database migrations, initialization etc.), 504s will occur. That's where HEALTHCHECK_URL comes in. We didn't want to enforce this policy by default because it looks for a 200 OK at the root (/), which some applications might not respond as expected and that would be a breaking change. Therefore, you need to opt into this. You might also want to take a look into setting HEALTHCHECK_INITIAL_DELAY as well if you know how long it takes between the container booting and your app listening for incoming requests, as by default it's set to zero so health checks occur immediately.

> In general, should all apps have healthchecks now?

It depends on if you care about zero-downtime deploys. If so then yes, all your apps should have health checks. If that's not much of a concern and you care more about a faster deployment pipeline, then you should leave it unset.

Hope this helps!

**Comment by jeff-lee** [comment]
Ok.  We'll add those.  Thanks.

It looks like it's possible to get in a situation where there are zero processes running if you scale down while a build is happening.  I'm guessing that the scaling operation is shutting down the new units and then the deploy process is shutting down the old ones.  This happens with and without the HEALTHCHECK_URL set.  

I'll try to narrow things down and open a separate ticket.

**Comment by bacongobbler** [comment]
> It looks like it's possible to get in a situation where there are zero processes running if you scale down while a build is happening.

Please do. If you're scaling down to zero then that's intentional, but if not then it'd be interesting to see how that occurs.
