### ISSUE TITLE
Flannel doesn't start after reboot

### ISSUE THREAD

**Issue by afterthought** [deis/deis#4718]
https://github.com/deis/deis/commit/445dbaecfadb1e2690734413cc43f30abcb13b21#diff-be438a7ce6a159afe476e6cb80c59eddR53

I had been using "set" instead of "mk" in my unit. I was updating my units to match the official Deis files and when I changed this to "mk" flannel wouldn't boot because this key was already set. I might be missing something, because I would think others would have run into this very fast. Might just be something unique in my setup.

**Comment by aledbf** [comment]
@afterthought in the flanneld.service is missing `command: start`

**Comment by afterthought** [comment]
I added command:start as well. However, before I added that it was still starting (maybe because of a dependency?) and it kept failing over and over on the line creating the etcd key.

**Comment by mboersma** [comment]
This fix for `flannel.service` is in [Deis v1.12.1](https://github.com/deis/deis/releases/tag/v1.12.1).
