### ISSUE TITLE
user-data: flannel configuration setup fails on any node but the first

### ISSUE THREAD

**Issue by jannispl** [deis/deis#4724]
This line in `user-data` is responsible for setting up flannel through etcd: https://github.com/deis/deis/commit/445dbaecfadb1e2690734413cc43f30abcb13b21#diff-be438a7ce6a159afe476e6cb80c59eddR53

All nodes trying to `mk` this etcd key = first node succeeding, others failing. Eventually flanneld fails to start and that in turn makes docker fail to start.

I have already fixed this for my production cluster by changing it like this: (adding the error-supressing `-`)
```
ExecStartPre=-/usr/bin/etcdctl mk /coreos.com/network/config '{"Network": "10.244.0.0/16", "SubnetLen": 24, "SubnetMin": "10.244.0.0", "Backend": {"Type": "vxlan"}}'
```
`etcdctl set` would also work, but would overwrite any customization the user might apply.

PR coming later, this issue reminds me to do it.

**Comment by mboersma** [comment]
> I have already fixed this for my production cluster by changing it like this

@jannispl, great minds think alike: Deis implemented [the same fix](https://github.com/deis/deis/commit/b07db69e9b3ad197d869fec4cb0b5a7051a0ef16) in [Deis v1.12.1](https://github.com/deis/deis/releases/tag/v1.12.1). :grinning:
