### ISSUE TITLE
Can't run http server.

### ISSUE THREAD

**Issue by YUSTAS2009** [deis/deis#4728]
Can't run http server, error: 
$ npm start
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                                                                                                                               node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! path D:\Git\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'D:\Git\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Git\npm-debug.log

My project with package.json file in D:\Git-projects\angular-phonecatpackage/package.json puth. How can I change directory? How to fix this problem? Thank you.

**Comment by krancour** [comment]
This does not look the least bit related to Deis.  Perhaps this issue was accidentally opened against the wrong project?  Closing.

**Comment by YUSTAS2009** [comment]
Thank you. I opened wrog project. Now it run well.
