### ISSUE TITLE
repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*" when push to deis

### ISSUE THREAD

**Issue by tuananh** [deis/deis#4733]
When i `git push deis master`, i got the below error and the app fails to build after.

    Counting objects: 933, done.
    Delta compression using up to 4 threads.
    Compressing objects: 100% (922/922), done.
    Writing objects: 100% (933/933), 134.49 KiB | 0 bytes/s, done.
    Total 933 (delta 576), reused 0 (delta 0)
    Unable to find image 'MyApp:latest' locally
    repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"
    To ssh://git@<my-deis-domain>:2222/my-app-test.git
     * [new branch]      master -> master

How do i fix this? Is this known bug?

**Comment by tuananh** [comment]
It seems to be caused by ENV vars. I removed `NEW_RELIC_APP_NAME` env var and it works now.

**Comment by sgoings** [comment]
I'm thinking the error has more to do with the name of the Docker image... and the use of Docker Registry V2.

See more info:

- Documentation: https://docs.docker.com/registry/spec/api/#overview
- Issue reports: https://github.com/docker/distribution/issues/1008

**Comment by bacongobbler** [comment]
Yes. This actually looks more like the FROM clause uses CamelCase which docker doesn't like. Try using lowercase, do a `docker build .` locally after running `docker rm -f $(docker ps -aq)` so you're at a clean slate and see if that works.

**Comment by mboersma** [comment]
Yes, this is because now that Deis interacts with Docker registry V2, repository names must comply with a stricter spec:
```console
$ docker pull MyApp:latest
repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"
```

**Comment by KabeloShongwe** [comment]
please use lowercase
