### ISSUE TITLE
Disappearing Apps on Deployment

### ISSUE THREAD

**Issue by Crispy1975** [deis/deis#4734]
Something a little concerning has come up a few times recently. On doing a `git push` deploy to our production Deis v1.10.1 cluster - using Dockerfiles - we have lost that application entirely. The deploy process goes through the motions of the build, and then the push to the registry (stateless S3), however the router is throwing back a 403 from nginx and the application is down. Pushing again immediately has so far resolved the issue.

To date I have not located anything convincing from our PaperTrail logs that indicate any kind of a problem, everything looks normal. Is there something that we could check for this?

**Comment by iancoffey** [comment]
@Crispy1975 Have you noticed if the new app containers actually come up when the deploy happens?

The source of truth for what nginx will publish is the etcd service keys in /deis/service, which are created by the publisher from the docker event stream, so it would seem that something in this chain is broken. When this happens, checking if the app containers are up, and published to the service etcd directory would be a good start. 

Depending on whats going on there, the issue can be narrowed down quite a bit,

**Comment by Crispy1975** [comment]
@iancoffey from memory the containers are not present when this happens according to `fleetctl list-units`, however I will check when/if this happens again.

**Comment by bacongobbler** [comment]
ping @Crispy1975, have you seen this happen again?

**Comment by bacongobbler** [comment]
closing as inactive, but please feel free to re-open this bug when you get more info to share. Thanks!
