### ISSUE TITLE
Terraform / Rigger  DO provisioning, unable to deploy multiple clusters

### ISSUE THREAD

**Issue by geeksoul-me** [deis/deis#4747]
I have a 3 node cluster with names: deis-1, deis-2 and deis-3 running on DO. I want to setup two more clusters like this. In 'Create CoreOS Droplets' step at http://docs.deis.io/en/latest/installing_deis/digitalocean/ , I see that there is a option to send custom prefix. But when I run ```terraform apply``` , it powers down my existing cluster and things go haywire.

Below is an example command I am using to create a new cluster with names "devdeis"

```
$ terraform apply -var 'token=a1b2c3d3e4f5' \
                  -var 'ssh_keys=c1:d3:a2:b4:e4:f5' \
                  -var 'region=nyc3' \
                  -var 'prefix=devdeis' \
                  -var 'instances=3' \
                  -var 'size=8GB' \
                  contrib/digitalocean
```

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776), and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this.
