### ISSUE TITLE
add deis apps:rename command

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#475]
For my applications, I'd like to be able to rename them to something more descriptive than `kingly-gemstone`. This should follow the spec that heroku has already laid out at https://devcenter.heroku.com/articles/renaming-apps

**Comment by olalonde** [comment]
+1. Personally, I don't mind what the docker containers are called. I would just like to have more descriptive names when I run `deis apps`. Internally, `deis apps:rename` could just map the new name to the actual docker container name without changing it.

**Comment by olalonde** [comment]
Has this been implemented yet?

**Comment by mboersma** [comment]
> Has this been implemented yet?

Not yet. We would love to see a PR submitted. :smile:

**Comment by carmstrong** [comment]
> I would just like to have more descriptive names when I run deis apps

`apps:rename` hasn't been implemented. Are you aware that you can give an app a descriptive name when you create it? There's a parameter for the application's name, and you can give it a friendly one.

**Comment by Joshua-Anderson** [comment]
I'd be happy to take a look at this once the go client rewrite has settled down.

**Comment by deis-admin** [comment]
This issue was moved to deis/controller#1217
