### ISSUE TITLE
"git push deis master" creates an app but does not create the processs.

### ISSUE THREAD

**Issue by robeferre** [deis/deis#4755]
I was working pretty fine with the 1.11.x version, I just upgraded to the 1.12.1, I have an app that was working fine at the previous version, but now every time that I try to push my app to deis, my app is created, but the processes are not available.

root@james:/u01/deis_apps/portal3# git push deis master
Counting objects: 3, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 428 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)

-----> Building Docker image
remote: Sending build context to Docker daemon 2.048 kB
Step 0 : FROM robeferre/jboss:as7
 ---> 64f212c4250e
Step 1 : MAINTAINER ROBERTO FERREIRA JUNIOR
 ---> Using cache
 ---> a1743699e14b
Step 2 : RUN echo admin=e69ece0378522fdff0c061f63c8e65a2 > /jboss-as-7.1.1.Final/domain/configuration/mgmt-users.properties
 ---> Using cache
 ---> 82077a521baa
Step 3 : RUN echo admin=e69ece0378522fdff0c061f63c8e65a2 > /jboss-as-7.1.1.Final/standalone/configuration/mgmt-users.properties
 ---> Using cache
 ---> 6eb20a3ede8a
Step 4 : CMD /run.sh
 ---> Using cache
 ---> f73c57219703
Step 5 : EXPOSE 8080
 ---> Using cache
 ---> beebd9f0eb4c
Step 6 : ENV GIT_SHA 2c55f94e56449649de81d9523cb4a8390e2dee84
 ---> Running in bfda4b675c13
 ---> 60635dd51372
Removing intermediate container bfda4b675c13
Successfully built 60635dd51372
-----> Pushing image to private registry
To ssh://git@deis.192.168.57.69.xip.io:2222/knotty-vineyard.git
 * [new branch]      master -> master

Heres how my app looks like after the build process:

root@james:/u01/deis_apps/portal3# deis info
=== knotty-vineyard Application
updated:  2015-11-17T17:08:46UTC
uuid:     0001bfb4-bf27-419c-82d3-ce71a02c164f
created:  2015-11-17T17:08:46UTC
url:      knotty-vineyard.192.168.57.69.xip.io
owner:    admin
id:       knotty-vineyard

=== knotty-vineyard Processes

=== knotty-vineyard Domains

**Comment by krancour** [comment]
@robeferre, could we see builder and controller logs coinciding with this?

**Comment by robeferre** [comment]
@krancour Thanks a lot

Bulder Logs:

Nov 17 17:22:36 coreos001 sh[19944]: [info] Checking closer.
Nov 17 17:22:36 coreos001 sh[19944]: [info] Accepted connection.
Nov 17 17:22:36 coreos001 sh[19944]: [info] Adding key 'command="/usr/local/bin/gitreceive run admin 4f:a4:b6:be:61:5a:3a:54:05:88:db:d5:8f:02:0d:5f",no-agent-forwarding,no-pty,no-user-rc,no-X11-forwarding,no-port-forwarding ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCrA8VyELbzkaKCNpc/VBej3W2tjJoPXMS8pH1xZpPELFesEq6CA42IV4cYoliBAVz8yj5G2UtJk54jh5UlLzazrkbEuB9+Cdp8dHdBlF3EZ/QRTJyHAEtgcv+jMKUUi2iYtUSQvdze9oXJBTY8buuGdesErGvCNQesJpakNybc/+cyJxsgfTPoRS3m14S38lzcdRxOJH+aOVc0QrgxB0x0L51Zrbdgvf9mpqXlhtTw7lGRfGHaw8VD+oG3VFXEwlS6bb+eJWPdln8LN7/UNfW33NKI5AaoKu8sHHLNhwngTNlwpHcVqMOjUl703HLUQC/IlPo74bo31Z86fTkbrP0RgRxZYX8H6u1IY8HoaYzM7nlb8UY88kLBUTUZfeiyEqlUWlPhvl1cjQo1jsYKhidecPz15/GlGfct3or+3d1WUDU1G+JdeISUIECRHcmM+LFbQHf6jAxKso9etfG/4kRGAXw1mGRKF6jjXsgGlHjS/SBreMUVK7QLXkktJH+mDwPXd7CmQnRgK7O5Q/ZrmBJRPUiZrTHm2syNAfBpWFz9chbQqBzYcBB4RqNASNthdwhjrhk/sSdb+q4nmFTj7tbR7u7wJE3KFle1grCJ4CTh5WJfo3jY4q3hXURhZivGXMUJLOl29tl/YlrAyk+xzkJtI8YsERojcwQlT5ywDMxTYw== your_email@example.com'
Nov 17 17:22:36 coreos001 sh[19944]: [info] Adding key 'command="/usr/local/bin/gitreceive run admin 4f:a4:b6:be:61:5a:3a:54:05:88:db:d5:8f:02:0d:5f",no-agent-forwarding,no-pty,no-user-rc,no-X11-forwarding,no-port-forwarding ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCrA8VyELbzkaKCNpc/VBej3W2tjJoPXMS8pH1xZpPELFesEq6CA42IV4cYoliBAVz8yj5G2UtJk54jh5UlLzazrkbEuB9+Cdp8dHdBlF3EZ/QRTJyHAEtgcv+jMKUUi2iYtUSQvdze9oXJBTY8buuGdesErGvCNQesJpakNybc/+cyJxsgfTPoRS3m14S38lzcdRxOJH+aOVc0QrgxB0x0L51Zrbdgvf9mpqXlhtTw7lGRfGHaw8VD+oG3VFXEwlS6bb+eJWPdln8LN7/UNfW33NKI5AaoKu8sHHLNhwngTNlwpHcVqMOjUl703HLUQC/IlPo74bo31Z86fTkbrP0RgRxZYX8H6u1IY8HoaYzM7nlb8UY88kLBUTUZfeiyEqlUWlPhvl1cjQo1jsYKhidecPz15/GlGfct3or+3d1WUDU1G+JdeISUIECRHcmM+LFbQHf6jAxKso9etfG/4kRGAXw1mGRKF6jjXsgGlHjS/SBreMUVK7QLXkktJH+mDwPXd7CmQnRgK7O5Q/ZrmBJRPUiZrTHm2syNAfBpWFz9chbQqBzYcBB4RqNASNthdwhjrhk/sSdb+q4nmFTj7tbR7u7wJE3KFle1grCJ4CTh5WJfo3jY4q3hXURhZivGXMUJLOl29tl/YlrAyk+xzkJtI8YsERojcwQlT5ywDMxTYw== your_email@example.com'
Nov 17 17:22:36 coreos001 sh[19944]: [info] Key accepted for user git.
Nov 17 17:22:36 coreos001 sh[19944]: [info] Channel type: session
Nov 17 17:22:36 coreos001 sh[19944]: Key='LANG', Value='pt_BR.UTF-8'
Nov 17 17:22:36 coreos001 sh[19944]: [info] Checking user /deis/builder/users/admin
Nov 17 17:22:36 coreos001 sh[19944]: [info] Found user admin for fingerprint 4f:a4:b6:be:61:5a:3a:54:05:88:db:d5:8f:02:0d:5f
Nov 17 17:22:36 coreos001 sh[19944]: [info] Directory /home/git/knotty-vineyard.git already exists.
Nov 17 17:22:36 coreos001 sh[19944]: [info] git-shell -c git-receive-pack 'knotty-vineyard.git'
Nov 17 17:22:36 coreos001 sh[19944]: Waiting for git-receive to run.
Nov 17 17:22:36 coreos001 sh[19944]: Waiting for deploy.
Nov 17 17:22:36 coreos001 sh[19944]: [info] Deploy complete.
Nov 17 17:22:38 coreos001 sh[19944]: [info] Checking closer.
Nov 17 17:22:38 coreos001 sh[19944]: [info] Accepted connection.
Nov 17 17:22:38 coreos001 sh[19944]: [info] Adding key 'command="/usr/local/bin/gitreceive run admin 4f:a4:b6:be:61:5a:3a:54:05:88:db:d5:8f:02:0d:5f",no-agent-forwarding,no-pty,no-user-rc,no-X11-forwarding,no-port-forwarding ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCrA8VyELbzkaKCNpc/VBej3W2tjJoPXMS8pH1xZpPELFesEq6CA42IV4cYoliBAVz8yj5G2UtJk54jh5UlLzazrkbEuB9+Cdp8dHdBlF3EZ/QRTJyHAEtgcv+jMKUUi2iYtUSQvdze9oXJBTY8buuGdesErGvCNQesJpakNybc/+cyJxsgfTPoRS3m14S38lzcdRxOJH+aOVc0QrgxB0x0L51Zrbdgvf9mpqXlhtTw7lGRfGHaw8VD+oG3VFXEwlS6bb+eJWPdln8LN7/UNfW33NKI5AaoKu8sHHLNhwngTNlwpHcVqMOjUl703HLUQC/IlPo74bo31Z86fTkbrP0RgRxZYX8H6u1IY8HoaYzM7nlb8UY88kLBUTUZfeiyEqlUWlPhvl1cjQo1jsYKhidecPz15/GlGfct3or+3d1WUDU1G+JdeISUIECRHcmM+LFbQHf6jAxKso9etfG/4kRGAXw1mGRKF6jjXsgGlHjS/SBreMUVK7QLXkktJH+mDwPXd7CmQnRgK7O5Q/ZrmBJRPUiZrTHm2syNAfBpWFz9chbQqBzYcBB4RqNASNthdwhjrhk/sSdb+q4nmFTj7tbR7u7wJE3KFle1grCJ4CTh5WJfo3jY4q3hXURhZivGXMUJLOl29tl/YlrAyk+xzkJtI8YsERojcwQlT5ywDMxTYw== your_email@example.com'
Nov 17 17:22:38 coreos001 sh[19944]: [info] Adding key 'command="/usr/local/bin/gitreceive run admin 4f:a4:b6:be:61:5a:3a:54:05:88:db:d5:8f:02:0d:5f",no-agent-forwarding,no-pty,no-user-rc,no-X11-forwarding,no-port-forwarding ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCrA8VyELbzkaKCNpc/VBej3W2tjJoPXMS8pH1xZpPELFesEq6CA42IV4cYoliBAVz8yj5G2UtJk54jh5UlLzazrkbEuB9+Cdp8dHdBlF3EZ/QRTJyHAEtgcv+jMKUUi2iYtUSQvdze9oXJBTY8buuGdesErGvCNQesJpakNybc/+cyJxsgfTPoRS3m14S38lzcdRxOJH+aOVc0QrgxB0x0L51Zrbdgvf9mpqXlhtTw7lGRfGHaw8VD+oG3VFXEwlS6bb+eJWPdln8LN7/UNfW33NKI5AaoKu8sHHLNhwngTNlwpHcVqMOjUl703HLUQC/IlPo74bo31Z86fTkbrP0RgRxZYX8H6u1IY8HoaYzM7nlb8UY88kLBUTUZfeiyEqlUWlPhvl1cjQo1jsYKhidecPz15/GlGfct3or+3d1WUDU1G+JdeISUIECRHcmM+LFbQHf6jAxKso9etfG/4kRGAXw1mGRKF6jjXsgGlHjS/SBreMUVK7QLXkktJH+mDwPXd7CmQnRgK7O5Q/ZrmBJRPUiZrTHm2syNAfBpWFz9chbQqBzYcBB4RqNASNthdwhjrhk/sSdb+q4nmFTj7tbR7u7wJE3KFle1grCJ4CTh5WJfo3jY4q3hXURhZivGXMUJLOl29tl/YlrAyk+xzkJtI8YsERojcwQlT5ywDMxTYw== your_email@example.com'
Nov 17 17:22:38 coreos001 sh[19944]: [info] Key accepted for user git.
Nov 17 17:22:38 coreos001 sh[19944]: [info] Channel type: session
Nov 17 17:22:38 coreos001 sh[19944]: Key='LANG', Value='pt_BR.UTF-8'
Nov 17 17:22:38 coreos001 sh[19944]: [info] Checking user /deis/builder/users/admin
Nov 17 17:22:38 coreos001 sh[19944]: [info] Found user admin for fingerprint 4f:a4:b6:be:61:5a:3a:54:05:88:db:d5:8f:02:0d:5f
Nov 17 17:22:38 coreos001 sh[19944]: [info] Directory /home/git/knotty-vineyard.git already exists.
Nov 17 17:22:38 coreos001 sh[19944]: [info] git-shell -c git-receive-pack 'knotty-vineyard.git'
Nov 17 17:22:38 coreos001 sh[19944]: Waiting for git-receive to run.
Nov 17 17:22:38 coreos001 sh[19944]: Waiting for deploy.
Nov 17 17:22:38 coreos001 sh[19944]: [info] Deploy complete.


Controller:
Nov 17 17:08:46 coreos003 sh[28348]: INFO knotty-vineyard: config knotty-vineyard-7dd19dd updated
Nov 17 17:08:46 coreos003 sh[28348]: INFO knotty-vineyard: release knotty-vineyard-v1 created
Nov 17 17:08:46 coreos003 sh[28348]: INFO [knotty-vineyard]: admin created initial release
Nov 17 17:08:46 coreos003 sh[28348]: 10.244.91.1 "POST /v1/apps/ HTTP/1.0" 201 216 "Deis Client v1.11.1"
Nov 17 17:08:56 coreos003 sh[28348]: 192.168.57.65 "POST /v1/hooks/push HTTP/1.1" 201 471 "curl/7.42.1"
Nov 17 17:08:56 coreos003 sh[28348]: 192.168.57.65 "POST /v1/hooks/config HTTP/1.1" 200 200 "deis-builder"
Nov 17 17:22:48 coreos003 sh[28348]: 192.168.57.65 "GET /v1/apps/knotty-vineyard/ HTTP/1.0" 200 216 "Deis Client v1.11.1"
Nov 17 17:22:48 coreos003 sh[28348]: 192.168.57.66 "GET /v1/apps/knotty-vineyard/containers/?page_size=100 HTTP/1.0" 200 52 "Deis Client v1.11.1"
Nov 17 17:22:48 coreos003 sh[28348]: 10.244.91.1 "GET /v1/apps/knotty-vineyard/domains/?page_size=100 HTTP/1.0" 200 52 "Deis Client v1.11.1"


I´m not sure if its related to the issue above but the registry is showing this critical error:

Nov 17 17:09:14 coreos002 sh[18812]: 17/Nov/2015:17:09:14 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Nov 17 17:09:14 coreos002 sh[18812]: 192.168.57.65 - - [17/Nov/2015:17:09:14 +0000] "GET /v1/images/beebd9f0eb4cac70267e3c8b8dcc822a31b35b8882f5131451b4c5a487b4a7a4/json HTTP/1.1" 404 28 "-" "docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/4.1.7-coreos os/linux arch/amd64"
Nov 17 17:09:14 coreos002 sh[18812]: 17/Nov/2015:17:09:14 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Nov 17 17:09:14 coreos002 sh[18812]: 192.168.57.65 - - [17/Nov/2015:17:09:14 +0000] "GET /v1/images/60635dd51372d68b3344eef9bf27210eeb5b40805517f9fc9bc6e01e59657850/json HTTP/1.1" 404 28 "-" "docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/4.1.7-coreos os/linux arch/amd64"
Nov 17 17:09:15 coreos002 sh[18812]: 17/Nov/2015:17:09:15 +0000 INFO: CORS request from Origin:None, setting Access-Control-Allow-Origin:null
Nov 17 17:09:15 coreos002 sh[18812]: 192.168.57.65 - - [17/Nov/2015:17:09:15 +0000] "PUT /v1/images/614eb10045c6d235c2d0181dadfd94c050f0c460f8241662f63f583c9b0cd089/json HTTP/1.1" 200 4 "-" "docker/1.8.3 go/go1.4.2 git-commit/f4bf5c7 kernel/4.1.7-coreos os/linux arch/amd64"
Nov 17 17:12:40 coreos002 sh[18812]: [2015-11-17 17:12:40 +0000] [38] [CRITICAL] WORKER TIMEOUT (pid:51)
Nov 17 17:12:40 coreos002 sh[18812]: [2015-11-17 17:12:40 +0000] [51] [INFO] Worker exiting (pid: 51)
Nov 17 17:12:40 coreos002 sh[18812]: [2015-11-17 17:12:40 +0000] [15602] [INFO] Booting worker with pid: 15602
Nov 17 17:12:40 coreos002 sh[18812]: 17/Nov/2015:17:12:40 +0000 WARNING: Cache storage disabled!
Nov 17 17:12:40 coreos002 sh[18812]: 17/Nov/2015:17:12:40 +0000 WARNING: LRU cache disabled!
Nov 17 17:12:40 coreos002 sh[18812]: 17/Nov/2015:17:12:40 +0000 INFO: Configuring CORS for app:'docker-registry' with resources:[(<_sre.SRE_Pattern object at 0x7fd186c2fc60>, {})]
Nov 17 17:12:40 coreos002 sh[18812]: 17/Nov/2015:17:12:40 +0000 WARNING: No S3 region specified, using boto default region, this may affect performance and stability.
Nov 17 17:12:40 coreos002 sh[18812]: 17/Nov/2015:17:12:40 +0000 INFO: Boto based storage initialized

**Comment by robeferre** [comment]
Also all units is running fine.
coreos001 myUnits # dl
UNIT                                    MACHINE                         LOAD    ACTIVE  SUB
deis-builder.service                    062c03aa.../192.168.57.65       loaded  active  running
deis-controller.service                 5f3514e3.../192.168.57.67       loaded  active  running
deis-database.service                   6331a62c.../192.168.57.66       loaded  active  running
deis-kube-apiserver.service             062c03aa.../192.168.57.65       loaded  active  running
deis-kube-controller-manager.service    062c03aa.../192.168.57.65       loaded  active  running
deis-kube-kubelet.service               062c03aa.../192.168.57.65       loaded  active  running
deis-kube-kubelet.service               5f3514e3.../192.168.57.67       loaded  active  running
deis-kube-kubelet.service               6331a62c.../192.168.57.66       loaded  active  running
deis-kube-proxy.service                 062c03aa.../192.168.57.65       loaded  active  running
deis-kube-proxy.service                 5f3514e3.../192.168.57.67       loaded  active  running
deis-kube-proxy.service                 6331a62c.../192.168.57.66       loaded  active  running
deis-kube-scheduler.service             062c03aa.../192.168.57.65       loaded  active  running
deis-logger.service                     5f3514e3.../192.168.57.67       loaded  active  running
deis-logspout.service                   062c03aa.../192.168.57.65       loaded  active  running
deis-logspout.service                   5f3514e3.../192.168.57.67       loaded  active  running
deis-logspout.service                   6331a62c.../192.168.57.66       loaded  active  running
deis-publisher.service                  062c03aa.../192.168.57.65       loaded  active  running
deis-publisher.service                  5f3514e3.../192.168.57.67       loaded  active  running
deis-publisher.service                  6331a62c.../192.168.57.66       loaded  active  running
deis-registry@1.service                 6331a62c.../192.168.57.66       loaded  active  running
deis-router@1.service                   062c03aa.../192.168.57.65       loaded  active  running
deis-router@2.service                   5f3514e3.../192.168.57.67       loaded  active  running
deis-router@3.service                   6331a62c.../192.168.57.66       loaded  active  running
deis-store-daemon.service               062c03aa.../192.168.57.65       loaded  active  running
deis-store-daemon.service               5f3514e3.../192.168.57.67       loaded  active  running
deis-store-daemon.service               6331a62c.../192.168.57.66       loaded  active  running
deis-store-gateway@1.service            062c03aa.../192.168.57.65       loaded  active  running
deis-store-metadata.service             062c03aa.../192.168.57.65       loaded  active  running
deis-store-metadata.service             5f3514e3.../192.168.57.67       loaded  active  running
deis-store-metadata.service             6331a62c.../192.168.57.66       loaded  active  running
deis-store-monitor.service              062c03aa.../192.168.57.65       loaded  active  running
deis-store-monitor.service              5f3514e3.../192.168.57.67       loaded  active  running
deis-store-monitor.service              6331a62c.../192.168.57.66       loaded  active  running
deis-store-volume.service               062c03aa.../192.168.57.65       loaded  active  running
deis-store-volume.service               5f3514e3.../192.168.57.67       loaded  active  running
deis-store-volume.service               6331a62c.../192.168.57.66       loaded  active  running

**Comment by robeferre** [comment]
I dont know why my image was not working, I tested using the base Jboss image and its working fine, just had to change some details.

Cheers
