### ISSUE TITLE
Proposal: Deploy docker images from private registries.

### ISSUE THREAD

**Issue by Crispy1975** [deis/deis#4756]
It would be great to be able to deploy pre-built docker images from private registries. As an idea each app could be configured using the `deis` client with a set of params to identify the registry endpoint, username, and password. I would suggest doing it at the app level as it gives the flexibility to have different images coming from different private registries. Something like the following to manage the registries:

```
deis registry:add
deis registry:list
deis registry:remove
```

On adding a registry the user would be prompted for that registries `endpoint`, `username`, and `password` which would then be stored internally.

Each app could then be told to get it's images from one of the stored registries. Perhaps setting the app level registry like so:

```
deis apps:registry -a <whatever> --registry=<name>
```

Could then use the `deis pull` command to make the image deployment.

**Comment by bacongobbler** [comment]
We already have this: `deis pull` will pull an image from a private registry. With the recent change to use the host's docker socket, technically you just need to add your credentials to .dockercfg on each host for it to work if you have authentication fronting your registry.

**Comment by bacongobbler** [comment]
@Crispy1975 it's been available since v0.10.0 :) https://github.com/deis/deis/releases/tag/v0.10.0

You can pull images from DockerHub as you'd normally expect. The syntax is generally the same as `docker pull`, but the meaning is changed from "pull an image into your local workspace" to "pull an image to be used as a new release of your application". For example, `deis create example-go && deis pull deis/example-go:latest` will create the app then pull the image from DockerHub, promoting it as the build image.

More docs here: http://docs.deis.io/en/latest/using_deis/using-docker-images/#using-docker-images

**Comment by Crispy1975** [comment]
Do I assume that the recent Docker announcement will affect this functionality from Docker Hub?

    On December 7, 2015, pulls via clients 1.5 and earlier will be disabled.
    Only version 1.6 or later will be supported.

To my knowledge Deis is running a version of CoreOS that uses `v1.5` of Docker?

I still think that the proposed functionality would be very flexible from and end user point of view, and very easy to use. Imagine being able to have 5 different Docker images (apps) that can be easily configured to pull from different private registries with no headaches. :)

**Comment by bacongobbler** [comment]
For versions older than v1.12.0, yes. However, master currently uses [v1.8.3](https://github.com/deis/deis/blob/v1.12.1/builder/rootfs/Dockerfile#L30) and any nodes provisioned with the v1.12.1 tag will be using [CoreOS 766.5.0](https://github.com/deis/deis/blob/v1.12.1/contrib/utils.sh#L16) which uses Docker v1.7.1. We've mentioned this in the release notes: https://github.com/deis/deis/releases/tag/v1.12.0

@mboersma hinted to me that private registry pulls might've been recently broken with the latest changes to `deis pull` though so we'll have to verify that. I'll file an issue.

I'm trying to read between the lines, but I'm still missing the use case for `registry:add` which `deis pull` doesn't already accomplish. Would you mind explaining how a user would go through its normal workflow, from app creation to procurement of the first build?

**Comment by bacongobbler** [comment]
#4760 to follow the thread

**Comment by bacongobbler** [comment]
ping @Crispy1975. I'm trying to read between the lines, but I'm still missing the use case for `registry:add` which `deis pull` doesn't already accomplish. Would you mind explaining how a user would go through its normal workflow, from app creation to procurement of the first build?

**Comment by Crispy1975** [comment]
@bacongobbler the idea was so that a list of different registries could be maintained, so you could have Docker Hub, Quay, or any other registry you want on an internal list identified by a simple tag of sorts.

This tag could then be used to allow different apps to pull their images from different private registries. From your explanation it sounds like you can only configure one private registry per host. But the idea here is to allow you to configure a private registry per app.

**Comment by bacongobbler** [comment]
> From your explanation it sounds like you can only configure one private registry per host.

Not exactly. `deis pull` will work with any registry that is discoverable from the cluster, so if you have a registry at 192.168.0.10 and your cluster is at 192.168.0.11 through 192.168.0.15, you can just run `deis pull 192.168.0.10/myimage:build-5309` and the controller will pull that image in and promote it as the build image. There's no need to maintain a "white list" of registries for `deis pull` to work.

To answer your use case:

> This tag could then be used to allow different apps to pull their images from different private registries.

`deis pull myprivateregistry.com/Crispy1975/myapp` should work shortly after we verify https://github.com/deis/deis/issues/4760 and fix it for the LTS release (https://github.com/deis/deis/issues/4776).

**Comment by Crispy1975** [comment]
Thanks @bacongobbler that `deis pull` sounds like it could be what we need. :)

**Comment by bacongobbler** [comment]
Excellent! Closing as resolved then. Thanks!
