### ISSUE TITLE
logspout didn't handle service restarts correctly

### ISSUE THREAD

**Issue by afterthought** [deis/deis#4759]
I have a timer that restarts each service nightly. I noticed though that logspout on one host didn't seem to properly reattach when the services restarted. I tried reproducing just now and cannot. I figured I'd post here just incase it struck someone as "obvious".

Here are the logspout logs from startup to the service restarts at midnight. Notice the "attach: <id> finished" for each service that got stopped/started with fleet at that time.

    Nov 17 21:58:54 ip-10-21-152-196.eu-central-1.compute.internal systemd[1]: Started deis-logspout.
    Nov 17 21:58:54 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/17 21:58:54 attach: 2164d3e91124 deis-logspout success
    Nov 17 21:58:54 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/17 21:58:54 attach: 5762afd18e92 emergency-fake-emergency-api_v1.cmd.0 success
    Nov 17 21:58:54 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/17 21:58:54 attach: b25d4608ed43 emergency-fake-emergency-processor_v1.cmd.0 success
    Nov 17 21:58:54 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/17 21:58:54 attach: 27dea00f7ac7 registration-eu-demo-api_v1.cmd.0 success
    Nov 17 21:58:54 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/17 21:58:54 attach: cb8c7d0a2307 feature-services-api-prod_v4.cmd.2 success
    Nov 17 21:58:54 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/17 21:58:54 attach: d1445b3d5bc9 feature-services-api-prod_v4.cmd.1 success
    Nov 17 21:58:54 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/17 21:58:54 attach: ed33837f28f2 event-tracking-eu-demo-api_v1.cmd.0 success
    Nov 17 21:58:54 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/17 21:58:54 attach: 0cbafaa039db dd-agent success
    Nov 17 21:58:54 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/17 21:58:54 attach: 6b6193f83ef8 deis-router success
    Nov 17 21:58:54 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/17 21:58:54 attach: e75c3ce57a58 deis-publisher success
    Nov 17 21:58:54 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/17 21:58:54 etcd: http://10.21.152.196:4001
    Nov 17 21:58:54 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/17 21:58:54 routing all to udp://10.21.3.4:514
    Nov 17 21:58:54 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/17 21:58:54 loading and persisting routes in /tmp
    Nov 17 21:58:54 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/17 21:58:54 logspout serving http on :8000
    Nov 18 00:00:21 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/18 00:00:21 attach: 5762afd18e92 finished
    Nov 18 00:00:31 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/18 00:00:31 attach: b25d4608ed43 finished
    Nov 18 00:00:41 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/18 00:00:41 attach: ed33837f28f2 finished
    Nov 18 00:01:01 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/18 00:01:01 attach: d1445b3d5bc9 finished
    Nov 18 00:01:11 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/18 00:01:11 attach: cb8c7d0a2307 finished
    Nov 18 00:02:01 ip-10-21-152-196.eu-central-1.compute.internal sh[31144]: 2015/11/18 00:02:01 attach: 27dea00f7ac7 finished

Here's what happened when I tried to reproduce, which seems like the expected behavior:

    Nov 18 17:36:38 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:36:38 attach: 1157e5bf9d38 deis-logspout success
    Nov 18 17:36:38 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:36:38 attach: d41926e158bd event-tracking-eu-demo-api_v1.cmd.0 success
    Nov 18 17:36:38 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:36:38 attach: d0bd8af982f1 emergency-fake-emergency-processor_v1.cmd.0 success
    Nov 18 17:36:38 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:36:38 attach: d83f94aa6a91 emergency-fake-emergency-api_v1.cmd.0 success
    Nov 18 17:36:38 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:36:38 attach: 7320eb701048 registration-eu-demo-api_v1.cmd.0 success
    Nov 18 17:36:38 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:36:38 attach: 012b5c82e6c2 feature-services-api-prod_v4.cmd.2 success
    Nov 18 17:36:38 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:36:38 attach: dd288767d9fc feature-services-api-prod_v4.cmd.1 success
    Nov 18 17:36:38 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:36:38 attach: 0cbafaa039db dd-agent success
    Nov 18 17:36:38 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:36:38 attach: 6b6193f83ef8 deis-router success
    Nov 18 17:36:38 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:36:38 attach: e75c3ce57a58 deis-publisher success
    Nov 18 17:36:38 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:36:38 etcd: http://10.21.152.196:4001
    Nov 18 17:36:38 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:36:38 routing all to udp://10.21.3.4:514
    Nov 18 17:36:38 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:36:38 loading and persisting routes in /tmp
    Nov 18 17:36:38 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:36:38 logspout serving http on :8000
    Nov 18 17:40:48 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:40:48 event: d0bd8af982f1 kill
    Nov 18 17:40:49 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:40:49 event: d0bd8af982f1 die
    Nov 18 17:40:49 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:40:49 attach: d0bd8af982f1 finished
    Nov 18 17:40:49 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:40:49 event: d0bd8af982f1 destroy
    Nov 18 17:41:10 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:41:10 event: vertx/vertx3 pull
    Nov 18 17:41:10 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:41:10 event: 88e5e63500b2 create
    Nov 18 17:41:10 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:41:10 event: 88e5e63500b2 attach
    Nov 18 17:41:10 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:41:10 event: 88e5e63500b2 start
    Nov 18 17:41:10 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:41:10 attach: 88e5e63500b2 emergency-fake-emergency-processor_v1.cmd.0 success
    Nov 18 17:41:10 ip-10-21-152-196.eu-central-1.compute.internal sh[25161]: 2015/11/18 17:41:10 event: 88e5e63500b2 attach

I'm running 1.12.1

**Comment by krancour** [comment]
I haven't seen this before.  With older versions of Deis, I have witnessed logspout _not_ attaching to containers after some period of time when a deadlock has occurred.  That was fixed long ago.  This looks as if it successfully attached and then _detached_.

If it can't be deterministically replicated, the most I can do for the moment is keep an eye out for this.

Thank you for reporting it.  If it happens again, please pass along more logs.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant so I'm closing this.
