### ISSUE TITLE
Deis no longer drains app logs via `/deis/logs/drain`?

### ISSUE THREAD

**Issue by kenaniah** [deis/deis#4768]
Looking to drain application logs to Papertrail. Docs (http://docs.deis.io/en/latest/managing_deis/platform_logging/#application-log-drain) suggest a method using `deisctl config logs set drain=...`, which apparently manages the `/deis/logs/drain` key in etcd. However, looking through the source code, it appears as though Deis v0.12  and onwards no longer consult this etcd key.

Is there another a new way to ship application logs?

**Comment by bacongobbler** [comment]
@kenaniah AFAIK this is [still available as a feature](https://github.com/deis/deis/blob/5bec074c6fd1e092ce2fb1e1fe1d56d4680739c2/logger/configurer/configurer.go#L93). Are no logs being drained to your forwarded address, or is this just a general question?

**Comment by kenaniah** [comment]
No logs are being drained. Logs will drain when adding a service that performs `journalctl -f | ncat --ssl ...`, but the logger service is not consulting the drain key, even after stop / start.

**Comment by kenaniah** [comment]
Actually, it turns out this was an oversight in the documentation. I had to restart the `deis-logger` and `deis-logspout` services (unclear if restarting `deis-logger` first was necessary) after making the `deisctl config set` call.

**Comment by krancour** [comment]
logger doesn't require restart when the drain url changes.  logspout does require restart if the logger's IP changes-- which can happen if it is ever rescheduled to a different host for some reason.  This will be addressed if we ever get around to upgrading logspout (waiting for their upcoming stable release has been a blocker).  Also, we've periodically seen logspout seize up (deadlock), and to our knowledge, we've addressed those issues, but I'd not be surprised if this were still somehow possible.  If this happens to you again, checking logspout's logs (on each host) and logger's logs may be enlightening as to what's going on.  Using `deis logs` to look for recent app logs should also give you some indication of whether logs are reaching the logger.  If not, that is more indicative of a logspout problem.
