### ISSUE TITLE
Strange issue on deployment and/or scaling

### ISSUE THREAD

**Issue by Crispy1975** [deis/deis#4773]
Sometimes we deploy one of our APIs and find that two of three containers are operating normally, yet one is throwing HTTP 500s. We can scale that app down to 1, then back up to three and have have the same issues but on different nodes. Our general process for deploying is to scale the apps down to one, do a `git push`, then scale back up to the desired number. This seems to have the best results, but we still end up with the situation described above now and then.

Scaling down also isn't ideal as we're running Node.js and this means a single process under heavy load.

There are no meaningful log entries from the failing container either, any ideas where to look to try and resolve this?

We are running stateless on AWS with version `v1.10.1`.

**Comment by carmstrong** [comment]
Is the container itself throwing the 500, or the router? I would compare logs from the container itself with those of the router component on that host.

**Comment by bacongobbler** [comment]
ping @Crispy1975

**Comment by Crispy1975** [comment]
From memory it was the router, the api worked well. But we do not risk doing a `git push` unless we have scaled back to 1 container. Next time it happens I will collect as much details as possible and report back here.

**Comment by bacongobbler** [comment]
sounds good. For now I'm going to close this bug as inactive, but please feel free to re-open once you get more info/logs. Thanks! :)
