### ISSUE TITLE
[meta] define a set of fixes necessary for a Deis v1 LTS release

### ISSUE THREAD

**Issue by mboersma** [deis/deis#4776]
The next minor release of Deis is intended to be a "long-term support" release that provides a stable, supported platform that will continue to receive fixes for many months. 

Please help us ensure that Deis LTS will meet your needs by pointing out which changes are necessary for your use. Add a comment here referencing an existing GitHub issue or describing the problem, and we will roll them up into an "LTS" milestone and update the roadmap document so we can all track progress.

**Comment by iancoffey** [comment]
I would :heart: if https://github.com/deis/deis/pull/4554 could get manual testing and be included. I know its a bear but it feels like its either time to manually test it finally or just close it.

**Comment by rvadim** [comment]
Hello guys. Thank you for your work. Deis is actually great. We use it in production in 1 DC and planning up +2 production clusters in 2 other DC's in February 2016.
At this moment we have one P1(not P0) issue with locking app configuration in controller #4746 and we will be very happy if this issue will be fixed in LTS release. Also i can help with fixing, adding PR, writing tests etc.

**Comment by rvadim** [comment]
#4796

**Comment by carmstrong** [comment]
Thank you @rvadim!!

**Comment by jannispl** [comment]
#3969

**Comment by rcreasey** [comment]
#4494 would need to be fixed as well.

Running a coreos/deis install entirely behind a corporate proxy makes this a showstopper.

**Comment by lslaslo** [comment]
#4787 might be beneficial.

**Comment by hakobera** [comment]
Thanks for deis guys, deis is really nice product.
#4746 is neccesary for production usage. Our deis cluster is often lock by multiple config update at same time.

**Comment by dpanelli** [comment]
A way to get around this https://github.com/docker/docker/issues/14788

**Comment by dmcnaught** [comment]
https://github.com/deis/deis/pull/4763 : "tags:set isn't restricting my app to certain hosts"

**Comment by bacongobbler** [comment]
@dmcnaught yes, that's been merged in master so it will go into the LTS release.

**Comment by aespinosa** [comment]
#4732 or getting docker to cleanup its iptables in some way or another.

**Comment by nathansamson** [comment]
can someone please look at #3479?
