### ISSUE TITLE
AWS termination policy semi-broke cluster after instance going down

### ISSUE THREAD

**Issue by szymonpk** [deis/deis#4781]
At one of our deis clusters one of instances went down (it failed health checks). Autoscaling group took 'arbitrary' decision to terminate it and boot up new one. In result we've two initial deis instances (part of etcd cluster) and one new (just an etcd proxy), our etcd cluster isn't healthy, we could fix it by updating user data and tinkering with etcd api to replace node and reconfigure new node as part of cluster.

Best case scenario would be to have time to reboot instance (it probably failed to some issues with underlying hardware and reboot would help) and if it doesn't work then we can try to replace instance.

So the issue is, default AWS default Deis deployment scripts configuration is a little bit 'broken' or at least not suitable for production usage.

Are there any known best practices to avoid such situations?

**Comment by iancoffey** [comment]
This is indeed a known issue, one that our [documentation](http://docs.deis.io/en/latest/managing_deis/add_remove_host/#adding-a-node) doesn't seem to do a very good job of acknowledging or addressing yet - and I think that documentation is the thing we should likely address first. Apologies for that. There is no simple "fix" unfortunately, but the ideal way to manage the cluster would involve never using the disco url after the initial provisioning. One way forward for those who can afford to have a few extra nodes is to isolate the [etcd cluster](http://docs.deis.io/en/latest/managing_deis/isolating-etcd/), and leave the rest of the nodes as proxy nodes. The proxy nodes could then more safely be in an autoscale group. Still, even with an isolated etcd cluster, one would have to add and remove etcd member nodes in a manual fashion - creating the new nodes(s), using the member join api, then starting with the correct peers, or using static or dns based discovery. On AWS, or any other provider, nodes are cycled over time - and so any solution that assumes that nodes are permanent is flawed in this way.

In the meanwhile @szymonpk, I can gladly describe how to manually perform the process of managing the etcd cluster if it is helpful.

@krancour, I know you have spent time thinking on this, do you have thoughts on this?

**Comment by szymonpk** [comment]
@iancoffey I would appreciate any instructions how we can avoid this in future, so don't hesitate to describe 'your way'.

**Comment by stuszynski** [comment]
@iancoffey Humble bump. Could you share with us those instructions that you mentioned, please? :) 

I'm about to perform some tests with AutoScaling group on AWS to some fresh Deis testing-cluster. Maybe there is some way to adjust AS group (e.g. by changing termination policy) to avoid this issue for now.  Anyway it would be good to have some workaround if something goes wrong instead of reinstalling whole platform.

**Comment by iancoffey** [comment]
@stuszynski @szymonpk Sure, theres not anything formal as far as docs yet  but I can describe the steps. Writing this up is on my to-do list.

The first step would be to ensure autoscaling is not enabled for the cluster that etcd is running on. Following that, adding or removing a node manually should be done via either the [etcdctl members commands](https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md#add-a-new-member) or the [members API](https://github.com/coreos/etcd/blob/master/Documentation/other_apis.md).

Once the existing cluster has knowledge of the new node, you could join the node statically by setting the ETCD_INITIAL_CLUSTER and ETCD_INITIAL_CLUSTER_STATE in the new nodes etcd2 unit config. Once the etcd2 units started, it should then join the cluster and fleet will do its things.

Feel free to jump into #deis to chat more about this.

**Comment by stuszynski** [comment]
FYI. I do some crash-tests and check some scenarios. In short i was trying to prevent AS from replacing a certain instances (e.g. 3 first instances) on failure. Unfortunately either Termination Protection nor Scale-In protection did not work for instances flagged with Unhealthy Status. 

Anyway, I find out that most suitable for us for now is to put a [ReplaceUnhealthy in Suspended Processes](http://docs.aws.amazon.com/AutoScaling/latest/DeveloperGuide/US_SuspendResume.html) in a Auto Scaling group. Works just like it sounds. Any instance from the group will not be replaced even if unhealthy status is detected. This gives us a chance to rescue (reboot) an instance with etcd node. Scale-out and Scale-In processes works as well and the replace process can be manually pushed just by terminating selected instance.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant so I'm closing this.
