### ISSUE TITLE
deisctl list not working on Mac with Vagrant

### ISSUE THREAD

**Issue by tjherring** [deis/deis#4782]
Mac OS Yosemite  w Vagrant 1.74 Virtual Box 5.0.10

Cloned  deis source and checked out v1.12.2
Install vagrant-triggers
make discovery-util
vagrant up (this created 3 VM's in Virtual Box)
ssh-add insecure_private_key (ssh-add -L verified this)
I can 'vagrant ssh deis-01' with success
Installed deisctl v1.12.2
export DEISCTL_TUNNEL=172.7.8.100
Verified that this ip address does resolve as local3.deisapp.com
"deisctl list"  does not work.  It always outputs "Error: timeout reached"

I have tried everything... uninstalled VirtualBox, vagrant.  Cleaned up .ssh and .vagrant.d.

I can't seem to determine what is going wrong because everything seems to be working correctly.

What can I do to debug the connection that deisctl is trying to make?

Thanks
TJ

here is the output of vagrant up:
Bringing machine 'deis-01' up with 'virtualbox' provider...
Bringing machine 'deis-02' up with 'virtualbox' provider...
Bringing machine 'deis-03' up with 'virtualbox' provider...
==> deis-01: Running triggers before up...
==> deis-01: Importing base box 'coreos-stable'...
==> deis-01: Matching MAC address for NAT networking...
==> deis-01: Checking if box 'coreos-stable' is up to date...
==> deis-01: Setting the name of the VM: deis_deis-01_1449529002947_6748
==> deis-01: Clearing any previously set network interfaces...
==> deis-01: Preparing network interfaces based on configuration...
    deis-01: Adapter 1: nat
    deis-01: Adapter 2: hostonly
==> deis-01: Forwarding ports...
    deis-01: 22 => 2222 (adapter 1)
==> deis-01: Running 'pre-boot' VM customizations...
==> deis-01: Booting VM...
==> deis-01: Waiting for machine to boot. This may take a few minutes...
    deis-01: SSH address: 127.0.0.1:2222
    deis-01: SSH username: core
    deis-01: SSH auth method: private key
    deis-01: Warning: Connection timeout. Retrying...
==> deis-01: Machine booted and ready!
==> deis-01: Setting hostname...
==> deis-01: Configuring and enabling network interfaces...
==> deis-01: Running provisioner: file...
==> deis-01: Running provisioner: shell...
    deis-01: Running: /var/folders/z7/6fkr0f8d3nn636p0z3lg1v8c0000gn/T/vagrant-shell20151207-4449-1vhdr0p.sh
==> deis-01: Running provisioner: shell...
    deis-01: Running: inline script
==> deis-02: Running triggers before up...
==> deis-02: Importing base box 'coreos-stable'...
==> deis-02: Matching MAC address for NAT networking...
==> deis-02: Checking if box 'coreos-stable' is up to date...
==> deis-02: Setting the name of the VM: deis_deis-02_1449529023292_96782
==> deis-02: Fixed port collision for 22 => 2222. Now on port 2200.
==> deis-02: Clearing any previously set network interfaces...
==> deis-02: Preparing network interfaces based on configuration...
    deis-02: Adapter 1: nat
    deis-02: Adapter 2: hostonly
==> deis-02: Forwarding ports...
    deis-02: 22 => 2200 (adapter 1)
==> deis-02: Running 'pre-boot' VM customizations...
==> deis-02: Booting VM...
==> deis-02: Waiting for machine to boot. This may take a few minutes...
    deis-02: SSH address: 127.0.0.1:2200
    deis-02: SSH username: core
    deis-02: SSH auth method: private key
    deis-02: Warning: Connection timeout. Retrying...
==> deis-02: Machine booted and ready!
==> deis-02: Setting hostname...
==> deis-02: Configuring and enabling network interfaces...
==> deis-02: Running provisioner: file...
==> deis-02: Running provisioner: shell...
    deis-02: Running: /var/folders/z7/6fkr0f8d3nn636p0z3lg1v8c0000gn/T/vagrant-shell20151207-4449-4y6s5.sh
==> deis-02: Running provisioner: shell...
    deis-02: Running: inline script
==> deis-03: Running triggers before up...
==> deis-03: Importing base box 'coreos-stable'...
==> deis-03: Matching MAC address for NAT networking...
==> deis-03: Checking if box 'coreos-stable' is up to date...
==> deis-03: Setting the name of the VM: deis_deis-03_1449529043800_83710
==> deis-03: Fixed port collision for 22 => 2222. Now on port 2201.
==> deis-03: Clearing any previously set network interfaces...
==> deis-03: Preparing network interfaces based on configuration...
    deis-03: Adapter 1: nat
    deis-03: Adapter 2: hostonly
==> deis-03: Forwarding ports...
    deis-03: 22 => 2201 (adapter 1)
==> deis-03: Running 'pre-boot' VM customizations...
==> deis-03: Booting VM...
==> deis-03: Waiting for machine to boot. This may take a few minutes...
    deis-03: SSH address: 127.0.0.1:2201
    deis-03: SSH username: core
    deis-03: SSH auth method: private key
    deis-03: Warning: Connection timeout. Retrying...
==> deis-03: Machine booted and ready!
==> deis-03: Setting hostname...
==> deis-03: Configuring and enabling network interfaces...
==> deis-03: Running provisioner: file...
==> deis-03: Running provisioner: shell...
    deis-03: Running: /var/folders/z7/6fkr0f8d3nn636p0z3lg1v8c0000gn/T/vagrant-shell20151207-4449-9yy6i7.sh
==> deis-03: Running provisioner: shell...
    deis-03: Running: inline script

**Comment by bacongobbler** [comment]
if you're directly on the box, don't set DEISCTL_TUNNEL. That is used only for remote connections via SSH, so what's happening is that it's trying to attain an SSH tunnel to 172.17.8.100:22. What you want is to unset DEISCTL_TUNNEL. Does that work for you?

**Comment by bacongobbler** [comment]
either that or install deisctl on your local machine and use `ssh-add ~/.vagrant.d/insecure_private_key && DEISCTL_TUNNEL=172.17.8.100 deisctl list`

**Comment by tjherring** [comment]
I am on the mac with deisctl installed.  So your second reply is what I am doing.  "ssh-add ~/.vagrant.d/insecure_private_key && DEISCTL_TUNNEL=172.17.8.100 deisctl list" it always results in Error: timeout reached.   Each VM has an ethernet adapter listening on the 172.17.8 network.  I can ping those IP's from my Mac host.   I can also ssh like this:

ssh core@172.17.8.100
Last login: Mon Dec  7 23:30:25 2015 from 172.17.8.1
 * *    *   *****    ddddd   eeeeeee iiiiiii   ssss
*   *  * *  *   *     d   d   e    e    i     s    s
 * *  ***** *****     d    d  e         i    s
*****  * *    *       d     d e         i     s
*   * *   *  * *      d     d eee       i      sss
*****  * *  *****     d     d e         i         s
  *   *****  * *      d    d  e         i          s
 * *  *   * *   *     d   d   e    e    i    s    s
***** *****  * *     ddddd   eeeeeee iiiiiii  ssss

Welcome to Deis			Powered by CoreOS
core@deis-01 ~ $

**Comment by bacongobbler** [comment]
I guess you could also check if fleet/etcd is up and running. If the connection is ok then I don't see why it would time out otherwise.

**Comment by tjherring** [comment]
Logged in to deis-01 using vagrant ssh.  Here is the output... I noticed that etcd is referring to the 10. network... should it be 172 instead?

core@deis-01 ~ $ ps -ef|grep etcd
etcd      1096     1  0 Dec07 ?        00:00:00 /usr/bin/etcd2
root     22319     1  0 15:41 ?        00:00:00 /usr/bin/etcdctl mk /coreos.com/network/config {"Network": "10.244.0.0/16", "SubnetLen": 24, "SubnetMin": "10.244.0.0", "Backend": {"Type": "vxlan"}}
core     22332 22328  0 15:42 pts/0    00:00:00 grep --colour=auto etcd
core@deis-01 ~ $ ps -ef|grep fleet
root      1101     1  0 Dec07 ?        00:00:03 /usr/bin/fleetd
core     22344 22328  0 15:42 pts/0    00:00:00 grep --colour=auto fleet

**Comment by bacongobbler** [comment]
that would be [flannel](https://github.com/coreos/flannel) which uses a separate internal bridged network, so that's not the issue. :(

**Comment by tjherring** [comment]
This is quite bizarre.  I am able to make this work on another Mac following the same procedures.  Is there something that can be done within deisctl to display diagnostics or verbose information?   I looked through the source of deisctl, but not being familiar with it, I didn't really find anywhere to add a break point.

**Comment by bacongobbler** [comment]
deisctl's connection relies on [fleetctl's remote tunneling library](https://github.com/coreos/fleet/blob/master/Documentation/using-the-client.md#from-an-external-host), but there is no verbose flag for the connection unfortunately. The code you are looking for is [here](https://github.com/coreos/fleet/blob/master/ssh/ssh.go)

**Comment by tjherring** [comment]
So far... tcpdump is showing the same connection sequence (deisctl is connecting to the same IP and port that plain ole ssh is).    I'm not so good with getting all of the details out of tcpdump, so I am trying to investigate.  Any pointers on good options to try will be helpful.

**Comment by krancour** [comment]
@tjherring did you ever get this resolved?  If you're still having trouble, here's my suggestion for how to troubleshoot further:

```
ssh -vvv core@172.17.8.100
```

That should help you establish why the ssh connection to the VMs is failing.

**Comment by rheicide** [comment]
I'm getting the same problem on Linux Mint 17.3 64-bit with Vagrant 1.8.1, VirtualBox 5.0.12, both Deis and `deisctl` at 1.12.2.

**Comment by krancour** [comment]
@rheicide, have you tried my troubleshooting suggestion above?

**Comment by tjherring** [comment]
Sorry for the delay on my side... over the holiday's I got pulled in to something.  I will troubleshoot my issue in the coming days.

**Comment by tjherring** [comment]
Well ssh works... but diesctl list still does not. I couldn't find anything in the output of the ssh command that seems to identify any issue. Here is the output in case you might be able to identify something:
sc-therring-osx:deis therring$ ssh -vvv core@172.17.8.100
OpenSSH_7.1p1, OpenSSL 1.0.2e 3 Dec 2015
debug1: Reading configuration data /usr/local/etc/ssh/ssh_config
debug2: ssh_connect: needpriv 0
debug1: Connecting to 172.17.8.100 [172.17.8.100] port 22.
debug1: Connection established.
debug1: identity file /Users/therring/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/therring/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/therring/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/therring/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/therring/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/therring/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/therring/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/therring/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.7
debug1: match: OpenSSH_6.7 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 172.17.8.100:22 as 'core'
debug3: hostkeys_foreach: reading file "/Users/therring/.ssh/known_hosts"
debug3: record_hostkey: found key type ED25519 in file /Users/therring/.ssh/known_hosts:11
debug3: load_hostkeys: loaded 1 keys from 172.17.8.100
debug3: order_hostkeyalgs: prefer hostkeyalgs: ssh-ed25519-cert-v01@openssh.com,ssh-ed25519
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1
debug2: kex_parse_kexinit: ssh-ed25519-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa
debug2: kex_parse_kexinit: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit: none,zlib@openssh.com,zlib
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit: first_kex_follows 0
debug2: kex_parse_kexinit: reserved 0
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
debug2: kex_parse_kexinit: ssh-rsa,ssh-dss,ssh-ed25519
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
debug2: kex_parse_kexinit: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: kex_parse_kexinit: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit:
debug2: kex_parse_kexinit: first_kex_follows 0
debug2: kex_parse_kexinit: reserved 0
debug1: kex: server->client chacha20-poly1305@openssh.com none
debug1: kex: client->server chacha20-poly1305@openssh.com none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-ed25519 SHA256:7p7UXuoFduXaiK8qb8R6XPLQRp/j+v1nsns2YrtQR3E
debug3: hostkeys_foreach: reading file "/Users/therring/.ssh/known_hosts"
debug3: record_hostkey: found key type ED25519 in file /Users/therring/.ssh/known_hosts:11
debug3: load_hostkeys: loaded 1 keys from 172.17.8.100
debug1: Host '172.17.8.100' is known and matches the ED25519 host key.
debug1: Found key in /Users/therring/.ssh/known_hosts:11
debug2: set_newkeys: mode 1
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /Users/therring/.vagrant.d/insecure_private_key (0x7fa45a700a90),
debug2: key: /Users/therring/.ssh/id_rsa (0x7fa45a4154c0),
debug2: key: /Users/therring/.ssh/id_dsa (0x0),
debug2: key: /Users/therring/.ssh/id_ecdsa (0x0),
debug2: key: /Users/therring/.ssh/id_ed25519 (0x0),
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug3: start over, passed a different list publickey,password,keyboard-interactive
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/therring/.vagrant.d/insecure_private_key
debug3: send_pubkey_test
debug2: we sent a publickey packet, wait for reply
debug1: Server accepts key: pkalg ssh-rsa blen 277
debug2: input_userauth_pk_ok: fp SHA256:1M4RzhMyWuFS/86uPY/ce2prh/dVTHW7iD2RhpquOZA
debug3: sign_and_send_pubkey: RSA SHA256:1M4RzhMyWuFS/86uPY/ce2prh/dVTHW7iD2RhpquOZA
debug1: Authentication succeeded (publickey).
Authenticated to 172.17.8.100 ([172.17.8.100]:22).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug2: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: ssh_packet_set_tos: set IP_TOS 0x10
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug2: channel 0: request shell confirm 1
debug2: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug2: channel 0: rcvd adjust 2097152
debug2: channel_input_status_confirm: type 99 id 0
debug2: shell request accepted on channel 0
Last login: Wed Jan 6 16:46:54 2016 from 172.17.8.1

* * ***** ddddd eeeeeee iiiiiii ssss
* * * * * d d e e i s s
* ***** ***** d d e i s ***** * * * d d e i s
* * * * * d d eee i sss ***** * * ***** d d e i s
***** * * d d e i s
* * * * * d d e e i s s ***** ***** * * ddddd eeeeeee iiiiiii ssss
Welcome to Deis Powered by CoreOS

**Comment by krancour** [comment]
@tjherring ok... looks like this is not an ssh issue then.  Do _other_ `deisctl` commands work?  What does `fleetctl list-machines` say?  You can try that command from a node _or_ from your Mac with `FLEETCTL_TUNNEL` set to `172.7.8.100`.

**Comment by rheicide** [comment]
@krancour I can ssh into 172.17.8.100 just fine with `ssh -vvv core@172.17.8.100`. Other `deisctl` commands seem to be not working as well:
```
$ deisctl machines
INFO client.go:292: Failed getting response from http://127.0.0.1:4001/: cancelled
Error: timeout reached
```
`deisctl status` doesn't output anything.

The `fleetctl` command doesn't exist on my host, so I ssh'd into 127.17.8.101:
```
core@deis-02 ~ $ which fleetctl
/usr/bin/fleetctl
core@deis-02 ~ $ export FLEETCTL_TUNNEL=172.17.8.100
core@deis-02 ~ $ fleetctl list-machines
Unable to initialize client: failed initializing SSH client: SSH_AUTH_SOCK environment variable is not set. Verify ssh-agent is running. See https://github.com/coreos/fleet/blob/master/Documentation/using-the-client.md for help.
core@deis-02 ~ $ eval `ssh-agent -s`
Agent pid 7423
core@deis-02 ~ $ fleetctl list-machines
The authenticity of host '172.17.8.100' can't be established.
RSA key fingerprint is 02:c0:e1:87:dd:9e:6c:f5:c8:56:b2:0e:ba:4b:a3:6b.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '172.17.8.100' (RSA) to the list of known hosts.
Unable to initialize client: failed initializing SSH client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

**Comment by krancour** [comment]
@rheicide, try that again, but don't bother setting `FLEETCTL_TUNNEL`.  That is only used when connecting to a _remote_ fleet node.  Since you have already ssh'ed to a fleet node (deis-02), you should not set this variable.

**Comment by rheicide** [comment]
@krancour Here's the output without `FLEETCTL_TUNNEL` being set:
```bash
core@deis-01 ~ $ eval `ssh-agent -s`
Agent pid 6338
core@deis-01 ~ $ fleetctl list-machines
Error retrieving list of active machines: googleapi: Error 503: fleet server unable to communicate with etcd
core@deis-01 ~ $ ps aux | grep etcd
etcd      2094  0.0  0.6 217968 14040 ?        Ssl  01:00   0:00 /usr/bin/etcd2
root      6348  0.0  0.5 122764 12156 ?        Ssl  04:16   0:00 /usr/bin/etcdctl mk /coreos.com/network/config {"Network": "10.244.0.0/16", "SubnetLen": 24, "SubnetMin": "10.244.0.0", "Backend": {"Type": "vxlan"}}
core      6373  0.0  0.0   4400   800 pts/0    S+   04:18   0:00 grep --colour=auto etcd
```

**Comment by krancour** [comment]
@rheicide, it looks like maybe the etcd cluster is not working.  From that node, try `etcdctl cluster-health`.

**Comment by rheicide** [comment]
@krancour Here's the output:
```bash
core@deis-01 ~ $ etcdctl cluster-health
client: etcd cluster is unavailable or misconfigured
```

**Comment by tjherring** [comment]
I also have the same results as @rheicide for fleetctl list-machines and etcdctl cluster-health.

**Comment by krancour** [comment]
@rheicide and @tjherring that actually puts some closure on this.  If your etcd cluster isn't available and healthy, neither fleet nor deisctl is expected to work properly.  The question now is one of why your etcd cluster isn't healthy.  If you need assistance troubleshooting that, it should be opened as a separate issue, but real quick-- the most likely cause is that you accidentally reused a discovery URL... only a guess.

I'm going to go ahead and close this because it adequately explains the issue you are having with `deisctl list`,

**Comment by tjherring** [comment]
I wonder if this could be due to the fact that I am behind a corporate proxy??? Does etcd need to access the internet?

**Comment by bacongobbler** [comment]
Initially, yes. Etcd uses a [discovery URL](https://coreos.com/os/docs/latest/cluster-discovery.html) to learn about each node for the first time. That can be sidestepped if you know the IP addresses ahead of time and have some knowledge of etcd, however. See https://coreos.com/os/docs/latest/cluster-architectures.html for more information.
