### ISSUE TITLE
git push hangs on Azure when deploying an app if it takes > ~10 min

### ISSUE THREAD

**Issue by colrack** [deis/deis#4784]
Hi all

I'm testing deis on Microsoft Azure.
The first time I create and deploy an app it usually takes > 10 min.
For example, when I create and deploy deis/example-php it takes ~15 min (in this case controller, builder and publisher are Standard_D1 VMs).
Deployment is successful, however git push always hangs, in my case at "-----> Pushing image to private registry".
In Azure you can set loadbalancer idle timeout and even public ip idle timeout as high as 30 min (see https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-load-balancer-manage-idle-timeout/ ); however this is not solving the problem.
So I've done some tests.
From outside the cluster, git push hangs pushing both at port 2222 and 2223 (first case reaching nginx, second reaching the builder directly).
From inside the cluster, after creating an app, I changed the remote branch url and set it to the local address of the builder (at port 2223) or nginx (at port 2222) and then git push just works without hanging. 
From inside the cluster pushing at the public ip hangs in both cases. 

When sniffing with Wireshark the connection seems to be alive; it is not closed, however no traffic is generated until I CTRL-C git push and the connection is obviously closed.

Can you please help me found out what the problem is?
Isn't it worth to implement some sort of application level keep alive, and possibly have more precise progress status?
Possibly related: #3755.
Can you also post some benchmark or estimated time it takes to push deis sample apps in various aws instances so I can compare?

Thanks

**Comment by bacongobbler** [comment]
If it's hanging when pushing to the registry, I'd take a look at the registry's logs and see why it fails to push the application there. It's also likely that the application has been attempted to deploy but failed to do so, which in that case you can check the fleet unit logs (or`deis logs` if it's flapping) to see why it's not deploying.

for application health checks, see http://docs.deis.io/en/latest/using_deis/config-application/#custom-health-checks.

**Comment by colrack** [comment]
I don't think it's a registry issue. During the building process, the builder is pushing the image to registry correctly; then also the controller pulls the image, tag a new release and push to registry again. Then the node scheduled by fleet is pulling the image and starting it. This all is working, the app is correctly scheduled and started, while git push is hanged as reported.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant so I'm closing this.
