### ISSUE TITLE
Staging - production question

### ISSUE THREAD

**Issue by gergelyke** [deis/deis#4785]
Hi,

just a quick question: I am playing with a staging/production setup for apps running on deis. Is there an easy way to push a staging image to production, like the pipeline feature in Heroku?

Thanks a lot,

cc @ozonid

**Comment by colrack** [comment]
No at this time as far as I know.
What you can do is:
1. have 2 clusters, 1 dev and 1 prod. 2 apps; See *Multiple Profile Support* at http://docs.deis.io/en/latest/using_deis/install-client/
2. 1 cluster, tag machines with metadata, 2 apps. See *Application runtime segregation* at http://docs.deis.io/en/latest/managing_deis/security_considerations/?highlight=staging ,
 *Isolate the Application* at http://docs.deis.io/en/latest/using_deis/manage-application/ , and remember to enable enablePlacementOptions see *Decorating units* at http://docs.deis.io/en/latest/managing_deis/isolating-planes/?highlight=isolating

**Comment by gergelyke** [comment]
I am more interested in running on the same cluster a staging and production version of the same application, so my use-case would be piping the staging image to the production app without a `git push`.

**Comment by aledbf** [comment]
@gergelyke you can use `deis pull` from the prod cluster using the registry from the dev cluster.

**Comment by colrack** [comment]
This is not possible at this time afaik.
A workaround could be using docker images. If you prepare a docker image, push it to a private repo you can then use deis pull (as @aledbf said) and you will not have the building time overhead.

**Comment by gergelyke** [comment]
@aledbf in that case I would need two clusters, right?

is that possible to do the same with one cluster?

Take the following example:

* existing `my-app-staging` application, with remote `deis`
* existing `my-app-production` application
* `git push deis master`

Can I use the `deis pull` in this case? If so, how?

**Comment by colrack** [comment]
Yes you can use one cluster.

- existing my-app-staging app: use git push to deploy
- existing my-app-production app: use deis pull local-deis-registry:5000/my-app-staging:v2 to deploy

**Comment by aledbf** [comment]
@gergelyke yes you can. 
You need to know where the registry is running `REG_HOST=$(etcdctl get /deis/registry/host)`
Then you just run `deis pull $REG_HOST:5000/my-app-staging:vXX -a my-app-production`

**Comment by gergelyke** [comment]
@colrack @aledbf I tried it, and it seems working, however the pulled container doesn't start.

I deployed a Node.js app to staging, then (after the internal registry address lookup), I tried the following:

```
deis pull 10.21.2.207:5000/test-staging:v6 -a test-production
# with the output:
Creating build... done
```

However, I get the following error if I run `deis logs -a test-production`:

```
2015-12-13T14:16:21UTC test-production[deis-controller]: warning, some containers failed to start
```

If I run `deisctl journal deis-controller.service`, I get the following:

```
Dec 13 14:15:34 ip-10-21-2-208.eu-west-1.compute.internal sh[2974]: INFO test-production: build test-production-c227e45 created
Dec 13 14:15:34 ip-10-21-2-208.eu-west-1.compute.internal sh[2974]: INFO test-production: release test-production-v16 created
Dec 13 14:15:34 ip-10-21-2-208.eu-west-1.compute.internal sh[2974]: INFO [test-production]: gergelyke deployed 10.21.2.207:5000/test-staging:v6
Dec 13 14:15:34 ip-10-21-2-208.eu-west-1.compute.internal sh[2974]: INFO Pulling Docker image 10.21.2.207:5000/test-staging:v6
Dec 13 14:15:41 ip-10-21-2-208.eu-west-1.compute.internal sh[2974]: INFO Tagging Docker image 10.21.2.207:5000/test-staging:v6 as 10.21.2.207:5000/test-staging:v6
Dec 13 14:15:41 ip-10-21-2-208.eu-west-1.compute.internal sh[2974]: INFO Building Docker image 10.21.2.207:5000/test-production:v16
Dec 13 14:15:47 ip-10-21-2-208.eu-west-1.compute.internal sh[2974]: INFO Pushing Docker image 10.21.2.207:5000/test-production:v16
Dec 13 14:16:21 ip-10-21-2-208.eu-west-1.compute.internal sh[2974]: WARNING test-production: warning, some containers failed to start
Dec 13 14:16:21 ip-10-21-2-208.eu-west-1.compute.internal sh[2974]: WARNING [test-production]: warning, some containers failed to start
```

Any idea what's wrong?

**Comment by gergelyke** [comment]
Once I do `deisctl status test-production`, I get this:

```
● test-production_v16.cmd.1.service - test-production_v16.cmd.1
   Loaded: loaded (/run/fleet/units/test-production_v16.cmd.1.service; linked-runtime; vendor preset: disabled)
   Active: activating (start-pre) since Sun 2015-12-13 14:39:41 UTC; 2s ago
  Process: 13789 ExecStop=/usr/bin/docker stop test-production_v16.cmd.1 (code=exited, status=1/FAILURE)
  Process: 13721 ExecStart=/bin/sh -c IMAGE=$(etcdctl get /deis/registry/host 2>&1):$(etcdctl get /deis/registry/port 2>&1)/test-production:v16; docker run --name test-production_v16.cmd.1 --rm    -P $IMAGE  (code=exited, status=0/SUCCESS)
  Process: 13714 ExecStartPre=/bin/sh -c docker inspect test-production_v16.cmd.1 >/dev/null 2>&1 && docker rm -f test-production_v16.cmd.1 || true (code=exited, status=0/SUCCESS)
 Main PID: 13721 (code=exited, status=0/SUCCESS);         : 13870 (sh)
   Memory: 2.0M
      CPU: 57ms
   CGroup: /system.slice/test-production_v16.cmd.1.service
           └─control
             ├─13870 /bin/sh -c IMAGE=$(etcdctl get /deis/registry/host 2>&1):$(etcdctl get /deis/registry/port 2>&1)/test-production:v16; docker pull $IMAGE
             └─13884 docker pull 10.21.2.207:5000/test-production:v16

Dec 13 14:39:41 ip-10-21-1-8.eu-west-1.compute.internal systemd[1]: Starting test-production_v16.cmd.1...

● test-production_v16.web.1.service - test-production_v16.web.1
   Loaded: loaded (/run/fleet/units/test-production_v16.web.1.service; linked-runtime; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2015-12-13 14:39:44 UTC; 2s ago
  Process: 24416 ExecStop=/usr/bin/docker stop test-production_v16.web.1 (code=exited, status=1/FAILURE)
  Process: 24347 ExecStart=/bin/sh -c IMAGE=$(etcdctl get /deis/registry/host 2>&1):$(etcdctl get /deis/registry/port 2>&1)/test-production:v16; docker run --name test-production_v16.web.1 --rm    -P $IMAGE bash -c 'node app.js' (code=exited, status=0/SUCCESS)
  Process: 24339 ExecStartPre=/bin/sh -c docker inspect test-production_v16.web.1 >/dev/null 2>&1 && docker rm -f test-production_v16.web.1 || true (code=exited, status=0/SUCCESS)
  Process: 24315 ExecStartPre=/bin/sh -c IMAGE=$(etcdctl get /deis/registry/host 2>&1):$(etcdctl get /deis/registry/port 2>&1)/test-production:v16; docker pull $IMAGE (code=exited, status=0/SUCCESS)
 Main PID: 24347 (code=exited, status=0/SUCCESS)
   Memory: 0B
      CPU: 0
   CGroup: /system.slice/test-production_v16.web.1.service

Dec 13 14:39:44 ip-10-21-2-208.eu-west-1.compute.internal systemd[1]: test-production_v16.web.1.service: Control process exited, code=exited status=1
Dec 13 14:39:44 ip-10-21-2-208.eu-west-1.compute.internal systemd[1]: test-production_v16.web.1.service: Unit entered failed state.
Dec 13 14:39:44 ip-10-21-2-208.eu-west-1.compute.internal systemd[1]: test-production_v16.web.1.service: Failed with result 'exit-code'.
```

**Comment by colrack** [comment]
Can you post your deis version? This may not work cause of #4760.
I'm pretty sure I tried this and it was working.
Pay attention when deploying from dockerfiles/images to scale using `deis scale cmd=X` not `deis scale web=X`. Try to scale down to zero with both `deis scale cmd=0` not `deis scale web=0` and then scale up again with `deis scale cmd=1`.
Your steps look good to me.
I'll try with deis/example-nodejs-express and post results.

**Comment by gergelyke** [comment]
I am running `1.12.1` - thanks!

any reason why I have to scale the `cmd`, and not `web`?

**Comment by gergelyke** [comment]
Which version are you running ?

**Comment by colrack** [comment]
Ok I can confirm that what you are trying to do is not working for me on a `1.12.2` cluster.

From what I see from logs the reason is the following: when I create the second app pulling the image from the first app repo, a fleet unit is created and as in logs by @gergelyke it is trying to start the app with `bash -c 'node app.js'`. This is not working cause the workdir (supposed to be /app) is not set and the container immediately stops. I manually replaced in the fleet unit file `bash -c 'node app.js'` with  `'cd /app/ && node server.js'` and it works.

The reason using `cmd` and not `web` is cause with dockerfiles and docker images deis is supposed to scale the CMD entry. See http://docs.deis.io/en/latest/using_deis/using-dockerfiles/ and http://docs.deis.io/en/latest/using_deis/using-docker-images/. However this seems not to be the case because the image is created with heroku nodejs buildpack so there is not CMD and if you try to `scale cmd=X` the created fleet unit is not running any cmd.

/cc @aledbf

**Comment by gergelyke** [comment]
thanks!
