### ISSUE TITLE
AWS CloudFormation Updates: SSHFrom - possible from more than one CIDR?

### ISSUE THREAD

**Issue by dmcnaught** [deis/deis#4788]
Can we specify more than one CIDR that is allowed to connect to members of the Deis cluster?

It seems to work ok to add new CIDR to the instance security in AWS, but would be nice to manage from the scripts (provision-aws-cluster.sh, update-aws-cluster.sh)

**Comment by bacongobbler** [comment]
@dmcnaught you should be able to plug that into the [cloudformation template](https://github.com/deis/deis/blob/master/contrib/aws/deis.template.json), no?

**Comment by dmcnaught** [comment]
It looks like that might work if we update the AllowedPattern too.
```
"SSHFrom" : {
      "Description" : "Lockdown SSH access to the Deis hosts (default: can be accessed from anywhere)",
      "Type" : "String",
      "MinLength": "9",
      "MaxLength": "18",
      "Default" : "174.16.231.181/32",
      "AllowedPattern" : "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})",
      "ConstraintDescription" : "must be a valid CIDR range of the form x.x.x.x/x."
    },
```
If that's the case I think the AllowedPattern should reflect what patterns are actually allowed.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776), and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this.
