### ISSUE TITLE
update_ec2_cluster.sh : error when updating ClusterSize in deis.template.json

### ISSUE THREAD

**Issue by dmcnaught** [deis/deis#4789]
This is the section in deis.template.json:
```
    "ClusterSize": {
      "Default": "3",
      "MinValue": "3",
      "MaxValue": "12",
      "Description": "Number of nodes in cluster (3-12).",
      "Type": "Number"
    },
```
When I update Default to 5, and MinValue to 5 
    __or__
Default to 5 and MinValue to 3:
```
./update-aws-cluster.sh
A client error (ValidationError) occurred when calling the UpdateStack operation: No updates are to be performed.
```

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776) and the architecture in deis v2 has dramatically changed such that this is no longer relevant so I'm closing this.
