### ISSUE TITLE
Deis Router to route on paths.

### ISSUE THREAD

**Issue by Crispy1975** [deis/deis#4793]
Would be great to be able to route requests through nginx based on the path supplied in addition to the domain. The reasoning is that different paths could be rewritten to a container specifically for that domain/path combination. An example would be...

`http://www.example.com/` - goes to the regular container as expected for the `www` app.
`http://www.example.com/blog` - goes to a different container based on the domain and path combination.

Would like to get thoughts on this as a feature as it would allow a lot more flexibility in the way the Deis platform as a whole can be used.

So, right now `git push` will deploy a container for that sub-domain, and I don't see that needing to change. The idea is that you could `git push` a `blog` app which would live in Deis under `http://blog.example.com/`, but with an additional config setting we could route that path through to this container making it's content display at `http://www.example.com/blog`.

**Comment by krancour** [comment]
This wouldn't make it into v1.x, as we're not adding new features unless we and the community jointly judge them to be must haves for an LTS.  You could open this issue against deis/router instead.

That said, I would, personally, still be opposed to this as it drastically increases complexity in a number of ways.  For instance, today, most config is managed at the app level.  Apps have domains.  What you're proposing inverts that relationship such that domains have apps.  Not only is that more difficult for someone familiar with the Heroku workflow to wrap their head around, but it would make configuration way more difficult for a Deis user.  You want to increase a timeout somewhere, for instance?  Is that on a domain?  Or on one of the potentially many containers serving that domain?  I'm siding with the simplicity of the current model.

All this being said, you _can_ do this yourself.  The app for such a domain could be your own nginx, for instance, statically configured to proxy requests for `www.example.com/blog` to `blog.example.com` while the rest are proxied to the container for the www app.  I know this adds an extra hop... so if you were feeling ambitious you could customize the deis-router instead to handle this special case with some static config.  Just some ideas.

**Comment by bacongobbler** [comment]
I agree with @krancour. I feel that this is something where a third party router could come into play here. A similar idea has been proposed before for the same reasons (though I can't seem to find it) so there is also precedence at play here. In any case, this isn't something we can handle for the reasons stated above (healthchecks, ssl certs, router timeouts etc. all have to be considered)

**Comment by krancour** [comment]
@Crispy1975: Another DIY possibility I should mention-- in Kubernetes (which is the container orchestration system underlying Deis v2), there is a concept of "ingress" and that is a routing system.  It's an beta feature, with available implementations being only alpha in quality, but it can do what you're asking for.  (The fact that this isn't stable yet is the reason we're not using this.)  YMMV because it doesn't let you configure much else.  But this illustrates a nice feature of v2.  If there's something k8s can do natively that isn't utilized by Deis, you can "drop down" to k8s to get it done.

**Comment by Crispy1975** [comment]
Thanks for the comments. Noted and understood the points why this won't be available in 1.x. Until 2.x is stable then I think we'll look at building a custom router to do what we need. Kubernetes sounds like a good idea but a little too far from being in a stable release with Deis.

**Comment by bacongobbler** [comment]
closing as a wontfix. This is something we cannot handle with our router, however this is a great opportunity for a third-party router to handle this use case.

**Comment by Crispy1975** [comment]
Thanks for the comments, maybe we'll look into building something. :+1:
