### ISSUE TITLE
Improve procfile handling on pull / builds:create

### ISSUE THREAD

**Issue by helgi** [deis/deis#4794]
```
./deis pull deis/example-go -a hmm -p example-go/Procfile
Error: yaml: unmarshal errors: line 1: cannot unmarshal !!str `example...` into map[string]string
core@micro-kube ~ $ cat example-go/Procfile
web: example-go
```

**Comment by helgi** [comment]
`./deis pull deis/example-go -a hmm -p "web: example-go"` works

**Comment by bacongobbler** [comment]
-p is intended to be a string, not a file path. it interpreted `example-go/Procfile` and failed to find a value since there was no delimiter. CLosing as intentional.
