### ISSUE TITLE
Request logs

### ISSUE THREAD

**Issue by gergelyke** [deis/deis#4799]
Hello,

is there any way to easily access nginx request logs?

Gergely

**Comment by krancour** [comment]
`deisctl journal router` should tail logs (including access logs) for all routers in turn.  (Interrupting with `ctrl-c` moves you to the next router.)

If you want to archive access requests, I would suggest having applications log them, as application logs (unlike system logs) are aggregated by the `deis-logger` where you can also choose to drain them off to someplace else like Splunk or Papertrail.

**Comment by krancour** [comment]
Actually... I take that back.  `deis-logger` does also aggregate logs from deis components-- including the routers.  There just isn't an easy command for accessing them via cli -> controller -> logger.  If you're already configured with a log drain to the likes of Splunk or Papertrail, you can already find the access logs in there.

**Comment by gergelyke** [comment]
Got, it thanks a lot for the quick response! :)
