### ISSUE TITLE
deis config:set SENTRY_DSN=""

### ISSUE THREAD

**Issue by dmcnaught** [deis/deis#4802]
I have a project where I'd like to set SENTRY_DSN="" as an environment variable.
The project starts fine with 
`docker run -e SENTRY_DSN=""`
When I try to set that with 
`deis config:set SENTRY_DSN=""`
or
`deis config:set SENTRY_DSN=`
I get the error 
`'SENTRY_DSN=' does not match the pattern 'key=var', ex: MODE=test`
If I add it to an env file as SENTRY_DSN="", and do a 
`deis config:push -p .env-test`
 then my node app throws the error:
`Error: Invalid Sentry DSN: ""`
If I add it to the env file as SENTRY_DSN=
then I get the error:
`'SENTRY_DSN=' does not match the pattern 'key=var', ex: MODE=test`
How can I get the deis app to start the same as 
`docker run -e SENTRY_DSN=""`

**Comment by bacongobbler** [comment]
hmm, seems like you at least need to set a value. Would `deis config:set SENTRY_DSN="1"` work instead?

**Comment by bacongobbler** [comment]
Though I agree that it's a workaround. We should be able to allow blank values as well.

**Comment by dmcnaught** [comment]
I'd tried a few values, and they don't seem to work:
Invalid Sentry DSN: 1
Invalid Sentry DSN: .
