### ISSUE TITLE
[resolved] "deisctl start platform" stuck at deis-store-monitor

### ISSUE THREAD

**Issue by monaka** [deis/deis#4806]
I've already resolved this issue. But I wrote this for sharing.
As it will be encountered almost all people who deploy Deis on Azure. 
The behavior of this issue is similar to #2330. But it seems something wrong.

I deployed 3 nodes into Azure using scripts provided by Azure.
And I executed `deisctl platform start`. But stuck at deis-store-monitor.

```
deis-store-monitor.service      03b7a3bd.../10.0.0.4    loaded  activating      auto-restart
deis-store-monitor.service      24d6cfbe.../10.0.0.6    loaded  activating      start-pre
deis-store-monitor.service      87cd5a7a.../10.0.0.5    loaded  activating      start-pre
```
And all other services are "dead".

Following is the result of journalctl in one node.
 
```
 $ journalctl -fu deis-store-monitor
-- Logs begin at Thu 2015-12-17 20:04:16 UTC. --
Dec 19 07:22:19 deisNode2 systemd[1]: Unit deis-store-monitor.service entered failed state.
Dec 19 07:22:19 deisNode2 systemd[1]: deis-store-monitor.service failed.
Dec 19 07:22:24 deisNode2 systemd[1]: deis-store-monitor.service holdoff time over, scheduling restart.
Dec 19 07:22:24 deisNode2 systemd[1]: Starting deis-store-monitor...
Dec 19 07:22:27 deisNode2 sh[49908]: Pulling repository alpine
Dec 19 07:22:29 deisNode2 sh[49908]: time="2015-12-19T07:22:29Z" level="fatal" msg="Could not reach any registry endpoint"
Dec 19 07:22:29 deisNode2 systemd[1]: deis-store-monitor.service: control process exited, code=exited status=1
Dec 19 07:22:29 deisNode2 systemd[1]: Failed to start deis-store-monitor.
```

```
cat /etc/lsb-release 
DISTRIB_ID=CoreOS
DISTRIB_RELEASE=647.2.0
DISTRIB_CODENAME="Red Dog"
DISTRIB_DESCRIPTION="CoreOS 647.2.0"
```

It's too old.

After update CoreOS and reboot. It works fine.

```
$ cat /etc/lsb-release 
DISTRIB_ID=CoreOS
DISTRIB_RELEASE=835.9.0
DISTRIB_CODENAME="Red Dog"
DISTRIB_DESCRIPTION="CoreOS 835.9.0"
$ journalctl -fu deis-store-monitor
-- Logs begin at Thu 2015-12-17 20:04:16 UTC. --
Dec 19 08:02:18 deisNode2 sh[1106]: 978b0fee5c40: Pulling fs layer
Dec 19 08:02:18 deisNode2 sh[1106]: 8e0aa5f79abe: Pulling fs layer
Dec 19 08:02:18 deisNode2 sh[1106]: 73d6763f0c57: Pulling fs layer
```

**Comment by carmstrong** [comment]
Are you using our scripts to provision on Azure? We [specify](https://github.com/deis/deis/blob/455e6b04e30c9ebcd56e25e9e2b6198e3c95efc5/contrib/azure/parameters.json#L30) the CoreOS version, so the hosts should come up with the proper version...

**Comment by monaka** [comment]
I must add some information to this issue.

I got the script from https://github.com/Azure/azure-quickstart-templates
So I this issue is not caused by your team. I didn't know your scripts available.

The reason I create this ticket is for new comers.
But possibly someone will get  the article written by Azure when he google with "Azure Deis".

I'll send my pull request to Azure later.
