### ISSUE TITLE
Log messages are malformed when deploying from Codeship

### ISSUE THREAD

**Issue by gergelyke** [deis/deis#4810]
Hello,

when deploying from Codeship, I get the following logformat:

```
remote: ote: icrotime@2.0.0 (bindings@1.2.1, nan@2.0.9)`
```

Any idea why?

**Comment by krancour** [comment]
Those logs are seen where exactly?

**Comment by gergelyke** [comment]
On codeship - in papertrail the look fine.

(this is the output of `git push deis master` as seen on Codeship)

**Comment by krancour** [comment]
I'm not too familiar with Codeship.  Maybe @ngauthier could comment on this?  He works for Codeship and I do know he has some familiarity with Deis as well.

**Comment by ngauthier** [comment]
Sounds like a Codeship bug. Could you email support at codeship dot com so it opens a ticket on our end?

**Comment by krancour** [comment]
Thanks @ngauthier.

**Comment by gergelyke** [comment]
Thanks @ngauthier , @krancour - just did that.

**Comment by kblcuk** [comment]
@gergelyke have you heard back from Codeship yet? Been seeing the same "ote ote ote" in node projects I'm working on nowadays, sometimes it's pretty annoying. (Also immediately brings up that song about umbrella in my head)

**Comment by gergelyke** [comment]
not really :/

**Comment by kblcuk** [comment]
Hmkay :/
