### ISSUE TITLE
Deis with Loggly

### ISSUE THREAD

**Issue by gergelyke** [deis/deis#4814]
To be able to work with Loggly, I need to set a syslog header (https://www.loggly.com/docs/streaming-syslog-without-using-files/)

Is there a way to set it in Deis?

**Comment by geeksoul-me** [comment]
I too need info on this.

**Comment by krancour** [comment]
> Is there a way to set it in Deis?

Not currently.  Feel free to take a stab at adding support for this to the logger.

**Comment by bacongobbler** [comment]
PRs this-a-way (for Workflow, the successor to Deis) --> https://github.com/deis/logger

**Comment by bacongobbler** [comment]
Loggly has support for fluentd as well, which you can contribute a PR to deis/fluentd.

https://www.loggly.com/docs/fluentd-logs/

**Comment by deis-admin** [comment]
This issue was moved to deis/logger#133
