### ISSUE TITLE
Deis with Vagrant on Windows 8.1 gives an error

### ISSUE THREAD

**Issue by hvram1** [deis/deis#4815]
I managed to get the change done on user-data . ( of replacing the #DISCOVERY_URL) 

But when I run `vagrant up ` I get the following error

     There was an error loading a Vagrantfile. The file being loaded and the error message are shown below. This is usually caused by a syntax error.

     Path: E:/projects/deis/deis/Vagrantfile
     Line number: /Vagrant/embedded/lib/ruby/2.0.0/open3.rb
     Message: Errno::ENOENT: No such file or directory - /usr/bin/env

Can u let me know what should this be ?

**Comment by hermanjunge** [comment]
That error means that a `*nix` machine (e.g. Ubuntu, OSX) is needed to run this `Vagrantfile`.

**Comment by bacongobbler** [comment]
as the error suggests, /usr/bin/env was not found, which is to be expected. We have not tested the Vagrantfile on Windows so there's likely going to be hiccups like this one.

**Comment by bacongobbler** [comment]
This is not something we'll be able to get to for the LTS release (#4776), and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this.
