### ISSUE TITLE
Show Revision Number In Logs

### ISSUE THREAD

**Issue by alexw23** [deis/deis#4819]
It would be great if logs showed the revision number in logs as it can sometimes be confusing (like below).

```
2015-12-30T20:17:54UTC my-service[web.1]: Starting php-fpm...
2015-12-30T20:17:56UTC my-service[web.1]: Starting nginx...
2015-12-30T20:17:56UTC my-service[web.1]: Application ready for connections on port 5000.
2015-12-30T20:17:57UTC my-service[web.1]: Going down, terminating child processes...
```

I was led to believe that the service kept crashing for some reason. What I should see is:

```
2015-12-30T20:17:54UTC my-service[web.1 - V2]: Starting php-fpm...
2015-12-30T20:17:56UTC my-service[web.1 - V2]: Starting nginx...
2015-12-30T20:17:56UTC my-service[web.1 - V2]: Application ready for connections on port 5000.
2015-12-30T20:17:57UTC my-service[web.1 - V1]: Going down, terminating child processes...
```

**Comment by sgoings** [comment]
I think this issue would be good to get into our LTS release... if it's important to you (and you'd rather see it in the LTS release, not just wait for Deis v2), chime in here: https://github.com/deis/deis/issues/4776

**Comment by bacongobbler** [comment]
this is a holdover from Heroku's logs as they do not display this information to the user. For sake of backwards compatibility I don't think we should fix this for the LTS release, and I believe the new logger does not display this information either.

@jchauncey, what do you think about adding this to the v2 logger?

**Comment by kenaniah** [comment]
On this topic, I think it would be nice if we could set a custom logging format via a `deisctl config` command. Having an etcd2 key that the logger reads from would provide ultimate flexibility.

**Comment by bacongobbler** [comment]
@kenaniah this is partially available today! You can customize the log format [here](https://github.com/deis/deis/blob/master/logspout/logspout.go#L86-L92), but there's no way to set it via etcd.

Going forward into v2 this kind of customization will eventually be deprecated (no etcd in deis v2) and you'll have to roll your own custom image for these changes. We've had endless requests to extend *everything* on the platform (mostly the router, but there are cases like this one) which hasn't been a sustainable solution which we could support properly, so if you want a custom logging format you'll want to extend or fork the image directly and make your changes there.

Hope this helps!

**Comment by bacongobbler** [comment]
closing as a backwards-incompatible fix for v1.
