### ISSUE TITLE
Insecure deployment with Digitalocean

### ISSUE THREAD

**Issue by kevinsimper** [deis/deis#4823]
The coreos deployment on digitalocean is not secure by default without provisioning TLS certificates, because the private networking is shared with everybody in the same region.

Isn't that a critical mistake not to mention?

**Comment by krancour** [comment]
> the private networking is shared with everybody in the same region

Is that accurate?  I am more familiar with AWS networking than with DO.  In AWS, security groups are used to lock this down.

Is it the case that literally any node in a given DO region can address any other node in the same region using its private IP?

If so, then yes, this should be documented.

**Comment by krancour** [comment]
Ping @carmstrong.  I think you've possibly done more with DO than myself.

**Comment by carmstrong** [comment]
I was unaware this is how private networking is implemented on DO, but it sounds like it is: https://www.digitalocean.com/company/blog/introducing-private-networking/#comment-1160317518

There is a [request](http://digitalocean.uservoice.com/forums/136585-digitalocean/suggestions/3574245-vlan) to add VLAN support to private networking, but it doesn't look like it's been implemented.

This is indeed an oversight, but not sure how it should be fixed... I wonder what CoreOS is doing upstream, as they seem to default to private networking as well: https://coreos.com/os/docs/latest/booting-on-digitalocean.html

**Comment by kevinsimper** [comment]
@krancour It says so right here, https://www.digitalocean.com/company/blog/introducing-private-networking/

Also here:
https://www.digitalocean.com/community/tutorials/how-to-isolate-servers-within-a-private-network-using-iptables

> The private interface is accessible only to other VPSs on the same private network. In the case of DigitalOcean, this means that only other VPSs in the same datacenter can access the private interface. Compared to the Internet, this makes it a relatively safe place for your VPSs to serve traffic but it would be even safer if it was only accessible to your own VPSs.

**Comment by carmstrong** [comment]
Note that we do provide a firewall for use on providers like DigitalOcean: http://docs.deis.io/en/latest/managing_deis/security_considerations/#running-deis-on-public-clouds

We could this out more explicitly in the DO docs, though. @kevinsimper give the Deis firewall a go, and if it works well for you on DO, we'd appreciate a PR to update the installation guide.

**Comment by kevinsimper** [comment]
@carmstrong A better solution would be to enforce SSL as the traffic is unencryptet and therefore can be sniffed.

**Comment by nathansamson** [comment]
@kevinsimper 
"A better solution would be to enforce SSL as the traffic is unencryptet and therefore can be sniffed."

I am not sure if that is really necessary. I suspect that droplets in DO only receive traffic intendend for them (as in, you can't put the private network device in promiscious mode), so data passing from droplet A to droplet B over the DO "private" network will never be visible from droplet C from another user.
I could be wrong about this though...

Obviously if droplet C does a request to droplet A / B it will receive a reply (unless the firewall is configured correctly).

I am not saying I am opposed to this change, and I would like DO private network to be really private, I think configured with the firewall the DO deployment is actually relatively safe.

**Comment by jchauncey** [comment]
It would be wrong to ever assume that network traffic flowing between nodes is private or secure without SSL. For most people data in flight has to be encrypted (even when passing among different interfaces on the same node).

**Comment by kevinsimper** [comment]
@carmstrong I also created a issue at CoreOS https://github.com/coreos/docs/issues/718

The problem I think is bigger with Deis, because developers that may use Deis, does not nessasary know that CoreOS that is beneath is insecure configured.

The docs should really add a warning sign and say that you can be hacked.

@nathansamson Does the firewall also cover CoreOS ports?

**Comment by bacongobbler** [comment]
@kevinsimper the firewall blocks all public ports except [ports 22 (SSH), 80 (http), 443 (https) and 2222 (`git push deis master`)](https://github.com/deis/deis/blob/master/contrib/util/custom-firewall.sh#L46-L47). After that, only [the nodes part of the fleet cluster](https://github.com/deis/deis/blob/master/contrib/util/custom-firewall.sh#L40-L41) have full access. The rest of the connections on the private network [are dropped](https://github.com/deis/deis/blob/master/contrib/util/custom-firewall.sh#L49-L51).
