### ISSUE TITLE
Deis Terraform provider

### ISSUE THREAD

**Issue by msull92** [deis/deis#4824]
I created this Terraform provider plugin for Deis out of need, would love for the Deis community to pick it up and help me out on maintaining it. If we can get enough stars and stability we can get it committed to the offical Terraform repository so that it's built-in.

https://github.com/botlink/terraform-provider-deis

**Comment by sgoings** [comment]
Hey @msull92 - thanks for creating this. The interface looks pretty clean and adheres to the "feel" of other Terraform providers. Do you foresee the repository moving into the deis org as a first step? I'll setup a time for us to chat about how we might accomplish your end goal of getting it into Terraform proper.

**Comment by msull92** [comment]
@sgoings That would be wonderful to both!

**Comment by bacongobbler** [comment]
I don't think this is something we'll be able to get to for the LTS release (#4776), and provisioning Deis v2 is done through installing a vanilla kubernetes cluster so I'm going to go ahead and close this. Thank you for the PR though!

**Comment by sgoings** [comment]
Actually @bacongobbler this is something that applies to v2 as well.

**Comment by bacongobbler** [comment]
orly? Awesome, let's keep it open then :)

**Comment by bacongobbler** [comment]
hey @msull92 :) just wanted to let you know that v2.0 is now officially GA and you can read more here: https://deis.com/blog/2016/workflow-stable/

Any chance you'd be interested in doing this for v2?

**Comment by krancour** [comment]
> Actually @bacongobbler this is something that applies to v2 as well.

That was probably true on Jan 21. Is that still true based on where we ended up?

**Comment by msull92** [comment]
@bacongobbler @krancour This is a provider for the Terraform, which means it uses the Deis api to programmatically create apps on Deis and then set config variables, certs, domains, etc. So it probably still works, unless the API to manage those things changed drastically... It was built against v1.7 of the API.

**Comment by bacongobbler** [comment]
@msull92 the API [has not changed significantly](https://deis.com/docs/workflow/reference-guide/controller-api/v2.0/). Should be a straightforward port :)

**Comment by krancour** [comment]
I think I misunderstood the nature of the issue... carry on.

**Comment by jennyfountain** [comment]
Would love to use this. :D

**Comment by gregorskii** [comment]
I would also like to see this. For my current project I am primarily working with Docker Images rather than builpacks. I would really like to see a Terraform project that can encapsulate creating applications and managing ENV variables for them.

My main goals for it would be to:

- Create applications
- Upload Docker credentials for the application via GCR long lived tokens
- Set images to be pulled from GCR and run
- Manage ENV variables for those applications
- Manage SSL for routers/applications
- Manage custom DNS for applications

**Comment by bacongobbler** [comment]
ping, is this still being worked on

**Comment by deis-admin** [comment]
This issue was moved to deis/workflow#710
