### ISSUE TITLE
Builder v1.10.1 Broken

### ISSUE THREAD

**Issue by Crispy1975** [deis/deis#4825]
Due to the recent Docker Hub changes it is not possible to rebuild the builder component as it tries to pull the `Cedar` image, as a result `slugrunner` cannot be built. We were able to update components to pull from `quay.io` to enable pulling of those images, but the `Cedar` image I guess would require a custom built builder or a fix?

**Comment by krancour** [comment]
@Crispy1975 I believe this was accounted for in more recent releases.

**Comment by bacongobbler** [comment]
Yes, see the note here: https://github.com/deis/deis/releases/tag/v1.12.0

> NOTE: Docker Hub will disable access for docker versions 1.5 and earlier on December 7, 2015. Releases of Deis prior to v1.12.0 relied on docker 1.5.0 and will experience problems after that date. As a result, all users are encouraged to provision a new v1.12.0 cluster which does not rely on a specific docker version.

I don't think there's anything we can do at this point for older versions. Older clusters on an older version of Docker is unsupported by Docker, and older versions of Deis won't work with Docker 1.8.3 until you upgrade the controller to v1.12 so it has [this patch](https://github.com/deis/deis/pull/4581), so the only true fix we can come up with is to provision a newer CoreOS cluster that has Docker v1.8.3 and up with Deis v1.12+. Either that, or you can custom build a v1.5 `cedar` image and push it to Quay, then run a custom builder that uses those images as you suggested, @Crispy1975. That might keep you hobbling along, but unfortunately clusters running "older" versions of Docker won't work with DockerHub any more.

**Comment by Crispy1975** [comment]
Thanks @krancour @bacongobbler we have decided to get onto `v1.12` asap. Any eta on a stable `v2`?

**Comment by carmstrong** [comment]
> Any eta on a stable v2?

We're shooting for stable by March. Alpha is out now, and look for beta in February.

**Comment by Crispy1975** [comment]
@carmstrong awesome, thanks.
