### ISSUE TITLE
[meta] Deis v2 Alpha Feedback

### ISSUE THREAD

**Issue by slack** [deis/deis#4827]
This is a meta issue to aggregate community feedback for the Deis v2 Alpha!

**Comment by olalonde** [comment]
Not sure if I'm supposed to ask this here but what happens with deisctl in v2? Couldn't find references to it in https://github.com/deis/workflow

**Comment by bacongobbler** [comment]
deisctl will be going away. The installation process has been succeeded by [helm](https://github.com/helm/helm) and most of the customization is being done through attaching annotations to a replication controller through kubectl. We are planning on completely removing etcd.
