### ISSUE TITLE
deis tags:set isn't restricting my app to certain hosts (deis 1.12.2)

### ISSUE THREAD

**Issue by dmcnaught** [deis/deis#4830]
I increased my autoscaling group after adding the new tag environi=prod (10.51.2.106). I also added that tag to 10.51.1.91, but I didn't restart the instance after adding the tag.
I scaled the app down to 0 and up again - and here is the following state (app is deployed onto nodes without that tag):

$ deis tags:list
=== madras-woodshed Tags
environi     prod

aws ec2 describe-instances --filters "Name=tag:environi,Values=prod"  --query "Reservations[*].Instances[*].PrivateIpAddress[]" --output=text
10.51.2.106	10.51.1.91

madras-woodshed_v8.cmd.1.service	18066820.../10.51.2.106	active	running
madras-woodshed_v8.cmd.2.service	18066820.../10.51.2.106	active	running
madras-woodshed_v8.cmd.3.service	227126dd.../10.51.2.131	active	running
madras-woodshed_v8.cmd.4.service	227126dd.../10.51.2.131	active	running
madras-woodshed_v8.cmd.5.service	18066820.../10.51.2.106	active	running
madras-woodshed_v8.cmd.6.service	18066820.../10.51.2.106	active	running
madras-woodshed_v8.cmd.7.service	227126dd.../10.51.2.131	active	running
madras-woodshed_v8.cmd.8.service	18066820.../10.51.2.106	active	running

**Comment by dmcnaught** [comment]
Oh - I forgot. We want these tags in the fleet metadata... Sry.

**Comment by dmcnaught** [comment]
I set the tag in the fleet metadata:
fleetctl list-machines
MACHINE		IP		METADATA
227126dd...	10.51.2.131	controlPlane=true,dataPlane=true,routerMesh=true
4f059baf...	10.51.1.91	controlPlane=true,dataPlane=true,routerMesh=true
d223bf46...	10.51.1.76	controlPlane=true,dataPlane=true,routerMesh=true
f09fdae0...	10.51.2.87	controlPlane=true,dataPlane=true,environi=prod,routerMesh=true

Then I unset the tag, and set it again (since instructions say to do this after tag is created).

$ deis tags:list
=== madras-woodshed Tags
environi     prod

Still no restriction on scaling down to 0 and back up:
$fleetctl list-units
madras-woodshed_v10.cmd.1.service	227126dd.../10.51.2.131	active	running
madras-woodshed_v10.cmd.2.service	227126dd.../10.51.2.131	active	running
madras-woodshed_v10.cmd.3.service	f09fdae0.../10.51.2.87	active	running
madras-woodshed_v10.cmd.4.service	f09fdae0.../10.51.2.87	active	running
madras-woodshed_v10.cmd.5.service	f09fdae0.../10.51.2.87	active	running

**Comment by krancour** [comment]
Can you show the fleet units for any if the app processes?

**Comment by dmcnaught** [comment]
Sure. Doesn't seem to get the [X-Fleet]\nMachineMetadata

fleetctl cat madras-woodshed_v10.cmd.1
[Unit]
Description=madras-woodshed_v10.cmd.1

[Service]
ExecStartPre=/bin/sh -c "IMAGE=$(etcdctl get /deis/registry/host 2>&1):$(etcdctl get /deis/registry/port 2>&1)/madras-woodshed:v10; docker pull $IMAGE"
ExecStartPre=/bin/sh -c "docker inspect madras-woodshed_v10.cmd.1 >/dev/null 2>&1 && docker rm -f madras-woodshed_v10.cmd.1 || true"
ExecStart=/bin/sh -c "IMAGE=$(etcdctl get /deis/registry/host 2>&1):$(etcdctl get /deis/registry/port 2>&1)/madras-woodshed:v10; docker run --name madras-woodshed_v10.cmd.1 --rm    -P $IMAGE "
ExecStop=/usr/bin/docker stop madras-woodshed_v10.cmd.1
TimeoutStartSec=20m
TimeoutStopSec=10
RestartSec=5
Restart=on-failure

**Comment by dmcnaught** [comment]
I'll dig into the deis logs tomorrow...

**Comment by krancour** [comment]
@dmcnaught see #4763.  It corrects the bug that I suspect is behind your problem.  I _thought_ that fix was in 1.12.2, but apparently not, so this should be corrected in the next minor or patch release.

**Comment by dmcnaught** [comment]
@krancour Is there a work-around?

**Comment by bacongobbler** [comment]
@dmcnaught you could apply that patch to v1.12.2 and build your own custom controller. Other than that, there's no real workaround. I mean you *could* create your own fleet units, but that defeats the purpose of using Deis.

**Comment by dmcnaught** [comment]
It looks like this means that control plane units are not restricted to nodes with that tag too. Is that right?

**Comment by bacongobbler** [comment]
The control plane units should have that X-Fleet directive as that's part of deisctl. This is part of the scheduler which only affects application units. A `fleetctl cat deis-controller` should let you know if it was or was not applied though.

**Comment by krancour** [comment]
@dmcnaught a workaround could be to ensure all nodes are tagged with `dataPlane=true` (looks like that may already be the case for you) and then `$ deisctl config platform set enablePlacementOptions=true`

I think that would get you around the bug, but as @bacongobbler suggests, you could also create a custom controller image.  You could _probably_ build it from master and be fine, or you could cherry-pick the commit that has the fix.

**Comment by dmcnaught** [comment]
@krancour Thanks - that workaround looks good:

$deisctl config platform set enablePlacementOptions=true

$ fleetctl cat madras-woodshed_v12.cmd.5.service
[Unit]
Description=madras-woodshed_v12.cmd.5

[Service]
ExecStartPre=/bin/sh -c "IMAGE=$(etcdctl get /deis/registry/host 2>&1):$(etcdctl get /deis/registry/port 2>&1)/madras-woodshed:v12; docker pull $IMAGE"
ExecStartPre=/bin/sh -c "docker inspect madras-woodshed_v12.cmd.5 >/dev/null 2>&1 && docker rm -f madras-woodshed_v12.cmd.5 || true"
ExecStart=/bin/sh -c "IMAGE=$(etcdctl get /deis/registry/host 2>&1):$(etcdctl get /deis/registry/port 2>&1)/madras-woodshed:v12; docker run --name madras-woodshed_v12.cmd.5 --rm    -P $IMAGE "
ExecStop=/usr/bin/docker stop madras-woodshed_v12.cmd.5
TimeoutStartSec=20m
TimeoutStopSec=10
RestartSec=5
Restart=on-failure

[X-Fleet]
MachineMetadata="environi=prod" "dataPlane=true"

**Comment by krancour** [comment]
Glad that worked.  Since this is a known issue that's already been addressed and you have a viable workaround in the meantime, I'm going to close this.

**Comment by dmcnaught** [comment]
@bacongobbler : 
It looks like the problem was extending to all tags as deis-controller also didn't have the X-Fleet section

**Comment by krancour** [comment]
@dmcnaught `enablePlacementOptions=true` drives whether deisctl "decorates" fleet units for Deis components at the time of `deisctl install platform`.

**Comment by dmcnaught** [comment]
Thanks. So for now I'll run the workaround before deisctl install platform (deisctl config platform set enablePlacementOptions=true) and that should get the plane/tag isolation working again.
