### ISSUE TITLE
Fresh install of v1.12.2 fail to start

### ISSUE THREAD

**Issue by nkts** [deis/deis#4831]
It's 1 node "cluster".

```
$ deisctl install platform --router-mesh-size=1
● ▴ ■
■ ● ▴ Installing Deis...
▴ ■ ●
Storage subsystem...
deis-store-daemon.service: loaded
deis-store-volume.service: loaded
deis-store-metadata.service: loaded
deis-store-monitor.service: loaded
deis-store-gateway@1.service: loaded
Logging subsystem...
deis-logspout.service: loaded
deis-logger.service: loaded
Control plane...
deis-builder.service: loaded
deis-registry@1.service: loaded
deis-database.service: loaded
deis-controller.service: loaded
Data plane...
deis-publisher.service: loaded
Router mesh...
deis-router@1.service: loaded
Done.

Please run `deisctl start platform` to boot up Deis.

$ deisctl start platform
● ▴ ■
■ ● ▴ Starting Deis...
▴ ■ ●
Storage subsystem...
```

journal output:
```
-- Unit deis-store-monitor.service has begun starting up.
Jan 05 03:40:05 coreos1 dockerd[760]: time="2016-01-05T03:40:05.971099212Z" level=info msg="GET /v1.21/images/alpine:3.2/history"
Jan 05 03:40:06 coreos1 dockerd[760]: time="2016-01-05T03:40:06.018612475Z" level=info msg="GET /v1.21/containers/deis-store-monitor-data/json"
Jan 05 03:40:06 coreos1 sh[2444]: /bin/sh: /run/deis/bin/get_image: No such file or directory
Jan 05 03:40:06 coreos1 sh[2444]: docker: "pull" requires 1 argument.
Jan 05 03:40:06 coreos1 sh[2444]: See 'docker pull --help'.
Jan 05 03:40:06 coreos1 sh[2444]: Usage:        docker pull [OPTIONS] NAME[:TAG|@DIGEST]
Jan 05 03:40:06 coreos1 sh[2444]: Pull an image or a repository from a registry
Jan 05 03:40:06 coreos1 systemd[1]: deis-store-monitor.service: Control process exited, code=exited status=1
Jan 05 03:40:06 coreos1 systemd[1]: Failed to start deis-store-monitor.
-- Subject: Unit deis-store-monitor.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit deis-store-monitor.service has failed.
-- 
-- The result is failed.
Jan 05 03:40:06 coreos1 systemd[1]: deis-store-monitor.service: Unit entered failed state.
Jan 05 03:40:06 coreos1 systemd[1]: deis-store-monitor.service: Failed with result 'exit-code'.
```

**Comment by krancour** [comment]
If I had to take a guess... your 1 node "cluster" is probably still wanting wanting a majority of three (the default) etcd nodes available to establish quorum.  Without etcd functioning properly, other components are not going to start cleanly.  (If this explanation _is_ correct, though, I'm a little surprised that you even got past the `deisctl install platform` step successfully.)

Consider checking etcd cluster health to either verify or refute this explanation.  ssh to the node and:

```
$ etcdctl cluster-health
```

Also, it's well worth noting that Deis 1.x is not supported on fewer than three nodes.  For single node "clusters," we have historically pointed people in the direction of [dokku](http://dokku.viewdocs.io/dokku/), whose development we have also sponsored.

**Comment by rimusz** [comment]
as @krancour have mentioned Deis v1 does not work on one node.
Recently we have released Deis v2 alpha, which works on top of Kubernetes and can be run on one node, using Deis-Lite helm chart https://github.com/TheNewNormal/kube-charts/tree/master/deis-lite you can install Deis v2 on any one node Kubernetes cluster for testing it out.

Our newsletter about Deis v2 https://groups.google.com/forum/#!topic/deis-users/Qhia4DD2pv4

**Comment by bacongobbler** [comment]
I'm going to close this as we do not support clusters with less than three nodes as stated in the documentation. Ceph, and deisctl rely on three nodes being present at the very least. In v2 this has changed, but this isn't something that we're going to fix for v1.
