### ISSUE TITLE
AWS: Can we configure to use more than two Availability Zones in deis.template.json?

### ISSUE THREAD

**Issue by dmcnaught** [deis/deis#4833]
Resources.Subnet1 and Resources.Subnet2 specify the Availability Zones for CloudFormation in deis.template.json
Can we configure to use four AZs instead of the default (two)?

**Comment by krancour** [comment]
If you BYO-VPC (bring your own VPC), you can IIRC, use as many subnets in as many AZs as you have available.  Generally, I _would_ recommend bringing your own VPC anyway.  Separating the management and lifecycle of the virtual network from the things deployed _into_ that network is good for many practical reasons.

**Comment by dmcnaught** [comment]
Thanks @krancour
