### ISSUE TITLE
deis register command options not working? (1.12.2)

### ISSUE THREAD

**Issue by dmcnaught** [deis/deis#4836]
When I try to register in one command it hangs, works fine when doing interactive:

`deis register --username=<username> --password=<pw> --email=<email> https://deis.ourdomain.com`

**Comment by sgoings** [comment]
That's no good! I'll try to reproduce right quick. Is there any chance there are some characters in the username, password, or email that could be messing with the command's execution? (Try quoting the value of each)

**Comment by dmcnaught** [comment]
I tried quoting them all and no luck. Password has no special characters (just numbers and letters).
Username and email have a "."

**Comment by bacongobbler** [comment]
That's certainly interesting -- that's how the [integration tests](https://github.com/deis/deis/blob/v1.12.2/tests/auth_test.go#L14) register a user. When you mean by "it hangs", is it like a connection hang, or is it prompting for more information? If you have wireshark set up or some similar network sniffer, that might help knock down the problem here.

**Comment by bacongobbler** [comment]
Oh, I see the problem. Try adding the options **after** the URL. As per the usage:

> Usage: deis auth:register <controller> [options]

Certainly odd that it hangs in that situation though.

**Comment by dmcnaught** [comment]
Actually working with non ssl - so let me dig into that a little more...

**Comment by sgoings** [comment]
I am able to replicate the behavior via:

```
deis register https://deis.${DEIS_TEST_DOMAIN} --username=test --password=test --email=test@example.com
```

but everything works fine if I choose http (not https) for the `deis register` url.

**Comment by bacongobbler** [comment]
Hey @dmcnaught, did you install a SSL certificate on the routers following the guide at http://docs.deis.io/en/latest/managing_deis/ssl-endpoints/?

**Comment by dmcnaught** [comment]
@bacongobbler I thought I did, but I lost that line from my cluster automation setup script. I've re-adding it and it looks good now, thanks.
