### ISSUE TITLE
Question Can I use update-aws-cluster.sh without destroying apps?

### ISSUE THREAD

**Issue by rstacruz** [deis/deis#4837]
In the documentation, it says this about `update-aws-cluster.sh`:

> Depending on the parameters that you have changed, CloudFormation may replace the EC2 instances in your stack.

I assume changing `InstanceType` will kill my nodes and bring new ones back up. Does this mean I'll need to reinstall deis on the new nodes? Will the apps that live on my nodes disappear?

**Comment by bacongobbler** [comment]
If you're changing the InstanceType, all nodes will be wiped. At that point the entire will be completely knocked out, losing all data. You'll probably want to go through the backup/restore documentation. Yes, the apps that live on your nodes will disappear.

docs: http://docs.deis.io/en/latest/managing_deis/backing_up_data/

**Comment by rstacruz** [comment]
Will I need to `deisctl install platform` again?

**Comment by bacongobbler** [comment]
Yep. If you go that route you'll likely have to start from complete scratch.

**Comment by dmcnaught** [comment]
@rstacruz Probably best to update the InstanceType in new copy of the Autoscaling group (and set the ASG to use that) if you want to change the type for an existing cluster. Adding and Terminating one node at a time you could probably get the deis platform and apps to move over. Not sure you'd want to do it that way though...

**Comment by carmstrong** [comment]
I recall someone recently commenting on a GitHub issue that they worked around this by pausing automatic termination of hosts until they could be manually replaced one-by-one. Trying to dig for that now...

**Comment by dmcnaught** [comment]
Here's the page on suspending AutoScaling groups. I haven't seen anything on that and deis update-aws-cluster.sh
http://docs.aws.amazon.com/AutoScaling/latest/DeveloperGuide/US_SuspendResume.html

I used it to update coreos metadata (tags) for deis nodes.
Steps:
- Suspend healthcheck (or it stays unhealthy after reboot in my experience - can't just stop termination because of this)
- Stop Instance
- Change user data
- Start instance
- Remove suspension of healthcheck when instance is up and functioning.

**Comment by rstacruz** [comment]
Should I suspend `Terminate` too to be sure?

![pasted_image_1_8_16__5_51_pm](https://cloud.githubusercontent.com/assets/74385/12195201/6da07568-b630-11e5-8433-4de43c7c456e.jpg)

**Comment by rstacruz** [comment]
hmm.. I ran `update-aws-cluster.sh` but nothing happened. I see `Your Deis cluster on AWS CloudFormation has been successfully updated.` but no events show up in the EC2 autoscale's events.

**Comment by dmcnaught** [comment]
@rstacruz Did you look in CloudTrail to see what actions occurred in AWS? What did you update in update-aws-cluster.sh?
It worked for me just to suspend HealthCheck, but I'd recommend testing it out yourself before using on a live system.

**Comment by rstacruz** [comment]
I updated cloudformation.json like so:

```diff
[
    {
        "ParameterKey":     "KeyPair",
        "ParameterValue":   "deis"
    },
+   {
+       "ParameterKey":     "InstanceType",
+       "ParameterValue":   "m3.large"
+   }
]
```

...i saw the actions in the CloudFormation log, but nothing in EC2 AutoScaling or EC2.

**Comment by dmcnaught** [comment]
@rstacruz - Regarding my earlier comment about updating the cluster to a new instance type. Probably it would be easier just to stop each instance (one at a time) and change the instance type in AWS (suspending the autoscaling healthcheck). No need to create new instances.
It seems unlikely to me that update-aws-cluster.sh would be set up to update the instance type - that would be quite a complex scripting operation, not really related to the deis project imho.

**Comment by rstacruz** [comment]
aye, gotcha. it just really seemed like `update-aws-cluster.sh` was the right way, from what I gathered with the docs.

**Comment by rstacruz** [comment]
This is amazing... it worked flawlessly. Can I contribute a how-to guide on this?

**Comment by bacongobbler** [comment]
Certainly! Perhaps some documentation in https://github.com/deis/deis/blob/master/docs/installing_deis/aws.rst would be useful for others maintaining v1 clusters.

**Comment by rstacruz** [comment]
By the way, I see `provision-aws-cluster.sh` by default creates an autoscaling group with `min=3` `max=12`. Does this mean that new machines will spawn as needed? This doesn't seem to be mentioned in the guide.

**Comment by rstacruz** [comment]
@bacongobbler neat. should I make a new page, or just consider to write this as a blog post? Here's a very rough draft: (sorry about the image)

> <img src='https://cloud.githubusercontent.com/assets/74385/12205770/b931def8-b677-11e5-969b-373f73bdb5ac.png' width='400'>

**Comment by bacongobbler** [comment]
> Does this mean that new machines will spawn as needed? This doesn't seem to be mentioned in the guide.

Yes, new machines will be spawned if others are killed off. :)

I think that document would look good in the AWS installation docs, perhaps under a new title called "Changing Instance Types".

**Comment by rstacruz** [comment]
> Yes, new machines will be spawned if others are killed off. :)

What about, say, when CPU and Memory resources are getting near-exhausted?

**Comment by rstacruz** [comment]
Also, does this mean that you don't need `update-aws-cluster.sh` to, say, go from 3 machines to 5? you can simply change the auto-scaling group to `min=5`. Looks like it can work in theory.

**Comment by carmstrong** [comment]
@rstacruz `update-aws-cluster.sh` is used to update the CloudFormation template in AWS when you make changes to template parameters. You can certainly do this yourself in the interface, such as when you update the autoscaling group.

Also, note that AWS doesn't immediately replace all resources upon a change - you'll need to consult the AWS docs to see what action (if any) is taken on update for each individual parameter. 

For example, for `InstanceType`: 

> InstanceType
> The instance type, such as t2.micro. The default type is "m1.small". For a list of instance types, see Instance Families and Types.
> Required: No
> Type: String
> Update requires: Some interruptions for Amazon EBS-backed instances
> Update requires: Replacement for instance store-backed instances


See http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-instancetype
