### ISSUE TITLE
Deis remove docker base image

### ISSUE THREAD

**Issue by gergelyke** [deis/deis#4847]
Hey,

it seems that the base image I am using for one of the applications is not updated - can you help me how can I remove/bust the cache?

Thanks a lot,
Gergely

**Comment by krancour** [comment]
Can you elaborate a bit, please?

**Comment by gergelyke** [comment]
Hello @krancour,

sure.

So my use case was the following:

* created an alpine-based image on dockerhub https://hub.docker.com/r/risingstack/alpine/tags/ with the tag v4.2.4
* tried to deploy an app using that image, but the image was broken
* fixed the image with the same tag
* new tried to deploy again, but it seems that the builder is not using the latest image

Any idea?

**Comment by bacongobbler** [comment]
that's a design feature (or flaw, whatever you think of it) of Docker. If the image exists in the current "registry" (not a docker registry, the local image registry) then it won't pull down the other tag. "Immutable infrastructure" and all that jazz :)

To fix this the only way I know of would be to use `deisctl dock builder` and `docker rmi -f risingstack/alpine:v4.2.4` and then try another build. That'll force the builder to fetch the new image.

**Comment by gergelyke** [comment]
thanks!
