### ISSUE TITLE
git push deis master fails with PRIVATE_KEY

### ISSUE THREAD

**Issue by pawel-yesware** [deis/deis#4848]
I thought this was fixed in deis 1.10 but looks like it's not

https://github.com/deis/deis/issues/2682

deis config:set PRIVATE_KEY="-----BEGIN RSA PRIVATE KEY-----\n"

$ git push -f deis master
Counting objects: 159996, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (35506/35506), done.
Writing objects: 100% (159996/159996), 55.80 MiB | 5.10 MiB/s, done.
Total 159996 (delta 117801), reused 159912 (delta 117735)
Unable to find image 'RSA:latest' locally
repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"
To ssh://git@:2222/yeswaredev.git
 + d92a004...dc2ec95 master -> master (forced update)

**Comment by bacongobbler** [comment]
@pawel-yesware capital letters in docker images are not allowed. You'll have to change your Dockerfile's FROM clause to something in line with their expectations of a proper docker image name.

**Comment by carmstrong** [comment]
@bacongobbler I'm pretty sure this is our bug - the `RSA` comes from the space in the config, as @pawel-yesware reported.

**Comment by bacongobbler** [comment]
good catch; my apologies. Re-opening!

**Comment by bacongobbler** [comment]
pretty sure this has been fixed in v2. please re-open if this is not the case. Thanks!
