### ISSUE TITLE
[meta] Standardize Storage Paths for K8S Components

### ISSUE THREAD

**Issue by slack** [deis/deis#4852]
For all v2 components that declare volumes, we should standardize on the location to make troubleshooting and expectations consistent. We should audit all components and make sure there is a sensible filesystem layout!

For example, minio should store data in `/data/minio/...`, postgres would use `/data/postgres/...`

Refs deis/deis#4809

**Comment by technosophos** [comment]
I've noticed (as I read through various stuff) that in Kubernetes, they seem to treat `/var/run/secrets` as the de facto path for mounting secrets. Maybe `/var/run/data` would be a nice parallel for persistent data?

/cc @arschles @helgi and @krancour

**Comment by arschles** [comment]
I'm :+1: on `/var/run/data` for persistence

**Comment by bacongobbler** [comment]
Is there any technical benefit to this other than consistency? For example in deis/postgres it makes sense to mount the minio AWS credentials in `/etc/wale.d/env/` because those values are then used as environment variables when paired with `envdir`. Not sure if this is something we should target for beta, as this qould require changes both at deis/charts and in each respective repo just for consistency.

**Comment by arschles** [comment]
Audit of storage locations:

- [deis-dev/builder](https://github.com/deis/charts/blob/master/deis-dev/tpl/deis-builder-rc.yaml)
	- `minio-user` secret: `/var/run/secrets/object/store`
	- `builder-key-auth` secret: `/var/run/secrets/api/auth`
	- `objectstore-creds` secret: `/var/run/secrets/deis/objectstore/creds
- [deis-dev/database](https://github.com/deis/charts/blob/master/deis-dev/tpl/deis-database-rc.yaml)
	- `minio-user` secret: `/etc/wal-e.d/env`
	- `database-creds` secret: `/var/run/secrets/deis/database/creds`
	- `objectstore-creds` secret: `/var/run/secrets/deis/objectstore/creds`
- [deis-dev/registry](https://github.com/deis/charts/blob/master/deis-dev/tpl/deis-registry-rc.yaml)
	- `registry-storage` empty dir: `/var/lib/registry`
	- `registry-creds` secret: `/var/run/secrets/deis/registry/creds`
- [deis-dev/workflow](https://github.com/deis/charts/blob/master/deis-dev/tpl/deis-workflow-rc.yaml)
	- `docker-socket` dir: `/var/run/docker.sock`
	- `minio-user` secret: `/var/run/secrets/deis/minio/user`
	- `builder-key-auth` secret: `/var/run/secrets/api/builder/auth`
	- `django-secret-key` secret: `/var/run/secrets/api/django`
	- `database-creds` secret: `/var/run/secrets/deis/database/creds`
- [deis-dev/minio](https://github.com/deis/charts/blob/master/deis-dev/manifests/deis-minio-rc.yaml)
	- `minio-admin` secret: `/var/run/secrets/deis/minio/admin`
	- `minio-user` secret: `/var/run/secrets/deis/minio/user`
- [deis-dev/router](https://github.com/deis/charts/blob/master/deis-dev/manifests/deis-router-rc.yaml) mounts no volumes
- [router-dev](https://github.com/deis/charts/blob/master/router-dev/manifests/deis-router-rc.yaml) mounts no volumes
- [router](https://github.com/deis/charts/blob/master/router/manifests/deis-router-rc.yaml) mounts no volumes
- [deis-logger](https://github.com/deis/charts/blob/master/deis-logger/manifests/deis-logger-rc.yaml) mounts no volumes

**Comment by bacongobbler** [comment]
> @bacongobbler what are the code changes necessary in the deis/database repo to move that?

Should be only three line changes: https://github.com/deis/postgres/blob/16d13629d72a512b9f99521de2064d5cf0f254b5/rootfs/docker-entrypoint-initdb.d/001_setup_envdir.sh#L3-L7

**Comment by arschles** [comment]
@bacongobbler thanks!

**Comment by helgi** [comment]
I have no clue why it mounts the docker socket. Probably from when we were doing new FS layers or maybe it's required to do the docker client stuff re: ports discovery and stuff. @mboersma @bacongobbler  ?

**Comment by bacongobbler** [comment]
Yeah it was from when we pulled in the image, injected the envvars into the image then re-pushed to the registry. However I still think we need it: https://github.com/deis/workflow/blob/60041c52681a3de879079c80e3dfd25420f4cc85/rootfs/scheduler/__init__.py#L595-L598

**Comment by arschles** [comment]
@bacongobbler @helgi ok, I'll leave it in for now

**Comment by arschles** [comment]
@slack @bacongobbler @helgi turns out this will require a few non-trivial code changes. I recommend that we punt this to RC for the following reasons:

1. Releasing a beta without these changes won't hinder the individual-component upgrade path
2. The changes required pose a risk, but the reward seems only to be more standardized paths, which I don't think is worth it for beta

Thoughts?

**Comment by bacongobbler** [comment]
:+1:. It ;s the same argument held over at https://github.com/deis/charts/pull/142. High risk, low reward, doesn't impact component upgrade path.

**Comment by helgi** [comment]
Do we have a handle on what needs changing? If the above list is good enough and shows us what needs to be done then we can easily post that as "here are all the paths" in docs and call it a day for beta, potentially even RC.

Punt to RC for now and lets revisit then

**Comment by arschles** [comment]
Ok, punting to RC1

**Comment by smothiki** [comment]
@slack as of now we aare using a single storage secret for every component and Paths look more standard than before https://github.com/deis/workflow/blob/master/src/installing-workflow/configuring-object-storage.md#deisdatabase. what else can be done here moving to next sprint

**Comment by slack** [comment]
Good enough!
