### ISSUE TITLE
[meta] Audit components for port usage.

### ISSUE THREAD

**Issue by slack** [deis/deis#4853]
All components deployed as part of the Deis platform should use standard ports wherever possible. Audit all cluster services and make sure default ports are used by default.

Refs deis/deis#4809

**Comment by technosophos** [comment]
This is marked checked on the TODO list. Can whoever did the check also close this issue?

**Comment by technosophos** [comment]
Now it's marked unchecked... so I'll assume we still need to do this.

**Comment by bacongobbler** [comment]
I just did a quick sweep audit on the deis-dev chart. Everything looks like standard ports based on their parent projects (9000 for minio, 5432 for postgres, port 80/443/2222 for router, 2223 for builder). Closing!

**Comment by slack** [comment]
By "standard ports" I intended to convey that we would use standard ports for the *protocol* being used. 

In this case registry should move from 5000 to 80, minio should move from 9000 to 80, etc.

This will remove ambiguity as we later add component SSL support.

**Comment by bacongobbler** [comment]
The main blocker for that is the ability to bind to port 80 without being a root user. It's a security issue, and this is why these projects (including postgres) recommend binding to a port higher than 1024 like port 5000 and port 9000, then let projects like `nginx` bind to "standard" ports because they handle permissions correctly by binding to the specified port as root, then drop privileges to the `Nobody` user for the workers accepting incoming connections.

For example, see https://github.com/deis/router/issues/125#issuecomment-186354040.

**Comment by slack** [comment]
Sure, the service expression within the k8s cluster can be on standard ports and the containers can listen on alternate (but standardized) ports. I'm really looking for consistency. If it is an http service, 80, 443 (and 6080, 6443) or whatever. So operators of the Deis platform don't have to go digging on a per-component basis to figure out who is listening on what.

Make sense?

**Comment by bacongobbler** [comment]
Ah you just want the `port` value on the services to be port 80, but the containers can leave their `targetPort`s as they see fit. Makes sense. Re-opening so we can open issues for the respective components to handle this behaviour.

**Comment by arschles** [comment]
See below for the current status of ports. Non-standard ports are in __bold__.

- [deis/router-dev](https://github.com/deis/charts/blob/master/router-dev/manifests/deis-router-service.yaml) and [deis/router](https://github.com/deis/charts/blob/master/router/manifests/deis-router-service.yaml)
	- 80 (http)
	- 443 (https)
	- 2222 (ssh)
	- 9090 (healthz)
- [deis/logger](https://github.com/deis/charts/blob/master/deis-logger/manifests/deis-logger-svc.yaml)
	- __8088 (http)__
	- 1514 (udp)
- [deis-dev/builder](https://github.com/deis/charts/blob/master/deis-dev/manifests/deis-builder-service.yaml)
	- 2222 (ssh)
- [deis-dev/database](https://github.com/deis/charts/blob/master/deis-dev/manifests/deis-database-service.yaml)
	- __5432 (http)__
- [deis-dev/minio](https://github.com/deis/charts/blob/master/deis-dev/manifests/deis-minio-service.yaml)
	- __9000 (http)__
- [deis-dev/registry](https://github.com/deis/charts/blob/master/deis-dev/manifests/deis-registry-service.yaml)
	- __5000 (http)__
- [deis-dev/router](https://github.com/deis/charts/blob/master/deis-dev/manifests/deis-router-service.yaml)
	- 80 (http)
	- 443 (https)
	- 2222 (builder)
	- 9090 (healthz)
- [deis-dev/workflow](https://github.com/deis/charts/blob/master/deis-dev/manifests/deis-workflow-service.yaml)
	- 80 (http)

**Comment by arschles** [comment]
The lone remaining PR on this meta-issue is https://github.com/deis/charts/pull/142 (accompanying issue: https://github.com/deis/charts/issues/138), and @bacongobbler has been working on a fix for it in deis/postgres for at least a few days.

I believe that all components but the database can work with the Minio service on any port (as defined by the `DEIS_MINIO_SERVICE_PORT` env var), we should punt this issue (and deis/charts#138) to RC. Meanwhile, the only component whose upgrade will be broken is the database itself.

Thoughts?

cc/ @slack @bacongobbler @technosophos

**Comment by smothiki** [comment]
moving this to next print

**Comment by slack** [comment]
deis/charts#138 Not worth the effort at this point. Closing.
