### ISSUE TITLE
Container Specific Resolv.conf

### ISSUE THREAD

**Issue by mooyah** [deis/deis#4868]
Hello,

I'm hoping you can help me with a specific problem I'm encountering with my deis container. I am using a Dockerfile deploy to deis based on a centos6 container. My application relies on the search domain of the container to properly find the dns names. How do I update the resolv.conf of my container without affecting the core os resolv.conf?

TYIA for your help!

**Comment by bacongobbler** [comment]
This is what I got from [Docker's documentation](https://docs.docker.com/engine/userguide/networking/default_network/configure-dns/):

> Regarding DNS settings, in the absence of the --dns=IP_ADDRESS..., --dns-search=DOMAIN..., or --dns-opt=OPTION... options, Docker makes each container’s /etc/resolv.conf look like the /etc/resolv.conf of the host machine (where the docker daemon runs). When creating the container’s /etc/resolv.conf, the daemon filters out all localhost IP address nameserver entries from the host’s original file

So for v1, I know we don't supply any way to add any additional flags to the `docker run` operation. You will need to modify your host's resolv.conf in order for changes to occur within the container, or create a patch for Deis to plug into the container's dns resolver with an option flag in the fleet manifest file.

When you mean by relying on the search domain of the container, would it be easier to use the hostname instead? Perhaps there's an easier way to resolve your issue.

**Comment by mooyah** [comment]
I may end up working around the problem by appending the FQDN to all of my configuration options, but I'd also like to contribute to deis by adding a feature that allows options to be passed to the docker run operation. Do you already have a design on how those options would be specified when the application is built using a Dockerfile?

**Comment by krancour** [comment]
> I'd also like to contribute to deis by adding a feature that allows options to be passed to the docker run operation.

We're in a transition period right now between Deis v1.x and an upcoming Deis v2 release.  We're fixing bugs in the 1.x branch to create an LTS release (long-term support).  For the most part, we're not contemplating adding new features there.

With respect to v2, Deis pivots a bit to run atop Kubernetes.  They way this _could_ be achieved in v2 on k8s is definitely different from how it might have been achieved in the v1.x days.  At any rate, this has not been speced out.

All that being said, I do believe that what you're attempting runs counter to the principles described by [12 factor](http://12factor.net/) and Deis caters to 12factor apps.  Specifically I believe this violates [factor no. 3](http://12factor.net/config).  By relying on configuration (i.e. non-fully qualified hostnames) that is only complete when considered in the context of the host (even though the host is a container in this instance), the application has been made less portable.

imho, the workaround you considered is actually the right way to address this.
