### ISSUE TITLE
Deis Whitelist breaks under specific configuration

### ISSUE THREAD

**Issue by sstarcher** [deis/deis#4869]
In reference to #4400 (comment)

* enforceHTTPS=true
* enforceWhitelist=true
* proxyProtocol=false
* SSL termination at AWS ELB
* DEIS_WHITELIST fails to block connections

**Comment by krancour** [comment]
@sstarcher just want to check something here:

> DEIS_WHITELIST fails to block connections

Would it be more accurate to say "DEIS_WHITELIST fails to _allow_ connections?"

What I'm seeing is that _without_ PROXY protocol in play, although the HTTP `X-Forwarded-For` header has been set correctly by the ELB, the value of this header has no affect on the `allow` directive, which is only considering the IP of the proximate client-- the ELB.

Ultimately, this appears to me not to be a failure to block, but a failure to allow.

Here is how I might consider fixing this:

https://end0tknr.wordpress.com/2015/06/18/access-allowdeny-control-by-x-forwarded-for-ip-address-in-nginx-conf/

@bacongobbler: I'm wondering if you have an opinion on whether this needs to be fixed for the LTS.

**Comment by bacongobbler** [comment]
I'm not sure if we have the resources to fix it for the LTS. It's a bug, but we should be focusing on last-minute features for v1 first, then if we have time come back to bug fixes in the future. If you want to tackle the issue yourself @sstarcher then we'd be more than happy to accept a patch, but we've already got a [pretty tall list](https://github.com/deis/deis/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22v1.13+LTS%22) for 3 people on the LTS team (being myself, @krancour and @mboersma). If I have time I can try to swing back to this but I can't make any guarantees.

**Comment by sstarcher** [comment]
@bacongobbler It's more of an FYI 

I worked around it by terminating my SSL at the routers instead of the ELB.

**Comment by krancour** [comment]
@bacongobbler fwiw, I think this fix is relatively easy.

**Comment by krancour** [comment]
Actually, my initially proposed solution won't work, but that's ok, because after more consideration, this is just a symptom of a larger problem with, ironically, an _easier_ fix.

We're _only_ using the `real_ip` module when PROXY protocol is used.  We should be at least _attempting_ to set the real IP from the `X-Forwarded-For` header whenever proxy protocol is _not_ used.
