### ISSUE TITLE
Pushing non-master branches

### ISSUE THREAD

**Issue by rstacruz** [deis/deis#4870]
It seems like it's possible to push a non-master branch, contrary to the docs.

> Deis builds are created automatically on the controller when a developer uses git push deis master.
> When a new build is created, a new Release is created automatically.
>
> Note:
> Deis only supports git push to the master branch.

```
$ git push deis develop
Total 0 (delta 0), reused 0 (delta 0)
-----> Fetching custom buildpack
-----> Multipack app detected
       =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
       =====> Detected Framework: Node.js

-----> Creating runtime environment
...
```

Should the docs be updated?

**Comment by carmstrong** [comment]
ping @arschles

**Comment by bacongobbler** [comment]
I recall that this is intentional after @technosophos rewrote the builder in Go, so yes the docs should be updated.

**Comment by arschles** [comment]
@bacongobbler is also correct for the current builder implementation - it allows pushes to all branches. I believe there was another issue or discussion about this, but its location escapes me right now.

**Comment by Anilkumar18** [comment]
when pushing repository from local branch to remote branch getting an error
`git push test(local deis branch) test:master(remote)`
when using this command docker file is building from remote branch
while building docker file it shows as below

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.9/main: temporary error (try again later)
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.9/main: No such file or directory
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.9/community: temporary error (try again later)
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.9/community: No such file or directory
ERROR: unable to select packages:
  bash (no such package):
    required by: world[bash]
The command '/bin/sh -c apk add --update bash && rm -rf /var/cache/apk/*' returned a non-zero code: 1
```
I searched and did many troubleshoot to resolve this error regarding docker.
but now I doubt that it may error from github or deis push.
we are installing deis workflow in eks cluster and deploying deis apps in eks cluster.
i don't have any idea why it happening. can anyone help me to resolve this error?thank you
