### ISSUE TITLE
Azure: VM's not being created and IP not set

### ISSUE THREAD

**Issue by zwanthor** [deis/deis#4881]
I am creating a 3-Node Deis cluster on Azure. Using this tutorial: http://docs.deis.io/en/latest/installing_deis/azure. When I execute this command 

`azure group create --name deis --location "West US" --deployment-name deis --template-file arm-template.json --parameters-file parameters.json`

A new resource group is created on my account, which contains deisAvailabilitySet, loadBalancer, loadBalancerIP and deisvNet, but the resource group fails to create the VM's and the loadBlancer does not have an IP.

As a note in the resource group under "last deployment" it is listed as failed.

In the parameters.json file I have the following
```
{
  "newStorageAccountName": {
    "value": "deis"
  },
  "publicDomainName": {
    "value": "deisNinja"
  },
  "dnsPrefixNameForPublicIP": {
    "value": ""
  },
```

**Comment by monaka** [comment]
Try filling in the value of dnsPrefixNameForPublicIP like this:

```
"dnsPrefixNameForPublicIP": {
    "value": "deisNinja"
  },
```

**Comment by carmstrong** [comment]
@monaka Is correct - this value is required.

**Comment by zwanthor** [comment]
Ok I missed something before, but I I looked more into why the deployments failed. The deployment of the loadBalancerIP, VM's etc. failed with this error message:

```
{"error":{"code":"InvalidDomainNameLabel","message":"The domain name label deisNinja is invalid. It must conform to the following regular expression: ^[a-z][a-z0-9-]{1,61}[a-z0-9]$.","details":[]}}
```

So looks like Microsoft restricts the domain name not having capitals and numbers. The example in 
http://docs.deis.io/en/latest/installing_deis/azure/ uses "deisNode" for the publicDomainName prefix, which would fail.

**Comment by carmstrong** [comment]
> The example in 
> http://docs.deis.io/en/latest/installing_deis/azure/ uses "deisNode" for the publicDomainName prefix

Actually, `deisNode` is [defined](https://github.com/deis/deis/blob/6ec3e06702714f4529d4383e3ab063d062d927af/contrib/azure/arm-template.json#L111) in the template itself as the `vmNamePrefix`. The example works as-is, and assumes that you set a proper value for `publicDomainName` as no default is supplied. 

But you are correct - the regular expression they output (`^[a-z][a-z0-9-]{1,61}[a-z0-9]$.`) does not accept upper-case characters.

**Comment by zwanthor** [comment]
Oh, thanks for the clarification!
