### ISSUE TITLE
Logs drain over HTTP protocol

### ISSUE THREAD

**Issue by arkkanoid** [deis/deis#4884]
Hi, 
I want to drain all logs to ElasticSearch. I'm using AWS ElasticSearch service that uses HTTP protocol and doesn't support TCP (http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html).

As I see in Deis documentation the logger component only supports TCP and UDP connections. 

Is there anyway to connect the logger component with AWS ElasticSearch service?

**Comment by jchauncey** [comment]
We are not adding new features to the v1 logger but with deis v2 this will be supported out of the box. If you would like you can check out github.com/deis/logger and github.com/deis/fluentd for more information.
