### ISSUE TITLE
Design Doc: Support Private Registries Behind Auth

### ISSUE THREAD

**Issue by miketheprogrammer** [deis/deis#4885]
Goal: 
To support enterprise stacks without the need for `git push deis` which is often slow in most normal network conditions.

Code Changes:
Client - implement flag -f --forward-credentials
  - this can utilize a users docker login, to forward credentials from ~/.docker/auth.json
  - this would be familiar to users of other schedulers

Builder - go-dockerclient and docker remote api support the x-registry-auth and related headers.
Our builder should leverage theses with the forwarded credentials

By always forwarding credentials we improve security dramatically by not storing state in the cluster.

Testing:
  Unit tests should be implemented at the builder level for param validation.
  Functional tests should test the relationship between the client and the builder service.

Any suggestions?

**Comment by bacongobbler** [comment]
@miketheprogrammer I'm having a tough time recalling specifically what this use case resolves. Can you please provide your use case as well as how you'd intend to use such a feature in your environment with client command examples?

**Comment by miketheprogrammer** [comment]
Please just close this. Its not relevant to the next version anyway
