### ISSUE TITLE
Stateless/Cephless Question

### ISSUE THREAD

**Issue by Crispy1975** [deis/deis#4891]
This is more of a question than an issue. We run stateless on AWS, but we were wondering if it's feasible to do something similar on say ... Google Cloud. My understanding is that S3 replaces the store component so that the registry components can store it's images. Would it be feasible to replace the registry component with Google's hosted Docker registry and negate the need for the cluster registry component and S3 backing it?

**Comment by krancour** [comment]
In theory, yes, but if I am not mistaken, what currently doesn't exist right now is any option/ability to authenticate the builder and each worker/host to a private registry.

**Comment by Crispy1975** [comment]
Thanks @krancour would what @bacongobbler alludes to here https://github.com/deis/deis/issues/4756 make this feasible?

**Comment by krancour** [comment]
Only partly.  @bacongobbler mentions the possibility of adding credentials to the `.dockercfg` file on each host.  What that would allow is for Fleet units (scheduled via Deis) that do a `docker pull` from the private registry to successfully authenticate.  That would, in theory, get `deis pull` working fine, but if you want to build apps using buildpacks, it is not only each host that must be able to authenticate to your external, private registry, but, I believe, builder and controller would need to be able to as well.

**Comment by bacongobbler** [comment]
Only builder :) the controller mounts the host's socket (we don't for the builder for isolation/security purposes

**Comment by carmstrong** [comment]
> the controller mounts the host's socket

But the client is what does the auth, no? So wouldn't controller itself still need the credentials? Consuming the socket is presumably the same as talking to an external daemon in terms of auth.

**Comment by bacongobbler** [comment]
Actually scratch that. I believe the docker client handles sending the auth credentials from dockercfg so it would need to be mounted into the controller as well.

**Comment by bacongobbler** [comment]
Ha, async issues :)

**Comment by bacongobbler** [comment]
@Crispy1975 if you're able to get this working, we'd be more than happy to document this workflow or accept PRs! :)

**Comment by bacongobbler** [comment]
Workflow v2 has support for GCS. Since we won't be doing any more features for v1, closing this as resolved!
