### ISSUE TITLE
[client] `deis auth:cancel --username=someuser` removes ~/.deis/client.json

### ISSUE THREAD

**Issue by olalonde** [deis/deis#4896]
When calling `deis auth:cancel --username=someuser` to remove a user different than the one which is currently logged in, the deis client removes `~/.deis/client.json`. This is only the expected behaviour when   removing the currently logged in user (e.g. without the --username argument).

**Comment by Joshua-Anderson** [comment]
:blush: Sorry, I think that was a typo on my part

I think it should be 
``` diff
++ if username == "" || c.Username == username {
-- if username != "" || c.Username == username {
```

I don't have the time to fix this right now (I'm super busy), but it looks like a easy fix.

**Comment by carmstrong** [comment]
@Joshua-Anderson I just found that too! I think that is indeed the fix: https://github.com/deis/deis/blob/6ec3e06702714f4529d4383e3ab063d062d927af/client/cmd/auth.go#L249-L254
