### ISSUE TITLE
rkt support

### ISSUE THREAD

**Issue by iyn** [deis/deis#4899]
Given that rkt just reached v1.0 ([blog post](https://coreos.com/blog/rkt-hits-1.0.html)), are there any plans to support it in Deis? I've seen https://github.com/deis/deis/issues/3818 but it's been over 6 months since that question, so maybe things are different. I've also looked at [the roadmap](http://docs.deis.io/en/latest/roadmap/roadmap/) and I'm aware that there's not rkt support on the list.

Given that rkt provides easy migration tools from Docker to rkt and it's possible to use Dockerfiles with it, how hard would it be to add rkt support to Deis? If one were to work on such thing, what are the important things to keep in mind?

Thank you for your time.

**Comment by bacongobbler** [comment]
Deis utilizes kubernetes under the hood for v2 which currently does not have full rkt support. In terms of how difficult it would be to support the two (Docker and rkt), here's a list of things I can come up with:

 - need an internal registry to store rkt ACIs from application builds
 - rkt support in kubernetes for deploying across the cluster (somewhat available but not out-of-the-box, and isn't ready for production)
 - rkt support in [deis/builder](https://github.com/deis/builder) for `git push deis master` to build a rkt ACI
 - `deis pull` support for rkt ACIs

The difficulty of pulling off such a feature would be very high, as it affects and touches nearly all points in Deis and would require intimate knowledge of the platform. I'm not trying to discourage such an idea, but it would be a lot of time.

Keep in mind that this is just the application workflow as well. If we wanted Deis to be deployable using rkt, we would then need to make the travis builds punch out ACIs and kubernetes manifest files, which would also mean either waiting for TravisCI to have rkt support or to use another CI provider in conjunction with Travis. We'd also need our new installer [helm](http://helm.sh/) to have knowledge about deploying a rkt implementation of Deis onto kubernetes.

Hope this helps :)

**Comment by iyn** [comment]
Thanks, @bacongobbler, this is very informative. Sadly, I don't have enough knowledge and experience with Deis to work on this, but will definitely keep this issue in mind while I learn more about the Deis & rkt.

**Comment by krancour** [comment]
To add to @bacongobbler's comments, I think this is worth exploring further, but strictly with respect to v2.  As kubernetes own support for rkt improves over time, perhaps there will be more we can do.  This repository and issue queue is mainly for Deis v1.x, and I think we can safely rule out rkt support every coming to v1.x, as we're mainly investing in bug fixes at the moment and divesting from feature development in favor of implementing new features in v2.
