### ISSUE TITLE
Cryptic Go error stacktrace when using some deis commands

### ISSUE THREAD

**Issue by olalonde** [deis/deis#4900]
UPDATE: figured out the problem, see [last comment](https://github.com/deis/deis/issues/4900#issuecomment-180090611)

``` bash
$ deis ps
panic: interface conversion: interface is nil, not []interface {}

goroutine 1 [running]:
github.com/deis/deis/client/controller/client.Client.LimitedRequest(0xc820015ce0, 0x0, 0xc82012c6a0, 0x4, 0x0, 0x0, 0x0, 0xc82012c6a7, 0x12, 0x0, ...)
        /Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/controller/client/http.go:82 +0x386
github.com/deis/deis/client/controller/models/ps.List(0xc8200e62c0, 0xc820014021, 0xb, 0x64, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
        /Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/controller/models/ps/ps.go:15 +0x1a7
github.com/deis/deis/client/cmd.PsList(0xc820014021, 0xb, 0x64, 0x0, 0x0)
        /Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/cmd/ps.go:26 +0xd0
github.com/deis/deis/client/parser.psList(0xc82000a230, 0x1, 0x1, 0x0, 0x0)
        /Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/parser/ps.go:67 +0x2d0
github.com/deis/deis/client/parser.Ps(0xc82000a230, 0x1, 0x1, 0x0, 0x0)
        /Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/parser/ps.go:34 +0x29f
main.Command(0xc82000a230, 0x1, 0x1, 0x188010)
        /Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/deis.go:85 +0x694
main.main()
        /Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/deis.go:18 +0x60
$ deis ps:scale web=0
Scaling processes... but first, coffee!
done in 0s
panic: interface conversion: interface is nil, not []interface {}

goroutine 1 [running]:
github.com/deis/deis/client/controller/client.Client.LimitedRequest(0xc820083b30, 0x0, 0xc8201623e0, 0x4, 0x0, 0x0, 0x0, 0xc8201623e7, 0x12, 0x0, ...)
        /Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/controller/client/http.go:82 +0x386
github.com/deis/deis/client/controller/models/ps.List(0xc820168000, 0xc82000a051, 0xb, 0x64, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/controller/models/ps/ps.go:15 +0x1a7
github.com/deis/deis/client/cmd.PsScale(0xc82000a051, 0xb, 0xc820164040, 0x1, 0x1, 0x0, 0x0)
        /Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/cmd/ps.go:76 +0x6e3
github.com/deis/deis/client/parser.psScale(0xc820082160, 0x2, 0x2, 0x0, 0x0)
        /Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/parser/ps.go:119 +0x2b0
github.com/deis/deis/client/parser.Ps(0xc820082160, 0x2, 0x2, 0x0, 0x0)
        /Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/parser/ps.go:26 +0x139
main.Command(0xc820082160, 0x2, 0x2, 0x188010)
        /Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/deis.go:85 +0x694
main.main()
        /Users/jenkins/workspace/build-deis-cli-installer-darwin/src/github.com/deis/deis/client/deis.go:18 +0x60
$ deis --version
1.12.2
```

**Comment by olalonde** [comment]
It seems the issue is related to the controller:

```
$ deis config:set TEST=1
Creating config... Error: unexpected end of JSON input
$ deis config:unset TEST=1
Removing config... Error: unexpected end of JSON input
```

**Comment by olalonde** [comment]
```
$ deis config
=== appname Config
```

Hmmm, all config gone... that's not good.

**Comment by olalonde** [comment]
All config is still in etcd, according to

```
for i in $(etcdctl ls --recursive /deis/config/appname); do etcdctl get $i; done
```

So I guess it's a problem with the controller but `fleetctl journal -f deis-controller` doesn't show anything unusual.

**Comment by olalonde** [comment]
Ohhhh, pin pointed the problem. Did deis change the way it detects which app commands apply to?

Everything works find when I explicitly add the `--app appname` argument to my commands. What happened is I just created a new app called `appname-test` but both app share the same repo. When I was switching the `deis` git remote, it seems the deis client didn't pick that up.

**Comment by olalonde** [comment]
Ah ok I figured the actual problem. I was using a different domain here `ssh://git@deis.domain.com:2222/appname.git` than the domain I used to login with deis. It looks like the deis client ignores the deis remote if the remote's domain doesn't match the domain in `~/.deis/client.json`.

**Comment by bacongobbler** [comment]
nice sleuthing @olalonde. We'll have to try and re-create the bug and see if we can fix up that panic. :)

**Comment by krancour** [comment]
@olalonde how did the domain in the remote come to be different from the domain that the controller is on?  iirc, the domain of the controller you're logged into is used by `deis create` in constructing the git remote for the app-- meaning there shouldn't be a mismatch.  Did you manually edit remotes?

**Comment by olalonde** [comment]
@krancour I changed my cluster's domain name but forgot to logout and login again with the deis client. Pretty much everything kept working which is why it took me a while to figure this out. I have a script in my repo which I use to remove/add the deis remote (`npm run deis:git:prod` and `npm run deis:git:test`) where I was using the new cluster domain name. What compounded to the confusion was that some deis commands seemed to be were working and others not. I'm not sure we can really classify this as a bug except maybe for that go panic.

**Comment by bacongobbler** [comment]
@krancour also note that remotes can be renamed, but they won't be utilized afterwards since we expect the `deis` remote (note the `-r` option flag):

```
><> deis help create
Creates a new application.

- if no <id> is provided, one will be generated automatically.

Usage: deis apps:create [<id>] [options]

Arguments:
  <id>
    a uniquely identifiable name for the application. No other app can already
    exist with this name.

Options:
  --no-remote
    do not create a 'deis' git remote.
  -b --buildpack BUILDPACK
    a buildpack url to use for this app
  -r --remote REMOTE
    name of remote to create. [default: deis]
```

That go panic should certainly be cleaned up, and is also likely an issue with the v2 client.

**Comment by Joshua-Anderson** [comment]
I checked this out in workflow and this no longer seems to be an issue. I've worked a lot of code in this area, so I'm not certain what fixed it. I'm going to leave this open for fixed in V1 though.
