### ISSUE TITLE
deis on kubernetes

### ISSUE THREAD

**Issue by geoHeil** [deis/deis#4901]
Hi,
I wanted to try kubernetes and deis and installed the great kube-cluster app. My small test cluster is up and running and I installed deis.
The installer completes with the following messages:

```
Deis PaaS install is completed ...
It can be accessed via http://deis.192.168.64.3.xip.io

Please read how to:
Deploy Applications - https://github.com/deis/workflow/blob/node1/docs/src/using-deis/deploying-an-application.md
To manage Applications - https://github.com/deis/workflow/blob/node1/docs/src/using-deis/managing-an-application.md
Using Deis PaaS - https://github.com/deis/workflow/tree/node1/docs/src/using-deis
```
But unfortunately NONE of the URLs works. Github results in a 404 and http://deis.192.168.64.3.xip.io results in a timeout.

**Comment by rimusz** [comment]
@geoHeil I have released the new kube-cluster v0.1.9 with the correct URLs to Deis documentation.
Accessing directly Deis router IP (in your case http://deis.192.168.64.3.xip.io) will not show anything as we do  to have any Deis UI yet. That url is used  to register and login a user to Deis and install/configure/etc your Apps.

**Comment by geoHeil** [comment]
Great Thank you. In case you are the maintainer for the homebrew cask formula for kube-cluster it would be great if you could upgrade it as well

**Comment by rimusz** [comment]
@geoHeil no, I do not maintain the homebrew cask formula for kube-cluster, maybe somebody just volunteered to do it by himself :)

**Comment by geoHeil** [comment]
:) I will try to update the cask

**Comment by rimusz** [comment]
It looks like it runs automatically to update casks :)

**Comment by geoHeil** [comment]
They have a cask repair script `cask-repair --pull origin --push geoheil kube-cluster` but I seem to lack permissions for a pull request there ;(
