### ISSUE TITLE
Deis database running multiple times resulting in havoc

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#4902]
Hi,

The first thing I noticed was that a new deployment wasn't properly picked up (a bugfix I did still happened). After closes examination (with fleetctl list-units) I saw that v207 and v208 were running concurrently (and apparantly the routers were hitting v207).
I manually cleared this up thinking it was my own fault because I stopped a git push halfway through (although I did that many times before), and then immedtialy did another one.

Then it happened again with v208 and v210 (deis releases at that point didn't even show a v210) and I started looking at the controller

~~~
[2016-02-08 17:13:26 +0000] [115] [INFO] Handling signal: hup
[2016-02-08 17:13:26 +0000] [115] [INFO] Hang up: Master
[2016-02-08 17:13:26 +0000] [583] [INFO] Booting worker with pid: 583
[2016-02-08 17:13:26 +0000] [584] [INFO] Booting worker with pid: 584
[2016-02-08 17:13:26 +0000] [585] [INFO] Booting worker with pid: 585
[2016-02-08 17:13:26 +0000] [586] [INFO] Booting worker with pid: 586
[2016-02-08 17:13:26 +0000] [587] [INFO] Booting worker with pid: 587
[2016-02-08 17:13:26 +0000] [588] [INFO] Booting worker with pid: 588
[2016-02-08 17:13:26 +0000] [589] [INFO] Booting worker with pid: 589
[2016-02-08 17:13:26 +0000] [592] [INFO] Booting worker with pid: 592
[2016-02-08 17:13:26 +0000] [590] [INFO] Booting worker with pid: 590
[2016-02-08 17:13:26 +0000] [593] [INFO] Booting worker with pid: 593
[2016-02-08 17:13:26 +0000] [594] [INFO] Booting worker with pid: 594
[2016-02-08 17:13:26 +0000] [595] [INFO] Booting worker with pid: 595
[2016-02-08 17:13:26 +0000] [596] [INFO] Booting worker with pid: 596
[2016-02-08 17:13:26 +0000] [591] [INFO] Booting worker with pid: 591
[2016-02-08 17:13:26 +0000] [563] [INFO] Worker exiting (pid: 563)
[2016-02-08 17:13:26 +0000] [564] [INFO] Worker exiting (pid: 564)
[2016-02-08 17:13:26 +0000] [599] [INFO] Booting worker with pid: 599
[2016-02-08 17:13:26 +0000] [597] [INFO] Booting worker with pid: 597
[2016-02-08 17:13:26 +0000] [598] [INFO] Booting worker with pid: 598
[2016-02-08 17:13:26 +0000] [565] [INFO] Worker exiting (pid: 565)
~~~

was printed many times over.

So suddenly especially because deis releases wasn't consistent I realized I must have had 2 databases running and they would constantly fight over the controllers attention which then would give very unreliable pushes.

I stopped the oldest database (with docker stop), and suddenly my problems went away.

I believe this happened a few days ago when one of my nodes (the one with the oldest database) had connectivity problems for a few minutes. Apparanttly long enough to reschedule the database to another node, but not long enough to kill the database on this node once it came back online..

This is mostly written as referecence to other people using deis v1.12.2 which might have the same problem, as I understand this might not be easy to fix for the LTS release (although it is a critical problem).

**Comment by nathansamson** [comment]
This happened to me today. 2 Running database nodes.

fleetctl list-units was only displaying the latest one.


Extract of The docker logs of the original one are pasted

~~~
        STRUCTURED: time=2016-02-09T03:54:25.827887-00 pid=17308 action=push-wal key=s3://db_wal/wal_005/0000000500000088000000A5.lzo prefix= rate=2976.74 seg=0000000500000088000000A5 state=complete
Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "wal-push".
        STRUCTURED: time=2016-02-09T03:59:26.341428-00 pid=17657
wal_e.worker.upload INFO     MSG: begin archiving a file
        DETAIL: Uploading "pg_xlog/0000000500000088000000A6" to "s3://db_wal/wal_005/0000000500000088000000A6.lzo".
        STRUCTURED: time=2016-02-09T03:59:26.378798-00 pid=17657 action=push-wal key=s3://db_wal/wal_005/0000000500000088000000A6.lzo prefix= seg=0000000500000088000000A6 state=begin
wal_e.worker.upload INFO     MSG: completed archiving to a file
        DETAIL: Archiving to "s3://db_wal/wal_005/0000000500000088000000A6.lzo" complete at 107.716KiB/s.
        STRUCTURED: time=2016-02-09T03:59:27.572210-00 pid=17657 action=push-wal key=s3://db_wal/wal_005/0000000500000088000000A6.lzo prefix= rate=107.716 seg=0000000500000088000000A6 state=complete
Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "wal-push".
        STRUCTURED: time=2016-02-09T04:03:38.146054-00 pid=17912
wal_e.worker.upload INFO     MSG: begin archiving a file
        DETAIL: Uploading "pg_xlog/0000000500000088000000A7.00000028.backup" to "s3://db_wal/wal_005/0000000500000088000000A7.00000028.backup.lzo".
        STRUCTURED: time=2016-02-09T04:03:38.187771-00 pid=17912 action=push-wal key=s3://db_wal/wal_005/0000000500000088000000A7.00000028.backup.lzo prefix= seg=0000000500000088000000A7.00000028.backup state=begin
~~~

4:03 is indeed the moment the other database container started.
So definitly a problem of having a split brain which is quite critical...

**Comment by nathansamson** [comment]
http://pastebin.com/ZzCw62Ew fleet journal on affected host

**Comment by nathansamson** [comment]
So the stopping of the database was actually triggered but the container kept running...

~~~
Feb 09 04:03:34 ams3-cloud-beeple-2 fleetd[764]: INFO manager.go:138: Triggered systemd unit deis-database.service stop: job=48129697
Feb 09 04:03:34 ams3-cloud-beeple-2 fleetd[764]: INFO manager.go:259: Removing systemd unit deis-database.service
~~~

**Comment by nathansamson** [comment]
Intrestingly sytemd  claims to have stopped the container, although obviously it kept running

~~~
Feb 09 04:01:13 ams3-cloud-beeple-2 sh[15868]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Feb 09 04:01:26 ams3-cloud-beeple-2 sh[15868]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Feb 09 04:01:48 ams3-cloud-beeple-2 sh[15868]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Feb 09 04:02:00 ams3-cloud-beeple-2 sh[15868]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Feb 09 04:02:23 ams3-cloud-beeple-2 sh[15868]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Feb 09 04:02:35 ams3-cloud-beeple-2 sh[15868]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Feb 09 04:03:34 ams3-cloud-beeple-2 systemd[1]: Stopping deis-database...
Feb 09 04:03:35 ams3-cloud-beeple-2 docker[28700]: wal_e.main   INFO     MSG: starting WAL-E
Feb 09 04:03:35 ams3-cloud-beeple-2 docker[28700]: DETAIL: The subcommand is "backup-push".
Feb 09 04:03:35 ams3-cloud-beeple-2 docker[28700]: STRUCTURED: time=2016-02-09T04:03:35.490526-00 pid=17878
Feb 09 04:03:35 ams3-cloud-beeple-2 docker[28700]: wal_e.operator.backup INFO     MSG: start upload postgres version metadata
Feb 09 04:03:35 ams3-cloud-beeple-2 docker[28700]: DETAIL: Uploading to s3://db_wal/basebackups_005/base_0000000500000088000000A7_00000040/extended_version.txt.
Feb 09 04:03:35 ams3-cloud-beeple-2 docker[28700]: STRUCTURED: time=2016-02-09T04:03:35.701619-00 pid=17878
Feb 09 04:03:36 ams3-cloud-beeple-2 docker[28700]: wal_e.operator.backup INFO     MSG: postgres version metadata upload complete
Feb 09 04:03:36 ams3-cloud-beeple-2 docker[28700]: STRUCTURED: time=2016-02-09T04:03:36.348843-00 pid=17878
Feb 09 04:03:36 ams3-cloud-beeple-2 docker[28700]: wal_e.worker.upload INFO     MSG: beginning volume compression
Feb 09 04:03:36 ams3-cloud-beeple-2 docker[28700]: DETAIL: Building volume 0.
Feb 09 04:03:36 ams3-cloud-beeple-2 docker[28700]: STRUCTURED: time=2016-02-09T04:03:36.522838-00 pid=17878
Feb 09 04:03:37 ams3-cloud-beeple-2 docker[28700]: wal_e.worker.upload INFO     MSG: begin uploading a base backup volume
Feb 09 04:03:37 ams3-cloud-beeple-2 docker[28700]: DETAIL: Uploading to "s3://db_wal/basebackups_005/base_0000000500000088000000A7_00000040/tar_partitions/part_00000000.tar.lzo".
Feb 09 04:03:37 ams3-cloud-beeple-2 docker[28700]: STRUCTURED: time=2016-02-09T04:03:37.455829-00 pid=17878
Feb 09 04:03:37 ams3-cloud-beeple-2 docker[28700]: wal_e.worker.upload INFO     MSG: finish uploading a base backup volume
Feb 09 04:03:37 ams3-cloud-beeple-2 docker[28700]: DETAIL: Uploading to "s3://db_wal/basebackups_005/base_0000000500000088000000A7_00000040/tar_partitions/part_00000000.tar.lzo" complete at 13598.3KiB/s.
Feb 09 04:03:37 ams3-cloud-beeple-2 docker[28700]: STRUCTURED: time=2016-02-09T04:03:37.813267-00 pid=17878
Feb 09 04:03:38 ams3-cloud-beeple-2 sh[15868]: wal_e.main   INFO     MSG: starting WAL-E
Feb 09 04:03:38 ams3-cloud-beeple-2 sh[15868]: DETAIL: The subcommand is "wal-push".
Feb 09 04:03:38 ams3-cloud-beeple-2 sh[15868]: STRUCTURED: time=2016-02-09T04:03:38.146054-00 pid=17912
Feb 09 04:03:38 ams3-cloud-beeple-2 sh[15868]: wal_e.worker.upload INFO     MSG: begin archiving a file
Feb 09 04:03:38 ams3-cloud-beeple-2 sh[15868]: DETAIL: Uploading "pg_xlog/0000000500000088000000A7.00000028.backup" to "s3://db_wal/wal_005/0000000500000088000000A7.00000028.backup.lzo".
Feb 09 04:03:38 ams3-cloud-beeple-2 sh[15868]: STRUCTURED: time=2016-02-09T04:03:38.187771-00 pid=17912 action=push-wal key=s3://db_wal/wal_005/0000000500000088000000A7.00000028.backup.lzo prefix= seg=0000000500
Feb 09 04:03:38 ams3-cloud-beeple-2 sh[15868]: wal_e.worker.upload INFO     MSG: begin archiving a file
Feb 09 04:03:38 ams3-cloud-beeple-2 sh[15868]: DETAIL: Uploading "pg_xlog/0000000500000088000000A7" to "s3://db_wal/wal_005/0000000500000088000000A7.lzo".
Feb 09 04:03:38 ams3-cloud-beeple-2 sh[15868]: STRUCTURED: time=2016-02-09T04:03:38.357933-00 pid=17912 action=push-wal key=s3://db_wal/wal_005/0000000500000088000000A7.lzo prefix= seg=0000000500000088000000A7 s
Feb 09 04:03:38 ams3-cloud-beeple-2 sh[15868]: wal_e.worker.upload INFO     MSG: completed archiving to a file
Feb 09 04:03:38 ams3-cloud-beeple-2 sh[15868]: DETAIL: Archiving to "s3://db_wal/wal_005/0000000500000088000000A7.lzo" complete at 668.22KiB/s.
Feb 09 04:03:38 ams3-cloud-beeple-2 sh[15868]: STRUCTURED: time=2016-02-09T04:03:38.870773-00 pid=17912 action=push-wal key=s3://db_wal/wal_005/0000000500000088000000A7.lzo prefix= rate=668.22 seg=00000005000000
Feb 09 04:03:38 ams3-cloud-beeple-2 sh[15868]: wal_e.worker.upload INFO     MSG: completed archiving to a file
Feb 09 04:03:38 ams3-cloud-beeple-2 sh[15868]: DETAIL: Archiving to "s3://db_wal/wal_005/0000000500000088000000A7.00000028.backup.lzo" complete at 00KiB/s.
Feb 09 04:03:38 ams3-cloud-beeple-2 sh[15868]: STRUCTURED: time=2016-02-09T04:03:38.872138-00 pid=17912 action=push-wal key=s3://db_wal/wal_005/0000000500000088000000A7.00000028.backup.lzo prefix= rate=00 seg=00
Feb 09 04:03:39 ams3-cloud-beeple-2 docker[28700]: NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
Feb 09 04:03:40 ams3-cloud-beeple-2 systemd[1]: Stopped deis-database.service.
~~~

**Comment by nathansamson** [comment]
Docker logs as well, nothing really weird here except some broken pipes + the database container ID  (2369a743a248) is not listed

http://pastebin.com/ZUEBXubR

**Comment by nathansamson** [comment]
Because the frequence it apparantly can happen, and a relatively simple trigger (network issues on one node) I am flagging this for #4776 @mboersma ?

**Comment by bacongobbler** [comment]
So to summarize this bug, it looks the components acted the way they should: the fleet node came down, re-jiggered the components and everything came back up. However deis-database was instructed to be stopped yet never did, therefore two databases started. To me that sounds like either a bug upstream with fleet not managing cluster state properly or the network split caused a new database to start on a different node once the cluster noticed that the other node was "gone", then when it re-joined it still had its old jobs but never removed from fleet. In either case it's a bug upstream, I'd think.

@nathansamson does that sound right to you?

**Comment by nathansamson** [comment]
I don't think that's entirely correct.

"therefore two databases started." One new started, one was kept running (but maybe that's what you mean)

"then when it re-joined it still had its old jobs but never removed from fleet." Fleet seems to instruct the shutdown. This can be seen in the logs. It just does not properly do so as far as I can tell...

see the "Feb 09 04:03:34 ams3-cloud-beeple-2 systemd[1]: Stopping deis-database..." So it just seems that docker did actually not properly stop the database. (by the time I looked it was up for 16 hours, while 04 was only 5-6 hours ago at that  time).

**Comment by bacongobbler** [comment]
Sorry, that's what I meant to say. :)

**Comment by nathansamson** [comment]
As I see it fleet did its job.

The failure is in either docker or the unit file of the database

**Comment by carmstrong** [comment]
> or the unit file of the database

I'd tend to agree - I think this is at least worth investigating a fix for to ensure we only ever have one database active. @nathansamson if you can help us to understand repro steps, that would be useful.

**Comment by nathansamson** [comment]
At this moment my prevention steps are praying it doesn't happen anymore. Which seems fairly succesful ;)

Note that due to an earlier bug in the setup process, fleet traffic is going over the public internet in my cluster.

~~~
^Ccore@ams3-cloud-beeple-2 ~ $ fleetctl list-machines
MACHINE		IP		METADATA
03ee7055...	188.166.*	controlPlane=true,dataPlane=true,routerMesh=true
421f15df...	188.166.*	controlPlane=true,dataPlane=true,routerMesh=true
467bad7d...	178.62.*	controlPlane=true,dataPlane=true,routerMesh=true
664452fd...	178.62.*	controlPlane=true,dataPlane=true,routerMesh=true
feae31b0...	188.166.*	controlPlane=true,dataPlane=true,routerMesh=true
core@ams3-cloud-beeple-2 ~ $ 
~~~
(obfuscated IPs out of paranoia)

Reproduction steps are probably overloading the network traffic of the node with deis-database on so that fleet stops functioning. (plugging a physical and/or virtual cable in a virtualized environment probably does the trick as well).

**Comment by bacongobbler** [comment]
It’s possible docker didn’t respond to a stop/kill of the container. We've previously added a bunch of ExecStopPost’s into the units after which we stopped seeing this, but if docker doesn’t respect the signal to kill the container, then there's not too much we can do on our end.

Another alternative solution could be to [increase the engine reconciliation interval and the etcd request timeout](https://github.com/coreos/fleet/issues/1289#issuecomment-146423617) so fleet is a little more resilient against etcd network splits, but there are latency tradeoffs in fleet reconciliation with that setup and it doesn't fix the root issue; just sidesteps it.

**Comment by nathansamson** [comment]
But why would that happen twice in such a short amount of time (few days). In one cluster (but different nodes)?

And why only with the database container?

And why wasn't this reported earlier by someone else, because someone must have noticed that before?

**Comment by bacongobbler** [comment]
> But why would that happen twice in such a short amount of time (few days). In one cluster (but different nodes)?

etcd by default has a really low default request timeout value, so any small blip in network latency can cause this.

> And why only with the database container?

The database has a more complex [shutdown sequence](https://github.com/deis/deis/blob/master/deisctl/units/deis-database.service#L12-L14). We'd have to look into it further rather than just post theories about the problem to answer that. :P

**Comment by carmstrong** [comment]
> We've previously added a bunch of ExecStopPost’s into the units after which we stopped seeing this

Note that we're currently only stopping the container, not killing/rming it: https://github.com/deis/deis/blob/7356d26adeb2f48d8df82a1d0baa090da7d4bb20/deisctl/units/deis-database.service#L14

**Comment by bacongobbler** [comment]
This is also another issue that is resolved in deis v2 thanks to kubernetes Replication Controllers. Woop

**Comment by bacongobbler** [comment]
since [v2.0.0 is now GA](https://deis.com/blog/2016/workflow-stable/) and this has been resolved thanks to kubernetes's notion of replication controllers, I am closing this. Thanks for the report!
