### ISSUE TITLE
Update all components to use the same version of Alpine Linux

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#4904]
Our components are using a combination of Alpine Linux versions. We should consider getting everything on the same version for consistency and so we fully understand our exposure for vulnerabilities.

The components are the following versions:

3.1
- database
- registry

3.2 
- builder
- controller
- logger
- logspout
- publisher
- router
- mock-store
- test-etcd

Note that Alpine 3.3 is the latest release, so we could upgrade everything to 3.3 as well.

**Comment by mboersma** [comment]
Updating database from alpine:3.1 means upgrading PostgreSQL to a new version (unless we build from source rather than use `apk`). When I tried this before, that meant the DB won't start up as it expects data files to live in a different directory. So this may require writing a migration script.

**Comment by mboersma** [comment]
deis-registry also fails to build in `alpine:3.2`. Don't remember why know, but I tried it months ago and gave up in the face of build errors.

**Comment by carmstrong** [comment]
Thanks @mboersma. This definitely isn't crucial, and may not be worth the work involved.
