### ISSUE TITLE
Performance comparison: bare metal vs VM

### ISSUE THREAD

**Issue by BattleBrisket** [deis/deis#4905]
Does the team have any insight or recommendations as regards to . We are moving ahead with Deis, and are fortunate enough to have both cloud VM's and bare metal hosting options available.

We of course understand the performance hit you take when utilizing any virtual layer, but does that penalty warrant consideration where Deis is concerned? For the purposes of this conversation, assume a "vanilla" Deis setup, for application(s) with moderate load.

**Comment by gerred** [comment]
Hi @BattleBrisket,

As far as Deis itself is concerned, there's no impact beyond the overhead of running applications inside of containers.

There's some good knowledge [here](http://stackoverflow.com/questions/21889053/what-is-the-runtime-performance-cost-of-a-docker-container) regarding performance of containers on bare metal vs. VMs, as that will be the primary performance difference you're going to find. The container overhead on top of this is minimal.

**Comment by BattleBrisket** [comment]
Thanks for the info, @gerred!  I'd still like to hear directly from a team member/collaborator, should they have any additional information to add.

And how did you close my issue, anyway?

**Comment by bacongobbler** [comment]
@BattleBrisket @gerred is a team member. Github allows us to change the titles. As such he has permission to close issues.

**Comment by BattleBrisket** [comment]
Thanks for the clarification. My apologies, @gerred, the usual GitHub title on the author line seems to be absent.
