### ISSUE TITLE
Use the cluster url as an app url

### ISSUE THREAD

**Issue by jamescw** [deis/deis#4906]
Hi,
I have a need to use a subdomain as the cluster url and also have that url serve a default app...

For example, url `project.example.com` will point to the cluster and I can also set up wildcard record for `*.project.example.com` to also point to the cluster. I can not create the record `*.example.com` due to company policy. I also have the need to serve an application at the cluster root url (`project.example.com`) and may have other apps serving on subdomains off this (`anotherapp.project.example.com`).

Is this possible in deis?

**Comment by bacongobbler** [comment]
Yes, this is possible. For the first bit:

```
deisctl config platform set domain=project.example.com
```

All apps will now be displayed as running on `*.project.example.com`, including deis, which will be accessible at `deis.project.example.com`. You'll need to set up DNS as described [here](http://docs.deis.io/en/latest/managing_deis/configure-dns/#necessary-dns-records) for the platform domain, changing `*.myapps.com` to `*.project.example.com`.

As for the specific app, you can just use a one-off domain via `deis domains:add project.example.com`.

Hope this helps!

**Comment by jamescw** [comment]
brilliant thanks!
