### ISSUE TITLE
persistant storage 2

### ISSUE THREAD

**Issue by spinus** [deis/deis#4907]
according to https://github.com/deis/deis/issues/1310 persistant storage is not a feature in deis but now when some time passed by and deis has ceph cluster built in and docker can mount (https://ceph.com/planet/getting-started-with-the-docker-rbd-volume-plugin/) ceph, do you plan to add volumes management for apps?

**Comment by bacongobbler** [comment]
I believe attaching block storage to applications would be targeted in similar fashion to #231. We'd need to tackle the UX and develop that feature first before we go into developing a RDB or SSHFS addon for applications.

That being said, this isn't something we will be able to tackle in Deis v1. With Deis v2 Ceph is going away so there will not be a ceph cluster out of the box, so I'm not sure.

**Comment by spinus** [comment]
oh ok I see, didn't know that ceph was abandoned in v2. I also know that kubernetes supports ceph storage, so maybe worth to keep it?

**Comment by carmstrong** [comment]
> so maybe worth to keep it

The larger question is that exposing storage to individual applications would arguably be a leaky abstraction. One of the main tenets of 12-factor applications is that they don't store state locally. Can you elaborate on your use case?

**Comment by spinus** [comment]
Sure, big fan of simplicity and functional approach in general, but I need to deploy some 3rd party apps as well. Let's say most of internal apps are cool 12-factor, but wordpress is not, even if I keep database outside of the cluster, on rds for example, there still is a problem.

So in other words, I would like to manage some "legacy" apps as well.

**Comment by bacongobbler** [comment]
@spinus I think the best answer is if you want to store state in your application, you'll want to upload it to S3, similar to how Heroku handles persistent state. Wordpress, Drupal et al. have plugins to replace their local filesystem with S3, and is considered best practice for handling static assets.

In the future, we can add a plugin gateway to provide a similar feature with #231, but for now I'm closing this as resolved. Please feel free to re-open if you have any more questions about this and we'd be more than happy to answer :)

**Comment by spinus** [comment]
@bacongobbler interesting, thanks for explaining this.

**Comment by cies** [comment]
I'm also interested in this feature. Besides #231 there is also a relevant discussion for this topic in https://github.com/deis/controller/issues/450
