### ISSUE TITLE
Running DEIS in a standalone network

### ISSUE THREAD

**Issue by udragon** [deis/deis#4908]
Many organizations runs a standalone network outside the internet, or connected behind firewalls etc. DEIS gets many things from outside the system (docker registry, installation in build-packs, github ...), so it isn't possible to deploy in such places. is there any way to install DEIS in a "standalone mode"? is that something you consider?

Thanks

**Comment by bacongobbler** [comment]
After installing deis, everything except for the build process can be run in a standalone network. You can use `deis pull` to fetch images from a registry within your network. You can also reference images stored inside your internal network in your Dockerfile, so essentially the only workflow that *won't* work in an isolated environment is buildpacks.

Makes sense?

**Comment by bacongobbler** [comment]
Then again, you can also use `deis config:set BUILDPACK_URL=git://myinternalgithost.com/mybuildpack` in a firewall environment so installing deis internally is technically possible.

**Comment by krancour** [comment]
Although this raises the question of how Deis components themselves get installed on such a network.  Public registries such as Docker Hub and quay.io are the only available distribution mechanisms.  "Deis on a stick," for instance, is not currently possible.

**Comment by aespinosa** [comment]
an organization can deploy a registry proxy and configure all the docker daemons to go to that proxy for fetching images from public registries.

**Comment by krancour** [comment]
@aespinosa I was interpreting it as a case where there was a prohibition against use of any public registry (proxied or otherwise).  I probably read into that too much.

**Comment by bacongobbler** [comment]
ping @udragon. Did the following comments answer your question?

**Comment by udragon** [comment]
Yes, thank you. You may close the issue.
