### ISSUE TITLE
[controller] When deleting a user, its apps are deleted from the database but keep running

### ISSUE THREAD

**Issue by olalonde** [deis/deis#4909]
When deleting a user, all the apps it owns are deleted from the controller's database. However, the apps (fleet services and docker containers) keep running. Afterwards, when re-creating an app with the same name as one of the apps that was deleted, `deis logs` will show the logs of the deleted app of the same name.

To reproduce:

- deis register http://controller.com
- deis create someapp
- deis auth:cancel
- deis login (with another admin user)

Notice that `deis apps` doesn't list the app that was deleted (`someapp`) but `fleetctl list-units | grep someapp` show that the app is still running and `http://someapp.controller.com` is still up.

deis v1.12.2

**Comment by helgi** [comment]
https://github.com/deis/workflow/pull/391 fixes the same but in v2, takes the approach of denying the `auth:cancel` if the user has applications assigned.

It should be straightforward to backport

**Comment by olalonde** [comment]
:+1:
