### ISSUE TITLE
Deploy an existing app when upgrading

### ISSUE THREAD

**Issue by omykuji** [deis/deis#4910]
I'm testing Deis migration upgrade, this upgrade method provisions a new cluster running in parallel to the old one.
If both clusters share the same S3 external storage and database, how can I deploy existing applications in the new cluster without a "git push"?

**Comment by aledbf** [comment]
> If both clusters share the same S3 external storage and database, how can I deploy existing applications in the new cluster without a "git push"?

Running `deis scale <type>=0 -a <app> && deis scale <type>=1 -a <app>` in the new cluster.

**Comment by omykuji** [comment]
It works. Thanks!
