### ISSUE TITLE
Unable to install deis to newly configured Azure cluster

### ISSUE THREAD

**Issue by n1rvana** [deis/deis#4914]
Notes:
-- Previously had installed a vagrant cluster on my machine
-- Custer creation went fine via the contrib/azure scripts and instructions in deis docs
-- Setup wildcard domain, and DEISCTL_TUNNEL to node0
-- Able to successfully ssh into node0 without problem
-- Deisctl seems to be looking locally for some reason:
```
🌀  deisctl machines
INFO client.go:298: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:214: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 100ms
```

Can't set the private key (though default key is one configured in parameters.son):

```
🌀    deisctl config platform set sshPrivateKey=~/.ssh/id_rsa
Error: 502:  (unhandled http status [Service Unavailable] with body [{"message":"proxy: zero endpoints currently available"}]) [0]
```

Or the domain:
```
deisctl config platform set domain=factom.nirvana.io
Error: 502:  (unhandled http status [Service Unavailable] with body [{"message":"proxy: zero endpoints currently available"}]) [0]
```

deisctl list doesn't work:
```
deisctl list
INFO client.go:298: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
ERROR client.go:214: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 100ms
INFO client.go:298: Response 503 Service Unavailable from http://127.0.0.1:4001/ unusable
```

DEISCTL_TUNNEL is set: (xxx for machine modesty)
```
export
declare -x DEISCTL_TUNNEL="xxx.xxx.xxx.4"
```

deis and deisctl are the same version:
```

🌀  deisctl install platform
Error: Missing platform domain, use:
deisctl config platform set domain=<your-domain>
🌀  deisctl --version
1.12.3
🌀  git status
HEAD detached at v1.12.3
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   arm-template.json
	modified:   parameters.json

no changes added to commit (use "git add" and/or "git commit -a")
🌀  
```

I'm sure it's something stupid and obvious.  Basically I installed the cluster on azure, that went ok, machines running and the like, I set up DNS, seemed to go ok, updated to latest deisctl, and then got nowhere on the "install deis platform" instructions here: http://docs.deis.io/en/latest/installing_deis/install-platform/#install-deis-platform

It sure seems to be trying to connect to my local machine rather than a remote one-- is there some context saved somewhere?  I'm running all this from the contrib/azure directory... shouldn't it look to DEISCTL_TUNNEL for where to connect (instead of 127.0.0.1:4001)??

**Comment by bacongobbler** [comment]
from all the errors, it sounds like etcd on the host you're targeting is down. `deisctl` runs inside a SSH tunnel when you set DEISCTL_TUNNEL so from its perspective the logs are showing that it's attempting to connect to fleet from localhost. I'd SSH into your azure host and figure out why your etcd cluster is unhealthy and post logs here :)

**Comment by mattk42** [comment]
Did you forget to generate a new discovery-url before provisioning your new cluster? If not, etcd may not have come up correctly and that could be causing your issues.

**Comment by n1rvana** [comment]
I did generate a new discovery URL and put it in the config using:

```
./create-azure-user-data $(curl -s https://discovery.etcd.io/new)
```

Hmm... rebooted the cluster and it appears etcd is not in good shape:
```
$ etcdctl cluster-health
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured
error #0: client: etcd member http://127.0.0.1:2379 has no leader
error #1: client: etcd member http://127.0.0.1:4001 has no leader

```

I don't know why etcd is not correctly configured.  I'm going to blow away the whole resource group and try again from scratch.

**Comment by n1rvana** [comment]
I did make some changes to arm-template.json-- which I would assume be ok, as these are variables, but maybe other values are hardcoded elsewhere.

The changes were
```
   "vmNamePrefix": "miklosNode",
    "virtualNetworkName": "miklosvNet",
    "availabilitySetName": "miklosAvailabilitySet",
```

If this deployment fails the same way I'm going to revert those changes and try again.

**Comment by n1rvana** [comment]
On second deployment, it seems the etcd cluster is healthy:

```
core@miklosNode0 ~ $ etcdctl cluster-health
member 65ca48d7093ae2d is healthy: got healthy result from http://10.0.0.7:2379
member 64391d5124428671 is healthy: got healthy result from http://10.0.0.6:2379
member cfe49a936c546325 is healthy: got healthy result from http://10.0.0.8:2379
cluster is healthy
core@miklosNode0 ~ $ 
```

Appears this was just a broken deployment for some reason (silent failure on Microsoft's fault.) 

The redeployment has worked well enough to me to get thru deisctl install platform.

Closing.

Thanks!
