### ISSUE TITLE
Best way to support multiple versions of the same app. (eg: DEV, QA, PROD)

### ISSUE THREAD

**Issue by n1rvana** [deis/deis#4915]
Have a Deis cluster, and want to configure/release apps for different purposes. I believe I can use .env to set parameters that the app uses (eg: which database it talks to and which versions of other services)... but is there a good way to switch between them?  Is there a way to have three versions of app foo running?

eg: git push deis prod for prod, git push deis qa for qa (and have them pick up the appropriate environment?)

These are go apps so they live in the go path source directory (otherwise I could just have three copies of the git repo with different ENVs)

What's the best practice for this?

Yes, I know prod should probably be its own cluster and it will eventually but we will at least still need DEV and QA.

**Comment by bacongobbler** [comment]
It's all through git remotes, so you can do it the following way:

```
$ deis create appname-prod -r prod
$ deis create appname-dev -r dev
$ deis create appname-qa -r qa
```

Then, once that's done you can use `deis apps:info -a appname-dev` to explicitly to state that you want to run this command against the dev version and `git push dev master` to push changes to the `dev` application.

Hope this helps!

**Comment by n1rvana** [comment]
Ah, and I can set different configs for each app.  Got it, thanks!
