### ISSUE TITLE
Docs: document `ceph mon remove` in removing hosts

### ISSUE THREAD

**Issue by rstacruz** [deis/deis#4916]
In the documentation http://docs.deis.io/en/latest/managing_deis/add_remove_host/, it seems to be missing the step:

```
ceph mon remove ip-10-20-30-40.us-west-1.compute.internal
```

http://docs.ceph.com/docs/master/rados/deployment/ceph-deploy-mon/

Am I right that this is needed? I can do a PR if needed.

**Comment by rstacruz** [comment]
BTW, I ended up here because AWS EC2 automatically changed the IP of one of my cluster nodes, leading to `deis-store-monitor` to being down in one host.

I had to find out what was the old IP and flush it out of Ceph first.

```sh
ssh core@$NODE0
fleetctl list-machines
# find out the active machines, identified that 10.21.1.221 is the stale IP

# remove from ceph OSD
etcdctl get /deis/store/osds/10.21.1.221 #=> 0
nse deis-store-admin
... ceph osd out 0
... ceph osd crush remove osd.0
... ceph auth del osd.0
... ceph osd rm 0

# remove from deis config
etcdctl rm /deis/store/osds/10.21.1.221
etcdctl rm /deis/store/hosts/10.21.1.221
```

This still led to `HEALTH_WARN` in `ceph -s`, then I did `ceph mon remove`:

```sh
$ ceph -s
     health HEALTH_WARN
$ ceph mon stat
  e4: 4 mons at ...
$ ceph mon remove ip-10-21-1-221.ap-southeast-2.compute.internal
$ ceph mon stat
  e5: 3 mons at ...
$ ceph -s
     health HEALTH_OK
```

and everything was fine then.

**Comment by carmstrong** [comment]
> Am I right that this is needed?

It is indeed, and is mentioned here: http://docs.deis.io/en/latest/managing_deis/add_remove_host/#removing-a-monitor
