### ISSUE TITLE
How do we enable graceful-etcd-shutdown?

### ISSUE THREAD

**Issue by rstacruz** [deis/deis#4918]
The docs say:

> The contrib/user-data.example provides 2 units, graceful-etcd-shutdown.service and graceful-ceph-shutdown.service, that contain some experimental logic to clean-up a Deis node’s cluster membership before reboot, shutdown or halt events. The units can be used independently or together.

>    root@deis-1:/# systemctl enable graceful-etcd-shutdown
>     root@deis-1:/# systemctl start graceful-etcd-shutdown

But I get:

```
$ sudo systemctl enable graceful-etcd-shutdown
Failed to execute operation: No such file or directory
```

I provisioned my cluster using `provision-aws-cluster.sh`.

**Comment by carmstrong** [comment]
This was only merged in #4554 18 days ago, so it's only provisioned on hosts that were launched as of Deis v1.12.3.

**Comment by rstacruz** [comment]
Ahh. Can I fit it into my 1.12.2 provisioned hosts somehow?

**Comment by bacongobbler** [comment]
@rstacruz you can re-provision your hosts from master, then manually set the platform version to v1.12.2 but be warned that we don't "officially" test that scenario.

**Comment by bacongobbler** [comment]
Considering that @carmstrong answered your question, I'm going to go ahead and close this issue, but please re-open if you need help getting that working. Thanks! :)
