### ISSUE TITLE
Problem bringing up stateless platform

### ISSUE THREAD

**Issue by glenwong** [deis/deis#4928]
I followed the instructions in the cephless doc but when I try to bring up the platform with "deisctl start stateless-platform" it gets stuck on the deis-builder activating/start-post state. When I log the builder service it shows:

Feb 20 23:34:25 ip-....us-west-2.compute.internal sh[10607]: [info] Re-trying template build. (Elapsed time: 856)
Feb 20 23:34:25 ip-....us-west-2.compute.internal sh[10607]: [debug] Recoverable error: exit status 1
Feb 20 23:34:25 ip-....us-west-2.compute.internal sh[10607]: [debug] Output: "2016-02-20T23:34:25Z 61389ab79c22 confd[1363]: ERROR template: builder:59:14: executing \"builder\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2016-02-20T23:34:25Z 61389ab79c22 confd[1363]: ERROR template: check-repos:14:20: executing \"check-repos\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2016-02-20T23:34:25Z 61389ab79c22 confd[1363]: ERROR template: push-images:9:37: executing \"push-images\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2016-02-20T23:34:25Z 61389ab79c22 confd[1363]: ERROR template: receiver:15:55: executing \"receiver\" at <getv \"/deis/controll...>: error calling getv: key does not exist\n"

**Comment by Blystad** [comment]
Try:
```
deisctl config store set gateway/dummy=1
```

and see if that helps.

Might be related to #4912

**Comment by bacongobbler** [comment]
ping @glenwong. Did the suggestion @Blystad made work for you?

**Comment by rpanachi** [comment]
I'm getting the same error on deis v1.12.3

@Blystad @bacongobbler I tried to set this `gatewat/dymmy=1` but the error persist

Here the log of `deis-builder` trapped on `activating/start-post` state:

```
sh[12199]: [info] Re-trying template build. (Elapsed time: 36)
sh[12199]: [debug] Recoverable error: exit status 1
sh[12199]: [debug] Output: "2016-03-02T17:45:27Z 8ae2d0259f64 confd[135]: ERROR template: builder:59:14: executing \"builder\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2016-03-02T17:45:27Z 8ae2d0259f64 confd[135]: ERROR template: check-repos:14:20: executing \"check-repos\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2016-03-02T17:45:27Z 8ae2d0259f64 confd[135]: ERROR template: push-images:9:37: executing \"push-images\" at <getv \"/deis/registry...>: error calling getv: key does not exist\n2016-03-02T17:45:27Z 8ae2d0259f64 confd[135]: ERROR template: receiver:15:55: executing \"receiver\" at <getv \"/deis/controll...>: error calling getv: key does not exist\n"
```

Any ideia?
