### ISSUE TITLE
Dockerfile based apps not working for me

### ISSUE THREAD

**Issue by n1rvana** [deis/deis#4932]
I tested out the method with the hello world example from the deis docs.  That worked, but then I try to do my own and it uses the heroku build pack method.

This app is a go app, but because of the way our build system works we can't use GoDeps (due to a bug in GoDeps).  So I'm trying to use the docker file method.

Despite the presence of a Docker File it's trying to use heroku build packs:

```

🌀  deis create monitor-config
Creating Application... done, created monitor-config
Git remote deis added
remote available at ssh://git@deis.foo.example.com:2222/monitor-config.git
🌀  git push deis master
ssh: connect to host deis.foo.example.com port 2222: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
🌀  git push deis master
Counting objects: 220, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (183/183), done.
Writing objects: 100% (220/220), 121.90 KiB | 0 bytes/s, done.
Total 220 (delta 80), reused 3 (delta 0)
-----> Go app detected
 !     Godeps are required. For instructions:
 !     https://devcenter.heroku.com/articles/go-support
To ssh://git@deis.foo.example.com:2222/monitor-config.git
 * [new branch]      master -> master
🌀  ls -a
.		.env		.gitignore	Makefile	couchbase	monitor.go	writer
..		.git		Dockerfile	README.md	monitor		reader
🌀  
```

**Comment by bacongobbler** [comment]
@n1rvana can you please confirm that you've committed the Dockerfile to the project? I recall seeing a similar issue before and it was resolved because they forgot to commit the Dockerfile to the project.

**Comment by bacongobbler** [comment]
for reference https://github.com/deis/deis/issues/2662

**Comment by n1rvana** [comment]
I've made progress. I think that at that point I was probably not committing the Docker file.  Now my app is failing to run:
```
🌀  deis logs --app=monitor-config
2016-02-24T17:51:51UTC monitor-config[deis-controller]: n1rvana created initial release
2016-02-24T21:56:15UTC monitor-config[deis-controller]: n1rvana deployed 5df967d
2016-02-24T21:56:32UTC monitor-config[deis-controller]: n1rvana scaled containers cmd=1
2016-02-25T17:15:25UTC monitor-config[deis-controller]: n1rvana scaled containers cmd=3
2016-02-25T17:15:50UTC monitor-config[deis-controller]: warning, some containers failed to start
2016-02-25T17:25:03UTC monitor-config[deis-controller]: n1rvana deployed 6b3c639
2016-02-25T17:36:30UTC monitor-config[deis-controller]: n1rvana deployed b406693
2016-02-25T17:37:14UTC monitor-config[deis-controller]: warning, some containers failed to start
2016-02-25T17:46:28UTC monitor-config[deis-controller]: n1rvana deployed 0995622
🌀  
```

Questions:
-- First thing this app does is print to STDOUT and to "log" using the golang log package.  Should that output be showing up in deis logs?
-- If so, that indicates that the command is not starting up in the docker container.   I'm using make to cross compile a binary and then using this docker file to build the container:
```
FROM centurylink/ca-certs

COPY monitor /

EXPOSE 8080

CMD /monitor
```
-- How do I debug problems with a container starting up, since there's nothing in the logs? 

I'm a newbie Deis user so pointers to RTFM can help (Though I read the logging info on the website and some issues here and wasn't able to find details.)

-- IRC channel doesn't seem to be well attended. Are y'all using Slack or Gitter?

**Comment by n1rvana** [comment]
Further info in case it helps:
```
deis info
=== monitor-config Application
updated:  2016-02-25T17:15:50UTC
uuid:     2fa5c668-9948-42aa-ae50-c7f0b4fb5186
created:  2016-02-24T17:51:51UTC
url:      monitor-config.example.com
owner:    n1rvana
id:       monitor-config

=== monitor-config Processes
--- cmd:
cmd.1 down (v5)
cmd.2 down (v5)
cmd.3 down (v5)

=== monitor-config Domains
```

here's the build results:
```
  git push deis master
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 337 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)

-----> Building Docker image
remote: Sending build context to Docker daemon 8.367 MB
Step 0 : FROM centurylink/ca-certs
 ---> a39ef86716f9
Step 1 : COPY monitor /
 ---> 87fa695406d9
Removing intermediate container cfe536cc0365
Step 2 : EXPOSE 8080
 ---> Running in f2a0a073fc04
 ---> 7fa57eb44522
Removing intermediate container f2a0a073fc04
Step 3 : CMD /monitor
 ---> Running in 0ec687db9baf
 ---> 01cd899ef71f
Removing intermediate container 0ec687db9baf
Step 4 : ENV GIT_SHA 0995622c0d48bf36c8625a43dbcf28438d687d47
 ---> Running in e29ee93bc092
 ---> 2f325693196e
Removing intermediate container e29ee93bc092
Successfully built 2f325693196e
-----> Pushing image to private registry

-----> Launching... 
       done, monitor-config:v5 deployed to Deis

       http://monitor-config.example.com

       To learn more, use `deis help` or visit http://deis.io

To ssh://git@deis.example.com:2222/monitor-config.git
   673bcbc..0995622  master -> master
```

**Comment by bacongobbler** [comment]
> IRC channel doesn't seem to be well attended. Are y'all using Slack or Gitter?

We're online from 9AM-5PM MST. I've always got IRC on so I see the chatter from last night. We're just missing each other likely due to time zone differences.

Deis just runs your container as-is, so the easiest way to debug is to `docker build/docker run` on your host. If nothing shows up in `deis logs`, either the logger/logspout isn't running or your container isn't booting :)

**Comment by n1rvana** [comment]
Was a problem with my Dockerfile.  Working now.  Thanks for the help.

**Comment by bacongobbler** [comment]
FWIW hopefully Deis v2 will show this problem in a better fashion than having to manually jump in the cluster and figure out what's wrong with the deployment :)

**Comment by n1rvana** [comment]
Sounds great! Looking forward to when Deis v2 is in beta (or alpha.)
