### ISSUE TITLE
Deis builder container removed

### ISSUE THREAD

**Issue by arkkanoid** [deis/deis#4936]
I'm trying to deploy new apps in my Deis platform. Previous apps were deployed successfully. Now, when I run 'git push' the action is not performed. I checked 'deisctl list' and the builder component doesn't appear. In the node, I see the builder component image, but the container doesn't exist in 'docker ps neither 'docker ps -a'.

Now I want to re-run the builder component, I tried 'deis install builder' but it gives a timeout, and 'deisctl restart builder' returns 'Could not find unit: deis-builder.service'.

In journalctl I see:

    Feb 23 16:39:43 ip-10-21-2-117.eu-west-1.compute.internal fleetd[714]: ERROR reconcile.go:79: Unable to determine agent's current state: failed fetching     unit states from UnitManager: dbus: connection closed by user
    Feb 23 16:39:44 ip-10-21-2-117.eu-west-1.compute.internal fleetd[714]: ERROR generator.go:65: Failed fetching current unit states: dbus: connection     closed by user
    Feb 23 16:39:45 ip-10-21-2-117.eu-west-1.compute.internal fleetd[714]: ERROR generator.go:65: Failed fetching current unit states: dbus: connection     closed by user
    Feb 23 16:39:46 ip-10-21-2-117.eu-west-1.compute.internal fleetd[714]: ERROR generator.go:65: Failed fetching current unit states: dbus: connection     closed by user
    Feb 23 16:39:47 ip-10-21-2-117.eu-west-1.compute.internal fleetd[714]: ERROR generator.go:65: Failed fetching current unit states: dbus: connection     closed by user

Why I getting this error?
How can I run the builder image?

**Comment by bacongobbler** [comment]
Judging from the logs I would assume that fleet is down. Can you confirm that etcd/fleet is responding correctly?

**Comment by arkkanoid** [comment]
Fleet, etcd and systemd are running properly : /

**Comment by arkkanoid** [comment]
It's a Fleet problem. I close this thread.
Thanks.
