### ISSUE TITLE
App process died at one point, no longer logs to `deis logs`

### ISSUE THREAD

**Issue by davidcelis** [deis/deis#4941]
I have a Twitter bot I use as a test app on my deis cluster. Recently, I noticed that it hadn't tweeted anything for a while, and when I checked on its processes it was listed as `destroyed`. I scaled back up to 1, and noticed that the process was now listed as running but doesn't produce any log output. The app has been in this state for several days and, though listed as "running", isn't doing anything.

I tried destroying the app and re-creating it with the same configuration and name, but when I started up the new app and checked `deis logs`, I was simply presented with the logs for my _old_ application and no new STDOUT output. When the bot starts up, it prints three lines to state it's online and streaming a timeline from Twitter. Or it prints errors if something's wrong. No output means it's not actually running.

I also tried editing the Procfile to change the name of my process from `cmd` to `bot`, but that still doesn't cause the app to actually come up. If I SSH into my cluster using `deisctl ssh router`, I can run `fleetctl list-units` and I _do_ see the container for my app running (it's the first one):

```
core@deis-1 ~ $ fleetctl list-units
UNIT				            MACHINE				        ACTIVE	SUB
dcelis-ebooks_v4.bot.1.service	4733f964.../10.132.127.105	active	running
deis-builder.service		    c14d7014.../10.132.129.119	active	running
deis-controller.service		    67a57db0.../10.132.130.126	active	running
deis-database.service		    67a57db0.../10.132.130.126	active	running
deis-logger.service		        c14d7014.../10.132.129.119	active	running
deis-logspout.service		    4733f964.../10.132.127.105	active	running
...
```

However, I'm not sure where to go from here with debugging. It appears my app's container is up and running with a process, but it's not doing anything and I don't know why. I've since renamed the process back to `cmd` because I like it better and the change didn't appear to do anything. Pushing up a new version and scaling that process type to 1 gives the same results. A container is running (now named `dcelis-ebooks_v5.cmd.1.service`) but producing no output.

Somewhat related: it's perturbing that I can destroy an application, create a new one with the same name, and see the old application's logs in `deis logs`.

**Comment by davidcelis** [comment]
So it does look like the container itself is providing logs:

```
core@deis-1 ~ $ docker ps
CONTAINER ID        IMAGE                                  COMMAND                CREATED             STATUS              PORTS                                                                                      NAMES
c75b8be1da13        10.132.129.119:5000/dcelis-ebooks:v5   "/runner/init start    10 minutes ago      Up 10 minutes       0.0.0.0:32903->5000/tcp                                                                    dcelis-ebooks_v5.cmd.1   
07f9bc4f60da        deis/database:v1.12.3                  "/app/bin/boot"        6 days ago          Up 6 days           0.0.0.0:5432->5432/tcp                                                                     deis-database            
490c51f3d860        deis/publisher:v1.12.3                 "/usr/local/bin/publ   6 days ago          Up 6 days                                                                                                      deis-publisher           
1d171b4830ae        deis/logspout:v1.12.3                  "/bin/logspout"        6 days ago          Up 6 days                                                                                                      deis-logspout            
b44c4da33556        deis/store-metadata:v1.12.3            "/app/bin/boot"        6 days ago          Up 6 days                                                                                                      deis-store-metadata      
be136afa2540        deis/store-daemon:v1.12.3              "/app/bin/boot ceph-   6 days ago          Up 6 days                                                                                                      deis-store-daemon        
d25f4a208497        deis/store-monitor:v1.12.3             "/app/bin/boot"        6 days ago          Up 6 days                                                                                                      deis-store-monitor       
63fe9c0d0425        deis/router:v1.12.3                    "boot"                 6 days ago          Up 6 days           0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:2222->2222/tcp, 0.0.0.0:9090->9090/tcp   deis-router              
633d9e377bb2        deis/store-admin:v1.12.2               "/app/bin/boot"        7 weeks ago         Up 7 weeks                                                                                                     deis-store-admin         
core@deis-1 ~ $ docker logs c75b8be1da13
@dcelis_ebooks: User information updated
@dcelis_ebooks: starting tweet stream
@dcelis_ebooks: Online!
core@deis-1 ~ $ 
```

However, it's unclear as to why the application doesn't appear to be doing anything. When run locally, it works as expected…

**Comment by davidcelis** [comment]
Update: the app finally did start doing expected things:

```
$ docker logs c75b8be1da13
@dcelis_ebooks: User information updated
@dcelis_ebooks: starting tweet stream
@dcelis_ebooks: Online!
Building: sentence 0 of 2620
Attempting to produce tweet try 1/10
Attempting to produce tweet try 1/10
@dcelis_ebooks: Tweeting 'Screening for abuse is not enough of a majority based on party lines.'
Building: sentence 0 of 2620
Attempting to produce tweet try 1/10
@dcelis_ebooks: Tweeting 'A very short life for my blog posts and someone just used it for the first things I see?'
@dcelis_ebooks: @adelinereilly15 favorited: A very short life for my blog posts and someone just used it for the first things I see?
```

However, none of the logs seem to be making it into `deis logs`. I can view them only by SSHing into my host and running `docker logs` with the container ID.

**Comment by carmstrong** [comment]
> However, none of the logs seem to be making it into deis logs. I can view them only by SSHing into my host and running docker logs with the container ID.

Is only this app having issues with logging? If none of your application logs are making it, you may need to restart the `logger` component. If some apps are logging and others aren't, try to see if there is commonality between them - if they are running on the same host, you could try restarting that host's `logspout` component.

**Comment by davidcelis** [comment]
It looks like _none_ of my apps are currently producing logs. I've restarted `deis-logger` but to no avail.

This has also persisted through a graceful upgrade from 1.12.2 to 1.12.3.

**Comment by carmstrong** [comment]
Another thing to investigate is whether the logs aren't being written, or aren't being read. 

Try jumping onto a host and looking at `/var/lib/deis/store`. This is a mounted CephFS filesystem, and is how the logger and controller components share log files. Tail the log file for your app and see if log events are being written to disk.

**Comment by davidcelis** [comment]
The contents of `/var/lib/deis/store/logs/dcelis-ebooks.log` match what I see in `deis logs`, so it appears new logs aren't getting written to disk.

**Comment by bacongobbler** [comment]
@davidcelis can you take a look at the logs for deis-logspout on this host, as well as restarting the process? It's possible that it is not sending logs to the correct host any more: https://github.com/deis/deis/issues/4293

**Comment by jchauncey** [comment]
Yeah my guess is logspout is in a weird state

**Comment by krancour** [comment]
Here are the two most plausible explanations:

1.  We've seen logspout seize up before and stop "attaching" to containers-- which is the process whereby it watches all app containers' STDOUT and STDERR so it can forward each line to the logger component.  To the best of our knowledge, we have fixed this, so this is the less likely of the two explanations.  However, you could check if this is the case by using journalctl to look at logspout's own logs on any host that's hosting an app container whose logs are missing.  If you don't see messages that clearly indicate "attaching" to containers, then this is the problem.  Again... this isn't too likely.

2.  The more likely problem is this: https://github.com/deis/deis/issues/4293.  This could be resolved simply by restarting logspout.

**Comment by davidcelis** [comment]
Yup, restarting logspout fixed it. Thank you!
