### ISSUE TITLE
deis-builder "key does not exist" errors

### ISSUE THREAD

**Issue by rstacruz** [deis/deis#4948]
Hey,

Possibly related to #4922, but deis-builder is giving me these errors.

> [debug] Output: "2016-02-29T20:58:18Z 24b0aecf9246 confd[357]: ERROR template: builder:59:14: executing \"builder\" at \<getv \"/deis/registry...\>: error calling getv: key does not exist

> 2016-02-29T20:58:21Z 24b0aecf9246 confd[357]: ERROR template: check-repos:14:20: executing \"check-repos\" at \<getv \"/deis/registry...\>: error calling getv: key does not exist

> 2016-02-29T20:58:21Z 24b0aecf9246 confd[357]: ERROR template: push-images:9:37: executing \"push-images\" at \<getv \"/deis/registry...\>:  key does not exist

> late: receiver:15:55: executing \"receiver\" at \<getv \"/deis/controll...\>: error calling getv: key does not exist\n"

Running deis 1.12.2 in AWS EC2. Any clue how I can figure out what keys its trying to retrieve, and why it doesnt' exist?

**Comment by rstacruz** [comment]
```
 $ etcdctl ls /deis/controller
/deis/controller/secretKey
/deis/controller/builderKey
/deis/controller/registrationMode
/deis/controller/webEnabled
/deis/controller/unitHostname
/deis/controller/protocol
```

**Comment by rstacruz** [comment]
```
$ etcdctl ls /deis/registry
/deis/registry/protocol
/deis/registry/bucketName
/deis/registry/hosts
```

Okay, I found something strange: `/deis/registry/hosts` has an old IP in it (10.21.1.221), which doesn't show up anymore in `deisctl list`. This is likely an old machine that AWS EC2 auto-scaling decided to shut down.

```
 $ etcdctl ls /deis/registry/hosts
/deis/registry/hosts/10.21.1.221
/deis/registry/hosts/10.21.2.212
```

**Comment by bacongobbler** [comment]
> getv \"/deis/registry

that error indicates something's wrong with the registry. The core issue about confd not showing further information is tracked here, which has since been fixed in master: https://github.com/kelseyhightower/confd/issues/268

As per your comment update, two keys that are missing are `/deis/registry/host` and `/deis/registry/port`. Do you have a registry running on your cluster?

**Comment by rstacruz** [comment]
Yes I do.

```
deis-registry@1.service         71043b08.../10.21.2.212 loaded  active          running
```

**Comment by bacongobbler** [comment]
hmm... What are the logs on the registry's side of things? Perhaps there's something blocking it from publishing to etcd.

**Comment by rstacruz** [comment]
looks like it's been trying to create a bucket, but can't.

`journalctl -u deis-registry@1`

> Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: Traceback (most recent call last):
Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: File "/app/bin/create_bucket", line 26, in <module>
Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: conn.create_bucket(name)
Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 612, in create_bucket
Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: data=data)
Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: File "/usr/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: retry_handler=retry_handler
Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: File "/usr/lib/python2.7/site-packages/boto/connection.py", line 1068, in make_request
Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: retry_handler=retry_handler)
Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: File "/usr/lib/python2.7/site-packages/boto/connection.py", line 943, in _mexe
Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: response = connection.getresponse()
Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: response.begin()
Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: File "/usr/lib/python2.7/httplib.py", line 415, in begin
Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: version, status, reason = self._read_status()
Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: line = self.fp.readline(_MAXLINE + 1)
Feb 29 20:13:25 ip-10-21-2-212.ap-southeast-2.compute.internal sh[12683]: File "/usr/lib/python2.7/socket.py", line 476, in readline

**Comment by bacongobbler** [comment]
Yes, that sounds like a cascading issue stemming from https://github.com/deis/deis/issues/4943.

**Comment by rstacruz** [comment]
how can I fix this?

**Comment by bacongobbler** [comment]
closing by proxy from #4943
