### ISSUE TITLE
Question: is stateless Deis still supported on v2?

### ISSUE THREAD

**Issue by rstacruz** [deis/deis#4949]
Sorry for asking questions here, not really sure where to. I try asking on IRC sometimes but oftentimes no one is available to answer.

Can I still run Deis in the "stateless" mode on Deis v2 (kubernetes-based)? I understand it doesn't have Ceph anymore, but it seems a lot of problems arise in my AWS cluster that can possibly be alleviated by statelessness.

EC2 regularly changes IPs of machines which causes problems intermittently... I'd like to avoid these headaches when they happen.

**Comment by bacongobbler** [comment]
> Sorry for asking questions here, not really sure where to. I try asking on IRC sometimes but oftentimes no one is available to answer.

We're usually awake and available from 09:00-17:00MST during regular American work days on IRC. :)

> Can I still run Deis in the "stateless" mode on Deis v2 (kubernetes-based)?

That is something we are targeting for v2. Users should be able to replace object storage with S3, deis-database with RDS, etc. See https://github.com/deis/deis/issues/4809 for more info on what we're cooking up for the beta release.
