### ISSUE TITLE
Stateless without logging?

### ISSUE THREAD

**Issue by rstacruz** [deis/deis#4950]
I'd like to run a stateless cluster without Papertrail. is that possible?

**Comment by bacongobbler** [comment]
@rstacruz yes. From http://docs.deis.io/en/latest/managing_deis/running-deis-without-ceph/#logger:

> In a Ceph-less cluster, the Logger component should be configured, instead, to use in-memory log storage. Optionally, a drain may also be configured to forward logs to an external log service (such as Papertrail) for longer-term archival.

So it's possible to run a stateless cluster without Papertrail.

**Comment by rstacruz** [comment]
so just don't set `drain=`?

**Comment by bacongobbler** [comment]
yes.
