### ISSUE TITLE
Quartz.net

### ISSUE THREAD

**Issue by ainux4mrvce** [deis/deis#4955]
i have a fuelUI Scheduler control on web page,
![image](https://cloud.githubusercontent.com/assets/5284414/13599920/b4af7bd0-e54b-11e5-8243-f29052a2a554.png)

using service stack i am collecting all the scheduling information need to schedule a job from this page, and also have a method which converts the time into cron expression as i am using cron. can some on evaluate this code or if you enhance this code.

source code:

**> public string getCronPattern(RecurrencePattern recurrencePattern, TimeSpan time)
>         {
> 
>             string cronPattern = string.Empty;
>             if (recurrencePattern.FREQ == "DAILY")
>             {
>                 if (recurrencePattern.BYDAY != null)
>                     cronPattern = "0 " + time.Minutes + " " + time.Hours + " 1/" + recurrencePattern.INTERVAL + " * " + recurrencePattern.BYDAY + " * *";
>                 else
>                     cronPattern = "0 " + time.Minutes + " " + time.Hours + " 1/" + recurrencePattern.INTERVAL + " * ? *";
>             }
>             else if (recurrencePattern.FREQ == "HOURLY")
>             {
>                 cronPattern = "0 " + time.Minutes + " " + time.Hours + "/" + recurrencePattern.INTERVAL + " * * ? *";
>             }
>             else if (recurrencePattern.FREQ == "WEEKLY")
>             {
>                 cronPattern = "0 " + time.Minutes + " " + time.Hours + " ? * " + recurrencePattern.BYDAY + " *";
>             }
>             else if (recurrencePattern.FREQ == "MONTHLY")
>             {
>                 if (recurrencePattern.BYMONTHDAY > 0)
>                     cronPattern = " 0 " + time.Minutes + " " + time.Hours + " " + recurrencePattern.BYMONTHDAY + " 1/1 ? *";
>                 else
>                     cronPattern = "0 " + time.Minutes + " " + time.Hours + " ? 1/1 " + recurrencePattern.BYDAY + "#" + recurrencePattern.BYSETPOS + " *";
>             }
>             else
>             {
>                 if (recurrencePattern.BYDAY != null)
>                     cronPattern = "0 0 12 ? " + recurrencePattern.BYMONTH + " " + recurrencePattern.BYDAY + "#" + recurrencePattern.BYSETPOS + " *";
>                 else
>                     cronPattern = "0 0 12 " + recurrencePattern.BYMONTHDAY + " " + recurrencePattern.BYMONTH + " ? *";
>             }
>             return cronPattern;
> 
>         }**

**Comment by krancour** [comment]
This issue does not appear relevant to Deis.  Perhaps it was accidentally opened against the wrong project?  Closing.

**Comment by ainux4mrvce** [comment]
ya sorry by mistake i did that.
