### ISSUE TITLE
How to view deis users and/or reset passwords

### ISSUE THREAD

**Issue by jamescw** [deis/deis#4960]
I created a user when bringing up the cluster (which got admin) and have no idea what the user/pass was. I registered a second user (and maybe a third) which are non admins...
How can I manage users? I have deisctl access.

**Comment by bacongobbler** [comment]
The first user created has administration access. You must log in as that user and use `deis users:list`. If you're completely stuck,

```
deisctl dock controller
python manage.py shell
>>> from django.contrib.auth.models import User
>>> user = User.objects.get(username='<user>')
>>> user.set_password('new password')
>>> user.save()
```

Or

```
deisctl dock controller
python manage.py changepassword <user>
```

Or just create a new superuser

```
deisctl dock controller
python manage.py createsuperuser
```

**Comment by jamescw** [comment]
@bacongobbler thanks that what I ended up doing :)
