### ISSUE TITLE
Set SSL on Application

### ISSUE THREAD

**Issue by arkkanoid** [deis/deis#4963]
Hi, 
I want to set the SSL certificate in the application I deploy. I know that it's possible to set the certificates in the router components, but I prefer having all flow, from client to the application, with SSL.

I've exposed the application to the port 443, but how can I configure the router component to redirect to this port?
I use AWS, the ELB is configured to redirect TCP requests on port 443, and the Proxy Protocol in Deis is activated.

**Comment by krancour** [comment]
You're looking for "end to end" SSL.  There is no support for it in v1.x or the upcoming v2.  It is, however, something we're already quite intent on adding.  An approach has been chosen, and I'd expect this to land somewhere in the v2.1 or v2.2 timeframe.

**Comment by arkkanoid** [comment]
Thanks @krancour

**Comment by bacongobbler** [comment]
@arkkanoid https://github.com/deis/workflow/issues/355 is the issue we're tracking for v2
