### ISSUE TITLE
deis scale omits environment tags

### ISSUE THREAD

**Issue by arkkanoid** [deis/deis#4964]
Hi, 
I'm testing Deis environment tags. When I have an application with scaled=1 and a specific environment tag it works fine.
When I scale >1 the application is deployed on random nodes, so it omits the environment tag. I also tried to apply the environment tag after scale the containers but it doesn't works.

Have you reproduced this behaviour?

**Comment by mboersma** [comment]
@arkkanoid I assume you're using Deis v1.12.x? To clarify:
```console
$ deis scale web=6
$ deis tags:set environ=staging
```
After commands like those, are you seeing the app units deployed to hosts that do not have the `environ: staging` metadata set?

**Comment by arkkanoid** [comment]
@mboersma, yes I set the commands you said on version 1.12.2. Specifically:
 
    fleetctl list-machines
    MACHINE   IP    METADATA
    4eb5ca9f... 10.21.1.250 controlPlane=true,dataPlane=true,environ=prod,routerMesh=true
    78a98606... 10.21.2.66  controlPlane=true,dataPlane=true,environ=prod,routerMesh=true
    7d0d5b8e... 10.21.2.160 controlPlane=true,dataPlane=true,environ=devpre,routerMesh=true
    8bac4bf9... 10.21.1.251 controlPlane=true,dataPlane=true,environ=prod,routerMesh=true
    bd8deb7e... 10.21.1.100 controlPlane=true,dataPlane=true,environ=devpre,routerMesh=true
    bd947c86... 10.21.1.90  controlPlane=true,dataPlane=true,environ=devpre,routerMesh=true
    
deis tags:set environ=devpre -a gentle-offshoot

    fleetctl list-units
    UNIT          MACHINE     ACTIVE  SUB
    deis-builder.service      7d0d5b8e.../10.21.2.160 active  running
    deis-controller.service     8bac4bf9.../10.21.1.251 active  running
    deis-logger.service     4eb5ca9f.../10.21.1.250 active  running
    ....
    gentle-offshoot_v8.web.1.service  7d0d5b8e.../10.21.2.160 active  running
    
deis tags:set environ=devpre -a gentle-offshoot
deis scale web=3 -a gentle-offshoot

    fleetctl list-units    
    UNIT          MACHINE     ACTIVE  SUB
    deis-builder.service      7d0d5b8e.../10.21.2.160 active  running
    deis-controller.service     8bac4bf9.../10.21.1.251 active  running
    deis-logger.service     4eb5ca9f.../10.21.1.250 active  running
    ....
    gentle-offshoot_v8.web.1.service  7d0d5b8e.../10.21.2.160 active  running
    gentle-offshoot_v8.web.2.service  78a98606.../10.21.2.66  active  running

**Comment by bacongobbler** [comment]
@arkkanoid can you run `fleetctl cat gentle-offshoot_v8.web.2` just to confirm the fleet unit's state so we can nail down the issue?

**Comment by arkkanoid** [comment]
[Unit]
    Description=gentle-offshoot_v10.web.3
    
    [Service]
    ExecStartPre=/bin/sh -c "IMAGE=$(etcdctl get /deis/registry/host 2>&1):$(etcdctl get /deis/registry/port 2>&1)/gentle-offshoot:v10; docker pull $IMAGE"
    ExecStartPre=/bin/sh -c "docker inspect gentle-offshoot_v10.web.3 >/dev/null 2>&1 && docker rm -f gentle-offshoot_v10.web.3 || true"
    ExecStart=/bin/sh -c "IMAGE=$(etcdctl get /deis/registry/host 2>&1):$(etcdctl get /deis/registry/port 2>&1)/gentle-offshoot:v10; docker run --name gentle-offshoot_v10.    web.3 --rm    -P $IMAGE start web"
    ExecStop=/usr/bin/docker stop gentle-offshoot_v10.web.3
    TimeoutStartSec=20m
    TimeoutStopSec=10
    RestartSec=5
    Restart=on-failure

**Comment by bacongobbler** [comment]
I was not able to reproduce on master. I found the MachineMetadata tags on each unit after a `git push deis master && deis scale web=3 && deis tags:set dataPlane=true`: https://gist.github.com/bacongobbler/26ad178de20e606740fb

**Comment by arkkanoid** [comment]
@bacongobbler I've deployed a new Deis cluster. I've tried to set an environment tag but the error persist on v1.12.2. 
Running fleetctl cat myapp,  doesn't appears the [X-fleet] section.

If I load a custom unit file, with:
    [X-Fleet]
    MachineMetadata="environ=devpre"
The application runs in the correct node. 

So it seems that Deis client isn't setting the new environment tag properly. How can I analyse in-depth?

**Comment by arkkanoid** [comment]
I'm running a new Deis cluster v1.12.3 and when I try to set an environ tag it is ommited in the unit file. 
I paste some logs:

`POST deis.deistag.omykuji.com/v1/apps/tag6/config
RESPONSE:
{
"uuid": "1326c4ed-dfc9-4258-a381-50db409ba236",
"app": "tag6",
"owner": "omykuji",
"values":{
"DEIS_APP": "tag6",
"DEIS_RELEASE": "v4"
},
"memory":{},
"cpu":{},
"tags":{
"environ": "devpre",
"dataplane": "true"
},
"created": "2016-04-01T09:54:37UTC",
"updated": "2016-04-01T09:54:37UTC"
}


fleetctl journal deis-controller
-- Logs begin at Thu 2016-03-31 14:06:28 UTC, end at Fri 2016-04-01 09:55:41 UTC. --
Apr 01 09:43:07 ip-10-21-2-90.eu-west-1.compute.internal sh[3213]: INFO Pushing Docker image 10.21.1.40:5000/tag6:v3
Apr 01 09:44:11 ip-10-21-2-90.eu-west-1.compute.internal sh[3213]: 10.21.1.233 "POST /v1/apps/tag6/config HTTP/1.0" 201 246 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"
Apr 01 09:54:37 ip-10-21-2-90.eu-west-1.compute.internal sh[3213]: INFO tag6: config tag6-1326c4e updated
Apr 01 09:54:37 ip-10-21-2-90.eu-west-1.compute.internal sh[3213]: INFO tag6: release tag6-v4 created
Apr 01 09:54:37 ip-10-21-2-90.eu-west-1.compute.internal sh[3213]: INFO [tag6]: omykuji added tag environ
Apr 01 09:54:37 ip-10-21-2-90.eu-west-1.compute.internal sh[3213]: INFO Pulling Docker image 10.21.1.40:5000/tag6:git-89109849
Apr 01 09:54:43 ip-10-21-2-90.eu-west-1.compute.internal sh[3213]: INFO Tagging Docker image 10.21.1.40:5000/tag6:git-89109849 as tag6:git-89109849
Apr 01 09:54:43 ip-10-21-2-90.eu-west-1.compute.internal sh[3213]: INFO Building Docker image 10.21.1.40:5000/tag6:v4
Apr 01 09:54:55 ip-10-21-2-90.eu-west-1.compute.internal sh[3213]: INFO Pushing Docker image 10.21.1.40:5000/tag6:v4
Apr 01 09:55:21 ip-10-21-2-90.eu-west-1.compute.internal sh[3213]: 10.21.1.233 "POST /v1/apps/tag6/config HTTP/1.0" 201 265 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"


fleetctl cat tag6_v4.web.1.service
[Unit]
Description=tag6_v4.web.1

[Service]
ExecStartPre=/bin/sh -c "IMAGE=$(etcdctl get /deis/registry/host 2>&1):$(etcdctl get /deis/registry/port 2>&1)/tag6:v4; docker pull $IMAGE"
ExecStartPre=/bin/sh -c "docker inspect tag6_v4.web.1 >/dev/null 2>&1 && docker rm -f tag6_v4.web.1 || true"
ExecStart=/bin/sh -c "IMAGE=$(etcdctl get /deis/registry/host 2>&1):$(etcdctl get /deis/registry/port 2>&1)/tag6:v4; docker run --name tag6_v4.web.1 --rm    -P $IMAGE start web"
ExecStop=/usr/bin/docker stop tag6_v4.web.1
TimeoutStartSec=20m
TimeoutStopSec=10
RestartSec=5
Restart=on-failure
`

**Comment by arkkanoid** [comment]
Solved. I had to set: deisctl config platform set enablePlacementOptions=true
 It would be nice to set this parameter in the documentation.
Thanks!
