### ISSUE TITLE
Question: does Deis drain HTTP connections before stopping containers?

### ISSUE THREAD

**Issue by olalonde** [deis/deis#4967]
I have an app which handles relatively large file uploads (0-100mb) so I would like Deis to wait for all HTTP connections to terminate before stopping the old containers when I deploy a new release, so that ongoing file uploads aren't interrupted by deploys. Is that something Deis can handle natively? Otherwise, any suggested workarounds? (deis v1.12.2)

**Comment by krancour** [comment]
Fleet has no idea what's going on inside your containers, so no... Deis doesn't do this.  As for workarounds... possibly some tweaking of the application Fleet units created by the controller (i.e. custom controller) + some careful signal handling within the applucation.  I couldn't guarantee it would work.

**Comment by olalonde** [comment]
Ok, thanks. In theory, couldn't the deis router keep track of "in flight" connections and tell the controller when it's ok to kill the old containers? I understand that it's out of scope though and searching google for how to do this with nginx doesn't yield many useful results..

**Comment by Blystad** [comment]
You could handle large file uploads better in your application. See how Google have done it with their resumable file uploads: https://developers.google.com/drive/v3/web/manage-uploads#resumable
