### ISSUE TITLE
git push builder error

### ISSUE THREAD

**Issue by naphatkrit** [deis/deis#4969]
Hi,

I encountered the following error when trying to push to Deis:

```
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 260 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
/home/git/builder: eval: line 116: unexpected EOF while looking for matching ``'
/home/git/builder: eval: line 117: syntax error: unexpected end of file
To ssh://git@deis.*******.com:2222/*******.git
   5da89aa..1531fdd  HEAD -> master
```

Does anyone know how I can debug this? It only affects the current app, not newly created ones.

**Comment by bacongobbler** [comment]
This looks very similar to https://github.com/deis/deis/issues/2980 and https://github.com/deis/deis/issues/3994. What does `deis config:list` look like?

**Comment by naphatkrit** [comment]
Ah, looks like the exact same issue. Alright, consider this a duplicate!
