### ISSUE TITLE
Healthcheck failure on deploy not reported.

### ISSUE THREAD

**Issue by obmarg** [deis/deis#4978]
If I deploy a new version of my application and that application fails it's health check, the `git push` output does not inform me that this has happened.  It just rolls back silently and prints the usual "deployed to Deis" message:

```
-----> Launching...
       done, app:v73 deployed to Deis

       http://url

       To learn more, use `deis help` or visit http://deis.io

To ssh://myserver:2222/repo.git
 * [new branch]      master -> master
```

The only way to tell a deploy has failed is to notice that the version number in the message has not incremented.  This might have been behind the issue I was experiencing in #4841

**Comment by bacongobbler** [comment]
this has been fixed in v2 or at least we have the technology to identify this case. @helgi, thoughts on whether we've fixed this?

**Comment by helgi** [comment]
Off hand, it may be fixed in v2 but I am also adding in a bit more of a "panic panic it failed" mode so that the API would throw the appropriate errors, which in turn Builder would support

**Comment by bacongobbler** [comment]
this has been fixed in v2.
