### ISSUE TITLE
Config in etcd not rolled back on healthcheck failure.

### ISSUE THREAD

**Issue by obmarg** [deis/deis#4979]
If I add the `HEALTHCHECK_URL` setting to an application that subsequently fails its healthcheck, the release will be rolled back.  However, the etcd `/deis/config/app/healthcheck_url` key is not removed, which seems to cause the publisher to remove the existing containers from nginx, causing the app to 502 until someone fixes it.

**Comment by bacongobbler** [comment]
this is likely going to be addressed in v2 via https://github.com/deis/controller/issues/798

**Comment by deis-admin** [comment]
Deis v1 LTS support ends February 13, 2017, and [v1.13.4](https://github.com/deis/deis/releases/tag/v1.13.4) is intended to be the last official release, so I'm closing this.

Please see [Deis Workflow](https://github.com/deis/workflow), the documentation / hub repository for the next-generation PaaS.
