### ISSUE TITLE
Broken Deploys

### ISSUE THREAD

**Issue by jwaldrip** [deis/deis#4983]
I have an issue with one of my apps, new versions aren’t deploying because there are duplicate unit files. With each new deploy attempt, new units get created but not destroyed or for some reason the controller just crashes.

To try and remedy this, I destroyed the units from fleet. Now any command from deis, rollback or deploy fails because it is looking for the new units. How can I resolve this issue in deis so that it will let me deploy new units?

**Comment by jwaldrip** [comment]
**New development:** I cant even destroy the application now

**Comment by bacongobbler** [comment]
Bumping this issue. @jwaldrip were you able to resolve this? From the slack conversation we had two weeks ago it looked like your fleet cluster was barfing 500 errors rather than duplicate unit file errors.

**Comment by jwaldrip** [comment]
I had to completely destroy the app and recreate it. You assumed it was the
fleet cluster, but as I mentioned in slack, you we're wrong. You can just
close this. I don't get any good support from opening these anymore anyway.
:-(

  

Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On Apr 4 2016, at 12:08 am, Matthew Fisher &lt;notifications@github.com&gt;
wrote:  

> Bumping this issue. [@jwaldrip](https://github.com/jwaldrip) were you able
to resolve this? From the slack conversation we had two weeks ago it looked
like your fleet cluster was barfing 500 errors rather than duplicate unit file
errors.

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/deis/de
is/issues/4983#issuecomment-205149432)![](https://github.com/notifications/bea
con/AAConAPH3zF-h4Jw384UOD4Pe5B4ux4xks5p0KrJgaJpZM4H3HA1.gif)
