### ISSUE TITLE
builder cleanup operations should occur on success and failure

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#4991]
currently they only occur on success, but things like cleaning up the build dir, running `git gc` and killing the docker job should also occur on failure.

This should also get ported over to v2.

**Comment by arschles** [comment]
@bacongobbler we currently do `git gc` in the v2 builder, but can you submit issues in the v2 builder repo for the other cleanup tasks?

**Comment by bacongobbler** [comment]
absolutely :) I'm currently porting over #4990.

**Comment by arschles** [comment]
thanks!

**Comment by bacongobbler** [comment]
filed https://github.com/deis/builder/issues/271 for v2

**Comment by bacongobbler** [comment]
This isn't a core issue, but since we've ported over a fix for v2 I'm happy to close this one out to work on other important LTS features.
