### ISSUE TITLE
Limit max containers per node

### ISSUE THREAD

**Issue by arkkanoid** [deis/deis#5000]
Hi, 
I've a lot of containers running with a memory limitation, i.e. 128MB. This restriction is only set in case the process running in the container try to consume more than 128MB, but in a normal situation it only consumes 60MB. 

If I've 1024MB of free memory in my node, Deis will run (1024M / 60M) 17 applications in this node, but it should be (1024M / 128M) 8 applications due to the memory restriction.

So, I would like to reserve 128MB for each container, can I do it? Maybe setting a limit of maximum number of containers per node?

**Comment by bacongobbler** [comment]
See `deis help limits`. Fleet is not a true resource-aware scheduler which is why we moved to kubernetes in v2.

**Comment by arkkanoid** [comment]
thanks
