### ISSUE TITLE
CLI doesn't report error on pushing image.

### ISSUE THREAD

**Issue by monaka** [deis/deis#5003]
It seems CLI doesn't report errors like this even if private repository has trouble, 

```
Step 12 : ENV GIT_SHA 22af1330ef395cdbb40faa9ab3c7ef4f8b1e93b1
 ---> Running in cf832cdfe241
 ---> c7f273984a9b
Removing intermediate container cf832cdfe241
Successfully built c7f273984a9b
-----> Pushing image to private registry
To ssh://git@deis.{{censored}}:2222/{{censored}.git
 + 8d6b4b9...22af133 HEAD -> master (forced update)
```

It's better to report errors after 'Pushing image to private registry.'

**Comment by bacongobbler** [comment]
It looks like we do this now in v2: https://github.com/deis/dockerbuilder/blob/master/rootfs/deploy.py#L104-L105

@smothiki or @kmala can you confirm this has been fixed in v2?

**Comment by bacongobbler** [comment]
closing as fixed for v2.
