### ISSUE TITLE
Support ssh keys larger than 4096 on Workflow (v2)

### ISSUE THREAD

**Issue by rosstimson** [deis/deis#5007]
I'm a Deis n00b but I'm testing out the v2 (Workflow) beta and when it came to trying to add my ssh key with `deis keys:add` I encountered:

```
Uploading id_rsa.pub to deis...
Error:
500 Internal Server Error
<h1>Server Error (500)</h1>
```

Being a paranoid sys admin I have a larger than average default ssh key (`16384`), I generated a new `4096` key and pushed successfully.

It would be nice if Deis supported larger keys.

**Comment by bacongobbler** [comment]
@rosstimson sorry for the late response, but do you happen to have controller logs that show the server error? My assumption is that [the fingerprint](https://github.com/deis/controller/blob/5a190359a1efcbac40f071e3d6dab8979722eed9/rootfs/api/models/key.py#L35) for your key was [longer than 128 characters](https://github.com/deis/controller/blob/5a190359a1efcbac40f071e3d6dab8979722eed9/rootfs/api/models/key.py#L25).

**Comment by deis-admin** [comment]
This issue was moved to deis/controller#1211
