### ISSUE TITLE
Removing user may break app releases list and app itself

### ISSUE THREAD

**Issue by szymonpk** [deis/deis#5019]
Scenario from today
- App owned by user 'foo', 'foo' was only user doing releases (push).
- App ownership is transferred to different user. (apps:transfer)
- User 'foo' is removed (auth:cancel)
- From now on I can't see any releases, git push or see config (api throwing 500 with "DoesNotExist: Release matching query does not exist."), when running database query on api_release (`select * from api_release where app_id = '<foo app id>';`) I see empty list :(
- I've managed to fetch config directly from database and setup same app under different name, I've also had to remove old containers by hand.

Any chance this may be fixed as LTS?

**Comment by bacongobbler** [comment]
@szymonpk this has been fixed in v2 as you cannot cancel a user until you remove all apps from the user. The LTS release has been shipped but if you're willing to write up a patch we'll eventually cut a 1.13.1 release once there's enough bugfixes in there :)

**Comment by bacongobbler** [comment]
@helgi and @mboersma also mentioned to me that the auth:cancel feature was also back-ported in 1.13.0. Could you please try 1.13.0 and see if that works for you?

**Comment by szymonpk** [comment]
@bacongobbler I've transfered ownership to different user (before running auth:cancel, which is present in 12.x), but releases weren't transfered. Is it fixed in v2 as well?

In result releases list was empty and there was no way to redeploy, restart etc.
