### ISSUE TITLE
Docs: clarify AWS instructions on upgrading

### ISSUE THREAD

**Issue by rstacruz** [deis/deis#5035]
In the [Upgrading Deis](http://docs.deis.io/en/latest/managing_deis/upgrading-deis/) page, it has this to say about AWS:

> On AWS, Deis enables the PROXY protocol by default. If an in-place upgrade is required, run deisctl config router set proxyProtocol=1, enable PROXY protocol for ports 80 and 443 on the ELB, add a TCP 443:443 listener, and change existing targets and health checks from HTTP to TCP.

I think it should be clarified a little further.

- Do you really need to enable PROXY protocol? Shouldn't this have already been enabled for you when you first installed Deis? If not, how do you enable it? As far as I know, it's not a straight-forward process; there aren't controls for this in the AWS web console.

- `deisctl config router set proxyProtocol=1` probably needs to be ran *before* the uprgade, so this note should be higher up the page.

- It says to _"change existing targets and health checks from HTTP to TCP."_, but not exactly what to configure here (like what port.

I almost messed up an upgrade here because ELB thought my nodes are dead; I changed the health check to TCP and it thought my nodes are dead, haha.

For reference, it looks like this in the AWS web console:

![image](https://cloud.githubusercontent.com/assets/74385/15188135/da60da3c-17d6-11e6-888f-f0f354cfd5c3.png)

**Comment by bacongobbler** [comment]
> Shouldn't this have already been enabled for you when you first installed Deis? If not, how do you enable it?

Yes. At the the end of the AWS install script, deisctl makes a call to [enable proxy protocol](https://github.com/deis/deis/blob/master/contrib/aws/provision-aws-cluster.sh#L174) for you. This section of the docs only applies to users upgrading from v1.5.0 and earlier, since v1.6.0 enables proxy protocol by default.

If you have a cluster newer than v1.5.0, this section of the docs does not apply.

**Comment by mboersma** [comment]
Closed by #5036. Thanks @rstacruz!
