### ISSUE TITLE
Question: multiple SSL certificates

### ISSUE THREAD

**Issue by rstacruz** [deis/deis#5037]
Is it possible to have multiple SSL certificates? The docs say this:

> You can also use the Deis routers to terminate SSL connections. Use deisctl to install the certificate and private keys:

>     $ deisctl config router set sslKey=<path-to-key> sslCert=<path-to-cert>

> If your certificate has intermediate certs that need to be presented as part of a certificate chain, append the intermediate certs to the bottom of the sslCert value.

But I'd like to have my Deis cluster live in `fooappdev.com`, while the production live in `fooapp.com`. This means I'd like to have SSL certificates for both domains. In this case, should I have `fooappdev.com`'s certificate on the router and `fooapp.com` on the app?

**Comment by bacongobbler** [comment]
Yes. :)
