### ISSUE TITLE
Deis components uninstall themselves

### ISSUE THREAD

**Issue by rstacruz** [deis/deis#5040]
I woke up to a stateless 1.13 cluster that looks like this:

 ```
$ deisctl list
UNIT            MACHINE            LOAD    ACTIVE    SUB
deis-logspout.service    a8317182.../1.2.3.66    loaded    active    running
deis-publisher.service    a8317182.../1.2.3.66    loaded    active    running
deis-router@2.service    a8317182.../1.2.3.66    loaded    active    running
```

It seems services died, and I tried to do this:

```
deisctl stop stateless-platform
deisctl install stateless-platform
deisctl start stateless-platform
```

but it stops at:

```
$ deisctl install stateless-platform
● ▴ ■
■ ● ▴ Installing Deis...
▴ ■ ●
Logging subsystem...
deis-logspout.service: loaded
```

any clues on where to start debugging this?

**Comment by rstacruz** [comment]
installing individual components is no good either.

```
$ deisctl install controller

...stalls indefinitely
```

**Comment by laurrentt** [comment]
Can happen when you enable placement options, but don't have any eligible node in the cluster to handle the unit (.service). For example, `deis-controller.service` needs an available node with a machine metadata containing `controlPlane=true`. `fleetctl list-machines` will show you which node has which metadata.

**Comment by bacongobbler** [comment]
ping @rstacruz did taht help you? ^

**Comment by rstacruz** [comment]
Hey thanks, forgot to update on this. I found out what happened here. Something maxed out our CPU. This exhausted our nodes and processes died. 

For the record, it was a Rails app that we did `deis run rake db:migrate` on, where `rake` somehow spawned an infinite number of `spring` servers.

Thanks for all your help.
