### ISSUE TITLE
HSTS does not get set on router

### ISSUE THREAD

**Issue by Crispy1975** [deis/deis#5050]
@krancour On enabling all the HSTS options as defined in the documentation here:

http://docs.deis.io/en/latest/customizing_deis/router_settings/#settings-used-by-router

We can see the `etcd` keys have been written from this following listing...

```shell
~ $ etcdctl ls /deis/router/
/deis/router/hosts
/deis/router/sslCiphers
/deis/router/preloadHSTS
/deis/router/sslKey
/deis/router/gzip
/deis/router/bodySize
/deis/router/affinityArg
/deis/router/sslCert
/deis/router/enableHSTS
/deis/router/hsts
/deis/router/sslProtocols
/deis/router/includeSubdomainsHSTS
/deis/router/maxAgeHSTS
/deis/router/enforceHTTPS
```

...however on checking the active router `nginx.conf` we see that the relevant nginx config isn't generates as it should be by looking at the router options here:

https://github.com/deis/deis/blob/v1.12.3/router/rootfs/etc/confd/templates/nginx.conf#L74

The `/deis/router/hsts/` directory on `etcd` is empty.

We are running `v1.12.3` stateless right now.

**Comment by bacongobbler** [comment]
@Crispy1975 seems like one of the configs that need to be enabled is `/deis/router/hsts/enabled` in order to turn on hsts templating. Can you please try `deisctl config router set hsts/enabled=true`?

**Comment by Crispy1975** [comment]
@bacongobbler sure, will try that now.

**Comment by Crispy1975** [comment]
@bacongobbler setting the keys that way has resulted in the nginx option working. Thanks. Perhaps it was me not understanding the format for the key itself and using the template variable format like `preloadHSTS` instead of `hsts/preload`?

**Comment by bacongobbler** [comment]
perhaps. This is one of those odd edge cases where the key is 4 levels deep. Usually it'd be `/deis/router/hstsEnabled` but since we can't make breaking changes and this has been documented we cannot break userland.

Let me know if you need any more help. Closing!
