### ISSUE TITLE
Understanding new architecture

### ISSUE THREAD

**Issue by amon-ra** [deis/deis#5052]
Hello.
I have been reading documentation and architecture documents and I cannot find any reference to persistent volume claims (to use storage quotas and storage plugins) and location inside domain ruting (ex. redirect /secondapp to another pod).
Can someone clarify this?

Thanks in advice.

**Comment by krancour** [comment]
Persistent volume claims are not currently applicable for applications deployed to k8s via Deis Workflow, as Workflow focuses on managing and deploying 12factor applications. (See http://12factor.net) Such applications do not store any state by writing it directly to a file system; rather, they depend on "backing services" such as object stores and databases to store state.

**Comment by amon-ra** [comment]
Ok. Thanks
