### ISSUE TITLE
Error while trying to import Kubernetes vmdk to vsphere

### ISSUE THREAD

**Issue by purplesmurf1510** [deis/deis#5059]
Trying to set up a Deis2 cluster following the instructions here http://kubernetes.io/docs/getting-started-guides/vsphere/

When I get to this step "govc import.vmdk kube.vmdk ./kube/" I get the following error

[22-06-16 11:17:25] Uploading... Error: Put https://vmhost002/folder/kube/kube-src.vmdk?dsName=$DATASTORE: dial tcp: lookup vmhost002: no such host
govc: Put https://vmhost002/folder/kube/kube-src.vmdk?dsName=$DATASTORE: dial tcp: lookup vmhost002: no such host

Not sure where this is set or where to change it any help would be appreciated.

**Comment by bacongobbler** [comment]
@purplesmurf1510 I'm not sure how vspere is set up, but perhaps you should try filing an issue up at https://github.com/kubernetes/kubernetes? You'll likely find others who have traveled the same road.

**Comment by bacongobbler** [comment]
for anyone else hitting this, https://github.com/kubernetes/kubernetes/issues/27947 is the upstream bug
