### ISSUE TITLE
Ruby app is created but doesn't starts

### ISSUE THREAD

**Issue by lmorais** [deis/deis#5060]
I'm with a problem when deploying a ruby app(2.3.0) with phusion passenger(5.0.28)

The application is created but, doesn't starts.

The command `deis logs` returns the error:

INFO [core-api]: config m4t-core-api-1a4cb0c updated
INFO [core-api]: config m4t-core-api-1a4cb0c updated
INFO [core-api]: leomorais created initial release
INFO [core-api]: leomorais created initial release
INFO [core-api]: domain m4t-core-api added
INFO [core-api]: domain m4t-core-api added
INFO [core-api]: build m4t-core-api-2cc34e1 created
INFO [core-api]: build m4t-core-api-2cc34e1 created
INFO [core-api]: leomorais deployed 14ef51f
INFO [core-api]: leomorais deployed 14ef51f
core-api-v2-web-ft5u3 -- &: -c: line 0: unexpected EOF while looking for matching `''
core-api-v2-web-ft5u3 -- &: -c: line 0: unexpected EOF while looking for matching `''
core-api-v2-web-ft5u3 -- &: -c: line 1: syntax error: unexpected end of file
core-api-v2-web-ft5u3 -- &: -c: line 1: syntax error: unexpected end of file
core-api-v2-web-ft5u3 -- &: -c: line 0: unexpected EOF while looking for matching `''
core-api-v2-web-ft5u3 -- &: -c: line 0: unexpected EOF while looking for matching `''
core-api-v2-web-ft5u3 -- &: -c: line 1: syntax error: unexpected end of file
core-api-v2-web-ft5u3 -- &: -c: line 1: syntax error: unexpected end of file
core-api-v2-web-ft5u3 -- &: -c: line 0: unexpected EOF while looking for matching `''
core-api-v2-web-ft5u3 -- &: -c: line 0: unexpected EOF while looking for matching `''
core-api-v2-web-ft5u3 -- &: -c: line 1: syntax error: unexpected end of file
core-api-v2-web-ft5u3 -- &: -c: line 1: syntax error: unexpected end of file
core-api-v2-web-ft5u3 -- &: -c: line 0: unexpected EOF while looking for matching `''
core-api-v2-web-ft5u3 -- &: -c: line 0: unexpected EOF while looking for matching `''
core-api-v2-web-ft5u3 -- &: -c: line 1: syntax error: unexpected end of file
core-api-v2-web-ft5u3 -- &: -c: line 1: syntax error: unexpected end of file
core-api-v2-web-ft5u3 -- &: -c: line 0: unexpected EOF while looking for matching `''
core-api-v2-web-ft5u3 -- &: -c: line 0: unexpected EOF while looking for matching `''
core-api-v2-web-ft5u3 -- &: -c: line 1: syntax error: unexpected end of file
core-api-v2-web-ft5u3 -- &: -c: line 1: syntax error: unexpected end of file
core-api-v2-web-ft5u3 -- &: -c: line 0: unexpected EOF while looking for matching `''
core-api-v2-web-ft5u3 -- &: -c: line 0: unexpected EOF while looking for matching `''
core-api-v2-web-ft5u3 -- &: -c: line 1: syntax error: unexpected end of file
core-api-v2-web-ft5u3 -- &: -c: line 1: syntax error: unexpected end of file

And the command `kubectl get pods --namespace=core-api` , returns the state:

NAME                        READY     STATUS                   RESTARTS   AGE
core-api-v6-web-gdbxt   0/1       CrashLoopBackOff   210                 17h

My Procfile is:
web: bundle exec passenger start -p $PORT --max-pool-size 8

**Comment by bacongobbler** [comment]
Hey there! This should be fixed up by https://github.com/deis/controller/pull/822 as it sounds a lot like https://github.com/deis/controller/pull/821.

**Comment by lmorais** [comment]
Great! I'll be waiting the fix

**Comment by bacongobbler** [comment]
@lmorais as a temporary fix, you can introduce a script that calls this, then make your Procfile invoke this script at boot. For example:

```
$ cat Procfile
web: /app/start.sh
$ cat start.sh
bundle exec passenger start -p $PORT --max-pool-size 8
$ chmod 755 start.sh
$ git add .
$ git commit -m "workaround"
$ git push deis master
```

Let me know if that resolves your issue in the meantime.

**Comment by lmorais** [comment]
@bacongobbler  It works! Thank you very much for this workaround. :smiley: 

kubectl get pods --namespace=core-api

`
NAME                                     READY            STATUS    RESTARTS   AGE
`
`
core-api-v5-web-cavkg            1/1                   Running           0             1m
`
