### ISSUE TITLE
How to update client to v2.1

### ISSUE THREAD

**Issue by gajus** [deis/deis#5061]
I have followed the instructions outlined in https://deis.com/docs/workflow/quickstart/install-cli-tools/ to install deis CLI program. It installed v2.0. In the mean time, the rest of the instruction (e.g. https://deis.com/docs/workflow/quickstart/provider/gke/install-gke/) guides through installation of workflow v2.1.0. As a result, I am getting an error:

```
 deis-test deis config:list -a junior-mainsail
!    WARNING: Client and server API versions do not match. Please consider upgrading.
!    Client version: 2.0
!    Server version: 2.1
=== junior-mainsail Config
POWERED_BY      Gajus
```

Looking at the `deis --help` I do not see an option to self-update.

I have looked into the http://deis.io/deis-cli/install-v2.sh script and constructed what is supposed to be the URL of the client binary (https://storage.googleapis.com/workflow-cli/v2.1.0/deis-v2.1.0-darwin-x86_64), but it appears to be non-existent.

**Comment by Joshua-Anderson** [comment]
Sorry about this, v2.1 was released Friday, and this appears to have been overlooked. We will fix this up the next work day, Tuesday. Meanwhile, you can download the latest version of the client from the README of this repository.

**Comment by gajus** [comment]
> Meanwhile, you can download the latest version of the client from the README of this repository.

Can you provide a link please? It is not clear what you are referring to since the `README.md` does not provide any instructions for installing/ downloading the client. There is only https://github.com/deis/deis/tree/master/client, which gives instructions how to build the client.

**Comment by Joshua-Anderson** [comment]
Sorry, my bad! I was thinking this was https://github.com/deis/workflow-cli, where the download links I mentioned are

**Comment by Joshua-Anderson** [comment]
@gajus The `v2.1.0` binaries have now been uploaded and we have found the issue that has prevented them from being uploaded!

https://storage.googleapis.com/workflow-cli/v2.1.0/deis-v2.1.0-darwin-amd64

We'll be updating the install deis script very soon, and I'll close this when that gets updated.
Thank you for catching this mistake and apologies for any confusion!
