### ISSUE TITLE
Deis Procfile requires bash to be installed in Docker image 

### ISSUE THREAD

**Issue by klpx** [deis/deis#5064]
I trying to create simple app from busybox (which does not contain bash):
Dockerfile:
```
FROM busybox
COPY echoer.sh /bin/echoer
CMD ["/bin/echoer", "CMD"]
```

echoer.sh
```
#!/bin/sh
while true; do echo "This is" $1; sleep 3; done
```

Procfile:
```
first: echoer FIRST
second: echoer SECOND
```

When i scale up instances `first` and `second` i receive `exec: "bash": executable file not found in $PATH`

Everything i found about this behaviour is this part of code: https://github.com/deis/deis/blob/master/controller/api/models.py#L620
I do not really know is it relative to the problem.

**Comment by bacongobbler** [comment]
Yes, bash is (unfortunately) a requirement in any container. This is for compatibility reasons with Heroku's dynos where they source environment variables stored in /app/profile.d from the buildpack, among other assumptions they make about the environment when executing the process.

Perhaps we should put this in the dockerfile requirements section in https://deis.com/docs/workflow/applications/using-dockerfiles/#dockerfile-requirements as this has been asked a few times in Slack.

**Comment by klpx** [comment]
Thank you for response. Putting this into doc would be nice. I can do this little thing for you to be not distracted :)

**Comment by bacongobbler** [comment]
Sure! That would be appreciated. If you feel up to the task, just make a PR to change it [here](https://github.com/deis/workflow/blob/master/src/applications/using-docker-images.md#docker-image-requirements) and [here](https://github.com/deis/workflow/blob/master/src/applications/using-dockerfiles.md#dockerfile-requirements), which when merged will show up at https://deis.com/docs/workflow/.

Bonus points if you also feel like adding a note to the v1 docs [here](https://github.com/deis/deis/blob/master/docs/using_deis/using-docker-images.rst#docker-image-requirements) and [here](https://github.com/deis/deis/blob/master/docs/using_deis/using-dockerfiles.rst#dockerfile-requirements). :)
