### ISSUE TITLE
compound issue: deis-database and deis-store-daemon

### ISSUE THREAD

**Issue by yebyen** [deis/deis#5070]
Was discussing this issue today on slack, this is kind of complex, my deployment is v1.13.2

I have a 5-node cluster and one of my nodes was randomly assigned as controller, store-gateway, database, builder, router, and logger.  I install SNMP on all of my nodes to keep an eye on disk usage, and this node was filling up its disk and had reached about 84% of 80GB.  I've had this happen to me a couple of times and I haven't made a specific set of instructions to repro, but standing up a cluster with whatever all I usually do and waiting about 2 weeks to a month seems to do it reliably.

I looked into why this was happening, and there were two reasons I could see, (1) snmpd service is spamming /var/lib/deis/store/logs/snmpd.log with about 200 lines of text per minute, each time nagios polls it.  This only generated about 500MB of cruft though, (2) much larger deis-store-daemon spam about 10 lines of text per second had generated about 2.5GB of cruft, errors matching this issue from way back: #3969 

These errors from store-daemon didn't look great, I also see now in hindsight that it looks like Ceph is reporting `pool .rgw.buckets has too few pgs`, and maybe this is the root of my problem.  But the overall usage of storage by GB stayed under half of the total 597GB available, and ceph seemed to be operating.

In the interest of getting my cluster back in good working order, I manually stopped (with systemctl) all of the deis services on that node, destroyed their containers using `docker ps` and `docker rm`, deleted all of the images that did not still belong to some running container, and purged all of the dangling volumes.  I was thinking this followed by a reboot would let fleet put those services onto another node, and my database would restore from WAL.

It didn't.  The logs from just before and after what I'm describing looked like this:

[gist: deis-database.log](https://gist.github.com/yebyen/802a2122d6a02134b0001b8723afa1aa)

16:05:44UTC is where fleet started the recovery, on about [line 3797](https://gist.github.com/yebyen/802a2122d6a02134b0001b8723afa1aa#file-deis-database-log-L3797)

You can see before there, a long span of repeating errors ending up in messages like:

```
2016-07-20 15:53:09 UTC LOG:  archive command failed with exit code 2
2016-07-20 15:53:09 UTC DETAIL:  The failed archive command was: envdir /etc/wal-e.d/env wal-e wal-push pg_xlog/000000010000000200000034
2016-07-20 15:53:09 UTC WARNING:  archiving transaction log file "000000010000000200000034" failed too many times, will try again later
```

I have the whole log un-truncated, in case there might be relevant information further back.  I just posted 4000 line snippet because it's quite long.

Anyway, I downed the node and let it reboot, watched all of the services get restarted in a pretty orderly way by fleet, controller came back and started running migrations (...), and I started to suspect that I had lost my deis database for good.  I used deisctl to `set registrationMode` back to enabled, created myself a new admin user, found my app's web processes still up, still routed and healthy, but no longer listed by `deis ps:list` at all, and it looks like I have a (mostly) brand new, healthy cluster.

So, this issue is for postmortem and LTS supporting purposes.  If there was a safer or smarter way to regenerate my database (`deisctl stop database && deisctl uninstall database` then `deisctl install database && deisctl start database`), or if there was some way for me to avoid or detect my WAL archiving failures so I could avoid destroying the database (I think it was still working), or or or...

There is actually probably more than one separate issue documented here, or in the best case maybe it's just one issue that follows from another fault further up the stack, with a root cause.  This is not the first time I've had a cluster blow up like this, in fact I'd say it's probably happened every time with enough patience.

I haven't spent a lot of time writing automated checks for Deis platform health, usually I let check_mk set up a couple of checks for issues that will affect the whole node, problems I can detect by SNMP in a container (node is running out of disk, node is spinning CPU at 100%, out-of-memory, just the basics) and I add a health check to confirm that my app stays up, and leave it at that.  So when minor things start to go wrong (like for some reason WAL can't archive anymore) and they start spamming the logs with errors, they are silently ignored until they are affecting an attempted app deployment or until they are somehow or other becoming more serious problems.

As an aside, if I could have a wish-list item to add to the LTS feature-set, even if it was something built as a separate product or as an add-on (LTS not supposed to get any new features), I would be asking for full-stack health monitoring of Deis platform services.  Something to tell me if WAL logs are current or if they are falling behind, if Ceph is HEALTH_OK or some other status, if one of my MDS is down and needs to be restarted, or if controller has stopped communicating with database.

I can find out when a lot of this stuff is wrong by tailing logs and journals, and I could probably use logstash to set up alerting based on those logs.  For this information to have a central outlet inside of the Deis platform seems like a logical extension though.  Self-healing is absolutely good, but I think it's probably not the be-all end-all of health monitoring.

My first attempt at preventing this from happening again is going to be silencing the logger spam from SNMPD.  SNMP daemon has a quiet mode.  Maybe this wouldn't happen or wouldn't happen so soon if that log spam weren't coming in constantly.

(So from a debugging perspective, I think spamming Ceph's posix store might be the key step to being able to reproduce this problem... I'm not doing very much else out of ordinary to my clusters that could possibly explain why some people don't have this problem)

**Comment by bacongobbler** [comment]
Hey sorry for not getting back to this post-mortem, but thank you for posting this after our debugging session!

From our conversation, there was a multitude of problems, but all of it stemmed from ceph falling flat on its face. It's actually well-known in the ceph community that reaching the threshold of disk usage in certain nodes can cause some pretty fantastic errors.

> I install SNMP on all of my nodes to keep an eye on disk usage, and this node was filling up its disk and had reached about 84% of 80GB.

This node in particular likely caused the issue. The resolution usually is to re-balance OSDs so that the data is nicely distributed across the hosts, but that requires manual intervention *before* the cluster starts to fail. For that reason that's why most users go with S3 for a maintenance-free storage backend.

Because of ceph failing over, your database was not able to restore from ceph, which caused database/platform downtime.

> So, this issue is for postmortem and LTS supporting purposes. If there was a safer or smarter way to regenerate my database (deisctl stop database && deisctl uninstall database then deisctl install database && deisctl start database), or if there was some way for me to avoid or detect my WAL archiving failures so I could avoid destroying the database (I think it was still working), or or or...

In most cases, it is as easy as you describe. `deisctl stop database && deisctl uninstall database && deisctl install database && deisctl start database`) will regenerate the database. In v2, kubernetes has healthchecks so it will automatically restart the database if it goes into an error state such as with WAL archiving failures. Fleet has no such feature for us to utilize.

> I would be asking for full-stack health monitoring of Deis platform services.

While this isn't something we're planning on implementing in the v1 line, this is something we addressed in v2 as there is a monitoring stack built into the platform via grafana/influxdb/fluentd/telegraf. See https://github.com/deis/monitor for more information.

In fact, v1 has been in LTS mode for over a year, so we're planning on end-of-life'ing it relatively soon. If you're still on v1 we strongly encourage you to try v2.8.0.

Hope this addresses your issue. Please let me know if I missed something! :)

**Comment by deis-admin** [comment]
Deis v1 LTS support ends February 13, 2017, and [v1.13.4](https://github.com/deis/deis/releases/tag/v1.13.4) is intended to be the last official release, so I'm closing this.

Please see [Deis Workflow](https://github.com/deis/workflow), the documentation / hub repository for the next-generation PaaS.

**Comment by yebyen** [comment]
Thanks for your follow-up

I missed your November reply, it looks like you answered my concerns in
detail

I am sorry that Deis-v1 will no longer be maintained, but I am learning
Kubernetes and I am excited about the future of Deis!
