### ISSUE TITLE
logspout does not recover on container restart (V1)

### ISSUE THREAD

**Issue by nathansamson** [deis/deis#5077]
I have noticed this behaviour for quite some while now but never bothered to try to debug it.

I noticed that logspout basically stops logging after service restarts (eg deploys or any other reason why new containers are booted)

Note I am on a stateless V1.13.2 cluster with CoreOS 1068.8.0 and applied fix #5074 (although I do not think that matters)
I believe I had similar issues in V1.12 (stateful cluster) but I blamed that on "deis-logspout now continuously re-discovers the logger’s connection information, should it be re-scheduled onto another host" which got released in V1.13 so I had hoped my problems would go away with V1.13.

At this point I can not tell if this is actually a new issue in V1.13; if it is related to staless vs statefull (I don't think it is by looking at the backtraces), or if it is related to newer CoreOS version, or if the problem exists for a long time already

So here is the complete scenario (complete logs: http://pastebin.com/6a6ksEE6 but I recommend you read the scenario first)

* restart logspout so it is in a working state (eg it logs attaching to nodeABC on startup for all containers)
* Restart a container (eg `deis ps:restart`)
* At the moment the old container is destroyed this gets detected; but logspout crashes
~~~
Aug 06 09:32:51 eu1-cloud-worker-01 sh[5391]: 2016/08/06 09:32:51 event: 417ba0517a81 kill
Aug 06 09:32:51 eu1-cloud-worker-01 sh[5391]: 2016/08/06 09:32:51 event: 417ba0517a81 die
Aug 06 09:32:51 eu1-cloud-worker-01 sh[5391]: 2016/08/06 09:32:51 attach: 417ba0517a81 finished
Aug 06 09:32:52 eu1-cloud-worker-01 sh[5391]: panic: runtime error: slice bounds out of range
Aug 06 09:32:52 eu1-cloud-worker-01 sh[5391]: goroutine 84 [running]:
Aug 06 09:32:52 eu1-cloud-worker-01 sh[5391]: main.NewAttachManager.func1(0xc82009a180, 0xc820011160)
Aug 06 09:32:52 eu1-cloud-worker-01 sh[5391]:         /home/jenkins/workspace/test-acceptance/src/github.com/deis/deis/logspout/attacher.go:35 +0x3f0
Aug 06 09:32:52 eu1-cloud-worker-01 sh[5391]: created by main.NewAttachManager
Aug 06 09:32:52 eu1-cloud-worker-01 sh[5391]:         /home/jenkins/workspace/test-acceptance/src/github.com/deis/deis/logspout/attacher.go:41 +0x313
~~~
* Logspout crashing is "okay"; it gets restarted automatically and can even attach to containers
~~~
Aug 06 09:32:52 eu1-cloud-worker-01 systemd[1]: deis-logspout.service: Unit entered failed state.
Aug 06 09:32:52 eu1-cloud-worker-01 systemd[1]: deis-logspout.service: Failed with result 'exit-code'.
Aug 06 09:32:57 eu1-cloud-worker-01 systemd[1]: deis-logspout.service: Service hold-off time over, scheduling restart.
Aug 06 09:32:57 eu1-cloud-worker-01 systemd[1]: Stopped deis-logspout.
Aug 06 09:32:57 eu1-cloud-worker-01 systemd[1]: Starting deis-logspout...
Aug 06 09:32:58 eu1-cloud-worker-01 systemd[1]: Started deis-logspout.
Aug 06 09:32:58 eu1-cloud-worker-01 sh[7052]: 2016/08/06 09:32:58 attach: 1d6a60f94ff0 deis-logspout success
Aug 06 09:32:58 eu1-cloud-worker-01 sh[7052]: 2016/08/06 09:32:58 attach: 4c745b55f30a bplpp-staging_v109.web.1 success
....
~~~
* Then the new container is started again gets detected by logspout but crashes again in similar way
~~~
Aug 06 09:33:06 eu1-cloud-worker-01 sh[7052]: 2016/08/06 09:33:06 event: 10.133.20.19 pull
Aug 06 09:33:06 eu1-cloud-worker-01 sh[7052]: 2016/08/06 09:33:06 event: 5913ff325cb6 create
Aug 06 09:33:06 eu1-cloud-worker-01 sh[7052]: 2016/08/06 09:33:06 event: 5913ff325cb6 attach
Aug 06 09:33:07 eu1-cloud-worker-01 sh[7052]: panic: runtime error: slice bounds out of range
Aug 06 09:33:07 eu1-cloud-worker-01 sh[7052]: goroutine 79 [running]:
Aug 06 09:33:07 eu1-cloud-worker-01 sh[7052]: main.NewAttachManager.func1(0xc820086180, 0xc820010e80)
Aug 06 09:33:07 eu1-cloud-worker-01 sh[7052]:         /home/jenkins/workspace/test-acceptance/src/github.com/deis/deis/logspout/attacher.go:35 +0x3f0
Aug 06 09:33:07 eu1-cloud-worker-01 sh[7052]: created by main.NewAttachManager
Aug 06 09:33:07 eu1-cloud-worker-01 sh[7052]:         /home/jenkins/workspace/test-acceptance/src/github.com/deis/deis/logspout/attacher.go:41 +0x313
~~~
* Ok so logspout crashes; fleet and/or systemd will handle this for us right?
~~~
Aug 06 09:33:07 eu1-cloud-worker-01 systemd[1]: deis-logspout.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 06 09:33:07 eu1-cloud-worker-01 docker[7394]: Failed to stop container (deis-logspout): Error response from daemon: No such container: deis-logspout
Aug 06 09:33:07 eu1-cloud-worker-01 systemd[1]: deis-logspout.service: Unit entered failed state.
Aug 06 09:33:07 eu1-cloud-worker-01 systemd[1]: deis-logspout.service: Failed with result 'exit-code'.
Aug 06 09:33:12 eu1-cloud-worker-01 systemd[1]: deis-logspout.service: Service hold-off time over, scheduling restart.
Aug 06 09:33:12 eu1-cloud-worker-01 systemd[1]: Stopped deis-logspout.
Aug 06 09:33:12 eu1-cloud-worker-01 systemd[1]: Starting deis-logspout...
Aug 06 09:33:13 eu1-cloud-worker-01 systemd[1]: Started deis-logspout.
Aug 06 09:33:33 eu1-cloud-worker-01 sh[7579]: 2016/08/06 09:33:33 routing all to udp://10.133.20.195:514
Aug 06 09:33:43 eu1-cloud-worker-01 sh[7579]: 2016/08/06 09:33:43 routing all to udp://10.133.20.195:514
Aug 06 09:33:53 eu1-cloud-worker-01 sh[7579]: 2016/08/06 09:33:53 routing all to udp://10.133.20.195:514
~~~

So it did restart the service, but for some reason it did not attach to ANY containers but silently does nothing.

Note that it still listens for events and the same cycle can be repeated again. It is undeterministic if at the end it will actually have attached to containers or not

So I see 2 probably distinct bugs

A) It crashes on a container restart (this seems to be consistent and we get a stacktrace so probably quite easy to debug and solve). At minimum this will give us some missing logs during container restarts (probably the boot logs of a container which is very frustrating if that container is crashing on boot and there is no easy way to see the logs)

B) It does not seem to attach to containers on startup (this is without logs and does not happen every time, I suspect some sort of race condition in the boot sequence)

If there is anything I can do to help debug this issue (eg try out a custom logspout image) I am obviously willing to do so

**Comment by bacongobbler** [comment]
@nathansamson just an FYI that we'd accept PRs to fix this but we are not actively working on Deis v1 so it may take some time for us to get back with a fix.

**Comment by bacongobbler** [comment]
I just noticed #5078. I'll take a look at that. Thanks!

**Comment by nathansamson** [comment]
@bacongobbler Note that #5078 is only a fix for bug A) in this report.

The thing is I am not sure if B) is just a result of A) (eg restarting logspout while starting a container results in the race condition) or if B) is really another bug
Would you be able to give some pointers on how to debug B)?

(Note that when restarting logspout manually I never have noticed yet A) but a rarely follow the logspout logs when doing so)

**Comment by bacongobbler** [comment]
B) would probably be another bug, but we should be [attaching to all containers on boot](https://github.com/deis/deis/blob/3ef983f8c5c7c2d57f3261789a15443fb021f22e/logspout/attacher.go#L26-L30). Perhaps it's erroring there as well due to the network event.
