### ISSUE TITLE
Update fsouza/go-dockerclient vendored package(s)

### ISSUE THREAD

**Issue by mboersma** [deis/deis#5083]
Deis v1's dependencies have rusted somewhat. In particular, logspout would like to take advantage of this fix: fsouza/go-dockerclient#206, but updating that with `godep` is anything but straightforward.

**Comment by bacongobbler** [comment]
I believe this should be easier when #5109 is merged.

**Comment by mboersma** [comment]
This isn't that straightforward and won't be updated before the EOL date, Feb. 13.
