### ISSUE TITLE
Standard for collecting app specific metrics?

### ISSUE THREAD

**Issue by vpetersson** [deis/deis#5086]
I love the fact that Deis comes with a pre-configured Grafana setup. What would make it even more awesome would be if there was a standard for app metrics such that this could be done with auto discovery.

This can of course be done already using something like Prometheus to scrape the metrics, and then add that as a data source in Grafana. 

However, I was just curious if this was something that you guys had given any thought to and if so if there was any thought to.

**Comment by vpetersson** [comment]
Relevant comment from the Prometheus team: 
https://coreos.com/blog/prometheus-and-kubernetes-up-and-running.html

**Comment by bacongobbler** [comment]
ping @jchauncey :)

**Comment by jchauncey** [comment]
Ok so our setup is definitely tailored to have metrics pushed to it from any source (user deployed apps or apps we add to the stack ourselves). If you are wanting to collect metrics from your apps all you need to do is encode them using the [Influx line protocol](https://docs.influxdata.com/influxdb/v0.13/write_protocols/line/) and send them to our nsq instance on the metrics topic. We will then pull that data off using telegraf and send it to influx. Now if you do it this way your data will be colocated in the same database as the other metrics we collect.

Another way, if you dont want to have your data in the same database, is just to send the data directly to influx to the database you want. 

The benefit to use nsq/telegraf is that you can change the destination at anytime without having to change your app code. So you may decide to send that data to librato or kafka and all you need to do is reconfigure telegraf and send the data for you.

**Comment by jchauncey** [comment]
Here is how we are sending data to nsq via fluentd for router metrics - https://github.com/deis/fluentd/blob/master/rootfs/opt/fluentd/deis-output/lib/fluent/mixin/deis.rb

**Comment by vpetersson** [comment]
Very interesting. Thanks, @jchauncey. Will look closer into this.

**Comment by Joshua-Anderson** [comment]
@vpetersson Do you have any other questions or is it okay to close this? We also have our community slack channel if you would like to discuss this more in the future.

**Comment by vpetersson** [comment]
@Joshua-Anderson Please close it out. I got something to work with now.
