### ISSUE TITLE
Workflow: can't add readiness probe healthcheck

### ISSUE THREAD

**Issue by robinmonjo** [deis/deis#5092]
Workflow client version: 2.4.0-78118eb
Workflow version: 2.4.2
Kubernetes version: 1.3.4

When I try to setup a readiness probe to my app I do:

````bash
$> deis healthchecks:set readiness httpGet 80 --path / --type web
Applying readinessProbe healthcheck... done

=== myapp Healthchecks

web:
--- Liveness
No liveness probe configured.

--- Readiness
Initial Delay (seconds): 50
Timeout (seconds): 50
Period (seconds): 10
Success Threshold: 1
Failure Threshold: 3
Exec Probe: N/A
HTTP GET Probe: Path="/" Port=80 HTTPHeaders=[]
TCP Socket Probe: N/A
````

So everything looks good, however when I `deis healthcheks:list` to ensure it's set:

````bash
$> deis healthchecks:list                                             
=== myapp Healthchecks

web/cmd:
--- Liveness
No liveness probe configured.

--- Readiness
No readiness probe configured.
````

If I `kubectl describe` my pod, I have this: 

`````
Readiness:		exec [bash -c [[ '$(ps -p 1 -o args)' != *'bash /runner/init'* ]]] delay=30s timeout=5s period=5s #success=1 #failure=1
`````

which seems to be the default probes and not the one I want. When I try to set the probe agains, I got this message:

`````
Applying readinessProbe healthcheck... Error: Unknown Error (409): {"detail":"robin changed nothing - release stopped"}
`````

Logs of the `deis-controller` pod doesn't show anything special.

Am I missing something or is this a bug ?

**Comment by robinmonjo** [comment]
Tested again with `workflow 2.6` and kubernetes `1.4`, no more problem. However, `deis healthchecks:list` doesn't work as expected if I don't specify `--type=web` (even if web is shown in the output).

Anyway, closing

**Comment by bacongobbler** [comment]
Sorry @robinmonjo! This was actually a fallout of a recent change made to `deis healthchecks`.

In the future, if you can file issues on deis/workflow, it'd be more likely that you'll get a response. This repo is for the v1 project which is only being maintained (passively) by myself and 2 other devs. No active development has been taken here for a while.

See duplicate issue: https://github.com/deis/controller/issues/1030
