### ISSUE TITLE
deis Truck Factor

### ISSUE THREAD

**Issue by 2mferreira** [deis/deis#5093]
Dear **deis** contributors,

I am Master's student investigating the importance of the idea of truck factors in Software Engineering.

As you know, [truck factor](https://en.wikipedia.org/wiki/Bus_factor) (aka bus factor) is defined as “the number of people on your team who have to be hit by a truck before the project is in serious trouble”.  By "serious trouble", we mean that it will very difficult to maintain the project (e.g., bugs will take more time to be fixed, new features will be delayed etc).

I would appreciate your contribution by answering two questions:

1) According to your experience, what number best represents the truck factor of **deis**?

2) Who are the developers responsible for this truck factor (i.e., the name of the developers who are responsible for the TF result answered in the previous question)?

Mívian Ferreira
Master's Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by bacongobbler** [comment]
Hi @2mferreira!

> 1) According to your experience, what number best represents the truck factor of deis?

At any given point, our bus factor is at minimum a factor of 3. We have a policy in place where two other maintainers must provide an LGTM (Looks Good To Me) on any feature in our components.

> 2) Who are the developers responsible for this truck factor (i.e., the name of the developers who are responsible for the TF result answered in the previous question)?

You mean https://github.com/orgs/deis/people? If you can provide more information on what you require for this topic I'd be happy to answer. There's nobody responsible for this bus factor, if that's what you mean. It's written in [our documentation](https://deis.com/docs/workflow/contributing/submitting-a-pull-request/#merge-approval). :)

Let me know if you have any more questions!

**Comment by bacongobbler** [comment]
Closing as the question has been answered and no response has been received in a week. Please re-open if you have any further questions!
