### ISSUE TITLE
Is it possible to disallow features at a cluster level?

### ISSUE THREAD

**Issue by jkurz** [deis/deis#5103]
* we do not want developers to create stateful applications. Do do this, we do not want to allow for volume attachments.
* we do not want allow users to create new networks on the clusters.
* Is there a way to configure what types of features applications can use? Is this something the DEIS platform is interested in allowing at a configuration based level?

**Comment by jkurz** [comment]
Actually I think this is a little confusing. I found out you guys dont support volumes at all. :) sweet win for me. I'll close this and rephrase if needed.

**Comment by bacongobbler** [comment]
Feel free to ask questions on our slack channel! https://slack.deis.io/

**Comment by krancour** [comment]
To clarify for anyone who finds this thread in the future, Workflow currently is focused on 12factor apps only, which are inherently stateless, hence no current support for volume mounting.
