### ISSUE TITLE
How to change timezone?

### ISSUE THREAD

**Issue by ChillarAnand** [deis/deis#5113]
```
→deis releases      
=== stagingapi Releases
v11     2017-01-04T10:44:04Z    f deployed 93924ad
v10     2017-01-04T10:22:24Z    f deployed f6e80f8
v9      2017-01-04T10:06:22Z    f deployed 3e367ee
```

It would be easier to read logs, if local time is used instead of UTC.

**Comment by mboersma** [comment]
@ChillarAnand unfortunately the `TIME_ZONE` setting is hard-coded here: https://github.com/deis/controller/blob/master/rootfs/api/settings/production.py#L37

So you could change it locally and deploy a custom Docker image for the controller.

It wouldn't be too hard to allow an environment variable to override `UTC`, but no one's done that yet. Pull requests are always welcome!

**Comment by ChillarAnand** [comment]
Do we have to change this https://github.com/deis/deis/blob/master/controller/deis/settings.py#L38 also?

**Comment by bacongobbler** [comment]
Nah, the one you linked to is for v1 which is in maintenance mode at this point. Feel free if you'd like to but we're dropping support for v1 in a month.

**Comment by ChillarAnand** [comment]
Then no need for it. Thanks @bacongobbler
