### ISSUE TITLE
InvalidDomainNameLabel while provisioning Docker EE on Azure 

### ISSUE THREAD

**Issue by MadhurBhardwaj** [deis/deis#5122]
Hi,

Getting following error while provisioning Swarm cluster on azure ...
The domain name label applb-DockerEECluster is invalid. It must conform to the following regular expression: ^[a-z][a-z0-9-]{1,61}[a-z0-9]$.

But I'm not providing any domain name , it is auto generated ,
Could someone please help me with this...

Thanks
Madhur

**Comment by bacongobbler** [comment]
Please open a ticket at https://github.com/Azure/ACS. Deis is a PaaS and does not run on top of Swarm. Thanks!
