### ISSUE TITLE
DEIS controller with vmware/vsphere

### ISSUE THREAD

**Issue by lcheng61** [deis/deis#593]
Hi,

Is it possible that we deploy a DEIS controller to spawn instances from vmware/vsphere eco-system ? Any advice/document will be appreciated.

**Comment by jessehu** [comment]
Hello, I don't found vSphere on http://docs.deis.io/en/latest/installing_deis/#installing-deis , does it mean vSphere is not supported by Deis ?  Thanks.

**Comment by bacongobbler** [comment]
@jessehu while we don't have any vsphere documentation for Deis v1, I'm sure there's documentation out there for setting up kubernetes on vsphere for Workflow (v2)!

**Comment by jessehu** [comment]
Thanks @bacongobbler . I only find Vagrant on VMware Fusion/Workstation on https://github.com/deis/workflow/blob/46b279df73146cce5f3cad724d60d2fe55d3a39e/src/quickstart/provider/vagrant/boot.md but not vSphere.
