### ISSUE TITLE
Support both Dockerfiles and Procfiles

### ISSUE THREAD

**Issue by benton** [deis/deis#668]
Currently, deploying any codebase that contains both a Procfile and a Dockerfile will receive an error:

```
name 'slug_path' is not defined
```

This is because the variable `slug_path` is not defined for the relevant context in Python (see `builder/templates/builder` around line 60).

Ideally, a Dockerfile-based app with a Procfile should be treated exactly the same as a buildpack-based app with a Procfile. That is, the commands in the Procfile should be considered authoritative, and supercede the CMD in the Dockerfile.

So just like with buildpacks, the same build output (in this case a container image, not a slug) can still be run with the command from the Procfile, right? The only issue I can think of might be that the Procfile format (with which I'm pretty unfamiliar) may allow sequences of commands (or worse, I/O redirection) that won't work as a custom run argument to the docker executable.

But I've had reasonable success applying arbitrary shell commands to random containers, even if i have to wrap it in Bash like:

```
CMD ["bash", "-c", "bundle exec rake release && exec bundle exec rackup -p $PORT"]
```

Is this feature possible?

**Comment by bourquep** [comment]
I have tried to do this with Deis Workflow (v2) with no success. I have 2 processes that must be run from the same image, and having both a Dockerfile and a Procfile led to nothing running at all.
