### ISSUE TITLE
Some documentation codeblocks cut short

### ISSUE THREAD

**Issue by bacongobbler** [deis/deis#684]
Some of the codeblocks in the documentation looks quite ugly on some screens due to the right border cutoff. Example shown below. My display is set to 2880x1800. I suggest we should allow a side-scrolling feature, much like how codeblocks are shown on Github.

![codeblock](http://i.imgur.com/XNBQwOJ.png)

**Comment by mboersma** [comment]
The Deis v1 docs at http://docs.deis.io are likely to stay with this old-school styling. Going forward, doc improvements will be made at https://github.com/deis/workflow. Work is underway to mesh that content with https://deis.com/.
