### ISSUE TITLE
Microsoft Azure as a cloud provider

### ISSUE THREAD

**Issue by xtagon** [deis/deis#802]
Hi,

I have an app I'd like to run on Microsoft Azure using Deis. It currently runs on Heroku, but I've been tasked to move it from Heroku to Azure. For now, I will be managing the VMs and deployment using Ansible and Capistrano, but I'd really like something more Heroku-like, and Deis seems the perfect fit (when it's ready).

I spoke with @gabrtv on Freenode who told me Azure support is being discussed and planned for a future release. Azure support for loading custom VM images: [Creating and Uploading a Virtual Hard Disk that Contains the Linux Operating System](http://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-create-upload-vhd/)

**Comment by carmstrong** [comment]
Opening this so we can close it again soon :)

**Comment by imton** [comment]
awesome! :+1:

**Comment by irony** [comment]
Great work!
