### ISSUE TITLE
Allow container-less apps

### ISSUE THREAD

**Issue by johanneswuerbach** [deis/deis#815]
With rails (and others) we need to migrate our database before starting the rails server.

Today, I do this using a second app with the same DATABASE_URL, which is deployed before the actual app and is just executing the db migrations and not serving any requests.

This is work really well, except that every time a web container is created, even when it was scaled down (web=0) before. So having container-less apps should be allowed as on heroku.

Is there another way to execute pre-start migrations?

**Comment by mhahn** [comment]
i'm just now coming across the same issue as @johanneswuerbach.

so the preferred way to run migrations before deploying code would be to create a migration app with:

`deis create app-migrations --structure='{"web": 0}'`

i would then deploy to "app-migrations" and run the db migration with `deis run` before deploying to the web workers?
