### ISSUE TITLE
Define the Deis HA story

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#874]
High-availability clusters for Deis is a prerequisite for our 1.0 release. To achieve high availability, there are several things to consider:
- How do we handle router being moved within the cluster?
- Should the router be scheduled with fleet in the first place?
- Should Deis concern itself with deploying router at all, or do we provide provisioning scripts to deploy, and they are then passed into `clusters:create`?
- How do we handle HA Postgres/DB backups/replication?

**Comment by SamuelMarks** [comment]
@gabrtv / @carmstrong: It has been about a year, are you open to reconsidering [vulcand](https://github.com/mailgun/vulcand)?

**Comment by bacongobbler** [comment]
Websockets are unsupported which is a non-starter, imo
