### ISSUE TITLE
Allow to customize or change default nginx gzip settings

### ISSUE THREAD

**Issue by johanneswuerbach** [deis/deis#884]
When running nginx behind elb, cloudfront or other proxies the [gzip_proxied](http://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_proxied) setting must be set to serve compressed files. Also nginx is compressing only `text/html` by default, so the [gzip_types](http://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_types) needs to be extended to enable gzip for other types like css, json, etc..

Today [gzip is turned on](https://github.com/deis/deis/blob/master/router/templates/nginx.conf#L21), but without the two settings above, compression is disabled in most cases. It would awesome if gzip would have some other defaults or is configurable via etcd.

Here are for example the default settings used by AWS OpsWorks https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.4/nginx/attributes/nginx.rb#L37 but they also didn't include `application/json`, which I need for our json-api.

**Comment by davidlmorton** [comment]
What do you suggest for turning on the 'gunzip' option for nginx?

http://nginx.com/resources/admin-guide/compression-and-decompression/

I would have expected that setting the key 'deis/router/gunzip' to 'on' would do it.

**Comment by aledbf** [comment]
@davidlmorton is on by default http://docs.deis.io/en/latest/customizing_deis/router_settings/#settings-used-by-router

**Comment by bacongobbler** [comment]
@davidlmorton the correct setting is `/deis/router/gzip`. use `deisctl config router set gzip=on` :)

**Comment by davidlmorton** [comment]
@aledbf and @bacongobbler Thanks for the prompt responses, but I'm asking for the decompression settings to be turned on for nginx, not the compression.  When I send a request to my app I want to be able to send gzip compressed requests without doing the decompression in the app itself.  Unless I'm doing things wrong, I haven't seen nginx do the decompression, it will compress large responses though.

**Comment by bacongobbler** [comment]
Ah. That's something which is currently not implemented. Could you please open a different issue for that?

**Comment by davidlmorton** [comment]
I opened an issue for that, thanks again for the responses.  It is issue #3600 for reference.
